### PR TITLE
Fix #4564: Invalidate clashing case class methods

### LINKED ISSUE #4564: Overriding `copy` of case class results in unhelpful error messages
```scala
case class A(x: Int) {
  def copy(x: Int = x) = A(x)
}
```
results in merge errors and friends:
```scala
-- Error: try/CaseClassCopyMergeError.scala:2:20 -------------------------------
2 |  def copy(x: Int = this.x) = A(x)
  |                    ^^^^^^
  |             cannot merge
  |               method copy: (x: Int): A  and
  |               method copy: (x: Int): A;
  |             they are both defined in class A but have matching signatures
  |               (x: Int): A and
  |               (x: Int): A
  |             when seen as members of A(A.this)
-- Error: try/CaseClassCopyMergeError.scala:1:19 -------------------------------
1 |case class A(x: Int) {
  |                   ^
  |             cannot merge
  |               method copy: (x: Int): A  and
  |               method copy: (x: Int): A;
  |             they are both defined in class A but have matching signatures
  |               (x: Int): A and
  |               (x: Int): A
  |             when seen as members of A(A.this)
-- [E119] Duplicate Symbol Error: try/CaseClassCopyMergeError.scala:2:6 --------
2 |  def copy(x: Int = this.x) = A(x)
  |      ^
  |method copy in class A is already defined as def copy(x: Int): A at line 1.
  |The definitions have matching type signatures after erasure.
-- Error: try/CaseClassCopyMergeError.scala:1:0 --------------------------------
1 |case class A(x: Int) {
  |^
  |two or more overloaded variants of method copy have default arguments
```

We have a use case for this in inox (where we override `copy` to also also copy over some metadata), but I see how one would like to enforce some semantics for `copy` on case classes. In any case, this should produce a more intelligible error message.

### PR DESCRIPTION
**Pull request by odersky**
Invalidate a compiler generated case class method that clashes
with a user-defined method in the same scope with a matching type.

Invalidation is done by overwriting its info on completion with `NoType` and
eliminating the method altogether during type checking.

Methods potentially affected are `apply`, `unapply`, `copy`, and `copy`'s default getters.

### CODE REVIEW

**Comment by odersky** [comment]
See also scala/scala #5816.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1413,7 +1413,12 @@ class Typer extends Namer
     }
   }
 
-  def typedDefDef(ddef: untpd.DefDef, sym: Symbol)(implicit ctx: Context) = track("typedDefDef") {
+  def typedDefDef(ddef: untpd.DefDef, sym: Symbol)(implicit ctx: Context): Tree = track("typedDefDef") {
+    if (!sym.info.exists) { // it's a discarded synthetic case class method, drop it
+      assert(sym.is(Synthetic) && desugar.isDesugaredCaseClassMethodName(sym.name))
+      sym.owner.info.decls.openForMutations.unlink(sym)
```
Comment (adriaanm) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Neat! We should consider dropping here, instead of in the completer, for scalac too.

File: tests/pos/i4564.scala [hunk 2]
```diff
@@ -0,0 +1,63 @@
+case class A(x: Int) {
```
Comment (adriaanm) [inline tests/pos/i4564.scala]: There's also a negative version -- would be good to include.

**Comment by odersky** [comment]
@smarter I believe it's probably better if we exclude selectors from the scheme altogether.

**Comment by adriaanm** [comment]
PS: A pleasure to read the code!

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: It works because `dotc` is quite good at deciding that symbols with `NoType` as info don't really exist. (c.f. `reallyExsists` and its references). I am not sure what the state for scalac is here.

**Comment by odersky** [comment]
Added the neg test. This required some more changes in Typer to give better error messages similar to what's done in scala/scala.

**Comment by Blaisorblade** [comment]
If we keep this scheme for `_1`, and so on, we could also try taking a look at #4520 (about the error messages we get, and the expected behavior in Scala 2 and Scala 3 modes). If we still generate `_1` in Scala2 mode, should 2.14 deprecate such custom accessors?
