### PR TITLE
Don't suggest invisible members of root imports

### LINKED ISSUE #24995: Incorrect "did you mean" in the presence of shadowed root imports
It's probably because inScopeCandidates does not faithfully copy the logic in `Typer.findMember`: If the import is a root import (i.e. from scala, java.lang or Predef` then it shadows the synthesized root import at the beginning of the program. That should be fixed as well (either in this PR or another one).

In current main, when we compile
```scala
import Predef.{Map as _}
val xx: Mop[Int, Int] = Mop()
```
we see already:
```scala
~/workspace/dotty/tests/pos-custom-args/captures> sccs ../../new/test.scala 
-- [E006] Not Found Error: ../../new/test.scala:3:8 ----------------------------
3 |val xx: Mop[Int, Int] = Mop()
  |        ^^^
  |        Not found: type Mop - did you mean Map?
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: ../../new/test.scala:3:24 ---------------------------
3 |val xx: Mop[Int, Int] = Mop()
  |                        ^^^
  |                        Not found: Mop - did you mean Map?
  |
  | longer explanation available when compiling with `-explain`
```
Those "did you mean" messages are also wrong.

_Originally posted by @odersky in https://github.com/scala/scala3/pull/24959#discussion_r2698205502_

### PR DESCRIPTION
**Pull request by odersky**
If some member from a root import is hidden by a subsequent import, don't suggest that member in a "did you mean?" clause.

Fixes #24995

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/DidYouMean.scala [hunk 1]
```diff
@@ -46,6 +47,8 @@ object DidYouMean:
       then ctx.outer
       else nextInteresting(ctx.outer)
 
+    var ignoredRootImports: mutable.Set[Symbol] = mutable.Set()
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/reporting/DidYouMean.scala]:
```suggestion
    val ignoredRootImports = mutable.Set.empty[Symbol]
```
Did you mean?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/reporting/DidYouMean.scala]: Ah yes!

**Review by SolalPirelli — APPROVED** [review]
Looks good. Just so I understand this better, is there a fundamental reason why `DidYouMean` has to partially reimplement the logic for finding things?

**Comment by odersky** [comment]
> Looks good. Just so I understand this better, is there a fundamental reason why DidYouMean has to partially reimplement the logic for finding things?

I think it's because in Typer we search for one name only, and do so in a highly optimized way. Whereas in DidyouMean we search for all members and then match them with the Levenshtein distance.
