### PR TITLE
Output other compiler errors

### LINKED ISSUE #14303: No errors shown on forwards/backwards compat test failure
## Compiler version

When compiling with test with a file containing the `c3.0.0` name, the errors are not reported.

## Minimized example

`tests/pos/mytest/A_1_c3.0.0.scala`
```Scala
def f: Int = match
```

`tests/pos/mytest/B_2.scala`
```scala
def test() = f
```

## Output

```
sbt> testCompilation tests/pos/mytest
...
[info] Test dotty.tools.dotc.CompilationTests.pos started
-- [E006] Not Found Error: tests/pos/mytest/B_2.scala:1:13 ----------------------------------------
1 |def test() = f
  |             ^
  |             Not found: f
Compilation failed for: 'tests/pos/mytest'                    
[=======================================] completed (1/1, 1 failed, 5s)
...
```

## Expectation
The errors of `A_1_c3.0.0.scala` should be reported to be able to fix them easily. Note that it might be an error that only occurred in that version.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #14303

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Not sure how to create a test for this.

This is the current error message we get for the example in #14303
```
[info] Test dotty.tools.dotc.CompilationTests.pos started
-- Error: tests/pos/mytest/A_1_c3.0.0.scala:1:9 --------------------------------
1 |def f: Int = match
  |         ^
  |Compilation of tests/pos/mytest/A_1_c3.0.0.scala with Scala 3.0.0 failed at line: 1, column: 10. Full error output:
  |
  |    -- [E007] Type Mismatch Error: tests/pos/mytest/A_1_c3.0.0.scala:1:10 ----------
  |    1 |def f: Int = match
  |      |          ^
  |      |          Found:    Null
  |      |          Required: Int
  |    
  |    longer explanation available when compiling with `-explain`
-- Error: tests/pos/mytest/A_1_c3.0.0.scala:1:12 -------------------------------
1 |def f: Int = match
  |            ^
  |Compilation of tests/pos/mytest/A_1_c3.0.0.scala with Scala 3.0.0 failed at line: 1, column: 13. Full error output:
  |
  |    -- [E018] Syntax Error: tests/pos/mytest/A_1_c3.0.0.scala:1:13 -----------------
  |    1 |def f: Int = match
  |      |             ^^^^^
  |      |             expression expected but match found
  |    
  |    longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: tests/pos/mytest/B_2.scala:1:13 -------------------------------------------------------------
1 |def test() = f
  |             ^
  |             Not found: f
Compilation failed for: 'tests/pos/mytest'                                      
[=======================================] completed (1/1, 1 failed, 6s)
```

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 1]
```diff
@@ -505,19 +505,28 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
+            val span = Spans.Span(offset)
+            val sourcePos = SourcePosition(sourceFile, span)
+            diagnostics ::= Diagnostic.Error(s"Compilation of $filePath with Scala $compilerVersion failed at line: $line, column: $column. Full error output:\n\n$indent$error\n", sourcePos)
+          case summaryPattern() => // Ignored
+          case errorLine =>
+            diagnostics match
+              case head :: tail =>
+                diagnostics = Diagnostic.Error(s"${head.msg.rawMessage}$indent$errorLine\n", head.pos) :: tail
+              case Nil =>
+      diagnostics
```
Comment (nicolasstucki) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala:529]: I should reverse this list

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 2]
```diff
@@ -504,20 +504,35 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
+      val summaryPattern = """\d+ (?:warning|error)s? found""".r
+      val indent = "    "
+      var diagnostics = List.empty[Diagnostic.Error]
+      def barLine(start: Boolean) = s"$indent${if start then "╭" else "╰"}${"┄" * pageWidth}${if start then "╮" else "╯"}\n"
+      def errorLine(line: String) = s"$indent┆${String.format(s"%-${pageWidth}s", stripAnsi(line))}┆\n"
+      def stripAnsi(str: String): String = str.replaceAll("\u001b\\[\\d+m", "")
+      def addToLast(str: String): Unit =
+        diagnostics match
+          case head :: tail =>
+            diagnostics = Diagnostic.Error(s"${head.msg.rawMessage}$str", head.pos) :: tail
```
Comment (prolativ) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala:518]: If we catch warnings as well, we should handle them properly too. Although I'm not sure if we really need that and if we can handle this reliably as the external compiler process might not fail if there are some warnings but no error. As far as I know, every time we want to check if a warning was raised we enable fatal warnings and check for errors instead

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 3]
```diff
@@ -528,18 +543,19 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
 
+      val pageWidth = 80
       val flags1 = flags.copy(defaultClassPath = substituteClasspath(flags.defaultClassPath))
         .withClasspath(targetDir.getPath)
         .and("-d", targetDir.getPath)
+        .and("-pagewidth", pageWidth.toString)
 
-      val dummyStream = new PrintStream(new ByteArrayOutputStream())
-      val reporter = TestReporter.reporter(dummyStream, ERROR)
+      val reporter = TestReporter.reporter(System.out, ERROR)
```
Comment (prolativ) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala:552]: I would say we don't want to show all the logs in all situations as we don't show them by default when compiling with the latest compiler inside the same process. I think it would make sense to show the logs if the external process failed but no errors were parsed or if there's a mismatch between the expected number and positions of errors and the errors that we extracted from the logs

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 4]
```diff
@@ -504,20 +504,35 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
-          val sourcePos = SourcePosition(sourceFile, span)
-
-          Diagnostic.Error(s"Compilation of $filePath with Scala $compilerVersion failed at line: $line, column: $column. Full error output:\n\n$errorsText\n", sourcePos)
-      }
+    private def parseErrors(errorsText: String, compilerVersion: String, pageWidth: Int) =
+      val errorPattern = """^.*Error: (.*\.scala):(\d+):(\d+).*""".r
+      val summaryPattern = """\d+ (?:warning|error)s? found""".r
+      val indent = "    "
+      var diagnostics = List.empty[Diagnostic.Error]
+      def barLine(start: Boolean) = s"$indent${if start then "╭" else "╰"}${"┄" * pageWidth}${if start then "╮" else "╯"}\n"
```
Comment (prolativ) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala:512]: What version of the compiler and with which options did you use to get his kind of a frame? I've never seen it before

Comment (nicolasstucki) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:512]: It is just [ASCII boxes](https://en.wikipedia.org/wiki/Box-drawing_character). I'm creating the frame here.

Comment (prolativ) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:512]: Yeah, that I know. I was wondering why you're getting this in your compiler output while this doesn't happen to me and I didn't even know we have such a functionality

Comment (prolativ) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:512]: OK, sorry, for some reason I thought it's a part of your usual compiler output and you're trying to parse it here

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:519]: I added code to ignore warnings

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala (hunk 3 above)
Comment (nicolasstucki) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: Now errors are not printed in neg tests unless the test fails.

**Review by prolativ — APPROVED** [review]

**Review by prolativ — APPROVED** [review]
