### PR TITLE
Fix #1750: Alternative fix for cyclic references due to illegal class overrides

### LINKED ISSUE #1750: crash on compilable code: cyclic reference involving class Visitor
scalac can compile but dotc crashes.

$ cat abc.scala
```
trait Lang1 {
  trait Exp
  trait Visitor { def f(left: Exp): Unit }
  class Eval1 extends Visitor { self =>
    def f(left: Exp) = ()
  }
}
trait Lang2 extends Lang1 {
  class Visitor extends Eval1 { Visitor =>
  }
}
```

$ dotc abc.scala
```
exception while transforming () extends Lang2.this.Eval1() {} of class class dotty.tools.dotc.ast.Trees$Template # 174
exception while transforming class Visitor() extends Lang2.this.Eval1() {} of class class dotty.tools.dotc.ast.Trees$TypeDef # 175
exception while transforming () extends Object with Lang1 {
  class Visitor() extends Lang2.this.Eval1() {}
} of class class dotty.tools.dotc.ast.Trees$Template # 176
exception while transforming @scala.annotation.internal.SourceFile("abc.scala") <trait> trait Lang2() extends

Object with Lang1 {
  class Visitor() extends Lang2.this.Eval1() {}
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 177
exception while transforming package <empty> {
  @scala.annotation.internal.SourceFile("abc.scala") <trait> trait Lang1()
     extends
   Object {
    <trait> interface trait Exp() extends Object {}
    <trait> interface trait Visitor() extends Object {
      def f(left: Lang1.this.Exp): Unit
    }
    class Eval1() extends Object() with Lang1.this.Visitor {
      def f(left: Lang1.this.Exp): Unit = ()
    }
  }
  @scala.annotation.internal.SourceFile("abc.scala") <trait> trait Lang2()
     extends
   Object with Lang1 {
    class Visitor() extends Lang2.this.Eval1() {}
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 178

exception occurred while compiling abc.scala
Exception in thread "main" dotty.tools.dotc.core.Types$CyclicReference: cyclic reference involving class Visitor
	at dotty.tools.dotc.core.Types$CyclicReference$.apply(Types.scala:3838)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$baseTypeRefOf$2.apply(SymDenotations.scala:1720)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$baseTypeRefOf$2.apply(SymDenotations.scala:1709)
	at dotty.tools.dotc.reporting.Reporting$class.conditionalTraceIndented(Reporter.scala:132)
	at dotty.tools.dotc.core.Contexts$Context.conditionalTraceIndented(Contexts.scala:57)
	at dotty.tools.dotc.reporting.Reporting$class.debugTraceIndented(Reporter.scala:127)
	at dotty.tools.dotc.core.Contexts$Context.debugTraceIndented(Contexts.scala:57)
<snipped>
```

### PR DESCRIPTION
**Pull request by odersky**
Illegal class overrides are fundamentally at odds with the way dotty
represents types and therefore can cause lots of low-level problems.

Two measures in this commit:

First, we detect direct illegal class overrides on completion instead of
during RefChecks. Break the override by making the previously
overriding type private.

This fixes i1750.scala, but still fails for indirect overrides between
two unrelated outer traits/classes that are inherited by the same class or trait.
We fix this by catching the previously thrown ClassCastException
in both ExtractAPI and RefChecks.

Test case for indirect overrides is in i1750a.scala.

Review by @liufengyun

### CODE REVIEW

**Comment by odersky** [comment]
The CI failure Iis an OOM during dotty bootstrap.

File: compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala [hunk 1]
```diff
@@ -122,10 +123,18 @@ object OverridingPairs {
...
+            if (overriding.owner != overridden.owner && matches(overriding, overridden)) {
+              visited += overridden
+              if (!hasCommonParentAsSubclass(overriding.owner, overridden.owner)) return
+            }
+          }
+          catch {
+            case ex: CyclicReference =>
+              // See neg/i1750a for an example where a cyclic error can arise.
+              // The root cause in this example is an illegal "override" of an inner trait
+              ctx.error(cyclicErrorMsg(ex), base.pos)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala]: As a general rule in development, may I understand that `try/catch` can only be used as the last resort? Just want to know.

File: tests/neg/overrides.scala [hunk 2]
```diff
@@ -34,11 +34,6 @@ package p2 { // all being in the same package compiles fine
     }
   }
 
-  abstract class T3 extends T2 {
-    class A {   // error: classes cannot be overridden
-      bug()
-    }
-  }
 }
```
Comment (liufengyun) [inline tests/neg/overrides.scala]: why remove the class here?

Comment (odersky) [inline tests/neg/overrides.scala]: It now masks the other errors because the error is raised now in typer, whereas the others would be raised in RefChecks.

File: compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala (hunk 1 above)
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala]: It's complicated. Cyclic references can only be handled with try-catch, because at the points they are raised we typically do not have a way to back out cleanly. So if a cyclic reference is a possibility we need to handle it with try/catch. And we should try to minimize the places where cyclic references can be raised.

I would think twice before we introduce other exceptions and handle them with try/catch.

File: tests/neg/overrides.scala (hunk 2 above)
Comment (liufengyun) [inline tests/neg/overrides.scala]: I see, it makes sense.

**Comment by odersky** [comment]
We still get an OOM on dotty bootstrapped. @smarter @DarkDimius do we even need this test anymore, now that we bootstrap already as part of the build?

**Comment by smarter** [comment]
> We still get an OOM on dotty bootstrapped. @smarter @DarkDimius do we even need this test anymore, now that we bootstrap already as part of the build?

Yes, the bootstrap can now be done through sbt, but it still has to be done explicitly by using the `dotty-compiler-bootstrapped` subproject. This is exactly what `partest-only` now does, it runs partest inside `dotty-compiler-bootstrapped` instead of running it inside `dotty-compiler`.

The OOM we're getting here is similar to what I experienced while working on the sbt bootstrap, I thought I fixed them by increasing the heap size that sbt can use in https://github.com/lampepfl/dotty/pull/1896/commits/239a850f2d89a78e53386e3f9b8959be74bb9e65, but it looks like it wasn't enough. To recap: the OOM does not happen in one of the forked JVM where we run the tests, instead it happens in the original JVM used by sbt to run its tasks. Since `Runtime.getRuntime.availableProcessors` returns 40 on our CI, sbt can run up to 40 tasks at the same time, some of these tasks can be compile tasks where scalac compiles dotty, or dotty compiles itself, this easily adds up to a lot of heap usage. We could fix this by reducing the parallelism used by sbt but that would slow down our tests, instead I propose to try increasing the heap used by sbt again. We should also check if running dotty through sbt leaks memory, but that's less urgent.

**Comment by smarter** [comment]
... In fact you can disregard everything I said in the previous commit because this branch is not rebased on top of master, so it should not be using the new sbt-based bootstrap and the new CI settings, I'll rebase it to master and everything should be fine.

**Comment by odersky** [comment]
@smarter Thanks for rebasing!
