### PR TITLE
Fix #3588: Do not emit switch when matching on Any

### LINKED ISSUE #3588: Crash when trying to emit switch when matching on an Any
```scala
class Foo {
  val a: Any = 3
  a match {
    case 1 =>
    case 2 =>
    case 3 =>
    case _ =>
  }
}
```
 Crashes in the backend with

```
java.lang.AssertionError: assertion failed: Cannot emit primitive conversion from Ljava/lang/Object; to I
	at scala.Predef$.assert(Predef.scala:219)
	at scala.tools.nsc.backend.jvm.BCodeIdiomatic$JCodeMethodN.emitT2T(BCodeIdiomatic.scala:260)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.adapt(BCodeBodyBuilder.scala:900)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:435)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genMatch(BCodeBodyBuilder.scala:805)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:422)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:861)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:861)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:602)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:635)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:506)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.$anonfun$gen$1(BCodeSkelBuilder.scala:508)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.$anonfun$gen$1$adapted(BCodeSkelBuilder.scala:508)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:508)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:116)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:218)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:171)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:379)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:345)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:66)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:289)
....
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
As done `scalac`.

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 1]
```diff
@@ -834,7 +834,9 @@ object PatternMatcher {
       }
       plan match {
         case plan: TestPlan =>
-          val switchCases = collectSwitchCases(plan)
+          val switchCases =
+            if (plan.scrutinee.tpe.widen.classSymbol == defn.AnyClass) Nil
+            else collectSwitchCases(plan)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: I think it should be part of `collectSwitchCases` and use the already defined `isSwitchableType` function

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 2]
```diff
@@ -795,7 +795,8 @@ object PatternMatcher {
         (tpe isRef defn.IntClass) ||
         (tpe isRef defn.ByteClass) ||
         (tpe isRef defn.ShortClass) ||
-        (tpe isRef defn.CharClass)
+        (tpe isRef defn.CharClass) ||
+        (tpe isRef defn.StringClass)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: Scalac does not emit switch for `String`. Is it a limitation we can lift? Java supports switch for `String` since JDK 7

Comment (vitorsvieira) [reply compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: https://docs.oracle.com/javase/specs/jls/se7/html/jls-14.html#jls-14.11

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: Is support for switching on strings actually implemented somewhere in the compiler? The Java support is implemented by desugaring them into two switch statements on integers, there is no bytecode-level support for switching on strings.

File: library/test/dotty/ShowTests.scala [hunk 3]
```diff
@@ -64,7 +64,7 @@ class ShowTests {
     case class Car(model: String, manufacturer: String, year: Int)
 
     assertEquals("Car(Mustang,Ford,1967)", Car("Mustang", "Ford", 1967).show)
-    assertEquals("Map()", Map().show)
+    assertEquals("Map()", Map[String, String]().show)
```
Comment (allanrenucci) [inline library/test/dotty/ShowTests.scala]: What's the warning emitted?

The test actually expect something of type `Map[Nothing, Nothing]`.

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: We currenly do exactly the same as in scalac. We desugar it into if/then/else

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 4]
```diff
@@ -791,12 +791,6 @@ object PatternMatcher {
      *  plan and following onSuccess plans.
      */
     private def collectSwitchCases(plan: TestPlan): List[Plan] = {
-      def isSwitchableType(tpe: Type): Boolean =
-        (tpe isRef defn.IntClass) ||
-        (tpe isRef defn.ByteClass) ||
-        (tpe isRef defn.ShortClass) ||
-        (tpe isRef defn.CharClass)
-
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: I tried with `isSwitchableType` and it seems to work if you widen before calling it: 
```scala
isSwitchableType(scrutinee.tpe.widen)
```

File: tests/pos/i3588.scala [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+case class A(i: Int) extends AnyVal
+class Foo3 {
+  val a: A = new A(3)
+  a match {
+    case A(1) =>
+    case A(2) =>
+    case A(3) =>
+    case _ =>
+  }
+}
```
Comment (allanrenucci) [inline tests/pos/i3588.scala]: I would add two more tests:
- a pos test compiled with `-Xfatal-warnings`:
```scala
class Test {
  def test(x: 1) = (x: @annotation.switch) match {
    case 1 => 1
    case 2 => 2
    case 3 => 3
  }
}
```
- a neg test compiled with `-Xfatal-warnings`:
```scala
object Test {
  case class IntAnyVal(x: Int) extends AnyVal

  def test(x: IntAnyVal) = (x: @annotation.switch) match { //error: warning: could not emit switch
    case IntAnyVal(1) => 1
    case IntAnyVal(2) => 2
    case IntAnyVal(3) => 3
    case _ => 4
  }
}
```

Comment (nicolasstucki) [reply tests/pos/i3588.scala]: Done

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala (hunk 4 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: done
