### PR TITLE
Fix #6263: Register needsStaging when creating a synthetic quoted type

### LINKED ISSUE #6263: Passing Type[T] implicit argument where T <: AnyRef gives Dotty internal error
```scala
import quoted._

def fn[T : Type](v : T) = ???
```

Calling:
```scala
> fn("foo")
> fn((1,2))
> object O
  fn(O)
```
etc... (likely for any Ref type)

Give the following error:
```
java.lang.Error: Internal error: this method call should have been replaced by the compiler
        at scala.internal.Quoted$.typeQuote(Quoted.scala:17)
        at rs$line$5$.<init>(rs$line$5:1)
        at rs$line$5$.<clinit>(rs$line$5)
        at rs$line$5.res1(rs$line$5)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:57)
        at scala.Option.map(Option.scala:163)
...
```

Calling `foo(1)`, `foo('1')` (it seems for any Val type) instead gives the expected "missing implementation" error.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -667,29 +667,36 @@ trait Implicits { self: Typer =>
...
-                case _ =>
-                  ok = false
-                  t
-              }
-            case _ => t
+    def synthesizedTypeTag(formal: Type): Tree = {
+      def quotedType(t: Type) = {
+        if (StagingContext.level == 0)
+          ctx.compilationUnit.needsStaging = true // We will need to run ReifyQuotes
+        ref(defn.InternalQuoted_typeQuote).appliedToType(t)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: I'm not sure if _implicit search_ is the best place to put the logic --- what about put the logic in typer?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Implicits.scala]: We detect quotes and splices when we type. The issue here is that we will do not type this tree because we create it already typed.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Implicits.scala]: The concern I have here is about _modularity_. It seems the added code does not belong here. Is it due to concern about performance? Modularity could be sacrificed for performance.

**Comment by liufengyun** [comment]
test performance please
