### PR TITLE
Fix #5433: check that the implemented super-accessor is valid

### LINKED ISSUE #5433: Compilation order dependencies in compileStdLib
Running `testCompilation` locally fails for me (Linux, Oracle JDK 1.8.0_192) due to what appears to be a compilation order dependency in `compileStdLib`. This isn't normally visible in CI runs, presumably due to platform dependency of the compilation order. Sorting the sources, as done in https://github.com/lampepfl/dotty/pull/5432 causes local and CI builds to fail in the same way.

### PR DESCRIPTION
**Pull request by smarter**
Relying on `matchingDenotation` is not enough as demonstrated by
i5433.scala: in `Fail`, `B#foo` matches `C$$super$foo`
but it cannot implement it since `X` is a supertype of `Y`

Note that scalac seems to have the same bug (but at least in Dotty this
is detected by -Ycheck:all).

For reference, here's what the spec says on resolving super accessors:

  > A reference super.m refers statically to a method or type m in the
  least proper supertype of the innermost template containing the
  reference. It evaluates to the member m′ in the actual supertype of that
  template which is equal to m or which overrides m.

This seems like it should be clarified to indicate that the member m'
may be found not only in "the actual supertype" (defined elsewhere) but
in any supertype of the actual supertype.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ResolveSuper.scala [hunk 1]
```diff
@@ -103,7 +103,13 @@ object ResolveSuper {
       val other = bcs.head.info.nonPrivateDecl(memberName)
       if (ctx.settings.Ydebug.value)
         ctx.log(i"rebindsuper ${bcs.head} $other deferred = ${other.symbol.is(Deferred)}")
-      sym = other.matchingDenotation(base.thisType, base.thisType.memberInfo(acc)).symbol
+      val otherMember = other.matchingDenotation(base.thisType, base.thisType.memberInfo(acc))
+
+      // Having a matching denotation is not enough: it should also be a subtype
+      // of the superaccessor's type, see i5433.scala for an example where this matters
+      if (otherMember.asSeenFrom(base.typeRef).info <:< acc.asSeenFrom(base.typeRef).info)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/ResolveSuper.scala]: We should discuss whether a failing condition should not be an error instead.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/ResolveSuper.scala]: Resolved: a failing condition should be an error.

**Comment by odersky** [comment]
@smarter I did the change we discussed. Can I go ahead merging this?

**Comment by allanrenucci** [comment]
Note that it doesn't fix the original compilation order issue. What used to be a `Ycheck` failure is now a compilation error:
```
-- Error: dotty/scala2-library/src/library/scala/collection/mutable/IndexedSeqView.scala:46:37 
46 |  private[collection] abstract class AbstractTransformedX[B] extends super.AbstractTransformedS[B] with TransformedX[B]
   |                                     ^
   |                        illegal mixin super call target:
   |                        
   |                          override def tail: => scala.collection.SeqView[B, Coll]  in class AbstractTransformedS
   |                        
   |                        does not conform to expected target type
   |                        
   |                          => Repr
```
Can be reproduced by sorting the files from the `compileStdLib` test

**Comment by smarter** [comment]
>  Since it would be a pain to fix

Not really, we just need to replace some instances of `super.tail` by `super[Something].tail`.

> @smarter I did the change we discussed. Can I go ahead merging this?

The fix is OK but I'd like to improve the error message to give more details (explain that the issue comes from the linearization orders, which mixins are involved, how the issue could be solved by replacing super.foo by super[X].foo, ...). This isn't critical to merge this if you want to go ahead.

**Comment by odersky** [comment]
No, I guess if you have improvements in the pipeline we can leave this open.

**Comment by adriaanm** [comment]
This one looks related: explicitly targeting an abstract super method should also yield an error, right?

https://github.com/scala/bug/issues/8693

**Comment by smarter** [comment]
Alright, I've now made the error message as helpful as I could:
```scala
-- Error: tests/neg/i5433.scala:17:6 -------------------------------------------
17 |class Fail extends B with C
   |      ^
   |class Fail cannot be instantiated due to a conflict between its parents when
   |resolving a super-call:
   |
   |1. One of its parent (trait C) contains a call super.foo in its body.
   |2. Because B comes before C in the linearization
   |   order of Fail, and because B overrides foo,
   |   this is resolved as a call to super[B].foo in Fail.
   |3. However:
   |   X (the type of super[B].foo in Fail)
   |   is not a subtype of
   |   Y (the type of super[C].foo in Fail)
   |
   |Here are two possible ways to resolve this:
   |
   |1. Change the linearization order of Fail such that
   |   C comes before B.
   |2. Alternatively, replace super.foo in the body of trait C by a
   |   super-call to a specific parent, e.g. super[A].foo
```
/cc @adriaanm it'd be nice to align the messages between scalac and dotty here: https://github.com/scala/scala/pull/7641

File: compiler/src/dotty/tools/dotc/transform/ResolveSuper.scala [hunk 2]
```diff
@@ -100,10 +100,67 @@ object ResolveSuper {
...
+        sym = otherMember.symbol
+        // Having a matching denotation is not enough: it should also be a subtype
+        // of the superaccessor's type, see i5433.scala for an example where this matters
+        val otherTp = otherMember.asSeenFrom(base.typeRef).info
+        val accTp = acc.asSeenFrom(base.typeRef).info
+        if (!(otherTp <:< accTp)) {
+          // The mixin containing a super-call that requires a super-accessor
+          val mixin = acc.owner
+          // The super-call in `mixin`
+          val superCall = i"super.$memberName"
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/ResolveSuper.scala]: The method is getting quote long. maybe it's better to move the error message generation or the whole check into a separate method?
