### PR TITLE
Fix #5826: specialize union types to avoid constraint cut

### LINKED ISSUE #5826: Pattern matching is unsound in the presence of type unions
```scala
scala> def test[A]: List[Int] | A => Int = { case ls: List[Int] => ls.head  case _ => 0 }
def test[A] => List[Int] | A => Int

scala> test(List("oops"))
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
```

The definition of `test` should at least yield a warning like "erased type argument `Int` in type pattern `List[Int]` is unchecked".

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #5826: specialize union types to avoid constraint cut

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 1]
```diff
@@ -122,9 +122,19 @@ object TypeTestsCasts {
           case _                   => recur(defn.AnyType, tpT)
         }
       case tpe: AppliedType     =>
-        // first try withou striping type parameters for performance
-        isClassDetermined(X, tpe)(ctx.fresh.setNewTyperState()) ||
-        isClassDetermined(stripTypeParam(X), tpe)(ctx.fresh.setNewTyperState())
+        X.widen match {
+          case OrType(tp1, tp2) =>
+            // This case is required to retrofit type inference,
+            // which cut constraints in the following two cases:
```
Comment (Blaisorblade) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: I'm familiar with `TypeComparer#either` but I'm not sure I get what you are saying...
```
This case is required to match type inference, which simplifies constraints in the following two cases:
```

But if that's the reason, what about `T1 & T2 <:< T3`? Do we need to handle that somehow?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: `T1 & T2 <:< T3` is handled in the top-level match on `P`
