### PR TITLE
Fix #1372: Add handler for `PatDef`s to REPL

### LINKED ISSUE #1372: repl breaks multiple val definiton syntax`
taken from: http://scalapuzzlers.com/#pzzlr-017
```scala
class C
val x1,x2 = new C
val y1@y2 = new C
println(x1 == x2)
println(y1 == y2)
```

This code works in dotc, but does not work in repl: 
```scala
scala> val x1,x2 = new C
scala> val y1@y2 = new C
scala> println(x1 == x2)
        ^
println(x1 == x2)
<console>:8: error: not found: x1
```

### PR DESCRIPTION
**Pull request by cswinter**
Adds a new handler to `CompilingInterpreter` to extract variable definitions from `PatDef` statements, which allows multiple assignment syntax and pattern match assignments to work properly in the REPL.

Review by @odersky?

### CODE REVIEW

File: src/dotty/tools/dotc/repl/CompilingInterpreter.scala [hunk 1]
```diff
@@ -662,29 +663,71 @@ class CompilingInterpreter(
...
+
+        s""" + "$prettyName: $varType = " + """ +
+          if_(s"$fullPath.asInstanceOf[AnyRef] != null") {
+            if_(s"$fullPath.toString().contains('\\n')") { "\"\\n\"" }
+            /* else */ { "\"\"" } +
+              s""" + $fullPath.toString() + "\\n" """
+          } /* else */ {
+            "\"null\\n\""
+          }
       }
```
Comment (odersky) [inline src/dotty/tools/dotc/repl/CompilingInterpreter.scala]: I find there are too many levels of escaping to be able to understand it. Can we try to put everything between
one pair of """s and use only interpolation inside? That should also obviate the need for `if_`.

**Comment by odersky** [comment]
Otherwise LGTM

File: src/dotty/tools/dotc/repl/CompilingInterpreter.scala [hunk 2]
```diff
@@ -662,29 +663,68 @@ class CompilingInterpreter(
...
-            req.fullPath(vname) +
-            ".toString().contains('\\n')) " +
-            " \"\\n\" else \"\") + " +
-            req.fullPath(vname) + ".toString() + \"\\n\") else \"null\\n\") ")
-        }
+        if (!shouldShowResult(req)) return
+
+        val resultExtractors =
+          for (varName <- boundNames)
+            yield resultExtractionCode(req, varName)
```
Comment (smarter) [inline src/dotty/tools/dotc/repl/CompilingInterpreter.scala]: `val resultExtractors = boundNames.map(name => resultExtractionCode(req, name))` is more concise

File: src/dotty/tools/dotc/repl/CompilingInterpreter.scala [hunk 3]
```diff
@@ -662,29 +663,68 @@ class CompilingInterpreter(
...
+        code.print(resultExtractors.mkString(""))
+      }
+
+      private def resultExtractionCode(req: Request, varName: Name): String = {
```
Comment (smarter) [inline src/dotty/tools/dotc/repl/CompilingInterpreter.scala]: Avoid overloading when possible, you could name this method `resultExtractor` or something like that

**Comment by smarter** [comment]
Thanks for making these changes, merged!
