### PR TITLE
Fix #24997: Avoid unnecessary CHECKCAST in untupled function parameters

### LINKED ISSUE #24997: Automatic untupling introduces extra unnecessary CheckCast Instructions
I saw this in some cats effect code when using resources.  I minimised it to the code below.

## Compiler version

3.7.4

## Minimized code

```scala
package app

object Example:
  private class Wrapper[A](value: A):
    def use[B](f: A => B): B = f(value)
  end Wrapper

  def run: Int =
    val tupleWrapper = Wrapper((42, "Answer"))

    // tupleWrapper.use { case (number, _) => number }
    tupleWrapper.use { (number, _) => number }
  end run
end Example
```

## Output
When using the `case` for the inner lambda the code produced for it is this:

```scala
private final static synthetic run$$anonfun$1(Lscala/Tuple2;)I
    // parameter final  x$1
   L0
    LINENUMBER 12 L0
    ALOAD 0
    ASTORE 1
    ALOAD 1
    INVOKEVIRTUAL scala/Tuple2._1 ()Ljava/lang/Object;
    INVOKESTATIC scala/runtime/BoxesRunTime.unboxToInt (Ljava/lang/Object;)I
    ISTORE 2
   L1
    ILOAD 2
    IRETURN
```
which is what one would expect.  Only the first element of the pair is referenced since it is the only one used. But when the `case` keyword is not there (in which case automatic untupling takes place), we get the following:

```scala
private final static synthetic run$$anonfun$1(Lscala/Tuple2;)I
    // parameter final  x$1
   L0
    LINENUMBER 12 L0
    ALOAD 0
    INVOKEVIRTUAL scala/Tuple2._1 ()Ljava/lang/Object;
    INVOKESTATIC scala/runtime/BoxesRunTime.unboxToInt (Ljava/lang/Object;)I
    ISTORE 1
   L1
    ALOAD 0
    INVOKEVIRTUAL scala/Tuple2._2 ()Ljava/lang/Object;
    CHECKCAST java/lang/String
    ASTORE 2
   L2
    ILOAD 1
    IRETURN
```

As you can see now we fetch the second unused elements of the pair and  we do a CHECKCAST on it (and so the JVM cannot remove references to it, since CHECKCAST is side-effecting -- throws exceptions).  If you had 10 ignored args you get 10 CHECKCAST instructions.

## Expectation
I would expect to get the same code in both cases.  In the words of @som-snytt why is it that we can't have nice things...

### PR DESCRIPTION
**Pull request by aviralgarg05**
### Summary
This PR fixes an issue where automatic parameter untupling (e.g., `(number, _) => number`) introduced unnecessary `CHECKCAST` instructions for unused wildcard parameters. 

Previously, the compiler generated `ValDef` bindings for every element of the tuple, even if they were named `_`. This forced an extraction and a type check for unused elements. By filtering out wildcard parameters during desugaring, we avoid these unnecessary operations, making the generated bytecode as efficient as explicit pattern matching (`case (number, _) => number`).

### Changes
- **Desugar.scala**: Modified `makeTupledFunction` to only generate `ValDef` bindings for parameters that are not wildcards (`nme.WILDCARD`).
- **DottyBytecodeTests.scala**: Added a new test case `i24997` to verify that automatic untupling and explicit case-based untupling produce equivalent bytecode without extra casts.

### Verification
Ran the new bytecode test:
```bash
sbt "scala3-compiler-bootstrapped/testOnly dotty.tools.backend.jvm.DottyBytecodeTests -- i24997"
```

Fixes #24997

### CODE REVIEW

**Comment by som-snytt** [comment]
LGTM! The CLA check has instructions https://contribute.akka.io/contribute/cla/scala

**Comment by aviralgarg05** [comment]
> LGTM! The CLA check has instructions https://contribute.akka.io/contribute/cla/scala

Yes will that once all workflows are done, will fix all workflows that fail, altogether!!

**Comment by aviralgarg05** [comment]
> LGTM! The CLA check has instructions https://contribute.akka.io/contribute/cla/scala

Done this

File: compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala [hunk 1]
```diff
@@ -2009,6 +2009,46 @@ class DottyBytecodeTests extends DottyBytecodeTest {
...
+          case _ => false
+        }
+      }
+
+      val withCaseCasts = getCheckCastCount("withCase")
+      val withoutCaseCasts = getCheckCastCount("withoutCase")
+
+      // Both methods should have the same number of CHECKCAST instructions
+      // (specifically, they should NOT have extra ones for unused wildcard elements)
+      assertEquals(s"withCase has $withCaseCasts CHECKCASTs, withoutCase has $withoutCaseCasts",
```
Comment (nmichael44) [inline compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala]: @aviralgarg05 What if in the future (for reasons unknown) we end up with 2 CHECKCASTs in both cases.  The test will pass but it shouldn't.  Asserting that they are equal but also that one of them is 1 would make this a better test.

Comment (aviralgarg05) [reply compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala]: That's a great point. I'll update the test to assert the exact number of CHECKCAST instructions (0 in this case) to prevent regression in both scenarios. I'll also update the test helper to ensure it captures the instructions within the generated lambdas, as checking the outer method alone was missing the target instructions.

Comment (nmichael44) [reply compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala]: @aviralgarg05 Shouldn't it be 1 in both cases?  That was the point wasn't it.  To make the non-case one the same as the case-one.  If I am right, why didn't your test fail?

Comment (aviralgarg05) [reply compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala]: Umm, You're spot onit definitely should be 1 in both cases.
I dug back into the bytecode and found exactly why the test was passing with "0 and 1" and where the logic was still leaking, and have fixed that, Sorry for the messup

**Comment by som-snytt** [comment]
The check for "param usage" relies on unique names, which works because nested expressions will see fresh names.

For example, this is OK:
```
    tupleWrapper.use {
      _.toString + _.toString + tupleWrapper.use { _.toString + _.toString }
    }
```
Since the fix just checks wildcard names, unused but named parameters are unchanged.

I haven't tried inlining in the body of the function. An inlined tree from another compilation unit could have arbitrary fresh names.

Edit: I tried it, and desugar doesn't see an `inline transparent` tree. I was interested in this sort of hygiene issue:
```
        {
          tupleWrapper.use[String]((x$1: (Int, String)) =>
            {
              val _$1: Int = x$1._1
              val _$2: String = x$1._2
              _$1.toString() + _$2.toString() +
                tupleWrapper.use[String](
                  {
                    (x$1: (Int, String)) =>
                      {
                        val _$1: Int = x$1._1
                        val _$2: String = x$1._2
                        _$1.toString() + _$2.toString()
                      }
                  }
                )
            }
          )
          ()
        }
```
where the nested function is from an inlined def in a different file.

(If there were an issue, it would only de-optimize benignly.)
