### PR TITLE
Treat synthetic casts as pure

### LINKED ISSUE #24990: Presence of `opaque type` causes erased class instance to not be a pure expression
## Compiler version

3.7.4, 3.8.0, and 3.8.1-RC1

## Minimized code

```scala
//> using scala 3.8.0
//> using options -language:experimental.erasedDefinitions -explain

object test {
  opaque type Foo = Int

  class Bar[A] extends compiletime.Erased
  object Bar { inline given inst[A]: Bar[A] = new Bar[A] }
}

def takesBar[A](a: A)(using b: test.Bar[A]): A = a

val _ = takesBar(1)
```

## Output

```scala
-- [E217] Type Error: ----------------------------------------------------------
10 |val _ = takesBar(1)
   |                   ^
   |  implicit argument to an erased parameter fails to be a pure expression
   |----------------------------------------------------------------------------
   | Explanation (enabled by `-explain`)
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   | The implicit argument to an erased parameter must be a pure expression, but I found:
   |
   |   {
   |   val $proxy1: test.type{type Foo = Int} =
   |     test.$asInstanceOf[test.type{type Foo = Int}]
   |   val test$_this: ($proxy1 : test.type{type Foo = Int}) = $proxy1
   |   new test$_this.Bar[Int]():test$_this.Bar[Int]
   | }
   |
   | This expression is not classified to be pure.
   | A pure expression is an expression that is clearly side-effect free and terminating.
   |           |Some examples of pure expressions are:
   |           |  - literals,
   |           |  - references to values,
   |           |  - side-effect-free instance creations,
   |           |  - applications of inline functions to pure arguments.
```

## Expectation

The creation of `Bar[Int]` is a pure expression. It looks like the compiler is casting `test.type` to an instance of `test.type { type Foo = Int }`, and my guess is it's because `Bar` is defined in the same scope as `Foo`, and so therefore should see it as an `Int`...?

### PR DESCRIPTION
**Pull request by mrdziuban**
Closes #24990

This aims to fix an issue with erased definitions in the presence of `opaque type`s. The expression generated in the test here is:

```scala
{
  val $proxy1: test.type{type Foo = Int} =
    test.$asInstanceOf[test.type{type Foo = Int}]
  val test$_this: ($proxy1 : test.type{type Foo = Int}) = $proxy1
  new test$_this.Bar[Int]():test$_this.Bar[Int]
}
```

This is not considered pure due to the creation of `val $proxy1`, an opaque proxy. Specifically the call to `asInstanceOf` is not considered pure.

This updates `TypedTreeInfo#exprPurity` to consider calls to `defn.Any_typeCast` pure as long as the call is synthetic, which allows the whole expression to be considered pure.

### CODE REVIEW

**Review by odersky — CHANGES_REQUESTED** [review]
This works, but I think it can be improved. The RHS of the OpaqueProxy definition is a cast, i.e. an application of this method in `tpd`:
```
    /** cast tree to `tp`, assuming no exception is raised, i.e the operation is pure */
    def cast(tp: Type)(using Context): Tree = cast(TypeTree(tp))
```
As the comment states a cast should be considered a pure expression since the compiler knows that the cast cannot fail. But it seems we do not recognize this when we compute the purity of an expression. 

So, can we try to recognize casts as pure instead, and drop the special treatment of OpaqueProxies?

**Comment by mrdziuban** [comment]
Thanks for the feedback, @odersky.

> So, can we try to recognize casts as pure instead, and drop the special treatment of OpaqueProxies?

My first attempt was to treat `defn.Any_typeCast` as pure (https://github.com/scala/scala3/commit/be1ba341eb8cf409d2e2957322ea991e63804599), though now I think it would be better to also check if `sym.is(Synthetic)`:

```scala
|| sym == defn.Any_typeCast && sym.is(Synthetic)
```

Even with that extra check, there are changes to `metac.expect` that [cause CI to fail](https://github.com/scala/scala3/actions/runs/21413557249/job/61661695985):

```diff
diff --git a/tests/semanticdb/metac.expect b/tests/semanticdb/metac.expect
index 76ad77ba87..1dfe030101 100644
--- a/tests/semanticdb/metac.expect
+++ b/tests/semanticdb/metac.expect
@@ -3764,7 +3764,7 @@ Text => empty
 Language => Scala
 Symbols => 12 entries
 Occurrences => 33 entries
-Diagnostics => 1 entries
+Diagnostics => 4 entries
 Synthetics => 4 entries
 
 Symbols:
@@ -3817,9 +3817,12 @@ Occurrences:
 [21:4..21:19): StructuralTypes -> example/StructuralTypes.
 
 Diagnostics:
+[12:2..12:11): [warning] A pure expression does nothing in statement position
+[13:2..13:10): [warning] A pure expression does nothing in statement position
 [14:20..14:23): [warning] Alphanumeric method foo is not declared infix; it should not be used as infix operator.
 Instead, use method syntax .foo(...) or backticked identifier `foo`.
 The latter can be rewritten automatically under -rewrite -source 3.4-migration.
+[20:2..20:13): [warning] A pure expression does nothing in statement position
 
 Synthetics:
 [12:2..12:6):user => reflectiveSelectable(*)
```

It looks like that originates from [this code](https://github.com/scala/scala3/blob/ead18e6d1c296b9fdcac168a9442eacee45a9b6d/tests/semanticdb/expect/StructuralTypes.scala). I'm guessing those changes aren't okay? If not, do you have any suggestions on how else I could limit the check to only identify casts?

**Comment by odersky** [comment]
The changes to semanticdb outcomes look all good to me. We can just update the expect file.

**Comment by mrdziuban** [comment]
Sounds good, updated

**Comment by mrdziuban** [comment]
Is there anything more I can do to help get this ready to be merged?

**Comment by odersky** [comment]
Sorry, this slipped through. I was not assigned back, so I missed the changes.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -596,6 +596,7 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
           || sym == defn.Predef_classOf
           || sym == defn.Compiletime_erasedValue && tree.tpe.dealias.isInstanceOf[ConstantType]
           || defn.capsErasedValueMethods.contains(sym)
+          || sym == defn.Any_typeCast && sym.is(Synthetic)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]:
```suggestion
          || sym == defn.Any_typeCast
```
`is(Synthetic)` is redundant here.

**Comment by mrdziuban** [comment]
No problem! Thanks for taking a look.

**Comment by Gedochao** [comment]
@mrdziuban @odersky @tgodzik it seems this is ready to merge? Should I, is there a reason it's hanging?
