### PR TITLE
Only check newVal/newMethod privateWithin on -Xcheck-macros

### LINKED ISSUE #17432: Compilation fails due to assertion in `scala.quoted.runtime.impl.QuotesImpl$reflect$Symbol$.newVal`
## Compiler version
3.3.1-RC1-bin-20230504-0e00420-NIGHTLY

Found in Open Community build in following projects: 

Projects with last successful builds using Scala <b>[1m3.3.1-RC1-bin-20230427-f128063-NIGHTLY[0m</b> [16]:
| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| carlos-verdes/zio-arangodb | 0.2.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750443957) |  |
| lambdaworks/zio-elasticsearch | 0.1.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750070858) |  |
| vigoo/desert | 0.3.3 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750846690) |  |
| yakivy/jam | 0.3.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8747413966) |  |
| zio/zio-openai | 0.2.0 -> 0.2.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750444201) |  |

## Output

```scala
Error:  -- Error: /build/repo/arangodb-http/src/main/scala/io/funkode/arangodb/http/SchemaCodecs.scala:21:46 
Error:  21 |  given Schema[ArangoError] = DeriveSchema.gen[ArangoError]
Error:     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:     |Exception occurred while executing macro expansion.
Error:     |java.lang.AssertionError: assertion failed: privateWithin must be a type symbol or `Symbol.noSymbol`
Error:     |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Symbol$.newVal(QuotesImpl.scala:2547)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Symbol$.newVal(QuotesImpl.scala:2546)
Error:     |	at zio.schema.DeriveSchema.deriveCaseClass(DeriveSchema.scala:153)
Error:     |	at zio.schema.DeriveSchema.deriveSchema(DeriveSchema.scala:94)
Error:     |	at zio.schema.DeriveSchema$.deriveSchema(DeriveSchema.scala:18)
Error:     |	at zio.schema.DeriveSchema$.inline$deriveSchema(DeriveSchema.scala:17)
Error:     |```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Closes #17432

### CODE REVIEW

**Comment by sjrd** [comment]
If it's a term, we should still drop it in favor of `NoSymbol`. Otherwise it breaks TASTy.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 1]
```diff
@@ -2540,13 +2540,15 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
       def newMethod(owner: Symbol, name: String, tpe: TypeRepr): Symbol =
         newMethod(owner, name, tpe, Flags.EmptyFlags, noSymbol)
       def newMethod(owner: Symbol, name: String, tpe: TypeRepr, flags: Flags, privateWithin: Symbol): Symbol =
-        assert(!privateWithin.exists || privateWithin.isType, "privateWithin must be a type symbol or `Symbol.noSymbol`")
+        xCheckMacroAssert(!privateWithin.exists || privateWithin.isType, "privateWithin must be a type symbol or `Symbol.noSymbol`")
+        val privateWithin1 = if privateWithin.isTerm then Symbol.noSymbol else privateWithin
         checkValidFlags(flags.toTermFlags, Flags.validMethodFlags)
         dotc.core.Symbols.newSymbol(owner, name.toTermName, flags | dotc.core.Flags.Method, tpe, privateWithin)
```
Comment (sjrd) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2546]:
```suggestion
        dotc.core.Symbols.newSymbol(owner, name.toTermName, flags | dotc.core.Flags.Method, tpe, privateWithin1)
```
;)
