### PR TITLE
Fix #8045: Refine QuoteContext{val tasty} provided by splices

### LINKED ISSUE #8045: Failed unification of arguments, dependent from given arguments.
## minimized code

```Scala
package cps3
  
import scala.quoted._

object Test


  def run(given qctx: QuoteContext)(
                                    cases: List[qctx.tasty.CaseDef],
                                    ): Int =
     import qctx.tasty.{_, given}
     val l =  '{  ${makeExpr(cases)}+1  }
     ???


  def makeExpr(given qctx: QuoteContext)(
                                        caseDefs: List[qctx.tasty.CaseDef],
                                        ):Expr[Int] =
     ???
```

<details>
<summary>
</summary>

```scala
 ...
[error] -- [E007] Type Mismatch Error: /Users/rssh/work/oss/dotty-cps/dotty-cps/src/test/scala/cps/cbs2/TestCompileTryTransform.scala:12:29 
[error] 12 |     val l =  '{  ${makeExpr(cases)}+1  }
[error]    |                             ^^^^^
[error]    |                            Found:    (cases : List[qctx.tasty.CaseDef])
[error]    |                            Required: List[evidence$1.tasty.CaseDef]
[error] one error found
```
</details>

## expectation
 should compiled.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/StagingContext.scala [hunk 1]
```diff
@@ -18,8 +24,27 @@ object StagingContext {
...
   /** Context with a decremented quotation level. */
   def spliceContext(implicit ctx: Context): Context =
     ctx.fresh.setProperty(QuotationLevel, level - 1)
-}
 
+  /** Context with a decremented quotation level and pops the Some of top of the quote context stack or None if the stack is empty.
+   *  The quotation stack could be empty if we are in a top level splice or an eroneous splice directly witin a top level splice.
+   */
+  def popQuoteContext()(implicit ctx: Context): (Option[tpd.Tree], Context) =
+    val ctx1 = ctx.fresh.setProperty(QuotationLevel, level - 1)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/StagingContext.scala]: The property `QuotationLevel` is also mutated in `spliceContext` and `quoteContext`. This may cause accidental errors when used without care. Maybe remove  `spliceContext` and `quoteContext`, since they are not used.

File: compiler/src/dotty/tools/dotc/core/StagingContext.scala [hunk 2]
```diff
@@ -18,8 +24,27 @@ object StagingContext {
   def quoteContext(implicit ctx: Context): Context =
     ctx.fresh.setProperty(QuotationLevel, level + 1)
 
+  /** Context with an incremented quotation level and pushes a refecence to a QuoteContext on the quote context stack */
+  def pushQuoteContext(qctxRef: tpd.Tree)(implicit ctx: Context): Context =
+    val old = ctx.property(QuoteQontextStack).getOrElse(List.empty)
+    ctx.fresh.setProperty(QuotationLevel, level + 1)
+             .setProperty(QuoteQontextStack, qctxRef :: old)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/StagingContext.scala]: I'm wondering if the stack can be avoided using scoping rules for implicits.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/StagingContext.scala]: Yes, it could but we would need to track a level context and a splice context. The errors when those implicit are not found would also be hard to interpret.

File: compiler/src/dotty/tools/dotc/core/StagingContext.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/StagingContext.scala]: We use those in `PCPCheckAndHeal` and `ReifyQuotes`. There we only need to track the level.
