### PR TITLE
check whether a value class parameter is call-by-name

### LINKED ISSUE #5121: Infinite loop with by name value classes
```scala
class Foo(sc: => Int) extends AnyVal
```

emits the error 
```scala
2 |  class Foo(sc: => Int) extends AnyVal
  |        ^
  |        value sc in class Foo does not take parameters
```

but then stays in an infinite loop.

In scalac it fails with 
```
Foo.scala:2: error: value class parameter must be a val and not be private[this]
```

In both scalac and dotty 
```scala
class Foo(val sc: => Int) extends AnyVal
```
fails correctly with `val parameters may not be call-by-name`

### PR DESCRIPTION
**Pull request by Jasper-M**
fixes #5121

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala [hunk 1]
```diff
@@ -1666,6 +1666,13 @@ object messages {
     val explanation = ""
   }
 
+  case class ValueClassParameterMayNotBeCallByName(valueClass: Symbol, param: Symbol)(implicit ctx: Context)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: We should reuse `VarValParametersMayNotBeCallByName` instead and maybe addapt a bit it's explanation.

**Comment by allanrenucci** [comment]
@nicolasstucki I don't think we should forbid this. `dotc` does not require value class parameter to be a `val` as opposed to `scalac`, so we don't need to impose this restriction.

We should fix the infinite loop of course

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala (hunk 1 above)
Comment (Jasper-M) [reply compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: That was my first idea, but I thought it might be confusing, because it's not really a `val` and doesn't seem to behave like a case class parameter, which implicitly is a `val`, either.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: You are right

**Comment by nicolasstucki** [comment]
@Jasper-M then could you just change the commit message to be `Fix #5121: Check if value class parameter is call-by-name`. The implementation looks good.

**Comment by nicolasstucki** [comment]
Thanks @Jasper-M

**Comment by Blaisorblade** [comment]
Thanks @Jasper-M, and nice to see you here!
