### PR TITLE
Fix varargs overload resolution with wildcard types

### LINKED ISSUE #24072: Ambiguous overload when involving wildcard types and variadic parameters
## Compiler version

3.7.3

## Minimized code

```scala
object Test {
  def main(args: Array[String]): Unit = {
    blub(classOf[Object])
  }

  def blub[T](a: Class[? <: T]): Unit = println("a")
  def blub[T](a: Class[T], ints: Int*): Unit = println("b")
}
```

## Output

```scala
Ambiguous overload. The overloaded alternatives of method blub in object Test with types
 [T](a: Class[T], ints: Int*): Unit
 [T](a: Class[? <: T]): Unit
both match arguments ((classOf[Object] : Class[Object]))
```

## Expectation

Should run and print `a`

## Reasons this should not be an error

1. The same code compiles in Scala 2 and prints `a`
2. If the variadic parameter is replaced with a default parameter, the code compiles in Scala2 and Scala3 and prints `a`
3. The same code works in Java and otherwise it's not possible to call the version that prints `a` from Scala3:
 ```java
public class TestInJava {
    public static void main(String[] args) {
        blub(Object.class);
    }

    public static <T> void blub(Class<? extends T> cls) {
        System.out.println("a");
    }

    public static <T> void blub(Class<T> cls, int ...b) {
        System.out.println("b");
    }
}
```

### PR DESCRIPTION
**Pull request by tanishiking**
Fixes #24072

When comparing overloaded methods where one is non-varargs with wildcard types (e.g., `Class[? <: T]`) and another is varargs, the non-varargs method should be preferred.
Previously, the compiler failed to distinguish these methods , and results in an ambiguity error.

```scala
def blub[T](a: Class[? <: T]): Unit // m1
def blub[T](a: Class[T], ints: Int*): Unit // m2
blub(classOf[Object]) // m1 should be picked, but fails to resolve
````

The problem is `compare(m1, m2)` returned 0 because:

- (1). `m2` (varargs) is correctly considered "not as good" as `m1`.
- (2). `m1` (non-varargs) was also considered "not as good" as `m2`. (but `m1` should be as good as `m2`! because `Class[Concrete]` can be applied to both m1 and m2).

The (2) occurred because `Class[? <: T]` is not a subtype of `Class[T]` (due to invariance). Consequently, `isApplicableMethodRef(m2, Class[? <: T])` returned `false` because `isCompatible(Class[? <: T], Class[T])` returned `false` during the applicability check against the method.

This commit adds special handling in `TestApplication.argOK` to check if wildcard upper bounds are compatible with their formal types during overload resolution, in addition to `isCompatible`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -2176,7 +2176,20 @@ trait Applications extends Compatibility {
...
             if winsType1 != winsType2 then if winsType1 then 1 else -1
             else if alt1.symbol == alt2.symbol then comparePrefixes
-            else 0
+            else
+              // Prefer non-varargs methods over varargs methods as a final tiebreaker.
+              // While `isAsGood` normally handles this, it can fail when wildcard types are involved.
+              // For example, when comparing:
+              //   def m[T](a: Class[? <: T]): Unit
+              //   def m[T](a: Class[T], ints: Int*): Unit
+              // Both winsType1 and winsType2 are false because Class[? <: T] is not
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala]: Given

- m1 = `def m[T](a: Class[? <: T]): Unit`
- m2 = `def m[T](a: Class[T], ints: Int*): Unit`

`isAsGood(m1, m2)` returns `false` because here

https://github.com/scala/scala3/blob/c3c121c484c1d8a6975b577659a225a78ada1ca4/compiler/src/dotty/tools/dotc/typer/Applications.scala#L2003

`isApplicableMethodRef(m2, List(Class[? <: T])` is `false`, because `Class[? <: T] <: Class[T]` doesn't hold.

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 2]
```diff
@@ -883,7 +883,27 @@ trait Applications extends Compatibility {
...
+        // For example, given:
+        //   def blub[T](a: Class[? <: T]): String = "a"
+        //   def blub[T](a: Class[T], ints: Int*): String = "b"
+        //   blub(classOf[Object])
+        //
+        // The non-varargs overload should be preferred. While Class[? <: T] is not a
+        // subtype of Class[T] (Class is invariant), for overload resolution we consider
+        // Class[? <: T] "applicable" where Class[T] is expected by checking if the
+        // wildcard's upper bound is a subtype of the formal type parameter.
+        def wildcardArgOK =
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:896]: The logic looks fine. My only concern here is compilation time. We should try to optimize this and only call wildcardArgOK in the (relatively rare) case where `argtpe` has wildcard arguments. Something like

```scala
hasWilcardArgs(argtpe) && (argtpe, formal).match ...
```

**Comment by tanishiking** [comment]
Thank you for reviewing @odersky ! merging
