### PR TITLE
Fix #6270: Allow change of color setting in TASTy Reflect

### LINKED ISSUE #6270: Expr[T].show should not show color
The following code, when compiled manually, will result in runtime exception due to the ASCII-colored output from `Expr[T].show`:

```Scala
// assert_1.scala
object api {
  inline def (x: => String) reflect : String =
    ${ reflImpl('x) }

  private def reflImpl(x: Expr[String])(implicit refl: Reflection): Expr[String] = {
    import refl._
    x.show.toExpr
  }
}

// test_2.scala
import api._

object Test {
  def main(args: Array[String]): Unit = {
    println(args(0).reflect)
    assert(args(0).reflect == "args.apply(0)")
  }
}
```

Command to compile:

```
dotc -d out tests/run-with-compiler/reflect-color/assert_1.scala
dotc -d out -classpath out tests/run-with-compiler/reflect-color/test_2.scala
dotr -classpath out Test
```

It compiles with `dotty-bootstrapped/testCompilation reflect-color`, because the test set by default disables color.

### PR DESCRIPTION
**Pull request by nicolasstucki**
This provides a way to enabled and disable color when printing. The default is set to the current compiler setting.

Now, if someone wants a show that never prints the colors it can be implemented with

```scala
implicit def (expr: scala.quoted.Expr[T]) showColorless[T] (implicit reflect: Reflection): String = {
  import reflect._
  expr.unseal.showCode(the[Context].withoutColors)
}
```

Note that `Tree.showCode` will change name to `Tree.show` to match `Expr.show`.

### CODE REVIEW

File: library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala [hunk 1]
```diff
@@ -22,7 +24,9 @@ trait QuotedOps extends Core { self: Printers =>
     def unseal(implicit ctx: Context): TypeTree =
       kernel.QuotedType_unseal(tpe)
 
-    /** Show a source code like representation of this type */
+    /** Show a source code like representation of this type
+     *  Will print Ansi colors if ctx.printColors is enabled.
+     */
     def show(implicit ctx: Context): String =
       unseal.showCode
```
Comment (liufengyun) [inline library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala]: It's better to default to no colors other than `ctx.printColors` as that's what users want most of the time.

Otherwise, users will be forced to write `x.show(the[Context].withColors)` instead of `x.show`.

Comment (liufengyun) [reply library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala]: We can do either with a default `color: Boolean = false` or have two methods:

- show
- showColored

Both are more friendly than `x.show(the[Context].withColors)`

Comment (nicolasstucki) [reply library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala]: We cannot a default the is different for the compiler setting or every other use case will break.

As shown in the example it is easy to add your own version of `show` where you disregard the default settings.

Comment (nicolasstucki) [reply library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala]: We can always add some variant later

Comment (liufengyun) [reply library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala]: I think it's better to have it now as we go -- we will forget all these minor usability issues. If such usability issues accumulate, the user experience with Tasty Reflect will degrade.
