### PR TITLE
Fix #10107: Improve `inline if` constant condition detraction and reporting

### LINKED ISSUE #10107: inline if error suggests it expects a literal expression
## Minimized code

Say we make a simple macro that just returns the value `true`.
```Scala
object Proc {
  inline def isTrue: Boolean = ${ isTrueImpl }
  def isTrueImpl(using qctx: QuoteContext) = {
    Expr(true) // even tried: Literal(Constant(true).seal.asExprOf[Boolean])
  }
}
```
Now if we use that with an inline if statement:
```scala
  inline def oneOf(): String = {
    inline if (isTrue)
      "foo"
    else
      "bar"
  }
```
Then when I run that:
```scala
oneOf()
```
The following error happens...

## Output

```
[error]    |    cannot reduce inline if
[error]    |     its condition   miniquill.ListProc.isTrue
[error]    |     is not a constant value
```

## Expectation
I think this should be more intelligent about looking at the AST and detecting if there is a constant value. I even tried making `oneOf` return `Literal(Constant(true))` but it still did not work.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Showing the reduced condition is much more useful than showing the original condition.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -1235,9 +1235,8 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
           else Block(cond1 :: Nil, selected)
         case cond1 =>
           if (tree.isInline)
-            errorTree(tree, em"""cannot reduce inline if
-                                | its condition   ${tree.cond}
-                                | is not a constant value""")
+            errorTree(tree, em"""Cannot reduce `inline if` with non constant value.
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:1238]: I think the old error message is clearer.

**Review by odersky — COMMENTED** [review]
Otherwise LGTM

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1238]: The issue with the previous message is that the condition is printed in the middle of the message. That condition may be long or have several lines. Ideally we should have a message where the tree is printed last.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1238]:
```
Cannot reduce `inline if` because its condition is not a constant value:
$cond1
```
I keep meaning to see that Ralph Fiennes movie, "The Constant Gardener."

If we could use that title for a narrative about compilation, then we'd have the same problem as that other Fiennes movie, "The English Patient," whether to emphasize the adjective or the noun.

The suggested edit avoids "non constant" --> "non-constant" --> "inconstant" discussion.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: I used ```"Cannot reduce `inline if` because its condition is not a constant value: $cond"```.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: OK, I see the reasoning now.
