### PR TITLE
Fix #12249: don't export java defined modules

### LINKED ISSUE #12249: Export Java Symbols compiles, but fails at runtime with `NoClassDefFoundError`.
## Compiler version

3.0.0-RC3 (also fails in the earlier versions)

## Minimized code

```Scala
export java.util.UUID

println(UUID.randomUUID())
```

## Output

```scala
[error] (run-main-0) java.lang.NoClassDefFoundError: java/util/UUID$
[error] java.lang.NoClassDefFoundError: java/util/UUID$
[error]         at dev.insideyou.delete3me.Main$package$.UUID(Main.scala:4)
[error]         at dev.insideyou.delete3me.Main$.<clinit>(Main.scala:9)
[error]         at dev.insideyou.delete3me.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: java.util.UUID$
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
```

## Expectation
I either expect it NOT to compile in the first place or even better actually work.

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 1]
```diff
@@ -1000,6 +1000,8 @@ class Namer { typer: Typer =>
           ) match
               case Some(other) => No(i"overrides ${other.showLocated}, which is already a member of $cls")
               case None => Yes
+        else if sym.is(JavaDefined) then
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:1003]: I think the issue comes from trying to export a Java class because we're missing code for exporting the static methods of the class but we shouldn't prevent exporting a Java method

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 2]
```diff
@@ -1000,6 +1000,8 @@ class Namer { typer: Typer =>
           ) match
               case Some(other) => No(i"overrides ${other.showLocated}, which is already a member of $cls")
               case None => Yes
+        else if sym.is(JavaDefined) && sym.is(Module) then
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:1003]:
```suggestion
        else if sym.is(JavaModule) then
```

**Review by smarter — CHANGES_REQUESTED** [review]

**Review by smarter — APPROVED** [review]
