### PR TITLE
Fix #1490: type test of union types via type alias

### LINKED ISSUE #1490: Incorrect type test of union types via type alias
``` Scala
class Base {
  type T = Int | Boolean
  def test(x: Object) = x.isInstanceOf[T]
}

object Test {
  def main(args: Array[String]) = {
    val b = new Base
    println(b.test(Int.box(3)))                   
    println(b.test(Double.box(3.4)))    // should be false, but true
  }
}
```

### PR DESCRIPTION
**Pull request by liufengyun**
Make type erasure accept one additional parameter:

- `eraseOrType`: Whether erase OrType to its lowest uppper bound

### CODE REVIEW

File: src/dotty/tools/dotc/core/TypeErasure.scala [hunk 1]
```diff
@@ -112,9 +112,10 @@ object TypeErasure {
   /** The standard erasure of a Scala type. Value classes are erased as normal classes.
    *
    *  @param tp            The type to erase.
-  */
-  def erasure(tp: Type)(implicit ctx: Context): Type =
-    erasureFn(isJava = false, semiEraseVCs = false, isConstructor = false, wildcardOK = false)(tp)(erasureCtx)
+   *  @param eraseOrType   Whether erase OrType to its lowest uppper bound
```
Comment (smarter) [inline src/dotty/tools/dotc/core/TypeErasure.scala]: I would write `Whether OrType should be erased to its lowest upper bound`

File: src/dotty/tools/dotc/core/TypeErasure.scala [hunk 2]
```diff
@@ -112,9 +112,10 @@ object TypeErasure {
...
+   */
+  def erasure(tp: Type, eraseOrType: Boolean = true)(implicit ctx: Context): Type =
+    erasureFn(isJava = false, semiEraseVCs = false, isConstructor = false, wildcardOK = false)(tp, eraseOrType)(erasureCtx)
```
Comment (smarter) [inline src/dotty/tools/dotc/core/TypeErasure.scala]: I think it would be more consistent to add this parameter to the `TypeErasure` class like `semiEraseVCs`, etc.

Comment (liufengyun) [inline src/dotty/tools/dotc/core/TypeErasure.scala]: Indeed it's, I'll update the commit.

File: src/dotty/tools/dotc/core/TypeErasure.scala (hunk 1 above)
Comment (liufengyun) [inline src/dotty/tools/dotc/core/TypeErasure.scala]: Thanks, will address in the next commit.

**Comment by odersky** [comment]
I am missing the context. Why do we need to make this distinction? The way it is done it adds a significant cost to compiler complexity. Adding a new boolean parameter to a core method should not be taken lightly, because you just have doubled all possible error scenarios!

**Comment by smarter** [comment]
`transformIsInstanceOf` takes erased arguments but sometimes y`ou don't actually want to erase things because you're going to do transformations on the `instanceOf` checks like for union types and singleton types. The alternative would be to rewrite `transformIsInstanceOf` to expect non-erased arguments and only erase them after doing the rewritings it needs to do, that might be better indeed.

**Comment by smarter** [comment]
By the way, the same thing is true in https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/transform/IsInstanceOfEvaluator.scala which deals with erased values and so might end up doing an incorrect rewriting.

**Comment by liufengyun** [comment]
> The alternative would be to rewrite transformIsInstanceOf to expect non-erased arguments and only erase them after doing the rewritings it needs to do, that might be better indeed.

@smarter That is how the previous implementation was done, but it doesn't handle the case in #1490 . A proper handling of #1490 would require us to recursively get rid of all type alias, that's part of the logic of type erasure. Either we need to find a way to reuse the type erasure code, or we have to duplicate some of its code.

**Comment by odersky** [comment]
Question: What should the imlementation

    xs.isInstanceOf[List[A | B]] 

be? Erase | or not? I would assume erase. In which case, the whole thing does belong in isInstanceOfEvaluator. Can #1490 not be addressed by dealiasing?

**Comment by smarter** [comment]
I think that inn your exaple, `A | B` is not erased if `eraseOrType` is false, but `List[A | B]` is erased to a raw `List` anyway so it doesn't matter

**Comment by liufengyun** [comment]
I agree it's better to make the core simpler. Will follow the original approach by dealiasing.

**Comment by smarter** [comment]
LGTM
