### PR TITLE
Fix #8573: Fix higher-kinded bounded opaque types

### LINKED ISSUE #8573: Opaque type has "possibly conflicting bounds"
## minimized code

```Scala
object Example1 { 
  opaque type Foo[A] <: A = A
}

object Example2 { 
  opaque type Foo[A] >: A = A
}
```

## Compilation output

```scala
object Example1 cannot be instantiated since it has a member Foo with possibly conflicting bounds LazyRef([A] =>> A) <: ... <: [X0] =>> A & X0

object Example2 cannot be instantiated since it has a member Foo with possibly conflicting bounds [X0] =>> A | X0 <: ... <: [A] =>> A
```

## expectation
No errors.

### PR DESCRIPTION
**Pull request by odersky**
- Fix the type parameters with which explicitly given bounds of a higher-kinded
   opaque type should be abstracted.

 - Explicitly disallow unapplied right-hand sides of opaque types. They will lead
   to bad bounds later anyway, so we should give an intelligible error message
   early on.

Open question: Should we disallow all unapplied right hand sides for all type aliases,
not just opaque ones?

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -460,7 +462,7 @@ object SymDenotations {
       info match
         case TypeAlias(alias) if isOpaqueAlias && owner.isClass =>
           setAlias(alias)
-          HKTypeLambda.boundsFromParams(alias.typeParams, bounds(rhs))
+          HKTypeLambda.boundsFromParams(tparams, bounds(rhs))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Just curious, we have to use `tparams` instead of `alias.typeParams` due to the following test in `boundsFromParams`?

```Scala
      def isOpaqueAlias = params match
        case (param: Symbol) :: _ => param.owner.is(Opaque)
        case _ => false
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: `alias.typeParams` is a list of `TypeParamRefs`, which are different from the symbols on `rhs`. That caused the problem.
