### PR TITLE
Fix #7392: Interpolate all wildcards in the resulttype of a closure

### LINKED ISSUE #7392: Default argument causes compiler to crash
```scala
object Test {

  trait ZStream[-R, +E, +A]

  object ZStream {
    def empty: ZStream[Any, Nothing, Nothing] =
      ???
  }

  trait Gen[-R, +A](sample: ZStream[R, Nothing, A])

  def fromIterable[R, A](
    as: Iterable[A],
    shrinker: (A => ZStream[R, Nothing, A]) = (_: A) => ZStream.empty
  ): Gen[R, A] = ???
}
```

This will compile if the default argument is removed but with the default argument it crashes with the following stack trace:

```
sbt:dotty-simple> compile
[info] Compiling 1 Scala source to /Users/adamfraser/dotty-project-template/target/scala-0.19/classes ...
[info] exception occurred while typechecking /Users/adamfraser/dotty-project-template/src/main/scala/Gen.scala
java.lang.Error: internal error: type of right-hand side A => Test.ZStream[(?), Nothing, (?)] is not fully defined, pos = <198..295> while compiling /Users/adamfraser/dotty-project-template/src/main/scala/Gen.scala
[info] exception occurred while compiling /Users/adamfraser/dotty-project-template/src/main/scala/Gen.scala
[error] ## Exception when compiling 4 sources to /Users/adamfraser/dotty-project-template/target/scala-0.19/classes
[error] internal error: type of right-hand side A => Test.ZStream[(?), Nothing, (?)] is not fully defined, pos = <198..295>
[error] dotty.tools.dotc.typer.Inferencing$.fullyDefinedType(Inferencing.scala:44)
[error] dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1358)
[error] dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1369)
[error] dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1377)
[error] dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1446)
[error] dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:769)
[error] dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:886)
[error] dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:796)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:257)
[error] dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:182)
[error] dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:184)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:397)
[error] dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2013)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2038)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2116)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2184)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2228)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1727)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2051)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2116)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2184)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2228)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1852)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2092)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2117)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2241)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:75)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:41)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:79)
[error] dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:109)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:109)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:159)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:169)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:177)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:184)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:121)
[error] dotty.tools.dotc.Run.compile(Run.scala:104)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error] dotty.tools.dotc.Driver.process(Driver.scala:178)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:278)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.lang.Error: internal error: type of right-hand side A => Test.ZStream[(?), Nothing, (?)] is not fully defined, pos = <198..295>
[error]         at dotty.tools.dotc.typer.Inferencing$.fullyDefinedType(Inferencing.scala:44)
[error]         at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1358)
[error]         at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1369)
[error]         at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1377)
[error]         at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1446)
[error]         at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:769)
[error]         at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:886)
[error]         at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:796)
[error]         at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:257)
[error]         at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:182)
[error]         at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:184)
[error]         at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:397)
[error]         at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2013)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2038)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2116)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2184)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2228)
[error]         at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1727)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2051)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2116)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2184)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2228)
[error]         at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1852)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2092)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2117)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2153)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2165)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2241)
[error]         at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:75)
[error]         at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:41)
[error]         at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:79)
[error]         at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:109)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:305)
[error]         at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:109)
[error]         at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:159)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error]         at dotty.tools.dotc.Run.runPhases$5(Run.scala:169)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:177)
[error]         at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:184)
[error]         at dotty.tools.dotc.Run.compileSources(Run.scala:121)
[error]         at dotty.tools.dotc.Run.compile(Run.scala:104)
[error]         at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error]         at dotty.tools.dotc.Driver.process(Driver.scala:178)
[error]         at dotty.tools.dotc.Main.process(Main.scala)
[error]         at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.lang.Error: internal error: type of right-hand side A => Test.ZStream[(?), Nothing, (?)] is not fully defined, pos = <198..295>
[error] Total time: 0 s, completed Oct 8, 2019 3:47:18 PM
```

### PR DESCRIPTION
**Pull request by odersky**
Make sure we interpolate all wildcards in the prototype before making it
the result type of an anonymous function. This was done previously only for
toplevel wildcards, but not for wildcards nested in some type.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -833,12 +833,18 @@ class Typer extends Namer
       case _: WildcardType => untpd.TypeTree()
       case _ => untpd.TypeTree(tp)
     }
+    def interpolateWildcards = new TypeMap {
+      def apply(t: Type) = t match
+        case WildcardType => newTypeVar(TypeBounds.empty)
+        case WildcardType(bounds: TypeBounds) => newTypeVar(bounds)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Could there be WildcardTypes in the bounds themselves that need to be replaced recursively ?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -833,12 +833,18 @@ class Typer extends Namer
       case _: WildcardType => untpd.TypeTree()
       case _ => untpd.TypeTree(tp)
     }
+    def interpolateWildcards = new TypeMap {
+      def apply(t: Type) = t match
+        case WildcardType => newTypeVar(TypeBounds.empty)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: `newTypeVar` will call `constrained(poly, untpd.EmptyTree, ...)` but we do actually have an owning tree that we could use here I think.
