### PR TITLE
Fix #3050: Avoid retyping synthesised code

### LINKED ISSUE #3050: notype when inlining pattern matching
```scala
object Test {
  inline def openImpl(n: Some[Int]): Int =
    n match { case Some(i) => i }

  def open(a: Some[Int]): Int = openImpl(a)
}
```

<details>
  <summary>Stack trace</summary>
<pre>
Exception in thread "main" java.lang.AssertionError: assertion failed: <notype> class dotty.tools.dotc.ast.Trees$TypeTree 115
        at scala.Predef$.assert(Predef.scala:219)
        at dotty.tools.dotc.typer.ReTyper.promote(ReTyper.scala:29)
        at dotty.tools.dotc.typer.ReTyper.typedTypeTree(ReTyper.scala:52)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1652)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1679)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.typedType(Typer.scala:1753)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedDefDef$1(Typer.scala:1294)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1287)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1620)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1678)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1716)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1739)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:620)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedBlock$1(Typer.scala:623)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:622)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1639)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1679)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedFunction$1(Typer.scala:846)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedFunction(Typer.scala:693)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1641)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1679)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2108)
        at dotty.tools.dotc.typer.Typer.adaptInterpolated(Typer.scala:2275)
        at dotty.tools.dotc.typer.Typer.$anonfun$adapt$3(Typer.scala:1855)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.$anonfun$adapt$1(Typer.scala:1851)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:1851)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1751)
        at dotty.tools.dotc.typer.ReTyper.typedUnApply(ReTyper.scala:61)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1665)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1679)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.typedPattern(Typer.scala:1755)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedCase$1(Typer.scala:964)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedCase(Typer.scala:918)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedCases$3(Typer.scala:912)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:62)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
        at dotty.tools.dotc.typer.Typer.typedCases(Typer.scala:912)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedMatch$1(Typer.scala:884)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:875)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1644)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1679)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Inliner.$anonfun$inlined$8(Inliner.scala:475)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:140)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:472)
        at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:245)
        at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:2146)
        at dotty.tools.dotc.typer.Typer.adaptInterpolated(Typer.scala:2275)
        at dotty.tools.dotc.typer.Typer.$anonfun$adapt$3(Typer.scala:1855)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.$anonfun$adapt$1(Typer.scala:1851)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:1851)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1751)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedDefDef$1(Typer.scala:1305)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1287)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1620)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1678)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1716)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1739)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedClassDef$1(Typer.scala:1405)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1335)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1623)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1678)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1716)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1739)
        at dotty.tools.dotc.typer.Typer.$anonfun$typedPackageDef$1(Typer.scala:1522)
        at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1509)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1662)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1679)
        at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1694)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented(Reporter.scala:169)
        at dotty.tools.dotc.reporting.Reporting.doTraceIndented$(Reporter.scala:154)
        at dotty.tools.dotc.core.Contexts$Context.doTraceIndented(Contexts.scala:58)
        at dotty.tools.dotc.reporting.Reporting.dotty$tools$dotc$reporting$Reporting$$doTraceIndented(Reporter.scala:151)
        at dotty.tools.dotc.reporting.Reporting.traceIndented(Reporter.scala:141)
        at dotty.tools.dotc.reporting.Reporting.traceIndented$(Reporter.scala:139)
        at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:58)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1692)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1751)
        at dotty.tools.dotc.typer.FrontEnd.$anonfun$typeCheck$1(FrontEnd.scala:64)
        at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:32)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:62)
        at dotty.tools.dotc.typer.FrontEnd.$anonfun$runOn$5(FrontEnd.scala:93)
        at dotty.tools.dotc.typer.FrontEnd.$anonfun$runOn$5$adapted(FrontEnd.scala:93)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:93)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:123)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:120)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:120)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:108)
        at dotty.tools.dotc.Run.compileSources(Run.scala:95)
        at dotty.tools.dotc.Run.compile(Run.scala:79)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
        at dotty.tools.dotc.Driver.process(Driver.scala:124)
        at dotty.tools.dotc.Driver.process(Driver.scala:93)
        at dotty.tools.dotc.Driver.process(Driver.scala:105)
        at dotty.tools.dotc.Driver.main(Driver.scala:132)
        at dotty.tools.dotc.Main.main(Main.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
</pre>
</details>

### PR DESCRIPTION
**Pull request by biboudis**
This is a crude way to fix #3050's bugs with retyping inlined code involving pattern matching.

WDYT?

### CODE REVIEW

**Comment by smarter** [comment]
The stackoverflow is spurious and unrelated to this PR, it's the same issue as https://github.com/lampepfl/dotty/issues/2924

**Comment by biboudis** [comment]
test performance please

**Comment by allanrenucci** [comment]
@nicolasstucki Can we open a separate PR with the last commit if it fixes #2924? I am eager to get this in as it would solve many CI failures.

File: compiler/src/dotty/tools/dotc/core/Decorators.scala [hunk 1]
```diff
@@ -112,9 +112,11 @@ object Decorators {
         else x1 :: xs1
       }
 
-    def foldRightBN[U](z: => U)(op: (T, => U) => U): U = xs match {
+    def foldRightBN[U](z: => U)(op: (T, => U) => U): U = xs.reverse.foldLeftBN(z)(op)
+
+    @tailrec final def foldLeftBN[U](z: => U)(op: (T, => U) => U): U = xs match {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/core/Decorators.scala]: `foldLeft` in the standard library has the accumulator as the first arg of the closure:
```scala
def foldLeft[U](z: U)(op: (U, T) => U): U
```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/Decorators.scala]: Oh yes, `z` is supposed to be called `acc`

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/Decorators.scala]: I will create a separate PR with this.

**Comment by nicolasstucki** [comment]
You will need to remove commit 00cf7f609c3cfb2d9b7dd36782fdb15ec054e6b4 and rebase.

**Comment by nicolasstucki** [comment]
Maybe no need of rebase

**Comment by biboudis** [comment]
If it is exactly the same code with the same white spaces will that be a
problem? :D

**Comment by nicolasstucki** [comment]
It is not exactly the same code

**Comment by nicolasstucki** [comment]
Your stack is 1/4 smaller, but it was not enough. You will need the fix in #3080.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -2277,4 +2269,18 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
...
+  protected def checkEqualityEvidence(tree: tpd.Tree, pt: Type)(implicit ctx: Context) : Unit = {
+    tree match {
+      case _: RefTree | _: Literal
+        if !isVarPattern(tree) &&
+          !(tree.tpe <:< pt) (ctx.addMode(Mode.GADTflexible)) =>
+        val cmp =
+          untpd.Apply(
+            untpd.Select(untpd.TypedSplice(tree), nme.EQ),
+            untpd.TypedSplice(dummyTreeOfType(pt)))
+        typedExpr(cmp, defn.BooleanType)(ctx.retractMode(Mode.Pattern))
```
Comment (OlivierBlanvillain) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: `retractMode(Pattern)` is redundant (it's removed by `typedExpr`)

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -2277,4 +2269,18 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
       }
     }
   }
+
+  protected def checkEqualityEvidence(tree: tpd.Tree, pt: Type)(implicit ctx: Context) : Unit = {
```
Comment (OlivierBlanvillain) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: /** Check that `tree == x: pt` is typeable. Used when checking a pattern
     *  againts a selector of type `pt`. This implementation accounts for
     *  user-defined definitions of `==`.
     *  Overwritten to no-op in ReTyper.
     */

**Comment by biboudis** [comment]
@OlivierBlanvillain can you give me pointers to debug this stackoverflow with the optimised bootstrapped compiler version?

**Comment by allanrenucci** [comment]
Have you tried with the fix in #3080?

**Comment by biboudis** [comment]
@allanrenucci let's see (although I feel that it is a different error)

**Comment by biboudis** [comment]
Tada! thanks @allanrenucci!
