### PR TITLE
Fix #12729: Don't encode <init> and <clinit> only.

### LINKED ISSUE #12729: Scala 2 regression: free-form names in backticks crash at runtime
## Compiler version
With 3.0.0 (or 3.0.1-RC1 on scastie)

## Minimized code

```Scala
object foo {
  val `<x>` = "hello!"
  def main(args: Array[String]): Unit = println(`<x>`)
}
```

## Output
In scastie this gives:

```
java.lang.ClassFormatError: Method "<x>" in class foo has illegal signature "()Ljava/lang/String;"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
	at sbt.internal.BottomClassLoader.lambda$findClass$0(BottomClassLoader.java:56)
	at sbt.internal.ClassLoadingLock.withLock(ClassLoadingLock.java:29)
	at sbt.internal.BottomClassLoader.findClass(BottomClassLoader.java:51)
	at sbt.internal.BottomClassLoader.loadClass(BottomClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.Run.getMainMethod(Run.scala:150)
	at sbt.Run.execute$1(Run.scala:81)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.TrapExit$App.run(TrapExit.scala:258)
	at java.lang.Thread.run(Thread.java:748)
```

I've also seen it give something like:

```
java.lang.ClassFormatError: Illegal method name "<expr>"
```

## Expectation
Since (fun) names like this worked fine in 2.13, I'd expect them to work fine in 3 too... perhaps they used to be name mangled?

This form in particular using ````<name>```` is useful for giving names to grammar rules in parsers.

### PR DESCRIPTION
**Pull request by mlachkar**
In addition, reject `<init>` and `<clinit>` in the parser, so that
users don't write them in source code.
fixes #12729

### CODE REVIEW

File: tests/neg/i12729.scala [hunk 1]
```diff
@@ -0,0 +1,3 @@
+class Test(i: Int):
+  val `<init>` = "init" // error: Illegal backquoted identifier: `<init>` and `<clinit>` are forbidden
```
Comment (smarter) [inline tests/neg/i12729.scala:2]: You should also test that `class <init>` and `def <init>` are rejected

File: compiler/src/dotty/tools/dotc/core/Names.scala [hunk 2]
```diff
@@ -342,8 +342,8 @@ object Names {
 
     override def encode: SimpleName = {
       val dontEncode =
-        length >= 3 &&
-        head == '<' && last == '>' && isIdentifierStart(apply(1))
+        length >= 6 &&
+        head == '<' && (this == StdNames.nme.CONSTRUCTOR || this == StdNames.nme.STATIC_CONSTRUCTOR)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Names.scala:346]: This can be simplified to just checking if this is CONSTRUCTOR or STATIC_CONSTRUCTOR, the checks for length and head aren't needed anymore.

**Review by smarter — APPROVED** [review]
Otherwise LGTM, but this PR also adds an empty .scalafmt.conf file, is that intentional?

File: compiler/src/dotty/tools/dotc/core/Names.scala (hunk 2 above)
Comment (mlachkar) [reply compiler/src/dotty/tools/dotc/core/Names.scala:346]: you're right! thanks

**Comment by smarter** [comment]
Very minor point but when fixing up a mistake in a previous commit, don't hesitate to squash these commits together and push-force, this makes the git history more readable.
