### PR TITLE
Fix #9439: Translate Java varargs `...T` into `T*` instead of `(T & Object)*`

### LINKED ISSUE #9439: Java interop: Type Mismatch for vararg ...T because "Required: T & Object"
## Minimized code

```scala
object Test {
  // First example with a concrete type <: AnyVal
  def main(args: Array[String]): Unit = {
    val coll = new java.util.ArrayList[Int]()
    java.util.Collections.addAll(coll, 5, 6)
    println(coll.size())
  }

  // Second example with an abstract type not known to be <: AnyRef
  def foo[A](a1: A, a2: A): Unit = {
    val coll = new java.util.ArrayList[A]()
    java.util.Collections.addAll(coll, a1, a2)
    println(coll.size())
  }
}
```

## Output

```
-- [E007] Type Mismatch Error: tests\run\hello.scala:5:39 ----------------------
5 |    java.util.Collections.addAll(coll, 5, 6)
  |                                       ^
  |                                       Found:    (5 : Int)
  |                                       Required: Int & Object
-- [E007] Type Mismatch Error: tests\run\hello.scala:5:42 ----------------------
5 |    java.util.Collections.addAll(coll, 5, 6)
  |                                          ^
  |                                          Found:    (6 : Int)
  |                                          Required: Int & Object
-- [E007] Type Mismatch Error: tests\run\hello.scala:12:39 ---------------------
12 |    java.util.Collections.addAll(coll, a1, a2)
   |                                       ^^
   |                                       Found:    (a1 : A)
   |                                       Required: A & Object
-- [E007] Type Mismatch Error: tests\run\hello.scala:12:43 ---------------------
12 |    java.util.Collections.addAll(coll, a1, a2)
   |                                           ^^
   |                                           Found:    (a2 : A)
   |                                           Required: A & Object
4 errors found
```

## Expectation

I expect that both examples compile.

## Notes

[JavaDoc of `java.util.Collections.addAll`](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#addAll-java.util.Collection-T...-)
```java
public static <T> boolean addAll(Collection<? super T> c, T... elements)
```

This prevents the Scala.js test `CollectionsOnCollectionsTest` from compiling, at the following line:
https://github.com/scala-js/scala-js/blob/6b9f04b0c0531d889235726d8956cb01a4c7476d/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/CollectionsOnCollectionsTest.scala#L146

### PR DESCRIPTION
**Pull request by smarter**
This is much more convenient for users but is more complicated for the
compiler since we still need to translate the varargs into an `Object[]`
in bytecode. Since ElimRepeated was already responsible for doing some
adaptation of repeated arguments, it now also takes care of this (this
differs from Scala 2 which handles this at Erasure).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 1]
```diff
@@ -54,11 +55,22 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
   private def elimRepeated(tp: Type)(using Context): Type = tp.stripTypeVar match
     case tp @ MethodTpe(paramNames, paramTypes, resultType) =>
       val resultType1 = elimRepeated(resultType)
-      val paramTypes1 =
-        if paramTypes.nonEmpty && paramTypes.last.isRepeatedParam then
-          val last = paramTypes.last.translateFromRepeated(toArray = tp.isJavaMethod)
-          paramTypes.init :+ last
-        else paramTypes
+      val paramTypes1 = paramTypes match
+        case init :+ last if last.isRepeatedParam =>
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:59]: This refactoring has the performance consequence that the `init` will always be extracted even if there is no repeat param at the end. Previously, constructing the `init` list would be delayed until we knew there was a repeat param.

Are you OK with that?

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 2]
```diff
@@ -54,11 +55,22 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
+          val isJava = tp.isJavaMethod
+          // A generic Java varargs `T...` is erased to `Object[]` in bytecode,
+          // we directly translate such a type to `Array[_ <: Object]` instead
+          // of `Array[_ <: T]` here. This allows the tree transformer of this phase
+          // to emit the correct adaptation for repeated arguments without
+          // relying on any cast (cf `adaptToArray`).
+          val last1 =
+            if isJava && last.elemType.isInstanceOf[TypeParamRef] then
+              defn.ArrayOf(TypeBounds.upper(defn.ObjectType))
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:68]: If `T` has a bound that is smaller than `Object`, for example `<T extends java.util.List>`, shouldn't this be translated to `Array[_ <: List]` instead of `Array[_ <: Object]`?

As a concrete example: `java.util.Arrays.parallelSort(T[])` has the following signature and descriptor:
```java
  public static <T extends java.lang.Comparable<? super T>> void parallelSort(T[]);
    descriptor: ([Ljava/lang/Comparable;)V
```
(shown by `javap -s java.util.Arrays`)

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: Yeah, I though it was a bit clearer that way but that's a lot of extra allocations indeed, fixed.

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala (hunk 2 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: Right, I simplified that condition too much, we should only to do this translation when T is unbounded (that's the only situation in which we can end up with an array of primitive that will need to be adapted).
