### PR TITLE
Fix #6435: Collect variables in quoted patterns

### LINKED ISSUE #6435: Quoted pattern failing as a val extractor
The following works
```scala
import scala.quoted._
import scala.quoted.matching._
def f(sc: quoted.Expr[StringContext]) given tasty.Reflection: Unit = {
  sc match {
    case '{ StringContext(${ExprSeq(parts)}: _*) } =>
      val ps: Seq[Expr[String]] = parts
  }
}
```
but rewiting it to 
```scala
import scala.quoted._
import scala.quoted.matching._
def f(sc: quoted.Expr[StringContext]) given tasty.Reflection: Unit = {
  val '{ StringContext(${ExprSeq(parts)}: _*) } = sc
  val ps: Seq[Expr[String]] = parts
}
```

fails with
```scala
15 |      val ps: Seq[Expr[String]] = parts
   |                                  ^^^^^
   |                                  Not found: parts
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -1550,6 +1550,14 @@ object desugar {
...
       case Block(Nil, expr) =>
         collect(expr)
+      case Quote(expr) =>
+        new TreeTraverser {
+          def traverse(tree: untpd.Tree)(implicit ctx: Context): Unit = tree match {
+            case Splice(expr) => collect(expr)
+            case TypSplice(expr) => collect(expr)
+            case _ => traverseChildren(tree)
+          }
+        }.traverse(expr)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala]: Why not just `collect(expr)` and handle `Splice` and `TypeSplice` as two cases in the outer match?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: Because everything directly inside of the quote is quoted code that is not part of the pattern (not in pattern mode). It only enters back in pattern mode inside the splices

For example in 
```scala
case '{ StringContext(${ExprSeq(parts2)}: _*) }
```
we use the traverser to traverse the trees `StringContext(XYZ: _*)` and then `collect` on `XYZ`, which in this case is a collect on the pattern `ExprSeq(parts2)` that will collect the variable `parts2`.
