### PR TITLE
Closes #1731 by fixing error message for overloaded method without re…

### LINKED ISSUE #1731: unhelpful error message when overloading apply without return type
`dotty`:
```scala
scala> case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) } 
-- Error: <console> ----------------------------------------------------------------------
6 |case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
  |                                                       ^^^
  |                                                       object Foo does not take parameters
```

The solution is to write `def apply[T](): Foo[T]` but good luck figuring that out from our error message, contrast with `scalac`:
```scala
scala> case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
<console>:15: error: overloaded method apply needs result type
       case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
                                                                 ^
```

### PR DESCRIPTION
**Pull request by bbarker**
This was achieved by adding a more specific conditional to note the specific error and by overloading apply for the already existing `OverloadedOrRecursiveMethodNeedsResultType`. 

While this is an improvement, it is still not quite right, as the error message now behaves like:

```
scala> case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) } 
-- [E043] Syntax Error: <console>:4:55 -----------------------------------------
4 |case class Foo[T](x: T); object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
  |                                                       ^^^
  |                      overloaded or recursive method Foo needs return type
```

To improve beyond this, it seems we would need some way to walk up the tree to get to the LHS (not sure if possible), or, catch it higher up the tree in the first place.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala [hunk 1]
```diff
@@ -1209,20 +1209,29 @@ object messages {
...
           |""".stripMargin
   }
 
+  object OverloadedOrRecursiveMethodNeedsResultType {
+    @specialized def apply[T >: Trees.Untyped](tree: NameTree[T])(implicit ctx: Context)
+    : OverloadedOrRecursiveMethodNeedsResultType =
+      OverloadedOrRecursiveMethodNeedsResultType(tree.name.toString)(ctx)
+    def apply(symbol: Symbol)(implicit ctx: Context)
+    : OverloadedOrRecursiveMethodNeedsResultType =
+      OverloadedOrRecursiveMethodNeedsResultType(symbol.name.toString)(ctx)
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: There's a "Showable" type class that can be accessed for both trees and symbols via `.show`

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala [hunk 2]
```diff
@@ -48,7 +48,7 @@ object ProtoTypes {
 
     private def disregardProto(pt: Type)(implicit ctx: Context): Boolean = pt.dealias match {
       case _: OrType => true
-      case pt => pt.isRef(defn.UnitClass)
+      case ptd => ptd.isRef(defn.UnitClass)
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: Maybe an unnecessary diff?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -1872,8 +1872,6 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
    */
   def adaptInterpolated(tree: Tree, pt: Type, original: untpd.Tree)(implicit ctx: Context): Tree = {
 
-    assert(pt.exists)
-
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Why was this assertion removed?

File: compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala [hunk 4]
```diff
@@ -214,9 +214,25 @@ class ErrorMessagesTests extends ErrorMessagesTest {
...
+//        |object Foo { def apply[T]() = Foo(null.asInstanceOf[T]) }
+//      """.stripMargin
+//    }.expect { (ictx, messages) =>
+//      implicit val ctx: Context = ictx
+//
+//      assertMessageCount(1, messages)
+//      val OverloadedOrRecursiveMethodNeedsResultType(treeName2) :: Nil = messages
+//      assertEquals("Foo", treeName2)
+//    }
+  }
```
Comment (felixmulder) [inline compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala]: This should be fine as it is reported after the front end (of which typer is a part). Why can't this test be enabled?

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala [hunk 5]
```diff
@@ -1320,7 +1329,8 @@ object messages {
            |"""
   }
 
-  case class MethodDoesNotTakeParameters(tree: tpd.Tree, methPartType: Types.Type)(err: typer.ErrorReporting.Errors)(implicit ctx: Context)
+  case class MethodDoesNotTakeParameters(tree: tpd.Tree, methPartType: Types.Type)
+  (err: typer.ErrorReporting.Errors)(implicit ctx: Context)
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: :+1:

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala [hunk 6]
```diff
@@ -1209,20 +1209,29 @@ object messages {
...
           |
-          |Case 2: ${tree} is recursive
-          |If `${tree.name}` calls itself on any path, you need to specify its return type.
+          |Case 2: $termName is recursive
+          |If `$termName` calls itself on any path, you need to specify its return type.
           |""".stripMargin
   }
 
+  object OverloadedOrRecursiveMethodNeedsResultType {
+    @specialized def apply[T >: Trees.Untyped](tree: NameTree[T])(implicit ctx: Context)
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: No need for the `@specialized` annotation, Dotty will have its own form of specialization that does not require the annotation. Also, the bootstrapped compiler currently doesn't do anything for `@specialized`.

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala [hunk 7]
```diff
@@ -1209,20 +1209,29 @@ object messages {
            |""".stripMargin
   }
 
-  case class OverloadedOrRecursiveMethodNeedsResultType(tree: Names.TermName)(implicit ctx: Context)
+  case class OverloadedOrRecursiveMethodNeedsResultType private (termName: String)(implicit ctx: Context)
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: Why make the name private? If you're an IDE, wouldn't you want to be able to extract the name from the message?

File: compiler/src/dotty/tools/dotc/core/Contexts.scala [hunk 8]
```diff
@@ -126,7 +126,7 @@ object Contexts {
     protected def sstate_=(sstate: SettingsState) = _sstate = sstate
     def sstate: SettingsState = _sstate
 
-    /** The current tree */
+    /** The current compilation unit */
```
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/core/Contexts.scala]: :heart:

File: compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala (hunk 4 above)
Comment (felixmulder) [inline compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala]: I cloned your branch and tried out the commented out test - and it runs fine for me. Did you do `git submodule update --init`?

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala (hunk 2 above)
Comment (bbarker) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: the 'case' pt shadows the outer pt, which may not be an issue here, but could crop up later if the function became more complex, I suppose. Happy to take it out though.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 3 above)
Comment (bbarker) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Wow, I don't know - it shouldn't have been, sorry that typo slipped through.

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala (hunk 6 above)
Comment (bbarker) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: :+1:

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala (hunk 7 above)
Comment (bbarker) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: My thought was to prevent accidental use that might happen by passing in a string directly; I may not understand all the implications, but even with private it seems I can still extract the string in `ErrorMessagesTests.scala`:

```
      val OverloadedOrRecursiveMethodNeedsResultType(treeName) :: Nil = messages
      assertEquals("i", treeName)
```
Seems to work

**Comment by bbarker** [comment]
I'm thinking about revising the commit message to "fixes for #1731" instead of "closes", and just update the issue. I'll plan to come back to it soon for a full fix.

File: compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala (hunk 4 above)
Comment (bbarker) [inline compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala]: Hmm, I thought I did but can't quite remember exactly which submodule command I originally ran. I tried this but it didn't make a difference. I'll uncomment for now and try to figure out my issue later.

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala (hunk 7 above)
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: Hmm, I did correct this before having coffee. Ignore this comment, it's just the constructor marked private, not the members ☕️

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala (hunk 2 above)
Comment (felixmulder) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: I think the point here is to specifically shadow it, we do this all over the compiler :)

File: compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala (hunk 4 above)
Comment (felixmulder) [inline compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala]: Submit it uncommented and we'll see what the CI says :smile:

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala (hunk 2 above)
Comment (bbarker) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: :+1:

File: compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala (hunk 4 above)
Comment (bbarker) [inline compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala]: Will do, I'm getting a number of failures from `sbt test` so will see how this compares.

**Comment by felixmulder** [comment]
Looks like it ran just fine - except that the test fails with:

```
recursiveMethodNeedsReturnType failed:
org.junit.ComparisonFailure: expected:<[i]> but was:<[def i = i + 5]>

// and
overloadedMethodNeedsReturnType failed:
org.junit.ComparisonFailure: expected:<[foo]> but was:<[def foo(i: Int) = foo(i.toString)]>
```

hint:

```scala
tree.show      // string of tree as "scala-like" code
tree.name.show // string of name without encodings
```

**Comment by bbarker** [comment]
Thanks again for the review ,and the help. I reviewed the dotty build instructions and started afresh on another system; I think the `--recursive` option may have been needed for `git submodule update --init`; also I don't think I ran `sbt managedSources` previously, which (may) have been causing other tests to fail.

Unfortunately, I still get the error for this test as originally reported in #1731, and now I seem to have managed (by means unknown) to have gotten the build system to replicate the issue:


```
[info] Test dotty.tools.dotc.reporting.ErrorMessagesTests.traitMayNotBeFinal started
[info] Test dotty.tools.dotc.reporting.ErrorMessagesTests.overloadedMethodNeedsReturnType started
[error] Test dotty.tools.dotc.reporting.ErrorMessagesTests.overloadedMethodNeedsReturnType failed: java.lang.AssertionError: assertion failed: denotation module _root_ invalid in run 2. ValidFor: Period(1..2, run = 3), took 0.023 sec
[error]     at scala.Predef$.assert(Predef.scala:170)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.bringForward(Denotations.scala:727)
[error]     at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:783)
[error]     at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:406)
[error]     at dotty.tools.dotc.core.Symbols$Symbol.isType(Symbols.scala:429)
[error]     at dotty.tools.dotc.core.Scopes$MutableScope.enter(Scopes.scala:270)
[error]     at dotty.tools.dotc.Compiler.rootContext(Compiler.scala:134)
[error]     at dotty.tools.DottyTest$class.checkCompile(DottyTest.scala:60)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTests.checkCompile(ErrorMessagesTests.scala:14)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTest$class.checkMessagesAfter(ErrorMessagesTest.scala:60)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTests.checkMessagesAfter(ErrorMessagesTests.scala:14)
[error]     at dotty.tools.dotc.reporting.ErrorMessagesTests.overloadedMethodNeedsReturnType(ErrorMessagesTests.scala:222)
[error]     ...
[info] Test dotty.tools.dotc.reporting.ErrorMessagesTests.expectedClassOrObjectDef started
[info] Test dotty.tools.dotc.reporting.ErrorMessagesTests.methodDoesNotTakeMorePrameters started
[info] Test dotty.tools.dotc.reporting.ErrorMessagesTests.missingTypeParameter started
[info] Test dotty.tools.dotc.reporting.ErrorMessagesTests.typeDoesNotTakeParameters started

**Comment by felixmulder** [comment]
That's great, I should be able to reproduce it now!

**Comment by felixmulder** [comment]
#3254 should have fixed your issue! :)

**Comment by bbarker** [comment]
Thanks @felixmulder - looks like CI is happy now

**Comment by felixmulder** [comment]
@bbarker it does indeed! I'm sorry this fell through the cracks, I went on vacation and simply haven't gotten around to merging this until today.

So, again, sorry for the belated merge, and thanks a bunch for contributing! :tada:
