### PR TITLE
Fix all REPL tests when production behavior is enabled

### LINKED ISSUE #25445: Fix scala3-repl tests to match production behavior
#25444 adds a way to disable the dangerous "try-catch-fallback" pattern from `Rendering` in tests, except it causes a ton of tests to fail, and I don't have time to fix them before shipping that workaround, so this issue tracks fixing them by enabling `-Ydebug` in the compiler options for `scala3-repl`.

### PR DESCRIPTION
**Pull request by SolalPirelli**
~Depends on #25444~

Fixes #25445

## How much have your relied on LLM-based tools in this contribution?

not

## How was the solution tested?

existing tests

### CODE REVIEW

File: repl/test-resources/repl/i7644 [hunk 1]
```diff
@@ -13,5 +13,5 @@ scala> class T extends CanEqual
   |       Cannot extend sealed trait CanEqual in a different source file
   |
   | longer explanation available when compiling with `-explain`
+2 warnings found
```
Comment (SolalPirelli) [inline repl/test-resources/repl/i7644]: see the change below for why this happens but we don't print the warnings

**Comment by SolalPirelli** [comment]
@hamzaremmal I'm interested in your thoughts on the 2nd commit.

**Comment by SolalPirelli** [comment]
@hamzaremmal I've removed the 2nd commit, will probably reintroduce it in a later PR simplifying Vulpix in general, but I want to get the fixes to REPL tests in first

**Comment by hamzaremmal** [comment]
> @hamzaremmal I'm interested in your thoughts on the 2nd commit.

For the record, we discussed it over Slack.

**Comment by hamzaremmal** [comment]
> @hamzaremmal I've removed the 2nd commit, will probably reintroduce it in a later PR simplifying Vulpix in general, but I want to get the fixes to REPL tests in first

In this case, I think your second commit had some merits. It added the `com.lihaoyi` properties to the classpath. I believe we should do that but just hold on the other changes. No need to query the classpath and filter it yet. (What I said here: https://github.com/scala/scala3/pull/25444/changes#r2895927959)

**Comment by SolalPirelli** [comment]
The com.lihaoyi additions in #25444 were merged so I'm not sure I understand what you mean

**Comment by hamzaremmal** [comment]
Right, sorry sorry. I lost track of what was done where. Let me check again the full context and I'll approve it if it all seems ok.

File: repl/test/dotty/tools/repl/ReplTest.scala [hunk 2]
```diff
@@ -100,7 +100,10 @@ extends ReplDriver(options, new PrintStream(out, true, StandardCharsets.UTF_8.na
         out.linesIterator.foreach(buf.append)
         nstate
       }
-      (optsLine :: buf.toList).filter(nonBlank)
+      // We run the repl with `-Ydebug` to not use the fallback if there's a class load exception so we can notice these,
+      // but as a consequence we get debug messages; ignore the stale symbol one, whose contents include symbol IDs
+      // that depend on the exact compiler.
+      (optsLine :: buf.toList).filter(nonBlank).filter(!_.startsWith("stale symbol;"))
```
Comment (hamzaremmal) [inline repl/test/dotty/tools/repl/ReplTest.scala]: Mmmh, this feels like a hack, why remove an error that was effectively produced? We should either fix it if it was not supposed to be produced or keep it, but hiding it is not a good idea in my opinion.

File: repl/test-resources/repl/i7644 (hunk 1 above)
Comment (hamzaremmal) [reply repl/test-resources/repl/i7644]: if it's about the stale symbol, I believe it should be fixed.

File: repl/test/dotty/tools/repl/ReplTest.scala (hunk 2 above)
Comment (SolalPirelli) [reply repl/test/dotty/tools/repl/ReplTest.scala]: yeah, it's preexisting, it was just hidden before because we didn't run with -Ydebug. I'm not sure if it's fixable since we are, by design, creating a symbol with the same name twice, so isn't it normal that we end up with funny things?

Comment (hamzaremmal) [reply repl/test/dotty/tools/repl/ReplTest.scala]: I don't think so. We might create the same symbol twice but during different run of the compiler, right?
Anyways, it's either we can do it then we should not have a stale symbol because the compiler knows how to handle it (it's part of it's business logic: "we can redefine symbols in the same REPL session") or we cannot do it then we should have a proper error saying "you cannot redefine this symbol during the same REPL session". This feels like it's in the middle of both possibilities; allowing you to redefine but at the same time the compiler is not very happy.

Comment (SolalPirelli) [reply repl/test/dotty/tools/repl/ReplTest.scala]: yeah that's true, I'll be less lazy and try to actually fix it

**Comment by SolalPirelli** [comment]
@hamzaremmal Fixed, at some cost to my sanity. Turns out we were not propagating the new `State` in case of errors, so the next executed line used the same index for the result value name (`resX`) and unsurprisingly that causes funny things to happen.

Also I deleted `results.scala` because it was a poor attempt at abstracting `Either` that no longer works once you have to sometimes also propagate the state on error.

There's plenty more that could be cleaned up in the REPL, or for starters in the compiler (why are we hardcoding behavior for the REPL in the compiler??), but tests passing will do for now.

File: repl/test-resources/repl/errmsgs [hunk 3]
```diff
@@ -90,10 +90,11 @@ scala> val x: List[Int] = "foo" :: List(1)
   | longer explanation available when compiling with `-explain`
 1 error found
 scala> while (((  foo ))) {}
--- [E006] Not Found Error: -----------------------------------------------------
+-- [E007] Type Mismatch Error: -------------------------------------------------
```
Comment (SolalPirelli) [inline repl/test-resources/repl/errmsgs:93]: we define it in the previous command...

**Comment by hamzaremmal** [comment]
> @hamzaremmal Fixed, at some cost to my sanity.

I very much understand what you are saying :disappointed:

> There's plenty more that could be cleaned up in the REPL, or for starters in the compiler (why are we hardcoding behavior for the REPL in the compiler??), but tests passing will do for now.

The REPL was until recently shipped in the same artifact as the compiler. We have just recently split it and it still needs A LOT of work to fully split the business logic.

File: repl/test-resources/repl/errmsgs (hunk 3 above)
Comment (hamzaremmal) [reply repl/test-resources/repl/errmsgs:93]: Indeed

**Comment by SolalPirelli** [comment]
tbh the repl should be a good use case to "validate" the compiler API... if you can't easily implement a REPL, the compiler API needs work :)

File: repl/test-resources/repl/i6474 [hunk 4]
```diff
@@ -15,10 +15,10 @@ scala> (1, 2): Foo3.T[Int][Int]
   |         Missing type parameter for Foo3.T[Int][Int]
 1 error found
 scala> ((1, 2): Foo3.T[Int][Int][Int]): Foo3.T[Any][Int][Int]
-val res2: Foo3.T[Any][Int][Int] = (1, 2)
+val res3: Foo3.T[Any][Int][Int] = (1, 2)
```
Comment (hamzaremmal) [inline repl/test-resources/repl/i6474:18]: So the basis of the fix is propagating the new state which makes indices increment even on errors.
As I see it, it's a fix but not the root cause probably. The context (the compiler's) and ofc the name table is still polluted. My question now is: what happens if we refer to `res2` (a not found??)?

File: repl/test-resources/repl/importFromObj [hunk 5]
```diff
@@ -14,7 +14,7 @@ scala> buf += xs
   | longer explanation available when compiling with `-explain`
 1 error found
 scala> buf ++= xs
-val res0: mutable.ListBuffer[Int] = ListBuffer(1, 2, 3)
+val res1: mutable.ListBuffer[Int] = ListBuffer(1, 2, 3)
```
Comment (hamzaremmal) [inline repl/test-resources/repl/importFromObj:17]: I imagine all of those will be the same comment I made above.

**Comment by hamzaremmal** [comment]
> tbh the repl should be a good use case to "validate" the compiler API... if you can't easily implement a REPL, the compiler API needs work :)

Agreed!

File: repl/test-resources/repl/i6474 (hunk 4 above)
Comment (SolalPirelli) [reply repl/test-resources/repl/i6474:18]: it prints the error itself, which is kind of interesting:

```
scala> 42 + java.lang.Integer.TYPE
-- [E134] Type Error: ----------------------------------------------------------
1 |42 + java.lang.Integer.TYPE
  |^^^^
  |None of the overloaded alternatives of method + in class Int with types
  | (x: Double): Double
  | (x: Float): Float
  | (x: Long): Long
  | (x: Int): Int
  | (x: Char): Int
  | (x: Short): Int
  | (x: Byte): Int
  | (x: String): String
  |match arguments ((Integer.TYPE : Class[Integer]))
1 error found

scala> 44
val res3: Int = 44

scala> res2
-- [E134] Type Error: ----------------------------------------------------------
1 |res2
  |^^^^
  |None of the overloaded alternatives of method + in class Int with types
  | (x: Double): Double
  | (x: Float): Float
  | (x: Long): Long
  | (x: Int): Int
  | (x: Char): Int
  | (x: Short): Int
  | (x: Byte): Int
  | (x: String): String
  |match arguments ((Integer.TYPE : Class[Integer]))
1 error found
```

Comment (SolalPirelli) [reply repl/test-resources/repl/i6474:18]: (I wouldn't enshrine this into a test though, I don't think anyone should rely on this... for now at least)

Comment (hamzaremmal) [reply repl/test-resources/repl/i6474:18]: Mmmh, so this is not what we want to have obviously but the proposed fix brings it closer to what we would like to have (at least the test suite behaves correctly). I'm inclined to approve this but only if we dig further to check how we can rollback the changes in the context (compiler's `Context`).

Now, I find this funny because what would happen if we define a value class, say `class Foo` and add an expression that is broken afterwards (in the same cycle). Can we still use that same class in the next run of the REPL? Would it also show the error or do we just have something that is half working (`Foo` works and `resX` shows the error)?

Comment (SolalPirelli) [reply repl/test-resources/repl/i6474:18]: these are good question and I encourage you to create an issue for them, but let's please solve one problem at a time so we don't keep PRs open forever :-)

Comment (hamzaremmal) [reply repl/test-resources/repl/i6474:18]: > these are good question and I encourage you to create an issue for them, but let's please solve one problem at a time so we don't keep PRs open forever :-)

We are not, I just want to understand what I'm approving. 

> I'm inclined to approve this but only if we dig further to check how we can rollback the changes in the context (compiler's Context).

I didn't mean here to say to do it right now, as long as we have an issue that highlights all of these problems, I'll approve the PR since it brings it closer to what we want.

Comment (SolalPirelli) [reply repl/test-resources/repl/i6474:18]: @hamzaremmal ping on clicking approve? 😇

Comment (hamzaremmal) [reply repl/test-resources/repl/i6474:18]: I thought you will create the issue first.

Comment (hamzaremmal) [reply repl/test-resources/repl/i6474:18]: #25514
