### PR TITLE
Fix #4659: disallow reference to object itself in super calls

### LINKED ISSUE #4659: Weird dependent class instantiation crashes with java.lang.VerifyError: Bad type on operand stack
```scala
sbt:dotty> repl
[info] Running (fork) dotty.tools.repl.Main -classpath dotty/library/target/scala-2.12/dotty-library_2.12-0.9.0-bin-SNAPSHOT-nonbootstrapped.jar

scala> class A(val a:A)(val b:a.T){type T}
// defined class A

scala> object a0 extends A(a0)(0){type T = Int}
// defined object a0

scala> new A(a0)(1)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    rs$line$5$a0$.<init>()V @6: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'rs$line$4$A
  Current Frame:
    bci: @6
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { uninitializedThis, uninitializedThis, 'java/lang/Integer }
  Bytecode:
    0x0000000: 2a2a 03b8 0017 b700 1a2a b300 1cb1

	at rs$line$6$.<init>(rs$line$6:1)
	at rs$line$6$.<clinit>(rs$line$6)
	at rs$line$6.res0(rs$line$6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.repl.Rendering.$anonfun$valueOf$2(Rendering.scala:57)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:57)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:86)
	at dotty.tools.repl.ReplDriver.$anonfun$displayDefinitions$8(ReplDriver.scala:288)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dotty.tools.repl.ReplDriver.displayMembers$1(ReplDriver.scala:288)
	at dotty.tools.repl.ReplDriver.$anonfun$displayDefinitions$15(ReplDriver.scala:315)
	at scala.Option.map(Option.scala:146)
	at dotty.tools.repl.ReplDriver.$anonfun$displayDefinitions$13(ReplDriver.scala:313)
	at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:26)
	at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:36)
	at dotty.tools.dotc.core.Phases.atPhase$(Phases.scala:35)
	at dotty.tools.dotc.core.Contexts$Context.atPhase(Contexts.scala:71)
	at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:308)
	at dotty.tools.repl.ReplDriver.$anonfun$compile$2(ReplDriver.scala:245)
	at scala.util.Either.fold(Either.scala:188)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:236)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:203)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:150)
	at dotty.tools.repl.ReplDriver.$anonfun$runUntilQuit$1(ReplDriver.scala:154)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:192)
	at dotty.tools.repl.ReplDriver.$anonfun$withRedirectedOutput$1(ReplDriver.scala:163)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:163)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:163)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:154)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #4659: disallow reference to object itself in super calls

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/util/SourcePosition.scala [hunk 1]
```diff
@@ -70,7 +70,7 @@ extends interfaces.SourcePosition with Showable {
 }
 
 /** A sentinel for a non-existing source position */
-@sharable object NoSourcePosition extends SourcePosition(NoSource, NoSpan) {
+@sharable object NoSourcePosition extends SourcePosition(NoSource, NoSpan, null) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/util/SourcePosition.scala]: How come this code worked in Scala 2 ? Can we try to emulate their behavior ?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/util/SourcePosition.scala]: Scala 2 behavior is incorrect, as the test case `tests/run/i4659b.scala` shows.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/util/SourcePosition.scala]: How is it incorrect ? `tests/run/i4659b.scala` compiles and runs without errors on Scala 2.12.8

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/util/SourcePosition.scala]: In `tests/run/i4659b.scala`, `NoSourcePosition` is used as a default value before it is initialized.   It should not compile.

While rejecting `tests/run/i4659b.scala` is currently out of reach, we can do better than Scala2 by rejecting `tests/neg/i4659b.scala` .

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 2]
```diff
@@ -783,6 +783,19 @@ trait Checking {
       else if (called.is(Trait) && !caller.mixins.contains(called))
         ctx.error(i"""$called is already implemented by super${caller.superClass},
                    |its constructor cannot be called again""", call.sourcePos)
+
+      if (caller.is(Module)) {
+        val objRef = caller.sourceModule.termRef
+        val traverser = new TreeTraverser {
+          def traverse(tree: Tree)(implicit ctx: Context) = tree match {
+            case tree: RefTree if tree.isTerm && tree.tpe <:< objRef =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]: You can avoid the subtype check here:
```suggestion
            case tree: RefTree if tree.isTerm && (tree.tpe.widen.classSymbol eq caller) =>
```

File: compiler/src/dotty/tools/dotc/util/SourcePosition.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/util/SourcePosition.scala]: I see, then we should leave a comment in `tests/run/i4659b.scala` to say that we'd like this to not compile eventually.

File: compiler/src/dotty/tools/dotc/typer/Checking.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: Avoiding subtype check will ignore the prefix to the object, which might be problematic if the object is nested inside classes.

However, I couldn't find a valid program that exploits the prefix,  so maybe it's safe to do the optimization.
