### PR TITLE
Fix #4364: Try SAM type when no candidates are found

### LINKED ISSUE #4364: SAM types + Overloading + Eta-expansion
The following code snippet fails to compile with Dotty. (Works with scalac)
```scala
class Test {
  def println(): Unit = ()
  def println(x: String): Unit = ()

  def foo(x: java.util.function.Consumer[String]) = 1
  foo(println(_))      // ok
  foo(x => println(x)) // ok
  foo(println)         // error
}
```
```scala
-- [E007] Type Mismatch Error: tests/allan/Test.scala:26:6 ---------------------
26 |  foo(println)
   |      ^^^^^^^
   |      found:    Unit
   |      required: java.util.function.Consumer[String]
   |      
one error found
```

### PR DESCRIPTION
**Pull request by odersky**
For overloading resolution, try a SAM type when no candidates are found.

Also, issue a warning when eta-expanding to a SAM type without a @FunctionalInterface 
annotation.

Based on #4821

### CODE REVIEW

File: tests/neg/i2033.scala [hunk 1]
```diff
@@ -3,7 +3,7 @@ import collection._
 object Test {
   def check(obj: AnyRef): Unit = {
     val bos = new ByteArrayOutputStream()
-    val out = new ObjectOutputStream(println) // error
+    val out = new ObjectOutputStream(println)
```
Comment (adriaanm) [inline tests/neg/i2033.scala]: I guess the overload is now resolved, but it's still a warning (`OutputStream is not @FunctionalInterface`), right?

Comment (odersky) [reply tests/neg/i2033.scala]: Yes, you get:

```
6 |    val out = new ObjectOutputStream(println)
  |                                     ^^^^^^^
  |method println is eta-expanded even though java.io.OutputStream does not have the @FunctionalInterface annotation.
```

**Comment by adriaanm** [comment]
Oh, one more semi-related question to eta-expansion of 0-argument methods. Is https://github.com/lampepfl/dotty/issues/2570#issuecomment-306202339 still the intended spec? 

Especially this part:
> If the expected type is of the form () => T, we eta expand.

does not seem to be implemented in https://github.com/dotty-staging/dotty/blob/master/compiler/src/dotty/tools/dotc/typer/Typer.scala#L2491-L2503

We're discussing this over in https://github.com/scala/scala/pull/6475.
