### PR TITLE
Fix #11061: stop accidentally supported auto-tupling for case classes

### LINKED ISSUE #10958: MatchError in PatternMatcher$Translator.matchArgsPatternPlan
## Minimized code

Affects `3.0.0-M3`

```Scala
object U:
  def unapply(s:String) = Tuple(s) // specifying the type :Tuple1[String] fixes the issue

object Tst extends App:
  "" match
    case s"${U(u)})" =>
```

## Output (click arrow to expand)
<details>

```scala
sbt:dotty-simple> compile
[info] compiling 1 Scala source to /Users/vletal/Workspace/Personal/adventofcode/Scadvent Of Code/target/scala-3.0.0-M3/classes ...
[success] Total time: 0 s, completed Dec 31, 2020 11:42:38 AM
sbt:dotty-simple> compile
[info] compiling 1 Scala source to /Users/vletal/Workspace/Personal/adventofcode/Scadvent Of Code/target/scala-3.0.0-M3/classes ...
[info] exception occurred while compiling /Users/vletal/Workspace/Personal/adventofcode/Scadvent Of Code/src/main/scala/AC21.scala
scala.MatchError: List() (of class scala.collection.immutable.Nil$) while compiling /Users/vletal/Workspace/Personal/adventofcode/Scadvent Of Code/src/main/scala/AC21.scala
[error] ## Exception when compiling 2 sources to /Users/vletal/Workspace/Personal/adventofcode/Scadvent Of Code/target/scala-3.0.0-M3/classes
[error] scala.MatchError: List() (of class scala.collection.immutable.Nil$)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsPatternPlan$1(PatternMatcher.scala:260)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsSelectorsPlan$2(PatternMatcher.scala:255)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsPlan$1(PatternMatcher.scala:266)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.unapplyPlan$3$$anonfun$2(PatternMatcher.scala:338)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.letAbstract(PatternMatcher.scala:107)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.unapplyPlan$1(PatternMatcher.scala:366)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.patternPlan(PatternMatcher.scala:401)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsPatternPlan$1(PatternMatcher.scala:261)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsSelectorsPlan$2(PatternMatcher.scala:255)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsSelectorsPlan$1$$anonfun$1(PatternMatcher.scala:254)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.letAbstract(PatternMatcher.scala:107)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsSelectorsPlan$2(PatternMatcher.scala:254)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchArgsPlan$1(PatternMatcher.scala:266)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchElemsPlan$1(PatternMatcher.scala:276)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.unapplySeqPlan$1(PatternMatcher.scala:302)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.$anonfun$9(PatternMatcher.scala:355)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.letAbstract(PatternMatcher.scala:107)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.unapplyPlan$3$$anonfun$2(PatternMatcher.scala:355)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.letAbstract(PatternMatcher.scala:107)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.unapplyPlan$1(PatternMatcher.scala:366)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.patternPlan(PatternMatcher.scala:401)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.caseDefPlan(PatternMatcher.scala:437)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchPlan$$anonfun$2$$anonfun$1(PatternMatcher.scala:444)
[error] scala.collection.immutable.List.foldRight(List.scala:352)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchPlan$$anonfun$1(PatternMatcher.scala:444)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.letAbstract(PatternMatcher.scala:107)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.matchPlan(PatternMatcher.scala:445)
[error] dotty.tools.dotc.transform.PatternMatcher$Translator.translateMatch(PatternMatcher.scala:1011)
[error] dotty.tools.dotc.transform.PatternMatcher.transformMatch(PatternMatcher.scala:41)
[error] dotty.tools.dotc.transform.MegaPhase.goMatch(MegaPhase.scala:779)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:369)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:429)
[error] dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:439)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:362)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:429)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:256)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:437)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:382)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:385)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:429)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:448)
[error] dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:460)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:185)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:195)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:203)
[error] scala.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:210)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:146)
[error] dotty.tools.dotc.Run.compile(Run.scala:130)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:173)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:171)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:458)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:413
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:498)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:400)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:165)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2176)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2133)
[error] sbt.internal.io.Retry$.apply(Retry.scala:40)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2129)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) scala.MatchError: List() (of class scala.collection.immutable.Nil$)
[error] Total time: 0 s, completed Dec 31, 2020 11:42:42 AM
sbt:dotty-simple> 
```
</details>

### LINKED ISSUE #11061: Incorrectly supported auto-tupling for case classes
## Minimized code

```Scala
case class Foo(a: Int, b: Int)

object Test {
  def foo(x: Foo) = List(x).map(_ + _)
  
  def main(args: Array[String]): Unit = println(foo(Foo(3, 4)))
}
```

## Output

The code compiles and runs.

## Expectation

The code should be rejected, as in Scala 2.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #11061: stop accidentally supported auto-tupling for case classes

This commit refactor the PR #5259 so that it will not impact pattern
matching code.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -111,21 +111,23 @@ object Applications {
...
-    }
-    def genTupleSelectors(n: Int, tp: Type): List[Type] = tp match {
-      case tp: AppliedType if !defn.isTupleClass(tp.tycon.typeSymbol) && tp.derivesFrom(defn.PairClass) =>
-        val List(head, tail) = tp.args
-        head :: genTupleSelectors(n, tail)
-      case _ => tupleSelectors(n, tp)
-    }
-    genTupleSelectors(0, tp)
+    val sels = for (n <- Iterator.from(0)) yield extractorMemberType(tp, nme.selectorName(n), errorPos)
+    sels.takeWhile(_.exists).toList
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:115]: This take while seems a bit fragile. We know how may products exist and can tabulate it directly.
```scala
List.tabulate(Definitions.MaxTupleArity) { n =>
  extractorMemberType(tp, nme.selectorName(n), errorPos)
}
```

File: library/src/scala/Tuple.scala [hunk 2]
```diff
@@ -199,7 +199,7 @@ object Tuple {
   def apply(): EmptyTuple = EmptyTuple
 
   /** Tuple with one element */
-  def apply[T](x: T): T *: EmptyTuple = Tuple1(x)
+  def apply[T](x: T): Tuple1[T] = Tuple1(x)
```
Comment (nicolasstucki) [inline library/src/scala/Tuple.scala:202]: The root of the issue seems to be that pattern matcher looks at `TupleN` but not `*:`. We should probably fix that instead. We are not supposed to use `Tuple1` explicitly as in the distant this might just be an erasure detail.

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

File: library/src/scala/Tuple.scala (hunk 2 above)
Comment (liufengyun) [reply library/src/scala/Tuple.scala:202]: For pattern matcher, the specification requires `_N` to be present. It's not clear how to improve the specification to support `*:` without complicating things.

Actually, I think it might be a feature creep, I am not sure if it should be supported. The representation of tuples as `*:` is an implementation detail. The users stay with `(a, b, c, ...)`, which desugars to `TupleN`, which in turn extends `*:`.

Comment (liufengyun) [reply library/src/scala/Tuple.scala:202]: I think we can create an issue to discuss whether support `*:` and how to support it as `unapply` result type. WDYT?

Comment (nicolasstucki) [reply library/src/scala/Tuple.scala:202]: Yes. Because the idea of having generic tuples is to not rely on `TupleN` anymore.  At some point in the future we plan to remove `TupleN[X1, ...]` and only use `(X1, ...)` or `X1 *: ...`. Then we will only rely on the `unapply` with `*:`.

Comment (liufengyun) [reply library/src/scala/Tuple.scala:202]: Just created #11008.

Comment (liufengyun) [reply library/src/scala/Tuple.scala:202]: BTW, this PR also discovered some accidentally supported usage that should be invalid (see the changes):

- `tests/pos/i6199a.scala`
- `scala3doc/src/dotty/renderers/MemberRenderer.scala `

**Comment by liufengyun** [comment]
@nicolasstucki: is this one ready to go, given that there is no consensus on #11008?

**Comment by liufengyun** [comment]
@nicolasstucki Can we merge this as it fixes #10958 and accidentally supported language features:

- `tests/pos/i6199a.scala`
- `scala3doc/src/dotty/renderers/MemberRenderer.scala `

Then we can think about how to support the new feature in #11008 .

**Comment by nicolasstucki** [comment]
Why not fix #11008. If we merge this one we would need to open an extra issue to revert the `X *: EmptyTuple` -> `Tuple1[X]` change. Seems unnecessarily complicated. This new issue would affect code than #10958.

**Comment by liufengyun** [comment]
> we would need to open an extra issue to revert the `X *: EmptyTuple` -> `Tuple1[X]` change.

We can revert that line of change in this PR and add it as a neg test.

The rationale for merging this is that it fixes another important issue #11061: the accidentally supported auto-untupling of case classes.

- `tests/pos/i6199a.scala`
- `scala3doc/src/dotty/renderers/MemberRenderer.scala `

The code changes of this PR mainly target the bug #11061.

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
@liufengyun there is a small conflict with master
