### PR TITLE
Fix #4730,#6992: Detect scope extrusions in `quoted.run` and fail-fast

### LINKED ISSUE #4730: Exception when running inner quote
```scala
import scala.quoted._

object Test {
  implicit val toolbox: scala.quoted.Toolbox = scala.quoted.Toolbox.make(getClass.getClassLoader)
  val ret: Expr[Int => Int] = '{ (x: Int) => ${ val z = run('{x + 1}); z.toExpr } }
  def main(args: Array[String]): Unit = {
    println(run(ret).apply(10))
  }
}
```

fails when running with:

```scala
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:40)
	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
Caused by: java.lang.IllegalArgumentException: Could not find proxy for x: Int in List(val x, method $anonfun, method apply, class Generated$Code$From$Quoted, module class <root>), encl = method apply, owners = method apply, class Generated$Code$From$Quoted, package <root>; enclosures = method apply, class Generated$Code$From$Quoted, package <root>
	at dotty.tools.dotc.transform.LambdaLift$Lifter.searchIn$1(LambdaLift.scala:381)
	at dotty.tools.dotc.transform.LambdaLift$Lifter.proxy(LambdaLift.scala:394)
	at dotty.tools.dotc.transform.LambdaLift$Lifter.proxyRef(LambdaLift.scala:412)
	at dotty.tools.dotc.transform.LambdaLift.transformIdent(LambdaLift.scala:526)
	at dotty.tools.dotc.transform.MegaPhase.goIdent(MegaPhase.scala:551)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:225)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:228)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:270)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
	at dotty.tools.dotc.transform.MegaPhase.transformTrees$$anonfun$1(MegaPhase.scala:420)
	at scala.collection.immutable.List.mapConserve(List.scala:179)
	at dotty.tools.dotc.transform.MegaPhase.transformTrees(MegaPhase.scala:420)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:271)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
	at dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:245)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:248)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:404)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
	at scala.collection.immutable.List.mapConserve(List.scala:179)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)

```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala [hunk 1]
```diff
@@ -15,8 +15,17 @@ object ToolboxImpl {
...
     def run[T](exprBuilder: QuoteContext => Expr[T]): T = synchronized {
-      driver.run(exprBuilder, settings)
+      try {
+        if (running) // detected nested run
+          throw new scala.quoted.Toolbox.ToolboxAlreadyRunning()
+        running = true
+        driver.run(exprBuilder, settings)
+      } finally {
+        running = false
+      }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: The documentation on the method `run` already says nested `run` is not supported, while this fix seems to suggest that nesting is fine if different toolboxes are used.

As the usage of nesting violates the protocol, I think an improvement of the documentation might be enough.

File: compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala [hunk 2]
```diff
@@ -20,14 +22,25 @@ object ToolboxImpl {
...
       }
     }
+  }
 
+  type ScopeId = Int
+
+  private[dotty] def checkScopeId(id: ScopeId) given Context: Unit = {
+    if (id != scopeId)
+      throw new Toolbox.RunScopeException
   }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: The approach to check scope extrusion seems to be too ad-hoc, and it only addresses the tip of a hard iceberg problem. I'm not sure if it's a win given the complication of the code.

Can we just make it clear that never use `run` in macros in the documentation for `run`?

/cc: @anatoliykmetyuk

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: Documentation is too weak for such things. If a user does a wrong thing, the compiler should tell them what exactly they did wrong.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: If it's something that can be effectively checked, then the compiler should perform the check. However, in programming there are so many properties and contracts that cannot be effectively checked by the compiler and have to be defined via documentation.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: Some prominent protocols not enforced by the compiler I worked with were the actor model, the http model, machine learning models, purely functional style and OOP patterns. Others were Scala 2 macros, SBT and Slick SQL library. The former group are the "laws of physics" you live by and the latter are the building blocks with which you try to build a building under the given laws of physics.

Weird physics can be fun, but if each building block is different and blows up under its own conditions and in its own way, it gets painful. Often we don't choose the rules of the game, but I believe that our responsibility is to manufacture reliable tools with which the given game can be played most efficiently. As a minimum it implies tools with no surprises (such as an obscure exception if you do something that is not in the free-form docs).

> Can we just make it clear that never use run in macros

That sounds like a simple enough protocol to be encoded. Otherwise it warrants a discussion on how to make `run` reliable (possibly trading power for reliability), not a guide on how to live with its surprises.

File: compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: It is the other fix that catches issues of nesting with different toolboxes.

File: compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: The way the check is implemented is quite ad-hoc but it will catch any attempt of using and Expr is a different instance of the compiler. Those crash the compiler in various and unexpected ways.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: It is only intended for scope extrusions in a `run`. Other kinds of scope extrusion happen on the same compiler which will only have Ycheck failures. We still need to handle those failures with a better message, but this is an orthogonal concern.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: It seems that `run` is useless in macros --- I'm not sure how useful it's in staged computation. I remember there is also theoretical problems with `run`.

I'm wondering if it is possible to just remove the method so that it will not be misused by macro authors.

/cc : @biboudis

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: `run` is useful for running literals. I [use it](https://github.com/anatoliykmetyuk/utest/blob/a4ac313b76886e4e053e5637b14ca761b1bce532/utest/src-0/utest/TestBuilder.scala#L68) in uTest for that purpose. I believe at least for the literals it should remain there, it works fine for them.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: NO, do not use run to evaluate literals. Use https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/ValueOfExpr.scala or the Const extractor directly. 

This miss use show that we really need to fail as soon as the user mixes the two concepts.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: Unfortunately it is not possible to remove the run when executing code in a macro. Though it might be possible to statically partially check for scope extrusion.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/ToolboxImpl.scala]: Those check would not be complete either and therefore we still need a runtime check
