### PR TITLE
Scaladoc: fix #14481: certain functions not being shown in searchbar

### LINKED ISSUE #14481: Scaladoc: can't find some functions using searchbar
## Compiler version

Nightly

## Reproduction steps

1. Open https://dotty.epfl.ch/api/index.html
2. Open scaladoc searchbar
3. Search for `readLine`

## Output

Nothing

## Expectation

`readLine` function on object `StdIn`.
https://dotty.epfl.ch/api/scala/io/StdIn$.html

## Gif

Peek 2022-02-14 22-41

### PR DESCRIPTION
**Pull request by jchyb**
Allows to search for public members inherited from hidden classlikes in Scaladoc. Additionally, to avoid confusing users about the missing link in the "Inherited from:" field, a `(hidden)` adnotation was also added to the superclass name of those function members.

Fixes #14481

### CODE REVIEW

**Comment by KacperFKorban** [comment]
https://scala3docstorage.blob.core.windows.net/pr-searchbar-inherited-hidden/scala3/api/index.html

File: scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala [hunk 1]
```diff
@@ -150,7 +150,7 @@ trait Resources(using ctx: DocContext) extends Locations, Writer:
             val entry = mkEntry(member.dri, member.name, flattenToText(sig), descr, member.kind.name)
             val children = member
                 .membersBy(m => m.kind != Kind.Package && !m.kind.isInstanceOf[Classlike])
-                .filter(m => m.origin == Origin.RegularlyDefined && m.inheritedFrom.isEmpty)
+                .filter(m => m.origin == Origin.RegularlyDefined && (m.inheritedFrom.isEmpty || m.inheritedFrom.get.isSourceSuperclassHidden))
```
Comment (pikinier20) [inline scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala:153]: NIT:
shorter and without `get`
`m.inheritedFrom.fold(true)(_.isSourceSuperclassHidden)`

**Review by pikinier20 — COMMENTED** [review]
Could you provide an example member that is added by this PR?
Also, it might be worth adding a signature test for this.

**Comment by jchyb** [comment]
@pikinier20 I've noticed now that I've misnamed this PR before - the methods were only missing from searchbar. Nevertheless I've added a SignatureTest for an example use case this issue presents. As for the searchbar itself, any StdIn method (e.g. readBoolean) would not show up there before. This is because they are being inherited from package private trait, rendering it inaccessible in API.
