### PR TITLE
Deprecate override class, improve checks

### LINKED ISSUE #24825: Allow `override enum`
## Minimized code

```scala
//> using scala 3.7.4

sealed trait A:
  type Blah

case object B extends A:
  override class Blah()

case object C extends A:
  override enum Blah:
    case Testing
```

## Output

```
[error] Only access modifiers are allowed on enum definitions
[error]   override enum Blah:
[error]                 ^^^^
```

## Expectation

The `C` case should compile like the `B` case does.

### LINKED ISSUE #25146: `override sealed abstract class` overriding type member fails when `sealed abstract class` succeeds
## Compiler version

3.7.4, 3.8.0-RC1, 3.nightly `3.8.3-RC1-bin-20260130-48bb326-NIGHTLY`

## Minimized code

```scala
//> using scala 3.nightly

class Super {
  type T
}

class Sub extends Super {
  override sealed abstract class T
}
```

## Output

```
abstract override values cannot be sealed
```

## Expectation

This should compile as `sealed abstract class T` works fine and `override` should just specify that the inner class is overriding `Super#T`.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #24825 and affirms the status quo by disallowing `override enum`.
Improve Scala 2 compat by deprecating `override class`.
Fixes #25146

### CODE REVIEW

**Comment by som-snytt** [comment]
Added a commit for skeptics @noti0na1

**Comment by som-snytt** [comment]
Also disallow `override class`, for those disillusioned by the thoughtless liberality that has crept into the opinionated compiler.

One might assume that someone intended to discard `class` altogether and take all humankind as co-equals.

**Comment by noti0na1** [comment]
I searched "override class“ and ”override trait“ across the Scala codebase on GitHub, and Libretto appears to be the only library that relies on this pattern.

I agree that completely disallowing override on class definitions may be overly aggressive. Some users may view it as analogous to overriding a type alias or other type member.

That said, I personally find this syntax confusing, as it can give the impression that one is refining a class definition in a way similar to virtual classes, which is not what is actually happening.

Given this, I think it is reasonable to allow override on enum, class, or trait only when they are actually refining a type member, while emitting warnings to discourage the pattern.

CC @sjrd if you have any opinion?

**Comment by som-snytt** [comment]
I would not issue warnings for what is legal and benign. If it is either illegal or malign, then it ought to be disallowed.

Libretto also had bad use of parens, as mentioned at https://github.com/scala/scala3/issues/25054.

Sometimes one must "batten down the hatches" against the ravages of syntax.

If type members are like type params, the argument is that if I have `C[A]`, I don't implement a `class A`. It's not very meaningful to say "please implement something with this name; that's easy, it can be anything you like."

Certain forms of term overrides were also forbidden, so there is precedent that having the same name does not mean that `override` is at your service. (Either to confirm or disprove an overriding relationship.)

Scala 2 has comments to remove shadowing class definitions, moreover. There is likely to be a `TODO`.

This is poignant:
```
// TODO: can we do better?
```
Yes, we can!

**Comment by som-snytt** [comment]
I see libretto currently says:
```
➜  libretto git:(upgrade/8) ✗ grep "override class" $(finds)
./core/src/main/scala/libretto/scaletto/impl/FreeScaletto.scala:  override class AssemblyError private[FreeScaletto](
```
So we must move fast with the prohibition in order to have something to prohibit.

Edit:
```
type AssemblyError <: Throwable
```
I wonder if that was enforced.

Edit: yes, refchecks.
```
9 |  override class Foo {
  |                 ^
  |               error overriding type Foo in trait Fooz with bounds <: Bar;
  |                 class Foo has incompatible type
```
In the supertrait, it's erased to its upper bound, there are bridges in subclasses, etc.

**Comment by som-snytt** [comment]
I'll wait for consensus before undertaking further spitballing.

**Comment by noti0na1** [comment]
We discussed this in the core meeting and decided to deprecate this usage.
The override modifier in this position is redundant and tends to introduce more confusion than clarity.

* We will emit a deprecation warning for the override modifier on class and trait, while keeping the current behavior for enum (not allowing override).
* In a subsequent version (maybe 3.9), override on class and trait will be disallowed.

**Comment by som-snytt** [comment]
To clarify, the syntax is redundant because it can be rewritten to use a different class name and an overriding type alias.

The current syntax is just a confusing convenience.

File: tests/neg/i24825c.scala [hunk 1]
```diff
@@ -0,0 +1,33 @@
+sealed trait A:
+  type Blah <: reflect.Enum
+
+case object B extends A:
+  override class Blah extends reflect.Enum: // deprecation
```
Comment (noti0na1) [inline tests/neg/i24825c.scala:5]: Can you add a test for `override trait`?

Comment (noti0na1) [reply tests/neg/i24825c.scala:5]: Other changes LGTM

Comment (som-snytt) [reply tests/neg/i24825c.scala:5]: done at the warn test
