### PR TITLE
ScalaDoc : type parameter in extension method is wrong

### LINKED ISSUE #12813: ScalaDoc : type parameter in extension method is wrong
## Compiler version

sbt 1.5.3 / scalaVersion 3.0.0 and 3.0.1-RC1

## Minimized example

Start a new project `sbt new scala/scala3.g8`

```Scala
/* src/main/scala/Main.scala */
@main def hello: Unit = 
  println(foo)

val foo: (Int,String) = 1.toTuple2("string")

extension [A](thiz:A)
  def toTuple2[B](that:B):(A,B) = thiz -> that /* <- HERE */

```
then run `sbt doc`, when finished open `target/scala-3*/api/index.html` in a browser and look for package `<empty>`.

## Output

image

## Expectation

Type parameter `B` is not present. Expecting the type paremeter of the method `toTuple2` function to be `[B]`

### PR DESCRIPTION
**Pull request by KacperFKorban**
fixes #12813

### CODE REVIEW

**Review by pikinier20 — APPROVED** [review]

**Review by romanowski — APPROVED** [review]

File: scaladoc/src/dotty/tools/scaladoc/translators/ScalaSignatureUtils.scala [hunk 1]
```diff
@@ -24,64 +24,61 @@ trait SignatureBuilder extends ScalaSignatureUtils {
...
+  def modifiersAndVisibility(t: Member, kind: String) =
+    val (prefixMods, suffixMods) = t.modifiers.partition(_.prefix)
+    val all = prefixMods.map(_.name) ++ Seq(t.visibility.asSignature) ++ suffixMods.map(_.name)
 
-    def generics(on: Seq[TypeParameter]) = list(on.toList, "[", "]"){ (bdr, e) =>
-      bdr.annotationsInline(e).text(e.variance).memberName(e.name, e.dri).signature(e.signature)
-    }
+    text(all.toSignatureString()).text(kind + " ")
 
+<<<<<<< HEAD
```
Comment (bishabosha) [inline scaladoc/src/dotty/tools/scaladoc/translators/ScalaSignatureUtils.scala:81]: theres some merge conflict here

**Review by bishabosha — CHANGES_REQUESTED** [review]
it appears there is a merge conflict that was unresolved

File: scaladoc/src/dotty/tools/scaladoc/translators/ScalaSignatureUtils.scala (hunk 1 above)
Comment (KacperFKorban) [reply scaladoc/src/dotty/tools/scaladoc/translators/ScalaSignatureUtils.scala]: fixed :sweat_smile:

**Review by bishabosha — APPROVED** [review]
