### PR TITLE
Fix constant conversion to singleton types

### LINKED ISSUE #12208: Literal singleton type accepting wrong value
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
scala> val pi: 3.14 = 3
val pi: 3.14 = 3.0

scala> pi
val res0: Double = 3.14
```

## Expectation

2.13.4

```Scala
scala> val pi: 3.14 = 3
                      ^
       error: type mismatch;
        found   : Double(3.0)
        required: 3.14
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #12208

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Constants.scala [hunk 1]
```diff
@@ -161,25 +163,29 @@ object Constants {
...
-      else if (target == defn.LongClass && isLongRange)
-        Constant(longValue)
-      else if (target == defn.FloatClass && isFloatRange)
-        Constant(floatValue)
-      else if (target == defn.DoubleClass && isNumeric)
-        Constant(doubleValue)
-      else
-        null
+      pt match
+        case ConstantType(value) if value == this => this
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/core/Constants.scala:167]: Idle thought, what would it look like with guard terminated by `then`? `case P if b then body`

File: compiler/src/dotty/tools/dotc/core/Constants.scala [hunk 2]
```diff
@@ -161,25 +163,29 @@ object Constants {
...
+          else if (target == defn.CharClass && isCharRange)
+            Constant(charValue)
+          else if (target == defn.IntClass && isIntRange)
+            Constant(intValue)
+          else if (target == defn.LongClass && isLongRange)
+            Constant(longValue)
+          else if (target == defn.FloatClass && isFloatRange)
+            Constant(floatValue)
+          else if (target == defn.DoubleClass && isNumeric)
+            Constant(doubleValue)
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/core/Constants.scala:186]: In a series of `if p && q then` where the ps are mutually exclusive, preferable to
```
expr match p => if q then res else default
```
Noticed the similar pattern in constant folding. Maybe nbd for 7 tests. My question would be what should my fingers type automatically for this pattern.

It could optimize `eq` as exclusive but maybe not `==`.

File: compiler/src/dotty/tools/dotc/core/Constants.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/Constants.scala:167]: Too late for that...

**Review by nicolasstucki — APPROVED** [review]
