### PR TITLE
Fix #1846: add regression test

### LINKED ISSUE #1846: Expanding a pattern match leads to "head of empty list"
When trying to compile this syntactically correct, but nonsensical program the compiler crashes:

```scala
object Bug {
  val x = 42
  x match {case {42}.toString => 42}
}
```
Beginning of the trace:

```
exception while transforming Bug.x match
  {
    case 42.toString() => 42
  } of class class dotty.tools.dotc.ast.Trees$Match # 79
exception while transforming () extends Object() {
  val x: Int = 42
  Bug.x match
    {
      case 42.toString() => 42
    }
} of class class dotty.tools.dotc.ast.Trees$Template # 81
exception while transforming @scala.annotation.internal.SourceFile("examples/bug.scala") final module class
  Bug$
() extends Object() {
  val x: Int = 42
  Bug.x match
    {
      case 42.toString() => 42
    }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 82
exception while transforming package <empty> {
  final lazy module val Bug: Bug$ = new Bug$()
  @scala.annotation.internal.SourceFile("examples/bug.scala") final module class

  Bug$() extends Object() {
    val x: Int = 42
    Bug.x match
      {
        case 42.toString() => 42
      }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 83

exception occurred while compiling examples/bug.scala
Exception in thread "main" java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$ScalacPatternExpanders$ScalacPatternExpander$class.applyMethodTypes(PatternMatcher.scala:1863)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$ScalacPatternExpanders$alignPatterns$.applyMethodTypes(PatternMatcher.scala:1904)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$ScalacPatternExpanders$alignPatterns$.apply(PatternMatcher.scala:1955)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$ScalacPatternExpanders$alignPatterns$.apply(PatternMatcher.scala:1978)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$ExtractorCall$.apply(PatternMatcher.scala:1412)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.extractor$lzycompute(PatternMatcher.scala:1127)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.extractor(PatternMatcher.scala:1127)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.paramType$1(PatternMatcher.scala:1185)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.extractorStep(PatternMatcher.scala:1201)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.nextStep(PatternMatcher.scala:1222)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$BoundTree.translate(PatternMatcher.scala:1231)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$class.translatePattern(PatternMatcher.scala:1338)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.translatePattern(PatternMatcher.scala:72)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$class.translateCase(PatternMatcher.scala:1335)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$OptimizingMatchTranslator.translateCase(PatternMatcher.scala:72)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$$anonfun$29.apply(PatternMatcher.scala:1299)
	at dotty.tools.dotc.transform.PatternMatcher$Translator$MatchTranslator$$anonfun$29.apply(PatternMatcher.scala:1299)
	at scala.collection.immutable.List.map(List.scala:273)
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #1846: add regression test

This PR does the following:

- removes the block syntax in patterns 
- fix a crash under `-Ycheck`
- check that stable identifier patterns are really stable -- scalac compatible

Note that by removing the block syntax from patterns, following code is still supported:

```Scala
implicit class Regex(sc: StringContext) {
  def r = new util.matching.Regex(sc.parts.mkString, sc.parts.tail.map(_ => "x"): _*)
}

scala> "123" match { case r"\d+" => true case _ => false }
res34: Boolean = true

scala> "123" match { case r"(\d+)$d" => d.toInt case _ => 0 }
res36: Int = 123
```

### CODE REVIEW

**Comment by allanrenucci** [comment]
Wow! I didn't know we could do that. We should probably spec it and test it thoroughly.

For instance, there are some inconsistencies:
```scala
42 match { case { 42 } => 42 } // OK
42 match { case { 42 }.toString => 42 } // OK, should error?
42 match { case { 42.toString } => 42 } // error
```

**Comment by allanrenucci** [comment]
@liufengyun I see you closed #1774 saying it is a bad idea. Then I think we should make this a neg test and make sure the compiler rejects block in patterns. WDYT?

**Comment by liufengyun** [comment]
@allanrenucci It's actually consistent, I've updated the test.

The following doesn't type-check because the pattern type and scrutinee type are irrelevant:

```Scala
42 match { case { 42.toString } => 42 }
```

The following code works:

```Scala
 "h" match { case { 42.toString } => 42 }
```

**Comment by liufengyun** [comment]
@allanrenucci Note that blocks are allowed in the syntax specification for Dotty:

```Scala
SimplePattern     ::=  PatVar                                                   Ident(wildcard)
                    |  Literal                                                  Bind(name, Ident(wildcard))
                    |  ‘(’ [Patterns] ‘)’                                       Parens(pats) Tuple(pats)
                    |  XmlPattern
                    |  SimplePattern1 [TypeArgs] [ArgumentPatterns]
SimplePattern1    ::=  Path
                    |  ‘{’ Block ‘}’
                    |  SimplePattern1 ‘.’ id
```

I think in #1774, I misunderstood the semantics of blocks in patterns.

**Comment by allanrenucci** [comment]
I understand why this typechecks:
```scala
42 match { case { 42.toString } => 42 }
```
But then I don't understand why this typechecks:
```scala
42 match { case { 42 }.toString => 42 }
```

**Comment by liufengyun** [comment]
The following code shows the pattern:

```Scala
    val x = 42
    val Y = "h"

    x match { case { "h" }.toString => println(42) }  // ok
    x match { case { "h".toString } => println(42) }  // error
    x match { case Y => println(42) }  // error
    x match { case Y.toString => println(42) }  // ok
```

But arguably, all of them should be invalid.

**Comment by allanrenucci** [comment]
> But arguably, all of them should be invalid.

Can you open an issue?

File: tests/run/i1846.scala [hunk 1]
```diff
@@ -0,0 +1,22 @@
+object Test {
```
Comment (allanrenucci) [inline tests/run/i1846.scala]: I think is it better to use `assert` instead of a check file for simple test cases like this one. Also one more think you could test:
```scala
val foo = 42 match { case x @ { 42 } => x }
assert(foo == 42)
```

File: tests/run/i3812.scala [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+    val Y = "42"
+
+    x match { case { 42 }           => () } // ok
+    x match { case { "42".toInt }   => () } // ok
+    x match { case { "42" }.toInt   => () } // ok
+    x match { case { "42".toInt }   => () } // ok
+    x match { case { Y.toInt }      => () } // ok
+    x match { case { Y }.toInt      => () } // ok
+
+    // x match { case Y.toInt          => () } // compiles but rejected by Ycheck
```
Comment (allanrenucci) [inline tests/run/i3812.scala]: @liufengyun `Ycheck` fails on this one. Should this be allowed?

Comment (liufengyun) [reply tests/run/i3812.scala]: Good catch, I think it should be allowed.

Comment (allanrenucci) [reply tests/run/i3812.scala]: Note that `case "42".toInt =>` does not parse. It might be confusing that one is allowed but not the other

Comment (liufengyun) [reply tests/run/i3812.scala]: The syntax specification requires the prefix has to be a` path` or `block`.

```
SimplePattern     ::=  PatVar                                                   Ident(wildcard)
                    |  Literal                                                  Bind(name, Ident(wildcard))
                    |  ‘(’ [Patterns] ‘)’                                       Parens(pats) Tuple(pats)
                    |  XmlPattern
                    |  SimplePattern1 [TypeArgs] [ArgumentPatterns]
SimplePattern1    ::=  Path
                    |  ‘{’ Block ‘}’
                    |  SimplePattern1 ‘.’ id
```

File: tests/run/i3812.scala [hunk 3]
```diff
@@ -0,0 +1,8 @@
+object Test {
+  def main(args: Array[String]): Unit = {
+    val x = 42
+    val Y = "42"
+
+    x match { case Y.toInt          => () } // ok
```
Comment (allanrenucci) [inline tests/run/i3812.scala]: This is an error in scalac, I don't think we should support it either

Comment (liufengyun) [reply tests/run/i3812.scala]: Good point, a check for stable prefix is missing for patterns here.

Comment (liufengyun) [reply tests/run/i3812.scala]: Now I'm a little unsure about Scalac behavior, as it also rejects the following code:

```
    var X = 42
    42 match { case X          => () }
```

It seems to be it can be accepted without any issue.

Comment (liufengyun) [reply tests/run/i3812.scala]: According to scala spec 2.13, the scalac behavior is correct.

https://www.scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html#stable-identifier-patterns

**Comment by liufengyun** [comment]
@odersky  This PR does the following:

- removes the block syntax in patterns 
- fix a crash under `-Ycheck`
- check that stable identifier patterns are really stable -- scalac compatible

Note that by removing the block syntax from patterns, following code is still supported:

```Scala
implicit class Regex(sc: StringContext) {
  def r = new util.matching.Regex(sc.parts.mkString, sc.parts.tail.map(_ => "x"): _*)
}

scala> "123" match { case r"\d+" => true case _ => false }
res34: Boolean = true

scala> "123" match { case r"(\d+)$d" => d.toInt case _ => 0 }
res36: Int = 123
```

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala [hunk 4]
```diff
@@ -75,6 +75,21 @@ object RefChecks {
     }
   }
 
+  /** Check that a stable identifier pattern is indeed stable (SLS 8.1.5)
+   */
+  private def checkStableIdentPattern(tree: Tree)(implicit ctx: Context) = {
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: I believe it would be simpler to put this check in Typer. 

Here, we could just add `if (ctx.mode.is(Mode.Pattern) && !tree.tpe.isStable) error` to the checks for Ident and Select.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: But I am also no sure why we should demand stability? What would go wrong if we didn't?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: The following check seems too strong to me:

```
if (ctx.mode.is(Mode.Pattern) && !tree.tpe.isStable) error
```

As a selection of `unapply` would fail this check. The check should only happen for _Stable Identifier Pattern_ (SLS 8.1.5). I don't know what's the motivation for the Scala specification. Arguably, a `var` could be allowed in a pattern, but then it complicates the specification and check.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: OK, so let's keep the test for stable idents but move it to Typer.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: OK, now it's done.
