### PR TITLE
Fix #6288: Allow Singletons in Unions

### LINKED ISSUE #6288: Conversion to opaque alias of singleton type not allowed in the companion
When an opaque type is an alias of a singleton type (literal or term), then in the companion object, the conversion from the singleton type to the alias type does not work. The conversion in the other direction works.

Test code 1:
```scala
object A{
  opaque type T = 3
  object T {
    val x: T = 3
  }
}
```

Output
```
-- [E007] Type Mismatch Error: opaque-singleton.scala:4:15 ---------
4 |    val x: T = 3
  |               ^
  |               Found:    Int(3)
  |               Required: A.T.T'
  |
  |               where:    T  is a object in object A
  |                         T' is a type in object T
one error found
```

Test code 2:
```scala
object O{
  val x = 3
  opaque type T = x.type
  object T {
    def wrap(a: x.type): T = a   // Error
    def unwrap(a: T): x.type = a // OK
  }
}
```

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by smarter** [comment]
For reference, here's the open issue about this: https://github.com/lampepfl/dotty/issues/1551

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
@nicolasstucki I had to disable compiling tasty-interpreters in BootstrappedOnlyCompile since I got errors of this form:
```
51 |    else jvmReflection.interpretNew(fn.symbol, evaluatedArgss(argss))
   |                                    ^^^^^^^^^
   |                                    Found:    Interpreter.this.reflect.Symbol
   |                                    Required: Interpreter.this.jvmReflection.reflect'.Symbol
   |                                    
   |                                    where:    reflect  is a value in class TreeInterpreter
   |                                              reflect' is a value in class JVMReflection
```
Can you take a look what went wrong here, and hopefully bring them back?

**Comment by odersky** [comment]
test performance please

File: tests/pos/i6288.scala [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  object T {
+    val x: T = 3
+  }
+}
+
+object O {
+  val x = 3
+  opaque type T = x.type
+  object T {
+    def wrap(a: x.type): T = a   // Error
```
Comment (nicolasstucki) [inline tests/pos/i6288.scala]: Is this intended to be a neg test?

**Comment by nicolasstucki** [comment]
I added a commit fixing the checkfile of `tasty-extractors-1` and then reverted it because there was a conflict with master. I will fix it once this is merged.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -1038,6 +1064,23 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
   }
 
+  /** Check whether we can compare the given set of atoms with another to determine
+   *  a subtype test between OrTypes. There is one situation where this is not
+   *  the case, which has to do with SkolemTypes. TreeChecker sometimes expects two
+   *  types to be equal that have different skolems. To account for this, we identify
+   *  two different skolems in all phases `p`, where `p.isTyper` is false.
+   *  But in that case comparing two sets of atoms that contain skolems
+   *  for equality would give the wrong result, so we should not use the sets
+   *  for comparisons.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Isn't not using the sets a potential performance problem ? Have you considered having both `OrType#atoms` and `OrType#atomsUnifySkolems` instead, where the latter would replace all skolems referring to the same type by a single instance ?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -1499,30 +1542,38 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
   /** The greatest lower bound of a list types */
   final def glb(tps: List[Type]): Type = ((AnyType: Type) /: tps)(glb)
 
+  def widenInUnions(implicit ctx: Context): Boolean = ctx.scala2Mode || ctx.erasedTypes
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Do we have examples of Scala 2 code that breaks without the `scala2Mode` here ?

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 4]
```diff
@@ -188,29 +192,82 @@ trait TypeOps { this: Context => // TODO: Make standalone object.
...
+      }
+      val tp2w = tp2 match {
+        case tp2: TypeProxy if !isClassRef(tp2) => tp2.superType.widenExpr
+        case _ => tp2
+      }
+      if ((tp1w ne tp1) || (tp2w ne tp2)) {
+        val isSingle1 = tp1.isInstanceOf[SingletonType]
+        val isSingle2 = tp2.isInstanceOf[SingletonType]
+        return {
+          if (tp2w eq tp2) orDominator(tp1w | tp2)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala]: Would be helpful to add comments like `// 2.1` above conditions to relate them with the comment above and make sure they stay in sync in the future.

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 5]
```diff
@@ -188,29 +192,82 @@ trait TypeOps { this: Context => // TODO: Make standalone object.
...
+          else if (tp1w eq tp1) orDominator(tp1 | tp2w)
+          else if (tp1w frozen_<:< tp2w) orDominator(tp1w | tp2)
+          else if (tp2w frozen_<:< tp1w) orDominator(tp1 | tp2w)
+          else if (isSingle1 && !isSingle2) orDominator(tp1w | tp2)
+          else if (isSingle2 && !isSingle1) orDominator(tp1 | tp2w)
+          else if (tp1 frozen_<:< tp2w) tp2w
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala]: Is a case for 2.5 looking like `else if (tp2 frozen_<:< tp1w) tp1w` missing here ?

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 6]
```diff
@@ -188,29 +192,82 @@ trait TypeOps { this: Context => // TODO: Make standalone object.
...
+          else orDominator(tp1w | tp2)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala]: 2.6 says "pick tp1", that doesn't seem to match the code.

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 7]
```diff
@@ -1058,10 +1059,52 @@ object Types {
         tp.derivedRefinedType(tp.parent.widenUnion, tp.refinedName, tp.refinedInfo)
       case tp: RecType =>
         tp.rebind(tp.parent.widenUnion)
+      case tp =>
+        tp
+    }
+
+    /** Widen all top-level singletons reachable by dealising
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala]:
```suggestion
    /** Widen all top-level singletons reachable by dealiasing
```

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I believe skolems are sufficiently rare. If it turns out that we get a performance problem, what you suggest could be a good alternative.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 3 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I haven't tried. But it's better to be conservative, I think.

**Comment by odersky** [comment]
@nicolasstucki I tried to update the check file but still get errors for the runMacros test. Can you take a look? Thanks!

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 3 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I'm not sure, all these inference differences (that we'll have to document at some point) make it more risky for a codebase to turn off Scala2 mode since there's a non-zero chance any of them could cause a slient change of runtime behavior (e.g. because a different implicit ends up being selected). They're also only lightly tested since most of our tests are run without Scala2 mode enabled, meaning a higher risk of unforeseen interactions. So I'd limit them to things that significantly help in cross-compilation, but we can revisit this some other time.

**Comment by odersky** [comment]
> 2.5 and 2.6 now both end with "pick widened tp1" which doesn't seem correct.

No that's intentional. 2.6 is the one clause that is not symmetric, that's why it is separate from 2.5
