### PR TITLE
Make more anonymous functions static

### LINKED ISSUE #19224: Runtime regression from Scala 2: A non-closure lambda literal is no longer a constant value and is not equal to itself
## Compiler version

3.3.1

## Minimized code

```scala
object app extends App {
  def x(): Int => String = (i: Int) => i.toString

  locally {
    println(x() == x()) // true on Scala 2, false on Scala 3...
    println(x().hashCode -> x().hashCode) // same on Scala 2, different on Scala 3
  }
}
```

## Output

```bash
% coursier launch scala:2.13.12 -- example.scala
true
(1240730624,1240730624)
% coursier launch scala:3.3.1 -- example.scala
false
(580212331,390994841)
```

## Expectation

Expected repeated invocations of `x()` to produce the exact same lambda instance, as before in Scala 2 and currently in Java:

```java
class app {
    static java.util.function.Function<Integer, String> x() {
        return ((Integer i) -> i.toString());
    }

    public static void main(String[] args) {
        System.out.println(x() == x());
        System.out.println(x().equals(x()));
        System.out.println(x().hashCode());
        System.out.println(x().hashCode());
    }
}
```
Outputs:
```
true
true
707610042
707610042
```

We rely on this property very heavily in https://github.com/7mind/izumi (since Java behaves the same way, we assumed this property couldn't be broken in the future)

### LINKED ISSUE #19924: Compilation performance regression on 3.4.0
## Compiler version

3.4.0

## Expectation

using sbt 1.9.8 in a project of about 500 files split equally between 4 modules compilation time was 70 seconds on scala 3.3.3
scalacOptions is `-feature, -unchecked, -deprecation, -explaintypes, -encoding, UTF8, -language:_, -Yretain-trees, -Xmax-inlines:100, -no-indent`

## Actual

with scala version 3.4.0 same sources with same libs compile in about 120 seconds

### PR DESCRIPTION
**Pull request by odersky**
An anonymous function in a static object was previously mapped to a member of that object. We now map it to a static member of the toplevel class instead. This causes the backend to memoize the function, which fixes #19224. On the other hand, we don't do that for anonymous functions nested in the object constructor, since that can cause deadlocks (see run/deadlock.scala).

Scala 2's behavior is different: it does lift lambdas in constructors to be static, too, which can cause deadlocks.

Fixes #19224

### CODE REVIEW

**Comment by SethTisue** [comment]
commit message has wrong ticket number (should be 19224, not 19924)

**Comment by retronym** [comment]
I've added some comments in https://github.com/lampepfl/dotty/issues/19224#issuecomment-1852837753

File: tests/run/i19224.scala [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  locally {
+    assert(x() == x()) // true on Scala 2, was false on Scala 3...
+    assert(y() == y()) // also true if `y` accesses object-local fields
+
+    def z(): Int => String = (i: Int) => i.toString
+    assert(z() != z()) // lambdas in constructor are not lifted to static, so no memoization (Scala 2 lifts them, though).
+  }
+
+  val t1 = new C
+  val t2 = new C
```
Comment (retronym) [inline tests/run/i19224.scala:17]: Missing the definition of `class C` in the test?

File: compiler/src/dotty/tools/dotc/transform/Dependencies.scala [hunk 2]
```diff
@@ -184,23 +185,29 @@ abstract class Dependencies(root: ast.tpd.Tree, @constructorOnly rootContext: Co
...
             // non-static classes can capture owners, so should be avoided
           && (encClass.isProperlyContainedIn(local.topLevelClass)
               // can be false for symbols which are defined in some weird combination of supercalls.
               || encClass.is(ModuleClass, butNot = Package)
                   // needed to not cause deadlocks in classloader. see t5375.scala
               )
-        )
-        || (
+          && (!sym.isAnonymousFunction || sym.owner.ownersIterator.exists(_.isConstructor))
+            // For anonymous functions in static objects, we prefer them to be static because
```
Comment (retronym) [inline compiler/src/dotty/tools/dotc/transform/Dependencies.scala:196]: What does the "in static objects" part mean here?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/Dependencies.scala:196]: Static means toplevel or nested in a static object.

Comment (retronym) [reply compiler/src/dotty/tools/dotc/transform/Dependencies.scala:196]: How does the comment relate to an anonymous function in the extended test case? It is in a class, not a static object. I feel like I'm missing something here...

```scala
class C {
  def x(): Int => String = (i: Int) => i.toString
}
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/Dependencies.scala:196]: It added more comments. Hope it is clearer now.

File: compiler/src/dotty/tools/dotc/transform/Dependencies.scala [hunk 3]
```diff
@@ -181,26 +182,47 @@ abstract class Dependencies(root: ast.tpd.Tree, @constructorOnly rootContext: Co
...
+     *  This is either the enclosing package or the enclosing class. If the former,
+     *  the method will be be translated to a static method of its toplevel class.
+     *  In that case, we might later re-adjust the owner to a nested class via
+     *  `narrowTo` when we see that the method refers to the this-type of that class.
+     *  We choose the enclosing package when there's something potentially to gain from this
+     *  and when it is safe to do so
+     */
     def setLogicOwner(local: Symbol) =
       val encClass = local.owner.enclosingClass
+      // When to [efer enclosing class over enclosing package:
```
Comment (retronym) [inline compiler/src/dotty/tools/dotc/transform/Dependencies.scala:195]: Typo

File: compiler/src/dotty/tools/dotc/transform/Dependencies.scala (hunk 2 above)
Comment (retronym) [reply compiler/src/dotty/tools/dotc/transform/Dependencies.scala]: Thanks, that helps me understand.

**Review by retronym — APPROVED** [review]
LGTM once the typo in the comment is fixed

File: compiler/src/dotty/tools/dotc/transform/Dependencies.scala (hunk 3 above)
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/Dependencies.scala:195]:
```suggestion
      // When to prefer the enclosing class over the enclosing package:
```

**Comment by odersky** [comment]
I believe it would be good to backport that patch to LTS, even though it changes runtime behavior.
