### PR TITLE
Fix gadt lhs union

### LINKED ISSUE #10102: GADT unsoundness: We can infer sufficient constraints when a union type is on the lhs of a subtype check
This compiles, but shouldn't:

```Scala
sealed trait Expr[+T]
final case class FooExpr() extends Expr[1 | 2]

object Test {
  def foo[T](x: Expr[T]): T = x match {
    case x: FooExpr =>
      3
  }

  val x: 1 | 2 = foo(FooExpr())
}
```

I think the problem is that when a union type is on the lhs, we can infer sufficient constraints regardless of whether we're in GadtConstraintInference mode or not, for example:
https://github.com/lampepfl/dotty/blob/b5a171536a8ce4294c2107770f47cb97dfc148f5/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L450
If I rewrite this to:
```scala
          isSubType(tp1.widenSingletons, tp2, approx.addLow)
```
Then the example above doesn't compile anymore:
```scala
-- [E007] Type Mismatch Error: try/gadtx.scala:7:6 -----------------------------
7 |      3
  |      ^
  |  Found:    (3 : Int)
  |  Required: T
  |
  |  where:    T is a type in method foo with bounds >: (1 : Int) | (2 : Int)
```
But I haven't checked what other consequences this would have or if there are other cases that would need to be changed like this too.

/cc @odersky

### PR DESCRIPTION
**Pull request by abgruszecki**
Fixes #10102.

### CODE REVIEW

**Comment by abgruszecki** [comment]
@smarter This is supposed to fix #10102  I think `inFrozenGadt` is, in principle, required in all places where I added it. 
I tried to add test cases for that and could not. For the applied-type-related code, I don't think that can result in unsound constraints _yet_, but the freeze should be there in principle. For the later join-related code, I don't know how to produce a non-soft union in the relevant position.

Still, both `.join`-s approximate unions in the same way that `.widenSingletons` does, so I'm quite convinced they need to have the GADTs frozen.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -434,15 +434,15 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
         def widenOK =
           (tp2.widenSingletons eq tp2)
           && (tp1.widenSingletons ne tp1)
-          && recur(tp1.widenSingletons, tp2)
+          && inFrozenGadt { recur(tp1.widenSingletons, tp2) }
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: I think this pattern (`inFrozenGadt(recur)`) should have its own method (`inFrozenGadtRecur` ?) which clearly documents how it differs from `recur` (the doc of `recur` says "`recur` should also not be used to compare approximated versions of the original types", but here we're intentionally violating that, which requires freezing the gadt bounds)

Comment (abgruszecki) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: I think it was already violated before, since here we _are_ recursing on approximations of the type. I'm not sure if there's anything special about `inFrozenGadt` here, rather, the docs of `recur` already suggest that it shouldn't be used here. I think the correct solution would be to add a comment to each of these calls explaining why they violate expectations of `recur`, but I don't know what to put in that comment.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: Yes, it was violated and thus broken before, but my understanding is that this violation is not a soundness issue as long as we freeze the gadt bounds, it just leads to missing solutions, but this is something we do intentionally in some situations.

Comment (abgruszecki) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: So do you want me to add add a comment to all of these callsites that we intentionally call `recur` on an approximated type, as it doesn't in this specific case lead to unsoundness? I don't think this merits a new definition, not yet anyway seeing as it's isolated to a single `match` branch.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: > So do you want me to add add a comment to all of these callsites that we intentionally call recur on an approximated type, as it doesn't in this specific case lead to unsoundness?

Are there other callsites than the three for which you wrapped with inFrozenGadt? If there are others, shouldn't they also be wrapped with inFrozenGadt?

Comment (abgruszecki) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: There are no other callsites that call `.widenSingletons` or `.join`, I checked that before opening the PR, should've mentioned it.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:437]: > EDIT: because I guess you don't mean "are there any other callsites in TypeComparer which call recur w/ an approx'd type".

That is what I meant yes.

**Comment by abgruszecki** [comment]
@odersky are you still going to take a look at this, or should we just merge it?
