### PR TITLE
Fix #10357: Add MATCHCASEtype tag to Tasty

### LINKED ISSUE #10357: TASTy: it seems the internal TypeBox and MatchCase are referenced from TASTy
I just tried naively moving `scala.internal.TypeBox` and `MatchCase` to `scala.runtime`. If I do that, from a clean build I get:
```
sbt:scala3> clean
[success] Total time: 0 s, completed 17 nov. 2020 15:08:20
[success] Total time: 0 s, completed 17 nov. 2020 15:08:20
sbt:scala3> scala-comp
{invalid input}
sbt:scala3> scala3-compiler/compile
[info] Compiling 71 Scala sources and 115 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\library\target\scala-3.0.0-M2\classes ...
[info] Compiling 7 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\interfaces\target\classes ...
[info] Unpacking scalajs-ir sources to C:\Users\sjrdo\Documents\Projets\dotty\compiler\target\scala-3.0.0-M2\src_managed\main\scalajs-ir-src...
[error] Bad symbolic reference. A signature
[error] refers to TypeBox/T in package scala.internal which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
[error] -- Error: C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\IArray.scala:478:21
[error] 478 |    Array.unapplySeq((x: Sup[T]): Array[_ <: T])
[error]     |                     ^
[error]     |                     class TypeBox does not have a member type CAP
[error] Bad symbolic reference. A signature
[error] refers to MatchCase/T in package scala.internal which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
[error] three errors found
[error] (scala3-library / Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 17 nov. 2020 15:08:35
```
This suggests that those two internal types made it as is in the TASTy of the dotty-library.

They shouldn't be there, as they are implementation details of the compiler, not something that we can justify in TASTy as a language independent of the compilers.

### PR DESCRIPTION
**Pull request by odersky**
We thus avoid references to a "magic" scala.internal.MatchCase class.

### CODE REVIEW

File: tasty/src/dotty/tools/tasty/TastyFormat.scala [hunk 1]
```diff
@@ -676,6 +678,7 @@ object TastyFormat {
     case TYPELAMBDAtype => "TYPELAMBDAtype"
     case LAMBDAtpt => "LAMBDAtpt"
     case MATCHtype => "MATCHtype"
+    case MATCHCASEtype => "MATCHCASEtype"
```
Comment (smarter) [inline tasty/src/dotty/tools/tasty/TastyFormat.scala:681]: I think TastyPrinter will need a case too.

**Review by smarter — CHANGES_REQUESTED** [review]

File: tasty/src/dotty/tools/tasty/TastyFormat.scala (hunk 1 above)
Comment (odersky) [reply tasty/src/dotty/tools/tasty/TastyFormat.scala:681]: I don't see why?

Comment (smarter) [reply tasty/src/dotty/tools/tasty/TastyFormat.scala:681]: Ah maybe not, I see we don't need cases for all type nodes in the printer.

**Review by smarter — APPROVED** [review]

**Comment by romanowski** [comment]
The failure in `scala3doc` comes from one of the projects what we use to build documentation for Scala 3 defined here: https://github.com/lampepfl/dotty/blob/master/project/Build.scala#L1499-L1503

**Comment by smarter** [comment]
Thanks @romanowski, looks like `tasty-core` should be `tasty-core-bootstrapped` and `scala3-library` should be `scala3-library-bootstrapped` to get tasty files compiled with the current compiler instead of the reference compiler (nothing needs to be done for `scala3-interfaces` since it's java-only)

**Comment by romanowski** [comment]
@smarter  I wonder if we should not include a path or any other way to quickly detect which `.tasty` file is causing problem in case of anyone will face similar issue in the future
