### PR TITLE
Fix #8600: Match trough type ascription

### LINKED ISSUE #8600: Match fails using quasiquotes
The issue is described in https://users.scala-lang.org/t/implementing-map-fusion-with-dotty-macros/5791/4?u=blaisorblade — sorry for not minimizing it further. Basically, the match in

```scala
  def mapImpl[A: Type, B: Type] (first: Expr[Pipe[A]], fn: Expr[A => B])(using qctx: QuoteContext): Expr[Pipe[B]] = {
    first match {
      case '{ Mapped($iFirst, $iFn) } =>
        '{ Mapped($iFirst, $iFn andThen $fn) }
      case _ =>
        '{ Mapped($first, $fn) }
    }
  }
```

fails to match against `Mapped(foo, bar)` (as produced by macro `Source(List(1, 2, 3)).map(x => x + 1)`). Using tasty reflection, I can make that match work by stripping `Typed` and `Inlined` nodes.
Additionally, I wanted to match against `TypeApply` by something like
`case '{ Mapped[$A, $B]($iFirst, $iFn) } =>` (or using `_` for `$A`), but I could not find a working syntax to express that.

To reproduce, check out https://github.com/Blaisorblade/dotty-map-fusion-staging-experiment.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: library/src/scala/internal/quoted/Matcher.scala [hunk 1]
```diff
@@ -175,8 +175,8 @@ private[quoted] object Matcher {
           case (Literal(constant1), Literal(constant2)) if constant1 == constant2 =>
             matched
 
-          case (Typed(expr1, tpt1), Typed(expr2, tpt2)) =>
-            expr1 =?= expr2 && tpt1 =?= tpt2
+          case (Typed(expr1, _), pattern) =>
+            expr1 =?= pattern
```
Comment (liufengyun) [inline library/src/scala/internal/quoted/Matcher.scala:179]: This means there is no way to match against a typed expression. It's fine in practice. As this is a design choice, it's better to add a small doc here, and add a link to the relevant issue.

Comment (nicolasstucki) [reply library/src/scala/internal/quoted/Matcher.scala:179]: That should be added to the docs in #8687. These do not exist yet.
