### PR TITLE
Fix #7554: Add TypeTest for sound pattern type test

### LINKED ISSUE #7554: Unsound use of ClassTag.unapply
## Issue
```scala
  /** A ClassTag[T] can serve as an extractor that matches only objects of type T.
   *
   * The compiler tries to turn unchecked type tests in pattern matches into checked ones
   * by wrapping a `(_: T)` type pattern as `ct(_: T)`, where `ct` is the `ClassTag[T]` instance.
   * Type tests necessary before calling other extractors are treated similarly.
   * `SomeExtractor(...)` is turned into `ct(SomeExtractor(...))` if `T` in `SomeExtractor.unapply(x: T)`
   * is uncheckable, but we have an instance of `ClassTag[T]`.
   */
  def unapply(x: Any): Option[T] = 
    ...
```

This unfortunately is known to break when used with path dependent type.

## Example
The following example shows a couple of cases where it fails
```scala
trait R {
  type Nat
  type Succ <: Nat
  type Idx
  given ClassTag[Nat]
  given ClassTag[Succ]
  given ClassTag[Idx]
  def n: Nat
  def one: Succ
}
class RI extens R {
  type Nat = Int
  type Succ = Int
  type Idx = Int
  given ClassTag[Nat] = classOf[Integer]
  given ClassTag[Succ] = new ClassTag[Integer] {
    def runtimeClass = classOf[Integer]
    def unapply(x: Any): Option[Succ] = x match
      case n: Int if n > 0 => Some(n)
      case _ => None
  }
  given ClassTag[Idx] = classOf[Integer]
  def n: Nat = 4
  def one: Succ = 1
}
object App {
  val r1: R = new RI
  val r2: R = new RI
  r1.n match {
    case n: r2.Nat => // Should not match or should have an unchecked waring
    case n: r1.Idx => // Should not match or should have an unchecked waring
    case n: r1.Succ => // Should match only if r1.n is an r1.Succ under the constraints set in r1
  }

  r1.one match {
    case n: r2.Nat => // Should not match or should have an unchecked waring
    case n: r1.Idx => // Should not match or should have an unchecked waring
    case n: r1.Nat => // Ok
  }
}
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Comparison with other kinds of type representations https://gist.github.com/nicolasstucki/ae3eaae553f594066bf9ad0e817f9a63

### CODE REVIEW

File: library/src/scala/tasty/TypeTest.scala [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package scala.tasty
```
Comment (sjrd) [inline library/src/scala/tasty/TypeTest.scala]: `TypeTest` isn't specific to TASTy. It should be in `scala.reflect`, just like `ClassTag`.

File: library/src/scala/tasty/TypeTest.scala [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ *  If a pattern match is performed on a term of type `s: S` that is uncheckable with `s.isInstanceOf[T]` and
+ *  the pattern are of the form:
+ *    - `t: T`
+ *    - `t @ X()` where the `X.unapply` has takes an argument of type `T`
+ *  then a given instance of `TypeTest[S, T]` is summoned and used to performed the test.
+ *
+ *  Note: This is replacemet for `ClassTag.unapply` that can be sound for path dependent types
+ */
+@scala.annotation.implicitNotFound(msg = "No TypeTest available for [${S}, ${T}]")
+trait TypeTest[S, T <: S] extends Serializable {
```
Comment (sjrd) [inline library/src/scala/tasty/TypeTest.scala]: I don't think we should enforce `T <: S`. With regular type test I can do:
```scala
scala> val x: CharSequence = "hello"
x: CharSequence = hello

scala> x match {
     |   case y: Comparable[_] => "ok"
     |   case _ => "ko"
     | }
res0: String = ok
```
soundly and without warning, even though `CharSequence` and `Comparable` are unrelated.

File: library/src/scala/tasty/TypeTest.scala (hunk 1 above)
Comment (nicolasstucki) [reply library/src/scala/tasty/TypeTest.scala]: Moved

File: library/src/scala/tasty/TypeTest.scala (hunk 2 above)
Comment (nicolasstucki) [reply library/src/scala/tasty/TypeTest.scala]: Removed `T <: S`

File: docs/docs/reference/other-new-features/type-test.md [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+`TypeTest` provides the a replacement for `ClassTag.unapply` where the type of the argument is generalized.
+`TypeTest.unapply` will return `Some(x.asInstanceOf[Y])` if `x` conforms to `Y`, otherwise it returns `None`.
+
+```scala
+trait TypeTest[-S, T] extends Serializable {
+  def unapply(s: S): Option[s.type & T]
+}
+```
+
+Just like `ClassTag` used to to, it can be used to perform type checks in patterns.
```
Comment (hrhino) [inline docs/docs/reference/other-new-features/type-test.md]: "used to do"

File: docs/docs/reference/other-new-features/type-test.md [hunk 4]
```diff
@@ -0,0 +1,70 @@
+---
+layout: doc-page
+title: "TypeTest"
+---
+
+TypeTest
+--------
+
+`TypeTest` provides the a replacement for `ClassTag.unapply` where the type of the argument is generalized.
```
Comment (hrhino) [inline docs/docs/reference/other-new-features/type-test.md]: "the a"

File: library/src/scala/reflect/TypeTest.scala [hunk 5]
```diff
@@ -0,0 +1,33 @@
+package scala.reflect
+
+/** A `TypeTest[S, T] contains the logic needed to know at runtime if a value of
+ *  type `S` can be downcased to `T`.
```
Comment (hrhino) [inline library/src/scala/reflect/TypeTest.scala]: "downcasted"

File: library/src/scala/reflect/TypeTest.scala [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+ *
+ *  If a pattern match is performed on a term of type `s: S` that is uncheckable with `s.isInstanceOf[T]` and
+ *  the pattern are of the form:
+ *    - `t: T`
+ *    - `t @ X()` where the `X.unapply` has takes an argument of type `T`
+ *  then a given instance of `TypeTest[S, T]` is summoned and used to performed the test.
```
Comment (hrhino) [inline library/src/scala/reflect/TypeTest.scala]: "used to perform"

File: library/src/scala/reflect/TypeTest.scala [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+ *
+ *  Note: This is replacemet for `ClassTag.unapply` that can be sound for path dependent types
```
Comment (hrhino) [inline library/src/scala/reflect/TypeTest.scala]: "the replacement"

File: library/src/scala/reflect/TypeTest.scala [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+ */
+@scala.annotation.implicitNotFound(msg = "No TypeTest available for [${S}, ${T}]")
+trait TypeTest[-S, T] extends Serializable {
+
+  /** A TypeTest[S, T] can serve as an extractor that matches only S of type T.
+   *
+   * The compiler tries to turn unchecked type tests in pattern matches into checked ones
+   * by wrapping a `(_: T)` type pattern as `tt(_: T)`, where `ct` is the `TypeTest[S, T]` instance.
```
Comment (hrhino) [inline library/src/scala/reflect/TypeTest.scala]: "tt"/"ct"

File: library/src/scala/reflect/TypeTest.scala [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+   * Type tests necessary before calling other extractors are treated similarly.
+   * `SomeExtractor(...)` is turned into `tt(SomeExtractor(...))` if `T` in `SomeExtractor.unapply(x: T)`
```
Comment (hrhino) [inline library/src/scala/reflect/TypeTest.scala]: That's not accurate, is it? Shouldn't the `tt` be used first?

Comment (nicolasstucki) [reply library/src/scala/reflect/TypeTest.scala]: `tt(SomeExtractor(...)) it is accurate. But as it is a pattern, the outer most pattern is applied first at runtime.

```scala
 x match { case tt(SomeExtractor(...)) =>  ... }
```

becomes something like
```scala
val x$1 = tt.unapply(x)
if (x$1.isDefined) {
 val x$2 = x$1.get
 val x$3 = SomeExtractor.unapply(x$2)
 if (x$3.isDefined) ...
} else ...
```

**Comment by sjrd** [comment]
And I strongly maintain that `ClassTag`s are not broken, and that it was type tests bolted on them that were broken since the beginning. Let's not fix what ain't broken, and let's put in two unrelated interfaces the two completely unrelated capabilities, namely that of creating `Array[A]`s and that of testing `x.isInstanceOf[A]`. Maintaining unrelated responsibilities in different interfaces is the only way to keep complexity down.

**Comment by nicolasstucki** [comment]
We still need this to make the `tasty.Reflection` interface sound.

**Comment by dwijnand** [comment]
Is there a legal open-access version of https://infoscience.epfl.ch/record/261291?

**Comment by nicolasstucki** [comment]
It looks like the paper can be freely downloaded from https://dl.acm.org/doi/10.1145/3241653.3241658

**Comment by nicolasstucki** [comment]
In #8993 I found that providing ClassTags were the type test is sound can lead unsoundess when using those ClassTags in arrays.

**Comment by nicolasstucki** [comment]
Also see https://gist.github.com/nicolasstucki/ae3eaae553f594066bf9ad0e817f9a63

**Comment by odersky** [comment]
The way I understand it, `Typeable` works soundly also for arbitrary types. And one can tweak it to get a usable `unapply`, as #9840 shows. I have a preference for `Typeable` over `TypeTest` because it seems simpler (just one type parameter instead of two) and it is already established. I have expressed before my concerns that we should not add to an ever-growing zoo of type-test and type-representation types. 

So what about the following strategy?

 - Get a version of scala.reflect.Typeable in the standard library: for the moment in the extra classes for the standard library that ship with Scala 3.
 - Use that version instead of native ClassTag support for tasty reflect.

What do people think about this alternative?

**Comment by nicolasstucki** [comment]
Note that the `Typable` proposal will not help with the Reflection API due to flexibility and soundness issues (see #7554 (comment)).

**Comment by nicolasstucki** [comment]
@odersky I updated the docs and added the `Typable` alias for context bounds.

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 10]
```diff
@@ -45,6 +45,38 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
...
+        val tp1 = fullyDefinedType(arg1, "TypeTest argument", span)
+        val tp2 = fullyDefinedType(arg2, "TypeTest argument", span)
+        val sym2 = tp2.typeSymbol
+        if tp1 <:< tp2 then
+          // optimization when we know the typetest will always succeed
+          ref(defn.TypeTestModule_identity).appliedToType(tp2).withSpan(span)
+        else if sym2 == defn.AnyValClass || sym2 == defn.AnyRefAlias || sym2 == defn.ObjectClass then
+          EmptyTree
+        else
+          // Generate SAM: (s: <tp1>) => if s.isInstanceOf[s.type & <tp2>] then Some(s.asInstanceOf[s.type & <tp2>]) else None
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:60]: The test for `s.type` seems tautological. Shouldn't it be
```suggestion
          // Generate SAM: (s: <tp1>) => if s.isInstanceOf[<tp2>] then Some(s.asInstanceOf[s.type & <tp2>]) else None
```

File: library/src/scala/reflect/Typeable.scala [hunk 11]
```diff
@@ -0,0 +1,12 @@
...
+/** A shorhand for `TypeTest[Any, T]`. A `Typable[T] contains the logic needed to
+ *  know at runtime if a value can be downcasted to `T`.
+ *
+ *  If a pattern match is performed on a term of type `s: Any` that is uncheckable with `s.isInstanceOf[T]` and
+ *  the pattern are of the form:
+ *    - `t: T`
+ *    - `t @ X()` where the `X.unapply` has takes an argument of type `T`
+ *  then a given instance of `Typable[T]` (`TypeTest[Any, T]`) is summoned and used to perform the test.
+ */
+type Typable[T] = TypeTest[Any, T]
```
Comment (sjrd) [inline library/src/scala/reflect/Typeable.scala:12]: I'm not a native English speaker, but shouldn't this be spelled `Typeable`?

Comment (bishabosha) [reply library/src/scala/reflect/Typeable.scala:12]: seems hackage has `Typeable`

Comment (nicolasstucki) [reply library/src/scala/reflect/Typeable.scala:12]: Indeed, it should be Typeable.

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala (hunk 10 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:60]: Indeed. I will remove it from the check.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 12]
```diff
@@ -781,21 +781,28 @@ class Typer extends Namer
...
+        ) match
+          case SearchSuccess(clsTag, _, _) =>
+            Some(typed(untpd.Apply(untpd.TypedSplice(clsTag), untpd.TypedSplice(tree.expr)), pt))
+          case _ =>
+            None
       }
+      val tag = withTag(defn.TypeTestClass.typeRef.appliedTo(pt, tref))
+        .orElse(withTag(defn.ClassTagClass.typeRef.appliedTo(tref)))
+        .getOrElse(tree)
+      if tag.symbol.owner == defn.ClassTagClass && !config.Feature.sourceVersion.isAtLeast(config.SourceVersion.`3.1`) then
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:803]: That logic seems inverted to me: it says we don't emit any warning about unsound ClassTag usage if we're using 3.1?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Oops. Fixed it.

**Comment by milessabin** [comment]
> What do people think about this alternative?

If it preserves (or improves the precision of) the semantics of shapeless's `Typeable` then :+1: 

shapeless has a [gadget](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/typeable.scala#L365-L382) for using its `Typeable` in pattern matches, but it's ergonomics on Scala 2 aren't great,

```scala
@Test
def testTypeCase: Unit = {
  import HList.ListCompat._

  def typeCase[T: Typeable](t: Any): Option[T] = {
    val T = TypeCase[T]
    val `List[T]` = TypeCase[List[T]]
    val `(String, T)` = TypeCase[(String, T)]
    val `List[(String, T)]` = TypeCase[List[(String, T)]]

    t match {
      case T(t) => Some(t)
      case `List[T]`(lt) => lt.headOption
      case `(String, T)`(s, t) => typed[String](s) ; Some(t)
      case `List[(String, T)]`((s, t) :: _) => typed[String](s); Some(t)
      case `List[(String, T)]`(lst) => assertTrue(lst.isEmpty) ; None
      case _ => None
    }
  }

  assertEquals(Some(23), typeCase[Int](23: Any))
  assertEquals(None, typeCase[String](23: Any))
  assertEquals(Some(23), typeCase[Int](List(23): Any))
  assertEquals(None, typeCase[String](List(23): Any))
  assertEquals(Some(23), typeCase[Int](("foo", 23): Any))
  assertEquals(None, typeCase[String](("foo", 23): Any))
  assertEquals(Some(23), typeCase[Int](List(("foo", 23)): Any))
  assertEquals(None, typeCase[String](List(("foo", 23)): Any))
}
```

It would be great if Scala 3 supported pattern syntax similar to the above without having to resort to backtick puns.

**Comment by nicolasstucki** [comment]
Rebased

File: docs/docs/reference/other-new-features/type-test.md [hunk 13]
```diff
@@ -0,0 +1,146 @@
...
+  new TypeTest[Any, String]
+    def unapply(s: Any): Option[s.type & String] =
+      s match
+        case s: String => Some(s)
+        case _ => None
+
+f[AnyRef, String]("acb")(using tt)
+```
+
+The compiler will synthesize a new instance of a type test if non is found in scope as
```
Comment (odersky) [inline docs/docs/reference/other-new-features/type-test.md:71]: none

**Review by odersky — COMMENTED** [review]
Code looks good, it's just the doc page that needs some fixes.

File: docs/docs/reference/other-new-features/type-test.md [hunk 14]
```diff
@@ -0,0 +1,146 @@
...
+
+f[String] // true
+f[Int] // fasle
+```
+
+### TypeTest and ClassTag
+`TypeTest` is a replacemnt for the same functionallity performed by the `ClassTag.unaplly`.
+Using `ClassTag` instances happend to be unsound.
+`TypeTest` fixes that unsoundess and adds extra flexibility with the `S` type.
+`ClassTag` type tests will still be supported but a warining will be emitted after 3.0.
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply docs/docs/reference/other-new-features/type-test.md]: Dropped it.

File: docs/docs/reference/other-new-features/type-test.md [hunk 15]
```diff
@@ -0,0 +1,146 @@
...
+  def safeDiv(m: Nat, n: Succ): (Nat, Nat)
+  val Zero: Zero
+  val Succ: SuccExtractor
+  trait SuccExtractor {
+    def apply(nat: Nat): Succ
+    def unapply(nat: Succ): Option[Nat]
+  }
+  given TypeTest[Nat, Zero] = typeTestOfZero
+  protected def typeTestOfZero: TypeTest[Nat, Zero]
+  given TypeTest[Nat, Succ]
```
Comment (bishabosha) [inline docs/docs/reference/other-new-features/type-test.md:127]:
```suggestion
  given TypeTest[Nat, Succ] = typeTestOfSucc
```

**Comment by nicolasstucki** [comment]
@odersky can I merge this PR?
