### PR TITLE
Fix #7519: Check PCP of constructor calls on the type

### LINKED ISSUE #7519: Erroneous phase consistency check error for type annotation in quoted code
## minimized code

```Scala
object Test {
  class Annot extends StaticAnnotation

  class Quoted[T]

  inline def quote[T]: Quoted[T] = ${ quoteImpl[T] }
  def quoteImpl[T: Type](given qctx: QuoteContext): Expr[Quoted[T]] = '{
    new Quoted[T @Annot]
  }
}
```

produces an erroneous `wrong stage` error

```scala
12 |    new Quoted[T @Annot]
   |        ^^^^^^^^^^^^^^^^
   |        access to constructor Annot from wrong staging level:
   |         - the definition is at level 0,
   |         - but the access is at level 1.
```

## expectation
Since `Annot` is global this shouldn't have been a problem.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Detect when a a reference to a constructor is a static path.
Also fix `isTerm` and `isType` on `Hole`. We do not pickle this extra
info as when we unpickle it we already know if it will be a type or a term.

### CODE REVIEW

**Comment by biboudis** [comment]
Yes, the parameterless annotation worked. However, when I tried to splice a parameter it reported a wrong staging level. WDYT?

```scala
  class Annot(in: Int) extends StaticAnnotation

  class Quoted[T]

  inline def quote[T]: Quoted[T] = ${ quoteImpl[T] }
  def quoteImpl[T: Type](given qctx: QuoteContext): Expr[Quoted[T]] = {
    val value = '{ 42 }
    '{
      new Quoted[T @Annot(${value})]
    }
  }
```

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 1]
```diff
@@ -157,6 +157,8 @@ class ReifyQuotes extends MacroTransform {
                 val tagDef = tagDefCache.getOrElseUpdate(prefix.symbol, mkTagSymbolAndAssignType(prefix))
                 tagDef.symbol.typeRef
             }
+          case AnnotatedType(parent, _) =>
+            apply(parent) // Only keep the Annotated tree
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: Does it mean it throws the annotation away? That will make it impossible to keep some annotations in types.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: We throw away the annotation on the type but then recover it from the `Annotated` type tree while unpickling. 
Maybe I should only do it if it contains a splice. In that case we would always have the tree.
