### PR TITLE
Fix GADT approximation

### LINKED ISSUE #9044: Verify HKT GADT code
## Minimized code

```Scala
sealed trait Test[+F[_], +A] extends Product with Serializable

object Test {

  implicit class Syntax[F[_], A](val self: Test[F, A]) extends AnyVal {

    def fold[B](completed: F[A] => B): B = self match {
      case Completed(fa) => completed(fa)
    }
  }


  final case class Completed[F[_], A](fa: F[A]) extends Test[F, A]
}
```

## Output

Dotty 0.24.0-RC1:

```scala
[error] -- [E007] Type Mismatch Error: /Users/daniel/Development/Scala/cats-effect/core/src/main/scala/cats/effect/Test.scala:26:38 
[error] 26 |      case Completed(fa) => completed(fa)
[error]    |                                      ^^
[error]    |                 Found:    (fa : F$1[A$1])
[error]    |                 Required: F[A]
[error]    |
[error]    |                 where:    A$1 is a type in method fold with bounds <: A
[error]    |                           F$1 is a type in method fold with bounds <: F
```

Dotty master:
```scala
-- [E029] Pattern Match Exhaustivity Warning: try/dj.scala:7:43 ----------------
7 |    def fold[B](completed: F[A] => B): B = self match {
  |                                           ^^^^
  |                          match may not be exhaustive.
  |
  |                          It would fail on pattern case: Test.Completed(_)

longer explanation available when compiling with `-explain`
-- Warning: try/dj.scala:3:7 ---------------------------------------------------
3 |object Test {
  |       ^
  |       the type test for Test.Completed[?, ?] cannot be checked at runtime
2 warnings found
```

## Expectation

I think 0.24.0-RC1 got it right, current master is missing the error and producing some weird warnings.

### LINKED ISSUE #9158: Revisit approximating GADTs after implicit lookup
In https://github.com/lampepfl/dotty/pull/9140 we needed to temporarily remove code for approximating/"healing" types with GADT constraints, as it introduced unsoundness.

The root of the issue is more-or-less that given constraints `F[X] <: G[X]; A <: B` we approximated `F[A] ~ G[B]`, even though we should not as F/G might not be injective.

@smarter the code for approximating GADTs is almost a copy of IsFullyDefinedAccumulator. Given that, do you suppose there's an equivalent problem with type variable approximation (forcing)? If not, then why?

### LINKED ISSUE #9274: Incorrect code ends up passing the typechecker due to GADT logic misfiring
## Minimized code

This could probably be minimized further.

```Scala
import cats.Order
import cats.implicits._

def test[F[_], B](lhs: F[B], tolerance: B)(implicit ord: Order[F[B]]): Boolean =
  (lhs: F[B]) <= (tolerance: B)
```

Cats 2.1.1 compiled for Scala 2.13.

## Output

Compiles and results in a `ClassCastException`.

## Expectation

Shouldn't compile. The ascriptions aren't necessary to trigger the bug, I just included them for clarity.

This may be specific to the Scala 2 unpickler. I wasn't able to reproduce it with this pure-Dotty minimization:

```scala
object Foo {

  implicit def toSyntax[A](a: A): Syntax[A] =
    new Syntax[A](a)

  class Syntax[A](self: A) {
    def <=(other: A)(implicit A: Order[A]): Boolean = true
  }

  def test[F[_], B](lhs: F[B], tolerance: B)(implicit ord: Order[F[B]]): Boolean =
    (lhs: F[B]) <= (tolerance: B)
}
```

The above fails to compile, as I would expect.

### PR DESCRIPTION
**Pull request by AleksanderBG**
Should fix #9044, fix #9158, fix #9274.

### CODE REVIEW

**Comment by AleksanderBG** [comment]
There's one remaining problem - I needed to bring back the alternate definition of `recover` in `adaptToSubType`, the one that tries at the absolute end to adapt using GADT approximation (https://github.com/lampepfl/dotty/pull/9322/files#diff-7c63b7bfffa9340fb48ac9b61fa56beeR3461). This turns out to be necessary in only one hyper-concrete example, in the following code:

```
object i7044 {
  case class Seg[T](pat:Pat[T], body:T)

  trait Pat[T]
  object Pat {
    case class Expr()            extends Pat[Int]
    case class Opt[S](el:Pat[S]) extends Pat[Option[S]]
  }

  def test[T](s:Seg[T]):Int = s match {
    case Seg(Pat.Expr(),body)          => body + 1
    case Seg(Pat.Opt(Pat.Expr()),body) => (body: Option[S$1]).get
  }
}
```

The type of `(body: Option[S$1]).get` is `(Option[S$1]#get : => S$1)` (`S$1` is a pattern-bound type). We have `S$1 <: Int`, but for some reason we don't take into account this knowledge during type comparison. The traces are:

```

==> adapting (body:Option[Int]).get to Int 
?
adapt to subtype (Option[Int]#get : => Int) <:< Int
Subtype trace:
  ==> (Option[Int]#get : => Int) <:< Int  
    ==> (Option[Int]#get : => Int) <:< Int recur 
      ==> Int <:< Int LoApprox 
        ==> Int <:< Int recur 
        <== Int <:< Int recur  = true
      <== Int <:< Int LoApprox  = true
    <== (Option[Int]#get : => Int) <:< Int recur  = true
  <== (Option[Int]#get : => Int) <:< Int   = true
 
==> adapting (body:Option[S$1]).get to Int 
?
adapt to subtype (Option[S$1]#get : => S$1) !<:< Int
Subtype trace:
  ==> (Option[S$1]#get : => S$1) <:< Int  
    ==> (Option[S$1]#get : => S$1) <:< Int recur 
    <== (Option[S$1]#get : => S$1) <:< Int recur  = false
  <== (Option[S$1]#get : => S$1) <:< Int   = false
```

And after I wrote all the above, it occurs to me that I should just clench my teeth and take another dive into TypeComparer. @smarter if the above tells you anything that'd save me that dive, I'd be happy to hear it.

**Comment by smarter** [comment]
No clue sorry, but I assume it has something to do with the fact that the result type is `=> S$1` and not `S$1`, so maybe GADT lookup is needed in an extra case related to ExprType.

**Comment by AleksanderBG** [comment]
@smarter can you review? The primary things to take a look at are the explanation comment @ https://github.com/lampepfl/dotty/pull/9322/commits/027d7dd6a6aac4d6bba50c5ee24d4bf15527043a#diff-45a98dd466c5e61cb95404238782f22dR179-R205 and https://github.com/lampepfl/dotty/pull/9322/commits/e09e489ef05eac4b8d478a7e153816ebf7f38175, which fixes the issue with subtyping we discussed.

I'm not certain what to do with https://github.com/lampepfl/dotty/pull/9322/commits/027d7dd6a6aac4d6bba50c5ee24d4bf15527043a#diff-e5c61d67affb377795aa901c89a20cd3. It previously accidentally typechecked because of GADT approximation, but now it doesn't. At the same time, it should typecheck in principle. It started as being a neg test. Should I maybe open an issue for it?

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 1]
```diff
@@ -171,37 +171,47 @@ object Inferencing {
...
+      * relationship _necessarily_ must hold.
+      *
+      * We accomplish that by:
+      *   - replacing covariant occurences with upper GADT bound
+      *   - replacing contravariant occurences with lower GADT bound
+      *   - leaving invariant occurences alone
+      *
+      * Examples:
+      *   - If we have GADT cstr A <: Int, then for all A <: Int, Option[A] <: Option[Int].
+      *     Therefore, we can approximate Option[A] ~~ Option[Int].
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:194]: I'm still concerned about the stuff I mentioned in https://github.com/lampepfl/dotty/issues/9274#issuecomment-653130226, it seems that if I have a method `def foo[T <: X] = ...`, then I immediately get a GADT constraint `T <: X`, and based on this documentation I would guess this means that ApproximateGadtAccumulator will replacing `Option[T]` by `Option[X]`, even though there's no need to do any approximation and nothing GADT related is actually going on?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:194]: OK, I now realize that approximateGADT is only called when the type of the tree is not a subtype of the expected type, so it's probably OK technically, but I think it's confusing and not great for performance that we run this stuff in situations which have nothing to do with GADTs. A few suggestions:
- Add some documentation above the call to approximateGADT in adaptToSubType, describing in what situation this might help (e.g., with a simple example)
- As far as I can tell, the result of the approximation is ignored unless `pt` is a `SelectjonProto` and `ctx.gadt.nonEmpty`, so we should only run the type map when these conditions are true, this is better for performance and for understanding what's going on.
- In https://github.com/lampepfl/dotty/issues/9274 you said:
  >  it's not possible to tell whether a symbol is a type parameter of an enclosing function after descending into its body; therefore, we need to stick those symbols somewhere when we see them and we stick them into GadtConstraint
   Type parameters have the `TypeParam` flag set, and I think method type parameters should always be TypeRefs where the prefix is `NoPrefix`, is that enough?

Comment (AleksanderBG) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:194]: Re. documentation: I'll add the doc to code in `adaptToSubType`. We need to approximate GADTs in `adapt` in order to look up members that should be there b/c of GADT constraints. We cannot take GADT constraints into account when doing normal member lookup b/c of cache. Sample code is https://github.com/lampepfl/dotty/pull/9322/files#diff-70e7287c36d5e6a572c97c2b51613049R1-R9.

Re. lazily performing the approximation: will do, doing it eagerly is a remainder from the old `recover`, which also used the result of approx.

Re. type parameters: key issue is telling whether the type parameters are from an enclosing method, or from somewhere else (i.e. a class?) Now that I think about it, there may be some way of doing so. Question is, do we actually get any performance out of it. I'd prefer to know for sure that there's a performance issue with this code before trying to change it.

Final concern: can you take a look @ https://github.com/lampepfl/dotty/pull/9322/files#diff-1b5c8ce1eaca91d793eef217487d5a59R754 and see whether that change makes sense to you? `isNewSubType` would at most return `false` early before doing the type comparison, so I cannot really see any way that this change is wrong, but at the same time all the justification I have for it is that no test broke and it fixes my issue.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:194]: > Re. type parameters: key issue is telling whether the type parameters are from an enclosing method, or from somewhere else (i.e. a class?)

Check if the owner is a method, type parameters from methods which are not enclosing should not be in scope at all.

> Final concern: can you take a look @ #9322 (files) and see whether that change makes sense to you? 

I guess that usage of isNewSubType was incorrect before? Maybe something worth asking Martin about.

**Comment by AleksanderBG** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -3407,25 +3407,26 @@ class Typer extends Namer
         case _ =>
       }
 
-      val approximation = Inferencing.approximateGADT(wtp)
+      // try GADT approximation, but only if we're trying to select a member
+      // Member lookup cannot take GADTs into account b/c of cache, so we
+      // approximate types based on GADT constraints instead. For an example,
+      // see MemberHealing in gadt-approximation-interaction.scala.
+      lazy val gadtApprox = Inferencing.approximateGADT(wtp)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3414]: I think a lazy val is overkill here, instead I would do something like:
```scala
pt match {
  case pt: SelectionProto if ctx.gadt.nonEmpty =>
    val gadtApprox = Inferencing.approximateGADT(wtp)
    gadts.println(...)
    if (pt.isMatchedBy(gadtApprox))
      return tpd.Typed(tree, TypeTree(gadtApprox))
  case _ =>
}
```

**Comment by AleksanderBG** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 2 above)
Comment (AleksanderBG) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3414]: That doesn't mesh well with the debug statement, which would be best printed both when `pt` is and isn't a `SelectionProto`.

Comment (AleksanderBG) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3414]: If the concern is about performance, I seriously would not care about it unless it shows up in the performance test.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala (hunk 1 above)
Comment (AleksanderBG) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:194]: > > Re. type parameters: key issue is telling whether the type parameters are from an enclosing method, or from somewhere else (i.e. a class?)
> 
> Check if the owner is a method, type parameters from methods which are not enclosing should not be in scope at all.

Yeah, that's what I was thinking about when I said "there may be some way of doing so". I'd still like an indication that we have a performance problem here.

> > Final concern: can you take a look @ #9322 (files) and see whether that change makes sense to you?
> 
> I guess that usage of isNewSubType was incorrect before? Maybe something worth asking Martin about.

@odersky can you take a look at the single line modified in TypeComparer in https://github.com/lampepfl/dotty/pull/9322/files#diff-1b5c8ce1eaca91d793eef217487d5a59R754 and check if the change looks OK to you? The problem that this change fixes is https://github.com/lampepfl/dotty/pull/9322#issuecomment-655570104.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 2 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3414]: No, I'm more concerned by clarity than peformance here, also I'm not convinced that we should print anything when pt is not a selectionproto: if I turn on the GADT printer, I want to see what the GADT logic has been doing, but I don't want my output full of messages about situation where it didn't do anything

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:194]: > I'd still like an indication that we have a performance problem here.

Even if it's not a performance problem, I think it's nicer if GADT code doesn't run when nothing GADT related is going on: it makes it easier to know what code can be safely ignored when trying to understand or debug something, and it makes the output of debug printers easier to read (especially the subtyping printer which is hard enough to follow in the best of situations), but this isn't a blocker for this PR, and if you think it would make the resulting GADT logic too complicated then we can keep the current logic of course.

**Comment by AleksanderBG** [comment]
@smarter I adjusted the logging logic as you suggested, and removed the tree attachment. If you don't have further feedback, I'd merge this PR - since Martin is on vacation I don't think we want to bother him with reviewing a single line + I'm reasonably confident that that change will at most get us into an infinite loop in type comparison, which is somewhat easy to detect.
