### PR TITLE
Fix #9992: Reset toplevel indent region width on left indent

### LINKED ISSUE #9992: Misindent imports produces a confusing error
## Minimized code

```Scala
  import scala.concurrent._

@main def main(): Unit =
  def test = ()
  test
```

## Output

```scala
[error] -- [E018] Syntax Error: /Users/meriamlachkar/perso/dotty/src/main/scala/Show.scala:3:24 
[error] 3 |@main def main(): Unit =
[error]   |                        ^
[error]   |                        expression expected but def found
[error] -- [E080] Syntax Error: /Users/meriamlachkar/perso/dotty/src/main/scala/Show.scala:5:2 
[error] 5 |  test
[error]   |  ^^^^
[error]   |  Expected a toplevel definition
[warn] -- [E129] Potential Issue Warning: /Users/meriamlachkar/perso/dotty/src/main/scala/Show.scala:3:22 
[warn] 3 |@main def main(): Unit =
[warn]   |                      ^
[warn]   |A pure expression does nothing in statement position; you may be omitting necessary parentheses
[warn] one warning found
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation
Fixing the import indentation fixes this error. 
From reading the error message, it's not clear what causes the error.

### PR DESCRIPTION
**Pull request by odersky**
If we start with a toplevel region with greater than 0 indent, and we
find a following line with less indentation, reset the current indentation
width to that smaller number.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Scanners.scala [hunk 1]
```diff
@@ -470,16 +470,16 @@ object Scanners {
       else if indentIsSignificant then
         if nextWidth < lastWidth
            || nextWidth == lastWidth && (indentPrefix == MATCH || indentPrefix == CATCH) && token != CASE then
-          if !currentRegion.isOutermost &&
-             !isLeadingInfixOperator() &&
-             !statCtdTokens.contains(lastToken) then
+          if currentRegion.isOutermost then
+            if nextWidth < lastWidth then currentRegion = topLevelRegion(nextWidth)
+//              report.error("Line is indented too far to the left", sourcePos())
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/parsing/Scanners.scala:475]:
```suggestion
```

**Review by nicolasstucki — APPROVED** [review]
