### PR TITLE
Fix #1959: infix type operators in the REPL

### LINKED ISSUE #1959: Infix types do not work in REPL
```scala
scala> trait +[N1, N2] 
defined trait +
scala> type MyAlias = Int + Int 
<console>:4: error: not found: type +
type MyAlias = Int + Int
```

### PR DESCRIPTION
**Pull request by abeln**
Infix type operators were broken in the REPL.
The REPL uses fold methods from the untpd package,
but those were skipping the operator subtree when folding
over an InfixOp.

Fix the issue by taking the operator into account.

Tested:
1) Verified that only the REPL code uses the modified
fold method.
2) The following interaction now works in the REPL
(used to fail with a 'can't find +' error):

scala> class +[A, B](a: A, B: B)
defined class +
scala> type IntAndString = Int + String
defined type alias IntAndString
scala> new IntAndString(42, "hello world")
val res0: +[Int, String] = $plus@6a472554

### CODE REVIEW

**Comment by abeln** [comment]
This fixes #1959.

**Comment by DarkDimius** [comment]
@abeln, thank you for your contribution, would you please edit commit message to start with 
"Fix #1959: "? It helps a lot when navigating commit history in github.

**Comment by DarkDimius** [comment]
Would you also kindly include a test to repl tests that would track that the issue stays fixed?

**Comment by smarter** [comment]
@abeln Nice catch! Would you mind adding a REPL test? It's pretty easy, you just need to add a file in https://github.com/lampepfl/dotty/tree/master/tests/repl which contains the output of a REPL session.

**Comment by abeln** [comment]
PTAL -- added repl test
thanks for the prompt review!

**Comment by DarkDimius** [comment]
>@abeln, thank you for your contribution, would you please edit commit message to start with
"Fix #1959: "? It helps a lot when navigating commit history in github.

@abeln, could you please update commit message?

**Comment by abeln** [comment]
@DarkDimius oops, sorry -- I'd changed the PR title, but forgot the commit title. PTAL.

File: compiler/src/dotty/tools/dotc/ast/untpd.scala [hunk 1]
```diff
@@ -526,7 +526,7 @@ object untpd extends Trees.Instance[Untyped] with UntypedTreeInfo {
       case Function(args, body) =>
         this(this(x, args), body)
       case InfixOp(left, op, right) =>
-        this(this(x, left), right)
+        this(this(this(x, left), op), right)
       case PostfixOp(od, op) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/untpd.scala]: I haven't checked how `UntypedTreeAccumulator` is used exactly, but if InfixOp folds over the `op`, then surely `PostfixOp` and `PrefixOp` should too?

Comment (abeln) [inline compiler/src/dotty/tools/dotc/ast/untpd.scala]: `UntypedTreeAccumulator` (and its cousing `UntypedDeepFolder`) is used only in the repl code (`CompilingInterpreter.scala`).
Changed `{Post, Pre}fixOp` as well.
PTAL.

**Comment by abeln** [comment]
@DarkDimius friendly ping :)

File: compiler/src/dotty/tools/dotc/ast/untpd.scala [hunk 2]
```diff
@@ -526,11 +526,11 @@ object untpd extends Trees.Instance[Untyped] with UntypedTreeInfo {
...
-        this(x, od)
+        this(this(x, od), op)
       case PrefixOp(op, od) =>
-        this(x, od)
+        this(this(x, op), od)
```
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/ast/untpd.scala]: Would it be possible to expand the test to also test this change?

Comment (abeln) [inline compiler/src/dotty/tools/dotc/ast/untpd.scala]: Does Dotty have prefix type operators? If so, how are they used?
"Regular" prefix operators already worked in the REPL *before* this change: it's a different ast that doesn't end up using the code above.

This is the hypothetical test I'd add, but like I said it's not really exercising this PR.

> scala> class B(val n: Int) {
>         def unary_! = new B(-n)
>        } 
> defined class B
> scala> val x = new B(42) 
> val x: B = B@10e92f8f
> scala> (!x).n 
> val res4: Int = -42

Thoughts?

**Comment by felixmulder** [comment]
Thanks for the contribution! :tada:

File: compiler/src/dotty/tools/dotc/ast/untpd.scala (hunk 2 above)
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/ast/untpd.scala]: Yes, I agree. Let's get this in.
