### PR TITLE
Fix #7525: Allow static methods having body in JavaParser

### LINKED ISSUE #7525: Java Parser doesn't accept empty method
Present in current master as of 8/11/2019

## minimized code

`Interface.java`
```java
public interface Interface {
  static void s() {}
}
```

`dotc Interface.java` errors:
```java
-- Error: Interface.java:2:18 --------------------------------------------------
2 |  static void s() {}
  |                  ^
  |                  ';' expected but '{' found.
-- [E067] Syntax Error: Interface.java:2:14 ------------------------------------
2 |  static void s() {}
  |              ^
  |Declaration of method s not allowed here: only classes can have declared but undefined members
two errors found
```

### PR DESCRIPTION
**Pull request by noti0na1**
Related issue: #7525

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/JavaParsers.scala [hunk 1]
```diff
@@ -521,7 +521,7 @@ object JavaParsers {
           val vparams = formalParams()
           if (!isVoid) rtpt = optArrayBrackets(rtpt)
           optThrows()
-          val bodyOk = !inInterface || (mods.is(Flags.DefaultMethod))
+          val bodyOk = !inInterface || mods.is(Flags.DefaultMethod) || mods.is(Flags.JavaStatic)
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/parsing/JavaParsers.scala]: Thank you for looking at this, perhaps it can be simplified to
```suggestion
          val bodyOk = !inInterface || mods.isOneOf(Flags.DefaultMethod | Flags.JavaStatic)
```

**Comment by bishabosha** [comment]
Otherwise looks good to me :)

File: compiler/src/dotty/tools/dotc/parsing/JavaParsers.scala (hunk 1 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/parsing/JavaParsers.scala]: Done
