### PR TITLE
Fix #4884: Fix handling of bounds of type lambdas

### LINKED ISSUE #4884: Abstract type bound of type member is forgotten?
```Scala
object Test {
  trait A
  trait TestConstructor1 { type F[_ <: A] }
  trait TestConstructor2[D] { type F[_ <: D] }

  val v1: TestConstructor1 => Unit = { f =>
    type P[a <: A] = f.F[a] // OK
  }

  val v2: TestConstructor2[A] => Unit = { f =>
    type P[a <: A] = f.F[a] // Error! Type argument a does not conform to upper bound D
  }
}
```

This compiles in Scala 2.12.1 and does not compile in Dotty 0.8.0. Just reporting this but I might have overlooked some dropped features.

### PR DESCRIPTION
**Pull request by odersky**
Type lambdas have their own type parameters which are correctly transformed during an as-seen-from. The problem was that these type parameters were not always retrieved when computing the type parameters of a higher-kinded type. This used to pick the type parameters of the symbol but that is wrong since it loses as-seen-from information. 

It would be most straightforward to always compute the type parameters of the info instead, but this
runs afoul of cyclic errors. So we have a subtle danse now in `TypeApplications#typeParams` do decide what strategy to use when.

Only last two commits are new wrt #4881.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 1]
```diff
@@ -168,11 +168,16 @@ class TypeApplications(val self: Type) extends AnyVal {
    *  any type parameter that is-rebound by the refinement.
    */
   final def typeParams(implicit ctx: Context): List[TypeParamInfo] = /*>|>*/ track("typeParams") /*<|<*/ {
+    def isTrivial(prefix: Type, tycon: Symbol) = prefix match {
+      case prefix: ThisType => prefix.cls `eq` tycon.owner
+      case NoPrefix => true
+      case _ => false
+    }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: Can we further refine `isTrivial` to cover the case when `prefix` is static?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: I am not sure we want to do this. The purpose of `isTrivial` is to fall back to a special case to avoid cyclic reference errors. It seems we don't need to include static `this` types to achieve this. On the other hand, the `isStatic` test could prompt cyclic references itself.

**Comment by Blaisorblade** [comment]
@odersky I got a new `asSeenFrom` bug by playing with this branch.

```scala
object Test {
  trait A
  trait B
  trait TestConstructor1 { type F[X <: A] <: TestConstructor2[A]
    trait FromSet[C[_ <: A with B]]

    trait MSetLike[X <: A with B, This <: MSet[X] with MSetLike[X, This]] {
      def to[C[X <: A with B] <: MSet[X] with MSetLike[X, C[X]]](fi: FromSet[C]): C[X] = ???
    }
    trait MSet[X <: A with B] extends MSetLike[X, MSet[X]]
    object MSetFactory extends FromSet[MSet]
  }

  trait TestConstructor4[D] {
    trait TestConstructor5[E] {
      trait FromSet[C[_ <: D with E]]

      trait MSetLike[X <: D with E, This <: MSet[X] with MSetLike[X, This]] {
        def to[C[X <: D with E] <: MSet[X] with MSetLike[X, C[X]]](fi: FromSet[C]): C[X] = ???
      }
      trait MSet[X <: D with E] extends MSetLike[X, MSet[X]]
      object MSetFactory extends FromSet[MSet]
    }
  }

  val v1: TestConstructor1 => Unit = { f =>
    type P[a <: A] = f.F[a]

    type P1[c <: C] = f.MSet[c]
      (f.MSetFactory: f.FromSet[f.MSet]): Unit
      (x: P1[C]) => x.to(f.MSetFactory)
  }

  def f3(f: TestConstructor4[A])(g: f.TestConstructor5[B]): Unit = {
    type P1[c <: C] = g.MSet[c]
      (g.MSetFactory: g.FromSet[g.MSet]): Unit
      (x: P1[C]) => x.to(g.MSetFactory)
      (x: P1[C]) => x.to[g.MSet](g.MSetFactory)
  }
}
```

Beware that `x.to(g.MSetFactory)` works in `v1` but not in `f3`.

Misc notes:
- FWIW, that's from some code in `tests/run/colltest5/` that failed when I oversimplified `typeApplications`.
- writing `f3` as a val triggers new #4906, but that seems unrelated.
- the rebase went wrong, #4881 was merged so those commits should disappear.

**Comment by Blaisorblade** [comment]
My actual goal with that test was to stress *both* asSeenFrom *and* a lazy denotation.

It seems likely that the new code will trigger cyclic errors when `tsym.infoOrCompleter` is a `LazyType` but the prefix isn't recognized as trivial. Taking those as errors could be fine (if stable under separate compilation), but none of the relevant tests need tricky `asSeenFrom` use.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -1238,7 +1238,7 @@ class Typer extends Namer
           args = args.take(tparams.length)
```
Comment (Blaisorblade) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: The test failure seems genuinely to appear with this new commit (not with my changes) — everything works with the parent.

```
sbt:dotty> dotc -d out -Ycheck:all tests/pos/t1786-cycle.scala -Yforce-sbt-phases
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running (fork) dotty.tools.dotc.Main -classpath /Users/pgiarrusso/git/dotty/library/../out/bootstrap/dotty-library-bootstrapped/scala-0.10/dotty-library_0.10-0.10.0-bin-SNAPSHOT.jar -d out -Ycheck:all tests/pos/t1786-cycle.scala -Yforce-sbt-phases
checking tests/pos/t1786-cycle.scala after phase frontend
exception occurred while compiling tests/pos/t1786-cycle.scala
Exception in thread "main" dotty.tools.dotc.core.TypeError: bad parameter reference LongTraversableLike#Repr at sbt-deps
the parameter is type Repr in trait LongTraversableLike but the prefix LongTraversableLike
does not define any corresponding arguments.
	at dotty.tools.dotc.core.Types$NamedType.argDenot(Types.scala:1834)
	at dotty.tools.dotc.core.Types$NamedType.fromDesignator$1(Types.scala:1751)
	at dotty.tools.dotc.core.Types$NamedType.computeDenot(Types.scala:1769)
	at dotty.tools.dotc.core.Types$NamedType.denot(Types.scala:1725)
	at dotty.tools.dotc.core.Types$NamedType.info(Types.scala:1714)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector$TypeDependencyTraverser.traverse(ExtractDependencies.scala:422)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4485)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4483)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4469)
	at dotty.tools.dotc.core.Types$TypeTraverser.traverseChildren(Types.scala:4486)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector$TypeDependencyTraverser.traverse(ExtractDependencies.scala:432)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4485)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4483)
	at dotty.tools.dotc.core.Types$TypeAccumulator.$anonfun$foldOver$5(Types.scala:4405)
	at dotty.tools.dotc.core.Types$VariantTraversal.atVariance(Types.scala:3942)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4405)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4409)
	at dotty.tools.dotc.core.Types$TypeTraverser.traverseChildren(Types.scala:4486)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector$TypeDependencyTraverser.traverse(ExtractDependencies.scala:432)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4485)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4483)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4435)
	at dotty.tools.dotc.core.Types$TypeTraverser.traverseChildren(Types.scala:4486)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector$TypeDependencyTraverser.traverse(ExtractDependencies.scala:432)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector$TypeDependencyTraverser.traverse(ExtractDependencies.scala:422)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4485)
	at dotty.tools.dotc.core.Types$TypeTraverser.apply(Types.scala:4483)
	at dotty.tools.dotc.core.Types$TypeAccumulator.$anonfun$foldOver$5(Types.scala:4405)
	at dotty.tools.dotc.core.Types$VariantTraversal.atVariance(Types.scala:3942)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4405)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4409)
	at dotty.tools.dotc.core.Types$TypeTraverser.traverseChildren(Types.scala:4486)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector$TypeDependencyTraverser.traverse(ExtractDependencies.scala:432)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.addTypeDependency(ExtractDependencies.scala:441)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:354)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1415)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1413)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1321)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1416)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:373)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1415)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1413)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1335)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1416)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:373)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1415)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1413)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.$anonfun$apply$1(Trees.scala:1297)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1297)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1333)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1416)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:373)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.$anonfun$traverse$3(ExtractDependencies.scala:371)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.$anonfun$traverse$3$adapted(ExtractDependencies.scala:371)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:371)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1415)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1413)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1377)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1416)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:373)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1415)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1413)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.$anonfun$apply$1(Trees.scala:1297)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1297)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1383)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1416)
	at dotty.tools.dotc.sbt.ExtractDependenciesCollector.traverse(ExtractDependencies.scala:373)
	at dotty.tools.dotc.sbt.ExtractDependencies.run(ExtractDependencies.scala:65)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:298)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:296)
	at dotty.tools.dotc.core.Phases$Phase.runOn$(Phases.scala:295)
	at dotty.tools.dotc.sbt.ExtractDependencies.runOn(ExtractDependencies.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:175)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:49)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:172)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:170)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:170)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:195)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:90)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:150)
	at dotty.tools.dotc.Run.compileSources(Run.scala:137)
	at dotty.tools.dotc.Run.compile(Run.scala:121)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:31)
	at dotty.tools.dotc.Driver.process(Driver.scala:134)
	at dotty.tools.dotc.Driver.process(Driver.scala:103)
	at dotty.tools.dotc.Driver.process(Driver.scala:115)
	at dotty.tools.dotc.Driver.main(Driver.scala:142)
	at dotty.tools.dotc.Main.main(Main.scala)
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -1259,10 +1260,10 @@ class Typer extends Namer
                 // An unbounded `_` automatically adapts to type parameter bounds. This means:
                 // If we have wildcard application C[_], where `C` is a class replace
                 // with C[_ >: L <: H] where `L` and `H` are the bounds of the corresponding
-                // type parameter in `C`, avoiding any referemces to parameters of `C`.
-                // The transform does not apply for patters, where empty bounds translate to
+                // type parameter in `C`.
+                // The transform does not apply for patterns, where empty bounds translate to
                 // wildcard identifiers `_` instead.
-                res = res.withType(avoid(tparam.paramInfo, tpt1.tpe.typeParamSymbols))
+                res = res.withType(tparamBounds)
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Yes, I believe that's correct.

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 4]
```diff
@@ -168,11 +168,16 @@ class TypeApplications(val self: Type) extends AnyVal {
...
     try self match {
       case self: TypeRef =>
         val tsym = self.symbol
         if (tsym.isClass) tsym.typeParams
-        else if (!tsym.exists) self.info.typeParams
+        else if (!tsym.exists || !isTrivial(self.prefix, tsym)) self.info.typeParams
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: There will always be cyclic errors. The challenge is to reduce them sufficiently that 

 - they occur only rarely
 - they can be communicated so that they make sense to the user
 - there is a way to work around them

and, probably most importantly

 - they don't break existing code. What worked with the current compiler should continue working.

So it's really quite fuzzy. Ideally, we should have a spec that says in exactly what situations cyclic errors are OK. But we are currently quite far away from this point. I believe most mainstream languages that allow unlimited recursion face the same fundamental problem.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: This is fixed in the latest commit.

**Comment by odersky** [comment]
@Blaisorblade 

> @odersky I got a new asSeenFrom bug by playing with this branch.

There are several undefined identifiers in the example as given. Can you check again?

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 5]
```diff
@@ -177,10 +177,9 @@ class TypeApplications(val self: Type) extends AnyVal {
       case self: TypeRef =>
         val tsym = self.symbol
         if (tsym.isClass) tsym.typeParams
-        else if (!tsym.exists || !isTrivial(self.prefix, tsym)) self.info.typeParams
         else tsym.infoOrCompleter match {
-          case info: LazyType => info.completerTypeParams(tsym)
-          case info => info.typeParams
+          case info: LazyType if tsym.exists && isTrivial(self.prefix, tsym) => info.completerTypeParams(tsym)
+          case _ => self.info.typeParams
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: Why change this line from `case info => info.typeParams`? If the info is already computed I would just reuse it

**Comment by Blaisorblade** [comment]
@odersky My example still doesn't work; sorry for the copy-paste mistakes, fixed them. Here are the errors I get:
```
- [E007] Type Mismatch Error: tests/pos/i4884c.scala:37:9 ---------------------
37 |      (g.MSetFactory: g.FromSet[g.MSet]): Unit
   |       ^^^^^^^^^^^^^
   |       found:    g.MSetFactory.type
   |       required: g.FromSet[g.MSet]
   |
-- [E007] Type Mismatch Error: tests/pos/i4884c.scala:38:27 --------------------
38 |      (x: P1[C]) => x.to(g.MSetFactory)
   |                         ^^^^^^^^^^^^^
   |                         found:    g.MSetFactory.type
   |                         required: g.FromSet[g.MSet]
   |
-- [E007] Type Mismatch Error: tests/pos/i4884c.scala:39:35 --------------------
39 |      (x: P1[C]) => x.to[g.MSet](g.MSetFactory)
   |                                 ^^^^^^^^^^^^^
   |                                 found:    g.MSetFactory.type
   |                                 required: g.FromSet[g.MSet]
   |
three errors found
```

**Comment by odersky** [comment]
Let's make a separate issue for the new error.

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala (hunk 5 above)
Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: To clarify (for @allanrenucci and future readers): if `tsym.exists && isTrivial(self.prefix, tsym)`, `self.info.typeParams` and `info.typeParams` should coincide and `self.info.typeParams` is more clearly right, so I tried to simplify things.

**Comment by Blaisorblade** [comment]
OK, filed #4908.

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala (hunk 5 above)
Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: Actually I tried: `info.typeParams` and `self.info.typeParams` are not equivalent, the newly added test was failing. I think this is because in the former, `info` may refer to the completer

Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: They’re only equivalent under those conditions, not in this pattern match branch.
I know that my commit didn’t change behavior in any scenario I tested with.
To play with this, you can go to the parent commit and replace info.typeParams with self.info.typeParams.
