### PR TITLE
Fix spurious subtype check pruning when both sides have unions

### LINKED ISSUE #17465: Error in `-Ycheck:typer` when refining String on StringOps defs
## Compiler version
3.3.0-RC4

## Minimized code
Compile this code with the `-Ycheck:typer` flag.
```Scala
import reflect.Selectable.reflectiveSelectable

trait A[T](x: T{ def *(y: Int): T }):
  def f: T = x * 2

class B extends A("Hello")
```

Edit: further minimization (thanks to @nicolasstucki):
```Scala
import reflect.Selectable.reflectiveSelectable
def f[T](x: T{ def *(y: Int): T }): T = x * 2
def test = f[scala.collection.StringOps | String]("Hello")
```

## Output
```
checking a.scala after phase typer

  exception while retyping new A[scala.collection.StringOps | String](augmentString("Hello")) of class Apply # -1

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/lampepfl/dotty/issues/new/choose

     while compiling: a.scala
        during phase: typer
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.10
    compiler version: version 3.3.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-b3643ee
            settings: -Ycheck List(typer) -classpath C:\Users\Tim\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.10\scala-library-2.13.10.jar;D:\Bureau\dotty\library\..\out\bootstrap\scala3-library-bootstrapped\scala-3.3.1-RC1-bin-SNAPSHOT-nonbootstrapped\scala3-library_3-3.3.1-RC1-bin-SNAPSHOT.jar

                tree: PackageDef(object <empty>)
       tree position: a.scala:1:0
           tree type: <empty>.type
              symbol: package <empty>
   symbol definition: final lazy module object <empty>: <empty> (a Symbol)
      symbol package: <root>
       symbol owners:
           call site: constructor B in class B in module class <empty>

  == Source file context for tree position ==

-- Error: a.scala:1:0 --------------------------------------------------------------------------------------------------
1 |import reflect.Selectable.reflectiveSelectable
  |^

2 |trait A[T](x: T{ def *(y: Int): T }):
3 |  def f: T = x * 2
4 |class B extends A("Hello")
*** error while checking a.scala after phase typer ***
Exception in thread "main" java.lang.AssertionError: assertion failed: Types differ
Original type : (x: (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}):
  A[scala.collection.StringOps | String]
After checking: (x: (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}):
  A[scala.collection.StringOps | String]
Original tree : new A[scala.collection.StringOps | String]
After checking: new A[scala.collection.StringOps | String]
Why different :
             Subtype trace:
   A[scala.collection.StringOps | String]  <:  (x: (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}):
    ==> (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String} in frozen constraint
      ==> (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  scala.collection.StringOps | String in frozen constraint
        ==> (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  scala.collection.StringOps | String in frozen constraint
          ==> (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  scala.collection.StringOps in frozen constraint
            ==> lub(scala.collection.StringOps, <notype>, canConstrain=false, isSoft=true)
            <== lub(scala.collection.StringOps, <notype>, canConstrain=false, isSoft=true) = <notype>
          <== (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  scala.collection.StringOps in frozen constraint = false
          ==> (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  String in frozen constraint
            ==> lub(<notype>, String, canConstrain=false, isSoft=true)
            <== lub(<notype>, String, canConstrain=false, isSoft=true) = <notype>
          <== (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  String in frozen constraint = false
        <== (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  scala.collection.StringOps | String in frozen constraint = false
      <== (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  scala.collection.StringOps | String in frozen constraint = false
    <== (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}  <:  (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String} in frozen constraint = false
   A[scala.collection.StringOps | String] = false: (scala.collection.StringOps | String){def *(y: Int): scala.collection.StringOps | String}):
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:408)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3175)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3179)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3291)
        at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:941)
        at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1101)
        at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:352)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedApply(TreeChecker.scala:501)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3040)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3103)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3175)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3179)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3291)
        at dotty.tools.dotc.typer.Typer.typedParent$1(Typer.scala:2560)
        at dotty.tools.dotc.typer.Typer.$anonfun$58(Typer.scala:2644)
        at dotty.tools.dotc.core.Decorators$.loop$1(Decorators.scala:94)
        at dotty.tools.dotc.core.Decorators$.mapconserve(Decorators.scala:110)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2644)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:567)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3028)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3032)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3102)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3175)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3179)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3201)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3247)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:632)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2804)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedPackageDef(TreeChecker.scala:658)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3073)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3103)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3175)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3179)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3291)
        at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:126)
        at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:106)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:324)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:328)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:246)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:262)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:270)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:279)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:279)
        at dotty.tools.dotc.Run.compileSources(Run.scala:194)
        at dotty.tools.dotc.Run.compile(Run.scala:179)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:197)
        at dotty.tools.dotc.Driver.process(Driver.scala:165)
        at dotty.tools.dotc.Driver.process(Driver.scala:177)
        at dotty.tools.dotc.Driver.main(Driver.scala:207)
        at dotty.tools.dotc.Main.main(Main.scala)
```

## Expectation
The code compiles both with and without the `-Ycheck:typer` flag.

## More information
This seems to be related to the widening of `String` to `scala.collection.StringOps | String`, as this issue does not arise with a homemade class: the following code passes the check.
```Scala
import reflect.Selectable.reflectiveSelectable

class C:
  def *(y: Int): C = this

trait A[T](x: T{ def *(y: Int): T }):
  def f: T = x * 2

class B extends A(new C())
```

### PR DESCRIPTION
**Pull request by Linyxus**
Fixes #17465.

In TypeComparer, `fourthTry` calls `isNewSubType` and `isCovered` to detect the subtype queries that have been covered by previous attempts and prune them. However, the pruning is spurious when both sides contain union types, as exemplified by the following subtype trace before the PR:
```
==> isSubType (test1 : (Int | String){def foo(x: Int): Int}) <:< Int | String?
  ==> isSubType (Int | String){def foo(x: Int): Int} <:< Int | String?
    ==> isSubType (Int | String){def foo(x: Int): Int} <:< Int?
    <== isSubType (Int | String){def foo(x: Int): Int} <:< Int = false
    ==> isSubType (Int | String){def foo(x: Int): Int} <:< String?
      ==> isSubType (Int | String){def foo(x: Int): Int} <:< String?
      <== isSubType (Int | String){def foo(x: Int): Int} <:< String = false
    <== isSubType (Int | String){def foo(x: Int): Int} <:< String = false
    // (1): follow-up subtype checks are pruned here by isNewSubType
  <== isSubType (Int | String){def foo(x: Int): Int} <:< Int | String = false
<== isSubType (test1 : (Int | String){def foo(x: Int): Int}) <:< Int | String = false
```
At `(1)`, the pruning condition is met, and follow-up recursions are skipped. However, in this case, only after `(1)` are the refinement on LHS dropped and the subtype between two identical OrTypes are accepted. The pruning is spurious.

This PR tempers the pruning conditions specified in `isCovered` and `isNewSubType` to fix these false negatives.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -1479,9 +1479,39 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+     *  combiners are AppliedTypes, RefinedTypes, RecTypes, And/Or-Types or AnnotatedTypes.
+     *
+     *  The exception is that if both sides contain OrTypes, the check hasn't been covered.
+     *  See #17465.
      */
     def isNewSubType(tp1: Type): Boolean =
-      if (isCovered(tp1) && isCovered(tp2))
+
+      def isCovered(tp: Type): (Boolean, Boolean) =
+        var containsOr: Boolean = false
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1493]: This entails an allocation since variables accessed from local functions are heap allocated

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -1479,9 +1479,39 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+                recur(tp.tp1 :: tp.tp2 :: todos)
+              case _ => false
+          case Nil => true
+        val result = recur(tp :: Nil)
+        (result, containsOr)
+
+      val (covered1, hasOr1) = isCovered(tp1)
+      val (covered2, hasOr2) = isCovered(tp2)
+
+      if covered1 && covered2 && !(hasOr1 && hasOr2) then
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1514]: So total, 4 allocations. We should avoid them in subtype checks, where possible. 

Techniques do so:

 - Instead of a variable, pass a second parameter to `recur`.
 - Use an enum instead of a pair of booleans. We need three states: `Uncovered, CoveredWithOr, Covered`

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -1479,9 +1479,39 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+     *
+     *  The exception is that if both sides contain OrTypes, the check hasn't been covered.
+     *  See #17465.
      */
     def isNewSubType(tp1: Type): Boolean =
-      if (isCovered(tp1) && isCovered(tp2))
+
+      def isCovered(tp: Type): (Boolean, Boolean) =
+        var containsOr: Boolean = false
+        @annotation.tailrec def recur(todos: List[Type]): Boolean = todos match
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1494]: Why recur over a list if types?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 4]
```diff
@@ -1479,9 +1479,39 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+          case tp :: todos =>
+            tp.dealiasKeepRefiningAnnots.stripTypeVar match
+              case tp: TypeRef =>
+                if tp.symbol.isClass && tp.symbol != NothingClass && tp.symbol != NullClass then recur(todos)
+                else false
+              case tp: AppliedType => recur(tp.tycon :: todos)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1500]: These nested recurrences might show up to be really expensive. Why do we need them?

**Review by odersky — CHANGES_REQUESTED** [review]
I believe this needs a better justification why expensive recursion operations are needed and some reworking to avoid allocations.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 4 above)
Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1500]: The recursion is equivalent to the one before. I refactored it to take a list of types, which is essentially a working list of recursive invocations, to make the function tail-recursive. I thought that this saves the stack and could lead to better performance, but I could revert this refactorization to avoid passing around a list during recursion and creating a new list object at each new invocation.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1500]: Previously we did not recurse in arguments of `AppliedTypes`, just in the type constructor. That's the one I would expect to matter most. 

Generally, I think using stack is cheaper than allocating.

Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1500]: Here we are not recursing on the arguments of the `AppliedType`: note that the `todos` is the working list, not the arguments of the `AppliedType`.

Thanks for pointing this out! I will revert this rewriting, and in the future I'll prefer reducing heap allocations over achieving tail recursion.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1500]: Ah, right, I had misread that!

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1500]: In fact, maybe it's simplest to just use `Int`s as the result of `recur`. Then `&&` could be replaced by `min`.

Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Yes, I just pushed the [commit](https://github.com/lampepfl/dotty/pull/18213/commits/380bd1b91a6ca0edbf4a555ea48455bdd221c5a5) that reverts the tailrec rewriting and uses an integer-based representation for the result of `isCovered`, interpreted bit-wisely. `min` is used to aggregate results as you suggested. (A bitwise `&` was first used for aggregation but later I found that `min` is more logical). We use bitwise operations to analyze the results as well.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 5]
```diff
@@ -2991,6 +2996,31 @@ object TypeComparer {
...
+    val CoveredWithOr: Repr = 2
+
+    /** The type is covered and free from OrTypes. */
+    val Covered: Repr = 3
+
+    object Repr:
+      extension (s: Repr)
+        inline def combinedWith(that: Repr): Repr = s min that
+
+    inline def bothHaveOr(s1: Repr, s2: Repr): Boolean = ~(s1 | s2 & NotHasOr) != 0
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3019]: That's a whole lot of inverters!  The most popular `!`, the domain-specific `Not`, and the bitwise lurker `~`!

The precedence is wrong here, no?  Don't you want
```suggestion
    inline def bothHaveOr(s1: Repr, s2: Repr): Boolean = ~((s1 | s2) & NotHasOr) != 0
```

Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Thanks Dale! You're right, I was assuming the wrong precedence.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 6]
```diff
@@ -1479,9 +1479,27 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+     *  combiners are AppliedTypes, RefinedTypes, RecTypes, And/Or-Types or AnnotatedTypes.
+     *
+     *  The exception is that if both sides contain OrTypes, the check hasn't been covered.
+     *  See #17465.
      */
     def isNewSubType(tp1: Type): Boolean =
-      if (isCovered(tp1) && isCovered(tp2))
+      def isCovered(tp: Type): CoveredStatus =
+        tp.dealiasKeepRefiningAnnots.stripTypeVar match
+          case tp: TypeRef if tp.symbol.isClass && tp.symbol != NothingClass && tp.symbol != NullClass => CoveredStatus.Covered
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1493]:
```suggestion
          case tp: TypeRef =>
            if tp.symbol.isClass && tp.symbol != NothingClass && tp.symbol != NullClass
            then CoveredStatus.Covered
            else CoveredStatus.Uncovered
```
It's a bit faster since it does not try the other patterns in case of a non-class TypeRef.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 7]
```diff
@@ -2991,6 +2996,33 @@ object TypeComparer {
...
+    /** The type is covered and free from OrTypes. */
+    val Covered: Repr = 3
+
+    object Repr:
+      extension (s: Repr)
+        def combinedWith(that: => Repr): Repr =
+          if s == Uncovered then Uncovered
+          else s min that
+
+    inline def bothHaveOr(s1: Repr, s2: Repr): Boolean = ~((s1 | s2) & NotHasOr) != 0
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3021]:
```suggestion
    inline def bothHaveOr(s1: Repr, s2: Repr): Boolean = s1 == CoveredWithOr && s2 == CoveredWithOr 
```
Or just inline the rhs where it is used.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 8]
```diff
@@ -2991,6 +2996,33 @@ object TypeComparer {
...
+    inline def bothCovered(s1: Repr, s2: Repr): Boolean = (s1 & s2 & IsCovered) != 0
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3022]:
```suggestion
    inline def bothCovered(s1: Repr, s2: Repr): Boolean = s1 >= CoveredWithOr && s2 >= CoveredWithOr
```
Or just inline rhs at the point of use.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3022]: Then you don't need the isCovered and NotHasOr fields. Better not to be too clever with bitsets unless it really gains performance - it's easy to get these wrong, and is generally harder to read than straight comparisons.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 9]
```diff
@@ -1479,9 +1479,27 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+          case tp: TypeRef if tp.symbol.isClass && tp.symbol != NothingClass && tp.symbol != NullClass => CoveredStatus.Covered
+          case tp: AppliedType => isCovered(tp.tycon)
+          case tp: RefinedOrRecType => isCovered(tp.parent)
+          case tp: AndType => isCovered(tp.tp1) combinedWith isCovered(tp.tp2)
+          case tp: OrType  => isCovered(tp.tp1) combinedWith isCovered(tp.tp2)
+          case _ => CoveredStatus.Uncovered
+
+      val covered1 = isCovered(tp1)
+      val covered2 = isCovered(tp2)
+      if CoveredStatus.bothCovered(covered1, covered2) && !CoveredStatus.bothHaveOr(covered1, covered2) then
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1502]:
```suggestion
      if (convered1 min covered2) >= ConveredStatus.CoveredWithOr && (covered1 max covered2) = ConveredStatus.Covered then
```
Then no helper functions are needed, and it's still quite clear, I think.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 10]
```diff
@@ -2991,6 +2996,33 @@ object TypeComparer {
   end ApproxState
   type ApproxState = ApproxState.Repr
 
+  /** Result of `isCovered` check. */
+  object CoveredStatus:
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3000]: Can be private

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 11]
```diff
@@ -2991,6 +2996,33 @@ object TypeComparer {
...
+    opaque type Repr = Int
+
+    private inline val IsCovered = 2
+    private inline val NotHasOr = 1
+
+    /** The type is not covered. */
+    val Uncovered: Repr = 1
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3007]: Style: In this case I'd write the three vals on subsequent lines with // comments to the right. It's more compact taht way and just as legible.

**Review by odersky — COMMENTED** [review]
Style comments only. Otherwise all LGTM

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 9 above)
Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Yes, that's much simpler and clearer. Thanks!

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 12]
```diff
@@ -2991,6 +2999,19 @@ object TypeComparer {
   end ApproxState
   type ApproxState = ApproxState.Repr
 
+  /** Result of `isCovered` check. */
+  private object CoveredStatus:
+    type Repr = Int
+
+    private inline val IsCovered = 2
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:3006]: These two are no longer needed.

**Review by odersky — APPROVED** [review]
Otherwise LGTM
