### PR TITLE
Fix #1441: init MODULE$ in <clinit> 

### LINKED ISSUE #1441: JDK9 blocker: stops supporting our scheme for MODULE$ initialization
https://bugs.openjdk.java.net/browse/JDK-8159215

the way we currently compile module classes, assigns the static _final_ MODULE$ from the module class constructor `<init>` which is called by `<clinit>`. This is prohibited by the spec and will be enforced by JDK9.

```
./scala-2.11.8/bin/scala
Exception in thread "main" java.lang.IllegalAccessError: Update to static final field scala.tools.nsc.MainGenericRunner$.MODULE$ attempted from a different method (scala.tools.nsc.MainGenericRunner$) than the initializer method <clinit>
        at scala.tools.nsc.MainGenericRunner$.<init>(MainGenericRunner.scala:102)
        at scala.tools.nsc.MainGenericRunner$.<clinit>(MainGenericRunner.scala)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

If they enforce the restriction and we move the initializers to the only allowed place, `<clinit>`, following code will _always_ throw NPE.

``` scala
class Super {
  Object.foo
}

object Singleton extends Super {

 def foo = 1

 // <clinit> -> new Singleton
 // <init> MODULE$ = this
}
```

Reported by Zoltán Majó. We have discussed the issue. The JDK product team seems have decided that this change is to stay. What it means, is that code compiled both by dotty and Scala cannot use bytecode version 53, unless we drop the `final` flag on all `MODULE$`.

PING @adriaanm, @lrytz, @retronym. I'll keep you informed on progress.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #1441: init $MODULE in `<clinit>`

Related: https://github.com/lampepfl/dotty/issues/5928 #8652

### CODE REVIEW

**Comment by odersky** [comment]
Good work: For generating super accessors you can use `AccessProxies`. It already contains most of the logic to produce protected and inline accessors, which can be shared.

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 1]
```diff
@@ -36,7 +36,7 @@ class ScalaSettings extends Settings.SettingGroup {
   val color: Setting[String] = ChoiceSetting("-color", "mode", "Colored output", List("always", "never"/*, "auto"*/), "always"/* "auto"*/) withAbbreviation "--color"
   val source: Setting[String] = ChoiceSetting("-source", "source version", "source version", List("3.0", "3.1", "3.0-migration", "3.1-migration"), "3.0").withAbbreviation("--source")
   val target: Setting[String] = ChoiceSetting("-target", "target", "Target platform for object files. All JVM 1.5 targets are deprecated.",
-    List("jvm-1.5", "jvm-1.5-fjbg", "jvm-1.5-asm", "jvm-1.6", "jvm-1.7", "jvm-1.8", "msil"), "jvm-1.8") withAbbreviation "--target"
+    List("jvm-1.5", "jvm-1.5-fjbg", "jvm-1.5-asm", "jvm-1.6", "jvm-1.7", "jvm-1.8", "jvm-9", "msil"), "jvm-1.8") withAbbreviation "--target"
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala:39]: While you're at it, you could also remove all the options except jvm-1.8 and jvm-9 since they never worked in dotty (there's even `msil` which is supposed to generate .NET bytecode!)

File: compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala [hunk 2]
```diff
@@ -106,14 +109,82 @@ trait BCodeSkelBuilder extends BCodeHelpers {
...
 
-      val methodSymbols = for (f <- cd.symbol.info.decls.toList if f.is(Method) && f.isTerm && !f.is(Module)) yield f
-      val hasStaticCtor = methodSymbols exists (_.isStaticConstructor)
-      if (!hasStaticCtor) {
-        // but needs one ...
-        if (isCZStaticModule || isCZParcelable) {
-          fabricateStaticInit()
+      val cd = if (isCZStaticModule) {
+        // Move statements from the primary constructor following the superclass constructor call to
+        // a newly synthesised tree representing the "<clinit>", which also assigns the MODULE$ field.
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala:114]: Do you think this could be done in a mini-phase just before the backend?

Comment (smarter) [reply compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala:114]: > Do you think this could be done in a mini-phase just before the backend?

Actually that might not be a goo idea if it interfers with scala.js/native like with https://github.com/lampepfl/dotty/pull/8652/commits/08a1ca0e6581ca997115ce1d483efa20d61427a4#r456815962, wdyt @sjrd ?

Comment (sjrd) [reply compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala:114]: Ah yes, moving that before the back-end would make things significantly more complicated for Scala.js and Native. Both have a first-class concept of `ModuleClass`, and encode the singleton pattern of `MODULE$` in a completely different way. In the Scala.js IR, there even isn't anything that corresponds to `MODULE$` per se.

So if you move this before the back-end, then Scala.js and Scala Native will have to reverse all the effects of this transformation, which would be counter-productive.

File: compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala [hunk 3]
```diff
@@ -702,33 +706,18 @@ trait BCodeBodyBuilder extends BCodeSkelBuilder {
...
           // 'super' call: Note: since constructors are supposed to
           // return an instance of what they construct, we have to take
           // special care. On JVM they are 'void', and Scala forbids (syntactically)
           // to call super constructors explicitly and/or use their 'returned' value.
           // therefore, we can ignore this fact, and generate code that leaves nothing
           // on the stack (contrary to what the type in the AST says).
-          mnode.visitVarInsn(asm.Opcodes.ALOAD, 0)
+
+          // scala/bug#10290: qual can be `this.$outer()` (not just `this`), so we call genLoad (not just ALOAD_0)
+          genLoad(superQual)
```
Comment (sjrd) [inline compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:718]: Since you are doing this for the JVM back-end, could you also apply the appropriate fix in the SJS back-end?

The code to fix is at
https://github.com/lampepfl/dotty/blob/6ada79cfe3f736b3d00c7f47882d4e023a053976/compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala#L1391-L1401
to be updated similarly to what was done for scalac at
https://github.com/scala-js/scala-js/commit/e02799b636b577eb56593d08c21a7cb2e68719e8#diff-c9a195a739d51194e79f0655bc93bd61R2343-R2363
and you can enable the `RegressionTest.scala` test (i.e., remove it from the blacklist) to test the fix at
https://github.com/lampepfl/dotty/blob/6ada79cfe3f736b3d00c7f47882d4e023a053976/project/Build.scala#L1024

Comment (liufengyun) [reply compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:718]: Thanks for the detailed instruction @sjrd, I'll do that.

Comment (liufengyun) [reply compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:719]: @sjrd FYI, in this PR (unlike scalac), the `qual` in a `Super` is still `this`, it's only in the backend phase where the invariant is broken. Do you think the changes proposed above are still relevant?

Comment (liufengyun) [reply compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:719]: Actually we can enrich the `-Ycheck` to make sure it's always a compiler invariant. Do you think it's a good idea @smarter ?

Comment (smarter) [reply compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:719]: Sounds good to me.

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 4]
```diff
@@ -35,8 +35,7 @@ class ScalaSettings extends Settings.SettingGroup {
   val help: Setting[Boolean] = BooleanSetting("-help", "Print a synopsis of standard options.") withAbbreviation "--help"
   val color: Setting[String] = ChoiceSetting("-color", "mode", "Colored output", List("always", "never"/*, "auto"*/), "always"/* "auto"*/) withAbbreviation "--color"
   val source: Setting[String] = ChoiceSetting("-source", "source version", "source version", List("3.0", "3.1", "3.0-migration", "3.1-migration"), "3.0").withAbbreviation("--source")
-  val target: Setting[String] = ChoiceSetting("-target", "target", "Target platform for object files. All JVM 1.5 targets are deprecated.",
-    List("jvm-1.5", "jvm-1.5-fjbg", "jvm-1.5-asm", "jvm-1.6", "jvm-1.7", "jvm-1.8", "jvm-9", "msil"), "jvm-1.8") withAbbreviation "--target"
+  val target: Setting[String] = ChoiceSetting("-target", "target", "Target platform for object files. All JVM 1.5 targets are deprecated.", List("jvm-1.8", "jvm-9"), "jvm-1.8") withAbbreviation "--target"
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala:38]:
```suggestion
  val target: Setting[String] = ChoiceSetting("-target", "target", "Target platform for object files.", List("jvm-1.8", "jvm-9"), "jvm-1.8") withAbbreviation "--target"
```

File: compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala (hunk 3 above)
Comment (sjrd) [reply compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:719]: > @sjrd FYI, in this PR (unlike scalac), the `qual` in a `Super` is still `this`, it's only in the backend phase where the invariant is broken. Do you think the changes proposed above are still relevant?

The proposed changes are direct equivalent of the changes you made to the JVM back-end, but in terms of SJSIR. So if the changes you made are relevant for the JVM (which I assume is true since you did them), then the proposed changes for the JS back-end are also relevant.

File: compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala [hunk 5]
```diff
@@ -1397,8 +1397,11 @@ class JSCodeGen()(using genCtx: Context) {
     } else /*if (isScalaJSDefinedJSClass(currentClassSym)) {
       genJSSuperCall(tree, isStat)
     } else*/ {
+      /* #3013 `qual` can be `this.$outer()` in some cases since Scala 2.12,
+       * so we call `genExpr(qual)`, not just `genThis()`.
+       */
       val superCall = genApplyMethodStatically(
-          genThis()(sup.span), sym, genActualArgs(sym, args))
+          genExpr(qual), sym, genActualArgs(sym, args))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala]: @sjrd The change causes non-termination in existing tests (not `RegressionTest.scala`). Any ideas?

Comment (sjrd) [reply compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala]: Hum. If I apply the same change on `master`, I can successfully run all existing tests (but not `RegressionTest.scala`). So it seems that it is related to other changes in this PR. :s

Comment (sjrd) [reply compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala]: Perhaps this has to do with the fact that the JVM back-end uses `DesugaredSelect` instead of `Select`. `DesugaredSelect` is a helper in `DottyBackendInterface` that turns an `Ident` whose `tpe` is a prefix type into a `Select`.

If this becomes too complicated, drop the Scala.js part, and I'll have a look once this PR is merged.

Comment (liufengyun) [reply compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala:1404]: Now it works after rebase, without using `DesugaredSelect`. The `RegressionTest.scala` test causes non-termination, so I didn't enable it.

Comment (sjrd) [reply compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala:1404]: Cool thank you :)

File: compiler/src/dotty/tools/backend/jvm/BCodeIdiomatic.scala [hunk 6]
```diff
@@ -29,6 +29,7 @@ trait BCodeIdiomatic {
     case "jvm-1.6"     => asm.Opcodes.V1_6
     case "jvm-1.7"     => asm.Opcodes.V1_7
     case "jvm-1.8"     => asm.Opcodes.V1_8
+    case "jvm-9"       => asm.Opcodes.V9
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/BCodeIdiomatic.scala:32]: It looks like we don't have testcases which are run with `-target jvm-9` currently, that would be very useful to validate that the changes in this PR indeed work correclty on Java 9 (since these tests can't be run on Java 8, they'll need to be excluded by default and only enabled in the CI when we run Java 11)

File: compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala [hunk 7]
```diff
@@ -107,14 +110,92 @@ trait BCodeSkelBuilder extends BCodeHelpers {
...
+        // moving that before the back-end would make things significantly more complicated for
+        // Scala.js and Native. Both have a first-class concept of ModuleClass, and encode the
+        // singleton pattern of MODULE$ in a completely different way. In the Scala.js IR, there
+        // even isn't anything that corresponds to MODULE$ per se.
+        //
+        // So if you move this before the back-end, then Scala.js and Scala Native will have to
+        // reverse all the effects of this transformation, which would be counter-productive.
+
+
+        // TODO: enable once we change lazy val encoding
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala:132]: To not forget about this, I suggest explaining this issue in https://github.com/lampepfl/dotty/issues/7140 and leaving a link to it here (also I'm surprised that this doesn't cause other issues on Java 9)i

**Comment by smarter** [comment]
test performance please

File: compiler/test/dotty/tools/vulpix/TestConfiguration.scala [hunk 8]
```diff
@@ -76,4 +77,19 @@ object TestConfiguration {
 
   /** Enables explicit nulls */
   val explicitNullsOptions = defaultOptions and "-Yexplicit-nulls"
+
+  /** Default target of the generated class files */
+  private def defaultTarget: String = {
+    import dotty.tools.dotc.config.Properties.javaVersion
+    val version: Int =
```
Comment (smarter) [inline compiler/test/dotty/tools/vulpix/TestConfiguration.scala:84]: scala.util.Properties contains `isJavaAtLeast`

Comment (liufengyun) [reply compiler/test/dotty/tools/vulpix/TestConfiguration.scala:84]: Thanks for the tip 👍

**Comment by liufengyun** [comment]
@smarter This is finally green, could you please have another look?

**Comment by liufengyun** [comment]
@nicolasstucki The classpath handling in dotty-staging does not work well with Java 11 11560cb. Any ideas?

**Comment by nicolasstucki** [comment]
Maybe something to do with the class loader 

https://github.com/lampepfl/dotty/blob/2ab9a588ac09439df56c0bac68d46a146f3aa8fb/staging/src/scala/quoted/staging/QuoteDriver.scala#L47https://github.com/lampepfl/dotty/blob/2ab9a588ac09439df56c0bac68d46a146f3aa8fb/staging/src/scala/quoted/staging/QuoteDriver.scala#L47

**Comment by liufengyun** [comment]
Thanks @nicolasstucki . It seems indeed related to classloaders:

https://stackoverflow.com/questions/46694600/java-9-compatability-issue-with-classloader-getsystemclassloader#comment80337394_46694600

**Comment by nicolasstucki** [comment]
We will need to adapt the logic in https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/util/ClasspathFromClassloader.scala#L19

**Comment by nicolasstucki** [comment]
We seem to get an instance of `AppClassLoader` https://java-browser.yawk.at/java/10/java.base/jdk/internal/loader/ClassLoaders.java#163

**Comment by nicolasstucki** [comment]
@liufengyun, this seems to fix the issue in Java 11. Coulld you try it on this PR?
```diff
@@ -38,6 +48,7 @@ object ClasspathFromClassloader {
             // with a different classloader.
             if (cl.getClass.getName == classOf[AbstractFileClassLoader].getName)
               collectClassLoaderPaths(cl.getParent)
+            classpathBuff += System.getProperty("java.class.path")
```

**Comment by liufengyun** [comment]
@nicolasstucki The test `tests/run-staging/tasty-extractors-constants-2` fails with the change.

File: tasty-inspector/src/scala/tasty/inspector/TastyInspector.scala [hunk 9]
```diff
@@ -62,7 +61,7 @@ trait TastyInspector:
 
     end TastyInspectorPhase
 
-    val currentClasspath = ClasspathFromClassloader(getClass.getClassLoader)
+    val currentClasspath = System.getProperty("java.class.path")
```
Comment (nicolasstucki) [inline tasty-inspector/src/scala/tasty/inspector/TastyInspector.scala:64]: This class path will not be complete we need to recover the URLs from the URLClassLoders firts

**Comment by nicolasstucki** [comment]
Try the version in #9506

File: .github/workflows/ci.yaml [hunk 10]
```diff
@@ -15,6 +15,9 @@ jobs:
     container: lampepfl/dotty:2020-04-24
 
     steps:
+      - name: Set up JDK version
```
Comment (smarter) [inline .github/workflows/ci.yaml:18]: I would call this step "Set JDK 11 as default" so we can easily know which version we're setting.

File: .github/workflows/ci.yaml [hunk 11]
```diff
@@ -216,13 +219,13 @@ jobs:
 
       - name: Test
         run: |
-          export PATH="/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"
+          export PATH="/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$PATH"
```
Comment (smarter) [inline .github/workflows/ci.yaml:222]: You used "::add-path::" above, I guess it would be good to do the same in this job for consistency.

File: compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala [hunk 12]
```diff
@@ -131,8 +131,12 @@ object DottyBackendInterface {
 
       def isStaticConstructor(using Context): Boolean = (sym.isStaticMember && sym.isClassConstructor) || (sym.name eq nme.STATIC_CONSTRUCTOR)
 
+      /** Fields of static modules will be static at backend */
+      def isStaticModuleField(using Context): Boolean =
+        sym.owner.isStaticModuleClass && sym.isField && !sym.name.is(LazyBitMapName)
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala:136]: The special handling of lazy bitmap fields should be explained here (maybe with a reference to the other comment in BCodeSkelBuilder)

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 13]
```diff
@@ -828,6 +828,19 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
     loop(tree)
   }
 
+  /** Return a pair consisting of (supercall, rest)
+   *
+   *  - supercall: the of superclass call, excluding trait constr calls
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:833]: Missing or extra word? "the of"

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 14]
```diff
@@ -828,6 +828,19 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
...
+   *
+   *  The supercall is always the first statement (if exists)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:835]:
```suggestion
   *  The supercall is always the first statement (if it exists)
```

File: compiler/src/dotty/tools/dotc/util/ClasspathFromClassloader.scala [hunk 15]
```diff
@@ -27,21 +27,26 @@ object ClasspathFromClassloader {
...
+              // here), but we do need to look at the parent of the REPL
+              // classloader, so we special case it. We can't do this using a type
+              // test since the REPL classloader class itself is normally loaded
+              // with a different classloader.
               collectClassLoaderPaths(cl.getParent)
+            else if cl eq ClassLoader.getSystemClassLoader then
+              // HACK: For Java 9+, if the classloader is an AppClassLoader then use the classpath from the system
+              // property `java.class.path`.
+              // See: https://java-browser.yawk.at/java/10/java.base/jdk/internal/loader/ClassLoaders.java#163
+              classpathBuff += System.getProperty("java.class.path")
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/util/ClasspathFromClassloader.scala:45]: Now that this is fixed, can test_bootstrapped be switched to using Java 11 again?

**Comment by smarter** [comment]
test performance please
