### PR TITLE
Fix #2063: Print tabs in message padding

### LINKED ISSUE #2063: Incorrect underlined position in error message when line contains tabs
```scala
$ echo "\tclass Foo extends Bar" > tab.scala
$ dotc tab.scala
-- [E006] Unbound Identifier Error: try/tab.scala ------------------------------
1 |     class Foo extends Bar
  |                  ^^^
  |                  not found: type Bar
$ scalac tab.scala
tab.scala:1: error: not found: type Bar
        class Foo extends Bar
                          ^
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala [hunk 1]
```diff
@@ -101,9 +100,12 @@ trait MessageRendering {
 
       math.min(currPad, minPad)
     }
+    val padding =
+      if (leastWhitespace - offset == pos.startColumn) pos.startColumnPadding
+      else " " * (leastWhitespace - offset)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala]: I don't understand why this is correct. Why not use startColumnPadding in currPad above?

File: compiler/src/dotty/tools/dotc/util/SourceFile.scala [hunk 2]
```diff
@@ -136,6 +136,17 @@ case class SourceFile(file: AbstractFile, content: Array[Char]) extends interfac
     col
   }
 
+  /** The padding of the column corresponding to `offset`, includes tabs */
+  def startColumnPadding(offset: Int): String = {
+    var idx = startOfLine(offset)
+    val pad = new StringBuffer("")
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/util/SourceFile.scala]: Use StringBuilder instead to avoid the synchronization overhead of StringBuffer, also you can use the empty constructor: `new StringBuilder`

File: compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala (hunk 1 above)
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala]: Because we do not know the size of one tab.

Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala]: But indeed I need to modify the logic a bit
