### PR TITLE
Fix #6146: Fix bounds check involving wildcards and f-bounds

### LINKED ISSUE #6146: f-bounds and wildcards don't mix?
I think the following should compile (it does in 2.13), but it produces the following errors (note the `LazyRef` in the error message):

```scala
  trait BS[T, S <: BS[T, S]]
  trait IS extends BS[Int, IS]

  sealed trait BSElem[T, S <: BS[_, S]] // we cannot make this S <: BS[T, S], as the `_` could be something else from T (that's what the `BSElem` implicit is for)

  /*
-- [E057] Type Mismatch Error: /Users/adriaan/git/scala/src/library/scala/collection/convert/StreamExtensions.scala:34:36 
34 |  sealed trait BSElem[T, S <: BS[_, S]]
   |                                    ^
   |Type argument S does not conform to upper bound StreamExtensions.this.BS[Any, LazyRef(S)] 
*/

  object BSElem {
    implicit val intStreamShape: BSElem[Int, IS] = ???
  }
  class Ops[A] {
    def asJavaSeqStream[S <: BS[_, S]](implicit s: BSElem[A, S]): S = ???
    /*
  -- [E057] Type Mismatch Error: /Users/adriaan/git/scala/src/library/scala/collection/convert/StreamExtensions.scala:39:35 
  39 |    def asJavaSeqStream[S <: BS[_, S]](implicit s: BSElem[A, S]): S = ???
     |                                   ^
     |Type argument S does not conform to upper bound StreamExtensions.this.BS[Any, LazyRef(S)] 
    */
  }
```

### PR DESCRIPTION
**Pull request by smarter**
Don't map arguments to their upper bounds before doing the bound check.
There was a comment justifiying that by talking about non
fully-determined arguments, but this check is done in PostTyper when all
types should already be fully-determined. Given that this comment was
written in 2014 I'm assuming it's no longer relevant.

### CODE REVIEW

**Comment by smarter** [comment]
Hmm, I'm having trouble coming up with an example where this would make a difference and our tests are green, can you take over this PR or come up with an example ?

**Comment by smarter** [comment]
> What we need here looks like another (simple) instance of capture conversion. I.e. replace any TypeBounds argument L..U by a skolem $n.CAP, where $n is of type TypeBox[L, U].

Isn't the existing wildcard capture logic in subtyping going to do that for us ?

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -75,8 +75,12 @@ object Checking {
     }.getOrElse(TypeTree(tparam.paramRef))
     val orderedArgs = if (hasNamedArg(args)) tparams.map(argNamed) else args
     val bounds = tparams.map(_.paramInfoAsSeenFrom(tree.tpe).bounds)
-    def instantiate(bound: Type, args: List[Type]) =
-      HKTypeLambda.fromParams(tparams, bound).appliedTo(args)
+    def instantiate(bound: Type, args: List[Type]) = tparams match {
+      case (_: Symbol) :: _ if args.exists(_.isInstanceOf[TypeBounds]) =>
+        bound.substApprox(tparams.asInstanceOf[List[Symbol]], args)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]: SubstApproxMap will start with `variance = 1` but when we call `instantiate(bounds.lo, argTypes)` surely we should start with `variance = -1` ? Maybe we should change `instantiate` to take a `TypeBounds` as input and as output.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: Also maybe leave a comment to note that we're not certain of the correctness here ?

**Comment by odersky** [comment]
In fact, thinking more about it the last commit 48f7ed6 still feels wrong. `substApprox` is no bullet. It does not pretend to be a meaning preserving substitution in the presence of wildcards. All it guarantees is that the result is not ill-formed.

The only way to deal with wildcards consistently is by skolemizing them in one way or another.

**Comment by odersky** [comment]
> I think this should be a migration warning.

It's hard to identify the point where we should issue such a warning. Also there's no good guideline we could give.
