### PR TITLE
Fix inherit doc warnings

### LINKED ISSUE #13068: Scaladoc omits file name from @inheritDoc warning, does not "count" warning
## Compiler version

3.0.1

## Minimized code

```Scala
class Test {
  /** {@inheritDoc} */
  def f: Unit = { }
}
```

## Output

Output via `sbt`:

```scala
<43..43>: the comment for method f contains @inheritdoc, but no parent comment is available to inherit from.
```

## Expectation

First, I would expect it to mention the file name --- important in a larger project with many uses of the same method name.

Second, note that the `sbt` output is not prefixed `[warn]` or `[error]` --- seems like `sbt` should pick up this issue as one or the other.  It is not included in the total-warnings count.

### PR DESCRIPTION
**Pull request by pikinier20**
closes #13068

### CODE REVIEW

**Review by KacperFKorban — APPROVED** [review]

File: scaladoc/src/dotty/tools/scaladoc/tasty/comments/CommentExpander.scala [hunk 1]
```diff
@@ -79,7 +79,7 @@ class CommentExpander {
       case None =>
         // SI-8210 - The warning would be false negative when this symbol is a setter
         if (ownComment.indexOf("@inheritdoc") != -1 && ! sym.isSetter)
-          println(s"${sym.span}: the comment for ${sym} contains @inheritdoc, but no parent comment is available to inherit from.")
+          report.warning(s"${sym.span}: the comment for ${sym} contains @inheritdoc, but no parent comment is available to inherit from.", sym.srcPos)
```
Comment (griggt) [inline scaladoc/src/dotty/tools/scaladoc/tasty/comments/CommentExpander.scala:82]: Is is still useful to include `${sym.span}` in the message now that `report.warning` is used with `sym.srcPos`?  The message may be confusing to the user who may not understand what those numbers mean?

```
 -- Warning: scaladoc-testcases/src/tests/inheritDoc.scala:6:6 ------------------
6 |  def f: Unit = { }
  |      ^
  |<76..76>: the comment for method f contains @inheritdoc, but no parent comment is available to inherit from.
```

Comment (pikinier20) [reply scaladoc/src/dotty/tools/scaladoc/tasty/comments/CommentExpander.scala:82]: You may be right. I didn't change the message, just the way it's sent, but probably we should remove span there.
