### PR TITLE
Fix #2797: Don't lift Java annotation arguments out of call

### LINKED ISSUE #2797: Assertion error in DottyBackendInterface: denot.name is not default getter
After merging the fix for #2704, I'm hitting a new assertion error in the backend while trying to compile the scala/compiler-benchmark with Dotty.

To reproduce

```
cd dotty
git checkout 0109fef834b4f08ba4dbc0fd08fe6f05753cb9b1
export NIGHTLYBUILD=yes
sbt dotty-bootstrapped/publishLocal
cd target
git clone https://github.com/olafurpg/compiler-benchmark.git
cd compiler-benchmark
git checkout c30610306e9bc7b5ed0609f0f24ca1054a48d26f // branch dotty2
sbt ++0.2.0-bin-20170623-0109fef-NIGHTLY compilation/test
...
[error] Error while emitting ScalacBenchmark.scala
[error] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitArgument(DottyBackendInterface.scala:259)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAssocs$$anonfun$2(DottyBackendInterface.scala:315)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAssocs(DottyBackendInterface.scala:315)
	at dotty.tools.backend.jvm.DottyBackendInterface.emitAnnotations$$anonfun$2(DottyBackendInterface.scala:308)
```
Compiling with -Ycheck:all gives a hint that an error occurred while typechecking this line here:
https://github.com/scala/compiler-benchmark/blob/d0f038e0a9f367e26dbe9825de9d00e9e699f592/compilation/src/main/scala/scala/tools/nsc/ScalacBenchmark.scala#L38

```
exception while typing java.nio.file.Files.walk(this.findSourceDir,
  [java.nio.file.FileVisitOption.FOLLOW_LINKS : java.nio.file.FileVisitOption]:
    Array[java.nio.file.FileVisitOption]
) of class class dotty.tools.dotc.ast.Trees$Apply # 11397
exception while typing java.nio.file.Files.walk(this.findSourceDir,
  [java.nio.file.FileVisitOption.FOLLOW_LINKS : java.nio.file.FileVisitOption]:
    Array[java.nio.file.FileVisitOption]
).collect of class class dotty.tools.dotc.ast.Trees$Select # 11399
exception while typing java.nio.file.Files.walk(this.findSourceDir,
  [java.nio.file.FileVisitOption.FOLLOW_LINKS : java.nio.file.FileVisitOption]:
    Array[java.nio.file.FileVisitOption]
).collect[java.util.List[java.nio.file.Path]^,
  java.util.stream.Collector[java.nio.file.Path, _,
    java.util.List[java.nio.file.Path]
  ]#A^
] of class class dotty.tools.dotc.ast.Trees$TypeApply # 11402
```

I unsuccessfully tried to minimize the error with
```scala
import java.nio.file._
import java.util.stream.Collectors
import scala.collection.JavaConverters._

object foo {
  Files.walk(Paths.get("."), FileVisitOption.FOLLOW_LINKS).collect(Collectors.toList[Path]).asScala
}
```

The failed assertion is here:
https://github.com/lampepfl/dotty/blob/7381e9d5106dec40cce70471c2c0c755b4bd374b/compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala#L259

This issue is a blocker for merging https://github.com/scala/compiler-benchmark/pull/31

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
Here is a minimized version, the reproduction requires loading the annotation from a class file:

*2797.java:*

```java
public @interface Fork {
  int value() default -1;
  String[] jvmArgs() default { "nope" };
}
```

*2797.scala:*

```scala
@Fork(jvmArgs = Array("I'm", "hot"))
class SexyScalacBenchmark
```

```bash
rm *.class; javac -d . 2797.java; dotc 2797.scala
```

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for minimizing @OlivierBlanvillain !

The scala/compiler-benchmark project compiles with this workaround and the unit tests pass. The annotations still seem to be emitted weirdly since I hit a new error when running the jmh benchmarks
```
Annotation @Param is not applicable to methods.
   [org.openjdk.jmh.generators.reflection.RFMethodInfo@20affcd9]

Annotation @Param is not applicable to methods.
   [org.openjdk.jmh.generators.reflection.RFMethodInfo@133b86b1]
```
I don't know if that error is related to this issue or not, the `@Param` annotations is defined on vars here https://github.com/scala/compiler-benchmark/blob/d0f038e0a9f367e26dbe9825de9d00e9e699f592/compilation/src/main/scala/scala/tools/nsc/ScalacBenchmark.scala#L18 It seems the annotation is attached to the wrong symbol

**Comment by OlivierBlanvillain** [comment]
@olafurpg Last commit should moves the annotation from getter/setter methods to the actual field, let me know if that's enough to make JMH happy!

**Comment by olafurpg** [comment]
I can confirm that the JMH benchmark runs from the latest commit! Thank you @OlivierBlanvillain t

**Comment by olafurpg** [comment]
Any chance to get this merged? It would help unblock https://github.com/scala/compiler-benchmark/pull/31

**Comment by OlivierBlanvillain** [comment]
It needs a review, @odersky could you have a look?

**Comment by DarkDimius** [comment]
@odersky  could you please review it today so we can get it into next milestone?
It would be nice to have JMH working with the released jar.

**Comment by odersky** [comment]
@smarter I am not sure how Scala annotations with default arguments are handled in the backend. Maybe @DarkDimius knows more?

**Comment by odersky** [comment]
I tried a translation to Scala; seems to work.

File: tests/pending/pos/i2797/Fork_1.java [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// Test is pending because we have no good way to test it.
```
Comment (smarter) [inline tests/pending/pos/i2797/Fork_1.java]: I don't understand why this test is pending, since Fork is suffixed with 1 and Test with 2, they should be compiled as you want

Comment (odersky) [inline tests/pending/pos/i2797/Fork_1.java]: They are not. I get: "Not found: Fork" when I compile Test.

Comment (smarter) [inline tests/pending/pos/i2797/Fork_1.java]: I've fixed the test. The issue was that the annotation needed to be called `Fork_1` since the name of the file is `Fork_1.java`. The javac error messages are eaten by our test suite, there's a WIP PR to fix that at https://github.com/lampepfl/dotty/pull/2811

**Comment by smarter** [comment]
It might not crash in the backend, but the Scala test case still generates some weird code:
```scala
@{
    <accessor> val value$1: Int = Fork.$lessinit$greater$default$1
    <accessor> val jvmArgs$1: Array{scala$Array$$T = String} = 
      Array.apply[String](["I\'m","hot" : String])(
        scala.reflect.ClassTag.apply[String](classOf[class String])
      )
    new Fork(Test.this.value$1, Test.this.jvmArgs$1)
```

It looks like scalac does something similar but with a warning:
```scala
% scalac tests/pos/i2797a/Fork.scala tests/pos/i2797a/Test.scala
tests/pos/i2797a/Test.scala:4: warning: Usage of named or default arguments transformed this annotation
constructor call into a block. The corresponding AnnotationInfo
will contain references to local values and default getters instead
of the actual argument trees
@Fork(jvmArgs = Array("I'm", "hot"))
 ^
```

**Comment by smarter** [comment]
Had to disable i2797 again because of joint compilation failure, see last commit, I'll open an issue for that.

File: tests/pending/pos/i2797/Fork_1.java (hunk 1 above)
Comment (odersky) [inline tests/pending/pos/i2797/Fork_1.java]: Ah, good to know.

**Comment by odersky** [comment]
In fact, we could put i2797 in pos-special and have legacyTests not try it.

**Comment by smarter** [comment]
Looks like separate compilation is not used with `compileDir` unfortunately.
