### PR TITLE
Fix #9067: avoid instantiate child parameters to Wildcard if possible 

### LINKED ISSUE #9067: Exhaustivity checking false positive
## Minimized code

```Scala
sealed trait Base[A, +B]
case class Foo[A, +B](f: A => B) extends Base[A, B]

def bar(x: Base[Any, Any]): Unit = x match { case Foo(_) => }
```

## Output

```scala
// defined trait Base
// defined case class Foo
4 |def bar(x: Base[Any, Any]): Unit = x match { case Foo(_) => }
  |                                   ^
  |                                   match may not be exhaustive.
  |
  |                                   It would fail on pattern case: Foo(_)
def bar(x: Base[Any, Any]): Unit
```

## Expectation

This should compile without a warning, as it does in Scala 2 and Dotty up until at least 0.23.0. I first noticed it giving this warning in 0.24.0-RC1, but haven't tried to narrow it down beyond that.

I also haven't tried very to hard to minimize it further, but it might be worth noting that making `B` invariant, `A` concrete, or changing `f: A => B` to something like `(A, B)` all make the warning go away.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #9067: avoid instantiate child parameters to Wildcard if possible 

In tests/patmat/i9067.scala, for `Foo[X1, X2] <: Base[Any, Any]`,
`X1` and `X2` can both be `Any` instead of `Wildcard`.
Inferring `Wildcard` will lead to the signature of `Foo.unapply`
be inferred as `Nothing => Nothing`, which causes the checker
to issue a false unexhaustive warning.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 1]
```diff
@@ -685,10 +686,15 @@ object TypeOps:
       }
     }
 
+    def isPatternTypeSymbol(sym: Symbol) = !sym.isClass && sym.is(Case)
+
     // replace uninstantiated type vars with WildcardType, check tests/patmat/3333.scala
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:689]: This sounds similar to what `Prototypes.wildApprox` does, could it be used instead of instUndetMap?
