### PR TITLE
Fix #8128: Fix atoms computations

### LINKED ISSUE #8128: Dependent function loses information about singleton type
```scala
object Test {
  def id: (x: 1 | 0) => x.type = x => x
  id(0): 0
}
```

```scala
-- [E007] Type Mismatch Error: /test.scala:3:4 
3 |  id(0): 0
  |  ^^^^^
  |  Found:    (1 : Int) | (0 : Int)
  |  Required: (0 : Int)
1 error found
```

### PR DESCRIPTION
**Pull request by odersky**
Several fixes related to how atoms are computed, which fixes some problems when comparing unions of singleton types. It's a partial fix of #8128. There's still some problem with typing dependent functions over singleton types (see commented out code in i8128.scala). This problem does not look related to atoms, however. 

Since I won't have time to work on this right now, it's better to get the fixes in this PR in independently.

UPDATE: I managed to find and fix the remaining problem. The fix meant that all intermediate commits were superseded because the structure to compute atoms had to be changed again. So this is best reviewed without looking at individual commits.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -1181,13 +1181,37 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
    *  for equality would give the wrong result, so we should not use the sets
    *  for comparisons.
    */
-  def canCompare(atoms: Set[Type]): Boolean =
-    ctx.phase.isTyper || {
+  def compareAtoms(tp1: Type, tp2: Type): Option[Boolean] =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: The use of an Option here might noticeably increase our allocation rate, a tri-state enum could be used instead.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -1181,13 +1181,37 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
    *  for equality would give the wrong result, so we should not use the sets
    *  for comparisons.
    */
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: The comment above applies to the `canCompare` method so it should be moved down.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -1181,13 +1181,37 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+  def compareAtoms(tp1: Type, tp2: Type): Option[Boolean] =
+    def canCompare(ts: Set[Type]) = ctx.phase.isTyper || {
       val hasSkolems = new ExistsAccumulator(_.isInstanceOf[SkolemType]) {
         override def stopAtStatic = true
       }
-      !atoms.exists(hasSkolems(false, _))
+      !ts.exists(hasSkolems(false, _))
     }
+    def verified(result: Boolean): Boolean =
+      if Config.checkAtomsComparisons && false then
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Since `checkAtomsComparisons is a final val this is equivalent to:
```suggestion
      if Config.checkAtomsComparisons then
```

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 4]
```diff
@@ -1167,35 +1167,36 @@ object Types {
...
-        else underlyingAtoms
-      case tp: ExprType => tp.resType.atoms(widenOK)
-      case tp: OrType => tp.atoms(widenOK) // `atoms` overridden in OrType
-      case tp: AndType => tp.tp1.atoms(widenOK) & tp.tp2.atoms(widenOK)
-      case tp: TypeProxy if widenOK => tp.underlying.atoms(widenOK)
-      case _ => Set.empty
-    }
+        tp.underlying.atoms match
+          case as @ Atoms.Range(lo, hi) =>
+            if hi.size == 1 then as else Atoms.Range(Set.empty, hi)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: Could you document this special case ?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 5]
```diff
@@ -1181,13 +1181,37 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+      result
+
+    def falseUnlessBottom = Some(verified(recur(tp1, NothingType)))
+
+    tp2.atoms match
+      case Atoms.Range(lo2, hi2) if canCompareAtoms && canCompare(hi2) =>
+        tp1.atoms match
+          case Atoms.Range(lo1, hi1) =>
+            if hi1.subsetOf(lo2) then Some(verified(true))
+            else if !lo1.subsetOf(hi2) then falseUnlessBottom
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: In what situation do we have a bottom type with a non-empty `lo1` ? Do we have a testcase for this ?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I don't think so, since the overwhelming majority of calls should give `None`. You get a `Some` only if both compared sides are consist of atoms.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 5 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I think it should be just `false`
