### PR TITLE
Normalise mirrorType for mirror Synthesis

### LINKED ISSUE #19198: MatchType not normalised for mirror synthesis when aliased
## Minimized code

```Scala
inline def check1[Tps <: NonEmptyTuple]: Unit =
  summonInline[Mirror.Of[Tuple.Head[Tps]]]

inline def check2[Tps <: NonEmptyTuple]: Unit =
  type FromType = Tuple.Head[Tps]
  summonInline[Mirror.Of[FromType]]

@main def Test: Unit =
  check1[Option[Int] *: EmptyTuple] // Ok
  check2[Option[Int] *: EmptyTuple] // Error: FromType is widened to Any in Syntheziser
```

## Output

```scala
13 |  check2[Option[Int] *: EmptyTuple] // Error: FromType is widened to Any in Syntheziser
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |No given instance of type scala.deriving.Mirror.Of[FromType] was found. Failed to synthesize an instance of type scala.deriving.Mirror.Of[FromType]:
   |    * class Any is not a generic product because it is not a case class
   |    * class Any is not a generic sum because it is not a sealed class
   |--------------------------------------------------------------------------------------------------------------------
```

## Expectation

`FromType` alias should make no difference.

### PR DESCRIPTION
**Pull request by EugeneFlesselle**
If `MirrorSource.reduce` is given a proxy to an unreduced match type, it will simply get its supertype `Any`. We need to normalise the `mirroredType` before attempting to reduce it to a kind of mirror source. 

Fix #19198

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 1]
```diff
@@ -339,7 +339,7 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
      *  or a TermRef to a singleton value. These are
      *  the base elements required to generate a mirror.
      */
-    def reduce(mirroredType: Type)(using Context): Either[String, MirrorSource] = mirroredType match
+    def reduce(mirroredType: Type)(using Context): Either[String, MirrorSource] = mirroredType.normalized match
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:342]: maybe we can explicitly do a check for AppliedType of a match type, (alongside the Tuple case), then normalise there

Comment (EugeneFlesselle) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:342]: Or maybe from `Implicits.inferImplicitArg` before even entering the Syntheziser. Is there any reason not to ?

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:342]: normalize is known to be a slow operation, so should be used only when necessary

**Review by bishabosha — APPROVED** [review]
