### PR TITLE
Fix #8839: Only warn if TASTy is not in sync with classfile

### LINKED ISSUE #8839: Tasty UUID test is too sticky
If I abort in the middle of a build I often get errors like this:
```
Tasty UUID (00c95233-db90-de00-00bb-2b5192afb400) file did not correspond the tasty UUID (007e6fd1-1df0-ff00-0051-207d11d1f200) declared in the classfile /Users/odersky/workspace/dotty/community-build/community-projects/scalatest/scalatest.dotty/target/scala-0.25/classes/org/scalatest/tools/StringReporter.class.
```
These errors are sticky. Rebuilding will come back with the same ones. I have to do a clean to make them go away. 

## Expectation

I think these errors should be handled better. If it's the wrong Tasty UUID, pretend it is not there and assume the class file is missing also, returning a stub symbol.

At the very minimum, add a note to the error that this requires a clean. But the note should really not be necessary, it's better to handle the problem at the root.

### PR DESCRIPTION
**Pull request by nicolasstucki**
If they are not in sync, we warn and suggest to clean.
We assume that the TASTy is up to date (arbitrary choise) and load it regardless.
This way we are resiliant to the failiure if the loaded class API did not change or
did not have an impact on the code we are compiling.

### CODE REVIEW

**Comment by smarter** [comment]
@odersky When you encountered https://github.com/lampepfl/dotty/issues/8839, were you running dotc from inside sbt or by itself? sbt should take care of restoring .class and .tasty files in case of failed compilation, if it doesn't there's a bug somewhere.

**Comment by odersky** [comment]
I think I was running standalone.

**Comment by nicolasstucki** [comment]
I also hit it in stand alone. Also reproduced it this way.

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -825,7 +825,7 @@ class ClassfileParser(
             val expectedUUID = new UUID(reader.readUncompressedLong(), reader.readUncompressedLong())
             val tastyUUID = new TastyHeaderUnpickler(tastyBytes).readHeader()
             if (expectedUUID != tastyUUID)
-              ctx.error(s"Tasty UUID ($tastyUUID) file did not correspond the tasty UUID ($expectedUUID) declared in the classfile $classfile.")
+              ctx.warning(s"$classfile is out of sync with its TASTy file. Try cleaning the project to fix this issue", NoSourcePosition)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:828]: The comment should mention that we're ignoring the classfile in favor of the tasty file

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala]: Done
