### PR TITLE
Fix #10264: Add code completion for extension methods

### LINKED ISSUE #10264: No code completion for extension methods
## Minimized code

```scala
object Bar

extension (bar: Bar.type) def xxxx: Int = 1

implicit class BarOps(bar: Bar.type) {
  def yyyy: Int = 2
}
```

```scala
Bar.xx
```

## Output

When pressing TAB in REPL, the method `xxxx` is not suggested.

## Expectation

`Bar.xx` should expand to `Bar.xxxx` just as `Bar.yy` expands to `Bar.yyyy`. The issue is not specific to REPL however. This doesn't work with Metals either.

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Comment by prolativ** [comment]
The tests are passing now. @nicolasstucki As far as I can see you've had some experience with the code around completions so it would be nice if you could have a look at that

**Comment by nicolasstucki** [comment]
Actually, I only wrote the test infrastructure for completion tests. The tests seem to be good. 

@smarter could you have a look at the implementation of the completion logic?

**Comment by prolativ** [comment]
Corresponding PR in scala2 repo: https://github.com/scala/scala/pull/6362

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -2176,4 +2176,8 @@ trait Applications extends Compatibility {
       report.error(em"not an extension method: $methodRef", receiver.srcPos)
     app
   }
+
+  def isApplicableExtensionMethod(ref: TermRef, receiver: Type)(using Context) =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:2180]: You could check `!receiver.isBottomType` here to exclude Nothing and Null so you don't have to exclude them in the caller.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Applications.scala (hunk 1 above)
Comment (prolativ) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:2180]: Right, I can move the check here but not sure we should exclude Null. The compiler still lets you define an extension on Null so I think for consistency this should be displayed in a completion

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:2180]: > The compiler still lets you define an extension on Null so I think for consistency this should be displayed in a completion

I don't think it's a big deal either way, but because by default `Null` is a subtype of every reference type, one should be careful to not include all the extension methods that apply to reference types in the list

Comment (prolativ) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:2180]: Checking `isBottomType` then

**Review by smarter — APPROVED** [review]
Nicely done, thanks!

**Comment by prolativ** [comment]
@smarter ready for merge

**Comment by smarter** [comment]
(note that you should have the rights to merge PRs yourself, and it's OK to do so once it's been approved)
