### PR TITLE
Fix desugaring of context bounds in extensions

### LINKED ISSUE #11586: Context bound desugared at the wrong place in extension method
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
trait Conv[T]

extension [T: Conv](x: T)
  def combine (y: T): T = ???
```

## Compiler output with -Xprint:typer

```scala
    extension [T >: Nothing <: Any](x: T) def combine(y: T)(
      implicit evidence$1: test.Conv[T]
    ): T = ???
```

## Expectation

```scala
    extension [T >: Nothing <: Any](x: T)(using x$2: test.Conv[T]) def combine(
      y: T
    ): T = ???
```

, obtained with "using" syntax:

```Scala
extension [T](x: T)(using Conv[T])
  def combine (y: T): T = ???
```

### PR DESCRIPTION
**Pull request by rjolly**
Fixes #11586
Unfixes #11583

### CODE REVIEW

**Comment by neko-kai** [comment]
I guess the change should avoid breaking  #11583 to have a chance...

**Comment by rjolly** [comment]
@neko-kai see my comment in https://github.com/lampepfl/dotty/pull/11584

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -218,15 +218,32 @@ object desugar {
...
+        )
+  end elimContextBounds
+
+  private def elimContextBounds(paramss: List[ParamClause], isPrimaryConstructor: Boolean, ext: Boolean)(using Context): List[ParamClause] =
     val evidenceParamBuf = ListBuffer[ValDef]()
 
     def desugarContextBounds(rhs: Tree): Tree = rhs match
       case ContextBounds(tbounds, cxbounds) =>
-        val iflag = if sourceVersion.isAtLeast(`future`) then Given else Implicit
+        val iflag = if ext || sourceVersion.isAtLeast(`future`) then Given else Implicit
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala:246]: This leads to the situation where context bound on the leading extension clause desugars to a `using` param clause but on the extension method params desugars to an `implicit` param clause, this seems inconsistent to me.
```scala
trait SemiGroup[T]:
   extension [U: Conv[T]](x: U) // using ev: Conv[T]
     def combine(y: T): T
   extension (x: T)
     def combine[U: Conv[T]](y: U): T  // implicit ev: Conv[T]
```

File: tests/neg/i10901.scala [hunk 2]
```diff
@@ -43,8 +43,8 @@ object BugExp4Point2D {
     val y = DoubleT
 
     val pos1: Point2D[Int,Double] = x º y       // error
-    val pos2: Point2D[Int,Double] = 100 º 200.1 // ok
-    val pos3: Point2D[Int,Double] = 101 º y     // ok
+//  val pos2: Point2D[Int,Double] = 100 º 200.1
```
Comment (bishabosha) [inline tests/neg/i10901.scala:46]: can we justify why these should now be broken? I tried the following change but it still did not type check.
It seems to be a tricky position where the compiler can not handle inference well for context parameters after the extension clause.
```scala
    extension [T1:Numeric](x: T1)

      // N - N
      @targetName("point2DConstant")
      def º[T2:Numeric](y: T2): Point2D[T1,T2] = ???


      // N - C
      @targetName("point2DConstantData")
      def º[T2:Numeric](y: ColumnType[T2]): Point2D[T1,T2] = ???



    extension [T1:Numeric](x: ColumnType[T1])
      // C - C
      @targetName("point2DData")
      def º[T2:Numeric](y: ColumnType[T2]): Point2D[T1,T2] = ???

      // C - N
      @targetName("point2DDataConstant")
      def º[T2:Numeric](y: T2): Point2D[T1,T2] = ???
```

File: tests/neg/missing-implicit1.check [hunk 3]
```diff
@@ -16,12 +16,7 @@
...
+-- [E008] Not Found Error: tests/neg/missing-implicit1.scala:23:18 -----------------------------------------------------
 23 |    List(1, 2, 3).traverse(x => Option(x)) // error
-   |                                          ^
-   |no implicit argument of type testObjectInstance.Zip[Option] was found for an implicit parameter of method traverse in trait Traverse
-   |
-   |The following import might fix the problem:
-   |
-   |  import testObjectInstance.instances.zipOption
-   |
+   |    ^^^^^^^^^^^^^^^^^^^^^^
```
Comment (bishabosha) [inline tests/neg/missing-implicit1.check:21]: this new error is definitely less helpful - it seems like the compiler should improve search of extension methods with context parameters on the first clause before we can make this change, which is not ideal

**Review by bishabosha — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala (hunk 1 above)
Comment (rjolly) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:246]: My first move was to use `using` for both, but I thought keeping `implicit` wherever possible might be better for compatibility. I have to use `using` at least in the extension clause, because the "resugaring" checks for it specifically, see dotty/tools/dotc/printing/RefinedPrinter.scala line 822:
```scala
val (trailingUsing, rest3) = rest2.span(isUsingClause)
```

Comment (neko-kai) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:246]: I think in principle, while somewhat inconsistent, it's justifiable to use `using` in extension clauses instead of `implicit` because extensions are a new syntactic construct - there is no "migrating" Scala 2 code using them by definition, as such there are no compatibility concerns that could force desugaring to `implicit` instead of immediately to `using`.

File: tests/neg/i10901.scala (hunk 2 above)
Comment (rjolly) [reply tests/neg/i10901.scala:46]: Well I don't know, overloads don't help for sure. Without these, it works, i.e. just C-C and N-N for instance. In addition, I had to comment lines 46-47 instead of reporting an error, because the latter is undeterministic (it changes at each recompile):
```scala
    val pos2: Point2D[Int,Double] = 100 º 200.1
                                    ^^^^^
value º is not a member of Int.
An extension method was tried, but could not be fully constructed:

    BugExp4Point2D.dsl.º[Int, T2](100)(scala.math.Numeric.IntIsIntegral, 
      /* ambiguous: both object FloatIsFractional in object Numeric and object CharIsIntegral in object Numeric match type Numeric[T2] */
        summon[Numeric[T2]]
    )    failed with

        ambiguous implicit arguments: both object FloatIsFractional in object Numeric and object CharIsIntegral in object Numeric match type Numeric[T2] of an implicit parameter of method º in object dsl
```

File: tests/neg/missing-implicit1.check (hunk 3 above)
Comment (rjolly) [reply tests/neg/missing-implicit1.check:21]: Agreed. Note that the problem will occur with `using` too (that is, irrespective of this PR), so indeed we might want to address it separately:
```scala
extension [A, B, G[_]](fa: F[A])(using Zip[G]) def traverse(f: A => G[B]): G[F[B]]
```

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala (hunk 1 above)
Comment (rjolly) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:246]: That was indeed my reasoning.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:246]: Yes it does appear that the parser explicitly forbids implicit parameters in the extension clauses, so this makes sense

**Comment by bishabosha** [comment]
I find the main issue here is that this change results in a worse state of affairs than the status quo.
If the compiler never improved search for extension methods then would it be worth all the boilerplate to manually put context parameters on extension methods to get the old behavior?

File: tests/neg/missing-implicit1.check (hunk 3 above)
Comment (bishabosha) [reply tests/neg/missing-implicit1.check:21]: its probably worth opening an issue for the manual desugaring not being found by the compiler

File: tests/neg/i10901.scala (hunk 2 above)
Comment (bishabosha) [reply tests/neg/i10901.scala:46]: its probably worth opening an issue for the manual desugaring not being found by the compiler

**Comment by neko-kai** [comment]
@bishabosha I think the desugaring is not at fault here since you're going to get the same type inference behavior if you were to write `using Functor[F]` instead of `: Functor`.

Previous desugaring would merely mask the issue by making context bounds infer "better" by making them more than just a short-hand which they are usually, then cause surprising change in behavior if a context bound was replaced with an explicit `using`/`implicit` clause.

**Comment by bishabosha** [comment]
> @bishabosha I think the desugaring is not at fault here since you're going to get the same type inference behavior if you were to write `using Functor[F]` instead of `: Functor`.
> 
> Previous desugaring would merely mask the issue by making context bounds infer "better" by making them more than just a short-hand which they are usually, then cause surprising change in behavior if a context bound was replaced with an explicit `using`/`implicit` clause.

Sorry, I should perhaps rephrase my original comment, I am in agreement in principle with the new proposed desugaring. However I am concerned that perhaps it should not go forward right now, purely because an extension such as
```scala
extension [F[_], A](f: F[A])(using Functor[F]) def ...
```
can not be found as easily by the compiler (therefore leading to more boilerplate to put all using clauses at the end of extension methods, a.k.a - how context bounds desugar before this PR).

**Comment by neko-kai** [comment]
> However I am concerned that perhaps it should not go forward right now, purely because an extension such as can not be found as easily by the compiler (therefore leading to more boilerplate to put all using clauses at the end of extension methods, a.k.a - how context bounds desugar before this PR). 


Yeah, but you'd lose that property immediately if you wrote an explicit `using` instead of a context bound anyway. I think ripping the band-aid early, while there are still very few users that would be impacted is better than waiting until there are even further impediments to this, such as binary compatibility, that would cause a temporary change 'for convenience' to be stuck in the language forever and become another embarassing inconsistency that has to be explained over and over to anyone who encounters it...

File: tests/neg/i10901.scala (hunk 2 above)
Comment (rjolly) [reply tests/neg/i10901.scala:46]: https://github.com/lampepfl/dotty/issues/11713

File: tests/neg/i10901.scala [hunk 4]
```diff
@@ -43,8 +43,8 @@ object BugExp4Point2D {
...
+//  val pos3: Point2D[Int,Double] = 101 º y
```
Comment (bishabosha) [inline tests/neg/i10901.scala:47]: could this test be rewritten to enable these tests again, e.g. by manually desugaring the context bounds to how they would be before this PR?

File: tests/neg/missing-implicit1.check (hunk 3 above)
Comment (bishabosha) [reply tests/neg/missing-implicit1.check:21]: same here, could the extension methods be rewritten so that the error does not change?

File: tests/neg/missing-implicit4.check [hunk 5]
```diff
@@ -16,12 +16,7 @@
...
+-- [E008] Not Found Error: tests/neg/missing-implicit4.scala:20:18 -----------------------------------------------------
 20 |    List(1, 2, 3).traverse(x => Option(x)) // error
-   |                                          ^
-   |no implicit argument of type Zip[Option] was found for an implicit parameter of method traverse in trait Traverse
-   |
-   |The following import might fix the problem:
-   |
-   |  import instances.zipOption
-   |
+   |    ^^^^^^^^^^^^^^^^^^^^^^
```
Comment (bishabosha) [inline tests/neg/missing-implicit4.check:21]: same here, tests should maintain the same error message, so the extension methods should be manually desugared

**Review by bishabosha — CHANGES_REQUESTED** [review]

**Review by bishabosha — APPROVED** [review]
LGTM

**Comment by bishabosha** [comment]
@rjolly this PR was reverted after merging because it was decided to wait to fix issues like #11713 first

**Comment by rjolly** [comment]
Yes, I saw that, thanks

**Comment by griggt** [comment]
Should this be revisited now that #11713 is fixed?

**Comment by bishabosha** [comment]
would that be a scala 4 change?
