### PR TITLE
Fix #24547: Strip inferred retains annotation from Macro/inline call trees

### LINKED ISSUE #24547: Compiler crash in `getkyo/kyo` + `dotty-cps-async/dotty-cps-async`
Based on the OpenCB failure in`getkyo/kyo` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/19666033780/job/56323260327) 

I was not able to minimise problem fully. The `dotty-cps-async/dotty-cps-async` macros are really complex and I was not being able to create to self-contained minimalization yet. 
@rssh do you think you can help us to get to the root of the problem?  

It's also possible that it might require changes in the `dotty-cps-async/dotty-cps-async` implementation - one possibility for this might be null-check of stdlib, capture checking of stdlib or something completely different. 

Detection of this problem was delayed by previous errors described in https://github.com/scala/scala3/issues/24097

## Compiler version
3.8.0-RC2

Last good release: 3.8.0-RC1-bin-20250822-658c8bd-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250823-712d5bc-NIGHTLY

Exact bisect is ineffective as we're landing at the common unrelated  commit due to multiple significant changes in that time 

## Reproduced code

```scala
// macro.scala
//> using dep "io.github.dotty-cps-async::dotty-cps-async:1.1.5"

package kyo:
  opaque type <[+A, -S] = A | Kyo[A, S]
  class Kyo[+A, -S] extends Serializable
  class KyoCpsMonad[S] extends cps.CpsMonadContext[[A] =>> A < S], cps.CpsMonad[[A] =>> A < S] {
    type Context = KyoCpsMonad[S]

    def apply[T](op: KyoCpsMonad.this.Context => T < S): T < S = ???
    def flatMap[A, B](fa: A < S)(f: A => B < S): B < S = ???
    def map[A, B](fa: A < S)(f: A => B): B < S = ???
    def pure[T](t: T): T < S = ???
    def monad: cps.CpsMonad[[A] =>> A < S] = ???
  }
  
  import scala.quoted.*
  transparent inline def direct[A](inline f: A) = ${ impl[A]('f) }

  private def impl[A: Type](body: Expr[A])(using quotes: Quotes): Expr[Any] =
    import quotes.reflect.*
    val pending: TypeRepr = TypeRepr.of[Any]
    pending.asType match
      case '[s] =>
        '{
          given KyoCpsMonad[s] = KyoCpsMonad[s]
          cps.async {
            ${ body.asExprOf[A] }
          }.asInstanceOf[A < s]
        }
```

```scala
// test.scala

import scala.collection.IterableOps
import kyo.*

def iterableTests[Coll[X] <: Iterable[X] & IterableOps[X, Coll, Coll[X]]]: Unit =
    def Coll[X](x: X*): Coll[X] = ???
    def xsValues: Coll[Int]     = Coll(1, 2, 3, 4)
 
    locally {
        direct:
          val (take, drop) = xsValues.span(???)
          take.toSeq
    }

```

## Output

```scala
-- Error: /Users/wmazur/projects/scala/community-build3/test.test.scala:11:10 --------------------------------------------------
10 |        direct:
11 |          val (take, drop) = xsValues.span(???)
   |        ^
   |        Coll[Int] is not a legal path
   |        since it is not a concrete type
12 |          take.toSeq
   |----------------------------------------------------------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from test.scala:25
25 |          given KyoCpsMonad[s] = KyoCpsMonad[s]
   |          ^
26 |          cps.async {
27 |            ${ body.asExprOf[A] }
28 |          }.asInstanceOf[A < s]
    ----------------------------------------------------------------------------------------------------------------------------
1 error found
Compilation failed
```

### PR DESCRIPTION
**Pull request by noti0na1**
Fix #24547

### CODE REVIEW

**Comment by noti0na1** [comment]
Em...
With this fix, the test should be compilable, as in 3.7, but it does not pass the `-Ycheck:all`, as in 3.7. There are some issues with this macro even before 3.8.

<details/>

```
Error: java.lang.AssertionError: assertion failed: bad owner; value $3$ has owner value $4$, expected was value $4
owner chain = value $3$, value $4$, value macro, method reproTest, the top-level definitions in package <empty>, package <empty>, package <root>, ctxOwners = value $4, value $4, value $4, method reproTest, method reproTest, method reproTest, method reproTest, method reproTest, method reproTest, method reproTest, the top-level definitions in package <empty>, the top-level definitions in package <empty>, package <empty>, package <empty>, package <empty>, package <root>, package <root>, package <root>, package <root>, package <root>, package <root>, package <root>,  <none>,  <none>,  <none>,  <none>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.transform.TreeChecker$Checker.checkOwner(TreeChecker.scala:575)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats$$anonfun$1(TreeChecker.scala:687)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:686)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1516)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1520)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:306)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:673)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3679)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.$anonfun$19(Typer.scala:1617)
        at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:2738)
        at dotty.tools.dotc.typer.Applications.harmonic$(Applications.scala:470)
        at dotty.tools.dotc.typer.Typer.harmonic(Typer.scala:155)
        at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:1620)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3680)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3890)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3909)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:691)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1516)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1520)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:306)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:673)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3679)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.typedLabeled(Typer.scala:2329)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedLabeled$$anonfun$1(TreeChecker.scala:696)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedLabeled(TreeChecker.scala:696)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3664)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3758)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3952)
        at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:2968)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedValDef(TreeChecker.scala:622)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3650)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3758)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3863)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3909)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:691)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1516)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1520)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:306)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:673)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3679)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.ReTyper.typedInlined(ReTyper.scala:100)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined$$anonfun$1(TreeChecker.scala:676)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined(TreeChecker.scala:676)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3694)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.ReTyper.typedInlined(ReTyper.scala:100)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined$$anonfun$1(TreeChecker.scala:676)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined(TreeChecker.scala:676)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3694)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3890)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3909)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:691)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1516)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1520)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:306)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:673)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3679)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3952)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1523)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:673)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:306)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:673)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3679)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3952)
        at dotty.tools.dotc.typer.Typer.$anonfun$68(Typer.scala:3028)
        at dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:256)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:3028)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef$$anonfun$1(TreeChecker.scala:648)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:278)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:651)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3653)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3758)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3863)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3909)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:691)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:3328)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:618)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3659)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3663)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3758)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3863)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3909)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:691)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:3461)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedPackageDef(TreeChecker.scala:717)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3705)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3759)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:434)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3836)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3841)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:416)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3952)
        at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:131)
        at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:111)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:383)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:376)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at dotty.tools.dotc.Run.showProgress(Run.scala:482)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:432)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:325)
        at dotty.tools.dotc.Run.compileSuspendedUnits(Run.scala:446)
        at dotty.tools.dotc.Driver.finish(Driver.scala:63)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:148)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$9(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:73)
        at bloop.tracing.NoopTracer$.trace(BraveTracer.scala:53)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:72)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$8(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:71)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

<details>

**Comment by noti0na1** [comment]
I propose: we merge this into 3.8 to avoid `retains` interacting with any types during macro/inline expansion, and keep the original issue open for further investigation.

cc @odersky @hamzaremmal

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala [hunk 1]
```diff
@@ -100,18 +101,34 @@ object Inlines:
...
+          val stripped = stripRetains(tree.tpe)
+          if stripped ne tree.tpe then tree.withType(stripped)
+          else tree
+        case tree => tree
+      }
+    )
+
+    val tree0 = stripper.transform(tree)
+
+    if tree0.symbol.denot != SymDenotations.NoDenotation
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/inlines/Inlines.scala]:
```suggestion
    if tree0.symbol.denot.exists
```

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala [hunk 2]
```diff
@@ -100,18 +101,34 @@ object Inlines:
    *            and body that replace it.
    */
   def inlineCall(tree: Tree)(using Context): Tree = ctx.profiler.onInlineCall(tree.symbol):
-    if tree.symbol.denot != SymDenotations.NoDenotation
-      && tree.symbol.effectiveOwner == defn.CompiletimeTestingPackage.moduleClass
+
+    /** Strip @retains annotations from inferred types in the call tree */
+    val stripRetains = CleanupRetains()
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/inlines/Inlines.scala]: Why use a separate `val` here? Can we not just do `typeMap = CleanupRetains()` below?

**Comment by odersky** [comment]
Agreed. Let's merge for 3.8.0 but keep the issue open.

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala (hunk 2 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala]: Maybe we should just simply map all types in a tree, given macro can work with any type from the tree?

```scala
val cleanupRetains = new TreeTypeMap(typeMap = CleanupRetains())
val tree0 = cleanupRetains.transform(tree)
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala]: But that risks losing capture sets in the input of an inline call. I think the original version was safer.

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala]: I see. Agree, then I should not pass typeMap to `TreeTypeMap`, since it will eventually map all types.
