### PR TITLE
Make body of quotes inlinable

### LINKED ISSUE #8208: assertion failed: private method dynamicPower in object X
## minimized code

```Scala
package playground

import scala.quoted._
import scala.quoted.matching._

object X {

  inline def power(n: Int, x: Double): Double =
    ${ powerImpl('n, 'x) }

  private def powerImpl(nExpr: Expr[Int], xExpr: Expr[Double])(given QuoteContext): Expr[Double] =
    nExpr match {
      case Const(n1) => '{ 42.0 }
      case _ => '{ dynamicPower($nExpr, $xExpr) }
    }

  private def dynamicPower(n: Int, x: Double): Double = {
    println(s"dynamic: $n^$x")
    if (n == 0) 1.0
    else if (n % 2 == 0) dynamicPower(n / 2, x * x)
    else x * dynamicPower(n - 1, x)
  }
}
```
create some worksheet:
```scala
import playground.X
X.power(f, 2)
```

## Compilation output

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: private method dynamicPower in object X in C:\Users\dmitrii.naumenko\Desktop\dev\dotty-example-project\src\main\scala\playground\X.scala accessed from constructor rs$line$10$ in rs$line$10
    at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
    at dotty.tools.dotc.transform.ExpandPrivate.ensurePrivateAccessible(ExpandPrivate.scala:84)
    at dotty.tools.dotc.transform.ExpandPrivate.transformIdent(ExpandPrivate.scala:92)
    at dotty.tools.dotc.transform.ExpandPrivate.transformIdent(ExpandPrivate.scala:91)
    at dotty.tools.dotc.transform.MegaPhase.goIdent(MegaPhase.scala:551)
    at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:225)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:270)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:306)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:287)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:324)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:406)
    at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
    at scala.collection.immutable.List.mapConserve(List.scala:444)
    at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:286)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:245)
    at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:248)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
    at dotty.tools.dotc.transform.MegaPhase.transformSpecificTree(MegaPhase.scala:400)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:336)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
    at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:404)
    at dotty.tools.dotc.transform.MegaPhase.$anonfun$1(MegaPhase.scala:409)
    at scala.collection.immutable.List.mapConserve(List.scala:444)
    at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
    at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:356)
    at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:359)
    at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
    at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:415)
    at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:427)
    at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
    at scala.collection.immutable.List.map(List.scala:219)
    at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
    at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:161)
    at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
    at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
    at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
    at dotty.tools.dotc.Run.runPhases$5(Run.scala:171)
    at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:179)
    at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
    at dotty.tools.dotc.Run.compileUnits(Run.scala:186)
    at dotty.tools.dotc.Run.compileUnits(Run.scala:128)
    at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:156)
    at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:166)
    at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:229)
    at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:193)
    at dotty.tools.repl.ReplDriver.run$$anonfun$1(ReplDriver.scala:136)
    at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:148)
    at dotty.tools.repl.ReplDriver.run(ReplDriver.scala:137)
    at dotty.tools.languageserver.worksheet.ReplProcess$.main(ReplProcess.scala:13)
    at dotty.tools.languageserver.worksheet.ReplProcess.main(ReplProcess.scala)
```

## expectation
`X.power` shouldn't compile cause it is inlined and uses private method

### LINKED ISSUE #12948: Packaged macro that accesses protected definitions emits access errors
Access modifiers are treated transparently through a _packaged_ macro inlining, so a a protected method that is not protected for the macro itself is still considered protected when inlined and we get illegal access error. 

## Compiler version

v3.0.1-RC2 (also tested on nightly)

## Minimized code
See minimized project at: https://github.com/soronpo/dottybug/tree/inline_illegal_access

**mylib/Main.scala**
```Scala
package mylib
import scala.quoted.*

object Main:
  protected def foo: Unit = {}
  inline def fooCaller: Unit = foo
  inline def fooCallerM: Unit = ${ fooMacro }
  def fooMacro(using Quotes): Expr[Unit] =
    '{ foo }
```

**Test.scala**
```scala
import mylib.Main

object Test:
  Main.fooCaller //works
  Main.fooCallerM //error
```

## Output

```scala
[error] -- Error: C:\IdeaProjects\dottybug\src\main\scala\Test.scala:5:7 ------------------------------------------------------------
[error] 5 |  Main.fooCallerM
[error]   |  ^^^^^^^^^^^^^^^
[error]   |  illegal access to protected method foo in object Main from object Test
[error]   | This location contains code that was inlined from Main.scala:9
[error]   | This location contains code that was inlined from Main.scala:9
[error] one error found
```

## Expectation
No error.

### PR DESCRIPTION
**Pull request by nicolasstucki**
This adds inline accessors for private/protected members if needed as we do with inline defs.

Fixes #8208
Fixes #12948

### CODE REVIEW

File: tests/pos-macros/i12948b.scala [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import scala.quoted.*
+
+package foo {
+  trait Bar:
+    def bar(using Quotes) = '{ Baz }
```
Comment (nicolasstucki) [inline tests/pos-macros/i12948b.scala:5]: This is failing because we generate the inline accessor for `Baz` in this class.
```scala
trait Bar:
  def bar(using Quotes) = '{ this.foo$Bar$$inline$Baz }
  def foo$Bar$$inline$Baz = Baz
```
which then fails because it tries to access the `this` in the quote
```scala
5 |    def bar(using Quotes) = '{ Baz }
  |                               ^
  |                              access to Bar.this from wrong staging level:
  |                               - the definition is at level 0,
  |                               - but the access is at level 1.
```
We should have the inline accessor placed in the same scope as `Baz` to make its reference stage consistent.

**Review by anatoliykmetyuk — APPROVED** [review]
