### PR TITLE
Normalize MatchAlias in unrollTupleTypes

### LINKED ISSUE #19385: summonAll for type alias does not work
## Compiler version

3.4.0-RC1

## Minimized code

```Scala
import scala.compiletime.summonAll

inline def f[M <: Tuple]: Unit = {
  type Alias = Tuple.Map[M, [X] =>> Numeric[X]]
  summonAll[Tuple.Map[M, [X] =>> Numeric[X]]] // compiles
  summonAll[Alias] // error: Tuple element types must be known at compile time
}

val y1 = f[(Int, Int)]
```

## Expectation

Compiles in scala 3.3.1.

### PR DESCRIPTION
**Pull request by EugeneFlesselle**
I'm not sure whether the normalisation of `MatchAlias` should be done in `dealias`. 
I suppose it is safer to only add the change in `unrollTupleTypes` where it is necessary.

Fixes #19385

### CODE REVIEW

**Comment by EugeneFlesselle** [comment]
Similar to #19199

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala [hunk 1]
```diff
@@ -443,6 +443,9 @@ object Inlines:
             unrollTupleTypes(tail).map(head :: _)
           case tpe: TermRef if tpe.symbol == defn.EmptyTupleModule =>
             Some(Nil)
+          case tpRef: TypeRef => tpRef.info match
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/inlines/Inlines.scala:446]: The fix works, but I am not sure if this is the correct way to handle `MatchAlias`es.

@sjrd could you have a look at this one?

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala:446]: It looks reasonable, although usually we would rather expect
```scala
case tpe: AppliedType if tpe.isMatchAlias => ... tpe.tryNormalize ...
```
It is a bit suspicious that we directly encounter the `tycon` here, rather than the surrounding `AppliedType`. What are `tpe` and `tpe.dealias` when we get here on the problematic test case?

Comment (EugeneFlesselle) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala:446]: Yes I noticed that for instance `isMatchAlias` is defined on `AppliedType`s. 
But in this case, we have `tpe := TypeRef(NoPrefix, Alias)` which remains the same after `dealias` since the info of `Alias` is not a `TypeAlias` but a `MatchAlias`. The case is not covered here: 
https://github.com/lampepfl/dotty/blob/997103d818ead17d528d320b01edefb8792579ac/compiler/src/dotty/tools/dotc/core/Types.scala#L1438-L1445

**Review by sjrd — APPROVED** [review]
