### PR TITLE
Fix #13495: Break completion cycles

### LINKED ISSUE #13495: Cyclic reference involving variable with match type
## Compiler version

Scala 3.0.2 (Scastie)

## Minimized code

```Scala
import scala.annotation.showAsInfix

trait Component
sealed trait Deleted extends Component

type Deletable[L <: CList] <: CList = L match {
  case h &: t => (h | Deleted) &: Deletable[t]
  case CNil => CNil
}

sealed trait CList
sealed trait CNil extends CList
@showAsInfix case class &:[+C <: Component, +L <: CList](h: C, t: L) extends CList

case class A(x: Int, y: Int) extends Component
case class B(x: Int, y: Int) extends Component

val x: Deletable[A &: B &: CNil] = ???
```

## Output

Compiler error:
```
Cyclic reference involving val x
```

## Expectation

No compiler error. I expect the type of x to be `(A | Deleted) &: (B | Deleted) &: CNil`.

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -1611,7 +1611,7 @@ object SymDenotations {
                   case _ => false
 
         if owner.isClass then
-          for c <- owner.info.decls.toList if maybeChild(c) do
+          for c <- owner.info.decls.toList if maybeChild(c) && (c.isClass || c.is(EnumVal)) do
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1614]: This duplicates similar checks done in `maybeChild`, this can probably be avoided by tweaking maybeChild a bit.
