### PR TITLE
Fix #5970: suppress spurious warning in isInstanceOf check

### LINKED ISSUE #5970: Union matching not exhaustive or refining
Compiling the following,
```scala
object Test extends App {
  case class Foo[T](t: T)

  def foo[T](ft: T|Foo[T]): T = {
    ft match {
      case Foo(t) => t
      case t => t
    }
  }

  foo(Foo(23))
}
```
results in,
```
-- [E007] Type Mismatch Error: tests/run/typeclass-derivation7.scala:6:21 ------
6 |      case Foo(t) => t
  |                     ^
  |          Found:    T$1(t)
  |          Required: T
  |          
  |          where:    T is a type in method foo with bounds >: Test.Foo[T$1]
-- [E007] Type Mismatch Error: tests/run/typeclass-derivation7.scala:7:16 ------
7 |      case t => t
  |                ^
  |                Found:    (T | Test.Foo[T])(t)
  |                Required: T
two errors found
```
Intuitively the pattern matcher ought to be able to see that the `t`'s on the RHS's of the branches conform to `T`. If we add type tests,
```scala
object Test extends App {
  case class Foo[T](t: T)

  def foo[T](ft: T|Foo[T]): T = {
    ft match {
      case Foo(t: T) => t
      case t: T => t
    }
  }

  foo(Foo(23))
}
```
The match is reported as not exhaustive and the type tests are reported as uncheckable, despite being intuitively irrefutable.

Replacing the `T` in the union with `Unit` eliminates the non-exhaustiveness, but still results in a complaint about uncheckability,
```scala
object Test extends App {
  case class Foo[T](t: T)

  def foo[T](ft: Unit|Foo[T]): T = {
    ft match {
      case Foo(t) => t
      case () => ???
    }
  }

  foo(Foo(23))
}
```
```
-- Warning: tests/run/typeclass-derivation7.scala:6:11 -------------------------
6 |      case Foo(t) => t
  |           ^^^^^^
  |           the type test for Test.Foo[T] cannot be checked at runtime
one warning found
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #5970: suppress spurious warning in isInstanceOf check

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -1575,6 +1575,17 @@ object SymDenotations {
...
+     *
+     *  @note The test is based on single-class inheritance and the closed
+     *        hierarchy of final classes.
+     *
+     *  @return The result may contain false positives, but never false negatives.
+     */
+    final def mayHaveCommonChild(that: ClassSymbol)(implicit ctx: Context): Boolean =
+      !this.is(Final) && !that.is(Final) && (this.is(Trait) || that.is(Trait)) ||
+        this.derivesFrom(that) || that.derivesFrom(this.symbol)
+
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: @OlivierBlanvillain I'm not sure if how this fits into your refactoring. Maybe we can delay this PR until the refactoring is merged.
