### PR TITLE
Fix #12128: Add test

### LINKED ISSUE #12128: Testing unusable with -Ysafe-init
Running munit tests using the `-Ysafe-init` flag crashes the compiler. This should be easy to reproduce on any project with munit test framework. Compiling and running the main build works fine though.

## Compiler version

3.0.0-RC2

## Repro steps

* Create a dotty project with 3.0.0-RC2
* Add the compiler flag.
```sbt
    Compile / scalacOptions ++= Seq( "-Ysafe-init") 
```
* Run test using `sbt test`

## Output (click arrow to expand)
<details>

```scala
[info] cannot take signature of MethodType(List(c), List(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class macros)),object blackbox),Context)), MethodType(List(code), List(TypeRef(TermParamRef(c),Tree)), TypeRef(TermParamRef(c),Tree)))
[info] exception occurred while compiling /Users/swoorup.joshi/Downloads/test/src/test/scala/Test1.scala
cannot resolve reference to type c.type.Tree
the classfile defining the type might be missing from the classpath while compiling /Users/swoorup.joshi/Downloads/test/src/test/scala/Test1.scala
[error] ## Exception when compiling 1 sources to /Users/swoorup.joshi/Downloads/test/target/scala-3.0.0-RC2/test-classes
[error] dotty.tools.dotc.core.MissingType: 
[error] dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:776)
[error] dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:204)
[error] dotty.tools.dotc.core.Signature$.apply(Signature.scala:169)
[error] dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3392)
[error] dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3413)
[error] dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3388)
[error] dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3413)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:612)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:602)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.atSignature(Denotations.scala:644)
[error] dotty.tools.dotc.core.Denotations$SingleDenotation.atSignature(Denotations.scala:642)
[error] dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1215)
[error] dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1289)
[error] dotty.tools.dotc.core.tasty.TreeUnpickler.readRhs$2$$anonfun$2$$anonfun$1(TreeUnpickler.scala:811)
[error] dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1426)
[error] dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy(Trees.scala:967)
[error] dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy$(Trees.scala:962)
[error] dotty.tools.dotc.ast.Trees$ValOrDefDef.forceIfLazy(Trees.scala:377)
[error] dotty.tools.dotc.ast.Trees$ValOrDefDef.rhs(Trees.scala:382)
[error] dotty.tools.dotc.printing.RefinedPrinter.defDefToText$$anonfun$4$$anonfun$3(RefinedPrinter.scala:860)
[error] dotty.tools.dotc.printing.RefinedPrinter.withEnclosingDef(RefinedPrinter.scala:47)
[error] dotty.tools.dotc.printing.RefinedPrinter.defDefToText$$anonfun$1(RefinedPrinter.scala:861)
[error] dotty.tools.dotc.printing.RefinedPrinter.dclTextOr(RefinedPrinter.scala:783)
[error] dotty.tools.dotc.printing.RefinedPrinter.defDefToText(RefinedPrinter.scala:862)
[error] dotty.tools.dotc.printing.RefinedPrinter.toTextCore(RefinedPrinter.scala:541)
[error] dotty.tools.dotc.printing.RefinedPrinter.toText$$anonfun$2(RefinedPrinter.scala:674)
[error] dotty.tools.dotc.printing.MessageLimiter.controlled(MessageLimiter.scala:23)
[error] dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:36)
[error] dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:745)
[error] dotty.tools.dotc.ast.Trees$Tree.toText(Trees.scala:197)
[error] dotty.tools.dotc.printing.Showable.show(Showable.scala:23)
[error] dotty.tools.dotc.printing.Showable.show$(Showable.scala:9)
[error] dotty.tools.dotc.ast.Trees$Tree.show(Trees.scala:56)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBodyStat$2(Checking.scala:97)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$3(Checking.scala:173)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:173)
[error] dotty.tools.dotc.transform.init.Checking$.checkConstructor$1$$anonfun$1(Checking.scala:123)
[error] dotty.tools.dotc.transform.init.Util$.traceOp(Util.scala:18)
[error] dotty.tools.dotc.transform.init.Checking$.checkConstructor$2(Checking.scala:126)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$2(Checking.scala:169)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:170)
[error] dotty.tools.dotc.transform.init.Checking$.checkConstructor$1$$anonfun$1(Checking.scala:123)
[error] dotty.tools.dotc.transform.init.Util$.traceOp(Util.scala:18)
[error] dotty.tools.dotc.transform.init.Checking$.checkConstructor$2(Checking.scala:126)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$2(Checking.scala:169)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:170)
[error] dotty.tools.dotc.transform.init.Checking$.checkConstructor$1$$anonfun$1(Checking.scala:123)
[error] dotty.tools.dotc.transform.init.Util$.traceOp(Util.scala:18)
[error] dotty.tools.dotc.transform.init.Checking$.checkConstructor$2(Checking.scala:126)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$2(Checking.scala:164)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:170)
[error] dotty.tools.dotc.transform.init.Checker.transformTypeDef(Checker.scala:60)
[error] dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:989)
[error] dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:990)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:257)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:437)
[error] dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:442)
[error] dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:382)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:385)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:429)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:448)
[error] dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:460)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:230)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:166)
[error] dotty.tools.dotc.Run.compile(Run.scala:150)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2346)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2303)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2299)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]            
[error] dotty.tools.dotc.core.MissingType: 
[error]         at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:776)
[error]         at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:204)
[error]         at dotty.tools.dotc.core.Signature$.apply(Signature.scala:169)
[error]         at dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3392)
[error]         at dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3413)
[error]         at dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3388)
[error]         at dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3413)
[error]         at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:612)
[error]         at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:602)
[error]         at dotty.tools.dotc.core.Denotations$SingleDenotation.atSignature(Denotations.scala:644)
[error]         at dotty.tools.dotc.core.Denotations$SingleDenotation.atSignature(Denotations.scala:642)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1215)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1289)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler.readRhs$2$$anonfun$2$$anonfun$1(TreeUnpickler.scala:811)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1426)
[error]         at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy(Trees.scala:967)
[error]         at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy$(Trees.scala:962)
[error]         at dotty.tools.dotc.ast.Trees$ValOrDefDef.forceIfLazy(Trees.scala:377)
[error]         at dotty.tools.dotc.ast.Trees$ValOrDefDef.rhs(Trees.scala:382)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.defDefToText$$anonfun$4$$anonfun$3(RefinedPrinter.scala:860)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.withEnclosingDef(RefinedPrinter.scala:47)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.defDefToText$$anonfun$1(RefinedPrinter.scala:861)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.dclTextOr(RefinedPrinter.scala:783)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.defDefToText(RefinedPrinter.scala:862)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.toTextCore(RefinedPrinter.scala:541)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.toText$$anonfun$2(RefinedPrinter.scala:674)
[error]         at dotty.tools.dotc.printing.MessageLimiter.controlled(MessageLimiter.scala:23)
[error]         at dotty.tools.dotc.printing.PlainPrinter.controlled(PlainPrinter.scala:36)
[error]         at dotty.tools.dotc.printing.RefinedPrinter.toText(RefinedPrinter.scala:745)
[error]         at dotty.tools.dotc.ast.Trees$Tree.toText(Trees.scala:197)
[error]         at dotty.tools.dotc.printing.Showable.show(Showable.scala:23)
[error]         at dotty.tools.dotc.printing.Showable.show$(Showable.scala:9)
[error]         at dotty.tools.dotc.ast.Trees$Tree.show(Trees.scala:56)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBodyStat$2(Checking.scala:97)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$3(Checking.scala:173)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:173)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkConstructor$1$$anonfun$1(Checking.scala:123)
[error]         at dotty.tools.dotc.transform.init.Util$.traceOp(Util.scala:18)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkConstructor$2(Checking.scala:126)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$2(Checking.scala:169)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:170)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkConstructor$1$$anonfun$1(Checking.scala:123)
[error]         at dotty.tools.dotc.transform.init.Util$.traceOp(Util.scala:18)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkConstructor$2(Checking.scala:126)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$2(Checking.scala:169)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:170)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkConstructor$1$$anonfun$1(Checking.scala:123)
[error]         at dotty.tools.dotc.transform.init.Util$.traceOp(Util.scala:18)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkConstructor$2(Checking.scala:126)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody$$anonfun$2(Checking.scala:164)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at dotty.tools.dotc.transform.init.Checking$.checkClassBody(Checking.scala:170)
[error]         at dotty.tools.dotc.transform.init.Checker.transformTypeDef(Checker.scala:60)
[error]         at dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:989)
[error]         at dotty.tools.dotc.transform.MegaPhase.goTypeDef(MegaPhase.scala:990)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:257)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:437)
[error]         at dotty.tools.dotc.transform.MegaPhase.recur$1(MegaPhase.scala:442)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:442)
[error]         at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:382)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:385)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:429)
[error]         at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:448)
[error]         at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:460)
[error]         at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
[error]         at scala.collection.immutable.List.map(List.scala:246)
[error]         at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
[error]         at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error]         at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
[error]         at dotty.tools.dotc.Run.compileSources(Run.scala:166)
[error]         at dotty.tools.dotc.Run.compile(Run.scala:150)
[error]         at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error]         at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error]         at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error]         at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
[error]         at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error]         at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
[error]         at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error]         at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
[error]         at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2346)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2303)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2299)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Test / compileIncremental) dotty.tools.dotc.core.MissingType: 
[error] Total time: 5 s, completed 17 Apr. 2021, 2:24:07 pm
```
</details>

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #12128: Add test

When we are reading a new definition from tasty and setting `info` of
a symbol in `readNewDef`:

          sym.info = methodType(paramss, resType)

The line above will reach `TreeChecker.transformSym`:

          assert(symd.signature == initial.signature

At the time, the `symd` is not yet completed. Getting signature of the
denotation will force the symbol and trigger completion of the info,
which reaches the `PositionTree` in `readIndexedDef`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala [hunk 1]
```diff
@@ -332,6 +332,8 @@ class TreePickler(pickler: TastyPickler) {
 
   def pickleDef(tag: Int, mdef: MemberDef, tpt: Tree, rhs: Tree = EmptyTree, pickleParams: => Unit = ())(using Context): Unit = {
     val sym = mdef.symbol
+    if sym.isScala2MacroInScala3 then return
```
Comment (griggt) [inline compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala:335]: Doesn't this break the use of Scala 3 compiled artifacts containing mixed Scala 2/3 macros from Scala 2?

If I understand this change correctly, given the following code example:

```scala
object MacroCompat {
  trait LocationMacro {
    inline implicit def location: Location = ${ locationImpl() }
    implicit def location: Location = macro MacroCompatScala2.locationImpl
  }
  def locationImpl()(using Quotes): Expr[Location] = '{ new Location(${Expr(0)}) }
}
```

this `def`:

```
implicit def location: Location = macro MacroCompatScala2.locationImpl
```

will no longer be pickled in TASTy.  But doesn't that mean that the `location` macro is now inaccessible from Scala 2 using `-Ytasty-reader`?

---

As a test, I tried a small adaptation (repo [here](https://github.com/griggt/mix-macros)) of the [mixing macros example](https://scalacenter.github.io/scala-3-migration-guide/docs/tutorials/macro-mixing.html) in the Scala 3 migration guide with this PR.  (This also required changing the TASTy minor and experimental versions to 0 to force compatibility with 2.13.6.) Compilation failed due to the missing method:

```scala
sbt:mix-macros> ++3.0.1-RC1-bin-SNAPSHOT! exampleLib/compile
  ... successful compilation ...

sbt:mix-macros> ++2.13.6 exampleTest/run
[info] Setting Scala version to 2.13.6 on 1 projects.
[info] Excluded 2 projects, run ++ 2.13.6 -v for more details.
[info] Reapplying settings...
[info] set current project to mix-macros (in build file:/src/mix-macros/)
[info] compiling 1 Scala source to /src/mix-macros/test/target/scala-2.13/classes ...
[error] /src/mix-macros/test/src/main/scala/Test.scala:5:39: Unsupported Scala 3 inline macro method location; found in object location.Macros.
[error]     println(s"We are on line ${Macros.location.line}")
[error]                                       ^
[error] one error found
```

I ran into the same issue attempting to use a version of MUnit compiled with this PR from Scala 2.13.6 (the Scala 3 published MUnit artifact is [intended to be usable from Scala 2](https://scalameta.org/munit/blog/2021/01/05/macromix.html)):

```
[error] /tmp/munit-simple/src/test/scala/Test.scala:2:23: Unsupported Scala 3 inline macro method generate; found in trait munit.internal.MacroCompat.LocationMacro.
```

```scala
// munit-simple/src/test/scala/Test.scala
class Test1 extends munit.FunSuite {
  test("Simple test") {
    assertEquals(1,2)
  }
}
```

**Review by griggt — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala:335]: Thank you for looking into it @griggt . Yes, you are right, we have to pickle the Scala 2 macro definition to support the migration use case. I'll try a different fix.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala]: @griggt In c259f4d, we have a different fix that does not touch the pickler.

File: tests/init/crash/i12128/Reflect_1.scala [hunk 2]
```diff
@@ -0,0 +1,30 @@
+trait Context: // Dummy scala.reflect.macros.Context
```
Comment (griggt) [inline tests/init/crash/i12128/Reflect_1.scala:1]: This regression test using the dummy `scala.reflect.macros.Context` for some reason does not trigger the issue reported in #12128.  It passes when compiled with 3.0.0 (aside from the cyclic reference while unpickling if -Ycheck is specified).

So, I have manually verified that the issue is fixed, but the test passes even without the fix in place.  :confused: 

It's the end of my day here, but I can probably find time to investigate this tomorrow if needed.

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 3]
```diff
@@ -91,7 +91,7 @@ class TreeChecker extends Phase with SymTransformer {
     // until erasure, see the comment above `Compiler#phases`.
     if (ctx.phaseId <= erasurePhase.id) {
       val initial = symd.initial
-      assert(symd.signature == initial.signature,
+      assert(!symd.isCompleted || symd.signature == initial.signature,
```
[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:94]: Thanks @griggt ! Here `!symd.isCompleted` should be equivalent to `symd == initial`, which means we are not missing some invariants. I'll update the code with the latter, which is better.

File: tests/init/crash/i12128/Reflect_1.scala (hunk 2 above)
Comment (liufengyun) [reply tests/init/crash/i12128/Reflect_1.scala:1]: > This regression test using the dummy scala.reflect.macros.Context for some reason does not trigger the issue reported in #12128.
> So, I have manually verified that the issue is fixed

Thanks for checking that. I intended to add the original example as a test, but as it depends on `scala-reflect`, which makes it difficult to do so --- creating a dummy `Context` seems to be the closest thing that can be done.

Comment (griggt) [reply tests/init/crash/i12128/Reflect_1.scala:1]: I have some (mostly complete) changes that I believe will make the test case work properly without the dependency on `scala-reflect`. I'll finish and push them in the morning.

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 4]
```diff
@@ -91,7 +91,7 @@ class TreeChecker extends Phase with SymTransformer {
     // until erasure, see the comment above `Compiler#phases`.
     if (ctx.phaseId <= erasurePhase.id) {
       val initial = symd.initial
-      assert(symd.signature == initial.signature,
+      assert(symd == initial || symd.signature == initial.signature,
```
[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:94]: Yes, using `eq` is a good idea, semantically they are the same for Dotty. BTW, we usually use backquote for non-symbolic infix operators.

File: tests/init/crash/i12128/Reflect_1.scala (hunk 2 above)
Comment (griggt) [reply tests/init/crash/i12128/Reflect_1.scala]: Considering the regression test consists of three components:

  (a) Reflect_1 (as a stand-in for `scala-reflect`)
  (b) Macro_2 (as a stand-in for `munit`)   
  (c) Test_3 (user code)

the key to reproduce the issue in #12128 is to compile these separately, with

  - the output from (a) on the classpath while compiling (b)
  - the output from (b) on the classpath while compiling (c)
  - the output from (a) *_not_* on the classpath while compiling (c)

In the real-world case of #12128, this situation occurs because MUnit has a `Provided` dependency on `scala-reflect`:
https://github.com/scalameta/munit/blob/d592d71f8360f1eaae2f19c1d582b75fe5d44714/build.sbt#L178-L182

I have rebased (to resolve conflicts) and pushed a commit which modifies the testing to meet the above requirements.

Incidentally, #12128 seems to have been fixed both by #12484 (for the old init checker) and #12495 (the new init checker).

**Review by liufengyun — COMMENTED** [review]
Thank you @griggt , LGTM.

I'm wondering if we should keep a copy of the test with normal compilation, as it tests a different stack trace. Or, it has the same stack trace as if compiled normally?

**Comment by liufengyun** [comment]
> I'm wondering if we should keep a copy of the test with normal compilation, as it tests a different stack trace. Or, it has the same stack trace as if compiled normally?

Just checked, the modified test still has the same stack trace, so we are good.

**Comment by griggt** [comment]
> I'm wondering if we should keep a copy of the test with normal compilation, as it tests a different stack trace. Or, it has the same stack trace as if compiled normally?

The revised test I pushed (with separate classpaths) gives the following stack trace on 3.0.0:

```
java.lang.AssertionError: assertion failed: Cyclic reference while unpickling definition at address 188 in unit tests/init/special/i12128/Test_3.scala while compiling tests/init/special/i12128/Test_3.scala
Fatal compiler crash when compiling: tests/init/special/i12128/Test_3.scala:
assertion failed: Cyclic reference while unpickling definition at address 188 in unit tests/init/special/i12128/Test_3.scala
scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:771)
dotty.tools.dotc.core.tasty.TreeUnpickler$Completer.complete(TreeUnpickler.scala:122)
dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:610)
dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:602)
dotty.tools.dotc.transform.TreeChecker.transformSym(TreeChecker.scala:94)
    ....
```

and this stack trace on 3.0.0 with the TreeChecker fix from this PR:

```
cannot resolve reference to type c.type.Tree
the classfile defining the type might be missing from the classpath while compiling tests/init/special/i12128/Test_3.scala
Fatal compiler crash when compiling: tests/init/special/i12128/Test_3.scala:
dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:776)
dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:204)
dotty.tools.dotc.core.Signature$.apply(Signature.scala:169)
dotty.tools.dotc.core.Types$MethodOrPoly.computeSignature$1(Types.scala:3394)
dotty.tools.dotc.core.Types$MethodOrPoly.signature(Types.scala:3415)
dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:612)
dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:602)
  ....
```

So I believe we are ok.

**Review by griggt — APPROVED** [review]
