### PR TITLE
Fix #8781: handle union of primitive types in type test

### LINKED ISSUE #8781: Matching Over Unions With Primitive Type Problem
## Minimized example

```Scala
object test:

  val x: Int | String = 1

  x match
    case _: Int =>
    case _: String =>
```

## Output

```scala
-- Error: i8779.scala:6:9 ------------------------------------------------------
6 |    case _: Int =>
  |         ^
  |this case is unreachable since type Int | String is not a subclass of class Integer
```

## Expectation

Should compile.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #8781: handle union of primitive types in type test

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 1]
```diff
@@ -199,29 +199,38 @@ object TypeTestsCasts {
                // if `test` is primitive but `found` is not, we might have a case like
                // found = java.lang.Integer, test = Int, which could be true
                // (not sure why that is so, but scalac behaves the same way)
+            !(!testCls.isPrimitiveValueClass && foundCls.isPrimitiveValueClass) &&
+               // foundCls can be `Boolean`, while testCls is `Integer`
+               // it can happen in `(3: Boolean | Int).isInstanceOf[Boolean]`
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:204]:
```suggestion
               // it can happen in `(3: Boolean | Int).isInstanceOf[Int]`
```
