### PR TITLE
Fix references to class members defined in quotes

### LINKED ISSUE #17103: Reference to quoted local member fails to in quote pickling
## Compiler version

3.3.1-RC1-bin-20230313-f28d708-NIGHTLY and before

## Minimized code

```Scala
import scala.quoted.*

def test(using Quotes): Expr[Unit] =
  '{
    trait C:
      val d: D
    trait D
    val c: C = ???
    ${
      val expr = '{
        val cRef: c.type = ???
        cRef.d
        ()
      }
      expr
    }
  }
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" 
  unhandled exception while running pickleQuotes on tests/neg-macros/path-dependent-type-capture.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/lampepfl/dotty/issues/new/choose

     while compiling: <no file>
        during phase: <no phase>
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.10
    compiler version: version 3.3.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-29e229b
            settings: -Vprint List(splicing, staging) -classpath /Users/nicolasstucki/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar:/Users/nicolasstucki/Github/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.3.1-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.3.1-RC1-bin-SNAPSHOT.jar -d t/out -pagewidth 120

                tree: EmptyTree
       tree position: :<unknown>
           tree type: <notype>
              symbol: val <none>
           call site: package <root> in module class <root>

  == Source file context for tree position ==
java.lang.AssertionError: assertion failed: unresolved symbols: value cRef (line 11) #15683 when pickling tests/neg-macros/path-dependent-type-capture.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:809)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:222)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:34)
        at dotty.tools.dotc.transform.PickleQuotes$.pickleAsTasty$1(PickleQuotes.scala:291)
        ...
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**
If an inner quote selects a symbol that is defined in an outer quote we need to transform it or reject it. The issue is that the inner quote cannot contain a reference to the type of the class defined in the outer quote. Any such reference is erased the parents of that class that are statically know outside those quotes. If the selected symbol is overriding a symbol in one of those statically known classes, we can use that overridden symbol instead. If not we have to reject the code.

Fixes #17103

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 1]
```diff
@@ -208,6 +208,14 @@ class Splicing extends MacroTransform:
 
     override def transform(tree: tpd.Tree)(using Context): tpd.Tree =
       tree match
+        case tree: Select if tree.isTerm && isCaptured(tree.symbol) =>
+          tree.symbol.allOverriddenSymbols.find(sym => !isCaptured(sym.owner)) match
```
Comment (natsukagami) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:212]: Does it matter if there are multiple overridden symbols that are not captured? I think it doesn't but just want to make sure.

**Review by natsukagami — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:212]: It should no matter.
