### PR TITLE
Fix #3561: Correctly handle switches followed by other tests in matches

### LINKED ISSUE #3561: Compiler crashes when trying to emit invalid @switch
```scala
class Test {
  val Constant = 'Q' // OK if final
  def tokenMe(ch: Char) = (ch: @annotation.switch) match {
    case ' ' => 1
    case 'A' => 2
    case '5' | Constant => 3
  }
}
```
<details>
  <summary>Stacktrace</summary>
  <pre>
[info] Running dotty.tools.dotc.Main -classpath /Users/renucci/projects/dotty/library/target/scala-2.12/dotty-library_2.12-0.5.0-bin-SNAPSHOT-nonbootstrapped.jar -d out tests/allan/Test.scala
exception occurred while compiling tests/allan/Test.scala
Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitSwitchCases(PatternMatcher.scala:818)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitSwitchCases(PatternMatcher.scala:820)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitSwitchCases(PatternMatcher.scala:820)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitSwitchCases(PatternMatcher.scala:820)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emitSwitchCases(PatternMatcher.scala:820)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emit(PatternMatcher.scala:838)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emit(PatternMatcher.scala:846)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.emit(PatternMatcher.scala:842)
	at dotty.tools.dotc.transform.PatternMatcher$Translator.translateMatch(PatternMatcher.scala:932)
	at dotty.tools.dotc.transform.PatternMatcher.transformMatch(PatternMatcher.scala:31)
	at dotty.tools.dotc.transform.MegaPhase.goMatch(MegaPhase.scala:711)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:323)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:365)
	at dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:228)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:231)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:364)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$1(MegaPhase.scala:373)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$transformStats$2(MegaPhase.scala:378)
	at scala.collection.immutable.List.mapConserve(List.scala:176)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:378)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:317)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:365)
	at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:234)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:364)
	at dotty.tools.dotc.transform.MegaPhase.transformStat$1(MegaPhase.scala:373)
	at dotty.tools.dotc.transform.MegaPhase.$anonfun$transformStats$2(MegaPhase.scala:378)
	at scala.collection.immutable.List.mapConserve(List.scala:176)
	at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:378)
	at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:334)
	at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:337)
	at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:365)
	at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:384)
	at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:396)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:289)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:287)
	at dotty.tools.dotc.core.Phases$Phase.runOn$(Phases.scala:286)
	at dotty.tools.dotc.transform.MegaPhase.runOn(MegaPhase.scala:138)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:125)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:123)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:121)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:121)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:141)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:86)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:107)
	at dotty.tools.dotc.Run.compileSources(Run.scala:94)
	at dotty.tools.dotc.Run.compile(Run.scala:78)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:29)
	at dotty.tools.dotc.Driver.process(Driver.scala:127)
	at dotty.tools.dotc.Driver.process(Driver.scala:96)
	at dotty.tools.dotc.Driver.process(Driver.scala:108)
	at dotty.tools.dotc.Driver.main(Driver.scala:135)
	at dotty.tools.dotc.Main.main(Main.scala)
 </pre>
</details>
<br/>

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by smarter** [comment]
Trying to test this I noticed that something seems very broken with `@switch`, we get the `Could not emit switch for @switch annotated match` in all these cases (both before and after this PR):
```scala
import scala.annotation.switch

object Test {
  def foo1(x: Int) = (x: @switch) match {
    case 1 =>
      println("a")
  }
  def foo2(x: Int) = (x: @switch) match {
    case 1 =>
      println("b")
    case 2 =>
      println("c")
  }
  def foo3(x: Int) = (x: @switch) match {
    case 1 | 2 =>
      println("d")
  }
}
```
However, this one works somehow:
```scala
import scala.annotation.switch

object Test {
  def foo4(x: Int) = (x: @switch) match {
    case 1 =>
      println("e")
    case 2 | 3 =>
      println("f")
  }
}
```

**Comment by nicolasstucki** [comment]
@smarter, when there are 1 or 2 (maybe 3 with default) branches in the pattern match the pattern is always compiled with `if/else` even if it could potentially do a `switch`. That is why the first ones fail the `@switch` tests. We should probably emit a better warning message or just disregard it in those cases.

File: tests/run/switches.scala [hunk 1]
```diff
@@ -18,7 +18,7 @@ object Test extends App {
     case _ => 4
   }
 
-  val x3 = (x: @switch) match {
+  val x3 = x match {
     case '0' if x > 0 => 0
```
Comment (smarter) [inline tests/run/switches.scala]: scalac supports emitting switch when cases contain conditions, it translates something like:
```scala
  def foo(x: Int, cond: Boolean) = x match {
    case 1 if cond =>
      println("1")
    case 2 =>
      println("2")
    case 3 =>
      println("3")
    case _ =>
      println("4")
  }
```
to
```scala
      x1 match {
        case 1 => if (cond)
          scala.Predef.println("1")
        else
          default5()
        case 2 => scala.Predef.println("2")
        case 3 => scala.Predef.println("3")
        case _ => default5(){
          scala.Predef.println("4")
        }
      }
```
Is this an intended limitation of Dotty `@switch`, or something that still needs to be implemented?

Comment (nicolasstucki) [reply tests/run/switches.scala]: This was supposed to go in the local optimizations. I made an implementation of this a while ago but I do not know if it went into Dotty or just stayed in the linker.

Comment (smarter) [reply tests/run/switches.scala]: I think it would make sense to have it by default. Could you open an issue so we keep track of it?

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 2]
```diff
@@ -967,12 +967,21 @@ object PatternMatcher {
...
-          tpes.toSet.size: Int // without the type ascription, testPickling fails because of #2840.
+        def typesInPattern(pat: Tree): List[Type] = pat match {
+          case Alternative(pats) => pats.flatMap(typesInPattern)
+          case _ => pat.tpe :: Nil
         }
-        if (numConsts(resultCases) < numConsts(original.cases))
+        def typesInCases(cdefs: List[CaseDef]): List[Type] =
+          cdefs.flatMap(cdef => typesInPattern(cdef.pat))
+        def numTypes(cdefs: List[CaseDef]): Int =
+          typesInCases(cdefs).toSet.size: Int // without the type ascription, testPickling fails because of #2840.
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: #2840 is fixed, it should be safe to remove the ascription

**Comment by nicolasstucki** [comment]
This PR needs a rebase

File: tests/run/switches.scala (hunk 1 above)
Comment (smarter) [reply tests/run/switches.scala]: > Could you open an issue so we keep track of it?

Turns out there's already one: https://github.com/lampepfl/dotty/issues/1313
