### PR TITLE
Fix named arguments evaluation order with by-name parameters

### LINKED ISSUE #25160: Unexpected named arguments evaluation order when by-name parameters are present
## Compiler version

- Scala 2.13.18: call-site order
- Scala 3.8.1: parameter definition order
  - (confirmed 3.2.0~ has this behavior, and 3.0.x and 3.1.x generates invalid bytecode) 

## Minimized code

```scala
abstract class Foo(a: => Int, b: Int, c: Int)

object Bar extends Foo(
  b = { println("b evaluated"); 2 },
  c = { println("c evaluated"); 3 },
  a = { println("a evaluated"); 1 }
)

object Main {
  def main(args: Array[String]): Unit = {
    Bar
  }
}
```

## Output

```scala
$ scala-cli -S 2.13.18 test.scala
b evaluated
c evaluated
```

```scala
$ scala-cli -S 3.8.1 test.scala
c evaluated
b evaluated
```

## Expectation

Arguments should be evaluated in **call-site order** (as Scala 2 does), instead of parameter definition order (as Scala 3 does).
(The difference appears only when there's a by-name parameter is involved 🤔 . Without the by-name parameter `a: => Int`, both versions evaluate in call-site order.)

According to the scala specification ([3.4](https://scala-lang.org/files/archive/spec/3.4/06-expressions.html) `6.6.1 Named and Default Arguments`), IIUC, the arguments should be evaluated in left-to-right at call-site.

### PR DESCRIPTION
**Pull request by tanishiking**
Fix #25160 
(https://github.com/scala/scala3/issues/24201 is kinda variant of this issue, it's default argument is involved. In that case, we use `LiftComplex` instead of `LiftImpure`, and lifting `ExprType` is the problem...)

---

Previously, when named arguments were reordered and by-name parameters were there, arguments were evaluated in wired order.

```scala
abstract class Foo(a: => Int, b: Int, c: Int)

object Bar extends Foo(
  b = { println("b evaluated"); 2 },  // call-site position 0
  c = { println("c evaluated"); 3 },  // call-site position 1
  a = { println("a evaluated"); 1 }   // call-site position 2 (by-name, shouldn't be evaluated)
)

object Main {
  def main(args: Array[String]): Unit = {
    Bar
  }
}
```

It should be evaluated in `b evaluated` -> `c evaluated` (call-site order), but actually, `c evaluated` and then `b evaluated`.

---

The problem was in `impureArgIndices` which use `lifter.noLift(arg)` for all arguments, while `liftArgs` uses different lifters based on parameter type: `liftArgs` uses `exprLifter` for by-name parameters.

```scala
val impureArgIndices = typedArgBuf.zipWithIndex.collect {
  case (arg, idx) if !lifter.noLift(arg) => idx
}
```

- For the above case, it's `[0, 1, 2]` but it should be `[1, 2]` because `a` won't be lifted (because `exprLifter = NoLift` for `LiftImpure`).
- Later, it's zipped with `argDefBuf` which should be a list of actually lifted definitions `[def_b, def_c]`.
- `argDefBuf.zip(impureArgIndices)` will be `[(def_b, 0), (def_c, 1)]`
- sort by `originalIndices` (call-site positions) `[2, 0, 1]` (because it's `b, c, a` at call-site) -> `[def_c, def_b]`

```scala
// ...
scala.util.Sorting.stableSort[(Tree, Int), Int](
  argDefBuf.zip(impureArgIndices), (arg, idx) => originalIndex(idx)).map(_._1)
```

---

This commit fixes by `Application` to use the same logic as `Lifter`s to check the argument would be lifted or not.

- The above example now have `[1, 2]` for `impureArgIndices`
- `argDefBuf.zip(impureArgIndices)` will be `[(def_b, 1), (def_c, 2)]`
- sort by `originalIndices` (call-site positions) `[2, 0, 1]` -> `[def_b, def_c]`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -1144,8 +1144,11 @@ trait Applications extends Compatibility {
             // with all non-explicit default parameters at the end in declaration order.
             val orderedArgDefs = {
               // Indices of original typed arguments that are lifted by liftArgs
-              val impureArgIndices = typedArgBuf.zipWithIndex.collect {
-                case (arg, idx) if !lifter.noLift(arg) => idx
+              val impureArgIndices = {
+                val paramInfos = methType.paramInfoss.flatten
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala]: I think we only need the parameter infos from the current `MethodType`?

Comment (tanishiking) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: Right, fixed to use `methodType.paramInfos` instead 👍

**Review by odersky — APPROVED** [review]

**Comment by tanishiking** [comment]
Thanks @noti0na1 @odersky !
