### PR TITLE
Fix #8681: handle scrutinee of union types

### LINKED ISSUE #8681: No compilation error on invalid case statements when pattern matching on union types
## Minimized code

```Scala
case class A(a: Int)
case class B(b: Int)
case class C(c: Int)

val a = (A(1): A) match {
  case A(_) => "OK"
  case B(_) => "NOT OK" // Compiler Error: this case is unreachable since class A and class B are unrelated
}

val b = (A(1): A | B) match {
  case A(_) => "OK"
  case B(_) => "OK"
  case C(_) => "NOT OK" // No Compiler Error
}
```

## Output

```scala
[error]    |  case B(_) => "NOT OK"
[error]    |       ^
[error]    |       this case is unreachable since class A and class B are unrelated
```

## Expectation

The compiler should also yield an unreachable code error for the second match statement when trying to match on `C` since it's not related to type `A | B`.

### LINKED ISSUE #8711: Unreachability check for pattern is not precise enough when the scrutinee is a union
```Scala
class A
class B
class C

object Test {
  def foo(x: A) = x match {
    case x: B => x // as expected, error: this case is unreachable since class A is not a subclass of class B
    case _ =>
  }

  def bar(x: A | B) = x match {
    case x: C => x // no error!
    case _ =>
  }
}
```
The logic handling this is in `TypeTestCast#interceptTypeApply#interceptWith#transformIsInstanceOf` which computes a class symbol for the scrutinee:
>           def foundCls = effectiveClass(expr.tpe.widen)

So when the pattern has type `A | B`, `testCls` will be `Any`. This logic needs to be adapted to handle union types where there's more than one possible class symbol.

### PR DESCRIPTION
**Pull request by liufengyun**
- Fix #8681: handle scrutinee of union types
- Fix #8711: add test

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 1]
```diff
@@ -214,38 +216,49 @@ object TypeTestsCasts {
...
-              constant(expr, Literal(Constant(foundCls == testCls)))
+          else {
+            val nestedCtx = ctx.fresh.setNewTyperState()
+            val foundClsSyms = foundClasses(expr.tpe.widen, Nil)
+            val sensical = foundClsSyms.exists(sym => checkSensical(sym)(using nestedCtx))
+            if (!sensical) {
+              nestedCtx.typerState.commit()
+              constant(expr, Literal(Constant(false)))
+            }
+            else if (testCls.isPrimitiveValueClass )
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:240]:
```suggestion
            else if (testCls.isPrimitiveValueClass)
```

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 2]
```diff
@@ -214,38 +216,49 @@ object TypeTestsCasts {
...
+              if (foundClsSyms.size == 1 && foundClsSyms.head.isPrimitiveValueClass)
+                constant(expr, Literal(Constant(foundClsSyms.head == testCls)))
+              else
+                transformIsInstanceOf(expr, defn.boxedType(testCls.typeRef), flagUnrelated)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:244]: I think this would be nicer as a pattern match `foundClsSyms match { case List(foundCls) => ... case _ => ... }`
