### PR TITLE
Fix #8619: Demand `transparent` for whitebox inlines

### LINKED ISSUE #8619: Change syntax of given whitebox macros
### Status quo

```Scala
inline def whiteBox1 <: T = ...
inline given whiteBox2 as _ <: T = ...
```
### Critique

 - Syntax is not consistent
 - You could argue that the first syntax is too quiet and also misleading since at first glance `whiteBox1` is in the position where you would expect to see a type.
 - `_ <: T` is technically wrong (or, rather, old style) since it suggests a lambda. We are after an existential instead.

### Proposal

Write `? <: T` (analogous to a wildcard type argument) to express both forms of whitebox macros. I.e.

```Scala
inline def whiteBox1: ? <: T = ...
inline given whiteBox2 as ? <: T = ...
```

Opinions?

### PR DESCRIPTION
**Pull request by odersky**
Previously, whitebox inlines could be declared in three different ways

 1. writing `inline def f <: T = ...` for inline methods
 2. writing `inline given f as _ <: T` = ...` for inline givens
 3. leaving out the result type for inline methods

The last was an oversight, not backed by the spec. It turned out that it
was not that easy to prevent (3), so it was not done, and afterwards
code exploited the loophole.

In the new scheme, "whitebox" inlines demand `transparent`. The result type
can be given or left out, the effect is the same. The old `<:` result type
syntax will be phased out in a subseqent PR once the new syntax is in a release.

`transparent` is a soft modifier. It is valid only together with `inline`. Why not
allow `transparent` on its own and let it subsume `inline`? The point is that
we should steer users firmly towards blackbox macros, since they are much
easier to deal with for tooling. This means we want to make whitebox macros
strictly more verbose than blackbox macros. Otherwise someone might find
`transparent` "nicer" than `inline` and simply use it on these grounds without
realizing (or caring about) the consequences.

For the same reason I did not follow the (otherwise tempting) idea to simply
re-use `opaque` instead of `transparent`. An opaque inline keeps its type on
expansion whereas a transparent one gets the type of its expansion. But that
would have nudged to user to prefer `inline` over `opaque inline`, so would
again have gjven the wrong incentive.

On the other hand, `transparent` as a dual of `opaque` is nice. It fits into
the same terminology. It's simply that type aliases are transparent by default
and have to be made opaque with a modifier, whereas inline methods are opaque
by default, and have to be made transparent by a modifier.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -33,6 +33,8 @@ object Parsers {
   import reporting.Message
   import reporting.messages._
 
+  val AllowOldWhiteboxSyntax = true
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: This seems to be unnecessary.

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 2]
```diff
@@ -863,10 +863,11 @@ class Namer { typer: Typer =>
...
     private def addInlineInfo(sym: Symbol) = original match {
       case original: untpd.DefDef if sym.isInlineMethod =>
-        PrepareInlineable.registerInlineInfo(
-            sym,
-            implicit ctx => typedAheadExpr(original).asInstanceOf[tpd.DefDef].rhs
-          )(localContext(sym))
+        def rhsToInline(using Context): tpd.Tree =
+          val mdef = typedAheadExpr(original).asInstanceOf[tpd.DefDef]
+          if original.mods.hasMod(classOf[untpd.Mod.Transparent]) then mdef.rhs
+          else tpd.Typed(mdef.rhs, mdef.tpt)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala]:
```scala
PrepareInlineable.wrapRHS(original, mdef.tpt, mdef.rhs)
```

File: compiler/src/dotty/tools/dotc/typer/PrepareInlineable.scala [hunk 3]
```diff
@@ -223,7 +228,7 @@ object PrepareInlineable {
           inlined.updateAnnotation(LazyBodyAnnotation {
             given ctx as Context = inlineCtx
             val initialErrorCount = ctx.reporter.errorCount
-            var inlinedBody = treeExpr(ctx)
+            var inlinedBody = treeExpr(using ctx)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/PrepareInlineable.scala]:
```suggestion
            var inlinedBody = treeExpr
```

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 4]
```diff
@@ -203,13 +203,7 @@ object desugar {
...
    *      def f$default$2[T](x: Int) = x + "m"
    *
-   *  3. Convert <: T to : T in specializing inline methods. E.g.
-   *
-   *      inline def f(x: Boolean) <: Any = if (x) 1 else ""
-   *  ==>
-   *      inline def f(x: Boolean): Any = if (x) 1 else ""
-   *
-   *  4. Upcast non-specializing inline methods. E.g.
+   *  3. Upcast non-specializing inline methods. E.g.
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala]: We do not upcast at this point anymore

File: docs/docs/reference/contextual/givens.md [hunk 5]
```diff
@@ -79,17 +79,16 @@ given (using config: Config) as Factory = MemoizingFactory(config)
...
-## Given Whitebox Macro Instances
+## Given Macros
 
-An `inline` alias given can be marked as a whitebox macro by writing
-`_ <:` in front of the implemented type. Example:
+Given aliases can have the `inline` and `transparent` modifiers.
+Example:
 ```scala
-inline given mkAnnotations[A, T] as _ <: Annotations[A, T] = ${
+transparent inline given mkAnnotations[A, T] as Annotations[A, T] = ${
```
Comment (nicolasstucki) [inline docs/docs/reference/contextual/givens.md]: We need tests for this.

Comment (nicolasstucki) [reply docs/docs/reference/contextual/givens.md]: I mean, we do not have any tests with `transparent inline given ...`

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: This is so that someone can come back and remove the old syntax

File: compiler/src/dotty/tools/dotc/typer/Namer.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala]: Ah yes, I meant to get back to that change and then forgot!
