### PR TITLE
Fluidify explicit self types for non-CC classes

### LINKED ISSUE #25634: The self type of a class compiled without CC is not treated as fluid in CC
## Compiler version

3.8.4-RC1-bin-20260326-5d03b33-NIGHTLY
3.nightly

## Minimized code

`Stest_1.scala`

```scala
class A:
  self: A =>
```

`Stest_2.scala`

```scala
import language.experimental.captureChecking

class B extends A, caps.SharedCapability
```

`scala compile -S 3.nightly Stest_1.scala Stest_2.scala`

## Output

```scala
-- [E058] Type Mismatch Error: Stest_2.scala -----------------------------
105 |class B extends A, SharedCapability
    |      ^
    |illegal inheritance: self type B^ of class B does not conform to self type A
    |of parent class A
    |
    |where:    ^ refers to a root capability classified as SharedCapability in the type of class B
    |
    | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

Should compile.

## Discussion

This pattern happens with `munit`. I want to test an impure class, then I want to store the instance as a field in my test class which extends `munit.FunSuite`. `FunSuite`  has a self type, which is considered "pure" in cc, this rejects any impure field.

### PR DESCRIPTION
**Pull request by Linyxus**
Fixes #25634.

## How much have you relied on LLM-based tools in this contribution?

I used GPT-5.4 to pinpoint the root and produce a fix.

## How was the solution tested?

Human eyes and `testCompilation`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/Setup.scala [hunk 1]
```diff
@@ -147,6 +147,17 @@ class Setup extends PreRecheck, SymTransformer, SetupAPI:
     && !sym.owner.is(CaptureChecked)
     && !defn.isFunctionSymbol(sym.owner)
 
+  private def fluidifySelfInfo(info: Type)(using Context): Type = info match
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/Setup.scala]: This should make use of the existing method `fluidify`.

File: compiler/src/dotty/tools/dotc/cc/Setup.scala [hunk 2]
```diff
@@ -949,6 +953,13 @@ class Setup extends PreRecheck, SymTransformer, SetupAPI:
    */
   private def fluidify(using Context) = new TypeMap:
     def apply(t: Type): Type = t match
+      case cinfo: ClassInfo =>
+        val selfInfo1: TypeOrSymbol = cinfo.selfInfo match
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/Setup.scala]: You can use `givenSelfTyoe` here to simplify the logic.

Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/cc/Setup.scala]: Fixed. I wasn't aware of this helper! Thanks.

**Comment by Linyxus** [comment]
@odersky ping for review
