### PR TITLE
Fix #2939: Avoid duplicating symbols in default arguments

### LINKED ISSUE #2939: Pure expressions are never lifted from function calls, may be copied by default getters logic without creating new symbols, leading to duplicate methods after lambdalift
For this class, Dotty does not seem to work properly:
```scala
import scala.collection.mutable._

class Tag(val name: String, val buffer: Buffer[Tag] = ArrayBuffer()) {
	def space(n: Int = 0): String = {
	    s"${" " * n}<$name>\n" +
	        (if(buffer.isEmpty) "" else buffer.map(_.space(n + 4)).mkString("", "\n", "\n")) +
	    s"${" " * n}</$name>"
	}
	
	def apply[U](f: implicit Tag => U)(implicit tag: Tag = null): this.type = {
		f(this)
		if(tag != null) tag.buffer += this
		this
	}
	
	override def toString(): String = space(0)
}

object Tag {
	implicit def toTag(symbol: Symbol): Tag = new Tag(symbol.name)

	def main(args: Array[String]): Unit = {
	}
}
```
run by dotr(0.2.0-RC1-bin-SNAPSHOT-git-54d7089):
```
$ dotc Tag.scala
$ dotr Tag
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name&signature in class file Tag$
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Tag.main(HTML.scala)
```
Or compiled with SBT and then used in the repl (dottyVersion="0.3.0-bin-20170729-df4b3dd-NIGHTLY"  )
```scala
$ sbt console
[info] Loading global plugins from /home/glavo/.sbt/0.13/plugins
[info] Loading project definition from /home/glavo/IdeaProjects/Test/test/project
[info] Set current project to dotty-simple (in build file:/home/glavo/IdeaProjects/Test/test/)
[info] Compiling 1 Scala source to /home/glavo/IdeaProjects/Test/test/target/scala-0.3/classes...
Starting dotty interpreter...
Welcome to Scala.next (pre-alpha, git-hash: df4b3dd)  (OpenJDK 64-Bit Server VM, Java 1.8.0_131).
Type in expressions to have them evaluated.
Type :help for more information.
scala> import Tag._ 
import Tag._
scala> 'html {} 
java.lang.ClassFormatError: Duplicate method name&signature in class file 
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at dotty.tools.dotc.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:29)
	at java.lang.ClassLoader.loadClass(ClassLoa...

```

### PR DESCRIPTION
**Pull request by odersky**
Previously a method argument could be duplicated because it was passed
to the method as well as to its default argument methods. This was fatal
if the argument contained local definitions or was a closure.

We now unconditionally lift such arguments if the method has default
parameters.

### CODE REVIEW

**Comment by odersky** [comment]
Something fails with the CI.

**Comment by smarter** [comment]
I can reproduce the failure locally, the added run test compiles correctly but generates invalid bytecode which is detected at runtime:
```scala
> run tests/run/i2939.scala
[info] Running dotty.tools.dotc.Main -classpath /home/smarter/opt/dotty/library/target/scala-2.12/dotty-library_2.12-0.7.0-bin-SNAPSHOT-nonbootstrapped.jar tests/run/i2939.scala
[success] Total time: 4 s, completed 21 janv. 2018 18:57:56
> dotr Test
Exception in thread "main" java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Test$.x$1$1()I @0: aload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Test$' }
    stack: { }
  Bytecode:
    0x0000000: 2bbe ac                                

        at Test.main(i2939.scala)
```

**Comment by smarter** [comment]
Actually, compilation also fails with Ycheck:
```scala
> run -Ycheck:all tests/run/i2939.scala
exception while typing def x$2: Int = args.length of class class dotty.tools.dotc.ast.Trees$DefDef # 584
...
Exception in thread "main" java.lang.AssertionError: assertion failed: wrong type, expect a method type for Test$._$x$2, but found: Int
        at scala.Predef$.assert(Predef.scala:219)
        at dotty.tools.dotc.transform.TreeChecker$Checker.$anonfun$typedDefDef$2(TreeChecker.scala:405)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:180)
        at dotty.tools.dotc.transform.TreeChecker$Checker.$anonfun$typedDefDef$1(TreeChecker.scala:393)
        at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:180)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:392)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1708)
...
```

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -345,7 +346,7 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
        | Super(_, _)
        | Literal(_)
        | Closure(_, _, _) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: How come a Closure is considered a PurePath? It can contain local definitions.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: ah no it doesn't, nevermind.

File: compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala [hunk 2]
```diff
@@ -13,23 +13,44 @@ import Decorators._
...
+ *  default arguments, where we lift also complex pure expressions, since in that case
+ *  arguments can be duplicated as arguments to default argument methods.
+ */
+abstract class Lifter {
   import tpd._
 
+  /** Test indicating `expr` does not need lifting */
+  def noLift(expr: Tree)(implicit ctx: Context): Boolean
+
+  /** The corresponding lifter for paam-by-name arguments */
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala]: typo: paam -> param ?

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 3]
```diff
@@ -322,17 +322,18 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
...
       Impure
       // TODO: It seem like this should be exprPurity(tree)
       // But if we do that the repl/vars test break. Need to figure out why that's the case.
   }
 
   /** The purity level of this expression.
-   *  @return   pure        if expression has no side effects
-   *            idempotent  if running the expression a second time has no side effects
-   *            impure      otherwise
+   *  @return   PurePath    if expression has no side effects and cannot contain local definitions
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: Not sure if PurePath is the best name for this since not every PurePath expression is a valid path. Maybe NoDefPure? Or SimplePure/ComplexPure considering that later on we talk about "complex expressions" ?
