### PR TITLE
Fix #6734: Suppress interpolation for extension methods

### LINKED ISSUE #6734: Extension methods and tuples don't mash
## minimized code

```Scala
object Bug {

  def (ab: (A, B)) pipe2[A, B, Z](f: (A, B) => Z): Z = f(ab._1, ab._2)

  def (a: A) leftErr[A, B](b: B): A = (a, b).pipe2((a, b) => a) //Doesn't compile
  def (a: A) leftOk1[A, B](b: B): A = Tuple2(a, b).pipe2((a, b) => a) //Compiles
  def (a: A) leftOk2[A, B](b: B): A = {
    val t = (a, b)
    t.pipe2((a, b) => a) //Compiles
  }
}
```

Error:
```
[error] -- [E007] Type Mismatch Error: D:\DevProjects\Incubating\Squeal\squeal\src\main\scala\squeal\TupleBug.scala:7:50
[error] 7 |  def (a: A) leftErr[A, B](b: B): A = (a, b).pipe2((a, b) => a)
[error]   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |                                      Found:    Any
[error]   |                                      Required: A
```

## expectation
I would expect that all three would work. In most cases I can inline a val without any types without changing the behavior of the program.

### PR DESCRIPTION
**Pull request by odersky**
Suppress interpolation in the middle of an ExtMethodApply. The reason is that
the ExtMethodApply has a WildcardType, which hides information about bound type
variables in the result type.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2206,7 +2206,11 @@ class Typer extends Namer
 
   /** Interpolate and simplify the type of the given tree. */
   protected def simplify(tree: Tree, pt: Type, locked: TypeVars)(implicit ctx: Context): tree.type = {
-    if (!tree.denot.isOverloaded) // for overloaded trees: resolve overloading before simplifying
+    if (!tree.denot.isOverloaded &&
+          // for overloaded trees: resolve overloading before simplifying
+        !tree.isInstanceOf[Applications.IntegratedTypeArgs]
+          // don't interpolatie in the middle of an extension method application
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: typo:
```suggestion
          // don't interpolate in the middle of an extension method application
```
also the two ifs could be fused into one if.
