### PR TITLE
Fix #651 Generalize criterion for isOpAssign

### LINKED ISSUE #651: += is not a member of Set[String]
```
[info] # partest /Users/dark/workspace/dotty/tests/partest-generated/run/colltest1.scala
[info] % dotc colltest1.scala
[info]
[info] compiling /Users/dark/workspace/dotty/tests/partest-generated/run/colltest1.scala
[info] options: -pagewidth 160 -Yno-deep-subtypes -Yno-double-bindings -Ycheck:tailrec,resolveSuper,mixin,restoreScopes -d ./tests/partest-generated/run/colltest1-run.obj
[info] warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenSetFactory$$CC; assuming they are invariant
[info] warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$SetFactory$$CC; assuming they are invariant
[info] /Users/dark/workspace/dotty/tests/partest-generated/run/colltest1.scala:148: error: += is not a member of scala.collection.Set[String]
[info]     s += ("D", "E", "F")
```

### PR DESCRIPTION
**Pull request by odersky**
Methods like + can have multiple parameters. In that case
+= also takes multiple parameters.

Review by @DarkDimius

### CODE REVIEW

File: tests/run/colltest1.scala [hunk 1]
```diff
@@ -139,7 +139,8 @@ object Test extends dotty.runtime.LegacyApp {
 
   def setTest(empty: => Set[String]): Unit = {
     var s = empty + "A" + "B" + "C"
-    s += ("D", "E", "F")
```
Comment (DarkDimius) [inline tests/run/colltest1.scala]: Is this modification intentional? it makes thus test not cover `+=` operation

Comment (odersky) [inline tests/run/colltest1.scala]: No, that was an oversight.
