### PR TITLE
Make source a field in Positioned nodes

### LINKED ISSUE #9738: dotc: Error: requirement failed: array index too large, maximum is 2^30 - 1
Sometimes I'm getting this stacktrace while running heavy TASTY macros:

```
dotc: Error: requirement failed: array index too large, maximum is 2^30 - 1
java.lang.IllegalArgumentException: requirement failed: array index too large, maximum is 2^30 - 1
	at scala.Predef$.require(Predef.scala:340)
	at dotty.tools.dotc.util.SparseIntArray.update(SparseIntArray.scala:32)
	at dotty.tools.dotc.core.tasty.TreeBuffer.registerTreeAddr(TreeBuffer.scala:34)
	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:348)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle$$anonfun$1(TreePickler.scala:736)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:736)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$3$$anonfun$2(Pickler.scala:64)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:101)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:101)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:105)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
	at dotty.tools.dotc.Run.compileSources(Run.scala:142)
	at dotty.tools.dotc.Run.compile(Run.scala:124)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
	at dotty.tools.dotc.Driver.process(Driver.scala:195)
	at dotty.tools.dotc.Main.process(Main.scala)
	at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
	at xsbt.CompilerInterface.run(CompilerInterface.java:41)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:42)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:43)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:145)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:131)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:121)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:128)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:105)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:63)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

I cannot provide a minimized example - the issue manifests occasionally, so it's really hard to make a minimized example. 

It sometimes happens during [`izumi-reflect`](https://github.com/zio/izumi-reflect) build. It may be a recent regression, I didn't see it before 0.27

### PR DESCRIPTION
**Pull request by odersky**
The purpose of the PR is to revise the source pos scheme so that no global data structures are needed. There seems to be no way other than to simply add the source file as a field to each tree.

Fixes #9738

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
If we take take the average of the two benchmark runs we get a ~1% deterioration for 3 of the 4 compilation test and a ~1% improvement for the last (re2). So it looks like nothing much to worry about.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
Trees now have a source field instead of a uniqueId, so their size does not change. Unique ids can still be obtained via a weak hashmap if -Yshow-tree-ids or -Ydebug-tree-with-id is set. Since trees are no longer mappable to Ints, we cannot use SpareArrays pickling anymore. For now, we reverted back to an IdentityHashMap, which means all stored addresses are boxed. We could improve on this with a different custom data structure.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
Test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
That's the first instalment of the source position changes. We make source position a field and remove all usages of uniqueId except for debugging. This should fix #9738. 

There's scope for further changes. namely to pass sources when we also set the span of a tree. It turns out that's a lot trickier to do, so we will defer this to a separate PR.

File: compiler/src/dotty/tools/dotc/ast/Positioned.scala [hunk 1]
```diff
@@ -19,34 +19,37 @@ import java.io.{ PrintWriter }
 /** A base class for things that have positions (currently: modifiers and trees)
  */
 abstract class Positioned(implicit @constructorOnly src: SourceFile) extends SrcPos, Product, Cloneable {
+  import Positioned.{ids, nextId, debugId}
 
   private var myUniqueId: Int = _
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/Positioned.scala:24]:
```suggestion
```

File: compiler/src/dotty/tools/dotc/ast/Positioned.scala [hunk 2]
```diff
@@ -237,8 +240,14 @@ abstract class Positioned(implicit @constructorOnly src: SourceFile) extends Src
...
 object Positioned {
-  @sharable private[Positioned] var debugId = Int.MinValue
+  @sharable private var debugId = Int.MinValue
+  @sharable private var ids: java.util.WeakHashMap[Positioned, Int] = null
+  @sharable private var nextId: Int = 0
 
-  def updateDebugPos(using Context): Unit =
+  def init(using Context): Unit =
     debugId = ctx.settings.YdebugTreeWithId.value
+    if ctx.settings.YshowTreeIds.value
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/Positioned.scala:249]:
```suggestion
    if ids == null && ctx.settings.YshowTreeIds.value
```

File: compiler/src/dotty/tools/dotc/ast/Trees.scala [hunk 3]
```diff
@@ -221,7 +221,7 @@ object Trees {
       }
     }
 
-    override def hashCode(): Int = uniqueId // for debugging; was: System.identityHashCode(this)
+    override def hashCode(): Int = System.identityHashCode(this)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/Trees.scala:224]: I could not find which `hashCode` we are overriding. If it is indeed so we should just remove this override.

File: compiler/src/dotty/tools/dotc/util/IntMap.scala [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+ *                           Minimum value is 4.
+ *  @param  capacityMultiple The minimum multiple of capacity relative to used elements.
+ *                           The hash table will be re-sized once the number of elements
+ *                           multiplied by capacityMultiple exceeds the current size of the hash table.
+ *                           However, a table of size up to DenseLimit will be re-sized only
+ *                           once the number of elements reaches the table's size.
+ */
+final class IntMap[Key](initialCapacity: Int = 8, capacityMultiple: Int = 2)
+extends PerfectHashing[Key](initialCapacity, capacityMultiple):
+  private var values: Array[Int] = _
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/util/IntMap.scala:22]:
```suggestion
  private[this] var values: Array[Int] = _
```

**Review by nicolasstucki — CHANGES_REQUESTED** [review]
The new scheme is a clear improvement over the old one. Just forgot to remove some fields.

File: compiler/src/dotty/tools/dotc/util/IntMap.scala (hunk 4 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/util/IntMap.scala:22]: private[this] is no longer supported!

File: compiler/src/dotty/tools/dotc/ast/Trees.scala (hunk 3 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/Trees.scala:224]: We are overriding Object's hashcode, which is the same. But that way it is clear what we want. In fact, maybe we can emphasize this better by making `hasCode` and `equals` final.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Trees.scala:224]: Ok

File: compiler/src/dotty/tools/dotc/ast/Positioned.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/Positioned.scala:249]: No, I think we want to reset ids on each `init`. I am going to add an `else` clause that sets `ids = null`.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/Positioned.scala:249]: Or, do you think it is better to keep ids once it is set? That would allow us to track ids across multiple runs, which might be useful.

**Review by nicolasstucki — APPROVED** [review]
