### PR TITLE
Fix #7567: Variance checking fixes

### LINKED ISSUE #7567: Unsoundness due to missing variance checks of private members
## minimized code

```Scala
class A
class B extends A
class C extends A

object Foo {
  private[this] class Bar[+T](var x: T)
  def foo: B = {
    val barB: Bar[B] = new Bar(new B)
    val barA: Bar[A] = barB
    barA.x = new C
    barB.x
  }
}

Foo.foo
```

## result

`java.lang.ClassCastException`

## expectation

Variance error is reported.

## variations

  * `private` is also broken in Dotty
  * `private[this]` is also broken in Scalac
  * `private` is detected in Scalac

### PR DESCRIPTION
**Pull request by odersky**
Do check private[this] members for variances but cut relative variance
computations at private[this] members.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala [hunk 1]
```diff
@@ -83,24 +83,21 @@ class VarianceChecker()(implicit ctx: Context) {
...
-      if (base == tvar.owner) v
-      else if (base.is(Param) && base.owner.isTerm)
+      if base == tvar.owner then
+        v
+      else if base.is(Param) && base.owner.isTerm && !base.owner.isAllOf(PrivateLocal) then
         relativeVariance(tvar, paramOuter(base.owner), flip(v))
-      else if (ignoreVarianceIn(base.owner)) Bivariant
-      else if (base.isAliasType) relativeVariance(tvar, base.owner, Invariant)
-      else relativeVariance(tvar, base.owner, v)
+      else if base.owner.isTerm || base.owner.is(Package) || base.isAllOf(PrivateLocal) then
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala]: by inlining `ignoreVarianceIn`, was it intentional to do `base.isAllOf(PrivateLocal)` and not `base.owner.isAllOf(PrivateLocal)`?

File: compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala [hunk 2]
```diff
@@ -189,11 +186,10 @@ class VarianceChecker()(implicit ctx: Context) {
     override def traverse(tree: Tree)(implicit ctx: Context) = {
       def sym = tree.symbol
       // No variance check for private/protected[this] methods/values.
-      def skip =
-        !sym.exists ||
-        sym.isAllOf(PrivateLocal) ||
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala]: I found that this change to `skip` alone is sufficient to pass `tests/neg/i7567.scala` - the other changes are not exercised in a test

File: compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala]: Yes, the previous implementation was in fact wrong.

File: compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala]: They are: neg/variances.scala will give a different number of errors.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala]: Ah yes I see, my mistake
