### PR TITLE
Fix Crashes when Capture-set Parameters Conflict with Terms

### LINKED ISSUE #25025: CC: Crash when a Method's Capture Variable and Parameter are Identically Named
## Compiler version

Current nightly `3.8.2-RC1-bin-20260120-e277a73-NIGHTLY-git-e277a73`

## Minimized code

Try one of these

```Scala
def foo[c^](c: AnyRef^): AnyRef^{c} = c
def foo[c^](c: AnyRef^): Int = 0
```

## Output (click arrow to expand)

We get

```
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
```

Judging by the stack trace, it tries to construct an error message 
(so it is correctly identified as an error, good!) but crashes
while doing that:

<details>

```scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2672)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.effectiveOwner(SymDenotations.scala:1190)
	at dotty.tools.dotc.reporting.AlreadyDefined.where$1(messages.scala:2125)
	at dotty.tools.dotc.reporting.AlreadyDefined.msg(messages.scala:2153)
	at dotty.tools.dotc.reporting.Message.message$$anonfun$1(Message.scala:426)
	at dotty.tools.dotc.reporting.Message.inMessageContext(Message.scala:422)
	at dotty.tools.dotc.reporting.Message.message(Message.scala:426)
	at dotty.tools.dotc.reporting.MessageRendering.messageAndPos(MessageRendering.scala:301)
	at dotty.tools.dotc.reporting.MessageRendering.messageAndPos$(MessageRendering.scala:21)
	at dotty.tools.dotc.reporting.AbstractReporter.messageAndPos(AbstractReporter.scala:8)
	at dotty.tools.dotc.reporting.ConsoleReporter$AbstractConsoleReporter.doReport(ConsoleReporter.scala:43)
	at dotty.tools.repl.ReplDriver.printDiagnostic(ReplDriver.scala:700)
	at dotty.tools.repl.ReplDriver.displayErrors$$anonfun$1(ReplDriver.scala:684)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:327)
	at dotty.tools.repl.ReplDriver.displayErrors(ReplDriver.scala:684)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$1(ReplDriver.scala:383)
	at scala.util.Either.fold(Either.scala:200)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:384)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:343)
	at dotty.tools.repl.ReplDriver.$anonfun$4(ReplDriver.scala:252)
	at dotty.tools.repl.JLineTerminal.withMonitoringCtrlC(JLineTerminal.scala:125)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:253)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:259)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:293)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:267)
	at dotty.tools.repl.ScalaClassLoader$.asContext(ScalaClassLoader.scala:32)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:267)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:259)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:166)
	at dotty.tools.repl.Main$.main(Main.scala:8)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

### PR DESCRIPTION
**Pull request by bracevac**
Fixes #25025

This PR fixes compiler crashes and adds proper error reporting when capture-set parameters (`[c^]`) conflict with term definitions of the same name.

### Fixes
- **Namer.scala**: Fixed `NoDenotation.owner` crash when `companionClass` returns `NoSymbol`
- **Typer.scala**: Fixed `ClassCastException` in `typedSingletonTypeTree` when widened type isn't a `TypeRef`
- **NamerOps.scala**: Added conflict detection for `def foo(c: AnyRef^)[c^]` pattern (term param before capture param)

### Improvements
- Enhanced `AlreadyDefined` message class to handle capture-set conflicts with proper error code (E161) and explanation

### CODE REVIEW

**Comment by bracevac** [comment]
Perhaps we should also rule out nonsense like `def foo[c^](x: c) = ...`, but that's going to be more involved.

File: compiler/src/dotty/tools/dotc/core/NamerOps.scala [hunk 1]
```diff
@@ -358,10 +360,14 @@ object NamerOps:
    */
   def addDummyTermCaptureParam(param: Symbol)(using Context): Unit =
     val name = param.name.toTermName
-    val flags = (param.flagsUNSAFE & AccessFlags).toTermFlags | CaptureParam
-    val dummy = newSymbol(param.owner, name, flags, param.typeRef)
-    typr.println(i"Adding dummy term symbol $dummy for $param, flags = $flags")
-    ctx.enter(dummy)
+    val preExisting = ctx.effectiveScope.lookup(name)
+    if Feature.ccEnabled && preExisting.exists then
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/NamerOps.scala]: Drop `Feature.ccEnabled` since it should be redundant?

**Review by odersky — APPROVED** [review]
