### PR TITLE
Propagate dependencies through implicit parameters

### LINKED ISSUE #5427: implicit search fails with intra-parameter-list dependency
Adapted from https://contributors.scala-lang.org/t/better-type-inference-for-scala-send-us-your-problematic-cases/2410/53?u=smarter:
```scala
trait Foo[In] { type Out }

object Test {
  implicit def fooInt: Foo[Int] { type Out = String } = ???
  implicit def str: String = ???

  def test1[A](f1: Foo[A])(implicit f2: f1.Out) = ???
  def test2[A](implicit f1: Foo[A], f2: f1.Out) = ???

  test1(fooInt) // OK
  test2 // error: no implicit argument of type f1.Out was found for parameter f2 of method test2
}
```

### PR DESCRIPTION
**Pull request by milessabin**
Fixes #5427.

If an implicit parameter list is dependent, we must propagate inferred types through the remainder of the parameter list, similarly to how it's done for non-implicit parameter lists in `Applications#matchArgs#addTyped`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2361,10 +2361,17 @@ class Typer extends Namer
...
               case _ =>
-                arg :: implicitArgs(formals1)
+                // If the implicit parameter list is dependent we must propagate inferred
+                // types through the remainder of the parameter list similarly to how it's
+                // done for non-implicit parameter lists in Applications#matchArgs#addTyped.
+                val formals2 =
+                  if (wtp.isParamDependent && arg.tpe.exists)
+                    formals1 mapconserve {f1 => safeSubstParam(f1, wtp.paramRefs(n), arg.tpe)}
+                  else formals1
+                arg :: implicitArgs(formals2, n+1)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
                arg :: implicitArgs(formals2, n + 1)
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -2348,7 +2348,7 @@ class Typer extends Namer
       def dummyArg(tp: Type) = untpd.Ident(nme.???).withTypeUnchecked(tp)
 
       def addImplicitArgs(implicit ctx: Context) = {
-        def implicitArgs(formals: List[Type]): List[Tree] = formals match {
+        def implicitArgs(formals: List[Type], n: Int): List[Tree] = formals match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: either give a more explicit name for this parameter or add some documentation for this method (something that would be nice to have anyway :))

Comment (milessabin) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Renamed to `argIndex`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (milessabin) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Done.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -2361,10 +2361,17 @@ class Typer extends Namer
                 // If there are none, we have to propagate the ambiguity to the caller.
                 arg :: formals1.map(dummyArg)
               case _ =>
-                arg :: implicitArgs(formals1)
+                // If the implicit parameter list is dependent we must propagate inferred
+                // types through the remainder of the parameter list similarly to how it's
+                // done for non-implicit parameter lists in Applications#matchArgs#addTyped.
+                val formals2 =
+                  if (wtp.isParamDependent && arg.tpe.exists)
+                    formals1 mapconserve {f1 => safeSubstParam(f1, wtp.paramRefs(n), arg.tpe)}
```
[the remark this answers is not in the document]
Comment (milessabin) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Done.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 4]
```diff
@@ -2361,10 +2361,17 @@ class Typer extends Namer
                 // If there are none, we have to propagate the ambiguity to the caller.
                 arg :: formals1.map(dummyArg)
               case _ =>
-                arg :: implicitArgs(formals1)
+                // If the implicit parameter list is dependent we must propagate inferred
+                // types through the remainder of the parameter list similarly to how it's
+                // done for non-implicit parameter lists in Applications#matchArgs#addTyped.
+                val formals2 =
+                  if (wtp.isParamDependent && arg.tpe.exists)
```
[the remark this answers is not in the document]
Comment (milessabin) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: We do need `exists` here. Switching to `!arg.tpe.isError` results in an assertion for a non-existent getter denotation.

I'll add some negative test cases.

**Comment by milessabin** [comment]
@smarter incorporated your feedback.

**Comment by allanrenucci** [comment]
We prefix Dotty issues with `i` (e.g. `i5427.scala)`. Issues that start with `t` come from `scalac`

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I suggest pressing "Resolve conversation" below instead of saying "Done.", it reduces the number of emails we get :).

**Comment by smarter** [comment]
@milessabin Now that github shows diffs when push-forcing commits, I prefer when commits are amended and push-forced to address the feedback of reviewers instead of making new commits just for that (it keeps the history cleaner)

**Comment by milessabin** [comment]
Okey doke. I'll reprefix the tests to `i`, squash and force-push.

**Comment by milessabin** [comment]
@smarter do you want to do the honours?
