### PR TITLE
Keep correct kind when preparing constraint in stripParams

### LINKED ISSUE #14760: Unexpected error message when typing wildcard parameters in pattern
## Compiler version

`3.1.2-RC2`

## Minimized code

```Scala
enum SUB[-A, +B]:
  case Refl[X]() extends SUB[X, X]

def foo[C, A >: C <: C, B](e: SUB[B, A]) = e match
  case SUB.Refl() =>
```

It seems that in the code snippet above, the compiler wrongly assumes that the wildcard argument `X$1` (which is the type parameter of class Refl) is a higher-kinded type. And it complains that there is no type parameters supplied to `X$1`. However, it is simple-kinded.

I found that the bound `A >: C <: C` is necessary to trigger the error. And we have to match `SUB[B, A]` instead of `SUB[A, B]`. Not sure how these conditions are related to this issue.

## Output

```scala
[info] running (fork) dotty.tools.dotc.Main -classpath /Users/linyxus/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar:/Users/linyxus/Workspace/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.1.3-RC1-bin-SNAPSHOT.jar -color:never issues/simple-kind-error.scala
-- [E141] Type Error: issues/simple-kind-error.scala:5:15 -----------------------------------------------------------------------------------------------------------------------------------------------------------
5 |  case SUB.Refl() =>
  |               ^
  |               Missing type parameters for X$1
  |
  | longer explanation available when compiling with `-explain`
1 error found
[error] Nonzero exit code returned from runner: 1
[error] (scala3-compiler / Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 3 s, completed Mar 23, 2022, 7:59:28 PM
```

## Expectation

The code should compile.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #14760

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala [hunk 1]
```diff
@@ -248,7 +248,7 @@ class OrderingConstraint(private val boundsMap: ParamBounds,
       NoType
     case tp: TypeBounds =>
       val lo1 = stripParams(tp.lo, todos, !isUpper).orElse(defn.NothingType)
-      val hi1 = stripParams(tp.hi, todos, isUpper).orElse(defn.AnyKindType)
+      val hi1 = stripParams(tp.hi, todos, isUpper).orElse(tp.kind)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala:251]: You should be able to use [`TypeApplications#topType`](https://github.com/lampepfl/dotty/blob/fa3893e96ea8e1d3beaedcc17bec67ce74ca799f/compiler/src/dotty/tools/dotc/core/TypeApplications.scala#L232-L240) instead which I needed for the same reason :).
```suggestion
      val hi1 = stripParams(tp.hi, todos, isUpper).orElse(tp.topType)
```

**Review by smarter — CHANGES_REQUESTED** [review]

**Review by Linyxus — APPROVED** [review]
Thanks for checking the issue. LGTM!
