### PR TITLE
Fix wunused false positive on CanEqual

### LINKED ISSUE #17762: spurious unused warning of local given for CanEqual with -Wunused:locals and -language:strictEquality
3.3 is awesome, thank you for bringing warnings back and all your hard work! :heart:
There seems to be a small interaction problem with what is regarded unused and `-language:strictEquality` though:

## Compiler version

3.3.0

## Minimized code

CompilerOptions:
* -language:strictEquality
* -Wunused:locals

```Scala
class SomeType

def testIt(st1: SomeType, st2: SomeType): Boolean =
  given CanEqual[SomeType, SomeType] = CanEqual.derived
  st1 == st2
```

## Output

A warning that the `given` definition is unused - or a compiler error that `SomeType` can not be compare with itself when removed

## Expectation

It should not warn since the `given CanEqual[...]` is required  by the compiler under `-language:strictEquality`

## Scastie
https://scastie.scala-lang.org/i6Osmdc1SSK9FQlN3a65dA

### PR DESCRIPTION
**Pull request by szymon-rd**
Fixes #17762

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 1]
```diff
@@ -643,9 +643,21 @@ object CheckUnused:
...
         imp.expr.tpe.member(sel.name.toTypeName).alternatives.exists(_.symbol.isOneOf(GivenOrImplicit))
-      )
-
+      ) 
+    
+    /**
+     * Ignore CanEqual imports
+     */
+    private def isImportIgnored(imp: tpd.Import, sel: ImportSelector)(using Context): Boolean =
+      (sel.isWildcard && imp.expr.tpe.allMembers.exists(p => p.symbol.typeRef.baseClasses.exists(_.derivesFrom(defn.CanEqualClass)))) ||
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:652]: I think this is problematic because perhaps it only imports CanEqual's that are not even used. Perhaps it makes more sense to record the can equal usages in the typer?

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:652]: Also this should check if its also a "given" import, rather than "*"

Comment (szymon-rd) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:652]: Unfortunately, after a lengthy discussion with Martin and the team and making some PoCs, we decided that extracting that information from Typer is unfeasible without making the Typer and Implicit resolution slower / more complex. So we want to emulate it or fix false positives. But I will address the second commend 👍

Comment (szymon-rd) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala]: Yes, and this logic could get even more complex I suppose given that it is a type param, and the resolution is pre typer vs the emulation would be post typer. Not a good idea

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala]: Im not sure how it works, but might it produce more accurate warnings if you only ignore warnings generated by the import selector when the specific unused symbol derives from CanEqual?

Comment (szymon-rd) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala]: It's pretty much what we are doing here
