### PR TITLE
Check protected parent constructor accesses only occurs in child constructors

### LINKED ISSUE #25442: Compiler incorrectly permits access to protected constructor
On 3.8.2:

```scala
class I protected (x: Int) {
  protected def f = x
}

class M protected () extends I(42) {
  def t1(m: M) = m.f // ok
  def t2(i: I) = i.f // error (spec 5.2.2): the type of `i` does not conform to
                     // "a type-instance of the class which contains the access"

  def t3 = new M()   // ok
  def t4 = new I(42) // allowed, but should be rejected (Scala 2 rejects it)
}
```

### PR DESCRIPTION
**Pull request by jmesyou**
Fixes #25442.

Currently, protected parent class constructor calls that occur outside of their subclass constructors are not properly checked. So it possible to call a parent constructor in any method of subclass. This change checks that such accesses only occur inside subclass constructors. 

No LLM-based tools were used.

negative test case from issue included.

### CODE REVIEW

**Review by bracevac — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -946,10 +946,12 @@ object SymDenotations {
         val cls = owner.enclosingSubClass
         if !cls.exists then
           pre.termSymbol.isPackageObject && accessWithin(pre.termSymbol.owner)
-        else
+        else {
+          val isConstructorAccessOK = isConstructor && ctx.owner.isConstructor
```
Comment (lrytz) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:950]: The following should also be rejected; is it?

```scala
class I protected (x: Int) {
  protected def f = x
}

class M protected () extends I(42) {
  def this(x: Int) = { this(); new I(x) } // error
}
```

Comment (bracevac) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala:950]: Right. It should've been `ctx.owner.isPrimaryConstructor` then.

Comment (bracevac) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala:950]: @jmesyou would you like to take a look?

Comment (bracevac) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala:950]: Playing with this some more, I think even checking for `isPrimaryConstructor` is not granular enough:
```scala
class A protected (x: Int)
class B protected (a: A) extends A(a.hashCode)
class C extends B(new A(1)) // should be error, but ok currently
```
