### PR TITLE
Drop all usage of `sbt-dotty` in community build

### LINKED ISSUE #14391: Lots of Builds in the community-build are silently skipping tests and even test-compiles
It looks like lots of Builds not running or even compiling their tests. When they get to testing this happens:
```
2022-01-30T08:16:22.4896099Z [error] Error loading test framework (java.lang.NoClassDefFoundError: sbt/testing/Framework). This usually means that you are using a layered class loader that cannot reach the sbt.testing.Framework class. The most likely cause is that your project has a runtime dependency on your test framework, e.g. scalatest. To fix this, you can try to set
2022-01-30T08:16:22.4899342Z [error] Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.ScalaLibrary
2022-01-30T08:16:22.4900029Z [error] or
2022-01-30T08:16:22.4900718Z [error] Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
2022-01-30T08:16:22.5477827Z [success] Total time: 23 s, completed Jan 30, 2022 9:16:22 AM
```
As similar issues happens for some builds trying to use ZTestFramework:
```
2022-01-30T08:21:26.8954542Z [error] Error loading test framework (scala.MatchError: zio.test.sbt.ZTestFramework@31fd0360 (of class zio.test.sbt.ZTestFramework)). This usually means that you are using a layered class loader that cannot reach the sbt.testing.Framework class. The most likely cause is that your project has a runtime dependency on your test framework, e.g. scalatest. To fix this, you can try to set
```

When this error occurs in a project, none of the tests will be run or even compiled. It is effectively a total disabling of testing code for the given project.

I first saw these in the my quill PR builds:
Screenshot from 2022-01-31 11-48-26

Some quick grepping (attached) shows me this is happening for the following projects:

#### in community-build-a
- scalatest
- scala-stm
- scalatestplus-testng
- izumi-reflect
- Lucre

#### in community-build-c
- protoquill (I got this one...)
- akka
- jackson-module-scala
- libretto
- xml-interpolator
- scalatestplus-scalacheck
- scala-parallel-collections
- sconfig
- onnx-scala 

I solved this problem by adding something slightly different to my settings:
```
Compile / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
```
When I added this, the error went away.

This could all be totally wrong and my grepping could be incorrect too but I've tried this with the quill build. I tried running the community build with and actual compile error in my scalatests and without the classLoaderLayeringStrategy parameter. The build passes as though nothing is wrong.

I think that project owners should maybe have a look at their builds and see if this is happening for them.

[grepping_results.txt](https://github.com/lampepfl/dotty/files/7972659/grepping_results.txt)

### PR DESCRIPTION
**Pull request by griggt**
The `sbt-dotty` plugin was deprecated with the release of sbt 1.5.0, and removed from the dotty build in https://github.com/lampepfl/dotty/commit/b477c42b1c32cf0c28f8e73f85b8a8413669d0bd

However it was still being injected into the community build, as many projects therein had not been updated to a recent sbt, or were using a (possibly outdated) version of `sbt-dotty` either directly or indirectly via some other plugin.

This commit discontinues that practice, since sbt 1.6.x no longer plays nice with `sbt-dotty` (see the linked ticket https://github.com/lampepfl/dotty/issues/14391).

Many of the community build projects are already updated upstream to use sbt 1.5.x or 1.6.x without `sbt-dotty`; those are updated to their upstream versions in this PR as appropriate.

A handful of community build projects are either unmaintained or do not offer Scala 3 support upstream, or their inclusion in the community build was part of some special effort. Those projects, listed below, have had their `dotty-staging` forks updated to use sbt 1.6.2 and drop `sbt-dotty`.

  - betterfiles
  - effpi
  - fastparse
  - intent
  - scalap

This PR also:
  - upgrades to sbt 1.6.2
  - adds some debugging output on dependency overrides to the community build workflows
  - fixes the exclusion of flaky scalatest tests
  - drops `algebra` as a separate project since it is now incorporated into `cats`

[test_forward_compat]

Fixes #14391

### CODE REVIEW

File: community-build/src/scala/dotty/communitybuild/projects.scala [hunk 1]
```diff
@@ -750,8 +748,8 @@ object projects:
 
   lazy val fs2 = SbtCommunityProject(
     project = "fs2",
-    sbtTestCommand = "coreJVM/test; coreJS/test",  // io/test requires JDK9+
-    sbtPublishCommand = "coreJVM/publishLocal; coreJS/publishLocal",
+    sbtTestCommand = """set coreJVM/scalacOptions -= "-Xfatal-warnings"; coreJVM/test; set coreJS/scalacOptions -= "-Xfatal-warnings"; coreJS/test""",  // io/test requires JDK9+
+    sbtPublishCommand = """set coreJVM/scalacOptions -= "-Xfatal-warnings"; coreJVM/publishLocal; set coreJS/scalacOptions -= "-Xfatal-warnings"; coreJS/publishLocal""",
```
Comment (armanbilge) [inline community-build/src/scala/dotty/communitybuild/projects.scala:752]: If you wish :)

```suggestion
    sbtTestCommand = "set ThisBuild/tlFatalWarnings := false; coreJVM/test; coreJS/test",  // io/test requires JDK9+
    sbtPublishCommand = "set ThisBuild/tlFatalWarnings := false; coreJVM/publishLocal; coreJS/publishLocal",
```

**Comment by griggt** [comment]
Two of the Cats Effect tests picked up by the resync with upstream are failing since #14295 

```
[info] ThunkSpec
[info] Thunk.asFunction0 should
[error]   x return the same function
[error]    false (file:1)
```

```
[info] TracingSpec
[info] IO.delay should
[error]   x generate identical traces
[error]    false (file:1)
[info]   + generate unique traces
[info] Async.delay should
[error]   x generate identical traces
[error]    false (file:1)
[info]   + generate unique traces
```

They have been disabled for now in https://github.com/dotty-staging/cats-effect/commit/2510979ee03d10e60011812698567885547d85d7

fyi @armanbilge

**Comment by djspiewak** [comment]
@griggt fwiw, I think those tests are picking up an actual regression in the compiler. More discussion on the linked Cats Effect issue, but it appears at least in preliminary analysis that the compiler now generates additional redundant wrapping functions around thunks. CE is sensitive to this because of how it detects call sites for tracing purposes, which is why it fails functional tests, but it should also show up in microbenchmarks and other performance metrics.

File: community-build/src/scala/dotty/communitybuild/projects.scala (hunk 1 above)
Comment (griggt) [reply community-build/src/scala/dotty/communitybuild/projects.scala]: #14407 has now been fixed so we can re-enable fatal-warnings :)

**Comment by griggt** [comment]
@djspiewak @armanbilge I see there has been additional discussion re: thunks on the linked ticket and Discord.  If ultimately you feel there is a compiler regression that needs attention, please do open an issue. Thanks.

**Comment by armanbilge** [comment]
@griggt I just tried the latest nightly that includes the changes in https://github.com/lampepfl/dotty/pull/14628. You should be able to re-enable the `ThunkSpec` and the `TracingSpec` for Cats Effect in the community build.

Thanks again for your help with this one! :)

**Comment by SethTisue** [comment]
Great to see this landing! Thanks Tom & everyone who helped 👏
