### PR TITLE
Fix typeMember/typeMembers documentation

### LINKED ISSUE #14901: Documentation for some methods in Quotes seems to be wrong
## Compiler version

git hash: 2ec9c52

## Minimized code

```
/** Get non-private named methods defined directly inside the class */
def declaredType(name: String): List[Symbol]

/** Get all non-private methods defined directly inside the class, excluding constructors */
def declaredTypes: List[Symbol]
```

## Expectation

It seems that these methods return symbols representing **types** instead of **methods**

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #14901

### CODE REVIEW

File: library/src/scala/quoted/Quotes.scala [hunk 1]
```diff
@@ -3878,10 +3878,10 @@ trait Quotes { self: runtime.QuoteUnpickler & runtime.QuoteMatching =>
         /** Get all non-private methods declared or inherited */
         def methodMembers: List[Symbol]
 
-        /** Get non-private named methods defined directly inside the class */
+        /** Get non-private named type defined directly inside the class */
         def declaredType(name: String): List[Symbol]
 
-        /** Get all non-private methods defined directly inside the class, excluding constructors */
+        /** Get all non-private type defined directly inside the class, excluding constructors */
```
Comment (pikinier20) [inline library/src/scala/quoted/Quotes.scala:3884]:
```suggestion
        /** Get all non-private types defined directly inside the class */
```
