### PR TITLE
Fix #1891: Don't add redundant constraint

### LINKED ISSUE #1891: StackOverflow in TypeAssigner with @inline & type alias
```scala
object Test {
  case class CC2[A, B](a: A, b: B)

  type T2[A, B] = CC2[A, B]

  class ArrowAssoc[A](val self: A) {
    @inline def f[B](y: B): CC2[A, B] = CC2(self, y)
  }

  def foo = (new ArrowAssoc(1)).f(2)
}
```

```scala
Exception in thread "main" java.lang.StackOverflowError
        at dotty.tools.dotc.ast.tpd$.localSyms(tpd.scala:20)
        at dotty.tools.dotc.typer.TypeAssigner$$anonfun$avoidingType$1.apply(TypeAssigner.scala:133)
        at dotty.tools.dotc.typer.TypeAssigner$$anonfun$avoidingType$1.apply(TypeAssigner.scala:133)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.forbidden$lzycompute(TypeAssigner.scala:54)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.forbidden(TypeAssigner.scala:54)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2$$anonfun$toAvoid$1.apply(TypeAssigner.scala:59)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2$$anonfun$toAvoid$1.apply(TypeAssigner.scala:58)
        at dotty.tools.dotc.core.Types$ExistsAccumulator.apply(Types.scala:3735)
        at dotty.tools.dotc.core.Types$Type.existsPart(Types.scala:236)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.toAvoid(TypeAssigner.scala:58)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.apply(TypeAssigner.scala:69)
        at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:3479)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.apply(TypeAssigner.scala:126)
        at dotty.tools.dotc.typer.TypeAssigner$class.avoid(TypeAssigner.scala:129)
        at dotty.tools.dotc.typer.Typer.avoid(Typer.scala:64)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.apply(TypeAssigner.scala:123)
        at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:3479)
        at dotty.tools.dotc.typer.TypeAssigner$$anon$2.apply(TypeAssigner.scala:126)
        ...
```

### PR DESCRIPTION
**Pull request by odersky**
Before adding a constraint, make sure there is no way
the two types are already in a subtype relation.

Adding redundant constraints is problematic because we
might introduce cycles. See i1891.scala for a test.

Fixes #1891. Review by @OlivierBlanvillain or/and @smarter?

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -375,11 +375,19 @@ class TypeComparer(initctx: Context) extends DotClass with ConstraintHandling {
...
     case tp2: PolyParam =>
       def comparePolyParam =
-        (ctx.mode is Mode.TypevarsMissContext) ||
-        isSubTypeWhenFrozen(tp1, bounds(tp2).lo) || {
+        (ctx.mode is Mode.TypevarsMissContext) || {
+        val alwaysTrue =
+          // The following condition is carefully formulated to catch all cases
+          // where the subtype relation is true without needing to add a constraint
+          // It's tricky because we might need to either appriximate tp2 by its
+          // lower bound or else widen tp1 and check that the result is a subtype of tp2.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I don't see a widening of `tp1` in the code below?

Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: The widening is done by all the other parts of subtyping. The important part is not to narrow the lower bound of tp2 before we had a chance to widen tp1.

**Comment by smarter** [comment]
LGTM, though this is still a bit mysterious to me ;)
