### PR TITLE
Fix #6419: Support @compileTimeOnly

### LINKED ISSUE #6419: Do not deprecate @compileTimeOnly
What's the rationale for deprecating `@compileTimeOnly` in https://github.com/lampepfl/dotty/pull/6416?

First, doing that would introduce unnecessary migration pain, for little gain (I assume it's quite straightforward to support in the compiler). Second, the proposed alternative doesn't cover all use cases of `@compileTimeOnly` well. For example, can you encode the following with just `inline` and `error`?

```scala
scala> trait A { @scala.annotation.compileTimeOnly("oops") def f: Int }
defined trait A

scala> class B extends A { def f = 0 }
defined class B

scala> (new B).f
res0: Int = 0

scala> (new B : A).f
<console>:14: error: oops
       (new B : A).f
                   ^
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Support @compileTimeOnly and remove migration waining (see https://github.com/lampepfl/dotty/issues/6419#issuecomment-489008330).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala [hunk 1]
```diff
@@ -326,8 +326,23 @@ object Erasure {
...
+              ctx.warning("Reference to member with @compileTimeOnly", tree.sourcePos)
+            } else {
+              annot.tree match {
+                case Apply(_, Literal(msg) :: Nil) => ctx.error(msg.stringValue, tree.sourcePos)
+                case _ => ctx.error("Reference to member with @compileTimeOnly", tree.sourcePos)
+              }
+            }
+          case _ => // OK
+        }
+      }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/Erasure.scala]: In `RefChecks.scala`, there is commented code:

```Scala
    /*  (Not enabled yet)
       *  See an explanation of compileTimeOnly in its scaladoc at scala.annotation.compileTimeOnly.
       *
      if (sym.isCompileTimeOnly) {
        def defaultMsg =
          sm"""Reference to ${sym.fullLocationString} should not have survived past type checking,
              |it should have been processed and eliminated during expansion of an enclosing macro."""
        // The getOrElse part should never happen, it's just here as a backstop.
        ctx.error(sym.compileTimeOnlyMessage getOrElse defaultMsg, pos)
      }*/
```

Maybe we should just revive the code?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Erasure.scala]: No, it would not take into account if it is into an erased context or not. Which is already performed in the place where I check it.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Erasure.scala]: As in https://github.com/lampepfl/dotty/pull/6424/files#diff-a12cb93e6ac05566103dd86ede6e5901R12, where the reference of the `@compileTimeOnly` is inside an `erased def`

**Comment by nicolasstucki** [comment]
Dropped scalatest changes and rebased
