### PR TITLE
Record ordering constraint between HK type variables

### LINKED ISSUE #9676: Regression: type inference involving higher-kinded types and upper-bounds
## Minimized code

```Scala
// compiles fine
object Main extends App {
  trait SubtypeOf[A[_], B[_]]
  implicit def instance[F[_], G[a] >: F[a]]: SubtypeOf[F, G] = new SubtypeOf[F, G] {}

  implicitly[SubtypeOf[List, Seq]]
}

// won't compile on dotty, but compiles fine on scala 2.13.3
object Main2 extends App {
  trait SubtypeOf[A[_], B[_]]
  implicit def instance[G[_], F[a] <: G[a]]: SubtypeOf[F, G] = new SubtypeOf[F, G] {}

  implicitly[SubtypeOf[List, Seq]]
}
```

## Output

```scala
no implicit argument of type Main.SubtypeOf[List, Seq] was found for parameter ev of method implicitly in object DottyPredef.
I found:

    Main.instance[Nothing, Nothing]

But method instance in object Main does not match type Main.SubtypeOf[List, Seq].
```

## Expectation
Implicit resolution works in both cases.

### PR DESCRIPTION
**Pull request by smarter**
If `?F <: [X] => ?G[X]`, then the ordering part of the constraint should
record `?F <: ?G`, otherwise constraints won't be propagated correctly.

It's not clear to me if we should make a similar change in `stripParams`
but note that doing so would require being a bit careful: since we use
the upper bound of a type variable to determine its kind, we can't just
replace it by `[X] => ?G[X]` by `AnyKind`.

Fixes #9676.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -605,7 +605,7 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
             if (tparams1.nonEmpty)
               return recur(tp1.EtaExpand(tparams1), tp2) || fourthTry
             tp2 match {
-              case EtaExpansion(tycon2) if tycon2.symbol.isClass && tycon2.symbol.is(JavaDefined) =>
+              case EtaExpansion(tycon2: TypeRef) if tycon2.typeSymbol.isClass && tycon2.symbol.is(JavaDefined) =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:608]: typeSymbol = symbol on a TypeRef, so you can use just symbol.
```suggestion
              case EtaExpansion(tycon2: TypeRef) if tycon2.symbol.isClass && tycon2.symbol.is(JavaDefined) =>
```

**Review by odersky — APPROVED** [review]

**Comment by smarter** [comment]
(Merging, community build failure is due to flaky test and is being taken care of elsewhere: https://github.com/lampepfl/dotty/pull/9784)
