### PR TITLE
Fix #6570: Don't reduce match types with empty scrutinies

### LINKED ISSUE #6570: Match types' type binds are unsound
It is possible to exploit the way match types bind type variable to make match types "forget" they are dealing with an abstract type. I have multiple examples, but possibly the one easiest to understand is:

```scala
object Base {
  trait Trait1
  trait Trait2
  type N[t] = t match {
    case String => Trait1
    case Int => Trait2
  }
}
import Base._

object UpperBoundParametricVariant {
  trait Cov[+T]
  type M[t] = t match { 
    case Cov[t] => N[t]
  }
  
  trait Root[A] {
    def thing: M[A]
  }

  trait Child[A <: Cov[Int]] extends Root[A]

  // we reduce `M[T]` to `Trait2`, even though we cannot be certain of that
  def foo[T <: Cov[Int]](c: Child[T]): Trait2 = c.thing

  class Asploder extends Child[Cov[String & Int]] {
    def thing = new Trait1 {}
  }

  def explode = foo(new Asploder) // ClassCastException
}
```

Essentially, what seems to happen is that when reducing `M`, we pick the `Cov[t]` case, bind `t` to a non-abstract type and happily proceed with the reduction. It's illustrating to consider that `foo` would not compile if we defined `M` like:
```scala
  type M[t] = t match {
    case Cov[String] => Trait1
    case Cov[Int] => Trait2
}
```

The other "exploits"
<details><summary>
are here
</summary><p>

```scala
object InheritanceVariant {
  // allows binding a variable to the UB of a type member
  type Trick[a] = { type A <: a }
  type M[t] = t match { case Trick[a] => N[a] }

  trait Root {
    type B
    def thing: M[B]
  }

  trait Child extends Root { type B <: { type A <: Int } }

  def foo(c: Child): Trait2 = c.thing

  class Asploder extends Child {
    type B = { type A = String & Int }
    def thing = new Trait1 {}
  }
}

object ThisTypeVariant {
  type Trick[a] = { type A <: a }
  type M[t] = t match { case Trick[a] => N[a] }

  trait Root {
    def thing: M[this.type]
  }

  trait Child extends Root { type A <: Int }

  def foo(c: Child): Trait2 = c.thing

  class Asploder extends Child {
    type A = String & Int
    def thing = new Trait1 {}
  }
}

object ParametricVariant {
  type Trick[a] = { type A <: a }
  type M[t] = t match { case Trick[a] => N[a] }
  
  trait Root[B] {
    def thing: M[B]
  }

  trait Child[B <: { type A <: Int }] extends Root[B]

  def foo[T <: { type A <: Int }](c: Child[T]): Trait2 = c.thing

  class Asploder extends Child[{ type A = String & Int }] {
    def thing = new Trait1 {}
  }

  def explode = foo(new Asploder)
}

object UpperBoundVariant {
  trait Cov[+T]
  type M[t] = t match { case Cov[t] => N[t] }
  
  trait Root {
    type A 
    def thing: M[A]
  }

  trait Child extends Root { type A <: Cov[Int] }

  def foo(c: Child): Trait2 = c.thing

  class Asploder extends Child {
    type A = Cov[String & Int]
    def thing = new Trait1 {}
  }

  def explode = foo(new Asploder)
}
```

</p></details>

/cc @OlivierBlanvillain

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
This PR fixes the soundness hole exposed in #6570 by adding an extra condition to match type reduction: scrutinies should be non empty.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -2136,6 +2137,35 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
   /** Returns last check's debug mode, if explicitly enabled. */
   def lastTrace(): String = ""
 
+  private def typeparamCorrespondsToField(tycon: Type, tparam: TypeParamInfo): Boolean =
+    productSelectorTypes(tycon, null).exists {
+      case tp: TypeRef =>
+        (tp.designator: Any) == tparam // Bingo!
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: To avoid the upcast, maybe use `eq` instead?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -2136,6 +2137,35 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+      case _ =>
+        false
+    }
+
+  /** Is `tp` an empty type?
+   *
+   *  `true` implies that we found a proof; uncertainty default to `false`.
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: defaults

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -2136,6 +2137,35 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+   */
+  def provablyEmpty(tp: Type): Boolean =
+    tp.dealias match {
+      case tp if tp.isBottomType => true
+      case AndType(tp1, tp2) => disjoint(tp1, tp2)
+      case OrType(tp1, tp2) => provablyEmpty(tp1) && provablyEmpty(tp2)
+      case at @ AppliedType(tycon, args) =>
+        args.lazyZip(tycon.typeParams).exists { (arg, tparam) =>
+          tparam.paramVariance >= 0 &&
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: You can write `&&` in front now, which looks nicer IMO.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 4]
```diff
@@ -2144,8 +2174,12 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
    *
    *  1. Single inheritance of classes
    *  2. Final classes cannot be extended
-   *  3. ConstantTypes with distinc values are non intersecting
+   *  3. ConstantTypes with distinct values are non intersecting
    *  4. There is no value of type Nothing
+   *
+   *  Note on soundness: the correctness of match types relies on on the
+   *  property that in all possible contexts, a same match type expression
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: a same --> the same

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 5]
```diff
@@ -2187,27 +2221,13 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
           else
             false
       case (AppliedType(tycon1, args1), AppliedType(tycon2, args2)) if tycon1 == tycon2 =>
+        // It is possible to conclude that two types applies are disjoints by
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: disjoints --> disjoint

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 6]
```diff
@@ -2187,27 +2221,13 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+        // looking at covariant type parameters if The said type parameters
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: The -> the, "disjoin"
