### PR TITLE
REPL: Fix crash when printing instances of value classes

### LINKED ISSUE #16322: REPL regression with instantiating class instances from the `scala.concurrent.duration` package
## Compiler version

3.2.1

## Minimized code
Open a Scala 3.2.1 REPL:

```Scala
Welcome to Scala 3.2.1 (17.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                        
scala> new scala.concurrent.duration.DurationInt(5)
```

## Output

```scala
Exception in thread "main" java.lang.ClassNotFoundException: package$DurationInt
	at dotty.tools.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at dotty.tools.repl.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:57)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at dotty.tools.repl.Rendering.rewrapValueClass(Rendering.scala:127)
	at dotty.tools.repl.Rendering.$anonfun$4(Rendering.scala:106)
	at scala.Option.flatMap(Option.scala:283)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:106)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:149)
	at dotty.tools.repl.ReplDriver.$anonfun$7(ReplDriver.scala:365)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:371)
	at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:403)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:409)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:307)
	at scala.util.Either.fold(Either.scala:189)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:323)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:248)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:168)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:191)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:179)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:179)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:133)
	at dotty.tools.repl.Main$.main(Main.scala:7)
	at dotty.tools.MainGenericRunner$.run$1(MainGenericRunner.scala:193)
	at dotty.tools.MainGenericRunner$.process(MainGenericRunner.scala:270)
	at dotty.tools.MainGenericRunner$.main(MainGenericRunner.scala:281)
	at dotty.tools.MainGenericRunner.main(MainGenericRunner.scala)
```

Same error happens if `new` is not used.

## Expectation

Scala 3.2.0 REPL:

```scala
Welcome to Scala 3.2.0 (17.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                        
scala> new scala.concurrent.duration.DurationInt(5)
```

Output:
```scala
val res0: scala.concurrent.duration.package.DurationInt = 5
```

Although, the result is also weird, there's a mention of `scala.concurrent.duration.package.DurationInt`, which is not the same fully qualified name. As far as I can tell, this behavior is consistent in Scala 3.1.3 too. I did not check older versions.

Edit:

Scala 2.13.10 reports the same value as:
```scala
val res0: concurrent.duration.DurationInt = scala.concurrent.duration.package$DurationInt@5
```

The mention of `package` might just be down to the bytecode encoding and might be completely fine.

### LINKED ISSUE #16387: explicit `unapplySeq` call in REPL throw `ClassNotFoundException: SeqFactory$UnapplySeqWrapper`
## Compiler version

- 3.2.1
- 3.3.0-RC1-bin-20221119-786ad3f-NIGHTLY

## Minimized code

```scala
Vector.unapplySeq(Vector(2))
```

## Output

```
Welcome to Scala 3.3.0-RC1-bin-20221119-786ad3f-NIGHTLY-git-786ad3f (11.0.17, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                               
scala> Vector.unapplySeq(Vector(2))
[error] java.lang.ClassNotFoundException: SeqFactory$UnapplySeqWrapper
[error] 	at dotty.tools.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:51)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error] 	at dotty.tools.repl.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:57)
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] 	at dotty.tools.repl.Rendering.rewrapValueClass(Rendering.scala:135)
[error] 	at dotty.tools.repl.Rendering.$anonfun$4(Rendering.scala:114)
[error] 	at scala.Option.flatMap(Option.scala:283)
[error] 	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:114)
[error] 	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:157)
[error] 	at dotty.tools.repl.ReplDriver.$anonfun$7(ReplDriver.scala:372)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:378)
[error] 	at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:410)
[error] 	at scala.Option.map(Option.scala:242)
[error] 	at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:416)
[error] 	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:312)
[error] 	at scala.util.Either.fold(Either.scala:189)
[error] 	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:330)
[error] 	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:253)
[error] 	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:168)
[error] 	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:171)
[error] 	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:196)
[error] 	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:184)
[error] 	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
[error] 	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:184)
[error] 	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:171)
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

## Expectation

don't throw error

### PR DESCRIPTION
**Pull request by dwijnand**
By fixing `Rendering`'s `rewrapValueClass` to use the fully qualified class name

Sequel to #15545

Fixes #16322
Fixes #16387

### CODE REVIEW

File: compiler/src/dotty/tools/repl/Rendering.scala [hunk 1]
```diff
@@ -123,6 +126,9 @@ private[repl] class Rendering(parentClassLoader: Option[ClassLoader] = None):
         else
           s
       }
+  catch
+    case e: InvocationTargetException    => throw e
+    case e: ReflectiveOperationException => throw InvocationTargetException(e)
```
Comment (smarter) [inline compiler/src/dotty/tools/repl/Rendering.scala:131]: What does this do?

Comment (dwijnand) [reply compiler/src/dotty/tools/repl/Rendering.scala:131]: Gets caught:

https://github.com/lampepfl/dotty/blob/36353033551b6d457a58e7914bdbf21d778653f2/compiler/src/dotty/tools/repl/Rendering.scala#L150-L160

And rendered as an error:

https://github.com/lampepfl/dotty/blob/36353033551b6d457a58e7914bdbf21d778653f2/compiler/src/dotty/tools/repl/ReplDriver.scala#L372-L377

As opposed to crashing out of the REPL.

Comment (smarter) [reply compiler/src/dotty/tools/repl/Rendering.scala:131]: But why is ReflectiveOperationException rewrapepd in some other exception? And isnt `case e: InvocationTargetException    => throw e` equivalent to not having a case?

Comment (dwijnand) [reply compiler/src/dotty/tools/repl/Rendering.scala:131]: > But why is ReflectiveOperationException rewrapped in some other exception?

Because `InvocationTargetException` is what's handled upstream (in renderVal).

> And isnt `case e: InvocationTargetException => throw e` equivalent to not having a case?

No, because InvocationTargetException <: ReflectiveOperationException and I don't want to that wrapped.

Comment (smarter) [reply compiler/src/dotty/tools/repl/Rendering.scala:131]: Could the code upstream be changed to handle ReflectiveOperationException instead?

File: compiler/src/dotty/tools/repl/Rendering.scala [hunk 2]
```diff
@@ -131,7 +137,13 @@ private[repl] class Rendering(parentClassLoader: Option[ClassLoader] = None):
    */
   private def rewrapValueClass(sym: Symbol, value: Object)(using Context): Option[Object] =
     if ValueClasses.isDerivedValueClass(sym) then
-      val valueClassName = sym.flatName.encode.toString
+      val pkg = sym.enclosingPackageClass
+      val pkgName = if pkg.isEmptyPackage then "" else s"${pkg.fullName.mangledString}."
+      val clsFlatName = if sym.isOneOf(JavaDefined | ConstructorProxy) then
+        // See ExtractDependencies.recordDependency
```
Comment (smarter) [inline compiler/src/dotty/tools/repl/Rendering.scala:143]: I would prefer if we could extract the logic out of recordDependency in a shared method, it looks like we have a potential third user for this method too: https://github.com/lampepfl/dotty/pull/16392#discussion_r1036892345

File: compiler/src/dotty/tools/repl/Rendering.scala (hunk 1 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/repl/Rendering.scala]: Done

**Review by smarter — APPROVED** [review]
