### PR TITLE
Fix superType of SuperType

### LINKED ISSUE #17555: Wrong linearization for super calls in case classes
## Compiler version

3.2.2
3.3.0-RC3
Worked in 3.1.2

## Minimized code

```Scala
class Root {
  override def toString() = "Root"
}
trait A extends Root with B {  }
trait B {
   override def toString() = "B"
}
case class C() extends A {
  override def toString() = super.toString()
}

println(C())
```

## Output

```
Root
```

## Expectation
`toString` in trait `B` should be called and output should be B.
This works for normal classes, but the case class breaks that.

### PR DESCRIPTION
**Pull request by odersky**
I am not quite sure about he previous definition of superType in SuperType. I believe it's probably needed for something. But it's clearly wrong if the `supertpe` argument does not have a symbol. We now fall back to the default 
```
   def superType = underlying
``` 
in this case.

Fixes #17555

### CODE REVIEW

File: tests/run/i17555.scala [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+case class C() extends A {
+  override def toString() = super.toString()
+}
+class D() extends A, Serializable {
+  override def toString() = super.toString()
+}
+
+@main def Test =
+  println(C())
+  println(D())
```
Comment (som-snytt) [inline tests/run/i17555.scala:17]: vulpix does not verify output without a check file, so `assert` is more effective or defensive.

Comment (odersky) [reply tests/run/i17555.scala]: Oh, yes, that was an oversight. Thanks for pointing it out!

**Review by dwijnand — APPROVED** [review]
