### PR TITLE
Fix #15701: Implement js.dynamicImport for dynamic module loading.

### LINKED ISSUE #15701: Scala.js `js.dynamicImport` always outputs "stub" error
## Compiler version

Any, tested fom `3.0.0` to `3.2.1-RC1-bin-20220717-5c43324-NIGHTLY`. Behaviour does not occur on 2.13.8.

## Minimized code

```Scala
import scala.scalajs.js

object Main {
  def main(args: Array[String]): Unit = {
    // Message is dynamically imported and results in a `import(...) call in JS`
    js.dynamicImport {
      println(new Message().msg)
    }
  }
}

class Message {
  def msg = "Hello world dynamic import"
}
```

Needs some linker config settings to support ES modules. Repro here in a sbt project: https://github.com/hugo-vrijswijk/scala-js-dynamic-import-scala3-bug

## Output

```scala
[info] Running Main.
<ref *1> $c_jl_Error [java.lang.Error]: stub
    at $c_LMain$.main__AT__V (file:///project/target/scala-3.2.1-RC1-bin-20220717-5c43324-NIGHTLY/hello-world-fastopt/main.mjs:818:27)
    at $s_LMain__main__AT__V (file:///project/target/scala-3.2.1-RC1-bin-20220717-5c43324-NIGHTLY/hello-world-fastopt/main.mjs:804:15)
    at file:///project/target/scala-3.2.1-RC1-bin-20220717-5c43324-NIGHTLY/hello-world-fastopt/main.mjs:1744:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
  jl_Throwable__f_s: 'stub',
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: [Circular *1],
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null
}
```

Scala.JS on Scala 3 emits the line:
- fastLinkJS: `throw $ct_jl_Error__T__(new $c_jl_Error(), "stub")`
- fullLinkJS: `throw new $c_jl_Error("stub")` 

On 2.13.8 the import is emitted as expected.

## Expectation

Code runs without error and prints the expected message to the console. `sbt ++2.13.x run` works as expected, while `sbt run` gives the error above

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Dependencies.scala [hunk 1]
```diff
@@ -182,14 +184,24 @@ abstract class Dependencies(root: ast.tpd.Tree, @constructorOnly rootContext: Co
...
+                  // needed to not cause deadlocks in classloader. see t5375.scala
+              )
+        )
+        || (
+          /* Scala.js: Never move any member beyond the boundary of a DynamicImportThunk.
+           * DynamicImportThunk subclasses are boundaries between the eventual ES modules
+           * that can be dynamically loaded. Moving members across that boundary changes
+           * the dynamic and static dependencies between ES modules, which is forbidden.
+           */
+          ctx.settings.scalajs.value && encClass.isSubClass(jsdefn.DynamicImportThunkClass)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/Dependencies.scala:202]: Is this enough to guarantee that no member is ever moved across a `DynamicImportThunk` class boundary?

Scala 2 did not move things around like that, so this is new code compared to the commit we're porting.

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala [hunk 2]
```diff
@@ -279,6 +279,39 @@ class PrepJSInterop extends MacroTransform with IdentityDenotTransformer { thisP
...
+
+          assert(currentOwner.isTerm, s"unexpected owner: $currentOwner at ${tree.sourcePos}")
+
+          val cls = newNormalizedClassSymbol(currentOwner, tpnme.ANON_CLASS, Synthetic | Final,
+              List(jsdefn.DynamicImportThunkType), coord = span)
+          val constr = newConstructor(cls, Synthetic, Nil, Nil).entered
+
+          val applySym = newSymbol(cls, nme.apply, Method, MethodType(Nil, Nil, defn.AnyType), coord = span).entered
+          val newBody = transform(body).changeOwnerAfter(currentOwner, applySym, thisPhase)
+          val applyDefDef = DefDef(applySym, newBody)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:301]: Is this the correct way to completely move a tree, and everything that it contains, inside the new `def apply(): Any` method?

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala [hunk 3]
```diff
@@ -279,6 +279,39 @@ class PrepJSInterop extends MacroTransform with IdentityDenotTransformer { thisP
...
+        case Apply(TypeApply(fun, List(tpeArg)), List(body))
+            if fun.symbol == jsdefn.JSPackage_dynamicImport =>
+          val span = tree.span
+          val currentOwner = ctx.owner
+
+          assert(currentOwner.isTerm, s"unexpected owner: $currentOwner at ${tree.sourcePos}")
+
+          val cls = newNormalizedClassSymbol(currentOwner, tpnme.ANON_CLASS, Synthetic | Final,
+              List(jsdefn.DynamicImportThunkType), coord = span)
+          val constr = newConstructor(cls, Synthetic, Nil, Nil).entered
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:297]: I kind of wanted to use `tpe.AnonClass` here, but it only creates *forward* methods, whereas I need a new method (`apply`) that actually contains the tree `body`. Is there a better way to do this?

**Comment by sjrd** [comment]
@odersky May I ask you to review this one? This is mostly a port, but I have pointed out a few places where I'm not sure what I'm doing. The most critical is the change in lambdalift's `Dependencies`, which `git blame` traces to you.

The most important tests for these features are in https://github.com/scala-js/scala-js/blob/v1.10.1/test-suite/js/src/test/require-multi-modules/org/scalajs/testsuite/jsinterop/SJSDynamicImportTest.scala and are brought in by the last commit of this PR. Without the change in lambdalift, the test `localDefDynamic()` fails, for example, because the `def apply` gets lifted in `SJSDynamicImportTest` instead of being kept in the anonymous `DynamicImportThunk` class.

**Review by odersky — APPROVED** [review]
I only reviewed the changes to the non-js compiler code base. These look all good to me.

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala (hunk 3 above)
Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala]: Indeed, there was some opportunity for refactoring. In fact, it extended to two other places in the codebase which followed the same pattern. I have added a commit that factors out the common pattern from those 4 places. Does it look good to you?

File: compiler/src/dotty/tools/dotc/ast/tpd.scala [hunk 4]
```diff
@@ -340,27 +340,35 @@ object tpd extends Trees.Instance[Type] with TypedTreeInfo {
...
+  def AnonClass(owner: Symbol, parents: List[Type], coord: Coord)(body: ClassSymbol => List[Tree])(using Context): Block =
     val parents1 =
       if (parents.head.classSymbol.is(Trait)) {
         val head = parents.head.parents.head
         if (head.isRef(defn.AnyClass)) defn.AnyRefType :: parents else head :: parents
       }
       else parents
-    val cls = newNormalizedClassSymbol(owner, tpnme.ANON_CLASS, Synthetic | Final, parents1,
-        coord = fns.map(_.span).reduceLeft(_ union _))
+    val cls = newNormalizedClassSymbol(owner, tpnme.ANON_CLASS, Synthetic | Final, parents1, coord = coord)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/tpd.scala:368]: Nitpick: If it's the same name, consider just writing it once. I.e. `coord` instead of `coord = coord`.

**Review by odersky — APPROVED** [review]
It's a nice simplification!

File: compiler/src/dotty/tools/dotc/ast/tpd.scala (hunk 4 above)
Comment (sjrd) [reply compiler/src/dotty/tools/dotc/ast/tpd.scala:368]: I can't. There are other parameters with default values in the middle, namely `selfInfo` and `privateWithin`. So we need `coord =`.
