### PR TITLE
Fix #11654: create new symbol for stdlib patches

### LINKED ISSUE #11654: test_windows_full in the CI is broken: pickling difference in stdlibPatches
It appears to have started with https://github.com/lampepfl/dotty/commit/96ced0232b8b91e21127674215ad5ee63dfc33ed, the CI run is https://github.com/lampepfl/dotty/runs/2057136722:
```scala
 class dotty.tools.dotc.reporting.Diagnostic$Error at ?: pickling difference for module class language$ in library\src\scala\runtime\stdLibPatches\language.scala, for details:
Fatal compiler crash when compiling: library\src\scala\runtime\stdLibPatches:

  diff before-pickling.txt after-pickling.txt while compiling library\src\scala\runtime\stdLibPatches\language.scala, library\src\scala\runtime\stdLibPatches\Predef.scala
pickling difference for module class language$ in library\src\scala\runtime\stdLibPatches\language.scala, for details:

  diff before-pickling.txt after-pickling.txt
dotty.tools.dotc.report$.error(report.scala:71)
dotty.tools.dotc.transform.Pickler.testSame(Pickler.scala:145)
dotty.tools.dotc.transform.Pickler.testUnpickler$$anonfun$2(Pickler.scala:135)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
scala.collection.AbstractIterable.foreach(Iterable.scala:919)
scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
dotty.tools.dotc.transform.Pickler.testUnpickler(Pickler.scala:136)
dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:119)
dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
dotty.tools.dotc.Run.compileUnits(Run.scala:230)
dotty.tools.dotc.Run.compileSources(Run.scala:166)
dotty.tools.dotc.Run.compile(Run.scala:150)
dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
dotty.tools.dotc.Driver.process(Driver.scala:198)
dotty.tools.dotc.Driver.process(Driver.scala:166)
dotty.tools.vulpix.ParallelTesting$Test.compile(ParallelTesting.scala:490)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$2$$anonfun$1(ParallelTesting.scala:219)
scala.collection.immutable.List.map(List.scala:246)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$1(ParallelTesting.scala:219)
scala.util.Try$.apply(Try.scala:210)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.dotty$tools$vulpix$ParallelTesting$CompilationLogic$$compileTestSource(ParallelTesting.scala:220)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource$$anonfun$1(ParallelTesting.scala:265)
dotty.tools.vulpix.ParallelTesting$Test.tryCompile(ParallelTesting.scala:433)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource(ParallelTesting.scala:268)
dotty.tools.vulpix.ParallelTesting$Test$LoggedRunnable.run(ParallelTesting.scala:336)
dotty.tools.vulpix.ParallelTesting$Test$LoggedRunnable.run$(ParallelTesting.scala:318)
dotty.tools.vulpix.ParallelTesting$$anon$2.run(ParallelTesting.scala:263)
java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Error:  Test dotty.tools.dotc.BootstrappedOnlyCompilationTests.picklingWithCompiler failed: java.lang.AssertionError: Expected no errors when compiling, failed for the following reason(s):
Error:  
Error:    - encountered 1 test failures(s), took 25.844 sec
Error:      at dotty.tools.vulpix.ParallelTesting$CompilationTest.checkCompile(ParallelTesting.scala:897)
Error:      at dotty.tools.dotc.BootstrappedOnlyCompilationTests.picklingWithCompiler(BootstrappedOnlyCompilationTests.scala:177)
Error:      ...
[info] Test dotty.tools.dotc.BootstrappedOnlyCompilationTests.negWithCompiler started
[info] Test dotty.tools.dotc.BootstrappedOnlyCompilationTests.posMacros started
Foo[T]
[info] Test dotty.tools.dotc.BootstrappedOnlyCompilationTests.runWithCompiler started
foo
[info] Test dotty.tools.dotc.BootstrappedOnlyCompilationTests.runBootstrappedOnly started

================================================================================
Test Report
================================================================================

10 suites passed, 1 failed, 11 total
    library\src\scala\runtime\stdLibPatches failed
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #11654: create new symbol for stdlib patches

[test_windows_full]

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 1]
```diff
@@ -1108,6 +1110,9 @@ class Definitions {
    *  is read from a classfile.
    */
   def patchStdLibClass(denot: ClassDenotation)(using Context): Unit =
+    val annot = Annotation.deferredSymAndTree(defn.CompileTimeOnlyAnnot) {
+      Literal(Constant("The symbol can only be used at compile time in import statements"))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:1114]: I suggest putting those annotations directly in the source code in stdlibPatches/language.scala, because they might not apply to other definitions (like those in stdlibPatches/Predef.scala or others we may add in the future)

File: library/src/scala/runtime/stdLibPatches/language.scala [hunk 2]
```diff
@@ -56,6 +61,7 @@ object language:
      *  symbol literals are still supported with a language import, but new software
      *  should not use them.
      */
+    @compileTimeOnly("`symbolLiterals` can only be used at compile time in import statements")
```
Comment (smarter) [inline library/src/scala/runtime/stdLibPatches/language.scala:64]: `object deprecated` above should also be `@compileTimeOnly` since it doesn't exist in the scala 2 scala.language

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 3]
```diff
@@ -1111,10 +1111,49 @@ class Definitions {
...
+
+      def makeNonClassSymbol(patch: Symbol) =
+        if patch.is(Inline) then
+          // Inline symbols contain trees in annotations, which is coupled
+          // with the underlying symbol.
+          // Changing owner for inline symbols is a simple workaround.
+          patch.denot = patch.denot.copySymDenotation(owner = denot.symbol)
+          patch
+        else
+          // change `info` which might contain reference to the patch
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:1148]: Could we use a TreeTypeMap to map the info instead?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:1148]: You mean for the `inline` tree in the annotation? It's quite complex -- we need to create a copy of all local symbols (e.g. for type, term symbols, symbols in the function body, etc.) and rewire them.

For non-inline symbols, we make strong assumptions on `symbol.info`, which seems to be simpler.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:1148]: I meant for both, but I don't know if TreeTypeMap works on inline defs

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:1148]: I don't see a principled way to do this --- a map needs to make assumptions about `from` and `to`. We will not make fewer assumptions and the code will be complex.

**Review by smarter — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 4]
```diff
@@ -1111,10 +1111,49 @@ class Definitions {
...
    */
   def patchStdLibClass(denot: ClassDenotation)(using Context): Unit =
-
     def patch2(denot: ClassDenotation, patchCls: Symbol): Unit =
       val scope = denot.info.decls.openForMutations
+
       def recurse(patch: Symbol) = patch.is(Module) && scope.lookup(patch.name).exists
+
+      def makeClassSymbol(patch: Symbol, parents: List[Type], selfInfo: TypeOrSymbol) =
+        newClassSymbol(
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:1120]: Why can't we use `patch.copy(...)` here? Would that not be shorter?

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 5]
```diff
@@ -1111,10 +1111,49 @@ class Definitions {
...
+          owner = denot.symbol,
+          name = patch.name.asTypeName,
+          flags = patch.flags,
+          // need to rebuild a fresh ClassInfo
+          infoFn = cls => ClassInfo(
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:1125]: Would it not be shorter to use `derivedClassInfo` here?

File: compiler/src/dotty/tools/dotc/core/Definitions.scala (hunk 4 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:1120]: The reason is that `info` and `symbol` depend on each other, and `Symbol.copy` does not support that.

File: compiler/src/dotty/tools/dotc/core/Definitions.scala (hunk 5 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:1125]: That does not make much difference, as we change all fields here except `parents`.

**Review by odersky — APPROVED** [review]
OK, makes sense. Thanks for the explanations!
