### PR TITLE
Drop FreeSeqFactory from stdlib-cc

### LINKED ISSUE #19745: Another `is not a class type` error when creating an anonymous subclass of an abstract class via `new` through a type alias
## Compiler version

3.4.0

## Minimized code
https://scastie.scala-lang.org/gxYxc2GGSL2Kakv3xDQyKA
```Scala
final abstract class ForcedRecompilationToken[T]
object ForcedRecompilationToken {
  implicit def default: ForcedRecompilationToken["abc"] = null
}

object x {
  abstract class GoodNoParens[T](implicit ev: ForcedRecompilationToken[T])
}
type BadNoParens[T] = x.GoodNoParens[T]

object App extends App {
  // error
  new BadNoParens {}

  // ok
  new BadNoParens() {}
  new x.GoodNoParens {}

  println("compiled")
}
```

## Output

```scala
x.GoodNoParens is not a class type
```

## Expectation

Same issue as in https://github.com/lampepfl/dotty/issues/18623, but this time it's when instantiating via `new` instead of declaring an object.

### LINKED ISSUE #19845: `ClassNotFoundException` when running a program compiled with CC Scala 2 library
## Compiler version

`main`

## Minimized code

```Scala
class Foo extends Seq[Int]:
  def iterator: Iterator[Int] = ???
  def apply(i: Int): Int = 0
  def length: Int = 0

object Test {
  def main(args: Array[String]): Unit = {
    val foo: Foo = new Foo()
  }
}
```

## Output

```scala
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/FreeSeqFactory
	at Test$.main(xml.scala:8)
	at Test.main(xml.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.FreeSeqFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 2 more
```

### PR DESCRIPTION
**Pull request by odersky**
FreeSeqFactory was a construction to demonstrate type safety for certain iterableFactory.from calls where we rely in the fact that for all Seqs iterableFactory has an eager implementation of from.

While that shows that we _can_ make it typesafe, it does not work at runtime as a drop-in replacement for stdlib since of course stdlib does not have a FreeSeqFactory.

This commit drops FreeSeqFactory and adds three unsafeAssumePure calls instead, with explanations.

Fixes #19845

### CODE REVIEW

File: scala2-library-cc/src/scala/collection/Factory.scala [hunk 1]
```diff
@@ -297,16 +297,20 @@ object IterableFactory {
...
 
 // !!! Needed to add this separate trait
-trait FreeSeqFactory[+CC[A]] extends IterableFactory[CC]:
-  def from[A](source: IterableOnce[A]^): CC[A]
-  override def apply[A](elems: A*): CC[A] = from(elems)
+//trait FreeSeqFactory[+CC[A]] extends IterableFactory[CC]:
+//  def from[A](source: IterableOnce[A]^): CC[A]
+//  override def apply[A](elems: A*): CC[A]
+
+// type FreeSeqFactory[+CC[A] <: SeqOps[A, Seq, Seq[A]]] = SeqFactory[CC]
```
Comment (Linyxus) [inline scala2-library-cc/src/scala/collection/Factory.scala:304]: This seems obsolete. Shall we drop them?

**Review by Linyxus — APPROVED** [review]
Otherwise, LGTM!

(edit: I didn't notice there is one the failing test. It seems to be a result of overriding the method `apply` inside `SeqFactory`)
