### PR TITLE
Fix #8623: Treat parameterless givens as stable

### LINKED ISSUE #8623: Crash when using Tasty Reflect extension methods and a QuoteContext from a class
# Example 1
```Scala
import scala.quoted._

class Dummy(val ctx: QuoteContext)
given (using h: Dummy) as QuoteContext = h.ctx

def f[T](expr: Expr[T])(using h: Dummy) = {
  import h.ctx.tasty._
  expr.unseal.pos.sourceCode
}
```

<details><summary>Crash output</summary>

```scala
exception occurred while compiling /Users/kmetiuk/Projects/scala3/pg/misc/iss_1.scala
java.lang.AssertionError: assertion failed: unresolved symbols: value <skolem>(line -1), value <skolem>(line -1), value <skolem>(line -1) when pickling /Users/kmetiuk/Projects/scala3/pg/misc/iss_1.scala while compiling /Users/kmetiuk/Projects/scala3/pg/misc/iss_1.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: value <skolem>(line -1), value <skolem>(line -1), value <skolem>(line -1) when pickling /Users/kmetiuk/Projects/scala3/pg/misc/iss_1.scala
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:722)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$9$$anonfun$8(Pickler.scala:63)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:87)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:87)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:318)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:319)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:91)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:192)
	at dotty.tools.dotc.Run.compileSources(Run.scala:129)
	at dotty.tools.dotc.Run.compile(Run.scala:112)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
	at dotty.tools.dotc.Driver.process(Driver.scala:189)
	at dotty.tools.dotc.Driver.process(Driver.scala:158)
	at dotty.tools.dotc.Driver.process(Driver.scala:170)
	at dotty.tools.dotc.Driver.main(Driver.scala:197)
	at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

Typer phase output:

```scala
    def f[T >: Nothing <: Any](expr: quoted.Expr[T])(using h: Dummy): String =
      {
        import h.ctx.tasty._
        <skolem>.tasty.positionOps.sourceCode(
          <skolem>.tasty.TreeOps.pos(
            expr.unseal(iss_1$package.given_QuoteContext(h))
          )(<skolem>.tasty.given_Context)
        )
      }
```

# Example 2
```scala
import scala.quoted._

class Dummy(val ctx: QuoteContext)
given (using h: Dummy) as QuoteContext = h.ctx

def f[T](expr: Expr[T])(using h: Dummy) =
  import h.ctx.tasty._
  expr.unseal.pos
```

Compile output:

```scala
-- [E007] Type Mismatch Error: /Users/kmetiuk/Projects/scala3/pg/misc/iss_1-1.scala:7:2
7 |  import h.ctx.tasty._
  |  ^
  |  Found:    ?1.tasty.Position
  |  Required: quoted.QuoteContext#tasty.Position
  |
  |  where:    ?1 is an unknown value of type quoted.QuoteContext
8 |  expr.unseal.pos
```

Typer phase output:

```scala
    def f[T >: Nothing <: Any](expr: quoted.Expr[T])(using h: Dummy):
      quoted.QuoteContext#tasty.Position
     =
      {
        import h.ctx.tasty._
        <skolem>.tasty.TreeOps.pos(
          expr.unseal(iss_1-1$package.given_QuoteContext(h))
        )(<skolem>.tasty.given_Context)
      }
```

### PR DESCRIPTION
**Pull request by odersky**
Parameterless givens can be evaluated lazily, but should not have side
effects. Therefore, we should treat them as stable. This avoids
generation of skolem types when computing the result type of a dependent
method that takes another given as argument and whose result type
depends on that argument. Skolem types cannot be used for term inference
since they cannot be materialized as legal trees.

### CODE REVIEW

**Comment by milessabin** [comment]
Any overlap with https://github.com/lampepfl/dotty-feature-requests/issues/11?

**Review by smarter — CHANGES_REQUESTED** [review]
Even if we enforce purity (at least in the spec), we can't really enforce totality since writing an infinite loop is an easy mistake to make, so this is reintroduces a soundness hole we spent a lot of time and energy closing (https://github.com/lampepfl/dotty/issues/50):
```scala
object Test {
  trait A {
    type X = String
  }
  trait B {
    type X = Int
  }

  def foo: A & B = o
  given o as (A & B) = foo

  def xToString(x: o.X): String = x

  def intToString(i: Int): String = xToString(i)

  def main(args: Array[String]): Unit = {
    val z: String = intToString(1) // ClassNotFoundException
  }
}
```

**Comment by odersky** [comment]
@smarter You are right, unfortunately. It's a very thorny problem. Let's see whether there is anything else we can do...

**Comment by odersky** [comment]
We now do this:

## Make parameterless givens lazy vals

We used to represent them as defs and converted some of them to lazy
vals later, in CacheAliasImplicits.

But that means a parameterless given value is never a stable prefix, so
we cannot use it as a qualifier for an abstract type.

We now change the scheme so that parameterless givens start out as lazy vals
and some of them are changed to defs later in CacheAliasImplicits.

This is not a uniform improvement, since lazy vals have the restriction
that their types must be realizable. See i9103.scala, where we had to
change a type field to a trait to keep it working.

But I think overall this is an improvement to what we had before.

**Comment by odersky** [comment]
@milessabin We should see what we can do about lampepfl/dotty-feature-requests#11. But it's unrelated to the fix here. Somebody should drill down on what we can do here without compromising soundness. It's easy to slip about that, as the history of this PR shows.

File: compiler/src/dotty/tools/dotc/transform/CacheAliasImplicits.scala [hunk 1]
```diff
@@ -46,19 +46,36 @@ class CacheAliasImplicits extends MiniPhase with IdentityDenotTransformer { this
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/CacheAliasImplicits.scala:46]: The documentation comment of this class still states that aliases start as defs, it should be updated to describe how things work now.

File: compiler/src/dotty/tools/dotc/transform/CacheAliasImplicits.scala [hunk 2]
```diff
@@ -46,19 +46,36 @@ class CacheAliasImplicits extends MiniPhase with IdentityDenotTransformer { this
...
+   *
+   *    lazy val x = rhs
+   *
+   *  unless `rhs` has a stable type and is of one of them forms
+   *
+   *    this
+   *    this.y
+   *    y
+   *
+   *  Parameterless given defs are generated during typeclass derivation.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/CacheAliasImplicits.scala:71]: So this code path is only triggered because of these generated defs? Couldn't they be defined as given lazy vals too?

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/transform/CacheAliasImplicits.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/CacheAliasImplicits.scala:71]: I thought of it but then decided against. Typeclass derivation is very implicit. I felt its better to generate in one way only. This would make a difference if, say, the generated typeclass would have a side effect on instantiation. I have no idea whether something like this would be useful or not. But its easier to reason about if parameterized instances and parameterless instances behave the same.

**Comment by odersky** [comment]
Since we have so much else to do I propose to merge this now and come back to the deriving issue in a a separate PR.
