### PR TITLE
Fix #5270: Make TupleXXL extend Product

### LINKED ISSUE #5270: Is TupleN for N > 22 a Product at runtime?
`tests/pending/tuple-erased.scala` fails assertions at runtime about the erased classes. It fails because `Tuple23` is not a `Product`.

Should `TupleN` for `N>22` be a `Product`?

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: library/src/scala/TupleXXL.scala [hunk 1]
```diff
@@ -1,10 +1,15 @@
...
-final class TupleXXL private (es: Array[Object]) {
+final class TupleXXL private (es: Array[Object]) extends Product {
   assert(es.length > 22)
+
+  def productElement(n: Int): Any = es(n)
+  def productArity: Int = es.length
+
   override def toString = elems.mkString("(", ",", ")")
   override def hashCode = getClass.hashCode * 41 + deepHashCode(elems)
+  override def canEqual(that: Any): Boolean = that.isInstanceOf[TupleXXL]
```
Comment (smarter) [inline library/src/scala/TupleXXL.scala]: `&& that.productArity == this.productArity` ?

Comment (nicolasstucki) [reply library/src/scala/TupleXXL.scala]: Will add

Comment (nicolasstucki) [reply library/src/scala/TupleXXL.scala]: Added
