### PR TITLE
Fix #4373: reject wildcard types in syntactically invalid positions

### LINKED ISSUE #4373: Parser should reject wildcards in invalid positions
Seems to be caused by wildcards in unions or intersections in type bounds.

```scala
class X[A >: _ | X[_]]
// or
class X[A >: _ | _]
// or
class X[A <: (Int & _)]
```

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)) AppliedType(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class App$)),class X),List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))))
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.core.Types$OrType.<init>(Types.scala:2523)
	at dotty.tools.dotc.core.Types$CachedOrType.<init>(Types.scala:2551)
	at dotty.tools.dotc.core.Types$OrType$.apply(Types.scala:2556)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:488)
	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:487)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:83)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedOrTypeTree$1(Typer.scala:1188)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedOrTypeTree(Typer.scala:1184)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1801)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1829)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1816)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1829)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1860)
	at dotty.tools.dotc.reporting.trace$.op1$3(trace.scala:32)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:33)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1868)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedTypeBoundsTree$1(Typer.scala:1286)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedTypeBoundsTree(Typer.scala:1284)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1806)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1829)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1860)
	at dotty.tools.dotc.reporting.trace$.op1$3(trace.scala:32)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:33)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1868)
	at dotty.tools.dotc.typer.Namer.$anonfun$typedAheadType$1(Namer.scala:1006)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:999)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1006)
	at dotty.tools.dotc.typer.Namer.typeDefSig(Namer.scala:1256)
	at dotty.tools.dotc.typer.Namer$TypeDefCompleter.typeSig(Namer.scala:878)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:843)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:821)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:248)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:213)
	at dotty.tools.dotc.ast.desugar$DerivedFromParamTree.derivedTree(Desugar.scala:98)
	at dotty.tools.dotc.ast.desugar$DerivedFromParamTree.derivedTree(Desugar.scala:51)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedTypeTree$1(Typer.scala:1158)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedTypeTree(Typer.scala:1153)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1798)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1829)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1860)
	at dotty.tools.dotc.reporting.trace$.op1$3(trace.scala:32)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:33)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1868)
	at dotty.tools.dotc.typer.Namer.$anonfun$typedAheadType$1(Namer.scala:1006)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:999)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1006)
	at dotty.tools.dotc.typer.Namer.typeDefSig(Namer.scala:1256)
	at dotty.tools.dotc.typer.Namer$TypeDefCompleter.typeSig(Namer.scala:878)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:843)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:821)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:248)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:213)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:354)
	at dotty.tools.dotc.typer.Namer.$anonfun$defDefSig$1(Namer.scala:1217)
	at dotty.tools.dotc.typer.Namer.$anonfun$defDefSig$1$adapted(Namer.scala:1217)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1217)
	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:796)
	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:843)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:821)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:248)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:213)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:354)
	at dotty.tools.dotc.typer.Namer$ClassCompleter.completeInCreationContext(Namer.scala:979)
	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:821)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:248)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeInfo$1(SymDenotations.scala:211)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:213)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:354)
	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:1730)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1755)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1828)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1860)
	at dotty.tools.dotc.reporting.trace$.op1$3(trace.scala:32)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:33)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1868)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1887)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1916)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedClassDef$1(Typer.scala:1529)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1455)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1768)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1828)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1860)
	at dotty.tools.dotc.reporting.trace$.op1$3(trace.scala:32)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:33)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1868)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1887)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1916)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedPackageDef$1(Typer.scala:1636)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1627)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1808)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1829)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1860)
	at dotty.tools.dotc.reporting.trace$.op1$3(trace.scala:32)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:33)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1856)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1868)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1928)
	at dotty.tools.dotc.typer.FrontEnd.$anonfun$typeCheck$1(FrontEnd.scala:66)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:34)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:64)
	at dotty.tools.dotc.typer.FrontEnd.$anonfun$runOn$7(FrontEnd.scala:95)
	at dotty.tools.dotc.typer.FrontEnd.$anonfun$runOn$7$adapted(FrontEnd.scala:95)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:95)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:174)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:171)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:169)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:169)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:194)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:88)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:149)
	at dotty.tools.dotc.Run.compileSources(Run.scala:136)
	at dotty.tools.dotc.Run.compile(Run.scala:120)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:29)
	at dotty.tools.dotc.Driver.process(Driver.scala:127)
	at dotty.tools.dotc.Driver.process(Driver.scala:96)
	at dotty.tools.dotc.Driver.process(Driver.scala:108)
	at dotty.tools.dotc.Driver.main(Driver.scala:135)
	at dotty.tools.dotc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by Blaisorblade**
The testcase is from examples in #4373, variations and tests for types with wildcards. I'm unsure for a couple cases.

The strategy I use comes from generalizing existing code.

A separate commit avoids cascade errors. That was the trickiest part of this PR, but pretty instructive. I now sometimes use `Ident(nme.ERROR)` instead of `scalaAny` to replace illegal wildcards in `extends` clauses.

Action items:
- [x] rebase
- [x] merge #4424 since it was approved
- [x] make `checkWildcard` private to Parsers again
- [x] go through #4389 and try all reported issues in Bugs.txt that contain a `_` somewhere.
- [x] test and fix `with` too (noticed from #4389)
- [x] add testcases with annotations

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -2279,7 +2279,8 @@ object Parsers {
     /** ConstrApp         ::=  SimpleType {ParArgumentExprs}
      */
     val constrApp = () => {
-      val t = checkWildcard(annotType())
+      // Using Ident(nme.ERROR) to avoid causing cascade errors on non-user-written code
+      val t = checkWildcard(annotType(), fallbackTree = Ident(nme.ERROR))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: In extends caluse you could use `AnyRef` instead of `Any`

File: tests/neg/i4373.scala [hunk 2]
```diff
@@ -0,0 +1,23 @@
+trait Base
+trait TypeConstr[X]
+
+class X1[A >: _ | X1[_]] // error
```
Comment (smarter) [inline tests/neg/i4373.scala]: Maybe add some examples involving annotations too? `@_`, `_ @x`, ...

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 3]
```diff
@@ -1114,8 +1117,8 @@ object desugar {
         Apply(Select(Apply(Ident(nme.StringContext), strs), id), elems)
       case InfixOp(l, op, r) =>
         if (ctx.mode is Mode.Type)
-          if (!op.isBackquoted && op.name == tpnme.raw.AMP) AndTypeTree(l, r)     // l & r
-          else if (!op.isBackquoted && op.name == tpnme.raw.BAR) OrTypeTree(l, r) // l | r
+          if (!op.isBackquoted && op.name == tpnme.raw.AMP) AndTypeTree(checkWildcard(l), checkWildcard(r))     // l & r
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala]: I wonder if we shouldn't do this in Parser directly. This desugaring is kind of weird anyway, since it's not really about sugar but about how to parse something: we could just emit AndTypeTree or OrTypeTree as appropriate directly in Parser

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 4]
```diff
@@ -41,6 +41,25 @@ object Parsers {
     def nonePositive: Boolean = parCounts forall (_ <= 0)
   }
 
+  /** Checks whether `t` is a wildcard type.
+   *  If it is, returns the [[Position]] where the wildcard occurs.
+   */
+  @tailrec
+  final def findWildcardType(t: Tree): Option[Position] = t match {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: You could avoid using an `Option` here by returning `NoPosition`. You can then call `exists` on `Position`.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: That didn't work, because I end up with error messages like this, even though `https://github.com/scala/scala/blob/2.13.x/src/library-aux/scala/AnyRef.scala#L15` talks about a `trait AnyRef`:

```scala
scala> class A extends AnyRef with AnyRef
1 |class A extends AnyRef with AnyRef
  |                            ^^^^^^
  |                            class Object is not a trait
```

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 4 above)
Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Makes sense, but is that a good idea even if the existing code used `Option[Position]`?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: The existing code is not always right :)

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala (hunk 3 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: The reason to do it this way is that `op` is an identifier with a position. Converted to And/OrTypeTree, that information is lost.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 4 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: I guess it was a defensive move to accommodate the fact that the returned position could be NoPosition. So, yes, I'd leave it as is.

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala (hunk 3 above)
Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: 👍, trying this out.

It took me a while to give up searching `OrTypeTree` in the `Parser`, and honestly I was very confused that wasn't already the case.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 4 above)
Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Actually, self-answer: probably yes, that's the point of `NoPosition`, plus it avoids allocations.

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala (hunk 3 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: > The reason to do it this way is that op is an identifier with a position. Converted to And/OrTypeTree, that information is lost.

But is that information useful for anything?

Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: FWIW, changing this passes CI, see #4424.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: > But is that information useful for anything?

Go to definition in the IDE?

**Comment by odersky** [comment]
I think it would be good to go through #4389 and try all reported issues in Bugs.txt that contain a `_` somewhere. but fixed all the other ones there but left wildcard bugs alone, awaiting the fixes.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 5]
```diff
@@ -1035,6 +1035,19 @@ object Parsers {
       else
         rejectWildcard(t, fallbackTree)
 
+    def checkAndOrArgument(t: Tree): Tree =
+      findWildcardType(t, true) match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: At this point, `findWildcardType` is a misnomer.

**Comment by Blaisorblade** [comment]
FWIW, there's a bunch of further errors in #4389 which I'm making progress on — it seems some testcases still fail even when the minimizations were fixed.

File: tests/neg/i4373.scala (hunk 2 above)
Comment (Blaisorblade) [reply tests/neg/i4373.scala]: Done!

**Comment by Blaisorblade** [comment]
Ready for re-review, I've addressed all open action items.

I've looked through `bugs.txt` and I think I'm done here with it, the leftovers with wildcards are different issues, namely #4382 (again) and #4453. Non-minimized bugs are another matter.

```scala
// ==> 09d8cdb2f7be2b81c318d338626268b7ec28ab12.scala <==
trait x0[x0[_]] {
  (??? :x0[_]):x0[Int]
}
```
