### PR TITLE
Fix #7991: don't set JavaDefined for Dotty Enum module class

### LINKED ISSUE #7991: Cannot access enum from dependency at runtime
## minimized code

`Num.scala`
```Scala
enum Num { case One }
```

`Test.scala`
```Scala
object Test extends App {
  Num.One
}
```

```
$ mkdir out2
$ sbt
> dotc -d out2 Num.scala
> dotc -d out2 -classpath out2 Test.scala
> dotr -classpath out2 Test
Exception in thread "main" java.lang.NoSuchFieldError: One
        at Test$.<init>(Test_2.scala:2)
        at Test$.<clinit>(Test_2.scala)
        at Test.main(Test_2.scala)
```

## expectation
Should run

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #7991: don't set JavaDefined for Dotty Enum module class

Top-level Dotty Enum classes have the flag JAVA_ACC_ENUM.
We cannot tell from the flag whether a class is JavaDefined or not.
The `moduleRoot` already has the flag `JavaDefined` set, it suffices
to test the flag.

### CODE REVIEW

**Comment by smarter** [comment]
https://github.com/lampepfl/dotty/issues/7501 lists other NoSuchFieldError issues which should be fixed by this

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -200,12 +200,13 @@ class ClassfileParser(
...
 
-    // eager load java enum definitions for exhaustivity check of pattern match
+    // eager load enum definitions for exhaustivity check of pattern match
     if (isEnum) {
       instanceScope.toList.map(_.ensureCompleted())
       staticScope.toList.map(_.ensureCompleted())
-      classRoot.setFlag(Flags.JavaEnumTrait)
-      moduleRoot.setFlag(Flags.JavaEnumTrait)
+      val flag = if moduleRoot.is(Flags.JavaDefined) then Flags.JavaEnumTrait else Flags.Enum
+      classRoot.setFlag(flag)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala]: Why is enum treated specially ? The normal way to set java flags is done above:
```scala
    val sflags       = classTranslation.flags(jflags)
    // ...
    classRoot.setFlag(sflags)
```
It seems that the only missing piece is that [translateFlag](https://github.com/lampepfl/dotty/blob/83ab6c7ee82ff854ee782790d897748d474ccc0d/compiler/src/dotty/tools/dotc/core/classfile/ClassfileConstants.scala#L340) needs to be taught about the JAVA_ACC_ENUM flag (in fact, the corresponding method in scalac already does that: https://github.com/scala/scala/blob/d41fd0cb21edc102a4ab34b03e24c4215d130207/src/reflect/scala/reflect/internal/ClassfileConstants.scala#L356)

**Comment by smarter** [comment]
Ah, I see you already added tests for them :).

**Comment by bishabosha** [comment]
for #7410 can we also test a statement in the REPL accessing an enum constant from the class path

**Comment by nicolasstucki** [comment]
We should also have a variant of `tests/run/i7991` where the `Num` is a java enum.

File: compiler/src/dotty/tools/dotc/Compiler.scala [hunk 2]
```diff
@@ -58,8 +58,8 @@ class Compiler {
          new CheckReentrant,         // Internal use only: Check that compiled program has no data races involving global vars
          new ElimPackagePrefixes,    // Eliminate references to package prefixes in Select nodes
          new CookComments,           // Cook the comments: expand variables, doc, etc.
-         new CompleteJavaEnums) ::   // Fill in constructors for Java enums
-    List(new CheckStatic,            // Check restrictions that apply to @static members
+         new CheckStatic) ::         // Check restrictions that apply to @static members
+    List(new CompleteJavaEnums,      // Fill in constructors for Java enums
```
Comment (anatoliykmetyuk) [inline compiler/src/dotty/tools/dotc/Compiler.scala]: Why is this swap needed? Since we are adding the `@static` annotation in `CompleteJavaEnums`, should this phase not go before `CheckStatic` so that the latter can check the newly added static members?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/Compiler.scala]: `CheckStatic` will reject our code, because it requires that a `@static` member is located in a companion object, not the class.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/Compiler.scala]: Would it be a better idea to modify `CheckStatic` to accept the code? E.g., "1. Only objects and classes that extend java.lang.Enum can have members annotated with `@static`"?

The meaning of `CheckStatic` is to provide guarantees on `@static`. If there exists code that doesn't follow the existing guarantees, this complicates the codebase maintenance and usage. We have the exact same scenario with setting flags on completion: there are rules about which flags are immutable wrt completion but they are not enforced. And hence there are lots of places in the codebase that don't follow these rules.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/Compiler.scala]: I have a commit message in f6f3b28cfcc1f79d002a8af950ef49a84bc88b07: the `@static` infrastructure needs fundamentla refactoring, but it's out of the scope of this PR.
