### PR TITLE
Fix #2246: Use semantic names when freshening

### LINKED ISSUE #2246: Semantic names not used in LambdaLift
The semantic name PR broke compilation of scalatest, see https://github.com/lampepfl/dotty/issues/2233, the stacktrace is at https://gist.github.com/smarter/2b03b8fc57f7b8e4a027affe39b4426b and fails in LambdaLift. I'm not sure why, but I've noticed that LambdaLift defines the following method:
```scala
    private def newName(sym: Symbol)(implicit ctx: Context): Name =
      if (sym.isAnonymousFunction && sym.owner.is(Method, butNot = Label))
        (sym.name ++ NJ ++ sym.owner.name).freshened
      else sym.name.freshened
```
Which seems like it should be creating a semantic qualified name instead.

### PR DESCRIPTION
**Pull request by odersky**
I have decided to treat the super call problems elsewhere. Both are needed to make ScalaTest compile again.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/HoistSuperArgs.scala [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+      case tp: LambdaType =>
+        tp.derivedLambdaType(resType = replaceResult(tp.resultType, restpe))
+      case _ => restpe
+    }
+
+    /** A method representing a hoisted supercall argument */
+    def newSuperArgMethod(argType: Type) = {
+      val (staticFlag, methOwner) =
+        if (cls.owner.is(Package)) (JavaStatic, cls) else (EmptyFlags, cls.owner)
+      val argTypeWrtConstr = argType.subst(allParams, allParamRefs(constr.info))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/HoistSuperArgs.scala]: It seems `allParamRefs(constr.info)` is called for each argument, maybe turn it into lazy val? Or, it's because `constr.info` may change between different calls?

**Comment by liufengyun** [comment]
A mini test that reproduce the run-time exceptions:
```Scala
class Base[A](exp: => Option[A])

object Empty extends Base[Nothing](None)

object Test {
  def main(args: Array[String]): Unit = Empty
}
```

**Comment by odersky** [comment]
The super call arguments handling had "interesting" interactions with elimByName. The new treatment has been moved to a separate PR #2282.

**Comment by odersky** [comment]
@liufengyun I added your example to #2282. Thanks!
