### PR TITLE
Fix #6109: implement FunctionX.curried

### LINKED ISSUE #6109: Function5.curried not implemented
The following code fails at runt-time:

```Scala
object Test extends App {
  val f = (x1: Int, x2: Int, x3: Int, x4: Int, x5: Int) => x1 + x2 + x3 + x4 + x5
  println(f.curried(1)(2)(3)(4)(5))
}
```

`curried` in Function5 up to Function22 are not implemented.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #6109: implement FunctionX.curried

### CODE REVIEW

**Comment by liufengyun** [comment]
I'm not sure this is the right fix -- as the default methods are implemented in `scala.FunctionX`, it seems suffice to just remove the default implementation in `JFunctionX`.

File: library/src/dotty/runtime/function/JFunction14.java [hunk 1]
```diff
@@ -9,16 +9,4 @@
 public interface JFunction14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R> extends scala.Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R>, java.io.Serializable {
```
Comment (smarter) [inline library/src/dotty/runtime/function/JFunction14.java]: It doesn't need to be done in this PR, but we could also remove all the interfaces that just contain an empty `$init$` method, I think only https://github.com/lampepfl/dotty/blob/44e6d0f427cf251e67131fed02e1dac46babb537/compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala#L1179-L1181 would need to be adapted to check `arity <= 2`

File: library/src/dotty/runtime/function/JProcedure10.java [hunk 2]
```diff
@@ -8,7 +8,7 @@
 import scala.runtime.BoxedUnit;
 
 @FunctionalInterface
-public interface JProcedure10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> extends JFunction10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, BoxedUnit>, java.io.Serializable {
+public interface JProcedure10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> extends scala.Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, BoxedUnit>, java.io.Serializable {
     default void $init$() {
```
Comment (smarter) [inline library/src/dotty/runtime/function/JProcedure10.java]: I wonder if we could also remove all the empty $init$ methods, I don't think they serve any purpose.
