### PR TITLE
Fix #6255: Don't check unreachability for Expr[T]

### LINKED ISSUE #6255: Quoted pattern unreachable check always fails
```scala
class Foo {
  def foo(x: quoted.Expr[Int]) given scala.tasty.Reflection: Unit = x match {
    case '{ 1 } =>
    case '{ 2 } =>
    case _ =>
  }
}
```

which is transformed in typer to 

```scala
package <empty> {
  class Foo() extends Object() { 
    def foo(x: quoted.Expr[Int])(implicit x$2: scala.tasty.Reflection): Unit = 
      x match 
        {
          case scala.internal.quoted.Matcher.unapply[Unit](())('{1}, x$2) => 
            ()
          case scala.internal.quoted.Matcher.unapply[Unit](())('{2}, x$2) => 
            ()
          case _ => 
            ()
        }
  }
}
```

Where the patterns become part of the implicit arguments of the [`unapply`](https://github.com/lampepfl/dotty/blob/master/library/src-bootstrapped/scala/internal/quoted/Matcher.scala#L32).

The second case is considered as unreachable even when they differ in their parameters.
```scala
-- [E030] Match case Unreachable Warning: Foo.scala:4:9 ------------------------
4 |    case '{ 2 } =>
  |         ^^^^
  |         Unreachable case
```

### PR DESCRIPTION
**Pull request by liufengyun**
This seems to be the best strategy for now, given that
the implicit args trick is only used for matching Expr[T],
and `case _ =>` is always used in such cases.

Otherwise, we will need to reason equality of Terms, which is subtle.

### CODE REVIEW

**Comment by smarter** [comment]
> Otherwise, we will need to reason equality of Terms, which is subtle.

You can do =:= on termref which won't give any false positive, isn't that good enough?

**Comment by liufengyun** [comment]
>> Otherwise, we will need to reason equality of Terms, which is subtle.

> You can do =:= on termref which won't give any false positive, isn't that good enough?

That will be on the safe side, but will not help in checking `Expr[T]`, given that the parameters are not really implicit, but some trees:

          case scala.internal.quoted.Matcher.unapply[Unit](())('{1}, x$2) => 
            ()
          case scala.internal.quoted.Matcher.unapply[Unit](())('{2}, x$2) =>

**Comment by smarter** [comment]
Ah that's more complicated indeed, we do have a simple structural equality implementation for trees but I don't know if it's powerful enough for what you need: https://github.com/lampepfl/dotty/blob/eae5a38f24be24fbd6f9b583a687a7738747e5a0/compiler/src/dotty/tools/dotc/ast/TreeInfo.scala#L785-L789

File: tests/pos/i6255.scala [hunk 1]
```diff
@@ -0,0 +1,7 @@
+class Foo {
+  def foo(x: quoted.Expr[Int]) given scala.tasty.Reflection: Unit = x match {
+    case '{ 1 } =>
+    case '{ 2 } =>
+    case _ =>
```
Comment (smarter) [inline tests/pos/i6255.scala]: Shouldn't this be a pattern matching test ? Also do we get a warning if `case _` is missing ?

Comment (liufengyun) [reply tests/pos/i6255.scala]: Good catch, thanks. If we skip the check as it's done in this PR, we will not get the warning. I agree it will be helpful to issue an issue here. I'll update the PR to support that.

**Comment by AleksanderBG** [comment]
@liufengyun can we have a comment documenting why checking unreachability does not work for `Expr` in particular? If I understand everything correctly, it could go something like this:
```scala
// Ignore Expr for unreachability as a special case.
// Quote patterns produce repeated calls to the same unapply method,
// but with different implicit parameters.
// Since we understand repeated calls to the same unapply method to overlap
// and implicit parameters cannot normally differ between two patterns in one `match`,
// the easiest solution is just to ignore Expr.
```

**Comment by liufengyun** [comment]
@AleksanderBG Thanks for spelling it out, yes, that is what I have in mind.
