### PR TITLE
Fix #3339: Disallow accesses to private package members from nested pkgs

### LINKED ISSUE #3339: Missing access checks when accessing package private classes
This code shouldn't compile:
```scala
package outer {
  private class A

  package inner {
    object Test {
      def main(args: Array[String]): Unit = {
        println(new A)
      }
    }
  }
}
```
Because if you try to run it you get:
```scala
% dotr outer.inner.Test
Exception in thread "main" java.lang.IllegalAccessError: tried to access class outer.A from class outer.inner.Test$
        at outer.inner.Test$.main(i3302.scala:7)
        at outer.inner.Test.main(i3302.scala
```

This code compiles and run with scalac because the class `A` is emitted as `public` whereas dotty emits it as `private`.

### PR DESCRIPTION
**Pull request by odersky**
Change of the accessibility rules: Disallow accesses to private package members from nested packages.

Such accesses were causing an access error at runtime before.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -733,7 +730,9 @@ object SymDenotations {
              (  !(this is Local)
              || (owner is ImplClass) // allow private local accesses to impl class members
              || isCorrectThisType(pre)
-             )
+             ) &&
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: This long chain of conditions is getting really hard to read, factor it out into a few vals?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: I tried but it does not seem to help. The key is treating !A || B as an implication then things get clearer. I was wondering whether we should add an inline helper method `implies` on `Boolean` to do this. But it's quite a lot of effort.
