### PR TITLE
Fix #10614: align unchecked pattern definition syntax with Scala 2

### LINKED ISSUE #10614: Usage of `@unchecked` annotation with `val` is inconsistent between Scala 2 and 3
in Scala 2, one annotates the scrutinee:

```scala
scala 2.13.4> val Some(x) = Option(3)
                                  ^
              warning: match may not be exhaustive.
              It would fail on the following input: None
val x: Int = 3

scala 2.13.4> val Some(x) = Option(3): @unchecked
val x: Int = 3
```

whereas in Scala 3.0.0-M2 under `-source:3.1` one must annotate the pattern, while annotating the scrutinee is ignored:

```scala
scala> val Some(x) = Option(3)
1 |val Some(x) = Option(3)
  |    ^^^^^^^
  |pattern's type Some[Int] is more specialized than the right hand side expression's type Option[Int]
  |
  |If the narrowing is intentional, this can be communicated by writing `: @unchecked` after the full pattern.

scala> val Some(x) = Option(3): @unchecked                                                                              
1 |val Some(x) = Option(3): @unchecked
  |    ^^^^^^^
  |pattern's type Some[Int] is more specialized than the right hand side expression's type Option[Int] @unchecked
  |
  |If the narrowing is intentional, this can be communicated by writing `: @unchecked` after the full pattern.

scala> val Some(x): @unchecked = Option(3)
val x: Int = 3
```

Scala 3's behavior is as documented at https://dotty.epfl.ch/docs/reference/changed-features/pattern-bindings.html :

> Sometimes one wants to decompose data anyway, even though the pattern is refutable. For instance, if at some point one knows that a list `elems` is non-empty one might want to decompose it like this:
> 
> ```scala
> val first :: rest = elems   // error
> ```
> 
> This works in Scala 2. In fact it is a typical use case for Scala 2's rules. But in Scala 3.1 it will give a type error. One can avoid the error by marking the pattern with an @unchecked annotation:
> 
> ```scala
> val first :: rest : @unchecked = elems   // OK
> ```
> 
> This will make the compiler accept the pattern binding. It might give an error at runtime instead, if the underlying assumption that `elems` can never be empty is wrong.

but I suggest that Scala 3 should adopt the Scala 2 convention, because:

* it is more consistent with `match`; one also annotates the scrutinee with `match`, like `(foo: @unchecked) match ...`
* we want to support cross-building between 2 and 3, and 2's style is the established precedent

(this came up at https://github.com/scala/bug/issues/12245)

This became more important with the release of Scala 2.13.4, where improved exhaustivity checking has sent many users scurrying to add `@unchecked` to their matches.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #10614: align unchecked pattern definition syntax with Scala 2

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -1006,14 +1006,17 @@ object desugar {
...
     else {
-      val sel1 = Annotated(sel, New(ref(defn.UncheckedAnnot.typeRef)))
-      if (checkMode != MatchCheck.None) sel1.pushAttachment(CheckIrrefutable, checkMode)
-      sel1
+      if (checkMode == MatchCheck.None)
+        Annotated(sel, New(ref(defn.UncheckedAnnot.typeRef)))
+      else
+        // TODO: use `pushAttachment` and investigate duplicate attachment
+        sel.withAttachment(CheckIrrefutable, checkMode)
+        sel
```
Comment (b-studios) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala:1019]: I cannot foresee the interaction of existing attachments here. However, the implementation of `makeSelector` could be factored to

```
checkMode match {
      case MatchCheck.Exhaustive => 
        sel
      case MatchCheck.None =>  
        Annotated(sel, New(ref(defn.UncheckedAnnot.typeRef)))      
      case MatchCheck.IrrefutablePatDef | MatchCheck.IrrefutableGenFrom => 
        // TODO: use `pushAttachment` and investigate duplicate attachment
        sel.withAttachment(CheckIrrefutable, checkMode)
    }
```
to be even closer to the comment documenting it.

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 2]
```diff
@@ -671,30 +671,32 @@ trait Checking {
       report.error(ex"$cls cannot be instantiated since it${rstatus.msg}", pos)
   }
 
-  /** Check that pattern `pat` is irrefutable for scrutinee tye `pt`.
-   *  This means `pat` is either marked @unchecked or `pt` conforms to the
+  /** Check that pattern `pat` is irrefutable for scrutinee tye `sel.tpe`.
```
Comment (b-studios) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:674]: There is a small type: "tye" -> "type"
```suggestion
  /** Check that pattern `pat` is irrefutable for scrutinee type `sel.tpe`.
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -1386,18 +1386,27 @@ class Typer extends Namer
...
         result match {
-          case Match(sel, CaseDef(pat, _, _) :: _) =>
+          case result @ Match(sel, CaseDef(pat, _, _) :: _) =>
             tree.selector.removeAttachment(desugar.CheckIrrefutable) match {
               case Some(checkMode) =>
                 val isPatDef = checkMode == desugar.MatchCheck.IrrefutablePatDef
-                if (!checkIrrefutable(pat, sel.tpe, isPatDef) && sourceVersion == `3.1-migration`)
-                  if (isPatDef) patch(Span(pat.span.end), ": @unchecked")
+                if (!checkIrrefutable(sel, pat, isPatDef) && sourceVersion == `3.1-migration`)
+                  if (isPatDef) patch(Span(tree.selector.span.end), ": @unchecked")
```
Comment (b-studios) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1394]: Did you check whether patching is still necessary here?

File: docs/docs/reference/changed-features/pattern-bindings.md [hunk 4]
```diff
@@ -25,9 +25,9 @@ want to decompose it like this:
 ```scala
 val first :: rest = elems   // error
 ```
-This works in Scala 2. In fact it is a typical use case for Scala 2's rules. But in Scala 3.1 it will give a type error. One can avoid the error by marking the pattern with an `@unchecked` annotation:
+This works in Scala 2. In fact it is a typical use case for Scala 2's rules. But in Scala 3.1 it will give a type error. One can avoid the error by marking the rhs with an `@unchecked` annotation:
```
Comment (b-studios) [inline docs/docs/reference/changed-features/pattern-bindings.md:28]: Maybe spell `rhs` out as "right-hand side"?

File: tests/neg-strict/unchecked-patterns.scala [hunk 5]
```diff
@@ -1,13 +1,13 @@
...
-  val (y1: Some[Int] @unchecked) = Some(1): Option[Int]  // OK
+  val (y1: Some[Int]) = Some(1): Option[Int] @unchecked  // OK
   val y2: Some[Int] @unchecked = Some(1): Option[Int]    // error
 
   val x :: xs = List(1, 2, 3)        // error
   val (1, c) = (1, 2)                // error
   val 1 *: cs = 1 *: Tuple()         // error
 
-  val (_: Int | _: Any) = ??? : Any  // error
+  val (_: Int | _: AnyRef) = ??? : AnyRef  // error
```
Comment (b-studios) [inline tests/neg-strict/unchecked-patterns.scala:10]: Why do you need this change?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 6]
```diff
@@ -1386,18 +1386,27 @@ class Typer extends Namer
...
                   else patch(Span(pat.span.start), "case ")
+
+                // skip exhaustivity check in later phase
+                // TODO: move the check above to patternMatcher phase
+                val uncheckedTpe = AnnotatedType(sel.tpe.widen, Annotation(defn.UncheckedAnnot))
+                tpd.cpy.Match(result)(
+                  selector = tpd.Typed(sel, tpd.TypeTree(uncheckedTpe)),
+                  cases = result.cases
+                )
```
Comment (b-studios) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1403]: I am not sure, but doesn't this skip too many checks?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 3 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1394]: It's to change the source code to help auto-migrate the code, I think it's still necessary.

File: tests/neg-strict/unchecked-patterns.scala (hunk 5 above)
Comment (liufengyun) [reply tests/neg-strict/unchecked-patterns.scala:10]: This is due to the parametric top, we cannot match `Any`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 6 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1403]: It's basically the same as before. Previously we add `@unchecked` blindly during desugaring. Due to the syntax change, we cannot do that anymore, thus we add them here.

File: tests/neg-strict/unchecked-patterns.scala (hunk 5 above)
Comment (b-studios) [reply tests/neg-strict/unchecked-patterns.scala:10]: Ok, that's what I guessed :) Thanks

**Review by b-studios — APPROVED** [review]
