### PR TITLE
Fix #9463: create varargs forwarder symbols in transform instead of transformDefDef

### LINKED ISSUE #9463: Overriding an `@varargs` method fails under separate compilation
## Minimized code

`A.scala`

```
import scala.annotation.varargs

trait FirstMixin {
  @varargs
  def counter(name: String*): Int = ???
}

```
`B.scala`:

```
trait Minimization extends FirstMixin {
    override def counter(name: String*): Int = 0
}
```

## Output

Separate compilation of B.scala fails:

```scala
$ dotc A.scala
$ dotc -classpath . B.scala
-- [E037] Declaration Error: try/i9463b.scala:3:6 ------------------------------
3 |trait Minimization extends FirstMixin {
  |      ^
  |      method counter overrides nothing
```

## Expectation

Compiles successfully.

### PR DESCRIPTION
**Pull request by TheElectronWill**
This allows the forwarder symbols to be visible during separate compilation.
See [smarter's comment](https://github.com/lampepfl/dotty/issues/9463#issuecomment-665724166) in #9463.

### CODE REVIEW

**Comment by TheElectronWill** [comment]
Oopsie :eyes: Here are the tests.

**Comment by TheElectronWill** [comment]
I don't understand why `tests/pos/annot-bootstrap` fails now, especially as it's not consistent: sometimes it fails in `test`, sometimes in `test_bootstraped`, sometimes both, and I can't reproduce it locally :confused: 
When looking for the overriden symbols in `overridesJava` in `transform` ([here](https://github.com/lampepfl/dotty/blob/b720d6c7d1e12cda6620ba3d27d02d1a6168b590/compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala#L65)), it ends up calling `complete` on a `NoLoader`, which fails.

**Comment by smarter** [comment]
Hmm, not sure what's going on. One thing I see is that `overridesJava(sym)` is now going to be called more often since the `ref1 ne ref` check was moved below it, so I guess this is causing some sort of cycle, but only in very specific conditions? From the stacktrace I see that the call to complete the NoLoader symbol comes from `isAbsent` which is itself called from the `TreeChecker#transformSym`, that call could be changed to `isAbsent(canForce = false)` to avoid that completion (this won't break anything since TreeChecker is just here to run extra sanity checks anyway).

**Comment by TheElectronWill** [comment]
🤔 Hmmm my last commit doesn't fix the problem. But I have another idea.

**Comment by TheElectronWill** [comment]
It works! :tada:

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 1]
```diff
@@ -62,9 +62,9 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
     super.transform(ref) match
       case ref1: SymDenotation if ref1.is(Method) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:63]: Originally the `ref1 ne ref` was here which I think is equivalent to what the code is doing now?

Comment (TheElectronWill) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:63]: Not quite, because now `transformVarArgs` is always called. If I move `ref1 ne ref` back to the `case` guard, some situations are not covered and e.g. `tests/neg/varargs-annot` fails.

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 2]
```diff
@@ -34,12 +33,43 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
+    end
+
     super.transform(ref) match
-      case ref1: SymDenotation if (ref1 ne ref) && overridesJava(ref1.symbol) =>
-        // This method won't override the corresponding Java method at the end of this phase,
-        // only the forwarder added by `addVarArgsForwarder` will.
-        ref1.copySymDenotation(initFlags = ref1.flags &~ Override)
+      case ref1: SymDenotation if ref1.is(Method) =>
+        val sym = ref1.symbol
+        val isJavaOverride = (ref1 ne ref) && overridesJava(sym) // (ref1 ne ref) avoids cycles
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:65]: A better name for this would be `isJavaVarargsOverride` since this is what `ref1 ne ref` implies and what we actually want: we don't want to remove the `Override` flag on all methods that are Java overrides, just the methods which override Java methods with a varargs parameter. And actually thinking about it, even that is not precise enough: we only want to do to this for Scala methods, so I think we need:
```suggestion
        val isJavaVarargsOverride = (ref1 ne ref) && !sym.is(JavaDefined) && overridesJava(sym)
```

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 3]
```diff
@@ -162,39 +197,36 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
-        else
-          // non-overrides cannot be synthetic otherwise javac refuses to call them
-          addVarArgsForwarder(tree, isBridge = isOverride)
-      else
-        tree
+    val isVarArgs = atPhase(thisPhase)(isVarargsMethod(sym))
+    if isVarArgs then
+      // Get the symbol generated in transform
+      val forwarderType = atPhase(thisPhase)(toJavaVarArgs(sym.info))
+      val forwarderSym = currentClass.info.decl(sym.name).alternatives
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:213]: Instead of `alternative.find`, using `altsWith` should be more efficient

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 4]
```diff
@@ -216,61 +248,54 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
-          // Can't call `.argTypes` here because the underlying array type is of the
-          // form `Array[? <: SomeType]`, so we need `.argInfos` to get the `TypeBounds`.
-          val elemtp = vararg.tpe.widen.argInfos.head
-          ref(original.termRef)
-            .appliedToTypes(trefs)
-            .appliedToArgss(init)
-            .appliedToArgs(last :+ tpd.wrapArray(vararg, elemtp))
-          })
-        Thicket(ddef, bridgeDef)
+        decls.enter(forwarder.enteredAfter(thisPhase))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:298]: I think the `decls.enter` here doesn't do anything, `enteredAfter` should already be taking care of adding the declaration in the correct scope, and it looks like `decls` is unused and will be garbage-collected.

Comment (TheElectronWill) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:298]: I misunderstood how `.enteredAfter` works, thanks for pointing that out!

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala (hunk 2 above)
Comment (TheElectronWill) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: Agreed. I've used `.is(Method, butNot = JavaDefined)` since it's useless to try to generate forwarders for java-defined varargs.

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 5]
```diff
@@ -54,17 +54,17 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
           else
-            addVarArgsForwarder(sym, isJavaOverride, hasAnnotation)
+            addVarArgsForwarder(sym, isJavaVarargsOverride, hasAnnotation)
       else if hasAnnotation
         report.error("A method without repeated parameters cannot be annotated with @varargs", sym.sourcePos)
     end
 
     super.transform(ref) match
-      case ref1: SymDenotation if ref1.is(Method) =>
+      case ref1: SymDenotation if ref1.is(Method, butNot=JavaDefined) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:63]: Spaces around the = sign:
```suggestion
      case ref1: SymDenotation if ref1.is(Method, butNot = JavaDefined) =>
```

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 6]
```diff
@@ -54,17 +54,17 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
         val sym = ref1.symbol
-        val isJavaOverride = (ref1 ne ref) && overridesJava(sym) // (ref1 ne ref) avoids cycles
-        transformVarArgs(sym, isJavaOverride)
-        if isJavaOverride then
+        val isJavaVarargsOverride = (ref1 ne ref) && overridesJava(sym) // (ref1 ne ref) avoids cycles
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:65]: I think that comment can be dropped since it's not only about avoiding cycles but also about only selecting the correct overrides

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 7]
```diff
@@ -280,22 +279,22 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
...
 
-    // Find a method that would conflict with the forwarder if the latter existed.
+    // Find methods that would conflict with the forwarder if the latter existed.
     // This needs to be done at thisPhase so that parent @varargs don't conflict.
-    val conflict =
-      classInfo.member(original.name).alternatives.find { s =>
+    val conflicts =
+      classInfo.member(original.name).altsWith { s =>
         s.matches(forwarder) &&
         !(isBridge && s.asSymDenotation.is(JavaDefined))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:287]: I think the `asSymDenotation` can be removed since `s` is a Symbol here.
