### PR TITLE
Fix #5494: Spurious unchecked warning when type testing an alias

### LINKED ISSUE #5494: Matches on type aliases for Unions generates incorrect warning
Valid for Dotty 0.23.0-RC1 as of 5/04/2020:

## Minimised example

```scala
class A
class B

type AorB = A | B

def foo(any: Any) = any match {
  case aorb: AorB =>
    println("got AorB")
}
```

```
[warn] -- Warning: .../unions.scala:5:7 
[warn] 5 |      case aorb: AorB =>
[warn]   |           ^^^^^^^^^^
[warn]   |        the type test for AorB cannot be checked at runtime
[warn] one warning found
```

This warning is incorrect as the correct instanceof checks are generated in the class file:

```
 public void foo(java.lang.Object);
    descriptor: (Ljava/lang/Object;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=5, args_size=2
         0: aload_1
         1: astore_2
         2: aload_2
         3: instanceof    #20                 // class example/A
         6: ifne          16
         9: aload_2
        10: instanceof    #22                 // class example/B
        13: ifeq          35
        16: aload_2
        17: checkcast     #4                  // class java/lang/Object
        20: astore_3
        21: aload_3
        22: astore        4
        24: getstatic     #27                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
        27: ldc           #40                 // String got AorB
        29: invokevirtual #32                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
        32: goto          46
        35: getstatic     #27                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
        38: ldc           #34                 // String got Any
        40: invokevirtual #32                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
        43: goto          46
        46: return
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
           22      13     4    ab   Ljava/lang/Object;
            0      47     0  this   Lexample/Demo$;
            0      47     1   foo   Ljava/lang/Object;
      LineNumberTable:
        line 19: 0
        line 20: 0
        line 22: 2
        line 23: 24
        line 25: 35
      StackMapTable: number_of_entries = 3
        frame_type = 252 /* append */
          offset_delta = 16
          locals = [ class java/lang/Object ]
        frame_type = 18 /* same */
        frame_type = 10 /* same */
```

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

**Comment by smarter** [comment]
There's still some bootstrapping errors indicating more issues with the checking logic:
```scala
[error] -- Error: /home/smarter/opt/dotty/compiler/src/dotty/tools/dotc/ast/NavigateAST.scala:95:15 
[error] 95 |          case p: WithLazyField[?] =>
[error]    |               ^^^^^^^^^^^^^^^^^^^
[error]    |the type test for dotty.tools.dotc.ast.Trees.WithLazyField[_] @_ cannot be checked at runtime
[error] -- Error: /home/smarter/opt/dotty/compiler/src/dotty/tools/dotc/core/Annotations.scala:89:59 
[error] 89 |    override def isEvaluated: Boolean = myTree.isInstanceOf[Tree]
[error]    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |the type test for dotty.tools.dotc.ast.tpd.Tree cannot be checked at runtime
[error] -- Error: /home/smarter/opt/dotty/compiler/src/dotty/tools/dotc/core/Annotations.scala:122:59 
[error] 122 |    override def isEvaluated: Boolean = myTree.isInstanceOf[Tree]
[error]     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |the type test for dotty.tools.dotc.ast.tpd.Tree cannot be checked at runtime
[error] -- Error: /home/smarter/opt/dotty/compiler/src/dotty/tools/dotc/core/tasty/PositionPickler.scala:58:10 
[error] 58 |          _: WithLazyField[?]
[error]    |          ^^^^^^^^^^^^^^^^^^^
[error]    |the type test for dotty.tools.dotc.ast.Trees.WithLazyField[_] @_ cannot be checked at runtime
```
- Doing a type test against a class type applied to wildcards like `WithLazyField[?]` is never unchecked
- Doing a type test against a class type like `Tree` is never unchecked

@liufengyun do you think you could have a look at those ?

**Comment by smarter** [comment]
> Doing a type test against a class type like Tree is never unchecked

Hmm actually maybe this one is correct: `Tree` here is `tpd.Tree` and we're checking against `tpd.Tree | (Context => tpd.Tree)`. Because `Function1` is a trait, we cannot rule out that there exists some subclass of `Tree` which extends it and is not a `tpd.Tree`.

**Comment by smarter** [comment]
> Doing a type test against a class type applied to wildcards like WithLazyField[?] is never unchecked

Actually here the problem is the confusion between pattern matching `_` and wildcard `?`, I'll open a separate issue for this.

**Comment by smarter** [comment]
> Actually here the problem is the confusion between pattern matching _ and wildcard ?, I'll open a separate issue for this.

Spoke too soon: the issue also happens with `_`.

**Comment by liufengyun** [comment]
Sure, I'll take a look at it. Thanks for the diagnosis.

**Comment by smarter** [comment]
OK, so the real issue with `WithLazyField` is that it's an unrelated trait to the type we're testing (`Positioned`), this shouldn't lead to unchecked warnings since any subclass may extend the trait. It didn't lead to errors before this PR because the logic in `isClassDetermined` used to be:
```scala
      P1 <:< X       // constraint P1

      // use fromScala2x to avoid generating pattern bound symbols
      maximizeType(P1, span, fromScala2x = true)

      val res = P1 <:< P
```
which succeeds even if `P1 <:< X` returns false.

By the way, the logic in `recur` is weird because it does:
```scala
X.classSymbol.exists && P.classSymbol.exists && !X.classSymbol.asClass.mayHaveCommonChild(P.classSymbol.asClass) || ...
```
Meaning that if `X` and `P` are known to never have a common child, the test returns true and no warning is emitted! Apparently this check was added to deal with union types (https://github.com/lampepfl/dotty/commit/94524371983b7adb2409c2f152a4cb2eae73a80e) but I think it's done at the wrong level, it leads to the following code emitting no warning:
```scala
class A
class B[T]

object Test {
  def foo(x: A) = x match {
    case x: B[Int] =>
    case _ =>
  }
}
```

**Comment by smarter** [comment]
Maybe we should consider redoing TypeTestsCasts based on the scala 2 implementation which is much more battle-tested: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Checkable.scala

**Comment by liufengyun** [comment]
@smarter The warning for always false test and runtime checkable are different.

The always false test warning is actually issued:

```Scala
scala> class A
     | class B[T]
     |
     | object Test {
     |   def foo(x: A) = x match {
     |     case x: B[Int] =>
     |     case _ =>
     |   }
     | }
6 |    case x: B[Int] =>
  |         ^
  |         this case is unreachable since type A and class B are unrelated
```

**Comment by liufengyun** [comment]
> Maybe we should consider redoing TypeTestsCasts based on the scala 2 implementation which is much more battle-tested: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Checkable.scala

I had a look at our implementation, I don't think it's a good idea to go to Scala 2 implementation, I believe our approach is more principled. We have a spec, and the bugs so far found can be easily fixed without changing the spec nor complicating the implementation.

The `isInstanceOf` check is, in essence, an inference problem. Thanks to the powerful GADT support in Dotty (thanks to @AleksanderBG ), we can now handle the check properly.

As far as I know, the Scala 2 implementation does not resort to type inference, thus it cannot cover the cases that the Dotty implementation can handle.

For example, Scala 2 does not issue any warning for the following code, while our check do:

```Scala
  trait A[+T]
  class B[T] extends A[T]

  class C
  class D extends C

  def quux(a: A[C]): Unit = a match {
    case _: B[C] => // error!!
  }

  quux(new B[D])
```

Another evidence for the correctness of the new implementation is that it founds many true positives in the compiler itself, catching mistakes from missing variance annotation on tree definitions (58f506ba7d51e2c659f5553ece4dc3d5d62c1c11), missing prefix such as `untpd` in patterns, or missing `@unchecked` (31c751f36a9c486047ec02ea93d84944c0bdac65).

It also catches the subtle errors demonstrated in the following code:

```Scala
  trait Tree[-T]
  trait Context

  trait Type

  def foo1(myTree: Tree[Type] | (Context => Tree[Type])) =
    println(myTree.isInstanceOf[Tree[Type]])   // error
    /* class DummyTree extends Tree[Nothing] with (Context => Tree[Type]) */
```

So I'd suggest we stay with the current scheme until a better solution emerges.

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/ast/Trees.scala [hunk 1]
```diff
@@ -579,7 +579,7 @@ object Trees {
   }
 
   /** Array(elems) */
-  class JavaSeqLiteral[T >: Untyped] private[ast] (elems: List[Tree[T]], elemtpt: Tree[T])(implicit @constructorOnly src: SourceFile)
+  class JavaSeqLiteral[-T >: Untyped] private[ast] (elems: List[Tree[T]], elemtpt: Tree[T])(implicit @constructorOnly src: SourceFile)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Trees.scala:582]: This is good for uniformity but why would this make any difference for type test safety warnings ?

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 2]
```diff
@@ -105,10 +105,9 @@ object TypeTestsCasts {
       debug.println("P1 : " + P1.show)
       debug.println("X : " + X.show)
 
-      P1 <:< X       // constraint P1
+      P1 <:< X
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:108]: I don't undestand what is going on here, the documentation above still says "constrain `Xs` with `pre.F[Xs] <:< X`", but this is not true in general since no constraint will be added if `P1` is not a subtype of `X`. The documentation need to explain why this is safe.

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 3]
```diff
@@ -105,10 +105,9 @@ object TypeTestsCasts {
...
 
-      // use fromScala2x to avoid generating pattern bound symbols
-      maximizeType(P1, span, fromScala2x = true)
+      maximizeType(P1, span, fromScala2x = false)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:110]: Similarly, why is it correct to use `maximizeType` here ?

File: compiler/src/dotty/tools/dotc/tastyreflect/ReflectionCompilerInterface.scala [hunk 4]
```diff
@@ -117,7 +117,7 @@ class ReflectionCompilerInterface(val rootContext: core.Contexts.Context) extend
   def isInstanceOfPackageClause(using ctx: Context): IsInstanceOf[PackageClause] = new {
     def runtimeClass: Class[?] = classOf[PackageClause]
     override def unapply(x: Any): Option[PackageClause] = x match
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/tastyreflect/ReflectionCompilerInterface.scala:119]: Can we avoid all these unchecked warnings by replacing `x: Any` by `x: tpd.Tree` here and below? /cc @nicolasstucki

File: compiler/src/dotty/tools/dotc/ast/Trees.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/ast/Trees.scala:582]: The following code shows why it matters:

```Scala
trait Tree[-T]

class JavaSeqLiteral[T] extends Tree[T]

trait Type

class DummyTree extends JavaSeqLiteral[Any]

def foo1(tree: Tree[Type]) =
  tree.isInstanceOf[JavaSeqLiteral[Type]]   // error

foo1(new DummyTree)
```

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:108]: That is expected if `P1` is not a subtype of `X`. It just tries to infer type parameters of `P1` from `X` if the value `x` indeed has the outer type `pre.F[_]`. Then it goes on to check if `P1 <: P`, which means the type arguments in `P` are trivial, thus no runtime checks are needed for them. Therefore, no warnings in such cases.

I'll refine the doc.

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala (hunk 3 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:110]: Maximization of the type means we try to cover all possible values which conform to the skeleton `pre.F[_]` and `X`. Then we have to make sure all of them are actually of the type `P`,  which implies that the type arguments in `P` are trivial (no runtime check needed).

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 5]
```diff
@@ -136,10 +144,10 @@ object TypeTestsCasts {
             // See TypeComparer#either
             recur(tp1, P) && recur(tp2, P)
           case _ =>
-            // first try withou striping type parameters for performance
+            // first try without striping type parameters for performance
             X.classSymbol.exists && P.classSymbol.exists && !X.classSymbol.asClass.mayHaveCommonChild(P.classSymbol.asClass) ||
-            isClassDetermined(X, tpe)(ctx.fresh.setNewTyperState()) ||
-            isClassDetermined(stripTypeParam(X), tpe)(ctx.fresh.setNewTyperState())
+            isClassDetermined(X, tpe)(ctx.fresh.setNewTyperState().setFreshGADTBounds) ||
```
[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:149]: The case for non-class type constructors is tested in the case `TypeProxy`, where we assume it cannot be checked at runtime. It seems the assumption is practical enough to cover use cases we know of. When the need emerges, we may relax the check a little bit to make it more expressive.

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 6]
```diff
@@ -136,10 +144,11 @@ object TypeTestsCasts {
             // See TypeComparer#either
             recur(tp1, P) && recur(tp2, P)
           case _ =>
-            // first try withou striping type parameters for performance
+            // always false test warnings are emitted elsewhere
             X.classSymbol.exists && P.classSymbol.exists && !X.classSymbol.asClass.mayHaveCommonChild(P.classSymbol.asClass) ||
-            isClassDetermined(X, tpe)(ctx.fresh.setNewTyperState()) ||
-            isClassDetermined(stripTypeParam(X), tpe)(ctx.fresh.setNewTyperState())
+            // first try without striping type parameters for performance
+            isClassDetermined(X, tpe)(ctx.fresh.setNewTyperState().setFreshGADTBounds) ||
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:150]: Instead of `setNewTyperState` you should be able to use `setExploreTyperState`: this is a less expensive version which assumes the typerstate will never be committed.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:150]: Also, since all calls to `isClassDetermined` need to use a fresh typer state, I recommend moving that logic inside `isClassDetermined` itself.

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:150]: > The case for non-class type constructors is tested in the case TypeProxy, where we assume it cannot be checked at runtime.

Ah I see, but this is incomplete: it doesn't handle situation where a type lambda is directly applied (or appears behind an alias):
```scala
trait A[T]
trait B[T] extends A[T]

object Test {
  def foo(x: ([X] =>> A[X])[Any]) = x match {
    case x: ([X] =>> B[X])[Any] =>
    case _ =>
  }
}
```

[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: Yes, we haven't seen use cases like this (though the example above type checks). When valid use cases emerge we can easily support them using the method `typeArgsTrivial`.
