### PR TITLE
Don't reduce inline matches, when a guard cannot be checked at compile time

### LINKED ISSUE #13570: Problem with conditionals in inline matches
## Compiler version

3.02 and 3.1.0-RC1

## Minimized code

```Scala
object Fred {
  inline def jim(seq:Seq[Int]) = {
    inline seq match { // If this is not inline, this code works as expected, with the inline it fails as below
      case s:Seq[Int] if s.isEmpty => println("seq is empty")
      case s:Seq[Int] => println("seq is not empty")
      case _ => println("somthing hinky happened")
      }
    }
  def main(args:Array[String]):Unit = {
    Fred.jim(Seq())
    Fred.jim(Seq(1,2))
    }
  }
```

## Output

seq is not empty
seq is not empty

## Expectation

seq is empty
seq is not empty

## Discussion

I am unsure whether the compiler is supposed to be able to evaluate this kind of match at compile time (which is after all when an inline match in an inline def is evaluated), so either the compiler should reject this as something that can only be be done in a runtime (i.e. non-inline) match, or it should produce the expected result.

If the inline on the match is removed, this code works as expected.

### PR DESCRIPTION
**Pull request by KacperFKorban**
fixes #13570

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -1442,21 +1447,33 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
         val gadtCtx = ctx.fresh.setFreshGADTBounds.addMode(Mode.GadtConstraintInference)
         if (reducePattern(caseBindingMap, scrutineeSym.termRef, cdef.pat)(using gadtCtx)) {
           val (caseBindings, from, to) = substBindings(caseBindingMap.toList, mutable.ListBuffer(), Nil, Nil)
+          val typedGuard = typer.typed(cdef.guard.subst(from, to), defn.BooleanType)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:1450]: We should avoid type checking this if `cdef.guard.isEmpty`

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1450]: You could use somthing like this instead
```scala
val (guardOK, canReduceGuard) = 
  if cdef.guard.isEmpty then (true, true)
  else typer.typed(cdef.guard.subst(from, to), defn.BooleanType) match {
    case ConstantValue(v: Boolean) => (v, true)
    case _ => (false, false)
  }
```

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 1 above)
Comment (KacperFKorban) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: ok, done

**Review by nicolasstucki — APPROVED** [review]
