### PR TITLE
Fix #25555: Preserve singleton precision during scoverage lifting

### LINKED ISSUE #25555: Coverage instrumentation widens singleton types during argument lifting, causing Ycheck failure
## Compiler version

`3.8.3-RC2`; latest `main` commit hash `61c882bc3796faeb6af649561212f82f322f1f5f` as of 18th March 2026.

## Minimized code

```scala
// Reproduction.scala

object Ops {
  final val PUBLIC = 1
  final val STATIC = 8
}

object Minimal {
  final val PublicStatic =
    Ops.PUBLIC | (Ops.STATIC + 0)
}

object MinimalJavaReflect {
  final val PublicStatic =
    java.lang.reflect.Modifier.PUBLIC | java.lang.reflect.Modifier.STATIC
}
```

Compile with Scoverage and Ycheck:

```
scalac -coverage-out out -Ycheck:instrumentCoverage Reproduction.scala
```

## Output

```scala
*** error while checking /Users/anatolii/Projects/scala3/.ctxlayer/scoverage/test-surface/data/genbcodeops-int-singleton-repro/Minimal.scala after phase instrumentCoverage ***

  unhandled exception while running Ycheck on /Users/anatolii/Projects/scala3/.ctxlayer/scoverage/test-surface/data/genbcodeops-int-singleton-repro/Minimal.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: /Users/anatolii/Projects/scala3/.ctxlayer/scoverage/test-surface/data/genbcodeops-int-singleton-repro/Minimal.scala
        during phase: Ycheck
                mode: Mode(ImplicitsEnabled)
     library version: version 3.8.4-RC1-bin-SNAPSHOT-nonbootstrapped
    compiler version: version 3.8.4-RC1-bin-SNAPSHOT-nonbootstrapped-git-61c882b
            settings: -Ycheck List(instrumentCoverage) -classpath /Users/anatolii/Projects/scala3/library/target/scala-library-nonbootstrapped/scala-library-3.8.4-RC1-bin-SNAPSHOT-nonbootstrapped.jar -coverage-out /Users/anatolii/Projects/scala3/.ctxlayer/scoverage/test-surface/data/genbcodeops-int-singleton-repro/coverage-out -d /Users/anatolii/Projects/scala3/out/default-last-scalac-out.jar

Exception in thread "main" java.lang.AssertionError: assertion failed: Type Mismatch (while checking adapt):
Found:    Int
Required: (9 : Int)
I tried to show that
  Int
conforms to
  (9 : Int)
but none of the attempts shown below succeeded:

  ==> Int  <:  (9 : Int)  = false

The tests were made under the empty constraint
tree = Ops.PUBLIC | x$1 Apply
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:10)
        at dotty.tools.dotc.transform.TreeChecker$Checker.checkType(TreeChecker.scala:827)
        at dotty.tools.dotc.transform.TreeChecker$Checker.adapt(TreeChecker.scala:815)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:4017)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:4022)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:417)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:4134)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1553)
```

## Expectation

Should compile

## Notes

Two independent objects are included in the reproduction, both reproducing the issue.
Discovered when attempting to enable scoverage on the compiler itself.

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
Fixes #25555:

- Preserve type precision when lifting `ConstantType`s for Scoverage.
- Use inheritance to limit the above change to the typing logic to only affect the Scoverage lifting and not general lifting done by `EtaExpansion.scala`.

## How much have your relied on LLM-based tools in this contribution?

Moderately

## How was the solution tested?

- Tests included in the PR pass locally
- Full `pos` and coverage tests suite pass locally

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
@Gedochao this one is ready for review now!

File: compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala [hunk 1]
```diff
@@ -213,6 +217,16 @@ object LiftCoverage extends LiftImpure {
   override def noLift(expr: tpd.Tree)(using Context) =
     if liftingArgs then noLiftArg(expr) else super.noLift(expr)
 
+  /** Preserve singleton precision for lifted coverage temps when the underlying value is a
+   *  compile-time constant (same notion ConstFold uses), so constant re-folding after lifting
+   *  still matches the original inferred singleton type. Everything else uses the base widen.
+   */
+  override protected def liftedExprType(expr: tpd.Tree)(using Context): Type =
+    val dealiased = expr.tpe.dealias.deskolemized
+    dealiased.widenTermRefExpr.normalized.simplified match
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala:226]: this line should be kept in a museum with the caption "why singleton types are hard to integrate into a type system in a user-friendly way"

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala:226]: Thank you for the review @SolalPirelli ! If there's no other remarks, can we merge it? I don't have a write access to the repo, so would need someone to merge it :)

Comment (Gedochao) [reply compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala:226]: let me do the honors then
