### PR TITLE
Fix NoSuchElementException in scaladoc

### LINKED ISSUE #18143: Nightly Dotty workflow of 2023-07-05 failed
See https://github.com/lampepfl/dotty/actions/runs/5460101159

### PR DESCRIPTION
**Pull request by Florian3k**
This should fix the error causing recent fails of Nightly Dotty workflow.
However, I don't know why it fails so randomly. We might want to investigate and fix this properly.

Fixes #18143

### CODE REVIEW

File: scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/SectionRenderingExtension.scala [hunk 1]
```diff
@@ -33,7 +33,7 @@ object SectionRenderingExtension extends HtmlRenderer.HtmlRendererExtension:
       val Section(header, body) = node
       val idSuffix = repeatedIds.getOrElseUpdate((c, header.getText), 0)
       val ifSuffixStr = if(idSuffix == 0) then "" else idSuffix.toString
-      repeatedIds.update((c, header.getText), repeatedIds((c, header.getText)) + 1)
+      repeatedIds.update((c, header.getText), idSuffix + 1)
```
Comment (nicolasstucki) [inline scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/SectionRenderingExtension.scala:36]: Those the result of `header.getText` have a stable hash?

Comment (Florian3k) [reply scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/SectionRenderingExtension.scala]: I think it should, but just to be extra safe I extracted that in the next commit

**Review by nicolasstucki — APPROVED** [review]
