### PR TITLE
Fix #5980

### LINKED ISSUE #5980: Buggy or undocumented behavior concerning subtyping relationships with unions, intersections and variance
Not sure if it is a bug or an unintuitive/undocumented behavior.

```scala
trait A
trait B

trait Covariant[F[+_]] {
  trait G[+X]

  def fx: F[A  &   B] = ???  // fy: Type Mismatch Error
  def fy: F[A] & F[B] = fx

  def gx: G[A  &   B] = gy
  def gy: G[A] & G[B] = gx
}
```

Above, `fx = fy` gives a type mismatch error. However, `gx = gy` does not. My guess is, in case of `fx = fy`, the only fact the compiler knows about `F` is that it is covariant. According to the covariance laws, `fx = fy` is illegal. However, in case of `gx = gy`, the compiler knows the actual type `G`. It hence can compute what exactly members should `G[A & B]` and `G[A] & G[B]` have, and see that these members are identical, and hence allow for `gx = gy`.

However, this logic does not stand the contravariance test:

```scala
trait Contravariant[F[-_]] {
  trait G[-X]

  def fx: F[A  &   B] = fy  
  def fy: F[A] | F[B] = ??? // fx: Type Mismatch Error

  def gx: G[A  &   B] = gy
  def gy: G[A] | G[B] = ??? // gx: Type Mismatch Error
}
```

Here, `fy = fx` is illegal according to contravariance laws, and the fact that `F` is contravariant is the only thing the compiler knows about `F`. However, if the `Covariant` example reasoning above is correct, then the compiler will take into account the information available about the concrete `G` trait. Following the covariant example logic, in case of `gy = gx`, the compiler should be able to compute that `G[A] | G[B]` type has the same members as `G[A & B]`. And, if `gx = gy` is allowed for the covariant case, following the same logic, `gy = gx` should be allowed for the contravariant case. However, this does not happen, and the compiler appears to be guided only by the contravariance laws, ignoring this time the distinction between the type parameters and traits.

A similar case makes its appearance in the documentation on [intersection types](http://dotty.epfl.ch/docs/reference/new-types/intersection-types.html), precisely, the snippet of:

```scala
val x: A & B = new C
val ys: List[A & B] = x.children
```

There, the documentation says:

> The type of `children` in `A & B` is the intersection of `children`'s type in `A` and its type in `B`, which is `List[A] & List[B]`. This can be further simplified to `List[A & B]` because List is covariant.

The simplification can indeed be done when defining `C`, so that the `children` method returns `List[A & B]`, because `List[A & B] <: List[A] & List[B]`. However, what exactly happens in case of `val ys: List[A & B] = x.children`?

```scala
val x: A & B = new C
def f(x: C) = ???
f(x)
```

The above fails with

```
[error] 14 |  f(x)
[error]    |    ^
[error]    |    Found:    (A & B)(Official.x)
[error]    |    Required: C
```

So, there is no chance that when doing `val ys: List[A & B] = x.children`, the compiler knows that `x` is of type `C`. The compiler thinks that `x` is of type `A & B`. And what should the type of `children` of `A & B` be? According to the doc on the intersection types:

> If a member appears in both `A` and `B`, its type in `A & B` is the intersection of its type in `A` and its type in `B`. For instance, assume the definitions:

Hence, the type of `children` in `A & B` must be `List[A] & List[B]`, and `List[A] & List[B] >: List[A & B]`. I can't see any reason for the compiler to make the type in question a more special `List[A & B]`.

Hence, the assignment `val ys: List[A & B] = x.children` should not be possible, because `x` is of type `A & B` and `x.children` is inferred to `List[A] & List[B]`, and `List[A & B] <: List[A] & List[B]`. 

One way it can be possible is if the compiler utilizes the information it has about the `List` type and computes that `List[A] & List[B] =:= List[A & B]`. However, this does not appear to be true:

```
[error] 15 |  implicitly[List[A & B] =:= List[A] & List[B]]
[error]    |                                               ^
[error]    |no implicit argument of type List[A & B] =:= List[A] & List[B] was found for parameter ev of method implicitly in object DottyPredef
```

And, if this was the case, then why does it not work with the union type as described above?

So, is it a bug, or is there some logic regarding subtyping rules with covariance/contravariance and unions/intersections that the documentation does not mention?

I tested the above code on dotty 0.13.0-RC1 and 0.14.0-bin-20190222-789269d-NIGHTLY.

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
This is a fix for #5980.

# Motivation
I have not found a proof anywhere that `F[A] & F[B] <:< F[A & B]` for all covariant `F[+_]`. However, this property is featured in tests and docs, and there is a deliberate logic in the sources to distribute type parameters for covariant type constructors.

Also, it seems that the bug originates not really because of the distribution itself but because of inconsistent treatment of how subtyping relationship is inferred for traits and type params. Even if the `F[A] & F[B] <:< F[A & B]` is not true for all types, I think the relationship should be inferred the same way (in the sense elaborated in the Solution section below) for both type params and traits.

# Solution
Consider that we need to compute `F[A] & F[B] <:< F[A & B]`. `F` can be either a type param or a trait (see the issue description above). The `<:<` relationship needs to be computed e.g. when assigning `F[A] & F[B]` to a value of type `F[A & B]`.

The difference between how traits and type params are treated originates at the match inside [compareAppliedType2](https://github.com/lampepfl/dotty/blob/3185338f55ab44bdf5ca1c795e57e477f1cd1456/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L908) of `isSubType` of `TypeComparer`.

`TypeBounds ` handles type params among other things and, via `compareLower`, ultimately leads to the `fourthTry`. In `forthTry`, ultimately the [following](https://github.com/lampepfl/dotty/blob/3185338f55ab44bdf5ca1c795e57e477f1cd1456/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L740) logic is used: "`A & B <: C` is true if either `A <: C` or `B <: C` is true".

In case of ClassInfo, the branch will ultimately lead us to [this](https://github.com/lampepfl/dotty/blob/3185338f55ab44bdf5ca1c795e57e477f1cd1456/compiler/src/dotty/tools/dotc/core/SymDenotations.scala#L1827) line which computes the `&` operation over the two type bounds.

Since the `&` operation sometimes simplifies the types (as in for covariant `F[+_]`, it may distribute type parameters, so that `F[A] & F[B]` becomes `F[A & B]`), the two behaviors (for traits and type bounds) are inconsistent. For traits, the result of the `&` operation will be checked to be a subtype of the target type, and for type params, no such check is performed.

To summarise, when inferring `F[A] & F[B] <:< F[A & B]`, in case if `F` is a class or a trait, the result of the `&` operation on types will be compared to be a subtype of `F[A & B]`. No such check will be performed if `F` is a type param.

This PR adds such a check to the corresponding inference logic.

# Notes on `andType`
## The problem with `&`
`andType` is still not the same as `&`. However, if you plug in `&` instead of `andType` there, Scala 2 library compilation tests will not pass. Precisely, [this](https://github.com/lampepfl/dotty/blob/3185338f55ab44bdf5ca1c795e57e477f1cd1456/tests/scala2-library/src/library/scala/collection/parallel/package.scala#L42) line will cause an infinite loop when inferring a subtype via `isSubType` we have just modified. In a minimised form, the offending example looks like this (also added to the tests):

```scala
object foo {
  trait A[X]
  trait B extends A[B]
  trait Min[+S <: B with A[S]]

  def c: Any = ???
  c match {
    case pc: Min[_] =>
  }
}
```

The loop seems to happen on the `case pc: Min[_] =>` typecheck. When traced which types get compared in turn in `recur` of `TypeComparer` (via `println(s"recCount = ${recCount}; ${tp1.show} <: ${tp2.show}")`), under `-Yno-deep-subtypes` compiler option, the trace is:

```scala
// ...
recCount = 0; foo.Min <: class dotty.tools.dotc.typer.ProtoTypes$AnyTypeConstructorProto$
recCount = 0; Nothing <: Nothing
recCount = 0; foo.B & foo.A[LazyRef(foo.Min[_]#S)] <: Any
recCount = 0; _ <: Nothing
recCount = 1; foo.B & foo.A[LazyRef(foo.Min[_]#S)] <: Nothing
recCount = 2; foo.B <: Nothing
recCount = 2; foo.A[LazyRef(foo.Min[_]#S)] <: Nothing

// The previous two comparisons failed. Since they were made to determine if foo.B & foo.A[LazyRef(foo.Min[_]#S)] and
// since we have modified the logic that determins this condition,
// maybeAndType invoked here in attempt to compute the & operation on
// foo.B and foo.A[LazyRef(foo.Min[_]#S)] types
// As part of this operation, it tries to see if either operand is a subtype of the other
// Hence the traces from here are from within the & operation
recCount = 2; foo.A[LazyRef(foo.Min[_]#S)] <: foo.B

// Start of the loop's period
recCount = 2; foo.B <: foo.A[LazyRef(foo.Min[_]#S)]
recCount = 3; foo.A[foo.B] <: foo.A[LazyRef(foo.Min[_]#S)]
recCount = 4; foo.type(foo) <: foo.type(foo)
recCount = 4; LazyRef(foo.Min[_]#S) <: foo.B
recCount = 5; foo.Min[_]#S <: foo.B
recCount = 6; foo.B & foo.A[LazyRef(foo.Min[_]#S)] <: foo.B
recCount = 7; foo.B <: foo.B
recCount = 4; foo.B <: LazyRef(foo.Min[_]#S)
recCount = 5; foo.B <: foo.Min[_]#S
recCount = 6; foo.B <: foo.B & foo.A[LazyRef(foo.Min[_]#S)]
recCount = 7; foo.B <: foo.B

// End of the loop's period, note how the next trace is the same as the one at the beginning of the loop's period start
// From here, the period will repeat itself
recCount = 7; foo.B <: foo.A[LazyRef(foo.Min[_]#S)]
recCount = 8; foo.A[foo.B] <: foo.A[LazyRef(foo.Min[_]#S)]
recCount = 9; foo.type(foo) <: foo.type(foo)
recCount = 9; LazyRef(foo.Min[_]#S) <: foo.B
recCount = 10; foo.Min[_]#S <: foo.B
recCount = 11; foo.B & foo.A[LazyRef(foo.Min[_]#S)] <: foo.B
recCount = 12; foo.B <: foo.B
recCount = 9; foo.B <: LazyRef(foo.Min[_]#S)
recCount = 10; foo.B <: foo.Min[_]#S
recCount = 11; foo.B <: foo.B & foo.A[LazyRef(foo.Min[_]#S)]
recCount = 12; foo.B <: foo.B
recCount = 12; foo.B <: foo.A[LazyRef(foo.Min[_]#S)]
recCount = 13; foo.A[foo.B] <: foo.A[LazyRef(foo.Min[_]#S)]
recCount = 14; foo.type(foo) <: foo.type(foo)
recCount = 14; LazyRef(foo.Min[_]#S) <: foo.B
```

Basically for some reason at some point `foo.B & foo.A[LazyRef(foo.Min[_]#S)]` (which is the type bounds of `S`) gets compared to `Nothing`. Given that `&` operation on types as part of its workflow checks its operands to be a subtype of one another, we end up with the above periodic situation if we solve the bug with `&`. It seems that type aliases are involved here: `S` is a `TypeAlias`. Normally, the compiler does not allow for things like `type S = B with A[S]` because of cyclic references. However, it seems to allow for such a cyclic reference under the special conditions presented above.

## Why andType does the job
`&` delegates to `glb` computation, and [andType](https://github.com/lampepfl/dotty/blob/3185338f55ab44bdf5ca1c795e57e477f1cd1456/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L1661) basically checks whether it can distribute the type arguments if the two operands are type constructors, falling back to the original `AndType` otherwise. `glb` involves subtyping checks between its two arguments, and `andType` does not. Hence the risk of getting an infinite subtyping check loop is eliminated. This also is enough to make sure the bug in question is solved, since the behavior now is more consistent between traits and type params – more consistent distribution-wise.

# Tests
With the `&` solution, among all the `testCompilation`, only the issue above was encountered. After replacing `&` with `andType` all tests, including the one testing the issue in question, pass. I've also included the tests to describe that weird typecheck looping behavior I encountered, just in case.

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
More thoughts of why `andType` is usable instead of `&` and gives consistency with the behavior in case of traits.

`&` is implemented in terms of `glb`, and `glb` ultimately uses `andType`. `glb` distinguishes the following input cases:

- Cases where `glb` is either of its operands – in the scenario of checking `A & B <: C`, if `A & B` is simplified to either `A` or `B`, it has already been checked at the point where we want to simplify `A & B`. Hence we don't need to do it again.
- Either of the operands is an `OrType` – `OrType`s seem to also be handled in the `fourthTry` in the `AndType(tp11, tp12)` branch, right before the modified snippet.
- Either of the operands is a subtype of another, in which case the result of `glb` seems to be that subtype. So again, `A & B` is simplified to either `A` or `B` which were already handled.
- Both operands are `ConstantType`, in which case return `Nothing`. So `A & B` gets simplified to `Nothing` in this case, which is a subtype of everything. Type bounds don't seem to inherit from `ConstantType`, so in case of type parameters, the semantics stays the same. However, I have doubts on whether the semantics stays the same for all possible cases when neither `A <: C` nor `B <: C` are true – it depends on whether `ConstantType`s can get to the `fourthTry`.
- In all other cases, use `andType`.

So basically in all cases, in case of type parameters, the semantics of `andType` should be the same as `&` when used in type comparison scenario.

However, I'm not completely sure whether it makes for the consistent subtyping behaviour between type params and traits since there's a lot going on there. Would appreciate some feedback on the above logic regarding whether `andType` can be used in place of `&` there without loss of consistency between type params and traits.

**Comment by odersky** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -737,7 +737,12 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
             return recur(AndType(tp11, tp121), tp2) && recur(AndType(tp11, tp122), tp2)
           case _ =>
         }
-        either(recur(tp11, tp2), recur(tp12, tp2))
+
+        def maybeAndType = {
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: `either` by itself is expensive, so it would be good to avoid the extra call. 
Furthermore, `andType(tp11, tp12)` is known to be a subtype of `AndType(tp1, tp2)` and we can exploit that.
Finally, `!=` should not be used for type comparisons, since it is meaningless and potentially expensive. Use
`=:=` for semantic equality or `eq` for syntactic equality.
So how about:
```scala
val tp1norm = andType(tp11, tp12)
if (tp1norm ne tp1) recur(tp1norm, tp2)
else either(recur(tp11, tp2), recur(tp12, tp2))
```

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Ok, though this solution kept failing [run/mixins1/A_1.scala](https://github.com/lampepfl/dotty/blob/master/tests/run/mixins1/A_1.scala) – minimised example:

```scala
trait A[This <: A[This] with B]
trait B extends A[B]
```

At some point, `A[LazyRef(This)] & A[B] ne A[LazyRef(This)] & A[B]` returned `true`. This is due to `LazyRef`, which is uncached. I modified the solution to avoid needless construction of the `AndType` if we already have the equivalent object.

**Comment by odersky** [comment]
Looks good now, thanks!

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -1659,16 +1673,11 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
-    val t1 = distributeAnd(tp1, tp2)
-    if (t1.exists) t1
-    else {
-      val t2 = distributeAnd(tp2, tp1)
-      if (t2.exists) t2
-      else if (isErased) erasedGlb(tp1, tp2, isJava = false)
-      else liftIfHK(tp1, tp2, AndType(_, _), _ & _)
-    }
-  }
+  final def andType(tp1: Type, tp2: Type, isErased: Boolean = ctx.erasedTypes): Type =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: The `isErased` argument is not passed down to `andTypeGen`.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Oops :) updated it

**Comment by smarter** [comment]
Please squash your commits down to a single commit with a nice commit message

**Comment by anatoliykmetyuk** [comment]
Done

**Comment by smarter** [comment]
By "nice commit message" I mean "commit message explaining everything involved so that someone reading it in five years will understand what this change was about" :).

**Comment by anatoliykmetyuk** [comment]
Okay :) Will this do?

**Comment by smarter** [comment]
Looks great!

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -1641,6 +1643,18 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
         NoType
     }
 
+  private[this] def andTypeGen(tp1: Type, tp2: Type, op: (Type, Type) => Type
+    , original: (Type, Type) => Type, isErased: Boolean = ctx.erasedTypes): Type = trace(s"glb(${tp1.show}, ${tp2.show})", subtyping, show = true) {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: it seems `original` is always `_ & _`. Why not inline it?

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I didn't inline it for consistency reasons: if there is a degree of freedom in the `op` parameter to `liftIfHK`, it would IMO be weird if there wouldn't be a degree of freedom in the `original` as well.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: On the second thought, I agree, `_ & _` repeated twice doesn't look nice. I have found a compromise in terms of making the `original` in `andTypeGen` a default parameter.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 4]
```diff
@@ -1641,6 +1643,18 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
         NoType
     }
 
+  private[this] def andTypeGen(tp1: Type, tp2: Type, op: (Type, Type) => Type
+    , original: (Type, Type) => Type = _ & _, isErased: Boolean = ctx.erasedTypes): Type = trace(s"glb(${tp1.show}, ${tp2.show})", subtyping, show = true) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Put commas at the end o lines, not at the beginning.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Ok, updated

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 3 above)
Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I don't understand why this function signature should be consistent with `liftIfHK`. And I don't think having a default parameter is the right way to remove the duplication.

Bonus point: if you inline `original`, you will avoid allocating a lambda most of the time.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: > I don't understand why this function signature should be consistent with `liftIfHK`.

The problem of the control over the execution flow of a program is solved by decoupling the logic from the data. Doing so partially is inconsistent (even if sufficient for the issue in question).

>Bonus point: if you inline original, you will avoid allocating a lambda most of the time.

How?

Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: When calling `andTypeGen`, a lambda is allocated for `original`. But unless `liftIfHK` is called, there is no need to allocate this lambda.

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Does it have to do with the fact that `andTypeGen` passes the reference along but `liftIfHK` calls it in its body?
