### PR TITLE
Fix generic signatures of generic methods

### LINKED ISSUE #3411: Missing parameter list in JavaGeneric signature
```scala
object Foo {
  def foo[U](a: Int, b: Double)(c: Boolean, d: String)(e: Object): Int = 1
}
```
will generate the signature `public <U> int Foo$.foo(int,double)` which misses all parameters not in the first parameter list.

### PR DESCRIPTION
**Pull request by Duhemm**
We ignored the case where a `MethodType` had another `MethodType` as
result type. This commit fixes the issue by collecting the parameters of
the result type if it is a `MethodType`, recursively.

Fixes #3411

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -239,9 +239,14 @@ object GenericSignatures {
...
         case mtpe: MethodType =>
+          def allParamTypes(mtpe: MethodType): List[Type] =
+            mtpe.resultType match {
+              case restpe: MethodType => mtpe.paramInfos ::: allParamTypes(restpe)
+              case _ => mtpe.paramInfos
+            }
           // phantom method parameters do not make it to the bytecode.
-          val params = mtpe.paramInfos.filterNot(_.isPhantom)
-          val restpe = mtpe.resultType
+          val params = allParamTypes(mtpe).filterNot(_.isPhantom)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: `.paramInfoss`

Comment (Duhemm) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: That's much better, thanks.

**Comment by nicolasstucki** [comment]
Btw, the convention for the commit message fixing a bug would be`Fix #3411: Fix generic signatures of generic methods`.
