### PR TITLE
Fix #3340: Always throw when casting to scala.Nothing

### LINKED ISSUE #3340: null asInstance of Nothing not always throwing
In the following code the cast to Nothing does not throw the expected `NullPointerException`
```scala
def f: Unit = {
  val a: Nothing = null.asInstanceOf[Nothing] // No exception
}
```
but it does in 
```scala
def f: Unit = {
  val a: Nothing = null.asInstanceOf[Nothing]
  println(a) // throws here
}
```

```scala
def f: Unit = {
  val a: Int = null.asInstanceOf[Nothing] // throws here
}
```

```scala
def f: Unit = {
  null.asInstanceOf[Nothing] // throws here
}
```
This issue was metioned prevoiusly in #1002.

### LINKED ISSUE #4410: NullPointerException was delayed throw
For the following code, it can run normally: 
```scala
object Main {
  val a = null.asInstanceOf[Nothing]
  def main(args: Array[String]): Unit = {
  }
}
```
But NullPointerException will only be thrown when using a:
```scala 
object Main {
  val a = null.asInstanceOf[Nothing]
  def main(args: Array[String]): Unit = {
    a
  }
}
```
```
sbt:dotty-simple> run
[info] Compiling 1 Scala source to /home/glavo/IdeaProjects/dotty/test/target/scala-0.8/classes ...
[info] Done compiling.
[info] Packaging /home/glavo/IdeaProjects/dotty/test/target/scala-0.8/dotty-simple_0.8-0.1.0.jar ...
[info] Done packaging.
[info] Running Main 
[error] (run-main-6) java.lang.NullPointerException
[error] java.lang.NullPointerException
[error] 	at Main$.a(Main.scala:2)
[error] 	at Main$.main(Main.scala:4)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1172)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1167)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 1 s, completed 2018-4-29 12:40:42
```

I think NullPointerException or ClassCastException should be thrown when the conversion happens

### PR DESCRIPTION
**Pull request by nicolasstucki**
When casting to `Nothing`, rather than relying on the cast to `scala.runtime.Nothing$` to throw a `ClassCastException` we evaluate the qualifier and then thorw. This makes sure that the case `null.asInstanceOf[Nothing]` (i.e. `null.asInstanceOf[scala.runtime.Nothing$]` in bytecode) does not succeed.

Also fix #4410.

This fix also aligns with Scala.js https://github.com/lampepfl/dotty/pull/1002#issuecomment-168642220

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 1]
```diff
@@ -244,6 +244,13 @@ object TypeTestsCasts {
           else if (isDerivedValueClass(testCls)) {
             expr // adaptToType in Erasure will do the necessary type adaptation
           }
+          else if (testCls eq defn.NothingClass) {
+            // In the JVM `x.asInstanceOf[Nothing]` would throw a class cast exception except when `x eq null`.
+            // To avoid this loophole we execute `x` and then regardless of the result throw a `ClassCastException`
```
Comment (OlivierBlanvillain) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: For completeness I would add a test where x is a side effect

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: Added
