### PR TITLE
Fix #6783: Check all owner to detect if inside an `inline` method

### LINKED ISSUE #6783: Spurious/inaccurate error messages when quoting
## minimized code

```Scala
  def testImpl(f: (Expr[Int], Expr[Int]) => Expr[Int]): Expr[Int] = f('{1}, '{2})

  inline def test(f: (Int, Int) => Int) = ${
    testImpl((a: Expr[Int], b: Expr[Int]) =>  '{ f(${a}, ${b}) }) // error: splice outside quotes
  }

  test((a, b) => a + b)
```

```Scala
  def testImpl(f: Expr[(Int, Int) => Int]): Expr[Int] = f('{1}, '{2})

  inline def test(f: (Int, Int) => Int) = ${
    testImpl('f)
  } // malformed macro

  test((a, b) => a + b)
```
## expectation

I think the first one has an inaccurate error message while the second should have passed. @nicolasstucki WDYT?

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2082,7 +2082,7 @@ class Typer extends Namer
   }
 
   private def checkSpliceOutsideQuote(tree: untpd.Tree)(implicit ctx: Context): Unit = {
-    if (level == 0 && !ctx.owner.isInlineMethod)
+    if (level == 0 && !ctx.owner.ownersIterator.exists(_.is(Inline)))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: What if the following code?

```Scala
inline def foo() = {
  class A {
    def bar = $(...)
  }
}
```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: It will fall back to error message of the macro body checking .

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Those checks are performed by the `Splicer`
