### PR TITLE
Fix #5021: Remove duplicate test

### LINKED ISSUE #5021: Bootstrapped builds fail sporadically since Java 9 merge
Bootstrap started failing (sporadically) since #3138 was merged with FileAlreadyExistsException http://dotty-ci.epfl.ch/lampepfl/dotty/7060/5, and this affects PR validation (e.g. http://dotty-ci.epfl.ch/lampepfl/dotty/7075/5).

/cc @smarter @allanrenucci:

```
java.nio.file.FileAlreadyExistsException: /tmp/2/out/compilePosWithCompiler/core/dotty/tools/dotc/core/Denotations$StaleSymbol.class
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at dotty.tools.io.AbstractFile.fileOrSubdirectoryNamed(AbstractFile.scala:242)
	at dotty.tools.io.AbstractFile.fileNamed(AbstractFile.scala:253)
	at scala.tools.nsc.backend.jvm.BytecodeWriters.getFile(BytecodeWriters.scala:35)
	at scala.tools.nsc.backend.jvm.BCodeHelpers.getFileForClassfile(BCodeHelpers.scala:38)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.liftedTree1$1(GenBCode.scala:254)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.$anonfun$3(GenBCode.scala:259)
	at scala.collection.immutable.List.map(List.scala:287)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:261)
	at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:179)
	at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:417)
	at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:383)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:53)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:299)
```

### PR DESCRIPTION
**Pull request by allanrenucci**
These tests may be run in parallel in the same group, and compile the
same files at the same time which caused non deterministic issues.

### CODE REVIEW

File: compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala [hunk 1]
```diff
@@ -43,8 +43,7 @@ class BootstrappedOnlyCompilationTests extends ParallelTesting {
     compileDir("compiler/src/dotty/tools/dotc/reporting", withCompilerOptions) +
     compileDir("compiler/src/dotty/tools/dotc/typer", withCompilerOptions) +
     compileDir("compiler/src/dotty/tools/dotc/util", withCompilerOptions) +
-    compileDir("compiler/src/dotty/tools/io", withCompilerOptions) +
-    compileDir("compiler/src/dotty/tools/dotc/core", withCompilerOptions)
```
Comment (allanrenucci) [inline compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala]: This one is a duplicate of line 39

**Comment by Blaisorblade** [comment]
Thanks!!!
