### PR TITLE
Fix #6705: Improve adaptation of overloaded terms

### LINKED ISSUE #6705: Incorrect overloading resolution involving parameterless method
This is encountered when working with ScalaTest test set.

## minimized code

```Scala
trait StringTempl {
  def mkString: String
  def mkString(x: String): String
}


object Test {
  def (x: String) shouldBe(y: String): Boolean = ???

  def test(tmpl: StringTempl): Unit = {
    tmpl.mkString shouldBe "hello"                       // error
    tmpl.mkString(", world") shouldBe "hello, world"
  }
}
```

The compiler reports an error:

```Scala
-- [E134] Type Mismatch Error: examples/apply.scala:11:9 -----------------------
11 |    tmpl.mkString shouldBe "hello"
   |    ^^^^^^^^^^^^^
   |None of the overloaded alternatives of method mkString in trait StringTempl with types
   | (x: String): String
   | => String
   |match expected type ?{ shouldBe: ? }
```

## expectation

The compiler should accept the code without reporting an error.

### PR DESCRIPTION
**Pull request by odersky**
If a term is overloaded and the expected type is not an application,
prefer the parameterless alternative.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2421,18 +2421,26 @@ class Typer extends Namer
         case alt :: Nil =>
           readaptSimplified(tree.withType(alt))
         case Nil =>
+          // If alternative matches, there are still two ways to recover:
+          //  1. If context is an application, try to insert and apply or implicit
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
          //  1. If context is an application, try to insert an apply or implicit
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -2421,18 +2421,26 @@ class Typer extends Namer
...
             case _ =>
-              if (altDenots exists (_.info.paramInfoss == ListOfNil))
-                typed(untpd.Apply(untpd.TypedSplice(tree), Nil), pt, locked)
-              else
-                noMatches
+              alts.filter(_.info.isParameterless) match {
+                case alt :: Nil => readaptSimplified(tree.withType(alt))
+                case _ =>
+                  if (altDenots exists (_.info.paramInfoss == ListOfNil))
+                    typed(untpd.Apply(untpd.TypedSplice(tree), Nil), pt, locked)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Any reason we couldn't also do `readaptSimplified(tree.withType(alt))` here ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: We to add a `()` argument here, so the term changes.
