### PR TITLE
fix: correctly require a `ClassTag` when building a multidimensional `Array`

### LINKED ISSUE #23901: Wrong code emitted when creating generic multidimensional arrays
## Compiler version

https://github.com/scala/scala3/commit/c4c48e3efe6de5109945c10b995d3cd838da780f

## Minimized code

```scala
object MyArray:
  def ofDim[T](n: Int): Array[Array[T]] = new Array[Array[T]](n)
```

## Output

```scala
[[syntax trees at end of MegaPhase{pruneErasedDefs, uninitialized, inlinePatterns, vcInlineMethods, seqLiterals, intercepted, getters, specializeFunctions, specializeTuples, collectNullableFields, elimOuterSelect, resolveSuper, functionXXLForwarders, paramForwarding, genericTuples, letOverApply, arrayConstructors}]] // tests/run/hamza.scala
package <empty> {
  import scala.reflect.ClassTag
  final lazy module val MyArray: MyArray = new MyArray()
  @SourceFile("tests/run/hamza.scala") final module class MyArray() extends
    Object() {
    private def writeReplace(): AnyRef =
      new scala.runtime.ModuleSerializationProxy(classOf[MyArray.type])
    def ofDim[T](n: Int)(using evidence$1: scala.reflect.ClassTag[T]):
      Array[Array[T]] =
      scala.runtime.Arrays.newArray[Array[Array[T]]](classOf[Array[T]],
        classOf[Array[Array[T]]], [n : Int])
  }
}
```

## Expectation
Require the evidence that `T` has a `ClassTag` and use that evidence in `scala.runtime.Arrays.newArray` instead of always building multidimensional arrays of `Object`

### PR DESCRIPTION
**Pull request by hamzaremmal**
Closes #23901

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -1433,7 +1433,7 @@ trait Applications extends Compatibility {
           .select(defn.newGenericArrayMethod).withSpan(tree.span)
           .appliedToTypeTrees(targs).appliedToTermArgs(args)
 
-      if (TypeErasure.isGeneric(targ.tpe))
+      if TypeErasure.isGeneric(targ.tpe) || targ.tpe.derivesFrom(defn.ArrayClass) then
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala]: That seems too broad. What about `Array[Array[Int]]`?

Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: Then we require the `ClassTag` of `Int` to build the `ClassTag` of `Array[Int]`

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: Meh. It might be good to look at the exact condition that Scala 2 uses. Supposedly that one has been ironed out for years.

Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: Scala 2 tries to identify specific `Array^N[T]`. We could port that code here.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: Yes, that seems like the right thing to do.

File: compiler/src/dotty/tools/dotc/core/TypeErasure.scala [hunk 2]
```diff
@@ -386,6 +386,12 @@ object TypeErasure {
     case _ => false
   }
 
+  /** Is `tp` of the form `Array^N[T]` where T is generic? */
+  def isGenericArray(tp: Type)(using Context): Boolean = tp.dealias match
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/core/TypeErasure.scala]: NOTE: The call to `dealias` here is not really necessary since `def.ArrayOf.unapply` and `isGeneric` will always dealias before.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/core/TypeErasure.scala]: The name of this function is misleading. It also returns `true` for `T`, but its name implies it will only return `true` for `Array[T]`, `Array[Array[T]]`, etc.

Consider
```suggestion
  def isGenericArrayArg(tp: Type)(using Context): Boolean = tp.dealias match
```

File: tests/run/i23901.scala [hunk 3]
```diff
@@ -0,0 +1,8 @@
+import scala.reflect.ClassTag
+
+object MyArray:
+  def empty[T: ClassTag]: Array[Array[T]] = new Array[Array[T]](0)
+
+@main def Test =
+  val arr: Array[Array[String]] = MyArray.empty[String]
+  assert(arr.length == 0)
```
Comment (bishabosha) [inline tests/run/i23901.scala:8]: maybe test the runtime class?

Comment (hamzaremmal) [reply tests/run/i23901.scala:8]: What do you mean?

Comment (bishabosha) [reply tests/run/i23901.scala:8]: well to assert that it is specialised based on the classtag

Comment (hamzaremmal) [reply tests/run/i23901.scala:8]: Before this fix, we couldn't even create the array in Line 7, this is a run test witnessing that we are indeed creating the array correctly. Also, dotty will add a call to `asInstanceOf[Array[Array[String]]]` here which is enough to assert that the right array is created. Also note that `asInstanceOf` was what indicated that something was really wrong it the generated code.
