### PR TITLE
test: add in a regression test for #11706

### LINKED ISSUE #11706: Unable to call recursive private inline method defined in a trait
## Compiler version

3.0.0

## Minimized code

```Scala
package bugreport

import scala.compiletime.erasedValue

object Obj:
  
  inline def length[Tuple]: Int = loop[Tuple]

  private inline def loop[Tuple]: Int =
    inline erasedValue[Tuple] match
      case _: EmptyTuple => 0
      case _: (head *: tail) => 1 + loop[tail]

end Obj

// Same code, but in a trait instead of an object
trait Trait:

  inline def length[Tuple]: Int = loop[Tuple]

  private inline final def loop[Tuple]: Int =
    inline erasedValue[Tuple] match
      case _: EmptyTuple => 0
      case _: (head *: tail) => 1 + loop[tail]

end Trait

@main def run() =
  println(Obj.length[(Int, Int, String)]) // OK
  new Trait:
    println(length[(Int, Int, String)]) // ERROR
```

## Output

```text
[error] -- Error: bugreport.scala:18:38 
[error] 18 |  inline def length[Tuple]: Int = loop[Tuple]
[error]    |                                  ^^^^^^^^^^^
[error]    |undefined: Trait_this.loop # -1: TermRef(TermRef(NoPrefix,val Trait_this),loop) at inlining
```

When I call the variant in the trait, I get this error. But the same code works fine with an object.

## Expectation

Both versions work.

### PR DESCRIPTION
**Pull request by ckipp01**
[skip community_build]

closes #11706

### CODE REVIEW

File: tests/run/i11706.scala [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    inline erasedValue[Tuple] match
+      case _: EmptyTuple     => 0
+      case _: (head *: tail) => 1 + loop[tail]
+
+end Trait
+
+@main def Test() =
+  println(Obj.length[(Int, Int, String)]) // OK
+  new Trait:
+    println(length[(Int, Int, String)]) // ERROR
```
Comment (nicolasstucki) [inline tests/run/i11706.scala:30]:
```suggestion
    println(length[(Int, Int, String)])
```

**Review by nicolasstucki — APPROVED** [review]
