### PR TITLE
Fix #7401: Refine overloading resolution

### LINKED ISSUE #7401: Error with parameterless extension method overload resolution
## minimized code

```Scala
object Test {
  given (a: Int) {
    def foo(i: Int): Unit = ()
    def foo: Unit = ()
  }
  val x: Int = 5
  x.foo(4)
  x.foo
}
```

fails with

```scala
11 |  x.foo
   |  ^^^^^
   |  value foo is not a member of Int - did you mean x.+?.
   |  An extension method was tried, but could not be fully constructed:
   |  
   |      Test.given_foo_of_Int.foo(Test.x)
```

## expectation
It should compile and it should generate the same code as
```scala

object Test {
  given (a: Int) {
    def foo(i: Int): Unit = ()
    def foo(): Unit = ()
  }
  val x: Int = 5
  x.foo(4)
  x.foo()
}
```
which does compile.

### PR DESCRIPTION
**Pull request by odersky**
If we are left with several alternatives after normal overloadiong resolution
and the expected result type is not a FunProto, prefer the alternatives
that do not have a method result type. This makes i2378 compile, so it got
moved to a pos test.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -1785,28 +1785,42 @@ trait Applications extends Compatibility {
...
+        case pt @ FunProto(_, resType: FunProto) =>
+          // try to narrow further with snd argument list
+          val advanced = advanceCandidates(pt.typedArgs().tpes)
+          resolveOverloaded(advanced.map(_._1), resType, Nil) // resolve with candidates where first params are stripped
+            .map(advanced.toMap) // map surviving result(s) back to original candidates
+        case _ =>
+          // prefer alternatives that need no eta expansion
+          val noCurried = alts.filter(!resultIsMethod(_))
+          val noCurriedCount = noCurried.length
+          if noCurried.length == 1 then
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala]: As pointed out by @michelou ,  we can just use `noCurriedCount ` instead of `noCurried.length `.

Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala]:
```suggestion
          if noCurriedCount == 1 then
```
