### PR TITLE
Fix #2677: Several fixes involving super selection

### LINKED ISSUE #2677: Super-call in intersection type not type safe
Consider:
```scala
> trait A { def x = "foo" }
> trait B { def x = 42 }
> val AB = new A with B { override def x = super.x }
> AB.x
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```

I would expect the overriding method to be rejected, since it has type `String` and it is expected to be `Int & String`.

### PR DESCRIPTION
**Pull request by odersky**
This was much harder than I thought. In the end, there are several fixes that interact in interesting ways with each other.

 1. We fix the way baseclasses are computed in AndTypes.
 2. We fix the way members of supertypes are computed.
 3. We keep the order of operands of a `&` invariant. 

The problems in (1) and (3) conspired to cancel each other out. So once I fixed (1) the problem caused by (3) became apparent, but in a very indirect way. Details are in the commit message of
0f708eb.

### CODE REVIEW

**Comment by OlivierBlanvillain** [comment]
Failure reproduced with `sbt dotty-bootstrapped/vulpix t1751`

**Comment by odersky** [comment]
The problem is we need to know in what order the files for `dotc` itself were compiled. Unfortunately it's that order that makes a difference between a compiler that works and a compiler that crashes. Can you pull that out of the logs on your machine?

File: tests/pos/Orderings.scala [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+  }
+
+  def isLess[T]: T => T => implicit Ord[T] => Boolean =
+    x => y => implicitly[Ord[T]].less(x, y)
+}
+class Misc {
+  class Context
+  implicit val ctx: Context
+
+  f(2)               // OK
```
Comment (smarter) [inline tests/pos/Orderings.scala]: The definition of `f` appears to be missing from this test.

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -2307,6 +2300,37 @@ object Types {
...
+          case bc2 :: bcs2rest =>
+            if (isAnd)
+              if (bcs1set contains bc2)
+                if (bc2.is(Trait)) recur(bcs2rest)
+                else bcs1 // common class, therefore rest is the same in both sequences
+              else bc2 :: recur(bcs2rest)
+            else
+              if (bcs1set contains bc2)
+                if (bc2.is(Trait)) bc2 :: recur(bcs2rest)
+                else bcs2rest
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: Shouldn't this be `bcs2` ? Otherwise we miss `bc2` even though it's contained in the baseclasses of both operands

Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: Good catch!
