### PR TITLE
Fix #1868: Fix a logic error in a match

### LINKED ISSUE #1868: Crash when annotating type parameter of inner method
scalac compiles but dotc crashes.

$ cat abc.scala
```scala
class Test {
  def outer: Unit = {
    def inner[@specialized T]() = {}
  }
}
```
$ dotc abc.scala
```
exception occurred while typechecking abc.scala

exception occurred while compiling abc.scala
Exception in thread "main" scala.MatchError: Some(val <local Test>) (of class scala.Some)
	at dotty.tools.dotc.typer.Typer.annotCtx$lzycompute$1(Typer.scala:1147)
	at dotty.tools.dotc.typer.Typer.dotty$tools$dotc$typer$Typer$$annotCtx$1(Typer.scala:1145)
	at dotty.tools.dotc.typer.Typer$$anonfun$completeAnnotations$2.apply(Typer.scala:1157)
	at dotty.tools.dotc.typer.Typer$$anonfun$completeAnnotations$2.apply(Typer.scala:1157)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at dotty.tools.dotc.typer.Typer.completeAnnotations(Typer.scala:1157)
<...>
```

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1150,7 +1150,7 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
           // classes defined in a such arguments should not be entered into the
           // enclosing class.
           c.exprContext(mdef, exprOwner)
-        case None => c
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: This is a perfect example of why we shouldn't turn off exhaustiveness warnings when guards are used ;) (cf: https://github.com/scala/scala/pull/5617)

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -1150,7 +1150,7 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
           // classes defined in a such arguments should not be entered into the
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: while you're at it, you could fix the typo here: "in a such" -> "in such"

**Comment by odersky** [comment]
The other PR got merged, so this one can go in as well.
