### PR TITLE
Fix #9911: Remove Override flag from varargs forwarder when there is no forwarder to override

### LINKED ISSUE #9911: Adding varargs on override method fails to compile
## Minimized code

```Scala
import scala.annotation.varargs

trait A {
  def bla(as: String*): Unit
}

object B extends A {
  @varargs
  override def bla(a: String*) = ()
}
```

## Output

```sh
sbt:dotty-simple> compile
[info] Compiling 1 Scala source to /Users/Jens/Developer/chapter/dotty/chapter/target/scala-0.27/classes ...
[error] -- [E037] Declaration Error: /Users/Jens/Developer/chapter/dotty/chapter/src/main/scala/Varargs.scala:7:7 
[error] 7 |object B extends A {
[error]   |       ^
[error]   |       method bla overrides nothing
[error] one error found

```

## Expectation

This compiles in scala 2.13, dotty 0.25, but breaks with dotty 0.26+. 

Adding the `@varargs` also to the trait method does solve the issue.

### PR DESCRIPTION
**Pull request by TheElectronWill**
When the method overrides something but the forwarder doesn't, it is wrong to mark the latter as `Override` in all cases. This PR removes the flag when necessary.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 1]
```diff
@@ -266,7 +267,7 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
    *  The solution is to add a method that converts its argument from `Array[? <: T]` to `Seq[T]` and
    *  forwards it to the original method.
    */
-  private def addVarArgsForwarder(original: Symbol, isBridge: Boolean, hasAnnotation: Boolean)(using Context): Unit =
+  private def addVarArgsForwarder(original: Symbol, isBridge: Boolean, hasAnnotation: Boolean, parentHasAnnotation: Boolean)(using Context): Unit =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:270]: Can you add a description for this parameter to the documentation comment above? (looks like hasAnnotation is also missing doc)

**Review by smarter — APPROVED** [review]
Thanks!

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala (hunk 1 above)
Comment (TheElectronWill) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:272]: done!
