### PR TITLE
Inferred Contextual params are less nameable

### LINKED ISSUE #24375: Context function parameter name leaks into scope
@Sporarum mentioned this in https://users.scala-lang.org/t/using-context-function-parameter-by-name-and-not-by-type/10658.

## Compiler version

3.4..3.7.3

## Minimized code

```scala
def foo(f: (x: Int) ?=> Int) = f(using 0)
@main def Main = println(foo(x))
```

## Output

Compiles successfully, with `x` referring to the argument of the context function:

```scala
$ scala -S 3.4 ../test.scala
Compiling project (Scala 3.4.3, JVM (17))
Compiled project (Scala 3.4.3, JVM (17))
0
```

## Expectation

`x` should be not found, as in `< 3.4`:

```scala
$ scala -S 3.3 ../test.scala
Compiling project (Scala 3.3.7, JVM (17))
[error] /localhome/bovel/test.scala:2:30
[error] Not found: x
[error] @main def Main = println(foo(x))
[error]                              ^
Error compiling project (Scala 3.3.7, JVM (17))
Compilation failed
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #24375

The original name can be recovered for messages.

### CODE REVIEW

**Comment by som-snytt** [comment]
Just a stop-gap update. I will revisit the parameter disambiguation.

Now it is aware that the written `l` and the inferred `lcontextual$1` are not the same. Or maybe just let it ignore the difference.
```
def withFile[T](op: (l: caps.Capability) ?-> (f: File^{l}) => T): T =
  op(using caps.cap)(new File)

def test =
  withFile: f =>       // error with level checking, was OK under both schemes before
    val o = Service()
    o.file = f
    o.log
```

**Comment by odersky** [comment]
I think @Sporarum's comment on the issue makes sense.

File: compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala [hunk 1]
```diff
@@ -395,10 +394,17 @@ class PlainPrinter(_ctx: Context) extends Printer {
...
   }
 
-  protected def ParamRefNameString(name: Name): String = nameString(name)
+  protected def ParamRefNameString(name: Name): String =
+    nameString(name)
 
   protected def ParamRefNameString(param: ParamRef): String =
-    ParamRefNameString(param.binder.paramNames(param.paramNum))
+    val name = param.binder.paramNames(param.paramNum)
+    ParamRefNameString:
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala]: Answering @Sporarum's comment on the issue :
https://github.com/scala/scala3/issues/24375#issuecomment-3521974501 

Maybe we should work on the toString function for ContectFunctionParamNames instead of intervening here.

**Comment by som-snytt** [comment]
The `captures` tests start to fail in the presence of `java.lang.IO` because of the constructor proxy shadowing rule.

There are other failing tests on recent JDKs because of the way lambdas are printed, etc.

**Comment by som-snytt** [comment]
Pushed the same "fix" downstack, but I haven't given any thought to what is desirable in a superscript, or whether other kinds would benefit from similar tweaking.
