### PR TITLE
Make erased value type take a TypeRef instead of a ClassSymbol

### LINKED ISSUE #1198: Stale symbol in ErasedValueType
ErasedValueType refers to a class symbol. This symbol can become stale if the ErasedValueType survives as part of a signature into the next run, but the symbol is redefined. To reproduce:

    cd src/dotty/tools/dotc
    scala -Xms1g -Xmx3g dotty.tools.dotc.Bench #runs 2 -d ~/tmp/classes *.scala */*.scala

This will give a stale symbol error on class Position in run 2.

### PR DESCRIPTION
**Pull request by odersky**
To address #1198, we need to avoid putting symbols in ErasedValueTypes.
Fixes #1198.

Review by @VladimirNik.

### CODE REVIEW

**Comment by smarter** [comment]
Wait, how come an `ErasedValueType` ends up existing in multiple runs? They should only exist between `Erasure` and `ElimErasedValueType`

File: src/dotty/tools/dotc/core/TypeErasure.scala [hunk 1]
```diff
@@ -69,17 +69,17 @@ object TypeErasure {
    *  @param   cls               The value class symbol
```
Comment (smarter) [inline src/dotty/tools/dotc/core/TypeErasure.scala]: param doc needs to be updated

**Comment by odersky** [comment]
@smarter 

> Wait, how come an ErasedValueType ends up existing in multiple runs? They should only exist between Erasure and ElimErasedValueType

I believe it's as a result of an InfoTransformer.

**Comment by smarter** [comment]
Should we compile more tests like the `dotty` test with `twice` to catch this kind of bug?

**Comment by VladimirNik** [comment]
LGTM
