### PR TITLE
Fix #2727: Add self type explain to UnboundPlaceholderParameter

### LINKED ISSUE #2727: Self types with underscore
The following code compiles in scala 2.12.2:
```scala
Welcome to Scala 2.12.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.
tr
scala> trait A
defined trait A

scala>

scala> trait B {_:A => }
defined trait B
```

But fails in dotty:

```scala
Welcome to Scala.next (pre-alpha, git-hash: 05aeeb5)  (OpenJDK 64-Bit Server VM, Java 1.8.0_112).
Type in expressions to have them evaluated.
Type :help for more information.
scala> trait A
defined trait A
scala> trait B {_:A =>}
-- [E016] Syntax Error: <console>:1:9 ------------------------------------------
1 |trait B {_:A =>}
  |         ^^^
  |         unbound placeholder parameter; incorrect use of `_`

longer explanation available when compiling with `-explain`
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 1]
```diff
@@ -527,6 +527,17 @@ import ast.tpd
            |but an uninitialized var definition.
            |Only fields can be left uninitialized in this manner; local variables
            |must be initialized.
+           |
+           |Another occurrence for this error is defining a val with self type.
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:531]:
```suggestion
           |Another occurrence for this error is self type definition.
```

**Review by liufengyun — APPROVED** [review]
LGTM
