### PR TITLE
Fix generic signature for type params bounded by primitive

### LINKED ISSUE #15385: Invalid generic signature for type params bounded by primitive
## Compiler version

3.1.6

## Minimized code

```Scala
def foo[A <: Int]: A = ???
```

## Output

```java
public <A> A foo() {
    throw Predef$.MODULE$.$qmark$qmark$qmark();
}
```

## Expectation
```java
public int foo() {
    throw Predef$.MODULE$.$qmark$qmark$qmark();
}
```

It is important for performance of code dealing with types carrying meta-information like
```scala
type Validated[A] = A
opaque type Max[A, max] <: A with Validated[A] = A
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #15385

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -263,11 +272,11 @@ object GenericSignatures {
           else if (sym == defn.NullClass)
             builder.append("Lscala/runtime/Null$;")
           else if (sym.isPrimitiveValueClass)
-            if (!primitiveOK) jsig(defn.ObjectType)
+            if (!primitiveOK) ()
```
Comment (jan-pieter) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:275]: If you revert this change it will produce valid signatures again.

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 2]
```diff
@@ -5,16 +5,19 @@ package transform
...
 import core.Symbols._
 import core.TypeApplications.{EtaExpansion, TypeParamInfo}
-import core.TypeErasure.{erasedGlb, erasure, isGenericArrayElement}
+import core.TypeErasure.{erasedGlb, erasure, fullErasure, isGenericArrayElement}
 import core.Types._
 import core.classfile.ClassfileConstants
 import SymUtils._
 import TypeUtils._
+import config.Printers.transforms
+import reporting.trace
```
Comment (jan-pieter) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:20]: Imports w.r.t. debugging can be dropped

File: tests/generic-java-signatures/i15385/Lib.scala [hunk 3]
```diff
@@ -0,0 +1,24 @@
+class Loc(val idx: Int) extends AnyVal
+
+class Foo:
+  def testNoParam[A <: Int]: A = 1.asInstanceOf[A]
+  def testSingleParam[A <: Int](a: A): A = 2.asInstanceOf[A]        // <A:Ljava/lang/Object;>(I)I
```
Comment (jan-pieter) [inline tests/generic-java-signatures/i15385/Lib.scala:5]: Shouldn't we drop the generic signature here entirely? In the end it's just int => int

**Review by jan-pieter — COMMENTED** [review]
@dwijnand Can we now drop the check at https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/backend/jvm/BCodeHelpers.scala#L850-L854 as well?

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 2 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:20]: I'd love to never have to import them, so this is 1 more file that won't have to happen...

File: tests/generic-java-signatures/i15385/Lib.scala (hunk 3 above)
Comment (dwijnand) [reply tests/generic-java-signatures/i15385/Lib.scala:5]: I think it's a matter of taste a this point.  From Java, there's no more link between any passed type argument and the term argument, but maybe there is still a type argument you can provide - so that's why I kept it, as well as it being easier to implement it this way.  Unless we have a real reason to drop it, I think this is good.

**Review by smarter — APPROVED** [review]
