### PR TITLE
Fix #3343: Make baseType work properly with type lambdas

### LINKED ISSUE #3343: Implicit view not found involving an uninstantiated type variable
This fails to compile with Dotty
```scala
class Test {
  implicit def implicitContainer[C[_], T](
    implicit t: C[T] => Traversable[T]): C[T] = ???

  implicitly[List[Char]]
}
```
```scala
-- Error: tests/allan/Test.scala:5:24 ------------------------------------------
5 |  implicitly[List[Char]]
  |                        ^
  |no implicit argument of type scala.collection.immutable.List[Char] found for parameter e of method implicitly in object Predef
```
Note that this compiles:
```scala
class Test {
  implicitly[List[Char] => Traversable[Char]]
}
```

### PR DESCRIPTION
**Pull request by smarter**
Previously,
```scala
    `C[Char]`.baseTypeOf(`Traversable[Char]`)
    where C := `[X] => List[X]`
```
returned `Traversable[ParamRef(A)]` instead of `Traversable[Char]`,
because the substitution was done on the type parameters of the class
symbol instead of the type parameters of the type, these are different
when type lambdas are involved.

### CODE REVIEW

**Comment by odersky** [comment]
I think the real fault is in the condition. We check that the type-symbol refers a ClassDenotation. The idea was that this should ensure that the type constructor is a class, but the example shows this is wrong. So I'd try to get the condition right instead. One candidate is what use use in `substParams`: check that `typeParams` returns a list of `Symbols`. If that's not the case, form the baseType of the superType instead.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -1648,9 +1648,7 @@ object SymDenotations {
             if (subsym eq symbol) tp
             else subsym.denot match {
               case clsd: ClassDenotation =>
-                val tparams = clsd.typeParams
-                if (tparams.hasSameLengthAs(args)) baseTypeOf(tycon).subst(tparams, args)
-                else NoType
+                baseTypeOf(tycon).substTypeParams(tycon, args)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: I think the real fault is the condition. It was meant to check that we have an application of a class instead of a type lambda but failed at that. So I'd fix that first. One candidate is the condition of `substTypeParams`, that the `typeParams` of `subsym` are symbols. If that's the case, proceed as before, if not do a `baseTypeOf(superType)`, again as before.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Makes sense. PR updated.

**Comment by allanrenucci** [comment]
I can confirm it fixes the issue I reported from scalacheck
