### PR TITLE
Fix #6314: match type unsoundness

### LINKED ISSUE #6314: Type matches are unsound.
```scala
object G {
    final class X
    final class Y

    opaque type Foo = X & Y
    object Foo {
        def apply[F[_]](fa: F[X & Y]): F[Y & Foo] = fa
    }

    type Bar[A] = A match {
        case X & Y => String
        case Y => Int
    }

    def main(args: Array[String]): Unit = {
        val a: Bar[X & Y] = "hello"
        val i: Bar[Y & Foo] = Foo.apply[Bar](a)
        val b: Int = i
        println(b + 1)
    }
}
```

```scala
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
    at G$.main(test.scala:30)
    at G.main(test.scala)
```

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
This PR fixes several match issues

The first issue was that the algorithm assumes types in an `AndType` always came in the same order, so it wrongly concluded that `X & Y` and `Y & Type` are non intersecting from the fact that `X` and `Y` are non intersecting. The updated logic checks both permutations, and simply get stuck when `Type` is abstract, which fixes the unsoundness.

The second issue is related to the `Singleton`. This marker type needs to be taken it into account by the intersection algorithm, see the added test case.

Finally the previous handling of abstract type was problematic a showed by several of the examples in #6314. The logic is updated to do a sub-type check where all the abstract types (members or parameters) are replace by `WildcardType`. If the scrutinee is not a subtype of a pattern, but it is with wildcards, then the type shouldn't reduce.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -2005,10 +2005,15 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
         intersecting(tp1.tp1, tp2) || intersecting(tp1.tp2, tp2)
       case (_, tp2: OrType)  =>
         intersecting(tp1, tp2.tp1) || intersecting(tp1, tp2.tp2)
+      case (tp1: AndType, tp2: AndType) =>
+        intersecting(tp1.tp1, tp2.tp1) && intersecting(tp1.tp2, tp2.tp2) ||
+        intersecting(tp1.tp1, tp2.tp2) && intersecting(tp1.tp2, tp2.tp1)
       case (tp1: AndType, _) =>
-        intersecting(tp1.tp1, tp2) && intersecting(tp1.tp2, tp2) && intersecting(tp1.tp1, tp1.tp2)
+        intersecting(tp1.tp1, tp2) && intersecting(tp1.tp2, tp2) ||
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: That looks like the same thing is tested twice (???)

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -2005,10 +2005,15 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
+        intersecting(tp1.tp2, tp2) && intersecting(tp1.tp1, tp2)
       case (_, tp2: AndType) =>
-        intersecting(tp1, tp2.tp1) && intersecting(tp1, tp2.tp2) && intersecting(tp2.tp1, tp2.tp2)
+        intersecting(tp1, tp2.tp1) && intersecting(tp1, tp2.tp2) ||
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: same here

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I don't understand the intersecting logic.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Given that you have only certainty for things that do _not_ intersect, would it be better to flip the method and call it `disjoint`? It feels more naturally if unknown is treated as false.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -2152,6 +2152,15 @@ class TrackingTypeComparer(initctx: Context) extends TypeComparer(initctx) {
         case _ =>
           cas
       }
+      def widenAbstractTypes(tp: Type) = new TypeMap {
+        def apply(tp: Type) = tp match {
+          case tp: TypeRef if tp.symbol.isAbstractOrParamType | tp.symbol.isOpaqueAlias => WildcardType
+          case tp: TypeVar if !tp.isInstantiated => WildcardType
+          case _: SkolemType | _: TypeParamRef => WildcardType
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I don't think SkolemTypes need to be mapped to WildcardTypes. It seems good enough to just do a
```
   apply(tp.info)
```
for them.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Also, I think you need to follow alias types. Something like this:
```scala
case tp: TypeRef =>
    tp.info match {
      case TypeAlias(alias) => 
        val alias1 = widenAbstractTypes(alias)
        if (alias1 ne alias) alias1 else tp
      case _: TypeBounds => 
        WildcardType
  }
```
One could also consider mapping to a WildcardType with the underlying bounds widened recursively, but that's more complicated, and might not be necessary.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I renamed the method to `disjoint` and flipped all the logic, I think it's more natural that way!

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 3 above)
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I added the logic to follow aliases. If mapping over `.info` is good enough we can get rid of the `SkolemType` case since that's the default behavior of type maps.
