### PR TITLE
Fix #5551: Handle repl line modules in splicer

### LINKED ISSUE #5551: Is the meta programming allowed in REPL?
I have tried to run an example from the [Principled Meta Programming](https://dotty.epfl.ch/docs/reference/principled-meta-programming.html) doc page.
1. It seems that some import is missing to compile with the `showExpr` call.
2. Even after successful compilation without that call I cannot use the `assert` macro:
```
andriy@notebook:~/Downloads/dotty-0.10.0/bin$ ./dotr
Starting dotty REPL...
scala> import scala.quoted._                                                                                                                                                                                       
     | 
     | inline def assert(expr: => Boolean): Unit =
     |   ~ assertImpl('(expr))
     | 
     | def assertImpl(expr: Expr[Boolean]) =
     |   '{ if !(~expr) then throw new AssertionError("failed assertion")}
def assert(expr: => Boolean): Unit
def assertImpl(expr: quoted.Expr[Boolean]): quoted.Expr[Unit]

scala> assert(0 == 0)
1 |assert(0 == 0)
  |^^^^^^^^^^^^^^
  |Could not find macro class rs$line$1$ in classpath. The most common reason for that is that you apply macros in the compilation run that defines them
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Splicer.scala [hunk 1]
```diff
@@ -113,14 +113,22 @@ object Splicer {
...
     protected def interpretStaticMethodCall(moduleClass: Symbol, fn: Symbol, args: => List[Object])(implicit env: Env): Object = {
-      val instance = loadModule(moduleClass)
+      val (instance, clazz) =
+        if (moduleClass.name.startsWith(str.REPL_SESSION_LINE)) {
+          (null, loadReplLineClass(moduleClass))
+        } else {
+          val instance = loadModule(moduleClass)
+          (instance, instance.getClass)
+        }
+
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/Splicer.scala]: Do we need `instance` in the return? Seems it is not used.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicer.scala]: It is used in the last line of the method. https://github.com/lampepfl/dotty/pull/5688/files/b54e3c586d190fbb02df0e9f5b3b3c13a0c3c5cc#diff-43be0f2f8a9625bb70763569c65a6fdcR132

**Comment by nicolasstucki** [comment]
The issue is that we want to load a macro the is not on the current classpath. The REPL does some magic with the classloader to include the output classpath in the current one. Not sure what else can be done for now. 

In the future, we may be able to have the output directory in the classpath to expand macros defined in the same project. But we need to perform quite a few improvements before that can be performed in a sound way. When this happens we could simply remove the special case for the REPL.
