### PR TITLE
Fix #6460: less forcing in checkNonCyclic

### LINKED ISSUE #6460: Compiler crash in compileIncremental on Dotty project
Steps to reproduce:

 - Start a fresh sbt on the Dotty project (with an empty classpath)
 - clean
 - ~compile
 - Go to Config.scala and edit `final val tracingEnabled = false` to `final val tracingEnabled = true`
 
Here's the log I see:

1. Waiting for source changes in project dotty... (press enter to interrupt)
[info] Compiling 1 Scala source to /Users/odersky/workspace/dotty/compiler/target/scala-0.14/classes ...
[info] Done compiling.
[info] Compiling 2 Scala sources to /Users/odersky/workspace/dotty/compiler/target/scala-0.14/classes ...
[info] Done compiling.
[info] Compiling 22 Scala sources to /Users/odersky/workspace/dotty/compiler/target/scala-0.14/classes ...
dotty.tools.FatalError: 
	at dotty.tools.dotc.typer.ErrorReporting$Errors.takesNoParamsStr(ErrorReporting.scala:84)
	at dotty.tools.dotc.typer.TypeAssigner.fail$2$$anonfun$1(TypeAssigner.scala:394)
	at dotty.tools.dotc.reporting.diagnostic.MessageContainer.contained(MessageContainer.scala:59)
	at dotty.tools.dotc.reporting.diagnostic.MessageContainer.message(MessageContainer.scala:42)
	at dotty.tools.dotc.reporting.diagnostic.MessageContainer.isNonSensical(MessageContainer.scala:71)
	at dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden(HideNonSensicalMessages.scala:17)
	at dotty.tools.dotc.reporting.AbstractReporter.isHidden(AbstractReporter.scala:8)
	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:225)
	at dotty.tools.dotc.reporting.Reporting.error(Reporter.scala:105)
	at dotty.tools.dotc.core.Contexts$Context.error(Contexts.scala:71)
	at dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:26)
	at dotty.tools.dotc.typer.TypeAssigner.fail$1(TypeAssigner.scala:394)
	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:460)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:87)
	at dotty.tools.dotc.ast.tpd$.TypeApply(tpd.scala:51)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1086)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1203)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1083)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1203)

### PR DESCRIPTION
**Pull request by smarter**
checkNonCyclic was forcing too many infos because it didn't account for
the case where the prefix is a ModuleVal and not a ModuleClass. Fixing
this solves the incremental compilation issue in the Dotty build
reported in #6460 were the root cause was a completion cycle when
jointly compiling SymbolLoaders and Types that looked like this:

Complete `object tpd`
 Complete its parent `Trees.Instance`
  Complete its type parameter `T >: Untyped <: Type`
    run `checkNonCyclic` on the the type parameter definition
      Complete `Type`
        Complete `import ast.tpd._` in `Types.scala`
          Eventually this requires unpickling the selection `Trees.Instance#T` which
          gets a `NoDenotation` since `T` hasn't been entered yet.

As a side-effect this also means that the neg/toplevel-cyclic
test no longer leads to an "illegal cyclic reference" error, instead it
now causes "recursion limit exceeded" errors, which are less nice but
still acceptable.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -240,7 +240,7 @@ object Checking {
               )
             case prefix: NamedType =>
               (!sym.is(Private) && prefix.derivesFrom(sym.owner)) ||
-              (!prefix.symbol.isStaticOwner && isInteresting(prefix.prefix))
+              (!prefix.symbol.moduleClass.isStaticOwner && isInteresting(prefix.prefix))
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]: The previous implementation would exclude NamedTypes with prefixes that are static module classes. These are now included. Are we sure that does not present problems? If not, maybe we should keep the old and the new behavior. I.e.
```
var preSym = prefix.symbol
if (preSym.is(ModuleVal)) preSym = preSym.moduleClass
!preSym.isStaticOwner && isInteresting(prefix.prefix)
```

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: Ah indeed, I was expecting `moduleClass` to just return the current denotation if it's already a moduleClass. Do you think it'd be ok to change its definition to behave that way ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: I think that would also be OK. Then do the same for `sourceModule`, for symmetry.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 2]
```diff
@@ -852,13 +852,17 @@ object SymDenotations {
...
+    /** If this a module class, return itself, if this is a module, the corresponding class,
+     *  otherwise NoSymbol
+     */
     final def moduleClass(implicit ctx: Context): Symbol = {
       def notFound = {
       	if (Config.showCompletions) println(s"missing module class for $name: $myInfo")
       	NoSymbol
       }
-      if (this is ModuleVal)
+      if (this is ModuleClass)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: For speed I'd move the operations that return the same symbol towards the end, i.e. where otherwise `NoSymbol` would be returned.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 3]
```diff
@@ -873,20 +877,26 @@ object SymDenotations {
...
-      case ClassInfo(_, _, _, _, selfType) if this is ModuleClass =>
-        def sourceOfSelf(tp: TypeOrSymbol): Symbol = tp match {
-          case tp: TermRef => tp.symbol
-          case tp: Symbol => sourceOfSelf(tp.info)
-          case tp: RefinedType => sourceOfSelf(tp.parent)
+    /** If this a module, return itself, if this is a module class, the corresponding module,
+     *  otherwise NoSymbol
+     */
+    final def sourceModule(implicit ctx: Context): Symbol =
+      if (this is ModuleVal)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Same here.
