### PR TITLE
Fix #2998: Constrain type from above before interpolating variables

### LINKED ISSUE #2997: Special handling in the typer of scala.Singleton is missing
```scala
  case class Foo[T <: Int with Singleton](t : T)
  val one = 1
  final val final_one = 1
  val a : 1 = Foo(1).t //Type Mismatch Error
  val b : Int = Foo(one).t //OK, but unexpected
  val c : 1 = Foo(final_one).t //Type Mismatch Error
```
Scastie link: https://scastie.scala-lang.org/DcDeG4eYQTG17exjb2FigQ

### LINKED ISSUE #2998: When ExprType(T) has expected type Foo, we should add a constraint T <: Foo
Type inference should work the same for `zero` and `one`, but it doesn't, `foo(1).zero` has expected type `1` but this isn't added as a constraint, so we instantiate `T` to `Int` (because the only constraint is `>: 1` and we widen when instantiating a singleton lower bound)

```scala
class Foo[T] {
  def zero: T = ???
  def one(): T = ???
}

object Test {
  def foo[T](x: T): Foo[T] = new Foo

  val a: 1 = foo(1).zero // Fails: Found: Int, required: Int(1)
  val b: 1 = foo(1).one() // OK
}
```

### PR DESCRIPTION
**Pull request by odersky**
When interpolating type variables we should use all available information
at this point, including the expected result type. One situation where this makes
a difference is if the expected type is a singleton type, because type variables
are instantiated to singleton types only if their upper bounds are singleton types.

Also fixes #2997.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
The last commit seemed to have helped performance, so we are good on that count, I think.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 1]
```diff
@@ -375,6 +309,93 @@ object Inferencing {
...
+      constr.println(s"interpolate undet vars in ${tp.show}, pos = ${tree.pos}, mode = ${ctx.mode}, undets = ${constraint.uninstVars map (tvar => s"${tvar.show}@${tvar.bindingTree.pos}")}")
+      constr.println(s"qualifying undet vars: ${constraint.uninstVars filter qualifies map (tvar => s"$tvar / ${tvar.show}")}, constraint: ${constraint.show}")
+
+      val vs = variances(tp, qualifies)
+      val hasUnreportedErrors = ctx.typerState.reporter match {
+        case r: StoreReporter if r.hasErrors => true
+        case _ => false
+      }
+
+      var isConstrained = false
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala]: I think it would be cleaner to do:
```scala
var isConstrained = tree.isInstanceOf[Apply] || tree.tpe.isInstanceOf[MethodOrPoly]
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala]: I saw that comment to late, after merging. I'll attach the change to a subsequent PR.
