### PR TITLE
Sort implicits with a proper comparison function

### LINKED ISSUE #12479: [implicit search] Comparison method violates its general contract!
## Compiler version

3.0.0-RC3

## Minimized code

No minimized code, sorry.

## Output (click arrow to expand)
<details>

```scala
scalac: Error: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1438)
	at scala.collection.SeqOps.sorted(Seq.scala:700)
	at scala.collection.SeqOps.sorted$(Seq.scala:692)
	at scala.collection.immutable.List.scala$collection$immutable$StrictOptimizedSeqOps$$super$sorted(List.scala:79)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.StrictOptimizedSeqOps.sorted$(StrictOptimizedSeqOps.scala:78)
	at scala.collection.immutable.List.sorted(List.scala:79)
	at scala.collection.SeqOps.sortWith(Seq.scala:727)
	at scala.collection.SeqOps.sortWith$(Seq.scala:727)
	at scala.collection.AbstractSeq.sortWith(Seq.scala:1149)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.sort$1(Implicits.scala:1283)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1298)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1305)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1338)
	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:974)
	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:769)
	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:103)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:843)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:769)
	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:103)
	at dotty.tools.dotc.typer.Typer.implicitArgs$1(Typer.scala:3287)
	at dotty.tools.dotc.typer.Typer.addImplicitArgs$3(Typer.scala:3323)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$2(Typer.scala:3402)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3580)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3793)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3134)
	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3145)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3780)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3134)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2804)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2920)
	at dotty.tools.dotc.typer.Typer.$anonfun$35(Typer.scala:2146)
	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2146)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2650)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2734)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2804)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2826)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2876)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2332)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2661)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2665)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2734)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2804)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2826)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2876)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2455)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2706)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2735)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2804)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2920)
	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Main.process(Main.scala)
```
</details>

### PR DESCRIPTION
**Pull request by smarter**
Before this commit, we sorted implicits using `prefer` which relied on
`compareOwner`, but compareOwner does not induce a total ordering: just
because `compareOwner(x, y) == 0` does not mean that `compareOwner(x,
z)` and `compareOwner(y, z)` have the same sign, this violates the
contract of `java.util.Comparator#compare` and lead to an
IllegalArgumentException sometimes being thrown (although I wasn't able
to reproduce that, see #12479)

This commit fixes by this by replacing the usage of `compareOwner` by a
new `compareBaseClassesLength` which does induce a total ordering while
still hopefully approximating `compareOwner` well enough for our
purposes.

We also replace `prefer` which returned a Boolean by `compareEligibles`
which is directly usable as an Ordering we can pass to `sorted`, this is
more efficient than using `sortWith(prefer)` because the latter might end
up calling `prefer` twice for a single comparison.

Fixes #12479 (I hope).

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

**Comment by smarter** [comment]
@odersky I ended up not adding a tie-break based on names like discussed in https://github.com/lampepfl/dotty/issues/12479#issuecomment-845154149 since that isn't actually necessary for a total ordering and so shouldn't matter here

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -1247,53 +1247,102 @@ trait Implicits:
...
         case e1 :: Nil => eligible
         case e1 :: e2 :: Nil =>
-          if (prefer(e2, e1)) e2 :: e1 :: Nil
+          if compareEligibles(e2, e1) < 0 then e2 :: e1 :: Nil
           else eligible
         case _ =>
-          try eligible.sortWith(prefer)
+          try eligible.sorted(using (a, b) => compareEligibles(a, b))
           catch case ex: IllegalArgumentException =>
-            // diagnostic to see what went wrong
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala:1285]: Maybe move what follows in a separate method `checkContract`?

**Review by odersky — APPROVED** [review]
Otherwise LGTM
