### PR TITLE
Fix #7048: Check for splice stability

### LINKED ISSUE #7048: Path dependent types don't play well with macros and typeclasses
Consider the following:

```scala
import scala.quoted._


trait IsExpr[T] {
  type Underlying
  def toExpr(x: T): Expr[Underlying]
}

// object IsExpr { type Aux[T, U] = IsExpr[T] { type Underlying = U } }

// given [U] as IsExpr.Aux[Expr[U], U] = new IsExpr[Expr[U]] {
given [U] as IsExpr[Expr[U]] = new IsExpr[Expr[U]] {
  type Underlying = U
  def toExpr(x: Expr[U]): Expr[U] = x
}

def f(x: Any): String = x.toString

def g[T](x: T) given (e: IsExpr[T], tu: Type[e.Underlying]): given QuoteContext => Expr[String] = {
  val underlying: Expr[e.Underlying] = e.toExpr(x)
  '{f($underlying)}
}

// def g[T, U](x: T) given (e: IsExpr.Aux[T, U], tu: Type[U]): given QuoteContext => Expr[String] = {
//   val underlying: Expr[U] = e.toExpr(x)
//   '{f($underlying)}
// }

inline def mcr: Any = ${mcrImpl}
def mcrImpl given QuoteContext: Expr[Any] = {
  val x = '{1}
  g(x)
}
```

Will output:

```scala
-- Error: ../pg/Lib.scala:21:6 -------------------------------------------------
21 |  '{f($underlying)}
   |      ^^^^^^^^^^^
   |      access to value e from wrong staging level:
   |       - the definition is at level 0,
   |       - but the access is at level 1.
```

Sort of makes sense, since `e` is indeed defined at level 0. However, two facts make me think something can be done here. First, only the path-dependent type is accessed there (presumably, since the compiler needs to know the type of `underlying`), and we have it with the `Type` argument. Second, the following trick works:

```scala
import scala.quoted._


trait IsExpr[T] {
  type Underlying
  def toExpr(x: T): Expr[Underlying]
}

object IsExpr { type Aux[T, U] = IsExpr[T] { type Underlying = U } }

given [U] as IsExpr.Aux[Expr[U], U] = new IsExpr[Expr[U]] {
// given [U] as IsExpr[Expr[U]] = new IsExpr[Expr[U]] {
  type Underlying = U
  def toExpr(x: Expr[U]): Expr[U] = x
}

def f(x: Any): String = x.toString

// def g[T](x: T) given (e: IsExpr[T], tu: Type[e.Underlying]): given QuoteContext => Expr[String] = {
//   val underlying: Expr[e.Underlying] = e.toExpr(x)
//   '{f($underlying)}
// }

def g[T, U](x: T) given (e: IsExpr.Aux[T, U], tu: Type[U]): given QuoteContext => Expr[String] = {
  val underlying: Expr[U] = e.toExpr(x)
  '{f($underlying)}
}

inline def mcr: Any = ${mcrImpl}
def mcrImpl given QuoteContext: Expr[Any] = {
  val x = '{1}
  g(x)
}
```

`Aux` trick comes from Shapeless 2 and was used to bypass the limitations of Scala 2, where it was impossible to refer to a path-dependent type of a sibling argument from the same argument list.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: tests/neg/i7048e.scala [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+      val r1 = '{Option.empty[${T}]} // works
+      val r2 = '{Option.empty[List[${T}]]} // works
+      // val r3 = '{summon[Type[${T}]]} // access to Test.this from wrong staging level
+      val r4 = '{summon[${T} <:< Any]} // error
+    }
+
+    {
+      val s = '{Option.empty[${T}]}
+      val r = '{identity($s)} // works
+      val r2 = '{identity(${s: Expr[Option[T]]})} // error // error
```
Comment (liufengyun) [inline tests/neg/i7048e.scala]: It's not obvious why this is not accepted by the check.

Comment (nicolasstucki) [reply tests/neg/i7048e.scala]:
```
32 |      val r2 = '{identity[Option[T]](${s: Expr[Option[T]]})} // error // error
   |                                     ^^^^^^^^^^^^^^^^^^^^^
   |    (Test.this.given_Type_T : => quoted.Type[Test.this.T]) is not stable
```

All these can be fixed by making the `given`  stable

```scala
val getT: Type[T] = T // need this to avoid getting `null`
given getT.type = getT
```

Comment (nicolasstucki) [reply tests/neg/i7048e.scala]: Added an extra test for it

Comment (liufengyun) [reply tests/neg/i7048e.scala]: Why it has to be stable?

Comment (nicolasstucki) [reply tests/neg/i7048e.scala]: Type splices require a stable prefix to be correctly encoded. It also avoids having to deal with side effects in the transformation performed in `ReifyQuotes`. Most code receives the quoted type as a parameter and hence is stable.

Comment (liufengyun) [reply tests/neg/i7048e.scala]: It's a restriction in TASTy? This is unprecedented in Scala, as usually only the path in types needs to be stable.

Comment (nicolasstucki) [reply tests/neg/i7048e.scala]: This is a path in a type. A type that is inferred and then healed.
