### PR TITLE
Change top-level ~ evaluation scheme

### LINKED ISSUE #4735: Macro inside inline fails Ycheck
```scala
import scala.annotation.tailrec
import scala.quoted._

object Macro {

  inline def unrolledForeach(inline unrollSize: Int, seq: Array[Int], f: => Int => Unit): Unit = // or f: Int => Unit
    ~unrolledForeachImpl(unrollSize, '(seq), '(f))

  private def unrolledForeachImpl(unrollSize: Int, seq: Expr[Array[Int]], f: Expr[Int => Unit]): Expr[Unit] = '{
    val size = (~seq).length
    assert(size % (~unrollSize.toExpr) == 0) // for simplicity of the implementation
    var i = 0
    while (i < size) {
      println("<log> start loop")
      ~{
        for (j <- new UnrolledRange(0, unrollSize)) '{
          val element = (~seq)(i + ~j.toExpr)
          ~f('(element)) // or `(~f)(element)` if `f` should not be inlined
        }
      }
      i += ~unrollSize.toExpr
    }

  }

  private class UnrolledRange(start: Int, end: Int) {
    def foreach(f: Int => Expr[Unit]): Expr[Unit] = {
      @tailrec def loop(i: Int, acc: Expr[Unit]): Expr[Unit] =
        if (i >= 0) loop(i - 1, '{ ~f(i); ~acc })
        else acc
      loop(end - 1, '())
    }
  }
}
```

```scala

import scala.quoted._

object Test {
  def main(args: Array[String]): Unit = {
    val arr = Array.tabulate[Int](21)(x => x)
    for (x <- new Unrolled(arr)) {
      System.out.println(2*x)
    }
  }


}
class Unrolled(arr: Array[Int]) extends AnyVal {
  inline def foreach(f: => Int => Unit): Unit = Macro.unrolledForeach(3, arr, f)
}
```

Fails Ycheck with

```
exception while typing inline def foreach(f: => Function1[Int, Unit]): Unit = Macro.unrolledForeach(3, this.inline$arr, f) of class class dotty.tools.dotc.ast.Trees$DefDef # 4391
exception while typing @scala.annotation.internal.SourceFile(
  "/Users/nicolasstucki/GitHub/dotty/tests/run/quote-unrolled-foreach/quoted_2.scala"
) final class Unrolled(arr: Array[Int]) extends AnyVal() { 
  private[this] val arr: Array[Int]
  inline def foreach(f: => Function1[Int, Unit]): Unit = Macro.unrolledForeach(3, this.inline$arr, f)
  def inline$arr: Array[Int] = Unrolled.this.arr
  override def hashCode(): Int = Unrolled.this.arr.hashCode()
  override def equals(x$0: Any): Boolean = 
    x$0 match 
      {
        case x$0 @ _: Unrolled @unchecked => this.arr.==(x$0.arr)
        case _ => false
      }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 4520
exception while typing package <empty> {
  import scala.quoted._
  final lazy module val Test: Test = new Test()
  @scala.annotation.internal.SourceFile(
    "/Users/nicolasstucki/GitHub/dotty/tests/run/quote-unrolled-foreach/quoted_2.scala"
  ) final module class Test() extends Object() { this: Test.type => 
    def main(args: Array[String]): Unit = 
      {
        val arr: Array[Int] = 
          Array.tabulate[Int](21)(
            {
              def $anonfun(x: Int): Int = x
              closure($anonfun)
            }
          )(scala.reflect.ClassTag.apply[Int](Integer.TYPE))
        /* inlined from Unrolled*/ 
          {
            val Unrolled_this: Unrolled = new Unrolled(arr)
            /* inlined from Macro*/ 
              {
                val seq: Array[Int] = Unrolled_this.inline$arr
                {
                  val size: Int = seq.length
                  assert(size.%(3).==(0))
                  var i: Int = 0
                  {
                    <label> def while$(): Unit = 
                      if i.<(size) then 
                        {
                          {
                            println("<log> start loop")
                            {
                              {
                                val element: Int = seq.apply(i.+(0))
                                {
                                  val x$1: Int = element
                                  {
                                    System.out.println(2.*(x$1))
                                  }
                                }
                              }
                              {
                                {
                                  val element: Int = seq.apply(i.+(1))
                                  {
                                    val x$2: Int = element
                                    {
                                      System.out.println(2.*(x$2))
                                    }
                                  }
                                }
                                {
                                  {
                                    val element: Int = seq.apply(i.+(2))
                                    {
                                      val x$3: Int = element
                                      {
                                        System.out.println(2.*(x$3))
                                      }
                                    }
                                  }
                                  ()
                                }
                              }
                            }
                            i = i.+(3)
                          }
                          while$()
                        }
                       else ()
                    while$()
                  }
                }
              }
          }
      }
  }
  @scala.annotation.internal.SourceFile(
    "/Users/nicolasstucki/GitHub/dotty/tests/run/quote-unrolled-foreach/quoted_2.scala"
  ) final class Unrolled(arr: Array[Int]) extends AnyVal() { 
    private[this] val arr: Array[Int]
    inline def foreach(f: => Function1[Int, Unit]): Unit = Macro.unrolledForeach(3, this.inline$arr, f)
    def inline$arr: Array[Int] = Unrolled.this.arr
    override def hashCode(): Int = Unrolled.this.arr.hashCode()
    override def equals(x$0: Any): Boolean = 
      x$0 match 
        {
          case x$0 @ _: Unrolled @unchecked => this.arr.==(x$0.arr)
          case _ => false
        }
  }
  final lazy module val Unrolled: Unrolled = new Unrolled()
  @scala.annotation.internal.SourceFile(
    "/Users/nicolasstucki/GitHub/dotty/tests/run/quote-unrolled-foreach/quoted_2.scala"
  ) final module class Unrolled() extends Object() { this: Unrolled.type =>}
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 4733
*** error while checking /Users/nicolasstucki/GitHub/dotty/tests/run/quote-unrolled-foreach/quoted_2.scala after phase reifyQuotes ***
```

### LINKED ISSUE #4773: Macros fail Ycheck when called in inline
```scala
import scala.quoted._
object Foo {
  inline def foo2(): Unit = ~foo2Impl()
  def foo2Impl(): Expr[Unit] = '()
  inline def foo(): Unit = foo2()
}
```

fail Ycheck with 

```scala
exception while typing inline def foo(): Unit = StagedStreams.foo2() of class class dotty.tools.dotc.ast.Trees$DefDef # 49
exception while typing @scala.annotation.internal.SourceFile(
  "tests/run-no-deep-subtypes/staged-streams-macro/staged-streams_1.scala"
) final module class StagedStreams() extends Object() { 
  this: StagedStreams.type =>
 
  inline def foo2(): Seq[Any] => Object = 
    {
      def $anonfun$1(x$0: Seq[Any]): quoted.Expr[Unit] = 
        {
          val tastyContext$1: scala.tasty.Tasty = 
            x$0.apply(0).asInstanceOf[scala.tasty.Tasty]
          StagedStreams.foo2Impl()
        }
      closure($anonfun$1)
    }
  def foo2Impl(): quoted.Expr[Unit] = 
    scala.runtime.quoted.Unpickler.liftedExpr[Unit](())
  inline def foo(): Unit = StagedStreams.foo2()
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 180
exception while typing package <empty> {
  import scala.quoted._
  final lazy module val StagedStreams: StagedStreams = new StagedStreams()
  @scala.annotation.internal.SourceFile(
    "tests/run-no-deep-subtypes/staged-streams-macro/staged-streams_1.scala"
  ) final module class StagedStreams() extends Object() { 
    this: StagedStreams.type =>
   
    inline def foo2(): Seq[Any] => Object = 
      {
        def $anonfun$1(x$0: Seq[Any]): quoted.Expr[Unit] = 
          {
            val tastyContext$1: scala.tasty.Tasty = 
              x$0.apply(0).asInstanceOf[scala.tasty.Tasty]
            StagedStreams.foo2Impl()
          }
        closure($anonfun$1)
      }
    def foo2Impl(): quoted.Expr[Unit] = 
      scala.runtime.quoted.Unpickler.liftedExpr[Unit](())
    inline def foo(): Unit = StagedStreams.foo2()
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 181
*** error while checking tests/run-no-deep-subtypes/staged-streams-macro/staged-streams_1.scala after phase reifyQuotes ***
exception occurred while compiling tests/run-no-deep-subtypes/staged-streams-macro/staged-streams_1.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Types differ
Original type : Unit
After checking: Seq[Any] => Object
Original tree : StagedStreams.foo2()
After checking: StagedStreams.foo2()
Why different :
             Subtype trace:
  ==> Seq[Any] => Object <:< Unit  
  <== Seq[Any] => Object <:< Unit   = false
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:288)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1870)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1866)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1882)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:263)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1941)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedDefDef$1(Typer.scala:1428)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:35)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1410)
	at dotty.tools.dotc.transform.TreeChecker$Checker.super$typedDefDef(TreeChecker.scala:408)
	at dotty.tools.dotc.transform.TreeChecker$Checker.$anonfun$typedDefDef$2(TreeChecker.scala:408)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:179)
	at dotty.tools.dotc.transform.TreeChecker$Checker.$anonfun$typedDefDef$1(TreeChecker.scala:397)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:179)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:396)
...
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
The new scheme consists in only allowing simple interpretable expressions in top-level splices. Then, the inlined splice can be evaluated directly.

Changes:
* top-level ~ must contain a call to a static method
  * arguments must be quoted
  * inline arguments can be passed directly
* removed dependency on the original inlined code (removed in PostTyper)
* ReifyQuotes is no longer an InfoTransformer
* Splicer implements both checking and evaluation of splices in a single abstraction
* Addapted some tests
* Fix #4773
* Fix #4735

PR followed by #4823

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Rebased on #4616

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 1]
```diff
@@ -607,22 +565,16 @@ class ReifyQuotes extends MacroTransformWithImplicits with InfoTransformer {
                   ctx.error("Transparent macro method must be a static method.", tree.pos)
                 markDef(tree)
                 val reifier = nested(isQuote = true)
-                reifier.transform(tree) // Ignore output, we only need the its embedding
-                assert(reifier.embedded.size == 1)
-                val lambda = reifier.embedded.head
-                // replace macro code by lambda used to evaluate the macro expansion
-                cpy.DefDef(tree)(tpt = TypeTree(macroReturnType), rhs = lambda)
+                reifier.transform(tree) // Ignore output, only check PCP
+                cpy.DefDef(tree)(rhs = defaultValue(tree.rhs.tpe))
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: No. Now we just remove the RHS to prune the tree earlier in the pipeline. Maybe this could be done later.

[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: This logic will be simplified later in #4826.

File: compiler/src/dotty/tools/dotc/transform/Splicer.scala [hunk 2]
```diff
@@ -32,89 +34,52 @@ object Splicer {
...
+  /** Tree interpreter that evaluates the tree */
+  private class Interpreter(pos: Position, classLoader: ClassLoader)(implicit ctx: Context) extends AbstractInterpreter {
 
-  /** Tree interpreter that can interpret calls to static methods with it's default arguments
-   *
-   *  The interpreter assumes that all calls in the trees are to code that was
-   *  previously compiled and is present in the classpath of the current context.
-   */
-  private class Interpreter(pos: Position, classLoader: ClassLoader)(implicit ctx: Context) {
+    type Res = Object
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/Splicer.scala]: Res for "result"? I'd use the full name.

File: compiler/src/dotty/tools/dotc/transform/Splicer.scala [hunk 3]
```diff
@@ -172,6 +158,15 @@ object Splicer {
           ex.printStackTrace(new PrintWriter(sw))
           sw.write("\n")
           throw new StopInterpretation(sw.toString, pos)
+        case ex: InvocationTargetException =>
+          val sw = new StringWriter()
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/Splicer.scala]: Why use a low-level method to compose the output? Is it to avoid a stackoverflow?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicer.scala]: it was just to pass it simply to the  `ex. printStackTrace` method of `Exception`.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicer.scala]: Later I will need to improve the format of the output, then we will switch to a high level abstraction.
