### PR TITLE
Fix #9958: Avoid eta contractions when printing

### LINKED ISSUE #9958: Some type lambdas printed incorrectly
## Minimized code

```Scala
summon[[X] =>> (X, X)]
```

## Output

```scala
no implicit argument of type Tuple2 was found for parameter x of method summon in object DottyPredef
```

## Expectation

```scala
no implicit argument of type [X] =>> (X, X) was found for parameter x of method summon in object DottyPredef
```

### PR DESCRIPTION
**Pull request by odersky**
Don't eta contract if the result type of a lambda is an applied
type that's treated specially.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Does this also fixes #9971

**Comment by odersky** [comment]
#9971 was a different, and deeper problem. It's  now also fixed.

**Comment by odersky** [comment]
Fixes #9971

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 1]
```diff
@@ -26,25 +26,46 @@ object TypeApplications {
...
+    /** Test that the parameter bounds in a hk type lambda `[X1,...,Xn] => C[X1, ..., Xn]`
+     *  contain the bounds of the type parameters of `C`. This is necessary to be able to
+     *  contract the hk lambda to `C`.
+     */
+    private def weakerBounds(tp: HKTypeLambda, tparams: List[ParamInfo])(using Context): Boolean =
+      val onlyEmptyBounds = tp.typeParams.forall(_.paramInfo == TypeBounds.empty)
+      onlyEmptyBounds
+        // Note: this pre-test helps efficiency. It is also necessary since in some cases
+        // tparams is empty. This can happen when we change the owners of inlined local
+        // classes in mapSymbols. See pos/reference/delegates.scala for an example.
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/core/TypeApplications.scala:50]: It is the manifestation of #9965 which I also encountered in #9954.

It happens when inlining
https://github.com/lampepfl/dotty/blob/a128dab3a435a9eb3aa7a8cba359a9989a73d9c2/tests/pos/reference/delegates.scala#L114-L115

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 2]
```diff
@@ -26,25 +26,46 @@ object TypeApplications {
...
 
-    def unapply(tp: Type)(using Context): Option[Type] = tp match {
+    /** Test that the parameter bounds in a hk type lambda `[X1,...,Xn] => C[X1, ..., Xn]`
+     *  contain the bounds of the type parameters of `C`. This is necessary to be able to
+     *  contract the hk lambda to `C`.
+     */
+    private def weakerBounds(tp: HKTypeLambda, tparams: List[ParamInfo])(using Context): Boolean =
+      val onlyEmptyBounds = tp.typeParams.forall(_.paramInfo == TypeBounds.empty)
+      onlyEmptyBounds
+        // Note: this pre-test helps efficiency. It is also necessary since in some cases
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/core/TypeApplications.scala:48]:
```suggestion
        // Note: this pre-test helps efficiency. It is also necessary to workaround  #9965 since in some cases
```

**Review by nicolasstucki — APPROVED** [review]
LGTM.

It looks like #9965 is starting to cause issues in many places.

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala:50]: @odersky does this match what you saw while debugging or are there other problematic cases?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala:50]: That's what I saw, yes.
