### PR TITLE
fix #10511: compare enumvalues in provably disjoint

### LINKED ISSUE #10511: Enum Value singleton fails to reduce in match type
## Minimised Code

```scala
enum Bool {
  case True
  case False
}

import Bool._

type Not[B <: Bool] = B match {
  case True.type => False.type
  case False.type => True.type  
}

val f: Not[False.type] = True
```

## Output

```scala
13 |val f: Not[False.type] = True
   |                         ^^^^
   |                         Found:    (Bool.True : Bool)
   |                         Required: Not[(Bool.False : Bool)]
```

## Expectation

if I replace `enum Bool` with a sealed trait and case objects then the code compiles:
```diff
+sealed trait Bool
+object Bool {
+  case object True extends Bool
+  case object False extends Bool
-enum Bool {
-  case True
-  case False
 }
...
```

_Originally posted by @bishabosha in https://github.com/lampepfl/dotty/issues/10510#issuecomment-734297116_

### PR DESCRIPTION
**Pull request by bishabosha**
this also shortcuts comparing `object` refs without looking at their supertype

fixes #10511

### CODE REVIEW

**Comment by bishabosha** [comment]
I have also tested transitivity of passing aliases to singleton enum values, such as this:
```scala
val t: True.type = True
val f: False.type = False

val t1: Not[f.type] = t // transitivity
val f1: Not[t.type] = f // transitivity
```

it has been added under `pos-special` due to match types printing differently in the `pickling` test, despite `-from-tasty` producing the correct code

File: tests/run/i10511.scala [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+}
+
+import Bool._
+
+type Not[B <: Bool] = B match {
+  case True.type => False.type
+  case False.type => True.type
+}
+
+def not[B <: Bool & Singleton](b: B): Not[B] = b match {
```
Comment (OlivierBlanvillain) [inline tests/run/i10511.scala:17]: It's nice that `Singleton` helps inference here, the following compiles as expected:

```scala
not(True): False.type
```

Although it's a bit fragile:

```scala
val vrais = True
not(vrais): False.type // error, we lost the singleton type...
```

**Comment by OlivierBlanvillain** [comment]
I think this PR should also update the docs, the diff LGTM otherwise.

It wouldn't be sounds to compare singleton types in the general case, but as far as I can tell it's fine to do for enums because value cases are guaranteed to point to a different object.

File: compiler/test/dotty/tools/dotc/CompilationTests.scala [hunk 2]
```diff
@@ -52,6 +52,7 @@ class CompilationTests {
       compileFile("tests/pos-special/notNull.scala", defaultOptions.and("-Yexplicit-nulls")),
       compileDir("tests/pos-special/adhoc-extension", defaultOptions.and("-source", "3.1", "-feature", "-Xfatal-warnings")),
       compileFile("tests/pos-special/i7575.scala", defaultOptions.andLanguageFeature("dynamics")),
+      compileFile("tests/pos-special/i10511-transitivity.scala", defaultOptions), // avoid pickling test
```
Comment (OlivierBlanvillain) [inline compiler/test/dotty/tools/dotc/CompilationTests.scala:55]: I think it would be better to add the new test to `compiler/test/dotc/pos-test-pickling.blacklist` were we already have several match type tests.

Comment (bishabosha) [reply compiler/test/dotty/tools/dotc/CompilationTests.scala]: the pickling test seemed to work after cleaning my repo so ive merged it with the other pos test for now

**Comment by bishabosha** [comment]
I've updated the match-types doc

File: tests/run/i10511.scala (hunk 1 above)
Comment (bishabosha) [reply tests/run/i10511.scala:17]: yeah its true with enums you must do a lot of work to avoid the widening but thats something hopefully we can tune progressively without ruining bincompat

**Comment by bishabosha** [comment]
so FromTastyTest for `pos/i10511.scala` failed at -Ycheck:all due to the match type not reducing under `-from-tasty`, I've added an exception for now

**Comment by bishabosha** [comment]
it is possible to get the `-Ycheck:readTasty` for `Not[(f1 : Not[(t : (Bool.True : Bool))])]` to pass if I call `normalise` in a recursive version of `isEnumValueOrModule` but it is probably best to do that at unpickling time when we see a match type:

```scala
def isEnumValueOrModule(ref: TermRef): Boolean =
  val sym = ref.termSymbol
  sym.isAllOf(EnumCase, butNot=JavaDefined)
    || sym.is(Module)
    || (sym.info.normalized match
        case tp: TermRef => isEnumValueOrModule(tp)
        case tp => false)
```
