### PR TITLE
Fix #8501: Run closure adaptation in Erasure.etaExpand

### LINKED ISSUE #8501: Failed nightly test with Java 11
Nightly build failed `tests/run/context-functions.scala` with Java 11.

https://dotty-ci.epfl.ch/lampepfl/dotty/4916/1/7

Restarted test: https://dotty-ci.epfl.ch/lampepfl/dotty/4918

### PR DESCRIPTION
**Pull request by smarter**
Erasure.Boxing.etaExpand generates closures, but did not run the same closure
adaptation code used in Erasure#typedClosure which could lead to
type mismatches at runtime when invoking it. Fixed by moving out the
adaptation logic from Erasure#typedClosure into
Erasure.Boxing.adaptClosure and reusing this in
Erasure.Boxing.etaExpand.

This fixes tests/run/context-functions.scala on Java 11.

Also make sure ctx.typer is correctly set at Erasure (I'm surprised this
didn't come up before), otherwise adaptClosure won't work.

### CODE REVIEW

**Comment by smarter** [comment]
Merging this now to get it in the next nightly but I"ll still take review comments into account.

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala [hunk 1]
```diff
@@ -101,7 +101,7 @@ class Erasure extends Phase with DenotTransformer {
 
   def run(implicit ctx: Context): Unit = {
     val unit = ctx.compilationUnit
-    unit.tpdTree = eraser.typedExpr(unit.tpdTree)(ctx.fresh.setPhase(this.next))
+    unit.tpdTree = eraser.typedExpr(unit.tpdTree)(ctx.fresh.setTyper(eraser).setPhase(this.next))
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/Erasure.scala]: Amazing that this worked before. Or was `typer` set by other means?
