### PR TITLE
Fix #11464: avoid expanding local paramRef in HKTypeLambda

### LINKED ISSUE #11464: Partial Type Application with F-Bounds and braces crashes with java.lang.ClassCastException: class dotty.tools.dotc.core.Types$Range cannot be cast to class dotty.tools.dotc.core.Types$TypeBounds
## Compiler version

Scala: 3.0.0-RC1 (works in 3.0.0-M3)
sbt: 1.4.7

## Minimized code

```scala
trait Txn[T <: Txn[T]]

trait Adjunct

trait Type0
trait Type[A1, Repr[~ <: Txn[~]] <: Expr[~, A1]] extends Type0

object Expr {
  def test(peer: Type0): Adjunct = {
    new AdjunctImpl(peer.asInstanceOf[Type[Any, ({ type R[~ <: Txn[~]] <: Expr[~, Any] }) # R]])
  }
}

trait Expr[T <: Txn[T], +A]

class AdjunctImpl[A, E[~ <: Txn[~]] <: Expr[~, A]](tpe: Type[A, E]) extends Adjunct
```

## Output

```scala
[error] java.lang.ClassCastException: class dotty.tools.dotc.core.Types$Range cannot be cast to class dotty.tools.dotc.core.Types$TypeBounds (dotty.tools.dotc.core.Types$Range and dotty.tools.dotc.core.Types$TypeBounds are in unnamed module of loader dotty.tools.sbtplugin.DottyPlugin$DottyLoader$1 @5ea3d7c4)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error] 	at dotty.tools.dotc.core.Types$HKTypeLambda.newLikeThis$$anonfun$1(Types.scala:3740)
[error] 	at dotty.tools.dotc.core.Types$HKTypeLambda.<init>(Types.scala:3696)
[error] 	at dotty.tools.dotc.core.Types$HKTypeLambda$.apply(Types.scala:3805)
[error] 	at dotty.tools.dotc.core.Types$HKTypeLambda.newLikeThis(Types.scala:3741)
[error] 	at dotty.tools.dotc.core.Types$HKTypeLambda.newLikeThis(Types.scala:3736)
[error] 	at dotty.tools.dotc.core.Types$HKTypeLambda.newLikeThis(Types.scala:3735)
[error] 	at dotty.tools.dotc.core.Types$LambdaType.derivedLambdaType(Types.scala:3352)
[error] 	at dotty.tools.dotc.core.Types$LambdaType.derivedLambdaType$(Types.scala:3295)
[error] 	at dotty.tools.dotc.core.Types$HKLambda.derivedLambdaType(Types.scala:3368)
[error] 	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.derivedLambdaType(Types.scala:5546)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.mapOverLambda(Types.scala:5143)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5168)
[error] 	at dotty.tools.dotc.core.TypeOps$$anon$1.apply(TypeOps.scala:444)
[error] 	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.reapply(Types.scala:5549)
[error] 	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.expandBounds(Types.scala:5348)
[error] 	at dotty.tools.dotc.core.Types$ApproximatingTypeMap.tryWiden(Types.scala:5366)
[error] 	at dotty.tools.dotc.core.TypeOps$$anon$1.derivedSelect(TypeOps.scala:459)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5162)
[error] 	at dotty.tools.dotc.core.TypeOps$$anon$1.apply(TypeOps.scala:444)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.op$proxy13$1(Types.scala:5130)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.mapArgs(Types.scala:5130)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.mapArgs(Types.scala:5131)
[error] 	at dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5165)
[error] 	at dotty.tools.dotc.core.TypeOps$$anon$1.apply(TypeOps.scala:444)
[error] 	at dotty.tools.dotc.core.TypeOps$.avoid(TypeOps.scala:469)
[error] 	at dotty.tools.dotc.typer.TypeAssigner.avoidingType(TypeAssigner.scala:44)
[error] 	at dotty.tools.dotc.typer.TypeAssigner.avoidingType$(TypeAssigner.scala:20)
[error] 	at dotty.tools.dotc.typer.Typer.avoidingType(Typer.scala:102)
[error] 	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:368)
[error] 	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:20)
[error] 	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:102)
[error] 	at dotty.tools.dotc.ast.tpd$TypedTreeCopier.Block(tpd.scala:644)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1335)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:63)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:426)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1394)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:54)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$5(PostTyper.scala:344)
[error] 	at dotty.tools.dotc.transform.SuperAccessors.wrapDefDef(SuperAccessors.scala:225)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:344)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStat$1(MacroTransform.scala:42)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats$$anonfun$1(MacroTransform.scala:45)
[error] 	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:92)
[error] 	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:108)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats(MacroTransform.scala:45)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:61)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$8$$anonfun$1(PostTyper.scala:335)
[error] 	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:210)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$4(PostTyper.scala:335)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.withNoCheckNews(PostTyper.scala:98)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:337)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1398)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:54)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:361)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1407)
[error] 	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:54)
[error] 	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:426)
[error] 	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:150)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] 	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] 	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2177)
```

Note that a very strange thing happens - when I remove the braces from

```scala
  def test(peer: Type0): Adjunct = {
    new AdjunctImpl(peer.asInstanceOf[Type[Any, ({ type R[~ <: Txn[~]] <: Expr[~, Any] }) # R]])
  }
```

to

```scala
  def test(peer: Type0): Adjunct = {
    new AdjunctImpl(peer.asInstanceOf[Type[Any, ({ type R[~ <: Txn[~]] <: Expr[~, Any] }) # R]])
  }
```

the crash "disappears".

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #11464: avoid expanding local paramRef in HKTypeLambda

### CODE REVIEW

**Comment by smarter** [comment]
Could you try re-enabling `scissLucre` in the community build? It was disabled a few months ago due to an unrelated problem in the community build (https://github.com/lampepfl/dotty/pull/10828#issuecomment-747453983), and it fails on master with the Range ClassCastException

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 1]
```diff
@@ -439,7 +439,9 @@ object TypeOps:
           val lo1 = apply(lo)
           if (lo1 ne lo) lo1 else tp
         case tp: LazyRef if isExpandingBounds =>
-          emptyRange
+          if variance == 1 then defn.AnyType
+          else if variance == -1 then defn.NothingType
+          else TypeBounds.empty
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:444]: This is still not correct conceptually -- we need to know both the _kind_ and _variance_ of the LazyRef in order to produce an approximation.

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -5724,6 +5724,37 @@ object Types {
             foldOver(xs, tp)
   end NamedPartsAccumulator
 
+  class ExistsLocalRef(using Context) extends TypeAccumulator[Boolean]:
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala:5727]: Does this actually make type avoidance faster? It's not clear to me because this still requires traversing the type to see if there's something to avoid.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/Types.scala:5727]: We don't have much empirical evidence. It avoids computing `localSyms` and it has shortcut for references to type or term parameters. Or we can enhance the `TypeOps.avoid`. This part can come later if there indeed a noticeable speedup. For now, I'll remove it from the PR.

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 3]
```diff
@@ -429,17 +430,22 @@ object TypeOps:
             case _ =>
               emptyRange // should happen only in error cases
           }
-        case tp: ThisType if toAvoid(tp.cls) =>
-          range(defn.NothingType, apply(classBound(tp.cls.classInfo)))
+        case tp: ThisType =>
+          tp
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:434]: Could you explain why this change is needed and why it's safe to not do avoidance here?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:434]: We don't need this, this is an optimization -- the rationale is that ThisType doesn't exist outside of `class`, thus they are always safe in avoidance.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:434]: OK, I think this makes sense but it'd be good to check with an assert that this never happens in our tests (once the tests pass we can disable the assert for performance), and to add a comment explaining that this is safe.

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 4]
```diff
@@ -429,17 +430,22 @@ object TypeOps:
...
           range(defn.NothingType, apply(tp.info))
         case tp: TypeVar if mapCtx.typerState.constraint.contains(tp) =>
           val lo = TypeComparer.instanceType(
             tp.origin, fromBelow = variance > 0 || variance == 0 && tp.hasLowerBound)(using mapCtx)
           val lo1 = apply(lo)
           if (lo1 ne lo) lo1 else tp
-        case tp: LazyRef if isExpandingBounds =>
-          emptyRange
+        case tp: LazyRef =>
+          if locals.contains(tp.ref) then tp
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:443]: Why is it safe to return tp here, doesn't it need to be avoided if it contains a local symbol?

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala (hunk 4 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:443]: Here `locals` mean locally bound `ParamRef` in a HKTypeLambda -- we remember that in the set `locals`. The set is not the set of local symbols to be avoided.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:443]: Oh I see, would be good to give it another name to avoid confusing it with `localSyms` I think :). Maybe `localParamRefs` ?

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 5]
```diff
@@ -401,6 +401,7 @@ object TypeOps:
   def avoid(tp: Type, symsToAvoid: => List[Symbol])(using Context): Type = {
     val widenMap = new ApproximatingTypeMap {
       @threadUnsafe lazy val forbidden = symsToAvoid.toSet
+      val locals = util.HashSet[Type]()
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:404]: As an optimization, this could be an uninitialized var which is only initialized the first time we encounter an HKTypeLambda.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:404]: (or just make it a lazy val).

**Comment by liufengyun** [comment]
> OK, I think this makes sense but it'd be good to check with an assert that this never happens in our tests (once the tests pass we can disable the assert for performance), and to add a comment explaining that this is safe.

@smarter Could you elaborate a little bit about the assertion? To clarify, `ThisType` of course can occur in avoidance, but they are safe because the ThisType must be a class that encloses the block to be avoided.

**Comment by smarter** [comment]
What I had in mind was to add an `assert(!toAvoid(tp.cls))` in the ThisType clause to verify that indeed we don't have any ThisType to avoid.

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 6]
```diff
@@ -431,6 +431,10 @@ object TypeOps:
               emptyRange // should happen only in error cases
           }
         case tp: ThisType =>
+          // ThisType is only used inside a class.
+          // Therefore, either they don't appear in the type to be avoided, or
+          // it must be a class that encloses the block whose type is to be avoided.
+          assert(!toAvoid(tp.cls))
           tp
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:438]: @smarter The CI confirmed the assertion.

**Review by smarter — APPROVED** [review]
