### PR TITLE
Clear temp var for captured var expr to permit GC

### LINKED ISSUE #14198: Local is not cleared, causing an object not to be GC'd
## Compiler version

3.1.0

## Minimized code

```Scala
import java.lang.ref.WeakReference
import java.util.concurrent.atomic.AtomicReference

final class Mark

final object MyTest {

  def main(args: Array[String]): Unit = {
    myTest()
  }

  def myAssert(cond: => Boolean): Unit = {
    assert(cond)
  }

  def myTest(): Unit = {
    val ref = new AtomicReference[WeakReference[AnyRef]]
    var mark: AnyRef = null
    assert(ref.compareAndSet(null, new WeakReference(new Mark)))
    mark = ref.get().get()
    myAssert(mark ne null) // in theory this could fail, but it isn't
    mark = null
    while (ref.get().get() ne null) {
      System.gc()
      Thread.sleep(1L)
    }
  }
}
```

## Output

The program never exits.

## Expectation

I think eventually the GC should collect the `Mark` instance, and the `while` loop should finish. (Works fine on Scala 2.13.7.)

Looking at a heap dump, the `Mark` instance is a GC root.

Looking at the JVM bytecode, it seems there is an "unnamed" local variable in the method `myTest` (i.e., it is not in the LocalVariableTable). The LocalVariableTable contains slots 0 (`this`), 1 (`ref`), and 2 (`mark`). In the bytecode there is a store to slot 3:

```
        49: invokevirtual #78                 // Method java/lang/ref/Reference.get:()Ljava/lang/Object;
        52: astore_3
        53: aload_2
        54: aload_3
        55: putfield      #82                 // Field scala/runtime/ObjectRef.elem:Ljava/lang/Object;
```

I think `49: invokevirtual` is the second `.get()` in the line `mark = ref.get().get()`. Then `52: astore_3` is the store to this "unnamed local 3". Then `55: putfield` stores it in the `ObjectRef` corresponding to the `var mark`.

However, when later we (try to) clear the reference in the line `mark = null`, only the `ObjectRef` is cleared, the "unnamed local 3" isn't:

```
        76: aconst_null
        77: putfield      #82                 // Field scala/runtime/ObjectRef.elem:Ljava/lang/Object;
```

Interestingly, right before this, there is a store of null to another unnamed local, in slot 4 (I couldn't figure out, what is this local 4):

```
        69: aconst_null
        70: astore        4
        72: aload_2
        73: aload         4
        75: pop
```

Another observation: the `myAssert` seems necessary to reproduce the issue (with a normal `assert`, it works fine).

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #14198

### CODE REVIEW

**Comment by som-snytt** [comment]
That was just non-trivial enough to learn something. Running the suite locally shows errors, so converting to draft while I chase those.

Still to answer, what does a tree inherit by virtue of `cpy` (position?), and why `transformFollowing` is called twice.

**Comment by anatoliykmetyuk** [comment]
@som-snytt what's the status on this one? Is it review-ready?

**Comment by som-snytt** [comment]
Possibly the extra nullifier could be emitted only selectively.

File: compiler/src/dotty/tools/dotc/transform/CapturedVars.scala [hunk 1]
```diff
@@ -138,17 +142,21 @@ class CapturedVars extends MiniPhase with IdentityDenotTransformer { thisPhase =
     *  Also: If the ref type lhs is followed by a cast (can be an artifact of nested translation),
     *  drop the cast.
     */
-  override def transformAssign(tree: Assign)(using Context): Tree = {
+  override def transformAssign(tree: Assign)(using Context): Tree =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/CapturedVars.scala:145]: Could yo update the comment above this method to describe the special case where we assign null to the temporary?

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/transform/CapturedVars.scala [hunk 2]
```diff
@@ -138,17 +142,21 @@ class CapturedVars extends MiniPhase with IdentityDenotTransformer { thisPhase =
...
         recur(qual)
       case Select(_, nme.elem) if refInfo.boxedRefClasses.contains(lhs.symbol.maybeOwner) =>
-        val tempDef = transformFollowing(SyntheticValDef(TempResultName.fresh(), tree.rhs))
-        transformFollowing(Block(tempDef :: Nil, cpy.Assign(tree)(lhs, ref(tempDef.symbol))))
+        val tempDef = transformFollowing {
+          ValDef(newSymbol(ctx.owner, TempResultName.fresh(), Mutable | Synthetic, tree.rhs.tpe.widen, coord = tree.rhs.span), tree.rhs)
+        }
+        val update  = cpy.Assign(tree)(lhs, ref(tempDef.symbol))
+        def reset   = cpy.Assign(tree)(ref(tempDef.symbol), nullLiteral.cast(tempDef.symbol.info))
+        val res     = if (refInfo.objectRefClasses(lhs.symbol.maybeOwner)) reset else Literal(Constant(()))
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/transform/CapturedVars.scala:156]: unquiet syntax alert. Also, `unitLiteral`.

**Comment by som-snytt** [comment]
Documented the change, aligned the stars, and omit nullify for `x = null`.

File: compiler/src/dotty/tools/dotc/transform/CapturedVars.scala [hunk 3]
```diff
@@ -123,32 +128,44 @@ class CapturedVars extends MiniPhase with IdentityDenotTransformer { thisPhase =
...
+      case Literal(Constant(null)) | Typed(Literal(Constant(null)), _) => true
+      case _ => false
+    def recur(lhs: Tree): Tree = lhs match
+      case TypeApply(Select(qual@Select(_, nme.elem), nme.asInstanceOf_), _) =>
         recur(qual)
       case Select(_, nme.elem) if refInfo.boxedRefClasses.contains(lhs.symbol.maybeOwner) =>
-        val tempDef = transformFollowing(SyntheticValDef(TempResultName.fresh(), tree.rhs))
-        transformFollowing(Block(tempDef :: Nil, cpy.Assign(tree)(lhs, ref(tempDef.symbol))))
+        val tempDef = transformFollowing {
+          ValDef(newSymbol(ctx.owner, TempResultName.fresh(), Mutable | Synthetic, tree.rhs.tpe.widen, coord = tree.rhs.span), tree.rhs)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/CapturedVars.scala:163]: Instead of inlining SyntheticValDef here, what do you think of adding an optional `flags` argument to its definition to be able to reuse it:
```scala
def SyntheticValDef(name: TermName, rhs: Tree, flags: FlagSet = EmptyFlags)(using Context): ValDef =
  ValDef(newSymbol(ctx.owner, name, Synthetic | flags, rhs.tpe.widen, coord = rhs.span), rhs)
```

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/transform/CapturedVars.scala:163]: OK. As a single usage, I avoided over-generalizing.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/transform/CapturedVars.scala]: No opportunity for `synthetic.withAddedFlags(Mutable)`, but the design space is small to begin with. Still learning all the internal conveniences.

**Review by smarter — APPROVED** [review]
Thank you!
