### PR TITLE
Fix #9246 and #6800: Remove pure statements

### LINKED ISSUE #9246: Inlined methods of type Unit produce unnesesary code
```Scala
inline def check(v:Double): Unit = if(v==0) throw new Exception()

inline def divide(v: Double, d: Double): Double = { check(d); v / d }

def run =  divide(10,2)
```
```scala
// Java decompiled method run
public double run() {
  BoxedUnit var10000 = BoxedUnit.UNIT;
  return 5.0D;
}
```
## Expectation
The BoxedUnit type variable is very annoying when trying to optimize inlined code

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/Compiler.scala [hunk 1]
```diff
@@ -94,7 +94,8 @@ class Compiler {
          new LetOverApply,            // Lift blocks from receivers of applications
          new ArrayConstructors) ::   // Intercept creation of (non-generic) arrays and intrinsify.
     List(new Erasure) ::             // Rewrite types to JVM model, erasing all type parameters, abstract types and refinements.
-    List(new ElimErasedValueType,    // Expand erased value types to their underlying implmementation types
+    List(new PureStats,              // Remove pure stats from blocks
+         new ElimErasedValueType,    // Expand erased value types to their underlying implmementation types
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/Compiler.scala:98]: I would keep ElimErasedValueType the first phase after erasure, this way values with ErasedValueType as a type only exist for the minimal amount of time they need to.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/Compiler.scala]: Done

File: compiler/src/dotty/tools/dotc/transform/PureStats.scala [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  override def phaseName: String = PureStats.name
+
+  override def runsAfter: Set[String] = Set(Erasure.name)
+
+  override def transformBlock(tree: Block)(implicit ctx: Context): Tree =
+    val stats = tree.stats.flatMap {
+      case Typed(Block(stats, expr), _) if isPureExpr(expr) => stats
+      case stat => if !stat.symbol.isConstructor && isPureExpr(stat) then Nil else List(stat)
+    }
+    cpy.Block(tree)(stats, tree.expr)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/PureStats.scala:28]: This implementation copies all blocks which leads in practice to large scale tree rewriting & allocation even if there are no pure statements. I'd try this instead:
```scala
val stats = Trees.flatten(
  tree.stats.mapConserve {
    case Typed(Block(stats, expr), _) if isPureExpr(expr) => Thicket(stats)
    case stat if !stat.symbol.isConstructor && isPureExpr(stat) => EmptyTree
    case stat => stat
  })
```
(flatten avoids tree copying if possible).

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PureStats.scala:30]: That variant works well

File: compiler/src/dotty/tools/dotc/transform/PureStats.scala [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+  override def runsAfter: Set[String] = Set(Erasure.name)
+
+  override def transformBlock(tree: Block)(implicit ctx: Context): Tree =
+    val stats = Trees.flatten(
+    tree.stats.mapConserve {
+      case Typed(Block(stats, expr), _) if isPureExpr(expr) => Thicket(stats)
+      case stat if !stat.symbol.isConstructor && isPureExpr(stat) => EmptyTree
+      case stat => stat
+    })
+    cpy.Block(tree)(stats, tree.expr)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/PureStats.scala:30]: Since you're using `mapConserve` you may not need to call `Trees.flatten` and `cpy.Block`:
```scala
val stats = tree.stats.mapConserve { ... }
if stats eq tree.stats then tree
else cpy.Block(tree)(Trees.flatten(stats), tree.expr)
```
