### PR TITLE
Fix "NamedTuple type in match is parsed as named pattern"

### LINKED ISSUE #24917: NamedTuple type in match is parsed as named pattern
## Compiler version

3.8.1-RC1-bin-20260108-ea33a4d-NIGHTLY

## Minimized code

```scala
object test {
  ??? match {
    case _: (a: Int, b: String) => ???
  }
}
```

## Output

```scala
[error] ./summon_from_named_tuple.scala:3:13
[error] Named patterns cannot be used with <?>, because it is not a named tuple or case class
[error]     case _: (a: Int, b: String) => ???
[error]       
```

## Expectation

The code should compile.

### PR DESCRIPTION
**Pull request by lihaoyi**
Fixes #24917

Claude's explanation below:

> The issue was in compiler/src/dotty/tools/dotc/ast/Desugar.scala:1794. When desugaring a tuple, the code checked ctx.mode.is(Mode.Pattern) to decide whether to call adaptPatternArgs. However, when typing a type in a pattern (e.g., the type in _: (a: Int, b: String)), both Mode.Pattern AND Mode.Type are set because withMode(Mode.Type) adds to the existing mode bits rather than replacing them.

Also check the mode bits on the way out when choosing whether to keep the possibly reordered tuple, otherwise the type is broken.

### CODE REVIEW

File: tests/pos/i7247.scala [hunk 1]
```diff
@@ -0,0 +1,2 @@
+val x = "foo" match
+  case _: (a *: (b: Any)) => ???  // OK since (b: Any) is a named tuple type
```
Comment (som-snytt) [inline tests/pos/i7247.scala:2]: The comment was added to the original neg test, presumably as a TODO.

**Comment by lihaoyi** [comment]
Bump on this, could someone help merge it?

**Comment by som-snytt** [comment]
I expected quick eyes on my supplementary commit, but "NBD". I gave it a second glance. Did I write that code?

**Comment by tgodzik** [comment]
Looked good enough to me 😅
