### PR TITLE
Check method arguments with parametricity when static

### LINKED ISSUE #14460: Inner enum declarations cause initialization-checker error
## Compiler version

3.1.2-RC1

## Minimized code

```Scala
class Outer:
    enum MyEnum {
        case Case
    }
```

## Output

```scala
-- Error: tests/init/pos/inner-enum.scala:3:8 --------------------------------------------------------------------------
3 |        case Case
  |        ^
  |        Cannot prove that the value is fully initialized. May only use initialized value as method arguments.
  |
  |        The unsafe promotion may cause the following problem:
  |        Access non-initialized value $values. Calling trace:
  |         -> case Case	[ inner-enum.scala:3 ]
```

## Expectation

When compiling with the `-Ysafe-init` flag this declaration should pass.

### PR DESCRIPTION
**Pull request by Xavientois**
Closes #14460, #14751

When a global static is called, allow for a cold argument if the corresponding parameter is not `Matchable`.

When merged, this PR will bring the number of safe-init warnings from bootstrapping the compiler down to 23.

### CODE REVIEW

**Comment by Xavientois** [comment]
@olhotak @liufengyun This PR replaces https://github.com/lampepfl/dotty/pull/14751. It is currently incomplete, as I am unsure how to check whether a param is a type variable. Additionally, it fails the added test due to the parameters of `Array.apply` being `Matchable`.

Do you have any suggestions regarding this?

**Comment by olhotak** [comment]
It shouldn't matter whether it's a type variable or not, only whether it's a subtype of Matchable or not. A type variable whose upper bound is a subtype of Matchable wouldn't be safe to consider parametric, while a non-type-variable parameter type of Any is parametric.

Which apply is it (Array has many of them)? In `def apply[T : ClassTag](xs: T*): Array[T]`, the parameter type is `T*`, and `T` is not a subtype of Matchable.

**Comment by Xavientois** [comment]
> It shouldn't matter whether it's a type variable or not, only whether it's a subtype of Matchable or not. A type variable whose upper bound is a subtype of Matchable wouldn't be safe to consider parametric, while a non-type-variable parameter type of Any is parametric.

I agree, but we previously discussed that an special case needed to be made in order to allow for calls to `wrapRefArray` as can be seen in the desugared code  [here](https://github.com/lampepfl/dotty/issues/14460#issuecomment-1056983510).

> Which apply is it (Array has many of them)? In `def apply[T : ClassTag](xs: T*): Array[T]`, the parameter type is `T*`, and `T` is not a subtype of Matchable.

It appears to be [this one](https://www.scala-lang.org/api/2.13.3/scala/Array$.html#apply[T](xs:T*)(implicitevidence$5:scala.reflect.ClassTag[T]):Array[T]).

**Comment by Xavientois** [comment]
This solution does mean that we can pass cold values to `println`, such as with the test `early-promote2.scala`:

```Scala
class M {
  println(this)       // error (This line no longer causes an error)
  foo()
  private val a = 5   // error
  def foo() = a
}
```

**Comment by Xavientois** [comment]
> It seems to suggest we should always check for type parameters. This way, we can avoid unsafe usage like `println`.

What sort of check are you picturing? The `methodType` for `println` is
```
MethodType(List(x), List(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)), TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit))
```

**Comment by liufengyun** [comment]
> > It seems to suggest we should always check for type parameters. This way, we can avoid unsafe usage like `println`.
> 
> What sort of check are you picturing? The `methodType` for `println` is
> 
> ```
> MethodType(List(x), List(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)), TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit))
> ```

I suggest always check `paraInfo.isInstanceOf[TypeRef] && paraInfo.symbol.isTypeParam && !(paraInfo <: defn.MatchableType)`

**Comment by olhotak** [comment]
Just so we're clear, in theory, requiring the parameter type to be a type variable wouldn't be any more sound than just allowing `Any`, so we're talking about a heuristic. For example, the following compiles:
```scala
def myPrintln[T](x: T) = println(x)
```
Then I can bypass any warning on `println` by calling `myPrintln` instead.

That said, allowing initialization to skip parametric parameters only if their types are type variables may well be a good heuristic. One worry I'd have is explaining it to users: if you do or don't get a warning in a certain case, how do you explain to users why you are/are not supposed to get a warning?

For now, since @Xavientois has limited time, I propose to implement it and we can revisit the heuristic later.

**Comment by Xavientois** [comment]
> I suggest always check paraInfo.isInstanceOf[TypeRef] && paraInfo.symbol.isTypeParam && !(paraInfo <: defn.MatchableType)

@liufengyun After making the change, we are now back to failing the cases this PR was originally made to handle. If I use "or" rather than "and", it behaves exactly the same as if the `isTypeParam` clause was not there. Is that clause incorrect?

**Comment by liufengyun** [comment]
> > I suggest always check paraInfo.isInstanceOf[TypeRef] && paraInfo.symbol.isTypeParam && !(paraInfo <: defn.MatchableType)
> 
> @liufengyun After making the change, we are now back to failing the cases this PR was originally made to handle. If I use "or" rather than "and", it behaves exactly the same as if the `isTypeParam` clause was not there. Is that clause incorrect?

Do you mean the enum test case? The condition looks reasonable, it's hard to tell how we should change it. It would be nice to debug why the check is false.

**Comment by Xavientois** [comment]
> It would be nice to debug why the check is false.

@liufengyun  It looks like, for `println` and `apply`, it is not a type param, thus causing the tests to fail.

The tests in question are:
- tests/init/pos/inner-enum-multi-variant.scala
- tests/init/pos/inner-enum.scala
- tests/init/pos/enum-ordinal.scala
- tests/init/pos/enum-desugared.scala
- tests/init/pos/inner-case.scala
- tests/init/pos/some-this.scala
- tests/init/pos/inner-new.scala

If I try to change it from `isTypeParam && !isMatchable` to `isTypeParam || !isMatchable`, it causes a number of negative tests to fail.

**Comment by liufengyun** [comment]
> @liufengyun It looks like, for println and apply, it is not a type param, thus causing the tests to fail.

That is kind of expected, I think we do want to warn in those cases.

For other failing tests, they need to be analyzed case by case. If you are time-constrained, I'd suggest leaving the PR as it is. @olhotak and I can take it over. There are some design changes of parametricity coming up during our last meeting.

**Comment by Xavientois** [comment]
> That is kind of expected, I think we do want to warn in those cases.
I don't think we want to warn for`apply` since `Array.apply`, `List.apply`, etc. since they were the specific cases that prompted the need for parametricity in the first place.

The individual cases that fail due to parametricity that I am uncertain about are the following:
- tests/init/neg/early-promote.scala
- tests/init/neg/by-name-error.scala
- tests/init/neg/inlined-method.scala
- tests/init/neg/inner25.scala
- tests/init/neg/early-promote2.scala
- tests/init/neg/inner11.scala
- tests/init/neg/promotion-loop.scala
- tests/init/neg/scodec.scala
- tests/init/neg/leak-warm.scala
- tests/init/neg/inner-loop.scala
- tests/init/neg/t3273.scala

@liufengyun [Above](https://github.com/lampepfl/dotty/pull/14916#issuecomment-1098302659), you mentioned:
> It seems to suggest we should always check for type parameters. This way, we can avoid unsafe usage like println.

I think that this will help with many of these test cases, but we would need to find another way than using `isTypeParam`, since that breaks the test cases that we want to pass (the enum ones based on `Array.apply`)

**Comment by liufengyun** [comment]
> I think that this will help with many of these test cases, but we would need to find another way than using isTypeParam, since that breaks the test cases that we want to pass (the enum ones based on Array.apply)

For `Array.apply` and `List.apply`,  it's strange that `isTypeParam` is not true, as those methods do have a type parameter `T`.

**Comment by Xavientois** [comment]
@liufengyun I figured out the problem. We needed to do `info.repeatedToSingle.isInstanceOf[TypeParamRef]`.

The only remaining test to figure out is `cold-insert-hot-array`. It was added in https://github.com/lampepfl/dotty/pull/14895 to prevent this case from being accepted, but the current parametricity approach permits this code. The case is as follows:

```scala
object A:
  def foo[T](x: T, array: Array[T]): Unit = array(0) = x

class B {
  var a = new Array[B](2)
  A.foo(this, a) // error
  println(a(0).i)
  val i = 99
}
```

Should I remove this test case in order to merge this PR or should we figure out a way to trigger a warning for this case?

**Comment by liufengyun** [comment]
> @liufengyun I figured out the problem. We needed to do info.repeatedToSingle.isInstanceOf[TypeParamRef].

Great you figured it out 👍  The argument is varargs, thus we need to get the component. Here indeed we cannot test the symbol, because in Scala 3 the method type uses `TypeParamRef` and `ParamRef` instead of symbols --- the parameter symbols are only visible inside the method (Sorry for the incorrect code snippet).

For the failing test you mentioned, that's exactly the purpose of it: to defend against unsound solutions. The solution @olhotak and I discussed is the following:

- A non-hot method argument is allowed if the declared parameter type is a type parameter `T` with `Any` as its upper bound
- For any non-hot argument allowed for a type parameter `T`, the other arguments should either correspond to a parameter type that is `T` or that does not contain `T` as a component.
- If any non-hot method argument is allowed above, the result value of the method call is assumed to be Cold.

The method `Type.existsPart` will be useful for the 2nd test.

**Comment by Xavientois** [comment]
@liufengyun Just tried the approach you suggested. It does fix that failing `cold-insert-hot-array` test case but also breaks the following four (the cases embodying the original motivator for this PR):

- tests/init/pos/enum-desugared.scala
- tests/init/pos/inner-enum.scala
- tests/init/pos/inner-enum-multi-variant.scala
- tests/init/pos/enum-ordinal.scala

The problem is that the signature of the apply method has an Applied Type as seen here: https://www.scala-lang.org/api/current/scala/Array$.html#apply[T](xs:T*)(implicitevidence$5:scala.reflect.ClassTag[T]):Array[T]

`def apply[T](xs: T*)(implicit arg0: ClassTag[T]): Array[T]`

The `implicit` `arg0` breaks the second condition you outlined:

> For any non-hot argument allowed for a type parameter T, the other arguments should either correspond to a parameter type that is T or that does not contain T as a component.

Any ideas on how to work around this?

**Comment by liufengyun** [comment]
> The `implicit` `arg0` breaks the second condition you outlined:
> 
> > For any non-hot argument allowed for a type parameter T, the other arguments should either correspond to a parameter type that is T or that does not contain T as a component.
> 
> Any ideas on how to work around this?

Thanks for trying it. In this case, we can specialize the logic to allow all arguments of the type `ClassTag[?]`.

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala [hunk 1]
```diff
@@ -600,6 +601,25 @@ object Semantic {
         || (meth eq defn.Object_ne)
         || (meth eq defn.Any_isInstanceOf)
 
+      def checkArgsWithParametricity() =
+        val methodType = atPhaseBeforeTransforms { meth.info.stripPoly }
+        var allArgsPromote = true
+        var singleParamSet = immutable.HashSet.from(methodType.paramInfoss.flatten.map(_.repeatedToSingle))
+        val errors = methodType.paramInfoss.flatten.zip(args).flatMap { (info, arg) =>
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:608]: There seems to be no need for `immutable.HashSet`. Will something like the following work?

``` Scala
val allParamTypes = methodType.paramInfoss.flatten.map(_.repeatedToSingle)
val errors = allParamTypes.zip(args).flatMap { (info, arg) =>
```

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala [hunk 2]
```diff
@@ -600,6 +601,25 @@ object Semantic {
...
+          val singleInfo = info.repeatedToSingle
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:609]: There is no need for `info.repeatedToSingle` with the changes above.

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala [hunk 3]
```diff
@@ -600,6 +601,25 @@ object Semantic {
...
+          val isMatchable = defn.NothingType <:< singleInfo && singleInfo <:< defn.MatchableType
+          val isTypeParam = singleInfo.isInstanceOf[TypeParamRef]
+          val otherParamContains = singleParamSet.exists( param => { param != singleInfo && param.typeSymbol != defn.ClassTagClass && singleInfo.occursIn(param) } )
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:612]: Here, we only need to check other parameters if `isTypeParam` is true, and we need to check the bounds of the current type parameter.

The following is just a sketch for reference:

```Scala
val errors = arg.promote
allArgsPromote = allArgsPromote && errors.isEmpty

info match
case typeParamRef: TypeParamRef =>
  val bounds = typeParamRef.info.bounds
  def otherParamContains = allParamTypes.exists { param => 
    param != info && param.typeSymbol != defn.ClassTagClass && info.occursIn(param)
  }
  if bounds.lo <:< defn.NothingType && defn.AnyType <:< bounds.hi && !otherParamContains then Nil
  else errors
case _ =>
  errors
```

The reason we want to check the actual bounds is to avoid unsoundness when there are multiple type parameters, such as the following:

```
def foo[S, S <: T](x: S, arr: Array[T]) = arr(0) = x
```

**Review by liufengyun — APPROVED** [review]
Well done @Xavientois 🎉 

I left some comments for your reference.

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala (hunk 1 above)
Comment (Xavientois) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:608]: The reason I used the HashSet was to improve the runtime complexity of checking that no other parameter type contains the given type.

Also, just constructing an iterator like you suggest won't work since it needs to iterated over for each parameter. They need to be stored in a separate data collection for this reason. The reason I chose an `immutable.HashSet` is because `Type` can be hashed and the `Set` eliminated duplicates implicitly.  I could use a different collection type if you have a better one in mind.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:608]: > Also, just constructing an iterator like you suggest won't work since it needs to iterated over for each parameter. They need to be stored in a separate data collection for this reason

It seems possible to use `allParamTypes` for the same purpose. Note that method parameters are usually small, and the chance that they have the same type in our setting is even smaller.  Introducing HashSet here seems to be an unnecessary optimization.

Comment (Xavientois) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:608]: I just checked the function signatures for `flatten` and `map`. I mistakenly assumed that they did not return a `List`. The approach you are proposing should work!

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala [hunk 4]
```diff
@@ -600,6 +600,24 @@ object Semantic {
...
         || (meth eq defn.Any_isInstanceOf)
 
+      def checkArgsWithParametricity() =
+        val methodType = atPhaseBeforeTransforms { meth.info.stripPoly }
+        var allArgsPromote = true
+        var allParamTypes = methodType.paramInfoss.flatten.map(_.repeatedToSingle)
+        val errors = allParamTypes.zip(args).flatMap { (info, arg) =>
+          val isTypeParam = info.isInstanceOf[TypeParamRef]
+          val isWithinBounds = info.bounds.lo <:< defn.NothingType && defn.AnyType <:< info.bounds.hi
+          def otherParamContains = allParamTypes.exists( param => { param != info && param.typeSymbol != defn.ClassTagClass && info.occursIn(param) } )
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:610]: Nitpick:
```suggestion
          def otherParamContains = allParamTypes.exists { param => param != info && param.typeSymbol != defn.ClassTagClass && info.occursIn(param) } 
```

**Review by liufengyun — APPROVED** [review]
LGTM, thank you @Xavientois  🎉

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala (hunk 4 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:610]: BTW, there seems to be a typo: `param.occursIn(info)` instead of `info.occursIn(param)`?

What about adding the following as a neg test?

```Scala
object A:
  def foo[T, S <: T](x: S, array: Array[T]): Unit = array(0) = x

class B:
  var a = new Array[B](2)
  A.foo(this, a) // error
  println(a(0).i)
  val i = 99
```

Comment (Xavientois) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:610]: > BTW, there seems to be a typo: `param.occursIn(info)` instead of `info.occursIn(param)`?

`info.occursIn(param)` is correct as we want to check whether the type `T` occurs in any of the other parameters.

> What about adding the following as a neg test?

That test was already added in https://github.com/lampepfl/dotty/pull/14895. It passes with the current code

Comment (Xavientois) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:610]: @liufengyun Just tried adding the test and it fails due to not triggering a warning. This test case is more difficult to handle because we can't rely on the `occursIn` function.

After this PR is merged, I can open an issue to handle this test case.

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala [hunk 5]
```diff
@@ -600,6 +600,24 @@ object Semantic {
...
+          val isTypeParam = info.isInstanceOf[TypeParamRef]
+          val isWithinBounds = info.bounds.lo <:< defn.NothingType && defn.AnyType <:< info.bounds.hi
+          def otherParamContains = allParamTypes.exists { param => param != info && param.typeSymbol != defn.ClassTagClass && info.occursIn(param) }
+          val errors = arg.promote
+          allArgsPromote = allArgsPromote && errors.isEmpty
+          // A non-hot method argument is allowed if the corresponding parameter type is a
+          // type parameter T with Any as its upper bound and Nothing as its lower bound.
+          // the other arguments should either correspond to a parameter type that is T
+          // or that does not contain T as a component.
+          if isTypeParam && !isWithinBounds && !otherParamContains then Nil else errors
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/init/Semantic.scala:617]: `!isWithinBounds` look spurious, should it be `isWithinBounds`?

File: compiler/src/dotty/tools/dotc/transform/init/Semantic.scala (hunk 4 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/init/Semantic.scala]: > we can't rely on the occursIn function

That is a little strange. BTW, for the new example, `isWithinBounds` should be false(the upper bound of `S` is `T`, which is not `Any`), thus no reasoning by parametricity will be used here.

It seems the problem lies in how to retrieve bounds of a `TypeParamRef`. `info.bounds` will not return the bounds, the following will help:

```Scala
info match
case typeParamRef: TypeParamRef =>
    val bounds = typeParamRef.info.bounds
case _ =>
 ```

**Review by liufengyun — APPROVED** [review]

**Review by olhotak — APPROVED** [review]
LGTM
