### PR TITLE
Fix retained flags in exports

### LINKED ISSUE #19301: `infix` modifier lost when exporting a method/type
## Compiler version

`3.4.0-RC1-bin-20231207-16f1680-NIGHTLY`

## Minimized code

```Scala
object Extensions:
  extension (arg1: Int) infix def X (arg2: Int): Int = arg1 * arg2
  infix type X[A, B]
export Extensions.*
val x = 1 X 2
type Foo = Int X Int
```

## Output

```scala
Alphanumeric method X is not declared infix; it should not be used as infix operator.
Instead, use method syntax .X(...) or backticked identifier `X`.
The latter can be rewritten automatically under -rewrite -source 3.4-migration.
Alphanumeric type X is not declared infix; it should not be used as infix operator.
Instead, use prefix syntax X[...] or backticked identifier `X`.
The latter can be rewritten automatically under -rewrite -source 3.4-migration.
```

## Expectation
No warning.

### PR DESCRIPTION
**Pull request by hamzaremmal**
Fix #19301

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Flags.scala [hunk 1]
```diff
@@ -532,8 +532,17 @@ object Flags {
   /** Flags that can apply to a module class */
   val RetainedModuleClassFlags: FlagSet = RetainedModuleValAndClassFlags | Enum
 
-  /** Flags retained in export forwarders */
-  val RetainedExportFlags = Given | Implicit | Inline | Transparent
+  /** Flags retained in term export forwarders */
+  val RetainedExportTermFlags = Infix | Given | Implicit | Inline | Transparent | Erased | HasDefaultParams | NoDefaultParams | ExtensionMethod
+  // TODO: SHOULD WE ADD: ConstructorProxy ?
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Flags.scala:537]: I don't think so: a method that calls a constructor proxy is not itself a constructor proxy.

File: compiler/src/dotty/tools/dotc/core/Flags.scala [hunk 2]
```diff
@@ -532,8 +532,17 @@ object Flags {
...
+
+  val MandatoryExportTermFlags = Exported | Method | Final
+
+  /** Flags retained in type export forwarders */
+  val RetainedExportTypeFlags = Infix
+  // TODO: SHOULD WE ADD: TransparentType ?
```
[the remark this answers is not in the document]
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/core/Flags.scala:543]: Good point

File: compiler/src/dotty/tools/dotc/core/Flags.scala (hunk 1 above)
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/core/Flags.scala:537]: I will drop the todos
