### PR TITLE
Fix #3912: Account for units and blocks in inline and macros

### LINKED ISSUE #3912: Macro with Unit type splicing non Unit fails with `splice outside quotes`
```
import scala.quoted._
object Macros {
  inline def foo(): Unit = ~impl()
  def impl(): Expr[Int] = '(1)
}
```
```
import scala.quoted._
import Macros._
class Test {
  val a: Unit = foo()
}
```

fails with 
```
5 |    ~impl()
  |    ^^^^^^^
  |    splice outside quotes
```

because `inline def foo(): Unit = ~impl()` is transformed to 
`inline def foo(): Unit = { ~impl(); () }`, which is correct.

We need a better error message for this.

### PR DESCRIPTION
**Pull request by biboudis**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 1]
```diff
@@ -338,5 +346,20 @@ class ReifyQuotes extends MacroTransformWithImplicits {
...
+
+    /** InlineSplice is used to detect cases where the expansion
+     *  consists of a (possibly multiple & nested) block or a sole expression.
+     */
+    object InlineSplice {
+      def unapply(tree: Tree)(implicit ctx: Context): Option[Select] = {
+        tree match {
+          case expansion: Select if expansion.symbol.isSplice =>
+            Some(expansion)
+          case Block(List(stat), Literal(Constant(()))) => unapply(stat)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: Can you give an example of when this happen?

Comment (biboudis) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: Yes, this is related to the implicit conversion related to value discarding (simply put when an `e` returns a value and it's called from a function of expected type `Unit` and it is converted into `{ e; () }`). This manifested in quoted code as well.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: For example `inline foo: Unit = 4` will become `inline foo: Unit = { 4; () }` and then be inlined as `{ 4; () }`. In our case we have a `~xyz` instead of `4`.

Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: Got it! I would add a comment explaining why this is needed (i.e. the compiler can insert `()`).

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 2]
```diff
@@ -338,5 +346,20 @@ class ReifyQuotes extends MacroTransformWithImplicits {
             checkLevel(mapOverTree(enteredSyms))
         }
       }
+
+    /** InlineSplice is used to detect cases where the expansion
+     *  consists of a (possibly multiple & nested) block or a sole expression.
+     */
+    object InlineSplice {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: I don't know how performance sensitive this code is but you could return a `Tree` instead of `Option[Select]` to avoid boxing (and `EmptyTree` instead of `None`)

Comment (biboudis) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: We need that `.get` method on `unapply`s return type so isn't `Option` unavoidable?

Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: I believe `Tree` qualifies for both [product pattern](http://dotty.epfl.ch/docs/reference/changed/pattern-matching.html#product-pattern) and [name based pattern](http://dotty.epfl.ch/docs/reference/changed/pattern-matching.html#name-based-pattern). And scalac supports name based pattern

**Comment by odersky** [comment]
What's the relationship with #4019?

**Comment by nicolasstucki** [comment]
No relationship.

**Comment by nicolasstucki** [comment]
Needs rebase

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 3]
```diff
@@ -321,16 +321,22 @@ class ReifyQuotes extends MacroTransformWithImplicits {
...
             // To maintain phase consistency, we move the binding of the this parameter into the spliced code
             val (splicedBindings, stagedBindings) = bindings.partition {
               case vdef: ValDef => vdef.symbol.is(Synthetic) // Assume that only _this bindings are tagged with Synthetic
               case _ => false
             }
+
             val tree1 =
               if (level == 0) cpy.Inlined(tree)(call, stagedBindings, Splicer.splice(seq(splicedBindings, body)))
               else seq(stagedBindings, cpy.Select(expansion)(cpy.Inlined(tree)(call, splicedBindings, body), name))
             transform(tree1)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: This should be a`tree2`

`val tree2 = transform(tree1)`

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 4]
```diff
@@ -321,16 +321,22 @@ class ReifyQuotes extends MacroTransformWithImplicits {
...
+
+            // due to value-discarding which converts an { e } into { e; () })
+            if (tree.tpe =:= defn.UnitType) Block(tree1 :: Nil, Literal(Constant(())))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: And use `tree2` here and in next line

**Comment by biboudis** [comment]
Approve @nicolasstucki? ⭐️
