### PR TITLE
Fix #7264: Propagate prototypes in quoted type patterns

### LINKED ISSUE #7264: Missing type bound for quoted type splices in patterns
## minimized code

```Scala
import scala.quoted._
class Foo {
  def f[T](t: Type[T])(given QuoteContext) = t match {
    case '[ *:[Int, $t] ] =>
  }
}
```
fails with
```scala
4 |    case '[ *:[Int, $t] ] =>
  |                     ^
  |                   Type argument $t does not conform to upper bound Tuple 
```

## expectation
Should compile

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

File: tests/pos/i7264b.scala [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import scala.quoted._
+class Foo {
+  def f[T2: Type](e: Expr[T2])(given QuoteContext) = e match {
+    case '{ $x: *:[Int, $t] } =>
```
Comment (nicolasstucki) [inline tests/pos/i7264b.scala]: @odersky  unfortunately this case still has the same issue. Note that this time it is in a type within quoted Expr pattern.

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala [hunk 2]
```diff
@@ -321,7 +321,7 @@ trait QuotesAndSplices {
       ctx.error(missingArgMsg(qctx, defn.QuoteContextClass.typeRef, ""), ctx.source.atSpan(tree.span))
 
     val quoted = tree.quoted
-    val exprPt = pt.baseType(if quoted.isType then defn.QuotedTypeClass else defn.QuotedExprClass)
+    val exprPt = pt.baseType(defn.QuotedExprClass)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala]: I don't understand how this can be correct. If `pt` is `quoted.Type[...]` then `pt.baseType` is `NoType` and therefore `quotedPt` is `Any`. Is that what we want? If yes, it would be good to express that logic more directly instead of relying on a `baseType` to fail.

**Comment by peykaz** [comment]
hello guys. I need your help. in my website every time I fix a problem with my friend’s mobile. What can I do to prevent these errors? my site is for news https://peyk.az/ru. and already tired of struggling with etomi errors .

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala]: Added it again

**Comment by nicolasstucki** [comment]
Rebased
