### PR TITLE
Approximate MatchTypes with lub of case bodies, if non-recursive

### LINKED ISSUE #19710: Regression in match types combined with type lambda
Based on forum post: https://users.scala-lang.org/t/scala-3-how-do-we-make-a-lambda-type-conform-to-a-subtype/9805

## Compiler version
3.3.1
Last good release: 3.3.1-RC1-bin-20230514-b0ccf40-NIGHTLY
First bad release: 3.3.1-RC1-bin-20230515-22b2259-NIGHTLY
Bisect points to d1d6c2e9536ce331316f741b9c1c4c0520cef787

## Minimized code

```Scala
import scala.util.NotGiven

type HasName1 = [n] =>> [x] =>> x match {
    case n => true
    case _ => false
  }
@main def Test = {
  summon[HasName1["foo"]["foo"] =:= true]
  summon[NotGiven[HasName1["foo"]["bar"] =:= true]]
  summon[Tuple.Filter[(1, "foo", 2, "bar"), HasName1["foo"]] =:= Tuple1["foo"]] // error
}

```

## Output

```scala
-- [E057] Type Mismatch Error: /Users/wmazur/projects/dotty/bisect/main.scala:10:44 
10 |  summon[Tuple.Filter[(1, "foo", 2, "bar"), HasName1["foo"]] =:= Tuple1["foo"]]
   |                                            ^
   |Type argument HasName1[("foo" : String)] does not conform to upper bound [_] =>> Boolean
   |
   |Note: a match type could not be fully reduced:
   |
   |  trying to reduce  HasName1[("foo" : String)]
   |
   | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation
Should comile (probably)

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #19710

### CODE REVIEW

**Comment by sjrd** [comment]
At the very least, it does not correspond to anything that was ever specified or documented. Doing that would require a dedicated rule in the type system.

Off the top of my head, I don't see why it would be unsound. But that's also assuming that type bounds are correctly checked in the bodies, which IIUC is not done yet?

**Comment by dwijnand** [comment]
> But that's also assuming that type bounds are correctly checked in the bodies, which IIUC is not done yet?

I believe so:

https://github.com/lampepfl/dotty/blob/98efdab3c3edaac379c07b979f9ff103bf13cd07/compiler/src/dotty/tools/dotc/typer/Typer.scala#L2378-L2379

**Comment by EugeneFlesselle** [comment]
@dwijnand Some issues had been discussed in #8085, perhaps filtering for recursive match-types is enough to avoid then though.

**Comment by dwijnand** [comment]
I like the approach of caching the lub once during typing, much smarter.  I'll try that change.

**Comment by EugeneFlesselle** [comment]
> I like the approach of caching the lub once during typing, much smarter. I'll try that change.

I'm wondering however if doing the check during subtyping might make use of a narrowed context ? 
Or more generally, when it might be useful to recompute the bound. For example if a match type is inherited and the scrutinee has been refined ? 

In any case, I think this would be great improvement.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -2863,6 +2863,8 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
         disjointnessBoundary(tp.effectiveBounds.hi)
       case tp: ErrorType =>
         defn.AnyType
+      case NoType => // ParamRef#superTypeNormalized can return NoType
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: That seems to be a problem with `ParamRef#superTypeNormalized` rather than with `disjointnessBoundary`.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: What should `superTypeNormalized` do?

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: It should return the declared type of the corresponding param, which is supposed to be its `underlying`. I don't see a scenario in which `superTypeNormalized` should ever return `NoType`, *except* possibly for `AnyKind` itself.

Comment (EugeneFlesselle) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: Apparently, it can happen that it is not initialised:
https://github.com/lampepfl/dotty/blob/e994cf06eeee23e8a55a086907957e43140f2112/compiler/src/dotty/tools/dotc/core/Types.scala#L4690-L4695

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: That sort of explains it, although it's still concerning that we're attempting to read it from `provablyDisjoint` when it hasn't been initialized yet. Looks like a time bomb waiting to explode later due to weird compilation order issues.

Comment (EugeneFlesselle) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: Yes, and this is not the only case, I ran into a similar issue where normalisation relies on the `underlying` type, which is not always set as expected. For a `TypeRef`, it goes through the denotation info, of which the completion seemed a bit unpredictable to me (heavily influenced by small changes in where things happen to be reduced). 

Also (maybe) unrelated the normalization depends on the gadt ctx which doesn't seem to be reliably populated when using `NamedType`s.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: I guess I should've opted for AnyKind rather than Any, as the more conservative approach.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: I would still be less uncomfortable if we specifically handled `ParamRef` to deal with its `superTypeNormalized` returning `NoType`; instead of having this "catch-all" `NoType`. That would limit the blast radius of this workaround. We should also clearly comment that it is a workaround.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2866]: Sure thing.

**Review by sjrd — APPROVED** [review]
