### PR TITLE
Detect given bindings in for generators

### LINKED ISSUE #12170: Given patterns are never exhaustive, causing withFilter desugaring
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
import scala.compiletime.error

object BadFilters {
  inline def withFilter(f: Int => Boolean): BadFilters.type = error("Unexpected withFilter call")
  def foreach(f: Int => Unit): Unit = f(42)
}

@main def works = 
  for {
    x: Int <- BadFilters
  } println(x)

@main def breaks =
  for {
    given Int <- BadFilters
  } println(summon[Int])
```

## Output

Fails to compile `breaks` with `Unexpected withFilter call`

## Expectation

Compiles and prints:

```
42
42
```

---
The pattern `x: Int` is considered exhaustive, causing `withFilter` to not be emitted in `works`, while the pattern `given Int` isn't, so `withFilter` is emitted and `breaks` breaks.

### PR DESCRIPTION
**Pull request by odersky**
These are considered irrefutable, just like normal bindings.

Fixes #12170

### CODE REVIEW

File: tests/run/i12170.scala [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import scala.compiletime.error
+
+object BadFilters:
+  def withFilter(f: Int => Boolean): BadFilters.type = ???//error("Unexpected withFilter call")
```
Comment (nicolasstucki) [inline tests/run/i12170.scala:4]:
```suggestion
  inline def withFilter(f: Int => Boolean): BadFilters.type = error("Unexpected withFilter call")
```

**Comment by griggt** [comment]
Seems like this also fixes #10990

**Review by nicolasstucki — CHANGES_REQUESTED** [review]
Tests must be added
