### PR TITLE
 Fix #6415: Enable REPL code completion for opaque types

### LINKED ISSUE #6415: Code completion does not work in REPL for opaque types
This is becuase `opaque type T = Int` is desugared to `type T = T.T`, and autocompletion targets `T.T` instead of `Int`. The reason is that the code meant for autocompletion is inferred based on the position of the cursor in the user input. This position is oblivious to the desugaring and other transformation done to the tree as part of the typecheck for code completion. See #6414 for some discussion.

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
`opaque type T = Int` desugars to (roughly):

```scala
opaque type T = T.T
object T {
  opaque type T = Int
}
```

So one `opaque type T` desugars to two `opaque type T`'s. One of them is synthetic – the first one. It shadows the second one during code completion due to the fact that it has the same span.

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
(the first commit is from #6414)

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -820,7 +820,7 @@ object desugar {
       val moduleName = tdef.name.toTermName
       val localRef = Select(Ident(moduleName), tdef.name)
       localRef.pushAttachment(SuppressAccessCheck, ())
-      val aliasType = cpy.TypeDef(tdef)(rhs = completeForwarder(localRef))
+      val aliasType = cpy.TypeDef(tdef)(rhs = completeForwarder(localRef)).withSpan(Span(MaxOffset))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala]: Synthetic trees should always have a position where the start and the end are identical, that's how we distinguish them from user-written trees, but they should still point to the closest position where they were defined in the source code (otherwise, error messages involving them will point to the wrong line) so you should do `.withSpan(tdef.span.startPos)`

Comment (anatoliykmetyuk) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: Ok, this also works
