### PR TITLE
Fix links to unexisting types sites

### LINKED ISSUE #13867: Scaladoc: Do not link to private members
### Description
In `Predef` [page](https://dotty.epfl.ch/api/scala/Predef$.html) it says that `Predef` extends `LowPriorityImplicits`. But the link for `LowPriorityImplicits` leads to [`404`](https://dotty.epfl.ch/api/scala/LowPriorityImplicits.html), since it is a private class in package `scala`.
### Expectations
Either information about private classes shouldn't be shown or there should be no link.

### PR DESCRIPTION
**Pull request by pikinier20**
closes #13867

### CODE REVIEW

File: project/Build.scala [hunk 1]
```diff
@@ -319,10 +319,11 @@ object Build {
 
   private lazy val currentYear: String = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR).toString
 
-  lazy val scalacOptionsDocSettings = Seq(
-      "-external-mappings:" +
-        ".*scala/.*::scaladoc3::https://dotty.epfl.ch/api/," +
-        ".*java/.*::javadoc::https://docs.oracle.com/javase/8/docs/api/",
+  def scalacOptionsDocSettings(includeExternalMappings: Boolean = true) = {
```
Comment (KacperFKorban) [inline project/Build.scala:322]: Is this part needed for this fix?

**Review by KacperFKorban — COMMENTED** [review]
The code looks good.
Could you fix the build, so I can click through it?

File: project/Build.scala (hunk 1 above)
Comment (pikinier20) [reply project/Build.scala:322]: Yes, because by default we were adding a external mapping to dotty.epfl.ch in Scala documentation. Our mechanism to resolve links tries to match external mapping for symbols that are not present in docs. Since the private API was not present in docs, Scaladoc matched external mapping for it and generated unexisting link

Comment (KacperFKorban) [reply project/Build.scala:322]: ok, makes sense

Comment (BarkingBad) [reply project/Build.scala:322]: Isn't it a general problem? I mean, maybe we should not try to match any link for members that are private, not workaround it this way

Comment (pikinier20) [reply project/Build.scala:322]: That's why I introduced changes with filtering symbols that shouldn't be visible. Maybe we should once more go through whole code that gathers symbols and check if we filter all symbols correctly. 

I removed the external link to dotty because it was redundant and should never be there.

**Review by BarkingBad — APPROVED** [review]
