### PR TITLE
Fix #3917: Properly desugar `Ident`

### LINKED ISSUE #3917: Compiler crash: "failure to construct path"
```scala
class Hello {
  var verbose = false
}

object Main extends Hello {
  def test = {
    verbose = true
  }
}
```
```
dotc tests/allan/Test.scala
exception while typing Hello.this of class class dotty.tools.dotc.ast.Trees$This # 227
exception while typing Hello.this.verbose_= of class class dotty.tools.dotc.ast.Trees$Select # 228
exception while typing Hello.this.verbose_=(true) of class class dotty.tools.dotc.ast.Trees$Apply # 229
exception while typing {
  Hello.this.verbose_=(true)
} of class class dotty.tools.dotc.ast.Trees$Block # 230
exception while typing def test: Unit = 
  {
    Hello.this.verbose_=(true)
  } of class class dotty.tools.dotc.ast.Trees$DefDef # 231
exception while typing @scala.annotation.internal.SourceFile("tests/allan/Test.scala") final module 
  class
 Main() extends Hello() { 
  def test: Unit = 
    {
      Hello.this.verbose_=(true)
    }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 233
exception while typing package <empty> {
  @scala.annotation.internal.SourceFile("tests/allan/Test.scala") class Hello()
     extends
   Object() { 
    <accessor> def verbose: Boolean = false
    <accessor> def verbose_=(x$1: Boolean): Unit = ()
  }
  final lazy module val Main: Main = new Main()
  @scala.annotation.internal.SourceFile("tests/allan/Test.scala") final module 
    class
   Main() extends Hello() { 
    def test: Unit = 
      {
        Hello.this.verbose_=(true)
      }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 234
exception occurred while compiling tests/allan/Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: failure to construct path from method test/object Main/package <empty>/package <root> to `this` of class Hello;
object Main does not have an outer accessor
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:36)
	at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.loop$1(ExplicitOuter.scala:386)
	at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.path$extension(ExplicitOuter.scala:392)
	at dotty.tools.dotc.transform.Erasure$Typer.typedThis(Erasure.scala:454)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1721)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:442)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1701)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:492)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1720)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:646)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1727)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1381)
	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:577)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1708)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1809)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1832)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:672)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1422)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1711)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1769)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1809)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1832)
	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:672)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1593)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1751)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1770)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:94)
	at dotty.tools.dotc.typer.Typer.op1$2(Typer.scala:1787)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1783)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1844)
	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:99)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:293)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:295)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:123)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:136)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:141)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:88)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:143)
	at dotty.tools.dotc.Run.compileSources(Run.scala:94)
	at dotty.tools.dotc.Run.compile(Run.scala:78)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:29)
	at dotty.tools.dotc.Driver.process(Driver.scala:127)
	at dotty.tools.dotc.Driver.process(Driver.scala:96)
	at dotty.tools.dotc.Driver.process(Driver.scala:108)
	at dotty.tools.dotc.Driver.main(Driver.scala:135)
	at dotty.tools.dotc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by allanrenucci** [comment]
This fix doesn't work. We cannot always prefix identifier by `this`:
```scala
object Foo {
  var verbose = false
}

object Bar {
  def test = {
    import Foo._
    verbose = true
  }
}
```

**Comment by allanrenucci** [comment]
Someone might want to take over this PR. I am not sure what is the proper way to fix the issue

**Comment by smarter** [comment]
We have code to transform Ident into Select, that may help: https://github.com/lampepfl/dotty/blob/02252a870f7eb510656632dca6d0f005d8754ee8/compiler/src/dotty/tools/dotc/transform/localopt/Simplify.scala#L152-L160

File: compiler/src/dotty/tools/dotc/ast/tpd.scala [hunk 1]
```diff
@@ -826,14 +826,19 @@ object tpd extends Trees.Instance[Type] with TypedTreeInfo {
...
-          case Ident(_) =>
-            val setter = tree.symbol.setter
-            assert(setter.exists, tree.symbol.showLocated)
-            ref(tree.symbol.setter)
-          case Select(qual, _) => qual.select(tree.symbol.setter)
+        val setter = tree.symbol.setter
+        assert(setter.exists, tree.symbol.showLocated)
+        val qual = tree match {
+          case id: Ident =>
+            id.tpe match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/tpd.scala]: There's already three versions of `desugarIdent` in the codebase. I suggest we try to replace them by a common version in tpd.scala or something like that instead of adding one more variation.

Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/ast/tpd.scala]: I am only interested in the prefix of the desugared ident. Should I still extract the functionality and do something like:
```scala
val qual = tree match {
  case id: Ident =>
    desugarIdent(id).asInstanceOf[Select].qual
  ...
```
This would create an unnecessary `Select` node

Comment (smarter) [reply compiler/src/dotty/tools/dotc/ast/tpd.scala]: we could have a `desugarIdentPrefix` method.

File: compiler/src/dotty/tools/dotc/ast/tpd.scala [hunk 2]
```diff
@@ -1012,5 +1011,21 @@ object tpd extends Trees.Instance[Type] with TypedTreeInfo {
     val encoding = ctx.settings.encoding.value
     if (file != null && file.exists) new SourceFile(file, Codec(encoding)) else NoSource
   }
+
+  /** Desugar identifier into a select node. Return None if not possible */
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/tpd.scala]: We don't usually use Option in the compiler, first, because of the allocation overhead, and second, because we usually have sentinel values that signal absence of a proper result. E.g. `EmptyTree` for trees. So I would just let `desugarIdent` return an `EmptyTree` if no rules apply.  That's more idiomatic. Hint: `orElse` works on empty trees.

I see there are quite a lot of uses of `desugarIdent`, and have the impression that most of these uses could be improved by going to EmptyTree. The use of Option.fold in JSCodeGen is particularly opaque.

**Comment by allanrenucci** [comment]
@OlivierBlanvillain Can you please review the last commit?

File: compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala [hunk 3]
```diff
@@ -444,8 +444,12 @@ class DottyBackendInterface(outputDirectory: AbstractFile, val superCallsMap: Ma
   def desugarIdent(i: Ident): Option[tpd.Select] = {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala]: I could not get rid of the `Option` here since the backend expects this signature

File: compiler/src/dotty/tools/dotc/transform/localopt/Simplify.scala [hunk 4]
```diff
@@ -154,14 +154,10 @@ object Simplify {
    *  System members are the only static final fields that are mutable.
    *  See https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.5.4
    */
-  @tailrec def isEffectivelyMutable(t: Tree)(implicit ctx: Context): Boolean = t match {
+  def isEffectivelyMutable(t: Tree)(implicit ctx: Context): Boolean = t match {
     case _ if t.symbol.is(Mutable) => true
-    case s: Select => s.symbol.owner == defn.SystemModule
-    case i: Ident  =>
-      desugarIdent(i) match {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/localopt/Simplify.scala]: I did not understand why desugaring was needed here because it doesn't change the symbol of the tree

File: compiler/src/dotty/tools/dotc/transform/localopt/Devalify.scala [hunk 5]
```diff
@@ -194,7 +194,7 @@ class Devalify extends Optimisation {
       readingOnlyVals(qual)
 
     case t: Ident if !t.symbol.is(Mutable | Method) && !t.symbol.info.dealias.isInstanceOf[ExprType] =>
-      desugarIdent(t).forall(readingOnlyVals)
+      !isEffectivelyMutable(t)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/localopt/Devalify.scala]: Did not understand why desugaring was needed here too

File: compiler/src/dotty/tools/dotc/transform/localopt/ConstantFold.scala [hunk 6]
```diff
@@ -181,22 +181,19 @@ import ast.Trees._
...
       }
     case t1: Ident =>
-      desugarIdent(t1) match {
-        case Some(t) =>
-          val t2i = t2 match {
-            case t2: Ident => desugarIdent(t2).getOrElse(t2)
-            case _ => t2
-          }
-          isSimilar(t, t2i)
-        case None => t1.symbol eq t2.symbol
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/localopt/ConstantFold.scala]: I think the logic was wrong here. If `t2` is a select then it is not enough to compare the symbol

File: compiler/src/dotty/tools/dotc/transform/localopt/Devalify.scala (hunk 5 above)
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/transform/localopt/Devalify.scala]: I would keep the logic untouched then:

```scala
desugarIdent(t) match { case s: Select => readingOnlyVals(s); case _ => true }
```

**Comment by Blaisorblade** [comment]
Does this mean we can close #1686, though with a different fix than planned then?

**Comment by allanrenucci** [comment]
This doesn't really fix #1686. It gives you a way to desugar `Ident` into `Select` but it doesn't hide the distinction between `Select` and `Ident`. I think we can close with `revisit` though
