### PR TITLE
Fix #3012: Avoid swallowing multiple ()'s

### LINKED ISSUE #3012: Non-nullary apply is permitted on dotty nullary method overriding java method
Copy-pasteable repro.
```scala
cat << EOF > Fuzbar.java
package fuz;
public interface Fuzbar {
  public String str();
}
EOF
cat << EOF > a.scala
object a extends fuz.Fuzbar {
  override def str = ""
  str()()()()()()
}
EOF
dotc a.scala Fuzbar.java
// compiles OK, expected error
$ dotc -version
0.4.0-bin-SNAPSHOT-nonbootstrapped-git-d70b8f4
```

I expected dotty to report an error like below

```
-- Error: a.scala:5:6 ----------------------------------------------------------
5 |  str()()()()
  |  ^^^^^
  |  missing argument for parameter index of method apply: (index: Int): Char

```

Related https://github.com/lampepfl/dotty/issues/2570

### PR DESCRIPTION
**Pull request by odersky**
Allow dropping at most one () if a method is called that exists
in both ()T and => T forms.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -64,6 +64,7 @@ object Typer {
 
   private val ExprOwner = new Property.Key[Symbol]
   private val InsertedApply = new Property.Key[Unit]
+  private val DroppedEmptyArgs = new Property.Key[Unit]
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: I think every key should have a documentation comment :).

File: tests/neg/i3012/a.scala [hunk 2]
```diff
@@ -0,0 +1,5 @@
+
+object a extends fuz.Fuzbar {
+  override def str = ""
+  str()()()()()()  // error: missing argument
```
Comment (smarter) [inline tests/neg/i3012/a.scala]: Add a line with just `str()()` to check that it's also an error? A pos test with `str` and `str()` would be useful too.
