### PR TITLE
Detect provisional superclasses and recompute in Typer

### LINKED ISSUE #12722: Spurious "illegal trait inheritance"
## Compiler version
3.0.0

## Minimized code

The two first types are a minimization of scalajs-library, making this code independent of scalajs.
The last five form a somewhat interesting inheritance chain.

```Scala
trait JsAny extends AnyRef
class JsObject extends JsAny

trait HTMLAttributes[T] extends JsObject
trait Component[P] extends JsObject
trait IPersonaSharedProps extends HTMLAttributes[PersonaCoinBase]
trait PersonaCoinBase extends Component[IPersonaCoinProps]
trait IPersonaCoinProps extends IPersonaSharedProps
```

## Output

```

-- Error: tester.scala:8:32 
8 |trait IPersonaCoinProps extends IPersonaSharedProps
  |                                ^^^^^^^^^^^^^^^^^^^
  |illegal trait inheritance: superclass Object does not derive from trait IPersonaSharedProps's superclass JsObject
1 error found

```

## Expectation
Compiles, it did in Scala 2.

Most changes to the code above removes the compile error.

### PR DESCRIPTION
**Pull request by odersky**
Ensuring that the first parent of a class or trait is a class is done in completion.
But at that point some necessary info might not be computed yet, since not all base classes 
of parent classes are guaranteed to be known at that point. We cannot move the transform
to regular typing since that breaks too many assumptions.
Instead we detect the problematic case in Namer and recompute the superclass in Typer.

Fixes #12722

### CODE REVIEW

File: project/MiMaFilters.scala [hunk 1]
```diff
@@ -18,6 +18,7 @@ object MiMaFilters {
     exclude[MissingClassProblem]("scala.annotation.experimental"),
     exclude[MissingClassProblem]("scala.annotation.internal.ErasedParam"),
     exclude[MissingClassProblem]("scala.annotation.internal.ErasedParam"),
+    exclude[MissingClassProblem]("scala.annotation.internal.ProvisionalSuperClass"),
```
Comment (dwijnand) [inline project/MiMaFilters.scala:21]: Btw there's glob support in mima's exclusions so you can use `scala.annotation.internal.*` here next time.
