### PR TITLE
Fix #6150: Emit error when calling Scala 2 macro

### LINKED ISSUE #6150: Emit an error when trying to call a Scala 2 macro from Dotty
Right now, calling a Scala 2 macro present on the classpath will compile fine, but crash at runtime with a NoSuchMethodError since the method is not present in bytecode. We should emit an error at compile-time instead.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2655,6 +2655,10 @@ class Typer extends Namer
         tree.tpe <:< wildApprox(pt)
         readaptSimplified(Inliner.inlineCall(tree, pt))
       }
+      else if (tree.symbol.is(Macro, butNot = Inline)) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Why not check `Macro | Scala2x` ?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -2655,6 +2655,10 @@ class Typer extends Namer
...
+        ctx.error("Scala 2 macro cannot be used in Dotty", tree.sourcePos)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: I would add a link to http://dotty.epfl.ch/docs/reference/dropped-features/macros.html (which also needs to be updated: https://github.com/lampepfl/dotty/issues/5971)

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: The symbol does not have the `Scala2x` flag.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Sounds like a bug ?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Will add

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Yes, I will investigate.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: The trick is that the `Scala2x` is on the owner of the macro. The flag `Scala2xMacro` was also wrong.

File: project/Build.scala [hunk 3]
```diff
@@ -549,6 +549,12 @@ object Build {
             IO.delete(trgDir)
           IO.createDirectory(trgDir)
           IO.unzip(scalaJSIRSourcesJar, trgDir)
+
+          // Remove f interpolator macro call to avoid its expansion while compiling the compiler and the implementation of the f macro
+          val utilsFile = trgDir / "org/scalajs/ir/Utils.scala"
+          val patchedSource = IO.read(utilsFile).replace("""f"\\u$c%04x"""", """"\\u%04x".format(c)""")
```
Comment (nicolasstucki) [inline project/Build.scala]: This should be patched in the original source https://github.com/scala-js/scala-js/pull/3597

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 4]
```diff
@@ -807,6 +807,9 @@ object SymDenotations {
                            // we need an inline flag on them only do that
                            // reduceProjection gets access to their rhs
 
+    /** Is this a Scala 2 macro */
+    final def isScala2Macro(implicit ctx: Context): Boolean = is(Macro) && symbol.owner.is(Scala2x)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Why not change the Scala2Unpickler to set the Scala2x flag on methods too ?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: We could try that

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: > I added an alternative fix in 4b6d417 that sets the Scala2x flag to all symbols.


That looks good to me but maybe there was a reason to not set Scala2x on all Scala 2 symbols ? /cc @odersky

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: The issue is that we have to use an additional as `Scala2x` is only a type flag.

**Comment by nicolasstucki** [comment]
Rebased

File: docs/docs/reference/dropped-features/macros.md [hunk 5]
```diff
@@ -1,13 +1,12 @@
 ---
 layout: doc-page
-title: Dropped: Macros
+title: Dropped: Scala 2 Macros
 ---
 
 The previous, experimental macro system has been dropped. Instead,
 there is a cleaner, more restricted system based on two complementary
```
Comment (smarter) [inline docs/docs/reference/dropped-features/macros.md]: Don't talk about "two complementary concepts" when the list below has three entries :).

File: library/src-bootstrapped/scala/internal/StringContext.scala [hunk 6]
```diff
@@ -0,0 +1,21 @@
+package scala.internal
```
Comment (smarter) [inline library/src-bootstrapped/scala/internal/StringContext.scala]: I would put it it in the dotty package since this will be removed once we merge dotty-library and scala-library (the documentation should explain that too).

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 7]
```diff
@@ -2753,6 +2753,19 @@ class Typer extends Namer
         tree.tpe <:< wildApprox(pt)
         readaptSimplified(Inliner.inlineCall(tree, pt))
       }
+      else if (tree.symbol.isScala2Macro) {
+        if (ctx.settings.XignoreScala2Macros.value) {
+          ctx.warning("Scala 2 macro cannot be used in Dotty. See http://dotty.epfl.ch/docs/reference/dropped-features/macros.html", tree.sourcePos)
+          tree
+        } else if (tree.symbol eq defn.StringContext_f) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Add some documentation explaining what this branch does exactly and what the assumptions are.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 4 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: We did not add the flag as it was not absolutely necessary

File: library/src-bootstrapped/scala/internal/StringContext.scala (hunk 6 above)
Comment (nicolasstucki) [reply library/src-bootstrapped/scala/internal/StringContext.scala]: Moved to `dotty.internal`

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 7 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Modified the documentation.

File: docs/docs/reference/dropped-features/macros.md (hunk 5 above)
Comment (nicolasstucki) [reply docs/docs/reference/dropped-features/macros.md]: Modified text. Added more detail on how the parts interact without going in depth.
