### PR TITLE
Fix #10016: Bypass normalize for context function closure arguments

### LINKED ISSUE #10016: Overload resolution fails for methods having a context function argument but different numbers of argument lists
## Minimized code

```scala
def f(init: Int ?=> Int) : Int = 1
def f(s: String)(init: Int ?=> Int) : Int = 1

@main def main() =
  f((x:Int) ?=> x)
```

## Output

Compilation with Dotty 0.27.0-RC1 fails with the following error:

```scala
[error] -- [E134] Type Mismatch Error: C:\Git\Overload\src\main\scala\Main.scala:5:2 ---
[error] 5 |  f((x:Int) ?=> x)
[error]   |  ^
[error]   |  None of the overloaded alternatives of method f with types
[error]   |   (s: String)(init: (Int) ?=> Int): Int
[error]   |   (init: (Int) ?=> Int): Int
[error]   |  match arguments ((Int) ?=> Int)
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

Compilation should succeed, with the method call in `main` being resolved to `f(init: Int ?=> Int)`.

Note that compilation succeeds if the second definition of `f` is removed.

Note too that the following slightly more complex code (more representative of what I was actually trying to use) also similarly fails to compile:

```scala
def f(init: Int ?=> Int)(using i : Int) : Int = init
def f(s: String)(init: Int ?=> Int)(using i : Int) : Int = init

@main def main() =
  given Int = 10
  f((x:Int) ?=> x)
```

```scala
[error] -- [E134] Type Mismatch Error: C:\Git\Overload\src\main\scala\Main.scala:6:2 ---
[error] 6 |  f((x:Int) ?=> x)
[error]   |  ^
[error]   |  None of the overloaded alternatives of method f with types
[error]   |   (s: String)(init: (Int) ?=> Int)(using i: Int): Int
[error]   |   (init: (Int) ?=> Int)(using i: Int): Int
[error]   |  match arguments ((Int) ?=> Int)
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by odersky**
Do not widen to their result type if expected type is again a context function

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -677,7 +677,9 @@ trait Applications extends Compatibility {
    */
   class ApplicableToTrees(methRef: TermRef, args: List[Tree], resultType: Type)(using Context)
   extends TestApplication(methRef, methRef.widen, args, resultType) {
-    def argType(arg: Tree, formal: Type): Type = normalize(arg.tpe, formal)
+    def argType(arg: Tree, formal: Type): Type =
+      if untpd.isContextualClosure(arg) && defn.isContextFunctionType(formal) then arg.tpe
+      else normalize(arg.tpe, formal)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:682]: Can we instead check whether subtype conforms? The following code fails to type-check:

```Scala
def foo(init: String ?=> Int ?=> Int) : Int = 1
def foo(s: String)(init: Int ?=> Int) : Int = 2


@main def Test() =
  implicit val ev: String = "hello"
  assert(foo((using x:Int) => x) == 1)
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:682]: I think that goes beyond what's possible. That code also fails if only the first variant of `foo` is given. 

I don't see any way to improve the current solution.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:682]: Yes, I see the eta-expansion is before type checking the argument, it's pretty subtle.

**Review by liufengyun — APPROVED** [review]
LGTM
