### PR TITLE
Fix #4785: Change typing rule for wildcard star args

### LINKED ISSUE #4785: Arrays and Repeated arguments in 2.13 and future Dotty version
Starting with Scala 2.13 the default `Seq` type is `immutable.Seq`. This change apply to repeated arguments:
```scala
scala> def foo(x: Int*) = 1
foo: (x: Int*)Int

scala> foo(immutable.Seq(1, 2): _*)
res0: Int = 1

scala> foo(mutable.Seq(1, 2): _*)
                      ^
       error: type mismatch;
        found   : Seq[Int] (in scala.collection.mutable)
        required: Seq[Int] (in scala.collection.immutable)

scala> foo(Array(1, 2): _*)
res2: Int = 1
```
However, it is still possible to pass an Array where repeated arguments are expected. This is a requirement for java interoperability.

In Dotty, given `foo: _*`, `foo` must be a subtype of `Seq`. If `foo` is an array, then an implicit conversion is applied (i.e. `Predef.wrapXXXArray`). We don't need to special case arrays in typer but latter (in [ElimRepeated](https://github.com/lampepfl/dotty/blob/385082b2add7aabd5c2877892d78b6d40de025c2/compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala#L101-L102)) we have to revert the conversion if the array is used as a repeated arguments of a java defined method. E.g.
```scala
// xs: Array[String]

java.nio.file.Paths.get("foo", xs: _*)

// >>>>>> Typer
java.nio.file.Paths.get("foo", Predef.wrapRefArray(xs): String*)

// >>>>>> ElimRepeated
java.nio.file.Paths.get("foo", xs)
```

The current implicit conversions defined in `Predef` returns a `mutable.Seq`.

How do we solve this problem in the future when Dotty switch its default `Seq` type to `immutable.Seq` instead of `collection.Seq`? Here are my thoughts, either:

1. Introduce new implicit conversions in `DottyPredef` (or `Predef`?) from `Array` to `immutable.Seq`.
2. Change typing rules for repeated arguments. In expression position:
    ```
    foo <:< Array[A] or foo <:< immutable.Seq[A]
    ---------------------------------------------
    foo: _* ⊢ Repeated[A]
    ```

I think `scalac` does 2). @adriaanm, any thoughts on this?

### PR DESCRIPTION
**Pull request by allanrenucci**
We typecheck them without expected type to avoid relying on the implicit
conversion from Array to Seq defined in Predef. ElimRepeated does the
necessary adaptations (i.e. seqToArray and arrayToSeq conversions).

### CODE REVIEW

File: compiler/test/dotty/tools/dotc/CompilationTests.scala [hunk 1]
```diff
@@ -42,6 +42,7 @@ class CompilationTests extends ParallelTesting {
     compileList("compileStdLib", TestSources.stdLibWhitelisted, scala2Mode.and("-migration", "-Yno-inline")) +
     compileFile("tests/pos/nullarify.scala", defaultOptions.and("-Ycheck:nullarify")) +
     compileFile("tests/pos-scala2/rewrites.scala", scala2Mode.and("-rewrite")).copyToTarget() +
+    compileFile("tests/pos-special/i4785.scala", defaultOptions.and("-Yno-imports")) +
```
Comment (odersky) [inline compiler/test/dotty/tools/dotc/CompilationTests.scala]: You can achieve the same effect by importing explicitly anything from Predef. Then you could make it a regular test and would not need pos-special.

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 2]
```diff
@@ -91,12 +96,10 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
   private def seqToArray(tree: Tree, pt: Type)(implicit ctx: Context): Tree = tree match {
     case SeqLiteral(elems, elemtpt) =>
       JavaSeqLiteral(elems, elemtpt)
-    case app@Apply(fun, args) if defn.WrapArrayMethods().contains(fun.symbol) => // rewrite a call to `wrapXArray(arr)` to `arr`
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: Why was this optimization dropped?

Comment (allanrenucci) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: It is not needed anymore. When calling into java repeated we used to insert an implicit conversion from `Array` to `Seq` that we later reverted. For example:
```scala
def test(xs: Array[String]) = Paths.get("Hello", xs: _*)
```
Before this path:
```scala
// after frontend:
def test(xs: Array[String]) = Paths.get("Hello", wrapRefArray[String](xs):String*)

// after elimRepeated
def test(xs: Array[String]): = Paths.get("Hello", xs)
```
After this patch:
```scala
// after frontend:
def test(xs: Array[String]) = Paths.get("Hello", xs:String*) // no more call to wrapRefArray

// after elimRepeated
def test(xs: Array[String]): = Paths.get("Hello", xs)
```

**Comment by allanrenucci** [comment]
Comments addressed

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: Thanks for explaining!
