### PR TITLE
Fix #11885: disable flaky idempotency test on Windows

### LINKED ISSUE #11885: IdempotencyTests is flaky on Windows
Starting ~~with the merge of https://github.com/lampepfl/dotty/pull/11210~~ (EDIT: actually long before that, see comments below), it looks like test_windows_full has been failing IdempotencyTests from time to time, from https://github.com/lampepfl/dotty/runs/2178741539:
```scala
Test 'CheckPosIdempotency from idempotency/check' failed with output:           
Idempotency test failed between out\idempotency\posIdempotency1\pos\i6507b\Test.tasty and out\idempotency\posIdempotency2\pos\i6507b\Test.tasty
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:40)
	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
Caused by: java.lang.AssertionError: assertion failed: Failed 1 idempotency checks (out of 5116)
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at IdempotencyCheck$.checkIdempotency(IdempotencyCheck.scala:70)
	at Test$.main(CheckPosIdempotency.scala:4)
	at Test.main(CheckPosIdempotency.scala)
	... 6 more
```
@bishabosha could you investigate this (I've forwarded you the access information for the Windows machine if you want to investigate there)? /cc @liufengyun

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #11885: disable flaky idempotency test on Windows

This is a temporary fix.

[test_windows_full]

### CODE REVIEW

File: tests/idempotency/IdempotencyCheck.scala [hunk 1]
```diff
@@ -6,7 +6,12 @@ import java.util.stream.Stream as JStream
 import scala.collection.JavaConverters.*
 
 object IdempotencyCheck {
-  val blacklisted = Set(
+  val flakytests =
+    if scala.util.Properties.isWin
+    then Set(s"pos{JFile.separator}i6507b")
```
Comment (nicolasstucki) [inline tests/idempotency/IdempotencyCheck.scala:11]:
```suggestion
    then Set(s"pos${JFile.separator}i6507b")
```

The blacklist bellow seems to have the same issue. Maybe we should handle these paths as `JPath` to avoid the `\` vs `/` complications.

Comment (liufengyun) [reply tests/idempotency/IdempotencyCheck.scala:11]: Actually, we can try to remove the blacklist below, as they are not effective.

Comment (nicolasstucki) [reply tests/idempotency/IdempotencyCheck.scala]: I meant not to use the `toString` in the first place

**Review by nicolasstucki — APPROVED** [review]

File: tests/idempotency/IdempotencyCheck.scala (hunk 1 above)
Comment (nicolasstucki) [reply tests/idempotency/IdempotencyCheck.scala]: This can be improve in a subsequent PR

**Comment by smarter** [comment]
Looks like this didn't work, the merge commit for this PR failed test_windows_full in the usual way: https://github.com/lampepfl/dotty/runs/2229032212

**Comment by liufengyun** [comment]
We forget the file extension.
