### PR TITLE
Actively remove Scala 2 pickles and emit synthetic TASTy attribute for copied stdlib .class files

### LINKED ISSUE #24161: actively remove the pickle annotations when "copying" the class files over from Scala 2
## Compiler version
3.8-* (whatever is the latest nightly

While looking into changes in Scala 3.8 library ([SCL-24347](https://youtrack.jetbrains.com/issue/SCL-24347)) and investigating some exceptions in IntelliJ IDEA we [noticed](https://youtrack.jetbrains.com/issue/SCL-24347/Scala-3.8-adopt-to-changes-in-the-scala-library-format#focus=Comments-27-12788290.0-0) that:

In addition to TASTy in `Tuple1.tasty`, `Tuple1.class` contains Scala 2's "pickles" 
(which is not the case for other .class files). 

Here's the list of such classes (15 from 3643):
```scala
scala/AnyVal.class
scala/Tuple1.class
scala/Tuple2.class
scala/collection/DoubleStepper.class
scala/collection/IntStepper.class
scala/collection/LongStepper.class
scala/collection/immutable/DoubleVectorStepper.class
scala/collection/immutable/IntVectorStepper.class
scala/collection/immutable/LongVectorStepper.class
scala/collection/immutable/Range.class
scala/jdk/DoubleAccumulator.class
scala/jdk/IntAccumulator.class
scala/jdk/LongAccumulator.class
scala/runtime/NonLocalReturnControl.class
scala/util/Sorting.class
```

> I think those are the ones copied from the Scala 2 library due to specialization issues

>Some classes are copied directly from Scala 2.13 stdlid. See this file for the full list. It's not only specialized classess, but also the classes defining specialized methods as these would introduce additional bridges https://github.com/scala/scala3/blob/0afa50da6128b04289c108bc54ecf338f3e3e115/project/ScalaLibraryPlugin.scala#L105

>scala/AnyVal.class is not on the explicit list, we might need to investigate this one
I guess this one was not generated at all by Scala 3 compiler so the Scala 2 variant was used
See https://github.com/scala/scala3/blob/0afa50da6128b04289c108bc54ecf338f3e3e115/library/src/scala/AnyVal.scala.ignore (

> I think we should actively remove the pickle annotations when "copying" the class files over from Scala 2

### PR DESCRIPTION
**Pull request by WojciechMazur**
Fixes #24161 
Based on and superseeds #24180 

We're now actively removing Scala 2 pickle annotations and emit synthetic TASTY attributes (for primary classes). Both of validations are now checked at build time

### CODE REVIEW

File: tasty/src/dotty/tools/tasty/TastyVersion.scala [hunk 1]
```diff
@@ -20,7 +20,7 @@ case class TastyVersion private(major: Int, minor: Int, experimental: Int) {
   def validRange: String = {
     val min = TastyVersion(major, 0, 0)
     val max = if (experimental == 0) this else TastyVersion(major, minor - 1, 0)
-    val extra = Option.when(experimental > 0)(this)
```
Comment (hamzaremmal) [inline tasty/src/dotty/tools/tasty/TastyVersion.scala:23]: Why?

Comment (WojciechMazur) [reply tasty/src/dotty/tools/tasty/TastyVersion.scala:23]: Because it's compiled using Scala 2.12. For the sake of correctness we're adding tasty sources to unamanged sources of sbt build. See project/build.sbt changes

File: project/ScalaLibraryPlugin.scala [hunk 2]
```diff
@@ -46,6 +70,9 @@ object ScalaLibraryPlugin extends AutoPlugin {
       }
       var stamps = analysis.stamps
 
+      val classDir = (Compile / classDirectory).value
+      val sourceDir = (LocalProject("scala-library-nonbootstrapped") / sourceDirectory).value
```
Comment (hamzaremmal) [inline project/ScalaLibraryPlugin.scala]: Why does the plugin know about `scala-library-nonbootstrapped`? It shouldn't.
And even if it were to know about it, why doesn't it know about `scala-library-bootstrapped` too?

File: project/ScalaLibraryPlugin.scala [hunk 3]
```diff
@@ -103,6 +134,113 @@ object ScalaLibraryPlugin extends AutoPlugin {
...
+
+    // Skip TASTY handling for Java-sourced classes (they don't have .tasty files)
+    val tastyUUID =
+      if (javaSourceFile.exists()) None
+      else {
+        val tastyFile = classDirectory / (basePath + ".tasty")
+        assert(tastyFile.exists(), s"TASTY file $tastyFile does not exist for $relativePath")
+
+        // Only add TASTY attribute if this is the primary class (class path equals base path)
+        // Inner classes, companion objects ($), anonymous classes ($$anon), etc. don't get TASTY attribute
```
Comment (hamzaremmal) [inline project/ScalaLibraryPlugin.scala:217]: I don't remember this honestly but it doesn't seem like a little detail. This is part of the specification of what attributes generated classfiles contain. Where is this specification written?

File: project/ScalaLibraryPlugin.scala [hunk 4]
```diff
@@ -103,6 +134,113 @@ object ScalaLibraryPlugin extends AutoPlugin {
...
+        case "ScalaSig" | "ScalaInlineInfo" => ()
+        case _ => super.visitAttribute(attr)
+      }
+
+      override def visitAnnotation(desc: String, visible: Boolean): AnnotationVisitor =
+        if (isScala2PickleAnnotation(desc)) null
+        else super.visitAnnotation(desc, visible)
+    }
+    reader.accept(visitor, 0)
+    // Only add TASTY attribute for the primary class (not for inner/nested classes)
```
Comment (hamzaremmal) [inline project/ScalaLibraryPlugin.scala:160]: Then there is the question that we don't have any precedence for: should we add the attribute in specialized classes? I honestly don't know because I don't know what is the purpose of that attribute.

File: project/ScalaLibraryPlugin.scala (hunk 3 above)
Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:217]: No idea, it's based on the observations and outputs of compilation. Partially it's also based on the CodeGen logic: 
https://github.com/scala/scala3/blob/d67339594ff4ba0551c69f747c286a4288f1e361/compiler/src/dotty/tools/backend/jvm/CodeGen.scala#L61-L71

File: project/ScalaLibraryPlugin.scala [hunk 5]
```diff
@@ -103,6 +134,113 @@ object ScalaLibraryPlugin extends AutoPlugin {
...
+      }
+    }
+    new ClassReader(bytes).accept(
+      visitor,
+      ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES
+    )
+    found
+  }
+
+  def validateNoScala2Pickles(jar: File): Unit = {
```
Comment (hamzaremmal) [inline project/ScalaLibraryPlugin.scala:301]: It doesn't validate that `ScalaSig` and `ScalaInlineInfo` attributes were removed.

File: project/build.sbt [hunk 6]
```diff
@@ -1,7 +1,16 @@
...
\ No newline at end of file
+libraryDependencies += "org.yaml" % "snakeyaml" % "2.4"
+
+Compile / unmanagedSourceDirectories ++= {
+  val root = baseDirectory.value.getParentFile()
+  Seq(
+    root / "tasty/src",
+    root / "tasty/src/dotty/tools/tasty/util",
+  )
+}
```
Comment (hamzaremmal) [inline project/build.sbt:16]: Can't we just depend on the latest published version? Is it even possible to do such a thing between Scala 3 and Scala 2.12? Do we need to wait for sbt 2 to do it?

File: project/ScalaLibraryPlugin.scala [hunk 7]
```diff
@@ -144,4 +282,122 @@ object ScalaLibraryPlugin extends AutoPlugin {
...
+      if (length == 16) {
+        val bytes = new Array[Byte](16)
+        for (i <- 0 until 16) {
+          bytes(i) = classReader.readByte(offset + i).toByte
+        }
+        attr.uuid = Some(bytes)
+      }
+      attr
+    }
+  }
```
Comment (hamzaremmal) [inline project/ScalaLibraryPlugin.scala:488]: Can't we collapse them into a single class?

File: tasty/src/dotty/tools/tasty/TastyVersion.scala (hunk 1 above)
Comment (hamzaremmal) [reply tasty/src/dotty/tools/tasty/TastyVersion.scala:23]: Fair enough, linking to my comment here https://github.com/scala/scala3/pull/24846#discussion_r2653094333

File: project/ScalaLibraryPlugin.scala (hunk 3 above)
Comment (hamzaremmal) [reply project/ScalaLibraryPlugin.scala:217]: I think we need the answer to this question before blindly committing to a design. That's why #24180 is delayed, I still have more questions than answers. See this too: https://github.com/scala/scala3/pull/24846#discussion_r2653088596

File: project/ScalaLibraryPlugin.scala (hunk 2 above)
Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala]: I've rewritten this part so that sourceDir is not required at all. We now identify .java sources based on the Classfile Source attribute

File: project/ScalaLibraryPlugin.scala (hunk 4 above)
Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:160]: No, becouse these are not "primary". In the same way as we apparently don't add TASTY attribute for the companion module class or there is not TASTy for synthetic anonymous class 

Right now the TASTy attribute would be added only to the sources that would naturally contain TASTy attribute if compiled using Scala 3: 
```sh 
tastyUUID for scala/Tuple1.class: 00a339b792cd7eac008660ea168725f3
tastyUUID for scala/Tuple2.class: 000ca8e2dce9c19a00f363ecefcdbec5
tastyUUID for scala/collection/DoubleStepper.class: 00703d7c2e7ffcb700b287d999ad1595
tastyUUID for scala/collection/IntStepper.class: 009766856a8859b700c67a980eacefc3
tastyUUID for scala/collection/LongStepper.class: 00d2dfa3133310b7003d929d583684a5
tastyUUID for scala/collection/Stepper.class: 00bb7f046916eaa3007b9a1b982043f1
tastyUUID for scala/collection/immutable/DoubleVectorStepper.class: 00b8ae9a9f4f11b7002260fd37125644
tastyUUID for scala/collection/immutable/IntVectorStepper.class: 00409db0061756b7003367ff5f067f44
tastyUUID for scala/collection/immutable/LongVectorStepper.class: 0066415ac82ecfb700456af85e1a7744
tastyUUID for scala/collection/immutable/Range.class: 0032837a8789b8f500aa3b2437445bb4
tastyUUID for scala/jdk/DoubleAccumulator.class: 004dee438fc6f8de000762cc7744fa8b
tastyUUID for scala/jdk/IntAccumulator.class: 0090e4b14fdf4cdf00831888bf948aa1
tastyUUID for scala/jdk/LongAccumulator.class: 005598d1fa676cda00a901fcddc8f4c8
tastyUUID for scala/runtime/NonLocalReturnControl.class: 00b0cf8ea56508cb00420efcdf3acd38
tastyUUID for scala/util/Sorting.class: 009ef6b0ffdffbbd00988e02c758b8c8
```

File: project/ScalaLibraryPlugin.scala (hunk 5 above)
Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:301]: I've adjusted it so that both of these are now validated

File: project/ScalaLibraryPlugin.scala (hunk 7 above)
Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:488]: Potentially yes, but would be confusing as one is used only to extract attribute and other one to write it. I've refactored it so that reader one is locall to the function which extracts these

File: project/build.sbt (hunk 6 above)
Comment (WojciechMazur) [reply project/build.sbt:16]: We can't depend on it since that would require upgrade to sbt 2 which is not possible right now (e.g. MiMa plugin is not cross compiled yet) or to introduce cross compilation of tasty project (which again would require changes due to classess in stdlib that were stubbed in this PR_

sbt 1.11 already enables `-Xsource:3` by default, so most of sources should compile (based on syntax) unless there are changes in stdlib (like mentioned Option.when introduced in 2.13).  

Concept of depending on sources in the build definitions is frequently used in Scala.js and Scala Native altough it's more complicated there (it's used to bootstrap sbt plugins and whole toolchain that are later referenced from inside the build) 

I bealive we should be able to switch for regular dependencies after upgrading to sbt 2 in hopefully 4-6 months (fingers crossed it would be ready by that time, support for mima was merged but awaits for release https://github.com/lightbend-labs/mima/pull/878)

File: project/ScalaLibraryPlugin.scala (hunk 3 above)
Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:217]: To summarize behaviour based on the compiler implementation, since there is no dedicated specification:
1. Only one class per top-level definition gets the TASTy attribute - either the main class or the mirror class, never both
2. TASTy pickling only iterates over `topLevelClasses` (defined in `TreeInfo.scala`), not nested classes
3. Nested/inner classes are stored inside their parent's `.tasty` file, not in separate files
4. The TASTy attribute contains only a 16-byte UUID pointing to the `.tasty` file - if there's no separate `.tasty` file, there's nothing to point to 

**Verification from `ClassfileParser.scala`:**
- If a `.class` file has a TASTy attribute, the compiler expects a corresponding `.tasty` file
- If the UUID doesn't match, it warns about sync issues

Based on that current behavior is consistent with the design that **one `.tasty` file corresponds to one top-level class** and contains all nested definitions within it. 

TASTy for companion module is store in companion class. Even if we'd define just an `object foo` a mirror ``foo.class` would be created and it would contain TASTy attribute, not the `foo$.class`

There is no TASTy attribute for anonynous classes e.g. `foo$anon$1.class`. 
Since specialized class is basically a new anonymous class it should not define TASTY attribute either. 

If in the future we'd decide that TASTy should be also stored for synthetics then it can be easily added in the future. Right now TASTy attrs have been added only to the .class files that should have produced TASTy right now. We can add additional validation to ensure that's the case

Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:217]: Additional assertions were added in [9178964](https://github.com/scala/scala3/pull/24846/commits/9178964ec02ff07e7d7314fdff6b14884037f7f7)

**Comment by WojciechMazur** [comment]
@sjrd Please take a look at this PR, you should be the most oriented in how these attributes are used. We need a decision if we can backport this to 3.8.0-RC6 or make RC5 stable. 

The issue seemed to be workaround by JetBrains on their side (see [ticket](https://youtrack.jetbrains.com/issue/SCL-24347)) but it would be better to not have a "special" versions requiring dedicated fixed by the tools.

File: project/ScalaLibraryPlugin.scala (hunk 3 above)
Comment (sjrd) [reply project/ScalaLibraryPlugin.scala:217]: @WojciechMazur's analysis is correct.

In addition: *all* `.class` files produced by a Scala compiler (2 or 3, primary class or not) must have the `Scala` attribute. You might want to add that to the checks you perform. However, you shouldn't need to add/remove it since they will be present from the Scala 2 compilation.

Comment (WojciechMazur) [reply project/ScalaLibraryPlugin.scala:217]: That's a good catch and it seems the Scala 2 compiler might have a bug - there are 15 .class files that miss Scala attribute: 

```scala
[error] (scala-library-nonbootstrapped / Compile / packageBin) java.lang.AssertionError: assertion failed: JAR scala-library-3.8.1-RC1-bin-SNAPSHOT-nonbootstrapped.jar contains 15 class files without 'Scala' attribute: 
[error]   - scala/Tuple1.class
[error]   - scala/Tuple2.class
[error]   - scala/collection/DoubleStepper.class
[error]   - scala/collection/IntStepper.class
[error]   - scala/collection/LongStepper.class
[error]   - scala/collection/Stepper.class
[error]   - scala/collection/immutable/DoubleVectorStepper.class
[error]   - scala/collection/immutable/IntVectorStepper.class
[error]   - scala/collection/immutable/LongVectorStepper.class
[error]   - scala/collection/immutable/Range.class
[error]   - scala/jdk/DoubleAccumulator.class
[error]   - scala/jdk/IntAccumulator.class
[error]   - scala/jdk/LongAccumulator.class
[error]   - scala/runtime/NonLocalReturnControl.class
[error]   - scala/util/Sorting.class
```

These seems to match the list of specialized classes we copy. It appears that we have following attributes: 
- in Tuple1.class :  ScalaInlineInfo, ScalaSig (no Scala)
- in Tuple1$.class: ScalaInlineInfo, Scala
- in Tuple2$mcCC$sp.class: ScalaInlineInfo, Scala 

Unless ScalaSig was a special case for Scala attribute it seems to not match the spec. 
Since `Scala` attribute is empty we can easily add to the copied files
