### PR TITLE
GADTs: widen only top-level variant params

### LINKED ISSUE #11565: Unsound GADT infered constraints when mixing invariant and variant type constructors
## Compiler version
`Scala compiler version 3.0.0-RC2-bin-SNAPSHOT-nonbootstrapped-git-7bef33b -- Copyright 2002-2021, LAMP/EPFL`

## Minimized code

```Scala
@main def test: Unit = {
  trait TyCon[+A]
  trait S[T]
  trait P[T] extends S[TyCon[T]] {
    def consume(t: T): Unit
  }

  def patmat(s: S[TyCon[Int]]) = s match {
    case p: P[t] =>
      // "t is a type in method patmat which is an alias of Any"
      // def whatist(x: t): Nothing = x
      p.consume("Hi")
  }

  patmat(new P[Int] {
    override def consume(t: Int): Unit = t + 1 // ClassCastException: class String cannot be cast to class Integer 
  })
}
```

## Output

<details><summary>Click to expand</summary>

```scala
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
	at Test$$anon$1.consume(Test.scala:15)
	at Test$.patmat$1(Test.scala:11)
	at Test$.main(Test.scala:16)
	at Test.main(Test.scala)
```

</details>

## Expectation
The code should be rejected (by not concluding that `t =:= Any`).

By putting some logs, we observe the following run:
* `PatternTypeConstrainer#constrainPatternType` is given `P[t]` and `S[TyCon[Int]]`
* In `S`, types appearing in variant positions are (recursively) widened, yielding `S[TyCon[?]]`. `P[t]` is wrapped in a Skolem type 
* The algorithm then calls `isSubType` with `(?1 : P[t])` and `S[TyCon[?]]`
  * which leads to `S[TyCon[t]] <:< S[TyCon[?]]`
  * Since `S` is invariant, we have:  
    * `TyCon[?] <:< TyCon[t]` which records that `Any <:< t` (from `⊥..⊤ <:< t`)
    * and `TyCon[t] <:< TyCon[?]` (true; nothing inferred)

If I understand it correctly, it seems that, in GADT constraint inferencing mode, it is unwanted to deduce anything from `⊥..⊤ <:< x` (and from `x <:< ⊥..⊤` too) as `⊥..⊤` is used as a placeholder more than anything else.

### PR DESCRIPTION
**Pull request by abgruszecki**
Fixes #11565.

The change to an unrelated test file is to clarify what should and shouldn't be inferred.

### CODE REVIEW

**Comment by abgruszecki** [comment]
The fix is quite simple: we should only widen top-level variant type params - remember that the widening is there only to trick TypeComparer into doing comparison between the appropriate type params. The doc comment for the function even implies that only top-level params should be widened.

File: compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala [hunk 1]
```diff
@@ -189,16 +189,14 @@ trait PatternTypeConstrainer { self: TypeComparer =>
...
-      def apply(tp: Type) = mapOver(tp) match {
-        case tp @ AppliedType(tycon, args) =>
-          val args1 = args.zipWithConserve(tycon.typeParams)((arg, tparam) =>
-            if (tparam.paramVarianceSign != 0) TypeBounds.empty else arg
-          )
-          tp.derivedAppliedType(tycon, args1)
-        case tp =>
-          tp
-      }
+    def widenVariantParams(tp: Type) = tp match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala:192]: I don't quite understand what all this stuff is doing, but are we intentionally not dealiasing here?

**Review by smarter — COMMENTED** [review]
> The fix is quite simple: we should only widen top-level variant type params - remember that the widening is there only to trick TypeComparer into doing comparison between the appropriate type params. The doc comment for the function even implies that only top-level params should be widened.

That whole comment should go in the commit message.

File: compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala (hunk 1 above)
Comment (abgruszecki) [reply compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala:192]: The type is already dealiased in `constrainPatternType`, we need to dealias in order to correctly handle intersections, unions and other things.

**Review by smarter — APPROVED** [review]

**Comment by abgruszecki** [comment]
Oh, I was going to add the comment to the commit message, but I got distracted. Anyway, it's the source already (it's one of those Huge Alex Comments), so I guess it's fine.
