### PR TITLE
REPL: emit parse warnings by reusing the reporter

### LINKED ISSUE #13208: REPL fails to issue warnings from parser
@dwijnand and I found a case where the compiler issues a warning but the REPL does not:

```
% scalac -3.head -version
Scala compiler version 3.0.3-RC1-bin-20210728-a28aee1-NIGHTLY-git-a28aee1 -- Copyright 2002-2021, LAMP/EPFL
% scala -3.head -deprecation -source:future
scala> type M[X] = X match { case Int => String case _ => Int }                                                         

scala>                                                                                                                  
% echo 'type M[X] = X match { case Int => String case _ => Int }' > S.scala
% scalac -3.head -deprecation -source:future S.scala
-- Deprecation Warning: S.scala:1:46 -------------------------------------------
1 |type M[X] = X match { case Int => String case _ => Int }
  |                                              ^
  |        `_` is deprecated for wildcard arguments of types: use `?` instead
1 warning found
```

I'm not sure what the exact conditions are to trigger this or not.

Not _all_ warnings are affected. Here's an example where a `-source:future` deprecation warning is issued in the REPL as expected:

```
% scala -3.head -deprecation -source:future
scala> List(1) match { case List[_] => true }                                                                           
-- Deprecation Warning:
1 |List(1) match { case List[_] => true }
  |                          ^
  |        `_` is deprecated for wildcard arguments of types: use `?` instead
```

I'm not sure if the problem is reproducible without `-source:future`, but I assume that will become clearer when this is investigated.

### PR DESCRIPTION
**Pull request by dwijnand**
The original report requires the -deprecation and -source:future flags,
for which there is seems to be no support in repl.ScriptedTests.  So
switched to a non-deprecation syntax warning, that isn't guarded by
-source.

I might come back and add "pragma" support to the REPL scripts so I can
move the test out of pending.

Co-authored-by: Seth Tisue <seth@tisue.net>

Fixes #13208

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
This is somewhat related to https://github.com/scala/scala/commit/79ca1408c7

Reminds me that I need to test https://github.com/lampepfl/dotty/pull/12857/ with the REPL.

File: compiler/src/dotty/tools/repl/ReplDriver.scala [hunk 1]
```diff
@@ -243,7 +243,7 @@ class ReplDriver(settings: Array[String],
       unfusedPhases(using ctx).collectFirst { case phase: CollectTopLevelImports => phase.imports }.get
 
     implicit val state = {
-      val state0 = newRun(istate)
+      val state0 = newRun(istate, parsed.reporter)
       state0.copy(context = state0.context.withSource(parsed.source))
```
Comment (dwijnand) [inline compiler/src/dotty/tools/repl/ReplDriver.scala:247]: Btw, before I wired the reporter through newRun I was adding it here with `.fresh.setReporter(reporter)` but that was breaking something to do with class-loading, which seemed complicated.  I'm not sure if that's expected and if anyone knows why that happened.
