### PR TITLE
Fix #10143 and test stdlib from TASTy directly from Jar and TASTy files

### LINKED ISSUE #10143: Tasty stdlib cannot be loaded by the doctool
When we try to load .tasty files generated by the `stdlib-bootstrapped` project in the doctool, we get a Tasty parse (!) exception:

https://github.com/lampepfl/dotty/runs/1341421259?check_suite_focus=true#step:10:970

```
scala.MatchError: 137 (of class java.lang.Integer)
	at dotty.tools.dotc.core.tasty.TastyClassName$TreeSectionUnpickler.readNames$1(TastyClassName.scala:46)
	at dotty.tools.dotc.core.tasty.TastyClassName$TreeSectionUnpickler.unpickle(TastyClassName.scala:57)
	at dotty.tools.dotc.core.tasty.TastyClassName$TreeSectionUnpickler.unpickle(TastyClassName.scala:26)
	at dotty.tools.dotc.core.tasty.TastyUnpickler.unpickle$$anonfun$1(TastyUnpickler.scala:96)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.dotc.core.tasty.TastyUnpickler.unpickle(TastyUnpickler.scala:96)
	at dotty.tools.dotc.core.tasty.TastyClassName.readName(TastyClassName.scala:22)
	at dotty.tools.dotc.fromtasty.TastyFileUtil$.getClassName(TastyFileUtil.scala:29)
	at dotty.tools.dotc.Driver.$anonfun$1(Driver.scala:104)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at dotty.tools.dotc.Driver.fromTastySetup(Driver.scala:108)
	at dotty.tools.dotc.Driver.setup(Driver.scala:81)
	at dotty.tools.dotc.Driver.process(Driver.scala:193)
	at dotty.tools.dotc.Driver.process(Driver.scala:163)
	at dotty.tools.dotc.Driver.process(Driver.scala:175)
	at scala.tasty.inspector.TastyInspector.inspectFiles(TastyInspector.scala:95)
…
```
/cc @nicolasstucki

### PR DESCRIPTION
**Pull request by nicolasstucki**
Now we test that the `-from-tasty` compilation works on the std lib for a jar or individual tasty files.

We also fix #10143 as this failure shows up in the second set of tests. We did not parse correctly the name of the package if it was represented with a `SHAREDtype` in TASTy. Now we follow the shared type and read its name.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 1]
```diff
@@ -158,6 +158,7 @@ class ScalaSettings extends Settings.SettingGroup {
   val YretainTrees: Setting[Boolean] = BooleanSetting("-Yretain-trees", "Retain trees for top-level classes, accessible from ClassSymbol#tree")
   val Ysemanticdb: Setting[Boolean] = BooleanSetting("-Ysemanticdb", "Store information in SemanticDB.")
   val YshowTreeIds: Setting[Boolean] = BooleanSetting("-Yshow-tree-ids", "Uniquely tag all tree nodes in debugging output.")
+  val YfromTastyBlacklist: Setting[List[String]] = MultiStringSetting("-Yfrom-tasty-blacklist", "file", "List of `tasty` files in jar files that will not be loaded when using -from-tasty")
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala:161]: could we change this to ignore list?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/config/ScalaSettings.scala:161]: You mean `YfromTastyIgnoreList`?

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/config/ScalaSettings.scala:161]: sorry, yes thats what I meant

**Review by smarter — APPROVED** [review]
