### PR TITLE
Fixes #7051 Detect typos in neg tests and give a warning

### LINKED ISSUE #7051: Neg tests could  infer `//error` and `// error` as the same thing
When writing tests in `neg` package we have the option of giving `// error` at the end of a line to indicate a compilation error on that line. The space between `//` and `error` is strictly required and I have spent a lot of time figuring out why my tests in the `neg` folder did not work. Apparently I missed the space. 

Can we simplify this by treating both `//error` and `// error` as the same?

### PR DESCRIPTION
**Pull request by ashwinbhaskar**

### CODE REVIEW

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 1]
```diff
@@ -672,6 +675,35 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
 
+    /**
+     * We want to warn the developer about some of the possible typos when trying to point "error" and "nopos-error"
+     * For example - A warning could be emitted if the developer mistakenly types in "//error" instead of "// error"
+     * or "//nopos-error" instead of "// nopos-error"
+     *
+     * @param files test files
+     * @return Sequence of warning messages
+     */
+    def getWarnings(files : Seq[JFile]) : Seq[String] = {
```
Comment (nicolasstucki) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: We should check this in `getErrorMapAndExpectedCount` and emit the warnings in it. The main motivation is to process each file/line once.

Comment (nicolasstucki) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: I would suggest performing the check here:

https://github.com/lampepfl/dotty/pull/7062/files#diff-3be4e64955ddae8ae1de36d6f1fdc1bbR670

Comment (ashwinbhaskar) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: done

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 2]
```diff
@@ -658,20 +658,48 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
 
+    /**
+     * We want to warn the developer about some of the possible typos when trying to point "error" and "nopos-error"
+     * For example - A warning could be emitted if the developer mistakenly types in "//error" instead of "// error"
+     * or "//nopos-error" instead of "// nopos-error"
+     *
+     * @param line the line which will be checked for possible typos
+     * @return Some(warningMessage) or None
+     */
+    def maybeWarning(line : String) : Option[String] = {
```
Comment (nicolasstucki) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: It would be more efficient to inline these methods. There is no real need to box the message in an `Option`, we could directly echo the warning. The `line.contains` is executed more times than necessary, the `hasTypo` is an unnecessary check as `getWarning` also check those conditions.

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 3]
```diff
@@ -658,20 +658,48 @@ trait ParallelTesting extends RunnerOrchestration { self =>
...
 
+
           val noposErrors = line.sliding("// nopos-error".length).count(_.mkString == "// nopos-error")
           if (noposErrors > 0) {
             val nopos = errorMap.get("nopos")
             val existing: Integer = if (nopos eq null) 0 else nopos
             errorMap.put("nopos", noposErrors + existing)
           }
 
+          maybeWarning(line).foreach(warning => echo(s"Possible typo in file ${file.getCanonicalPath} at line number $lineNbr \n$warning"))
```
Comment (nicolasstucki) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: I would suggest something like this

```suggestion
          val possibleTypos = List("//error" -> "// error" , "//nopos-error" -> "// nopos-error")
          for ((possibleTypo, expected) <- possibleTypos) {
            if (line.contains(possibleTypo)) 
              echo(s"Warning: Possible typo in error tag in file ${file.getCanonicalPath}:$lineNbr: found `$possibleTypo` but expected `$expected`")
          }
```

Comment (ashwinbhaskar) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala]: done

**Comment by nicolasstucki** [comment]
Thanks @ashwinbhaskar
