### PR TITLE
Synthesize `ValueOf[Unit]` for a name designator

### LINKED ISSUE #12510: `Expr.summon[ValueOf[Unit]]` returns `None`
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
object M {
  import scala.quoted.*

  inline def valueOfUnit: ValueOf[Unit] =
    ${ _valueOfUnit }

  def _valueOfUnit(using Quotes): Expr[ValueOf[Unit]] = {
    import quotes.reflect.*
    Expr.summon[ValueOf[Unit]] getOrElse sys.error("Not found")
  }
}
```

```scala
object T {
  val ok = summon[ValueOf[Unit]]
  val ko = M.valueOfUnit
}
```

## Output

```scala
[error] 3 |  val ko = M.valueOfUnit
[error]   |           ^^^^^^^^^^^^^
[error]   |           Exception occurred while executing macro expansion.
[error]   |           java.lang.RuntimeException: Not found
[error]   |           	at scala.sys.package$.error(package.scala:27)
[error]   |           	at M$._valueOfUnit$$anonfun$1(b.scala:9)
[error]   |           	at scala.Option.getOrElse(Option.scala:201)
[error]   |           	at M$._valueOfUnit(b.scala:9)
[error]   |
[error]   | This location contains code that was inlined from a.scala:3
[error] one error found
```

## Expectation

No error.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #12510

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 1]
```diff
@@ -160,13 +160,12 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
...
     def success(t: Tree) =
       New(defn.ValueOfClass.typeRef.appliedTo(t.tpe), t :: Nil).withSpan(span)
-
     formal.argInfos match
       case arg :: Nil =>
         fullyDefinedType(arg.dealias, "ValueOf argument", span).normalized match
           case ConstantType(c: Constant) =>
             success(Literal(c))
-          case TypeRef(_, sym) if sym == defn.UnitClass =>
+          case tp: TypeRef if tp.symbol.derivesFrom(defn.UnitClass) =>
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:168]: Better use `isRef`. `Unit` is final, so `derivesFrom` is overkill.

**Review by odersky — COMMENTED** [review]
Otherwise LGTM

**Review by odersky — APPROVED** [review]
