### PR TITLE
Fix false positive in WUnused for renamed path-dependent imports (2)

### LINKED ISSUE #18366: False warning about unused import for local/relative import with Scala 3.3
## Compiler version

3.3.0 & 3.3.1-RC4

## Minimized code

```scala
  @SuppressWarnings(Array("UnusedMethodParameter"))
  private[api] def serializeWith[P <: SerializationPack](
      pack: P,
      collation: Collation
    )(builder: SerializationPack.Builder[pack.type]
    ): pack.Document = {

    import builder.{ elementProducer => element, int, string, boolean }

    val elements = Seq.newBuilder[pack.ElementProducer]

    elements += element("locale", string(collation.locale))
    ??? // ...
}
```

See: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/Collation.scala#L166

## Output

```
[error] 166 |    import builder.{ elementProducer => element, int, string, boolean }
[error]     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |                     unused import
```

## Expectation

No warning

### PR DESCRIPTION
**Pull request by szymon-rd**
Resolve #18366

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/StdNames.scala [hunk 1]
```diff
@@ -53,7 +53,7 @@ object StdNames {
     protected def kw(name: N): N = { kws += name; name }
 
     final val keywords: collection.Set[N] = kws
-  }
+  }
```
Comment (KacperFKorban) [inline compiler/src/dotty/tools/dotc/core/StdNames.scala:56]: nit: random space?

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 2]
```diff
@@ -337,7 +337,7 @@ object CheckUnused:
    * - usage
    */
   private class UnusedData:
-    import collection.mutable.{Set => MutSet, Map => MutMap, Stack => MutStack}
+    import collection.mutable.{Set => MutSet, Map => MutMap, Stack => MutStack, ListBuffer => MutList}
```
Comment (KacperFKorban) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:340]: nit: u don't have to rename ListBuffer, since it's unique in stdlib

**Review by KacperFKorban — APPROVED** [review]
LGTM
