### PR TITLE
Fix nested desugaring of applied constructor types

### LINKED ISSUE #25164: Compiler crash with function returning applied constructor type (tracked parameters)
# Compiler crash with function returning applied constructor type (tracked parameters)

## Compiler version

3.8.1

## Minimized code

```scala
import scala.language.experimental.modularity

trait Ctx {
  type State
}

sealed trait Base(tracked val ctx: Ctx)

object Base {
  abstract class Sub(tracked override val ctx: Ctx) extends Base(ctx) {
    // Crash: function returning applied constructor type Base(ctx)
    def f: Int => Base(ctx)
  }
}
```

## Output (click arrow to expand)

<details>

```
$ scalac -language:experimental.modularity CrashRepro.scala

  unhandled exception while running posttyper on CrashRepro.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: CrashRepro.scala
        during phase: posttyper
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.16
    compiler version: version 3.7.4
            settings: -language List(experimental.modularity)

Exception in thread "main" dotty.tools.dotc.ast.Trees$UnAssignedTypeException: type of Select(New(Ident(Base)),<init>) is not assigned
	at dotty.tools.dotc.ast.Trees$Tree.tpe(Trees.scala:77)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:409)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1649)
	at scala.collection.immutable.List.mapConserve(List.scala:473)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1649)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1585)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:51)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:558)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1609)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:42)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$7(PostTyper.scala:488)
	at dotty.tools.dotc.transform.SuperAccessors.wrapDefDef(SuperAccessors.scala:228)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:488)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1301)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1301)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transformStats(PostTyper.scala:609)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1303)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:49)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$6$$anonfun$1(PostTyper.scala:472)
	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:213)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$6(PostTyper.scala:472)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.withNoCheckNews(PostTyper.scala:151)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:474)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1611)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:42)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:536)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1301)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1301)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transformStats(PostTyper.scala:609)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1303)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:49)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$6$$anonfun$1(PostTyper.scala:472)
	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:213)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$6(PostTyper.scala:472)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.withNoCheckNews(PostTyper.scala:151)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:474)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1611)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:42)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:536)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1301)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1301)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transformStats(PostTyper.scala:609)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1303)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1622)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:42)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:599)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:20)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:383)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:376)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
	at scala.Function0.apply$mcV$sp(Function0.scala:42)
	at dotty.tools.dotc.Run.showProgress(Run.scala:482)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:432)
	at dotty.tools.dotc.Run.compileSources(Run.scala:319)
	at dotty.tools.dotc.Run.compile(Run.scala:304)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
	at dotty.tools.dotc.Driver.process(Driver.scala:201)
	at dotty.tools.dotc.Driver.process(Driver.scala:169)
	at dotty.tools.dotc.Driver.process(Driver.scala:181)
	at dotty.tools.dotc.Driver.main(Driver.scala:211)
	at dotty.tools.MainGenericCompiler$.run$1(MainGenericCompiler.scala:164)
	at dotty.tools.MainGenericCompiler$.main(MainGenericCompiler.scala:188)
	at dotty.tools.MainGenericCompiler.main(MainGenericCompiler.scala)
```
</details>

## Notes

The crash occurs when defining a **function type** that returns an applied constructor type with a tracked parameter.

**Works:**
- `def next: Base(ctx)` — direct value, no function
- `def f: Int => Int` — function not returning applied constructor type

**Crashes:**
- `def f: Int => Base(ctx)` — function returning applied constructor type

This blocks use cases where a class needs to store a continuation function that produces values of the same tracked-parameter type (e.g., `FlatMap` in a workflow DSL).

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #25164.

Done during the compiler issue spree of Februrary 16th, with @alexandrubabacea.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2714,10 +2714,10 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
       typed(tree.tpt, AnyTypeConstructorProto)
 
     val tparams = tpt1.tpe.dealiasKeepAnnotsAndOpaques.typeParams
-     if tpt1.tpe.isError then
-       val args1 = tree.args.mapconserve(typedType(_))
-       assignType(cpy.AppliedTypeTree(tree)(tpt1, args1), tpt1, args1)
-     else if (tparams.isEmpty) {
+    if tpt1.tpe.isError then
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2717]: This is just dedented; had a spurious 1-space indentation.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -2763,22 +2763,22 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
-                // with C[? >: L <: H] where `L` and `H` are the bounds of the corresponding
-                // type parameter in `C`.
-                // The transform does not apply for patterns, where empty bounds translate to
-                // wildcard identifiers `_` instead.
-                TypeTree(tparamBounds).withSpan(arg.span)
-              case _ =>
-                typedType(desugaredArg, argPt, mapPatternBounds = true)
-            }
-          else desugaredArg.withType(UnspecifiedErrorType)
+          arg match {
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2766]: This whole diff is also just dedent.
We move the check `if (desugaredArg.isType)` _after_ trying to type the argument as a type first (`typedType(desugaredArg, ...)`).

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (mbovel) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:2717]: OMG, I just realized GitHub has "Hide whitespace" option! Life is good!

image
