### PR TITLE
Fix #5032: Make sure that erroneous empty idents have a position

### LINKED ISSUE #5032: Position not set for Ident(<error>)
```scala
class i1@
```
```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: position not set for Ident(<error>) # 10
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.typer.Typer$.assertPositioned(Typer.scala:63)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1899)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1912)
	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:969)
	at dotty.tools.dotc.typer.Namer.typedAheadImpl(Namer.scala:962)
	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:969)
	at dotty.tools.dotc.typer.Namer.typedAheadAnnotationClass(Namer.scala:981)
	at dotty.tools.dotc.typer.Namer.typedAheadAnnotationClass(Namer.scala:980)
	at dotty.tools.dotc.typer.Namer.typedAheadAnnotationClass(Namer.scala:978)
	at dotty.tools.dotc.typer.Namer$Completer.addAnnotations$$anonfun$1(Namer.scala:753)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
```
AE-9fea5208d12255332071a58be4afc5275b9e8d64

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -543,8 +543,14 @@ object Parsers {
...
-    def termIdent(): Ident = atPos(in.offset) {
-      makeIdent(in.token, ident())
+    def termIdent(): Ident = {
+      val lastOffset = in.lastOffset
+      val id = atPos(in.offset) {
+        makeIdent(in.token, ident())
+      }
+      // Make sure that even trees with parsing errors have a offset that is within the offset
+      if (id.name == nme.ERROR && id.pos == NoPosition) atPos(lastOffset - 1)(id)
+      else id
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Why nothing for `typeIdent`? Also, I think we should put the whole logic in `makeIdent`, like this:
```scala
    private def makeIdent(tok: Token, name: Name) = {
      val tree =
        if (tok == BACKQUOTED_IDENT) BackquotedIdent(name)
        else Ident(name)
      if (name.toTermName == nme.ERROR) tree.withSpan(Span(in.offset, in.offset))
      else tree
    }
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: And,..., let's get new source positions in first, otherwise we just get needless rebase breakages.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Yes, we should wait until the changes in positions.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: This change has been implemented.
