### PR TITLE
Fix #3200: bind var for singleton pattern get scrutinee type

### LINKED ISSUE #3200: Compatibility with `-Xfuture` in type checking patmat
The following code fails with `scalac -Xfuture test.scala`, but Dotty compiles without problem:

```Scala
object Test {
  case object Bob { override def equals(other: Any) = true }
  def f(x: Any): Bob.type = x match { case x @ Bob => x }
}
```

This is a separate issue extracted from #1463.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #3200: bind var for singleton pattern get scrutinee type

Related issues:

https://issues.scala-lang.org/browse/SI-1503
https://github.com/lampepfl/dotty/issues/1463

### CODE REVIEW

File: tests/neg/3200b.scala [hunk 1]
```diff
@@ -0,0 +1,5 @@
+object Test {
+  def main(args: Array[String]): Unit = {
```
Comment (odersky) [inline tests/neg/3200b.scala]: Rename to i3200b.scala
