### PR TITLE
Fix #7329: Fix assertions

### LINKED ISSUE #7329: Tasty decompiler crash on simple case class
## minimized code

This has been introduced since 0.19 release, so only affects master

```Scala
case class Foo(a: Int)
```

`$ dotc -decompile Foo.tasty`

<details>
<summary>Stack trace</summary>

```scala
/** Decompiled from ./Foo.tasty */
java.lang.AssertionError: assertion failed while compiling Foo
Exception in thread "main" java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.Symbol_tree(ReflectionCompilerInterface.scala:1462)
	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.Symbol_tree(ReflectionCompilerInterface.scala:1461)
	at scala.tasty.reflect.SymbolOps$SymbolAPI.tree(SymbolOps.scala:54)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printParamDef(Printers.scala:1276)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printSeparated$14(Printers.scala:1248)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printArgsDefs$$anonfun$1(Printers.scala:1255)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.inParens(Printers.scala:525)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printArgsDefs(Printers.scala:1256)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printTree(Printers.scala:600)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printTrees$$anonfun$1(Printers.scala:1084)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printSeparated$3(Printers.scala:1075)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printList(Printers.scala:1079)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printTrees(Printers.scala:1084)
	at scala.tasty.reflect.Printers$SourceCodePrinter$Buffer.printTree(Printers.scala:565)
	at scala.tasty.reflect.Printers$SourceCodePrinter.showTree(Printers.scala:460)
	at dotty.tools.dotc.tastyreflect.ReflectionImpl$.showTree(ReflectionImpl.scala:21)
	at dotty.tools.dotc.decompiler.DecompilationPrinter.printToOutput(DecompilationPrinter.scala:46)
	at dotty.tools.dotc.decompiler.DecompilationPrinter.run(DecompilationPrinter.scala:23)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
	at scala.collection.immutable.List.map(List.scala:219)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:159)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:169)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:177)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:184)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:126)
	at dotty.tools.dotc.fromtasty.TASTYRun.compile(TASTYRun.scala:10)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.dotc.Driver.process(Driver.scala:178)
	at dotty.tools.dotc.Driver.process(Driver.scala:147)
	at dotty.tools.dotc.Driver.process(Driver.scala:159)
	at dotty.tools.dotc.Driver.main(Driver.scala:186)
	at dotty.tools.dotc.decompiler.Main.main(Main.scala)
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/tastyreflect/ReflectionCompilerInterface.scala [hunk 1]
```diff
@@ -1459,12 +1459,12 @@ class ReflectionCompilerInterface(val rootContext: core.Contexts.Context) extend
   def Symbol_flags(self: Symbol)(given Context): Flags = self.flags
 
   def Symbol_tree(self: Symbol)(given Context): Tree = {
-    assert(!self.is(Case, butNot = Enum | Module))
+    assert(!self.is(Case) || self.isClass)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/tastyreflect/ReflectionCompilerInterface.scala]:
```Scala
case object A
```

will translate to a term `A` with the flag `Case`:

```Scala
package <empty> {
  final lazy module case <stable> <touched> val A: A$ = new A$()
  final module case <noinits> <touched> class A$ <method> <stable> <touched>()
     extends
   Object(), _root_.scala.Product, _root_.scala.Serializable { this: A.type =>}
}
```

The same for enums:

```Scala
enum Color {
  case Red, Green, Blue
}
```

is transalted to

```Scala
    case <stable> <static> <enum> <touched> val Red: Color =
      Color.$new(0, "Red")
    case <stable> <static> <enum> <touched> val Green: Color =
      Color.$new(1, "Green")
    case <stable> <static> <enum> <touched> val Blue: Color =
      Color.$new(2, "Blue")
```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/tastyreflect/ReflectionCompilerInterface.scala]: There is no point having those assertions anyway. In the next PR `Symbol_tree` will return binds as well.
