### PR TITLE
Fix #5521: prefix not checked in realizability check

### LINKED ISSUE #5521: Prefix not checked in realizability check for non-final lazy val
```
  1 class Hello {
  2   class Foo {
  3     class Bar
  4     final lazy val s: Bar = ???
  5   }
  6 
  7   lazy val foo: Foo = ???
  8 
  9   val x: foo.s.type = ???
 10   val x2: foo.s.type = ???
 11 }
```
Expected: both line 9 and 10 produce an error.

Actual: only line 10 produces an error:
```
10 |  val x2: foo.s.type = ???
   |              ^
   |              Hello.this.foo.Bar(Hello.this.foo.s) is not a legal path
   |              since it refers to nonfinal lazy value foo
```

The reason is the cached and uncached cases are handled differently in https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/CheckRealizable.scala#L80
The uncached case doesn't check the prefix (hence why only the second time we try to use the same invalid path errors out).

### PR DESCRIPTION
**Pull request by abeln**
We were forgetting to check the prefix in the uncached case.

### CODE REVIEW

**Comment by abeln** [comment]
@Blaisorblade do you have time to take a look? Guillaume mentioned on gitter that you were looking at `CheckRealizable`.

File: compiler/src/dotty/tools/dotc/core/CheckRealizable.scala [hunk 1]
```diff
@@ -77,8 +77,11 @@ class CheckRealizable(implicit ctx: Context) {
           else if (!isLateInitialized(sym)) realizability(tp.prefix)
           else if (!sym.isEffectivelyFinal) new NotFinal(sym)
           else realizability(tp.info).mapError(r => new ProblemInUnderlying(tp.info, r))
-        if (r == Realizable) sym.setFlag(Stable)
-        r
+        val r1 = if (r == Realizable) {
+          sym.setFlag(Stable)
+          realizability(tp.prefix)
```
Comment (Blaisorblade) [inline compiler/src/dotty/tools/dotc/core/CheckRealizable.scala]: I looked at this time ago in #4036, I should look more closely, and I'm in a rush, but here are some initial comments.

I agree this is a bug and this change should give the correct behavior; but this change risks being pretty computationally expensive (possible fix below). This can duplicate recursive calls, and that risks causing exponential slowdowns. Triggering it might require a chain of final lazy vals or be impossible, but it's more robust to not duplicate calls.

If `isLateInitialized(sym)`, this calls `realizability(tp.prefix)` again, and that can be too expensive. Caching only affects symbols, but we don't cache `realizability` on whole types; `tp` could not even be a `TermRef` and fall through `boundsRealizability(tp).andAlso(memberRealizability(tp))`.

I asked dottybot for a performance test. But maybe one could just reorganize the logic.
Looking at #4036 (which is where I "studied" this), I propose to add to your change the following:
```diff
-else if (!isLateInitialized(sym)) realizability(tp.prefix)
+else if (!isLateInitialized(sym)) Realizable
```
because in this branch we can certainly mark the symbol as stable (that PR also achieves this goal, though in a hackier way). If that works, this PR can go in with that fix.

## Optional requests

Here's a couple of bonus requests one could fix here as well — if they are non-trivial, feel free to defer them. I should probably do these changes myself and PR them, I'm in a rush right now.

On performance: https://github.com/lampepfl/dotty/pull/4036/files#diff-0535d82f8f57a2204d6452bae575efc9 might be a useful test here (if it doesn't cause a stack overflow).

On error reporting, I think one could cherry-pick from #4036 the following:
```diff
-realizability(tp.prefix)
+realizability(tp.prefix).mapError(r => new ProblemInUnderlying(tp.prefix, r))
```

**Comment by Blaisorblade** [comment]
test performance please

**Comment by Blaisorblade** [comment]
@abeln To move things along I did the necessary changes myself — basic tests pass locally, let's see what the CI says. I've stuck to changes that really belong here to avoid scope creep.

**Comment by Blaisorblade** [comment]
test performance please

**Comment by Blaisorblade** [comment]
Martin wrote:
> If you are comfortable with #5522, yes please go ahead and merge it. Maybe run a performance test again, to be sure.

so doing that.

**Comment by abeln** [comment]
@Blaisorblade thanks for doing this, and sorry I didn't get to it myself! I got busy trying to get the flow-sensitive type inference to work for the null project (still working on it).
