### PR TITLE
Fix #7852: avoid reading stale .tasty files from jars

### LINKED ISSUE #7852: Tasty UUID file did not correspond the tasty UUID
## minimized code

Reproducible code project attached: [oids.zip](https://github.com/lampepfl/dotty/files/4002839/oids.zip)

### steps to reproduce:

1. Unpack the archive above and `cd` into it
2. `sbt`
3. `~desktop/run`
4. Try writing a few changes to `Oids.scala` and/or `Main.scala`. Usually after 3-4 compilations I see the UUID error.

## expectation

When I run `sbt desktop/run` my application should run. Instead I get the following output:

```
sbt:all-platforms> desktop/run
[info] Compiling 1 Scala source to /Users/cory.klein/code/playground/oids/core/target/scala-0.20/classes ...
[info] Done compiling.
[info] Packaging /Users/cory.klein/code/playground/oids/core/target/scala-0.20/core_0.20-0.1.0.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /Users/cory.klein/code/playground/oids/desktop/target/scala-0.20/classes ...
[error] Tasty UUID (00580745-b126-5400-0085-2577bf86b400) file did not correspond the tasty UUID (00de03e0-a506-9b00-00fa-46ff8b91a900) declared in the classfile /Users/cory.klein/code/playground/oids/core/target/scala-0.20/core_0.20-0.1.0.jar(com/coryfklein/oids/Oids.class).
[error] one error found
[error] (desktop / Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed Dec 26, 2019 8:04:53 AM
```

The specific error I want to call out is `Tasty UUID (00580745-b126-5400-0085-2577bf86b400) file did not correspond the tasty UUID (00de03e0-a506-9b00-00fa-46ff8b91a900) declared in the classfile /Users/cory.klein/code/playground/oids/core/target/scala-0.20/core_0.20-0.1.0.jar(com/coryfklein/oids/Oids.class)`

This appears to happen intermittently, although once it starts it is difficult to get it to go away.

Is there anything I can try to help debug this or some reliable way to clear out the bad state?

EDIT: It appears to go away when I exit my `sbt` console and open it again. Next time I'll try and see if `reload` fixes the issue.

EDIT2: `reload` does not fix the issue, but exiting `sbt` and re-running it again still works.

### PR DESCRIPTION
**Pull request by smarter**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -780,22 +780,29 @@ class ClassfileParser(
...
-                tastyOutStream.flush()
-                tastyOutStream.toByteArray
               }
-              else {
-                ctx.error(s"Could not find $path in $jar")
-                Array.empty
+              finally {
+                // If we don't close the classloader, spooky things happen (see
+                // scripted test source-dependencies/export-jars2).
+                cl.close()
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala]: I wonder if we should also handle potential `IOExceptions` from `close`

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala]: I can't find any other place in the compiler where we do that currently, so I wouldn't bother

**Comment by smarter** [comment]
I had to use a different approach, see latest commit
