### PR TITLE
Fix #7380: Check type members of mirror formals

### LINKED ISSUE #7380: Unsoundness with Mirrors: it is possible to summon a mirror with an incorrect MirrorElemTypes of your choice
# Example
```scala
import scala.deriving.Mirror

@main def Test =
  val mrr = summon[Mirror.Of[(Int, String)] { type MirroredElemTypes = (Int, Int, Int) }]
  val ev1 = summon[(Int, Int, Int) =:= mrr.MirroredElemTypes]
  val ev2 = summon[(Int, String) =:= mrr.MirroredElemTypes]
  // val ev3 = summon[(Int, String) =:= (Int, Int, Int)]  // Implicit not found (correct, but breaks transitivity)

  val tup: (Int, String) = (1, "foo")
  val res: mrr.MirroredElemTypes = tup
```

Run it:

```scala
Exception in thread "main" java.lang.ClassCastException: scala.Tuple2 cannot be cast to scala.Tuple3
	at Test$package$.Test(Test.scala:10)
	at Test.main(Test.scala:3)
```

# Expectation
I would expect `mrr` to be impossible to summon because of the bad refinement type.

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 1]
```diff
@@ -219,6 +219,12 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
       case _ => true
     loop(formal)
 
+  private def checkRefinement(formal: Type, name: TypeName, expected: Type, span: Span)(using Context): Unit =
+    val actual = formal.lookupRefined(name)
+    if actual.exists && !(expected =:= actual)
+    then report.error(
+      em"$name missmatch, expected: $expected, found: $actual.", ctx.source.atSpan(span))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:226]:
```suggestion
      em"$name mismatch, expected: $expected, found: $actual.", ctx.source.atSpan(span))
```

**Review by smarter — APPROVED** [review]
