### PR TITLE
Turn mismatch given errors into given not found errors

### LINKED ISSUE #8053: $conforms[Nothing] shows up as a placeholder for missing implicits
## minimized code

```Scala
class Foo

List(new Foo).sorted
```

https://scastie.scala-lang.org/27qWTarCSHyAW7OtgXGGvg

The error message unexpectedly mentions `$conform[Nothing]`.

```
No implicit Ordering defined for B

where:    B is a type variable with constraint >: Foo

I found:

    scala.math.Ordering.ordered[A]($conforms[Nothing])

But method $conforms in object Predef does not match type scala.math.Ordering.AsComparable[A].
```

## expectation

The error message should be:

~~~
No implicit Ordering defined for B

where: B is a type variable with constraint >: Foo
~~~

(there should be no “I found: ...” part)

### PR DESCRIPTION
**Pull request by julienrf**
Fixes #8053

When a given candidate turns out to not be applicable we used to report that
there is a mismatch between the candidate type and the expected type.

However, I believe that if there is a type mismatch, then the candidate should
not be a candidate in the first place.

I’ve changed the failure to be a `NoMatchingImplicitsFailure` instead of a mismatch.

Hopefully this won’t have a negative impact. I’ve added a couple of tests that used to
report a mismatch for the "candidate" `$conforms[Nothing]` and they now report that
no given could be found. One existing test was broken by my changes. This test was
very similar to the ones described in #8053, so I’ve changed the test expectation.

### CODE REVIEW

**Comment by julienrf** [comment]
How can I reproduce the test failure? I’ve run `dotty-compiler-bootstrapped/test` but didn’t get the failure reported by the CI.

**Comment by smarter** [comment]
My guess is that there's some non-determinism in the order in which we look for implicits, which leads to non-deterministic error output.

**Comment by odersky** [comment]
I doubt this is an improvement. At least the previous strategy was intentional. The idea is to always provide the most specific information. If there is just one candidate that could plausibly match, and it doesn't in the end, I want to find out why by getting a type mismatch error. "Implicit not found" is much less helpful.

**Comment by julienrf** [comment]
@odersky I don’t completely agree: it’s true that it’s better to provide the most precise information as possible to the user, but in our case I think the information we provide is useless: if the candidate can’t be typed, then it should not be a candidate in the first place. But maybe there are other kinds of mismatch that could be worth reporting?

Do we agree at least that inferring `$conforms[Nothing]` or `refl[Nothing]` is useless because these types are uninhabited anyway? Could we at least add a special case to turn those two specific “mismatches” into “not found”?

**Comment by odersky** [comment]
> Do we agree at least that inferring $conforms[Nothing] or refl[Nothing] is useless because these types are uninhabited anyway? Could we at least add a special case to turn those two specific “mismatches” into “not found”?

Yes, that makes sense!

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -1407,11 +1407,15 @@ trait Implicits { self: Typer =>
...
-          adapted.tpe match {
-            case _: SearchFailureType => adapted
-            case _ => adapted.withType(new MismatchedImplicit(ref, pt, argument))
-          }
+        adapted.tpe match {
+          case _: SearchFailureType => SearchFailure(adapted)
+          case _ =>
+            // Special case for `$conforms[Nothing]` and `<:<.refl[Nothing]`. Showing them
+            // up to the users brings no value, so we instead report a `NoMatchingImplicitsFailure`
+            if (adapted.show == "$conforms[Nothing]" || adapted.show == "<:<.refl[Nothing]")
```
Comment (julienrf) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: In case it is not recommended to use `show` to compare trees, could you please advise on how to build the following tree?

~~~
TypeApply(Ident($conforms),List(TypeTree[TypeVar(TypeParamRef(A) -> TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing))]))
~~~

In particular, I’m not sure how to construct the part of the tree that are tostringed to “module class scala” and “class Nothing”.

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 2]
```diff
@@ -1407,11 +1407,15 @@ trait Implicits { self: Typer =>
...
+              NoMatchingImplicitsFailure
+            else
+              SearchFailure(adapted.withType(new MismatchedImplicit(ref, pt, argument)))
```
Comment (julienrf) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: Note that there are (and they were) no tests to exercise this code path.

File: tests/neg/missing-implicit3.check [hunk 3]
```diff
@@ -0,0 +1,18 @@
+-- Error: tests/neg/missing-implicit3.scala:3:37 -----------------------------------------------------------------------
+3 |val sortedFoos = List(new Foo).sorted // error
+  |                                     ^
+  |                  No implicit Ordering defined for B
+  |
+  |                  where:    B is a type variable with constraint >: Foo
+  |                  ..
+  |                  I found:
+  |
+  |                      scala.math.Ordering.ordered[A](/* missing */implicitly[scala.math.Ordering.AsComparable[B]])
```
Comment (smarter) [inline tests/neg/missing-implicit3.check:10]: Could you use some locally defined implicits instead of depending on what is in the standard library? It makes the test more stable in case the library changes, and it seems that even when the library don't change our output is not stable based on earlier failures of this PR (this is something we should try to fix, but it might be hard).

Comment (julienrf) [reply tests/neg/missing-implicit3.check:10]: Sure I can do that. On the other hand, please be aware that by creating artificial test scenarios we might simplify the reality and miss bugs/limitations.

This is what motivated this PR: the existing test suite for import suggestions was only based on artificial scenarios and we didn’t know that the output of the compiler was not good on some real world cases.

Comment (julienrf) [reply tests/neg/missing-implicit3.check]: Fixed and squashed.
