### PR TITLE
Fix #6999: Emit an error when using type splice in quoted val pattern

### LINKED ISSUE #6999: Quote pattern spliced expression has wrong type
## minimized code

```Scala
def expr(e: Expr[Any]) = {
  val '{ $x: $t } = e
  '{
    val a: $t = $x
   }
}
```

```
30 |        val a: $t = $x
   |                     ^
   |                     Found:    scala.quoted.Expr[Any](x)
   |                     Required: quoted.Expr[t.T]
```

## expectation
`x` should have type `quoted.Expr[t.T]`

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -1740,7 +1740,8 @@ object desugar {
         new TreeTraverser {
           def traverse(tree: untpd.Tree)(implicit ctx: Context): Unit = tree match {
             case Splice(expr) => collect(expr)
-            case TypSplice(expr) => collect(expr)
+            case TypSplice(expr) =>
+              ctx.error("Type splices cannot ve used in val patterns. Consider using `match` instead.", tree.sourcePos)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala]: typo: `ve` -> `be`
