### PR TITLE
Fix #8355: REPL tests : fix for two tests failing on Windows

### LINKED ISSUE #8355: REPL tests : fix for two tests failing on Windows
## Minimized code

The following two REPL tests
- [`LoadTests.scala`](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/repl/LoadTests.scala)
- [`ReplCompilerTests.scala`](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/repl/ReplCompilerTests.scala)

are failing on Windows due to EOL mismatches between the *expected* output and the *actual* output produced by a REPL snipplet. Concretely statement `assertEquals(expected, actual)` does fail in 4 cases : [line 58](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/LoadTests.scala#L58), [line 60](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/LoadTests.scala#L62), [line 160](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/ReplCompilerTests.scala#L160) and [line 176](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/ReplCompilerTests.scala#L176).

## Compilation output

```shell
> sbt -sbt-version 1.3.8 "compile; test"
[info] Loading settings for project dotty-multiline-build-build from build.sbt ...
[info] Loading project definition from W:\dotty-multiline\project\project
[...]
[error] Failed: Total 364, Failed 10, Errors 0, Passed 352, Skipped 2
[error] Failed tests:
[error]         dotty.tools.repl.ReplCompilerTests   <=======
[error]         dotty.tools.repl.LoadTests           <=======
[error]         dotty.tools.dotc.CompilationTests
[error]         dotty.tools.repl.ScriptedTests
[info] Passed: Total 75, Failed 0, Errors 0, Passed 75
[error] (dotty-compiler / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1421 s (23:41), completed 20 Feb 2020 23:16:27
```

## Expectation

```shell
> sbt -sbt-version 1.3.8 "compile; test"
[info] Loading settings for project dotty-multiline-build-build from build.sbt ...
[info] Loading project definition from W:\dotty-multiline\project\project
[...]
[error] Failed: Total 363, Failed 5, Errors 0, Passed 356, Skipped 2
[error] Failed tests:
[error]         dotty.tools.dotc.CompilationTests
[error]         dotty.tools.repl.ScriptedTests
[error] (dotty-compiler / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1421 s (23:41), completed 20 Feb 2020 22:48:17
```

**NB.** Both tests `dotc.CompilationTests` and `repl.ScriptedTests` will be handled by another PR.

## Solution

As a preamble, I'd like to mention that file `repl.ReplCompilerTests.scala` uses in some test cases a workaround to that issue, namely function [`lines()`](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/ReplCompilerTests.scala#L8) - which returns a list of lines (w/o line ending) - is used in two `assertEquals` tests ([line 57](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/ReplCompilerTests.scala#L57) and [line 128](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/ReplCompilerTests.scala#L128)) where two lists rather than two (multiline) strings are compared.

My solution is to replaced `assertEquals` with `assertMultilineEquals` in the above 4 cases.
Before submitting a PR, I'd like to get your feedback about the following two implementations :

### Solution 1
String `expected` keeps untouched (role similar to a check file).

```scala
object LoadTests {
  // ... (some more code) ...
  private val pattern = Pattern.compile("\\r[\\n]?|\\n");

  // Ensure 'expected' and 'actual' contain the same line separator(s).
  private def assertMultiLineEquals(expected: String, actual: String): Unit = {
    val m = pattern.matcher(expected)
    val actual0 =
      if (m.find()) {
        val expectedLineSep = m.group()
        pattern.matcher(actual).replaceAll(expectedLineSep)
      }
      else
        actual
    assertEquals(expected, actual0)
  }

}
```

### Solution 2
Both strings are transformed (*"brut force"*) and passed to `assertEquals`.

```scala
object LoadTests {
  // ... (some more code) ...
  private val pattern = Pattern.compile("\\r[\\n]?|\\n");

  // Ensure 'expected' and 'actual' contain the same line separator(s).
  private def assertMultiLineEquals(expected: String, actual: String): Unit = {
    val expected0 = pattern.matcher(expected).replaceAll(System.lineSeparator)
    val actual0 = pattern.matcher(actual).replaceAll(System.lineSeparator)
    assertEquals(expected0, actual0)
  }

}
```

### PR DESCRIPTION
**Pull request by michelou**
See description/review in #8355.

### CODE REVIEW

File: compiler/test/dotty/tools/repl/LoadTests.scala [hunk 1]
```diff
@@ -82,4 +83,13 @@ object LoadTests {
     file
   }
 
+  private val pattern = Pattern.compile("\\r[\\n]?|\\n");
+
+  // Ensure 'expected' and 'actual' contain the same line separator(s).
+  private def assertMultiLineEquals(expected: String, actual: String): Unit = {
```
Comment (smarter) [inline compiler/test/dotty/tools/repl/LoadTests.scala]: Instead of duplicating this method in two file, could you use `ReplCompilerTests.assertMultiLineEquals` in thsi file ?

Comment (michelou) [reply compiler/test/dotty/tools/repl/LoadTests.scala]: Fine for me if having a dependency between `LoadTests` and `ReplCompilerTests` is ok for you !
