### PR TITLE
FIx Ctrl+C handling in the REPL

### LINKED ISSUE #25551: Repl returns null when using io.StdIn.readLine()
## Compiler version

`3.8.2`

## Minimized code

```scala

def askQuestion(msg: String): Boolean =
  print(msg)
  io.StdIn.readLine() match
    case "y" | "Y" => true
    case "n" | "N" => false
    case other         =>       
      askQuestion(msg)
```

When we run REPL and invoke askQuestion it ends up in an infinite loop. The other case with null seems to be matched.

## Output

For:
```
> askQuestion("question?")
```

```scala
question?question?question?question?question?question?question?....
```

## Expectation

nothing is returned until user writes the answer.

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #25551

Basically a revert of #24842, plus some minor cleanups.

I've spent a day trying to make it work with raw mode and failed. A working REPL that offers suboptimal UX inside other processes is better than a nonworking REPL that offers slightly better UX.

I don't think the "raw mode" approach, nor any approach based on handling `System.in` manually in one way or another, can work for a REPL that lets users consume from `System.in` themselves.

## How much have you relied on LLM-based tools in this contribution?

not

## How was the solution tested?

manually with `scala3-repl / run` it no longer messes up stdin input, with `bin/replQ` after `sbt buildQuick` neither, and Ctrl+C works in these scenarios

and

`sbt scala3-bootstrapped/publishLocalBin`

then write `mill-build/build.mill`:

```scala
package build

import mill.*, scalalib.*
import mill.api.*

object `package` extends ScalaModule:
  object JvmWorker extends JvmWorkerModule:
    override def repositories =
      super.repositories() ++ Seq(CoursierModule.KnownRepositories.ScalaLangNightlies)

  override def jvmWorker: ModuleRef[JvmWorkerModule] = ModuleRef(JvmWorker)
  override def repositories =
    super.repositories() ++ Seq(CoursierModule.KnownRepositories.ScalaLangNightlies)
  def scalaVersion = "3.8.5-RC1-bin-SNAPSHOT" // change this
```

then `./mill.sh --repl` stdin works but Ctrl+C terminates the entire Mill process on Ctrl+C, which is not great but I think this should be handled in Mill.

### CODE REVIEW

File: repl/src/dotty/tools/repl/JLineTerminal.scala [hunk 1]
```diff
@@ -48,7 +49,7 @@ class JLineTerminal extends java.io.Closeable {
   private val history = new DefaultHistory
 
   private def magenta(str: String)(using Context) =
-    if (ctx.settings.color.value != "never") Console.MAGENTA + str + Console.RESET
+    if (ctx.settings.color.value != "never") AnsiColor.MAGENTA + str + AnsiColor.RESET
```
Comment (SolalPirelli) [inline repl/src/dotty/tools/repl/JLineTerminal.scala:39]: I noticed as a side thing that `Console` captures `System.in/out/err` as they are when it's first initialized, so it's probably better to not initialize it within the REPL...

**Comment by SolalPirelli** [comment]
@lihaoyi what steps can I take to make sure this doesn't re-break REPL-inside-Mill ?

**Comment by lihaoyi** [comment]
@SolalPirelli publish a local version, use the local version in a Mill `ScalaModule`, and call `.repl` to test it

**Comment by Gedochao** [comment]
@lihaoyi I think we wanted the steps to make sure the initial ctrl+c fix for Mill is preserved while fixing https://github.com/scala/scala3/issues/25551

**Comment by lihaoyi** [comment]
@Gedochao yeah, I meant open up the `repl` and manually test Ctrl-C in it: while running `while (true) {}`, `Iterator.continually(1).sum`, make sure Ctrl-C can interrupt it correctly when using your locally published version of Scala

**Comment by SolalPirelli** [comment]
OK so this preserves Ctrl+C but stdin is still null... yay, more investigation needed

File: repl/src/dotty/tools/repl/JLineTerminal.scala (hunk 1 above)
Comment (Gedochao) [reply repl/src/dotty/tools/repl/JLineTerminal.scala:39]: Given that we don't have a test covering it, maybe a comment explaining that would be nice here.

**Review by Gedochao — APPROVED** [review]
LGTM
Tested locally and seems to solve the issue (although can't say I'm very familiar with these internals).

I'm guessing that having a test for this is a tall order?

File: repl/src/dotty/tools/repl/JLineTerminal.scala (hunk 1 above)
Comment (SolalPirelli) [reply repl/src/dotty/tools/repl/JLineTerminal.scala:39]:
```suggestion
    // Deliberately do not use these properties on `Console` to avoid initializing it,
    // and thus capturing stdin/stdout/stderr state in its `Console.in/out/err` properties,
    // since the REPL may wish to change the std streams before giving control to the user.
    if (ctx.settings.color.value != "never") AnsiColor.MAGENTA + str + AnsiColor.RESET
```

**Comment by SolalPirelli** [comment]
> I'm guessing that having a test for this is a tall order?

Yeah I don't even know where to begin. Though I'll add a comment reminding people to test manually.

File: repl/src/dotty/tools/repl/JLineTerminal.scala [hunk 2]
```diff
@@ -100,34 +88,15 @@ class JLineTerminal extends java.io.Closeable {
...
 
   def close(): Unit =
-    try terminal.setAttributes(originalAttributes)
-    finally terminal.close()
+    terminal.close()
 
   /** Execute a block while monitoring for Ctrl-C keypresses.
    *  Calls the handler when Ctrl-C is detected during block execution.
    */
   def withMonitoringCtrlC[T](handler: () => Unit)(block: => T): T = {
```
Comment (SolalPirelli) [inline repl/src/dotty/tools/repl/JLineTerminal.scala:96]:
```suggestion
  def withMonitoringCtrlC[T](handler: () => Unit)(block: => T): T = {
  // If you change Ctrl+C handling in any way, such as by trying to read/peek from stdin for Ctrl+C,
  // make sure you manually check that reading from, e.g., `Console.in` still works!
  // Remember that the user can use stdin from code they enter into the REPL, we do not have exclusive access to it.
```

**Comment by SolalPirelli** [comment]
@lihaoyi sorry to have to effectively revert your PR but I really couldn't find a way to make Ctrl+C handling not stop Mill while also not screwing with stdin if the user wants to read it. Perhaps Mill itself can be changed to also handle Ctrl+C and not quit if it's running the REPL?
