### PR TITLE
Fix #8842: Refine types of inlined inline vals

### LINKED ISSUE #8842: Inline val in inline def does not always get a constant type
## Minimized code

```Scala
inline def f(inline x: Int): Unit = {
  inline val twice = x + x
}

def test: Unit = f(3)
```

## Output

```scala
-- Error: Foo.scala:7:18 -------------------------------------------------------
7 |def test: Unit = f(3)
  |                 ^^^^
  |                 type of inline must be a known value
  | This location contains code that was inlined from Foo.scala:3

result of Foo.scala after typer:
package <empty> {
  final lazy module val Foo$package: Foo$package$ = new Foo$package$()
  final module class Foo$package$() extends Object(), _root_.scala.Serializable
     {
   this: Foo$package.type =>
    inline def f(inline x: Int): Unit = 
      {
        inline val twice: Int = x.+(x)
        ()
      }:Unit
    def test: Unit = 
      {
        {
          inline val twice: Int = 6
          ()
        }:Unit
      }
  }
}
```

## Expectation
When `f` is inlined, the type of `twice` should be `6`. Therewise we wont be able to inline this value.
```scala
    def test: Unit = 
      {
        {
          inline val twice: 6 = 6
          ()
        }:Unit
      }
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -1219,6 +1219,15 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
             super.typedIf(if1, pt)
       }
 
+    override def typedValDef(vdef: untpd.ValDef, sym: Symbol)(using Context): Tree =
+      val vdef1 =
+        if sym.is(Inline) then
+          val rhs = typed(vdef.rhs)
+          sym.info = rhs.tpe
+          untpd.cpy.ValDef(vdef)(vdef.name, untpd.TypedSplice(TypeTree(rhs.tpe)), untpd.TypedSplice(rhs))
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:1227]:
```suggestion
          untpd.cpy.ValDef(vdef)(vdef.name, untpd.TypeTree(rhs.tpe), untpd.TypedSplice(rhs))
```
