### PR TITLE
Do not propagate `@tailrec` to exported methods

### LINKED ISSUE #19505: Cannot export `@tailrec` method
## Compiler version

3.3.1

## Minimized code

```Scala
import scala.annotation.tailrec

object Foo:
  @tailrec
  def foo: Int = foo

object Bar:
  export Foo.foo
```

## Output

```
-- [E097] Syntax Error: --------------------------------------------------------
9 |  export Foo.foo
  |             ^
  |TailRec optimisation not applicable, method foo contains no recursive calls
```

## Expectation

I should be able to export a `@tailrec` method.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #19505

### CODE REVIEW

**Review by sjrd — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 1]
```diff
@@ -1254,7 +1254,10 @@ class Namer { typer: Typer =>
               newSymbol(cls, forwarderName, mbrFlags, mbrInfo, coord = span)
 
           forwarder.info = avoidPrivateLeaks(forwarder)
-          forwarder.addAnnotations(sym.annotations.filterConserve(_.symbol != defn.BodyAnnot))
+          forwarder.addAnnotations(sym.annotations.filterConserve { annot =>
+            annot.symbol != defn.BodyAnnot
+            && annot.symbol != defn.TailrecAnnot
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:1259]: alternatively, could the tailrec check for the exported flag and ignore it?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:1259]: Right, we also need to filter macro annotations. 

I think that disabling the behavior where it is checked will be less scalable. For example, I disable the macro annotations on exports I have to find one or more places where this restriction needs to be taken into account. And those places are usually code generation details like exports.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:1259]: I also added `@main`. Might might still need to filter others.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:1259]: I wonder if we should have a whitelist approach with this one. This would make sure that we never accidentally keep an annotation we do not want.

I tested this on `scala3-bootstrapped/testCompilation` and it only required the `@targetName` annotation.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:1259]: The thing is that we will never know what should be the behavior for custom annotations.

The only holistic solution here is to have an `@meta`-based indication of what to do. This is the approach used to determine whether annotations should go to fields/getters/setters. It would also be appropriate to determine whether it should go to exports/bridges/etc.

**Review by bishabosha — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/typer/Namer.scala (hunk 1 above)
Comment (soronpo) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:1259]: Maybe we need `ExportableAnnotation` trait that all such annotations should extend to get exported.
