### PR TITLE
Fix #12530: Wildcard of value types don't cover null

### LINKED ISSUE #12530: Missing warning for unreachable case when matching on a tuple
## Compiler version

Scala pre-3.0.1 at commit https://github.com/lampepfl/dotty/commit/c1eaf8cff63ae23948cca6cb7a9f132ff22b2537

## Minimized code

```Scala
object Test {
  def foo(a: Boolean, b: Boolean): Unit =
    (a, b) match {
      case (false, _) =>
      case (true,  _) =>
      case (_, false) => // unreachable
    }
}
```

## Output

No warning

## Expectation

Emit an unreachable case warning like Scala 2 does:
```scala
warning: unreachable code
      case (_, false) => // unreachable
                      ^
```
However, note that Scala 2 also fails to emit such a warning in a more complex example:
```scala
object Test {
  def foo(a: Option[Boolean], b: Boolean): Unit =
    (a, b) match {
      case (Some(false), _) =>
      case (Some(true), _) =>
      case (None, _) =>
      case (_, false) => // unreachable
    }
}
```

In Scala 3 the issue seems to be that tuples are not considered to be decomposable types, but I don't know if this is intentional to avoid a complexity blow up /cc @liufengyun

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #12530: Wildcard of value types don't cover null

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -355,18 +355,21 @@ class SpaceEngine(using Context) extends SpaceLogic {
...
-        Typ(ConstantType(c), false)
+        Typ(ConstantType(c), decomposed = false)
 
     case pat: Ident if isBackquoted(pat) =>
-      Typ(pat.tpe, false)
+      Typ(pat.tpe, decomposed = false)
 
     case Ident(nme.WILDCARD) =>
-      Or(Typ(erase(pat.tpe.stripAnnots), false) :: constantNullSpace :: Nil)
+      if pat.tpe <:< defn.AnyValType then
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:366]: could we use [isNullableClass](https://github.com/lampepfl/dotty/blob/d2dd0832fec8416b934d730a7e785d79f6218777/compiler/src/dotty/tools/dotc/core/SymDenotations.scala#L800) instead? That way null won't pollute our patterns when -Yexplicit-nulls is enabled.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:366]: also, for exhaustiveness we don't report missing nulls, so maybe it's fine to do the same for unreachability?
```scala
scala> final case class Foo(x: Int)
// defined case class Foo

scala> def foo(x: Foo) = x match { case Foo(_) => }
def foo(x: Foo): Unit

scala> foo(null)
scala.MatchError: null
```

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:366]: actually I guess we should emit a warning `_ only matches null` like we already do for `case _ =>`

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:366]: We have a feature that reports a warning if the last wildcard only matches `null` (https://github.com/lampepfl/dotty/pull/4253#discussion_r179486080). I think removing the `null` related stuff will make the code simpler.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:366]: > actually I guess we should emit a warning `_ only matches null` like we already do for `case _ =>`

That would make the check more complex and expensive, while not very useful to users. I think removing `null` related logic will produce expected and helpful warnings to users while keeping the logic simple and fast.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: Actually, we can avoid computing precisely whether a pattern covers exactly `null`. Instead, we can blindly provide a hint for `null` if the last case is `_` and is unreachable. This allows us to use `Typ(tp)` instead of `Or(Type(tp), nullSpace)` for a wildcard pattern.

Doing that simplifies the code, and uncovers a bug that I'm now investigating:

```Scala
object Test {
  sealed trait Cause[+E]

  object Cause {
    final case class Fail[E](value: E) extends Cause[E]
  }

  def fn(cause: Cause[Any]): String =
    cause match {
      case Cause.Fail(t: Throwable) => t.toString
      case Cause.Fail(any)          => any.toString
    }
}
```

Previously no warning is produced because the checker thought that 2nd case matches `Fail(null)`, which is incorrect.

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 2]
```diff
@@ -838,7 +838,7 @@ import transform.SymUtils._
 
   class MatchCaseOnlyNullWarning()(using Context)
   extends PatternMatchMsg(MatchCaseOnlyNullWarningID) {
-    def msg = em"""Only ${hl("null")} is matched. Consider using ${hl("case null =>")} instead."""
+    def msg = em"""Unreachable case. If ${hl("null")} is matched, consider using ${hl("case null =>")}."""
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:841]: If this case is potentially reachable by null then it's a bit misleading to say it's unreachable, I think the previous wording was fine, otherwise we could go with something like this:
```suggestion
    def msg = em"""Unreachable case except for ${hl("null")} (if this is intentional, consider writing ${hl("case null =>")} instead)."""
```

**Review by smarter — APPROVED** [review]
Otherwise LGTM
