### PR TITLE
Fix #6709: Correlate match types and match expression

### LINKED ISSUE #6709: Correlating match types with pattern matching expressions
I've been trying to use match types to implement a type-level binary nat type.

Here is the code I would ideally like to work:
```scala
object Main {

  enum BinNat {
    case Zero
    // 2n + 1
    case Odd[N <: BinNat](n: N)
    // 2(n + 1)
    case Even[N <: BinNat](n: N)
  }

  import BinNat._

  type Inc[N <: BinNat] <: BinNat =
    N match {
      case Zero.type => Odd[Zero.type]
      case Odd[n] => Even[n]
      case Even[n] => Odd[Inc[n]]
    }

  def inc(b: BinNat): Inc[b.type] =
    b match {
      case Zero => Odd(Zero)
      case Odd(n) => Even(n)
      case Even(n) =>
        // 2(n + 1) + 1 = 2(inc(n)) + 1
        Odd(inc(n))
    }
}

```

The error message I get is:
```
[error] -- [E007] Type Mismatch Error: /Users/oscar/oss/dotty_tests/src/main/scala/Main.scala:30:22                                                                                     
[error] 30 |      case Zero => Odd(Zero)
[error]    |                   ^^^^^^^^^
[error]    |                   Found:    Main.BinNat
[error]    |                   Required: Main.Inc[Main.BinNat(b)]
[error] -- [E007] Type Mismatch Error: /Users/oscar/oss/dotty_tests/src/main/scala/Main.scala:31:25                                                                                     
[error] 31 |      case Odd(n) => Even(n)
[error]    |                     ^^^^^^^
[error]    |                     Found:    Main.BinNat
[error]    |                     Required: Main.Inc[Main.BinNat(b)]
[error] -- [E007] Type Mismatch Error: /Users/oscar/oss/dotty_tests/src/main/scala/Main.scala:34:11                                                                                     
[error] 34 |        Odd(inc(n))
[error]    |        ^^^^^^^^^^^
[error]    |        Found:    Main.BinNat
[error]    |        Required: Main.Inc[Main.BinNat(b)]
[error] three errors found
```

I have tried several different variants (using manual sealed trait/case classes, matching on `_: Zero.type`, explicitly adding type annotations in the `def inc` method... each seemed to trigger different errors and I couldn't find any that worked.

## expectation

I'd like it to compile, or suggest a better action to take in the error message

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
This PR adds a simple form of dependent typing by allowing match expressions to be typed as match types when their scrutinee type, pattern types, and body types align. Concretely, this means that we can define a value level counterpart to the `LeafElem` type from the match type documentation, and type check that expression with the match type: 

```scala
type LeafElem[X] = X match {
  case String      => Char
  case Array[t]    => LeafElem[t]
  case Iterable[t] => LeafElem[t]
  case AnyVal      => X
}

def leafElem[X](x: X): LeafElem[X] =
  x match {
    case x: String      => x.charAt(0)
    case x: Array[t]    => leafElem(x(0))
    case x: Iterable[t] => leafElem(x.head)
    case _: AnyVal      => x
  }
```

This special mode of typing for match expressions is only used when the following conditions are met: (that logic is implemented by the `isMatchTypeShaped` function in Typer.scala)

1. The match expression patterns do not have guards
2. The match expression scrutinee's type is a subtype of the match type scrutinee's type
3. The match expression and the match type have the same number of cases
4. The match expression patterns are all [Typed Patterns](https://scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html#typed-patterns), and these types are `=:=` to their corresponding type patterns in the match type

Follow up work could potentially relax some of these conditions, for instance to support unapply patterns that are equivalent to typed patterns.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1157,7 +1157,55 @@ class Typer extends Namer
         if (tree.isInline) checkInInlineContext("inline match", tree.posd)
         val sel1 = typedExpr(tree.selector)
         val selType = fullyDefinedType(sel1.tpe, "pattern selector", tree.span).widen
-        val result = typedMatchFinish(tree, sel1, selType, tree.cases, pt)
+
+        /** Extractor for match types hidden behind an AppliedType/MatchAlias */
+        object MatchTypeInDisguise {
```
[the remark this answers is not in the document]
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I haven't found any, is it ok to leave it nested in here until we found another use of it?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -1157,7 +1157,55 @@ class Typer extends Namer
...
+          tree.cases.forall(_.guard.isEmpty) &&
+          tree.cases
+            .map(cas => untpd.unbind(untpd.unsplice(cas.pat)))
+            .zip(mt.cases)
+            .forall {
+              case (pat: Typed, pt) =>
+                // To check that pattern types correspond we need to type
+                // check `pat` here and throw away the result.
+                val gadtCtx: Context = ctx.fresh.setFreshGADTBounds
+                val pat1 = typedPattern(pat, selType)(gadtCtx)
```
[the remark this answers is not in the document]
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I think that would be too much spaghetti, we should need pass these GADT contexts and the typed patterns around inside `typedMatchFinish`, `typedCases`, and zip them with the trees finally pass them to `typedCase` where they are needed...

**Comment by OlivierBlanvillain** [comment]
I agree the commit updating the docs was unreviewable, I've just splitted it into 6 smaller commits with some explanations in the commit message to justify the changes. I will wait for your input on which part of the delete text you would like to preserve before thinking about creating a *more details* docs page.

File: docs/docs/reference/new-types/match-types.md [hunk 3]
```diff
@@ -90,34 +90,25 @@ Here, `[Xs]` is a type parameter clause of the variables bound in pattern `Pi`.
...
 
-We define match type reduction in terms of an auxiliary relation, `can-reduce`:
+Match type reduction follows the semantics of match expression, that is, a match type of the form `S match { P1 => T1 ... Pn => Tn }` reduces to `Ti` if and only if `s: S match { _: P1 => T1 ... _: Pn => Tn }` evaluates to a value of type `Ti` for all `s: S`.
 
-```
-Match(S, C1, ..., Cn)  can-reduce  i, T'
-```
-if `Ci = [Xs] => P => T` and there are minimal instantiations `Is` of the type variables `Xs` such that
-```
-S <: [Xs := Is] P
```
Comment (odersky) [inline docs/docs/reference/new-types/match-types.md]: The problem is that the rewritten version only talks about subtyping, not about type variable instantiation. But instantiation is crucial for understanding what goes on in more complicated examples. Maybe the existing text is not clear enough. Then it needs to be improved, but it should not be dropped outright.

File: docs/docs/reference/new-types/match-types.md [hunk 4]
```diff
@@ -143,55 +143,6 @@ The third rule states that a match type conforms to its upper bound
 
 Within a match type `Match(S, Cs) <: B`, all occurrences of type variables count as covariant. By the nature of the cases `Ci` this means that occurrences in pattern position are contravarant (since patterns are represented as function type arguments).
 
-## Handling Termination
-
```
Comment (odersky) [inline docs/docs/reference/new-types/match-types.md]: Agree that the tone of the description is more like an issue and not like a spec. But a spec still has to talk about termination. So the info needs to be given, just formulated differently.

File: docs/docs/reference/new-types/match-types.md [hunk 5]
```diff
@@ -56,197 +85,117 @@ is `Match(S, C1, ..., Cn) <: B` where each case `Ci` is of the form
...
-(The actual error message shows some additional lines in the stacktrace).
+
+Internally, `dotc` detects these cycles by turning selected stackoverflows
+into type errors. If there is a stackoverflow during subtyping, the exception
+will be caught and turned into a compile-time error that indicates a trace of
+the subtype tests that caused the overflow without showing a full stacktrace.
+
+## Variance Laws for Match Types
+
+Within a match type `Match(S, Cs) <: B`, all occurrences of type variables count as covariant. By the nature of the cases `Ci` this means that occurrences in pattern position are contravarant (since patterns are represented as function type arguments).
```
Comment (LPTK) [inline docs/docs/reference/new-types/match-types.md:186]: @OlivierBlanvillain this formulation does not make any sense to me.

I think you wanted to say something along the lines of:

> The type `S` and each type `Ci` occur positively in match type `Match(S, Cs) <: B` — i.e., the match type is covariant in `S` and `Ci`.

Furthermore, I imagine that the match type is _contravariant_ in `B` , right?

Comment (OlivierBlanvillain) [reply docs/docs/reference/new-types/match-types.md:186]: This paragraph was not modified by PR, not sure why it shows up in the overall diff... But it appears to be outdated, so thanks for pointing it out!

> Furthermore, I imagine that the match type is contravariant in B , right?

The bound isn't used when doing subtyping between two match types, so `Match(S, Cs) <: B1` is `=:=` to `Match(S, Cs) <: B2` forall `B1`, `B2`

Comment (LPTK) [reply docs/docs/reference/new-types/match-types.md:186]: Sure!

> The bound isn't used when doing subtyping between two match types

It still needs to be considered during variance checks, no? Otherwise I think it could lead to unsoundness.

Comment (OlivierBlanvillain) [reply docs/docs/reference/new-types/match-types.md:186]: I don't see how, do you have an example?

Comment (LPTK) [reply docs/docs/reference/new-types/match-types.md:186]: I think I could come up with examples, but there does not seem to be an easy way to get a type with mismatched variance into the bound of a match type, at least from user code:

```scala
scala> class C[+T] { type A[X] <: T = X match { case Int => Nothing } }
1 |class C[+T] { type A[X] <: T = X match { case Int => Nothing } }
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |              covariant type T occurs in invariant position in type [X] =
  |                X match {
  |                  case Int => Nothing
  |                } <: T of type A
```

Is there any other way for match type bounds to get picked up, other than by using and upper bound on an abstract type? If not, then I guess there is no soundness problem. But I'd be wary of corner cases.

Comment (OlivierBlanvillain) [reply docs/docs/reference/new-types/match-types.md:186]: > Is there any other way for match type bounds to get picked up, other than by using and upper bound on an abstract type?

No, that's the only syntax we have (which is kind of limiting, for example there is no way to specify bounds of nested match types).

Comment (LPTK) [reply docs/docs/reference/new-types/match-types.md:186]: Well, of you ever add a first-class syntax for match type bounds, you should remember to check their variance too :^P
