### PR TITLE
Fix #1276: `_` binding in patternmatcher

### LINKED ISSUE #1276: Patternmatcher fails to bind `_: _*` correctly
When transforming:

```scala
val List(_: _*) = List(1)
```

`_` is evaluated to be an `Int` instead of a `Seq[Int]`.

### PR DESCRIPTION
**Pull request by felixmulder**
This fix changes the typer to infer a `A*` instead of `Seq[A]` for repeated arguments. Subsequent parts of the patternmatcher and checking has been changed to accommodate this.

Related issue: #1276

### CODE REVIEW

File: src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 1]
```diff
@@ -119,7 +119,12 @@ class TreeChecker extends Phase with SymTransformer {
     val prevPhase = ctx.phase.prev // can be a mini-phase
     val squahsedPhase = ctx.squashed(prevPhase)
     ctx.echo(s"checking ${ctx.compilationUnit} after phase ${squahsedPhase}")
-    val checkingCtx = ctx.fresh.setReporter(new ThrowingReporter(ctx.reporter))
+
+    val checkingCtx = ctx
+        .fresh
+        .setMode(Mode.ImplicitsEnabled)
```
Comment (felixmulder) [inline src/dotty/tools/dotc/transform/TreeChecker.scala]: Added `setMode(Mode.ImplicitsEnabled)` here since `Compiler` uses that in its initial context.

File: tests/pos/t9765.scala [hunk 2]
```diff
@@ -0,0 +1,7 @@
+case class A(v: Int)
+class B(v: Int) extends A(v)
+
+object Test {
+  val a = new B(1)
+  a match { case A(_) => 1 }
+}
```
Comment (liufengyun) [inline tests/pos/t9765.scala]: Is there a typo? You probably mean SI-9795 here.

File: src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 3]
```diff
@@ -1559,30 +1560,31 @@ class PatternMatcher extends MiniPhaseTransform with DenotTransformer {thisTrans
...
         // [2] then we have to index the binder that represents the sequence for the remaining subpatterns, except for...
         // [3] the last one -- if the last subpattern is a sequence wildcard:
         //       drop the prefix (indexed by the refs on the preceding line), return the remainder
-        (    productElemsToN(binder, firstIndexingBinder)
-          ++ genTake(binder, expectedLength)
-          ++ lastTrees
-          ).toList
-      }
+
+        productElemsToN(binder, firstIndexingBinder) ++
```
Comment (DarkDimius) [inline src/dotty/tools/dotc/transform/PatternMatcher.scala]: I find previous version easier to read.

File: src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 4]
```diff
@@ -1157,8 +1158,8 @@ class PatternMatcher extends MiniPhaseTransform with DenotTransformer {thisTrans
 
       object TypeBound {
         def unapply(tree: Tree): Option[Type] = tree match {
-          case Typed(_, _)  => Some(tree.typeOpt)
-          case _                                      => None
+          case Typed(_, arg) if !arg.tpe.isRepeatedParam => Some(tree.typeOpt)
+          case _                                     => None
```
Comment (DarkDimius) [inline src/dotty/tools/dotc/transform/PatternMatcher.scala]: indentation a bit off.

File: tests/pos/t9765.scala (hunk 2 above)
Comment (felixmulder) [inline tests/pos/t9765.scala]: Yes, thank you - fixed it :)

**Comment by DarkDimius** [comment]
LGTM, thanks!

File: src/dotty/tools/dotc/transform/TreeChecker.scala (hunk 1 above)
Comment (smarter) [inline src/dotty/tools/dotc/transform/TreeChecker.scala]: I don't think `TreeChecker` should have to do implicit searches, did you have to enable this to make some tests pass?

**Comment by felixmulder** [comment]
@smarter - for some reason github couldn't find your comment so I'm reposting it here or maybe you deleted it? Anyway, for posterity...

> I don't think `TreeChecker` should have to do implicit searches, did you have to enable this to make some tests pass?

I had a look in `Compiler.scala` and figured that tree checking should have the same fresh context as the regular compiler. That being said - this change makes absolutely no difference now. Why? Because for some reason the `ImplicitsEnabled` mode is not retracted after the implicit search - so it's prevalent throughout the entire pipeline. I reckon this is a bug, but I think @DarkDimius is already aware of it - not sure whether to report it properly or not.
