### PR TITLE
Fix #3187: Don't crash in requiredClass if class is missing

### LINKED ISSUE #3187: Trying to re-define a scala core object results in a ClassCastException
```
package scala

object collection
```

results 

```
java.lang.Exception
	at dotty.tools.dotc.core.Denotations$MissingRef.(Denotations.scala:1053)
	at dotty.tools.dotc.core.Denotations$MissingRef$.apply(Denotations.scala:1052)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.select$1(Denotations.scala:1202)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1224)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1221)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$4(Denotations.scala:1226)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:1228)
	at dotty.tools.dotc.core.Symbols.requiredClass(Symbols.scala:365)
	at dotty.tools.dotc.transform.localopt.Simplify.prepareForUnit(Simplify.scala:79)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$init$$$anonfun$135(TreeTransform.scala:543)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.mutateTransformers(TreeTransform.scala:496)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:555)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:475)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$2(Phases.scala:283)
	at scala.collection.immutable.List.map(List.scala:284)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:285)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$1(Run.scala:81)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:89)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:94)
	at dotty.tools.dotc.Run.compileSources(Run.scala:63)
	at dotty.tools.dotc.Run.compile(Run.scala:47)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:63)
	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:53)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:912)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
creating stub for generic, owner = module class collection$#3261, file = null
decls = method #3852
sbt: [trace] Stack trace suppressed: run 'last compile:compileIncremental' for the full output.
sbt: [error] (compile:compileIncremental) java.lang.ClassCastException: dotty.tools.dotc.core.Symbols$Symbol cannot be cast to dotty.tools.dotc.core.Symbols$ClassSymbol
sbt: [info] Compiling 1 Scala source to /tmp/scastie2359257166745281823/target/scala-0.3/classes...
java.lang.Exception
	at dotty.tools.dotc.core.Denotations$MissingRef.(Denotations.scala:1053)
	at dotty.tools.dotc.core.Denotations$MissingRef$.apply(Denotations.scala:1052)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.select$1(Denotations.scala:1202)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1224)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recurSimple$1(Denotations.scala:1221)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.recur$4(Denotations.scala:1226)
	at dotty.tools.dotc.core.Denotations$DenotationsBase.staticRef(Denotations.scala:1228)
	at dotty.tools.dotc.core.Symbols.requiredClass(Symbols.scala:365)
	at dotty.tools.dotc.transform.localopt.Simplify.prepareForUnit(Simplify.scala:79)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.$init$$$anonfun$135(TreeTransform.scala:543)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.mutateTransformers(TreeTransform.scala:496)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.macroTransform(TreeTransform.scala:555)
	at dotty.tools.dotc.transform.TreeTransforms$TreeTransformer.run(TreeTransform.scala:475)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$2(Phases.scala:283)
	at scala.collection.immutable.List.map(List.scala:284)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:285)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$1(Run.scala:81)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:89)
	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:94)
	at dotty.tools.dotc.Run.compileSources(Run.scala:63)
	at dotty.tools.dotc.Run.compile(Run.scala:47)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:63)
	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:53)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:912)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
creating stub for generic, owner = module class collection$#3261, file = null
decls = method #3852
```

### PR DESCRIPTION
**Pull request by odersky**
Also, issue stacktraces for missing refs only if Y-debug-missing-refs is set.

The test case issues error messages without positions, so it is left in `pos`.

### CODE REVIEW

**Comment by odersky** [comment]
I know this could be improved (e.g. trying to relate error messages to source), but I won't have the time to sink more effort into this.

**Comment by smarter** [comment]
> The test case issues error messages without positions, so it is left in pos.

It's possible to check for errors without positions by putting `// nopos-error` anywhere in the file.

File: compiler/src/dotty/tools/dotc/core/Denotations.scala [hunk 1]
```diff
@@ -277,7 +277,7 @@ object Denotations {
       disambiguate(p) match {
         case m @ MissingRef(ownerd, name) =>
           if (generateStubs) {
-            m.ex.printStackTrace()
+            if (ctx.settings.YdebugMissingRefs.value) m.ex.printStackTrace()
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Denotations.scala]: This check should also be done at https://github.com/lampepfl/dotty/blob/67e34d7674f03b48c863322bba8ac02893d0b554/compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala#L412 instead of ctx.debug

**Comment by smarter** [comment]
Somehow the tests compiled with an optimized compiler fail with:
```scala
[error] Test dotty.tools.ShowClassTests.loadDotty failed: java.lang.AssertionError: assertion failed: stubs found: 36, expected: 5
[error] stubs: class Stream,class Seq,class BufferedIterator,class Iterator,class List,class Iterable,class TraversableOnce,class IndexedSeq,class Vector,class Range,class StringBuilder,module mutable,class ::,module immutable,class Traversable,class Set,class Map,module immutable,class Stream,class Seq,class BufferedIterator,class Iterator,class List,class Iterable,class TraversableOnce,class IndexedSeq,class Vector,class Range,class StringBuilder,module mutable,class ::,module immutable,class Traversable,class Set,class Map,module immutable, took 0.043 sec
[error]     at dotty.DottyPredef$.assertFail(DottyPredef.scala:39)
[error]     at dotty.tools.ShowClassTests.showPackage$$anonfun$4(ShowClassTests.scala:82)
[error]     at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
[error]     at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
[error]     at dotty.tools.ShowClassTests.doTwice(ShowClassTests.scala:58)
[error]     at dotty.tools.ShowClassTests.showPackage(ShowClassTests.scala:83)
[error]     at dotty.tools.ShowClassTests.loadDotty(ShowClassTests.scala:145)
[error] ...
```

**Comment by odersky** [comment]
@OlivierBlanvillain Can you help debug this?

**Comment by OlivierBlanvillain** [comment]
I couldn't reproduce on my laptop, I will give it another shot when I'm back in Lausanne

**Comment by OlivierBlanvillain** [comment]
I finally managed to isolate that bug. The neg test case added in this PR breaks `dotty.tools.ShowClassTests` when compiled before, as shown by the latest commit (it's independent of being bootstrapped or optimized).

The problem comes from [`Symbols.stubs`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/Symbols.scala#L695), a mutable variable shared between compiler instances and read in `dotty.tools.ShowClassTests`. When `neg/i3187.scala` is run first, a bunch of stubs are added to this var which break assumptions made in `dotty.tools.ShowClassTests`.

I'm not sure what would be the best solution here, I guess we could remove either `neg/i3187.scala` or `dotty.tools.ShowClassTests`...

**Comment by smarter** [comment]
> I'm not sure what would be the best solution here, I guess we could remove either neg/i3187.scala or ShowClassTests...

No, I think that's a real issue you found, we shouldn't have a shared mutable stub list, it should be per-compiler at the very least.

**Comment by OlivierBlanvillain** [comment]
This list of stub is only used for testing, in `ShowClassTests`, so removing that test would solve the issue.
