### PR TITLE
Fix #2117: bug in typechecking super prefix with invalid enclosing class

### LINKED ISSUE #2117: Dotty crashes while typechecking invalid super prefix
When typechecking

`
class A {
  C.super.foo()
}
`

the typer throws with the following stacktrace: http://pastebin.com/arjFaB0Z
The issue is an unguarded pattern matching in TypeAssigner: https://github.com/lampepfl/dotty/blob/d0621108bad55f9fc66c1c5ade9a0b7edb3117e7/compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala#L294

The fix (I think) is to simply handle the case where the qualifier has type ErrorType and bail out early.

### PR DESCRIPTION
**Pull request by abeln**
When typechecking

`class A {
  C.super.foo()
}`

If C isn't an enclosing class, the compiler was throwing because of an
unguarded pattern match.

Fix the issue by checking for ErrorType.

Tested:
Verified that the example above no longer throws.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala [hunk 1]
```diff
@@ -291,26 +291,28 @@ trait TypeAssigner {
...
-
-    def findMixinSuper(site: Type): Type = site.parents filter (_.name == mix.name) match {
-      case p :: Nil =>
-        p
-      case Nil =>
-        errorType(SuperQualMustBeParent(mix, cls), tree.pos)
-      case p :: q :: _ =>
-        errorType("ambiguous parent class qualifier", tree.pos)
+    qual.tpe match {
+      case err: ErrorType => untpd.cpy.Super(tree)(qual, mix).withType(err)
```
Comment (abeln) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: Is this necessary, or can I just do `tree.withType(err)`?
In general, when I should I be using the tree copier?

Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: Tree copier provides structural sharing and is used when you think that the tree might stay the same after your changes.

**Comment by DarkDimius** [comment]
Thanks for the contribution!
> What would be a good place to unit tests for this?

tests/neg/i2117.scala.

Would you also kindly update commit message to "Fix #2117: ..."

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala (hunk 1 above)
Comment (abeln) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: Thanks. In this case, would it be ok/better to do `tree.withType(err)`?

**Comment by abeln** [comment]
Added the test. PTAL.
What's the significance of "i" in "i2117"? (i.e. what's the naming convention, given that other files in that directory don't follow the same style).

**Comment by smarter** [comment]
"i" means issue and refers to an issue number on https://github.com/lampepfl/dotty/issues. "t" means ticket and refers to an issue number on scalac bug tracker (because the test was imported from scalac): https://issues.scala-lang.org/secure/Dashboard.jspa

**Comment by abeln** [comment]
Friendly ping @DarkDimius @smarter @felixmulder 
Does this look good or would you like something changed? Thanks!

**Comment by DarkDimius** [comment]
@abeln, thank you for pinging. It's good as is.
LGTM
