### PR TITLE
Fix #6361: Add regression test

### LINKED ISSUE #6361: REPL Completion picks up implied members imported without the `implied` modifier
```scala
scala> object foo { implied bar for Int = 10 }
// defined object foo

scala> import foo._

scala> ba
```

If you press TAB after `ba`, it will autocomplete to `bar`. If you press ENTER afterwards:

```scala
scala> bar
1 |bar
  |^^^
  |Not found: bar
```

Can be related to #5074 and #5895, the former one dealing with the imports and the latter one dealing with the completion.

### PR DESCRIPTION
**Pull request by griggt**
Closes #6361

### CODE REVIEW

File: compiler/test/dotty/tools/repl/TabcompleteTests.scala [hunk 1]
```diff
@@ -126,6 +126,10 @@ class TabcompleteTests extends ReplTest {
     assertEquals(List("Predef"), tabComplete("object Foo { opaque type T = Pre"))
   }
 
+  @Test def i6361 = initially {
+    assertEquals(Nil, tabComplete("object foo { given bar: Int = 10 }; import foo.*"))
```
Comment (OlivierBlanvillain) [inline compiler/test/dotty/tools/repl/TabcompleteTests.scala:130]: Shouldn't that string end with `; ba` to test the faulty completion?

Comment (griggt) [reply compiler/test/dotty/tools/repl/TabcompleteTests.scala:130]: :facepalm: thanks for catching that

**Review by anatoliykmetyuk — APPROVED** [review]
