### PR TITLE
Inline transparent implicit parameters when typing Unapply trees

### LINKED ISSUE #19623: Regression in `tarao/record4s` - transparent inline looses type dependent type info in match
Regression found in OpenCB for `tarao/record4s` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/7762532209/job/21176959388) 
All `transparent inline given` instances used in match block are loosing information about dependent type, it does not happen when calling unapply outside match block. 

## Compiler version
Last good release: 3.4.1-RC1-bin-20240129-b20747d-NIGHTLY
First bad release: 3.4.1-RC1-bin-20240130-7a5cb6e-NIGHTLY
Bisect points to 5648f12fb136886da4e1f00695627cbfde90ee9e

## Minimized code

```Scala
import scala.compiletime.*
import scala.language.dynamics

abstract class % extends Selectable

trait Select { type Out <: % }
trait Selector extends Dynamic {
  def selectDynamic[S <: Singleton & String](label: S): Any = ???
  
  def unapply[R: RecordLike](record: R)(using
      t: Select,
      r: RecordLike[t.Out]
  ): r.ElemTypes = ???
}

trait RecordLike[R] {
  type ElemTypes <: Tuple
}


@main def Test = {
  val r: %{ val name: String; } = ???

  // originally derived in macro, use dummy instance instead
  transparent inline given outputRecordLike[R <: %]: RecordLike[R] = null.asInstanceOf[
    RecordLike[R] {
      type ElemTypes = String *: EmptyTuple
    }
  ]

  type FieldSelector = Select { type Out = % { val name: String } }
  given fieldSelector: FieldSelector = ???
  val selector: Selector = ???

  val works = selector.unapply(r)
  val works2 = selector.unapply(r)(using summon, fieldSelector, summon) 
  r match {
    case selector(value) => value // compilation error
  }
}
```

## Output

```scala
- [E108] Declaration Error: /Users/wmazur/projects/dotty/bisect/main.scala:38:17 
38 |    case selector(value) => value // compilation error
   |         ^^^^^^^^^^^^^^^
   | ?1.ElemTypes is not a valid result type of an unapply method of an extractor.
   |
   |where:    ?1 is an unknown value of type RecordLike[%{val name: String}]
   |
   | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /Users/wmazur/projects/dotty/bisect/main.scala:38:28 
38 |    case selector(value) => value // compilation error
   |                            ^^^^^
   |                            Not found: value - did you mean valueOf?
   |
   | longer explanation available when compiling with `-explain`
2 errors found
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by nicolasstucki**
We needed to delay the inlining of the transparent inline when typing the unapply function application. We used the NoInline mode, but this also stopped the inlining of the arguments of the unapply. To fix this we target more precisely the inlining of the unapply method and not the implicit arguments. To do this we detect the dummy argument that is used type the unapply as an application, before it is transformed into a pattern.

Fixes #19623
Fixes solution added in #19380

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Mode.scala [hunk 1]
```diff
@@ -122,6 +122,9 @@ object Mode {
 
   val PatternOrTypeBits: Mode = Pattern | Type
 
+  /** Skip inlining of unapply methods. */
+  val NoInlineUnapply: Mode = newMode(18, "NoInlineUnapply")
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/core/Mode.scala:126]: Note that this is the last free mode. If we want more modes we will need to use a Long to encode them.

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 2]
```diff
@@ -1492,7 +1492,7 @@ trait Applications extends Compatibility {
 
         val dummyArg = dummyTreeOfType(ownType)
         val (newUnapplyFn, unapplyApp) =
-          val unapplyAppCall = withMode(Mode.NoInline):
+          val unapplyAppCall = withMode(Mode.NoInlineUnapply):
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:1495]: Would be good to add an explanation why unapplys should not be inlined here.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:1495]: We are running out of mode bits. Is there some other way to know this info? For instance we could observe that the `unapply` is applied to a dum,yArg and not inline in this case?

**Review by odersky — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Applications.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: Now the implementation is based on the existence of the dummy. No extra mode required.

**Review by odersky — APPROVED** [review]
LGTM. Glad we did not need to use that mode bit.
