### PR TITLE
Fix #9892: Add span when translating `with` to an and type

### LINKED ISSUE #9892: Bug with scala.js return type check and intersection types
## Minimized code

```Scala
import scala.scalajs.js
@js.native
trait ObjectConstructor {
  def assign[T, U](target: T, source: U): T with U = js.native
}

```

## Output

```
[error] -- Error: /home/olvind/.cache/scalablytyped/ScalablyTyped/s/std/src/main/scala/typings/std/ObjectConstructor.scala:30:6 
[error] 30 |  def assign[T, U](target: T, source: U): T with U = js.native
[error]    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |The type of assign must be explicitly specified because it is JS native.

```

## Expectation
Should compile. 

Notes:
- Works in scala 2
- Tested with 0.28.0-bin-20200925-f4528ce-NIGHTLY
- annotated return type of `T & U` compiles
- `T` and `U` could be concrete types and still trigger the error. I have several examples with concrete types, this was just the smallest
- I also saw this for `val`s
- It might not actually be relevant given the above, but I thought I should mention this was just fixed, https://github.com/lampepfl/dotty/issues/9717

### PR DESCRIPTION
**Pull request by tgodzik**
Fix https://github.com/lampepfl/dotty/issues/9892

Without adding the span it is thought to be synthetic, which causes scalaJS to throw an error.

### CODE REVIEW

**Comment by sjrd** [comment]
I believe the best place to add a test here is to add `// ok` lines in the class `A4` in `js-native-members.scala` at
https://github.com/lampepfl/dotty/blob/38ba6e18cebb3b17512da4b327406b6a8c6656d5/tests/neg-scalajs/js-native-members.scala#L54-L58

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -1549,7 +1549,7 @@ object Parsers {
         else
           if sourceVersion.isAtLeast(`3.1`) then
             deprecationWarning(DeprecatedWithOperator(), withOffset)
-          makeAndType(t, withType())
+          makeAndType(t, withType()).withSpan(Span(startOffset(t), in.lastOffset, startOffset(t)))
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:1552]: Should this be
```suggestion
          atSpan(in.lastOffset)(makeAndType(t, withType()))
```
?

I'm not familiar with the parser and how spans are supposed to be assigned. Perhaps someone else from the dotty team can check this? @nicolasstucki ?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:1552]: This variant has the proper point set on it. That may be the extra info that is missing for scalajs.
```suggestion
          atSpan(in.lastOffset, withOffset) { makeAndType(t, withType()) }
```

**Comment by tgodzik** [comment]
> I believe the best place to add a test here is to add `// ok` lines in the class `A4` in `js-native-members.scala` at

Added the test.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (tgodzik) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Thanks! I applied the suggestion.

**Review by sjrd — APPROVED** [review]
Thanks @tgodzik !

**Comment by sjrd** [comment]
Apparently the latest changes cause several other failures. It seems that the offset of other errors in the files are displaced. Perhaps the latest changes cause an overall displacement of all the offsets in the file?

**Comment by nicolasstucki** [comment]
Maybe try with the version that @sjrd proposed

**Comment by tgodzik** [comment]
@nicolasstucki position changes at `js-native-members.check` were expected and the other ones were most likely caused by the fact that we were pointing at `with` instead of the full type tree. Should be good now, what you think?

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
Thank you @tgodzik
