### PR TITLE
Fix #7458: Refine typevar interpolation

### LINKED ISSUE #7458: Issue with a nullary extension method and covariance
## minimized code

```
type Tr[+V, +O <: V]
def (tr: Tr[V, O]) sl[V, O <: V]: Tr[V, O] = ???
def as[V, O <: V](tr: Tr[V, O]) : Tr[V, O] = tr.sl
```
An error is found by the compiler whine none is expected
```
-- [E007] Type Mismatch Error: ABug.scala:5:45 ---------------------------------
5 |def as[V, O <: V] (tr: Tr[V, O]): Tr[V, O] = tr.sl
  |                                             ^^
  |                       Found:    queries.Tr[V, V]
  |                       Required: queries.Tr[V, O]
  |                       
  |                       where:    O is a type in method as with bounds <: V
  |                                 V is a type in method as with bounds >: O
  |                       
  |                       Constraint(
  |                        uninstVars = ;
  |                        constrained types = 
  |                        bounds = 
  |                        ordering = 
  |                       )
  |                       Subtype trace:
```

For information, the issue disappears if I replace nullary method by parameterless

### PR DESCRIPTION
**Pull request by odersky**
If there are several type variables to instantiate in an interpolation call,
instantiate first those type variables that do not tighten the constraint for
other instantiatable type variables.

The following code from i7458.scala requires this new scheme to compile.
```
type Tr[+V1, +O1 <: V1]
def [V2, O2 <: V2](tr: Tr[V2, O2]) sl: Tr[V2, O2] = ???
def as[V3, O3 <: V3](tr: Tr[V3, O3]) : Tr[V3, O3] = tr.sl
```
Interestingly, adding `()` to the parameter list of `sl` makes
the problem disappear even without the fix. The reason is that in
this case interpolation is suspended to a later point since expressions of
method type are not interpolated.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 1]
```diff
@@ -421,22 +421,68 @@ trait Inferencing { this: Typer =>
...
+         */
+        def doInstantiate(buf: InstantiateQueue): Unit =
+          if buf.nonEmpty then
+            val suspended = new InstantiateQueue
+            while buf.nonEmpty do
+              val first @ (tvar, fromBelow) = buf.head
+              buf.dropInPlace(1)
+              val suspend = buf.exists{ (following, _) =>
+                if fromBelow then constraint.isLess(following.origin, tvar.origin)
+                else constraint.isLess(following.origin, tvar.origin)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala]: These two lines are the same, I assume one is supposed to have its parameters flipped ? (Incidentally this is why I like to always put a new line before each branch of an if/else, this makes this sort of things easier to spot :)).

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala]: Glad you spotted this!
