### PR TITLE
Fix #1716: Don't allow wildcards as type arguments to methods

### LINKED ISSUE #1716: Exception while typechecking and compiling pattern matching with @
```
object Fail {
  case class So[+T]()

  def main(args: Array[String]): Unit = {
    So[Int]() match {
      case p@So[_] => Console.println("Yep")
      case _       => Console.println("Nope")
    }
  }
}
```

Compiler says,

```
exception occurred while typechecking /path/to/Src.scala
exception occurred while compiling /path/to/Src.scala
```

Works well if underscore in pattern matching is replaced with a specific type.

### PR DESCRIPTION
**Pull request by odersky**
Wildcards don't make sense as type arguments to methods, and I believe to keep things
simple this should also apply to method type arguments in patterns.

The best way to enforce this is to make use of the existing infrastructure in the parser
for topLevelTypes.

This is an alternate fix for #1716 more in line with the way we exclude wildcards in types already.

Review by @liufengyun ?

### CODE REVIEW

File: tests/pending/neg/i1716.scala [hunk 1]
```diff
@@ -0,0 +1,9 @@
+object Fail {
```
Comment (liufengyun) [inline tests/pending/neg/i1716.scala]: Seems a slip here: move the test from `tests/pending/neg` to `tests/neg`
