### PR TITLE
Enhance constant-folding during inlining

### LINKED ISSUE #24412: inline boolean value is not simplified in some cases
## Compiler version

3.7.4, 3.8.0-RC1-bin-20251113-8b5d445-NIGHTLY,

## Minimized code

```scala
object test {
  import scala.compiletime.erasedValue

  inline def contains[T <: Tuple, E]: Boolean = inline erasedValue[T] match {
    case _: EmptyTuple => false
    case _: (_ *: tail) => contains[tail, E]
  }
  inline def check[T <: Tuple]: Unit = {
    inline if contains[T, Long] && false then ???
  }

  check[(String, Double)]
}
```

## Output

```scala
[error] ./inline_and.scala:12:3
[error] Cannot reduce `inline if` because its condition is not a constant value: {
[error]   {
[error]     false:Boolean
[error]   }:Boolean
[error] }:Boolean && false
[error]   check[(String, Double)]
[error]   ^^^^^^^^^^^^^^^^^^^^^^^
```

## Expectation

The code should compile.

### LINKED ISSUE #24420: `inline val` not inlined
Bug found by @asunluer.

## Compiler version

3.0
3.7.4
3.8.0-RC1-bin-20250822-658c8bd-NIGHTLY

## Minimized code

```scala
inline def f(): Long =
  1L

inline def g(): Long =
  inline val x = f()
  x

inline def h(): Long = 
  inline if g() > 0L then 1L else 0L

@main def main(): Unit =
  println(h())
```

## Output

```scala
$ scala -S 3.7.4 inline_val_bug.scala
Compiling project (Scala 3.7.4, JVM (23))
[error] ./inline_val_bug.scala:12:11
[error] Cannot reduce `inline if` because its condition is not a constant value: {
[error]   inline val x: Long = 1L:Long
[error]   x:Long
[error] }:Long > 0L
[error]   println(h())
[error]           ^^^
Error compiling project (Scala 3.7.4, JVM (23))
Compilation failed
```

## Expectation

Compiles, and constant-fold `h()` to `1L`.

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #24420 (see https://github.com/scala/scala3/issues/24420#issuecomment-3539228280 for some context) and fixes #24412.

Expressions can be constant-folded during inlining, but it isn't easy to determine which expressions qualify. For example, this works:

```scala
inline def g1(): Boolean =
  true

inline def g2(): Long =
  inline if g1() then 1L else 2L

@main def Test: Unit =
  assert(g2() == 1L)
```

And this works:

```scala
inline def f1(): Long =
  1L

inline def f2(): Long =
  inline val x = f1() + 1L
  x

@main def Test: Unit =
  assert(f2() == 2L)
```

But if we change the right‐hand side of `x` to just be `f1()`, then we get an error:

```scala
inline def f1(): Long =
  1L

inline def f3(): Long =
  inline val x = f1()
  x

@main def Test: Unit =
  assert(f3() == 1L)
```

```
$ scala -S 3.7.4 test3.scala
Compiling project (Scala 3.7.4, JVM (17))
[error] ./test3.scala:9:10
[error] inline value must have a literal constant type
[error]   assert(f3() == 1L)
[error]          ^^^^
Compilation failed
```

The first two examples work because they rely on `ConstantValue`, which always strips `Typed`:
https://github.com/scala/scala3/blob/96b1b83ff166be70cd8c5b1e2774580e52af4a3a/compiler/src/dotty/tools/dotc/ast/TreeInfo.scala#L1217-L1220

This PR makes the third example work too by:

1. Making constant-folding during inlining more permissive. In particular we now allow unwrapping `Typed` trees in more places (it was already done in `ConstantValue`, but not `constToLiteral`). This is implemented via a new `inlinedConstToLiteral` function — a stronger version of `constToLiteral` — that it is called in critical places in the `Inliner` where a constant is required.

2. Applying this function in two additional locations during inlining: on the result of inlined calls, and on the right-hand side of inline values.

This PR does not affect constant folding outside inlining (see #24432 for that discussion). It also keeps the existing semantics of `inline val`; it merely documents and strengthens the behavior already present.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/inlines/Inliner.scala [hunk 1]
```diff
@@ -928,7 +928,10 @@ class Inliner(val call: tpd.Tree)(using Context):
     override def typedValDef(vdef: untpd.ValDef, sym: Symbol)(using Context): Tree =
       val vdef1 =
         if sym.is(Inline) then
-          val rhs = typed(vdef.rhs)
+          val rhs =
+            typed(vdef.rhs) match
+              case ConstantValue(v) => Literal(Constant(v))
+              case rhs => rhs
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/inlines/Inliner.scala]: Should we directly report an error here?

**Comment by sjrd** [comment]
> It is also visible for operations that can be constant-folded:

This is wrong. It breaks separate compilation/tasty compatibility if you later change the body of `f1()`. We must prevent that.

`inline if` is fine because it's reduced by the inliner, not by typer/constant folding.

**Comment by mbovel** [comment]
> This is wrong. It breaks separate compilation/tasty compatibility if you later change the body of f1().

But that only works here because we are inside an `inline def` and `f()` has already been inlined, doesn't it?

Inside an `inline def`, I would expect the right hand-side of an `inline val` to be constant-folded similarly to the condition of an `inline if`, shouldn't it be the case?

**Comment by sjrd** [comment]
No, `inline val` is weird. It doesn't behave like the other `inline`s. It needs to be a *constant expression* (spec concept), which is required already during the initial typing.

**Comment by som-snytt** [comment]
Grateful I'm not trying to get something past sjrd right now.

**Comment by mbovel** [comment]
> No, `inline val` is weird. It doesn't behave like the other `inline`s. It needs to be a _constant expression_ (spec concept), which is required already during the initial typing.

Why is it important that this is at `typer` already?

That doesn't seem aligned with the implementation, which only checks that during `inlineVals`.

And is this implied by the specification? Do spec definitions imply _during `typer`_?

**Comment by mbovel** [comment]
Follow-up on the constant-folding part, independently from inlining: #24432.

**Comment by mbovel** [comment]
See also https://contributors.scala-lang.org/t/what-does-the-error-inline-value-must-be-pure-mean/7281/8.

**Comment by mbovel** [comment]
We discussed with @sjrd in person. Accepting `inline val`s that are inside `inline def`s and that are constant only after inlining might be okay 🥳

~Closing this PR in favor of #24425, which should be more general (but requires some more work).~

File: compiler/src/dotty/tools/dotc/inlines/Inliner.scala (hunk 1 above)
Comment (mbovel) [reply compiler/src/dotty/tools/dotc/inlines/Inliner.scala]: Will do separately.

**Comment by Gedochao** [comment]
(rebased)

**Comment by Gedochao** [comment]
@sjrd @mbovel what's the current status of this PR?

**Comment by mbovel** [comment]
> @sjrd @mbovel what's the current status of this PR?

Waiting for a review 😄

**Comment by Gedochao** [comment]
Bump @sjrd

**Comment by mbovel** [comment]
CI fails because `https://index.scala-lang.org/alexarchambault/data-class` is `503`.

File: compiler/src/dotty/tools/dotc/inlines/Inliner.scala [hunk 2]
```diff
@@ -187,6 +187,27 @@ object Inliner:
...
+  def inlinedConstToLiteral(rootTree: Tree)(using Context): Tree =
+    def rec(tree: Tree): Tree =
+      inline def recChild(subTree: Tree): Tree =
+        val res = rec(subTree)
+        if res eq subTree then tree else res
+
+      tree match
+        case Typed(expr, _) => recChild(expr)
+        case Inlined(_, _, expr) => recChild(expr)
+        case Block(_, expr) => recChild(expr)
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/inlines/Inliner.scala:203]: Note: it's okay to ignore statements here if the block's trailing expression is a constant, because we have already checked that `rootTree` is pure through `isElidableExpr`.
