### PR TITLE
Fix #5583: Pass correct offset to bind node

### LINKED ISSUE #5583: Wrong position for binding definitions
A position of the definition of binding `y` is wrong

```scala
x match {
  case y @ Some(_) => ...
        // ^ currently it point here
}
```

It can be reproduced in `dotty.tools.languageserver.DefinitionTest` with

```scala
@Test def goToBinding: Unit = {
    withSources(
      code"""class Foo {
            |val x = Some(6)
            |x match {
            |  case ${m1}y${m2} @ Some(_) => ${m3}y${m4}
            |}
       }"""
    ) .definition(m3 to m4, List(m1 to m2))
  }
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -1699,8 +1699,8 @@ object Parsers {
           case pt @ Ident(tpnme.WILDCARD_STAR) =>
             migrationWarningOrError("The syntax `x @ _*' is no longer supported; use `x : _*' instead", startOffset(p))
             atPos(startOffset(p), offset) { Typed(p, pt) }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: The `offset` in the above looks dubious too

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: I checked the positions of those trees and they look fine.
