### PR TITLE
Fix #9482: simplified Manifest synthesis

### LINKED ISSUE #9482: OptManifest not resolved
I'm currently adding Dotty support to [ScalaSTM](https://github.com/scala-stm/scala-stm). Everything went smooth except that `OptManifest` implicit compiler resolution seems broken (works through Scala 2.11–13).

## Minimized code

We use the following API

```scala
object Ref {
  def make[A: OptManifest]: Ref[A] = ???
}
trait Ref[A]
```

which is needed to distinguish between primitive types and reference types, and create arrays.

This works in the cases where the type is concrete, such as `Ref.make[String]` or `Ref.make[Int]`, but also when it is abstract such as

```scala
trait Foo[A] {
  val bar = Ref.make[Int]
  val baz: Ref[A] = Ref.make
}
```

## Output

This no longer works in Dotty 

```
[error] -- Error: /data/temp/dotty-optmanifest/src/main/scala/Foo.scala:2:25 -----------
[error] 2 |  val bar = Ref.make[Int]
[error]   |                         ^
[error]   |no implicit argument of type OptManifest[Int] was found for an implicit parameter of method make in object Ref
[error] -- Error: /data/temp/dotty-optmanifest/src/main/scala/Foo.scala:3:28 -----------
[error] 3 |  val baz: Ref[A] = Ref.make
[error]   |                            ^
[error]   |no implicit argument of type OptManifest[A] was found for an implicit parameter of method make in object Ref
[error] two errors found
```

## Expectation

It should work, like it did in Scala 2.13, i.e. resolve to either `ClassManifest` or `NoManifest`. E.g.:

https://travis-ci.org/github/scala-stm/scala-stm/jobs/714280130

### PR DESCRIPTION
**Pull request by bishabosha**
This PR is an alternative to #13129, it approximates what Scala 2 does but with some simplification.

The goal of the implementation is to say that for the following expressions compiled by Scala 2 that yield true:
- `manifest[A] == manifest[B]`
- `manifest[A].runtimeClass == manifest[B].runtimeClass`
- `optManifest[A] == optManifest[B]`
- `optManifest[A].asInstanceOf[ClassTag[A]].runtimeClass == optManifest[B].asInstanceOf[ClassTag[B]].runtimeClass`

then the same snippets compiled by Scala 3 should also be true.

This means `manifest[List[Int]] != manifest[List[? <: Int]]` because type arguments are compared in the `equals` method of `Manifest`, however `optManifest[List[Int]] == optManifest[List[? <: Int]]` because equality of `ClassTypeManifest` only cares about the `runtimeClass`, not type arguments

However the implementation does not care about replicating the exact expressions compiled by Scala 2, so `toString` can differ.

This PR also creates a deprecation warning whenever a Manifest is successfully synthesized.

fixes #9482

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 1]
```diff
@@ -375,14 +375,131 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
...
+        case EmptyTree if kind == Opt => ref(defn.NoManifestModule)
+        case result                   => result
+
+    formal.argInfos match
+      case arg :: Nil =>
+        val manifest = synthesize(fullyDefinedType(arg, "Manifest argument", span), kind, topLevel = true)
+        if manifest != EmptyTree then
+          report.deprecationWarning(
+            i"""Compiler synthesis of Manifest and OptManifest is deprecated,
+               |and calls should be replaced by `reflect.classTag[$arg]`.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:479]: I think I would mention `scala.reflect.ClassTag` instead of `classTag` since rather than changing the call, most of the time it's the definition that needs to be changed to replace `: Manifest` by something else.

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 2]
```diff
@@ -375,14 +375,131 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
...
+               |Alternatively, the using new metaprogramming features of Scala 3
+               |could help avoid the need for runtime type information, see
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:481]:
```suggestion
               |Alternatively, consider using the new metaprogramming features
               |of Scala 3, see
```

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala (hunk 1 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:479]: should this also be a `future` warning, rather than all language modes?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala]: No I think it's fine to deprecate by default, Manifest is already not recommended for use in scala 2

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Synthesizer.scala]: ok I've edited the message

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 3]
```diff
@@ -375,14 +375,130 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
           synthesizedSumMirror(formal, span)
       case _ => EmptyTree
 
+  private def escapeJavaArray(elemTp: Type)(using Context): Type = elemTp match
+    case JavaArrayType(elemTp1) => defn.ArrayOf(escapeJavaArray(elemTp1))
+    case _ => elemTp
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala:380]: Seems like this method could be used to solve https://github.com/lampepfl/dotty/issues/13131 :)

**Review by smarter — APPROVED** [review]
