### PR TITLE
Fix #6247: Remove incorrect early check

### LINKED ISSUE #6247: Unable to find member method
For the explicit nulls project, we want to have an extension method that strips away nullability:
```scala
implicit class NN[T](x:T|Null) {
  def nn: T = x.asInstanceOf[T]
}
```

This works must of the time, but weirdly fails in the code below:
```scala
class Foo {
  val x1: String|Null = null
  x1.nn.length
  val x2: String = x1.nn
  x1.nn.length
}

-- [E008] Member Not Found Error: kk.scala:10:8 --------------------------------
10 |  x1.nn.length
   |  ^^^^^^^^^^^^
   |  value length is not a member of T
   |
   |  where:    T is a type variable with constraint >: String
one error found
```
Line 10 is the second `x1.nn.length`. However, both
```scala
class Foo {
  val x1: String|Null = null
  x1.nn.length
  // val x2: String = x1.nn <---------- commented out
  x1.nn.length
}
```
 and
```scala
class Foo {
  val x1: String|Null = null
  x1.nn.length
  val x2 = x1.nn // <---------- the type of `x2` is inferred
  x1.nn.length
}
```
typecheck fine.

@liufengyun any hints about what could be going here?

### PR DESCRIPTION
**Pull request by smarter**
The check relied on the assumption that `locked` is always contained in
`state.ownedVars`, but this can stop being true when an owned type
variable is garbage-collected.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/util/SimpleIdentitySet.scala [hunk 1]
```diff
@@ -7,6 +7,7 @@ import collection.mutable.ListBuffer
  */
 abstract class SimpleIdentitySet[+Elem <: AnyRef] {
   def size: Int
+  def nonEmpty: Boolean = size > 0
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/util/SimpleIdentitySet.scala]: I think it would be more idiomatic to use `isEmpty` instead. Or else neither and just use `size > 0`.

**Comment by liufengyun** [comment]
A regression for Dotty happened after this PR?

**Comment by smarter** [comment]
Yes, see https://github.com/lampepfl/dotty/pull/6331
