### PR TITLE
Fix #5376, fix #5434: Unpickle quotes eagerly

### LINKED ISSUE #5376: Quotation unexpectedly creates cyclic structures
It's currently easy using quotation to inadvertently create a cyclic structure that fails when it's used.  For example, the following code fails with a `StackOverflowError` on the call to `show`:

```scala
var e = '(1)
e = '(~e + 1)
e.show
```

@nicolasstucki tells me that this is likely to be fixed by the code in https://github.com/lampepfl/dotty/pull/5297, which makes the evaluation of quotations more eager.

### LINKED ISSUE #5434: Quote evaluation order (debugging)
When debugging the following code
```scala
import scala.quoted._
object Test {
  def main(args: Array[String]): Unit = {
    implicit val toolbox: scala.quoted.Toolbox = scala.quoted.Toolbox.make

    println("start")

    {
      println("start e")
      val e = '{
        ~{
          println("splice")
          '(3)
        }
      }
      println("end e")
      e.run
    }

    println("end")
  }
}
```

the output will be
 
```
start
start e
end e
splice
end
```

where the natural order would be 

```
start
start e
splice
end e
end
```

This makes debugging quite hard. The source of the issue is the laziness of the evaluation of the contents of a quote. Making the evaluation eager fixes this.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/quoted/QuoteContext.scala [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    new scala.internal.quoted.TastyTreeExpr(
+      PickledQuotes.unpickleExpr(pickledExpr, args) given qctx.tasty.rootContext.asInstanceOf[Context]
+    ).asInstanceOf[Expr[T]]
+  }
+
+  def unpickleType[T](pickledType: PickledType, args: PickledTypeArgs): given scala.quoted.QuoteContext => Type[T] = given qctx => {
+    new scala.internal.quoted.TreeType(
+      PickledQuotes.unpickleType(pickledType, args) given qctx.tasty.rootContext.asInstanceOf[Context]
+    ).asInstanceOf[Type[T]]
+  }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/quoted/QuoteContext.scala]: I feel confused with the type signature of the two methods : why the result type cannot be just `Expr[T]` or `Type[T]`, given that `this` is the type `QuteContext`?

File: library/src/scala/quoted/QuoteContext.scala [hunk 2]
```diff
@@ -46,8 +51,18 @@ class QuoteContext(val tasty: scala.tasty.Reflection) {
...
   }
 
+  /** Unpickle `pickledExpr` which represents a pickled `Expr` tree
+   */
+  private[scala] def unpickleExpr[T](pickledExpr: PickledExpr, args: PickledExprArgs): given QuoteContext => Expr[T]
+
+  /** Unpickle `pickledType` which represents a pickled `Type` tree
+   */
+  private[scala] def unpickleType[T](pickledType: PickledType, args: PickledTypeArgs): given QuoteContext => Type[T]
+
```
Comment (liufengyun) [inline library/src/scala/quoted/QuoteContext.scala]: If they are private, why we need them in the trait?

File: library/src/scala/runtime/quoted/Unpickler.scala [hunk 3]
```diff
@@ -1,24 +1,27 @@
...
+
+  type PickledType = List[String]
+  type PickledTypeArgs = Seq[Seq[Any] => Type[_]]
 
   /** Unpickle `repr` which represents a pickled `Expr` tree,
    *  replacing splice nodes with `args`
    */
-  def unpickleExpr[T](repr: Pickled, args: Seq[Seq[Any] => ((given QuoteContext => Expr[Any]) | Type[_])]): given QuoteContext => Expr[T] = new TastyExpr[T](repr, args)
+  def unpickleExpr[T](repr: PickledExpr, args: PickledExprArgs): given QuoteContext => Expr[T] =
+    the[QuoteContext].unpickleExpr(repr, args)
```
Comment (liufengyun) [inline library/src/scala/runtime/quoted/Unpickler.scala]: If I were correct, the code will be expanded as follows:

```Scala
qctx => qctx.unpickleExpr(repr, args).apply(qctx)
```

It seems we can change the return type of `QuoteContext.unpickleExpr` to be just `Expr[T]`.

Comment (nicolasstucki) [reply library/src/scala/runtime/quoted/Unpickler.scala]: Yes, `QuoteContext.unpickleExpr` does not need the quote context argument.

File: compiler/src/dotty/tools/dotc/quoted/QuoteContext.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/QuoteContext.scala]: Yes, they should not return the contextual function type

File: library/src/scala/quoted/QuoteContext.scala (hunk 2 above)
Comment (nicolasstucki) [reply library/src/scala/quoted/QuoteContext.scala]: The alternative is to move it to the Kernel. That would probably simplify it a bit.

File: compiler/src/dotty/tools/dotc/tastyreflect/ReflectionInternal.scala [hunk 4]
```diff
@@ -28,6 +29,16 @@ class ReflectionCompilerInterface(val rootContext: core.Contexts.Context) extend
...
+  //
+  // QUOTE UNPICKLING
+  //
+
+  def unpickleExpr(repr: Unpickler.PickledQuote, args: Unpickler.PickledExprArgs): scala.quoted.Expr[_] =
+    new scala.internal.quoted.TastyTreeExpr(PickledQuotes.unpickleExpr(repr, args))
+
+  def unpickleType[T](repr: Unpickler.PickledQuote, args: Unpickler.PickledTypeArgs): scala.quoted.Type[_] =
+    new scala.internal.quoted.TreeType(PickledQuotes.unpickleType(repr, args))
+
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/tastyreflect/ReflectionInternal.scala]: Minor question: what about return `Tree`s instead of `Expr[_]` and `Type[_]`.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/tastyreflect/ReflectionInternal.scala]: Because it is specific to Expr and Type. There are no use cases where we need the tree directly.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/tastyreflect/ReflectionInternal.scala]: The type parameter `T` is not used.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/tastyreflect/ReflectionInternal.scala]: I will remove it
