### PR TITLE
Fix Java record problems (#19578) and (#19386)

### LINKED ISSUE #18639: Parameterized Java records result in MatchError
## Compiler version

  An unhandled exception was thrown in the compiler.

     while compiling: <no file>
        during phase: <no phase>
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.10
    compiler version: version 3.3.1
            settings: -bootclasspath ... -d .../target/classes -java-output-version 21

                tree: EmptyTree
       tree position: :<unknown>
           tree type: <notype>
              symbol: val <none>
           call site: package <root> in module class <root>

  == Source file context for tree position ==

## Minimized code

```Java
import java.util.List;

public record Result<U extends Number>(List<U> original,
                                       List<U> removed) { }
```

## Output (click arrow to expand)
<details>

```scala
-- [E161] Naming Error: Record.java:3:21 ---------------------------------------
3 |public record Result<U extends Number>(List<U> original,
  |                     ^^^^^^^^^^^^^^^^
  |U is already defined as type U
  |
  |Note that overloaded methods must all be defined in the same group of toplevel definitions

scala.MatchError: NoType (of class dotty.tools.dotc.core.Types$NoType$) while typechecking .../Result.java

exception occurred while typechecking .../Result.java

...

scala.MatchError: NoType (of class dotty.tools.dotc.core.Types$NoType$)
dotty.tools.dotc.core.Types$TypeLambdaCompanion.toPInfo(Types.scala:3997)
dotty.tools.dotc.core.Types$TypeLambdaCompanion.toPInfo(Types.scala:3995)
dotty.tools.dotc.core.Types$LambdaTypeCompanion.fromParams$$anonfun$2$$anonfun$1(Types.scala:3983)
scala.collection.immutable.List.map(List.scala:250)
dotty.tools.dotc.core.Types$LambdaTypeCompanion.fromParams$$anonfun$2(Types.scala:3983)
dotty.tools.dotc.core.Types$PolyType.<init>(Types.scala:4197)
dotty.tools.dotc.core.Types$PolyType$.apply(Types.scala:4303)
dotty.tools.dotc.core.Types$PolyType$.apply(Types.scala:4300)
dotty.tools.dotc.core.Types$LambdaTypeCompanion.fromParams(Types.scala:3984)
dotty.tools.dotc.core.NamerOps$.recur$1(NamerOps.scala:54)
dotty.tools.dotc.core.NamerOps$.methodType(NamerOps.scala:56)
dotty.tools.dotc.typer.Namer.wrapMethType$1(Namer.scala:1783)
dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1787)
dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:791)
dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:934)
dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:814)
dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:174)
dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
dotty.tools.dotc.core.NamerOps$ApplyProxyCompleter.complete(NamerOps.scala:106)
dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:174)
dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:393)
dotty.tools.dotc.core.SymDenotations$SymDenotation.annotations(SymDenotations.scala:231)
dotty.tools.dotc.core.SymDenotations$SymDenotation.getAnnotation(SymDenotations.scala:269)
dotty.tools.dotc.core.SymDenotations$SymDenotation.targetName(SymDenotations.scala:573)
dotty.tools.dotc.core.SymDenotations$SymDenotation.hasTargetName(SymDenotations.scala:563)
dotty.tools.dotc.core.Denotations$SingleDenotation.matches(Denotations.scala:1006)
dotty.tools.dotc.typer.Checking.checkDecl$1$$anonfun$2(Checking.scala:1102)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
scala.collection.AbstractIterable.foreach(Iterable.scala:933)
scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
dotty.tools.dotc.typer.Checking.checkDecl$1(Checking.scala:1114)
dotty.tools.dotc.typer.Checking.checkNoDoubleDeclaration$$anonfun$1(Checking.scala:1119)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.immutable.List.foreach(List.scala:333)
dotty.tools.dotc.core.Scopes$Scope.foreach(Scopes.scala:93)
dotty.tools.dotc.typer.Checking.checkNoDoubleDeclaration(Checking.scala:1119)
dotty.tools.dotc.typer.Checking.checkNoDoubleDeclaration$(Checking.scala:809)
dotty.tools.dotc.typer.Typer.checkNoDoubleDeclaration(Typer.scala:116)
dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2671)
dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3036)
dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3040)
dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3111)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3210)
dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3256)
dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2669)
dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3036)
dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3040)
dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3111)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3210)
dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3256)
dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2812)
dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3081)
dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3112)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3300)
dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:44)
dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:54)
scala.Function0.apply$mcV$sp(Function0.scala:42)
dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:440)
dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:54)
dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:88)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.immutable.List.foreach(List.scala:333)
dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:88)
dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:246)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
dotty.tools.dotc.Run.runPhases$1(Run.scala:262)
dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:270)
dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:279)
dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
dotty.tools.dotc.Run.compileUnits(Run.scala:279)
dotty.tools.dotc.Run.compileSources(Run.scala:194)
dotty.tools.dotc.Run.compile(Run.scala:179)
dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
sbt_inc.InProcessSbtIncrementalCompiler.compile(InProcessSbtIncrementalCompiler.java:72)
scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:325)
scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:119)
scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:86)
scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:310)
scala_maven.ScalaCompileMojo.execute(ScalaCompileMojo.java:108)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
java.base/java.lang.reflect.Method.invoke(Method.java:580)
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

```
</details>

### LINKED ISSUE #19386: Java and Scala compilers treat records differently, Scala compiler not exposing accessor methods
## Compiler version
3.3.1

## Minimized code
MyRecord.java: 
```
public record MyJavaRecord(String name, Integer age) {}
```
MyTest.scala
```
object MyScalaObject {
  @main def test(): Unit = {
    val javaRecord = new MyJavaRecord("Name", 50)
    println(javaRecord.name())
    println(javaRecord.age)
  }
}
```

If MyJavaRecord is compiled with java compiler, and MyScalaObject is compiled with scala compiler using class file generated by Java compiler for the record, you'd get no syntax errors from scala compiler.

If MyJavaRecord & MyScalaObject are both compiled with scala compiler, first println would give you syntax error.

## Expectation
When record is compiled via Scala compiler, it exposes accessor methods to the fields just like Java compiler.  We should get no errors compiling both with scala compiler.  Scala compiler should not enforce a syntax for java data type that is illegal by java compiler.

### LINKED ISSUE #19578: Possible regression in compilation for generic records for Java from 3.3.1
## Compiler version

Tested on:
- branch **main**: fails
- Released 3.3.1 succeeds

## Minimized code

```java
record R4<T>(t: T)
```

## Output

```scala
[E161] Naming Error: tests/pos-java16+/java-records/R4.java:1:10 ----------------------------------------------------
1 |record R4<T>(T t) {}
  |          ^
  |          T is already defined as type T
  |
  |          Note that overloaded methods must all be defined in the same group of toplevel definitions
```

## Expectation

Compiles

### PR DESCRIPTION
**Pull request by yilinwei**
This is a dependency of #19577 and should be reviewed and merged first.

fixes #18639
fixes #19386
fixes #19578

### CODE REVIEW

**Comment by nicolasstucki** [comment]
It seems that #19578 is still failing.

**Comment by bishabosha** [comment]
should link this to #18639

**Comment by bishabosha** [comment]
@yilinwei I haven't started anything yet so please feel free

**Comment by yilinwei** [comment]
Turned out the problem _was_ in the parser @bishabosha, just that the parsed tree didn't trigger the correct branches within the namer.

This should be all good to go, if it doesn't cause any other regressions.

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 1]
```diff
@@ -902,9 +906,9 @@ class Namer { typer: Typer =>
             && (definesMember || inheritsConcreteMember)
           )
           ||
-          // remove synthetic constructor of a java Record if it clashes with a non-synthetic constructor
-          (denot.isConstructor
-            && denot.owner.is(JavaDefined) && denot.owner.derivesFrom(defn.JavaRecordClass)
+          // remove synthetic constructor or method of a java Record if it clashes with a non-synthetic constructor
+          (isJavaRecord(denot.owner)
+            && (denot.isConstructor || definesMember)
             && denot.owner.unforcedDecls.lookupAll(denot.name).exists(c => c != denot.symbol && c.info.matches(denot.info))
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:912]: Is `denot.owner.unforcedDecls.lookupAll(denot.name).exists(c => c != denot.symbol && c.info.matches(denot.info))` redundant with `definesMember`?

**Review by noti0na1 — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Namer.scala (hunk 1 above)
Comment (yilinwei) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:912]: Yes I think so, but I think that we ought to switch it out since we want the `denot.info` to match exactly in this case. I will change the logic here.

Comment (yilinwei) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:912]: @noti0na1 Changed the logic and the tests passed locally.

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:912]: Great! I'm not that familiar with other parts, let's wait for review from Nicolas.

**Comment by yilinwei** [comment]
@nicolasstucki @bishabosha is there anything I can do to help move this along?

**Comment by bishabosha** [comment]
I've just been busy, sorry, free tomorrow

**Review by bishabosha — APPROVED** [review]
looks good, and I tried with some other variants, thanks for seeing this through!

**Comment by He-Pin** [comment]
@Kordyjan Will this be backported to 3.3.x?

**Comment by ek-gh** [comment]
I too am anxiously waiting for this to be back-ported to 3.3.x as well.
