### PR TITLE
Fix #6083: Dealias before kind checking

### LINKED ISSUE #6083: Kind polymorphic type cannot must take parameters
Given that we can write
```scala
type K0[T] = T
val a: K0[Int] = 1

type K1[T[_]] = T
val b: K1[List][Int] = Nil
```

We could try abstract this type over kind with

```scala
type K[T <: AnyKind] = T
val a: K[Int] = 1
val b: K[List][Int] = Nil
```
Though this one currently fails with
```scala
-- [E056] Syntax Error ----------------------------
9 |  val a: K[Int] = 1
  |         ^^^^^^
  |         Missing type parameter for Test.K[Int]
-- [E056] Syntax Error ---------------------------
12 |  val b: K[List][Int] = Nil
   |         ^^^^^^^^^^^^
   |         Missing type parameter for Test.K[List][Int]
```

There is a potential [usecase in #6082](https://github.com/lampepfl/dotty/pull/6082/files#diff-3cf36ed2ae10a954b9c0c1be6b5237faR20) for the internal encoding of `quoted.Type` splices.

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -799,7 +799,7 @@ trait Checking {
 
   /** Check that `tpt` does not define a higher-kinded type */
   def checkSimpleKinded(tpt: Tree)(implicit ctx: Context): Tree =
-    if (!tpt.tpe.hasSimpleKind && !ctx.compilationUnit.isJava) {
+    if (!tpt.tpe.dealias.hasSimpleKind && !ctx.compilationUnit.isJava) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]: Shouldn't `hasSimpleKind` be the one who does the dealiasing ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala]: Good point.

File: compiler/src/dotty/tools/dotc/config/Config.scala [hunk 2]
```diff
@@ -161,7 +161,7 @@ object Config {
   final val showCompletions = false
 
   /** If set, enables tracing */
-  final val tracingEnabled = false
+  final val tracingEnabled = true
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/config/Config.scala]: This shouldn't get in.
