### PR TITLE
fix: do not allow `@targetName` on primary constructor too

### LINKED ISSUE #24681: `@targetName` is only checked in non-primary constructors
## Compiler version

abfb3f99ab88e2bd4b4d57807ca4d44d0632cd47

## Minimized code

```scala
import scala.annotation.targetName

class Foo @targetName("bla") ()
```

## Output

```scala
Exception in thread "main" 
  unhandled exception while running erasure on test.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: test.scala
        during phase: erasure
                mode: Mode(ImplicitsEnabled)
     library version: version 3.8.1-RC1-bin-SNAPSHOT-nonbootstrapped
    compiler version: version 3.8.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-abfb3f9
            settings: -Vprint List(typer) -classpath <redacted>
java.lang.AssertionError: assertion failed

        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:13)
        at dotty.tools.dotc.core.Contexts$FreshContext.setOwner(Contexts.scala:647)
        at dotty.tools.dotc.core.Contexts$Context.superOrThisCallContext(Contexts.scala:446)
        at dotty.tools.dotc.core.Contexts$Context.superCallContext(Contexts.scala:424)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:3219)
        at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1048)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3753)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3757)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3858)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3946)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3951)
```

## Expectation

Should not compile and obviously not crash the compiler.

## Notes

I noticed this while reading the code of `Typer` that we only do the check for non-primary constructors :

https://github.com/scala/scala3/blob/abfb3f99ab88e2bd4b4d57807ca4d44d0632cd47/compiler/src/dotty/tools/dotc/typer/Typer.scala#L3126-L3140

### PR DESCRIPTION
**Pull request by hamzaremmal**
Closes #24681

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -3126,6 +3126,10 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
     if sym.isConstructor then
       if sym.is(Inline) then
         report.error("constructors cannot be `inline`", ddef)
+
+      if sym.targetName != sym.name then
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3130]: Just for the record: Technically, if the specification says (for #22372) we are not allowed to use `@targetName` on constructors, then this check (that was already present) doesn't encode that specification since we can always write this example below and it will work:

```scala
import scala.annotation.targetName

class Foo @targetName("<init>") ()
```

**Review by mbovel — APPROVED** [review]
This check was introduced in #7726 (found with `git log -L 3121,3136:compiler/src/dotty/tools/dotc/typer/Typer.scala`).
As far as I can tell, it was indeed meant to apply to any constructor.
