### PR TITLE
Record NotNullInfo for exceptional try-catch

### LINKED ISSUE #24296: Flow-typing does not record non-null info for try-catch blocks
## Compiler version

3.7

## Minimized code

```scala
//> using options -Yexplicit-nulls

def main() =
  var cache: String | Null = null
  try {
    cache = ""
  } catch {
    case e =>
      throw e
  }
  cache.trim()
```

## Output

```scala
-- [E008] Not Found Error: local/flow.scala:10:8 -------------------------------
10 |  cache.trim()
   |  ^^^^^^^^^^
   |  value trim is not a member of String | Null.
   |  Since explicit-nulls is enabled, the selection is rejected because
   |  String | Null could be null at runtime.
   |  If you want to select trim without checking for a null value,
   |  insert a .nn before .trim or import scala.language.unsafeNulls.
```

## Expectation
If the try block sets a variable to non-null, and the catch block does not retract it, we can expect the variable outside of the try-catch to be non-null as well

### PR DESCRIPTION
**Pull request by HarrisL2**
Fixes #24296

This PR modifies the logic for recording notNullInfo in try-catch-finally blocks, motivated by repeated pattern from community build sconfig ([source](https://github.com/dotty-staging/sconfig/blob/7b66d352e0b75cd46198432037366c120ad19476/sconfig/shared/src/main/scala/org/ekrich/config/impl/ConfigImpl.scala#L86)):
```scala
def computeCachedConfig(
      loader: ClassLoader,
      key: String,
      updater: Callable[Config]
  ): Config = {
    var cache: LoaderCache = null
    try {
      cache = LoaderCacheHolder.cache
    } catch {
      case e: ExceptionInInitializerError =>
        throw ConfigImplUtil.extractInitializerError(e)
    }
    cache.getOrElseUpdate(loader, key, updater)
  }
```
Here, the cache will never be null. Because all cases of the catch block resolve exceptionally, no matter where in the try block an exception occurs, once an exception is thrown, the entire context will resolve exceptionally. Hence, we can use the notNullInfo of the try block to type what comes after the catch.

The logic of the notNullInfo is as follows (also in code):
```
/** Graphic explanation of NotNullInfo logic:
   *  Leftward exit indicates exceptional case
   *  Downward exit indicates normal case
   *
   *           ┌─────┐
   *           │ Try ├─────┬────────┬─────┐
   *           └──┬──┘     ▼        ▼     │
   *              │    ┌───────┐┌───────┐ │
   *              │    │ Catch ││ Catch ├─┤
   *              │    └───┬───┘└───┬───┘ │
   *              └─┬──────┴────────┘     │
   *                ▼                     ▼
   *           ┌─────────┐           ┌─────────┐
   *           │ Finally ├──────┐    │ Finally ├──┐
   *           └────┬────┘      │    └────┬────┘  │
   *                ▼           └─────────┴───────┴─►
   *  α = tryEffect
   *  λ = α.retracted.seq.(catchEffects.reduce.alt)
   *  β = α.alt(λ)
   *  finallyCtx = β.retracted
   *  δ = finallyEffect
   *  resultNNInfo = β.seq(δ).alt(β.retracted.seq(δ).seq(empty.terminated))
   *
   *  It is sufficient to type finally once provided that we type it in a context
   *  that considers all the paths before it that reach the finally. Since the NNinfo
   *  that we get from typing finally summarizes the effect of the finally, we can
   *  type the finally once and use the obtained NN info twice: once sequenced
   *  with β (normalNNInfo) and once sequenced with β.retractedInfo but post-sequenced
   *  by empty.terminated (to indicate that this path does not reach the code after
   *  the try-catch-finally).
   */
```

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2457,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+    else
+      NotNullInfo.empty
+    val normalResolveNNInfo = tryNNInfo.alt(catchNNInfo)
+    val exceptionalResolveNNInfo = catchNNInfo.retractedInfo
+
+    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(exceptionalResolveNNInfo))
+    val normalFinalNNInfo = normalResolveNNInfo.seq(finalizer1.notNullInfo)
+    val exceptionalFinalNNInfo = exceptionalResolveNNInfo.seq(finalizer1.notNullInfo)
+    val resNNInfo =
+      if (cases2.forall(_.tpe == defn.NothingType)) then
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: If the `notNullinfo.asserted` is `null`, then we know the program terminates in middle exceptionally, which tracks more cases than just the result type. See the comment of `NotNullInfo` and uses of `terminatedInfo`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -2457,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
-      nnInfo = expr1.notNullInfo.retractedInfo
-
-      val casesCtx = ctx.addNotNullInfo(nnInfo)
+      val casesCtx = ctx.addNotNullInfo(expr1.notNullInfo.retractedInfo)
       val cases1 = typedCases(tree.cases, EmptyTree, defn.ThrowableType, pt.dropIfProto)(using casesCtx)
       expr1 :: cases1
     }: @unchecked
     val cases2 = cases2x.asInstanceOf[List[CaseDef]]
-
+    val tryNNInfo = expr2.notNullInfo
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: The names of `tryNNInfo` and `catchNNInfo` variables are confusing. 
* We should rename `tryNNInfo` to `exprNNInfo` to indicate the info from `expr`.
* According to the logic, if cases is not empty, `catchNNInfo` contains the nninfo not only from cases but also from the expr?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -2457,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
     // Therefore, the code in the finalizer and after the try block can only rely on the retracted
     // info from the cases' body.
-    if cases2.nonEmpty then
-      nnInfo = nnInfo.seq(cases2.map(_.notNullInfo.retractedInfo).reduce(_.alt(_)))
-
-    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(nnInfo))
-    nnInfo = nnInfo.seq(finalizer1.notNullInfo)
-    assignType(cpy.Try(tree)(expr2, cases2, finalizer1), expr2, cases2).withNotNullInfo(nnInfo)
+    val catchNNInfo = if cases2.nonEmpty then
+      tryNNInfo.seq(cases2.map(_.notNullInfo).reduce(_.alt(_)))
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: As the comment mentioned, it is possible to have non-exhaustive cases, so we can only use the `retractedInfo` from the cases and combine

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 4]
```diff
@@ -2457,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+    val exceptionalResolveNNInfo = catchNNInfo.retractedInfo
+
+    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(exceptionalResolveNNInfo))
+    val normalFinalNNInfo = normalResolveNNInfo.seq(finalizer1.notNullInfo)
+    val exceptionalFinalNNInfo = exceptionalResolveNNInfo.seq(finalizer1.notNullInfo)
+    val resNNInfo =
+      if (cases2.forall(_.tpe == defn.NothingType)) then
+        normalFinalNNInfo
+      else
+        exceptionalFinalNNInfo
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: As discussed in https://github.com/scala/scala3/issues/24296#issuecomment-3458966918, if we want to consider the situation where all cases are exceptional, we should only apply the special rule if `finally` is empty, otherwise we need to type `finally` tree twice using different initial nninfos.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 5]
```diff
@@ -2457,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
-    if cases2.nonEmpty then
-      nnInfo = nnInfo.seq(cases2.map(_.notNullInfo.retractedInfo).reduce(_.alt(_)))
-
-    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(nnInfo))
-    nnInfo = nnInfo.seq(finalizer1.notNullInfo)
-    assignType(cpy.Try(tree)(expr2, cases2, finalizer1), expr2, cases2).withNotNullInfo(nnInfo)
+    val catchNNInfo = if cases2.nonEmpty then
+      tryNNInfo.seq(cases2.map(_.notNullInfo).reduce(_.alt(_)))
+    else
+      NotNullInfo.empty
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: If `cases` is empty, then the nninfo from `expr` will never be included?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 6]
```diff
@@ -2457,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+    val normalResolveNNInfo = tryNNInfo.alt(catchNNInfo)
+    val exceptionalResolveNNInfo = catchNNInfo.retractedInfo
+
+    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(exceptionalResolveNNInfo))
+    val normalFinalNNInfo = normalResolveNNInfo.seq(finalizer1.notNullInfo)
+    val exceptionalFinalNNInfo = exceptionalResolveNNInfo.seq(finalizer1.notNullInfo)
+    val resNNInfo =
+      if (cases2.forall(_.tpe == defn.NothingType)) then
+        normalFinalNNInfo
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Also, I would like to name the situation where all cases terminates exceptionally as "exceptional"..

File: tests/explicit-nulls/neg/i21619.scala [hunk 7]
```diff
@@ -89,4 +89,78 @@ def test6 = {
...
+  x.trim() // ok
+
+def test9() =
+  var x: String | Null = null
+  try {
+    x = ""
+  } catch {
+    case e: AssertionError =>
+      throw e
+    case _ =>
```
Comment (olhotak) [inline tests/explicit-nulls/neg/i21619.scala:178]: Add a variant of `test9` without the default case (with only the `AssertionError` case).

File: tests/explicit-nulls/neg/i21619.scala [hunk 8]
```diff
@@ -89,4 +89,78 @@ def test6 = {
...
+    x = ""
+  } catch {
+    case e =>
+      x = null
+      throw e
+  } finally {
+    throw new Exception
+    x = ""
+  }
+  x.trim() // ok
```
Comment (olhotak) [inline tests/explicit-nulls/neg/i21619.scala]: Add a variant of `test12` without the `x = ""` in the `finally` clause. That should still be `// ok` because the `finally` clause cannot terminate normally, so the `x.trim()` is unreachable.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 9]
```diff
@@ -2436,8 +2436,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
       val capabilityProof = caughtExceptions.reduce(OrType(_, _, true))
       untpd.Block(makeCanThrow(capabilityProof), expr)
 
+  /** Graphic explaination of NotNullInfo logic:
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
  /** Graphic explanation of NotNullInfo logic:
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 10]
```diff
@@ -2436,8 +2436,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+   *            ┌─────────┐          ┌─────────┐
+   * δ = type(ε)│ Finally ├──────┐   │ Finally ├─────────┐
+   *            └────┬────┘      │   └────┬────┘         │
+   *                 │           │        ▼              ▼
+   *                 │ γ.seq(δ)  └──────────────────────────►
+   *                 ▼                               ε.seq(δ)
+   *  We choose to use γ.seq(δ) as the NotNullInfo of the
+   *  overall tree if all the catch cases have NothingType,
+   *  otherwise we use ε.seq(δ).
+   */
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2466]: It occurred to me that putting the Greek letters on the diagram is misleading. (I take the blame for originally 
suggesting it.)

It is misleading because the `nnInfo` represents the effect of a piece of code, not the nullness information at a particular program point. The Greek letters on the diagram suggest program points.

Instead, the Greek letters should be defined below the diagram as equations. (And we could come up with suitable descriptive English names instead of Greek letters.)

\alpha = effect of try
\lambda = \alpha.retractedInfo seq ((effects of catches).reduce(alt))
\beta = \alpha alt \lambda
context for typing finally = (\alpha.retractedInfo) alt (\lambda.retractedInfo) = \beta.retractedInfo
\delta = effect of finally
\theta = (\beta seq \delta) alt (\beta.retractedInfo seq \delta seq empty.terminatedInfo)

Possible English names:
\alpha -> effectOfTry
\delta -> effectOfFinally
\theta is just the final nnInfo that we compute for the whole try-catch-finally, so maybe it doesn't need a name
\lambda and \beta I'm not sure of good names
contextForFinally would be a good name, or finallyCtx
\beta means try/catch has completed normally (possibly with an exception that was handled by the catch)
The code below uses `normalNNInfo` for \beta and `exceptionalResolveNNInfo` for finallyCtx

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 2 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: We need to distinguish \beta (from my comment above) from finallyCtx. Here `catchNNInfo` is computing \beta. But I agree it needs to use the retracted form of `tryNNInfo`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 11]
```diff
@@ -2450,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
     // Therefore, the code in the finalizer and after the try block can only rely on the retracted
     // info from the cases' body.
-    if cases2.nonEmpty then
-      nnInfo = nnInfo.seq(cases2.map(_.notNullInfo.retractedInfo).reduce(_.alt(_)))
-
-    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(nnInfo))
-    nnInfo = nnInfo.seq(finalizer1.notNullInfo)
-    assignType(cpy.Try(tree)(expr2, cases2, finalizer1), expr2, cases2).withNotNullInfo(nnInfo)
+    val catchNNInfo = if cases2.nonEmpty then
+      tryNNInfo.seq(cases2.map(_.notNullInfo).reduce(_.alt(_)))
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
      tryNNInfo.retractedInfo.seq(cases2.map(_.notNullInfo).reduce(_.alt(_)))
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 3 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: If the cases are non-exhaustive, then not matching any of the cases causes an exception to propagate outwards. It is equivalent to adding a default case `case e => thow e`.

In this case, the finally block does get executed but the code after the try-catch-finally does not execute.

Therefore, \beta should have the **non-retracted** info from the cases for finallyCtx needs to have the retracted info.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 5 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: It need not be included in \lambda here (`catchNNInfo`) because we will recover it when we do `\beta = \alpha alt \lambda`, but it does need to be included in finallyCtx. See my suggested code change to `exceptionalResolveNNInfo` below.

Example (please add as a test case):
```scala
try {
  x = null
  throw new RuntimeException
} finally {
  x.trim() // error
}
x.trim() // OK
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 12]
```diff
@@ -2450,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+    else
+      NotNullInfo.empty
+    val normalResolveNNInfo = tryNNInfo.alt(catchNNInfo)
+    val exceptionalResolveNNInfo = catchNNInfo.retractedInfo
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
    val exceptionalResolveNNInfo = normalResolveNNInfo.retractedInfo // tryNNInfo.retractedInfo.alt(catchNNInfo.retractedInfo)
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I agree. I think the correct thing to do here would be
```scala
val resNNInfo = normalFinalNNInfo alt (exceptionalFinalNNInfo seq NotNullInfo.empty.terminatedInfo)
```
See \theta in my comment above.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 5 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: However, if cases is empty, it should be `empty.terminatedInfo` because any exception will never be caught.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 13]
```diff
@@ -2450,25 +2473,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
-    if cases2.nonEmpty then
-      nnInfo = nnInfo.seq(cases2.map(_.notNullInfo.retractedInfo).reduce(_.alt(_)))
-
-    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(nnInfo))
-    nnInfo = nnInfo.seq(finalizer1.notNullInfo)
-    assignType(cpy.Try(tree)(expr2, cases2, finalizer1), expr2, cases2).withNotNullInfo(nnInfo)
+    val catchNNInfo = if cases2.nonEmpty then
+      tryNNInfo.seq(cases2.map(_.notNullInfo).reduce(_.alt(_)))
+    else
+      NotNullInfo.empty
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
      NotNullInfo.empty.terminatedInfo
```

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 4 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: It is sufficient to type `finally` once provided that we type it in a context that considers all the paths before it that reach the `finally`. That condition is satisfied in the status quo and should also be satisfied in this PR with the suggested fixes.

The NN info that we get from typing `finally` is a summary of the effect of the finally block on the nullness state. An important distinction is that the effect is **not** an abstraction of the nullness state at any particular program point, such as the end of the `finally` block. This distinction is what makes the Greek letters in the diagram misleading.

Since the NN info that we get from typing `finally` summarizes the effect of the `finally`, we can type the `finally` once and use the obtained NN info twice: once sequenced with \beta (`normalNNInfo`) and once sequenced with \beta.retractedInfo but post-sequenced by empty.terminated (to indicate that this path does not reach the code after the try-catch-finally).

The latter alternative is necessary because the NN info represents, in one structure, both the information about normal completion of a block of code and about exceptional completion of a block of code. Specifically, for a given resNNInfo computed for a try-catch-finally block, both of the following need to be correct:

1. If the t-c-f block completes normally, the resNNInfo soundly overapproximates the state for the code after the t-c-f block.
2. If the t-c-f block completes exceptionally, then resNNInfo.retractedInfo soundly overapproximates the state in any exception handler that may be catching this exception.

It is easy to focus on 1. and forget about 2.

A possible alternative design would be for NNinfo to explicitly distinguish these two cases, so that `.retractedInfo` doesn't just manipulate these two sets. This would require a third set in `NNinfo` for what is retracted on an exceptional completion. (The asserted set for an exceptional completion is always empty, so we don't need to add a fourth set.) That would be a refactoring of NNinfo. It would give a small improvement in precision, perhaps too small to be valuable, and an improvement in understandability, which may be a more compelling argument for doing it.

**Comment by olhotak** [comment]
I see that Github reordered my comments by the chronological order of @noti0na1 's comments that they were replying to. That puts my comments in a confusing order. It's clearer to read them in code order, in the order in which they appear on the Files Changed view.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 10 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:2466]: No, I did mean beta, not alpha. Another way of writing it would be:
\theta = (\alpha seq \delta) alt (\lambda seq \delta) alt (\beta.retractedInfo seq \delta seq empty.terminatedInfo)
But since \beta = \alpha alt \lambda, I think the first two cases are equivalent to \beta seq \delta.

\alpha seq \delta corresponds to the try block completing normally, then the finally block completing normally.

\lambda seq \delta corresponds to the try block throwing, the catch block catching it and completing normally, then the finally block completing normally.

Comment (HarrisL2) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:2466]: I see, I realized after commenting that I mixed up some symbols and deleted my reply, sorry for the confusion.

**Comment by noti0na1** [comment]
This is the example I mentioned yesterday. If we are able to type the finally block twice, the following test can pass (although we don't want to make it pass to avoid typing twice):

```scala
class SomeException extends Exception

def test1: String =
  var x: String | Null = ???
  var y: String | Null = ???
  // ...
  try
    x = null
    // ...
    x = ""
  catch
    case e: SomeException =>
      x = null
      // situation 1: don't throw or return
      // situation 2:
      return ""
  finally
    y = x
    // should always error on y.trim

  y.trim  // ideally, should error if situation 1, should not error if situation 2
```

**Comment by noti0na1** [comment]
I simplify the logic a little bit to reduce some computation:

```scala
    val exprNNInfo = expr2.notNullInfo

    // The total effect only from catch cases
    val casesNNInfo =
      cases2.map(_.notNullInfo)
        .foldLeft(NotNullInfo.empty.terminatedInfo)(_.alt(_))

    // The nnInfo after executing all catch cases
    val nnInfoBeforeFinally = exprNNInfo.retractedInfo.seq(casesNNInfo)

    // It is possible to have non-exhaustive cases, and some exceptions are thrown and not caught.
    // Therefore, the code in the finalizer and after the try block can only rely on the retracted
    // info from the cases' body.
    val finalizer1 = typed(tree.finalizer, defn.UnitType)(using ctx.addNotNullInfo(nnInfoBeforeFinally.retractedInfo))

    val resNNInfo = exprNNInfo.alt(nnInfoBeforeFinally).seq(finalizer1.notNullInfo)
```

I also have some additional tests:

```scala

class SomeException extends Exception

def test1: String =
  var x: String | Null = ???
  var y: String | Null = ???
  // ...
  try
    x = null
    // ...
    x = ""
  catch
    case e: SomeException =>
      x = null
      // situation 1: don't throw or return
      // situation 2:
      return ""
  finally
    y = x
    // should always error on y.trim

  y.trim  // ideally, should error if situation 1, should not error if situation 2

def test2: String =
  var x: String | Null = ???
  x = ""
  try
    // call some method that throws
    // ...
    x = ""
  catch
    case e: SomeException =>
      x = null
      // call some method that throws
      // ...
      x = "<error>"
  finally {}

  x.trim() // ok

def test3: String =
  var x: String | Null = ???
  x = ""
  try
    // call some method that throws
    // ...
    x = ""
  catch
    case e: SomeException =>
      x = null
      // call some method that throws
      // ...
      x = "<error>"
  finally
    println(x.trim()) // should error

  ""

def test4: String =
  var x: String | Null = ???
  var y: String | Null = ???
  // ...
  try
    x = null
    y = null
    // ...
    x = ""
    y = ""
  catch
    case e: SomeException =>
      x = null
      return ""
  finally {}

  x.trim + y.trim


def test5: String =
  var x: String | Null = ???
  try
    x = null
  catch
    case e: SomeException =>
      x = null
      throw e
  finally
    throw new Exception()
  x.trim // ok

def test6: String =
  var x: String | Null = ???
  x = ""
  try
    x = ""
  catch
    case e: SomeException =>
      x = ""
  finally {}
  x.trim // ok
```

~~I also find some tests I think is not correct in `tests/explicit-nulls/neg/i21619.scala`. For example:~~

```scala
def test2: String =
  var x: String | Null = null
  x = ""
  var i: Int = 1
  try
    i match
      case _ =>
        x = null
        throw new Exception()
    x = ""
  catch
    case e: NoSuchMethodError =>
      x = "e"
  x.replace("", "") // should be error
```

~~Inside the body of the case, there may be an exception thrown before the assignment, so we only rely on the retracted info.~~

**Comment by HarrisL2** [comment]
> I also find some tests I think is not correct in tests/explicit-nulls/neg/i21619.scala. For example:
```scala
def test2: String =
  var x: String | Null = null
  // x = ""    // assume this line isn't here
  var i: Int = 1
  try
    i match
      case _ =>
        x = null
        throw new Exception()
    x = ""
  catch
    case e: NoSuchMethodError =>
      x = "e"
  x.replace("", "") // should be error
```
> Inside the body of the case, there may be an exception thrown before the assignment, so we only rely on the retracted info.

If an exception is caught before the assignment, either it will be caught by the given case, which assigns it a valid value, or it is not caught, at which point it is terminated info. So `x.replace` should still be ok.

**Comment by noti0na1** [comment]
Oh I forgot, then the `restNNInfo` can be simpler: 

```scala
val resNNInfo = exprNNInfo.alt(nnInfoBeforeFinally).seq(finalizer1.notNullInfo)
```

Maybe we should also mention some assumptions in the comment like: for all `nninfo`, if a tree can be typed using `nninfo.retractedInfo`, then it can also be typed using `nninfo`.

**Review by noti0na1 — APPROVED** [review]
