### PR TITLE
Enter missing symbols generated by the MacroAnnotation expansion

### LINKED ISSUE #18825: Overriding final method using MacroAnnotations
## Compiler version

3.3.1

## Minimized code

`Macro_1.scala`

```scala
import scala.annotation.experimental
import scala.annotation.MacroAnnotation
import scala.quoted.*

@experimental
class toString extends MacroAnnotation :
    def transform(using Quotes)(tree: quotes.reflect.Definition): List[quotes.reflect.Definition] =
        import quotes.reflect.*
        tree match
            case ClassDef(name, ctr, parents, self, body) =>
                val cls = tree.symbol
                val toStringSym = Symbol.requiredMethod("java.lang.Object.toString")
                val toStringOverrideSym = Symbol.newMethod(cls, "toString", toStringSym.info, Flags.Override, Symbol.noSymbol)
                val toStringDef = DefDef(toStringOverrideSym, _ => Some(Literal(StringConstant("Hello from macro"))))
                val newClassDef = ClassDef.copy(tree)(name, ctr, parents, self, toStringDef :: body)
                List(newClassDef)
            case _ =>
                report.error("@toString can only be annotated on class definitions")
                tree :: Nil
```

`Test_2.scala`

```scala
import annotation.experimental

class Foo :
    final override def toString(): String = "Hello"

@experimental
@toString
class AFoo extends Foo //:
    //override def toString(): String = "Hello from macro"

@experimental
@main def run =
    println(new AFoo().toString)
```

## Output

It compiles and it crashes when running the code

## Expectation

It should not compile

### PR DESCRIPTION
**Pull request by hamzaremmal**
Closes #18825 & #18806

### CODE REVIEW

**Comment by nicolasstucki** [comment]
There is a failure in `tests/run/quotes-add-erased`. The macro migth be doing somthing that it should not and now it got caught.

**Comment by nicolasstucki** [comment]
The failure was 
```
 error overriding method takesErased in class TakesErased of type (erased x: Int, y: Int): Int;
  method takesErased of type (erased x: Int, y: Int): Int needs `override` modifier
```

I assume that we simply missed the `override` in the flags of the new Symbol we create in `tests/run/quotes-add-erased/Macros_1.scala`.

File: compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala [hunk 1]
```diff
@@ -130,6 +134,20 @@ class MacroAnnotations:
     else if annotated.isClass && annotated.owner.is(Package) /*&& !sym.isClass*/ then
       report.error(i"macro annotation can not add top-level ${sym.showKind}. $annot tried to add $sym.", annot.tree)
 
+  private def enterMissingSymbols(tree: DefTree)(using Context) = new TreeTraverser {
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala:137]: This deserves some documetnation

File: compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala [hunk 2]
```diff
@@ -130,6 +134,20 @@ class MacroAnnotations:
...
+    def traverse(tree: tpd.Tree)(using Context): Unit = tree match
+      case tdef @ TypeDef(_, template: Template) =>
+        //for tree <- template.constr :: template.body do
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala:140]:
```suggestion
```

File: compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala [hunk 3]
```diff
@@ -130,6 +134,20 @@ class MacroAnnotations:
...
+        val isSymbolInDecls = tdef.symbol.asClass.info.decls.toList.toSet
+        for tree <- template.body do
+          if tree.symbol.owner != tdef.symbol then
+            report.error(em"Macro added a definition with the wrong owner - ${tree.symbol.owner} - ${tdef.symbol} in ${tree.source}")
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala:144]: We should have a test that produces this error. This test should have a checkfile.

File: compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala [hunk 4]
```diff
@@ -130,6 +134,20 @@ class MacroAnnotations:
...
+          else if !isSymbolInDecls(tree.symbol) then
+            tree.symbol.enteredAfter(phase)
+        traverseChildren(tree) // Traverse before or after dealing with this class?
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala:147]:
```suggestion
        traverseChildren(tree)
```

**Review by nicolasstucki — CHANGES_REQUESTED** [review]
Also squash and rebase the commit on main.

File: compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala (hunk 3 above)
Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala:146]: I don't think we need this check anymore. When running the `wrong-owner` test, I have the following result in `testlog`

> -- Error: tests/neg-macros/wrong-owner/Test_2.scala:7:6 ----------------------------------------------------------------
> 5 |@experimental
> 6 |@wrongOwner
> 7 |class Foo
>   |^
>   |Malformed tree was found while expanding macro with -Xcheck-macros.
>   |               |The tree does not conform to the compiler's tree invariants.
>   |               |
>   |               |Macro was:
>   |               |@scala.annotation.internal.SourceFile("tests/neg-macros/wrong-owner/Test_2.scala") @wrongOwner @scala.annotation.experimental class Foo()
>   |               |
>   |               |The macro returned:
>   |               |@scala.annotation.internal.SourceFile("tests/neg-macros/wrong-owner/Test_2.scala") @wrongOwner @scala.annotation.experimental class Foo() {
>   |  override def toString(): java.lang.String = "Hello from macro"
>   |}
>   |               |
>   |               |Error:
>   |               |assertion failed: bad owner; method toString has owner class String, expected was class Foo
>   |owner chain = method toString, class String, package java.lang, package java, package <root>, ctxOwners = class Foo, class Foo, package <empty>, package <empty>, package <empty>, package <root>, package <root>, package <root>, package <root>, package <root>, package <root>, <none>, <none>, <none>, <none>, <none>
>   |               |
>   |stacktrace available when compiling with `-Ydebug`
>   |               |
> Macro added a definition with the wrong owner - class String - class Foo in tests/neg-macros/wrong-owner/Test_2.scala
> 2 errors found

Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala]: Fixed. The issue was that tests under the `/tests/neg-macros` run with the `-Xcheck-macros` which itself trigger the second error. We agreed with @nicolasstucki to keep both error messages in the sense that if the flag is enabled, the more developed error message will be displayed.

Comment (hamzaremmal) [reply compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala]: Actually, maybe we should add this information in the new error message. e.g "More information available under with the `-Xcheck-macros`"

**Comment by hamzaremmal** [comment]
**How I fixed it** :

- First, I checked if the issue is up to date. 
- When compiling the code and running it, we see that the generated code is presented in the byte code and it crashes when running. 
- After, I've checked if the generated tree is presented after the Inlining by compiling with the `-Xprint:inline` flag. 
- After compiling the `-Xprint:inline` flag, we can see that the tree is correct and not malformed. The question still remains, why is this tree skipping all the tests.
- To answer this question, I had to change the point of view, from trees to symbols. The question remains: Are the symbol consistent ?
- After checking, we can see that all the symbols generated by MacroAnnotations are not actually entered and therefore, the compiler is blind towards them and skips all the checks.
- To fix, we needed to enter the new symbols and that what this PR does :-)

File: tests/neg-macros/wrong-owner/Test_2.scala [hunk 5]
```diff
@@ -0,0 +1,5 @@
+import scala.annotation.experimental
+
+@experimental
+@wrongOwner
+class Foo // error
```
Comment (nicolasstucki) [inline tests/neg-macros/wrong-owner/Test_2.scala:5]: Add missing last line line return to all files.
```suggestion
class Foo // error

```

**Review by nicolasstucki — COMMENTED** [review]
LGTM.

@hamzaremmal could you squash your commits into one?

File: tests/neg-macros/wrong-owner/Test_2.scala (hunk 5 above)
Comment (hamzaremmal) [reply tests/neg-macros/wrong-owner/Test_2.scala]: Done

**Comment by hamzaremmal** [comment]
@nicolasstucki I've squashed the commits into one with all the necessary changes

**Review by nicolasstucki — APPROVED** [review]
