### PR TITLE
Change is volatile

### LINKED ISSUE #1047: infinite loop typechecking nominal subtyping hierarchies
I wanted to test out in DOT a way to create nominal subtyping hierarchies, that can be modular, and both sealed or open. I get a StackOverflow for the `newSubCat` def.

```scala
package hello

object world extends App {
  println("hello dotty!")

  trait AnimalPackage {
    type Animal <: AnimalU
    type AnimalU = { val age: Int }
    def newAnimal(a: AnimalU): Animal
    def newSubAnimal[T](a: AnimalU & T): Animal & T
  }
  val p: AnimalPackage = new AnimalPackage { p =>
    type Animal = AnimalU
    override def newAnimal(a: AnimalU): Animal = a
    override def newSubAnimal[T](a: AnimalU & T): Animal & T = a
  }
  val lambda: p.Animal = p.newAnimal(new { val age = 1 })
  trait CatPackage { pc =>
    type Cat <: p.Animal & pc.CatDelta
    type CatDelta = { val meow: Int }
    type CatU = p.AnimalU & pc.CatDelta
    def newCat(c: CatU): Cat
    def newSubCat[T](c: CatU & T): Cat & T
  }
  val pc: CatPackage = new CatPackage { pc =>
    type Cat = p.Animal & pc.CatDelta
    def newCat(c: CatU): Cat = p.newSubAnimal[pc.CatDelta](c)
    def newSubCat[T](c: CatU & T): Cat & T = p.newSubAnimal[pc.CatDelta & T](c)
  }
  val felix: pc.Cat = pc.newCat(new { val age = 1; val meow = 2 })
}
```

The error is

```
[info] Running dotty.tools.dotc.Main examples/hello.scala
[error] Exception in thread "main" java.lang.StackOverflowError
[error] 	at dotty.tools.dotc.core.Scopes$Scope.denotsNamed(Scopes.scala:117)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.membersNamed(SymDenotations.scala:1498)
[error] 	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.findMember(SymDenotations.scala:1551)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:432)
[error] 	at dotty.tools.dotc.core.Types$Type.goRefined$1(Types.scala:457)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:428)
[error] 	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:522)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.findMember(Denotations.scala:177)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:432)
[error] 	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:522)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.findMember(Denotations.scala:177)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:432)
[error] 	at dotty.tools.dotc.core.Types$Type.goAnd$1(Types.scala:512)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:446)
[error] 	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:522)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.findMember(Denotations.scala:177)
[error] 	at dotty.tools.dotc.core.Types$Type.go$1(Types.scala:432)
[error] 	at dotty.tools.dotc.core.Types$Type.findMember(Types.scala:522)
[error] 	at dotty.tools.dotc.core.Types$Type.memberExcluding(Types.scala:418)
[error] 	at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:409)
[error] 	at dotty.tools.dotc.core.Types$Type$$anonfun$member$1.apply(Types.scala:409)
[error] 	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error] 	at dotty.tools.dotc.core.Types$Type.member(Types.scala:408)
[error] 	at dotty.tools.dotc.core.Types$abstractTermNameFilter$.apply(Types.scala:3354)
[error] 	at dotty.tools.dotc.core.Types$Type.memberNames(Types.scala:547)
[error] 	at dotty.tools.dotc.core.Types$Type.memberNames(Types.scala:551)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1$$anonfun$apply$1.apply(TypeOps.scala:356)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1$$anonfun$apply$1.apply(TypeOps.scala:353)
[error] 	at scala.collection.LinearSeqOptimized$class.exists(LinearSeqOptimized.scala:93)
[error] 	at scala.collection.immutable.List.exists(List.scala:84)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1.apply(TypeOps.scala:353)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1.apply(TypeOps.scala:348)
[error] 	at scala.collection.LinearSeqOptimized$class.forall(LinearSeqOptimized.scala:83)
[error] 	at scala.collection.immutable.List.forall(List.scala:84)
[error] 	at dotty.tools.dotc.core.TypeOps$class.isVolatile(TypeOps.scala:348)
[error] 	at dotty.tools.dotc.core.Contexts$Context.isVolatile(Contexts.scala:53)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1.apply(TypeOps.scala:359)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1.apply(TypeOps.scala:348)
[error] 	at scala.collection.LinearSeqOptimized$class.forall(LinearSeqOptimized.scala:83)
[error] 	at scala.collection.immutable.List.forall(List.scala:84)
[error] 	at dotty.tools.dotc.core.TypeOps$class.isVolatile(TypeOps.scala:348)
[error] 	at dotty.tools.dotc.core.Contexts$Context.isVolatile(Contexts.scala:53)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1.apply(TypeOps.scala:359)
[error] 	at dotty.tools.dotc.core.TypeOps$$anonfun$isVolatile$1.apply(TypeOps.scala:348)
[error] 	at scala.collection.LinearSeqOptimized$class.forall(LinearSeqOptimized.scala:83)
...
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #1047 and prepares the way for other realizibility tests involving `null` and type projections.

### CODE REVIEW

**Comment by odersky** [comment]
Also fixes #1050.

**Comment by odersky** [comment]
Also fixes #50 and #1050.

**Comment by odersky** [comment]
State so far: Problems involving type projections and laziness should be addressed by this PR. Problems involving `null` need the planned changes to the typesystem which model `null` explicitly. Problems involving uninitialized fields need to be handled separately.

**Comment by odersky** [comment]
What's the review status of this one? If there are no further comments this will be merged.

**Comment by smarter** [comment]
I'll review this today

File: src/dotty/tools/dotc/core/CheckRealizable.scala [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+  private val checkedFields: mutable.Set[Symbol] = mutable.LinkedHashSet[Symbol]()
+
+  /** Is symbol's definitition a lazy val?
+   *  (note we exclude modules here, because their realizability is ensured separately)
+   */
+  private def isLateInitialized(sym: Symbol) = sym.is(Lazy, butNot = Module)
+
+  /** Is this type a path with some part that is initialized on use?
+   */
+  private def isLateInitialized(tp: Type): Boolean = tp.dealias match {
```
Comment (smarter) [inline src/dotty/tools/dotc/core/CheckRealizable.scala]: This method is never used.

File: src/dotty/tools/dotc/core/CheckRealizable.scala [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+      val bounds = mbr.info.bounds
+      !(bounds.lo <:< bounds.hi)
+    }
+    tp.nonClassTypeMembers.find(hasBadBounds) match {
+      case Some(mbr) => new HasProblemBounds(mbr)
+      case _ => Realizable
+    }
+  }
+
+  /** `Realizable` if `tp` all of `tp`'s non-struct fields have realizable types,
```
Comment (smarter) [inline src/dotty/tools/dotc/core/CheckRealizable.scala]: I think the first ``tp`` should not be there: "Realizable if all of ..."

File: src/dotty/tools/dotc/core/CheckRealizable.scala [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+   *  a `HasProblemField` instance pointing to a bad field otherwise.
+   */
+  private def memberRealizability(tp: Type) = {
+    def checkField(sofar: Realizability, fld: SingleDenotation): Realizability =
+      sofar andAlso {
+        if (checkedFields.contains(fld.symbol) || fld.symbol.is(Private | Mutable | Lazy))
```
Comment (smarter) [inline src/dotty/tools/dotc/core/CheckRealizable.scala]: Why do you bypass the realizability checks if a field is private or mutable or lazy?

File: src/dotty/tools/dotc/typer/Checking.scala [hunk 4]
```diff
@@ -49,7 +50,7 @@ object Checking {
     checkBounds(args, poly.paramBounds, _.substParams(poly, _))
 
   /** Check all AppliedTypeTree nodes in this tree for legal bounds */
```
Comment (smarter) [inline src/dotty/tools/dotc/typer/Checking.scala]: This documentation needs to be updated.

**Comment by smarter** [comment]
This patch makes the following code illegal:
```scala
trait HasA {
  type A
}
trait Foo[T <: HasA] {
  type B = T#A // error: T is not a legal path since it is not a concrete type
}
```
However, I think that we can safely allow this, because `Foo#B` is not a valid path, you need to write `Foo[something]#B` and we will check at that point if the type is legal or not. What do you think?

**Comment by smarter** [comment]
Nevermind, if we allow this then the following would compile:
```scala
object Test {
  trait C { type A }

  type T = C { type A >: Any }
  type U = C { type A <: Nothing }

  trait Foo[Elem <: T] {
    def foo: Elem#A = 1
  }

  def main(args: Array[String]) = {
    val a = new Foo[T & U] {}
    val z: String = a.foo
  }
}
```

**Comment by smarter** [comment]
This pull request needs to be rebased.

File: src/dotty/tools/dotc/typer/Checking.scala [hunk 5]
```diff
@@ -57,6 +58,12 @@ object Checking {
           val bounds = tparams.map(tparam =>
             tparam.info.asSeenFrom(tycon.tpe.normalizedPrefix, tparam.owner.owner).bounds)
           checkBounds(args, bounds, _.substDealias(tparams, _))
+        case Select(qual, name) if name.isTypeName =>
+          checkRealizable(qual.tpe, qual.pos)
+        case SelectFromTypeTree(qual, name) if name.isTypeName =>
+          checkRealizable(qual.tpe, qual.pos)
+        case SingletonTypeTree(ref) =>
+          checkRealizable(ref.tpe, ref.pos)
         case _ =>
```
Comment (smarter) [inline src/dotty/tools/dotc/typer/Checking.scala]: What about `AndTypeTree`, `OrTypeTree, `RefinedTypeTree`, etc? Maybe we should add a case like:
```scala
case typ: TypTree =>
  checkRealizable(typ.tpe, typ.pos)
```
I think that if we do this, then my proposition at https://github.com/lampepfl/dotty/pull/1051#issuecomment-181572666 becomes safe, because `Foo[T & U]` will be invalid.

Comment (odersky) [inline src/dotty/tools/dotc/typer/Checking.scala]: That's not how things are done in DOT. We have one scheme to ensure soundness that we know works and a lot of others that we thought worked at some time, but didn't in the end. So we should stick to the one that works. I believe approximating realizability of other types is too strict and is also not necessary.

**Comment by Atry** [comment]
Is it possible to treat singleton types as stable?
Does it sound?
``` scala
object O {
  type T = String
}

def stableMethod: O.type = O

def doesItSound(x: stableMethod.T) = x
```

**Comment by smarter** [comment]
@Atry Maybe, but it seems cleaner to never allow defs to be stable. In  your example you could just write `val stableMethod: O.type = O` instead, is there a specific reason why you would want it to be a def?

**Comment by Atry** [comment]
`val stableMethod` costs some memory overhead at runtime.

**Comment by Atry** [comment]
Thinking about a very complex monad transformer chain, each depends on another.

**Comment by DhashS** [comment]
Hey, I'm fairly new to Scala and was curious about just this in something I'm writing.

Having both `#` and the dot-notation way of accessing the inner type is not particularly ergonomic. 
In the function body, I think they do different things. (If i'm understanding https://stackoverflow.com/questions/9443004/what-does-the-operator-mean-in-scala correctly).

The existing behaviour is semi-attractive, but if the `#` syntax for in declaring function argument types is probably expected behavior, disallowing dot-notation there might make sense.

I'm not super-sure what I've said is sensical, I'm a fairly new Scala programmer, and not a compiler dev.
