### PR TITLE
fix #25456: parser crash on polymorphic context bound

### LINKED ISSUE #25456: ICE: "exception occurred while parsing" with polymorphic context bounds on higher-kinded type
## Compiler version

3.8.2

## Minimized code

```Scala
trait ApplicativeError[F[_], E]

object A {
  def generate[F[_]: { ApplicativeError[_[?], ?] }]: Int = 1
}
```

## Output (click arrow to expand)

<details>

```scala
[info] compiling 1 Scala source to /home/kisaragi/IdeaProjects/ice-test-20260308/target/scala-3.8.2/classes ...
[info] 
[info]   exception occurred while parser /home/kisaragi/IdeaProjects/ice-test-20260308/src/main/scala/ap.scala
[info] 
[info]   An unhandled exception was thrown in the compiler.
[info]   Please file a crash report here:
[info]   https://github.com/scala/scala3/issues/new/choose
[info]   For non-enriched exceptions, compile with -Xno-enrich-error-messages.
[info] 
[info] 
[info]      while compiling: /home/kisaragi/IdeaProjects/ice-test-20260308/src/main/scala/ap.scala
[info]         during phase: parser
[info]                 mode: Mode(ImplicitsEnabled)
[info]      library version: version 3.8.2
[info]     compiler version: version 3.8.2
[info]             settings: -classpath /home/kisaragi/IdeaProjects/ice-test-20260308/target/scala-3.8.2/classes:/home/kisaragi/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.8.2/scala3-library_3-3.8.2.jar:/home/kisaragi/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/3.8.2/scala-library-3.8.2.jar -d /home/kisaragi/IdeaProjects/ice-test-20260308/target/scala-3.8.2/classes
[error] ## Exception when compiling 1 sources to /home/kisaragi/IdeaProjects/ice-test-20260308/target/scala-3.8.2/classes
[error] java.lang.AssertionError: assertion failed: end of NoSpan
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:10)
[error] dotty.tools.dotc.util.Spans$Span$.end$extension(Spans.scala:51)
[error] dotty.tools.dotc.parsing.Parsers$Parser.contextBound(Parsers.scala:2333)
[error] dotty.tools.dotc.parsing.Parsers$Parser.contextBounds$$anonfun$1$$anonfun$1(Parsers.scala:2343)
[error] dotty.tools.dotc.parsing.Parsers$Parser.commaSeparatedRest(Parsers.scala:672)
[error] dotty.tools.dotc.parsing.Parsers$Parser.commaSeparated(Parsers.scala:660)
[error] dotty.tools.dotc.parsing.Parsers$Parser.contextBounds$$anonfun$1(Parsers.scala:2343)
[error] dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:619)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:638)
[error] dotty.tools.dotc.parsing.Parsers$Parser.contextBounds(Parsers.scala:2343)
[error] dotty.tools.dotc.parsing.Parsers$Parser.typeAndCtxBounds(Parsers.scala:2320)
[error] dotty.tools.dotc.parsing.Parsers$Parser.typeParam$1(Parsers.scala:3671)
[error] dotty.tools.dotc.parsing.Parsers$Parser.typeParamClause$$anonfun$1$$anonfun$1(Parsers.scala:3685)
[error] dotty.tools.dotc.parsing.Parsers$Parser.commaSeparated(Parsers.scala:660)
[error] dotty.tools.dotc.parsing.Parsers$Parser.typeParamClause$$anonfun$1(Parsers.scala:3685)
[error] dotty.tools.dotc.parsing.Parsers$Parser.enclosedWithCommas(Parsers.scala:628)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inBracketsWithCommas(Parsers.scala:642)
[error] dotty.tools.dotc.parsing.Parsers$Parser.typeParamClause(Parsers.scala:3686)
[error] dotty.tools.dotc.parsing.Parsers$Parser.recur$6(Parsers.scala:3619)
[error] dotty.tools.dotc.parsing.Parsers$Parser.typeOrTermParamClauses(Parsers.scala:3623)
[error] dotty.tools.dotc.parsing.Parsers$Parser.defDefOrDcl(Parsers.scala:4165)
[error] dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:4058)
[error] dotty.tools.dotc.parsing.Parsers$Parser.localDef(Parsers.scala:4941)
[error] dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq$$anonfun$1(Parsers.scala:4972)
[error] dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:555)
[error] dotty.tools.dotc.parsing.Parsers$Parser.blockStatSeq(Parsers.scala:4978)
[error] dotty.tools.dotc.printing.SyntaxHighlighting$.highlight(SyntaxHighlighting.scala:133)
[error] dotty.tools.dotc.reporting.MessageRendering.sourceLines(MessageRendering.scala:67)
[error] dotty.tools.dotc.reporting.MessageRendering.messageAndPos(MessageRendering.scala:299)
[error] dotty.tools.dotc.reporting.MessageRendering.messageAndPos$(MessageRendering.scala:21)
[error] dotty.tools.dotc.reporting.AbstractReporter.messageAndPos(AbstractReporter.scala:8)
[error] dotty.tools.xsbt.DelegatingReporter.doReport(DelegatingReporter.java:57)
[error] dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:171)
[error] dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:206)
[error] dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:225)
[error] dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:228)
[error] dotty.tools.dotc.report$.error(report.scala:72)
[error] dotty.tools.dotc.parsing.Parsers$ParserCommon.syntaxError(Parsers.scala:179)
[error] dotty.tools.dotc.parsing.Parsers$ParserCommon.syntaxError(Parsers.scala:172)
[error] dotty.tools.dotc.parsing.Parsers$Parser.syntaxErrorOrIncomplete(Parsers.scala:309)
[error] dotty.tools.dotc.parsing.Parsers$Parser.accept(Parsers.scala:327)
[error] dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:619)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:638)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:652)
[error] dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:655)
[error] dotty.tools.dotc.parsing.Parsers$Parser.templateBody(Parsers.scala:4754)
[error] dotty.tools.dotc.parsing.Parsers$Parser.templateBodyOpt(Parsers.scala:4747)
[error] dotty.tools.dotc.parsing.Parsers$Parser.template(Parsers.scala:4724)
[error] dotty.tools.dotc.parsing.Parsers$Parser.templateOpt(Parsers.scala:4736)
[error] dotty.tools.dotc.parsing.Parsers$Parser.objectDef(Parsers.scala:4350)
[error] dotty.tools.dotc.parsing.Parsers$Parser.tmplDef(Parsers.scala:4304)
[error] dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:4064)
[error] dotty.tools.dotc.parsing.Parsers$Parser.topStatSeq(Parsers.scala:4818)
[error] dotty.tools.dotc.parsing.Parsers$Parser.topstats$1(Parsers.scala:5014)
[error] dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit$$anonfun$1(Parsers.scala:5019)
[error] dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:555)
[error] dotty.tools.dotc.parsing.Parsers$Parser.compilationUnit(Parsers.scala:5024)
[error] dotty.tools.dotc.parsing.Parsers$Parser.parse(Parsers.scala:207)
[error] dotty.tools.dotc.parsing.Parser.parse$$anonfun$1(ParserPhase.scala:32)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:533)
[error] dotty.tools.dotc.parsing.Parser.parse(ParserPhase.scala:40)
[error] dotty.tools.dotc.parsing.Parser.$anonfun$2(ParserPhase.scala:52)
[error] scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:495)
[error] scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:599)
[error] scala.collection.immutable.List.prependedAll(List.scala:156)
[error] scala.collection.immutable.List$.from(List.scala:682)
[error] scala.collection.immutable.List$.from(List.scala:682)
[error] scala.collection.IterableOps$WithFilter.map(Iterable.scala:911)
[error] dotty.tools.dotc.parsing.Parser.runOn(ParserPhase.scala:51)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
[error] scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] dotty.tools.dotc.Run.showProgress(Run.scala:482)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:432)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:319)
[error] dotty.tools.dotc.Run.compile(Run.scala:304)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:196)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:252)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:166)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:166)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:214)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3(Incremental.scala:182)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$3$adapted(Incremental.scala:180)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:458)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:264)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:413)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:500)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:400)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:208)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:542)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:496)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:433)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2343)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2293)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:41)
[error] sbt.internal.io.Retry$.sbt$internal$io$Retry$$impl(Retry.scala:114)
[error] sbt.internal.io.Retry$.io(Retry.scala:102)
[error] sbt.internal.io.Retry$.io(Retry.scala:78)
[error] sbt.internal.io.Retry$.io(Retry.scala:67)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:41)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2291)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

### PR DESCRIPTION
**Pull request by warcholjakub**
Fixes #25456

```scala
def generate[F[_] = : {ApplicativeError[?], _root_.scala.Any}] =
  _root_.scala.Predef.???
```

```scala
val newSpan = t.span.withPoint(t.span.end).withEnd(in.lastOffset)
```

Trying to access `end` on `NoSpan` (span of `scalaAny`) caused an assert to fail:

```scala
def end: Int = {
    assert(exists, "end of NoSpan")
    ((coords >>> StartEndBits) & StartEndMask).toInt
  }
```

The fix was to add a guard against `NoSpan` in `contextBound`.

## How much have you relied on LLM-based tools in this contribution?

Minimally - to verify correctness of the solution.

## How was the solution tested?

Added `tests/neg/i25456.scala`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -2333,8 +2333,10 @@ object Parsers {
           in.nextToken()
           ident()
         else EmptyTermName
-      val newSpan = t.span.withPoint(t.span.end).withEnd(in.lastOffset)
-      ContextBoundTypeTree(t, pname, ownName).withSpan(newSpan)
+      val res = ContextBoundTypeTree(t, pname, ownName)
+      if t.span.exists then
+        res.withSpan(t.span.withPoint(t.span.end).withEnd(in.lastOffset))
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: If you choose, `res.withSpan(Span(t.span.start, end = in.lastOffset, point = t.span.end))`.

(Not sure if Scala 3 enforces invariants yet, but it was a Scala 2 issue that order matters.)

**Comment by som-snytt** [comment]
> Minimally - to verify correctness of the solution.

I almost said on the review that this is what LLM is not good at. (That is, verification.)

Apparently, I was distracted by the mechanics of constructing a span.

> ... removed the request for review from SolalPirelli

You know who would have asked about the other case.

**Comment by warcholjakub** [comment]
Yeah, that's my bad. I thought that with a change so minimal, one review would suffice and didn't want to bother more people.

**Comment by som-snytt** [comment]
No, totally my bad.
