### PR TITLE
WIP: Fix #11251

### LINKED ISSUE #11251: call of inline method of result of other inline method produce a tree with incorrect ownity, (crashed with -Ycheck:macros)
## Compiler version

Latest Dotty nightly build version: 3.0.0-RC1-bin-20210128-ce684de-NIGHTLY

## Minimized code

class X.scala

```Scala
package x

import scala.quoted._

class SL:

  inline def foo(inline step: Int => Int): SL =
     val f = step
     this

  def run1(): Unit = ???

  inline def run(): Unit =
    run1()


object X:

 inline def process[T](inline f:T) = ${
   processImpl[T]('f)
 }

 def processImpl[T:Type](t:Expr[T])(using Quotes):Expr[T] =
   import quotes.reflect._
   val checker = new TreeMap() {}
   checker.transformTerm(t.asTerm)(Symbol.spliceOwner)
   t
```

 Main.scala:
```
package x

object Main {

 def main(args:Array[String]):Unit =
    val sl = new SL()
    X.process(
      sl.foo(x=>x+1).run()
    )

}

```

compile  with -Ycheck:macros flag  (flag is essential)

## Output (click arrow to expand)
<details>

```scala
Latest Dotty nightly build version: 3.0.0-RC1-bin-20210128-ce684de-NIGHTLY
[info] loading settings for project root from build.sbt ...
[info] set current project to test (in build file:/Users/rssh/tests/dotty/crash-yycheck-macros-light/)
[info] compiling 2 Scala sources to /Users/rssh/tests/dotty/crash-yycheck-macros-light/target/scala-3.0.0-RC1/classes ..
[error] -- Error: /Users/rssh/tests/dotty/crash-yycheck-macros-light/src/main/scala/x/Main.scala:8:13 
[error] 8 |    X.process(
[error]    |    ^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: Tree had an unexpected owner for val f
[error]    |Expected: val SL_this (x.Main$._$_$SL_this)
[error]    |But was: val macro (x.Main$._$macro)
[error]    |
[error]    |
[error]    |The code of the definition of val f is
[error]    |val f: scala.Function1[scala.Int, scala.Int] = ((x: scala.Int) => x.+(1))
[error]    |
[error]    |which was found in the code
[error]    |({
[error]    |  val f: scala.Function1[scala.Int, scala.Int] = ((x: scala.Int) => x.+(1))
[error]    |  SL_this
[error]    |}: x.SL)
[error]    |
[error]    |which has the AST representation
[error]    |Inlined(Some(Apply(Select(Ident("sl"), "foo"), List(Block(List(DefDef("$anonfun", List(TermParamClause(List(ValDef("x", Inferred(), None)))), Inferred(), Some(Apply(Select(Ident("x"), "+"), List(Literal(IntConstant(1))))))), Closure(Ident("$anonfun"), None))))), Nil, Typed(Block(List(ValDef("f", Inferred(), Some(Inlined(None, Nil, Block(List(DefDef("$anonfun", List(TermParamClause(List(ValDef("x", Inferred(), None)))), Inferred(), Some(Apply(Select(Ident("x"), "+"), List(Literal(IntConstant(1))))))), Closure(Ident("$anonfun"), None)))))), Inlined(None, Nil, Ident("SL_this"))), TypeIdent("SL")))
[error]    |
[error]    |
[error]    |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$$anon$9.traverse(QuotesImpl.scala:2823)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1563)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1563)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1436)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1438)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1471)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1564)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$$anon$9.traverse(QuotesImpl.scala:2826)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1563)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1563)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1465)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1442)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1564)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$$anon$9.traverse(QuotesImpl.scala:2826)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1563)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1563)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1491)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1564)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$$anon$9.traverse(QuotesImpl.scala:2826)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$.yCheckOwners(QuotesImpl.scala:2827)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$yCheckedOwners(QuotesImpl.scala:2789)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$ValDef$.copy(QuotesImpl.scala:294)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$ValDef$.copy(QuotesImpl.scala:293)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformStatement(Quotes.scala:4266)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformStatement$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformStatement(X.scala:25)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTree(Quotes.scala:4240)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTree$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformTree(X.scala:25)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTrees$$anonfun$1(Quotes.scala:4370)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTrees(Quotes.scala:4370)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTrees$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformTrees(X.scala:25)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformSubTrees(Quotes.scala:4385)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformSubTrees$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformSubTrees(X.scala:25)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTerm(Quotes.scala:4327)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTerm$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformTerm(X.scala:25)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTerm(Quotes.scala:4311)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTerm$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformTerm(X.scala:25)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTerm(Quotes.scala:4327)
[error]    |	at scala.quoted.Quotes$reflectModule$TreeMap.transformTerm$(Quotes.scala:4229)
[error]    |	at x.X$$anon$1.transformTerm(X.scala:25)
[error]    |	at x.X$.processImpl(X.scala:26)
[error]    |
[error]    | This location contains code that was inlined from Main.scala:8
[error] 9 |      sl.foo(x=>x+1).run()
[error] 10 |    )
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
</details>

### PR DESCRIPTION
**Pull request by rssh**
Fixes #11251 
   --  add changing ownity when generating ValDef for this proxy. (which can be a result of generated inline), see commit

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -2457,6 +2459,7 @@ object SymDenotations {
       !owner.isClass
       || owner.isRefinementClass
       || owner.is(Scala2x)
+      || denot.is(Synthetic)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:2462]: I don't see how this can be justified. Incremental compilation might have defined a synthetic in run 1 and then stopped defining the synthetic in run 2. So the synthetic is no longer valid (does not exist).

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 2]
```diff
@@ -501,7 +501,7 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
           ref(rhsClsSym.sourceModule)
         else
           inlineCallPrefix
-      val binding = ValDef(selfSym.asTerm, rhs).withSpan(selfSym.span).setDefTree
+      val binding = ValDef(selfSym.asTerm, rhs.changeOwner(ctx.owner,selfSym)).withSpan(selfSym.span).setDefTree
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:504]: This looks dangerous from a compilation-speed perspective. The invariant to keep is that the owners of definition inside the ValDef of symbol `x` must be either `x`, or one of `x`'s owners up to and including the method containing `x`. `changeOwner` is expensive since it does a full tree-traversal and it inspects every type in that tree. so we should do this only if it is absolutely necessary. 

One idea would be to do a changeOwner only if `!ctx.owner.isContainedIn(selfSym.enclosingMethodOrClass)`.

**Comment by odersky** [comment]
@rssh I edited the comment so that the issues are automatically linked. It used to work when issues were mentioned in the title  but doesn't anymore.

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 2 above)
Comment (rssh) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:504]: Currently  -Y"check:macros" check more strict invariant:  that inside definition symbol should have the owner as nearest enclosing declaration:
 https://github.com/lampepfl/dotty/blob/a63b1d114179d79be32a1ee6552fc160c1bb2410/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L2804

 Maybe we should change this check, to keep a set of 'allowed owners'  in check traverse. 
On the other side, moving block of code from one method to another (as we do during inlining), requires changing owner, and with 'less strict invariant'  in any case full traverse will be needed (because we don't know - what in this tree).   With more strict (which enforced by current yCheck) - changeOwner can omit subtrees of low-level definitions since they already have correct owners.

 Don't know, what policy is better.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:504]: Yes, quite possibly. I let @nicolasstucki comment on that.

File: compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala [hunk 3]
```diff
@@ -28,6 +28,8 @@ class BootstrappedOnlyCompilationTests {
       compileFilesInDir("tests/pos-macros", defaultOptions),
       compileFilesInDir("tests/pos-custom-args/semanticdb", defaultOptions.and("-Xsemanticdb")),
       compileDir("tests/pos-special/i7592", defaultOptions.and("-Yretain-trees")),
+      compileDir("tests/pos-special/i11251", defaultOptions.and("-Ycheck:macros")),
```
Comment (nicolasstucki) [inline compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala:31]: You should be able to out these tests in `tests/pos-macros`. `Ycheck` is already enabled there.

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:504]: We have `QuoteUtils.changeOwnerOfTree` for this purpose. This variant checks if the tree has an owner that needs to be changed.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:504]: Can we reproduce the failure without macros (only inline)? If not, this might be the wrong place to change the owner of that tree. It might also be an issue with the owners in the `TreeMap` or one of the methods the treemap calls.

File: compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala (hunk 3 above)
Comment (rssh) [reply compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala:31]: Hmm, interesting,  when I move i11331. to pos-macros. -- tests passed.  when moving to pos-special and compile this dir i11331 in separate steps - the test failed. 
(the result of the check depends on the number of files in the compilation?)

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 1 above)
Comment (rssh) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala:2462]: fully this should be:
```
(denot.is(Synthetic) && denot.is(ModuleClass) && stillValidInOwner(denot.companionClass))
```
this will cath our case and stillValidInOwner(denot.companionClass)  will sure that companiounClass exists.

(will move to a separate patch now,  since it's more simple than ownity).

**Comment by rssh** [comment]
// test is currently broken because #1400 not here,  will be fixed automatically after one will be merged in this branch (I guess the right way will be from master).

**Comment by rssh** [comment]
(hmm, looks like something fixed this).

**Comment by rssh** [comment]
Can confirm that this was fixed by commit 3f1e20a13efc08e581e47682d75a5283751763e6  from #9984

  (altouch I guess having this test-cases among regression tests will be useful, so move test to posExpr here)

File: compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala (hunk 3 above)
Comment (rssh) [reply compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala]: moved i11251 to pos-macros

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 2 above)
Comment (rssh) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: But yCheckOwner is defined in QuoteImpl,  so it will not be called without macros.
Note, that currently macros not change anything and used only to call yCheckOwner to tree.
(I can move yCheckOwner  be a separate check between phases and look).

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 1 above)
Comment (rssh) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: (now in #11400 )

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
@rssh could you squash and rebase your commits?

**Comment by rssh** [comment]
> @rssh could you squash and rebase your commits?

done

**Review by nicolasstucki — APPROVED** [review]
