### PR TITLE
Issue "positional after named argument" errors

### LINKED ISSUE #18122: Unnamed parameters after named ones
## Compiler version

3.3.2-RC1-bin-20230630-c629090-NIGHTLY and before

## Minimized code

The following snippet contains multiple cases obtained by uncommenting one of the commented lines at a time.

```scala
object Test {
  def foo1(x: Int, y: Int, z: Int) = println((x, y, z))
  def foo2(x: Int = 0, y: Int, z: Int) = println((x, y, z))
  def bar1(x: Int, ys: Int*) = println((x, ys))
  def bar2(x: Int = 0, ys: Int*) = println((x, ys))

  def main(args: Array[String]) = {
    // foo1(1, y = 2, 3)
    // foo2(1, y = 2, 3)
    // foo1(y = 1, 2, x = 3)
    // foo2(y = 1, 2, x = 3)
    // foo1(y = 1, 2, z = 3)
    // foo2(y = 1, 2, z = 3)
    // foo1(y = 1, 2)
    // foo2(y = 1, 2)

    // bar1()
    // bar2()
    // bar1(1)
    // bar2(1)
    // bar1(x = 1)
    // bar2(x = 1)
    // bar1(ys = 1)
    // bar2(ys = 1)
    // bar1(1, 2)
    // bar2(1, 2)
    // bar1(1, ys = 2)
    // bar2(1, ys = 2)
    // bar1(x = 1, 2)
    // bar2(x = 1, 2)
    // bar1(x = 1, ys = 2)
    // bar2(x = 1, ys = 2)
    // bar1(ys = 1, x = 2)
    // bar2(ys = 1, x = 2)
    // bar1(1, 2, 3)
    // bar2(1, 2, 3)
    // bar1(1, ys = 2, 3)
    // bar2(1, ys = 2, 3)
    // bar1(x = 1, 2, 3)
    // bar2(x = 1, 2, 3)
    // bar1(x = 1, ys = 2, 3)
    // bar2(x = 1, ys = 2, 3)
    // bar1(x = 1, 2, ys = 3)
    // bar2(x = 1, 2, ys = 3)
    // bar1(ys = 1, 2, x = 3)
    // bar2(ys = 1, 2, x = 3)
  }
}
```

## Output

| code                  | scala 3.nightly    | scala 2.13.11                                                   |
|-----------------------|--------------------|-----------------------------------------------------------------|
| foo1(1, y = 2, 3)     | (1,2,3)            | (1,2,3)                                                         |
| foo2(1, y = 2, 3)     | (1,2,3)            | (1,2,3)                                                         |
| foo1(y = 1, 2, x = 3) | (3,1,2)            | positional after named                                          |
| foo2(y = 1, 2, x = 3) | (3,1,2)            | positional after named                                          |
| foo1(y = 1, 2, z = 3) | missing argument x | positional after named                                          |
| foo2(y = 1, 2, z = 3) | too many arguments | positional after named                                          |
| foo1(y = 1, 2)        | missing argument x | positional after named, missing arguments x, z |
| foo2(y = 1, 2)        | (0,1,2)            | positional after named, missing argument z    |

| code                | scala 3.nightly    | scala 2.13.11                                        |
|---------------------|--------------------|------------------------------------------------------|
| bar1()              | missing argument x | missing arguments x, ys                              |
| bar2()              | (0,ArraySeq())     | def bar2 not compiling; missing argument ys          |
| bar1(1)             | (1,ArraySeq())     | (1,List())                                           |
| bar2(1)             | (1,ArraySeq())     | def bar2 not compiling                               |
| bar1(x = 1)         | (1,ArraySeq())     | (1,List())                                           |
| bar2(x = 1)         | (1,ArraySeq())     | def bar2 not compiling                               |
| bar1(ys = 1)        | missing argument x | vararg required exactly once                         |
| bar2(ys = 1)        | (0,ArraySeq(1))    | def bar2 not compiling; vararg required exactly once |
| bar1(1, 2)          | (1,ArraySeq(2))    | (1,ArraySeq(2))                                      |
| bar2(1, 2)          | (1,ArraySeq(2))    | def bar2 not compiling                               |
| bar1(1, ys = 2)     | (1,ArraySeq(2))    | (1,ArraySeq(2))                                      |
| bar2(1, ys = 2)     | (1,ArraySeq(2))    | def bar2 not compiling                               |
| bar1(x = 1, 2)      | (1,ArraySeq(2))    | (1,ArraySeq(2))                                      |
| bar2(x = 1, 2)      | (1,ArraySeq(2))    | def bar2 not compiling                               |
| bar1(x = 1, ys = 2) | (1,ArraySeq(2))    | (1,ArraySeq(2))                                      |
| bar2(x = 1, ys = 2) | (1,ArraySeq(2))    | def bar2 not compiling                               |
| bar1(ys = 1, x = 2) | (2,ArraySeq(1))    | (2,List(1))                                          |
| bar2(ys = 1, x = 2) | (2,ArraySeq(1))    | def bar2 not compiling                               |
| bar1(1, 2, 3)          | (1,ArraySeq(2, 3)) | (1,ArraySeq(2, 3))                             |
| bar2(1, 2, 3)          | (1,ArraySeq(2, 3)) | def bar2 not compiling                         |
| bar1(1, ys = 2, 3)     | (1,ArraySeq(2, 3)) | (1,ArraySeq(2, 3))                             |
| bar2(1, ys = 2, 3)     | (1,ArraySeq(2, 3)) | def bar2 not compiling                         |
| bar1(x = 1, 2, 3)      | (1,ArraySeq(2, 3)) | (1,ArraySeq(2, 3))                             |
| bar2(x = 1, 2, 3)      | (1,ArraySeq(2, 3)) | def bar2 not compiling                         |
| bar1(x = 1, ys = 2, 3) | (1,ArraySeq(2, 3)) | (1,ArraySeq(2, 3))                             |
| bar2(x = 1, ys = 2, 3) | (1,ArraySeq(2, 3)) | def bar2 not compiling                         |
| bar1(x = 1, 2, ys = 3) | (1,ArraySeq(3, 2)) | ys already specified                           |
| bar2(x = 1, 2, ys = 3) | (1,ArraySeq(3, 2)) | def bar2 not compiling; ys already specified   |
| bar1(ys = 2, 3) | missing argument x | positional after named   |
| bar2(ys = 2, 3) | (0,ArraySeq(2, 3)) | def bar2 not compiling; positional after named  |
| bar1(ys = 1, 2, x = 3) | (3,ArraySeq(1, 2)) | positional after named                         |
| bar2(ys = 1, 2, x = 3) | (3,ArraySeq(1, 2)) | def bar2 not compiling; positional after named |

Abbreviated error messages explained:
* `positional after named` - `positional after named argument` (scala 2)
* `too many arguments` - `too many arguments for method ...`
* `missing argument x` - `missing argument for parameter x of method ...` (scala 3),  `not enough arguments for method ... Unspecified value parameter x` (scala 2)
* `def bar2 not compiling` - ``a parameter section with a `*`-parameter is not allowed to have default arguments`` (scala 2)
* `vararg required exactly once` - `when using named arguments, the vararg parameter has to be specified exactly once`

## Expectation

* IMO scala 2 is right to disallow using unnamed arguments after named ones - otherwise it's quite unclear whether such an argument fills the first missing parameter slot (which I would personally assume, given that such usage is not disallowed completely) or the slot following the previous named parameter (which seems to be the case in scala 3, taking e.g. the behaviour of `foo1(y = 1, 2, x = 3)` into account)
* Given that a user knows the current behaviour of the compiler for separate named and unnamed arguments in scala 3, the behaviour for varargs might seem consistent in some way, but otherwise it's also rather surprising. My personal first guess about named vararg argument was that I should pass a sequence like `ys = Seq(2, 3)` instead of `ys = 2, 3`, but this doesn't work. Should any of these syntaxes be legal at all? Especially the results for `bar2(ys = 2, 3)` and `bar2(x = 1, 2, ys = 3)` seem very confusing to me
* The error messages for `foo1(y = 1, 2, z = 3)`, `foo2(y = 1, 2, z = 3)`, `foo1(y = 1, 2)` and `bar1(ys = 2, 3)` should be improved - currently it's not clear if the fix would be to add a name to an unnamed argument or to add another (possibly unnamed) argument

### PR DESCRIPTION
**Pull request by odersky**
Issue "positional after named argument" errors if a positional argument follows a named argument and one of the following is true:

 - There is a formal argument before the argument position that has not yet been instantiated with a previous actual argument, (either named or positional), or
 - The formal parameter at the argument position is also mentioned in a subsequent named parameter.

This brings the behavior largely in line with Scala 2.

Fixes #18122

### CODE REVIEW

File: tests/neg/i18122.scala [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    bar1(x = 1, 2, 3)
+    bar2(x = 1, 2, 3)
+    bar1(x = 1, ys = 2, 3)
+    bar2(x = 1, ys = 2, 3)
+    bar1(x = 1, 2, ys = 3)  // error: positional after named
+    bar1(1, 2, ys = 3)      // error: parameter ys is already instantiated
+    bar2(x = 1, 2, ys = 3)  // error: positional after named
+    bar1(ys = 1, 2, x = 3)  // error: positional after named
+    bar2(ys = 1, 2, x = 3)  // error: positional after named
+  }
```
Comment (som-snytt) [inline tests/neg/i18122.scala:48]: `bar2(x = 1, ys = 2, ys = 3)`? probably `parameter ys is already instantiated`.

`bar2(x = 1, 2, ys = 3)  // error: positional after named` on L45 is slightly confusing message.

I expect that if named args do not change ordering, then it's always OK.

I see the rule that's being enforced is that `ys` always names the start of the repeated param. Then the positional arg `2` is unknown detritus.

Comment (odersky) [reply tests/neg/i18122.scala:48]: All true, but positional after named is technically correct, and it would be messy to change the logic to emit a different error message. Keeping logic clean in the compiler is an underestimated good. Lose it and you enter quickly a downward slide where in the end nobody understands the code anymore.

**Review by prolativ — APPROVED** [review]

**Comment by prolativ** [comment]
@som-snytt any further objections or can we get this merged?

**Comment by som-snytt** [comment]
LGTM! I especially appreciate

> Keeping logic clean in the compiler is an underestimated good.

It's easy to go overboard, and the voice of experience is also an underestimated good.

I haven't looked at Scala 2 messaging yet, which I will do in light of:

> I see the rule that's being enforced is that ys always names the start of the repeated param.

**Comment by WojciechMazur** [comment]
There are 3 OpenCB projects which are now failing after this change, but I would not say it's an regression, but rather an improvement.

| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| carlos-verdes/zio-arangodb | 0.3.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/6053540629/job/16435016112) |  |
| fabiopinheiro/scala-did | 0.1.0-M9 -> 0.1.0-M10 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/6053540629/job/16433964262) |  |
| greenfossil/data-mapping | 1.0.5 -> 1.0.7 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/6053525493/job/16429271852) |  | 

My question is, @Kordyjan  should we backport this change to Scala 3.3.x? 
One example of weakly-defined behaviours possibly leading to bugs before this change was: 
```
case class Foo(a: Int, b: Long, c: Int){
  def x = copy(b = 0L, 0) // is the second param targetting `a` or `c`?
}
```

**Comment by som-snytt** [comment]
The previous (interesting) expectation was that a named arg "resets" the position, such that defaults to the left of that position are supplied. (Such as on zio-arangodb.)
```
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 20.0.1).
Type in expressions for evaluation. Or try :help.

scala> def f(x: Int, y: Int = 42, z: Int, a: Int) = List(x,y,z,a).sum
def f(x: Int, y: Int, z: Int, a: Int): Int

scala> f(1, z=3, 4)
                 ^
       error: positional after named argument.
        ^
       error: not enough arguments for method f: (x: Int, y: Int, z: Int, a: Int): Int.
       Unspecified value parameter a.
```
which on 3.3.0
```
Welcome to Scala 3.3.0 (20.0.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> def f(x: Int, y: Int = 42, z: Int, a: Int) = List(x,y,z,a).sum
def f(x: Int, y: Int, z: Int, a: Int): Int

scala> f(1, z=3, 4)
val res0: Int = 50
```
my dotty just finished compiling, so for completeness
```
scala> f(1, z=3, 4)
-- Error: --------------------------------------------------------------------------------------------------------------
1 |f(1, z=3, 4)
  |          ^
  |          positional after named argument
1 error found
```
The wrong expectation is not terrible, because visually you align the named arg with the signature. It feels like a feature, because otherwise default args are convenient only in trailing position.

The case class copy example is deceptive because there is no signature to look at besides the class parameters. (You don't see the defaults, in other words.)

The argument for backporting is that it's never too early to correct a mistaken expectation.
