### PR TITLE
Fix #3273: Extend cooking to parent types

### LINKED ISSUE #3273: Dotty gets confused by raw types in bytecode signatures
Consider the following file `Test.scala`:
```scala
import org.testng.IAnnotationTransformer
import org.testng.annotations.ITestAnnotation
import java.lang.reflect.Method
import java.lang.reflect.Constructor

class SingleTestAnnotationTransformer(testName: String) extends IAnnotationTransformer {
  override def transform( annotation: ITestAnnotation, testClass: java.lang.Class[_], testConstructor: Constructor[_], testMethod: Method): Unit = {}
}
```
Running
```
./bin/dotc -classpath "$(coursier fetch -p org.testng:testng:6.8.7)" Test.scala 
```
produces the following error:
```scala
-- [E036] Reference Error: Test.scala:9:15 -------------------------
9 |  override def transform( annotation: ITestAnnotation, testClass: java.lang.Class[_], testConstructor: Constructor[_], testMethod: Method): Unit = {
  |               ^
  |               method transform overrides nothing
```

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

File: tests/pos/i3273/client_2.scala [hunk 1]
```diff
@@ -0,0 +1,5 @@
+class Client {
+  val a = (_: Bar_1.A[AnyRef]).foo()
+  val b = (_: Bar_1.B[AnyRef]).bar()
+  def test(x: Bar_1.A[AnyRef]): Bar_1.B[_] = x
+}
```
Comment (retronym) [inline tests/pos/i3273/client_2.scala]: It would be good to test these cases under joint compilation, too (usually changes to classfile parser need to be mirrored in `JavaParsers`)

**Comment by retronym** [comment]
I'm guessing some more work will be needed to deal with raw types in type parameter bound position.

**Comment by smarter** [comment]
From the last commit message:
> if we compile Java files from sources we should demand that raw types are re-written as wildcard types.

Unfortunately this isn't always easy, because of `.class` and `.getClass`: `List.class` will return a `Class<? extends List>` and you cannot directly cast this to a `Class<List<?>>`, an intermediate cast is necessary:
```java
(Class<List<?>>) (Class<?>) List.class
```

Something like this was necessary to compile the strawman: https://github.com/lampepfl/dotty/issues/3028

**Comment by smarter** [comment]
Of course, it's possible that the 13 years old bug report on this issue will be fixed one day: https://bugs.openjdk.java.net/browse/JDK-6184881 :)

**Comment by odersky** [comment]
I have decided that as far as I am concerned I won't spend anymore cycles on this. If somebody really wants to use raw types in jointly compiled Java code, asking them to do the rewrite is justified even if it might be difficult.
