### PR TITLE
Fix #11885: Always clone trees if position already set 

### LINKED ISSUE #11885: IdempotencyTests is flaky on Windows
Starting ~~with the merge of https://github.com/lampepfl/dotty/pull/11210~~ (EDIT: actually long before that, see comments below), it looks like test_windows_full has been failing IdempotencyTests from time to time, from https://github.com/lampepfl/dotty/runs/2178741539:
```scala
Test 'CheckPosIdempotency from idempotency/check' failed with output:           
Idempotency test failed between out\idempotency\posIdempotency1\pos\i6507b\Test.tasty and out\idempotency\posIdempotency2\pos\i6507b\Test.tasty
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:40)
	at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
Caused by: java.lang.AssertionError: assertion failed: Failed 1 idempotency checks (out of 5116)
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at IdempotencyCheck$.checkIdempotency(IdempotencyCheck.scala:70)
	at Test$.main(CheckPosIdempotency.scala:4)
	at Test.main(CheckPosIdempotency.scala)
	... 6 more
```
@bishabosha could you investigate this (I've forwarded you the access information for the Windows machine if you want to investigate there)? /cc @liufengyun

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #11885: Always clone trees if position already set

The cause of the problem is that we use parallelism in Pickler:

      if !Pickler.ParallelPickling || ctx.settings.YtestPickler.value then force()

Sometimes on Windows, the futures run a little slower, and the later
phase `Inlining` can change the positions of the trees to be pickled,
thus non-determinism.

For the Dotty project, the statistics is as follows:

- Before: ntrees = 5331539
- After:  ntrees = 5334075

Performance-wise, this should be better than synchronizing the pickling tasks.

[test_windows_full]

### CODE REVIEW

**Review by smarter — CHANGES_REQUESTED** [review]
We should fix the non-determinism problem rather than working around it in the tests because we really want the compiler output to be idempotent to make builds reproducible: https://github.com/scala/scala-dev/issues/405

File: compiler/src/dotty/tools/dotc/CompilationUnit.scala [hunk 1]
```diff
@@ -85,6 +85,18 @@ class CompilationUnit protected (val source: SourceFile) {
   def assignmentSpans(using Context): Map[Int, List[Span]] =
     if myAssignmentSpans == null then myAssignmentSpans = Nullables.assignmentSpans
     myAssignmentSpans
+
+  /** Force pickling at end of Pickler phase for determinism
+   *
+   *  On Windows we observe non-deterministic failure for the
+   *  idempotency test tests/pos/i6507b.scala. The cause of the
+   *  non-determinism is that the positions of the to be pickled
+   *  trees might change in a later phase `Inlining` after pickling.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/CompilationUnit.scala:94]: @nicolasstucki Could Inlining avoid changing tree positions? Otherwise we could copy the tree first, this should still be more efficient than forcing pickling early.

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/CompilationUnit.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/CompilationUnit.scala:94]: Inlining is not supposed to change positions, `Inlined` nodes are supposed to have the same position as the original tree. Could be a bug setting the positions or maybe it is constant folding that removes some positions.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/CompilationUnit.scala:94]: Even if we fix the bug in `inlining`, it's so easy to re-introduce the bug in the future.

Or, we add an assertion in `def span_=` to check that spans are only set once. It seems to be a reasonable invariant.

**Comment by liufengyun** [comment]
As an update, I've changed the fix to always clone if the position is not empty.

For the Dotty project, the statistics is as follows:

- Before: ntrees = 5331539
- After: ntrees = 5334075

Performance-wise, this should be better than synchronizing the pickling tasks.

**Comment by smarter** [comment]
Since we're currently tracking a performance regression (https://github.com/lampepfl/dotty/pull/12153#issuecomment-824011111, https://github.com/lampepfl/dotty/pull/12229), I'd like to wait until we've fixed it before investigating the potential performance impact of this PR

**Comment by smarter** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/ast/Positioned.scala [hunk 2]
```diff
@@ -68,7 +68,9 @@ abstract class Positioned(implicit @constructorOnly src: SourceFile) extends Src
         if (mySpan.isSynthetic) {
           if (!mySpan.exists && span.exists)
             envelope(source, span.startPos) // fill in children spans
-          this
+            this
+          else
+            cloneIn(source)
         }
         else cloneIn(source)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Positioned.scala:75]: I think this can be simplified to:
```scala
        if !mySpan.exists then
          if span.exists then envelope(source, span.startPos) // fill in children spans
          this
        else
          cloneIn(source)
```

**Review by smarter — APPROVED** [review]
The filtering of i6507b.scala in IdempotencyTests.scala should be removed too, otherwise LGTM.

**Comment by liufengyun** [comment]
retest performance please
