### PR TITLE
Fix #6679: Handle wildcards in PCP check

### LINKED ISSUE #6679: Discarding part of .unsealed Expr inside .seal breaks TreeUnpickler
```scala
import quoted._
import tasty._

def makeMatch[A,T](a : Type[A], b : Type[T], head : Expr[_], parts : List[(Expr[_],Expr[_])])(implicit reflection : Reflection) : Expr[T] = {
  implicit val e1 = a
  implicit val e2 = b
  import reflection._
  Match(
    head.asInstanceOf[Expr[A]].unseal,
    parts.map({
      case (l,r) => {
        val sacrifice = '{
          ${ head.asInstanceOf[Expr[A]] } match {
            case x if x == ${ l.asInstanceOf[Expr[A]] } => ${ r.asInstanceOf[Expr[T]] }
          }
        }
        sacrifice.unseal match {
          case IsInlined(inl) => inl.body match {
            case IsMatch(m) => m.cases.head
          }
        }
      }
    })).seal.cast[T]
}

def mm(implicit reflection : Reflection) =
  makeMatch[Int,Boolean]('[Int],'[Boolean],'{42},List('{1}->'{true},'{2}->'{false},'{42}->'{true}))

inline def f = ${ mm }
```

Trying to call `f` will crash with a ClassCastException, suggesting that this code is causing some kind of misalignment wrt. holes in the tasty. It seems something is assuming some overly strong invariants about where the parts of a `.unseal`ed expression can end up.

Removing the call to `.unseal` will remove the error, no matter how the result of that call is (or isn't) used.

```
scala> f
1 |f
  |^
  |An exception occurred while executing macro expansion
  |class scala.internal.quoted.TaggedType cannot be cast to class scala.quoted.Expr
```

## Advice?

The root of the issue is that I can't generate match expressions with a variable number of cases using quotes, so I had to resort to `tasty.Reflection`. `tasty.Reflection` on the other hand doesn't seem to be able to generate the appropriate name bindings/patterns, so I have to "steal" the appropriate AST fragments from a quoted Expr.

Is there a better way to do this? Any workaround suggestions?

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: tests/run-macros/i6679/Macro_1.scala [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import scala.quoted._
+
+def makeMatch[A: Type](head : Expr[A]) given (qctx : QuoteContext) : Expr[Unit] = {
+  import qctx.tasty._
+
+  val sacrifice = '{ $head match { case _ => ??? } }
+  sacrifice.unseal
+
+  '{ println("Ok") }
```
Comment (liufengyun) [inline tests/run-macros/i6679/Macro_1.scala]: put `sacrifice` inside the quote?

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 2]
```diff
@@ -98,10 +98,14 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
...
-          case _ => tree
+      case Ident(name) =>
+        if (name == nme.WILDCARD) {
+          untpd.Ident(name).withType(checkType(tree.sourcePos).apply(tree.tpe)).withSpan(tree.span)
+        } else {
+          checkSymLevel(tree.symbol, tree.tpe, tree.sourcePos) match {
+            case Some(tpRef) => tpRef
+            case _ => tree
+          }
         }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Nitpick: maybe remove the unnecessary curly brace.

File: tests/run-macros/i6679/Macro_1.scala (hunk 1 above)
Comment (nicolasstucki) [reply tests/run-macros/i6679/Macro_1.scala]: We already show that it can be pickled and unpickled. Putting it in a quote would not touch that code further.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: It looked off without them.
