### PR TITLE
Fix #5636: properly type param accessors in constructors

### LINKED ISSUE #5636: Path dependency on trait/class-parameters in class parent uses constructor argument instead of member
Using path-dependent types as type parameters fails. The following example 
```scala
class A
trait Bar[X] {
  // same for `val foo: X = ???`
  def foo: X = ???
}
// same for `class Foo(...)...`
trait Foo(val a: A) extends Bar[a.type] {
  val same: a.type = foo
}
```
gives a type error:
```
[error] required: A(Foo.this.a)
[error]     val same: a.type = foo
```

### PR DESCRIPTION
**Pull request by smarter**
Replace the condition as suggested in the comment, the referenced test
failures do not seem to happen anymore.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -300,13 +300,9 @@ class Typer extends Namer
                 if (isSelfDenot(defDenot)) curOwner.enclosingClass.thisType
                 else {
                   val effectiveOwner =
-                    if (curOwner.isTerm && defDenot.symbol.isType)
+                    if (curOwner.isTerm && defDenot.symbol.maybeOwner.isType)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: The following alternative check passes all tests too:
```suggestion
                    if (curOwner.isConstructor)
```
This looks more obviously correct to me, wdyt @odersky ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: No, I think `curOwner` could also be `localDummy`. `maybeOwner.isType` looks correct.
