### PR TITLE
A bunch of exhaustivity fixes

### LINKED ISSUE #6088: Pattern matching exhaustivity warnings on higher kinded types
Experimenting with higher-kinded recursion schemes and dotty, I got exhaustivity and unchecked type warnings with the attached code, and I can't make up my mind they are right or spurious 
```scala
  /** Natural transformation. */
  trait ~>[F[_], G[_]] {
    def apply[A](fa: F[A]): G[A]
  }

  /** Higher-kinded pattern functor typeclass. */
  trait HFunctor[H[f[_], i]] {
    def hmap[A[_], B[_]](nt: A ~> B): ([x] => H[A,x]) ~> ([x] => H[B,x]) 
  }

  /** Some HK pattern functor. */
  enum ExprF[R[_],I] {
    case Const[R[_]](i: Int) extends ExprF[R,Int]
    case Neg[R[_]](l: R[Int]) extends ExprF[R,Int]
    case Eq[R[_]](l: R[Int], r: R[Int]) extends ExprF[R,Boolean]
  }

  /** Companion. */
  object ExprF {
    implied hfunctor for HFunctor[ExprF] {
      def hmap[A[_], B[_]](nt: A ~> B): ([x] => ExprF[A,x]) ~> ([x] => ExprF[B,x]) = {
        new ~>[[x] => ExprF[A,x], [x] => ExprF[B,x]] {
          def apply[I](fa: ExprF[A,I]): ExprF[B,I] = fa match {
            case Const(i) => Const(i)
            case Neg(l) => Neg(nt(l))
            case Eq(l, r) => Eq(nt(l), nt(r))
          }
        }
      }
    } 
  }
```
```scala
[warn] -- [E029] Pattern Match Exhaustivity Warning: /fixpoint-dotty/src/main/scala/HK.scala:25:53 
[warn] 25 |          def apply[I](fa: ExprF[A,I]): ExprF[B,I] = fa match {
[warn]    |                                                     ^^
[warn]    |match may not be exhaustive.
[warn]    |
[warn]    |It would fail on pattern case: ExprF.Const(_), ExprF.Neg(_), ExprF.Eq(_, _)
[warn] -- Warning: /fixpoint-dotty/src/main/scala/HK.scala:26:17 
[warn] 26 |            case Const(i) => Const(i)
[warn]    |                 ^^^^^^^^
[warn]    |        the type test for HK.ExprF.Const[A] cannot be checked at runtime
[warn] -- Warning: /fixpoint-dotty/src/main/scala/HK.scala:27:17 
[warn] 27 |            case Neg(l) => Neg(nt(l))
[warn]    |                 ^^^^^^
[warn]    |          the type test for HK.ExprF.Neg[A] cannot be checked at runtime
[warn] -- Warning: /fixpoint-dotty/src/main/scala/HK.scala:28:17 
[warn] 28 |            case Eq(l, r) => Eq(nt(l), nt(r))
[warn]    |                 ^^^^^^^^
[warn]    |           the type test for HK.ExprF.Eq[A] cannot be checked at runtime
[warn] four warnings found
[info] Done compiling.
```

The enum is sealed and all cases are matched so the exhaustivity warning seems spurious. 

If the exhaustivity warning is due to the fact that `ExprF[_[_], _]` is a higher-kinded GADT, well it seems that incorrect uses of a natural transformation 
`A ~> B ` lifted to `[x] => ExprF[A, x]  ~> [x] => ExprF[B, x]` using `ExprF.hfunctor`  will be caught anyway as demonstrated below: 
```scala
//a natural transformation from List to Option
val l2opt = new ~>[List, Option] {
    def apply[A](in: List[A]): Option[A] = {
      in match {
        case Nil => None
        case h :: _ => Some(h)
      }
    }
  }
// lifted to [x] => ExprF[List,x] ~> [x] => ExprF[Option,x]
val nt  = ExprF.hfunctor.hmap(l2opt)
// applied on a wrong ExprF value 
nt(ExprF.Neg(Set(12)))
```
```scala
[error] -- [E007] Type Mismatch Error: /fixpoint/fixpoint-dotty/src/main/scala/HK.scala:45:18 
[error] 45 |  nt(ExprF.Neg(Set(12)))
[error]    |               ^^^^^^^
[error]    |               Found:    Set[Int]
[error]    |               Required: List[Int]
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

So it seems to me that the pattern match is exhaustive and that unchecked warnings are kind of noisy as I see no way of providing wrong input to `nt` that would get uncaught by the type system beforehand.

Any how, dotty seems super nice for generic programming !

Attached is a fully working example of higher-kinded catamorphism, only issue are these warnings.

Best regards.

[HK.scala.gz](https://github.com/lampepfl/dotty/files/2962933/HK.scala.gz)

### LINKED ISSUE #9631: Recursion limit exceeded (F-bounded type and sealed pattern match)
## Minimized code

    git clone https://github.com/Sciss/DottyLucre.git
    cd DottyLucre
    git checkout dotty-issue-9626
    sbt compile

## Output (click arrow to expand)

crashes in either `SkipList` or `HASkipList` of the `data` module (crash doesn't indicate file or line number)

```
[info] exception occurred while compiling /home/hhrutz/Documents/devel/DottyLucre/data/src/main/scala/de/sciss/lucre/data/HASkipList.scala, /home/hhrutz/Documents/devel/DottyLucre/data/src/main/scala/de/sciss/lucre/data/Ordered.scala, /home/hhrutz/Documents/devel/DottyLucre/data/src/main/scala/de/sciss/lucre/data/Ordering.scala, /home/hhrutz/Documents/devel/DottyLucre/data/src/main/scala/de/sciss/lucre/data/SkipList.scala
Recursion limit exceeded.
Maybe there is an illegal cyclic reference?
If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
A recurring operation is (inner to outer):

  subtype LazyRef(ile / compileIncremental 1s
  de.sciss.lucre.stm.Txn[
    LazyRef(
      de.sciss.lucre.stm.Txn[
        LazyRef(
          de.sciss.lucre.stm.Txn[
```

Compiles fine under `++2.13.3`.

### LINKED ISSUE #9841: pat-map RecursionOverflow when F-bounded type parameter involved
## Minimized code

```Scala
trait Txn[T <: Txn[T]]

object Impl {
  sealed trait Entry[T <: Txn[T], A]
  case class EntrySingle[T <: Txn[T], A](term: Long, v: A)  extends Entry[T, A]
}

trait Impl[T <: Txn[T], K] {
  import Impl._

  def put[A](): Unit = {
    val opt: Option[Entry[T, A]] = ???
    
    opt match {
      case Some(EntrySingle(_, prevValue)) => ???   // crashes
      case _ =>
    }
  }
}
```

## Output

```scala
Recursion limit exceeded.
Maybe there is an illegal cyclic reference?
If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
A recurring operation is (inner to outer):

  subtype LazyRef(uent / Compile / compileIncremental 3s
  de.sciss.lucre.confluent.Txn[
    LazyRef(
      de.sciss.lucre.confluent.Txn[
        LazyRef(
          de.sciss.lucre.confluent.Txn[
            LazyRef(
```

## Expectation

Should work. Possibly related or the same underlying issue: #9631 , #9782

### PR DESCRIPTION
**Pull request by liufengyun**
- Fix #6088
- Fix #9631 
- Fix #9841 

Based on #9789

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 1]
```diff
@@ -721,37 +717,25 @@ object TypeOps:
...
     // If parent contains a reference to an abstract type, then we should
     // refine subtype checking to eliminate abstract types according to
     // variance. As this logic is only needed in exhaustivity check,
     // we manually patch subtyping check instead of changing TypeComparer.
-    // See tests/patmat/i3645b.scala
-    def parentQualify = tp1.widen.classSymbol.info.parents.exists { parent =>
-      inContext(ctx.fresh.setNewTyperState()) {
-        parent.argInfos.nonEmpty && minTypeMap.apply(parent) <:< maxTypeMap.apply(tp2)
-      }
+    // See tests/patmat/3645b.scala
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:733]: Accidental change? The file is still named `i3645b.scala`

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 2]
```diff
@@ -659,42 +659,38 @@ object TypeOps:
...
-          val exposed = expose(lo, hi)
-          typr.println(s"$tp exposed to =====> $exposed")
-          exposed
+        case tp: TypeRef if !tp.symbol.isClass =>
+          def lo = apply(tp.underlying.loBound)
+          def hi = apply(tp.underlying.hiBound)
+          boundTypeParams.getOrElseUpdate(tp, newTypeVar(TypeBounds(lo, hi)))
+
+        case AppliedType(tycon: TypeRef, _) if !tycon.dealias.typeSymbol.isClass =>
+          // Type inference cannot handle X[Y] <:< Int
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:686]: I'm confused by what is happening here:
- Could you describe in more details what the issue with type inference is here?
- Replacing a type lambda by its result type means that the type now contains references to binders which are not in scope, isn't that problematic?

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:733]: Yes, it's an accidental change.

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:686]: The issue here can be demonstrated by the example:

```Scala
    trait ModuleSig {
      type F[_]
      type U

      trait FooSig {
        type Type = F[U]
        def subst[F[_]](fa: F[Int]): F[Type]
      }

      val Foo: FooSig
    }
    val Module: ModuleSig = new ModuleSig {
      type F[A] = Int

      val Foo: FooSig = new FooSig {
        // type Type = Int
        def subst[F[_]](fa: F[Int]): F[Type] = fa
      }
    }
    type Foo = Module.Foo.Type

    sealed abstract class K[F]
    case object K1 extends K[Int]
    case object K2 extends K[Foo]

    val kv: K[Foo] = Module.Foo.subst[K](K1)
    def test(k: K[Foo]): Unit = k match {
      case K2 => ()
    }
```

We need to tell whether it's possible that `K1 <: K[Foo]`. If yes, we issue a warning; otherwise, no warnings.

- `K1 <: K[Foo]` is possible   <==> 
- `K[Int] <: K[Foo]` is possible   <==>
- `Int <: Foo` is possible   <==>
- `Int <: Module.Foo.Type` is possible

Standard subtyping does not answer whether it is _possible_` S <: T` given some instantiation of the type parameters. Therefore, we replace type parameters in `S` and `T` with tvars, and see if the subtyping is true.

In the example above (if we remove the special case), we will encounter the case `Int <: X[Y]`, where `X` and `Y` are tvars. The subtype checking will simply return false. But depending on the bounds of `X` and `Y`, the subtyping can be true.

As a workaround, we approximate higher-kinded type parameters with the value types that can be instantiated from its bounds.

> Replacing a type lambda by its result type means that the type now contains references to binders which are not in scope, isn't that problematic?

This is indeed a concern. I guess `instantiate` the `HKLambda` with its bounds is a more appropriate way to achieve that. The bounds could be F-Bounds again, we can make it recur for the possibility of F-bounds.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala]: Actually referencing the bound TypeParamRef in the HKTypeLambda here is fine, as TypeComparer will recurse on its bounds.

**Review by smarter — APPROVED** [review]
