### PR TITLE
Fix inconsistent `typeSize` calculation for `TupleN` vs recursive pair encodings

### LINKED ISSUE #24730: Different type sizes for TupleN vs nested pairs encoding
```scala
package dotty.tools.dotc.core

import dotty.tools.DottyTest
import dotty.tools.dotc.core.Symbols.defn
import dotty.tools.dotc.core.TypeOps

import org.junit.Test
import org.junit.Assert.assertEquals

class TypesTest extends DottyTest:

  @Test def tuple3TypeSize =
    val tpe = defn.TupleType(3).nn.appliedTo(List(defn.IntType, defn.BooleanType, defn.DoubleType))
    assertEquals(3, tpe.typeSize) // false,  tpe.typeSize == 1 🤔

  @Test def tuple3ConsTypeSize =
    val tpe = TypeOps.nestedPairs(List(defn.IntType, defn.BooleanType, defn.DoubleType))
    assertEquals(3, tpe.typeSize)
```

Shouldn't the size of a 3-tuple always be 3, whereas it is encoded with a `Tuple3` type application or with nested pairs?

### PR DESCRIPTION
**Pull request by Lluc24**
Currently, `typeSize` reports inconsistent values for standard tuple types (e.g., `(A, B)`) compared to their semantically equivalent recursive pair encodings (e.g., `A *: B *: EmptyTuple`).

This discrepancy arises because `TupleN` is represented as a flat `AppliedType`, whereas the nested encoding forms a deeper tree structure. As `typeSize` is often used as a heuristic for complexity or optimization limits, this inconsistency can lead to divergent behavior in the compiler depending on how a tuple is represented syntactically.

This PR modifies `TypeSizeAccumulator` to canonicalize `TupleN` types into their recursive `*:` representation before calculating their size. This ensures that the size metric is consistent regardless of whether the tuple is represented as a flat `AppliedType` or a nested structural type.

I have added a new unit test in `TypesTest` that asserts `Tuple3[Int, Boolean, Double]` and `Int *: Boolean *: Double *: EmptyTuple` both yield identical `typeSize` equal to 3.

Thanks to @mbovel for providing the unit test that effectively reproduces this issue and validates the fix.

Fixes #24730

### CODE REVIEW

**Comment by mbovel** [comment]
We could maybe use `normalizedTupleType` here: 

https://github.com/scala/scala3/blob/f67a1a0d91dc154b0f5e934a1b1e5e8cc5a508c1/compiler/src/dotty/tools/dotc/core/TypeUtils.scala#L148-L157

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -7124,7 +7124,15 @@ object Types extends TypeUtils {
...
+        case AppliedType(_, args) if defn.isTupleNType(tp) =>
+          args.foldRight(defn.EmptyTupleClass.typeRef: Type) { (elemType, acc) =>
+            defn.PairClass.typeRef.appliedTo(elemType, acc)
+          }
+        case _ => tp
+
+      canonicTp match {
         case tp: AppliedType =>
           val tpNorm = tp.tryNormalize
           if tpNorm.exists then apply(n, tpNorm)
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/core/Types.scala:7132]:
```suggestion
          val tpNorm = tp.normalized.normalizedTupleType
          if tpNorm ne tp then apply(n, tpNorm)
```

Comment (Lluc24) [reply compiler/src/dotty/tools/dotc/core/Types.scala:7132]: `normalizedTupleType` does the opposite of what we want. We need to convert `TupleN` to `*:` equivalent. I found this function in `TypeUtils.scala` that does exactly this:

https://github.com/scala/scala3/blob/c82b623d296cb2b4780018e152b7b69c4706a862/compiler/src/dotty/tools/dotc/core/TypeUtils.scala#L122-L126

Also note that `tp.normalized` on `TupleN` returns `NoType`.

Using this function, the code is cleaner and more readable:

```scala
def apply(n: Int, tp: Type): Int =
  tp match {
    case tp: AppliedType if defn.isTupleNType(tp) =>
      foldOver(n + 1, tp.toNestedPairs)
    // From here the following code is the same as the original
    case tp: AppliedType =>
      val tpNorm = tp.tryNormalize
      if tpNorm.exists then apply(n, tpNorm)
      else foldOver(n + 1, tp)
    ...
```

Comment (mbovel) [reply compiler/src/dotty/tools/dotc/core/Types.scala:7132]: > We need to convert `TupleN` to `*:` equivalent.

Why not do the opposite? `TupleN` needs less object allocations.

> Also note that `tp.normalized` on `TupleN` returns `NoType`.

Maybe the following would work?

```scala
  tp match {
    case tp: AppliedType =>
      val tpNorm = tp.tryNormalize
      if tpNorm.exists then apply(n, tpNorm.normalizedTupleType)
      else foldOver(n + 1, tp.normalizedTupleType)
```

The above has the advantage that it always normalizes the type, even when it's a tuple.

Comment (Lluc24) [reply compiler/src/dotty/tools/dotc/core/Types.scala:7132]: The motivation of this issue is that the concatenation type of two tuples is made by a Match Type. When a `TupleN` and another tuple were to be concatenated, the result type uses the `*:` equivalent. The resulting `typeSize` is larger and created a lot of false positives in the algorithm of PR #24661

Comment (mbovel) [reply compiler/src/dotty/tools/dotc/core/Types.scala:7132]: Yes, but from my understanding, the requirement is simply that both `TupleN` and nested `*:` pairs be normalized to the same representation. Does it matter whether `TupleN` is normalized to nested pairs, or vice versa? If we normalize to `TupleN`, then both types in the unit tests would have size `1`, wouldn't they?

Comment (mbovel) [reply compiler/src/dotty/tools/dotc/core/Types.scala:7132]: Well, I guess for your current implementation of match types termination checks, it's better if `(1, 2)` and `(1, 2, 3)` have sizes `2` and `3`.
