### PR TITLE
Fix #5144: Avoid Expr of method type

### LINKED ISSUE #5144: Error reifying reference to method
```scala
object Main {

  def eval1(x: scala.quoted.Expr[Int => Int]): Expr[Int] = ???

  def peval1(): scala.quoted.Expr[Unit] = '{
    def f(x: Int): Int = ~eval1('(f))
  }

}
```

fails with 
```scala
Exception in thread "main" java.lang.IllegalArgumentException: Could not find proxy for val f$1: scala.quoted.Expr in List(val f$1, method $anonfun$1, method peval1, module class Main$, module class <empty>, module class <root>), encl = method $anonfun$2, owners = method $anonfun$2, method peval1, object Main, package <empty>, package <root>; enclosures = method $anonfun$2, package <empty>, package <root>
        at dotty.tools.dotc.transform.LambdaLift$Lifter.searchIn$1(LambdaLift.scala:386)
        at dotty.tools.dotc.transform.LambdaLift$Lifter.proxy(LambdaLift.scala:399)
        at dotty.tools.dotc.transform.LambdaLift$Lifter.proxyRef(LambdaLift.scala:417)
        at dotty.tools.dotc.transform.LambdaLift.transformIdent(LambdaLift.scala:531)
        ...
```

At reify quotes `f` is suspicioucly lifted to an `Expr[(x: Int): Int]`

As noted by @benoitknuchel in https://github.com/benoitknuchel/Staged-Tagless-Interpreters-in-Dotty/blob/master/simplestagedinterpreter/src/main/scala/Main.scala

### PR DESCRIPTION
**Pull request by nicolasstucki**
Change the type of lifted method references to function types and
allow method references in Holes.

### CODE REVIEW

**Comment by smarter** [comment]
You could enforce this invariant by adding `assert(resType.isValueTypeOrWildcard, s"$resType")` in the constructor of `ExprType`, similarly to what is done in `OrType` and `AndType`.

File: tests/run-with-compiler/i5144.scala [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import scala.quoted._
+
+object Test {
+  implicit val toolbox: scala.quoted.Toolbox = scala.quoted.Toolbox.make
+
+  def eval1(ff: Expr[Int => Int]): Expr[Int] = '((~ff)(42))
+
+  def peval1(): Expr[Unit] = '{
+    def f(x: Int): Int = ~eval1('(f))
```
Comment (liufengyun) [inline tests/run-with-compiler/i5144.scala]: Just a curiosity: we do eta-expansion for methods when the expected type is a function, so that a method is always applied. In this case of quotes, it seems it breaks this invariant.

**Comment by nicolasstucki** [comment]
@smarter I dont see the relation with `ExprType`, these where generating types such as `scala.quoted.Expr[(x: Int): Int]`.

**Comment by smarter** [comment]
I see, so there's a typeapply where the argument is a methodtype? There could be an assertion to check for that too

**Comment by nicolasstucki** [comment]
Yes. I will add an assertion.

File: tests/run-with-compiler/i5144.scala (hunk 1 above)
Comment (nicolasstucki) [reply tests/run-with-compiler/i5144.scala]: It is unrelated with the eta-expansion. This is about lifting a tree that represents a reference to a method that is outside the quote. It could not come from eta-expansion the code above could be `def f(x: Int): Int = ~eval1('{ f(1); 2 })` where `f` also needs lifting.

**Comment by nicolasstucki** [comment]
The conditions for the assertion in `AppliedType` are more complex and may add unwanted overhead. Let's explore the invariants of the types and how to check them in a separate PR.
