### PR TITLE
Fix treatment of parameter selections via this in constructors.

### LINKED ISSUE #15723: The meaning of `this.field` in class body
## Compiler version

Scala 2 and Scala 3 (master)

## Minimized code

```Scala
class B(val y: Int):
  println(this.y)
  foo()
  def foo() = println(this.y)

class C(override val y: Int) extends B(10)

@main
def Test = new C(20)
```

## Output

```scala
10
20
```

## Expectation

I would expect `this.y` to have the same semantics both in the class body and method body.

It's up to discussion whether an unqualified `y` in class body and in method body should have the same semantics.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #15723

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Constructors.scala [hunk 1]
```diff
@@ -149,17 +149,21 @@ class Constructors extends MiniPhase with IdentityDenotTransformer { thisPhase =
...
-            // Variables need to go through the getter since they might have been updated,
-            // except if we are in a super call, since then the virtual getter call would
-            // be illegal.
-          then
+          def isOverridableSelect = tree.isInstanceOf[Select] && !sym.isEffectivelyFinal
+          def keepUnlessInSuperCall = sym.is(Mutable) || isOverridableSelect
+            // If true, switch to constructor parameters only in the super call.
+            // Variables need to go through the getter since they might have been updated.
+            // References via this need to use the getter as well as long as that getter
+            // can be overriddem. This is needed to handle overrides correctly. See run/i15723.scala.
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/transform/Constructors.scala:161]: typo overridden.

I understand the nice comment but not `keepUnlessInSupercall`, which means "keep accessor but you must also check inSuperCall". The double negative `!unless` is tricky. `def requiresParamSyms = inSuperCall || !sym.is(Mutable) && !isOverridableSelect` which just distributes the negation.

This PR still permits `class C(x: Int) { def f = this.x }` use of selection for parameter.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/Constructors.scala]: Good point. I turned the sense around.

**Review by liufengyun — APPROVED** [review]
LGTM
