### PR TITLE
Fix #4496: call ensureAccessible to bypass class-level accessibility

### LINKED ISSUE #4496: Incorrect treatment of structural type
<pre><font color="#3465A4">scala&gt; </font><font color="#C4A000">import</font> scala.reflect.<font color="#75507B">Selectable</font>.reflectiveSelectable 
<font color="#3465A4">scala&gt; </font>(<font color="#75507B">new</font> <font color="#75507B">Object</font> { <font color="#C4A000">val</font> <font color="#06989A">a</font>: <font color="#75507B">Int</font> = <font color="#CC0000">10</font>} : {<font color="#C4A000">val</font> <font color="#06989A">a</font>: <font color="#75507B">Int</font>}).a 
java.lang.<font color="#75507B">NoSuchFieldException:</font> a
	at java.lang.<font color="#75507B">Class</font>.getField(<font color="#75507B">Class</font>.java:<font color="#CC0000">1703</font>)
	at scala.reflect.<font color="#75507B">Selectable$</font>.selectDynamic$extension(<font color="#75507B">Selectable</font>.scala:<font color="#CC0000">7</font>)
	at scala.reflect.<font color="#75507B">Selectable</font>.selectDynamic(<font color="#75507B">Selectable</font>.scala:<font color="#CC0000">4</font>)
	at rs$line$13$.&lt;init&gt;(rs$line$13:<font color="#CC0000">1</font>)
	at rs$line$13$.&lt;clinit&gt;(rs$line$13)
	at rs$line$13.res9Show(rs$line$13)
	at sun.reflect.<font color="#75507B">NativeMethodAccessorImpl</font>.invoke0(<font color="#75507B">Native</font> <font color="#75507B">Method</font>)
	at sun.reflect.<font color="#75507B">NativeMethodAccessorImpl</font>.invoke(<font color="#75507B">NativeMethodAccessorImpl</font>.java:<font color="#CC0000">62</font>)
	at sun.reflect.<font color="#75507B">DelegatingMethodAccessorImpl</font>.invoke(<font color="#75507B">DelegatingMethodAccessorImpl</font>.java:<font color="#CC0000">43</font>)
	at java.lang.reflect.<font color="#75507B">Method</font>.invoke(<font color="#75507B">Method</font>.java:<font color="#CC0000">498</font>)
	at dotty.tools.repl.<font color="#75507B">Rendering</font>.valueOf(<font color="#75507B">Rendering</font>.scala:<font color="#CC0000">58</font>)
	at dotty.tools.repl.<font color="#75507B">Rendering</font>.renderVal(<font color="#75507B">Rendering</font>.scala:<font color="#CC0000">79</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayMembers$<font color="#CC0000">3</font>$$anonfun$<font color="#CC0000">3</font>(ReplDriver.scala:<font color="#CC0000">284</font>)
	at scala.collection.<font color="#75507B">TraversableLike</font>.$anonfun$map$<font color="#CC0000">1</font>(TraversableLike.scala:<font color="#CC0000">234</font>)
	at scala.collection.mutable.<font color="#75507B">ResizableArray</font>.foreach(<font color="#75507B">ResizableArray</font>.scala:<font color="#CC0000">59</font>)
	at scala.collection.mutable.<font color="#75507B">ResizableArray</font>.foreach$(<font color="#75507B">ResizableArray</font>.scala:<font color="#CC0000">52</font>)
	at scala.collection.mutable.<font color="#75507B">ArrayBuffer</font>.foreach(<font color="#75507B">ArrayBuffer</font>.scala:<font color="#CC0000">48</font>)
	at scala.collection.<font color="#75507B">TraversableLike</font>.map(<font color="#75507B">TraversableLike</font>.scala:<font color="#CC0000">234</font>)
	at scala.collection.<font color="#75507B">TraversableLike</font>.map$(<font color="#75507B">TraversableLike</font>.scala:<font color="#CC0000">227</font>)
	at scala.collection.<font color="#75507B">AbstractTraversable</font>.map(<font color="#75507B">Traversable</font>.scala:<font color="#CC0000">104</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayMembers$<font color="#CC0000">7</font>(ReplDriver.scala:<font color="#CC0000">284</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayDefinitions$$anonfun$<font color="#CC0000">3</font>$$anonfun$<font color="#CC0000">2</font>(ReplDriver.scala:<font color="#CC0000">311</font>)
	at scala.<font color="#75507B">Option</font>.map(<font color="#75507B">Option</font>.scala:<font color="#CC0000">146</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayDefinitions$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">311</font>)
	at dotty.tools.dotc.core.<font color="#75507B">Periods</font>.atPhase(<font color="#75507B">Periods</font>.scala:<font color="#CC0000">26</font>)
	at dotty.tools.dotc.core.<font color="#75507B">Phases</font>.atPhase(<font color="#75507B">Phases</font>.scala:<font color="#CC0000">36</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayDefinitions(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">316</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.compile$$anonfun$<font color="#CC0000">2</font>(ReplDriver.scala:<font color="#CC0000">241</font>)
	at scala.util.<font color="#75507B">Either</font>.fold(<font color="#75507B">Either</font>.scala:<font color="#CC0000">188</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.compile(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">242</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.interpret(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">202</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.loop$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">150</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.runUntilQuit$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">154</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.withRedirectedOutput$$anonfun$<font color="#CC0000">2</font>$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">163</font>)
	at scala.util.<font color="#75507B">DynamicVariable</font>.withValue(<font color="#75507B">DynamicVariable</font>.scala:<font color="#CC0000">58</font>)
	at scala.<font color="#75507B">Console$</font>.withErr(<font color="#75507B">Console</font>.scala:<font color="#CC0000">192</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.withRedirectedOutput$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">163</font>)
	at scala.util.<font color="#75507B">DynamicVariable</font>.withValue(<font color="#75507B">DynamicVariable</font>.scala:<font color="#CC0000">58</font>)
	at scala.<font color="#75507B">Console$</font>.withOut(<font color="#75507B">Console</font>.scala:<font color="#CC0000">163</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.withRedirectedOutput(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">163</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.runUntilQuit(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">154</font>)
	at dotty.tools.repl.<font color="#75507B">Main$</font>.main(<font color="#75507B">Main</font>.scala:<font color="#CC0000">6</font>)
	at dotty.tools.repl.<font color="#75507B">Main</font>.main(<font color="#75507B">Main</font>.scala)

<font color="#3465A4">scala&gt; </font>(<font color="#75507B">new</font> <font color="#75507B">Object</font> { <font color="#C4A000">def</font> <font color="#06989A">a</font>: <font color="#75507B">Int</font> = <font color="#CC0000">10</font>} : {<font color="#C4A000">def</font> <font color="#06989A">a</font>: <font color="#75507B">Int</font>}).a 
java.lang.<font color="#75507B">NoSuchFieldException:</font> a
	at java.lang.<font color="#75507B">Class</font>.getField(<font color="#75507B">Class</font>.java:<font color="#CC0000">1703</font>)
	at scala.reflect.<font color="#75507B">Selectable$</font>.selectDynamic$extension(<font color="#75507B">Selectable</font>.scala:<font color="#CC0000">7</font>)
	at scala.reflect.<font color="#75507B">Selectable</font>.selectDynamic(<font color="#75507B">Selectable</font>.scala:<font color="#CC0000">4</font>)
	at rs$line$14$.&lt;init&gt;(rs$line$14:<font color="#CC0000">1</font>)
	at rs$line$14$.&lt;clinit&gt;(rs$line$14)
	at rs$line$14.res1<font color="#CC0000">0</font>Show(rs$line$14)
	at sun.reflect.<font color="#75507B">NativeMethodAccessorImpl</font>.invoke0(<font color="#75507B">Native</font> <font color="#75507B">Method</font>)
	at sun.reflect.<font color="#75507B">NativeMethodAccessorImpl</font>.invoke(<font color="#75507B">NativeMethodAccessorImpl</font>.java:<font color="#CC0000">62</font>)
	at sun.reflect.<font color="#75507B">DelegatingMethodAccessorImpl</font>.invoke(<font color="#75507B">DelegatingMethodAccessorImpl</font>.java:<font color="#CC0000">43</font>)
	at java.lang.reflect.<font color="#75507B">Method</font>.invoke(<font color="#75507B">Method</font>.java:<font color="#CC0000">498</font>)
	at dotty.tools.repl.<font color="#75507B">Rendering</font>.valueOf(<font color="#75507B">Rendering</font>.scala:<font color="#CC0000">58</font>)
	at dotty.tools.repl.<font color="#75507B">Rendering</font>.renderVal(<font color="#75507B">Rendering</font>.scala:<font color="#CC0000">79</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayMembers$<font color="#CC0000">3</font>$$anonfun$<font color="#CC0000">3</font>(ReplDriver.scala:<font color="#CC0000">284</font>)
	at scala.collection.<font color="#75507B">TraversableLike</font>.$anonfun$map$<font color="#CC0000">1</font>(TraversableLike.scala:<font color="#CC0000">234</font>)
	at scala.collection.mutable.<font color="#75507B">ResizableArray</font>.foreach(<font color="#75507B">ResizableArray</font>.scala:<font color="#CC0000">59</font>)
	at scala.collection.mutable.<font color="#75507B">ResizableArray</font>.foreach$(<font color="#75507B">ResizableArray</font>.scala:<font color="#CC0000">52</font>)
	at scala.collection.mutable.<font color="#75507B">ArrayBuffer</font>.foreach(<font color="#75507B">ArrayBuffer</font>.scala:<font color="#CC0000">48</font>)
	at scala.collection.<font color="#75507B">TraversableLike</font>.map(<font color="#75507B">TraversableLike</font>.scala:<font color="#CC0000">234</font>)
	at scala.collection.<font color="#75507B">TraversableLike</font>.map$(<font color="#75507B">TraversableLike</font>.scala:<font color="#CC0000">227</font>)
	at scala.collection.<font color="#75507B">AbstractTraversable</font>.map(<font color="#75507B">Traversable</font>.scala:<font color="#CC0000">104</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayMembers$<font color="#CC0000">7</font>(ReplDriver.scala:<font color="#CC0000">284</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayDefinitions$$anonfun$<font color="#CC0000">3</font>$$anonfun$<font color="#CC0000">2</font>(ReplDriver.scala:<font color="#CC0000">311</font>)
	at scala.<font color="#75507B">Option</font>.map(<font color="#75507B">Option</font>.scala:<font color="#CC0000">146</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayDefinitions$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">311</font>)
	at dotty.tools.dotc.core.<font color="#75507B">Periods</font>.atPhase(<font color="#75507B">Periods</font>.scala:<font color="#CC0000">26</font>)
	at dotty.tools.dotc.core.<font color="#75507B">Phases</font>.atPhase(<font color="#75507B">Phases</font>.scala:<font color="#CC0000">36</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.displayDefinitions(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">316</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.compile$$anonfun$<font color="#CC0000">2</font>(ReplDriver.scala:<font color="#CC0000">241</font>)
	at scala.util.<font color="#75507B">Either</font>.fold(<font color="#75507B">Either</font>.scala:<font color="#CC0000">188</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.compile(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">242</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.interpret(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">202</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.loop$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">150</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.runUntilQuit$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">154</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.withRedirectedOutput$$anonfun$<font color="#CC0000">2</font>$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">163</font>)
	at scala.util.<font color="#75507B">DynamicVariable</font>.withValue(<font color="#75507B">DynamicVariable</font>.scala:<font color="#CC0000">58</font>)
	at scala.<font color="#75507B">Console$</font>.withErr(<font color="#75507B">Console</font>.scala:<font color="#CC0000">192</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.withRedirectedOutput$$anonfun$<font color="#CC0000">1</font>(ReplDriver.scala:<font color="#CC0000">163</font>)
	at scala.util.<font color="#75507B">DynamicVariable</font>.withValue(<font color="#75507B">DynamicVariable</font>.scala:<font color="#CC0000">58</font>)
	at scala.<font color="#75507B">Console$</font>.withOut(<font color="#75507B">Console</font>.scala:<font color="#CC0000">163</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.withRedirectedOutput(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">163</font>)
	at dotty.tools.repl.<font color="#75507B">ReplDriver</font>.runUntilQuit(<font color="#75507B">ReplDriver</font>.scala:<font color="#CC0000">154</font>)
	at dotty.tools.repl.<font color="#75507B">Main$</font>.main(<font color="#75507B">Main</font>.scala:<font color="#CC0000">6</font>)
	at dotty.tools.repl.<font color="#75507B">Main</font>.main(<font color="#75507B">Main</font>.scala)

</pre>

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix #4496. Writing this test led to #4528.

### CODE REVIEW

File: tests/neg/i4496b.scala [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import scala.reflect.Selectable.reflectiveSelectable
+
+trait Foo1 { val a: Int }
+trait Foo2 { def a: Int }
+trait Foo3 { var a: Int }
+
+object TestStructuralVar {
+  type T0 = {var a: Int} // error
```
Comment (smarter) [inline tests/neg/i4496b.scala]: Unrelated, but maybe this should be allowed and given the same semantics as having a getter/setter ?

Comment (smarter) [reply tests/neg/i4496b.scala]: On second thoughts, maybe that's not worth it, since then it needs to be meaningful for all possible interpretation of structural types, nevermind.

Comment (smarter) [reply tests/neg/i4496b.scala]: ...but maybe the error message could suggest replacing the var by a val and a setter.
