### PR TITLE
Permit new with trivial end

### LINKED ISSUE #24250: `end new` for anonymous classes doesn't work under some conditions
## Compiler version

v3.7.3

## Minimized code

```scala
//> using scala 3.7.4
trait Foo
val foo = 
  new Foo:
    // comment
  end new

val foo2 = 
  new Foo:
  end new

@main def test = {}
```

## Output

```scala
misaligned end marker errors
```

## Expectation
No error.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #24250 

Make trivial `end new` useful by supplying the empty template in parser.

This makes
```
new C {
}
```
equivalent to
```
new C:
end new
```

### CODE REVIEW

**Comment by sjrd** [comment]
> Then
> 
> ```
> new C
> end new
> ```
> is just `new C`.

Why would we want that? It doesn't seem to follow the rule that `end` closes a *block*.

**Comment by som-snytt** [comment]
I thought the rule was that you can remove the marker without changing semantics, but that does not hold.
```
if b then e
end if
```
I'll try that out. Why doesn't github offer embedded REPL?

This obeys the Odersky blank line rule:
```
def f(b: Boolean) =
  if b then println("""hello,







    world""")
  end if
@main def test = f(true)
```

**Comment by som-snytt** [comment]
> Why would we want that?

I remember the argument for
```
class C:
end C
```
was that I'm in the middle of editing, though I don't know if that's why it was finally allowed. But the same applies.
```
new C 
  // todo maybe override something later?
  // do we need an extra class? maybe we can avoid it.

  // override def toString = "Test C"
end new
```
The least github could do is test my late-night snippets in the browser.

**Comment by sjrd** [comment]
The thing is that `new C` and `new C {}` mean completely different things. The latter, because of the block, creates an anonymous subclass of `C`. The former doesn't. You can't just "add overrides" to a `new C`. There's a first, very signifiant step where you have to introduce an anonymous class. That's when you add the `:` and possibly the `end`, not before.

**Comment by som-snytt** [comment]
Yeah, maybe. I'm not wedded to any of this. Is colon enough of an indicator?

if I can write
```
  1
+ 2
end +
```
and I'm not sure they will yet, but my point is `new` gets equal protection. That is SIP 77. Or a similar argument for a named method, but I'm exaggerating for rhetorical effect.

**Comment by som-snytt** [comment]
> it makes it hard to discern when a large indentation region ends

I'll update to read "or a very small region." Joke.

But this is clear:

> If the statement defines an anonymous class, then s must be new.

`end` is intended only for when there was an anon class. I'll remove the even-more-trivial case of a named class instance.

That is at https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#the-end-marker

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -1566,15 +1568,23 @@ object Parsers {
           if MigrationVersion.Scala2to3.needsPatch then
             patch(source, Span(in.offset), "  ")
 
-    def possibleTemplateStart(isNew: Boolean = false): Unit =
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:1569]: `isNew` was never used

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 2]
```diff
@@ -1566,15 +1568,23 @@ object Parsers {
...
+    def possibleTemplateStart(): Unit =
+      possiblyNewTemplateStart(): Unit
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: ignores the boolean value

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 3]
```diff
@@ -2915,15 +2925,22 @@ object Parsers {
...
+          else if parent.isType then ensureApplied(wrapNew(parent))
+          else parent
+      case parents =>
+        // With brace syntax, the last token consumed by a parser is }, but with indent syntax,
+        // the last token consumed by a parser is OUTDENT, which causes mismatching spans, so don't reposition.
+        val indented = in.token == INDENT
+        val body =
+          val bo = templateBodyOpt(emptyConstructor, parents, derived = Nil)
+          if !indented then reposition(bo) else bo
+        New(body)
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2942]: preserves existing behavior, but what is the span of the result?

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 4]
```diff
@@ -2915,15 +2925,22 @@ object Parsers {
...
+      val colonized = possiblyNewTemplateStart()
+      parents match
+      case parent :: Nil if !in.isNestedStart =>
+        reposition:
+          if colonized then New(Template(emptyConstructor, parents, derived = Nil, self = EmptyValDef, body = Nil))
+          else if parent.isType then ensureApplied(wrapNew(parent))
+          else parent
+      case parents =>
+        // With brace syntax, the last token consumed by a parser is }, but with indent syntax,
+        // the last token consumed by a parser is OUTDENT, which causes mismatching spans, so don't reposition.
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2937]: comment inlined from the previous PR

File: tests/neg/i24250.scala [hunk 5]
```diff
@@ -0,0 +1,5 @@
+
```
Comment (som-snytt) [inline tests/neg/i24250.scala:1]: Is it possible to break the habit of inserting an initial blank line in test sources?

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 2 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Do we still need to keep `possibleTemplateStart` if it is just for ignoring the bool?

File: tests/pos/i24250.scala [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+  new Foo:
+  end new
+val foo3 =
+  new Foo {
+  }
+  end new
+
+class C
+val c =
+  new C:
```
Comment (noti0na1) [inline tests/pos/i24250.scala:17]: What will happened if `new C: end new` is in the same line?

**Review by noti0na1 — APPROVED** [review]
Just some small questions, otherwise LGTM

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 2 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: There are several usages to add `: Unit`.

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: I find it is a little confusing: two functions with similar but different names, and they have exact same behaviour...

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Also, in the middle of statements, the result of a function call should be ignored automatically without any warning, right?

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: An inlined if might sidestep `-Wnonunit-statement` if the lint ran late enough.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: The naming is too "cute", even for one usage. I'll make amends.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Also with inline transparent, the inlining trick does not work (yet); that lint should be moved to after inlining (which I won't do here).

File: tests/pos/i24250.scala (hunk 6 above)
Comment (som-snytt) [reply tests/pos/i24250.scala:17]: end of statement expected, not found type end
added to test

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:1569]: Edit: use it now for inlining.

The preferred idiom is blocked by https://github.com/scala/scala3/issues/24441
