### PR TITLE
Fix #7110: Fix splice overload

### LINKED ISSUE #7110: Wrong overload resolution when expanding macro call
## minimized code

Macro definition:
```Scala
import scala.quoted._

object Macros {

  inline def m[R](sym: Symantics[R]) : R = ${  mImpl[R]('{sym}) }

  def mImpl[R: Type](sym: Expr[Symantics[R]]) given (qctx: QuoteContext): Expr[R] =  '{
    $sym.Meth(42)
  }
}

trait Symantics[R]  {
  def Meth(exp: Int): R
  def Meth(): R
}
```

Use:
```Scala
import scala.quoted._
import Macros._

object Test {
  def main(args: Array[String]): Unit = {

    val sym = new Symantics[Int] {
      def Meth(exp: Int): Int = exp
      def Meth(): Int = 42
    }

    val test = m[Int](sym)
  }
}
```

## expectation
Overloading should work. Instead it reports:

```Scala
8 |    $sym.Meth(42)
  |    ^^^^^^^^^^^^
  |    wrong number of arguments at <no phase> for (): Int: ((): Int)(sym.Meth), expected: 0, found: 1
  | This location is in code that was inlined at Test_2.scala:13
```

If I remove the macro call it works (TASTy problem), if the `Symantics` is not parametric it also works. I don't think that it directly related to #7022 but it is definitely in the same area (@smarter WDYT?). BTW, the `<no phase>` in the error is also a bug I assume.

### PR DESCRIPTION
**Pull request by nicolasstucki**
To avoid wrong member selection when unpickling we must have qualifiers that have the same type as when it was pickled. This implies that we cannot expand the holes during unpickling as
the expansion of a qualifier could have a more precise type. To be able to unpickle a hole
without expanding it we must know its type, hence it must be pickled.

Once the pickled quote has been unpickled, we first replace all the type splices. After the
types are properly set we expand all the term holes.

Changes
* Types of holes are pickled in TASTy
* Pickled quotes are unpickled and then the holes are expanded
* Improved debugging info for unpickled quotes

### CODE REVIEW

**Comment by nicolasstucki** [comment]
test performance with #qutotes please

**Comment by nicolasstucki** [comment]
test performance with #quotes please

**Comment by nicolasstucki** [comment]
test performance with #quotes please

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 1]
```diff
@@ -61,44 +61,117 @@ object PickledQuotes {
...
+  }
+
+  /** Replace all term holes with the spliced terms */
+  private def spliceTerms(tree: Tree, splices: PickledArgs)(using Context): Tree = {
+    val evaluateHoles = new TreeMap {
+      override def transform(tree: tpd.Tree)(implicit ctx: Context): tpd.Tree = tree match {
+        case Hole(isTerm, idx, args) =>
+          val reifiedArgs = args.map { arg =>
+            if (arg.isTerm) (qctx: scala.quoted.QuoteContext) ?=> new TastyTreeExpr(arg, QuoteContext.scopeId)
+            else new TreeType(arg, QuoteContext.scopeId)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:88]: The syntax `(x:T) ?=> e` is deprecated in favor of `(using x:T) => e`

It's not clear why `qctx` is needed for creation of `TastyTreeExpr`, as from the code, it's not used.

File: compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala [hunk 2]
```diff
@@ -603,6 +604,7 @@ class TreePickler(pickler: TastyPickler) {
           writeByte(HOLE)
           withLength {
             writeNat(idx)
+            pickleType(tree.tpe, richTypes = true)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala:607]: If we change the tasty format, should we update the tasty version?

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala [hunk 3]
```diff
@@ -1224,7 +1224,10 @@ class TreeUnpickler(reader: TastyReader,
               val alias = if currentAddr == end then EmptyTree else readTpt()
               TypeBoundsTree(lo, hi, alias)
             case HOLE =>
-              readHole(end, isType = false)
+              val idx = readNat()
+              val tpe = readType()
+              val args = until(end)(readTerm())
+              TreePickler.Hole(true, idx, args).withType(tpe)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala:1230]: It seems now we can remove the `splices` param for `TreeUnpickler`.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 4]
```diff
@@ -61,44 +61,117 @@ object PickledQuotes {
...
-          transform(expr1)
-        case tree => super.transform(tree).withType(dealiasTypeTags(tree.tpe))
-      }
-    }
-    forceAndCleanArtefacts.transform(unpickled)
+    val unpickled = unpickle(tastyBytes, splices, isType = false)(ctx.addMode(Mode.ReadPositions))
+    val Inlined(call, Nil, expnasion) = unpickled
+    val inlineCtx = inlineContext(call)
+    val expansion1 = spliceTypes(expnasion, splices)(using inlineCtx)
+    val expansion2 = spliceTerms(expansion1, splices)(using inlineCtx)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:70]: Small opt: can we just do one pass for splicing?

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 5]
```diff
@@ -61,44 +61,117 @@ object PickledQuotes {
...
+            else filled.cloneIn(ctx.source).withSpan(tree.span)
+          else
+            // Replaces type holes generated by ReifyQuotes (non-spliced types).
+            // These are types defined in a quote and used at the same level in a nested quote.
+            val quotedType = splices(idx).asInstanceOf[Seq[Any] => quoted.Type[?]](reifiedArgs)
+            PickledQuotes.quotedTypeToTree(quotedType)
+        case tree: Select =>
+          // Retain selected members
+          val qual = transform(tree.qualifier)
+          qual.select(tree.symbol).withSpan(tree.span)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:107]: It would be nice to doc & spec this invariant: quoting & splicing do not change overloading resolution. The following can be an example to demonstrate:

```Scala
class A[T] {
  def foo(x: T): T = ???
  def foo(x: Int): Int = ???
}

class B extends A[Int]

import scala.quoted._

inline def m[T](a: A[T], x: T) : T = ${  mImpl[T]('a, 'x) }

def mImpl[T: Type](a: Expr[A[T]], x: Expr[T])(using qctx: QuoteContext): Expr[T] =  '{
  $a.foo($x)
}

// which `foo` will be called?
m(new B,  5)
```

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 6]
```diff
@@ -61,44 +61,117 @@ object PickledQuotes {
...
+        override def apply(tp: Type): Type = {
+            tp match
+              case tp @ AnnotatedType(underlying, annot) =>
+                val underlying1 = this(underlying)
+                derivedAnnotatedType(tp, underlying1, annot.derivedAnnotation(transform(annot.tree)))
+              case _ => mapOver(tp)
+        }
+      }
     }
-    tpt.withType(dealiasTypeTags(tpt.tpe))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:94]: We can remove `dealiasTypeTags`, as it is not used anymore.

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 7]
```diff
@@ -331,7 +331,37 @@ class ReifyQuotes extends MacroTransform {
...
+        override def apply(tp: Type): Type = tp match
+          case tp @ TypeRef(NoPrefix, _) if capturers.contains(tp.symbol) =>
+            // reference to term with a type defined in outer quote
+            getTypeHoleType(tp)
+          case tp @ TermRef(NoPrefix, _) if capturers.contains(tp.symbol) =>
+            // widen term refs to terms defined in outer quote
+            apply(tp.widenTermRefExpr)
+          case tp =>
+            mapOver(tp)
+      }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala:360]: Will approximation of the hole type has consequences with member resolution in unpickling?

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 8]
```diff
@@ -122,7 +195,13 @@ object PickledQuotes {
     unpickler.enter(Set.empty)
 
     val tree = unpickler.tree
-    quotePickling.println(i"**** unpickle quote ${tree.show}")
+
+    // Make sure trees and positions are fully loaded
+    new TreeTraverser {
+      def traverse(tree: Tree)(implicit ctx: Context): Unit = traverseChildren(tree)
+    }.traverse(tree)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:202]: What will happen if we remove the code above? Maybe add a doc for consequences if the action is not taken.

File: compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala:607]: Yes, I missed it

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala:607]: Yes, I missed it

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala (hunk 4 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:70]: No, that was the first approach I tried. We need the types to be known when we expand the term holes as some of them may take some type parameters that the user inspects.  Note that `spliceTypes` is a no-op if the quote does not have type splices.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala (hunk 5 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:107]: That is in part of the spec of inlining. We just did something else by mistake. I will try to place this in the docs.

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala (hunk 7 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala:360]: Yes, the consequence is that when unpickling we use the same known bounds of the types to resolve members selection as was done in typed. This is the key to make sure they do not change.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala (hunk 8 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala:202]: Some symbols and positions are not loaded early enough. Not sure why though. But it has been like that since the start. Dimitry mentioned the need for this for loading trees from tasty in general and we have keep this mechanism so far.

File: compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala:607]: Oh, I rebased on another PR that also changed it.

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala (hunk 3 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala:1230]: Yes :)

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala:1230]: Actually the `QuoteUnpickler` is redundant now. We can use the `DottyUnpickler` directly.
