### PR TITLE
Fix #6828: Support by-name synthesized implicits

### LINKED ISSUE #6828: By-name ClassTag not found
## minimized code

```Scala
class Foo {
  inline def foo[T](implicit ct: =>scala.reflect.ClassTag[T]): Unit = Unit
  foo[Int]
  foo[String]
}
```

```
-- Error: Foo.scala:3:10 -------------------------------------------------------
3 |  foo[Int]
  |          ^
  |          No ClassTag available for Int
-- Error: Foo.scala:4:13 -------------------------------------------------------
4 |  foo[String]
  |             ^
  |             No ClassTag available for String
```

## expectation

It should compile

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -1066,8 +1066,9 @@ trait Implicits { self: Typer =>
                 tp.baseType(cls)
             }
             val base = baseWithRefinements(formal)
+            val formal1 = formal.resultType // Drop ExprType
```
Comment (milessabin) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: Should be `widenExpr` rather than `resultType`.
