### PR TITLE
Fix #3538: Better invalidation of typed arguments in FunProtos

### LINKED ISSUE #3538: Typechecker inferencing orphan type T
Code to reproduce it https://gist.github.com/rcano/14c1b3af9bec4b9dadbc7ba2fd097fd3
(Note, requires javafx which comes bundled with Oracle's JDK or you can install with to openjdk)

The error looks like this:

```
error when pickling type T
error when pickling type javafx.scene.control.ComboBox[T]
error when pickling tree javafx.scene.control.ComboBox[T]
error when pickling tree val cb: javafx.scene.control.ComboBox[T] = 
  Dsl.BorderPaneBuilder(this).right[javafx.scene.control.ComboBox[T]](
    Dsl.combobox[T](Test.this.planets: Planet*)
  )
error when pickling tree (planets: scala.collection.Seq[Planet] @scala.annotation.internal.Repeated())
   extends
 javafx.scene.layout.BorderPane() { $: Test => 
  private[this] val planets: scala.collection.Seq[Planet] @Repeated
  val cb: javafx.scene.control.ComboBox[T] = 
    Dsl.BorderPaneBuilder(this).right[javafx.scene.control.ComboBox[T]](
      Dsl.combobox[T](Test.this.planets: Planet*)
    )
  Test.this.cb.getSelectionModel().selectLast()
}
error when pickling tree @scala.annotation.internal.SourceFile(
  "/home/randa/Development/testdotty/src/main/scala/Main.scala"
) class Test(
  planets: scala.collection.Seq[Planet] @scala.annotation.internal.Repeated()
) extends javafx.scene.layout.BorderPane() { $: Test => 
  private[this] val planets: scala.collection.Seq[Planet] @Repeated
  val cb: javafx.scene.control.ComboBox[T] = 
    Dsl.BorderPaneBuilder(this).right[javafx.scene.control.ComboBox[T]](
      Dsl.combobox[T](Test.this.planets: Planet*)
    )
  this.cb.getSelectionModel().selectLast()
}
error when pickling tree package <empty> {
  import javafx.scene.Node
  import javafx.scene.control._
  import javafx.scene.layout._
  import Dsl._
  @scala.annotation.internal.SourceFile(
    "/home/randa/Development/testdotty/src/main/scala/Main.scala"
  ) class Test(
    planets: scala.collection.Seq[Planet] @scala.annotation.internal.Repeated()
  ) extends javafx.scene.layout.BorderPane() { $: Test => 
    private[this] val planets: scala.collection.Seq[Planet] @Repeated
    val cb: javafx.scene.control.ComboBox[T] = 
      Dsl.BorderPaneBuilder(this).right[javafx.scene.control.ComboBox[T]](
        Dsl.combobox[T](Test.this.planets: Planet*)
      )
    this.cb.getSelectionModel().selectLast()
  }
}
```

The orphan type T gets leaked even to the "presentation compiler" exposed through the language server.

### PR DESCRIPTION
**Pull request by odersky**
One scenario we overlooked was that an argument in a FunProto might have been
computed in a context that was subsequently retracted from its typerstate (e.g.
because an enclosing subtype test failed). In that case we need to re-evaluate
the argument in order to avoid orphan typerefs.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala [hunk 1]
```diff
@@ -570,6 +570,14 @@ class OrderingConstraint(private val boundsMap: ParamBounds,
   private def checkNonCyclic(param: TypeParamRef)(implicit ctx: Context): Unit =
     assert(!isLess(param, param), i"cyclic constraint involving $param in $this")
 
+// ---------- Invalidation -------------------------------------------
+
+  private var retracted = false
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala]: `private[this]` ?

File: compiler/src/dotty/tools/dotc/core/TyperState.scala [hunk 2]
```diff
@@ -33,6 +33,12 @@ class TyperState(previous: TyperState /* | Null */) extends DotClass with Showab
     myConstraint = c
   }
 
+  /** Reset constraint to `c` and mark current constraint as retracted if it differs from `c` */
+  def resetConstraintTo(c: Constraint) = {
+    if (c `ne` myConstraint) myConstraint.markRetracted()
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TyperState.scala]: Why use backquotes around `ne` ? New coding style for infix calls?
