### PR TITLE
Fix #10888: Avoid A.this.B for Java inner classes

### LINKED ISSUE #10888: exception caught when loading class C: Cyclic reference involving class C
## Minimized code

scala file failing to compile:

```Scala
import com.badlogic.gdx.graphics.g2d.ParticleEffectPool

case class DrawParticleEffect(effect: ParticleEffectPool)
```

mill build file build.sc, use this to fetch the ParticleEffectPool class which causes the issue :
```Scala

import Deps._
import mill._
import mill.scalalib._
import mill.scalalib.scalafmt._

object `gdx-lib` extends Common {
  override def ivyDeps = Agg(
    Gdx.Core,
    Gdx.Backend,
    Gdx.Native,
    Gdx.Controllers
  )
}

trait Common extends SbtModule with ScalafmtModule {
  override def scalaVersion = Deps.ScalaVersion

  override def scalacOptions = Seq("-deprecation", "-feature", "-unchecked")
}

object Deps {
  val ScalaVersion = "3.0.0-M3"

  object Gdx {
    private val Version = "1.9.12"
    val Core = ivy"com.badlogicgames.gdx:gdx:$Version"
    val Backend = ivy"com.badlogicgames.gdx:gdx-backend-lwjgl3:$Version"
    val BackendHeadless = ivy"com.badlogicgames.gdx:gdx-backend-headless:$Version"
    val Native = ivy"com.badlogicgames.gdx:gdx-platform:$Version;classifier=natives-desktop"
    val Controllers = ivy"com.badlogicgames.gdx:gdx-controllers-lwjgl3:$Version"
  }
}

```

use `mill __.compile` to compile and get the error.

## Output

```
[info] Compiling 1 Scala source to /home/ariskk/temp/scala3issue/out/gdx-lib/compile/dest/classes ...
exception caught when loading class ParticleEffectPool: Cyclic reference involving class ParticleEffectPool
[error] -- [E046] Cyclic Error: /home/ariskk/temp/scala3issue/gdx-lib/src/main/scala/games/lib/draw/DrawParticleEffect.scala:8:81 
[error] 8 |case class DrawParticleEffect(renderPriority: Float, x: Float, y: Float, effect: ParticleEffectPool, scaleFactor: Float = 1) {}
[error]   |                                                                                 ^
[error]   |                       Cyclic reference involving class ParticleEffectPool
[error] one error found

```

## Expectation

This should compile. It compiles ok with scala 2.13.4 but it could be a class file issue from the gdx library.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #10888: Avoid A.this.B for Java inner classes

For Java inner classes, we should use `A#B` instead of `A.this.B`.

Co-authored-by: Guillaume Martres <smarter@ubuntu.com>

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -349,12 +349,15 @@ class ClassfileParser(
       val tag = sig(index); index += 1
       (tag: @switch) match {
         case 'L' =>
-          def processInner(tp: Type): Type = tp match {
-            case tp: TypeRef if !tp.symbol.owner.is(Flags.ModuleClass) =>
-              TypeRef(processInner(tp.prefix.widen), tp.symbol.asType)
-            case _ =>
-              tp
-          }
+          /** Inner class references of A.this.B into A#B, do the same transformation recursively on `A` */
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:352]: That comment is no longer accurate when the input is a symbol, I suggest:
```suggestion
          /** A type representation where inner classes become `A#B` instead of `A.this.B` (like with `typeRef`) */
```

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 2]
```diff
@@ -349,12 +349,15 @@ class ClassfileParser(
...
+          def innerType(symbol: Symbol): Type =
+            if symbol.is(Flags.Package) then
+              ThisType.raw(TypeRef(NoPrefix, symbol.asType))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:355]: could this be `symbol.thisType` instead?

**Review by smarter — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:355]: Yes, that's much simpler.

**Comment by liufengyun** [comment]
@smarter Could you have a look at the last commit? It took a while to find out the root cause.

File: compiler/test/dotty/tools/AnnotationsTests.scala [hunk 3]
```diff
@@ -26,18 +26,24 @@ class AnnotationsTest:
...
-        }
+        val arrayOfString = defn.ArrayOf(defn.StringType)
+
+        // Even though we're forcing the annotation after erasure,
+        // the typed trees should be unerased, so the type of
+        // the annotation argument should be `arrayOfString` and
+        // not a `JavaArrayType`.
+
+        val annot = atPhase(erasurePhase.next) { cls.getAnnotation(annotCls) }
+        val arg = annot.get.argument(0).get
```
Comment (smarter) [inline compiler/test/dotty/tools/AnnotationsTests.scala:37]: It's important to run this line at erasure, otherwise we're not forcing the annotation tree at the erasure phase. But also, why is this test suddenly failing after the change you made? They don't seem related at all, and based on the comment you added I would expect it to fail before too. If you're not sure what's going on let me know and I can try to have a look.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/test/dotty/tools/AnnotationsTests.scala (hunk 3 above)
Comment (liufengyun) [reply compiler/test/dotty/tools/AnnotationsTests.scala:37]: I don't know why it's not failing before. But the subtyping trace and debugging tells that `Array[String] =:= Array[String]` is false after erasure due to the cause in the commit message. Just running the subtyping in an early phase is enough.

Comment (liufengyun) [reply compiler/test/dotty/tools/AnnotationsTests.scala]: @smarter: I've just updated the code so that we only do subtyping test before erasure. If it's green, then please have a look if you have clue why it's not failing before.

Comment (liufengyun) [reply compiler/test/dotty/tools/AnnotationsTests.scala]: From the investigation so far, the changes in `ClassfileParser` have changed subtyping path for `Array[String] <:< Array[String]`.

Previously, it does not touch the line `TypeComparer.compareAppliedType2`, now it reaches that line.

Comment (liufengyun) [reply compiler/test/dotty/tools/AnnotationsTests.scala]: After some further investigation, we know why it accidentally works before: before the change the two `Array[String]` and `Array[String]` point to the same object, thus they go through the short-cut `tp1 eq tp2` in TypeComparer, thus never reaches the line `TypeComparer.compareAppliedType2`.

The changes in ClassfileParser somehow changes the caching behavior.

**Review by smarter — DISMISSED** [review]
Thanks for looking into it, makes sense, LGTM!

**Comment by smarter** [comment]
Oh, looks like there's a failed test:
```scala
-- [E007] Type Mismatch Error: tests/pos/i5655/S_2.scala:4:41 ----------------------------------------------------------
4 |    val ab: J_1#A[String]#B[String] = j.m()
Compilation failed for: 'tests/pos/i5655'                                       
  |                                      ^^^^^
  |                                      Found:    J_1#A[?]#B[String]
  |                                      Required: J_1#A[String]#B[String]
```
Corresponding PR is https://github.com/lampepfl/dotty/pull/5656

**Review by smarter — APPROVED** [review]
