### PR TITLE
Fix #7249: Search for hidden givens only at whole type

### LINKED ISSUE #7249: Crash – StackOverflow when summoning
## minimized code

```Scala
trait F[H, T]

given [H, T](given h: H, t: T): F[H, T] = ???
@main def Test = summon[F[Int, Unit]]
```

<details>
<summary>Stack trace</summary>

```scala
java.lang.StackOverflowError while compiling ../pg/is2/Main.scala
Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4955)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5087)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4946)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5089)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$1(Types.scala:4925)
	at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:4929)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5081)
	at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:5075)
```
</details>

### PR DESCRIPTION
**Pull request by odersky**
Don't try to find a hidden implicit for a part of type type that
was searched for, unless that part is fully defined.

The reason is that any type variables in a subtype might be associated
with constraints that are lost at the point of issuing a "hidden
givens" addendum.

The commit also contains a tweak to "isFullyDefined" which makes
an uninstantiated type variable that is not bound in the current
constraint count as "not fully defined", where previously it was
"fully defined".

### CODE REVIEW

**Comment by odersky** [comment]
This fixes also #7248

File: tests/pos/i7250.scala [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import compiletime.erasedValue
+
+sealed trait Foo
+trait A extends Foo
+trait B[H] extends Foo
+
+inline given f[T <: Foo]: T = inline erasedValue[T] match
+  case _: A => new A{}.asInstanceOf[T]
+  case _: B[a] => summon[a].asInstanceOf[T]
```
Comment (anatoliykmetyuk) [inline tests/pos/i7250.scala]: This summon shouldn't succeed though on compile time. Starting from `println`:

```scala
// 1) initial call
f[B[Int]]

// 2) inlining `f`
inline erasedValue[B[Int]] match
  case _: A => new A{}.asInstanceOf[B[Int]]
  case _: B[a] => summon[a].asInstanceOf[B[Int]]

// 3) second case matched and inlined with a = Int
summon[Int].asInstanceOf[B[Int]]
```

`summon[Int]` should fail since there's no `Int` given in scope, shouldn't it?

```scala
scala> summon[Int]
1 |summon[Int]
  |           ^
  |no implicit argument of type Int was found for parameter x of method summon in object DottyPredef
```

Comment (anatoliykmetyuk) [reply tests/pos/i7250.scala]: Even if it tries `Int & Foo` it still won't find anything suitable, since `f` returns `T <: Foo` and nothing about it says that it is an intersection with `Int`.

Comment (odersky) [reply tests/pos/i7250.scala]: It actually tries `f[Nothing]` and succeeds with the `A` case.

Comment (anatoliykmetyuk) [reply tests/pos/i7250.scala]: Oh right. So the behaviour here stays the same as in the #7250 second example: if we run this test, it will fail at runtime with ClassCastException. It looks like it is the same problem as #7293, where Nothing appears in unexpected places.

Comment (anatoliykmetyuk) [reply tests/pos/i7250.scala]: Actually I remember testing it with `inline given f[T >: Nothing <: Foo]: T`, and it still finds `f` when looking for `Nothing` (as understood from the unchanged behaviour in that case).
