### PR TITLE
Fix #4207: Read whole zipfile before closing

### LINKED ISSUE #4207: Language server crashes at startup
On the master branch, running `launchIDE` fails.

Reverting this change fixes the issue: https://github.com/lampepfl/dotty/pull/3010/commits/0ae6f04b27d93a5e063420c9184062891ac8e53c#diff-174d2bebb262c406df14c007ac5c7344R133

<details>
  <summary>Logs</summary>

```
(...)
[info] Starting client: List(code, -n, --extensionDevelopmentPath=/Users/martin/Documents/Projects.nosync/Duhemm/dotty/vscode-dotty, /Users/martin/Documents/Projects.nosync/Duhemm/dotty/language-server/..)
[info] Starting server
[error] java.util.concurrent.CompletionException: java.lang.IllegalStateException: zip file closed
[error]         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[error]         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[error]         at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
[error]         at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: java.lang.IllegalStateException: zip file closed
[error]         at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[error]         at java.util.zip.ZipFile.access$200(ZipFile.java:60)
[error]         at java.util.zip.ZipFile$ZipEntryIterator.hasNext(ZipFile.java:508)
[error]         at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
[error]         at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
[error]         at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:39)
[error]         at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:447)
[error]         at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:478)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error]         at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:658)
[error]         at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:635)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at dotty.tools.dotc.interactive.InteractiveDriver.<init>(InteractiveDriver.scala:142)
[error]         at dotty.tools.languageserver.DottyLanguageServer.drivers$$anonfun$2(DottyLanguageServer.scala:82)
[error]         at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
[error]         at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at dotty.tools.languageserver.DottyLanguageServer.drivers(DottyLanguageServer.scala:83)
[error]         at dotty.tools.languageserver.DottyLanguageServer.initialize$$anonfun$2$$anonfun$1(DottyLanguageServer.scala:167)
[error]         at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[error]         ... 5 more
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last dotty-language-server/*:run for the full output.
[error] (dotty-language-server/*:run) Nonzero exit code returned from runner: 1
[error] Total time: 21 s, completed Mar 29, 2018 9:35:19 AM
```
</details>

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala [hunk 1]
```diff
@@ -132,7 +132,7 @@ class InteractiveDriver(val settings: List[String]) extends Driver {
 
     try {
       for {
-        entry <- zipFile.stream.iterator().asScala
+        entry <- zipFile.stream.toArray((size: Int) => new Array[ZipEntry](size))
         name = entry.getName
         tastySuffix <- tastySuffixes
         if name.endsWith(tastySuffix)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala]: While you're at, can you change the two lines above to:
```
tastySuffix <- tastySuffixes.find(name.endsWith)
```
I've mistakenly changed it in https://github.com/lampepfl/dotty/pull/3010/commits/0ae6f04b27d93a5e063420c9184062891ac8e53c
