### PR TITLE
Fix #5481: Follow opaque aliases in prototypes of functions

### LINKED ISSUE #5481: Opaque types don't play nicely with anonymous functions
Normally I could write an anonymous function and the argument type could be inferred based on the expected type. For example, if I defined `type Set[A] = A => Boolean` then I could write `def singleton[A](a: A): Set[A] = _ == a` and the type of `_` would be inferred as `A`. However, if I define `Set` as `opaque` and try to do this in the type companion it doesn't work. I have to specify the type of the argument explicitly, which seems unnecessary and inconsistent given that within the type companion the opaque type and its definition are supposed to be the same thing.

```
object TypeAlias {

  type Set[A] = A => Boolean

  object Set {
    def singleton[A](a: A): Set[A] = _ == a       // Works
  }
}

object OpaqueType {

  opaque type Set[A] = A => Boolean

  object Set {
    //def singleton[A](a: A): Set[A] = _ == a     // Does not compile
    def singleton0[A](a: A): Set[A] = (_: A) == a // Works
  }
}
```

### PR DESCRIPTION
**Pull request by odersky**
If the prototype of a function value is a synthetic opaque type alias, assume
the alias type. If the alias type is a function type, this allows one to infer
the parameter types of the function value.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -728,13 +728,12 @@ class Typer extends Namer
       case _: WildcardType => untpd.TypeTree()
       case _ => untpd.TypeTree(tp)
     }
-    pt.stripTypeVar match {
-      case _ if defn.isNonDepFunctionType(pt) =>
+    pt.dealias.followSyntheticOpaque match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: This seems fishy to me, outside of the companion of the opaque type, we shouldn't be doing this. And inside the companion, it should not be needed (since we can just dealias). The real issue I think is that `isNonDepFunctionType` is overly strict in what it considers a function type, such that an intersection of a function type and something else is not consider a function type. If we relax this, then I don't think the `followSyntheticOpaque` is needed. (This is closely related to https://github.com/lampepfl/dotty/issues/5473 where the issue is that the definition of implicit function type is too restrictive).

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Dealiasing does not work inside the companion object, since for an opaque type 

    opaque type T = A

the binding of `T.T` has the form

    type T >: A | outer.T <: A & outer.T

That's why `followSyntheticOpaque` is needed; it uncovers the alias `A` when inside the companion object.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: But If I look at the base types of `T` in the companion object, I should see `Function1[A, Boolean]`, because base types follow upper bounds, so if `isNonDepFunctionType` used `isRef` or something like that, we wouldn't need the special case.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: It would have to be `derivesFrom` but that would break other things. The code here is quite finely balanced out, and I don't want to upset it since this might take a long time and the result is probably the same.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I'm mostly mentioning this because https://github.com/lampepfl/dotty/issues/5473 could be solved the same way (using `derivesFrom`) and if we don't do that then more special cases are going to break (e.g. an implicit function type behind an opaque type)

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I propose to treat #5473 separately. I feel that's a much bigger can of worms than it looks at first.
