### PR TITLE
Avoid box failures and better diagnosis if they come back

### LINKED ISSUE #24543: Very obscure error message when cause is unboxing of parameter bounds
## Compiler version

3.8.0-RC2

## Minimized example

```Scala
import scala.language.experimental.captureChecking

def hh[T <: Ref^](x: Box[T]): Unit =
  val y: (Ref^, Int) = (x.elem, 1)
```

## Output

```scala
4 |  val y: (Ref^, Int) = (x.elem, 1)
  |                       ^^^^^^^^^^^
  |    Found:    (T^'s1, Int)
  |    Required: (Ref^, Int)
  |
  |    Note that capability cap is not included in capture set {}.
  |
  |    where:    ^   refers to a fresh root capability in the type of value y
  |              cap is a fresh root capability in the type of type T
  |
  | longer explanation available when compiling with `-explain`
```

## Expectation

Either no error, or a clearer error message that shows the cause of the problem. If I compile with -explain -Ycc-verbose I see
```
4 |  val y: (Ref^, Int) = (x.elem, 1)
  |                       ^^^^^^^^^^^
  |          Found:    (box T^'s1, Int)
  |          Required: (box Ref^{cap}, Int)
  |
  |          Note that capability cap² is not included in capture set {}.
  |
  |          where:    cap  is a fresh root capability in the type of value y
  |                    cap² is a fresh root capability in the type of type T
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  |
  | Tree:
  |
  | Tuple2.apply[T, Int](x.elem, 1)
  |
  | I tried to show that
  |   (box T^'s1, Int)
  | conforms to
  |   (box Ref^{<fresh in value y hiding 's2>}, Int)
  | but none of the attempts shown below succeeded:
  |
  |   ==> (box T^'s1, Int)  <:  (box Ref^{<fresh in value y hiding 's2>}, Int)
  |     ==> box T^'s1  <:  box Ref^{<fresh in value y hiding 's2>}
  |       ==> T  <:  Ref^{<fresh in value y hiding 's2>}
  |         ==> T  <:  Ref
  |           ==> box Ref^{<fresh in method hh hiding 's3>}  <:  Ref
  |             ==> subcaptures {<fresh in method hh hiding 's3>} <:< {} in open varState
  |               ==> {} accountsFor <fresh in method hh hiding 's3> with {<fresh in method hh hiding 's3>}  = false
  |         ==> box Ref^{<fresh in method hh hiding 's3>}  <:  Ref^{<fresh in value y hiding 's2>}
  |           ==> {} accountsFor <fresh in method hh hiding 's3> with {<fresh in method hh hiding 's3>}  = false
  |           ==> {} accountsFor <fresh in method hh hiding 's3> with {<fresh in method hh hiding 's3>}  = false
  |     ==> (box T^'s1, Int)  <:  (box Ref^{<fresh in value y hiding '{<fresh in method hh hiding 's3>}>}, Int)
  |       ==> box T^'s1  <:  box Ref^{<fresh in value y hiding '{<fresh in method hh hiding 's3>}>}
  |         ==> T  <:  Ref^{<fresh in value y hiding '{<fresh in method hh hiding 's3>}>}
  |           ==> T  <:  Ref
  |             ==> box Ref^{<fresh in method hh hiding 's3>}  <:  Ref
  |               ==> subcaptures {<fresh in method hh hiding 's3>} <:< {} in open varState
  |                 ==> {} accountsFor <fresh in method hh hiding 's3> with {<fresh in method hh hiding 's3>}  = false
  |           ==> box Ref^{<fresh in method hh hiding 's3>}  <:  Ref^{<fresh in value y hiding '{<fresh in method hh hiding 's3>}>}
  |             ==> {} accountsFor <fresh in method hh hiding 's3> with {<fresh in method hh hiding 's3>}  = false
  |             ==> {} accountsFor <fresh in method hh hiding 's3> with {<fresh in method hh hiding 's3>}  = false
  |
  | The tests were made under the empty constraint
```

The critical part are in the last three lines: We are comparing a `box Ref^` with a `Ref^`, that's why it fails.

### PR DESCRIPTION
**Pull request by odersky**
The first commit gives a better error message for box failures. At least we don't get

    Note that cap is not included in {}

anymore. To make this even better we'd have to trace back a box failure to the original types we were trying to compare. Right now the box failure error notes are too disconnected from the rest. But they become clearer when one compiles with -explain.

The second commit fixes the underlying problem. The neg tests are now pos tests. I kept the special error message for better diagnosis if the mismatch arises elsewhere. The mismatch still persists in eta.scala. We should investigate
whether that's legit or not.

Fixes #24543

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/CaptureSet.scala [hunk 1]
```diff
@@ -1377,6 +1384,12 @@ object CaptureSet:
         else
           trailing:
             i"capability ${elem.showAsCapability} cannot be included in capture set $cs"
+      case cs: EmptyOfBoxed =>
+        trailing:
+          val (boxed, unboxed) =
+            if cs.tp1.isBoxedCapturing then (cs.tp1, cs.tp2) else (cs.tp2, cs.tp1)
+          i"""${cs.tp1} does not conform to ${cs.tp2} because $boxed is boxed but $unboxed is not.
+             |This could be an error in the capture checker implementation."""
```
Comment (Linyxus) [inline compiler/src/dotty/tools/dotc/cc/CaptureSet.scala]: Not sure about this error note. It feels to me a bit ambiguous: should the user open an issue ticket when they see this?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/cc/CaptureSet.scala]: We are not sure whether it's an error or not, so I refrained from giving clear guidance to users.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/cc/CaptureSet.scala]: In fact eta.scala still shows the same error.
