### PR TITLE
Reject incomplete implicit dictionaries

### LINKED ISSUE #6796: Incomplete implicit dictionaries should be rejected
This is Dotty's equivalent of https://github.com/scala/bug/issues/11591. Here, rather than crashing the compiler, it compiles incorrectly yielding a null. The correct behaviour is to report an implicit search failure.

```scala
object Test {
  class A
  class B

  implicit def mkA(implicit b: => B): A = ???
  implicit def mkB(implicit a: A, i: Int): B = ???

  implicitly[A]
}
```

PR incoming ...

### PR DESCRIPTION
**Pull request by milessabin**
If any RHS of a recursive implicit dictionary (after pruning) is an `EmptyTree`, then this indicates that implicit search failed and we should report the overall search as a failure.

Fixes #6796.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -1842,6 +1842,7 @@ final class SearchRoot extends SearchHistory {
           val pruned = prune(List(tree), implicitDictionary.map(_._2).toList, Nil)
           implicitDictionary0 = null
           if (pruned.isEmpty) result
+          else if (pruned.exists(_._2 == EmptyTree)) NoMatchingImplicitsFailure
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: Is there a way to provide a more detailed error that would let the user know more about how the search failed?

Comment (milessabin) [reply compiler/src/dotty/tools/dotc/typer/Implicits.scala]: In principle I guess so. But it's not obvious (to me) how to do that.
