### PR TITLE
Fix protected constructor access

### LINKED ISSUE #25442: Compiler incorrectly permits access to protected constructor
On 3.8.2:

```scala
class I protected (x: Int) {
  protected def f = x
}

class M protected () extends I(42) {
  def t1(m: M) = m.f // ok
  def t2(i: I) = i.f // error (spec 5.2.2): the type of `i` does not conform to
                     // "a type-instance of the class which contains the access"

  def t3 = new M()   // ok
  def t4 = new I(42) // allowed, but should be rejected (Scala 2 rejects it)
}
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #25442

Alternative for #25515

## How much have you relied on LLM-based tools in this contribution?

I looked at this with @bracevac with the aim of simplifying his PR #25515. Claude suggested a fix which is in
the first commit of this PR. That still left a corner case open. I came up with the fix in the second commit that
also handles the corner case.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Contexts.scala [hunk 1]
```diff
@@ -441,6 +441,14 @@ object Contexts {
         .setScope(this.scope)
     }
 
+    /** Is this a super call context?
+     *  This is the case if we are in a primary constructor and
+     *  the outer context has as owner the owner of the enclosing class.
+     *  The enclosing class is `owner.owner`, hence `outer.owner == owner.owner.owner`.
+     */
+    def isSuperCallContext: Boolean =
+      owner.isPrimaryConstructor && outer.owner == owner.owner.owner
```
Comment (bracevac) [inline compiler/src/dotty/tools/dotc/core/Contexts.scala:450]: Now that's what I call an ownership chain.

**Comment by odersky** [comment]
I must say, the fix suggested by Claude was quite ingenious, even if it was ultimately insufficient. Also, kudos that Claude detected the missing corner case itself. I would have signed off on the fix it suggested.
