### PR TITLE
Fix #3149: Fix pickling of child annotations to local classes

### LINKED ISSUE #3149: Compiler crashes on inner class that extends sealed class
```scala
sealed class Foo

class Test {
  def f = {
    class Bar extends Foo
  }
}
```

<details>
  <summary>Stacktrace</summary>
  <pre>
exception occurred while compiling tests/allan/Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: class Bar when pickling tests/allan/Test.scala
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:592)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$3(Pickler.scala:52)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$3$adapted(Pickler.scala:45)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$2(Pickler.scala:45)
	at dotty.tools.dotc.transform.Pickler.$anonfun$run$2$adapted(Pickler.scala:44)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:44)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:288)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:286)
	at dotty.tools.dotc.core.Phases$Phase.runOn$(Phases.scala:285)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:76)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:124)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:122)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:120)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:120)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:86)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:108)
	at dotty.tools.dotc.Run.compileSources(Run.scala:95)
	at dotty.tools.dotc.Run.compile(Run.scala:79)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.Driver.process(Driver.scala:105)
	at dotty.tools.dotc.Driver.main(Driver.scala:132)
	at dotty.tools.dotc.Main.main(Main.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
  </pre>
</details>
<br>

### PR DESCRIPTION
**Pull request by odersky**
i3149.scala is an interesting test case: A sealed top-level class `Foo`
has a child which is a local (i.e., term-owned) definition in a different top-level class.
It is then impossible to establish a symbolic reference to the child class
from `Foo`, and it is also impossible to refer to `Foo` using a path. We deal with this
by avoiding pickling such child annotations and re-establishing the annotation
when the body of the child class is unpickled.

### CODE REVIEW

**Comment by odersky** [comment]
That one was really tricky to get right.

**Comment by smarter** [comment]
We could also disallow local classes directly extending a sealed trait since it kind of defeat the purpose of sealed traits :)

**Comment by odersky** [comment]
Actually, here are use cases. PatternMatcher.scala in Dotty is one. Also, Allan told me it was a minimized test case from some community project.

**Comment by allanrenucci** [comment]
Actually the test case came to me when I was playing with #3145.

**Comment by smarter** [comment]
> Actually, here are use cases. PatternMatcher.scala in Dotty is one.

Where is this used in PatternMatcher.scala ?

**Comment by odersky** [comment]
We fail in several PRs with the following. Is this a bug in the buld script?

[info] Resolving key references (15718 settings) ...
48s
209
[info] Set current project to dotty (in build file:/tmp/3/)
50s
210
<set>:1: error: not found: value bootstrapOptimised
50s
211
bootstrapOptimised in ThisBuild := true
50s
212
^
50s
213
[error] Type error in expression

**Comment by smarter** [comment]
Should go away if you rebase.

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -514,12 +514,7 @@ class SpaceEngine(implicit ctx: Context) extends SpaceLogic {
 
   /** Decompose a type into subspaces -- assume the type can be decomposed */
   def decompose(tp: Type): List[Space] = {
-    val children = tp.classSymbol.annotations.filter(_.symbol == ctx.definitions.ChildAnnot).map { annot =>
-      // refer to definition of Annotation.makeChild
-      annot.tree match {
-        case Apply(TypeApply(_, List(tpTree)), _) => tpTree.symbol
-      }
-    }
+    val children = tp.classSymbol.children
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: Nice refactoring!

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala [hunk 2]
```diff
@@ -702,6 +702,10 @@ class TreeUnpickler(reader: TastyReader, nameAtRef: NameRef => TermName, posUnpi
       if (!sym.isType) { // Only terms might have leaky aliases, see the documentation of `checkNoPrivateLeaks`
         sym.info = ta.avoidPrivateLeaks(sym, tree.pos)
       }
+      if ((sym.isClass || sym.is(CaseVal)) && sym.isLocal)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: Why not use `isLocal` instead of `isInaccessibleChildOf` here?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: Because we don't have a parent yet against which to test with `inAccessibleChildOf`
