### PR TITLE
Restore MatchTypeNoCases warning with correct source position

### LINKED ISSUE #23822: Match type reduction does not fail even if selector matches none of the cases
## Compiler version

3.6.2, 3.7.1

## Minimized code

```scala
object MatchTypes {

  type ConstituentPartOf[A] = A match {
    case BigInt => Int
    case String => Char
  }

  def lastPartOf[A](thing: A): ConstituentPartOf[A] = thing match {
    case number: BigInt => (number % 10).toInt
    case string: String => string.charAt(string.length - 1)
  }

  def main(args: Array[String]): Unit = {
    val lastPartOfSomethingElse = lastPartOf(BigDecimal("10"))
    println(lastPartOfSomethingElse)
  }
}
```

## Output

Program compiles succesfully (which it shouldn't), and throws an exception at runtime:

```scala
Exception in thread "main" scala.MatchError: 10 (of class scala.math.BigDecimal)
	at MatchTypes$.lastPartOf(MatchTypes.scala:10)
	at MatchTypes$.main(MatchTypes.scala:14)
	at MatchTypes.main(MatchTypes.scala)
```

## Expectation

It should throw a compilation error as it does in scala 3.3.6

Image

### LINKED ISSUE #24753: `MatchTypeNoCases` is no longer emitted
`MatchTypeNoCases` error defined at 
https://github.com/scala/scala3/blob/f67a1a0d91dc154b0f5e934a1b1e5e8cc5a508c1/compiler/src/dotty/tools/dotc/reporting/messages.scala#L3311-L3314
originally used in 
https://github.com/scala/scala3/blob/f67a1a0d91dc154b0f5e934a1b1e5e8cc5a508c1/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L3955-L3963 
is still commented out. It makes this error code effectively inactive. 

The mentioned test is still commented out 
https://github.com/scala/scala3/blob/f67a1a0d91dc154b0f5e934a1b1e5e8cc5a508c1/tests/warn/12974.scala#L22-L34

## Compiler version
3.7.4 
3.8.1-nightly

## Expectation
It's been almost 2 years since this error message was suppressed we should either restore the original mechanism or make the error formally inactive. 

Maybe related discussion in https://github.com/scala/scala3/issues/23822

### PR DESCRIPTION
**Pull request by dancewithheart**
Fixes #24753  
Fixes #23822

## LLM usage

Moderately - used to help navigate the codebase and draft the initial approach.

## Testing

Tested locally with:
- `sbt --error "testCompilation 23822"`
- `sbt --error "testCompilation 12974"`
- `sbt --error "testCompilation i12049"`
- `sbt --error "testCompilation matchtype-seq"`

## Change

Restore emission of `MatchTypeNoCases` in `TypeComparer.matchCases`
when match type reduction reaches the no-match branch.

The warning is emitted only when:
- a real source position exists
- positions are being read
- the owner is a term
- the scrutinee is not an intermediate `TypeVar`
- the compiler is in `typer`
- no errors have already been reported

This avoids repeated internal warnings while restoring the user-visible diagnostic.

Examples:
- `tests/warn/12974.scala`
- `tests/warn/i23822.scala`

~~I'm trying to sign the Scala CLA at : https://contribute.akka.io/cla/scala but ATM I get HTTP 500.~~

### CODE REVIEW

**Comment by Gedochao** [comment]
> I also trying to sign the Scala CLA at : https://contribute.akka.io/cla/scala but ATM I get HTTP 500.

It seems there is a bug with the CLA service, as the CLA check seems to be passing.
I think this has been reported before.
cc @SethTisue @lrytz

**Comment by dancewithheart** [comment]
Replaced de-duplicate check using Set, with condition:
* `pos.exists` =>  only a real source position
* `Mode.ReadPositions` => only when positions are being read (not in internal contexts)
* `ctx.owner.isTerm` => only term-level
* `!TypeVar` => no intermediate TypeVar states

This solves failing tests for `sbt "testCompilation matchtype-seq"`

**Comment by lrytz** [comment]
> It seems there is a bug with the CLA service, as the CLA check seems to be passing.

Right, I think this was reported before. People see an http 500, but the signature is still recorded. https://contribute.akka.io/contribute/cla/scala/check/dancewithheart

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -3974,10 +3974,22 @@ class MatchReducer(initctx: Context) extends TypeComparer(initctx) {
...
-        report.warning(reporting.MatchTypeNoCases(noCasesText), pos = ???)
-        */
+        val pos = ctx.source.atSpan(ctx.owner.span)
+        val isStableScrut = !scrut.isInstanceOf[TypeVar]
+        val noErrorYet = !ctx.reporter.hasErrors
+
+        // Emit warn for user-facing term-level typing, and avoid intermediate / redundant reports
+        val doEmit =
+          pos.exists
+            && ctx.mode.is(Mode.ReadPositions)
```
Comment (bracevac) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: This doesn't look right. The mode is used when reading source positions from tasty. When we just compile from source, this will not trigger.
You can see this with `sbt "scalac tests/warn/i23822.scala‎` (NO warning) vs. `sbt "scalac -Xsemanticdb tests/warn/i23822.scala‎` (shows warning).

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -3974,10 +3974,22 @@ class MatchReducer(initctx: Context) extends TypeComparer(initctx) {
             MatchTypeTrace.emptyScrutinee(scrut)
             NoType
       case Nil =>
-        /* TODO warn ? then re-enable warn/12974.scala:26
         val noCasesText = MatchTypeTrace.noMatchesText(scrut, cases)
-        report.warning(reporting.MatchTypeNoCases(noCasesText), pos = ???)
-        */
+        val pos = ctx.source.atSpan(ctx.owner.span)
+        val isStableScrut = !scrut.isInstanceOf[TypeVar]
+        val noErrorYet = !ctx.reporter.hasErrors
```
Comment (bracevac) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I think this will suppress the warning if there is any other unrelated error in the same file. Maybe drop this?

**Review by bracevac — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (dancewithheart) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Thank you for explanation :bowing_man: 
Removed this condition - locally tests are passing and warning is emitted with Xsemanticdb and without.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 2 above)
Comment (dancewithheart) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Removing this condition, breaks tests/neg/i12049.scala. On top of existing errors:

```
-- [E007] Type Mismatch Error: tests/neg/i12049.scala:14:17 --------------------
14 |val y3: String = ??? : Last[Int *: Int *: Boolean *: String *: EmptyTuple]  // error
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                 Found:    Last[EmptyTuple]
   |                 Required: String
   |
   |                 Note: a match type could not be fully reduced:
   |
   |                   trying to reduce  Last[EmptyTuple]
   |                   failed since selector EmptyTuple
   |                   matches none of the cases
   |
   |                     case _ *: _ *: t => Last[t]
   |                     case t *: EmptyTuple => t
   |
   | longer explanation available when compiling with `-explain`
-- [E007] Type Mismatch Error: tests/neg/i12049.scala:22:20 --------------------
22 |val z3: (A, B, A) = ??? : Reverse[(A, B, A)] // error
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^
   | Found:    Tuple.Concat[Reverse[A *: EmptyTuple.type], (B, A)]
   | Required: (A, B, A)
   |
   | Note: a match type could not be fully reduced:
   |
   |   trying to reduce  Tuple.Concat[Reverse[A *: EmptyTuple.type], (B, A)]
   |   trying to reduce  Reverse[A *: EmptyTuple.type]
   |   failed since selector A *: EmptyTuple.type
   |   matches none of the cases
   |
   |     case t1 *: t2 *: ts => Tuple.Concat[Reverse[ts], (t2, t1)]
   |     case EmptyTuple => EmptyTuple
   |
   | longer explanation available when compiling with `-explain`
```
there are new warnings enabled by this PR - but they feel redundant:
```
-- [E184] Type Warning: tests/neg/i12049.scala:14:4 ----------------------------
14 |val y3: String = ??? : Last[Int *: Int *: Boolean *: String *: EmptyTuple]  // error
   |    ^
   |    Match type reduction failed since selector EmptyTuple
   |    matches none of the cases
   |
   |        case _ *: _ *: t => Last[t]
   |        case t *: EmptyTuple => t
-- [E184] Type Warning: tests/neg/i12049.scala:22:4 ----------------------------
22 |val z3: (A, B, A) = ??? : Reverse[(A, B, A)] // error
   |    ^
   |    Match type reduction failed since selector A *: EmptyTuple.type
   |    matches none of the cases
   |
   |        case t1 *: t2 *: ts => Tuple.Concat[Reverse[ts], (t2, t1)]
   |        case EmptyTuple => EmptyTuple
```
One way would be to update `tests/neg/i12049.check`, I am investigating.

Comment (dancewithheart) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I removed the `hasErrors` condition, following the review feedback.

My current understanding is, that to suppress extra warnings in `tests/neg/i12049` more information from higher-level typing / reporting paths are needed.

I was able to suppress extra warnings in `i12049` when I inspected the stack trace:
```scala
  val fromInferredRhs =
    stack.exists(ste =>
      ste.getMethodName == "rhsType$1" ||
      ste.getMethodName == "cookedRhsType$1" ||
      ste.getMethodName == "inferredResultType" ||
      ste.getMethodName == "typedAheadExpr$$anonfun$1" ||
      ste.getMethodName == "typedAheadType$$anonfun$1"
    )
 ```
this suggest more information needs to be passed from caller site.

My proposition is to:
* keep this PR scoped to restoring `MatchTypeNoCases` warn, as this address:
  * #24753
  * #23822
* handle redundant warn during existing error reporting as a separate follow-up issue
