### PR TITLE
Patch to allow interop with XMLBuilder and -Yexplicit-nulls

### LINKED ISSUE #22914: Can't use `-Yexplicit-nulls` along with XML literals
## Compiler version

3.3.5, 3.4.3, 3.5.2, 3.6.4, and latest nightly 3.7.1-RC1-bin-20250402-a8cf11d-NIGHTLY

## Minimized code

Running `scala-cli` like this:

```bash
scala-cli -Yexplicit-nulls -S 3.6.4 --dep org.scala-lang.modules::scala-xml:2.3.0
```

and then evaluating this code:

```scala
<test />
```

## Output

```scala
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |<test />
  | ^
  |Found:    Null
  |Required: String
  |Note that implicit conversions were not tried because the result of an implicit conversion
  |must be more specific than String
  |
  | longer explanation available when compiling with `-explain`
```

## Expectation

I could use these two features together.

Running with `-Xprint:typer` I can see why the error happens:

```scala
[[syntax trees at end of                     typer]] // rs$line$1
package <empty> {
  final lazy module val rs$line$1: rs$line$1 = new rs$line$1()
  final module class rs$line$1() extends Object() { this: rs$line$1.type =>
    val res0: <error unspecified error> =
      {
        new _root_.scala.xml.Elem(null, "test", _root_.scala.xml.Null,
                               // ^^^^ null passed here
          scala.xml.TopScope, true, [ : scala.xml.Node]*)
      }
  }
}
```

There's probably more to it, but at first glance it looks like a binary compatible fix would require two changes:

1. Updating `scala-xml` to allow an empty string as a prefix: https://github.com/scala/scala-xml/compare/main...mrdziuban:allow-empty-prefix
2. Updating XML literals to use an empty string instead of `null` for the prefix here: https://github.com/scala/scala3/blob/c044420a2a648d12410a9d5e223d9292e547b910/compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala#L213

### PR DESCRIPTION
**Pull request by HarrisL2**
A dirty patch to allow -Yexplicit-nulls to be used along with XML literals

Fixes #22914

### CODE REVIEW

**Comment by olhotak** [comment]
The general idea is to generate `null.asInstanceOf` instead of `null` in the code that the parser/desugar generates from XML literal in calls to the scala-xml library.

See also the discussion at https://github.com/scala/scala-xml/pull/791

**Comment by olhotak** [comment]
@HarrisL2 does this enable running scalatest et al. in the community build with -Yexplicit-nulls?

**Comment by HarrisL2** [comment]
No it doesn't, its based on the main branch so that it doesn't have to be tangled with the community build changes too.

**Comment by noti0na1** [comment]
LGTM, are we able to test this in dotty?

**Comment by HarrisL2** [comment]
> LGTM, are we able to test this in dotty?

Yes, I've added a compilation test for it

**Comment by olhotak** [comment]
I tried running the scalatest tests in the community build and I can confirm that this patch makes all of the XML-related errors in scalatest disappear.

Note that scalatest is currently commented out in the community build for some reason, so I uncommented it.

File: compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala [hunk 1]
```diff
@@ -69,7 +69,11 @@ class SymbolicXMLBuilder(parser: Parser, preserveWS: Boolean)(using Context) {
 
   // convenience methods
   private def LL[A](x: A*): List[List[A]] = List(x.toList)
-  private def const(x: Any) = Literal(Constant(x))
+  private def const(x: Any) =
+    val lit = Literal(Constant(x))
+    if (ctx.explicitNulls && x == null)
+      Select(lit, nme.asInstanceOf_)
+    else lit
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala]:
```suggestion
  private def const(x: String) =
    val lit = Literal(Constant(x))
    if ctx.explicitNulls && x == null 
    then lit.cast(defn.StringType)
    else lit
```

File: compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala:16]:
```suggestion
import Parsers.Parser
import dotty.tools.dotc.ast.tpd.TreeOps
```

File: compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala (hunk 1 above)
Comment (olhotak) [reply compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala]: @noti0na1 Looks like this breaks pickling in the CI.

File: compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala [hunk 2]
```diff
@@ -69,7 +70,11 @@ class SymbolicXMLBuilder(parser: Parser, preserveWS: Boolean)(using Context) {
 
   // convenience methods
   private def LL[A](x: A*): List[List[A]] = List(x.toList)
-  private def const(x: Any) = Literal(Constant(x))
+  private def const(x: Any) =
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala]: Can you change the parameter type to `String` so we don't accidentally pass non-string to `const`?

Comment (HarrisL2) [reply compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala]: When the type is changed to String, there will be a crash in the pickler phase that has to do with calling `toString` on a null value. I'm unsure why, but I've changed it back to Any so that we can get the patch in first.

Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala]: That's weird. Does `String | Null` works? We can keep the `Any`, but can you leave a comment here?

Comment (HarrisL2) [reply compiler/src/dotty/tools/dotc/parsing/xml/SymbolicXMLBuilder.scala]: No, it also does not work. I think it's because the Constant function has different calls depending on the type of the argument, and not typing it as causes a difference in behaviour.
