### PR TITLE
Keep tree of type ascriptions of quote pattern splices

### LINKED ISSUE #18409: Regression in arainko/ducktape: -Wunused:all false-positive in quotes
## Compiler version
3.3.1-RC5
3.4.0-RC1-bin-20230815-ca6a80e-NIGHTLY 
Works in 3.3.0 -version` instead).

Bisect points to b7a7227e55558de2c483731d34b829d2d4018203

## Minimized code

```Scala
//> using options -Wunused:all
import scala.quoted.*

object model {
  trait Transformer[Source, Dest] {
    def transform(from: Source): Dest
  }
  object Transformer {
    trait ForProduct[A, B] extends Transformer[A, B]
  }
}

object Ops {
  import model.Transformer // unused import false-positive

  def unapply(using Quotes)(term: quotes.reflect.Term): Option[String] = {
    term.asExpr match {
      case '{
            ($transformer: Transformer.ForProduct[a, b]).transform($appliedTo)
          } =>
        Some("")
      case other => None
    }
  }
}
```

## Output

```scala
[warn] ./bisect/main.scala:14:16
[warn] unused import
[warn]   import model.Transformer // unused import false-positive
[warn]             
```

## Expectation
Should not mark this import as unused

### PR DESCRIPTION
**Pull request by nicolasstucki**
These trees where removed as part of an optimization. However, they should be kept around to allow for better error messages and IDE navigation.

The type of the ascription in pickled in the TASTy file but is elided in the pickled quote pattern (same optimization already done later).

Fixes #18409

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/PostTyper.scala [hunk 1]
```diff
@@ -492,18 +492,9 @@ class PostTyper extends MacroTransform with InfoTransformer { thisPhase =>
...
           ctx.compilationUnit.needsStaging = true
           super.transform(tree)
-        case _: QuotePattern =>
-          if !ctx.reporter.errorsReported then
-            Checking.checkAppliedTypesIn(TypeTree(tree.tpe).withSpan(tree.span))
-          ctx.compilationUnit.needsStaging = true
-          super.transform(tree)
-        case tree: SplicePattern =>
-          if !ctx.reporter.errorsReported then
-            Checking.checkAppliedTypesIn(TypeTree(tree.tpe).withSpan(tree.span))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/PostTyper.scala:505]: This was a workaround that we added to check the types of the splices because we removed them in `QuotesAndSplices`. Now those types are checked directly on their ASTs.

**Review by jchyb — APPROVED** [review]
LGTM!
