### PR TITLE
Fix infinite loop bug in scaladoc after dotty version bump

### LINKED ISSUE #10166: Doc: infinite loop in implicitly-added member lookup since upgrade from 0.27-RC1
Uncommenting the following lines causes an infinite loop when documenting S3D testcases: https://github.com/dotty-staging/dotty/commit/fd6a59345bddf2e446271735275aba9643de9ec7

This code worked previously on 0.27-RC1.

This seems to be caused by the following classes: https://github.com/dotty-staging/dotty/blob/demo%2Fdoctool-infinite-loop/scala3doc-testcases/src/example/Inheritance.scala#L11-L19.
Specifically, members of example.A.B.D include example.A.B and vice versa.

@nicolasstucki took a glance at our hack to list all members of a class (https://github.com/dotty-staging/dotty/blob/demo%2Fdoctool-infinite-loop/scala3doc/src/dotty/dokka/tasty/SyntheticSupport.scala#L65-L76) and he doesn't see any obvious problem with it.

### PR DESCRIPTION
**Pull request by pikinier20**
closes #10166 

After bump of dotty version there was a problem with infinite loop in member extraction, specifically with extraction of members looking like this:
```Scala
class C extends A
class A:
  class D extends C
```
In new version our code which was used to retrieve inherited methods and fields, returns also classlikes and it led to infinite loop.
This PR fixes this bug by parsing inherited classlikes for signature only (without delving into its members)

### CODE REVIEW

**Review by romanowski — APPROVED** [review]

File: scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala [hunk 1]
```diff
@@ -130,6 +130,11 @@ trait ClassLikeSupport:
       case _ => None
   )
 
+  private def parseInheritedMember(s: Tree): Option[Member] = processTreeOpt(s)(s match
+      case c: ClassDef if c.symbol.shouldDocumentClasslike && !c.symbol.isGiven => Some(parseClasslike(c, signatureOnly = true))
+      case other => parseMember(other)
```
Comment (abgruszecki) [inline scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala:135]: Can we keep the indentation uniform at 2 spaces? Mismatched indentation is a problem when diffing git changes. We'd like to avoid that now that our history is part of Dotty repo.

File: scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala [hunk 2]
```diff
@@ -139,14 +144,13 @@ trait ClassLikeSupport:
...
-      //     case dd: DefDef if !dd.symbol.isClassConstructor && !(dd.symbol.isSuperBridgeMethod || dd.symbol.isDefaultHelperMethod) => dd
-      //     case other => other
-      //   }
-
-      c.membersToDocument.flatMap(parseMember)
-      // ++
-      //   inherited.flatMap(s => parseMember(s).map(_.withOrigin(Origin.InheritedFrom(s.symbol.owner.name, s.symbol.owner.dri))))
+      val inherited = c.getNonTrivialInheritedMemberTrees.collect {
+          case dd: DefDef if !dd.symbol.isClassConstructor && !(dd.symbol.isSuperBridgeMethod || dd.symbol.isDefaultHelperMethod) => dd
+          case other => other
```
Comment (abgruszecki) [inline scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala:149]: See above comment on indentation.

**Review by abgruszecki — COMMENTED** [review]
Aside from indentation nitpick, code LGTM, will merge once CI passes.

File: scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala (hunk 1 above)
Comment (pikinier20) [reply scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala]: fixed indentation

File: scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala (hunk 2 above)
Comment (pikinier20) [reply scala3doc/src/dotty/dokka/tasty/ClassLikeSupport.scala]: fixed

**Review by abgruszecki — APPROVED** [review]
