### PR TITLE
Fix #2973: Check variances of class parents

### LINKED ISSUE #2973: Unsoundness due to missing variance checks for extends clause
This shouldn't compile:
```scala
class Foo[T]
class Bar[-T] extends Foo[T]
```
scalac realises that:
```scala
error: contravariant type T occurs in invariant position in type [-T]Foo[T] {
  def <init>(): Bar[T]
} of class Bar
class Bar[-T] extends Foo[T]
      ^
one error found
````

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix #2973: check variance of parent classes via `ClassInfo.classParents` (via @odersky's fix in #4057).
To account for `@uncheckedVariance` (unlike #4057), prevent `Namer` from stripping annotations in `classParents`. Surprisingly, the rest of Dotty doesn't mind!

We probably should test this on the new collections and the community build, since collections will stress this out much more.

### CODE REVIEW

File: tests/neg/i2973.scala [hunk 1]
```diff
@@ -0,0 +1,2 @@
+class Foo[U]
+class Bar[-T] extends Foo[T] // error: contravariant type T occurs in invariant position
```
Comment (smarter) [inline tests/neg/i2973.scala]: More testcases (related to annotations, etc) would be nice.

Comment (Blaisorblade) [reply tests/neg/i2973.scala]: Can't find any annotation for parent classes apart from `@uncheckedVariance`. So added more tests for that.
