### PR TITLE
Give "did you mean ...?" hints also for simple identifiers

### LINKED ISSUE #17067: Ask did you mean only for accessible members.
## Compiler version

3.3.1-RC1-bin-SNAPSHOT-git-6ad22aa

## Minimized code

```Scala
Welcome to Scala 3.3.1-RC1-bin-SNAPSHOT-git-6ad22aa (19, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> "123".view.reverse.padTo(5, '0').iterator.reverse
-- [E008] Not Found Error: ---------------------------------------------------------------------------------------------
1 |"123".view.reverse.padTo(5, '0').iterator.reverse
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value reverse is not a member of Iterator[Char] - did you mean Iterator[Char].reversed?
1 error found

scala> "123".view.reverse.padTo(5, '0').iterator.reversed
-- [E173] Reference Error: ---------------------------------------------------------------------------------------------
1 |"123".view.reverse.padTo(5, '0').iterator.reversed
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |method reversed in trait IterableOnceOps cannot be accessed as a member of Iterator[Char] from module class rs$line$1$.
  | Access to protected method reversed not permitted because enclosing object rs$line$1
  | is not a subclass of trait IterableOnceOps in package scala.collection where target is defined
1 error found
```

## Output

As shown.

## Expectation

No suggestion of `reversed`, as in Scala 2.

The Scala 2 backport of "did you mean...?" includes further improvements which are worth forward porting.

https://github.com/scala/scala/pull/10262

```
Welcome to Scala 2.13.11-20230306-152152-44c6006 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> "123".view.reverse.padTo(5, '0').iterator.reverse
                                                 ^
       error: value reverse is not a member of Iterator[Char]

scala> "123".view.reverse.padTo(5, '0').it
                                        ^
       error: value it is not a member of scala.collection.View[Char]
       did you mean init or wait? or perhaps inits or tail?
```

where further suggestions are at a farther edit distance.

### LINKED ISSUE #18682: Can we have "did you mean..." for top-level names rather than just methods
## Compiler version

3.3.1

## Minimized example

Mis-typing a method results in a nice suggestion, presumably using Levenshtein distance or something:

Screenshot 2023-10-12 at 10 51 10 PM

But mis-typing a free variable name doesn't:

Screenshot 2023-10-12 at 10 50 48 PM

Could we make mis-typed top level names give nice suggestions too? Presumably we already know everything that is in scope, and can do a Levenshtein distance comparison to find any that look close enough to suggest

### PR DESCRIPTION
**Pull request by odersky**
Fixes #18682
Fixes #17067

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 1]
```diff
@@ -243,14 +244,29 @@ extends NamingMsg(DuplicateBindID) {
...
+    i"Not found: $treeKind$name$addendum"
   def explain(using Context) = {
-    i"""|The identifier for `$treeKind$name` is not bound, that is,
-        |no declaration for this identifier can be found.
-        |That can happen, for example, if `$name` or its declaration has either been
-        |misspelt or if an import is missing."""
+    i"""|Each identifier in Scala needs a matching declaration. There are two kinds of
+        |identifiers: type identifiers and value identifiers. Value identifiers are introduced
+        |by `val`, `def`, or `object` declarations. Type identifiers are introduced by `type`,
+        |`class`, or `trait` declarations.
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:262]:
```suggestion
        |`class`, `enum`, or `trait` declarations.
```

File: tests/neg/yimports-stable.check [hunk 2]
```diff
@@ -3,12 +3,12 @@ error: bad preamble import hello.world.potions
...
   |         ^^^^
-  |         Not found: type Numb
+  |         Not found: type Numb - did you mean Null?
   |
   | longer explanation available when compiling with `-explain`
 -- [E006] Not Found Error: tests/neg/yimports-stable/C_2.scala:4:16 ----------------------------------------------------
 4 |  val v: Numb = magic // error // error
   |                ^^^^^
-  |                Not found: magic
+  |                Not found: magic - did you mean main?
```
Comment (som-snytt) [inline tests/neg/yimports-stable.check:12]: in case you wondered if `@main` is too much magic

If `scala.annotation` were opened by `@syntax`, then annotations there would autocomplete only under `@ma[etc]`.

Comment (odersky) [reply tests/neg/yimports-stable.check:12]: Yes, I like that and did propose it at some point. Failed to convince @sjrd though.
