### PR TITLE
fix(#17255): cannot find Scala companion module from Java

### LINKED ISSUE #17255: Companion object cannot be found from Java in Scala 3, but it compiles in Scala 2.x.
## Compiler version

3.0.2, 3.1.3, 3.2.2, 3.3.0-RC3

## Minimized code

https://github.com/i10416/reproduce-missing-symbol-error-in-scala-3

The following code compiles in Scala 2.x, but won't compile in Scala 3.x for "Not found: type Foo".

src/main/java/Bar.java
```java
package example;

import example.Foo$;

public class Bar {
	// this compiles in Scala 2.x, but won't compile in Scala 3
	private static final Foo$ MOD = Foo$.MODULE$;
}
```

src/main/scala/Foo.scala

```scala
package example

case class Foo(i: Int)

object Foo
```

## Output

```
error] -- [E006] Not Found Error: /path/to/src/main/java/Bar.java:7:21 
[error] 7 |     private static final Foo$ MOD = Foo$.MODULE$;
[error]   |                          ^^^^
[error]   |                          Not found: type Foo
[error]   |
```

## Expectation

It should compile. Or is this expected behavior?

## Note

It compiles in Scala 3 when you explicitly specify `compileOrder := CompileOrder.ScalaThenJava`. However, if there are both Scala code depending on Java and Java code depending Scala, you have no choice but `CompileOrder.Mixed`. 

Notably, even if there are both Scala code depending on Java and Java code depending Scala, Scala 2.x can compile them （in CompileOrder.Mixed mode）.

### PR DESCRIPTION
**Pull request by i10416**
To find Scala companion mudule from Java, we should strip module suffix `$`.
This ~provides workaround~ fixes #17255 as well as forward-port https://github.com/scala/scala/pull/10644. ~, but it requires some refinment to fix it because not-fully-qualified type like the following example still fails to compile due to missing symbol.~

Related to https://github.com/scala/scala/pull/10644

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/ContextOps.scala [hunk 1]
```diff
@@ -55,11 +55,18 @@ object ContextOps:
...
       inContext(ctx) {
-
+        import dotty.tools.dotc.core.NameOps.*
         val preSym = pre.typeSymbol
 
         // 1. Try to search in current type and parents.
-        val directSearch = pre.findMember(name, pre, required, excluded)
+        val directSearch =
+          if name.isTypeName && name.endsWith(StdNames.str.MODULE_SUFFIX) then
+            pre.findMember(name.stripModuleClassSuffix, pre, required, excluded) match
```
Comment (i10416) [inline compiler/src/dotty/tools/dotc/core/ContextOps.scala:64]: It searches for `<root>.Foo$` when I replace `private static final example.Foo$` with `import example.Foo$` and `private static final Foo$`, and results in missing symbol.

Comment (i10416) [reply compiler/src/dotty/tools/dotc/core/ContextOps.scala:63]: NOTE: importing companion object from Java works.

The following example compiles.

```java
package example;

import example.Foo$;

public class Bar {
	private static final example.Foo$ MOD = example.Foo$.MODULE$;
}
```

But the following does not.

```java
package example;

import example.Foo$;

public class Bar {
	private static final Foo$ MOD = Foo$.MODULE$;
}
```

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/core/ContextOps.scala:63]: There is a different code path fro a raw identifier like `Foo$` look in `findRef`

Comment (i10416) [reply compiler/src/dotty/tools/dotc/core/ContextOps.scala]: Thank you!

File: compiler/src/dotty/tools/dotc/core/ContextOps.scala [hunk 2]
```diff
@@ -59,13 +59,16 @@ object ContextOps:
...
-          if name.isTypeName && name.endsWith(StdNames.str.MODULE_SUFFIX) then
-            pre.findMember(name.stripModuleClassSuffix, pre, required, excluded) match
-              case NoDenotation => NoDenotation
-              case symDenot: SymDenotation =>
-                symDenot.companionModule.denot
-          else
-            pre.findMember(name, pre, required, excluded)
+          def asModule =
+            if name.isTypeName && name.endsWith(StdNames.str.MODULE_SUFFIX) then
+              pre.findMember(name.stripModuleClassSuffix, pre, required, excluded) match
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/core/ContextOps.scala:64]: I suggest to convert the name to a `moduleClassName` (after stopping the suffix), in that case you should hopefully find the real module class in scope
```suggestion
              pre.findMember(name.stripModuleClassSuffix.moduleClassName, pre, required, excluded) match
```

**Comment by i10416** [comment]
CI is failing because of https://github.com/lampepfl/dotty/issues/19772

**Comment by bishabosha** [comment]
Hello, thank you for opening this! I am getting to it

File: tests/run/i17255/J.java [hunk 3]
```diff
@@ -0,0 +1,13 @@
+package p;
+
+public class J {
+	public static J j = new J();
+	public static p.J f() {
+		return p.J.j;
+	}
+	public static p.Module$ module() {
```
Comment (bishabosha) [inline tests/run/i17255/J.java:8]: This ends up being incorrectly typed as `p.Module` (i.e. the class) rather than `p.Module.type`

Comment (bishabosha) [inline tests/run/i17255/J.java:8]: should also test the case without a package prefix, because this activates a different code path (findRef), and is actually correctly typed as (p.Module.type).
```suggestion
	public static Module$ module2() {
		return p.Module$.MODULE$;
	}
	public static p.Module$ module() {
```

File: tests/run/i17255/Module.scala [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+
+package p {
+  object Module {
+    override def toString = "Module"
+  }
+}
+
+object Test extends App {
+  assert(p.J.f().toString == "J")
+  assert(p.J.module().toString == "Module")
```
Comment (bishabosha) [inline tests/run/i17255/Module.scala:11]:
```suggestion
  assert(p.J.module().toString == "Module")
  assert(p.J.module2().toString == "Module")
```

File: tests/run/i17255/J.java (hunk 3 above)
Comment (bishabosha) [reply tests/run/i17255/J.java:8]: When the tree reaches TASTy, this looks like
```
    87:       DEFDEF(12) 16 [module]
    90:         EMPTYCLAUSE
    91:         SELECTtpt 17 [Module$] // should be SELECTtpt 19 [Module[ModuleClass]]
    93:           SHAREDtype 3
    95:         ELIDED
    96:           TYPEREF 19 [Module[ModuleClass]]
    98:             SHAREDtype 3
   100:         STATIC
```

Comment (bishabosha) [reply tests/run/i17255/J.java:8]: also the tree ends up being 
```
   101:       DEFDEF(12) 20 [module2]
   104:         EMPTYCLAUSE
   105:         IDENTtpt 17 [Module$]
   107:           TYPEREF 19 [Module[ModuleClass]]
   109:             SHAREDtype 12
   111:         ELIDED
   112:           SHAREDtype 107
   114:         STATIC
```
where `105` would ideally become `IDENTtpt 19 [Module[ModuleClass]`

Comment (bishabosha) [reply tests/run/i17255/J.java:11]: can leave this to follow-up, as it is still better than status quo. However this does rely on the compiler (aka all TASTy clients) intrinsically knowing how to resolve `Module$` when the definition is actually `Module[ModuleClass]`

Comment (bishabosha) [reply tests/run/i17255/J.java:11]: new issue https://github.com/lampepfl/dotty/issues/19806

**Comment by bishabosha** [comment]
Thank you very much for contributing this fix! its been a long time since you opened that issue originally

File: tests/run/i17255/J.java (hunk 3 above)
Comment (i10416) [reply tests/run/i17255/J.java:11]: Thank you for reviewing. I will investigate #19806 too.

Comment (i10416) [reply tests/run/i17255/J.java:11]: I'm not familiar with TASTy, so it may take a while...

Comment (bishabosha) [reply tests/run/i17255/J.java:11]: The way to solve this is in `typedSelect` replacing the name in the `Select` tree, like you did in `javaFindMember`

Comment (i10416) [reply tests/run/i17255/J.java:11]: How can I test TASTy?

Comment (bishabosha) [reply tests/run/i17255/J.java:11]: you can do it manually with the `-Yprint-tasty` flag which will print any generated TASTy after pickler phase, make sure you use the required `-Yjava-tasty` also so that you generate tasty for java sources
