### PR TITLE
Fix #1652: Make assertion more robust

### LINKED ISSUE #1652: crash with assertion failed: bad inst
$ cat abc.scala
```
object Test {
  val v: Array[Array[Array]] = Array()
  def f[T](w: Array[Array[T]]) = { for (r <- w) () }
  f(v)
}

```

$ dotc abc.scala
```

exception occurred while typechecking abc.scala

exception occurred while compiling abc.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: bad inst T := X0, constr = Constraint(
 uninstVars = T, T;
 constrained types =
  [dotty$DottyPredef$arrayTag$$T] => (implicit ctag: scala.reflect.ClassTag[T])scala.reflect.ClassTag[Array[T]]
, [dotty$DottyPredef$arrayTag$$T] => (implicit ctag: scala.reflect.ClassTag[T])scala.reflect.ClassTag[Array[T]]
 bounds =
     T >: [X0] => Array[X0] <: Array[T]
     T = X0
 ordering =
)
	at scala.Predef$.assert(Predef.scala:165)
	at dotty.tools.dotc.core.Types$TypeVar.instantiate(Types.scala:2917)
	at dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.dotty$tools$dotc$typer$Inferencing$IsFullyDefinedAccumulator$$instantiate(Inferencing.scala:73)
	at dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:95)
	at dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.process(Inferencing.scala:116)
	at dotty.tools.dotc.typer.Inferencing$.isFullyDefined(Inferencing.scala:35)
	at dotty.tools.dotc.typer.Inferencing$.fullyDefinedType(Inferencing.scala:44)
	at dotty.tools.dotc.typer.Implicits$class.synthesizedClassTag(Implicits.scala:486)
	at dotty.tools.dotc.typer.Typer.synthesizedClassTag(Typer.scala:62)
	at dotty.tools.dotc.typer.Implicits$class.inferImplicitArg(Implicits.scala:459)
	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:62)
	at dotty.tools.dotc.typer.Typer$$anonfun$36.apply(Typer.scala:1765)
<snipped>
```

### PR DESCRIPTION
**Pull request by odersky**
An assertion fired giving a false negative after a fuzzing
test which introduced an ill-kinded type argument.

Fixes #1652. Review by @felixmulder?

### CODE REVIEW

File: src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -2527,6 +2527,8 @@ object Types {
       case _: MethodType => true
       case _ => false
     }
+    
+    def isTypeLambda: Boolean = variances.nonEmpty
```
Comment (felixmulder) [inline src/dotty/tools/dotc/core/Types.scala]: It would be nice to have a comment here, since it's not clear exactly why a `PolyType` is a type lambda if the variances are non-empty. Is it because a `PolyType` without parameters is not a type lambda?
