### PR TITLE
Keep annotation order

### LINKED ISSUE #14743: order of annotations in produced bytecode is not deterministic
This issue is not complete yet, but I wanted to get it out there before I lose track myself :)

Testing with Scala 3.1.1, it seems the same source code may lead to different orderings of annotations and imports in the resulting bytecode. For example for [the following sources](https://github.com/akka/akka/blob/v2.6.19/akka-actor-typed/src/main/scala-jdk-9/akka/actor/typed/internal/jfr/Events.scala):

```
package akka.actor.typed.internal.jfr

import jdk.jfr.Category
import jdk.jfr.Enabled
import jdk.jfr.Event
import jdk.jfr.Label
import jdk.jfr.StackTrace

import akka.annotation.InternalApi

(... snip ...)

/** INTERNAL API */
@InternalApi
@Enabled(true)
@StackTrace(false)
@Category(Array("Akka", "Delivery", "ConsumerController")) @Label("Delivery ConsumerController producer changed")
final class DeliveryConsumerChangedProducer(val producerId: String) extends Event
```

we saw the following (decompiled-again with `procyon -ec`) bytecode on one compilation:

```
package akka.actor.typed.internal.jfr

import akka.annotation.InternalApi
import jdk.jfr.Enabled
import jdk.jfr.Label
import jdk.jfr.StackTrace
import jdk.jfr.Category
import jdk.jfr.Event

@Category({ "Akka", "Delivery", "ConsumerController" })
@StackTrace(false)
@Label("Delivery ConsumerController producer changed")
@Enabled(true)
@InternalApi
public final class DeliveryConsumerChangedProducer extends Event
```

but on another machine:

```
package akka.actor.typed.internal.jfr

import akka.annotation.InternalApi
import jdk.jfr.StackTrace
import jdk.jfr.Enabled
import jdk.jfr.Category
import jdk.jfr.Label
import jdk.jfr.Event

@Label("Delivery ConsumerController producer changed")
@Category({ "Akka", "Delivery", "ConsumerController" })
@Enabled(true)
@StackTrace(false)
@InternalApi
public final class DeliveryConsumerChangedProducer extends Event
```

I seem to remember seeing a similar issue in Scala 2, but can't find a reference right now.

I'll try and dig up further details, and test with a more recent version of scala3, later.

### PR DESCRIPTION
**Pull request by raboof**
This change makes sure non-repeated annotations are kept in the order
they were found in the source code.

The motivation is not necessarily to have them in the original order,
but to have them in an order that is deterministic across rebuilds
(potentially even across different machines), for reasons discussed
further in #7661 and the corresponding scala/scala-dev#405

I tried adding an 'integration test' in `tests/pos` to be picked up by `IdempotencyCheck.scala`, but unfortunately couldn't reproduce the nondeterminism that way ~, so didn't end up including it in this commit~.

I didn't see an obvious place for a 'unit test' of this code, I'd be
happy to add one when someone can recommend a good place to put it.

This is basically the dotty equivalent of
https://github.com/scala/scala/commit/954c5d32d71a43b141be546877b01183a994a1b2

Fixes #14743

### CODE REVIEW

**Comment by smarter** [comment]
> I tried adding an 'integration test' in tests/pos to be picked up by
IdempotencyCheck.scala, but unfortunately couldn't reproduce the
nondeterminism that way, so didn't end up including it in this commit.

I think it's worth adding a test even if you can't get it to fail for reference here, can you reproduce the problem by manually compiling that file multiple times?

File: tests/pos/Annotations.scala [hunk 1]
```diff
@@ -0,0 +1,8 @@
+package foo.bar
+
+import jdk.jfr.Enabled
+
+@Enabled
+@Deprecated
```
Comment (smarter) [inline tests/pos/Annotations.scala:6]: Shouldn't the test involve using the same annotation multiple times to trigger use of RepeatableAnnotations, like in https://github.com/scala/scala/commit/954c5d32d71a43b141be546877b01183a994a1b2#diff-8bd66281732306fbd83125f4c1bba7a81797b9ed31a0857afb0b805dd6e1fe6cR258-R262 ?

**Comment by raboof** [comment]
> > I tried adding an 'integration test' in tests/pos to be picked up by
> > IdempotencyCheck.scala, but unfortunately couldn't reproduce the
> > nondeterminism that way, so didn't end up including it in this commit.
> 
> I think it's worth adding a test even if you can't get it to fail for reference here

Ok, added!

> can you reproduce the problem by manually compiling that file multiple times?

No, unfortunately not...

File: tests/pos/Annotations.scala (hunk 1 above)
Comment (raboof) [reply tests/pos/Annotations.scala:6]: I guess that would *also* be useful to test, though it wasn't the scenario I was aiming to fix: because the 'annotations.groupBy(_.symbol)` doesn't have a predictable order of keys, even regular 'unrepeated' annotations would not necessarily end up in the bytecode in the same order.

Comment (smarter) [reply tests/pos/Annotations.scala:6]: Ah, I didn't realize that this code wasn't simply bypassed when no repeated annotations exist. But yeah, if you could copy the tests that are in the scala 2 PRs that would be nice: to compile multiple files at once (the .java annotation definition and the scala usage) you can create a subdirectory in tests/pos.

Comment (raboof) [reply tests/pos/Annotations.scala:6]: Gotcha, added!

**Review by smarter — APPROVED** [review]

File: tests/annotations1/a.scala [hunk 2]
```diff
@@ -0,0 +1,2 @@
+class Annot1(s: String) extends scala.annotation.StaticAnnotation
```
Comment (griggt) [inline tests/annotations1/a.scala:1]: Are these tests meant to be under `tests/pos/` rather than directly under `tests/`?

Comment (smarter) [reply tests/annotations1/a.scala:1]: oh indeed

**Review by smarter — CHANGES_REQUESTED** [review]

File: tests/annotations1/a.scala (hunk 2 above)
Comment (raboof) [reply tests/annotations1/a.scala]: Oops, updated

**Review by griggt — APPROVED** [review]
