### PR TITLE
Fix for constraining dependent parameter references

### LINKED ISSUE #12803: Method type parameter not inferred when given a dependent type
## Compiler version

3.0.1-RC1

## Minimized code

```Scala
trait X {
  type Y
}

trait E[A]

trait Test {
  val x: X
  def wrap(x: X): E[x.Y] = ???
  def run[I](i: E[I]): Unit = ???
  run(wrap(x))
}
```

## Output

```scala
[error] -- [E007] Type Mismatch Error: /Users/adamw/projects/tapir/client/tests/src/main/scala/sttp/tapir/client/tests/ClientStreamingTests.scala:35:10
[error] 35 |  run(wrap(x))
[error]    |      ^^^^^^^
[error]    |      Found:    sttp.tapir.client.tests.E[Test.this.x.Y]
[error]    |      Required: sttp.tapir.client.tests.E[?1.Y]
[error]    |
[error]    |      where:    ?1 is an unknown value of type sttp.tapir.client.tests.X
[error] Explanation
[error] ===========
[error]
[error] I tried to show that
[error]   sttp.tapir.client.tests.E[Test.this.x.Y]
[error] conforms to
[error]   sttp.tapir.client.tests.E[?1.Y]
[error] but the comparison trace ended with `false`:
[error]
[error]   ==> sttp.tapir.client.tests.E[Test.this.x.Y]  <:  sttp.tapir.client.tests.E[?1.Y]
[error]     ==> sttp.tapir.client.tests.E[Test.this.x.Y]  <:  sttp.tapir.client.tests.E[?1.Y] (recurring)
[error]       ==> ?1.Y  <:  Test.this.x.Y
[error]         ==> ?1.Y  <:  Test.this.x.Y (recurring)
[error]           ==> ?1.Y  <:  Test.this.x.Y (recurring)
[error]             ==> (?1 : sttp.tapir.client.tests.X)  <:  (Test.this.x : sttp.tapir.client.tests.X)
[error]               ==> (?1 : sttp.tapir.client.tests.X)  <:  (Test.this.x : sttp.tapir.client.tests.X) (recurring)
[error]                 ==> sttp.tapir.client.tests.X  <:  (Test.this.x : sttp.tapir.client.tests.X) (left is approximated)
[error]                   ==> sttp.tapir.client.tests.X  <:  (Test.this.x : sttp.tapir.client.tests.X) (recurring)
[error]                   <== sttp.tapir.client.tests.X  <:  (Test.this.x : sttp.tapir.client.tests.X) (recurring) = false
[error]                 <== sttp.tapir.client.tests.X  <:  (Test.this.x : sttp.tapir.client.tests.X) (left is approximated) = false
[error]               <== (?1 : sttp.tapir.client.tests.X)  <:  (Test.this.x : sttp.tapir.client.tests.X) (recurring) = false
[error]             <== (?1 : sttp.tapir.client.tests.X)  <:  (Test.this.x : sttp.tapir.client.tests.X) = false
[error]             ==> Any  <:  Test.this.x.Y (left is approximated)
[error]               ==> Any  <:  Test.this.x.Y (recurring)
[error]               <== Any  <:  Test.this.x.Y (recurring) = false
[error]             <== Any  <:  Test.this.x.Y (left is approximated) = false
[error]           <== ?1.Y  <:  Test.this.x.Y (recurring) = false
[error]         <== ?1.Y  <:  Test.this.x.Y (recurring) = false
[error]       <== ?1.Y  <:  Test.this.x.Y = false
[error]     <== sttp.tapir.client.tests.E[Test.this.x.Y]  <:  sttp.tapir.client.tests.E[?1.Y] (recurring) = false
[error]   <== sttp.tapir.client.tests.E[Test.this.x.Y]  <:  sttp.tapir.client.tests.E[?1.Y] = false
[error]
[error] The tests were made under a constraint with:
[error]  uninstantiated variables:
[error]  constrained types: [I](i: sttp.tapir.client.tests.E[I]): Unit
[error]  bounds:
[error]      I := ?1.Y
[error]  ordering:
[error] one error found
```

## Expectation

Compile without errors :)

The above compiles fine using 2.13.

With Scala 3, the type parameter needs to be provided explicitly:

```scala
run[x.Y](wrap(x))
```

### PR DESCRIPTION
**Pull request by odersky**
We were too fast skolemizing the argument type as lower bound for a dependent parameter.
We need to do that only if the argument is unstable.

Fixing this revealed another problem in i6882a.scala, where we now got
confused by instantiating a poly type to a polymorphic function type
that contained the same polytype again. We avaoid that now by creating
a fresh copy of the polytype.

Fixes #12803

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala [hunk 1]
```diff
@@ -348,7 +348,14 @@ trait TypeAssigner {
             }
           }
           else {
-            val argTypes = args.tpes
+            // Make sure arguments don't contain the type `pt` itself.
+            // make a copy of the argument if that's the case.
+            // See pos/i6682a.scala for a test case where this matters.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:353]: I see that this makes -Ycheck pass but I don't understand what this accomplishes conceptually, and if I slightly tweak the testcase I can get it to crash on both master and this branch:
```scala
object O{
  val v = [T] => (y:T) => (x:y.type) => 3
  def m = v(identity(v))
}
```
```scala
*** error while checking tests/pos/i6682a.scala after phase typer ***
exception occurred while compiling tests/pos/i6682a.scala
java.lang.AssertionError: assertion failed:
Found:    [T] => (y: T) => y.type => Int
Required: [T] => (y: Any) => y².type => Int

where:    y  is a reference to a value parameter
          y² is a reference to a value parameter
```
So I suspect there's a deeper issue here?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:353]: The issue is that normally we need to generate fresh copies for every polymorphic type on every usage of that type. But that would lead to a lot of type copying. Type inference generates a fresh copy in ProtoTypes.constrained only if the same type is already in the constraint set. We need something equivalent for tree checkers and other retypers.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: The new problem seems to be unrelated to the old problem and the fix, and seems to indicate that self application of polymorphic function types is a minefield which should be studied in depth. If have opened #13143 for that.

**Review by smarter — APPROVED** [review]
