### PR TITLE
Fix #6588: Dealias inferred quoted types

### LINKED ISSUE #6588: Compiler failed to synthesize `Type[T]` for local type alias `T`
Discovered in #6586, the following code fails to compile:

```Scala
import scala.quoted._

inline def foo[T:Type]: Int = 10

def main = {
  type S = Int
  foo[S]                 // ok
  foo[Int]               // ok

  type T = Int => Int
  foo[T]                 // error
  foo[Int => Int]        // ok

  type U = List[Int]
  foo[U]                // error
  foo[List[Int]]        // ok

  type N = List
  foo[N]               // error
  foo[List]            // ok
}
```

```Scala
-- Error: examples/test.scala:11:8 ---------------------------------------------
11 |  foo[T]                 // error
   |        ^
   |no implicit argument of type quoted.Type[T] was found for parameter evidence$1 of method foo
-- Error: examples/test.scala:15:8 ---------------------------------------------
15 |  foo[U]                // error
   |        ^
   |no implicit argument of type quoted.Type[U] was found for parameter evidence$1 of method foo
-- Error: examples/test.scala:19:8 ---------------------------------------------
19 |  foo[N]               // error
   |        ^
   |no implicit argument of type quoted.Type[N] was found for parameter evidence$1 of method foo
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -673,33 +673,21 @@ trait Implicits { self: Typer =>
...
+     */
     def synthesizedTypeTag(formal: Type): Tree = {
       def quotedType(t: Type) = {
         if (StagingContext.level == 0)
           ctx.compilationUnit.needsStaging = true // We will need to run ReifyQuotes
         ref(defn.InternalQuoted_typeQuote).appliedToType(t)
       }
       formal.argInfos match {
-        case arg :: Nil if !arg.typeSymbol.is(Param) =>
-          object bindFreeVars extends TypeMap {
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: This `TypeMap` is completely useless here. This is already performed by the PCP check in the `Staging` phase which emits errors with extra level information if the implicit is not found.

File: tests/pos/i6588.scala [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+  type N = List
+  foo[N]
+  foo[List]
+
+  type V = List[S]
+  foo[V]
+
+  type B = V => T
+  foo[B]
```
Comment (nicolasstucki) [inline tests/pos/i6588.scala]: The code generated for the type tags is now
```scala
def main: Int = 
      {
        type S = Int
        {
          val evidence$1: quoted.Type[Int] = scala.quoted.Type.IntTag
          10:Int
        }
        {
          val evidence$1: quoted.Type[Int] = scala.quoted.Type.IntTag
          10:Int
        }
        type T = Function1[Int, Int]
        {
          val evidence$1: quoted.Type[Int => Int] = '[Int => Int]
          10:Int
        }
        {
          val evidence$1: quoted.Type[Int => Int] = '[Int => Int]
          10:Int
        }
        type U = List[Int]
        {
          val evidence$1: quoted.Type[List[Int]] = '[List[Int]]
          10:Int
        }
        {
          val evidence$1: quoted.Type[List[Int]] = '[List[Int]]
          10:Int
        }
        type N = List
        {
          val evidence$1: quoted.Type[List] = '[List]
          10:Int
        }
        {
          val evidence$1: quoted.Type[List] = '[List]
          10:Int
        }
        type V = List[S]
        {
          val evidence$1: quoted.Type[List[Int]] = '[List[Int]]
          10:Int
        }
        type B = Function1[V, T]
        {
          val evidence$1: quoted.Type[List[Int] => Int => Int] = 
            '[List[Int] => Int => Int]
          10:Int
        }
      }

```

Comment (nicolasstucki) [reply tests/pos/i6588.scala]: After the second commit, we get
```scala
      ...
      type V = List[S]
      {
        10:Int
      }
      type B = Function1[V, T]
      {
        10:Int
      }
```

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 3]
```diff
@@ -388,7 +388,7 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
     case New(_) | Closure(_, _, _) =>
       Pure
     case TypeApply(fn, _) =>
-      if (fn.symbol.is(Erased)) Pure else exprPurity(fn)
+      if (fn.symbol.is(Erased) || fn.symbol == defn.InternalQuoted_typeQuote) Pure else exprPurity(fn)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: Should we have some internal flag to mark those methods?

**Comment by nicolasstucki** [comment]
Rebased
