### PR TITLE
Erase `Int | Nothing` signatures types into `Int`

### LINKED ISSUE #14964: Tuple.toList.toArray raise java.lang.ClassCastException
## Compiler version

Scala 3.1.0, Scala 3.1.1, Scala 3.1.2 RC1, Scala 3.1.2

## Minimized code

```Scala
val xs = (1, 2).toList
val a1 = xs.toArray              // fine
println((1, 2).toList.toArray)  // this works without exception, but the result is wrong: get a [Ljava.lang.Object rather than [I@
val a2 = (1, 2).toList.toArray // java.lang.ClassCastException
```

## Output

```scala
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [I ([Ljava.lang.Object; and [I are in module java.base of loader 'bootstrap')
  ... 65 elided
java.lang.NoClassDefFoundError: Could not initialize class rs$line$1$
  at rs$line$1.a1(rs$line$1)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at dotty.tools.repl.Rendering.$anonfun$4(Rendering.scala:110)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.Rendering.valueOf(Rendering.scala:110)
  at dotty.tools.repl.Rendering.renderVal(Rendering.scala:139)
  at dotty.tools.repl.ReplDriver.$anonfun$10(ReplDriver.scala:335)
  at scala.collection.immutable.List.flatMap(List.scala:293)
  at scala.collection.immutable.List.flatMap(List.scala:79)
  at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:335)
  at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:358)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:361)
  at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:280)
  at scala.util.Either.fold(Either.scala:189)
  at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:296)
  at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:230)
  at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:162)
  at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:165)
  at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:186)
  at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:174)
  at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
  at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:174)
  at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:165)
  at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
  at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:233)
  at sbt.Console.console0$1(Console.scala:64)
  at sbt.Console.$anonfun$apply$5(Console.scala:74)
  at sbt.Run$.executeSuccess(Run.scala:186)
  at sbt.Console.$anonfun$apply$4(Console.scala:74)
  at sbt.internal.util.Terminal.withRawInput(Terminal.scala:145)
  at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:143)
  at sbt.internal.util.Terminal$ProxyTerminal$.withRawInput(Terminal.scala:384)
  at sbt.Console.$anonfun$apply$3(Console.scala:74)
  at sbt.internal.util.Terminal$TerminalImpl.withRawOutput(Terminal.scala:975)
  at sbt.internal.util.Terminal$ProxyTerminal$.withRawOutput(Terminal.scala:423)
  at sbt.Console.apply(Console.scala:71)
  at sbt.Console.apply(Console.scala:49)
  at sbt.Console.apply(Console.scala:41)
  at sbt.Defaults$.$anonfun$consoleTask$1(Defaults.scala:2232)
  at sbt.Defaults$.$anonfun$consoleTask$1$adapted(Defaults.scala:2218)
  at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
  at sbt.std.Transform$$anon$4.work(Transform.scala:68)
  at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
  at sbt.Execute.work(Execute.scala:291)
  at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.NoClassDefFoundError: Could not initialize class rs$line$1$
  at rs$line$1.a2(rs$line$1)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at dotty.tools.repl.Rendering.$anonfun$4(Rendering.scala:110)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.Rendering.valueOf(Rendering.scala:110)
  at dotty.tools.repl.Rendering.renderVal(Rendering.scala:139)
  at dotty.tools.repl.ReplDriver.$anonfun$10(ReplDriver.scala:335)
  at scala.collection.immutable.List.flatMap(List.scala:293)
  at scala.collection.immutable.List.flatMap(List.scala:79)
  at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:335)
  at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:358)
  at scala.Option.map(Option.scala:242)
  at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:361)
  at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:280)
  at scala.util.Either.fold(Either.scala:189)
  at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:296)
  at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:230)
  at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:162)
  at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:165)
  at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:186)
  at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:174)
  at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
  at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:174)
  at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:165)
  at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
  at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:233)
  at sbt.Console.console0$1(Console.scala:64)
  at sbt.Console.$anonfun$apply$5(Console.scala:74)
  at sbt.Run$.executeSuccess(Run.scala:186)
  at sbt.Console.$anonfun$apply$4(Console.scala:74)
  at sbt.internal.util.Terminal.withRawInput(Terminal.scala:145)
  at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:143)
  at sbt.internal.util.Terminal$ProxyTerminal$.withRawInput(Terminal.scala:384)
  at sbt.Console.$anonfun$apply$3(Console.scala:74)
  at sbt.internal.util.Terminal$TerminalImpl.withRawOutput(Terminal.scala:975)
  at sbt.internal.util.Terminal$ProxyTerminal$.withRawOutput(Terminal.scala:423)
  at sbt.Console.apply(Console.scala:71)
  at sbt.Console.apply(Console.scala:49)
  at sbt.Console.apply(Console.scala:41)
  at sbt.Defaults$.$anonfun$consoleTask$1(Defaults.scala:2232)
  at sbt.Defaults$.$anonfun$consoleTask$1$adapted(Defaults.scala:2218)
  at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
  at sbt.std.Transform$$anon$4.work(Transform.scala:68)
  at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
  at sbt.Execute.work(Execute.scala:291)
  at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
```

## Expectation
Both works

### LINKED ISSUE #14970: Erasure of `Int | Nothing`
## Compiler version

3.1.3

## Minimized example

```Scala
def foo: Int | Nothing  = 1
```

## Output

```scala
def foo(): Object = scala.Int.box(1)
```

## Expectation

`Int | Nothing` should erase to `int`

### PR DESCRIPTION
**Pull request by nicolasstucki**
Aligns `| Nothing` with `& Any` and `Nothing |` with `Any &` for value types.

This also fixes `summon[ClassTag[Int | Nothing]]` as it is now equivalent to `summon[ClassTag[Int]]`.

This applies to all value types.

Fixes #14970
Fixes #14964

> :warning: This is a binary breaking change :warning:
>
> the Previous version generated the `def f: Int` and `def f: Object` variants of the method.
> In the new one, we only generate the `def f: Int` version.
> Unfortunately, the previous version called the boxed version of the interface that does not exist anymore.
>
> Is this something that we encounter in practice?

### CODE REVIEW

**Comment by nicolasstucki** [comment]
As far as I can see, the `Int | Nothing` pattern should not appear in any user code. If this is the case then changing it should not impact signatures in real code. It will impact the `ClassTag` by fixing cases that were buggy.

I would argue that this erasure is a bug and should be fixed. If a library accidentally used this and cares about binary compatibility, they can add the bridge themselves.

**Comment by sjrd** [comment]
> they can add the bridge themselves.

I don't think that's possible. How would they do that? It would result in an ambiguous overload, wouldn't it?

**Comment by nicolasstucki** [comment]
>> they can add the bridge themselves.

> I don't think that's possible. How would they do that? It would result in an ambiguous overload, wouldn't it?

Indeed 😞

**Comment by smarter** [comment]
You can avoid ambiguous overload errors by relying on `@targetName`:
```scala
import scala.annotation.targetName
class A:
  def foo: Int = 1
  @targetName("foo") def fooBinCompat: Any = 1
```

**Comment by smarter** [comment]
... but that's not good enough for library authors in general as a workaround to binary compatibility breakages, because their methods might be overrridden in user code as @sjrd pointed out last time I wanted to break binary compatibility :grimacing:

**Comment by nicolasstucki** [comment]
Then the real question is if there are libraries that use these types in their signatures.

File: compiler/src/dotty/tools/dotc/core/TypeErasure.scala [hunk 1]
```diff
@@ -365,10 +365,18 @@ object TypeErasure {
   def erasedLub(tp1: Type, tp2: Type)(using Context): Type = {
     // After erasure, C | {Null, Nothing} is just C, if C is a reference type.
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeErasure.scala:366]: I think this logic has gotten a bit messy and can be simplified. Why not:
```scala
if tp1.isRef(defn.NothingClass)
    || tp1.isRef(defn.NullClass) && tp2.derivesFrom(defn.ObjectClass))
then return tp2
```
And the same for `tp1`.

**Review by odersky — CHANGES_REQUESTED** [review]
I would hope that A | Nothing would not normally appear in library code. The current behavior looks wrong since it violates the property that `erasure(A | B) = erasure(B)` if `A <: B`.

So I'd tend to go ahead with merging this after the logic is made clearer.

**Comment by smarter** [comment]
> You can avoid ambiguous overload errors by relying on @targetName:

By the way, even if this works around (some) binary-compatibility issues, it can also break tasty-compatibility since we refer to methods by their original names there.

**Comment by nicolasstucki** [comment]
> The current behavior looks wrong since it violates the property that `erasure(A | B) = erasure(B) if A <: B`

I believe it is not violated. With the current behavior, `Int | Nothing` and `Nothing | Int` erase to `Int`.
* `erasure(Int | Nothing) = erasure(Nothing) if Int <: Nothing` the guard does not hold
* `erasure(Nothing | Int) = erasure(Int) if Nothing <: Int` the guard holds and we have the correct erasure

Similarly for `erasure(A | B) = erasure(A) if B <: A`.

**Comment by nicolasstucki** [comment]
Apart from signatures and `ClassTag`s is there something else that uses erased lub?

File: tests/run/i14964b.scala [hunk 2]
```diff
@@ -0,0 +1,5 @@
+@main def Test: Unit =
+  println(summon[reflect.ClassTag[Int]]) // classOf[Int]
+  println(summon[reflect.ClassTag[Int | Int]]) // classOf[Int]
+  println(summon[reflect.ClassTag[Int | 1]]) // classOf[Int]
+  println(summon[reflect.ClassTag[Int | Nothing]]) // classOf[Object]
```
Comment (nicolasstucki) [inline tests/run/i14964b.scala:5]:
```suggestion
  println(summon[reflect.ClassTag[Int | Nothing]]) // classOf[Int]
```

**Review by dwijnand — APPROVED** [review]
LGTM

**Comment by nicolasstucki** [comment]
Based on #14998, the only `Nothing | T` `erasedLub` is for `Nothing | Null` which used to erase to `Object` and still erases to `Object`.

**Comment by smarter** [comment]
Breaking binary compatbility likes this sets a bad precedent. Is the current behavior really fundamentally broken or merely inconvenient?

**Comment by nicolasstucki** [comment]
> Breaking binary compatbility likes this sets a bad precedent. Is the current behavior really fundamentally broken or merely inconvenient?



As far as I can see it is only fundamentally broken for the `ClassTag` use case. It seems that the signature side only causes unnecessary boxing. I will investigate further to see if I can find a situation where the signatures break something.

We could do an alternative fix for #14964 that would make the erased lub behave differently if we are computing the erased type for a `ClassTag`.

**Comment by smarter** [comment]
Actually you don't even need ClassTag to run into issues:
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val x: Array[Int | Nothing] = Array()
    val y: Array[Int] = x
  }
}
```
```scala
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I
        at Test$.main(arri.scala:3)
        at Test.main(arri.scala)
```
So yeah, I guess the erasure of union types is just fundamentally broken which would justify changing it :/. If we do change it in 3.2, we could warn in 3.1.3 about any code that relies on it to ease migration.

**Review by odersky — APPROVED** [review]
LGTM

**Comment by bishabosha** [comment]
this will also break backwards tasty compatibility of resolving methods by their signature
