### PR TITLE
Fix #10905: Fix explicitSelf phase

### LINKED ISSUE #10905: NoSuchMethodError for method of extended class with self bound
## Minimized code

```Scala
case class C(x: Int) extends TypeHelpers
abstract class TypeHelpers:
  self: C =>
  def f = x
@main def m = C(0).f
```

## Output (click arrow to expand)
<details>

```scala
java.lang.NoSuchMethodError: TypeHelpers.x()I
	at TypeHelpers.f(main.scala:4)
	at main$package$.m(main.scala:6)
	at m.main(main.scala:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

https://scastie.scala-lang.org/fa5pOcEYSbas04xFxfXvJA

### PR DESCRIPTION
**Pull request by odersky**
We need to rewire also some references that are simple identifiers.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ExplicitSelf.scala [hunk 1]
```diff
@@ -26,18 +23,28 @@ class ExplicitSelf extends MiniPhase {
...
+    cpy.Select(tree)(thiz.cast(AndType(cls.classInfo.selfType, thiz.tpe)), tree.name)
+
   override def transformIdent(tree: Ident)(using Context): Tree = tree.tpe match {
     case tp: ThisType =>
       report.debuglog(s"owner = ${ctx.owner}, context = ${ctx}")
       This(tp.cls).withSpan(tree.span)
-    case _ => tree
+    case TermRef(thisTp: ThisType, _) =>
+      val cls = thisTp.cls
+      if needsCast(tree, cls) then castQualifier(tree, cls, This(cls))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/ExplicitSelf.scala:38]:
```suggestion
      if needsCast(tree, cls) then castQualifier(tree, cls, This(cls).withSpan(tree.span))
```

**Review by liufengyun — APPROVED** [review]
LGTM

File: compiler/src/dotty/tools/dotc/transform/ExplicitSelf.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/ExplicitSelf.scala:38]: It will get the span anyway through the cpy.Select(tree) call.
