### PR TITLE
Fix #5794: eta-expansion triggered properly

### LINKED ISSUE #5794: Dependent FTs example from docs doesn't compile
The following example taken from [docs](https://dotty.epfl.ch/docs/reference/new-types/dependent-function-types.html) failed to type check: 
```scala
  trait Entry { type Key; val key: Key }
  def extractKey(e: Entry): e.Key = e.key
  val extractor: (e: Entry) => e.Key = extractKey
```
with error:

```scala
33 |  val extractor: (e: Entry) => e.Key = extractKey
   |                                       ^^^^^^^^^^
   |                                 missing arguments for method extractKey
```

### PR DESCRIPTION
**Pull request by biboudis**
Previously eta-expansion was not triggered because the refined type-ness wasn't taken under-consideration in two places. 

- `functionArity` was prohibiting the necessary branch to be taken: solved after dropping the refinement
- `isNonDepFunctionType` wasn't checking whether the prototype was a refined type (also renamed method)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 1]
```diff
@@ -1121,15 +1121,15 @@ class Definitions {
   /** Is `tp` (an alias) of either a scala.FunctionN or a scala.ImplicitFunctionN
    *  instance?
    */
-  def isNonDepFunctionType(tp: Type)(implicit ctx: Context): Boolean = {
+  def isNonRefinedFunction(tp: Type)(implicit ctx: Context): Boolean = {
     val arity = functionArity(tp)
     val sym = tp.dealias.typeSymbol
-    arity >= 0 && isFunctionClass(sym) && tp.isRef(FunctionType(arity, sym.name.isImplicitFunction, sym.name.isErasedFunction).typeSymbol)
+    arity >= 0 && isFunctionClass(sym) && tp.isRef(FunctionType(arity, sym.name.isImplicitFunction, sym.name.isErasedFunction).typeSymbol) && !tp.isInstanceOf[RefinedType]
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala]: split this line, it's too long.

**Comment by smarter** [comment]
To make the git history easier to follow, please squash these two commits in one commit, and add the description in https://github.com/lampepfl/dotty/pull/5795#issue-247705088 to the commit message.
