### PR TITLE
Fix #12337: Enable exhaustivity check for case classes with checkable components

### LINKED ISSUE #12337: No warning is trigger for non-exhaustive pattern matching on case class field
## Compiler version
`3.0.0-RC3` from `print scalaVersion` on `sbt` console.

## Minimized code

```Scala
sealed trait Status
object Status {
  case object Active   extends Status
  case object Inactive extends Status
}

final case class Foo(status: Status)
def bar(user: Foo): Unit = user match {
  case Foo(Status.Active) =>
    println("active")
    // no compile-time warning for missing Status.Inactive case
}
```

`scalacOptions` has
```
List(
  "-unchecked",
  "-deprecation",
  "-feature",
  "-Xfatal-warnings"
)
```

**NOTE:**
Replacing the `Status` above with the `enum` like below doesn't make any difference.
```scala
enum Status {
  case Active
  case Inactive
}
```

## Output
It compiles without any warning or error even with `-Xfatal-warnings`, and it results in the following runtime error.

```
[error] (run-main-1) scala.MatchError: Foo(Inactive) (of class kevinlee.Example1$Foo)
[error] scala.MatchError: Foo(Inactive) (of class kevinlee.Example1$Foo)
...
```

## Expectation
The compile-time warning like
```
match may not be exhaustive.
It would fail on the following input: Foo(Inactive)
    def bar(user: Foo): Unit = user match {
```
(or the compile-time error with `"-Xfatal-warnings"` compiler option)

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #12337: Enable exhaustivity check for case classes with checkable components

This aligns with Scala 2 behavior.

### CODE REVIEW

File: tests/patmat/i12337.scala [hunk 1]
```diff
@@ -0,0 +1,12 @@
+sealed trait Status
+object Status {
+  case object Active   extends Status
+  case object Inactive extends Status
```
Comment (Kevin-Lee) [inline tests/patmat/i12337.scala:4]: Can one of these `case object` be `case class` instead to make sure it works for `case class` as well?

e.g.)
```scala
sealed trait Status
object Status {
  case class Active(since: Int) extends Status
  case object Inactive extends Status
}

case class Foo(status: Status)
def bar(user: Foo): Unit = user match {
  case Foo(Status.Active(2000)) =>
    println(s"active since 2000")
}
// Expected:
// warning: match may not be exhaustive.
// It would fail on the following inputs: Foo(Active((x: Int forSome x not in 2000))), Foo(Inactive)
// def bar(user: Foo): Unit = user match {
```

**Review by dwijnand — APPROVED** [review]

**Comment by liufengyun** [comment]
Thanks @dwijnand !
