### PR TITLE
Repl truncation copes with null

### LINKED ISSUE #17333: REPL crash when toString returns null
## Compiler version

3.2.2

## Minimized code

```Scala
scala> class Foo { override def toString = null }
// defined class Foo
                                                                                                                 
scala> new Foo()
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at dotty.tools.repl.Rendering.truncate(Rendering.scala:92)
	at dotty.tools.repl.Rendering.classLoader$$anonfun$1(Rendering.scala:79)
	at dotty.tools.repl.Rendering.classLoader$$anonfun$adapted$1(Rendering.scala:85)
	at dotty.tools.repl.Rendering.replStringOf(Rendering.scala:102)
	at dotty.tools.repl.Rendering.$anonfun$5(Rendering.scala:115)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.repl.Rendering.valueOf(Rendering.scala:115)
	at dotty.tools.repl.Rendering.renderVal(Rendering.scala:157)
	at dotty.tools.repl.ReplDriver.$anonfun$7(ReplDriver.scala:365)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.repl.ReplDriver.extractAndFormatMembers$1(ReplDriver.scala:371)
	at dotty.tools.repl.ReplDriver.renderDefinitions$$anonfun$2(ReplDriver.scala:403)
	at scala.Option.map(Option.scala:242)
	at dotty.tools.repl.ReplDriver.renderDefinitions(ReplDriver.scala:409)
	at dotty.tools.repl.ReplDriver.compile$$anonfun$2(ReplDriver.scala:307)
	at scala.util.Either.fold(Either.scala:189)
	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:323)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:248)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:168)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:191)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:179)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:179)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:171)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:133)
	at dotty.tools.repl.Main$.main(Main.scala:7)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

## Expectation

Scala 2.13 prints the following:
```scala
scala> class Foo { override def toString = null }
class Foo

scala> new Foo()
val res0: Foo = null toString
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #17333

### CODE REVIEW

File: compiler/test/dotty/tools/repl/ReplCompilerTests.scala [hunk 1]
```diff
@@ -347,6 +347,15 @@ class ReplCompilerTests extends ReplTest:
     assertEquals("java.lang.AssertionError: assertion failed", all.head)
   }
 
+  @Test def `i17333 print null result of toString`: Unit =
+    initially:
+      run("val tpolecat = new Object { override def toString(): String = null }")
+    .andThen:
+      assertEquals("val tpolecat: Object = null // non-null reference has null-valued toString", lines().head)
+
+end ReplCompilerTests
```
Comment (som-snytt) [inline compiler/test/dotty/tools/repl/ReplCompilerTests.scala:356]: this was in the style of
```
class Foo
object Foo
end Foo

```
so the extra `end` is redundant.

File: compiler/test/dotty/tools/repl/ReplCompilerTests.scala [hunk 2]
```diff
@@ -347,6 +347,15 @@ class ReplCompilerTests extends ReplTest:
     assertEquals("java.lang.AssertionError: assertion failed", all.head)
   }
 
+  @Test def `i17333 print null result of toString`: Unit =
+    initially:
+      run("val tpolecat = new Object { override def toString(): String = null }")
+    .andThen:
+      assertEquals("val tpolecat: Object = null // non-null reference has null-valued toString", lines().head)
```
Comment (bishabosha) [inline compiler/test/dotty/tools/repl/ReplCompilerTests.scala:354]: I think this is easier to read, what do you think?
```suggestion
      assertEquals("val tpolecat: Object = null // .toString() was null", lines().head)
```

File: compiler/src/dotty/tools/repl/Rendering.scala [hunk 3]
```diff
@@ -95,8 +98,9 @@ private[repl] class Rendering(parentClassLoader: Option[ClassLoader] = None):
       "replStringOf should only be called on values creating using `classLoader()`, but `classLoader()` has not been called so far")
     val maxPrintElements = ctx.settings.VreplMaxPrintElements.valueIn(ctx.settingsState)
     val maxPrintCharacters = ctx.settings.VreplMaxPrintCharacters.valueIn(ctx.settingsState)
-    val res = myReplStringOf(value, maxPrintElements, maxPrintCharacters)
-    if res == null then "null // non-null reference has null-valued toString" else res
+    Option(value)
```
Comment (bishabosha) [inline compiler/src/dotty/tools/repl/Rendering.scala:101]: if value is already expected to be non-null
```suggestion
    Some(value)
```

**Review by Kordyjan — CHANGES_REQUESTED** [review]
Thanks for the contribution. I like the idea of the comment explaining that the reference was not null even though `.toString` is null. Nevertheless, it seems that it is also shown for null references. That causes fail in [one of test cases](https://github.com/lampepfl/dotty/blob/main/compiler/test-resources/repl/renderNull) run by the [ScriptedTests](https://github.com/lampepfl/dotty/blob/main/compiler/test/dotty/tools/repl/ScriptedTests.scala).

**Comment by som-snytt** [comment]
Thanks for reviews. I will follow up expeditiously.

File: compiler/test/dotty/tools/repl/ReplCompilerTests.scala (hunk 2 above)
Comment (som-snytt) [reply compiler/test/dotty/tools/repl/ReplCompilerTests.scala:354]: I agree. I wondered even, `return value of .toString() was null` after the NPE message
```
scala> X.toString.toString
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "X$.toString()" is null
```
and now looking at it, I wonder if it is more useful and less redundant to use the default toString
```
scala> X
val res5: X.type = X$@23ba2c1e // return value of "X$.toString()" is null
```
or similar.

**Comment by som-snytt** [comment]
TIL `toIdentityString` is jdk 19. It seems so long ago. probably because of the "ea" program giving it a long runway.

**Comment by som-snytt** [comment]
The update corrects null handling and "improves" the message.

Someone somewhere asked why is Scala 3 REPL relying on Scala 2 runtime to "render a thing". After this tweak, and realizing that the Scala 2 hasn't been "upgraded", I have the same question. Usually I prefer "code sharing", but probably Scala 3 should just ingest the `stringOf` code. That is for printing arrays and other things.

There is an issue about rendering infinite things; I haven't tested whether the code which tests the lengths of renderings actually works in that case.

**Review by Kordyjan — APPROVED** [review]

**Comment by bishabosha** [comment]
I think it might be best to just do `null // "res0.toString" was null`, because otherwise you have inconsistency when objects are nested
```scala
scala> class Foo { override def toString = null }
// defined class Foo

scala> Foo()
val res0: Foo = Foo@4f7150bd // return value of "res0.toString" is null

scala> List(Foo())
val res1: List[Foo] = List(null)

scala>
```
