### PR TITLE
Set Span for top level annotations generated in PostTyper

### LINKED ISSUE #16318: Position not set error for `SourceFile` annotation, when accessed from a `transparent` macro
## Compiler version

3.2.1

## Minimized code

The following repository contains a minimized reproducer: https://github.com/vigoo/scala3-annotation-bug

Below I'm summarizing it but for the crash it is important to have two separate compiled modules.

Let's define a custom annotation and a case class that uses it:

```scala
import scala.annotation.StaticAnnotation

final case class testAnnotation(steps: String) extends StaticAnnotation

@testAnnotation("x")
final case class Record(a: String, b: Int)
```

then we create a macro that tries to collect all annotations of a given type:

```scala
case class Schema(annotations: List[Any])

object DeriveSchema {
  transparent inline def gen[T]: Schema = ${ deriveSchema[T] }

  def deriveSchema[T: Type](using ctx: Quotes): Expr[Schema] = {
    import ctx.reflect._

    val typeRepr = TypeRepr.of[T]
    val annotationExprs = TypeRepr.of[T].typeSymbol.annotations.map(_.asExpr)
//    val annotations = '{List.empty}
    val annotations = '{List(${Expr.ofSeq(annotationExprs)})} // NOTE: if this line is just an empty list it does not crash

    '{Schema($annotations)}
  }
}
```

and call it:

```scala
@main def run() = {
  val schema: Schema = DeriveSchema.gen[Record]
  println(schema)
}
```

if `Record` is defined in a different compilation unit (a separate sbt subproject in the linked repo) the compiler crashes. If `Record` is defined next to the macro invocation it works. Also if the `val annotations = ` line is replaced to the commented out one, it does not crash.

## Output (click arrow to expand)
<details>

```
[info] compiling 1 Scala source to /home/vigoo/projects/oss/scala3-annotation-bug/base/target/scala-3.2.1/classes ...
[info] compiling 2 Scala sources to /home/vigoo/projects/oss/scala3-annotation-bug/dep/target/scala-3.2.1/classes ...
java.lang.AssertionError: assertion failed: position not set for new scala.annotation.internal.SourceFile("base/src/main/scala/demo/Base.scala") # -1 of class dotty.tools.dotc.ast.Trees$Apply in <no file> while typechecking /home/vigoo/projects/oss/scala3-annotation-bug/dep/src/main/scala/demo/Dep.scala
[info] exception occurred while typechecking /home/vigoo/projects/oss/scala3-annotation-bug/dep/src/main/scala/demo/Dep.scala
java.lang.AssertionError: assertion failed: position not set for new scala.annotation.internal.SourceFile("base/src/main/scala/demo/Base.scala") # -1 of class dotty.tools.dotc.ast.Trees$Apply in <no file> while compiling /home/vigoo/projects/oss/scala3-annotation-bug/dep/src/main/scala/demo/Dep.scala, /home/vigoo/projects/oss/scala3-annotation-bug/dep/src/main/scala/demo/macros.scala
[error] ## Exception when compiling 2 sources to /home/vigoo/projects/oss/scala3-annotation-bug/dep/target/scala-3.2.1/classes
[error] java.lang.AssertionError: assertion failed: position not set for new scala.annotation.internal.SourceFile("base/src/main/scala/demo/Base.scala") # -1 of class dotty.tools.dotc.ast.Trees$Apply in <no file>
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.typer.Typer$.assertPositioned(Typer.scala:71)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3045)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.$anonfun$36(Typer.scala:1898)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:87)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:103)
[error] dotty.tools.dotc.typer.Typer.typedSeqLiteral(Typer.scala:1898)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2941)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.$anonfun$36(Typer.scala:1898)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:87)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:103)
[error] dotty.tools.dotc.typer.Typer.typedSeqLiteral(Typer.scala:1898)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2941)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:64)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2925)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$7(ProtoTypes.scala:483)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:406)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:484)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error] dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:557)
[error] dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:603)
[error] dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:460)
[error] dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
[error] dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1077)
[error] dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
[error] dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:121)
[error] dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:923)
[error] dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:1003)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3194)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1014)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:812)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2920)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$7(ProtoTypes.scala:483)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:406)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:484)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error] dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:557)
[error] dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:622)
[error] dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:460)
[error] dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
[error] dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1077)
[error] dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
[error] dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:121)
[error] dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:923)
[error] dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:1003)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3194)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1014)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:812)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2920)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:817)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2920)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error] dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3047)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.inlines.Inliner.inlined(Inliner.scala:671)
[error] dotty.tools.dotc.inlines.Inlines$InlineCall.expand(Inlines.scala:451)
[error] dotty.tools.dotc.inlines.Inlines$.inlineCall(Inlines.scala:148)
[error] dotty.tools.dotc.typer.Typer.adaptNoArgsOther$1(Typer.scala:3760)
[error] dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3862)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4082)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3431)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error] dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:2295)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2893)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2982)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3076)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3126)
[error] dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1060)
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1064)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2928)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error] dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1619)
[error] dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1609)
[error] dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1619)
[error] dotty.tools.dotc.typer.Namer.typedAheadRhs$1$$anonfun$1(Namer.scala:1871)
[error] dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:249)
[error] dotty.tools.dotc.typer.Namer.typedAheadRhs$1(Namer.scala:1871)
[error] dotty.tools.dotc.typer.Namer.rhsType$1(Namer.scala:1879)
[error] dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1897)
[error] dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1898)
[error] dotty.tools.dotc.typer.Namer.inferredResultType(Namer.scala:1909)
[error] dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1658)
[error] dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1665)
[error] dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1754)
[error] dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:787)
[error] dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:922)
[error] dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:810)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:173)
[error] dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
[error] dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
[error] dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:380)
[error] dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2861)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2886)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2982)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3076)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3126)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2556)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2908)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2912)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2982)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3076)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3126)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2687)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2953)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:44)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:54)
[error] scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:429)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:54)
[error] dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:88)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:88)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:233)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:244)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:252)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:261)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:261)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:191)
[error] dotty.tools.dotc.Driver.finish(Driver.scala:56)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2363)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2313)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2311)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]            
[error] java.lang.AssertionError: assertion failed: position not set for new scala.annotation.internal.SourceFile("base/src/main/scala/demo/Base.scala") # -1 of class dotty.tools.dotc.ast.Trees$Apply in <no file>
[error]         at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]         at dotty.tools.dotc.typer.Typer$.assertPositioned(Typer.scala:71)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3045)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.$anonfun$36(Typer.scala:1898)
[error]         at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:87)
[error]         at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:103)
[error]         at dotty.tools.dotc.typer.Typer.typedSeqLiteral(Typer.scala:1898)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2941)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.$anonfun$36(Typer.scala:1898)
[error]         at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:87)
[error]         at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:103)
[error]         at dotty.tools.dotc.typer.Typer.typedSeqLiteral(Typer.scala:1898)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2941)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:64)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2925)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$7(ProtoTypes.scala:483)
[error]         at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:406)
[error]         at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:484)
[error]         at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error]         at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error]         at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:557)
[error]         at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:603)
[error]         at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:460)
[error]         at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
[error]         at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
[error]         at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1077)
[error]         at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
[error]         at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:121)
[error]         at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:923)
[error]         at dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:1003)
[error]         at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3194)
[error]         at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1014)
[error]         at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error]         at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:812)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2920)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$7(ProtoTypes.scala:483)
[error]         at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:406)
[error]         at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:484)
[error]         at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error]         at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:866)
[error]         at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:557)
[error]         at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:622)
[error]         at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:460)
[error]         at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:748)
[error]         at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:865)
[error]         at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1077)
[error]         at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:327)
[error]         at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:121)
[error]         at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:923)
[error]         at dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:1003)
[error]         at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3194)
[error]         at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1014)
[error]         at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1052)
[error]         at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:327)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:812)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2920)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1917)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2942)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:817)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2920)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
[error]         at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:900)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3047)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.inlines.Inliner.inlined(Inliner.scala:671)
[error]         at dotty.tools.dotc.inlines.Inlines$InlineCall.expand(Inlines.scala:451)
[error]         at dotty.tools.dotc.inlines.Inlines$.inlineCall(Inlines.scala:148)
[error]         at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$1(Typer.scala:3760)
[error]         at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3862)
[error]         at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4082)
[error]         at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3431)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error]         at dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:2295)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2893)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2982)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3076)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3126)
[error]         at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1060)
[error]         at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1064)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2928)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1619)
[error]         at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1609)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1619)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadRhs$1$$anonfun$1(Namer.scala:1871)
[error]         at dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:249)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadRhs$1(Namer.scala:1871)
[error]         at dotty.tools.dotc.typer.Namer.rhsType$1(Namer.scala:1879)
[error]         at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1897)
[error]         at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1898)
[error]         at dotty.tools.dotc.typer.Namer.inferredResultType(Namer.scala:1909)
[error]         at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1658)
[error]         at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1665)
[error]         at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1754)
[error]         at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:787)
[error]         at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:922)
[error]         at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:810)
[error]         at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:173)
[error]         at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:187)
[error]         at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:189)
[error]         at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:380)
[error]         at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2861)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2886)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2982)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3076)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3126)
[error]         at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2556)
[error]         at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:2908)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2912)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2982)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3076)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3126)
[error]         at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2687)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2953)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2983)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3050)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3054)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3170)
[error]         at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:44)
[error]         at dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:54)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:42)
[error]         at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:429)
[error]         at dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:54)
[error]         at dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:88)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:88)
[error]         at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:233)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error]         at dotty.tools.dotc.Run.runPhases$1(Run.scala:244)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:252)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:261)
[error]         at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:261)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:191)
[error]         at dotty.tools.dotc.Driver.finish(Driver.scala:56)
[error]         at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
[error]         at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error]         at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error]         at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error]         at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error]         at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error]         at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error]         at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error]         at sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2363)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2313)
[error]         at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2311)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (dep / Compile / compileIncremental) java.lang.AssertionError: assertion failed: position not set for new scala.annotation.internal.SourceFile("base/src/main/scala/demo/Base.scala") # -1 of class dotty.tools.dotc.ast.Trees$Apply in <no file>
```
</details>

### PR DESCRIPTION
**Pull request by jchyb**
This should help avoid macros throwing assertion errors in the case of annotations not having assigned Spans/positions. Since the annotation is generated and does not have a position corresponding to the source file, it inherits Span from the tree to which it is assigned.

Fixes #16318

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/PostTyper.scala [hunk 1]
```diff
@@ -399,9 +399,9 @@ class PostTyper extends MacroTransform with IdentityDenotTransformer { thisPhase
               if ctx.compilationUnit.source.exists && sym != defn.SourceFileAnnot then
                 val reference = ctx.settings.sourceroot.value
                 val relativePath = util.SourceFile.relativePath(ctx.compilationUnit.source, reference)
-                sym.addAnnotation(Annotation.makeSourceFile(relativePath))
+                sym.addAnnotation(Annotation.makeSourceFile(relativePath, tree.span))
               if Feature.pureFunsEnabled && sym != defn.WithPureFunsAnnot then
-                sym.addAnnotation(Annotation(defn.WithPureFunsAnnot))
+                sym.addAnnotation(Annotation(defn.WithPureFunsAnnot, tree.span))
```
Comment (jchyb) [inline compiler/src/dotty/tools/dotc/transform/PostTyper.scala:404]: Worth noting: only the Source File annotation (in 402) caused problems in the issue, but I though it would be safer if all generated in PostTyper had positions set.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PostTyper.scala:404]: We should add a position for all annotation trees.

**Comment by jchyb** [comment]
Hi @Nicolas apologies for being so late with this. I was not entirely sure on what you meant in the above comment, so in the end I decided to add two commits. The first one fixes the issue by adding spans to all generated annotations in PostTyper, like before. This alone fixes the #16318, and adds annotations to two additional places where the issue has a chance to reappear (so this includes every annotation generated in PostTyper).

In the second commit, I make sure to add the span to every generated annotation in the compiler. For that I adjusted Annotation.apply methods to always require a span argument. This was obviously helpful for me, as it allowed me to easily locate span-less Annotations, and hopefully will be for others later, even if it is not futureproof (one can still pass a NoSpan, if necessary, in general it’s meant to be more of a remainder).

However, if the contents of the second commit end up being unnecessary, I can easily remove it from the PR and we can proceed with just the first commit.

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 2]
```diff
@@ -175,7 +175,7 @@ object desugar {
       case Into(tpt1) =>
         mods1 = vdef.mods.withAddedAnnotation(
           TypedSplice(
-            Annotation(defn.AllowConversionsAnnot).tree.withSpan(tpt.span.startPos)))
+            Annotation(defn.AllowConversionsAnnot, tpt.span.startPos).tree.withSpan(tpt.span.startPos)))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala:178]: I would imagine that the second `withSpan` is not needed anymore.

```suggestion
            Annotation(defn.AllowConversionsAnnot, tpt.span.startPos).tree))
```

File: compiler/test/dotty/tools/dotc/transform/TypeTestsCastsTest.scala [hunk 3]
```diff
@@ -15,7 +17,7 @@ class TypeTestsCastsTest extends DottyTest:
   @Test def orL = checkFound(List(StringType, LongType), OrType(LongType, StringType, false))
   @Test def orR = checkFound(List(LongType, StringType), OrType(StringType, LongType, false))
 
-  @Test def annot = checkFound(List(StringType, LongType), AnnotatedType(OrType(LongType, StringType, false), Annotation(defn.UncheckedAnnot)))
+  @Test def annot = checkFound(List(StringType, LongType), AnnotatedType(OrType(LongType, StringType, false), Annotation(defn.UncheckedAnnot, NoSpan)))
```
Comment (nicolasstucki) [inline compiler/test/dotty/tools/dotc/transform/TypeTestsCastsTest.scala:20]: Maybe use `Span(0)` as a dummy span. This way we won't have a nonexistent position in any place in the compiler or tests.

**Review by nicolasstucki — COMMENTED** [review]
Otherwise LGTM

**Comment by nicolasstucki** [comment]
> However, if the contents of the second commit end up being unnecessary, I can easily remove it from the PR and we can proceed with just the first commit.

The contents of the second commit are necessary. That is what I felt was missing before.

**Comment by jchyb** [comment]
Thank you for the review! I also just realized I @ the wrong person in my comment above before, for which I apologize, should be edited correctly now

**Review by nicolasstucki — APPROVED** [review]
