### PR TITLE
Fix #8750: Strip opaque refinements when checking self type

### LINKED ISSUE #8750: Cannot define 'opaque type' in class or trait
```Scala
class Abc:
  opaque type Log = Double

val v : Abc = new Abc
```
Fails with error: Abc does not conform to its self type Any{Log = LazyRef(Double)}; cannot be instantiated

### PR DESCRIPTION
**Pull request by odersky**
Strip opaque refinements when checking that a class is instantiatable

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -175,10 +175,16 @@ object Checking {
...
+            case RefinedType(parent, name, _) if cls.info.decl(name).symbol.isOpaqueAlias =>
+              parent.stripOpaques
+            case _ =>
+              tp
           // Create a synthetic singleton type instance, and check whether
           // it conforms to the self type of the class as seen from that instance.
           val stp = SkolemType(tp)
-          val selfType = cls.asClass.givenSelfType.asSeenFrom(stp, cls)
+          val selfType =
+            cls.asClass.givenSelfType.stripOpaques.asSeenFrom(stp, cls)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:187]: Maybe stripOpaque should be a boolean parameter of `givenSelfTypes` ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Checking.scala:187]: I think it's safer to keep givenSelfType as is.  It's really just when checking that we need to strip the refinements.
