### PR TITLE
Re-architecture quote pickling

### LINKED ISSUE #8100: Path dependent types level checking false negatives
## minimized code

```Scala
import scala.quoted._

class M {
  type E
}

def f[T: Type](using Quotes) =
  Expr.summon[M] match
    case Some('{ $mm : tt }) =>
      '{
        val m = $mm
        type ME = m.E
        ${ g[ME](using Type.of[ME]) }
        ${ g[m.E](using Type.of[ME]) }
        ${ g[ME](using Type.of[m.E]) }
        ${ g[m.E](using Type.of[m.E]) }
        ${ g[ME] }
        ${ g[m.E] }
      }

def g[T](using Type[T]) = ???
```
Has false negatives when checking the level of `m` in the types.

<details>
<summary>Compilation output</summary>

```scala
-- Error: Foo.scala:16:13 ------------------------------------------------------
16 |        ${ g[m.E](given '[ME]) }
   |             ^
   |             access to value m from wrong staging level:
   |              - the definition is at level 1,
   |              - but the access is at level 0.
-- Error: Foo.scala:18:13 ------------------------------------------------------
18 |        ${ g[m.E](given '[m.E]) }
   |             ^
   |             access to value m from wrong staging level:
   |              - the definition is at level 1,
   |              - but the access is at level 0.
-- Error: Foo.scala:19:16 ------------------------------------------------------
19 |        ${ g[ME] }
   |                ^
   |       access to type E from wrong staging level:
   |        - the definition is at level 0,
   |        - but the access is at level 1.
   |
   |        The access would be accepted with a given scala.quoted.Type[m.E]
-- Error: Foo.scala:20:13 ------------------------------------------------------
20 |        ${ g[m.E] }
   |             ^
   |             access to value m from wrong staging level:
   |              - the definition is at level 1,
   |              - but the access is at level 0.
```
</details>

## expectation
They should all compile and be equivalent

### LINKED ISSUE #12440: Path dependent type from quoted path miss handled in PickleQuotes
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
import scala.quoted.*

trait Mirror:
  type ElemTypes <: Tuple

class Eq:

  def test1(using Quotes): Unit = '{
    val m: Mirror = ???
    ${ summonType[m.ElemTypes]; ??? }
  }

  def test2(using Quotes): Unit = '{
    val m: Mirror = ???
    type ET = m.ElemTypes
    ${ summonType[ET]; ??? }
  }

  def summonType[X](using Type[X]) = ???
```

## Output (click arrow to expand)
<details>

```scala
java.lang.AssertionError: assertion failed: unresolved symbols: value m (line 8) #13908 when pickling tests/run-macros/typeclass-derivation2d/Lib_1.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:788)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:168)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:37)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickleAsTasty$1(PickleQuotes.scala:222)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickledQuote(PickleQuotes.scala:297)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:142)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:119)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1437)
        at scala.collection.immutable.List.mapConserve(List.scala:472)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1437)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1333)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:143)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:143)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformWithCapturer(PickleQuotes.scala:413)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.body$3(PickleQuotes.scala:394)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda$$anonfun$1(PickleQuotes.scala:404)
        at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:285)
        at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:120)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda(PickleQuotes.scala:404)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitSplice(PickleQuotes.scala:434)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformSplice(PickleQuotes.scala:316)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:130)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:143)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitQuote(PickleQuotes.scala:429)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:137)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:119)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1333)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:143)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1421)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:90)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:155)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:516)
        at dotty.tools.dotc.transform.PickleQuotes$$anon$1.transform(PickleQuotes.scala:95)
        at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
        at dotty.tools.dotc.transform.PickleQuotes.run(PickleQuotes.scala:91)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
        at dotty.tools.dotc.Run.compileSources(Run.scala:166)
        at dotty.tools.dotc.Run.compile(Run.scala:150)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:199)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.process(Driver.scala:179)
        at dotty.tools.dotc.Driver.main(Driver.scala:209)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

### LINKED ISSUE #13563: Assertion error when trying to reference abstract type in Macro
I'm not sure if this should work or not, but I do have a use case that I'm trying to fulfill using something similar to what follows.

## Compiler version

3.1.0-RC1

## Minimized code

```Scala
import scala.quoted.{Expr, Quotes, Type}

trait SomeTypeclass[A]:
  def runEffect[F[_]](): F[Int]

object SomeTypeclass:

  inline def derived[T]: SomeTypeclass[T] = ${ generateImpl[T] }
  def generateImpl[T: Type](using q: Quotes): Expr[SomeTypeclass[T]] =
    import q.reflect.*

    '{
      new SomeTypeclass[T] {
        override def runEffect[F[_]](): F[Int] = ${ runEffectImpl[F] }
      }
    }

  inline def runEffectImpl[F[_]: Type](using q: Quotes): Expr[F[Int]] =
    '{ ??? }
```

## Output (click arrow to expand)

Fails to compile and throws an assertion error instead.

```scala
java.lang.AssertionError: assertion failed: unresolved symbols: type F (line 16) #18013 when pickling /tmp/scastie3760419140958137017/src/main/scala/main.scala
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:777)
	at dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:167)
	at dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:36)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickleAsTasty$1(PickleQuotes.scala:221)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickledQuote(PickleQuotes.scala:296)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:141)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:118)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1464)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1500)
	at scala.collection.immutable.List.mapConserve(List.scala:472)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1500)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformSub(Trees.scala:1504)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1430)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformWithCapturer(PickleQuotes.scala:412)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.body$3(PickleQuotes.scala:393)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda$$anonfun$1(PickleQuotes.scala:403)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:285)
	at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:120)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda(PickleQuotes.scala:403)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitSplice(PickleQuotes.scala:433)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformSplice(PickleQuotes.scala:315)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:129)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1473)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitQuote(PickleQuotes.scala:428)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:136)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:118)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1390)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1396)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:93)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:35)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:41)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:54)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1473)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1473)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1484)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
	at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
	at dotty.tools.dotc.transform.PickleQuotes$$anon$1.transform(PickleQuotes.scala:94)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
	at dotty.tools.dotc.transform.PickleQuotes.run(PickleQuotes.scala:90)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:261)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:272)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:289)
	at dotty.tools.dotc.Run.compileSources(Run.scala:222)
	at dotty.tools.dotc.Run.compile(Run.scala:206)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
```
</details>

### LINKED ISSUE #13732: Unresolved symbol while pickling quote
## Compiler version

3.1.0

## Minimized code

```Scala
import scala.quoted.*

def generateImpl(using q: Quotes): Expr[Unit] =
  '{ def runEffect[T]: T = ${ runEffectImpl[T] } }

inline def runEffectImpl[T: Type]: Expr[T] = ???
```

Related to #13563

## Output

```scala
java.lang.AssertionError: assertion failed: unresolved symbols: type T (line 3) #13947 when pickling tests/pos-macros/i13563b.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:777)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:167)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:36)
        ...
```

## Expectation

Should compile

### LINKED ISSUE #14337: In splice reference to generic type at level 1
## Compiler version

3.1.1

## Minimized code

```Scala
import scala.quoted.*

def foo(using Quotes): Expr[Int] = '{
  def f[T](x: T): T = ${ bar('x) }
  f[Int](1)
}

def bar[T: Type](x: Expr[T]): Expr[T] = x
```

## Output (click arrow to expand)
<details>

```scala
4 |  def f[T](x: T): T = ${ bar('x) }
  |        ^
  |        pickling reference to as yet undefined T with symbol type T
exception occurred while compiling Foo.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: type T (line 3) #13985 when pickling Foo.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:774)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:162)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:36)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickleAsTasty$1(PickleQuotes.scala:221)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickledQuote(PickleQuotes.scala:296)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:141)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:118)
java.lang.AssertionError: assertion failed: unresolved symbols: type T (line 3) #13985 when pickling Foo.scala while compiling Foo.scala
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1493)
        at scala.collection.immutable.List.mapConserve(List.scala:472)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1493)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1389)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1403)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformWithCapturer(PickleQuotes.scala:412)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.body$8(PickleQuotes.scala:393)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda$$anonfun$1(PickleQuotes.scala:403)
        at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:286)
        at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:121)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda(PickleQuotes.scala:403)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitSplice(PickleQuotes.scala:433)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformSplice(PickleQuotes.scala:315)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:129)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1403)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitQuote(PickleQuotes.scala:428)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:136)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1383)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1389)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1466)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1477)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
        at dotty.tools.dotc.transform.PickleQuotes$$anon$1.transform(PickleQuotes.scala:94)
        at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
        at dotty.tools.dotc.transform.PickleQuotes.run(PickleQuotes.scala:90)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:259)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:270)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:278)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:287)
        at dotty.tools.dotc.Run.compileSources(Run.scala:220)
        at dotty.tools.dotc.Run.compile(Run.scala:204)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:199)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.process(Driver.scala:179)
        at dotty.tools.dotc.Driver.main(Driver.scala:209)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

### LINKED ISSUE #14373: AssertionError: assertion failed: unresolved symbols: anonymous class Object with
#### NG

- 3.1.1
- 3.1.1-RC1-bin-20211011-1ed25ce-NIGHTLY
- 3.1.2-RC1

#### OK

- 3.1.0
- 3.1.1-RC1-bin-20211008-0a89c6f-NIGHTLY

## Minimized code

```bash
git clone git@github.com:scalikejdbc/scalikejdbc.git
cd scalikejdbc
git checkout 272f48f568eb5d1f14b66660e6213ac91bbaf17f
sbt '++ 3.1.1!' 'syntax-support-macro/compile'
```

## Output (click arrow to expand)

<details>

```scala
[error] ## Exception when compiling 6 sources to /Users/kenji/scalikejdbc/scalikejdbc/scalikejdbc-syntax-support-macro/target/scala-3.1.1/classes
[error] java.lang.AssertionError: assertion failed: unresolved symbols: anonymous class Object with scalikejdbc.SQLSyntaxSupportImpl[A] {...} (line 25) #35404 when pickling /Users/kenji/scalikejdbc/scalikejdbc/scalikejdbc-syntax-support-macro/src/main/scala-3/scalikejdbc/SQLSyntaxSupportFactory.scala
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:777)
[error] dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:167)
[error] dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:36)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickleAsTasty$1(PickleQuotes.scala:221)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickledQuote(PickleQuotes.scala:300)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:141)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:118)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1390)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1396)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1404)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:147)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1500)
[error] scala.collection.immutable.List.mapConserve(List.scala:472)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1500)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformSub(Trees.scala:1504)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1416)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1464)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:35)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:54)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:147)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1500)
[error] scala.collection.immutable.List.mapConserve(List.scala:472)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1500)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformSub(Trees.scala:1504)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1416)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1500)
[error] scala.collection.immutable.List.mapConserve(List.scala:472)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1500)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1396)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1464)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformWithCapturer(PickleQuotes.scala:412)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.body$8(PickleQuotes.scala:393)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda$$anonfun$1(PickleQuotes.scala:403)
[error] dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:285)
[error] dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:120)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.makeLambda(PickleQuotes.scala:403)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitSplice(PickleQuotes.scala:433)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformSplice(PickleQuotes.scala:315)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:129)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:35)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:54)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:35)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:54)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1473)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:513)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1410)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:95)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.splitQuote(PickleQuotes.scala:428)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:136)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:118)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1390)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1396)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:93)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:142)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1473)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1484)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:154)
[error] dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:515)
[error] dotty.tools.dotc.transform.PickleQuotes$$anon$1.transform(PickleQuotes.scala:94)
[error] dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
[error] dotty.tools.dotc.transform.PickleQuotes.run(PickleQuotes.scala:90)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
[error] scala.collection.immutable.List.map(List.scala:250)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:261)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:272)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:289)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:222)
[error] dotty.tools.dotc.Run.compile(Run.scala:206)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Note

- https://github.com/lampepfl/dotty/compare/0a89c6f...1ed25ce
- https://github.com/scalikejdbc/scalikejdbc/pull/1457
- maybe https://github.com/lampepfl/dotty/pull/13547 🤔 
- https://github.com/scalikejdbc/scalikejdbc/blob/272f48f568eb5d1f14b66660e6213ac91bbaf17f/scalikejdbc-syntax-support-macro/src/main/scala-3/scalikejdbc/SQLSyntaxSupportFactory.scala#L25
- similar (but resolved) issue https://github.com/lampepfl/dotty/issues/8651

### PR DESCRIPTION
**Pull request by nicolasstucki**
Separate the logic that creates holes in quotes from the logic that pickles the quotes. Holes are created in the `Splicer` phase and the result of the transformation can be `-Ycheck`ed. Now, the `PickleQuotes` phase only needs to extract the contents of the holes, pickle the quote and put them into a call to `unpickleExprV2`/`unpickleTypeV2`. See documentation in `PickleQuotes` and `Splicer`.
    
We add `unpickleExprV2`/`unpickleTypeV2` to support some optimization in the encoding of the pickled quote. Namely, we removed an unnecessary lambda from the arguments of the hole passed into the contents of the hole. By not changing `unpickleExpr`/`unpickleType` the current compiler will be able to handle the old encoding in binaries compiled with older compilers.
    
Fixes #8100
Fixes #12440
Fixes #13563
Fixes #13732
Fixes #14337 
Fixes #14373

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Test performance please

**Comment by nicolasstucki** [comment]
@liufengyun, if you have time could you have a look at this? At least the high level changes. You reviewed and know the previous version.

**Comment by nicolasstucki** [comment]
Test performance please

**Comment by nicolasstucki** [comment]
Note that I wrote the `Splicing` class from scratch re-using some logic that was present in `PickleQuotes`. In `PickleQuotes` I mostly removed code and moved some of the methods.

**Comment by nicolasstucki** [comment]
test performance with #quotes please

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala [hunk 1]
```diff
@@ -68,16 +68,19 @@ object PickledQuotes {
...
       override def transform(tree: tpd.Tree)(using Context): tpd.Tree = tree match {
-        case Hole(isTerm, idx, args) =>
+        case Hole(isTermHole, idx, args, _, _) =>
           inContext(SpliceScope.contextWithNewSpliceScope(tree.sourcePos)) {
             val reifiedArgs = args.map { arg =>
-              if (arg.isTerm) (q: Quotes) ?=> new ExprImpl(arg, SpliceScope.getCurrent)
+              if (arg.isTerm)
+                version match
+                  case 1 => (q: Quotes) ?=> new ExprImpl(arg, SpliceScope.getCurrent)
+                  case 2 => new ExprImpl(arg, SpliceScope.getCurrent)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:80]: It seems the lambdas here are called during compilation. What will happen if we don't do the versioning? And do well need the versioning at the call-site of `reifiedArgs`?

**Review by liufengyun — APPROVED** [review]
LGTM 👍 

I added some clarification questions, mostly to better understand the code.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 2]
```diff
@@ -2994,7 +2994,11 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
   end reflect
 
   def unpickleExpr[T](pickled: String | List[String], typeHole: (Int, Seq[Any]) => scala.quoted.Type[?], termHole: (Int, Seq[Any], scala.quoted.Quotes) => scala.quoted.Expr[?]): scala.quoted.Expr[T] =
-    val tree = PickledQuotes.unpickleTerm(pickled, typeHole, termHole)
+    val tree = PickledQuotes.unpickleTerm(pickled, typeHole, termHole, version = 1)
+    new ExprImpl(tree, SpliceScope.getCurrent).asInstanceOf[scala.quoted.Expr[T]]
+
+  def unpickleExprV2[T](pickled: String | List[String], typeHole: (Int, Seq[Any]) => scala.quoted.Type[?], termHole: (Int, Seq[Any], scala.quoted.Quotes) => scala.quoted.Expr[?]): scala.quoted.Expr[T] =
+    val tree = PickledQuotes.unpickleTerm(pickled, typeHole, termHole, version = 2)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:3001]: Yes, it was intentional. There are no changes in the way types are unpickled. `unpickleExprV2` is actually a bit closer to how `unpickleType` encodes the arguments of the holes. See https://github.com/lampepfl/dotty/pull/12540/files#diff-76125c8da787411fc7d3143ddc2e9b97b26825d1eae3c9d4db12b8de9bd7ddbdR78-R81.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 3]
```diff
@@ -0,0 +1,409 @@
...
+import dotty.tools.dotc.transform.TreeMapWithStages._
+import dotty.tools.dotc.typer.Inliner
+
+import scala.annotation.constructorOnly
+
+object Splicing:
+  val name: String = "splicing"
+
+/** Transforms level 1 splices into holes. To do so it transforms the contents of the splice into
+ *  a lambda that receives all cross-quote references.
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:33]: The point is that it only happens for splices that are directly embedded in top-level quotes (i.e. at level 1). Other splices (at higher levels) do not get transformed in this phase.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 4]
```diff
@@ -0,0 +1,409 @@
...
+          if fn.symbol == defn.QuotedRuntime_exprQuote =>
+            args match
+              case List(tree: RefTree) if quotedDefs.contains(tree.symbol) =>
+                capturedTerm(tree)
+              case _ =>
+                val oldQuotes = quotes
+                if level == 0 then
+                  quotes = quotesArgs.head
+                val newArgs = args.mapConserve(arg => transformQuotedContent(arg)(using quoteContext))
+                quotes = oldQuotes
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:231]: Will do

File: compiler/src/dotty/tools/dotc/ast/Trees.scala [hunk 5]
```diff
@@ -973,9 +976,15 @@ object Trees {
   def genericEmptyTree[T >: Untyped]: Thicket[T]        = theEmptyTree.asInstanceOf[Thicket[T]]
 
   /** Tree that replaces a splice in pickled quotes.
-   *  It is only used when picking quotes (Will never be in a TASTy file).
+   *  It is only used when picking quotes (will never be in a TASTy file).
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Trees.scala:979]: If we would use a magical method to encode holes we would need to special-case it in the tree pickler/unpickler to transform it to/from a tree.

File: compiler/src/dotty/tools/dotc/ast/Trees.scala [hunk 6]
```diff
@@ -973,9 +976,15 @@ object Trees {
...
+   *  @param idx The index of the hole in the quote.
+   *  @param args The arguments of the splice to compute its content
+   *  @param content Lambda that computes the content of the hole. This tree is empty when in a quote pickle.
+   *  @param tpt Type of the hole
    */
-  case class Hole[-T >: Untyped](isTermHole: Boolean, idx: Int, args: List[Tree[T]])(implicit @constructorOnly src: SourceFile) extends Tree[T] {
+  case class Hole[-T >: Untyped](isTermHole: Boolean, idx: Int, args: List[Tree[T]], content: Tree[T], tpt: Tree[T])(implicit @constructorOnly src: SourceFile) extends Tree[T] {
     type ThisTree[-T >: Untyped] <: Hole[T]
     override def isTerm: Boolean = isTermHole
     override def isType: Boolean = !isTermHole
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Trees.scala:990]: I had that at the start but had issues when trying to retypecheck code containing a hole. Having it a tree helped.

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala [hunk 7]
```diff
@@ -194,6 +194,12 @@ trait QuotesAndSplices {
         using spliceContext.retractMode(Mode.QuotedPattern).withOwner(spliceOwner(ctx)))
     pat.select(tpnme.Underlying)
 
+  def typedHole(tree: untpd.Hole, pt: Type)(using Context): Tree = {
+    val tpt = typedType(tree.tpt)
+    // TODO check args and contents
+    tree.withType(tpt.tpe)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala:200]: Missed it. Will use it.

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:80]: > What will happen if we don't do the versioning?

Then macros that were compiled with a previous version of the compiler would not work with this version of the compiler. With this versioning, we can keep supporting any macro compiled since `3.0.0`.

> And do well need the versioning at the call-site of `reifiedArgs`?

Not sure if I understand correctly what you mean by _call-site of `reifiedArgs`_. If that refers to the generated code that is passed as `termHole` then that change is what is being reflected here.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 8]
```diff
@@ -0,0 +1,409 @@
...
+        val newTree = transform(tree)
+        val (refs, bindings) = refBindingMap.values.toList.unzip
+        val bindingsTypes = bindings.map(_.termRef.widenTermRefExpr)
+        val methType = MethodType(bindingsTypes, newTree.tpe)
+        val meth = newSymbol(spliceOwner, nme.ANON_FUN, Synthetic | Method, methType)
+        val ddef = DefDef(meth, List(bindings), newTree.tpe, newTree.changeOwner(ctx.owner, meth))
+        val fnType = defn.FunctionType(bindings.size, isContextual = false).appliedTo(bindingsTypes :+ newTree.tpe)
+        val closure = Block(ddef :: Nil, Closure(Nil, ref(meth), TypeTree(fnType)))
+        holeIdx += 1
+        tpd.Hole(true, holeIdx, refs, closure, TypeTree(tpe))
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:185]: Will extract `SpliceTransformer` from `QuoteTransformer` and pass extra parameters to `SpliceTransformer`.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 9]
```diff
@@ -0,0 +1,409 @@
...
+        case tree: DefDef if tree.symbol.is(Inline) =>
+          tree
+        case _ =>
+          super.transform(tree)
+  end Level0QuoteTransformer
+
+
+  /** Transforms all direct splices in the current quote and replace them with holes. */
+  private class QuoteTransformer() extends Transformer:
+    private val quotedDefs = mutable.Set.empty[Symbol]
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:102]: Good example.

First, the `Level0QuoteTransformer` finds that quote. Then the `QuoteTransformer` will transform the contents of the quote collecting the `quotedDefs`. When it reaches the splice

```
${
         // ...
         '{
             // ...
             ${ f('a) }
          }
     }
```
`quotedDefs = Set(<val a>)`.

Then the `SpliceTransformer` will transform the contents of the splice and create the hole. This is done with a snapshot of the current `quotedDefs` (the new version of the code is more explicit about this). The `SpliceTransformer` will only transform the captured definition reference and will just transform within quotes.
After this transformation, we get a hole like
```
    {{{ 0 | T | a |
      (x1: Expr[T2]) =>
         // ...
         '{
             // ...
             ${ f('{${x1}}) }
          }
    }}}
```
Then we recursively transform the contents of the hole using `Level0QuoteTransformer` which will find any quote can transform it. In this case, it will find
```
'{
       // ...
      ${ f('{${x1}}) }
}
```

Note that `QuoteTransformer` will also cancel splices. Therefore it will transform `'{${x1}}` into `x1`. Removing unnecessary splices that might have been added in the process.

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:80]: > Not sure if I understand correctly what you mean by call-site of reifiedArgs. If that refers to the generated code that is passed as termHole then that change is what is being reflected here.

I may be asking a stupid question here: Here we create a value based on `version`, when the value is used (elsewhere), do we need to handle two different values corresponding to the two `version`s at the usage site?

I think you already hinted at the answer above: the usage site for `version = 1` is from 3.0.0 macros, while values corresponding to `version = 2` will be consumed by macros compiled by this PR.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:80]: > I think you already hinted at the answer above: the usage site for version = 1 is from 3.0.0 macros, while values corresponding to version = 2 will be consumed by macros compiled by this PR.

That is right. For macros compiled from 3.0.0 up to this PR the compiler-generated code that called `unpickleExpr` which we internally handle as `version = 1`. This code expected the hole arguments to be passed as `Quotes ?=> Expr[Any]`. From the PR onwards the compiler will generate a call `unpickleExprV2` which is internally handled as `version = 2` which handles the hole arguments as `Expr[Any]`. Therefore at use-site we know the version based on which version of `unpickleExpr`/`unpickleExprV2` we call and the compiler is capable of handling both of them.

Of course, an old compiler will not be able to execute a macro compiled by this version of the compiler.

Another design option for versioning was to add a `unpickleExprVersioned` that takes a parameter the version number. `unpickleExpr` would just call `unpickleExprVersioned` with `version = 1`. This has the drawback of adding this extra parameter everywhere which seemed unnecessary overhead. Furthermore, if we have a next version we might change the signature of `unpickleExpr` completely. For example, encoding the arguments in a different way, maybe to optimize some common cases.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 4 above)
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Done

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 10]
```diff
@@ -0,0 +1,409 @@
...
+    override def transform(tree: tpd.Tree)(using Context): tpd.Tree =
+      assert(level == 0)
+      tree match
+        case Apply(Select(Apply(TypeApply(fn,_), List(code)),nme.apply),List(quotes))
+        if fn.symbol == defn.QuotedRuntime_exprQuote =>
+          QuoteTransformer().transform(tree)
+        case TypeApply(_, _) if tree.symbol == defn.QuotedTypeModule_of =>
+          QuoteTransformer().transform(tree)
+        case tree: DefDef if tree.symbol.is(Inline) =>
+          tree
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:94]: Done

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 11]
```diff
@@ -0,0 +1,409 @@
...
+          cpy.TypeDef(tree)(rhs = hole)
+        case Apply(Select(Apply(TypeApply(fn,_), List(code)),nme.apply),List(quotes))
+        if fn.symbol == defn.QuotedRuntime_exprQuote =>
+          super.transform(tree)(using quoteContext)
+        case tree: DefTree =>
+          quotedDefs += tree.symbol
+          transformAnnotations(tree)
+          super.transform(tree)
+        case _ =>
+          super.transform(tree).withType(mapAnnots(tree.tpe))
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:137]: This code is there to solve #7519 which was originally fixed in #7531. I will see if there is a better way to handle those annotations.

[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:137]: Actually the current failure in `tests/pos-macros/i7519b.scala` is different.

[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:137]: It is about transforming the trees of annotations in types. For example, we need to transform the tree `Annot($value)` of

```scala
'{ new Quoted[T @Annot($value)] }
```

Maybe I can make it apply this transformation only on `TypeTree`s as other annotations are transformed on the `Annotated` trees.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 12]
```diff
@@ -0,0 +1,409 @@
...
+        val tpe = expr.tpe.widenTermRefExpr
+        ref(defn.QuotedRuntime_exprQuote)
+          .appliedToType(tpe)
+          .appliedTo(expr)
+          .select(nme.apply)
+          .appliedTo(quotes)
+
+      /** Helper methods to construct trees calling methods in `Quotes.reflect` based on the current `quotes` tree */
+      private object reflect {
+        private def reflect(using Context) = quotes.select(nme.reflect)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: I will remove the definition.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 13]
```diff
@@ -0,0 +1,409 @@
...
+        spliced(tree.tpe) {
+          reflect.asExpr(tree.tpe)(
+            reflect.Assign(
+              reflect.asTerm(capturedTerm(tree.lhs)),
+              reflect.asTerm(quoted(tree.rhs))
+            )
+          )
+        }
+
+      /** Transform an assignment `f(a1, a2, ...)` with a captured `f` to
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Should be `application`

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 14]
```diff
@@ -0,0 +1,409 @@
...
+          val tree1 = transform(tree)
+          val tree2 = tree1 match
+            case Block(stats @ (x :: _), expr) if x.symbol.hasAnnotation(defn.QuotedRuntime_SplicedTypeAnnot) =>
+              Block(healedTypes.getTypeTags ::: stats, expr)
+            case _ => Block(healedTypes.getTypeTags, tree1)
+          healedTypes = old
+          tree2
+        }
+
+      type ArgsClause = (List[Tree], Boolean)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Ok

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 15]
```diff
@@ -0,0 +1,409 @@
...
+                val capturedTypeSym = capturedType(tree)
+                if level >= 1 then
+                  TypeTree(healedTypes.getTagRef(capturedTypeSym.termRef))
+                else
+                  ref(capturedTypeSym).select(defn.QuotedType_splice)
+              else super.transform(tree)
+          case tree: TypeTree =>
+            if containsCapturedType(tree.tpe) then
+              // TODO factor out the common code with the above case
+              val capturedTypeSym = capturedType(tree)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:203]: Yes. For example in the following quote 

```scala
'{ type X; type Y; ${ ... f[Map[X, Y]] ...  } }
```
we would end up with 

```scala
'{ type X; type Y; {{{ 0 | T | Map[X, Y] | (t: Type[Map[X, Y]]) => ... f[t.Undelying] ...  }}} }

```

We keep the `Map[X, Y]` as a whole because we cant recreate a tree for all cases types in the `TypeTree`. In this particular case it seems we could handle it as and `AppliedType` with two captured types but it is not clear if that would be better in general.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 16]
```diff
@@ -0,0 +1,409 @@
...
+              if level >= 1 then
+                TypeTree(healedTypes.getTagRef(capturedTypeSym.termRef))
+              else
+                ref(capturedTypeSym).select(defn.QuotedType_splice)
+            else tree
+          case tree @ Assign(lhs: RefTree, rhs) =>
+            if quotedDefs.contains(lhs.symbol) then transformSplicedAssign(tree)
+            else super.transform(tree)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:208]: It can be scope extruded like any other expression 
```scala
var bad: Expr[Any] = null
'{
  var x = 2
  ${ bad = '{ x = 3 }; 'x }
}
bad
```
The usual runtime mechanism will catch these extrusions.

The assignment itself does not insert any other kind of extrusion.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 17]
```diff
@@ -0,0 +1,409 @@
...
+          val old = healedTypes
+          healedTypes = new PCPCheckAndHeal.QuoteTypeTags(tree.span)
+          val tree1 = transform(tree)
+          val tree2 = tree1 match
+            case Block(stats @ (x :: _), expr) if x.symbol.hasAnnotation(defn.QuotedRuntime_SplicedTypeAnnot) =>
+              Block(healedTypes.getTypeTags ::: stats, expr)
+            case _ => Block(healedTypes.getTypeTags, tree1)
+          healedTypes = old
+          tree2
+        }
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: I will rewrite this method

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Done

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 18]
```diff
@@ -0,0 +1,409 @@
...
+        case _ =>
+          super.transform(tree)
+  end Level0QuoteTransformer
+
+
+  /** Transforms all direct splices in the current quote and replace them with holes. */
+  private class QuoteTransformer() extends Transformer:
+    private val quotedDefs = mutable.Set.empty[Symbol]
+    private var holeIdx = -1
+    private var typeHoles = mutable.Map.empty[Symbol, Hole]
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:104]: Yes. Added documentation.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 17 above)
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Done

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 9 above)
[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:104]: Thanks for the detailed explanation. If I understand correctly, the current algorithm will be quadratic in terms of the tree size if there are such nested quote/splices (which should be rare).

A digression: I am wondering if a linear algorithm is possible. As such use cases are rare, there is no need for premature optimization in this PR.

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:80]: > Of course, an old compiler will not be able to execute a macro compiled by this version of the compiler.

What is the impact of this? Does it mean it has to be in a bigger compiler version, such as `3.2`?

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 11 above)
[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: It seems what's done here is pretty general. Is it possible to change `Transformer`?

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 19]
```diff
@@ -26,45 +26,52 @@ import dotty.tools.dotc.typer.Inliner
...
+ *      ...
+ *      {{{ 1 | x2 | | T1 }}} // hole
+ *      ...
+ *      {{{ 2 | x1, x2 | | T2 }}} // hole
  *         ...
  *       ]],
  *       typeHole = (idx: Int, args: List[Any]) => idx match {
- *         case 0 => ...
+ *         case 0 => contentsTpe0.apply(args) // beta reduces in following phases
+ *         case 1 => contentsTpe1.apply(args) // beta reduces in following phases
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:65]: A naive question: is it possible for `content` to have the type `List[Tree] => Tree`, so that it naturally beta reduces. Just curious about the conceptual possibility. Engineering-wise it seems to be not a good idea, as closures may capture the context across phases, unlike trees, which may cause subtle bugs.

**Review by liufengyun — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 19 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:65]: Actually, the docs are missing something. I will update them.

**Comment by nicolasstucki** [comment]
> Is it possible to use a Type instead of Tree here? It would be nice to add a comment about the problem with retypecheck.

I misspoke in my previous comment. This is a tree because it is part of the AST structure of a hole in TASTy. No tree contains a `Type` as a field and I would not make this one an exception.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 19 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala]: I updated the docs

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 9 above)
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:104]: Linear might be possible but it would be much harder to reason about. 

There is also the possibility of detecting if the contents of a splice need further transformation while doing the first pass. Then avoid the second pass if not needed.

Another alternative is to warn the user where there are to many nested quotes or code in a splice is too large. The contents of a splice can always be extracted into a separate method. This is what we recommend in the best practices for legibility.

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala]: A macro compiled with 3.2+ cannot be used for code compiled with 3.0 or 3.1

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 20]
```diff
@@ -76,375 +83,80 @@ class PickleQuotes extends MacroTransform {
...
-                embedded.addTree(tree, capturedArg.symbol)
-                captured.put(tree.symbol, capturedArg)
-                capturedArg
-              }
-              val refSym = captured.getOrElseUpdate(tree.symbol, newCapture).symbol
-              ref(refSym).withSpan(tree.span)
+  private def makeHoles(tree: tpd.Tree)(using Context): (List[Tree], tpd.Tree) =
+
+    class HoleContentExtractor extends Transformer:
+      private var contents = List.newBuilder[Tree]
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:129]: If it's a mutable builder it probaly doesn't need to be a var too.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 21]
```diff
@@ -458,105 +170,215 @@ class PickleQuotes extends MacroTransform {
...
+      */
+    def pickleAsTasty() = {
+      val pickleQuote = PickledQuotes.pickleQuote(body)
+      val pickledQuoteStrings = pickleQuote match
+        case x :: Nil => Literal(Constant(x))
+        case xs => tpd.mkList(xs.map(x => Literal(Constant(x))), TypeTree(defn.StringType))
+
+      // TODO split holes earlier into types and terms. This all holes in each category can have consecutive indices
+      val (typeSplices, termSplices) = contents.zipWithIndex.partition {
+        case (splice, _) => splice.tpe.derivesFrom(defn.QuotedTypeClass)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:287]: The case shouldn't be needed here.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 22]
```diff
@@ -458,105 +170,215 @@ class PickleQuotes extends MacroTransform {
...
+          )
 
-    def isLiftedSymbol(sym: Symbol)(using Context): Boolean = map.contains(sym)
+      // This and all closures in termSplices are removed by the BetaReduce phase
+      val termHoles =
+        if termSplices.isEmpty then Literal(Constant(null)) // keep pickled quote without contents as small as possible
+        else
+          Lambda(
+            MethodType(
+              List("idx", "contents", "quotes").map(name => UniqueName.fresh(name.toTermName).toTermName),
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:315]: These names can be added to StdNames to avoid the toTermName.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 23]
```diff
@@ -458,105 +170,215 @@ class PickleQuotes extends MacroTransform {
...
+              List(defn.IntType, defn.SeqType.appliedTo(defn.AnyType), defn.QuotesClass.typeRef),
+              defn.QuotedExprClass.typeRef.appliedTo(defn.AnyType)),
+            args => {
+              val cases = termSplices.map { case (splice, idx) =>
+                val defn.FunctionOf(argTypes, defn.FunctionOf(quotesType :: _, _, _, _), _, _) = splice.tpe
+                val rhs = {
+                  val spliceArgs = argTypes.zipWithIndex.map { (argType, i) =>
+                    args(1).select(nme.apply).appliedTo(Literal(Constant(i))).select(defn.Any_asInstanceOf).appliedToType(argType)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:323]:
```suggestion
                    args(1).select(nme.apply).appliedTo(Literal(Constant(i))).asInstance(argType)
```

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 24]
```diff
@@ -458,105 +170,215 @@ class PickleQuotes extends MacroTransform {
...
+      val termHoles =
+        if termSplices.isEmpty then Literal(Constant(null)) // keep pickled quote without contents as small as possible
+        else
+          Lambda(
+            MethodType(
+              List("idx", "contents", "quotes").map(name => UniqueName.fresh(name.toTermName).toTermName),
+              List(defn.IntType, defn.SeqType.appliedTo(defn.AnyType), defn.QuotesClass.typeRef),
+              defn.QuotedExprClass.typeRef.appliedTo(defn.AnyType)),
+            args => {
+              val cases = termSplices.map { case (splice, idx) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:319]: No need for braces or case.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 25]
```diff
@@ -458,105 +170,215 @@ class PickleQuotes extends MacroTransform {
...
+      // This and all closures in termSplices are removed by the BetaReduce phase
+      val termHoles =
+        if termSplices.isEmpty then Literal(Constant(null)) // keep pickled quote without contents as small as possible
+        else
+          Lambda(
+            MethodType(
+              List("idx", "contents", "quotes").map(name => UniqueName.fresh(name.toTermName).toTermName),
+              List(defn.IntType, defn.SeqType.appliedTo(defn.AnyType), defn.QuotesClass.typeRef),
+              defn.QuotedExprClass.typeRef.appliedTo(defn.AnyType)),
+            args => {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:318]: No need for braces

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 26]
```diff
@@ -0,0 +1,394 @@
...
+ *  and then performs the same transformation on `'{ g(${x1$}, ${x2$}) }`.
+ *
+ */
+class Splicing extends MacroTransform:
+  import tpd._
+
+  override def phaseName: String = Splicing.name
+
+  override def run(using Context): Unit =
+    if (ctx.compilationUnit.needsQuotePickling) super.run(using freshStagingContext)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:79]: Old-style if.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 27]
```diff
@@ -0,0 +1,394 @@
...
+  /** Transforms all direct splices in the current quote and replace them with holes. */
+  private class QuoteTransformer() extends Transformer:
+    /** Set of definitions in the current quote */
+    private val quotedDefs = mutable.Set.empty[Symbol]
+
+    /** Number of holes created in this quote. Used for indexing holes. */
+    private var numHoles = 0
+
+    /** Mapping from the term symbol of a `Type[T]` to it's hole. Used to deduplicate type holes. */
+    private var typeHoles = mutable.Map.empty[Symbol, Hole]
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:110]: This also probably can be a val and not a var since it's mutable.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 28]
```diff
@@ -0,0 +1,394 @@
...
+     *  It also handles cases with multiple argument clauses using nested `Apply`/`TypeApply`.
+     */
+    private def transformCapturedApplication(tree: Tree, fn: RefTree, argss: List[ArgsClause])(using Context): Tree =
+      spliced(tree.tpe) {
+        def TermList(args: List[Tree]): List[Tree] =
+          args.map(arg => reflect.asTerm(quoted(transform(arg)(using spliceContext))))
+        def TypeTreeList(args: List[Tree]): List[Tree] =
+          args.map(arg => reflect.Inferred(reflect.TypeReprOf(transform(arg)(using spliceContext).tpe)))
+        reflect.asExpr(tree.tpe) {
+          argss.foldLeft[Tree](reflect.asTerm(capturedTerm(fn, defn.AnyType))) { case (acc, clause) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:321]: case can be removed.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 29]
```diff
@@ -0,0 +1,394 @@
...
+            if clause.isTerm then reflect.Apply(acc, TermList(clause.args))
+            else reflect.TypeApply(acc, TypeTreeList(clause.args))
+          }
+        }
+      }
+
+    private def capturedTerm(tree: Tree)(using Context): Tree =
+      val tpe = tree.tpe.widenTermRefExpr match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:329]: braces can be removed.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 30]
```diff
@@ -0,0 +1,394 @@
...
+      capturedTerm(tree, tpe)
+
+    private def capturedTerm(tree: Tree, tpe: Type)(using Context): Tree =
+      def newBinding = newSymbol(
+        spliceOwner,
+        UniqueName.fresh(tree.symbol.name.toTermName).toTermName,
+        Param,
+        defn.QuotedExprClass.typeRef.appliedTo(tpe),
+      )
+      val (_, bindingSym) = refBindingMap.getOrElseUpdate(tree.symbol, (tree, newBinding))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:342]: I would go with:
```suggestion
      val bindingSym = refBindingMap.getOrElseUpdate(tree.symbol, (tree, newBinding))._2
```
(same below)

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 31]
```diff
@@ -1603,7 +1603,11 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
       res
 
     override def typedTypeApply(tree: untpd.TypeApply, pt: Type)(using Context): Tree =
-      inlineIfNeeded(constToLiteral(betaReduce(super.typedTypeApply(tree, pt))))
+      val tree1 = inlineIfNeeded(constToLiteral(betaReduce(super.typedTypeApply(tree, pt))))
+      if tree1.symbol.isQuote then
+        ctx.compilationUnit.needsStaging = true
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:1608]: needsStaging seems like a misleading name if it's set to true whenever there is a quote?

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala [hunk 32]
```diff
@@ -194,6 +194,12 @@ trait QuotesAndSplices {
         using spliceContext.retractMode(Mode.QuotedPattern).withOwner(spliceOwner(ctx)))
     pat.select(tpnme.Underlying)
 
+  def typedHole(tree: untpd.Hole, pt: Type)(using Context): Tree = {
+    val tpt = typedType(tree.tpt)
+    // TODO check args and contents
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala:199]: Would be good to expand the TODO a bit on what needs to be checked and whether this is needed for soundness or for detecting bugs in the compiler.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala [hunk 33]
```diff
@@ -0,0 +1,394 @@
...
+        case GenericApply(CapturedApplication(fn, argss), args) =>
+          Some((fn, argss :+ ArgsClause(args)))
+        case _ =>
+          None
+    }
+
+    private def containsCapturedType(tpe: Type)(using Context): Boolean =
+      tpe match
+        case tpe @ TypeRef(prefix, _) => isCaptured(tpe.symbol) || containsCapturedType(prefix)
+        case tpe @ TermRef(prefix, _) => isCaptured(tpe.symbol) || containsCapturedType(prefix)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Splicing.scala:288]: I would do:
```suggestion
        case tpe: NamedType => isCaptured(tpe.symbol) || containsCapturedType(tpe.prefix)
```
Also I don't know the context here, but is this really complete? I would expect something like `tpe.existsPart(isCaptured)` to deal with aliases, type lambdas, etc (also existsPart takes a stopAt argument that can be used to avoid traversing static prefixes which I assume would make sense here).

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala [hunk 34]
```diff
@@ -458,105 +170,215 @@ class PickleQuotes extends MacroTransform {
...
+      */
+    def pickleAsLiteral(lit: Literal) = {
+      val typeName = body.tpe.typeSymbol.name
+      val literalValue =
+        if lit.const.tag == Constants.NullTag || lit.const.tag == Constants.UnitTag then Nil
+        else List(body)
+      reflect.asExpr(body.tpe) {
+        reflect.Literal {
+          reflect.self
+            .select(s"${typeName}Constant".toTermName)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:230]: I would prefer a match on the tag to select the correct symbol

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala [hunk 35]
```diff
@@ -51,34 +51,51 @@ object PickledQuotes {
...
-  def unpickleTypeTree(pickled: String | List[String], typeHole: (Int, Seq[Any]) => scala.quoted.Type[?], termHole: (Int, Seq[Any], scala.quoted.Quotes) => scala.quoted.Expr[?])(using Context): Tree = {
+  def unpickleTypeTree(pickled: String | List[String], typeHole: TypeHole)(using Context): Tree = {
     val unpickled = withMode(Mode.ReadPositions)(unpickle(pickled, isType = true))
-    spliceTypes(unpickled, typeHole, termHole)
+    spliceTypes(unpickled, typeHole)
   }
 
   /** Replace all term holes with the spliced terms */
-  private def spliceTerms(tree: Tree, typeHole: (Int, Seq[Any]) => scala.quoted.Type[?], termHole: (Int, Seq[Any], scala.quoted.Quotes) => scala.quoted.Expr[?])(using Context): Tree = {
+  private def spliceTerms(tree: Tree, typeHole: TypeHole, termHole: ExprHoleV1 | ExprHoleV2, version: Int)(using Context): Tree = {
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:81]: It can. I will do the change.

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala [hunk 36]
```diff
@@ -51,34 +51,51 @@ object PickledQuotes {
     changeOwnerOfTree(tpe1.typeTree, ctx.owner)
   }
 
+  type TypeHoleArg =  scala.quoted.Type[?]
+  type TypeHole = Null | ((Int, Seq[TypeHoleArg]) => scala.quoted.Type[?])
+
+  type ExprHoleArgV1 =  scala.quoted.Type[?] | (Quotes ?=> scala.quoted.Expr[Any])
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala]: Added

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala [hunk 37]
```diff
@@ -124,18 +141,21 @@ object PickledQuotes {
...
+  private def spliceTypes(tree: Tree, typeHole: TypeHole)(using Context): Tree = {
     tree match
       case Block(stat :: rest, expr1) if stat.symbol.hasAnnotation(defn.QuotedRuntime_SplicedTypeAnnot) =>
         val typeSpliceMap = (stat :: rest).iterator.map {
           case tdef: TypeDef =>
             assert(tdef.symbol.hasAnnotation(defn.QuotedRuntime_SplicedTypeAnnot))
             val tree = tdef.rhs match
-              case TypeBoundsTree(_, Hole(_, idx, args), _) =>
-                val quotedType = typeHole(idx, args)
+              case TypeBoundsTree(_, Hole(_, idx, args, _, _), _) => // to keep for backwards compat
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:152]: Added

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 20 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:129]: Should be a `val`. Fixed.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 21 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:287]: Removed

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 22 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:315]: Added

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 23 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:323]: Changed

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 24 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:319]: Could not make it work without braces. What is the correct syntax?

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 25 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:318]: Removed

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 26 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:79]: Updated

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 27 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:110]: Changed to `val`

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 28 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:321]: Removed

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 29 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala:329]: Removed

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 31 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1608]: It is based on the name of the `Staging` phase that it enables.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 33 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Indeed, `existsPart` seems to be what I need to use here.

File: compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala (hunk 34 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala:230]: Done

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala (hunk 32 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala]: Done.

**Comment by nicolasstucki** [comment]
test performance plese

**Comment by nicolasstucki** [comment]
Test performance please

**Comment by nicolasstucki** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 31 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1608]: But couldn't we merge needsStaging and needsQuotePickling into one variable which is checked in both phases?

**Comment by nicolasstucki** [comment]
test performance with #quotes please

**Comment by nicolasstucki** [comment]
Just realized that the optimization in ae3dc99ae07f529f58934e51136d1fcf96de7c1b will apply to all quoted patterns. This might be what improved the `Quote String interpolation matching` benchmark.

File: compiler/src/dotty/tools/dotc/transform/Splicing.scala (hunk 30 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/Splicing.scala]: Done

**Comment by nicolasstucki** [comment]
> Should these checks be done in TreeChecker#Checker#typedHole instead?

Yes. Moved `TreeChecker#Checker#typedHole`

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 31 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1608]: I thought that we had some cases that needed quote pickling without requiring staging. It seems that this is no longer the case and we can simplify it to a single `needsStaging` contdition.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1606]: Simplified

**Review by smarter — APPROVED** [review]

**Comment by nicolasstucki** [comment]
Rebased

**Comment by nicolasstucki** [comment]
`tests/pos-macros/backwardCompat-3.0` is failing with no error message (see #14303)

**Comment by nicolasstucki** [comment]
Can't manage to make `tests/pos-macros/backwardCompat-3.0` pass. The error is not reported and it is impossible to figure out why it fails (see #14303).

Noticed that if we manually compile those two files using `-Xtarget 9` , `3.0.2` fails to use that target and the compiler fails with a `UnsupportedClassVersionError`. But hardcoding `TestConfiguration.defaultTarget` to `"8"` does not fix the test.

**Review by smarter — CHANGES_REQUESTED** [review]
Otherwise LGTM but I think we should wait until https://github.com/lampepfl/dotty/issues/14306 is fixed before merging this (also we'll need to bump to 3.2.0 before or directly in this PR).

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala [hunk 38]
```diff
@@ -51,9 +51,21 @@ object PickledQuotes {
     changeOwnerOfTree(tpe1.typeTree, ctx.owner)
   }
 
-  /** `typeHole` argument of `QuoteUnpickler.{unpickleExpr,unpickleExprV2,unpickleType,unpickleTypeV2}` */
-  type TypeHole = Null | ((Int, Seq[TypeHoleArg]) => scala.quoted.Type[?])
-  type TypeHoleArg =  scala.quoted.Type[?]
+  /** `typeHole`/`types` argument of `QuoteUnpickler.{unpickleExpr,unpickleExprV2,unpickleType,unpickleTypeV2}` */
+  enum TypeHole:
+    /** `termHole` argument of `QuoteUnpickler.{unpickleExpr, unpickleType}`.
+     *  From code compiled with Scala 3.0.x and 3.1.x
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:57]: Indeed. Will update the doc

File: compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala [hunk 39]
```diff
@@ -146,23 +159,25 @@ object PickledQuotes {
...
-                PickledQuotes.quotedTypeToTree(quotedType)
-              case TypeBoundsTree(_, tpt, _) =>
-                // To keep for backwards compatibility. In some older version we missed the creation of some holes.
-                tpt
-              case Hole(_, idx, args, _, _) =>
-                val quotedType = typeHole(idx, reifyTypeHoleArgs(args))
-                PickledQuotes.quotedTypeToTree(quotedType)
+            val tree = typeHole match
+              case TypeHole.V1(evalHole) =>
+                tdef.rhs match
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala:170]: That is the case. In that version the hole was nested in a `TypeBoundsTree`. This is basically the current logic in the main branch.

**Comment by nicolasstucki** [comment]
> also we'll need to bump to 3.2.0 before or directly in this PR

Yes, to finish this pr we need to bump to 3.2.0. Currently I am generating the new scheme for 3.1 for testing purposes. But 3.1 should also get the old transformation. The places where this needs to change are marked with FXME.

File: sbt-test/scala3-compat/macros-forward-3.0/build.sbt [hunk 40]
```diff
@@ -0,0 +1,13 @@
...
+
+lazy val lib = project.in(file("lib"))
+  .settings(
+    scalacOptions ++= Seq("-Yscala-release", "3.0") ++ checkOptions
+  )
+
+lazy val app = project.in(file("app"))
+  .dependsOn(lib)
+  .settings(
+    scalaVersion := "3.0.2",
```
Comment (nicolasstucki) [inline sbt-test/scala3-compat/macros-forward-3.0/build.sbt:11]: @smarter I ported the previous tests to `sbt-test`. But it seems that this project is trying to load the `3.1.3-RC1-bin-SNAPSHOT` standard library. This happens when I have a dependency on `lib` (even when `lib` is empty). Do you know what I'm missing? 

```
[info] [info] compiling 1 Scala source to /private/var/folders/gl/4_k_l76n3pq17f7zxm0v6v_w0000gn/T/sbt_11f9b5da/app/target/scala-3.0.2/classes ...
[info] [error] error while loading $throws$package$,
[info] [error] class file scala/runtime/$throws$package.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
[info] [error] TASTy signature has wrong version.
[info] [error]  expected: {majorVersion: 28, minorVersion: 0}
[info] [error]  found   : {majorVersion: 28, minorVersion: 2 [unstable release: 1]}
[info] [error] 
[info] [error] This TASTy file was produced by an unstable release.
[info] [error] To read this TASTy file, your tooling must be at the same version.
[info] [error] The TASTy file was produced by Scala 3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped-git-17bf27f.
[info] [error] one error found
[info] [error] one error found
[info] [error] (app / Compile / compileIncremental) Compilation failed
[info] [error] Total time: 7 s, completed Feb 3, 2022 5:05:51 PM
````

Comment (smarter) [reply sbt-test/scala3-compat/macros-forward-3.0/build.sbt:11]: Yeah for now until sbt learns about -Yscala-release you have to manually make the app project depend on the old standard library, see the bottom of https://docs.scala-lang.org/scala3/reference/language-versions/binary-compatibility.html

**Comment by nicolasstucki** [comment]
test performance please

**Comment by nicolasstucki** [comment]
test performance with #quotes please

**Comment by xuwei-k** [comment]
I have just filed related issue 🙏 

- https://github.com/lampepfl/dotty/issues/14708

**Comment by nicolasstucki** [comment]
Finally, we are able to merge this PR. It needs a last review to check that nothing unwanted happened when rebasing.

**Review by smarter — APPROVED** [review]
:sparkle:
