### PR TITLE
Fix #6976: Improve macro exception stack handling

### LINKED ISSUE #6976: Exceptions in macro expansions are not reported properly
## minimized code

Macro file:

```Scala
package playground

import scala.quoted._, scala.quoted.matching._
import delegate scala.quoted._
import scala.tasty._

object macros {
  inline def mcr(x: => Any) = ${mcrImpl('x)}

  def mcrImpl(body: Expr[Any]) given (ctx: QuoteContext): Expr[Any] = {
    import ctx.tasty._
    body.unseal match { case Block(_, _) => '{2} }
  }
}
```

Main method file:

```scala
package playground

import playground.macros._

object Main {
  def main(args: Array[String]): Unit = mcr { 2 }
}
```

On execution, it says:

```scala
[error] -- Error: /Users/anatolii/Projects/dotty/playground/core/src/main/scala/playground/Main.scala:6:44
[error] 6 |  def main(args: Array[String]): Unit = mcr { 2 }
[error]   |                                        ^^^^^^^^^
[error]   |An exception occurred while executing macro expansion: Inlined(EmptyTree,List(),Literal(Constant(2))) (of class dotty.tools.dotc.ast.Trees$Inlined)
[error]   |sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]   |sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]   |sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]   |java.lang.reflect.Method.invoke(Method.java:498)
[error]   |
[error]   | This location is in code that was inlined at Main.scala:6
[error] one error found
```

## expectation
The type of the exception, as well as its error message, should be output instead of the "An exception occurred".

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Splicer.scala [hunk 1]
```diff
@@ -352,13 +352,16 @@ object Splicer {
...
-          for (stack <- ex.getTargetException.getStackTrace.iterator.takeWhile(_.getClassName != this.getClass.getName).drop(1)) {
-            sw.write(stack.toString)
-            sw.write("\n")
+          sw.write("Exception occurred while executing macro expansion.\n")
+          val targetException = ex.getTargetException
+          if (!ctx.settings.Ydebug.value) {
+            val end = ex.getTargetException.getStackTrace.lastIndexWhere { x =>
+              x.getClassName == method.getDeclaringClass.getCanonicalName && x.getMethodName == method.getName
+            }
+            val shortStackTrace = ex.getTargetException.getStackTrace.take(end + 1)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/Splicer.scala]: Same here
