### PR TITLE
Fix#12600: Handle ExprType during tab completion

### LINKED ISSUE #12600: REPL crash with tab completion - invalid prefix ExprType
## Compiler version

3.0.1 repl

## Minimized code

```Scala
// command 1
import quoted.*
```

```Scala
// command 2
def fooImpl(using Quotes): Expr[Int] = {
  import quotes.reflect.*
  TypeRepr.of[Int].<tab>
}
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: invalid prefix ExprType(TypeRef(TermRef(TermRef(NoPrefix,val x$1),val reflect),trait ConstantTypeMethods))
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.Types$NamedType.<init>(Types.scala:2025)
	at dotty.tools.dotc.core.Types$TermRef.<init>(Types.scala:2567)
	at dotty.tools.dotc.core.Types$CachedTermRef.<init>(Types.scala:2646)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.newType$1(Uniques.scala:42)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.enterIfNew(Uniques.scala:53)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2697)
	at dotty.tools.dotc.interactive.Completion$$anon$3.applyOrElse(Completion.scala:326)
	at dotty.tools.dotc.interactive.Completion$$anon$3.applyOrElse(Completion.scala:326)
	at scala.collection.immutable.List.collect(List.scala:267)
	at scala.collection.immutable.List.collect(List.scala:79)
	at dotty.tools.dotc.interactive.Completion$Completer.extractMemberExtensionMethods$2$$anonfun$1(Completion.scala:326)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at dotty.tools.dotc.interactive.Completion$Completer.extractMemberExtensionMethods$1(Completion.scala:326)
	at dotty.tools.dotc.interactive.Completion$Completer.extensionCompletions(Completion.scala:347)
	at dotty.tools.dotc.interactive.Completion$Completer.selectionCompletions(Completion.scala:243)
	at dotty.tools.dotc.interactive.Completion$.computeCompletions(Completion.scala:115)
	at dotty.tools.dotc.interactive.Completion$.completions(Completion.scala:49)
	at dotty.tools.repl.ReplDriver.completions$$anonfun$1(ReplDriver.scala:203)
	at scala.util.Either.map(Either.scala:382)
	at dotty.tools.repl.ReplDriver.completions(ReplDriver.scala:204)
	at dotty.tools.repl.ReplDriver.$anonfun$3(ReplDriver.scala:128)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4412)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4378)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4317)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3809)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
	at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:72)
	at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:133)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:143)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:148)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:167)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:148)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:114)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

### LINKED ISSUE #13365: Interactive - completions on `scala.quoted.Quotes.reflectModule.Term` fails
## 3.0.1

Originally reported in [metals repo](https://github.com/scalameta/metals/issues/3052)
Calling a completions on `tree` from the last line fails:

```Scala
import scala.quoted._

object Test {
  def test(using Quotes)(str: String) = {
    import quotes.reflect._
    val msg = Expr(str)
    msg.sh@@ow // works well
    val printHello = '{ print($msg) }
    val tree = printHello.asTerm 
    tree.sh@@ // doesn't work
  }
}
```

Error:
```
Exception in thread "pool-3-thread-11" java.lang.AssertionError: assertion failed: invalid prefix ExprType(TypeRef(TermRef(TermRef(NoPrefix,val x$2),val reflect),trait AnnotatedMethods))
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.Types$NamedType.<init>(Types.scala:2043)
	at dotty.tools.dotc.core.Types$TermRef.<init>(Types.scala:2585)
	at dotty.tools.dotc.core.Types$CachedTermRef.<init>(Types.scala:2664)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.newType$1(Uniques.scala:42)
	at dotty.tools.dotc.core.Uniques$NamedTypeUniques.enterIfNew(Uniques.scala:53)
	at dotty.tools.dotc.core.Types$TermRef$.apply(Types.scala:2715)
	at dotty.tools.dotc.interactive.Completion$$anon$3.applyOrElse(Completion.scala:305)
	at dotty.tools.dotc.interactive.Completion$$anon$3.applyOrElse(Completion.scala:305)
	at scala.collection.immutable.List.collect(List.scala:267)
	at scala.collection.immutable.List.collect(List.scala:79)
	at dotty.tools.dotc.interactive.Completion$Completer.extractMemberExtensionMethods$2$$anonfun$1(Completion.scala:305)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at dotty.tools.dotc.interactive.Completion$Completer.extractMemberExtensionMethods$1(Completion.scala:305)
	at dotty.tools.dotc.interactive.Completion$Completer.extensionCompletions(Completion.scala:326)
	at dotty.tools.dotc.interactive.Completion$Completer.selectionCompletions(Completion.scala:222)
	at dotty.tools.dotc.interactive.Completion$.computeCompletions(Completion.scala:115)
	at dotty.tools.dotc.interactive.Completion$.completions(Completion.scala:49)
	at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:39)
	at scala.meta.internal.pc.ScalaPresentationCompiler.complete$$anonfun$1(ScalaPresentationCompiler.scala:157)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$1(CompilerAccess.scala:87)
	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:197)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:139)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### PR DESCRIPTION
**Pull request by griggt**
Fixes #12600
Fixes #13365

### CODE REVIEW

File: language-server/test/dotty/tools/languageserver/CompletionTest.scala [hunk 1]
```diff
@@ -842,4 +842,19 @@ class CompletionTest {
...
+  @Test def i13365: Unit = {
+    code"""|import scala.quoted._
+        |
+        |object Test {
+        |  def test(using Quotes)(str: String) = {
+        |    import quotes.reflect._
+        |    val msg = Expr(str)
+        |    val printHello = '{ print("sdsd") }
+        |    val tree = printHello.asTerm
+        |    tree.sh${m1}@@ // doesn't work
```
Comment (prolativ) [inline language-server/test/dotty/tools/languageserver/CompletionTest.scala:855]:
```suggestion
        |    tree.sh${m1}
```
After the fix the comment makes sense.
`@@` is an equivalent of `${m1}` in tests of metals

**Review by prolativ — CHANGES_REQUESTED** [review]

**Review by prolativ — APPROVED** [review]
