### PR TITLE
Fix #2795: Fix name kind testing logic

### LINKED ISSUE #2795: Missing/abstract param accessor in implicit parameter of trait
```scala
trait Foo[T: ClassTag]() {
  def foo(x: T) = Array(x)
}
class Bar extends Foo[Int]()
```
fails with a `java.lang.AbstractMethodError: Method Bar.Foo$$evidence$1()Lscala/reflect/ClassTag; is abstract`

Where the tree after `genBCode` looks like

```
<trait> trait Foo extends Object { 
    def $init$(): Unit = ()
    implicit <accessor> def Foo$$evidence$1(): scala.reflect.ClassTag
    def foo(x: Object): Object = 
      Array.apply(Predef.genericWrapArray([x : Object]), this.Foo$$evidence$1())
  }
class Bar
   extends Object with Foo { 
    def <init>(): Unit = 
      {
        super()
        super[Foo].$init$()
        ()
      }
  }
```

### PR DESCRIPTION
**Pull request by odersky**
The previous logic would have UniqueNames shadow everything else. So if one starts
with a UniqueName(prefix, sep, number), and then does a qualified name, one gets a
unique name over a qualified name. The resulting name should still be recognized as a
qualified name, however. The change in this commit achieves that.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Names.scala [hunk 1]
```diff
@@ -233,17 +233,25 @@ object Names {
       }
     }
 
+    /** Is it impossible that trees of kind `kind` qualify as
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Names.scala]: you mean names, not trees, right?

Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Names.scala]: Oops. Of course.
