### PR TITLE
Make unchecked cases non-`@unchecked` and non-unreachable

### LINKED ISSUE #16451: Expected "the type test for <blah> cannot be checked at runtime" warning but none were produced
## Compiler version

`3.2.1` from https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.1/scala3-compiler_3-3.2.1.jar

## Minimized code

Given some generic class (in this case `Wrapper`) and some other type (in this case `Color` but I think this doesn't matter too much):
```scala
case class Wrapper[A](value: A)
enum Color:
  case Red, Green
```

The following code doesn't produce any warnings I think but I expect "the type test for &lt;blah&gt; cannot be checked at runtime":
```scala
def test_wrong(x: Wrapper[Color]): Option[Wrapper[Color.Red.type]] =
  x match
    case x: Wrapper[Color.Red.type] => Some(x)
    case _                          => None

def test_wrong_seq(xs: Seq[Wrapper[Color]]): Seq[Wrapper[Color.Red.type]] =
  xs.collect { case x: Wrapper[Color.Red.type] => x }
```

## Output

```scala
println(test_wrong_seq(Seq(Wrapper(Color.Red), Wrapper(Color.Green))))
// outputs: List(Wrapper(Red), Wrapper(Green))
```
The output is expected but no warnings is not expected.

## Expectation

What I expect when pattern matching on the type is:
```scala
def test_correct(x: Wrapper[Color]): Option[Wrapper[Color.Red.type]] =
  x match
    case x: Wrapper[Color.Red.type]   => Some(x)
    case x: Wrapper[Color.Green.type] => None
```
gives "the type test for &lt;blah&gt; cannot be checked at runtime":
```plain
[warn] -- [E029] Pattern Match Exhaustivity Warning: Example.scala:147:6
[warn] 147 |      x match
[warn]     |      ^
[warn]     |      match may not be exhaustive.
[warn]     |
[warn]     |      It would fail on pattern case: Wrapper(_)
[warn]     |
[warn]     | longer explanation available when compiling with `-explain`
[warn] -- [E030] Match case Unreachable Warning: Example.scala:152:13
[warn] 152 |        case x: Wrapper[Color.Red.type] => Some(x)
[warn]     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]     |             Unreachable case
[warn] -- Unchecked Warning: Example.scala:148:13
[warn] 148 |        case x: Wrapper[Color.Red.type]   => Some(x)
[warn]     |             ^
[warn]     |the type test for Wrapper[(Color.Red : => Color)] cannot be checked at runtime
[warn] -- Unchecked Warning: Example.scala:149:13
[warn] 149 |        case x: Wrapper[Color.Green.type] => None
[warn]     |             ^
[warn]     |the type test for Wrapper[(Color.Green : => Color)] cannot be checked at runtime
```

Hopefully this isn't a duplicate! I did some searching but I could always have missed something.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #16451

### CODE REVIEW

**Comment by dwijnand** [comment]
@liufengyun as usual, any comments or questions welcome - we always end up with a better change afterwards! 😉

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -461,16 +462,19 @@ object SpaceEngine {
...
 
       case tp @ AppliedType(tycon, args) =>
         val args2 =
-          if (tycon.isRef(defn.ArrayClass)) args.map(arg => erase(arg, inArray = true, isValue = false))
-          else args.map(arg => erase(arg, inArray = false, isValue = false))
+          if tycon.isRef(defn.ArrayClass) then
+            args.map(arg => erase(arg, inArray = true, isValue = false))
+          else tycon.typeParams.lazyZip(args).map { (tparam, arg) =>
+            if isValue && tparam.paramVarianceSign == 0 then WildcardType
+            else erase(arg, inArray = false, isValue = false)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:476]: Maybe add a document for the case `tparam.paramVarianceSign == 0`.

**Review by liufengyun — APPROVED** [review]
Otherwise, LGTM
