### PR TITLE
Scaladoc: Enums and enum cases fix

### LINKED ISSUE #11497: Missing enum children in Scaladoc

### PR DESCRIPTION
**Pull request by pikinier20**
closes #11497

### CODE REVIEW

File: scaladoc-testcases/src/tests/enumSignatures.scala [hunk 1]
```diff
@@ -9,19 +9,19 @@ enum Enum1
   case C
 }
 enum Enum2(val i: Int):
-  case A(val s: String) extends Enum2(1)
-  case B(val t: String) extends Enum2(2)
-  case C(val u: String) extends Enum2(3)
+  case A(s: String) extends Enum2/*<-*/(1)/*->*/
```
Comment (BarkingBad) [inline scaladoc-testcases/src/tests/enumSignatures.scala:12]: What is the reason for these funny inlined comments?

**Review by BarkingBad — APPROVED** [review]

File: scaladoc-testcases/src/tests/enumSignatures.scala (hunk 1 above)
Comment (pikinier20) [reply scaladoc-testcases/src/tests/enumSignatures.scala:12]: These arrows are marking fragments of signature that shouldn't be documented. We don't document constructors of parents and test would fail without that.
