### PR TITLE
Refine parameter adaptation logic for arrays 

### LINKED ISSUE #23179: LambdaConversionException: Type mismatch for instantiated parameter
## Compiler version

- 3.3.6
- 3.7.0
- 3.7.1-RC1
- 3.7.2-RC1-bin-20250515-c481e91-NIGHTLY

## Minimized code

JDK 11 or later

```
Welcome to Scala 3.7.1-RC1 (11.0.26, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                          
scala> trait A { def f(a: Array[AnyRef]): Any }
// defined trait A
                                                                                                                                          
scala> def g(a: A) = a.f(Array.empty[AnyRef])
def g(a: A): Any
                                                                                                                                          
scala> g((x: Array[? >: AnyRef]) => x.headOption)
java.lang.BootstrapMethodError: bootstrap method initialization exception
  at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:194)
  at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307)
  at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258)
  at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248)
  ... 66 elided
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for instantiated parameter 0: class java.lang.Object is not a subtype of class [Ljava.lang.Object;
  at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.checkDescriptor(AbstractValidatingLambdaMetafactory.java:308)
  at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:294)
  at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:503)
  at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:138)
  ... 69 more
```

JDK 8

```
Welcome to Scala 3.7.1-RC1 (1.8.0_442, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                          
scala> trait A { def f(a: Array[AnyRef]): Any }
// defined trait A
                                                                                                                                          
scala> def g(a: A) = a.f(Array.empty[AnyRef])
def g(a: A): Any
                                                                                                                                          
scala> g((x: Array[? >: AnyRef]) => x.headOption)
val res0: Any = None
```

## Expectation

compile error or success. don't throw runtime error

## Note

Scala 2.13.16

```
Welcome to Scala 2.13.16 (OpenJDK 64-Bit Server VM, Java 11.0.26).
Type in expressions for evaluation. Or try :help.

scala> trait A { def f(a: Array[AnyRef]): Any }
trait A

scala> def g(a: A) = a.f(Array.empty[AnyRef])
def g(a: A): Any

scala> g((x: Array[? >: AnyRef]) => x.headOption)
val res0: Any = None
```

Scala 2.12.20

```
Welcome to Scala 2.12.20 (OpenJDK 64-Bit Server VM, Java 11.0.26).
Type in expressions for evaluation. Or try :help.

scala> trait A { def f(a: Array[AnyRef]): Any }
defined trait A

scala> def g(a: A) = a.f(Array.empty[AnyRef])
g: (a: A)Any

scala> g((x: Array[? >: AnyRef]) => x.headOption)
res0: Any = None
```

### PR DESCRIPTION
**Pull request by bracevac**
Fixes #23179

Since JDK 9, argument checks for LambdaMetaFactory have become stricter. Which is to say that its JDK 8 version was too lax.

We apply adaptation now in case the samType is an array, but the implType is not.

### CODE REVIEW

**Comment by sjrd** [comment]
This seems misguided to me. Why `AnyRef` but not any of its subtypes? Also, this is not supported by spec text, whether from the Scala 2 or Scala 3 spec. 

Changes to erasure are extremely risky, because they basically break tasty and binary compatibility every time. They need a very strong justification. Typically, only fixing unsoundness is a good enough reason to do this.

**Comment by bracevac** [comment]
~Scala 2 certainly erases this array type to `Object[]`.~ What should be the general rule? 

Edit: Hmm it does not, at least judging by `-Xprint:erasure`. However in the resulting bytecode, the two relevant arguments to `altMetaFactory` are consistently array types, whereas in Scala 3 the second one ends up being `Object`.

```
BootstrapMethods:
  0: #38 REF_invokeStatic java/lang/invoke/LambdaMetafactory.altMetafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #26 ([Ljava/lang/Object;)Ljava/lang/Object;
      #30 REF_invokeStatic Test$.$anonfun$new$1$adapted:([Ljava/lang/Object;)Ljava/lang/Object;
      #26 ([Ljava/lang/Object;)Ljava/lang/Object;
      #31 0
```

**Comment by bracevac** [comment]
If we do not want to mess with erasure, could we just uniformly use the erased SAM methodtype for the implementation method type as well in the emitted bytecode? Would this always be safe for a type-correct source program?

**Comment by sjrd** [comment]
Probably, but we would need to do that at the backend level. Basically consider it a bridge method, or an `$adapted` something something. The extracted `private def` likely cannot be altered to take a different parameter type.

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala [hunk 1]
```diff
@@ -483,8 +483,13 @@ object Erasure {
       def sameClass(tp1: Type, tp2: Type) = tp1.classSymbol == tp2.classSymbol
 
       val paramAdaptationNeeded =
-        implParamTypes.lazyZip(samParamTypes).exists((implType, samType) =>
-          !sameClass(implType, samType) && !autoAdaptedParam(implType))
+        implParamTypes.lazyZip(samParamTypes).exists: (implType, samType) =>
+          !sameClass(implType, samType) && !autoAdaptedParam(implType)
+          || (samType, implType).match {
+            case (defn.ArrayOf(_), defn.ArrayOf(_)) => false
+            case (defn.ArrayOf(_), _) => true // see #23179
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/Erasure.scala]: Shouldn't there be the reverse order as well (`(_, defn.ArrayOf(_))`)? Like if the SAM takes an `Array[T]` where `T <: AnyRef` but the lambda is specialized to `T = String`, for example?

**Review by sjrd — COMMENTED** [review]
The new approach seems reasonable.

It might need similar changes in `ExpandSAMs` for Scala SAM types that don't translate to target SAM types.

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala (hunk 1 above)
Comment (bracevac) [reply compiler/src/dotty/tools/dotc/transform/Erasure.scala]: I'm unable to construct such a reversed example that will be accepted by the compiler.

Comment (lrytz) [reply compiler/src/dotty/tools/dotc/transform/Erasure.scala]: Do we need something similar for the result type (`resultAdaptationNeeded`)?

**Comment by bracevac** [comment]
> The new approach seems reasonable.
> 
> It might need similar changes in `ExpandSAMs` for Scala SAM types that don't translate to target SAM types.

I tried constructing each of the five cases in the comment at the top of `ExpandSAMs`, but those were either rejected or did not crash at run time.

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala (hunk 1 above)
Comment (bracevac) [reply compiler/src/dotty/tools/dotc/transform/Erasure.scala]: Not sure, I also fail here to construct an example that would cause a run time crash (which is of course weak evidence).

**Comment by lrytz** [comment]
It might be worth including the other combinations in the test case as regression tests.

**Comment by bracevac** [comment]
This solution doesn't appear to work for ScalaJS, I'll need to dig deeper.

**Comment by bracevac** [comment]
@sjrd @lrytz for scalajs, I needed to tweak `ExpandSAMs` next to the JVM-specific tweak in `Erasure`. The tests all pass now. I've also added the requested regression tests.

PS: The failing stdlib test is CC-related and not due to this PR. It also fails on main.

File: compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala [hunk 2]
```diff
@@ -69,14 +70,52 @@ class ExpandSAMs extends MiniPhase:
...
+          val samInfo = samDenot.info
+          val implInfo = implSym.info
+          val needsArrayAdaptation = (samInfo, implInfo) match
+            case (samMt: MethodType, implMt: MethodType) =>
+              samMt.paramInfos.lazyZip(implMt.paramInfos).exists { (samPt, implPt) =>
+                erasure(samPt).isInstanceOf[JavaArrayType] && !erasure(implPt).isInstanceOf[JavaArrayType]
+              }
+            case _ => false
+
+          val forwarderSym =
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala]: `val forwarderSym` seems to be directly followed by `forwarderSym`. Remove the `val` and directly use the `if/else` as result.

File: compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala [hunk 3]
```diff
@@ -69,14 +70,52 @@ class ExpandSAMs extends MiniPhase:
...
+          val implSym = fn.symbol.asTerm
+
+          // Check if SAM param erases to array but impl param doesn't (see #23179).
+          // E.g. SAM expects Array[AnyRef] (erases to Array[Object]) but impl has
+          // Array[? >: AnyRef] (erases to Object). In this case we need to create
+          // a wrapper with the SAM signature that casts arguments before forwarding.
+          val samInfo = samDenot.info
+          val implInfo = implSym.info
+          val needsArrayAdaptation = (samInfo, implInfo) match
+            case (samMt: MethodType, implMt: MethodType) =>
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala:82]: What if it's hidden behind a `PolyType`? Or in a second term param list?

File: compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala (hunk 2 above)
Comment (bracevac) [reply compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala]: Done

File: compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala (hunk 3 above)
Comment (bracevac) [reply compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala:82]: Do you have a concrete example in mind? Those cases do not qualify as SAMs afaik. 
I've added more run tests that involve multiple parameters and a generic return type on the trait.

For generics on the method, the compiler rejects both of these:
```scala
trait PolyA { def f[T](a: Array[AnyRef]): T }

object Test {
  def gPoly(a: PolyA) = a.f[Int](Array.empty[AnyRef])

  def main(args: Array[String]): Unit = {
    gPoly([T] => (x: Array[? >: AnyRef]) => x.length.asInstanceOf[T]) // error

    gPoly(new PolyA { // error
      def f[T](x: Array[? >: AnyRef]): T = x.length.asInstanceOf[T]
    })
  }
}
```
Same goes for curried argument lists:
```scala
trait CurriedA { def f(a: Array[AnyRef])(b: Int): Any }

object Test {
  def gCurried(a: CurriedA) = a.f(Array.empty[AnyRef])(42)

  def main(args: Array[String]): Unit = {
    gCurried((x: Array[AnyRef]) => (n: Int) => x.headOption) // error
  }
}
```
Scala 2 rejects these as well (modulo the polymorphic lambda syntax of course).

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala:82]: > Those cases do not qualify as SAMs afaik.

Right. I missed that. Seems all good.

**Comment by WojciechMazur** [comment]
Should this change be backported to 3.8.0? It seems to be that it might be useful, since it's now compiled with JDK 17 so potentially might be affected. 
I guess that changes here should also help with fixing #24573 which this time was affected by result type checks

**Comment by bracevac** [comment]
Yes, any JDK newer than 8 would result in a runtime failure for the kind of example this PR addresses.
