### PR TITLE
Fix #13455: Also consider sealed classes closed sums

### LINKED ISSUE #13455: Sealed traits behave different than sealed class for type match reduction
## Compiler version

3.0.1

## Minimized code

```scala
  sealed class R

  type X[T] = T match {
    case R        => String
    case (z => r) => Int
  }
  def x[T]: X[T] = ???
  
  def i(i0: Int): Unit = ???
  i(x[Int => String])
```

This match type fails with

```
[error] 30 |  i(x[Int => String])
[error]    |    ^^^^^^^^^^^^^^^^
[error]    |    Found:    X[Int => String]
[error]    |    Required: Int
[error]    |
[error]    |    Note: a match type could not be fully reduced:
[error]    |
[error]    |      trying to reduce  X[Int => String]
[error]    |      failed since selector  Int => String
[error]    |      does not match  case R => String
[error]    |      and cannot be shown to be disjoint from it either.
[error]    |      Therefore, reduction cannot advance to the remaining case
[error]    |
[error]    |        case z => r => Int
```

when the same example with

```scala
  sealed trait R
```

works?

## Expectation

Both examples compile.

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -2528,7 +2528,7 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
 
     /** Can we enumerate all instantiations of this type? */
     def isClosedSum(tp: Symbol): Boolean =
-      tp.is(Sealed) && tp.isOneOf(AbstractOrTrait) && !tp.hasAnonymousChild
+      tp.is(Sealed) && !tp.hasAnonymousChild
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2531]: should we check that it actually has children? and what about `sealed abstract case class`

Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2531]: This method is used as a predicate to decompose types along their children (we then do `.forall` on each children). So in the case of a sealed class with zero children, the algorithm will be able correctly conclude disjointness (a sealed type without children is empty!).

I didn't think about the `sealed abstract case class` combination, but I don't think it requires any particular treatment...

Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2531]: This logic relies on the contract from the `children` method:

```
/** If this is a sealed class, its known children in the order of textual occurrence */
def children(using Context): List[Symbol] =
```

If a sealed type has children that are unlisted by that method, then we are in trouble.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2531]: I only bring up `sealed case class` because I imagine it should be considered either a sum or product with the same rule as Mirror synthesis decides, however, seeing as this is about possible sub classes at runtime then it probably does not matter

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2531]: I suspect you can't make this change without also changing the usage of `children` because now there could be values of type Foo that aren't Foo1 or Foo2.  Similar to Jamie's sealedDescendants vs sealedStrictDescendants.

**Review by dwijnand — CHANGES_REQUESTED** [review]
After commenting in #13455, I'm more certain that this you can't change this and not change the children side too, though I don't have the concrete counter-example to prove it.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: @dwijnand I see what you mean, but at the precise point where we use decompose we know that `new Foo` isn't a subtype of `tp2`, so it's safe to decompose it regardless of if it's an abstract or concrete class. To put it another way (in the context of your https://github.com/lampepfl/dotty/issues/13455#issuecomment-918251986), since at this point in the code we know that `new R` is not an instance of `Function1[X, Y]`, and because `R` is sealed, it's OK to decompose `R` using `.children`. Does this make sense?

I added a refactoring commit to try to clarify that point in the code.

**Review by bishabosha — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -2570,9 +2563,12 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
             // subtype, so they must be unrelated by single inheritance
             // of classes.
             true
-          else if (isClosedSum(cls1))
+          else if (isDecomposable(cls1))
+            // At this point, !cls1.derivesFrom(cls2): we know that `new cls2`
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2567]:
```suggestion
            // At this point, !cls1.derivesFrom(cls2): we know that `cls1`
```

**Review by dwijnand — APPROVED** [review]
A small typo (iiuc) but looks good to me now, thanks for the attention, @OlivierBlanvillain!

**Comment by dwijnand** [comment]
Even better. 💯
