### PR TITLE
Fix #9967: Don't add forwarders for super accessors

### LINKED ISSUE #9967: Can't export all members of mutable.TreeMap (tried with List as well)
dottyVersion = "0.27.0-RC1"
Please find 3 different verions and 2 different outputs here:
## Minimized code
1:
```Scala
class MaxSizeMap[K, V](maxSize: Int)(using o: Ordering[K]):
  private val sortedMap: mutable.TreeMap[K, V] = mutable.TreeMap.empty[K, V](o)
  
  export sortedMap._
```
2:
```Scala
class MaxSizeMap[K, V](maxSize: Int)(using o: Ordering[K]):
  val sortedMap: mutable.TreeMap[K, V] = mutable.TreeMap.empty[K, V](o)
  
  export sortedMap._
```
3:
notice that all the methods I had to exclude to get rid of error messages from 1 return this.type
```Scala
class MaxSizeMap[K, V](maxSize: Int)(using o: Ordering[K]):
  private val sortedMap: mutable.TreeMap[K, V] = mutable.TreeMap.empty[K, V](o)
  
  export sortedMap.{mapValuesInPlace => _, toIterable => _, seq => _, --= => _, ++= => _, += => _, addAll => _, subtractAll => _, 
    lazyZip => _, filterInPlace => _, -= => _, addOne => _, subtractOne => _, transform => _, retain => _, _}
```

## Output
1:
```scala
[error] 8 |  export sortedMap._
[error]   |                   ^
[error]   |non-private method += in class MaxSizeMap refers to private value sortedMap
[error]   |in its type signature (elem1: (K, V), elem2: (K, V), elems: (K, V)*): 
[error]   |  (MaxSizeMap.this.sortedMap : collection.mutable.TreeMap[K, V])
```
2 and 3 (same stack trace):
truncated stack trace:
```scala
[error] ## Exception when compiling 6 sources to /home/michal/programming/scala/crypto-db/target/scala-0.27/classes
[error] java.lang.AssertionError: assertion failed
[error] dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
[error] dotty.tools.dotc.transform.ResolveSuper.transformDefDef(ResolveSuper.scala:63)
[error] dotty.tools.dotc.transform.MegaPhase.goDefDef(MegaPhase.scala:973)
[error] dotty.tools.dotc.transform.MegaPhase.goDefDef(MegaPhase.scala:974)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:426)
[error] dotty.tools.dotc.transform.MegaPhase.transformStat$2(MegaPhase.scala:436)
[error] dotty.tools.dotc.transform.MegaPhase.recur$3$$anonfun$1(MegaPhase.scala:441)
[error] dotty.tools.dotc.transform.MegaPhase$$Lambda$6255/00000000480AB540.apply(Unknown Source)
[error] scala.collection.immutable.List.mapConserve(List.scala:472)
```
## Expectation
It compiles

### PR DESCRIPTION
**Pull request by odersky**
Super accessors are flagged as Artifact in dotty, but not in nsc. So
We need to weed them out separately when creating export forwarders.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 1]
```diff
@@ -1029,10 +1029,13 @@ class Namer { typer: Typer =>
 
         def addWildcardForwarders(seen: List[TermName], span: Span): Unit =
           for mbr <- path.tpe.membersBasedOnFlags(required = EmptyFlags, excluded = PrivateOrSynthetic) do
-            val alias = mbr.name.toTermName
-            if !seen.contains(alias)
-               && mbr.matchesImportBound(if mbr.symbol.is(Given) then givenBound else wildcardBound)
-            then addForwarder(alias, mbr, span)
+            if !mbr.symbol.isSuperAccessor then
+              // Scala 2 superaccessors have neither Synthetic nor Artfact set, so we
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:1033]: Alternatively I guess we could set these flags for superaccessors in Scala2Unpickler, that way we're sure they're treated like the dotty ones.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:1033]: I'd consider that if we find other areas where the missing flag for super accessors messes things up. As it is now, we exercise the test a lot less often than if we have to test every symbol read from Scala 2 for whether it is a super accessor.

**Review by smarter — APPROVED** [review]
