### PR TITLE
Fix #7868: Normalize type parameter in ValueOf

### LINKED ISSUE #7868: Error: No singleton value available for scala.compiletime.S[scala.compiletime.S[(0 : Int)]].
## minimized code

```Scala
import scala.compiletime._

final case class Coproduct[+Set, +Value, Index <: Int](value: Value & Set, index: Index)

object Coproduct {
  opaque type +:[+A, +B] = A | B

  trait At[+Set, -Value, Index <: Int] {
    def cast: Value <:< Set
  }

  object At {

    given atHead[Head, Tail]: At[Head +: Tail, Head, 0] {
      def cast: Head <:< Head +: Tail = summon[Head <:< Head +: Tail]
    }

    given atTail[Head, Tail, Value, NextIndex <: Int](given atNext: At[Tail, Value, NextIndex]): At[Head +: Tail, Value, S[NextIndex]] {
      val cast: Value <:< Head +: Tail = atNext.cast
    }

    given [A](given A): (() => A)= { () => summon[A]}
  }

  def upCast[A, B](a: A)(given erased evidence: (A <:< B)): B = a.asInstanceOf[B]

  def from[Set, Value, Index <: Int](value: Value)(given erased at: At[Set, Value, Index])(given ValueOf[Index]): Coproduct[Set, Value, Index] = {
    Coproduct[Set, Value, Index](upCast(value: Value)(given at.cast.liftCo[[+X] =>> Value & X]), valueOf[Index])
  }

}

object Test extends App {
  import Coproduct._

  // Error: No singleton value available for scala.compiletime.S[scala.compiletime.S[(0 : Int)]].
  val c = from[Set = Int +: String +: Seq[Double] +: Nothing](Nil)
}
```

## expectation

It should compile

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: tests/pos/i7868.scala [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    given atTail[Head, Tail, Value, NextIndex <: Int](given atNext: At[Tail, Value, NextIndex]): At[Head +: Tail, Value, S[NextIndex]] {
+      val cast: Value <:< Head +: Tail = atNext.cast
+    }
+
+    given [A](given A): (() => A)= { () => summon[A]}
+  }
+
+  def upCast[A, B](a: A)(given erased evidence: (A <:< B)): B = a.asInstanceOf[B]
+
+  def from[Set, Value, Index <: Int](value: Value)(given erased at: At[Set, Value, Index]): (given ValueOf[Index]) => Coproduct[Set, Value, Index] = {
```
Comment (nicolasstucki) [inline tests/pos/i7868.scala]: I had to change the test case slightly to make sure  `Index` was fully defined before looking for `ValueOf[Index]`.

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 2]
```diff
@@ -861,7 +861,7 @@ trait Implicits { self: Typer =>
 
       formal.argTypes match {
         case arg :: Nil =>
-          fullyDefinedType(arg.dealias, "ValueOf argument", span) match {
+          fullyDefinedType(arg.dealias, "ValueOf argument", span).normalized match {
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: Not sure if it should be instead
```scala
fullyDefinedType(arg.dealias.normalized, "ValueOf argument", span)
// or
fullyDefinedType(arg.normalized.dealias, "ValueOf argument", span)
```

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Implicits.scala]: I think it's most general this way.
