### PR TITLE
Don't follow BaseType of abstract binders in MT reduction

### LINKED ISSUE #11982: Singleton inference failure when used in same file
## Compiler version

3.0.0-RC2

## Minimized code

The following compiles fine on it's own:
```Scala
package tuplefun
object Unpair {

  def pair[A, B](using a: ValueOf[A], b: ValueOf[B]): Tuple2[A, B] =
    (a.value, b.value)

  def unpair[X <: Tuple2[?, ?]](
      using a: ValueOf[Tuple.Head[X]],
            b: ValueOf[Tuple.Head[Tuple.Tail[X]]]
  ): Tuple2[Tuple.Head[X], Tuple.Head[Tuple.Tail[X]]] =
    type AA = Tuple.Head[X]
    type BB = Tuple.Head[Tuple.Tail[X]]
    pair[AA, BB](using a, b)
}
```

However, attempts to use `unpair` within the same file fail to compile, see the following scastie for an example:
https://scastie.scala-lang.org/wa8mgjM9TPOY2trROxRWXg

Everything compiles and works if we move `UnpairApp`, shown in above scastie link and below, to a new file.

```Scala
object UnpairApp {
  import Unpair._

  type Tshape = ("msg", 42)

  // the following won't compile when in the same file as Unpair
  val p1: ("msg", 42) = unpair[Tshape] // error: No singleton value available for Any

  @main def pairHello: Unit =
    assert(p1 == ("msg", 42))
    println(p1)
}
```

Additionally if one loads the `console` in `sbt` and imports `unpair` things work:

```
scala> import tuplefun.Unpair.unpair

scala> type T = ("msg", 42)
// defined alias type T = ("msg", 42)

scala> unpair[T]                   
val res0: ("msg", 42) = (msg,42)
```

## Expectation

`UnpairApp` and/or usage of `unpair` should compile whether defined in the same file or a separate file from `Unpair`

## What are you doing?

If curious, the motivation that lead me here was trying to call a function of the form `def func[A, B]` when what I have is a type alias `type T = Tuple2[A, B]` and I do not want to spell out the types again.

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
Fix #11982 and the associated soundness problem. The issue with the behavior on master arises from the fact that type binder of match types might change as context gets more precise, which results in a single match type reducing in two different ways. This issue comes from the fact that subtyping looks into base types, and is thus able to match a type such as `T <: Tuple2[Int, Int]` against a pattern `case Tuple2[a, b]`, even if the best solutions for `a` and `b` in the current context are not guaranteed to be the best solution in more precise contexts (such as at call site in the added test case).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -756,8 +756,13 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
     }
 
     def tryBaseType(cls2: Symbol) = {
+      val allowBaseType = caseLambda.eq(NoType) || (tp1 match {
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:759]: Better: !caseLambda.exists

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -776,7 +781,7 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
                 || narrowGADTBounds(tp1, tp2, approx, isUpper = true))
               && (tp2.isAny || GADTusage(tp1.symbol))
 
-            isSubType(hi1, tp2, approx.addLow) || compareGADT || tryLiftedToThis1
+            caseLambda.eq(NoType) && isSubType(hi1, tp2, approx.addLow) || compareGADT || tryLiftedToThis1
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:784]: !caseLambda.exists

**Review by odersky — APPROVED** [review]
