### PR TITLE
Fix displaying some signatures in scaladoc

### LINKED ISSUE #13297: Incorrect indentation for (nested) match types in scaladoc
## Compiler version

scaladoc generated for `3.0.3-RC1-bin-20210815-1524a5a-NIGHTLY`
## Example
[https://dotty.epfl.ch/api/scala/Tuple$.html#Take-0](https://dotty.epfl.ch/api/scala/Tuple$.html#Take-0)

## Output
image

## Expectation
Types printed out by the doctool should follow the rules for well-formatted scala code. In the form it is formatted right now, the signature is misleading.

### PR DESCRIPTION
**Pull request by KacperFKorban**
fixes #13297

### CODE REVIEW

File: scaladoc/src/dotty/tools/scaladoc/tasty/SymOps.scala [hunk 1]
```diff
@@ -70,6 +70,7 @@ object SymOps:
         case (None, None, (false, true, true)) => Visibility.Protected(ThisScope)
         case (None, None, (false, true, false)) => Visibility.Protected(implicitScope(sym.owner))
         case (None, None, (false, false, false)) => Visibility.Unrestricted
+        case (None, None, (true, true, false)) => Visibility.Protected(ThisScope)
```
Comment (BarkingBad) [inline scaladoc/src/dotty/tools/scaladoc/tasty/SymOps.scala:73]: Maybe we should add a comment to this so people won't be confused

**Review by BarkingBad — APPROVED** [review]
