### PR TITLE
fix(#11202): special case type trees in syntax highlighting

### LINKED ISSUE #11202: Incorrect highlight for type constructor in REPL
## Compiler version

``` bash
scalac -version
Scala compiler version 3.0.0-M3 -- Copyright 2002-2020, LAMP/EPFL
```

## Minimized code

```Scala
type Id[A] = A
```

## Output

image

But, if I type:

```scala
type Id[A] 
```

it just works fine:

image

## Expectation

Correctly highlighted.

It may be related to #3814 #3987

### PR DESCRIPTION
**Pull request by ckipp01**
This fixes #11202 and ensures that when a LambdaTypeTree is encountered
we are only highlighting the actual type params.

### Before

Screenshot 2022-02-19 at 13 23 27

Screenshot 2022-02-19 at 13 24 42

### After

Screenshot 2022-02-19 at 13 23 52

Screenshot 2022-02-19 at 13 25 06

### CODE REVIEW

File: compiler/test/dotty/tools/dotc/printing/SyntaxHighlightingTests.scala [hunk 1]
```diff
@@ -23,7 +23,9 @@ class SyntaxHighlightingTests extends DottyTest {
 
     if (expected != highlighted) {
       // assertEquals produces weird expected/found message
-      fail(s"expected: $expected but was: $highlighted")
+      fail(s"""|
```
Comment (ckipp01) [inline compiler/test/dotty/tools/dotc/printing/SyntaxHighlightingTests.scala:26]: Not related to the actual changes, but this makes seeing the actual diff much easier when testing.

**Comment by ckipp01** [comment]
So after fixing the actual issue it was bugging me that `List[Int]` was all one color. For example:
Screenshot 2022-02-19 at 16 13 23

This become really evident after the first commit since in a type lambda it became really obvious since the first part didn't have the brackets highlight and the second part did.

This is also how Ammonite handles this (at least in Scala 2):

Screenshot 2022-02-19 at 16 15 30

So after the second commit now in an AppliedTypeTree only the actual tpt and the args are colored with the brackets remaining as no color.

Screenshot 2022-02-19 at 16 17 29

File: compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala [hunk 2]
```diff
@@ -111,6 +111,11 @@ object SyntaxHighlighting {
             // the braces
             case tree: LambdaTypeTree =>
               tree.tparams.foreach(tparam => highlightPosition(tparam.span, TypeColor))
+            // Also special case these to ensure that each type and arg is
+            // highlighted without the braces.
+            case tree: AppliedTypeTree =>
+              highlightPosition(tree.tpt.span, TypeColor)
+              tree.args.foreach(arg => highlightPosition(arg.span, TypeColor))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala:118]: Won't the call to `traverseChildren` below already take care of highlighting the args and tpt? I imagine this would also give better results with nested types e.g. so that `List[Foo[Int]]` wouldn't highlight any of the brackets. If this is what we want, perhaps we can just change the `case _: TypTree` to be `case _: TypeTree`.

Comment (ckipp01) [reply compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala]: Ahhhh true, good call. I made that change. It works even better. I did notice one small _regression_ in the case where you have an incomplete type like `F[_` where the `_` was colored before but now it isn't. However I think the current situation is still much better.

Comment (ckipp01) [reply compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala]: Screenshot 2022-02-19 at 19 29 08

Now it covers the deeper nested types.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala]: Can you add a test for the nested case?

Comment (ckipp01) [reply compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala]: Sure, done.

**Review by smarter — APPROVED** [review]
:sparkler:
