### PR TITLE
Flatten nested capture sets in retainedElementsRaw

### LINKED ISSUE #23570: Can't pass an explicit capture set to a capset parameter in eta expansion
## Compiler version

3.7.3

## Minimized example

```Scala
def f[C^](xs: List[() ->{C} Unit]): List[() ->{C} Unit] =
  xs.reverse

def test(io: Object^, async: Object^): Unit =
  val ok = f[{io}](Nil)  // ok
  val x = f[{io}]        // error
  val y = f[{io, async}] // error
```

## Output

-- Error: explicit-cs-arg.scala:6:10 -------------------------------------------
6 |  val x = f[{io}]        // error
  |          ^
  |          Illegal capture reference: scala.caps.CapSet^{io}
-- Error: explicit-cs-arg.scala:7:10 -------------------------------------------
7 |  val y = f[{io, async}] // error
  |          ^
  |          Illegal capture reference: scala.caps.CapSet^{io, async}
2 errors found

## Expectation

No errors

### PR DESCRIPTION
**Pull request by odersky**
Without the added clause, i23570 looks like this after typer:

```scala
[[syntax trees at end of                     typer]] // i23570.scala
package <empty> {
  final lazy module val i23570$package: i23570$package = new i23570$package()
  final module class i23570$package() extends Object() {
    this: i23570$package.type =>
    def f[C >: scala.caps.CapSet <: scala.caps.CapSet^{cap}](
      xs: List[(() -> Unit)^{C}]): List[(() -> Unit)^{C}] = xs.reverse
    def test(io: Object^{cap}, async: Object^{cap}): Unit =
      {
        val ok: List[() ->{scala.caps.CapSet^{io}} Unit] =
          f[_root_.scala.caps.CapSet^{io}](Nil)
        val x:
          List[() ->{scala.caps.CapSet^{io}} Unit] ->
            List[() ->{scala.caps.CapSet^{io}} Unit]
         = (xs: List[() ->{scala.caps.CapSet^{io}} Unit]) =>
          f[_root_.scala.caps.CapSet^{io}](xs)
        val y:
          List[() ->{scala.caps.CapSet^{io, async}} Unit] ->
            List[() ->{scala.caps.CapSet^{io, async}} Unit]
         = (xs: List[() ->{scala.caps.CapSet^{io, async}} Unit]) =>
          f[_root_.scala.caps.CapSet^{io, async}](xs)
        ()
      }
  }
}
```
Note the nested capture sets in the types of `x` and `y`.

Fixes #23570

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/CaptureOps.scala [hunk 1]
```diff
@@ -94,6 +94,8 @@ extension (tp: Type)
   def retainedElementsRaw(using Context): List[Type] = tp match
     case OrType(tp1, tp2) =>
       tp1.retainedElementsRaw ++ tp2.retainedElementsRaw
+    case AnnotatedType(tp1, ann) if tp1.derivesFrom(defn.Caps_CapSet) && ann.symbol.isRetains =>
```
Comment (noti0na1) [inline compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:97]: Do we need `isRetainsLike` here?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/cc/CaptureOps.scala:97]: Ni, I don't think a call-by-name set can end up here.

**Review by noti0na1 — APPROVED** [review]
LGTM

**Review by bracevac — APPROVED** [review]
