### PR TITLE
Fix overcompilation due to unstable context bound desugaring

### LINKED ISSUE #18080: Generated names of context bound parameters change on incremental compilation causing unnecessary invalidations
## Compiler version

3.3.0, also happens with 3.3.1-RC1

## Minimized code

Unfortunately I haven't been able to come up with a minimal reproduction. This happens in a large, private codebase, and my attempts to replicate the behavior have so far been unsuccessful.

For what it's worth, this is a simplified version of what the code looks like (note that this doesn't reproduce the issue):

```scala
object myObject {
  sealed trait Thing {
    def call(): Option[String]
  }
  case class Thing1(o: Option[String]) extends Thing {
    def call(): Option[String] = o.map(s => s"Thing1($s)")
  }

  case class MyType[A](a: A)

  object MyType {
    implicit def myTypeClass[A: MyTypeClass]: MyTypeClass[MyType[A]] = MyTypeClass.derived
  }
}
```

If I change the string in `Thing1.call` from `"Thing1($s)"` to `"Thing($s)"` (or anything else that doesn't change the signature of `Thing1.call`) then recompile, I see that the context bound on `MyType.myTypeClass` has been renamed, causing invalidation of anything that depends on `MyType`.

## Output

I've enabled debug output in sbt with the following settings:

```scala
ThisBuild / logLevel := Level.Debug
ThisBuild / incOptions ~= (_.withApiDebug(true).withRelationsDebug(true))
```

And I see a number of diffs to the API that look like this (shown as a git diff for syntax highlighting):

```diff
- [diff] implicit def myTypeClass[ A >: scala.this#Nothing <: scala.this#Any](implicit evidence$63: example.this#MyTypeClass[<A>]): example.this#MyTypeClass[example.myObject$.this#MyType[<A>]]
+ [diff] implicit def myTypeClass[ A >: scala.this#Nothing <: scala.this#Any](implicit evidence$81: example.this#MyTypeClass[<A>]): example.this#MyTypeClass[example.myObject$.this#MyType[<A>]]
```

Note that the only thing changed is the name of the `MyTypeClass` parameter, from `evidence$63` to `evidence$81`.

## Expectation

Context bound parameter names shouldn't change, or at least they shouldn't cause API invalidation.

### PR DESCRIPTION
**Pull request by smarter**
Context bounds are desugared into term parameters `evidence$N` and before this
commit, the `N` was chosen to be unique in the current compilation unit. This
isn't great because it means that adding a new definition with a context bound
in the middle of a file would change the desugaring of subsequent definitions
in the same file.

Even worse, when using incremental compilation we could end up with the same
context bound desugared with a different value of `N` on different compilation
runs because the order in which a compilation unit is traversed during Typer is
not fixed but depends on the how the units that are jointly compiled depend on
each other (as demonstrated by the `stable-ctx-bounds` test). This issue
affects all fresh names generated during Typer, but it is especially
problematic for context bounds because they're part of the API and renaming
a method parameter forces the recompilation of all files calling that method.

To fix this, we now only require context bounds parameters to have unique names
among all the parameters of the method. This matches how we already desugar
`def foo(using A, B)` into `def foo(using x$1: A, x$2: B)` regardless of the
context.

Note that fresh names used in other situations are still problematic for
deterministic compilation. Most of the time they're not part of the API checked
by Zinc, but they can still lead to overcompilation if they appear in an
`inline def` since the entire body of the `inline def` constitutes its API. In
the future, we should follow Scala 2's lead and only require names to be fresh
at the method level: https://github.com/scala/scala/pull/6300 (The Scala 2
logic is slightly more complex to handle macros, but I don't think that applies
to Scala 3 macros), see #7661.

Fixes #18080.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1735,7 +1735,7 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
           val cases1 = tree.cases.mapconserve {
             case cdef @ CaseDef(pat @ Typed(Ident(nme.WILDCARD), _), _, _) =>
               // case _ : T  -->  case evidence$n : T
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1737]:
```suggestion
              // case _ : T  -->  case _$n : T
```

File: sbt-test/source-dependencies/stable-ctx-bounds/test [hunk 2]
```diff
@@ -0,0 +1,9 @@
+> compile
```
Comment (bishabosha) [inline sbt-test/source-dependencies/stable-ctx-bounds/test:1]: may be worth noting here the predicted order of typer visiting definitions in run 1 vs run 2, to illustrate how before the change it actually had unstable names between runs.

**Review by bishabosha — APPROVED** [review]

**Comment by mkurz** [comment]
This change is causing compatibilities when running a Play project with Scala 3.3.1 with Play artifacts build with Scala 3.3.2:
- https://github.com/playframework/playframework/issues/12418

@smarter Can you take a look?
