### PR TITLE
Use stringOf from REPL to avoid trimming

### LINKED ISSUE #11558: Scala 3 REPL regression compared to Scala 2: echoed strings are trimmed when they shouldn't, loosing e.g. newline-characters
## Compiler version

3.0.0-RC2-bin-20210227-07d9dd2-NIGHTLY

## Minimized code
The Scala 3 REPL trim all string values before echoing, which means that leading whitespace newline is lost and multi-line strings will get first line miss-aligned etc.
```Scala
scala> case class Box(x: String) { override def toString = s"\n$x" }                                                           
// defined case class Box
```

## Output

```scala
scala> Box("new line is lost")
val res0: Box = new line is lost

scala> Box("1 2 3\n1 2 3\n1 2 3")
val res1: Box = 1 2 3
1 2 3
1 2 3
```

## Expectation
```scala
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 11.0.10).
Type in expressions for evaluation. Or try :help.

scala> case class Box(x: String) { override def toString = s"\n$x" }
class Box

scala> Box("new line is NOT lost")
val res0: Box =

new line is NOT lost

scala> Box("1 2 3\n1 2 3\n1 2 3")
val res1: Box =

1 2 3
1 2 3
1 2 3

```

### PR DESCRIPTION
**Pull request by som-snytt**
ScalaRunTime.replStringOf adds extra newlines. Try not to
trim more than was added.

New API will not include the newlines.

Fixes #11558

### CODE REVIEW

**Comment by som-snytt** [comment]
With scala 2 published locally
```
Starting scala3 REPL...
scala> 42
val res0: Int = 42

scala> "hi there"
val res1: String = "hi there"

scala> case class Box(x: Any) { override def toString = s"\n$x\n" }
// defined case class Box

scala> Box("xxx")
val res2: Box = Box("xxx")

scala> Box("xxx").toString
val res3: String = """
xxx
"""

scala> Box(Array(1,2,3))
val res4: Box = Box(Array(1, 2, 3))

scala> case class Box(x: Any, y: Int) { override def toString = s"\n$x\n" }
// defined case class Box

scala> Box(Array(1,2,3), 42)
val res5: Box = Box(x = Array(1, 2, 3), y = 42)

scala>  
```

**Comment by som-snytt** [comment]
Regressed
```
scala> Option.empty
val res1: Option[Nothing] = None()

scala> enum E { case X } ; E.X
// defined class E
val res2: E = X()
```

File: compiler/src/dotty/tools/repl/Rendering.scala [hunk 1]
```diff
@@ -55,11 +55,29 @@ private[repl] class Rendering(parentClassLoader: Option[ClassLoader] = None) {
...
+          case _: NoSuchMethodException =>
+            val meth = scalaRuntime.getMethod("replStringOf", classOf[Object], classOf[Int])
+
+            (value: Object) => {
+              val res = meth.invoke(null, value, Integer.valueOf(MaxStringElements)).asInstanceOf[String]
+              val len = res.length()
+              if len == 0 || res.charAt(len-1) != '\n' then
+                res
+              else if len == 1 || res.charAt(0) != '\n' then
+                res.substring(0, len-1)
```
Comment (bjornregnell) [inline compiler/src/dotty/tools/repl/Rendering.scala:76]: This code seems yo assume that there always is a newline at the end of res? Why not check explicitly if also the last character is a newline to be cut, without just assuming that its there (to be more robust and not living on assumptions...)? Or am I missing something?

**Review by bjornregnell — COMMENTED** [review]
I just made the comment below; I hope I'm not completely off, so take it for what it is (a question from an person who does not know the underlying code base...)

File: compiler/src/dotty/tools/repl/Rendering.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: L73 checks last, L75 checks first char. I'll look again when awake.

Comment (bjornregnell) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: Yes, my bad. I was not going through all the cases in my head, so it seems to work.

Comment (bjornregnell) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: So the logic is:
`if` non-zero *or* no trailing \n `then` leave it as is
`else if` only one char *or* no leading \n `then` cut last (because we now know that there is a trailing \n)
`else` cut both first and last (because we now know that there must be both leading and trailing \n)

Comment (bjornregnell) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: Somehow I think this is easier to grok: (but maybe it's just me)
```scala
def trimNewlinesAtStartOrEnd(res: String) =
  val len = res.length
  if len == 0 || res == "\n" then ""
  else
    val from  = if res.charAt(0) == '\n' then 1 else 0
    val until = if res.charAt(len - 1) == '\n' then len - 1 else len
    res.substring(from, until)  
``` 
Take whatever version you like best :)
Simpler to just take the special cases first IMHO.
I just had to test it :)
```
scala> trimNewlinesAtStartOrEnd("")
val res0: String = ""

scala> trimNewlinesAtStartOrEnd("\n")                                                                                     
val res1: String = ""

scala> trimNewlinesAtStartOrEnd("\n\n")                                                                               
val res2: String = ""

scala> trimNewlinesAtStartOrEnd("\nhello\n")                                                                                   
val res3: String = hello

scala> trimNewlinesAtStartOrEnd("\n\n\n")                                                                                   
val res4: String = "
"
```

Comment (bjornregnell) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: BTW: Where do these surrounding newlines come from and why do they need to be trimmed away?

Comment (som-snytt) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: It appends always for Scala 2 REPL; other question is why doesn't Scala 3 use `stringOf`. I suppose it prepends on multiline so the lines are all left-adjusted.

My time box expired on this tweak, so I didn't add a special test; the repl tests break easily. I agree those lines tax the short-term memory of the reviewer; if the Scala 2 PR is merged, they will be unused code.

Comment (som-snytt) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: BTW `stringOf` is the original method name, not an internal helper; `replStringOf` was split out a decade ago out of fastidiousness. So my better option here was just to use `stringOf` directly. I'll take a few minutes to try that out, after I knock off of my day job.

Comment (bjornregnell) [reply compiler/src/dotty/tools/repl/Rendering.scala:76]: Ok thanks for info. LGTM.

**Review by bjornregnell — APPROVED** [review]
LGTM.

**Review by bjornregnell — APPROVED** [review]

**Comment by som-snytt** [comment]
I'll push a commit that uses `stringOf` and avoids the dread if-else.

Without the final null check in `replStringOf`
```
scala>     val tpolecat = new Object {
     |       override def toString(): String = null
     |     }
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at dotty.tools.repl.Rendering.truncate(Rendering.scala:97)
        at dotty.tools.repl.Rendering.replStringOf(Rendering.scala:106)
```

**Comment by bjornregnell** [comment]
Using `stringOf` instead seems good to me (although I do not have insight into REPL-historic complaints @tpolecat . But I *am* very glad to have learnt the new English word `fastidious`, thanks @som-snytt. That word turns out to have really many different translations to Swedish, but no single Swedish word as a direct translation - I'm not sure if it is a bug or a feature that Swedish seems less of an ambiguous language here... I choose `choosy` rather than `faddish` as a translation after traversing all synonyms until truncate at some arbitrary max size. :smiling_face_with_three_hearts: )

**Review by bjornregnell — APPROVED** [review]

**Comment by som-snytt** [comment]
My favorite Swedish action movie is "The Fastidious and the Furious."

**Review by anatoliykmetyuk — APPROVED** [review]
