### PR TITLE
Fix #8313: special case typeparamCorrespondsToField

### LINKED ISSUE #8313: Recursive match type fails to type check
## minimized code

```Scala
scala> type I[A <: Tuple] <: Tuple = A match {
     |   case Unit => Unit
     |   case hd *: tl => hd *: I[tl]
     | }

scala> (1, 2): I[(Int, Int)]
val res4: (Int, Int) = (1,2)

scala> type DU[A <: Tuple] <: Tuple = A match {
     |   case Unit => Unit
     |   case Unit *: tl => DU[tl]
     |   case hd *: tl => hd *: DU[tl]
     | }

scala> (1, 2): DU[(Int, Int)]
1 |(1, 2): DU[(Int, Int)]
  |^^^^^^
  |Found:    (Int, Int)
  |Required: DU[(Int, Int)]
```

## expectation

`DU[(Int, Int)]` should expand to `(Int, Int)` but doesn't. Only difference between `DU` and `I` (which works), is the `Unit *: tl` case.

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
Special case `typeparamCorrespondsToField` to `scala.*:`. Since `*:` is artificially added to tuples, we also need to special case that logic to conclude that `*:[A, _]` and `*:[B, _]` are disjoint when knowing that `A` and `B` are disjoint.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -2193,13 +2193,15 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
   /** Returns last check's debug mode, if explicitly enabled. */
   def lastTrace(): String = ""
 
+  /** Does `tycon` has a field with type `tparam`? Special cased for `scala.*:`
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: has -> have
