### PR TITLE
Fix #7425: Handle nullary/parameterless conflicts in infoMeet

### LINKED ISSUE #7425: Intersection of nullary and nilary crashes compiler
```scala
scala> class C { def f: Int = 0 }
// defined class C

scala> class D { def f(): Int = 0 }
// defined class D

scala> def foo(x: C & D) = x.f
assertion failure for (C & D)(x) <:< ?{ f: ? }, frozen = false
Exception in thread "main" java.lang.AssertionError: assertion failed: Int & (): Int / TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),module scala),class Int) & MethodType(List(), List(), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),module scala),class Int))
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
	at dotty.tools.dotc.core.Types$AndType$.apply(Types.scala:2777)
	at dotty.tools.dotc.core.TypeComparer.andType$$anonfun$1(TypeComparer.scala:1924)
	at dotty.tools.dotc.core.TypeComparer.liftIfHK(TypeComparer.scala:1963)
	at dotty.tools.dotc.core.TypeComparer.andTypeGen(TypeComparer.scala:1901)
	at dotty.tools.dotc.core.TypeComparer.andType(TypeComparer.scala:1924)
	at dotty.tools.dotc.core.TypeComparer.glb(TypeComparer.scala:1723)
	at dotty.tools.dotc.core.Types$Type.$amp(Types.scala:950)
	at dotty.tools.dotc.core.Denotations$.infoMeet(Denotations.scala:656)
	at dotty.tools.dotc.core.Denotations$Denotation.mergeSingleDenot$1(Denotations.scala:481)
	at dotty.tools.dotc.core.Denotations$Denotation.mergeDenot$1(Denotations.scala:401)
	at dotty.tools.dotc.core.Denotations$Denotation.$amp(Denotations.scala:504)
```

### PR DESCRIPTION
**Pull request by odersky**
We did handle ():T & (=> T), but not (=> T) & ():T.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Denotations.scala [hunk 1]
```diff
@@ -653,15 +653,18 @@ object Denotations {
       case ExprType(rtp1) =>
         tp2 match {
           case ExprType(rtp2) => ExprType(rtp1 & rtp2)
-          case _ => rtp1 & tp2
+          case _ => infoMeet(rtp1, tp2, sym1, sym2, safeIntersection)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Denotations.scala]: Can this ever actually succeed ? I assume `tp2` is always go to be a method type or a poly type so we'll end up with a mergeConflict. If so we might as well directly return with a mergeConflict here:
```suggestion
          case _ => mergeConflict(sym1, sym2, tp1, tp2)
```
```

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Denotations.scala]: Ah, I guess this would actually suceed if we're merging a `val` and a nilary `def`, nevermind then.
