### PR TITLE
Fix reflect.LambdaType type test

### LINKED ISSUE #16961: `Quotes#PolyType` type-tests as `Quotes#TypeLambda`
## Compiler version

3.3.1-RC1-bin-20230216-2507577-NIGHTLY

## Minimized example

```Scala
import scala.quoted.*

inline def test = ${ testImpl }

def testImpl(using Quotes) =
  import quotes.reflect.*

  PolyType(List("arg"))(_ => List(TypeBounds.empty), _ => TypeRepr.of[Any]) match
    case _: TypeLambda => println("is a TypeLambda")
    case _ => println("is not a TypeLambda")

  '{ () }
```

## Output

When expanding, the macro prints `is a TypeLambda`

## Expectation

The documentation shows the type hierarchy:
```
             +
             +- LambdaType -+- MethodOrPoly -+- MethodType
             |              |                +- PolyType
             |              +- TypeLambda
             +
``` 
Based on this, I would expect the output to be `is not a TypeLambda`. Of course, it could be that the run time type of what `PolyType` generates is a subtype of both `PolyType` and `TypeLambda`, but given the documentation I find this behavior at least unexpected. I suppose that the type test and the documentation should be aligned.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #16961

### CODE REVIEW

File: scaladoc/src/dotty/tools/scaladoc/tasty/TypesSupport.scala [hunk 1]
```diff
@@ -290,10 +290,10 @@ trait TypesSupport:
         }
         inner(sc) ++ keyword(" match ").l ++ plain("{\n").l ++ casesTexts ++ plain(spaces + "}").l
 
-      case ParamRef(TypeLambda(names, _, _), i) => tpe(names.apply(i)).l
-
       case ParamRef(m: MethodType, i) => tpe(m.paramNames(i)).l ++ plain(".type").l
 
+      case ParamRef(binder: LambdaType, i) => tpe(binder.paramNames(i)).l
```
Comment (nicolasstucki) [inline scaladoc/src/dotty/tools/scaladoc/tasty/TypesSupport.scala:295]: `case ParamRef(TypeLambda(names, _, _), i)` was accidentally matching `TypeLambda` and `PolyType` here. Replaced with `LambdaType` that matches `TypeLambda`, `PolyType`, and `MethodType`.

**Review by smarter — APPROVED** [review]
