### PR TITLE
Do not compute `protoFormal` if `param.tpt` is empty

### LINKED ISSUE #18276: Regression in inkytonik/kiama
Based on Open CB failure, build logs: https://github.com/VirtusLab/community-build3/actions/runs/5626149769/job/15248249692 

## Compiler version
Fails in 3.3.2-RC1-bin-20230720-98b452d-NIGHTLY 
Works with: 3.3.1-RC4
Bisect points to: 0f7c3abc3706b2054c48f3b16991741edb3a4610

## Minimized code

```Scala
import scala.language.implicitConversions

case class Assign(left: String, right: String)
class SyntaxAnalyser extends ParsersBase {
  val x: Parser[String ~ String] = ???
  val y: Parser[Assign] = x.map(Assign.apply)
}

class ParsersBase {
  trait ~[+T, +U]
  abstract class Parser[+T]:
    def map[U](f: T => U): Parser[U] = ???

  given [A, B, X]: Conversion[(A, B) => X, (A ~ B) => X] = ???
}
```

## Output

```scala
-- [E086] Syntax Error: /Users/wmazur/projects/sandbox/main.scala:6:32 ---------
6 |  val y: Parser[Assign] = x.map(Assign.apply(_,_))
  |                                ^^^^^^^^^^^^^^^^^
  |                                Wrong number of parameters, expected: 1
1 error found
```

## Expectation
Should be able to compile code, by applying the implicit conversion

### PR DESCRIPTION
**Pull request by nicolasstucki**
This was accidentally moved before of the `if (!param.tpt.isEmpty)` guard in https://github.com/lampepfl/dotty/commit/0f7c3abc3706b2054c48f3b16991741edb3a4610#diff-8c9ece1772bd78160fc1c31e988664586c9df566a1d22ff99ef99dd6d5627a90R1534. `protoFormal` has a side effect (error reporting) that caused this issue.

Fixes #18276

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1606,32 +1606,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
     if desugared.isEmpty then
       val inferredParams: List[untpd.ValDef] =
         for ((param, i) <- params.zipWithIndex) yield
-          val (formalBounds, isErased) = protoFormal(i)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1609]: This line moved into the else branch. The rest should not have changed.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -1606,32 +1606,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
                 )
-              cpy.ValDef(param)(tpt = paramTpt)
-          if isErased then param0.withAddedFlags(Flags.Erased) else param0
+            val paramTpt = untpd.TypedSplice(
+                (if knownFormal then InferredTypeTree() else untpd.TypeTree())
+                  .withType(paramType.translateFromRepeated(toArray = false))
+                  .withSpan(param.span.endPos)
+              )
+            val param0 = cpy.ValDef(param)(tpt = paramTpt)
+            if isErased then param0.withAddedFlags(Flags.Erased) else param0
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1633]: An this was moved into the else branch asl well

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -1606,32 +1606,31 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+              val formal0 = if !isErased then formal.stripAnnots(_.symbol != defn.ErasedParamAnnot) else formal
+              if knownFormal && !isBottomFromWildcard then
+                formal0
+              else
+                inferredFromTarget(param, formal, calleeType, isErased, paramIndex).orElse(
+                  if knownFormal then formal0
+                  else errorType(AnonymousFunctionMissingParamType(param, tree, inferredType = formal, expectedType = pt), param.srcPos)
                 )
-              cpy.ValDef(param)(tpt = paramTpt)
-          if isErased then param0.withAddedFlags(Flags.Erased) else param0
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1634]: And this was moved into the `else` branch asl well.

**Review by jchyb — APPROVED** [review]
