### PR TITLE
Compile quote patterns directly into QuotePattern AST

### LINKED ISSUE #14708: assertion failed: unresolved symbols while pickling quote with type bounds
## Compiler version

- 3.1.2-RC2
- 3.1.1
- 3.1.3-RC1-bin-20220317-17e46ad-NIGHTLY

## Minimized code

```Scala
import scala.quoted.*

object Main {
  def foo(a: Expr[Any])(using Quotes) = {
    a match {
      case '{ ($x: Set[t]).toSet } =>
      case _ =>
    }
  }
}
```

### workaround(?)

```scala
import scala.quoted.*

object Main {
  def foo(a: Expr[Any])(using Quotes) = {
    a match {
      case '{
              type t1
              type t2 >: `t1`
              ($x: Set[`t1`]).toSet[`t2`]
            } =>
      case _ =>
    }
  }
}
```

## Output (click arrow to expand)
<details>

```
[error] java.lang.AssertionError: assertion failed: unresolved symbols: value t$given1 (line 5) #14166 when pickling /Users/kenji/set-expr-match/Main.scala
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:777)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$1$$anonfun$1(Pickler.scala:69)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:106)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.Pickler.run(Pickler.scala:106)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
[error] dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:111)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:261)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:272)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:289)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:222)
[error] dotty.tools.dotc.Run.compile(Run.scala:206)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:750)

```
</details>

### LINKED ISSUE #16522: Quoted patterns regression: match with Underlying type fails
## Compiler version

Compiler version 3.2.1

## Minimized code

This is the code  that worked when discussed in issue https://github.com/lampepfl/dotty/issues/10358. I am reporting it here so that it does not slip through the cracks (discussed in November 2020):

```Scala
  import scala.quoted.*

  sealed trait HList
  case class HCons[+HD, TL <: HList](hd: HD, tl: TL) extends HList
  case object HNil extends HList

  def showFirstTwoImpl(e: Expr[HList])(using Quotes): Expr[String] = {
    e match {
      // Ok. No match 
      case '{HCons($h1, HCons($h2, $_))} => '{$h1.toString ++ $h2.toString}
      // Fails. Does not compile 
      case '{HCons($h1: hd1, HCons($h2: hd2, $_ : tl))} => '{$h1.toString ++ $h2.toString}
      // Ok
      case '{HCons[hd, HCons[sd, tl]]($h1, HCons($h2, $_))} => '{$h1.toString ++ $h2.toString}
      case _ => '{""}
    }
  }

  transparent inline def showFirstTwo(inline xs: HList) = ${ showFirstTwoImpl('xs) }  

```

## Output

```scala
error] -- [E007] Type Mismatch Error: /home/hmf/VSCodeProjects/sploty/meta/src/data/Macros3.scala:1184:45 
[error] 1184 |      case '{HCons($h1: hd1, HCons($h2: hd2, $_ : tl))} => '{$h1.toString ++ $h2.toString}
[error]      |                                             ^^^^^^^
[error]      |                                      Found:    tl$given2.Underlying
[error]      |                                      Required: data.Macros3.HList
[error]      |--------------------------------------------------------------------------
[error]      | Explanation (enabled by `-explain`)
```

<details close>
<summary>Compiler explanation:</summary>
<br>

```
error]      |
[error]      | Tree: ${_}:(tl$given2 @ _).Underlying
[error]      | I tried to show that
[error]      |   tl$given2.Underlying
[error]      | conforms to
[error]      |   TL
[error]      | but the comparison trace ended with `false`:
[error]      |
[error]      |   ==> tl$given2.Underlying  <:  TL
[error]      |     ==> tl$given2.Underlying  <:  TL
[error]      |       ==> tl  <:  TL
[error]      |         ==> tl  <:  TL in frozen constraint
[error]      |           ==> tl  <:  Nothing in frozen constraint
[error]      |             ==> Any  <:  Nothing (left is approximated) in frozen constraint
[error]      |             <== Any  <:  Nothing (left is approximated) in frozen constraint = false
[error]      |           <== tl  <:  Nothing in frozen constraint = false
[error]      |           ==> Any  <:  TL (left is approximated) in frozen constraint
[error]      |             ==> Any  <:  Nothing (left is approximated) in frozen constraint
[error]      |             <== Any  <:  Nothing (left is approximated) in frozen constraint = false
[error]      |           <== Any  <:  TL (left is approximated) in frozen constraint = false
[error]      |         <== tl  <:  TL in frozen constraint = false
[error]      |         ==> add constraint TL >: tl , constraint =  uninstantiated variables: TL, HD, TL, HD, TL, HD, TL, HD, TL  constrained types:    [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL] , [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL],    [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL] , [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL],    [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL]  bounds:       HD := Any      TL >: data.Macros3.HCons[Any, data.Macros3.HList] <: data.Macros3.HList      HD      TL <: data.Macros3.HList      HD >: hd1      TL >: data.Macros3.HCons[HD, TL] <: data.Macros3.HList      HD      TL <: data.Macros3.HList      HD >: hd2      TL <: data.Macros3.HList  ordering: 
[error]      |           ==> lub(Nothing, tl, canConstrain=false, isSoft=true)
[error]      |           <== lub(Nothing, tl, canConstrain=false, isSoft=true) = tl
[error]      |           ==> tl  <:  data.Macros3.HList
[error]      |             ==> Any  <:  data.Macros3.HList (left is approximated)
[error]      |             <== Any  <:  data.Macros3.HList (left is approximated) = false
[error]      |           <== tl  <:  data.Macros3.HList = false
[error]      |         <== add constraint TL >: tl , constraint =  uninstantiated variables: TL, HD, TL, HD, TL, HD, TL, HD, TL  constrained types:    [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL] , [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL],    [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL] , [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL],    [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL]  bounds:       HD := Any      TL >: data.Macros3.HCons[Any, data.Macros3.HList] <: data.Macros3.HList      HD      TL <: data.Macros3.HList      HD >: hd1      TL >: data.Macros3.HCons[HD, TL] <: data.Macros3.HList      HD      TL <: data.Macros3.HList      HD >: hd2      TL <: data.Macros3.HList  ordering:  = false
[error]      |       <== tl  <:  TL = false
[error]      |     <== tl$given2.Underlying  <:  TL = false
[error]      |   <== tl$given2.Underlying  <:  TL = false
[error]      |
[error]      | The tests were made under a constraint with:
[error]      |  uninstantiated variables: TL, HD, TL, HD, TL, HD, TL, HD, TL
[error]      |  constrained types: 
[error]      |   [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL]
[error]      | , [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL], 
[error]      |   [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL]
[error]      | , [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL], 
[error]      |   [HD, TL <: data.Macros3.HList](hd: HD, tl: TL): data.Macros3.HCons[HD, TL]
[error]      |  bounds: 
[error]      |      HD := Any
[error]      |      TL >: data.Macros3.HCons[Any, data.Macros3.HList] <: data.Macros3.HList
[error]      |      HD
[error]      |      TL <: data.Macros3.HList
[error]      |      HD >: hd1
[error]      |      TL >: data.Macros3.HCons[HD, TL] <: data.Macros3.HList
[error]      |      HD
[error]      |      TL <: data.Macros3.HList
[error]      |      HD >: hd2
[error]      |      TL <: data.Macros3.HList
[error]      |  ordering: 
[error]       --------------------------------------------------------------------------
```

</details>

## Expectation

Expect the code in https://github.com/lampepfl/dotty/issues/10358 to keep working on the latest compiler.

### LINKED ISSUE #18125: Compiler crash when referencing type in quotes
## Compiler version

Regression found in the Open Community Build in: 
- tinkoff/phobos - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/5426571795/jobs/9871076343) - reproduction below

## Compiler version
3.3.2-RC1-bin-20230629-90c59bd-NIGHTLY
Bisect points to b7b13e5c8ffa110ea3fbc5667b636e7132850fdf

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
//> using scala 3.nightly

package oolong.phobos

import scala.quoted.*
import scala.compiletime.*
import scala.annotation.StaticAnnotation

final class xmlns[T](ns: T) extends StaticAnnotation
trait Namespace[T]{
    val getNamespace: String
}

object common{
  private def extractFeildNamespace(using Quotes)(
      fieldAnnotations: List[Expr[Any]],
  ): Expr[Option[String]] = {
    import quotes.reflect.*

    fieldAnnotations.collect { case '{ xmlns($namespace: b) } =>
      '{ Some(summonInline[Namespace[b]].getNamespace) }
    }
    ???
  }
}
```

## Output (click arrow to expand)
<details>

```scala
//> using scala 3.nightly

package oolong.phobos

import scala.quoted.*
import scala.compiletime.*
import scala.annotation.StaticAnnotation

final class xmlns[T](ns: T) extends StaticAnnotation
trait Namespace[T]{
    val getNamespace: String
}

object common{
  private def extractFeildNamespace(using Quotes)(
      fieldAnnotations: List[Expr[Any]],
  ): Expr[Option[String]] = {
    import quotes.reflect.*

    fieldAnnotations.collect { case '{ xmlns($namespace: b) } =>
      '{ Some(summonInline[Namespace[b]].getNamespace) }
    }
    ???
  }
}
```
</details>

### LINKED ISSUE #18250: Duplicate quote pattern variable when referred in bounds
## Compiler version

3.3.2-RC1

## Minimized code

```Scala
import scala.quoted.*

def test(x: Expr[Any])(using Quotes): Unit =
  x match
    case '{ type t; type u <: t; () } =>
    case '{ type t <: Comparable[t]; () } =>
```

## Output

```scala
-- [E005] Naming Error: t/Test.scala:5:12 --------------------------------------
5 |    case '{ type t; type u <: t; () } =>
  |            ^^^^^^^^^^^^^^^^^^^^^^^
  |            duplicate pattern variable: t
  |
  | longer explanation available when compiling with `-explain`
-- [E005] Naming Error: t/Test.scala:6:12 --------------------------------------
6 |    case '{ type t <: Comparable[t]; () } =>
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |            duplicate pattern variable: t
  |
  | longer explanation available when compiling with `-explain`
```

## Expectation

This is an issue in the implementation of [SIP-53 - Support for multiple references to the same type in quoted type patterns](https://docs.scala-lang.org/sips/quote-pattern-type-variable-syntax.html#support-multiple-references-to-the-same-type-in-quoted-type-patterns).

It should be equivalent to 
```scala
import scala.quoted.*

def test(x: Expr[Any])(using Quotes): Unit =
  x match
    case '{ type t; type u <: `t`; () } =>
    case '{ type t <: Comparable[`t`]; () } =>

```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #14708
Fixes #16522
Fixes #18125
Fixes #18250

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala [hunk 1]
```diff
@@ -453,83 +229,56 @@ trait QuotesAndSplices {
...
       val quoteCtx = quotePatternContext(quoted.isType)
       if untpdTypeVariables.isEmpty then (Nil, quoteCtx)
       else typedBlockStats(untpdTypeVariables)(using quoteCtx)
+    val patternCtx = patternBlockCtx.addMode(if quoted.isType then Mode.QuotedTypePattern else Mode.QuotedExprPattern)
 
-    val quoted1 = inContext(patternCtx) {
+    val allTypeBindings = List.newBuilder[Bind]
+    for tpVar <- typeTypeVariables do
+      val sym = tpVar.symbol
+      sym.setFlag(Case)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala:245]: Could this flag be set when creating the symbol?

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala [hunk 2]
```diff
@@ -550,19 +299,43 @@ object QuotesAndSplices {
...
+      inline private def atVariance[T](v: Int)(op: => T): T = {
+        val saved = variance
+        variance = v
+        val res = op
+        variance = saved
+        res
+      }
+
+      override def transform(tree: Tree)(using Context) = tree match
+        case tree @ AppliedTypeTree(tpt, args) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala:330]: Maybe that doesn't matter for the transform you're doing, but this isn't complete, it's at least missing TypeBoundsTree, LambdaTypeTree as well as method parameters in DefTrees.

**Review by smarter — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala:330]: It might be a problem, but we must change this behavior in a minor release. This will not affect soundness of the pattern match, but it will change the behavior of existing programs. This is only used to decide which bound of the type we should return. 

This is related to the type inference of type variable bounds and shares some of the same problems and limitations. At some point, we will need a way to allow users to state explicitly if they want to solve for a lower or upper bound. This inference would become redundant or a warning like the one we have for the type bounds.

**Review by smarter — APPROVED** [review]
