### PR TITLE
Preserve tvar bounds that represent kinds

### LINKED ISSUE #6014: Inline match/match type bound HK type variables are miskinded on the RHS
Compiling the following,
```scala
import scala.compiletime._

object Test1 {
  type Foo[F[_]]
  type Bar[T] = T match {
    case Foo[f] => f[Int]
  }
}

object Test2 {
  inline def summon[T] = implicit match {
    case t: T => t
  }

  class Foo[F[_]]

  inline def bar[T] = inline erasedValue[T] match {
    case _: Foo[f] => summon[f[Int]]
  }
}
```
Fails similarly in both cases with the occurrences of `f` on the RHS of the case being reported as not taking type parameters,
```
-- [E053] Reference Error: tests/pos/match-bugs.scala:6:19 ---------------------
6 |    case Foo[f] => f[Int]
  |                   ^^^^^^
  |                   f does not take type parameters

longer explanation available when compiling with `-explain`
-- [E053] Reference Error: tests/pos/match-bugs.scala:18:29 --------------------
18 |    case _: Foo[f] => summon[f[Int]]
   |                             ^^^^^^
   |                             f does not take type parameters
```

### PR DESCRIPTION
**Pull request by milessabin**
The kinds of type variables being solved are represented by their upper bounds. If we lose track of these then kinds will be incorrect on the RHS of inline matches and match types.

Without the additional change in `TypeComparer` this breaks `tests/pos/i5574.scala`. The added fallback to `fourthTry` brings the higher kinded case into line with the path that's followed in the simply kinded
case and restores the correct behaviour. Unfortunately I'm not able to justify it other than that it emerged from extensive trial and error and comparison with the simply kinded case.

I'd also love to understand the use of `return` in `TypeComparer`. Is it an optimization or does it have some semantic significance?

Fixes #6014.

### CODE REVIEW

**Comment by smarter** [comment]
> I'd also love to understand the use return in TypeComparer. Is it an optimization or does it have some semantic significance?

Just an optimization (which might not actually be an optimization in practice if we're not careful and end up with non-local returns).

File: compiler/src/dotty/tools/dotc/core/Contexts.scala [hunk 1]
```diff
@@ -929,7 +929,10 @@ object Contexts {
             // - we don't want TyperState instantiating these TypeVars
             // - we don't want TypeComparer constraining these TypeVars
             val poly = PolyType(DepParamName.fresh(sym.name.toTypeName) :: Nil)(
-              pt => TypeBounds.empty :: Nil,
+              pt => (sym.info match {
+                case tb @ TypeBounds(lo, hi) if (lo eq defn.NothingType) && hi.isLambdaSub => tb
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Contexts.scala]: The lower bound being Nothing or not shouldn't change anything here.

Comment (milessabin) [reply compiler/src/dotty/tools/dotc/core/Contexts.scala]: My rationale was to restrict the change to just those bounds which only convey kind information. Happy to loosen that restriction if you think it's the right thing to do.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Contexts.scala]: If you don't want to loose the kind information when the lower bound is Nothing, then I don't think you want to loose it just because someone put a more precise lower bound. Try adding some extra testcases to clarify this.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/Contexts.scala]: I agree that it should not matter whether lower bound is `Nothing`. Btw, to test for nothingness, use `lo.isRef(NothingClass)`. `eq` on types is unpredictable, since types might be re-generated in interactive scenarios between runs. 

I am also mystified by the treatment of the upper bound. As things stand, we make the upper bound `Any` for all first kinded types (including ones with a bound), but we copy the upper bound from `sym` if it is higher-kinded. That looks unsystematic to me. Does the precise bound matter at all? This is a question for @AleksanderBG .

**Comment by odersky** [comment]
@AleksanderBG should also review this. Also, I noted that GADTMaps now constitute a large chunk of code in an already large file `Contexts.scala`. I believe it's time to move them to their separate source file.

File: compiler/src/dotty/tools/dotc/core/Contexts.scala (hunk 1 above)
Comment (milessabin) [reply compiler/src/dotty/tools/dotc/core/Contexts.scala]: I've removed the restriction on the lower bound and added a couple more tests as suggested by @smarter. The last of these (with `List` as a lower bound) failed with the restriction in place.

File: compiler/src/dotty/tools/dotc/core/Contexts.scala [hunk 2]
```diff
@@ -929,7 +929,10 @@ object Contexts {
             // - we don't want TyperState instantiating these TypeVars
             // - we don't want TypeComparer constraining these TypeVars
             val poly = PolyType(DepParamName.fresh(sym.name.toTypeName) :: Nil)(
-              pt => TypeBounds.empty :: Nil,
+              pt => (sym.info match {
+                case tb @ TypeBounds(_, hi) if hi.isLambdaSub => tb
+                case _ => TypeBounds.empty
+              }) :: Nil,
```
[the remark this answers is not in the document]
Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Contexts.scala]: OK, then can you open an issue and add a TODO in the code that points to the issue so we can keep track of this ?

**Comment by milessabin** [comment]
Test renamed as requested.

**Comment by milessabin** [comment]
Also need to rename in the blacklist ...

**Comment by milessabin** [comment]
> This'll do for now

@AleksanderBG happy for this to be merged?

**Comment by AleksanderBG** [comment]
@milessabin There were some post-#6165 conflicts, I'll merge once the tests pass (or you can do that if you notice it first :smile:).

Note to self: remember that on Github, "resolve conflicts" apparently means "merge master into the branch, unnecessarily convoluting history". Best not to touch that thing in the future.
