### PR TITLE
Fix #10787: List failed projects at community build test completion

### LINKED ISSUE #10787: Community Build test should say which tests failed
The community build test runs a long time with a huge log, only to say at the end that it failed in a single line.

It should state instead which community project(s) failed.

### PR DESCRIPTION
**Pull request by griggt**
Examples of this in action (near the bottom of each log):

 * https://github.com/lampepfl/dotty/runs/1554027835?check_suite_focus=true
 * https://github.com/lampepfl/dotty/runs/1554027939?check_suite_focus=true

Fixes #10787

### CODE REVIEW

File: community-build/test/java/dotty/communitybuild/FailureSummarizer.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import org.junit.runner.Result;
+import org.junit.runner.notification.Failure;
+import org.junit.runner.notification.RunListener;
+
+public class FailureSummarizer extends RunListener {
+  @Override
+  public void testRunFinished(Result result) throws Exception {
+    super.testRunFinished(result);
+    if (result.getFailureCount() > 0) {
+      Thread.sleep(500);  // pause to give sbt log buffers some time to flush
```
Comment (smarter) [inline community-build/test/java/dotty/communitybuild/FailureSummarizer.java:15]: Is that still needed if you output with System.out instead of System.err ?

Comment (griggt) [reply community-build/test/java/dotty/communitybuild/FailureSummarizer.java:15]: I was seeing interspersed and/or too early output without it, no matter which file handle I chose.  It's a bit hacky, but I don't think there's a way here to route the output via the sbt logger?

sbt/junit-interface has some functionality in current master (option --summary=2) that might also work to solve this issue, but there doesn't seem to have been a release since 0.11 over 6 years ago.

Comment (smarter) [reply community-build/test/java/dotty/communitybuild/FailureSummarizer.java:15]: Interesting, I think we should try to push for a new release of junit-interface.

Comment (smarter) [reply community-build/test/java/dotty/communitybuild/FailureSummarizer.java:15]: https://github.com/sbt/junit-interface/issues/94. Meanwhile this PR is already a great improvement even if we have to rely on some hacks so I'd be happy to get it in.
Another approach we might to explore would be using the github annotation API to get info from failed tests reported back in the github UI, there's some github actions to do this based on the XML reports that JUnit generates but I haven't tried them: https://github.com/marketplace/actions/junit-report-to-annotations, https://github.com/marketplace/actions/junit-report

Comment (griggt) [reply community-build/test/java/dotty/communitybuild/FailureSummarizer.java:15]: The annotation API is an interesting avenue for exploration; I'll take a look and see how we might make use of it, not just in regards to the community build but for all the JUnit tests.  But that will likely take time and experimentation and this PR provides a quick (albeit hacky) fix in the interim.

**Comment by griggt** [comment]
Ha, just stumbled across this: https://github.com/lampepfl/dotty-feature-requests/issues/32. How prescient.

**Review by smarter — APPROVED** [review]
