### PR TITLE
Fix parents of tuple classes

### LINKED ISSUE #13435: java.lang.AssertionError: assertion failed: <notype> & Serializable / NoType & TypeRef(ThisType(TypeRef(NoPrefix,module class io)),trait Serializable) in Types$AndType$.apply
was actually trying to minimize to file a non-crash report but here we are.

## Compiler version
3.0.2-RC2

## Minimized code

```Scala
type Axis = String&Singleton
type ShapeTuple = Tuple1[(Axis, Int)]|Tuple2[(Axis, Int), (Axis, Int)]
type Shape = (Axis, Int) |ShapeTuple


def mkSchema(s: Shape) =
  s match
    case (dim: Axis, size: Int) => dim
```

## Output (click arrow to expand)
<details>

```scala
java.lang.AssertionError: assertion failed: <notype> & Serializable / NoType & TypeRef(ThisType(TypeRef(NoPrefix,module class io)),trait Serializable)
[error] 	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] 	at dotty.tools.dotc.core.Types$AndType$.apply(Types.scala:3145)
[error] 	at dotty.tools.dotc.core.TypeOps$.approximateOr$3$$anonfun$2(TypeOps.scala:346)
[error] 	at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:738)
[error] 	at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:724)
[error] 	at scala.collection.AbstractIterable.reduceLeft(Iterable.scala:919)
[error] 	at dotty.tools.dotc.core.TypeOps$.approximateOr$1(TypeOps.scala:346)
[error] 	at dotty.tools.dotc.core.TypeOps$.orDominator(TypeOps.scala:356)
[error] 	at dotty.tools.dotc.core.Types$OrType.join(Types.scala:3229)
[error] 	at dotty.tools.dotc.core.Types$Type.classSymbol(Types.scala:521)
[error] 	at dotty.tools.dotc.core.PatternTypeConstrainer.tryConstrainSimplePatternType$1(PatternTypeConstrainer.scala:98)
[error] 	at dotty.tools.dotc.core.PatternTypeConstrainer.constrainPatternType(PatternTypeConstrainer.scala:178)
[error] 	at dotty.tools.dotc.core.PatternTypeConstrainer.constrainPatternType$(PatternTypeConstrainer.scala:14)
[error] 	at dotty.tools.dotc.core.TypeComparer.constrainPatternType(TypeComparer.scala:30)
[error] 	at dotty.tools.dotc.core.TypeComparer$.constrainPatternType(TypeComparer.scala:2794)
[error] 	at dotty.tools.dotc.typer.Applications.typedUnApply(Applications.scala:1337)
[error] 	at dotty.tools.dotc.typer.Applications.typedUnApply$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnApply(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedTuple(Typer.scala:2606)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2730)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedPattern(Typer.scala:2945)
[error] 	at dotty.tools.dotc.typer.Typer.typedCase(Typer.scala:1646)
[error] 	at dotty.tools.dotc.typer.Typer.typedCases$$anonfun$1(Typer.scala:1579)
[error] 	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:92)
[error] 	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:108)
[error] 	at dotty.tools.dotc.typer.Typer.typedCases(Typer.scala:1581)
[error] 	at dotty.tools.dotc.typer.Typer.$anonfun$20(Typer.scala:1571)
[error] 	at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:2192)
[error] 	at dotty.tools.dotc.typer.Applications.harmonic$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.harmonic(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Typer.typedMatchFinish(Typer.scala:1571)
[error] 	at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1527)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2707)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Typer.$anonfun$34(Typer.scala:2156)
[error] 	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
[error] 	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2156)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2670)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
[error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2352)
[error] 	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2681)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2685)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
[error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2475)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2726)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
[error] 	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
[error] 	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
[error] 	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
[error] 	at dotty.tools.repl.REPLFrontEnd.runOn(ReplFrontEnd.scala:23)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
[error] 	at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:152)
[error] 	at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:162)
[error] 	at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:250)
[error] 	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:213)
[error] 	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:147)
[error] 	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:150)
[error] 	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:169)
[error] 	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:150)
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.java:52)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:233)
[error] 	at sbt.Console.console0$1(Console.scala:64)
[error] 	at sbt.Console.$anonfun$apply$5(Console.scala:74)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:258)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)

```
</details>

### PR DESCRIPTION
**Pull request by odersky**
Fixes #13435

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 1]
```diff
@@ -349,7 +349,11 @@ object TypeOps:
       val doms = dominators(commonBaseClasses, Nil)
       def baseTp(cls: ClassSymbol): Type =
         tp.baseType(cls).mapReduceOr(identity)(mergeRefinedOrApplied)
-      doms.map(baseTp).reduceLeft(AndType.apply)
+      def meet(tp1: Type, tp2: Type) =
+        if !tp1.exists then tp2
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:353]: I don't understand why this is needed, we do:
```scala
val commonBaseClasses = tp.mapReduceOr(_.baseClasses)(intersect)
```
(btw, how is this different from `tp.baseClasses` ?)
So I would expect `tp.baseType` on any of the common base classes to exist, but in fact the base classes of `Tuple1[(Axis, Int)] | ((Axis, Int), (Axis, Int))` contains `Product2`, even though `Tuple1` does not extend `Product2`, so I think there's a bug in how we compute base classes for unions, either here or in OrType#baseClasses.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/TypeErasure.scala [hunk 2]
```diff
@@ -693,8 +693,13 @@ class TypeErasure(sourceLanguage: SourceLanguage, semiEraseVCs: Boolean, isConst
    */
   def eraseInfo(tp: Type, sym: Symbol)(using Context): Type =
     val tp1 = tp match
-      case tp: MethodicType => integrateContextResults(tp, contextResultCount(sym))
-      case _ => tp
+      case tp: MethodicType =>
+        integrateContextResults(tp, contextResultCount(sym))
+      case tp: ClassInfo
+      if defn.isTupleClass(sym) && tp.declaredParents.head.typeSymbol == defn.PairClass =>
+        tp.derivedClassInfo(declaredParents = defn.ObjectType :: tp.declaredParents.tail)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeErasure.scala:700]: Could this be handled by adding an entry to the specialErasure map instead? (https://github.com/lampepfl/dotty/blob/eb8773ecbedd32b7f7f6822696f3c3df3cde6930/compiler/src/dotty/tools/dotc/core/Definitions.scala#L1772-L1779)

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala]: > (btw, how is this different from tp.baseClasses ?)

Turns out it's different for `Null`. Since `Null` is also outside the inheritance hierarchy.

**Review by smarter — APPROVED** [review]
