### PR TITLE
Fix #3965: Make higher-kinded equality correct and efficient

### LINKED ISSUE #3965: Regression in community build: collection-strawman
https://travis-ci.org/lampepfl/dotty-community-build/jobs/336895282

### PR DESCRIPTION
**Pull request by odersky**
#3970 fixed equality for higher-kinded types but came at a steep performance penalty. This PR is trying to avoid the penalty. 

Investigation showed that the main culprit was that equality reverted to `eq` for some ProtoType case classes that inherit from type. Since the multiple copies of these case class instances all had the same hashcode, hashtables saw a significant drop in performance. This shows the danger of redefining equality without also redefining hashcode at the same time. We now dropped the shortcut of having a global `equals` in Type, preferring to overwrite `equals` in each subclass where necessary.

To make detection of such issues easier in the future e9388bc adds the numbers of hash-cons table accesses and collisions in the statistics output.

### CODE REVIEW

**Comment by odersky** [comment]
Test performance please

**Comment by liufengyun** [comment]
test performance please

**Comment by odersky** [comment]
Test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
It seems that caching MethodTypes and PolyTypes is not worth it, so we'll revert the last commit.

**Comment by odersky** [comment]
test performance please

**Comment by liufengyun** [comment]
Performance test finished successfully:

Visit http://dotty-bench.epfl.ch/3978/ to see the changes.

Benchmarks is based on merging with master (5943331)

**Comment by odersky** [comment]
OK, I think performance is roughly on par with what it was before and I don't see any immediate ways to improve. So, ready for review.

**Comment by smarter** [comment]
> Reduce number of calls to Type#equals 

Is this useful at all given that it just forwards to referential equality?

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala [hunk 1]
```diff
@@ -397,9 +397,20 @@ object ProtoTypes {
...
       }
 
-    val added =
-      if (state.constraint contains tl) tl.newLikeThis(tl.paramNames, tl.paramInfos, tl.resultType)
+    /** Ensure that `tl` is not already in constraint, make a copy of necessary */
+    def ensureFresh(tl: TypeLambda): TypeLambda =
+      if (state.constraint contains tl) {
+      	var paramInfos = tl.paramInfos
+      	if (tl.isInstanceOf[HKLambda]) {
+      	  // HKLambdas care hash-consed, need to create an artificial difference by adding
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: typo: care -> are

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: Would something break if we did `tl.clone()` instead to get a different instance?

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -1394,15 +1394,30 @@ object Types {
      */
     def simplified(implicit ctx: Context) = ctx.simplify(this, null)
 
+    final def equals(that: Any, bs: BinderPairs): Boolean =
+      (this `eq` that.asInstanceOf[AnyRef]) || this.iso(that, bs)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: I'm not completely convinced that the default `equals` should call `iso`. Why not explicitly use `iso` in the few cases where we need structural equality (monitored subtyping checks, constraint handing, anything else ?)

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 3]
```diff
@@ -1507,10 +1522,27 @@ object Types {
...
+     *  Otherise the standard identity hash.
+     */
+    override def identityHash(bs: Binders) = {
+       def recur(n: Int, tp: BindingType, rest: Binders): Int =
+        if (this `eq` tp) finishHash(hashing.mix(hashSeed, n), 1)
+        else if (rest == null) System.identityHashCode(this)
+        else recur(n + 1, rest.tp, rest.next)
+      avoidSpecialHashes(
+        if (bs == null) System.identityHashCode(this)
+        else recur(1, bs.tp, bs.next))
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: I just don't know how a 0 behaves for hashing.mix

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 4]
```diff
@@ -2774,7 +2835,7 @@ object Types {
   abstract case class MethodType(paramNames: List[TermName])(
       paramInfosExp: MethodType => List[Type],
       resultTypeExp: MethodType => Type)
-    extends CachedGroundType with MethodOrPoly with TermLambda with NarrowCached { thisMethodType =>
+    extends MethodOrPoly with TermLambda with NarrowCached { thisMethodType =>
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: Good point; we need one since MethodTypes can appear in refinements.

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala]: Yes, they would be assumed as `equals`, so e.g. pendingSubtypes would not distinguish between them.

File: compiler/src/dotty/tools/dotc/core/Types.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: It's just a shorthand to avoid the repeated `eq` tests everywhere it is called.
