### PR TITLE
Warn when @volatile is used on vals

### LINKED ISSUE #19416: Compiler should not allow to define `@volatile val`
`@volatile` annotation only makes sense on variables. The compiler should not allow to use this annotation on immutable `val` field.

## Compiler version
All Scala 3 versions

## Minimized code

```Scala
class Foo:
  @volatile val x: Int = ???
```

## Output

No warnings

## Expectation
Give the same error as Scala 2: 
```scala
./main.scala:2: error: values cannot be volatile
  @volatile val x: Int = ???
                ^
```

### PR DESCRIPTION
**Pull request by AnotherMedo**
Fixes #19416

Done on the scala spree of 16.01.2024 with @mbovel

### CODE REVIEW

**Comment by hamzaremmal** [comment]
The CI fails because of `tests/warn/i19416.check`. You should regenerate this file using the following command :
```sh
testCompilation --update-checkfiles i19416
```

File: compiler/src/dotty/tools/io/ZipArchive.scala [hunk 1]
```diff
@@ -160,7 +160,7 @@ final class FileZipArchive(jpath: JPath, release: Option[String]) extends ZipArc
     override def sizeOption: Option[Int] = Some(zipEntry.getSize.toInt)
   }
 
-  @volatile lazy val (root, allDirs): (DirEntry, collection.Map[String, DirEntry]) = {
+  lazy val (root, allDirs): (DirEntry, collection.Map[String, DirEntry]) = {
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/io/ZipArchive.scala:163]: This should be allowed and should not change. Volatile should also work on `lazy val` because the annotation applies in the `private var` that is used to encode the `lazy val`.

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/io/ZipArchive.scala (hunk 1 above)
Comment (mbovel) [reply compiler/src/dotty/tools/io/ZipArchive.scala:163]: Aren't `lazy vals` now thread-safe by default?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/io/ZipArchive.scala:163]: Right

File: tests/warn/i19416.check [hunk 2]
```diff
@@ -0,0 +1,4 @@
+-- [E193] Syntax Warning: tests\warn\i19416.scala:2:18 -----------------------------------------------------------------
```
Comment (hamzaremmal) [inline tests/warn/i19416.check:1]: The CI fails because of the windows style path.

**Review by hamzaremmal — APPROVED** [review]
