### PR TITLE
Fix and reinstate repl/errmsgs

### LINKED ISSUE #13444: Nightly Dotty workflow of 2021-09-02 failed
See https://github.com/lampepfl/dotty/actions/runs/1192643163

### PR DESCRIPTION
**Pull request by dwijnand**
[test_windows_full]

Fixes #13444

### CODE REVIEW

**Comment by griggt** [comment]
Might want [test_windows_full] ?

**Comment by dwijnand** [comment]
Ideally someone can approve, this passes CI and we can get a clean nightly run.

File: compiler/src/dotty/tools/repl/ReplDriver.scala [hunk 1]
```diff
@@ -428,7 +428,7 @@ class ReplDriver(settings: Array[String],
   /** Like ConsoleReporter, but without file paths or real -Xprompt'ing */
   private object ReplConsoleReporter extends ConsoleReporter(
     reader = null, // this short-circuits the -Xprompt display from waiting for an input
-    writer = new PrintWriter(out, /* autoFlush = */ true), // write to out, not Console.err
+    writer = new PrintWriter(new BufferedWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8)), /* autoFlush = */ true), // write to out, not Console.err
```
Comment (smarter) [inline compiler/src/dotty/tools/repl/ReplDriver.scala:431]: Is the BufferedWriter useful for something here?

**Comment by smarter** [comment]
Besides the CI run, someone should open cmd.exe on Windows and check that the output is actually correct.

File: compiler/src/dotty/tools/repl/ReplDriver.scala (hunk 1 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/repl/ReplDriver.scala:431]: I was wondering the same, but it already took me n hours today to figure out what was actually different (need to toInt chars to get real differences) and how it possibly broke, that I'm done.  This combination comes from what the constructor in PrintWriter does when it's given a PrintStream (out).

Comment (smarter) [reply compiler/src/dotty/tools/repl/ReplDriver.scala:431]: I guess it doesn't matter since there's autoFlush=true, but I'll note that the repl reporter in scala 2 doesn't use BufferedWriter.

**Comment by dwijnand** [comment]
I would hope that's what we had the tests running on Windows for...  Either way, I'd prefer to have the test reinstated even without that check.  Worst case I'll inline the call to doReport and avoid using a PrintWriter.

**Comment by smarter** [comment]
Tests are great but encoding and Windows are weird enough that this isn't enough in general to know what the user will see with their own eyes :).

**Comment by griggt** [comment]
I'll try to take a look soon. I have a Windows machine I can test on.

**Comment by griggt** [comment]
Real-life results don't look great.

Tested with Windows 10 Console:

with this PR:

Win10-Console-PR13459

3.0.2 (looks good):

Win10-Console-3 0 2

Same results using the new Windows Terminal instead of Windows Console.

The output on Windows 7 is a mess (but it seems to be so on 3.0.2 also):

Win7-Console-PR13459

**Comment by smarter** [comment]
Could you try using ctx.settings.encoding.value instead of UTF-8? Presumably that shouldn't impact the tests since they're always run with UTF-8 encoding.

**Comment by griggt** [comment]
> Could you try using ctx.settings.encoding.value instead of UTF-8? 

No change -- same bad output on the console.

**Comment by griggt** [comment]
FWIW the console output looks good if I run `chcp 65001` at the cmd.exe prompt before launching the REPL.   But 3.0.2 does not need this and I doubt that many users would even think to try this.

**Comment by griggt** [comment]
If we can discover the encoding used by the current `out: PrintStream` and re-use it when constructing the `OutputStreamWriter` for the reporter, we seem to get the proper output.

For example, this hack "works" and gives the expected output on JDK < 16

```diff
   /** Like ConsoleReporter, but without file paths or real -Xprompt'ing */
   private object ReplConsoleReporter extends ConsoleReporter(
     reader = null, // this short-circuits the -Xprompt display from waiting for an input
-    writer = new PrintWriter(new BufferedWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8)), /* autoFlush = */ true), // write to out, not Console.err
+    writer = new PrintWriter(new BufferedWriter(new OutputStreamWriter(out, encodingOfPrintStream(out))), /* autoFlush = */ true), // write to out, not Console.err
   ) {
     override def posFileStr(pos: SourcePosition) = "" // omit file paths
   }
 
+  private def encodingOfPrintStream(ps: PrintStream): String = {
+    val f = ps.getClass().getDeclaredField("charOut")
+    f.setAccessible(true)
+    f.get(ps).asInstanceOf[OutputStreamWriter].getEncoding
+  }
+
```

and gives the expected output on both my Windows machine (where it apparently uses encoding "Cp437") and Linux (where it uses "UTF8"). 

But can we get at this without the reflection hackery?

**Comment by griggt** [comment]
> Worst case I'll inline the call to doReport and avoid using a PrintWriter.

I've pushed a commit 1632cb9e7e5af5e4df3e151d32176060298f026c that takes that sort of approach, since there doesn't seem to be an API to get the encoding out of an existing PrintStream.

I verified with that commit the output looks good again in Windows Console / Windows Terminal.

**Comment by dwijnand** [comment]
> > Could you try using ctx.settings.encoding.value instead of UTF-8?
> 
> No change -- same bad output on the console.

It's weird this didn't work.  What encoding was being used?  Was it not Cp437?

**Comment by griggt** [comment]
> > Could you try using ctx.settings.encoding.value instead of UTF-8?
> 
> It's weird this didn't work. What encoding was being used? Was it not Cp437?

Just checked.  UTF-8 in that case.

**Comment by dwijnand** [comment]
Ah, so that's the encoding you're using for compiling the files but not for the console..  Hmm.

**Comment by griggt** [comment]
Yes, I believe so.  There seems to be API to ask for the former but not the latter (but the Console.out PrintStream automagically chooses the appropriate encoder, just doesn't want to share that tidbit)

**Comment by som-snytt** [comment]
Just to say, I got sucked into Windows issues on Scala 2 and will try to try stuff out during my waking hours. I sympathize with y'all. Currently I do everything under WSL; I bought a Windows box for last gig, was too lazy to dual boot this time.

**Comment by dwijnand** [comment]
Everyone happy to land this now?

**Review by smarter — APPROVED** [review]

**Comment by griggt** [comment]
I'll have time later today to look it over in detail if desired but at a glance LGTM.

**Review by griggt — APPROVED** [review]

**Comment by philwalk** [comment]
I'm seeing what looks like this problem for the first time, when I run `errmsgs` test in a `cygwin/mintty` environment.
Is this unexpected?   Or is there some configuration step I need to take?    Here's the output:
```scala
-- [E007] Type Mismatch Error: -------------------------------------------------
1 | abstract class C { type T; val x: T; val s: Unit = { type T = String; var y: T = x; locally { def f() = { type T = Int; val z: T = y }; f() } }; }
  |                                                                                  ^
  |Found:    (C.this.x : C.this.T)
  |Required: T▓
  |
  |where:    T  is a type in class C
  |          T▓ is a type in the initializer of value s which is an alias of String
longer explanation available when compiling with `-explain`
-- [E007] Type Mismatch Error: -------------------------------------------------
1 | abstract class C { type T; val x: T; val s: Unit = { type T = String; var y: T = x; locally { def f() = { type T = Int; val z: T = y }; f() } }; }
  |                                                                                                                                    ^
  |Found:    (y : T)
  |Required: T▓
  |
  |where:    T  is a type in the initializer of value s which is an alias of String
  |          T▓ is a type in method f which is an alias of Int
longer explanation available when compiling with `-explain`
```

and here's the expected output:
```scala
-- [E007] Type Mismatch Error: -------------------------------------------------
1 | abstract class C { type T; val x: T; val s: Unit = { type T = String; var y: T = x; locally { def f() = { type T = Int; val z: T = y }; f() } }; }
  |                                                                                  ^
  |Found:    (C.this.x : C.this.T)
  |Required: T┬▓
  |
  |where:    T  is a type in class C
  |          T┬▓ is a type in the initializer of value s which is an alias of String
longer explanation available when compiling with `-explain`
-- [E007] Type Mismatch Error: -------------------------------------------------
1 | abstract class C { type T; val x: T; val s: Unit = { type T = String; var y: T = x; locally { def f() = { type T = Int; val z: T = y }; f() } }; }
  |                                                                                                                                    ^
  |Found:    (y : T)
  |Required: T┬▓
  |
  |where:    T  is a type in the initializer of value s which is an alias of String
  |          T┬▓ is a type in method f which is an alias of Int
longer explanation available when compiling with `-explain`
```
