### PR TITLE
fix: #23261 Distinguish 0.0 and -0.0 in ConstantType match types

### LINKED ISSUE #23261: Match types do not treat 0.0d and -0.0d as equivalent constants
## Compiler version

Scala 3.7.0
(Confirmed with both sbt and Scala CLI)

## Minimized code

```scala
type DoubleToString[D <: Double] <: String = D match
  case 0.0 => "0.0"
  case _ => "_"

@main def main(): Unit =
  summon[DoubleToString[0.0] =:= "0.0"]
  summon[DoubleToString[-0.0] =:= "0.0"]
  summon[DoubleToString[-0.0] =:= "_"]
```

## Compilation output

```scala
[error] -- [E172] Type Error: src/main/scala/Main.scala:7:40 
[error] 7 |  summon[DoubleToString[-0.0] =:= "0.0"]
[error]   |                                        ^
[error]   |  Cannot prove that DoubleToString[(-0.0d : Double)] =:= ("0.0" : String).
[error]   |
[error]   |  Note: a match type could not be fully reduced:
[error]   |    trying to reduce  DoubleToString[(-0.0d : Double)]
[error]   |    failed since selector (-0.0d : Double)
[error]   |    is uninhabited (there are no values of that type).

[error] -- [E172] Type Error: src/main/scala/Main.scala:8:38 
[error] 8 |  summon[DoubleToString[-0.0] =:= "_"]
[error]   |                                      ^
[error]   |  Cannot prove that DoubleToString[(-0.0d : Double)] =:= ("_" : String).
[error]   |  Note: a match type could not be fully reduced:
[error]   |    trying to reduce  DoubleToString[(-0.0d : Double)]
[error]   |    failed since selector (-0.0d : Double)
[error]   |    is uninhabited (there are no values of that type).
```

## Problem description

In Scala 3.7.0, match types cannot distinguish or unify `0.0` and `-0.0`, even though:
  
- `0.0d == -0.0d` holds at runtime
- Using `=:=` on the type level compiles successfully: `summon[0.0 =:= -0.0]` works

However, in match types, writing `case 0.0 =>` causes `-0.0` to be rejected as an uninhabited selector.
Switching to `case -0.0 =>` then rejects `0.0`.

This suggests that match types are not treating `0.0d` and `-0.0d` as equivalent constant values, which is inconsistent with how `=:=` treats them.

## Expected behavior

Match types on `Double` constants should not distinguish `0.0` and `-0.0`, just as `=:=` does not.

### PR DESCRIPTION
**Pull request by kijuky**
Fixes #23261

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -401,7 +401,13 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
         compareErasedValueType
       case ConstantType(v2) =>
         tp1 match {
-          case ConstantType(v1) => v1.value == v2.value && recur(v1.tpe, v2.tpe)
```
Comment (kijuky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:404]: MEMO 

I tried to modify the Constants.scala below to change the processing of the `==` method, but it didn't work.

https://github.com/scala/scala3/blob/a5a7644dd900ee7af8c36e87205b4d0b64275878/compiler/src/dotty/tools/dotc/core/Constants.scala#L56

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:404]: The line should use equals, which is already correct, see equalHashValue comment.
```
case ConstantType(v1) => v1.value.equals(v2.value) && recur(v1.tpe, v2.tpe)
```

File: tests/neg/i23261.scala [hunk 2]
```diff
@@ -0,0 +1,7 @@
+@main def main(): Unit =
+  summon[0.0 =:= -0.0]
```
Comment (som-snytt) [inline tests/neg/i23261.scala:2]: `  summon[0.0 =:= -0.0] // error`
to annotate an expected error on that line

**Review by som-snytt — APPROVED** [review]
I suspect the call to `recur` is extraneous and could be deleted, but it must also be correct to leave it as it is. (It is no less correct than the existing code.)

**Review by sjrd — APPROVED** [review]
