### PR TITLE
Fix #17467: Limit isNullable widening to stable TermRefs; remove under explicit nulls.

### LINKED ISSUE #17467: Null <:< "foo" and other problems with Null subtyping (also in -Yexplicit-nulls)
## Compiler version

3.3.0-RC5

## Problem at a glance

`Null` is considered to be a subtype of anything *that `widenDealias`es* to a nullable type.

## Spec context

The spec actually says that `Null <:< x.type` if the underlying type of `x` is a nullable. But that is supposed to only apply to singleton types of the form `path.type`. Currently in dotty, we even have absurd things like `Null <:< "foo"` because `"foo"` widens to `"String"` which is nullable.

See https://scala-lang.org/files/archive/spec/2.13/03-types.html#singleton-types

## Minimized code

REPL session without `-Yexplicit-nulls`

```scala
$ cs launch scala:3.3.0-RC5
Welcome to Scala 3.3.0-RC5 (1.8.0_362, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                    
scala> val x: "foo" = null
val x: "foo" = null
                                                                                                    
scala> val y: 5 = null // Type error, as expected
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |val y: 5 = null // Type error, as expected
  |           ^^^^
  |Found:    Null
  |Required: (5 : Int)
  |Note that implicit conversions were not tried because the result of an implicit conversion
  |must be more specific than (5 : Int)
  |
  | longer explanation available when compiling with `-explain`
1 error found
                                                                                                    
scala> val a: "foo" = "foo"
val a: "foo" = foo
                                                                                                    
scala> val b: a.type = null
val b: a.type = null
                                                                                                    
scala> val c: Any = new AnyRef
val c: Any = java.lang.Object@78d73b1b
                                                                                                    
scala> val d: c.type = null
val d: c.type = null
                                                                                                    
scala> val e: AnyVal = 5
val e: AnyVal = 5
                                                                                                    
scala> val f: e.type = null // Type error as expected
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |val f: e.type = null // Type error as expected
  |                ^^^^
  |Found:    Null
  |Required: (e : AnyVal)
  |Note that implicit conversions were not tried because the result of an implicit conversion
  |must be more specific than (e : AnyVal)
  |
  | longer explanation available when compiling with `-explain`
1 error found
                                                                                                    
scala> summon[Null <:< "foo"]
val res0: Null =:= Null = generalized constraint
                                                                                                    
scala> summon[Null <:< c.type]
val res1: Null =:= Null = generalized constraint

scala> class Foo { def bar(): this.type = null }
// defined class Foo
```

Even under `-Yexplicit-nulls`, we have issues:

```scala
$ cs launch scala:3.3.0-RC5 -- -Yexplicit-nulls
Welcome to Scala 3.3.0-RC5 (1.8.0_362, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                    
scala> val x: "foo" = null // hey, progress!
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |val x: "foo" = null // hey, progress!
  |               ^^^^
  |Found:    Null
  |Required: ("foo" : String)
  |Note that implicit conversions were not tried because the result of an implicit conversion
  |must be more specific than ("foo" : String)
  |
  | longer explanation available when compiling with `-explain`
1 error found
                                                                                                    
scala> val x: Any = "foo"
val x: Any = foo
                                                                                                    
scala> val y: x.type = null // oops, still broken
val y: x.type = null
                                                                                                    
scala> val a: String | Null = "foo"
val a: String | Null = foo
                                                                                                    
scala> val b: a.type = null // this is broken too
val b: a.type = null
                                                                                                    
scala> summon[Null <:< a.type]
val res0: Null =:= Null = generalized constraint
                                                                                                    
scala> type Foo = a.type
// defined alias type Foo = a.type
                                                                                                    
scala> summon[Null <:< Foo]
val res1: Null =:= Null = generalized constraint
```

## Expectation

Not having `Null <:< T` for arbitrary `T`s that `widenDealias` to a nullable type. Only allow it for *singleton types* (in dotc terminology, `TermRef`s) whose direct underlying type is nullable, as the spec says.

Further, under `-Yexplicit-nulls`, IMO we should take the opportunity to tighten the spec to remove the weird clause about the underlying type of singleton types.

### PR DESCRIPTION
**Pull request by sjrd**
The Scala language specification has a peculiar clause about the nullness of singleton types of the form `path.type`. It says that `Null <:< path.type` if the *underlying* type `U` of `path` is nullable itself.

The previous implementation of that rule was overly broad, as it indiscrimately widened all types. This resulted in problematic subtyping relationships like `Null <:< "foo"`.

We do not widen anymore. Instead, we specifically handle `TermRef`s of stable members, which are how dotc represents singleton types. We also have a rule for `Null <:< null`, which is necessary for pattern matching exhaustivity to keep working in the presence of nulls.

---

#### Under explicit nulls, remove the rule Null <:< x.type.

The specified rule that `Null <:< x.type` when the underlying type `U` of `x` is nullable is dubious to begin with. Under explicit nulls, it becomes decidedly out of place. We now disable that rule under `-Yexplicit-nulls`.

### CODE REVIEW

**Review by odersky — APPROVED** [review]
Nicely confined changes!

File: tests/explicit-nulls/neg/i17467.scala [hunk 1]
```diff
@@ -0,0 +1,10 @@
+object Test:
+  def test(): Unit =
+    val a1: String = "foo"
+    val a2: a1.type = null // error
+
+    val b1: String | Null = "foo"
+    val b2: b1.type = null // error
+    summon[Null, b1.type] // error
```
Comment (noti0na1) [inline tests/explicit-nulls/neg/i17467.scala:8]: `summon[Null <:< b1.type]`

File: tests/explicit-nulls/neg/i17467.scala [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+  end test
```
Comment (noti0na1) [inline tests/explicit-nulls/neg/i17467.scala:9]: Can we add the code below to this file and `tests/neg/i17467.scala`.

```scala
val c1: Null = null
val c2: c1.type = null
```

**Review by noti0na1 — CHANGES_REQUESTED** [review]
I agree this is definitely a more refined rule for singleton type!
BTW, is there any specific reason why 
```scala
val c1: Null = null 
val c2: c1.type = null
```
is disallowed under explicit nulls?

**Comment by sjrd** [comment]
> BTW, is there any specific reason why
> 
> ```scala
> val c1: Null = null 
> val c2: c1.type = null
> ```
> 
> is disallowed under explicit nulls?

I added a comment with the test you suggested. The reason is that allowing this under explicit nulls would require a dedicated subtyping rule (both in spec and in implementation), and would provide marginal/debatable value. So IMO it is better to leave it out.

File: tests/explicit-nulls/neg/i17467.scala [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+
+    val b1: String | Null = "foo"
+    val b2: b1.type = null // error
+    summon[Null <:< b1.type] // error
+
+    /* The following would be sound, but it would require a specific subtyping
+     * rule (and implementation code) for debatable value. So it is an error.
+     */
+    val c1: Null = null
+    val c2: h1.type = null // error
```
Comment (dwijnand) [inline tests/explicit-nulls/neg/i17467.scala:14]: Here's the problem with making checkfiles optional... what's the error?  Are we meant to be testing `h1` wasn't found?

Comment (sjrd) [reply tests/explicit-nulls/neg/i17467.scala]: Oh my god :man_facepalming: 
Fixed, and added check files.

File: tests/explicit-nulls/neg/i17467.check [hunk 4]
```diff
@@ -0,0 +1,31 @@
+-- [E007] Type Mismatch Error: tests/explicit-nulls/neg/i17467.scala:4:22 ----------------------------------------------
+4 |    val a2: a1.type = null // error
+  |                      ^^^^
+  |                      Found:    Null
+  |                      Required: (a1 : String)
+  |                      Note that implicit conversions were not tried because the result of an implicit conversion
+  |                      must be more specific than (a1 : String)
```
Comment (dwijnand) [inline tests/explicit-nulls/neg/i17467.check:7]: An unfortunate error message, seeing how `a1 : String` is already a fairly specific type...  (not a blocker imo)

File: tests/neg/i17467.scala [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+
+    type MyNonNullable = Int
+    val e1: MyNonNullable = 5
+    val e2: e1.type = null // error
+
+    summon[Null <:< "foo"] // error
+
+    val f1: Mod.type = null // error
+
+    var g1: AnyRef = "foo"
```
Comment (dwijnand) [inline tests/neg/i17467.scala:23]: Is the var intended here?

Comment (sjrd) [reply tests/neg/i17467.scala:23]: Yes, the `var` is intended.

File: tests/explicit-nulls/neg/i17467.check (hunk 4 above)
Comment (sjrd) [reply tests/explicit-nulls/neg/i17467.check:7]: I agree, but that error message has nothing to do with nullability, AFAICT. Has it?

Comment (dwijnand) [reply tests/explicit-nulls/neg/i17467.check:7]: I think it's possible, given `isUnderSpecifiedArgument` ends up checking if the argument type `isRef(defn.NullClass)`.

**Review by noti0na1 — APPROVED** [review]
LGTM

**Comment by sjrd** [comment]
Rebased to be on top of #18284, since this was waiting for a minor release.

@Kordyjan Could you confirm that `main` is for 3.4.x now, and that therefore we can merge things that need a minor release?

**Comment by Kordyjan** [comment]
Yes. The Main is now 3.4. It can be safely merged.

**Comment by WojciechMazur** [comment]
We've found 1 project ([slick/slick](https://github.com/VirtusLab/community-build3/actions/runs/5836591202/job/15831389412)) which failed in Open CB after merging this change. The failing code can be minimizes to: 
```Scala 
class Foo:
  def foo(flag: Boolean): this.type = if(flag) this else null 
``` 
Failing with: 
```Scala 
-- [E007] Type Mismatch Error: /Users/wmazur/projects/dotty/bisect/main.scala:4:49 
4 |  def foo(): this.type = if(flag) this else null 
  |                                            ^^^^
  |Found:    Null
  |Required: (Foo.this : Foo)
```
The snippet above makes no sense to me so I don't treat it as a regression.

**Comment by sjrd** [comment]
Indeed, that makes absolutely no sense, and is precisely the kinds the soundness holes that this PR is meant to fix.

**Comment by WojciechMazur** [comment]
I've found 1 more project failing due this change (simy4/coregex)[https://github.com/VirtusLab/community-build3/actions/runs/5836591202/job/15831389198], which also make not much sense: 
```scala
type Matching[A >: Null <: String, Regex >: Null <: String with Singleton] <: A
def uuid: Matching[String, "[0-9a-f]"] = ??? // error Type argument ("[0-9a-f]" : String) does not conform to lower bound Null
```

The obious workaround it removing the null bound which allows to compile it: 
```Scala 
type Matching[A <: String, Regex <: String with Singleton] <: A
def uuid: Matching[String, "[0-9a-f]"] = ???

```

**Comment by sjrd** [comment]
> We've found 1 project ([slick/slick](https://github.com/VirtusLab/community-build3/actions/runs/5836591202/job/15831389412)) which failed in Open CB after merging this change. The failing code can be minimized to:

Actually, after thinking about this more, I think that particular case, with the `this.type`, is in fact an unintended regression. `this.type` is a *singleton type* in spec language, but not a `TermRef` in the implementation (it's a `ThisType` instead), so I think we need to handle `ThisType` in the new logic.
