### PR TITLE
Fix bytecode generation for Single Abstract Method lambdas

### LINKED ISSUE #10068: Lambda syntax for SAM crashes with AbstractMethodError
When using the Lambda syntax for SAM type, a trait in this case, the Dotty-compiled program crashes at runtime with `java.lang.AbstractMethodError`

## Minimized code

```Scala
def make[A](ord: (A, A) => Ordering): Ord[A] =
     (l, r) => ord(l, r) 
```

## Output
Dotty compiles the code without a complaint, but the code crashes at runtime.
```scala
[info]       java.lang.AbstractMethodError: Method zio/prelude/Ord$$$Lambda$10282.checkCompare(Ljava/lang/Object;Ljava/lang/Object;)Lzio/prelude/PartialOrdering; is abstract
[info]       	at zio.prelude.Ord$$$Lambda$10282/1407254277.checkCompare(Unknown Source)
[info]       	at zio.prelude.PartialOrd.compare(PartialOrd.scala:21)
```
https://app.circleci.com/pipelines/github/zio/zio-prelude/741/workflows/53a57041-ca7f-442c-bd00-64fdf7c8a139/jobs/4226/steps

## Expectation

Code should either fail to compile, or not crash. The same code works OK with Scala 2.

## Workaround
Use the verbose way:
```scala
   def make[A](ord: (A, A) => Ordering): Ord[A] = new Ord[A] { 
    override protected def checkCompare(l: A, r: A): Ordering = ord(l, r)
  }
```
https://github.com/zio/zio-prelude/pull/239/commits/c0450bb7ad098f688a0d04ef967edac66174ebf4
Then everything works as expected.

### LINKED ISSUE #11676: Compiler Crashes Attempting To Compile ZIO Prelude On 3.0.0-RC1
See PR attempting to update [here](https://github.com/zio/zio-prelude/pull/567).

The error message is unfortunately very long.

I realize this is not minimized but unfortunately given the nature of the error message I'm not sure how we would go about minimizing it. ZIO Prelude was compiling on `3.0.0-M3` so perhaps someone with more familiarity with the changes between `M3` and `RC1` would have a better sense of what could be causing the issue.

Copying @vigoo and @sideeffffect.

```
[info] exception occurred while compiling /home/runner/work/zio-prelude/zio-prelude/core/jvm/src/main/scala/PlatformSpecificAssociativeSyntax.scala, /home/runner/work/zio-prelude/zio-prelude/core/jvm/src/main/scala/PlatformSpecificIdentitySyntax.scala, /home/runner/work/zio-prelude/zio-prelude/core/jvm/target/scala-3.0.0-RC1/src_managed/main/sbt-buildinfo/BuildInfo.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala-2.13+/zio/prelude/InvariantVersionSpecific.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AnyType.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Assertions.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Associative.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeBoth.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeCompose.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeEither.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeFlatten.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Bicovariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Commutative.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/CommutativeBoth.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/CommutativeEither.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Const.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Contravariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Covariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Debug.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Derive.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Divariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Equal.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Equivalence.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ForEach.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/GenFs.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Gens.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Hash.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Id.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Idempotent.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Identity.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityBoth.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityCompose.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityEither.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityFlatten.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Invariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Inverse.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NewtypeModule.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NewtypeModuleF.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NonEmptyForEach.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NonEmptyList.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NonEmptySet.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Ord.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ParSeq.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/PartialEquivalence.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/PartialOrd.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/SafeFunction.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/These.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ZNonEmptySet.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ZSet.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Zivariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/coherent/coherent.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/fx/ZPure.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/fx/ZPureArities.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/fx/package.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/newtypes/package.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/package.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/recursive/Folder.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/recursive/Recursive.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/recursive/Unfolder.scala
10267
scala.MatchError: TypeRef(ThisType(TypeRef(NoPrefix,module class prelude)),trait Ord) (of class dotty.tools.dotc.core.Types$CachedTypeRef) while compiling /home/runner/work/zio-prelude/zio-prelude/core/jvm/src/main/scala/PlatformSpecificAssociativeSyntax.scala, /home/runner/work/zio-prelude/zio-prelude/core/jvm/src/main/scala/PlatformSpecificIdentitySyntax.scala, /home/runner/work/zio-prelude/zio-prelude/core/jvm/target/scala-3.0.0-RC1/src_managed/main/sbt-buildinfo/BuildInfo.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala-2.13+/zio/prelude/InvariantVersionSpecific.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AnyType.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Assertions.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Associative.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeBoth.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeCompose.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeEither.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/AssociativeFlatten.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Bicovariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Commutative.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/CommutativeBoth.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/CommutativeEither.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Const.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Contravariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Covariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Debug.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Derive.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Divariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Equal.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Equivalence.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ForEach.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/GenFs.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Gens.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Hash.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Id.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Idempotent.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Identity.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityBoth.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityCompose.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityEither.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/IdentityFlatten.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Invariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Inverse.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NewtypeModule.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NewtypeModuleF.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NonEmptyForEach.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NonEmptyList.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/NonEmptySet.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Ord.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ParSeq.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/PartialEquivalence.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/PartialOrd.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/SafeFunction.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/These.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ZNonEmptySet.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/ZSet.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/Zivariant.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/coherent/coherent.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/fx/ZPure.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/fx/ZPureArities.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/fx/package.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/newtypes/package.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/package.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/recursive/Folder.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/recursive/Recursive.scala, /home/runner/work/zio-prelude/zio-prelude/core/shared/src/main/scala/zio/prelude/recursive/Unfolder.scala
10268
[error] ## Exception when compiling 59 sources to /home/runner/work/zio-prelude/zio-prelude/core/jvm/target/scala-3.0.0-RC1/classes
10269
[error] scala.MatchError: TypeRef(ThisType(TypeRef(NoPrefix,module class prelude)),trait Ord) (of class dotty.tools.dotc.core.Types$CachedTypeRef)
10270
[error] dotty.tools.dotc.transform.Erasure$Boxing$.adaptClosure(Erasure.scala:421)
10271
[error] dotty.tools.dotc.transform.Erasure$Typer.typedClosure(Erasure.scala:1006)
10272
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2604)
10273
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
10274
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10275
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10276
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10277
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
10278
[error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:975)
10279
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2601)
10280
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
10281
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10282
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10283
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10284
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
10285
[error] dotty.tools.dotc.typer.Typer.$anonfun$35(Typer.scala:2080)
10286
[error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:223)
10287
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2080)
10288
[error] dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:929)
10289
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2570)
10290
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
10291
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10292
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10293
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10294
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
10295
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
10296
[error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1037)
10297
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2226)
10298
[error] dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1026)
10299
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2581)
10300
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2585)
10301
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
10302
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10303
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10304
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10305
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
10306
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
10307
[error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1037)
10308
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2378)
10309
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2626)
10310
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
10311
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10312
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10313
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10314
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
10315
[error] dotty.tools.dotc.transform.Erasure.run(Erasure.scala:124)
10316
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
10317
[error] scala.collection.immutable.List.map(List.scala:250)
10318
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
10319
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
10320
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
10321
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
10322
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
10323
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
10324
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
10325
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
10326
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
10327
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:230)
10328
[error] dotty.tools.dotc.Run.compileSources(Run.scala:166)
10329
[error] dotty.tools.dotc.Run.compile(Run.scala:150)
10330
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
10331
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
10332
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
10333
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
10334
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
10335
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
10336
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
10337
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
10338
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
10339
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
10340
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
10341
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
10342
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
10343
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
10344
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
10345
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
10346
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
10347
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
10348
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
10349
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
10350
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
10351
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
10352
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
10353
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
10354
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
10355
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
10356
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
10357
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
10358
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
10359
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
10360
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2200)
10361
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2157)
10362
[error] sbt.internal.io.Retry$.apply(Retry.scala:40)
10363
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
10364
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
10365
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2153)
10366
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
10367
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
10368
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
10369
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
10370
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
10371
[error] sbt.Execute.work(Execute.scala:291)
10372
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
10373
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
10374
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
10375
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10376
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
10377
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10378
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10379
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10380
[error] java.base/java.lang.Thread.run(Thread.java:834)
10381
[error]            
10382
[error] scala.MatchError: TypeRef(ThisType(TypeRef(NoPrefix,module class prelude)),trait Ord) (of class dotty.tools.dotc.core.Types$CachedTypeRef)
10383
[error] 	at dotty.tools.dotc.transform.Erasure$Boxing$.adaptClosure(Erasure.scala:421)
10384
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedClosure(Erasure.scala:1006)
10385
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2604)
10386
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
10387
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10388
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10389
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10390
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
10391
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:975)
10392
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2601)
10393
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
10394
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10395
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10396
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10397
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
10398
[error] 	at dotty.tools.dotc.typer.Typer.$anonfun$35(Typer.scala:2080)
10399
[error] 	at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:223)
10400
[error] 	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2080)
10401
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:929)
10402
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2570)
10403
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
10404
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10405
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10406
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10407
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
10408
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
10409
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1037)
10410
[error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2226)
10411
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedClassDef(Erasure.scala:1026)
10412
[error] 	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2581)
10413
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2585)
10414
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2654)
10415
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10416
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10417
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10418
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2746)
10419
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2796)
10420
[error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:1037)
10421
[error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2378)
10422
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2626)
10423
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2655)
10424
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
10425
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2720)
10426
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2724)
10427
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2840)
10428
[error] 	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:124)
10429
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
10430
[error] 	at scala.collection.immutable.List.map(List.scala:250)
10431
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
10432
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
10433
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
10434
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
10435
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
10436
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
10437
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
10438
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
10439
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
10440
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
10441
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
10442
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:150)
10443
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
10444
[error] 	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
10445
[error] 	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
10446
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
10447
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
10448
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
10449
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
10450
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
10451
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
10452
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
10453
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
10454
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
10455
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
10456
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
10457
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
10458
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
10459
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
10460
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
10461
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
10462
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
10463
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
10464
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
10465
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
10466
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
10467
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
10468
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
10469
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
10470
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
10471
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
10472
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
10473
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2200)
10474
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2157)
10475
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:40)
10476
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
10477
[error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
10478
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2153)
10479
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
10480
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
10481
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
10482
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
10483
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
10484
[error] 	at sbt.Execute.work(Execute.scala:291)
10485
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
10486
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
10487
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
10488
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10489
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
10490
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10491
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10492
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10493
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
10494
[error] (coreJVM / Compile / compileIncremental) scala.MatchError: TypeRef(ThisType(TypeRef(NoPrefix,module class prelude)),trait Ord) (of class dotty.tools.dotc.core.Types$CachedTypeRef)
10495
[error] Total time: 54 s, completed Mar 9, 2021, 5:58:09 PM
10496

10497
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by prolativ**
Partially based on https://github.com/scala/scala/pull/6087

Fixes #10068
Fixes #11676

### CODE REVIEW

File: compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala [hunk 1]
```diff
@@ -1457,21 +1457,38 @@ trait BCodeBodyBuilder extends BCodeSkelBuilder {
...
       }
 
-      val methodName = abstractMethod.javaSimpleName
-      val applyN = {
-        val mt = asmMethodType(abstractMethod)
-        mt.toASMType
+      val methodName = samMethod.javaSimpleName
+      val samMethodType = asmMethodType(samMethod).toASMType
+      val needsGenericBridge = samMethodType != instantiatedMethodType
+      val bridgeMethods = atPhase(erasurePhase.prev){
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:1463]: This can actually be run at `erasurePhase` because when running at a certain phase we see the types as they are before the phase denotation transformer is run.
```suggestion
      val bridgeMethods = atPhase(erasurePhase) {
```

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -927,8 +927,10 @@ object Types {
      */
     final def possibleSamMethods(using Context): Seq[SingleDenotation] = {
       record("possibleSamMethods")
-      abstractTermMembers.toList.filterConserve(m =>
-        !m.symbol.matchingMember(defn.ObjectType).exists && !m.symbol.isSuperAccessor)
+      atPhaseNoLater(erasurePhase.prev) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala:930]: Same here:
```suggestion
      atPhaseNoLater(erasurePhase) {
```

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala [hunk 3]
```diff
@@ -431,10 +431,14 @@ object Erasure {
...
       val implReturnsUnit = implResultType.classSymbol eq defn.UnitClass
-      // The SAM that this closure should implement
-      val SAMType(sam) = lambdaType: @unchecked
-      val samParamTypes = sam.paramInfos
-      val samResultType = sam.resultType
+      // The SAM that this closure should implement.
+      // At this point it should be already guaranteed that there's only one method to implement
+      val Seq(unerasedSam) = lambdaType.possibleSamMethods
+      // We're now in erasure so the alternatives will have erased types
+      val Seq(erasedSam: MethodType) = unerasedSam.symbol.alternatives.map(_.info)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/Erasure.scala:438]: To avoid this complication I suggest changing `possibleSamMethods` to do `.map(_.current)` at the end so the denotations always correspond to the current phase.

File: compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala [hunk 4]
```diff
@@ -1457,21 +1457,38 @@ trait BCodeBodyBuilder extends BCodeSkelBuilder {
         }
       }
 
-      val methodName = abstractMethod.javaSimpleName
-      val applyN = {
-        val mt = asmMethodType(abstractMethod)
-        mt.toASMType
+      val methodName = samMethod.javaSimpleName
+      val samMethodType = asmMethodType(samMethod).toASMType
+      val needsGenericBridge = samMethodType != instantiatedMethodType
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:1462]: I suggest adding the same comment than in Scala 2 for context:
```suggestion
      // scala/bug#10334: make sure that a lambda object for `T => U` has a method `apply(T)U`, not only the `(Object)Object`
      // version. Using the lambda a structural type `{def apply(t: T): U}` causes a reflective lookup for this method.
      val needsGenericBridge = samMethodType != instantiatedMethodType
```

**Review by smarter — CHANGES_REQUESTED** [review]
Otherwise LGTM, @hrhino might be interested in taking a look too.

**Comment by prolativ** [comment]
@smarter reworks done

**Review by smarter — APPROVED** [review]

**Comment by griggt** [comment]
`community_build_a` seems to be hung, it's been running for 3.5 hours

https://github.com/lampepfl/dotty/runs/2185729042?check_suite_focus=true

**Comment by smarter** [comment]
Looks like it was stuck in zio, maybe it would benefit from a larger heap? Restarting for now.
