### PR TITLE
Fix #7413: Adjust singleton arguments for new conversions

### LINKED ISSUE #7413: Instance of Conversion is not found for a singleton type
## minimized code

```Scala
import scala.language.implicitConversions

trait Fixture[A] extends Conversion[0, A]

trait TestFramework[A] {
  def (testName: String) in (test: given (Fixture[A]) => Unit): Unit = ???
}

trait Greeter {
  def greet(name: String): String = s"Hello $name"
}

case class MyFixture(name: String, greeter: Greeter)

class MyTest extends TestFramework[MyFixture] {
  "say hello" in {
    assert(0.greeter.greet(0.name) == s"Hello ${0.name}")
  }
}
```

## expectation

Expected `Fixture` Conversion to apply and attach names to `0`, but got error:
```
[error] example.scala:48:14: value greeter is not a member of Int
[error]     assert(0.greeter.greet(0.name) == s"Hello ${0.name}")
[error]              ^
```
Using an implicit def conversion instead of `Conversion` works as expected:

```scala
implicit def fixture0[A](z: 0)(implicit f: Fixture[A]): A = f(z)
```

### PR DESCRIPTION
**Pull request by odersky**
The types of old-style implicit conversion methods were massaged in `adjustSingletonArgs` to
become eligible for singleton arguments (which are widened, in order to get better cache hits
ratios). The same is now done for new style Conversion instances.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -174,14 +174,19 @@ object Implicits {
...
             val res = adjustSingletonArg(tp.resType)
-            if (res `eq` tp.resType) tp else tp.derivedLambdaType(resType = res)
+            if res eq tp.resType then tp else tp.derivedLambdaType(resType = res)
           case tp: MethodType =>
             tp.derivedLambdaType(paramInfos = tp.paramInfos.mapConserve(widenSingleton))
-          case _ => tp
-        }
+          case _ =>
+            tp.baseType(defn.ConversionClass) match
+              case app @ AppliedType(tycon, from :: to :: Nil) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Implicits.scala]: This could be:
```suggestion
              case app @ AppliedType(tycon, from :: rest) =>
```
The `rest` can be reused below instead of `to :: Nil`.
