### PR TITLE
Fix i14451

### LINKED ISSUE #14451: Extension methods ambiguity when type argument is added
Just adding a type argument causes the compiler to report ambiguity where there is none.

## Compiler version

v3.1.2-RC1

## Minimized code
https://scastie.scala-lang.org/cI1XmUISRwmnIqc8rOThSw

```Scala
class Foo

extension (dfVal: Foo)
  def prevOK(step: Int): Foo = ???
  def prevOK: Foo = ???
val ok = (new Foo).prevOK

extension (dfVal: Foo)
  def prevErr[S <: Int](step: S): Foo = ???
  def prevErr: Foo = ???
val err = (new Foo).prevErr
```

## Output

```scala
value prevErr is not a member of Playground.Foo.
Extension methods were tried, but could not be fully constructed:

    Playground.prevErr(new Playground.Foo())

    prevErr(new Playground.Foo())    failed with

        Ambiguous overload. The overloaded alternatives of method prevErr in object Playground with types
         (dfVal: Playground.Foo): Playground.Foo
         (dfVal: Playground.Foo): [S <: Int](step: S): Playground.Foo
        both match arguments (Playground.Foo)
```

## Expectation
No error.

### PR DESCRIPTION
**Pull request by Sporarum**
Fixes #14451

Implicitly assumed type clauses could only be at the beginning, which is wrong since:
```scala
extension (x: Int) def foo[T](y: T) = ???
```
de-sugars to something like:
```scala
def foo(x: Int)[T](y: T) = ???
```

To fix it, I implement `stripInferrable`, a variant of `stripImplicit` which also drops type clauses, and use it in `resultIsMethod`
I suspect the other uses of `stripImplicit` could be simplified, or even fixed (assuming they make the same mistake as `resultIsMethod`), by using `stripInferrable`

### CODE REVIEW

**Review by sjrd — APPROVED** [review]
AFAICT, this looks good to me.

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -2042,7 +2052,7 @@ trait Applications extends Compatibility {
       skip(alt.widen)
 
     def resultIsMethod(tp: Type): Boolean = tp.widen.stripPoly match
```
Comment (Sporarum) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:2054]:
```suggestion
    def resultIsMethod(tp: Type): Boolean = tp.widen match
```

Comment (Sporarum) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:2054]: Update:
The above suggestion is wrong 
As the `.stripPoly` is there to ensure we "apply" the method to one set or arguments, and look at what remains

**Review by sjrd — APPROVED** [review]
