### PR TITLE
Use tree checker in macros

### LINKED ISSUE #15779: Extracting contravariant type parameter in match breaks a quote
## Compiler version

3.2.0-RC3 and earlier

## Minimized code

Encoder.scala
```scala
import scala.quoted._
import scala.deriving.Mirror

trait Encoder[-A]

trait PrimitiveEncoder[A] extends Encoder[A]

given intOpt: PrimitiveEncoder[Option[Int]] with {}
  
given primitiveNotNull[T](using e: Encoder[Option[T]]): PrimitiveEncoder[T] =
  new PrimitiveEncoder[T] {}

transparent inline given fromMirror[A]: Any = ${ fromMirrorImpl[A] }

def fromMirrorImpl[A : Type](using q: Quotes): Expr[Any] =
  Expr.summon[Mirror.Of[A]].get match
    case '{ ${mirror}: Mirror.ProductOf[A] { type MirroredElemTypes = elementTypes } } =>
      val encoder = Type.of[elementTypes] match
        case '[tpe *: EmptyTuple] =>
          Expr.summon[Encoder[tpe]].get

      encoder match
        case '{ ${encoder}: Encoder[tpe] } => println("AAA")
        case _ => println("BBB")

      encoder match
        case '{ ${encoder}: Encoder[tpe] } => println("AAA")
        case _ => println("BBB")

      encoder
```

Main.scala
```scala
case class JustInt(i: Int)

val x = fromMirror[JustInt]
```

## Output

```scala
AAA
BBB
java.lang.AssertionError: assertion failed: unresolved symbols: type tpe (line 22) #29193 when pickling Main.scala while compiling Encoder.scala, Main.scala
[error] ## Exception when compiling 2 sources to dotty-test/tmp3/target/scala-3.2.0-RC3/classes
[error] java.lang.AssertionError: assertion failed: unresolved symbols: type tpe (line 22) #29193 when pickling Main.scala
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:783)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$1$$anonfun$1(Pickler.scala:72)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$1(Pickler.scala:110)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.transform.Pickler.run(Pickler.scala:110)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:311)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:312)
[error] dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:115)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:234)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:245)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:253)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:262)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:262)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:192)
[error] dotty.tools.dotc.Driver.finish(Driver.scala:56)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] stack trace is suppressed; run last tmp3 / Compile / compileIncremental for the full output
[error] (tmp3 / Compile / compileIncremental) java.lang.AssertionError: assertion failed: unresolved symbols: type tpe (line 22) #29193 when pickling Main.scala
```

## Expectation

This should compile successfully, without breaking the pickler.

It looks like an attempt to extract a type parameter from the type of a quoted expression in a match somehow mutates the quote: The first occurrence of
```scala
      encoder match
        case '{ ${encoder}: Encoder[tpe] } => println("AAA")
        case _ => println("BBB")
```
prints `AAA`, the second one prints `BBB`.

On the other hand nothing breaks if at least one of the modifications below is performed:
- `Encoder` is declared as invariant
- `PrimitiveEncoder` is declared as contravariant
- the definition of `JustInt` gets moved to `Encoder.scala`
- `case '{ ${encoder}: Encoder[tpe] } => println("AAA")` branch gets removed from both matches
- the return value of `fromMirrorImpl` is something else than `encoder`

### LINKED ISSUE #16636: Macro changes semantics based on how you refer to a type located in an `object` after a seemingly innocent quote match
## Compiler version
3.2.1, 3.3.0-RC1-bin-20230106-d49c2d9-NIGHTLY

## Minimized code

```Scala
// file: ReproTransformer.scala

import scala.quoted.*

trait ReproTransformer[A, B] {
  def transform(from: A): B
}

object ReproTransformer {
  final class Identity[A, B >: A] extends ReproTransformer[A, B] {
    def transform(from: A): B = from
  }

  given identity[A, B >: A]: Identity[A, B] = Identity[A, B]

  inline def getTransformer[A, B]: ReproTransformer[A, B] = ${ getTransformerMacro[A, B] }

  def getTransformerMacro[A, B](using quotes: Quotes, A: Type[A], B: Type[B]) = {
    import quotes.reflect.*

    val transformer = (A -> B) match {
      case '[a] -> '[b] => 
        val summoned = Expr.summon[ReproTransformer[a, b]].get
// ----------- INTERESTING STUFF STARTS HERE
        summoned match {
          case '{ $t: ReproTransformer[src, dest] } => t
        }
// ----------- INTERESTING STUFF ENDS HERE
    }
    transformer.asExprOf[ReproTransformer[A, B]]
  }
}
```

```scala
// file: usage.scala

object A {
  case class AnotherCaseClass(name: String)

  val errorsOut1 = ReproTransformer.getTransformer[A.AnotherCaseClass, AnotherCaseClass]
  val errorsOu2 = ReproTransformer.getTransformer[AnotherCaseClass, A.AnotherCaseClass]

  val works1 = ReproTransformer.getTransformer[A.AnotherCaseClass, A.AnotherCaseClass]
  val works2 = ReproTransformer.getTransformer[AnotherCaseClass, AnotherCaseClass]
}


```

## Output

```bash
[error] -- Error: /home/aleksander/repos/ducktape/ducktape/src/main/scala/io/github/arainko/ducktape/usage.scala:8:50 
[error]  8 |  val errorsOut1 = ReproTransformer.getTransformer[A.AnotherCaseClass, AnotherCaseClass]
[error]    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.Exception: Expr cast exception: io.github.arainko.ducktape.ReproTransformer.identity[io.github.arainko.ducktape.A.AnotherCaseClass, B]
[error]    |of type: io.github.arainko.ducktape.ReproTransformer.Identity[io.github.arainko.ducktape.A.AnotherCaseClass, B]
[error]    |did not conform to type: io.github.arainko.ducktape.ReproTransformer[io.github.arainko.ducktape.A.AnotherCaseClass, io.github.arainko.ducktape.A.AnotherCaseClass]
[error]    |
[error]    |    at scala.quoted.runtime.impl.QuotesImpl.asExprOf(QuotesImpl.scala:73)
[error]    |    at io.github.arainko.ducktape.ReproTransformer$.getTransformerMacro(ReproTransformer.scala:30)
[error]    |
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from ReproTransformer.scala:16
[error] 16 |  inline def getTransformer[A, B]: ReproTransformer[A, B] = ${ getTransformerMacro[A, B] }
[error]    |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     ----------------------------------------------------------------------------
```

## Expectation

An additional (irrefutable?) quote match shouldn't change the semantics of the macro and the way you refer to a type located in an `object` shouldn't matter.

If you change the implementation of `getTransformerMacro` to not include the additional pattern match:
```scala
 def getTransformerMacro[A, B](using quotes: Quotes, A: Type[A], B: Type[B]) = {
    import quotes.reflect.*

    val transformer = (A -> B) match {
      case '[a] -> '[b] => 
        val summoned = Expr.summon[ReproTransformer[a, b]].get
// ----------- INTERESTING STUFF STARTS HERE
        summoned // return the summoned Expr straight away without additional matches
// ----------- INTERESTING ends STARTS HERE
    }
    transformer.asExprOf[ReproTransformer[A, B]]
  }
```
both of the usages compile properly.

### Context
This issue was brought up by one of the users of [ducktape](https://github.com/arainko/ducktape) here: https://github.com/arainko/ducktape/issues/26, which was subsequently fixed here: https://github.com/arainko/ducktape/pull/27

### PR DESCRIPTION
**Pull request by nicolasstucki**
Trees are only checked if `-Xcheck-macros` is enabled.

Fixes:
 - Add missing positions to `{ValDef,Bind}.apply`
 - Inline by-name ascribed param
 - Unbound type variables after implicit search
 - Fixes #15779
 - Fixes #16636

### CODE REVIEW

**Comment by nicolasstucki** [comment]
We should test this on the extended community build before merging.

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 1]
```diff
@@ -724,4 +712,52 @@ object TreeChecker {
...
+    override def assertDefined(tree: untpd.Tree)(using Context): Unit =
+      // Only check definitions nested in the local tree
+      if nowDefinedSyms.contains(tree.symbol.maybeOwner) then
+        super.assertDefined(tree)
+
+  def checkMacroGeneratedTree(original: tpd.Tree, expansion: tpd.Tree)(using Context): Unit =
+    if ctx.settings.XcheckMacros.value then
+      val checkingCtx = ctx
+        .fresh
+        .addMode(Mode.ImplicitsEnabled)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:727]: Do we really need to generate implicits when checking trees?

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 2]
```diff
@@ -2395,7 +2395,12 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
 
     object Implicits extends ImplicitsModule:
       def search(tpe: TypeRepr): ImplicitSearchResult =
-        ctx.typer.inferImplicitArg(tpe, Position.ofMacroExpansion.span)
+        import tpd.TreeOps
+        val implicitTree = ctx.typer.inferImplicitArg(tpe, Position.ofMacroExpansion.span)
+        // Make sure that we do not have any uninstantiated type variables.
+        // See tests/pos-macros/exprSummonWithTypeVar with -Xcheck-macros.
+        implicitTree.foreachSubTree(tree => dotc.typer.Inferencing.fullyDefinedType(tree.tpe, "", tree))
```
Comment (smarter) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2402]: foreachSubTree is expensive.  You could use typer.interpolateTypeVars instead (probably with `pt = WildcardType` and `locked = ctx.typerState.ownedVars`).

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2402]: `interpolateTypeVars` did not work.

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:727]: I followed the original tree checker https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/TreeChecker.scala#L137.

I will try removing both.

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2402]: I there a way to make `inferImplicitArg` resolve all type variables that it inserts?

Comment (smarter) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2402]: Try defining val locked = ctx.typerState.ownedVars before the call to inferImplicitArg, so that variables created by it can be instantiated when you pass locked to interpolateTypeVars

Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala:2402]: It did not work either. Note that the `ownedVars` of this context are empty before and after the call to `inferImplicitArg`. The type variable in introduced within `inferImplicitArg`.

File: tests/neg-macros/annot-mod-top-method-add-top-method/Macro_1.scala [hunk 3]
```diff
@@ -9,5 +9,5 @@ class addTopLevelMethodOutsidePackageObject extends MacroAnnotation:
     import quotes.reflect._
     val methType = MethodType(Nil)(_ => Nil, _ => TypeRepr.of[Int])
     val methSym = Symbol.newMethod(Symbol.spliceOwner.owner, Symbol.freshName("toLevelMethod"), methType, Flags.EmptyFlags, Symbol.noSymbol)
-    val methDef = ValDef(methSym, Some(Literal(IntConstant(1))))
+    val methDef = DefDef(methSym, _ => Some(Literal(IntConstant(1))))
```
Comment (nicolasstucki) [inline tests/neg-macros/annot-mod-top-method-add-top-method/Macro_1.scala:12]: After rebasing, the check caught this unintended bug in this neg test.

**Review by smarter — APPROVED** [review]
