### PR TITLE
fix #2166: unpickling of shared CaseDef

### LINKED ISSUE #2166: Inlined pattern matching won't unpickle
```scala
object Test {
  @inline def f = "" match { case _ => false }

  def main(args: Array[String]): Unit = f
}
```

```bash
$ sbt "run -Ytest-pickler -Ystop-after:pickler /home/olivier/a.scala"
[...]
$ cat after-pickling.txt
[cannot display due to java.lang.AssertionError: assertion failed: Addr(134) Addr(138) Addr(140) MATCH, raw string = dotty.tools.dotc.printing.Formatting$StringFormatter@37f8bb67]
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #2166: the unpickling of CaseDef should take care of SHARED trees.

### CODE REVIEW

**Comment by smarter** [comment]
Missing test case?

**Comment by liufengyun** [comment]
The pickling tests pass, but the bootstrap pickling failed. Need to investigate further.

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala [hunk 1]
```diff
@@ -1062,7 +1062,13 @@ class TreeUnpickler(reader: TastyReader, tastyName: TastyName.Table, posUnpickle
       }
 
     def readCases(end: Addr)(implicit ctx: Context): List[CaseDef] =
-      collectWhile(nextByte == CASEDEF && currentAddr != end) { readCase()(ctx.fresh.setNewScope) }
+      collectWhile(nextByte == CASEDEF | nextByte == SHARED && currentAddr != end) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: I think you want `||`, not `|`

Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: And you also need to put parens in the correct place because `&&` has higher precedence:
```scala
(nextByte == CASEDEF || nextByte == SHARED) && currentAddr != end)
```

Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: Thanks a lot @smarter , I owe you a beer 👍  I will no longer claim I can write Scala in my CV :)

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala [hunk 2]
```diff
@@ -1062,7 +1062,13 @@ class TreeUnpickler(reader: TastyReader, tastyName: TastyName.Table, posUnpickle
       }
 
     def readCases(end: Addr)(implicit ctx: Context): List[CaseDef] =
-      collectWhile(nextByte == CASEDEF && currentAddr != end) { readCase()(ctx.fresh.setNewScope) }
+      collectWhile((nextByte == CASEDEF || nextByte == SHARED) && currentAddr != end) {
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: You can simply use `nextUnsharedTag` for this. 

    collectWhile(nextUnsharedTag == CASEDEF && currentAddr != end) { readCase()(ctx.fresh.setNewScope) }

**Comment by odersky** [comment]
Sorry, that was a wrong comment. In fact your original version is the correct one.
