### PR TITLE
Fix #5386: Normalize unary operator expressions

### LINKED ISSUE #5386: Crash when selecting ! on block
```scala
object Test {
  inline def assert(assertion: => Boolean): Boolean = !assertion

  def test = assert({println("Boom");true})
}
```

```scala
java.lang.AssertionError: NoDenotation.owner while compiling tests/run-separate-compilation/gestalt-innerclassmacro-inline/InnerClassMacro_1.scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
	at dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:1931)
	at dotty.tools.dotc.transform.Erasure$Typer.mapOwner$1(Erasure.scala:408)
	at dotty.tools.dotc.transform.Erasure$Typer.typedSelect(Erasure.scala:412)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1863)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1936)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1968)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
```

### PR DESCRIPTION
**Pull request by odersky**
A unary operator expression `pre.op` where `op` is one of `+`, `-`, `~`, `!`
that has a constant type `ConstantType(v)` but that is not a constant expression
(i.e. `pre` has side-effects) is translated to

    { pre; v }

This avoids the situation where we have a Select node which does not have a symbol.

### CODE REVIEW

**Comment by odersky** [comment]
Derived from biboudis:fix-#5386. Note: Always do PRs from staging then others can work on them.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -485,11 +485,27 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
...
    */
   def constToLiteral(tree: Tree)(implicit ctx: Context): Tree = {
     val tree1 = ConstFold(tree)
     tree1.tpe.widenTermRefExpr match {
-      case ConstantType(value) if isIdempotentExpr(tree1) => Literal(value)
+      case ConstantType(value) =>
+        if (isIdempotentExpr(tree1)) Literal(value)
+        else tree1 match {
+          case Select(qual, _) if tree1.tpe.isInstanceOf[ConstantType] =>
+            // it's a unary operator; Simplify `pre.op` to `{ pre; v }` where `v` is the value of `pre.op`
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: If we loose op before pickling, then it'll be missing from the IDE in go-to-definition/find-all-references

Comment (smarter) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: Also I don't really get what's special about unary operators here ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: They do not get a symbol. So nothing is lost when doing the transform.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: but why do they not get a symbol ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: Because constant folding replaces the type with a ConstantType.

File: tests/pos/i5386.scala [hunk 2]
```diff
@@ -22,4 +23,12 @@ object Test {
   { println("1"); 1 } + { println("2"); 2}
 
   !(try true finally{()})
+
+
+  class C {
+    def foo: 1 = 1
```
Comment (smarter) [inline tests/pos/i5386.scala]: To make sure this works as expected, the body of this method should contain a print, and this test should be a run test with a check file with that print.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 3]
```diff
@@ -485,11 +485,27 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
...
    */
   def constToLiteral(tree: Tree)(implicit ctx: Context): Tree = {
     val tree1 = ConstFold(tree)
     tree1.tpe.widenTermRefExpr match {
-      case ConstantType(value) if isIdempotentExpr(tree1) => Literal(value)
+      case ConstantType(value) =>
+        if (isIdempotentExpr(tree1)) Literal(value)
+        else tree1 match {
+          case Select(qual, _) if tree1.tpe.isInstanceOf[ConstantType] =>
+            // it's a primitive unary operator; Simplify `pre.op` to `{ pre; v }` where `v` is the value of `pre.op`
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: How do we know that this a primitive unary operator and not a user-defined one here ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: A user defined operator would not have a `ConstantType` as a type. The test contains that case.

File: tests/pos/i5386.scala (hunk 2 above)
Comment (odersky) [reply tests/pos/i5386.scala]: OK, but somebody else should do that, please. I was not volunteering to take this on issue, but since it was blocked otherwise, had to step in. So I won't spend any more context switches on this.
