### PR TITLE
Fix #6635: Improve subtype tests for aliases and singleton types

### LINKED ISSUE #6635: b: a.type but a.A != b.A
Even if e2: e1.type, e1.A = e2.A can still fail, in the same way, in Scala and Dotty — as of Dotty 0.16.0-bin-20190606-c46553a-NIGHTLY: 
https://gist.github.com/Blaisorblade/3e5a1102c0699f05f1c11333d785a077

See `castTestFail*`. We need in fact `e2: e1.type & something`, but even then the problem doesn't always appear.
Part of the problem is triggered `e2.A` is aliased, because then `e.A` can be evaluated too eagerly; it seems Dotty tries to correct for that, but not robustly enough.
 
```scala
object Test {
  abstract class ExprBase { s =>
    type A
  }

  abstract class Lit extends ExprBase { s =>
    type A = Int
    val n: A
  }

  abstract class LitU extends ExprBase { s =>
    type A <: Int
    val n: A
  }

  abstract class LitL extends ExprBase { s =>
    type A <: Int
    val n: A
  }

  def castTest1(e1: ExprBase)(e2: e1.type)(x: e1.A): e2.A = x
  def castTest2(e1: ExprBase { type A = Int })(e2: e1.type)(x: e1.A): e2.A = x
  def castTest3(e1: ExprBase)(e2: ExprBase with e1.type)(x: e2.A): e1.A = x

  def castTest4(e1: ExprBase { type A = Int })(e2: ExprBase with e1.type)(x: e2.A): e1.A = x

  def castTest5a(e1: ExprBase)(e2: LitU with e1.type)(x: e2.A): e1.A = x
  def castTest5b(e1: ExprBase)(e2: LitL with e1.type)(x: e2.A): e1.A = x

  //fail:
  def castTestFail1(e1: ExprBase)(e2: Lit with e1.type)(x: e2.A): e1.A = x // this is like castTest5a/b, but with Lit instead of LitU/LitL
  // the other direction never works:
  def castTestFail2a(e1: ExprBase)(e2: Lit with e1.type)(x: e1.A): e2.A = x
  def castTestFail2b(e1: ExprBase)(e2: LitL with e1.type)(x: e1.A): e2.A = x
  def castTestFail2c(e1: ExprBase)(e2: LitU with e1.type)(x: e1.A): e2.A = x

  // the problem isn't about order of intersections.
  def castTestFail2bFlip(e1: ExprBase)(e2: e1.type with LitL)(x: e1.A): e2.A = x
  def castTestFail2cFlip(e1: ExprBase)(e2: e1.type with LitU)(x: e1.A): e2.A = x

  def castTestFail3(e1: ExprBase)(e2: Lit with e1.type)(x: e1.A): e2.A = {
    val y: e1.type with e2.type = e2
    val z = x: y.A
    z
  }
}
```

Errors
```
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:31:73
[error] 31 |  def castTestFail1(e1: ExprBase)(e2: Lit with e1.type)(x: e2.A): e1.A = x // this is like castTest5a/b, but with Lit instead of LitU/LitL
[error]    |                                                                         ^
[error]    |            Found:    e2.A(x)
[error]    |            Required: e1.A'
[error]    |
[error]    |            where:    A  is a type in class Lit which is an alias of Int
[error]    |                      A' is a type in class ExprBase
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:33:74
[error] 33 |  def castTestFail2a(e1: ExprBase)(e2: Lit with e1.type)(x: e1.A): e2.A = x
[error]    |                                                                          ^
[error]    |            Found:    e1.A(x)
[error]    |            Required: e2.A'
[error]    |
[error]    |            where:    A  is a type in class ExprBase
[error]    |                      A' is a type in class Lit which is an alias of Int
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:34:75
[error] 34 |  def castTestFail2b(e1: ExprBase)(e2: LitL with e1.type)(x: e1.A): e2.A = x
[error]    |                                                                           ^
[error]    |                 Found:    e1.A(x)
[error]    |                 Required: e2.A'
[error]    |
[error]    |                 where:    A  is a type in class ExprBase
[error]    |                           A' is a type in class LitL with bounds <: Int
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:35:75
[error] 35 |  def castTestFail2c(e1: ExprBase)(e2: LitU with e1.type)(x: e1.A): e2.A = x
[error]    |                                                                           ^
[error]    |                 Found:    e1.A(x)
[error]    |                 Required: e2.A'
[error]    |
[error]    |                 where:    A  is a type in class ExprBase
[error]    |                           A' is a type in class LitU with bounds <: Int
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:38:79
[error] 38 |  def castTestFail2bFlip(e1: ExprBase)(e2: e1.type with LitL)(x: e1.A): e2.A = x
[error]    |                                                                               ^
[error]    |                 Found:    e1.A(x)
[error]    |                 Required: e2.A'
[error]    |
[error]    |                 where:    A  is a type in class ExprBase
[error]    |                           A' is a type in class LitL with bounds <: Int
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:39:79
[error] 39 |  def castTestFail2cFlip(e1: ExprBase)(e2: e1.type with LitU)(x: e1.A): e2.A = x
[error]    |                                                                               ^
[error]    |                 Found:    e1.A(x)
[error]    |                 Required: e2.A'
[error]    |
[error]    |                 where:    A  is a type in class ExprBase
[error]    |                           A' is a type in class LitU with bounds <: Int
[error] -- [E007] Type Mismatch Error: /Users/pgiarrusso/git/Papers/scala19_gadt_code/src/main/scala/openGADTs.scala:43:12
[error] 43 |    val z = x: y.A
[error]    |            ^
[error]    |            Found:    e1.A(x)
[error]    |            Required: y.A'
[error]    |
[error]    |            where:    A  is a type in class ExprBase
[error]    |                      A' is a type in class Lit which is an alias of Int
[error] 7 errors found
```

### PR DESCRIPTION
**Pull request by odersky**
1. backtrack in more cases when we fail after dealiasing
 2. fall back to atoms comparisons when comparing two singleton types

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by Blaisorblade** [comment]
Cool that Dotty can fix this! Needing backtracking is unfortunate but easy, and the alternative I had imagined (union-find) requires much more work, so that's cool...

**Comment by odersky** [comment]
@Blaisorblade Yes, I fear that union-find would be difficult to make fast in these situations.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -753,20 +744,16 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+              tp2.info.widenExpr.dealias match
+                case tp2i: SingletonType => recur(tp1, tp2i)
+                case _ => false
             }
-          case _ =>
-            false
-        }
-        isNewSubType(tp1.underlying.widenExpr) || comparePaths
+          case _ => false
+        comparePaths || isNewSubType(tp1.underlying.widenExpr)
```
Comment (AleksanderBG) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Discussed this change in-person w/ Martin: changing the order of arguments here is solely a performance optimization, not an actual change to logic.

Comment (hepin1989) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: `a || b` == `b || a`, so yes.

Comment (AleksanderBG) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: @hepin1989 thank you for your astute observation! I was thinking about things such as the old RHS assuming the old LHS already handled some type shape, or that we do some evil tricks when loading code from Tasty and the check on new LHS is necessary so that the new RHS doesn't blow up, but I suppose it never hurts to be reminded of elementary laws of Boolean algebra.

Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Or otherwise, `a || b` and `b || a` differ when `a` and `b` are not pure :-)

**Comment by anatoliykmetyuk** [comment]
What's the status on this? This one is the only blocker for the release.

**Comment by AleksanderBG** [comment]
@anatoliykmetyuk I thought that Martin also requested Olivier's review. If not, you can just merge this.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -233,54 +233,45 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
...
+                thirdTryNamed(tp2)
+              else
+                (  (tp1.name eq tp2.name)
+                && tp1.isMemberRef
+                && tp2.isMemberRef
+                && isSubType(tp1.prefix, tp2.prefix)
+                && tp1.signature == tp2.signature
+                && !(sym1.isClass && sym2.isClass)  // class types don't subtype each other
+                ) ||
+                thirdTryNamed(tp2)
```
Comment (hepin1989) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: introduce an explicit boolean return?

**Comment by anatoliykmetyuk** [comment]
> @anatoliykmetyuk I thought that Martin also requested Olivier's review. If not, you can just merge this.

/cc @OlivierBlanvillain

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -233,54 +233,45 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
 
     def firstTry: Boolean = tp2 match {
       case tp2: NamedType =>
-        def compareNamed(tp1: Type, tp2: NamedType): Boolean = {
+        def compareNamed(tp1: Type, tp2: NamedType): Boolean =
           implicit val ctx: Context = this.ctx
-          tp2.info match {
+          val info2 = tp2.info
```
Comment (OlivierBlanvillain) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: This binding doesn't seem necessary
