### PR TITLE
Always load REPL classes in macros including the output directory

### LINKED ISSUE #15104: Macro implementation in REPL cannot be non-toplevel
## Compiler version

3.2.0-RC1-bin-20220503-aff1e11-NIGHTLY

## Minimized code

In REPL paste the two snippets below one after another

```scala
import scala.quoted.*

object Foo:
  def macroImpl(using Quotes) = Expr(1)

inline def foo = ${ Foo.macroImpl }
```

```scala
def x = foo
```

## Output

```scala
-- Error: ----------------------------------------------------------------------
1 |def x = foo
  |        ^^^
  |        Could not find class rs$line$1$Foo$ in classpath
  |-----------------------------------------------------------------------------
  |Inline stack trace
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  |This location contains code that was inlined from rs$line$1:6
6 |inline def foo = ${ Foo.macroImpl }
  |                 ^^^^^^^^^^^^^^^^^^
   -----------------------------------------------------------------------------
1 error found
```

## Expectation

There should be no error, just like when `macroImpl` is a toplevel definition, e.g.
```scala
import scala.quoted.*

def macroImpl(using Quotes) = Expr(1)

inline def foo = ${ macroImpl }
```

```scala
def x = foo
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #15104

Also re-enable `compiler/test-resources/repl-macros` tests.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/quoted/Interpreter.scala [hunk 1]
```diff
@@ -32,10 +32,15 @@ import dotty.tools.dotc.reporting.Message
...
 
 /** Tree interpreter for metaprogramming constructs */
-class Interpreter(pos: SrcPos, classLoader: ClassLoader)(using Context):
+class Interpreter(pos: SrcPos, classLoader0: ClassLoader)(using Context):
   import Interpreter._
   import tpd._
 
+  val classLoader =
+    if ctx.owner.topLevelClass.name.startsWith(str.REPL_SESSION_LINE) then
+        new AbstractFileClassLoader(ctx.settings.outputDir.value, classLoader0)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/quoted/Interpreter.scala:41]: Shouldn't the REPL take care of passing the correct classloader to the Interpreter?

**Review by smarter — APPROVED** [review]
