### PR TITLE
Fix purity check for val inside of object

### LINKED ISSUE #17317: False positive dead code elimination on pure expressions
## Compiler version

3.3.0-RC3, 3.2.2

### Sample 1

```scala
//> using scala "3.2.2"

package object foo {

  object HelloGen {
    println("hello world")
  }

  val Hello = HelloGen
}

import foo.Hello

object Main {

  def main(args: Array[String]): Unit = Hello: Unit
}

```

### Sample 2

Instead of a package object, use a top-level definition.

```scala
//> using scala "3.2.2"


object HelloGen {
  println("hello world")
}

val Hello = HelloGen


object Main {

  def main(args: Array[String]): Unit = Hello: Unit
}
```

## Output

```scala
Compiling project (Scala 3.3.0-RC3, JVM)
[warn] ./main.scala:13:5
[warn] A pure expression does nothing in statement position; you may be omitting necessary parentheses
[warn]     Hello: Unit
[warn]     ^^^^^
Compiled project (Scala 3.3.0-RC3, JVM)
```

## Expectation

```scala
Compiling project (Scala 3.3.0-RC3, JVM)
Compiled project (Scala 3.3.0-RC3, JVM)
hello world
```

Notes:

1. Here's javap verbose for `main`:

```
public void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=0, locals=2, args_size=2
         0: return
      LineNumberTable:
        line 16: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       1     0  this   LMain$;
            0       1     1  args   [Ljava/lang/String;
    Signature: #27                          // ([Ljava/lang/String;)V
    MethodParameters:
      Name                           Flags
      args                           final
```

Notably the code is just a `return`, as the call is erased from the output.

2. This doesn't happen in Scala 2.13 or if you fully qualify `foo.Hello`.

### PR DESCRIPTION
**Pull request by aherlihy**
Fixes #17317

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -578,8 +578,9 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
       sym.owner.isPrimitiveValueClass
       || sym.owner == defn.StringClass
       || defn.pureMethods.contains(sym)
+
     tree.tpe.isInstanceOf[ConstantType] && tree.symbol != NoSymbol && isKnownPureOp(tree.symbol) // A constant expression with pure arguments is pure.
-    || fn.symbol.isStableMember && !fn.symbol.is(Lazy)  // constructors of no-inits classes are stable
+    || fn.symbol.isStableMember && fn.symbol.isConstructor // constructors of no-inits classes are stable
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:583]: I was a bit confused by what was going on here, but after reading https://github.com/lampepfl/dotty/commit/471fcd9e198204f37995f56c4eb4c5ec10122add it seems the issue is that:
1. Constructors of traits that do not have side-effects will return true to isStableMember
2. Other members might return true just because they're stable (always return the same value) even if they do have side-effects. The previous check excluding lazy was not broad enough to handle this (in fact, arbitrary methods can be marked stable with `scala.annotation.unchecked.uncheckedStable`)

If I understand https://github.com/lampepfl/dotty/commit/471fcd9e198204f37995f56c4eb4c5ec10122add correctly, I think this check is equivalent to:
```suggestion
    || fn.symbol.isConstructor && fn.symbol.owner.is(NoInits)
```
Which is more obviously correct. @sjrd: Can you confirm my understanding here?

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:583]: > I think this check is equivalent to:

I don't think so, because the condition required to set the constructor as stable is not just `fn.symbol.owner.is(NoInits)` but

```scala
if myFlags.is(Trait) then myFlags.is(NoInits) else isNoInitsRealClass
```

where

```scala
    def isNoInitsRealClass(using Context): Boolean =
      isRealClass &&
      (asClass.baseClasses.forall(_.is(NoInits)) || defn.isAssuredNoInits(symbol))
```

So `isStableMember` is the efficient way to verify that.

Perhaps we can `fn.symbol.isStableMember && fn.symbol.isConstructor` into a `isStableConstructor` method, and then throw this detail in its docs.  Or we can do that in situ here.

**Review by sjrd — APPROVED** [review]
