### PR TITLE
Fix #12241: Make space computation lazy

### LINKED ISSUE #12241: Compiler loops when compiling a pattern match with a large number of patterns
## Compiler version

3.0.0-RC3

## Minimized code

That's as far as I've been able to minimize. Removing some of the cases, or matching against a single `EndpointInput`, not a tuple, makes the code compile.

I suspect it's a loop, as I can wait for a couple of minutes and compilation doesn't complete, CPU usage is high.

I'm running compilation through sbt.

```scala
sealed trait EndpointInput[T]

object EndpointInput {
  case class Pair[T]() extends EndpointInput[T]
  case class MappedPair[T]() extends EndpointInput[T]
  case class Pair2[T]() extends EndpointInput[T]
  case class MappedPair2[T]() extends EndpointInput[T]
  case class FixedMethod[T]() extends EndpointInput[T]
  case class FixedPath[T]() extends EndpointInput[T]
  case class PathCapture[T]() extends EndpointInput[T]
  case class PathsCapture[T]() extends EndpointInput[T]
  case class Query[T]() extends EndpointInput[T]
  case class QueryParams[T]() extends EndpointInput[T]
  case class Cookie[T]() extends EndpointInput[T]
  case class ExtractFromRequest[T]() extends EndpointInput[T]
  case class ApiKey[T]() extends EndpointInput[T]
  case class Http[T]() extends EndpointInput[T]
  case class Body[R, T]() extends EndpointInput[T]
  case class FixedHeader[T]() extends EndpointInput[T]
  case class Header[T]() extends EndpointInput[T]
  case class Headers[T]() extends EndpointInput[T]
  case class StatusCode[T]() extends EndpointInput[T]
  case class Empty[T]() extends EndpointInput[T]
}

object Test extends App {
  import EndpointInput._

  def compare(left: EndpointInput[_], right: EndpointInput[_]): Boolean =
    (left, right) match {
      case (Pair(), Pair()) => true
      case (MappedPair(), MappedPair()) => true
      case (Pair2(), Pair2()) => true
      case (MappedPair2(), MappedPair2()) => true
      case (FixedMethod(), FixedMethod()) => true
      case (FixedPath(), FixedPath()) => true
      case (PathCapture(), PathCapture()) => true
      case (PathsCapture(), PathsCapture()) => true
      case (Query(), Query()) => true
      case (QueryParams(), QueryParams()) => true
      case (Cookie(), Cookie()) => true
      case (ExtractFromRequest(), ExtractFromRequest()) => true
      case (ApiKey(), ApiKey()) => true
      case (Http(), Http()) => true
      case (Body(), Body()) => true
      case (FixedHeader(), FixedHeader()) => true
      case (Header(), Header()) => true
      case (Headers(), Headers()) => true
      case (StatusCode(), StatusCode()) => true
      case (_, _) => false
    }
}
```

## Output

Fragment of the stack trace: https://gist.github.com/adamw/d06722ab6826aad108beca979065a90b

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #12241: Make space computation lazy

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance with #exhaustivity please

**Comment by liufengyun** [comment]
test performance with #exhaustivity please: 16a622f 16a622f 16a622f

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -113,45 +113,37 @@ trait SpaceLogic {
...
   })
 
+  /** Remove a space if it's a subspace of remaining spaces
+   *
+   *  Note: `dedup` will return the same result if the sequence >= 10
+   */
+  def dedup(spaces: Seq[Space])(using Context): Seq[Space] =
+    if (spaces.lengthCompare(1) <= 0 || spaces.lengthCompare(10) >= 0) spaces
+    else {
+      val res = spaces.map(sp => (sp, spaces.filter(_ ne sp))).find {
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:140]: I wonder if it would help performance if we do not compute `spaces.filter(_ ne sp)` eagerly.

**Review by nicolasstucki — APPROVED** [review]
Otherwise, LGTM

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:140]: Here `spaces` has a size < 10, so should not matter much.

**Comment by liufengyun** [comment]
The newly added test does get json data (from Chrom inspector):

``` json
[
[12271,"2021-04-29T12:36:56+0200","16a622fd1b",903.4235,846.695],
[12271,"2021-04-29T13:16:47+0200","16a622fd1b",871.691,831.192],
[12271,"2021-04-29T13:51:41+0200","16a622fd1b",955.0745,835.253],
[12271,"2021-04-29T14:26:22+0200","16a622fd1b",950.573,842.552]
]
```

The UI does not show them due to too few points (need to improve the JavaScript).
