### PR TITLE
Fix #6762: Add regression tests

### LINKED ISSUE #6762: Misleading error message for extension methods with implicits
## minimized code

```Scala
import scala.quoted._
import delegate scala.quoted._

type G[X]
case class Foo[T](x: T)
def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr})}
```

## expectation
An error message saying that the type of ` '{Foo(${word.toExpr})}` is incorrect: it is `Expr[Foo[String]]` whereas `Expr[Foo[G[String]]]` is expected. Instead, the error message is as follows:

```
[error] -- [E008] Member Not Found Error: /Users/anatolii/Projects/dotty/playground/macros/src/main/scala/playground/macros.scala:45:59
[error] 45 |  def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr})}
[error]    |                                                      ^^^^^^^^^^^
[error]    |      value toExpr is not a member of String.
[error]    |      An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |          quoted.ExprOps.toExpr[T](word)
[error] one error found
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: tests/neg/i6762.scala [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import scala.quoted.{_, given}
+
+type G[X]
+case class Foo[T](x: T)
+def f(word: String)(given QuoteContext): Expr[Foo[G[String]]] = '{Foo(${word.toExpr})} // error
```
Comment (anatoliykmetyuk) [inline tests/neg/i6762.scala]: Is `given QuoteContext` needed here? The original issue did not have this implicit parameter.

Comment (nicolasstucki) [reply tests/neg/i6762.scala]: Yes, there is a quote. the original issue is outdated.

Comment (nicolasstucki) [reply tests/neg/i6762.scala]: Without it there is an extra error about the missing QuoteContext
