### PR TITLE
Fix #5039: Handle null:_* as varargs parameter

### LINKED ISSUE #5039: Null expanded as a _* with Ycheck:all
```scala
// -Ycheck:all
class I0{List(null:_*)}
```
```scala
checking AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala after phase frontend
exception while typing List.apply[Nothing](null: Null) of class class dotty.tools.dotc.ast.Trees$Apply # 110
exception while typing class I0() extends Object() { 
  List.apply[Nothing](null: Null)
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 112
exception while typing package <empty> {
  class I0() extends Object() { 
    List.apply[Nothing](null: Null)
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 113
*** error while checking AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala after phase frontend ***
exception occurred while compiling AE-c00f7074d074a942f48e3e24845e7f7054b76b69.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: found:    Null
required: Nothing


tree = null: Null
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:38)
	at dotty.tools.dotc.transform.TreeChecker$Checker.adapt(TreeChecker.scala:460)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:312)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:664)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:664)
	at dotty.tools.dotc.typer.Applications$Application.$anonfun$4$$anonfun$1(Applications.scala:465)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.typer.Applications$Application.$anonfun$2(Applications.scala:465)
	at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:1568)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:465)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:256)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:565)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:663)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:723)
	at dotty.tools.dotc.typer.Applications.realApply$4$$anonfun$3(Applications.scala:748)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1984)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:759)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:794)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1818)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1869)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
```
AE-c00f7074d074a942f48e3e24845e7f7054b76b69

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -556,6 +556,8 @@ trait Applications extends Compatibility { self: Typer with Dynamic =>
             args match {
               case arg :: Nil if isVarArg(arg) =>
                 addTyped(arg, formal)
+              case Typed(Literal(Constant(null)), _) :: Nil =>
+                addTyped(args.head, formal)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala]: Note that I used `.head` because `args` is  of type `List[Arg]` and
```scala
  case (arg @ Typed(Literal(Constant(null)), _)) :: Nil =>
    addTyped(arg, formal)
```
would fail with 
```scala
[error] 560 |                addTyped(arg, formal)
[error]     |                         ^^^
[error]     |Found:    dotty.tools.dotc.ast.Trees.Typed[dotty.tools.dotc.ast.Trees.Untyped](arg)
[error]     |Required: Arg
```

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: What about just reject the code? We are moving towards null-safety, it seems it's better to reject. /cc: @abeln

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: We should not always reject it. We could pass it to a Java varargs. Not sure if someone actually uses this pattern for performance reasons.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: In Java it is legal to pass `null` as the actual array of the varargs https://coderanch.com/t/631441/java/Varargs-null

**Comment by nicolasstucki** [comment]
We fix the crash with this PR. We can add new null safety checks later when we integrate non billable types
