### PR TITLE
fix: look at the underlying of a TermRef for a getter

### LINKED ISSUE #24553: MIMA Binary compatibility breakage updating `export` of `val` from Scala 3.7.4 -> 3.8.0-RC1
## Compiler version

3.8.0-RC1 

## Minimized code

```scala
package foo
object Foo{
  val hello = 1337
  def main(args: Array[String]): Unit = println(hello)
}

export Foo.*
```

## Output

If you compile this code with 3.7.4 and 3.8.0-RC1 and run https://github.com/lightbend-labs/mima over the two jars, you get the following breakage report

```scala
Found 2 issue when checking against old
 * static method hello()Int in class foo.Foo#package has a different generic signature in current version, where it is ()Lscala/Function0<Ljava/lang/Object;>; rather than ()I. See https://github.com/lightbend-labs/mima#incompatiblesignatureproblem
   filter with: ProblemFilter.exclude[IncompatibleSignatureProblem]("foo.Foo#package.hello")
 * method hello()Int in object foo.Foo#package has a different generic signature in current version, where it is ()Lscala/Function0<Ljava/lang/Object;>; rather than ()I. See https://github.com/lightbend-labs/mima#incompatiblesignatureproblem
   filter with: ProblemFilter.exclude[IncompatibleSignatureProblem]("foo.Foo#package.hello")
```

Repro Zip:

[test 2.zip](https://github.com/user-attachments/files/23783677/test.2.zip)

Unpack and run `./mill mimaReportBinaryIssues`

## Expectation

I would expect upgrading a library from Scala 3.7.4 to Scala 3.8.0-RC1 would not cause any binary compatibility breakage, so that downstream code that was previously compiled against the 3.7.4 version of the project would not hit issues compiling against the 3.8.0-RC1 version of the project

TBH I'm not sure if this MIMA-reported error is a real error or if it is a false positive. If it is a false positive, feel free to close the issue and we can add a MIMA filter to turn off this reporting. But squinting at the error message, it seems Scala 3.8.0 is messing up the generic signature somehow, reporting it as `()Lscala/Function0<Ljava/lang/Object;>;` when it should be `()I`

I hit this when trying to update Mill to 3.8.0-RC1 https://github.com/com-lihaoyi/mill/pull/6242

### PR DESCRIPTION
**Pull request by hamzaremmal**
If the type of a `val` is a `TermRef`, generating the generic signature  based on the underlying type will produce the type `scala.Function0<underlying>`. The reason behind this is that during the `getters` phase, the same symbol will now refer to the getter where the type will be `=> <underlying>`. Since the `TermRef` originally intended to capture the underlying type of a `val`, we recover that information by directly checking the resultType of the getter.

Closes #24553

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -246,6 +246,16 @@ object GenericSignatures {
             jsig(erasedUnderlying, toplevel = toplevel, unboxedVCs = unboxedVCs)
           else typeParamSig(ref.paramName.lastPart)
 
+        case ref: TermRef if ref.symbol.isGetter =>
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:249]: Equivalent in `TypeErasure`:
https://github.com/scala/scala3/blob/fe49539352f1aed2e7395b12f4daebffcc12cf31/compiler/src/dotty/tools/dotc/core/TypeErasure.scala#L804-L806

File: tests/run/i24553.check [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+public final native java.lang.Class<?> java.lang.Object.getClass()
+public native int java.lang.Object.hashCode()
+public int Foo.hello()
+public final native void java.lang.Object.notify()
+public final native void java.lang.Object.notifyAll()
+public java.lang.String java.lang.Object.toString()
+public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
+public final void java.lang.Object.wait() throws java.lang.InterruptedException
+public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
+public int Foo.x()
```
Comment (hamzaremmal) [inline tests/run/i24553.check:11]: Before this fix, we would have gotten:

```java
public scala.Function0<java.lang.Object> Foo.x()
```
