### PR TITLE
Handle binding of beta reduced inlined lambdas 

### LINKED ISSUE #16374: Inline and beta reduction can generate incorrect `Inlined` trees
## Compiler version

3.2.1

## Minimized code

Compiling with `-Ycheck:all`

```Scala
def method(using String): String = ???

inline def inlineMethod(inline op: String => Unit)(using String): Unit =
  println(op(method))

def test(using String) =
  inlineMethod(c => ())
```

## Output

```scala
*** error while checking test.scala after phase inlining ***
java.util.NoSuchElementException: head of empty list while running Ycheck on tests.scala
exception occurred while compiling tests.scala
java.util.NoSuchElementException: head of empty list while compiling tests.scala
Exception in thread "main" java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:662)
        at scala.collection.immutable.Nil$.head(List.scala:661)
        at dotty.tools.dotc.transform.YCheckPositions$$anon$1.traverse(YCheckPositions.scala:45)
        ...
```

The tree is
```scala
def test(using x$1: String): Unit =
      {{ /* inlined from 
        inlineMethod(
          {
            def $anonfun(c: String): Unit = ()
            closure($anonfun)
          }
        )(x$1)
       */
        println(
          {{ /* inlined from outside */
            {
              val c$proxy1: String = method({{ /* inlined from outside */x$1}})
              ()
            }
          }}
        ):Unit
      }}
```

It seems we are adding an Inlined with no call when beta-reducing the lambda.

## Expectation

It should work. Beta reduction should not add this additional `Inlined` node, or it should balance it. Maybe the proxy should be in the `Inlined` bindings.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Handle all inline beta-reduction in the InlineReducer. All these
applications will contain `Inlined` nodes that need to be handled
without changing the nestedness of expressions in inlining scopes.

Fixes https://github.com/lampepfl/dotty/issues/16374

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala [hunk 1]
```diff
@@ -158,35 +158,46 @@ class InlineReducer(inliner: Inliner)(using Context):
...
+                substFrom = ddef.paramss.head.map(_.symbol),
+                substTo = argSyms)
+              Some(expander.transform(ddef.rhs))
+            case _ => None
+        case Block(stats, expr) if stats.forall(isPureBinding) =>
+          recur(expr).map(cpy.Block(cl)(stats, _))
+        case Inlined(call, bindings, expr) if bindings.forall(isPureBinding) =>
+          recur(expr).map(cpy.Inlined(cl)(call, bindings, _))
+        case Typed(expr, tpt) =>
+          recur(expr)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala:192]: Any reason we don't preserve the Typed node here?
```suggestion
          recur(expr).map(cpy.Typed(cl)(_, tpt))
```

**Review by smarter — APPROVED** [review]
Otherwise LGTM

File: compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/inlines/InlineReducer.scala:192]: It is intentional. This ascription is on the lambda and hence has the lambda type, but the result of this transformation has the type of the result of this lambda. Dropping it is the simplest option. We could attempt to add the ascription again on the result. This would be more complicated and would also prevent optimizations on constants. We also do the same in https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/BetaReduce.scala#L57-L58.
