### PR TITLE
Exhaustivity warnings on nested case classes

### LINKED ISSUE #13003: Missing exhaustivity when pattern matching on nested case classes
When pattern matching on a nested case class pattern like, `case One(Two(Some(...)))` the Scala 3 compiler does not detect the match as being non-exhaustive – unless option `-Ycheck-all-patmat` is given.

## Compiler version
I have tested on compiler version 3.0.2-RC1-bin-20210701-9f97b0b-NIGHTLY (as well as on 3.0.0 where even more cases go undetected.)

## Minimized code
Given this code…
```Scala
case class One(two: Two)
case class Two(o: Option[Int])

def matchOneTwo(one: One) = one match
    case One(Two(Some(i))) => "match!"

def matchTwo(two: Two) = two match
    case Two(Some(i)) => "match!"

def matchOO(oo: Option[Option[Int]]) = oo match
    case Some(Some(i)) => "match!"

def matchOOO(ooo: Option[Option[Option[Int]]]) = ooo match
    case Some(Some(Some(i))) => "match!"
```
…the compiler only emits warnings about non-exhaustive matches for `matchTwo()`, `matchOO()`, and `matchOOO()` but _not_ for `matchOneTwo()` – unless compiler option `-Ycheck-all-patmat` is given.

## Output
Without option `-Ycheck-all-patmat` the output is:

```
-- [E029] Pattern Match Exhaustivity Warning: /path/to/Example.scala:7:25 
7 |def matchTwo(two: Two) = two match
  |                         ^^^
  |                         match may not be exhaustive.
  |
  |                         It would fail on pattern case: Two(None)
-- [E029] Pattern Match Exhaustivity Warning: /path/to/Example.scala:10:39 
10 |def matchOO(oo: Option[Option[Int]]) = oo match
   |                                       ^^
   |                         match may not be exhaustive.
   |
   |                         It would fail on pattern case: None, Some(None)
-- [E029] Pattern Match Exhaustivity Warning: /path/to/Example.scala:13:49 
13 |def matchOOO(ooo: Option[Option[Option[Int]]]) = ooo match
   |                                                 ^^^
   |       match may not be exhaustive.
   |
   |       It would fail on pattern case: None, Some(None), Some(Some(None))
three warnings found
three warnings found
```

Adding compiler option `-Ycheck-all-patmat` causes the missing case to be detected:
```
4 |def matchOneTwo(one: One) = one match
  |                            ^^^
  |                            match may not be exhaustive.
  |
  |                            It would fail on pattern case: One(Two(None))
-- [E029] Pattern Match Exhaustivity Warning: /path/to/Example.scala:7:25 
```

However, from the description of the compiler option:
```
-Ycheck-all-patmat          Check exhaustivity and redundancy of all pattern
                            matching (used for testing the algorithm).
```
I would not expect this option to be one to use “in production” – I might be wrong here.

## Expectation
I would expect the compiler to detect all four cases without the use of compiler option `-Ycheck-all-patmat`.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #13003, by refixing #12485 (PR #12488).

Part of the issue is that isCheckable behaves differently under
-Ycheck-all-patmat and our tests only run under that flag.  So for
starters I added a test variant where that flag isn't used.  I'd like to
understand why that flag exists to see if we could remove it from
guarding the logic and the tests.

### CODE REVIEW

**Comment by bishabosha** [comment]
check performance please

**Comment by bishabosha** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -815,16 +816,13 @@ class SpaceEngine(using Context) extends SpaceLogic {
         isCheckable(and.tp1) || isCheckable(and.tp2)
       }) ||
       tpw.isRef(defn.BooleanClass) ||
-      classSym.isAllOf(JavaEnumTrait)
+      classSym.isAllOf(JavaEnumTrait) ||
+      classSym.is(Case) && productSelectorTypes(tpw, sel.srcPos).exists(isCheckable(_))
+    })
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:821]: I tried to understand why the cache breaks the cycle but couldn't figure it out --- when the recursive call tries to use the cache, the value is not there yet, so it will run into cycles.

But obviously, it works. Could you give a hint? :smile:

**Review by liufengyun — APPROVED** [review]
LGTM, thank you @dwijnand :+1:

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala (hunk 1 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:821]: I had exactly the same thought after I sent the PR and didn't understand it either.

But I think I do now: because the test case for #12488 is running under `-Ycheck-all-patmat` so it's short-circuting...  Damn `-Ycheck-all-patmat`.  Why does that flag exist?  It's misleading test results, as I see it.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:821]: It's created a long time ago for testing whether the algorithm works generally. Now it becomes a "feature".

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:821]: I only partially understood your answer there.  Do you think it should continue to exist?  In Scala 2 the only equivalents we have are: `-Xlint:strict-unsealed-patmat` to consider unsealed scrutinees checkable and `-Xnon-strict-patmat-analysis` to disable the pessimistic approximation of guards and custom extractors not matching (the "strict" patmat analysis).

Perhaps looking to transition the tests and the logic out from under the `-Ycheck-all-patmat` would be a good project to get me pinging around the patmat code, learning parts of it.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: > Do you think it should continue to exist? 

I don't really have an opinion here. It's not supposed to be used by end-users. So there is room to change.

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 2]
```diff
@@ -815,16 +817,15 @@ class SpaceEngine(using Context) extends SpaceLogic {
         isCheckable(and.tp1) || isCheckable(and.tp2)
       }) ||
       tpw.isRef(defn.BooleanClass) ||
-      classSym.isAllOf(JavaEnumTrait)
+      classSym.isAllOf(JavaEnumTrait) ||
+      classSym.is(Case) && {
+        if seen.add(tpw) then productSelectorTypes(tpw, sel.srcPos).exists(isCheckable(_))
+        else true // recursive case class: return true and other members can still fail the check
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:823]: It seems `false` aligns better with the protocol that if a component is `sealed`, then perform the check.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:823]: Given something like `case class Foo(parent: Option[Foo], other: Bar)` this else branch is hit when we've running `isCheckable(Foo)` on the Foo in the Option.  My thinking is we can optimistically return `true` here, and then whether or not `Bar` is checkable will determine if the top `Foo` is checkable.  So I think `true` is right here, no?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:823]: Given the following type:

```Scala
case class A(a: A)
```
IIRC, the implementation above will have `isCheckable(A) == true`. If that's as expected, then `true` is fine. Otherwise, it seems `false`  should be used here.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:823]: Yeah, I'm happy with that result.
