### PR TITLE
Fix #1648: don't define companion object for java.lang.Object

### LINKED ISSUE #1468: Missing type apply for scala.Dynamic
```scala
class Foo extends Dynamic {
  def applyDynamic[T](n: String)(): T = ???
}

new Foo().foo[Int]()
// should become
new Foo().applyDynamic[Int]("foo")()
```

The current behaviour is to convert the call to `applyDynamic("foo")[Int]()` which then fails type checking with an error message that is not useful.

### LINKED ISSUE #1648: crash with assertion failed: attempt to parse java.lang.Object from classfile
$ cat abc.scala
```
class Foo { Object[A] }

```

$ dotc abc.scala
```
-- [E006] Missing Identifier Error: abc.scala --------------------------------------------------------------------------
1 |class Foo { Object[A] }
  |                   ^
  |                   not found: type A

longer explanation available when compiling with `-explain`
exception caught when loading module class Object$: java.lang.AssertionError: assertion failed: attempt to parse java.lang.Object from classfile

exception occurred while typechecking abc.scala

exception occurred while compiling abc.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: attempt to parse java.lang.Object from classfile
	at scala.Predef$.assert(Predef.scala:165)
	at dotty.tools.dotc.core.classfile.ClassfileParser$ConstantPool.getSuperClass(ClassfileParser.scala:1017)
	at dotty.tools.dotc.core.classfile.ClassfileParser.parseParents$1(ClassfileParser.scala:103)
	at dotty.tools.dotc.core.classfile.ClassfileParser.parseClass(ClassfileParser.scala:119)
	at dotty.tools.dotc.core.classfile.ClassfileParser.run(ClassfileParser.scala:54)
	at dotty.tools.dotc.core.ClassfileLoader.load(SymbolLoaders.scala:259)
	at dotty.tools.dotc.core.ClassfileLoader.doComplete(SymbolLoaders.scala:255)
	at dotty.tools.dotc.core.SymbolLoader.complete(SymbolLoaders.scala:205)
	at dotty.tools.dotc.core.SymDenotations$LazyType$$anon$1.complete(SymDenotations.scala:1903)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:210)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.info(SymDenotations.scala:188)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:327)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.flags(SymDenotations.scala:136)
	at dotty.tools.dotc.core.SymDenotations$ModuleCompleter.complete(SymDenotations.scala:1941)
<snipped>
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #1648: `java.lang.Object` has no static methods, there's no need to define module object for it.

### CODE REVIEW

**Comment by liufengyun** [comment]
It seems the fix works. I'm not sure if it's the right way to do it. Could you please advise, @odersky ?

File: src/dotty/tools/dotc/core/SymbolLoaders.scala [hunk 1]
```diff
@@ -86,18 +86,27 @@ class SymbolLoaders {
...
   def enterClassAndModule(
       owner: Symbol, name: PreName, completer: SymbolLoader,
       flags: FlagSet = EmptyFlags, scope: Scope = EmptyScope)(implicit ctx: Context): Unit = {
     val clazz = enterClass(owner, name, completer, flags, scope)
-    val module = enterModule(
-      owner, name, completer,
-      modFlags = flags.toTermFlags & RetainedModuleValFlags,
-      clsFlags = flags.toTypeFlags & RetainedModuleClassFlags,
-      scope = scope)
+
```
Comment (odersky) [inline src/dotty/tools/dotc/core/SymbolLoaders.scala]: It's a way to do it, but not very elegant to test this for every class and module that's entered. 

I played with an alternative strategy, which also seems to work and is less intrusive: IN line 196 of Definitions, where we define ObjectClass, insert:

    val companion = JavaLangPackageVal.info.decl(nme.Object).symbol
    companion.info = NoType // to indicate that it does not really exist

Comment (odersky) [inline src/dotty/tools/dotc/core/SymbolLoaders.scala]: Note: The `NoType` technique is not an accident. It is used for all companion objects that are entered (because we see their file name) but turn out to not exist after class loading. Here we have to do it before class loading because once we try to load Object's classfile it is already too late.

Comment (liufengyun) [inline src/dotty/tools/dotc/core/SymbolLoaders.scala]: Thanks @odersky , this is much more elegant 👍 . I've pushed a new commit adopting the approach.

**Comment by odersky** [comment]
LGTM
