### PR TITLE
Fix #14667: Remove mangling of inner AnyQualifiedName's in fullNameSeparated

### LINKED ISSUE #14467: Initialization-checker error is unhelpful for inlined functions
## Compiler version

3.1.2-RC1

## Minimized code

```Scala
class InlineError {
  Assertion.failAssert(this)
  val v = 2;
}

object Assertion:
  transparent inline def failAssert(inline message: => Any): Unit =
    scala.runtime.Scala3RunTime.assertFailed(message)
```

## Output

```scala
[error] -- Error: /*******/dotty/compiler/src/dotty/tools/dotc/InlineError.scala:10:45
[error] 10 |    scala.runtime.Scala3RunTime.assertFailed(message)
[error]    |                                             ^^^^^^^
[error]    |Cannot prove that the value is fully initialized. Only initialized values may be used as arguments.
```

## Expectation

I would expect a helpful error message that highlights what value is truly uninitialized (`this` in this case). However, when the call to the inlined method is in another file, there is no indication as to the source of the error. The only straightforward way to figure out the cause of the error is to make the method not inlined and try recompiling.

### LINKED ISSUE #14667: Private field with non-alphanumeric identifier exhibits incorrect behavior at runtime
## Compiler version

Affects `3.0.0` to `3.1.2-RC1`.

Does not affect `2.13.8`.

## Minimized code

```Scala
trait A {
  private val ? = ""
  def a = ?
}

@main def run(): Unit = println(new A {}.a)
```

[Link to 3.1.1 Scastie](https://scastie.scala-lang.org/guffMVjITtG35SjoriJ2wQ)

## Output

```
null
```

## Expectation

This program should print an empty line, not `null`.

Observations: the problem does not occur when
* `?` is renamed to an alphanumeric identifier (**!**)
* `?` is a definition instead of a value
* `A` is a class instead of a trait
* `?` is protected or public

The `?` can be replaced with any other symbol e.g. `*`, `|||`, ... (all of those will trigger the same problem)

When replacing `""` by e.g. `1`, the program prints `0` which confirms that it is a problem related to initialization.

### PR DESCRIPTION
**Pull request by gagandeepkalra**
resolves #14667

cc @sjrd

### CODE REVIEW

**Comment by griggt** [comment]
I think the linked ticket ought to be https://github.com/lampepfl/dotty/issues/14667 ?

**Comment by sjrd** [comment]
@odersky You originally introduced this mangling in https://github.com/lampepfl/dotty/commit/e7b23253f1ba871b68471997b9818947838d649d. It seems that removing it now doesn't cause any failure, and it does fix the linked issue. Is there any reason to suspect that the mangling may still be necessary in some cases, not covered by the CI?

**Comment by odersky** [comment]
I don't know. It seems to be a very fundamental change to mangle or not, and mangling is explicitly demanded in the comment. So if we drop it I suggest to add an extensive test suite that makes sure nothing goes wrong. Maybe do first some research where fullNames are used in the compiler.

**Comment by sjrd** [comment]
I finally took the time to investigate the places where we use `fullName`s. I instrumented the `case name @ AnyQualifiedName(_, _) =>` that we are modifying in this PR, and there are only 3 sources:

* [`Mixin.traitSetterName`](https://github.com/lampepfl/dotty/blob/67f11ff0bfec11687e9c5f17307bab995a3a9dc9/compiler/src/dotty/tools/dotc/transform/Mixin.scala#L27), which is the method we are fixing with this change.
* [`TreeChecker.testDuplicate`](https://github.com/lampepfl/dotty/blob/67f11ff0bfec11687e9c5f17307bab995a3a9dc9/compiler/src/dotty/tools/dotc/transform/TreeChecker.scala#L52), which is only testing duplicate class names under `-Ycheck`, and therefore never affects compilation.
* [`ExpandPrivate.ensurePrivateAccessible`](https://github.com/lampepfl/dotty/blob/67f11ff0bfec11687e9c5f17307bab995a3a9dc9/compiler/src/dotty/tools/dotc/transform/ExpandPrivate.scala#L66), which manipulates private symbols that are visible in the same compilation unit but in a different class; since it is in the same compilation unit, separate compilation is not impacted, and therefore potentially changing the encoding is not an issue.

Therefore, I think it is safe to removing the mangling in this case.

Moreover, removing the mangling will bring the `case AnyQualfiedName` behavior in line with the `case SimpleName` behavior. I believe that making them more consistent is actually a good sign that this change is a good one.

**Comment by sjrd** [comment]
I rebased and elaborated the commit message.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -488,7 +488,7 @@ object SymDenotations {
           if kind == FlatName && !encl.is(JavaDefined) then qn.compactified else qn
         val fn = name replace {
           case name: SimpleName => qualify(name)
-          case name @ AnyQualifiedName(_, _) => qualify(name.mangled.toSimpleName)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:491]: In fact I now doubt whether we should have this case at all. If we remove this line, then #15702 succeeds. So if we can to this, it would be better.

**Review by odersky — COMMENTED** [review]
Let's see whether we can drop the clause altigether.

**Review by odersky — APPROVED** [review]
I just found out that at least for trait setters dropping the clause does not work unfortunately. So I think this is at least a step in the right direction.
