### PR TITLE
fix: clean up settings in the Build

### LINKED ISSUE #24703: Unexpected outputs in `scala3-library_3:3.8.0-RC3` jar
In 3.8.0-RC2 the scala3-library JAR was empty, in RC3 it contains some .class and .tasty files. Most likely caused by semantics conflicts in https://github.com/scala/scala3/pull/24645 

Image

The same problem can found in latest nightly version `3.8.1-RC1-bin-20251208-0bb0433-NIGHTLY`

Image

## Compiler version
3.8.0-RC3 

## Expectation

`scala3-library_3` arifacts should be empty. Duplicate entries on the classpath would negatively affect compiler and tooling

### PR DESCRIPTION
**Pull request by hamzaremmal**
Remove `classDirectory` from `scala3-library-*` projects and some cleanups of the settings.

Closes #24703

### CODE REVIEW

File: project/Build.scala [hunk 1]
```diff
@@ -1245,13 +1245,8 @@ object Build {
         "-sourcepath", (Compile / sourceDirectories).value.map(_.getCanonicalPath).distinct.mkString(File.pathSeparator),
       ),
       // Packaging configuration of the stdlib
-      Compile / packageBin / publishArtifact := true,
-      Compile / packageDoc / publishArtifact := false,
-      Compile / packageSrc / publishArtifact := true,
-      // Only publish compilation artifacts, no test artifacts
+      Compile / publishArtifact := true,
       Test    / publishArtifact := false,
```
Comment (WojciechMazur) [inline project/Build.scala:1249]: Can we start to deduplicate all the settings and set them in common settings group? Otherwise it's hard to review (need to expand the views to see to which projects given changes apply) and it's easy to forget about some. All of the published artifacts would use the same values for Compile/Test publishArtifacts, and multiple other settings. 
We've had a dedicated publishSetting previously, it might be worthy to restore it. 
Duplication of setting was useful during migration and to track changes, but it's hard to maintain

Comment (hamzaremmal) [reply project/Build.scala:1249]: Not with all the backports that are happening at the moment.

**Review by WojciechMazur — APPROVED** [review]
