### PR TITLE
Fix #9295: Avoid recursive Dynamics conversion

### LINKED ISSUE #9295: Stackoverflow via applyDynamic
## Minimized code

```Scala
// SOE-b6d7587f11f4e553d9998abb2b52d57285be4f28
import scala.language.dynamics

class Foo extends Dynamic {
  def applyDynamic(arg: Any): Foo = ???
}
val foo = new Foo
def baz = foo.blah(42)
```

## Output (click arrow to expand)
<details>

```scala
java.lang.StackOverflowError while compiling test.scala
Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.core.TyperState.isGlobalCommittable(TyperState.scala:63)
	at dotty.tools.dotc.typer.Typer$.assertPositioned(Typer.scala:60)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2496)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.Applications.typedFunPart$$anonfun$1(Applications.scala:842)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2633)
	at dotty.tools.dotc.typer.Applications.typedFunPart(Applications.scala:851)
	at dotty.tools.dotc.typer.Typer.typedFunPart(Typer.scala:89)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:863)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:998)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:89)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2376)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:545)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:569)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2346)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.Applications.typedFunPart$$anonfun$1(Applications.scala:842)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2633)
	at dotty.tools.dotc.typer.Applications.typedFunPart(Applications.scala:851)
	at dotty.tools.dotc.typer.Typer.typedFunPart(Typer.scala:89)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:863)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:998)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:89)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2376)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2436)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:545)
	at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:569)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2346)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2435)
	at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2502)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2511)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2514)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2625)
	at dotty.tools.dotc.typer.Applications.typedFunPart$$anonfun$1(Applications.scala:842)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2633)
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**
Avoid trying to apply `Dynamic` transformation on `apply` with a qualifier that already has
a been handled by the `Dynamic` transformation.

### CODE REVIEW

File: tests/neg/i9295b.scala [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+class Foo extends Dynamic {
+  def applyDynamic(arg: Any): Bar = ???
+}
+class Bar extends Dynamic {
+  def applyDynamic(arg: Any)(x: Int): Int = ???
+}
+object F {
+  val foo = new Foo
+  def baz = foo.blah(43) // error: method applyDynamic in class Foo does not take more parameters
```
Comment (liufengyun) [inline tests/neg/i9295b.scala:11]: Can we add a positive test here: `foo.blah.blah(43)`?

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala [hunk 2]
```diff
@@ -142,7 +142,8 @@ trait TypeAssigner {
     val mbr = qualType.findMember(name, pre)
     if (reallyExists(mbr))
       qualType.select(name, mbr)
-    else if (qualType.derivesFrom(defn.DynamicClass) && name.isTermName && !Dynamic.isDynamicMethod(name))
+    else if (qualType.derivesFrom(defn.DynamicClass) && name.isTermName && !Dynamic.isDynamicMethod(name) &&
+        !(name == nme.apply && Dynamic.isDynamicMethod(qual1.symbol.name)))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:146]: The following code type checks before, but fails to type-check with the change:

```Scala
import scala.language.dynamics

class Foo extends Dynamic {
  def applyDynamic(name: String)(): Bar = ???
}

class Bar extends Dynamic {
  def applyDynamic(name: String)(x: Int) = ???
}

val foo = new Foo
def baz = foo.blah().apply(42)
```

File: tests/neg/i9295b.scala (hunk 1 above)
Comment (nicolasstucki) [reply tests/neg/i9295b.scala:11]: Indeed

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:146]: Good catch. I need to check that the `apply` was not written in the source.

File: tests/neg/i9295b.scala (hunk 1 above)
Comment (nicolasstucki) [reply tests/neg/i9295b.scala:11]: Actually that one should also fail as it would require a selectDynamic.

Comment (nicolasstucki) [reply tests/neg/i9295b.scala:11]: I added extra tests

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: Fixed

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala [hunk 3]
```diff
@@ -142,7 +142,8 @@ trait TypeAssigner {
     val mbr = qualType.findMember(name, pre)
     if (reallyExists(mbr))
       qualType.select(name, mbr)
-    else if (qualType.derivesFrom(defn.DynamicClass) && name.isTermName && !Dynamic.isDynamicMethod(name))
+    else if (qualType.derivesFrom(defn.DynamicClass) && name.isTermName && !Dynamic.isDynamicMethod(name) &&
+        !(name == nme.apply && tree.span.isSynthetic && Dynamic.isDynamicMethod(qual1.symbol.name)))
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:146]: The following code compiles before, but fails to compile after the changes:

```Scala
import scala.language.dynamics

class Foo extends Dynamic {
  def applyDynamic(name: String): Bar = ???
}

class Bar extends Dynamic {
  def applyDynamic(name: String)(x: Int): Qux = ???
}

class Qux extends Dynamic {
  def applyDynamic(name: String)(x: Int) = ???
}


var foo = new Foo
def baz = foo.blah(42).blah(45)
```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:146]: That is intended, as in Scala 2.
https://scastie.scala-lang.org/gsxJ9jifRQyc5jLTbrmYSQ

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:146]: The only worry I have is about using positions for semantics (though we have precedent for that when dealing with contextual functions), as positions are very weak invariants.

If there are no better alternatives, maybe we add the example as a neg test?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:146]: Indeed. I will try to find another way to identify the application

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: Now I handle properly contextual functions, but we still need to check the positions.
