### PR TITLE
Fix #7580: Desugar TupleXXL selection into `apply(n)`

### LINKED ISSUE #7580: Pattern Definitions are not aware of TupleXXL
In desugared pattern definitions, each def for `val a1: Int = this.$1$._1`... relies on the existence of `_N` members, even beyond 22 parameters.

## minimized code

```Scala
val List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, _:_*) = List.fill(25)(0)
```

## error

```scala
-- [E008] Member Not Found Error: ValPattern.scala:1:2 ------------------------
1  |  val List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, _:_*) = List.fill(25)(0)
   |  ^
   |value _1 is not a member of (Int, Int, Int, Int, Int, Int, Int, Int, Int, Int, Int, Int, Int, Int, Int, Int
   |  , 
   |Int, Int, Int, Int, Int, Int, Int)
```

## expectation

no type or runtime error

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -1098,7 +1098,10 @@ object desugar {
           val firstDef =
             ValDef(tmpName, TypeTree(), matchExpr)
               .withSpan(pat.span.union(rhs.span)).withMods(patMods)
-          def selector(n: Int) = Select(Ident(tmpName), nme.selectorName(n))
+          val arity = vars.length
+          def selector(n: Int) =
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala]: As `selector` is called in a large loop, I think it makes more sense for it to be a function val, and only check `arity < 22` once

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala]: Done

**Comment by bishabosha** [comment]
LGTM
