### PR TITLE
Fix #4611

### LINKED ISSUE #4611: Compiler crash: Implicit Function types + SAM
```scala
trait Responder[T] {
  def responseFor(value: T): implicit Request => T
}

object Responder {
  val responseResponder: Responder[Response] =
    response => response
}

class Response
class Request
```
```
exception occurred while compiling tests/allan/Test.scala
Exception in thread "main" scala.MatchError: ArrayBuffer(<SingleDenotation of type MethodType(List(value), List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response)), AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class ImplicitFunction1),List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Request), TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response))))>, <SingleDenotation of type MethodType(List(value), List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response)), MethodType(List(x$0), List(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Request)), TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Response)))>) (of class scala.collection.mutable.ArrayBuffer)
	at dotty.tools.dotc.transform.ExpandSAMs.transformBlock(ExpandSAMs.scala:46)
	at dotty.tools.dotc.transform.MegaPhase.goBlock(MegaPhase.scala:668)
        ...
```
Initially reported by @jeffmay on Gitter

### PR DESCRIPTION
**Pull request by allanrenucci**
class and trait with a single abstract method which result type is an
implicit function type are not considered SAM types anymore. The reason
is because the abstract member desugar to mutiple ones. E.g.

```scala
trait Foo {
  def foo(): implicit Int => Int
}

// becomes
trait Foo {
  def foo(): implicit Int => Int
  def foo$direct(implicit x: Int): Int
}
```

### CODE REVIEW

**Comment by allanrenucci** [comment]
An alternative fix which did not introduce this restriction on SAM types was tried in #4621.

For now this fixes the compiler crash. In the future, if one wants to try again and lift the restriction, `implicitFuns2.scala` is a very good test case

**Comment by allanrenucci** [comment]
Blocked on #4753

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -3837,7 +3837,7 @@ object Types {
    *  A type is a SAM type if it is a reference to a class or trait, which
    *
    *   - has a single abstract method with a method type (ExprType
-   *     and PolyType not allowed!)
+   *     and PolyType not allowed!) which result type is not an implicit function type
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: which -> whose
