### PR TITLE
Fix false positive in WUnused for renamed path-dependent imports

### LINKED ISSUE #18366: False warning about unused import for local/relative import with Scala 3.3
## Compiler version

3.3.0 & 3.3.1-RC4

## Minimized code

```scala
  @SuppressWarnings(Array("UnusedMethodParameter"))
  private[api] def serializeWith[P <: SerializationPack](
      pack: P,
      collation: Collation
    )(builder: SerializationPack.Builder[pack.type]
    ): pack.Document = {

    import builder.{ elementProducer => element, int, string, boolean }

    val elements = Seq.newBuilder[pack.ElementProducer]

    elements += element("locale", string(collation.locale))
    ??? // ...
}
```

See: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/Collation.scala#L166

## Output

```
[error] 166 |    import builder.{ elementProducer => element, int, string, boolean }
[error]     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |                     unused import
```

## Expectation

No warning

### PR DESCRIPTION
**Pull request by szymon-rd**
Fix #18366

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala [hunk 1]
```diff
@@ -661,8 +661,10 @@ object CheckUnused:
         val simpleSelections = qual.tpe.member(sym.name).alternatives
         val typeSelections = sels.flatMap(n => qual.tpe.member(n.name.toTypeName).alternatives)
         val termSelections = sels.flatMap(n => qual.tpe.member(n.name.toTermName).alternatives)
+        val sameTermPath = qual.isTerm && sym.exists && sym.owner.isType && qual.tpe.typeSymbol == sym.owner.asType
         val selectionsToDealias = typeSelections ::: termSelections
-        val qualHasSymbol = simpleSelections.map(_.symbol).contains(sym) || (simpleSelections ::: selectionsToDealias).map(_.symbol).map(dealias).contains(dealiasedSym)
+        def renamedSelection = if(sameTermPath) then sels.find(sel => sel.imported.name == sym.name) else None
```
Comment (KacperFKorban) [inline compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:666]: `renamedSelection` will be computed multiple times, it shouldn't matter that much, but maybe `val` makes as much sense here?
Also the formatting of this `if` seems a bit off.

**Review by KacperFKorban — COMMENTED** [review]
The fix looks ok. Added one nitpick.
Also, please squash your commits before merging.

File: compiler/src/dotty/tools/dotc/transform/CheckUnused.scala (hunk 1 above)
Comment (szymon-rd) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala:666]: A lazy val would make more sense I think. It's last in the chain of `or`s, so I wanted to avoid calculating it eagerly.

Comment (szymon-rd) [reply compiler/src/dotty/tools/dotc/transform/CheckUnused.scala]: huh, the tests failed after changing def => lazy val, that's quite interesting

**Review by KacperFKorban — APPROVED** [review]
LGTM
