### PR TITLE
Fix #444: be more conservative on when Block and If types should be recomputed

### LINKED ISSUE #444: TypedTreeCopier makes incorrect assumption when deciding if Block or If nodes need to be retyped
For blocks, from `tpd.scala`:

``` scala
tree match {
  case tree: Block if (expr.tpe eq tree.expr.tpe) => tree1.withTypeUnchecked(tree.tpe)
  case _ => ta.assignType(tree1, stats, expr)
}
```

This assumes that `tree.tpe` and `tree.expr.tpe` are in sync, but with a block like:

``` scala
{
  val y: Position = new Position(1)
  y
}
```

Then `tree.expr.tpe` will be a `TermRef` but `tree.tpe` will be a widened version of that type since the `TermRef` should not escape the scope of the block. This means that if the info of `y` is changed by `DenotTransformer#transform`:
- `tree.expr.tpe` will still be a TermRef
- `tree.expr.tpe.widen` will be changed
- `tree.tpe` will not be changed, is now incorrect, and needs to be retyped.

This happens in phase  `ElimErasedValueType` in my implementation of value classes, see https://github.com/smarter/dotty/tree/add/value-classes%2Bcpy-bug and reproduce the bug by running:

```
> run -Ycheck:elimErasedValueType tests/pos/vcblock.scala
> run -Ycheck:elimErasedValueType tests/pos/vcif.scala
```

And note that the errors disappear if you always retype `Block` and `If`: https://github.com/smarter/dotty/tree/add/value-classes%2Bcpy-bug%2Bretype

Assigned to @DarkDimius .

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #444: be more conservative on when Block and If types should be recomputed

It seems that @DarkDimius forgot to make a PR after the fix.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/tpd.scala [hunk 1]
```diff
@@ -572,15 +572,25 @@ object tpd extends Trees.Instance[Type] with TypedTreeInfo {
...
       }
     }
 
     override def If(tree: Tree)(cond: Tree, thenp: Tree, elsep: Tree)(implicit ctx: Context): If = {
       val tree1 = untpdCpy.If(tree)(cond, thenp, elsep)
       tree match {
-        case tree: If if (thenp.tpe eq tree.thenp.tpe) && (elsep.tpe eq tree.elsep.tpe) => tree1.withTypeUnchecked(tree.tpe)
+        case tree: If if (thenp.tpe eq tree.thenp.tpe) && (elsep.tpe eq tree.elsep.tpe) &&
+          ((tree.tpe eq thenp.tpe) || (tree.tpe eq elsep.tpe)) =>
+          // last guard is needed in case previous if had computed a widened ORType that needs to be recomputed
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/tpd.scala]: New comment:
```scala
          // The last guard is a conservative check similar to the one done in `Block` above,
          // if `tree.tpe` is not identical to the type of one of its branch, it might have been
          // computed from the widened type of the branches, so the same reasoning than
          // in `Block` applies.
```

**Comment by smarter** [comment]
... I wish this wasn't merged so fast, my comment still stand.

**Comment by liufengyun** [comment]
@smarter Thanks a lot, I'll address the comment in another PR.
