### PR TITLE
fix #13994: initialise inline ctx in lateEnter

### LINKED ISSUE #13994: incremental crash: inlining from top-level object defined in file with other name
When incrementally compiling some project with `-sourcepath` compiler option, if I reference an inline method (`foo` defined in `a/zz.scala`, where `foo` is defined in a root object `a.Foo`)  in a non-inline method (`bar` in `a/Bar.scala`, where `bar` is defined in a root object `a.Bar`), and then modify the rhs of `foo` and recompile, zinc will compile `zz.scala` in one run, and then crash when compiling `Bar.scala` in the second run.

It seems the issue is only triggered when an inline method is defined in an object with a different name to the file it is in.

## Compiler version

`3.1.2-RC1-bin-20211119-2ef89b2-NIGHTLY`

## Minimized code

1) make sbt project (v1.5.5)

```scala
// build.sbt
scalaVersion := "3.1.2-RC1-bin-20211119-2ef89b2-NIGHTLY"

(Compile / scalacOptions) ++= Seq(
  "-sourcepath", (Compile / sourceDirectories).value.map(_.getAbsolutePath).distinct.mkString(java.io.File.pathSeparator),
)
```

2) add these files to the sources:

```Scala
// src/main/scala/a/zz.scala
package a

object Foo: // note that `Foo` is defined in `zz.scala`
  class Local
  inline def foo(using Local): Nothing =
    ???
```
```Scala
// src/main/scala/a/Bar.scala
package a

object Bar:
  given Foo.Local()
  def Bar = Foo.foo
```

3) run `sbt compile` successfully

4) Edit rhs of `foo` in `zz.scala`

```diff
 package a

 object Foo:
   class Local
   inline def foo(using Local): Nothing =
     ???
+    ???
```

4) run `sbt compile`, expect crash

## Output (click arrow to expand)
<details>

```scala
[info] compiling 1 Scala source to /Users/jamie/workspace/test-inc-inlining/target/scala-3.1.2-RC1-bin-20211119-2ef89b2-NIGHTLY/classes ...
[info] compiling 1 Scala source to /Users/jamie/workspace/test-inc-inlining/target/scala-3.1.2-RC1-bin-20211119-2ef89b2-NIGHTLY/classes ...
[info] exception occurred while compiling /Users/jamie/workspace/test-inc-inlining/src/main/scala/a/Bar.scala
java.util.NoSuchElementException: None.get while compiling /Users/jamie/workspace/test-inc-inlining/src/main/scala/a/Bar.scala
[error] ## Exception when compiling 2 sources to /Users/jamie/workspace/test-inc-inlining/target/scala-3.1.2-RC1-bin-20211119-2ef89b2-NIGHTLY/classes
[error] java.util.NoSuchElementException: None.get
[error] scala.None$.get(Option.scala:627)
[error] scala.None$.get(Option.scala:626)
[error] dotty.tools.dotc.typer.PrepareInlineable$.makeInlineable(PrepareInlineable.scala:35)
[error] dotty.tools.dotc.typer.PrepareInlineable$.registerInlineInfo$$anonfun$1$$anonfun$1(PrepareInlineable.scala:267)
[error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:238)
[error] dotty.tools.dotc.typer.PrepareInlineable$.registerInlineInfo$$anonfun$1(PrepareInlineable.scala:267)
[error] dotty.tools.dotc.core.Annotations$.dotty$tools$dotc$core$Annotations$$anon$2$$_$$lessinit$greater$$anonfun$1(Annotations.scala:165)
[error] dotty.tools.dotc.core.Annotations$LazyBodyAnnotation.tree(Annotations.scala:153)
[error] dotty.tools.dotc.typer.Inliner$.bodyToInline(Inliner.scala:52)
[error] dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:156)
[error] dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:86)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:103)
[error] dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
[error] dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1466)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1477)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
[error] dotty.tools.dotc.transform.Inlining$$anon$2.transform(Inlining.scala:72)
[error] dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
[error] dotty.tools.dotc.transform.Inlining.run(Inlining.scala:44)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:308)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:309)
[error] dotty.tools.dotc.transform.Inlining.runOn(Inlining.scala:48)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:261)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:272)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:280)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:289)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:222)
[error] dotty.tools.dotc.Run.compile(Run.scala:206)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.util.NoSuchElementException: None.get
[error] Total time: 0 s, completed Nov 23, 2021 10:14:13 AM
```
</details>

### PR DESCRIPTION
**Pull request by bishabosha**
In `lateEnter` the context is captured in the namer by the inline body annotation in `completeInCreationContext`. So we initialise the context for inlining before calling `lateEnter`.

I've not figured out a way to replicate this in sbt scripted tests, but you can experiment by copying the sources from #13994 to `library/src-bootstrapped`

fixes #13994

### CODE REVIEW

**Comment by bishabosha** [comment]
mostly before this can be merged we need to add a test case that can reproduce the original issue - sbt scripted tests do not appear to work for this, I have been told that the cmdTests can be useful here

**Comment by bishabosha** [comment]
@nicolasstucki I have added a case to bootstrapCmdTest - I would appreciate a better way to access the compiler version if possible

**Comment by bishabosha** [comment]
This is ready to review - the test case reproduces the issue in #13994, requiring the fixes to `Run` to succeed

**Review by nicolasstucki — APPROVED** [review]

**Review by odersky — CHANGES_REQUESTED** [review]
I think we need some changes. Detailed review will follow

File: compiler/src/dotty/tools/dotc/Run.scala [hunk 1]
```diff
@@ -303,17 +303,28 @@ class Run(comp: Compiler, ictx: Context) extends ImplicitRunInfo with Constraint
...
       def process()(using Context) = {
+
+        def enterTrees()(using Context) =
+          ctx.typer.lateEnter(unit.untpdTree)
+          def typeCheckUnit()(using Context) =
+            unit.tpdTree = ctx.typer.typedExpr(unit.untpdTree)
+            val phase = new transform.SetRootTree()
+            phase.run
+          if typeCheck then
+            val typerCtx: Context =
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/Run.scala:314]: Simpler:
```scala
atPhase(Phase.typerPhase) {
  if compiling then finalizeActions += (() => typeCheckUnit())
  else typeCheckUnit()
}
```

File: compiler/src/dotty/tools/dotc/Run.scala [hunk 2]
```diff
@@ -303,17 +303,28 @@ class Run(comp: Compiler, ictx: Context) extends ImplicitRunInfo with Constraint
...
-          unit.tpdTree = ctx.typer.typedExpr(unit.untpdTree)
-          val phase = new transform.SetRootTree()
-          phase.run
-        }
-        if (typeCheck)
-          if (compiling) finalizeActions += (() => processUnit()) else processUnit()
+        val namerCtx =
+          // inline body annotations are set in namer, capturing the current context
+          // we need to prepare the context for inlining.
+          if unit.isJava then ctx else PrepareInlineable.initContext(ctx)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/Run.scala:326]: I don't think we need the `isJava` distinction. So this could be
```scala
enterTrees()(using PrepareInlineable.initContext(ctx))
```

**Review by odersky — CHANGES_REQUESTED** [review]
Maybe evaluate whether some of this can be moved to Namer and be merged with `lateEnter` there. It's important to keep driver classes like `Run` clean and not burden them with implementation detail.

**Comment by bishabosha** [comment]
@odersky  I have moved most of the implementation of `lateCompile` to namer, save for a callback implemented in Run

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 3]
```diff
@@ -708,15 +710,44 @@ class Namer { typer: Typer =>
...
+    unit.untpdTree =
+      if (unit.isJava) new JavaParser(unit.source).parse()
+      else new Parser(unit.source).parse()
+
+    inContext(PrepareInlineable.initContext(ctx)) {
+      // inline body annotations are set in namer, capturing the current context
+      // we need to prepare the context for inlining.
+      lateEnter()
+      typeCheckCB { () =>
+        atPhase(Phases.typerPhase) {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:746]: Aren't we already in a Context at phase typer here?

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:746]: nope, its at parser phase if you don't set this

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:746]: but before parser and typer used to be the same phase, so maybe that's what you're thinking

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:746]: maybe typer phase should be set before entering - the bug I came across was that implicit search from an inline method would not work

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala:746]: yeah it should all be at typer phase.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Namer.scala]: I reordered it a bit

File: compiler/src/dotty/tools/dotc/Run.scala [hunk 4]
```diff
@@ -302,20 +300,16 @@ class Run(comp: Compiler, ictx: Context) extends ImplicitRunInfo with Constraint
...
+          if typeCheck then
+            if compiling then finalizeActions += doTypeCheck
+            else doTypeCheck()
+        )
+
+      inContext(unitCtx) {
+        process()
       }
-      process()(using unitCtx)
     }
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/Run.scala:313]: Previous version seemed fine?

File: project/scripts/bootstrapCmdTests [hunk 5]
```diff
@@ -83,3 +83,12 @@ clear_out "$OUT"
 ./bin/scalac -d "$OUT/out.jar" tests/pos/i12973.scala
 echo "Bug12973().check" | TERM=dumb ./bin/scala -cp "$OUT/out.jar" > "$tmp" 2>&1
 grep -qe "Bug12973 is fixed" "$tmp"
+
+echo "testing -sourcepath with inlining"
```
Comment (smarter) [inline project/scripts/bootstrapCmdTests:87]: Add a comment explaining what this is testing exactly / why it can't be tested with an sbt scripted test?

File: project/scripts/bootstrapCmdTests [hunk 6]
```diff
@@ -83,3 +83,12 @@ clear_out "$OUT"
...
+cwd=$(pwd)
+java_prop="-Dpack.version.file=$cwd/dist/target/pack/VERSION"
+sbt_test_command=";clean;prepareSources;compile;copyChanges;compile"
```
Comment (smarter) [inline project/scripts/bootstrapCmdTests:90]: isn't the property used here to do something equivalent to:
```suggestion
sbt_test_command="++$(cat dist/target/pack/VERSION)!;clean;prepareSources;compile;copyChanges;compile"
```

**Review by smarter — APPROVED** [review]

File: project/scripts/bootstrapCmdTests (hunk 6 above)
Comment (bishabosha) [reply project/scripts/bootstrapCmdTests:90]: I would like to do that but VERSION is a file with three properties inside

Comment (bishabosha) [reply project/scripts/bootstrapCmdTests:90]: found a solution without using java properties

File: compiler/src/dotty/tools/dotc/Run.scala (hunk 4 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/Run.scala]: reverted

**Comment by bishabosha** [comment]
@smarter I added a comment to the cmd tests, I have also found a way to parse the scala version in bash so I deleted the changes related to loading scala version from java properties.

**Comment by bishabosha** [comment]
@odersky would you like to check this again?

**Review by odersky — APPROVED** [review]
I think that way it is structured better than before.
