### PR TITLE
Ignore types in macro runtime dependencies

### LINKED ISSUE #12498: Cannot call macro defined in the same source file error
## Compiler version

3.0.1-RC1

## Minimized code

MainMacro.scala
```scala
import scala.quoted.*

case class Wrapper[T](t: T) extends MainMacro[T]

trait MainMacro[U] { this: Wrapper[U] => 
  inline def showTypeRepr: String = ${ MainMacro.showTypeReprImpl[U]}
}

object MainMacro {
  def showTypeReprImpl[U: Type](using Quotes): Expr[String] = {
      import quotes.reflect.*
 
      val tpe = TypeRepr.of[U]

      Expr(tpe.toString)
  }
}
```

Test1.scala
```scala
object TestData {
  case class Person(name: String, age: Int)
}

class Test1 {

  import TestData.*

  // Notice that without inline does not work also
  inline def in(fun: => Any): Any = fun

  in {
    Wrapper(Person("a", 1)).showTypeRepr
  }
}
```

## Output

```
$ mkdir classes
$ scalac -3.0.2-RC1 -d classes MainMacro.scala
$ scalac -3.0.2-RC1 -d classes -cp classes Test1.scala
-- Error: Test1.scala:13:28 ----------------------------------------------------
13 |    Wrapper(Person("a", 1)).showTypeRepr
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |    Cannot call macro class Person defined in the same source file
   | This location contains code that was inlined from Test1.scala:13
1 error found
```

## Expectation
It should compile, I guess.

### PR DESCRIPTION
**Pull request by nicolasstucki**
We can have different kinds of type references in the contents of a
splice. We do not care about types because those are erased and the
interpreter emulates erased semantics. These types are in `Tree`s that
extend `TypeTree` or `RefTree` referring to type.

Fixes #12498

### CODE REVIEW

**Comment by nicolasstucki** [comment]
How I fixed it: https://github.com/lampepfl/dotty/issues/12498#issuecomment-1167103699

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -1896,6 +1896,8 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
             level -= 1
             try apply(syms, body)
             finally level += 1
+          case TypeApply(fun, _) =>
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:1899]: Should we skip over `TypeTree` in general?  Or maybe even `TypTree`s?  I don't mind landing the patch as it is, but I was wondering.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:1899]: I think that is a good idea. I will change it. 

Something like `${ f('x): List[X] }` might fail if `X` is uncompled dependency.

**Review by dwijnand — APPROVED** [review]
💪🏼

**Comment by nicolasstucki** [comment]
Squashed and rebased

**Review by dwijnand — APPROVED** [review]
