### PR TITLE
Treat new Array(0) as immutable

### LINKED ISSUE #18882: `-Ysafe-init-global` not working with Scala 2 library TASTy
## Problematic tests

* `tests/init-global/neg/patmat.scala`
* `tests/init-global/neg/t9312.scala`
* `tests/init-global/neg/unapplySeq-implicit-arg.scala`
* `tests/init-global/neg/unapplySeq-implicit-arg2.scala`
* `tests/init-global/neg/unapplySeq-implicit-arg3.scala`

## Reproduction 1

```
sbt> set ThisBuild/Build.useScala2LibraryTasty := true
sbt> scala3-bootstrapped/testCompilation tests/init-global/neg/t9312.scala
```

## Reproduction 2

<details><summary>Without library TASTy</summary>

```
sbt> set ThisBuild/Build.useScala2LibraryTasty := false
sbt> scala3-bootstrapped/scalac -Ysafe-init-global tests/init-global/neg/t9312.scala
```

```scala
-- Warning: tests/init-global/neg/t9312.scala:18:11 ----------------------------
18 |    object Child1 extends Child     // error
   |           ^
   |Cyclic initialization: object Child1 -> object Parent -> object Child1. Calling trace:
   |-> object Child1 extends Child     // error [ t9312.scala:18 ]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |-> trait Child {    [ t9312.scala:12 ]
   |   ^
   |-> val parent = Parent      [ t9312.scala:14 ]
   |                ^^^^^^
   |-> object Parent {                    // error      [ t9312.scala:11 ]
   |   ^
   |-> final val children = Set(Child1, Child2) [ t9312.scala:21 ]
   |                            ^^^^^^
-- Warning: tests/init-global/neg/t9312.scala:11:9 -----------------------------
11 |  object Parent {                    // error
   |         ^
   |Cyclic initialization: object Parent -> object Child2 -> object Parent. Calling trace:
   |-> object Parent {                    // error      [ t9312.scala:11 ]
   |   ^
   |-> final val children = Set(Child1, Child2) [ t9312.scala:21 ]
   |                                    ^^^^^^
   |-> object Child2 extends Child      [ t9312.scala:19 ]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |-> trait Child {    [ t9312.scala:12 ]
   |   ^
   |-> val parent = Parent      [ t9312.scala:14 ]
   |                ^^^^^^
2 warnings found
```
</details> 

<details><summary>With library TASTy</summary>

```
sbt> set ThisBuild/Build.useScala2LibraryTasty := true
sbt> scala3-bootstrapped/scalac -Ysafe-init-global tests/init-global/neg/t9312.scala
```

```scala
-- Warning: tests/init-global/neg/t9312.scala:18:11 ----------------------------
18 |    object Child1 extends Child     // error
   |           ^
   |Cyclic initialization: object Child1 -> object Parent -> object Child1. Calling trace:
   |-> object Child1 extends Child     // error [ t9312.scala:18 ]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |-> trait Child {    [ t9312.scala:12 ]
   |   ^
   |-> val parent = Parent      [ t9312.scala:14 ]
   |                ^^^^^^
   |-> object Parent {                    // error      [ t9312.scala:11 ]
   |   ^
   |-> final val children = Set(Child1, Child2) [ t9312.scala:21 ]
   |                            ^^^^^^
-- Warning: tests/init-global/neg/t9312.scala:11:9 -----------------------------
11 |  object Parent {                    // error
   |         ^
   |Cyclic initialization: object Parent -> object Child2 -> object Parent. Calling trace:
   |-> object Parent {                    // error      [ t9312.scala:11 ]
   |   ^
   |-> final val children = Set(Child1, Child2) [ t9312.scala:21 ]
   |                                    ^^^^^^
   |-> object Child2 extends Child      [ t9312.scala:19 ]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |-> trait Child {    [ t9312.scala:12 ]
   |   ^
   |-> val parent = Parent      [ t9312.scala:14 ]
   |                ^^^^^^
Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating a field before its initialization: variable mutationCount. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.mutationCount = ArrayBuffer.this.mutationCount.+(1)

Mutating a field before its initialization: variable size0. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.size0 = ArrayBuffer.this.length.+(elemsLength)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating a field before its initialization: variable mutationCount. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.mutationCount = ArrayBuffer.this.mutationCount.+(1)

Mutating a field before its initialization: variable size0. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.size0 = ArrayBuffer.this.length.+(elemsLength)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating a field before its initialization: variable mutationCount. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.mutationCount = ArrayBuffer.this.mutationCount.+(1)

Mutating a field before its initialization: variable size0. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.size0 = ArrayBuffer.this.length.+(elemsLength)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating a field before its initialization: variable mutationCount. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.mutationCount = ArrayBuffer.this.mutationCount.+(1)

Mutating a field before its initialization: variable size0. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.size0 = ArrayBuffer.this.length.+(elemsLength)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.clone()

Reading mutable state of object Array during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> BitmapIndexedSetNode.this.originalHashes.apply(index)

Reading mutable state of object ArrayBuffer during initialization of object Parent.
Reading mutable state of other static objects is forbidden as it breaks initialization-time irrelevance. Calling trace: 
-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.apply(n)

Mutating object ArrayBuffer during initialization of object Parent.
Mutating other static objects during the initialization of one static object is forbidden. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> ArrayBuffer.this.array.update(index, elem.asInstanceOf[AnyRef])

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.appended[A](element)

Mutating a field before its initialization: variable content. Calling trace:

-> object Parent {                    // error  [ t9312.scala:11 ]
   ^
-> final val children = Set(Child1, Child2)     [ t9312.scala:21 ]
                        ^^^^^^^^^^^^^^^^^^^
-> hc.content = hc.content.updated[A](index, element)

86 warnings found
```
</details> 

## Question

What trigers the extra warnings? It is possible that the TASTy has some inconsitent information. It is also possible that the TASTy has more information, for example, now we know which classes have a pure constuctor.

### PR DESCRIPTION
**Pull request by liufengyun**
An array of size 0 is immutable, thus we can safely abstract them with the bottom value.

For the rules to be simple and understandable, we usually want to avoid such fine-tuning. However, given that we expect such code patterns to be rare and we want to avoid changes in the standard library, we fine-tune the analysis as a compromise.

Partly fixes #18882. The warnings in compiling `tests/init-global/neg/t9312.scala` goes down to 28 from 87.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/init/Objects.scala [hunk 1]
```diff
@@ -875,7 +875,7 @@ object Objects:
    * @param ctor        The symbol of the target constructor.
    * @param args        The arguments passsed to the constructor.
    */
-  def instantiate(outer: Value, klass: ClassSymbol, ctor: Symbol, args: List[ArgInfo]): Contextual[Value] = log("instantiating " + klass.show + ", outer = " + outer + ", args = " + args.map(_.value.show), printer, (_: Value).show) {
+  def instantiate(outer: Value, klass: ClassSymbol, ctor: Symbol, args: List[ArgInfo], inKlass: ClassSymbol): Contextual[Value] = log("instantiating " + klass.show + ", outer = " + outer + ", args = " + args.map(_.value.show), printer, (_: Value).show) {
```
Comment (olhotak) [inline compiler/src/dotty/tools/dotc/transform/init/Objects.scala:878]: Consider removing `inKlass`: it is not used.

**Review by olhotak — APPROVED** [review]
Othersize LGTM.
