### PR TITLE
Fix #2468: Replace wildcards in a mini-phase

### LINKED ISSUE #2468: `private[this] var x: String = _` crashes with "key not found: class String" in the backend
```scala
class A {
  private[this] var x: String = _
}
```
```scala
java.util.NoSuchElementException: key not found: class String
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:402)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:391)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:290)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:89)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder$$anonfun$genNormalBlock$1$1.apply(BCodeBodyBuilder.scala:860)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder$$anonfun$genNormalBlock$1$1.apply(BCodeBodyBuilder.scala:860)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalBlock$1(BCodeBodyBuilder.scala:860)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:892)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:408)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:606)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:640)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:509)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$$anonfun$gen$1.apply(BCodeSkelBuilder.scala:511)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$$anonfun$gen$1.apply(BCodeSkelBuilder.scala:511)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:511)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:118)
        at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.visit(GenBCode.scala:199)
        at dotty.tools.backend.jvm.GenBCodePipeline$Worker1.run(GenBCode.scala:152)
        at dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:367)
        at dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:333)
        at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:54)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:283)
        at dotty.tools.dotc.core.Phases$Phase$$anonfun$runOn$1.apply(Phases.scala:281)
        at scala.collection.immutable.List.map(List.scala:284)
        at dotty.tools.dotc.core.Phases$Phase$class.runOn(Phases.scala:281)
        at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:38)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:82)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:79)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:79)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
        at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:67)
        at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:76)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:67)
        at dotty.tools.dotc.Run.compileSources(Run.scala:64)
        at dotty.tools.dotc.Run.compile(Run.scala:48)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
        at dotty.tools.dotc.Driver.process(Driver.scala:124)
        at dotty.tools.dotc.Driver.process(Driver.scala:93)
        at dotty.tools.dotc.Driver.process(Driver.scala:105)
        at dotty.tools.dotc.Driver.main(Driver.scala:132)
        at dotty.tools.dotc.Main.main(Main.scala)
```
Interestingly, this also crashes:
```scala
class A {
  private[this] var x: String = _

  x = "foo"
}
```
But this doesn't:
```scala
class A {
  private[this] var x: String = _

  def test: Unit = {
    x = "foo"
  }
}
```

### PR DESCRIPTION
**Pull request by biboudis**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+        val literal = defaultValueLiteral(tree)
+        cpy.ValDef(tree)(rhs = literal)
+      case _ => tree
+    }
+  }
+
+  def defaultValueLiteral(tree: ValDef)(implicit ctx: Context) = {
+    val t = tree.rhs.tpe.widenDealias.classSymbol
+
+    if (t eq defn.DoubleClass) Literal(Constant(0.0d))
```
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala]: Use `tpd.defaultValue`

File: compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+
+class TransformWildcards extends MiniPhaseTransform with IdentityDenotTransformer { thisTransform =>
+  import tpd._
+
+  override def phaseName = "transformWildcards"
+
+  override def checkPostCondition(tree: Tree)(implicit ctx: Context): Unit = {
+    tree match {
+      case ValDef(_, _, Ident(name)) => assert(name ne nme.WILDCARD)
```
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala]: tpd.isWildcardArg(ident)

File: compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+      case _ =>
+    }
+  }
+
+  override def transformValDef(tree: ValDef)(implicit ctx: Context, info: TransformerInfo): Tree = {
+    tree.rhs match {
```
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala]: it should only transform it in methods.
check !ctx.owner.isClass.

File: compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+
+    if (t eq defn.DoubleClass) Literal(Constant(0.0d))
+    else if (t eq defn.IntClass) Literal(Constant(0))
+    else if (t eq defn.CharClass) Literal(Constant('\u0000'))
+    else if (t eq defn.ByteClass) Literal(Constant(0: Byte))
+    else if (t eq defn.LongClass) Literal(Constant(0L))
+    else if (t eq defn.FloatClass) Literal(Constant(0f))
+    else if (t eq defn.UnitClass) Literal(Constant(()))
+    else if (t eq defn.BooleanClass) Literal(Constant(false))
+    else Literal(Constant(null))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala]: This can be factored out in `Constants` as `defaultConstant(tpe: Type)`.

File: compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala (hunk 2 above)
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala]: + perform the check only method bodies.

File: compiler/src/dotty/tools/dotc/Compiler.scala [hunk 5]
```diff
@@ -95,7 +95,8 @@ class Compiler {
                                        // Note: in this mini-phase block scopes are incorrect. No phases that rely on scopes should be here
            new ElimStaticThis,      // Replace `this` references to static objects by global identifiers
            new Flatten,             // Lift all inner classes to package scope
-           new RestoreScopes),      // Repair scopes rendered invalid by moving definitions in prior phases of the group
+           new RestoreScopes,       // Repair scopes rendered invalid by moving definitions in prior phases of the group
+           new TransformWildcards), // Replace wildcards with default values
```
Comment (DarkDimius) [inline compiler/src/dotty/tools/dotc/Compiler.scala]: don't put phases in this block... This block is.... strage, se note above.
Better put it in the next block that has backend-specific phases similar to this one.

Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/Compiler.scala]: `wildcards` is ambiguous. Should say that it is only the ones in ValDef

File: compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+import core.DenotTransformers._
+import core.Contexts._
+import ast.Trees._
+import ast.tpd
+import core.Constants.Constant
+import core.StdNames._
+import core.Symbols._
+
+
+class TransformWildcards extends MiniPhaseTransform with IdentityDenotTransformer { thisTransform =>
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/TransformWildcards.scala]: Needs documentation

**Comment by biboudis** [comment]
Thanks @nicolasstucki for sponsoring this PR! 👍
