### PR TITLE
Fix #8845: Strip annots from proto when checking SAM

### LINKED ISSUE #8845: Cannot inline functional interface as parameter
```Scala
  trait IntToLong:
    def apply(v: Int) : Long

  inline def convert1(       f: IntToLong) = ???
  inline def convert2(inline f: IntToLong) = ???

  convert1(_ * 10)  // Compiles Fine
  convert2(_ * 10)  // Error:  Found: Int => Long, Required: IntToLong @InlineParam
```
Is this supposed to work at all?

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1170,7 +1170,7 @@ class Typer extends Namer
       if (tree.tpt.isEmpty)
         meth1.tpe.widen match {
           case mt: MethodType =>
-            pt match {
+            pt.stripAnnots match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1173]: I think the stripping should be done in the `SAMType` extractor instead

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Indeed. Moved.
