### PR TITLE
Re-architecture staging phase and fix all known issues of that phase

### LINKED ISSUE #6140: Type phase healing doesn't work on type members
```scala
import scala.quoted._
sealed trait Trait[T] {
  type t = T
}

object O {
  def fn[T:Type](t : Trait[T])(using QuoteContext): Type[T] = '[t.t]
}
```

This fails to compile with a phase incorrectness error:
```
xxx |  def fn[T:Type](t : Trait[T]) : Type[T] = '[t.t]
    |                                             ^
    |                           access to value t from wrong staging level:
    |                            - the definition is at level 0,
    |                            - but the access is at level 1.
```

which can be worked around with the following change, despite in both cases there being a `Type[T]` or `Type[t.t]` implicitly available:
```scala
sealed trait Trait[T] {
  type t = T
}

object O {
  def fn[T:Type](t : Trait[T]) : Type[T] = {
    type TT = t.t
    '[TT]
  }
}
```

This isn't a huge issue since the workaround is quite simple, but it does seem like a strange thing to not work.

### LINKED ISSUE #6772: Undefined `+=` in inner quote
Implementing `scala.quoted.ExprOps.toExprOfList` with
```Scala
    /** Lifts this list of expressions into an expression of a list
     *
     *  Transforms a list of expression
     *    `e1 :: e2 :: ... :: Nil` where `ei: Expr[T]`
     *  to an expression equivalent to
     *    `'{ $e1 :: $e2 :: ... :: Nil }` typed as an `Expr[List[T]]`
     */
    def (list: List[Expr[T]]) toExprOfList[T] given Type[T], QuoteContext: Expr[List[T]] = '{
      val buff = List.newBuilder[T]
      ${ Expr.block(list.map(v => '{ buff +=  $v }), '{ buff.result() }) }
    }
```

fails with 

```
35 |      ${ Expr.block(list.map(v => '{ buff `+=` $v }), '{ buff.result() }) }
   |                                     ^^^^^^^^^^^^
   |                                 undefined: buff.+= # 189467: TermRef(TermRef(NoPrefix,val buff),+=) at frontend
   | This location is in code that was inlined at quoted_2.scala:6
```

### LINKED ISSUE #7030: Unresolved symbols when pickling quotes: by-name parameters, underlyingArgument and unintuitive error message
Macros:

```scala
import scala.quoted._

inline def inner(exprs: Any): Any = ${innerImpl('exprs)}
def innerImpl(exprs: Expr[Any]) given QuoteContext: Expr[Any] =
  '{$exprs ; ()}

inline def outer(expr: => Any): Any = ${outerImpl('expr)}
def outerImpl(body: Expr[Any]) given (ctx: QuoteContext): Expr[Any] = {
  import ctx.tasty._
  body.unseal.underlyingArgument.seal
}
```

Test:

```scala
val x = outer(inner(???))
```

<details><summary>Crash</summary>

```scala
exception occurred while compiling ../pg-dotc/Main.scala
java.lang.AssertionError: assertion failed: unresolved symbols: value exprs(line 0) when pickling ../pg-dotc/Main.scala while compiling ../pg-dotc/Main.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: value exprs(line 0) when pickling ../pg-dotc/Main.scala
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:695)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$10$$anonfun$8(Pickler.scala:60)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at dotty.tools.dotc.transform.Pickler.run$$anonfun$2(Pickler.scala:83)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:83)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:316)
	at scala.collection.immutable.List.map(List.scala:286)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:318)
	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:87)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
	at dotty.tools.dotc.Run.compileSources(Run.scala:120)
	at dotty.tools.dotc.Run.compile(Run.scala:104)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.dotc.Driver.process(Driver.scala:180)
	at dotty.tools.dotc.Driver.process(Driver.scala:149)
	at dotty.tools.dotc.Driver.process(Driver.scala:161)
	at dotty.tools.dotc.Driver.main(Driver.scala:188)
	at dotty.tools.dotc.Main.main(Main.scala)
[error] Nonzero exit code returned from runner: 1
[error] (dotty-compiler / Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 8 s, completed Aug 12, 2019 2:07:51 PM
```

</details>

To make it compile, make the parameter to `inner` by-name:

```scala
inline def inner(exprs: => Any): Any = ${innerImpl('exprs)}
```

In my original use case, it was a mistake for me not to make it by-name. However, due to the obscure crash, I was not able to see that mistake right away.

This is already the second time I encounter unintuitive behaviour of `underlyingArgument` (don't remember the first time, but it was likely the same thing). I expected it to just return an immediate child node of the callee. However, it seems that it performs a deep traversal and transformation of the callee tree. If you debug `outerImpl` as follows:

```scala
def outerImpl(body: Expr[Any]) given (ctx: QuoteContext): Expr[Any] = {
  import ctx.tasty._
  println(s"Original:\n${body.unseal}")
  println(s"\nUnderlying:\n${body.unseal.underlyingArgument}")
  body.unseal.underlyingArgument.seal
}
```

<details><summary>Original will be</summary>

```scala
Inlined(
  EmptyTree,List(

  ),Inlined(
    Apply(
      Ident(
        inner
      ),List(
        Ident(
          ???
        )
      )
    ),List(
      ValDef(
        exprs,TypeTree[TypeRef(
          ThisType(
            TypeRef(
              NoPrefix,module class scala
            )
          ),class Nothing
        )],Ident(
          ???
        )
      )
    ),Typed(
      Inlined(
        Ident(
          Macros$package$
        ),List(

        ),Block(
          List(
            Inlined(
              EmptyTree,List(

              ),Inlined(
                EmptyTree,List(

                ),Ident(
                  exprs
                )
              )
            )
          ),Literal(
            Constant(
              (

              )
            )
          )
        )
      ),Ident(
        Any
      )
    )
  )
)
```

</details>

<details><summary>Underlying will be</summary>

```scala
Typed(
  Block(
    List(
      Ident(
        exprs
      )
    ),Literal(
      Constant(
        (

        )
      )
    )
  ),Ident(
    Any
  )
)
```

</details>

Notice how the following code is __not__ present in Underlying:

```scala
      ValDef(
        exprs,TypeTree[TypeRef(
          ThisType(
            TypeRef(
              NoPrefix,module class scala
            )
          ),class Nothing
        )],Ident(
          ???
        )
      )
```

Which is the likely cause of the crash.

I believe `underlyingArgument` should do just that – pill off the "outer layer" of the tree, returning the meaningful child. If the user really wants the current logic, we should make it into a separate method with a name reflecting its deep nature.

/cc @liufengyun since you looked into the issues with unresolved symbols while pickling recently

### LINKED ISSUE #7892: Compiler crash during pickling when extracting type info from quotation
## minimized code

```Scala
package a

import scala.quoted._
import scala.quoted.matching._


package x {

case class CExprResult1[F[_],T](
                origin:Expr[T],
                originType: Type[T]
)

}


import x._

trait M1[F[_]] {}

case class TC[F[_],T](
   patternCode: Expr[T],  // code, for which we build pattern expression
   patternType: Type[T],
   m1: Expr[M1[F]],
)

object Async1 {

 def rootTransform[F[_]:Type,T:Type](f: Expr[T], dm:Expr[M1[F]])(
                                           given qctx: QuoteContext): CExprResult1[F,T] = ???

}


class AssignTransform1[F[_]:Type,T:Type](cpsCtx: TC[F,T])

  import cpsCtx._

  // case Assign(left,right)
  def run(given qctx: QuoteContext)(left: qctx.tasty.Term, right: qctx.tasty.Term): CExprResult1[F,T] = {
     import qctx.tasty.{_, given}
     val cpsLeft = left.seal match {
        case '{ $le: $lt } =>
            Async1.rootTransform(le,m1)
     }
     val cpsRight = right.seal match {
        case '{ $re: $rt } =>
            Async1.rootTransform(re,m1)
     }
     run1(left,right,cpsLeft,cpsRight)
     ???
  }


  def run1[L:Type,R:Type](given qctx: QuoteContext)(left: qctx.tasty.Term, right: qctx.tasty.Term,
                cpsLeft: CExprResult1[F,L], cpsRight: CExprResult1[F,R]): CExprResult1[F,T] =
     import qctx.tasty.{_, given}
     ???


```

<details>
<summary>Stack trace</summary>

```scala
error] assertion failed: unresolved symbols: value cpsLeft(line 42) when pickling /Users/rssh/tests/scala-misc/dotty/assigntp/assigntp/src/main/scala/a/AssignTransform1.scala
[error] dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:704)
[error] dotty.tools.dotc.core.quoted.PickledQuotes$.pickle(PickledQuotes.scala:103)
[error] dotty.tools.dotc.core.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:35)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.pickleAsTasty$1(ReifyQuotes.scala:236)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.pickledQuote(ReifyQuotes.scala:244)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformQuotation(ReifyQuotes.scala:196)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:93)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
[error] scala.collection.immutable.List.mapConserve(List.scala:444)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1257)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
[error] scala.collection.immutable.List.mapConserve(List.scala:444)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:105)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
[error] scala.collection.immutable.List.mapConserve(List.scala:444)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1333)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.transform.ReifyQuotes$$anon$1.transform(ReifyQuotes.scala:93)
[error] dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
[error] dotty.tools.dotc.transform.ReifyQuotes.run(ReifyQuotes.scala:89)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
[error] scala.collection.immutable.List.map(List.scala:219)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:161)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:171)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:179)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:186)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:123)
[error] dotty.tools.dotc.Run.compile(Run.scala:106)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
[error] dotty.tools.dotc.Driver.process(Driver.scala:189)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
```
</details>

### LINKED ISSUE #7997: Unresolved symbol in quoted class with spliced field reference
## minimized code

```Scala
import scala.quoted._
def oops(using QuoteContext) = {
  val q = '{ class Foo { val x = 3; ${ val v = 'x; '{} }  }}
}
```

<details>
<summary>Compilation output</summary>

```scala
java.lang.AssertionError: assertion failed: unresolved symbols: class Foo(line 3) when pickling Foo.scala while compiling Foo.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: class Foo(line 3) when pickling Foo.scala
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:704)
        at dotty.tools.dotc.core.quoted.PickledQuotes$.pickle(PickledQuotes.scala:102)
        at dotty.tools.dotc.core.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:34)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.pickleAsTasty$1(ReifyQuotes.scala:236)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.pickledQuote(ReifyQuotes.scala:248)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformQuotation(ReifyQuotes.scala:196)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:93)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1251)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1257)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1320)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:105)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:105)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformWithCapturer(ReifyQuotes.scala:355)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.body$3(ReifyQuotes.scala:329)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.$anonfun$1(ReifyQuotes.scala:339)
        at dotty.tools.dotc.ast.tpd$.polyDefDef(tpd.scala:262)
        at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:221)
        at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:115)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.makeLambda(ReifyQuotes.scala:339)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.splitSplice(ReifyQuotes.scala:376)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformSplice(ReifyQuotes.scala:266)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:99)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:105)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.splitQuote(ReifyQuotes.scala:371)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformQuotation(ReifyQuotes.scala:191)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:93)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1251)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1257)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1320)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:105)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1333)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
        at dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:415)
        at dotty.tools.dotc.transform.ReifyQuotes$$anon$1.transform(ReifyQuotes.scala:93)
        at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
        at dotty.tools.dotc.transform.ReifyQuotes.run(ReifyQuotes.scala:89)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
        at scala.collection.immutable.List.map(List.scala:219)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:192)
        at dotty.tools.dotc.Run.compileSources(Run.scala:129)
        at dotty.tools.dotc.Run.compile(Run.scala:112)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
        at dotty.tools.dotc.Driver.process(Driver.scala:189)
        at dotty.tools.dotc.Driver.process(Driver.scala:158)
        at dotty.tools.dotc.Driver.process(Driver.scala:170)
        at dotty.tools.dotc.Driver.main(Driver.scala:197)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

## expectation
Should compile

### LINKED ISSUE #8651: Unresolved symbols: when pickling file containing an anonymous class.
Hello,

In some file I defined an abstract class 
```Scala
abstract class Coroutine[+T] {
  def continue: Option[T] 
}
```

In another file of the same package I created an anonymous implementation of Coroutine. The continue implementation references a variable `state` defined within the anonymous class

 ```Scala
object Macros {
   
  import scala.quoted._
  import scala.quoted.matching._ 
     

  inline def coroutine[T](inline body: Any): Coroutine[T] = ${ coroutineImpl('{body}) }
 
  def coroutineImpl[T: Type](expr: Expr[_ <: Any])(implicit qtx: QuoteContext): Expr[Coroutine[T]] = {
    import qtx.tasty.{_, given _}

    '{
      new Coroutine[T] { 
        var state: Int = 0 

        def continue: Option[T] = ${
          '{
            state = 1 //if this line is commented there are no compile errors anymore!!!
            None
          }
        }
        
      }
    }

  }
}
```

My aim was initially to create a function `continue` which when called would go to the next state (by increasing the state variable which is the root of the problem here) of the coroutine class and return the value yielded at the current state. I minimized the code so it does not make any semantical sense any more (the value returned is None and the state only gets updated to 1). Also with this minimized code an additional warning spawns on the compiler log.

Compiling those two files provokes an error. This error disappears whenever the reference to the `state` variable within the expression built in the continue method is removed.
So this reference seems to be the root of the error:
```|Canceled quote directly inside a splice. ${ '{ XYZ } } is equivalent to XYZ```

Initially I referenced the state variable within a foldLeft that was within the splice of the continue method. This caused the same error(without the warning) whenever I referenced `state` within the foldLeft.

Here is the truncated error output (ignore the warning):

```
sbt:dotty-simple> compile
[info] Compiling 1 Scala source to /home/snif/hackerspace/semester/bugReproduction/target/scala-0.22/classes ...
[warn] -- Warning: /home/snif/hackerspace/semester/bugReproduction/src/main/scala/Macros.scala:18:34 
[warn] 18 |        def continue: Option[T] = ${
[warn]    |                                  ^
[warn]    |Canceled quote directly inside a splice. ${ '{ XYZ } } is equivalent to XYZ.
[warn] 19 |          '{
[warn] 20 |            state = 1
[warn] 21 |            None
[warn] 22 |          }
[warn] 23 |        }
[info] exception occurred while compiling /home/snif/hackerspace/semester/bugReproduction/src/main/scala/Macros.scala
java.lang.AssertionError: assertion failed: unresolved symbols: anonymous class coroutines.Coroutine[T] {...}(line 14) when pickling /home/snif/hackerspace/semester/bugReproduc
tion/src/main/scala/Macros.scala while compiling /home/snif/hackerspace/semester/bugReproduction/src/main/scala/Macros.scala
[error] ## Exception when compiling 2 sources to /home/snif/hackerspace/semester/bugReproduction/target/scala-0.22/classes
[error] java.lang.AssertionError: assertion failed: unresolved symbols: anonymous class coroutines.Coroutine[T] {...}(line 14) when pickling /home/snif/hackerspace/semester/bug
Reproduction/src/main/scala/Macros.scala
[error] dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:715)
[error] dotty.tools.dotc.core.quoted.PickledQuotes$.pickle(PickledQuotes.scala:102)
[error] dotty.tools.dotc.core.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:34)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.pickleAsTasty$1(ReifyQuotes.scala:236)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.pickledQuote(ReifyQuotes.scala:248)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformQuotation(ReifyQuotes.scala:196)
[error] dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:94)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.op$1(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:417)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1251)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
[error] dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.op$1(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:417)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1257)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
[error] dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.op$1(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:417)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
[error] dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.op$1(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:417)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
[error] scala.collection.immutable.List.mapConserve(List.scala:444)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
[error] dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
[error] dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
[error] dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
[error] dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:106)
[error] dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.op$1(ReifyQuotes.scala:415)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:417)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformWithCapturer(ReifyQuotes.scala:355)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.body$3(ReifyQuotes.scala:329)
[error] dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.$anonfun$1(ReifyQuotes.scala:339)
...
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fix #6140, fix #6772, fix #7030, fix #7892, fix #7997, fix #8651 and improve #8100.
    
Differences with previous implementation
* Only track and check levels within quotes or splices
* Track levels of all symbols not at level 0
* Split level checking into specialized variants for types and terms (healType/healTermType)
* Detect inconsistent types rather than try to detect consistent ones
* Check/heal term inconsistencies only on leaf nodes (TypeTree, RefTree, Ident, This)

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@odersky this PR is ready for review. The CLA failed to finish.

**Comment by nicolasstucki** [comment]
In our first implementation, we assumed that handling levels of type and terms would be quite similar. We said that types and term can only be used at the same level ... with some exceptions for types that can be healed or are used at a lower level in a macro.

Since then we have realized that in general types can be used at any level, but if used in a larger level they must be healed. In the previous implementation tried to patch this in different places. Instead, this one handles types and terms as two different entities that need to be handled in their own way.

**Comment by nicolasstucki** [comment]
Rebased

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 1]
```diff
@@ -83,188 +129,122 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
...
-
-    /* Is a reference to an `<init>` method on a class with a static path */
-    def isStaticNew(tp1: Type): Boolean = tp1 match
-      case tp1: TermRef => tp1.symbol.isConstructor && isStaticPathOK(tp1.prefix)
-      case _ => false
-
-    if (!sym.exists || levelOK(sym) || isStaticPathOK(tp) || isStaticNew(tp))
-      None
-    else if (!sym.isStaticOwner && !isClassRef)
+  /** Check phase consistency of terms and heal incosistent type references. */
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala:195]: inconsistent

Also, maybe rename to `healTypeOfTerm`? i was confused in what way `healType` and `healTermType` are different.
