### PR TITLE
Don't explain erroneous bounds

### LINKED ISSUE #19334: Compiler hangs instead of throwing error when expanding anonymous function
## Compiler version

Hangs on `3.4.0-RC1-bin-20231223-938d405-NIGHTLY`
Fails to compile on `3.3.0`

## Minimized code

```Scala
//> using scala 3.4.0-RC1-bin-20231223-938d405-NIGHTLY

def foo[T](f: T): T = ???

@main
def main =
  foo {
    def f() = { }
    f(_)
  }
```

## Output

On `3.4.0-RC1-bin-20231223-938d405-NIGHTLY`:
```scala
Compiling project (Scala 3.4.0-RC1-bin-20231223-938d405-NIGHTLY, JVM)
<hangs forever>
```

On `3.3.0`:
```scala
[error] ./Main.scala:9:7
[error] Missing parameter type
[error] 
[error] I could not infer the type of the parameter _$1 of expanded function:
[error] _$1 => f(_$1).
[error]     f(_)
[error]   
```

## Expectation
Unsure, I don't know what change caused this.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #19334

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/Message.scala [hunk 1]
```diff
@@ -146,7 +145,7 @@ object Message:
       }
 
       def addendum(cat: String, info: Type): String = info match {
-        case bounds @ TypeBounds(lo, hi) if !(bounds =:= TypeBounds.empty) =>
+        case bounds @ TypeBounds(lo, hi) if !(bounds =:= TypeBounds.empty) && !lo.isErroneous && !hi.isErroneous =>
```
Comment (joroKr21) [inline compiler/src/dotty/tools/dotc/reporting/Message.scala:148]: Does this work?
```suggestion
        case bounds @ TypeBounds(lo, hi) if !(bounds =:= TypeBounds.empty) && !bounds.isErroneous =>
```

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/reporting/Message.scala:148]: maybe, and maybe better when lo eq hi. I'll try it when I have sufficiently recovered from this PR.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/reporting/Message.scala]: I should have just hit the commit suggestion button. My new year's resolution is to be bold in '24.

**Review by joroKr21 — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/reporting/Message.scala [hunk 2]
```diff
@@ -176,8 +175,8 @@ object Message:
       def needsExplanation(entry: Recorded) = entry match {
         case param: TypeParamRef => ctx.typerState.constraint.contains(param)
         case param: ParamRef     => false
-        case skolem: SkolemType => true
-        case sym: Symbol =>
+        case skolem: SkolemType  => true
+        case sym: Symbol         =>
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/reporting/Message.scala:179]:
```suggestion
        case sym: Symbol =>
```
There is nothing on the right of `=>` to align.

File: compiler/src/dotty/tools/dotc/reporting/Message.scala [hunk 3]
```diff
@@ -176,8 +175,8 @@ object Message:
       def needsExplanation(entry: Recorded) = entry match {
         case param: TypeParamRef => ctx.typerState.constraint.contains(param)
         case param: ParamRef     => false
-        case skolem: SkolemType => true
-        case sym: Symbol =>
+        case skolem: SkolemType  => true
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/reporting/Message.scala:178]:
```suggestion
        case skolem: SkolemType => true
```

File: tests/neg/i19334.scala [hunk 4]
```diff
@@ -0,0 +1,6 @@
+
+def foo[T](f: T): T = ???
+
+@main def main = foo:
+  def f() = ()
+  f(_) // error was OOM formatting TypeVar(TypeParamRef(T)) when offering explanations
```
Comment (nicolasstucki) [inline tests/neg/i19334.scala:6]: it might be worth adding a `tests/neg/i19334.check` file for this one.

File: compiler/src/dotty/tools/dotc/reporting/Message.scala (hunk 2 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/reporting/Message.scala:179]: Thanks, I go back & forth on this style. The question is, in mix of one-liners, is the odd arrow also aligned?

Also default case: `case _ => ???` where it's always ugly to align.

I'm not a huge fan of formatters, but for this use case, it would restore my decision budget.

File: tests/neg/i19334.scala (hunk 4 above)
Comment (som-snytt) [reply tests/neg/i19334.scala:6]: footnote I had one locally. I'm unaccustomed to the dotty-local customs around check files.

File: compiler/src/dotty/tools/dotc/reporting/Message.scala [hunk 5]
```diff
@@ -176,8 +175,8 @@ object Message:
...
+        case sym: Symbol         =>
           ctx.gadt.contains(sym) && ctx.gadt.fullBounds(sym) != TypeBounds.empty
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/reporting/Message.scala:180]: This equality check looks like the previous tweak to use `=:=` for this comparison. I have not yet investigated / learned about it.

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
@som-snytt could you squash the commits before we merge?

**Comment by som-snytt** [comment]
Thanks, squashed.
