### PR TITLE
Detect `InsertedApply` on `Apply` to break synthetic apply loops, not just `Select`

### LINKED ISSUE #24782: Stackoverflow due to infinite loop in ProtoTypes
## Compiler version

3.7.4, 3.8.1-RC1-bin-20251220-327be51-NIGHTLY

## Minimized code

```Scala
object S {
  trait F[A]
  type Pure = [a] => a => F[a]
  def f(using pure: Pure) = S(s => pure(s))
}
```

## Output (click arrow to expand)

<details>

```scala
$ scala-cli --server=false -S 3.nightly state.scala

  Exception while compiling /home/ejbyfeldt/dev/scala_playground/state.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: <no file>
        during phase: parser
                mode: Mode()
     library version: version 3.8.1-RC1-bin-20251220-327be51-NIGHTLY
    compiler version: version 3.8.1-RC1-bin-20251220-327be51-NIGHTLY-git-327be51
            settings: -classpath /home/ejbyfeldt/.cache/coursier/v1/https/repo.scala-lang.org/artifactory/maven-nightlies/org/scala-lang/scala3-library_3/3.8.1-RC1-bin-20251220-327be51-NIGHTLY/scala3-library_3-3.8.1-RC1-bin-20251220-327be51-NIGHTLY.jar:/home/ejbyfeldt/.cache/coursier/v1/https/repo.scala-lang.org/artifactory/maven-nightlies/org/scala-lang/scala-library/3.8.1-RC1-bin-20251220-327be51-NIGHTLY/scala-library-3.8.1-RC1-bin-20251220-327be51-NIGHTLY.jar -d /home/ejbyfeldt/dev/scala_playground/.scala-build/scala_playground_0ea6010142-ceebb4ae3c/classes/main -sourceroot /home/ejbyfeldt/dev/scala_playground

Exception in thread "main" java.lang.StackOverflowError
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isStaticOwner(SymDenotations.scala:759)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.isStatic(SymDenotations.scala:754)
	at dotty.tools.dotc.core.Symbols$Symbol.isStatic(Symbols.scala:218)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:966)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:970)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1$$anonfun$1(ProtoTypes.scala:969)
	at scala.collection.immutable.List.loop$3(List.scala:466)
	at scala.collection.immutable.List.mapConserve(List.scala:491)
	at dotty.tools.dotc.typer.ProtoTypes$.wildArgs$1(ProtoTypes.scala:969)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:977)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:988)
	at dotty.tools.dotc.typer.ProtoTypes$.wildApproxBounds$1(ProtoTypes.scala:994)
	at dotty.tools.dotc.typer.ProtoTypes$.approxPoly$1(ProtoTypes.scala:1000)
	at dotty.tools.dotc.typer.ProtoTypes$.dotty$tools$dotc$typer$ProtoTypes$$$wildApprox(ProtoTypes.scala:1004)
...
```
</details>

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #24782 

The code attaches `InsertedApply` to `Apply` nodes sometimes, without looking for it we end up in an infinite loop

## How much have your relied on LLM-based tools in this contribution?

not

## How was the solution tested?

new automated test

### CODE REVIEW

File: tests/pos/i14907.scala [hunk 1]
```diff
@@ -5,7 +5,7 @@ object Module {
     case 1 => Any *: Fill[0]
   }
   extension[N <: Int] (f: Fun[N])
-    def apply: Fill[N] => Any = ???
+    def apply(): Fill[N] => Any = ???
 
-  Fun[1]()(???)
+  Fun[1]()()(???)
```
Comment (SolalPirelli) [inline tests/pos/i14907.scala:10]: As discussed on Slack, per §6.6 of the language ref, `apply` should only be used if there are parameters. This is the only positive test I could find in which this was happening.

File: tests/neg/24782.scala
Comment (hamzaremmal) [inline tests/neg/24782.scala:1]: checkfile is missing :)

File: tests/pos/i14907.scala [hunk 2]
```diff
@@ -5,7 +5,7 @@ object Module {
     case 1 => Any *: Fill[0]
   }
   extension[N <: Int] (f: Fun[N])
-    def apply: Fill[N] => Any = ???
+    def apply(): Fill[N] => Any = ???
```
Comment (hamzaremmal) [inline tests/pos/i14907.scala:8]: > https://github.com/scala/scala3/pull/25463/changes#r2906064294

So defining `def apply` is not allowed?

Comment (SolalPirelli) [reply tests/pos/i14907.scala:8]: per conversation on Slack, no, parameterless apply should not be used since the language reference only talks about parameterized insertions of apply, see the recent thread in compiler-development

File: tests/neg/24782.scala
Comment (SolalPirelli) [reply tests/neg/24782.scala:1]: oops, thanks, added

File: tests/pos/i14907.scala (hunk 2 above)
Comment (hamzaremmal) [reply tests/pos/i14907.scala:8]: Okay, then can we have a clear test that shows explicitly this. Something like:
```scala
object A:
  def apply: Int = ???

val x: Int = A // error: must call apply explicitly
```

This test and the other have too many elements in them that it is not clear what their purpose is.

Comment (SolalPirelli) [reply tests/pos/i14907.scala:8]: It would be nice to have some systematic tests of language features, yeah, but for that we'd need an unambiguous language reference first, the slack thread already mentions some corner cases like "what if apply is of a custom function-like type". :/

Comment (hamzaremmal) [reply tests/pos/i14907.scala:8]: > but for that we'd need an unambiguous language reference first

I agree. If that is intended to be the case, and if you find the wording to be ambiguous, you can also update the wording to at least cover this case?

Comment (SolalPirelli) [reply tests/pos/i14907.scala:8]: created https://github.com/scala/scala3/issues/25504
