### PR TITLE
Fix #7383: Don't include nested classes in class bounds

### LINKED ISSUE #7383: Compiler Crashes When Attempting to Compile ZIO Streams
We are trying to compile ZIO Streams against Dotty in zio/zio#1928 and after addressing what seemed to be some relatively minor migration issues (needing to add parentheses around a parameter to a lambda, adding type arguments to work around #7382) we are now seeing the compiler crash. I realize this is the opposite of a minimized example but at least for me it is difficult to tell from this stack trace what this issue is or how to address it. Any help would be much appreciated!

Copying @iravid.

```
[info] exception occurred while compiling /home/circleci/project/streams/jvm/src/main/scala/zio/stream/platform.scala, /home/circleci/project/streams/jvm/target/scala-0.19/src_managed/main/sbt-buildinfo/BuildInfo.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/Sink.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/SinkPure.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/Stream.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/StreamEffect.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/StreamEffectChunk.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/Take.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/ZSink.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/ZStream.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/ZStreamChunk.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/package.scala
scala.MatchError: ClassInfo(RecThis(-498578181), class State, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object))) (of class dotty.tools.dotc.core.Types$CachedClassInfo) while compiling /home/circleci/project/streams/jvm/src/main/scala/zio/stream/platform.scala, /home/circleci/project/streams/jvm/target/scala-0.19/src_managed/main/sbt-buildinfo/BuildInfo.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/Sink.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/SinkPure.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/Stream.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/StreamEffect.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/StreamEffectChunk.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/Take.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/ZSink.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/ZStream.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/ZStreamChunk.scala, /home/circleci/project/streams/shared/src/main/scala/zio/stream/package.scala
[error] ## Exception when compiling 12 sources to /home/circleci/project/streams/jvm/target/scala-0.19/classes
[error] scala.MatchError: ClassInfo(RecThis(-498578181), class State, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object))) (of class dotty.tools.dotc.core.Types$CachedClassInfo)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:267)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:140)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleNewType$$anonfun$4(TreePickler.scala:224)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:225)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:140)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:228)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:140)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:542)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTpt(TreePickler.scala:291)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$5(TreePickler.scala:412)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:412)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$8(TreePickler.scala:423)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:423)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTreeUnlessEmpty(TreePickler.scala:294)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$2(TreePickler.scala:308)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:310)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:504)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:329)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:329)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$25(TreePickler.scala:530)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:531)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$2(TreePickler.scala:305)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:310)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:506)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:329)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:329)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$25(TreePickler.scala:530)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:531)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$2(TreePickler.scala:305)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:310)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:506)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:329)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:329)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$27(TreePickler.scala:540)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:540)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle$$anonfun$1(TreePickler.scala:695)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:695)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$10$$anonfun$8(Pickler.scala:63)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.transform.Pickler.run$$anonfun$2(Pickler.scala:87)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:305)
[error] dotty.tools.dotc.transform.Pickler.run(Pickler.scala:87)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
[error] scala.collection.immutable.List.map(List.scala:223)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
[error] dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:91)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:159)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:169)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:177)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:184)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:121)
[error] dotty.tools.dotc.Run.compile(Run.scala:104)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error] dotty.tools.dotc.Driver.process(Driver.scala:178)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1757)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1730)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:289)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] scala.MatchError: ClassInfo(RecThis(-498578181), class State, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object))) (of class dotty.tools.dotc.core.Types$CachedClassInfo)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:267)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:140)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleNewType$$anonfun$4(TreePickler.scala:224)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:225)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:140)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleNewType(TreePickler.scala:228)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleType(TreePickler.scala:140)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:542)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTpt(TreePickler.scala:291)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$5(TreePickler.scala:412)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:412)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$8(TreePickler.scala:423)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:423)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTreeUnlessEmpty(TreePickler.scala:294)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$2(TreePickler.scala:308)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:310)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:504)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:329)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:329)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$25(TreePickler.scala:530)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:531)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$2(TreePickler.scala:305)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:310)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:506)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:329)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:329)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$25(TreePickler.scala:530)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:531)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleDef$$anonfun$2(TreePickler.scala:305)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleDef(TreePickler.scala:310)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:506)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleStats$$anonfun$2(TreePickler.scala:329)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleStats(TreePickler.scala:329)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree$$anonfun$27(TreePickler.scala:540)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.withLength(TreePickler.scala:44)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickleTree(TreePickler.scala:540)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickle$$anonfun$1(TreePickler.scala:695)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:695)
[error] 	at dotty.tools.dotc.transform.Pickler.run$$anonfun$10$$anonfun$8(Pickler.scala:63)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at dotty.tools.dotc.transform.Pickler.run$$anonfun$2(Pickler.scala:87)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at dotty.tools.dotc.transform.Pickler.run(Pickler.scala:87)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
[error] 	at scala.collection.immutable.List.map(List.scala:223)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
[error] 	at dotty.tools.dotc.transform.Pickler.runOn(Pickler.scala:91)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:159)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:169)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:177)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:184)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:121)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:104)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:178)
[error] 	at dotty.tools.dotc.Main.process(Main.scala)
[error] 	at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1757)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1730)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (streamsJVM / Compile / compileIncremental) scala.MatchError: ClassInfo(RecThis(-498578181), class State, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object))) (of class dotty.tools.dotc.core.Types$CachedClassInfo)
[error] Total time: 7 s, completed Oct 7, 2019 5:12:24 PM
Exited with code 1
```

### PR DESCRIPTION
**Pull request by odersky**
When computing the class bound in an avoid, we approximate
members by refinements. But if the member itself is a class,
we cannot refine with  Classinfo type.

The current fix is to give up in this case and not refine
anything. We could try to refine with an abstract type, but
in that case we have to be careful with F-bounds.

### CODE REVIEW

File: tests/pos/i7383.scala [hunk 1]
```diff
@@ -0,0 +1,12 @@
+trait ZSink {
+
+  type State
+
+  def foo: ZSink =
+    class Anon extends ZSink
```
Comment (smarter) [inline tests/pos/i7383.scala]: I'd add back the braces here to make sure that file doesn't stop working or change meaning if the syntax changes.

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala [hunk 2]
```diff
@@ -57,13 +57,15 @@ trait TypeAssigner {
...
       val inheritedInfo = inherited.info
       val isPolyFunctionApply = decl.name == nme.apply && (parent <:< defn.PolyFunctionType)
-      if (isPolyFunctionApply || inheritedInfo.exists &&
-          decl.info.widenExpr <:< inheritedInfo.widenExpr &&
-          !(inheritedInfo.widenExpr <:< decl.info.widenExpr)) {
+      if isPolyFunctionApply
+         || inheritedInfo.exists
+            && decl.info.widenExpr <:< inheritedInfo.widenExpr
+            && !(inheritedInfo.widenExpr <:< decl.info.widenExpr)
+            && !decl.isClass
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: since this is a cheap test it could be moved before the subtype checks.
