### PR TITLE
Properly dealias tuple types when specializing

### LINKED ISSUE #18638: Tuple specialisation doesn't correctly see type
## Compiler version

Welcome to Scala 3.3.1 (17.0.8.1, Java OpenJDK 64-Bit Server VM).

## Minimized code

```Scala
type U[H, T] = (Unit, Unit)

(((), ()): U[Int, Int]) match
  case ((), ()) => println("ok")
```

## Output

```scala
java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class java.lang.Integer (scala.runtime.BoxedUnit is in unnamed module of loader java.net.URLClassLoader @5eefa415; java.lang.Integer is in module java.base of loader 'bootstrap')
```

## Expectation

- Should print "ok".
- Should behave the same as when unannotated or annotated with result of manually applying type alias to parameters:

```scala
(((), ()): (Unit, Unit)) match
  case ((), ()) => println("ok")
```

```scala
ok
```

## Additional observations

- This problem did not occur in Scala 3.1.x, and I first observed it in Scala 3.2.0.
- The problem seems to occur only for Tuple2 and 2-ary type aliases.
- The problem occurs for two, not necessary equal, integer-based actual type parameters: Boolean, Char, Int, Long
- It doesn't matter what the concrete tuple element types are, as long as at least one of them is different from the corresponding actual type parameter.
- It doesn't make a difference if the type parameters are actually used, e.g., 
   ```scala
   type ListNodeF[H, T] = (H, Option[T])
   ```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #18638

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/SpecializeTuples.scala [hunk 1]
```diff
@@ -37,15 +37,14 @@ class SpecializeTuples extends MiniPhase:
   end transformApply
 
   override def transformSelect(tree: Select)(using Context): Tree = tree match
-    case Select(qual, nme._1) if isAppliedSpecializableTuple(qual.tpe.widen) =>
-      Select(qual, nme._1.specializedName(qual.tpe.widen.argInfos.slice(0, 1)))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/SpecializeTuples.scala:41]: The issue was that `qual.tpe.widen` returned `U[Int, Int]`, `isAppliedSpecializableTuple` detected the tuple type through internal aliasing, but `qual.tpe.widen.argInfos` used the args of `U[Int, Int]` instead of the args of its dealiased type `Tuple2[Unit, Unit]`

**Review by dwijnand — APPROVED** [review]
