### PR TITLE
Fix #9538: repl crashes when :type and :doc are invoked with an empty expression

### LINKED ISSUE #9538: REPL crashes when using :type or :doc command without any parameter
## Minimized code

```Scala
scala> :type
// or
scala> :doc
```

## Output (click arrow to expand)

_REPL crashes after executing such line_

<details>

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at dotty.tools.dotc.util.SourceFile.lineToOffset(SourceFile.scala:124)
	at dotty.tools.dotc.util.SourcePosition.lineOffsets$$anonfun$1(SourcePosition.scala:40)
	at dotty.runtime.function.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:12)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.util.SourcePosition.lineOffsets(SourcePosition.scala:40)
	at dotty.tools.dotc.util.SourcePosition.beforeAndAfterPoint(SourcePosition.scala:43)
	at dotty.tools.dotc.reporting.MessageRendering.sourceLines(MessageRendering.scala:71)
	at dotty.tools.dotc.reporting.MessageRendering.sourceLines$(MessageRendering.scala:18)
	at dotty.tools.repl.Rendering$$anon$1.sourceLines(Rendering.scala:35)
	at dotty.tools.dotc.reporting.MessageRendering.messageAndPos(MessageRendering.scala:152)
	at dotty.tools.dotc.reporting.MessageRendering.messageAndPos$(MessageRendering.scala:18)
	at dotty.tools.repl.Rendering$$anon$1.messageAndPos(Rendering.scala:35)
	at dotty.tools.repl.Rendering.formatError$$anonfun$1(Rendering.scala:100)
	at dotty.tools.dotc.reporting.NoExplanation.msg(Message.scala:120)
	at dotty.tools.dotc.reporting.NoExplanation.toString(Message.scala:124)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)
	at dotty.tools.repl.ReplDriver.displayErrors$$anonfun$3(ReplDriver.scala:399)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.repl.ReplDriver.displayErrors(ReplDriver.scala:399)
	at dotty.tools.repl.ReplDriver.interpretCommand$$anonfun$2(ReplDriver.scala:380)
	at scala.util.Either.fold(Either.scala:190)
	at dotty.tools.repl.ReplDriver.interpretCommand(ReplDriver.scala:381)
	at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:203)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:129)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:132)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:151)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:132)
	at dotty.tools.repl.Main$.main(Main.scala:6)
	at dotty.tools.repl.Main.main(Main.scala)
```
</details>

### PR DESCRIPTION
**Pull request by december32**
The `:type` and `:doc` commands now handle being invoked with an empty expression gracefully by printing the corresponding usage text, similar to the repl in Scala 2.
```scala
scala>:type
:type <expression>.

scala>:doc
:doc <expression>.
```

### CODE REVIEW

File: compiler/src/dotty/tools/repl/ReplDriver.scala [hunk 1]
```diff
@@ -376,17 +376,25 @@ class ReplDriver(settings: Array[String],
       }
 
     case TypeOf(expr) =>
-      compiler.typeOf(expr)(newRun(state)).fold(
-        displayErrors,
-        res => out.println(SyntaxHighlighting.highlight(res)(using state.context))
-      )
+      expr match {
+        case "" => out.println(s":type <expression>.")
```
Comment (liufengyun) [inline compiler/src/dotty/tools/repl/ReplDriver.scala:380]:
```suggestion
        case "" => out.println(s":type <expression>")
```

File: compiler/src/dotty/tools/repl/ReplDriver.scala [hunk 2]
```diff
@@ -376,17 +376,25 @@ class ReplDriver(settings: Array[String],
...
+      }
       state
 
     case DocOf(expr) =>
-      compiler.docOf(expr)(newRun(state)).fold(
-        displayErrors,
-        res => out.println(res)
-      )
+      expr match {
+        case "" => out.println(s":doc <expression>.")
```
Comment (liufengyun) [inline compiler/src/dotty/tools/repl/ReplDriver.scala:391]:
```suggestion
        case "" => out.println(s":doc <expression>")
```

File: compiler/test-resources/repl/i9538 [hunk 3]
```diff
@@ -0,0 +1,5 @@
+scala>:type
+:type <expression>.
```
Comment (liufengyun) [inline compiler/test-resources/repl/i9538:2]:
```suggestion
:type <expression>
```

File: compiler/test-resources/repl/i9538 [hunk 4]
```diff
@@ -0,0 +1,5 @@
...
+
+scala>:doc
+:doc <expression>.
```
Comment (liufengyun) [inline compiler/test-resources/repl/i9538:5]:
```suggestion
:doc <expression>
```

File: compiler/test/dotty/tools/repl/DocTests.scala [hunk 5]
```diff
@@ -177,6 +177,12 @@ class DocTests extends ReplTest {
       assertEquals("Expansion: some-value", doc("Foo.hello"))
     }
 
+  @Test def docOfEmpty =
+    fromInitialState { implicit s =>
+    run(":doc")
+    assertEquals(":doc <expression>.", storedOutput().trim)
```
Comment (december32) [inline compiler/test/dotty/tools/repl/DocTests.scala:183]:
```suggestion
    assertEquals(":doc <expression>", storedOutput().trim)
```

File: compiler/test/dotty/tools/repl/TypeTests.scala [hunk 6]
```diff
@@ -21,4 +21,9 @@ class TypeTests extends ReplTest {
       run(":type x")
       assertEquals("Int", storedOutput().trim)
     }
+
+  @Test def typeOfEmpty = fromInitialState { implicit s =>
+    run(":type")
+    assertEquals(":type <expression>.", storedOutput().trim)
```
Comment (december32) [inline compiler/test/dotty/tools/repl/TypeTests.scala:27]:
```suggestion
    assertEquals(":type <expression>", storedOutput().trim)
```
