### PR TITLE
Fix #3443: adapt child compatibility check

### LINKED ISSUE #3443: Incorrect MatchCaseUnreachable warning on Coproduct
Here is an example where Dotty incorrectly reports an unreachable case in pattern marching:

```scala
object Test {
  // shapeless.Coproduct
  sealed trait Coproduct extends Product with Serializable
  sealed trait :+:[+H, +T <: Coproduct] extends Coproduct
  final case class Inl[+H, +T <: Coproduct](head : H) extends :+:[H, T]
  final case class Inr[+H, +T <: Coproduct](tail : T) extends :+:[H, T]
  sealed trait CNil extends Coproduct

  // Note that this only appears when T is a type parameter. Replaying T with
  // a concrete type (CNil or another :+:) leads to accurate warnnings
  def f[T <: Coproduct](fa: Int :+: T) =
    fa match {
      case Inl(x) => 1
      case Inr(x) => 2 // Dotty thinks this unreachable, but it is!
    }

  def main(args: Array[String]): Unit =
    assert(f(Inr(Inl(-1))) == 2) // Example of reachability
}
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #3443

Previously, the child compatibility check will result in a check like `CNil <: TVar(Nothing..Coproduct)`, which failed. Now we expose type param according to its variance. We only resort to `TVar` if the variance is 0.

This PR also removes the `@unchecked` check, as agreed with @allanrenucci the check should be somewhere else and handle more complex cases.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -778,41 +780,41 @@ class SpaceEngine(implicit ctx: Context) extends SpaceLogic {
    *
    *  A <: X :> Y  B <: U :> V   M { type T <: A :> B }  ~~>  M { type T <: X :> V }
    */
-  def expose(tp: Type, refineCtx: Boolean = false, up: Boolean = true): Type = tp match {
+  def expose(tp: Type, up: Boolean = true): Type = tp match {
```
Comment (OlivierBlanvillain) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: I would remove the default value here

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 2]
```diff
@@ -606,20 +606,19 @@ class SpaceEngine(implicit ctx: Context) extends SpaceLogic {
...
-            if (variance == 0) tp.underlying.bounds      // non-variant case is not well-founded
-            else if (variance == 1) TypeBounds.upper(tp)
-            else TypeBounds.lower(tp)
-          newTypeVar(bound)
+          val exposed =
+            if (variance == 0) newTypeVar(tp.underlying.bounds)
+            else if (variance == 1) expose(tp, true)
+            else expose(tp, false)
+
+          debug.println(s"$tp exposed to =====> " + exposed)
```
Comment (OlivierBlanvillain) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: You could put `$exposed` inside the string

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: I just removed the whole method :)
