### PR TITLE
Fix #9413: Fix test for user-defined equality

### LINKED ISSUE #9413: Value class equality boxes
## Minimized example

Compile the following with -Xprint:elimErasedValueType

```Scala
class ApproxState(private val bits: Int) extends AnyVal

object Main {
  val FreshApprox: ApproxState = new ApproxState(4)
  var approx: ApproxState = FreshApprox
  println(approx == FreshApprox)
}
```

## Output

The last statement compiles to:

```scala
    println(
      scala.Boolean.box(
        new ApproxState(Main.approx()).==(new ApproxState(Main.FreshApprox()))
      )
    )
```

## Expectation

No boxing

### PR DESCRIPTION
**Pull request by odersky**
Fix test to determine whether value class has a user-defined equality

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/VCElideAllocations.scala [hunk 1]
```diff
@@ -23,13 +23,16 @@ class VCElideAllocations extends MiniPhase with IdentityDenotTransformer {
   override def runsAfter: Set[String] = Set(ElimErasedValueType.name)
 
   override def transformApply(tree: Apply)(using Context): Tree =
+    def hasUserDefinedEquals(tp: Type): Boolean =
+      val eql = defn.Any_equals.overridingSymbol(tp.typeSymbol.asClass)
+      eql.exists && !eql.is(Synthetic)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/VCElideAllocations.scala:28]: Hmm, looks like vc-equals.scala is failing because we get a mixin forwarder `equals` in `D`, adding `butNot = Bridge` should fix that. Additionally, I think `overridingSymbol` only looks for symbols in the class itself since it calls `matchingDecl`, whereas we want `matchingMember` here.

**Comment by odersky** [comment]
Looks like it works now. Let's get it in!

File: compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala [hunk 2]
```diff
@@ -22,16 +22,12 @@ import reporting.trace
  * By comparison: Constraint handlers are parts of type comparers and can use their functionality.
  * Constraint handlers update the current constraint as a side effect.
  */
-trait ConstraintHandling[AbstractContext] {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala:25]: Looks like some unrelated changes made it here

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala:25]: Ah since it's fasttrack I don't mind removing them.
