### PR TITLE
Fix #2887: Add regression test

### LINKED ISSUE #2887: IndexOutOfBoundsException when attempting to reduce ill-kinded types
The following snippet is a variant of that causing #2771:

```Scala
trait A { type L[G[F[_],_],H[F[_],_]] }
trait B { type L[F[_],_] }
trait C { type M <: A }
trait D { type M >: B }

object Test {
  def test(x: C with D): Unit = {
    def foo(a: A, b: B)(z: a.L[b.L,b.L]) = z
    def bar(y: x.M, b: B) = foo(y, b)
    def baz(b: B) = bar(b, b)
    baz(new B { type L[F[_],X] = F[X] })(1)
  }
}
```

The underlying issue is likely the same, though the error message is different:

    exception occurred while compiling Test.scala
    Exception in thread "main" java.lang.IndexOutOfBoundsException: 1
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
        at scala.collection.immutable.List.apply(List.scala:84)
        at dotty.tools.dotc.core.Substituters$class.substParams(Substituters.scala:220)
        ...

The error disappears when the last line (the call to `baz`) is commented out. See #2771 for a more in-depth discussion.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: tests/neg/i2887b.scala [hunk 1]
```diff
@@ -0,0 +1,13 @@
+trait A { type S[X[_] <: [_] => Any, Y[_]] <: [_] => Any; type I[_] } // error // error
```
Comment (sstucki) [inline tests/neg/i2887b.scala:1]: There are errors in this file. The syntax of type lambdas is now `[_] =>>` rather than `[_] =>`.

**Review by sstucki — COMMENTED** [review]
See also my [comment](https://github.com/lampepfl/dotty/issues/2887#issuecomment-737864419) at #2887.

Unfortunately I couldn't figure out how to re-open the issue. Maybe I don't have the rights to do so?
