### PR TITLE
Fix #24573: Add stricter checks for platform SAM compatibility

### LINKED ISSUE #24573: Runtime `LambdaConversionException` failure for valid lambda invocation
Based on the user report https://contributors.scala-lang.org/t/scala-3-8-0-release-thread/7291/17 in `ichoran/kse3` project

## Compiler version
3.8.0-RC2 

Last good release: 3.8.0-RC1-bin-20250817-8c3f1a6-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250818-aaa39c5-NIGHTLY
Bisect points to aaa39c5f816253476c2b97e8bcc75e4c400c17f2 (most likely unrelated)

## Minimized code

```scala
trait Con[-T] extends (T => Unit):
  def apply(t: T): Unit

@main def Test =
    val c: Con[Int] = i => println(i)
    c(2)
```

## Output

```scala
Compiled project (Scala 3.8.1-RC1-bin-20251128-fe49539-NIGHTLY, JVM (21))
Exception in thread "main" java.lang.BootstrapMethodError: bootstrap method initialization exception
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274)
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264)
        at test$package$.Test(test.scala:5)
        at Test.main(test.scala:4)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda expected return: void is not convertible to class java.lang.Object
        at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.checkDescriptor(AbstractValidatingLambdaMetafactory.java:336)
        at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:315)
        at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:535)
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:147)
        ... 5 more
```

## Expectation

Should execute successfully

### PR DESCRIPTION
**Pull request by noti0na1**
This PR fixes issue #24573 by adding stricter checks for platform SAM compatibility.

The regression issue starts from version 3.8.0 where `Function1` and related traits gained the `NoInits` flag (I guess due to the way we read from jvm bytecode or from tasty?). 
This changes how the compiler determines whether a SAM type qualifies as a platform SAM. When a trait is classified as a Java platform SAM, the compiler uses `invokedynamic` with `LambdaMetaFactory` (LMF) to create the lambda at runtime, rather than expanding it into an anonymous class at compile time. This is more efficient, but LMF has limitations on what type adaptations it can perform automatically. 

It turns out the logic regarding SAM traits extending other traits has problems from the beginning, and even in Scala 2. The code from the issue works before 3.8 is totally by accident (because we always expand the SAM trait extending `FunctionN`).
We can reproduce the runtime exception using a custom function class (in Scala 2, and Scala 3.0~8):

```scala
trait F1[-T, +R]:
  def apply(t: T): R

trait SF[-T] extends F1[T, Unit]:
  def apply(t: T): Unit

@main def Test =
  val sf: SF[String] = i => println(i)
  sf("") // exception here
  // Caused by: java.lang.invoke.LambdaConversionException: 
  //Type mismatch for lambda expected return: void is not convertible to class java.lang.Object
```

From the view of Scala, `SF` is a valid SAM, because it has one abstract function `def apply(t: T): Unit`. However, after erasure, the `apply` of `F1` becomes `Object apply(Object)`, and the apply of `SF` becomes `void apply(Object)`, which are two different abstract functions; hence, `SF` is not qualifies as a function interface on JVM. This is not only for `Unit` type, any primitive number type can cause the similar problem.

Therefore, we have to expand the rhs of `val sf: SF[String] = i => println(i)` into an anonymous class and implement all the bridge functions.

This PR strengthen the SAM check on Java platform by adding a function called `samNotNeededExpansion` to check if the SAM method's erased signature is compatible with all overridden methods.  It mirrors the logic in `Erasure.Boxing.adaptClosure` to determine what LMF can and cannot auto-adapt.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/config/JavaPlatform.scala [hunk 1]
```diff
@@ -50,7 +50,10 @@ class JavaPlatform extends Platform {
     cls.superClass == defn.ObjectClass &&
     cls.directlyInheritedTraits.forall(_.is(NoInits)) &&
     !ExplicitOuter.needsOuterIfReferenced(cls) &&
-    cls.typeRef.fields.isEmpty // Superaccessors already show up as abstract methods here, so no test necessary
+    // Superaccessors already show up as abstract methods here, so no test necessary
+    cls.typeRef.fields.isEmpty &&
+    // LambdaMetafactory can't handle SAMs with Unit return type unless it's a FunctionN itself
+    !cls.typeRef.possibleSamMethods.exists(_.info.resultType.isRef(defn.UnitClass))
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/config/JavaPlatform.scala]: No this is not the correct fix. LMF can handle `Unit` result types all right.

It cannot handle the *conflicting requirements* of having both `Unit` and non-`Unit`, because of a bridge.

**Comment by noti0na1** [comment]
~Still WIP~

File: compiler/src/dotty/tools/dotc/core/TypeErasure.scala [hunk 2]
```diff
@@ -586,7 +586,102 @@ object TypeErasure {
...
+   *  to be qualifies as a valid functional interface on JVM.
+   *  This method returns true if all overridden methods have compatible erased signatures
+   *  that LMF can auto-adapt (or don't need adaptation).
+   *
+   *  When this returns true, the SAM class does not need to be expanded.
+   *
+   *  @param cls  The SAM class to check
+   *  @return     true if LMF can handle the required adaptation
+   */
+  def samNotNeededExpansion(cls: ClassSymbol)(using Context): Boolean = cls.typeRef.possibleSamMethods match
```
Comment (bracevac) [inline compiler/src/dotty/tools/dotc/core/TypeErasure.scala]:
```suggestion
  def samExpansionNotNeeded(cls: ClassSymbol)(using Context): Boolean = cls.typeRef.possibleSamMethods match
```

**Review by bracevac — APPROVED** [review]

**Review by sjrd — APPROVED** [review]
Let's add a test with a custom value class, just to be sure, but otherwise LGTM.
