### PR TITLE
Fix #4350: Do not check prefix of class type parameters

### LINKED ISSUE #4350: Wrong staging level when accessing type from class
When:
```
class F[T: Type] { '(null.asInstanceOf[T]) }
```

access to T from the class F is reported as a wrong level:
```
4 |  '(null.asInstanceOf[T])
  |                      ^
  |                      access to F.this from wrong staging level:
  |                       - the definition is at level 0,
  |                       - but the access is at level 1.
```

SImilarly:
```
class F {
  type T
  '(null.asInstanceOf[T])
}
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
TODO
- [x] Fix infinite recursion in neg test
- [x] Fix substitution of type

### CODE REVIEW

**Comment by biboudis** [comment]
@nicolasstucki it works for me (apart from the infinite recursion if someone omits the evidence). 

The other error we were getting was indeed a bug in the code.

File: compiler/src/dotty/tools/dotc/quoted/TreeCleaner.scala [hunk 1]
```diff
@@ -17,12 +17,14 @@ class TreeCleaner extends tpd.TreeMap {
   /** List of symbols and their types for type aliases `type T = U` */
   private[this] var aliasesSyms: List[Symbol] = Nil
   private[this] var aliasesTypes: List[Type] = Nil
+  private[this] val aliases = newMutableSymbolMap[Tree]
```
Comment (biboudis) [inline compiler/src/dotty/tools/dotc/quoted/TreeCleaner.scala]: The changes in this file are not relevant to the fix right? BTW can we add a comment for the `aliases` var just for symmetry? 😛
