### PR TITLE
Fix #6538: Make interfaces.SourcePosition resilient to missing sources

### LINKED ISSUE #6538: Error reporting for inlined code now depends on source code of library
In working with ScalaTest macros, we get the following compile error, which points to path on our release machine, which crashes the compiler:

```
[error] java.nio.file.NoSuchFileException: /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/tasty/reflect/utils/TreeUtils.scala
```

This seems to be a general problem when we report errors inside inlined code.

<details>
<summary>complete stacktrace</summary>
<pre>
[error] ## Exception when compiling 6 sources to /Users/fliu/Documents/scalatest-upstream/scalatest-test.dotty/target/scala-0.15/test-classes
[error] /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/tasty/reflect/utils/TreeUtils.scala
[error] sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error] sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[error] java.nio.file.Files.newByteChannel(Files.java:361)
[error] java.nio.file.Files.newByteChannel(Files.java:407)
[error] java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
[error] java.nio.file.Files.newInputStream(Files.java:152)
[error] dotty.tools.io.File.inputStream(File.scala:51)
[error] dotty.tools.io.PlainFile.input(PlainFile.scala:44)
[error] dotty.tools.io.AbstractFile.toByteArray(AbstractFile.scala:170)
[error] dotty.tools.dotc.util.SourceFile.SourceFile$superArg$1$$anonfun$1(SourceFile.scala:52)
[error] dotty.tools.dotc.util.SourceFile.content(SourceFile.scala:48)
[error] dotty.tools.dotc.util.SourceFile.lineIndices(SourceFile.scala:113)
[error] dotty.tools.dotc.util.SourceFile.offsetToLine(SourceFile.scala:132)
[error] dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:26)
[error] xsbt.DelegatingReporter$2.line(DelegatingReporter.java:89)
[error] sbt.internal.server.LanguageServerReporter.$anonfun$toDiagnostics$2(LanguageServerReporter.scala:109)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] scala.collection.Iterator.foreach(Iterator.scala:937)
[error] scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] sbt.internal.server.LanguageServerReporter.toDiagnostics(LanguageServerReporter.scala:107)
[error] sbt.internal.server.LanguageServerReporter.$anonfun$aggregateProblems$1(LanguageServerReporter.scala:97)
[error] sbt.internal.server.LanguageServerReporter.$anonfun$aggregateProblems$1$adapted(LanguageServerReporter.scala:94)
[error] scala.Option.foreach(Option.scala:257)
[error] sbt.internal.server.LanguageServerReporter.aggregateProblems(LanguageServerReporter.scala:94)
[error] sbt.internal.server.LanguageServerReporter.logError(LanguageServerReporter.scala:62)
[error] sbt.internal.inc.LoggedReporter.display(LoggedReporter.scala:161)
[error] sbt.internal.inc.LoggedReporter.log(LoggedReporter.scala:136)
[error] sbt.internal.server.LanguageServerReporter.log(LanguageServerReporter.scala:58)
[error] xsbt.DelegatingReporter.doReport(DelegatingReporter.java:127)
[error] dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:231)
[error] dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:291)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:291)
[error] dotty.tools.dotc.core.TyperState.commit(TyperState.scala:158)
[error] dotty.tools.dotc.typer.Applications.fail$1(Applications.scala:867)
[error] dotty.tools.dotc.typer.Applications.realApply$6$$anonfun$5$$anonfun$2(Applications.scala:873)
[error] scala.Option.getOrElse(Option.scala:138)
[error] dotty.tools.dotc.typer.Applications.realApply$7$$anonfun$6(Applications.scala:874)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2318)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:875)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:910)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:87)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2131)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2185)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2219)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2231)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2274)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2296)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1679)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2121)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2184)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2219)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2231)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2250)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2296)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1798)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2161)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2185)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2219)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2231)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2307)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:61)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:35)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:65)
[error] dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$2(FrontEnd.scala:89)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:89)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
[error] dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:185)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:120)
[error] dotty.tools.dotc.Run.compile(Run.scala:104)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:34)
[error] dotty.tools.dotc.Driver.process(Driver.scala:172)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:278)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]
[error] java.nio.file.NoSuchFileException: /drone/src/github.com/lampepfl/dotty/library/src-3.x/scala/tasty/reflect/utils/TreeUtils.scala
[error] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[error] 	at java.nio.file.Files.newByteChannel(Files.java:361)
[error] 	at java.nio.file.Files.newByteChannel(Files.java:407)
[error] 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
[error] 	at java.nio.file.Files.newInputStream(Files.java:152)
[error] 	at dotty.tools.io.File.inputStream(File.scala:51)
[error] 	at dotty.tools.io.PlainFile.input(PlainFile.scala:44)
[error] 	at dotty.tools.io.AbstractFile.toByteArray(AbstractFile.scala:170)
[error] 	at dotty.tools.dotc.util.SourceFile.SourceFile$superArg$1$$anonfun$1(SourceFile.scala:52)
[error] 	at dotty.tools.dotc.util.SourceFile.content(SourceFile.scala:48)
[error] 	at dotty.tools.dotc.util.SourceFile.lineIndices(SourceFile.scala:113)
[error] 	at dotty.tools.dotc.util.SourceFile.offsetToLine(SourceFile.scala:132)
[error] 	at dotty.tools.dotc.util.SourcePosition.line(SourcePosition.scala:26)
[error] 	at xsbt.DelegatingReporter$2.line(DelegatingReporter.java:89)
[error] 	at sbt.internal.server.LanguageServerReporter.$anonfun$toDiagnostics$2(LanguageServerReporter.scala:109)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at sbt.internal.server.LanguageServerReporter.toDiagnostics(LanguageServerReporter.scala:107)
[error] 	at sbt.internal.server.LanguageServerReporter.$anonfun$aggregateProblems$1(LanguageServerReporter.scala:97)
[error] 	at sbt.internal.server.LanguageServerReporter.$anonfun$aggregateProblems$1$adapted(LanguageServerReporter.scala:94)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at sbt.internal.server.LanguageServerReporter.aggregateProblems(LanguageServerReporter.scala:94)
[error] 	at sbt.internal.server.LanguageServerReporter.logError(LanguageServerReporter.scala:62)
[error] 	at sbt.internal.inc.LoggedReporter.display(LoggedReporter.scala:161)
[error] 	at sbt.internal.inc.LoggedReporter.log(LoggedReporter.scala:136)
[error] 	at sbt.internal.server.LanguageServerReporter.log(LanguageServerReporter.scala:58)
[error] 	at xsbt.DelegatingReporter.doReport(DelegatingReporter.java:127)
[error] 	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:231)
[error] 	at dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:291)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:291)
[error] 	at dotty.tools.dotc.core.TyperState.commit(TyperState.scala:158)
[error] 	at dotty.tools.dotc.typer.Applications.fail$1(Applications.scala:867)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$6$$anonfun$5$$anonfun$2(Applications.scala:873)
[error] 	at scala.Option.getOrElse(Option.scala:138)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$7$$anonfun$6(Applications.scala:874)
[error] 	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2318)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:875)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:910)
[error] 	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:87)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2131)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2185)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2219)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2231)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2274)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2296)
[error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1679)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2121)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2184)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2219)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2231)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2250)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2296)
[error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1798)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2161)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2185)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2219)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2231)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2307)
[error] 	at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:61)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:35)
[error] 	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:65)
[error] 	at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$2(FrontEnd.scala:89)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:89)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:158)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:170)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:178)
[error] 	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:185)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:120)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:104)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:34)
[error] 	at dotty.tools.dotc.Driver.process(Driver.scala:172)
[error] 	at dotty.tools.dotc.Main.process(Main.scala)
[error] 	at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
</pre>
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/util/SourcePosition.scala [hunk 1]
```diff
@@ -23,7 +23,7 @@ extends interfaces.SourcePosition with Showable {
   def point: Int = span.point
 
   /** The line of the position, starting at 0 */
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/util/SourcePosition.scala]: Doc comment can be removed since the interface already has one which is more accurate (same with column)

File: sbt-bridge/src/xsbt/DelegatingReporter.java [hunk 2]
```diff
@@ -86,7 +86,9 @@ public void doReport(MessageContainer cont, Context ctx) {
           return Optional.ofNullable(src.file().path());
         }
         public Optional<Integer> line() {
-          return Optional.of(pos.line());
+          int line = pos.line();
+          if (line == -1) return  Optional.empty();
```
Comment (smarter) [inline sbt-bridge/src/xsbt/DelegatingReporter.java]:
```suggestion
          if (line == -1) return Optional.empty();
```

File: sbt-bridge/src/xsbt/DelegatingReporter.java [hunk 3]
```diff
@@ -86,7 +86,9 @@ public void doReport(MessageContainer cont, Context ctx) {
           return Optional.ofNullable(src.file().path());
```
Comment (smarter) [inline sbt-bridge/src/xsbt/DelegatingReporter.java]: Would be clearer to use `if (src.exists())`, same for `sourceFile` above.

Comment (nicolasstucki) [reply sbt-bridge/src/xsbt/DelegatingReporter.java]: Done

**Comment by nicolasstucki** [comment]
@smarter could you have a look at the last two commits that add your suggestions
