### PR TITLE
Find annotation args in inline expansion

### LINKED ISSUE #24894: Inline not considered for annotation parameters even if macro returns constant expression
## Compiler version
3.7.2
3.7.4

## Minimized code

```scala
@Deprecated(since = Bar.bar()) class Foo

object Bar {
  import quoted.*

  inline def bar(): String = ${ macroBar() }
  def macroBar()(using Quotes): Expr[String] = {
    val s = "hello".reverse
    Expr(s)
  }
}
```

```scala
//> using dep org.openjdk.jmh:jmh-core:1.37
import org.openjdk.jmh.annotations.*
@Param(Bar.bar()) class Foo

object Bar {
  import quoted.*

  inline def bar(): Array[String] = ${ macroBar() }
  def macroBar()(using Quotes): Expr[Array[String]] = {
    val l = Range(0, 200, 10).map(_.toString).map(Expr(_)).toList
    '{ Array[String](${ Varargs(l) }*) }
  }
}
```
## Output

```scala
-- Error: test.scala:15:27 -----------------------------------------------------
15 |@Deprecated(since = Bar.bar()) class Foo
   |                    ^^^^^^^^^
   |                    Annotation argument is not a constant
1 error found
```

## Expectation
I expect the annotation to compile as if the result of the macro were inserted verbatim into the annotations parameter.

Thanks to @s5bug for minimization

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #24894 

Annotation args can be `inline transparent`, but `Inlining` phase doesn't inline into annotations.

The `Inlined` node must be handled when emitting the annotation and also when inspecting args.

### CODE REVIEW

**Comment by som-snytt** [comment]
I'm glad the checks are green, but I had a local failure that `final val` was no longer stable in a pattern. I tossed in some `StableRealizable` and `UncheckedStableAnnot` but apparently that is not necessary. Probably I had a stale binary in `.ivy2`.

I wonder if there's a way for the test rig to warn me if a failure includes a suspicious artifact.

At the moment:
```
[error] -- [E046] Cyclic Error: /home/amarki/projects/scala3/staging/test/scala/quoted/staging/repl/StagingScriptedReplTests.scala:11:39
[error] 11 |class StagingScriptedReplTests extends ReplTest(ReplTest.withStagingOptions) {
[error]    |                                       ^
[error]    |                             Cyclic reference involving val <import>
```
I'm not going to investigate, but it would be nice if the test suite just ran (locally). Elsewhere, a PR includes tweaks to help run under JDK 25. Spurious warnings and errors are demoralizing and distracting.

I'll add a simple test for the stability check in patterns. (Bootstrapping would fail, as it did for me spuriously, if that were broken. It complained about the vals in `concurrent.duration` which are aliases of Java enums.) I'll also ask myself why it doesn't need more help with stability. The check is `checkLegalValue` in typer.

**Comment by som-snytt** [comment]
Moving the second fix for `final val enum` to a separate PR, including `@inelidable` or `@inelisible`.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -155,6 +156,7 @@ trait TreeInfo[T <: Untyped] { self: Trees.Instance[T] =>
     case Apply(fn, args) => allArguments(fn) ::: args
     case TypeApply(fn, args) => allArguments(fn) ::: args
     case Block(Nil, expr) => allArguments(expr)
+    case Inlined(_, _, expansion) => allArguments(expansion)
     case _ => Nil
```
Comment (jchyb) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:158]: I don't really understand this part. It seems like we are removing the Inlined node from the function of Apply, rather than the argument, which seems unrelated to the rest of the PR. 
Like for annotation `@annot([Inlined] "someString"))` allArguments will still return `[Inlined] "someString"`

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/ast/TreeInfo.scala:158]: Likely! I didn't get back to write a test, a mental block. I'll follow up.

**Comment by som-snytt** [comment]
Dropped the ill-considered `allTermArguments` tweak and added a unit test for what is actually witnessed. Did not fiddle with adding a helper for convenience.
