### PR TITLE
Fix #9529: Desugar ExtMethods in expression position

### LINKED ISSUE #9529: Missing desugaring  case for extension methods.
## Minimized code

```Scala
given AnyRef = { // should have been `given AnyRef {`
  extension (n: Int)
    def plus(m: Int): Int = n + m
}
```

## Output (click arrow to expand)
<details>

```scala
scala.MatchError: ExtMethods(List(),List(List(ValDef(n,Ident(Int),EmptyTree))),List(DefDef(plus,List(),List(List(ValDef(m,Ident(Int),EmptyTree))),Ident(Int),InfixOp(Ident(n),Ident(+),Ident(m))))) (of class dotty.tools.dotc.ast.untpd$ExtMethods) while compiling Foo.scala
Exception in thread "main" scala.MatchError: ExtMethods(List(),List(List(ValDef(n,Ident(Int),EmptyTree))),List(DefDef(plus,List(),List(List(ValDef(m,Ident(Int),EmptyTree))),Ident(Int),InfixOp(Ident(n),Ident(+),Ident(m))))) (of class dotty.tools.dotc.ast.untpd$ExtMethods)
        at dotty.tools.dotc.ast.desugar$.apply(Desugar.scala:1717)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2468)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2484)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2553)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2554)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2557)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2671)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:871)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2431)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2484)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2553)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2554)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2557)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2671)
        at dotty.tools.dotc.typer.Typer.$anonfun$32(Typer.scala:1946)
        at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:217)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1946)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2400)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2483)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2553)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2554)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2557)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2579)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2627)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2081)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2411)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2415)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2483)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2553)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2554)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2557)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2579)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2627)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2207)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2455)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2484)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2553)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2554)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2557)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2671)
        at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
        at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:180)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:190)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:198)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:205)
        at dotty.tools.dotc.Run.compileSources(Run.scala:142)
        at dotty.tools.dotc.Run.compile(Run.scala:124)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
        at dotty.tools.dotc.Driver.process(Driver.scala:195)
        at dotty.tools.dotc.Driver.process(Driver.scala:164)
        at dotty.tools.dotc.Driver.process(Driver.scala:176)
        at dotty.tools.dotc.Driver.main(Driver.scala:203)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**
Desugar the extension method into a block with a Unit expression.
Also set a missing position for the ExtMethods tree.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/Desugar.scala [hunk 1]
```diff
@@ -1715,6 +1715,8 @@ object desugar {
       case PatDef(mods, pats, tpt, rhs) =>
         val pats1 = if (tpt.isEmpty) pats else pats map (Typed(_, tpt))
         flatTree(pats1 map (makePatDef(tree, mods, _, rhs)))
+      case ext: ExtMethods =>
+        Block(List(ext), Literal(Constant(())).withSpan(ext.span))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Desugar.scala:1719]: If this can only happen in case of error, maybe the parser should be changed to not try to parse extension methods in such positions?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:1719]: Why would we special case extensions? Isn't it better to handle them the same as `def`s? I would expect that the following would befave similarly

```scala

def f1: Unit = { def g = 0 }
def f2: Unit = { extension (x: Int) def g = 0 }


```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:1719]: Also, same error should be emitted for

```scala
def f1: Int = { def g = 0 } // error: Found: Unit   Required: Int
def f2: Int = { extension (x: Int) def g = 0 } // error: Found: Unit   Required: Int
```

Comment (smarter) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:1719]: Ah ok then is it possible to have a pos test for this change?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:1719]: Yes, ill add the test

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/ast/Desugar.scala:1719]: Added these tests
