### PR TITLE
Fix #10131: load enum types more lazily

### LINKED ISSUE #10131: latest nigtly broke compilation on JVM-14
## Minimized code

JAVA - JDK 14, macos.  Any code. (sbt in dotty - ok)

## Output

```scala
[error] scala.MatchError: ClassInfo(ThisType(TypeRef(NoPrefix,module class lang)), class Enum, List(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Object), TypeRef(ThisType(TypeRef(NoPrefix,module class constant)),trait Constable), AppliedType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),trait Comparable),List(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class Enum)),type E))), TypeRef(ThisType(TypeRef(NoPrefix,module class io)),trait Serializable))) (of class dotty.tools.dotc.core.Types$CachedClassInfo)
[error] dotty.tools.dotc.core.Definitions.JavaEnumClass(Definitions.scala:723)
[error] dotty.tools.dotc.core.Definitions.init(Definitions.scala:1666)
[error] dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:830)
[error] dotty.tools.dotc.core.Contexts$Context.initialize(Contexts.scala:542)
[error] dotty.tools.dotc.Run.rootContext(Run.scala:67)
[error] dotty.tools.dotc.Run.<init>(Run.scala:85)
[error] dotty.tools.dotc.Compiler.newRun(Compiler.scala:153)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
[error] dotty.tools.dotc.Driver.process(Driver.scala:194)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
```

## Expectation

the compilation will be successful.  Note, that with JDK8 - all works.

### LINKED ISSUE #10133: Can't build scala3-compiler with JDK 14
## Minimized code

using JDK 14 on commit 1ab76c19993feb85521b5b0d17ed7f53ed69a7f3:
```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

```Scala
sbt:scala3> clean
sbt:scala3> repl
```

## Output (click arrow to expand)
<details>

```scala
exception caught when loading class AnnotationDefault: java.lang.NullPointerException
[error] error while loading PreviewFeature,
[error] class file /modules/java.base/jdk/internal/PreviewFeature.class is broken, reading aborted with class java.lang.NullPointerException
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/Class.class while parsing annotations in /modules/java.base/java/lang/Class.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/Class.class while parsing annotations in /modules/java.base/java/lang/Class.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/String.class while parsing annotations in /modules/java.base/java/lang/String.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/String.class while parsing annotations in /modules/java.base/java/lang/String.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/String.class while parsing annotations in /modules/java.base/java/lang/String.class
[error] 6 errors found
[error] (scala3-library-bootstrapped / Compile / compileIncremental) Compilation failed
[error] Total time: 77 s (01:17), completed 1 Nov 2020, 00:27:03
```
</details>

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #10131: load enum types more lazily

Fix #10133: JDK 14 failure

This is an alternative to #10134 .

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -545,20 +545,26 @@ class ClassfileParser(
...
+        val sig = pool.getExternalName(index).value
         val enumCaseName = pool.getName(in.nextChar)
         if (skip)
           None
         else {
-          val enumModuleClass = enumClassTp.classSymbol.companionModule
-          Some(Select(ref(enumModuleClass), enumCaseName.name))
+          val res = (ctx: Context) => {
+            implicit val ctx2 = ctx
+            val enumClassTp = sigToType(sig)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:555]: Could we store just `sig` instead (so this method would return `Option[untpd.Tree | String]`) ?

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:555]: Yes, that's a good idea, I'll try that.

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 2]
```diff
@@ -598,13 +607,19 @@ class ClassfileParser(
...
-    val argbuf = new ListBuffer[untpd.Tree]
+    val argbuf = new ListBuffer[untpd.Tree | (Context => untpd.Tree)]
     var hasError = false
     for (i <- 0 until nargs) {
       val name = pool.getName(in.nextChar)
       parseAnnotArg(skip) match {
-        case Some(arg) => argbuf += untpd.NamedArg(name.name, arg)
-        case None => hasError = !skip
+        case Some(tag: EnumTag) =>
+          argbuf += ((ctx: Context) => untpd.NamedArg(name.name, enumTagTree(tag)(using ctx)))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:616]: Can we go further and store `(name, tag)` directly in `argbuf` and thus the `lazyBuf` of `ClassfileAnnotation`?

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 3]
```diff
@@ -518,7 +518,14 @@ class ClassfileParser(
   }
   // sigToType
 
-  def parseAnnotArg(skip: Boolean = false)(using ctx: Context, in: DataReader): Option[untpd.Tree] = {
+  type EnumTag = (String, NameOrString)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:521]: A class would be equivalent and a bit more clear.

**Review by smarter — APPROVED** [review]

**Review by smarter — CHANGES_REQUESTED** [review]
Oops, meant to record this review as a "Request changes"

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:616]: We can do that, but we need to refactor a little bit `ClassfileAnnotation` to delay the creation of `NamedArg`.

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 4]
```diff
@@ -572,7 +576,13 @@ class ClassfileParser(
     }
   }
 
-  class ClassfileAnnotation(annotType: Type, args: List[untpd.Tree]) extends LazyAnnotation {
+  class ClassfileAnnotation(annotType: Type, lazyArgs: List[(NameOrString, untpd.Tree | EnumTag)]) extends LazyAnnotation {
+    val args: Context ?=> List[untpd.Tree] = (using ctx: Context) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:580]: This could be a def

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 5]
```diff
@@ -545,20 +553,16 @@ class ClassfileParser(
...
+        if (skip) None else Some(EnumTag(sig, enumCaseName))
       case ARRAY_TAG =>
-        val arr = new ArrayBuffer[Tree]()
+        val arr = new ArrayBuffer[untpd.Tree]()
         var hasError = false
         for (i <- 0 until index)
           parseAnnotArg(skip) match {
-            case Some(c) => arr += c
+            case Some(c: untpd.Tree) => arr += c
+            case Some(tag: EnumTag) => arr += tag.toTree
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:565]: The `toTree` here means we're still forcing things early in some cases

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:565]: I guess if this works OK with JDK 14 we can merge as is but we should revisit it.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:565]: Yes, this is a recursive call, I see no other ways to deal with it elegantly.

**Review by smarter — CHANGES_REQUESTED** [review]
OK to merge if this works with JDK 14, it would be good to add it to the CI, you should be able to do that by reusing this commit: https://github.com/dotty-staging/dotty/commit/a40c69468d435ee102771d9efa7dd491cb075370 (I didn't make a PR with it at the time because there were other issues with JDK 14 which have been solved now)

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala (hunk 5 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:565]: We us this call to build up `elems` which is used in `Some(untpd.JavaSeqLiteral(elems, TypeTree()))`, if we want to delay things properly we'd have to propagate the delay to this construction too: replace EnumTag by `Context => untpd.Tree` again, and construct a new `Context => untpd.Tree` when any element in the Array is itself a `Context => untpd.Tree`

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:565]: Yes, if we go back to `Context => untpd.Tree`, things will work, but it will undo the micro-optimizations. I'd say being lazy enough is a good tradeoff. If a problem emerges, we can be lazier (the lazy problem might be in other places as well).
