### PR TITLE
[CI] Disable execution of requests flaky tests in the community build

### LINKED ISSUE #25257: Requests repo causes many CB failures
## Compiler version

3.8

## Minimized code

Besides flaky tests requiring restarting the task, which happens periodically, there is currently a stop-the-world issue.

## Output

```scala
[123-1] + requests.ModelTests.multipart file uploads should contain application/octet-stream content type 254ms  
[123-1] Tests: 1, Passed: 1, Failed: 0
[123-2] X requests.RequestTests 0ms 
[123-2]   java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
[123-2]     org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:277)
[123-2]     java.util.Optional.orElseThrow(Optional.java:403)
[123-2]     org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:268)
[123-2]     org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:154)
[123-2]     org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:196)
[123-2]     org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:108)
[123-2]     com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
[123-2]     org.testcontainers.containers.GenericContainer.start(GenericContainer.java:329)
[123-2]     com.dimafeng.testcontainers.SingleContainer.start(Container.scala:48)
[123-2]     com.dimafeng.testcontainers.ContainerDef.start(ContainerDef.scala:14)
[123-2]     com.dimafeng.testcontainers.ContainerDef.start$(ContainerDef.scala:6)
[123-2]     com.dimafeng.testcontainers.GenericContainer$Def.start(GenericContainer.scala:109)
[123-2]     requests.HttpbinTestSuite.<init>(HttpbinTestSuite.scala:13)
[123-2]     requests.RequestTests$.<init>(RequestTests.scala:6)
[123-2]     requests.RequestTests$.<clinit>(RequestTests.scala:8)
[123-2]     jdk.internal.misc.Unsafe.ensureClassInitialized0(Unsafe.java:-2)
[123-2]     jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
[123-2]     jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
[123-2]     jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
[123-2]     java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
[123-2]     java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
[123-2]     java.lang.reflect.Field.get(Field.java:425)
[123-2]     utest.PortableScalaReflectExcerpts$LoadableModuleClass.loadModule(PortableScalaReflectExcerpts.scala:68)
[123-2]     utest.PlatformShims$.loadModule(PlatformShims.scala:15)
[123-2]     utest.runner.BaseRunner.$anonfun$3(BaseRunner.scala:108)

```

## Expectation

Community build projects should not be a maintenance burden for normal integration builds.

### PR DESCRIPTION
**Pull request by WojciechMazur**
* Disable execution of requests tests, only perform tests compilation, fixes #25257
* Move special handling of `sourcecode` out of the main MillCommunityPojrect class to cleanup the logic

### CODE REVIEW

File: community-build/src/scala/dotty/communitybuild/projects.scala [hunk 1]
```diff
@@ -208,6 +212,7 @@ object projects:
   lazy val requests = MillCommunityProject(
     project = "requests",
     baseCommand = s"requests.jvm[$compilerVersion]",
+    executeTests = false,
```
Comment (Gedochao) [inline community-build/src/scala/dotty/communitybuild/projects.scala]:
```suggestion
    executeTests = false, // TODO: fix this to pass consistently
```

Comment (WojciechMazur) [reply community-build/src/scala/dotty/communitybuild/projects.scala]: Well, to pass it consistently some of the selected tests should be disabled anyway, since they depend on third-party services like https://httpbin.org/ - in the past that was the main cause of most failures. 
Since we cannot exclude these tests dynamically (like in the sbt with dedicated command) it means we need to actually maintain exclusion in the fork (submodule) which is yet another burden. 
Overall this project does not seem to be a good fit for community build
