### PR TITLE
Use dollar-free param names in stub implementations

### LINKED ISSUE #25531: Don't suggest parameters with dollars
## Compiler version

3.8.2

## Minimized code

```scala
scala> import java.nio.file.*

scala> val walker = new FileVisitor {}
-- Error: ----------------------------------------------------------------------
1 |val walker = new FileVisitor {}
  |             ^
  | object creation impossible, since:
  | it has 4 unimplemented members.
  | /** As seen from class $anon, the missing signatures are as follows.
  |  *  For convenience, these are usable as stub implementations.
  |  */
  |   def postVisitDirectory
  |   (x$0: T, x$1: java.io.IOException): java.nio.file.FileVisitResult = ???
  |   def preVisitDirectory
  |   (x$0: T, x$1: java.nio.file.attribute.BasicFileAttributes):
  |     java.nio.file.FileVisitResult = ???
  |   def visitFile
  |   (x$0: T, x$1: java.nio.file.attribute.BasicFileAttributes):
  |     java.nio.file.FileVisitResult = ???
  |   def visitFileFailed
  |   (x$0: T, x$1: java.io.IOException): java.nio.file.FileVisitResult = ???
1 error found
```

## Expectation

If there are no parameter names, pick better names than fresh ones.

Related to https://github.com/scala/scala3/issues/18234
and to improving the "stub" message.

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #25531.

When extending a Java class whose bytecode lacks the [`MethodParameters` attribute](https://docs.oracle.com/javase/specs/jvms/se24/html/jvms-4.html#jvms-4.7.24), `ClassfileParser.sig2type` generates synthetic `x$0`, `x$1` names:
https://github.com/scala/scala3/blob/83feab294d74a2c75f03e1eb499b90f031c68a84/compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala#L671

Normally these are replaced by `fillInParamNames` if the attribute is present:

https://github.com/scala/scala3/blob/83feab294d74a2c75f03e1eb499b90f031c68a84/compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala#L918

But when the attribute is missing the synthetic names persist, and they contain `$`.

When displaying stub implementations for unimplemented members, replace them with dollar-free versions (`x0`, `x1`) so the suggested code is directly usable.

## How much have you relied on LLM-based tools in this contribution?

Extensively.

## How was the solution tested?

New test case.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala [hunk 1]
```diff
@@ -733,11 +733,27 @@ object RefChecks {
...
+          case _ => tp
+
         def stubImplementations: List[String] = {
           // Grouping missing methods by the declaring class
           val regrouped = missingMethods.groupBy(_.owner).toList
           def membersStrings(members: List[Symbol]) =
-            members.sortBy(_.name.toString).map(_.asSeenFrom(clazz.thisType).showDcl + " = ???")
+            members.sortBy(_.name.toString).map: sym =>
+              val denot = sym.asSeenFrom(clazz.thisType)
+              denot.mapInfo(replaceSyntheticParamNames).showDcl + " = ???"
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/typer/RefChecks.scala:756]: Could also for the single missing member case.
```
def showDclAndLocation(sym: Symbol) =
            s"${sym.mapInfo(replaceSyntheticParamNames).showDcl} in ${sym.owner.showLocated}"
```
test
```
class Rble extends Readable // error
```

**Comment by som-snytt** [comment]
Worth adding that I previously wondered if there should be a scheme for inventing names, such as `x, y, z` etc perhaps depending on number of params. But simplicity wins.

Also, it would be nice to more directly support the suggestion as a rewrite; and for the diagnostic to bear the suggestion separately as text for a tool; somewhat relatedly, scastie can't show `-Vprint` output, which could use a similar side channel for text.

**Comment by mbovel** [comment]
> Thank-you Claude for lowering the activation energy?

Yes it helped! As usual, useful to find the relevant locations, answer questions and iterate through different solutions quickly, but needed my input to converge to a simple solution.

> By coincidence, it's still an issue that it's hard to copy/paste with `[error]` prefixed. [sbt/sbt#7067](https://github.com/sbt/sbt/issues/7067)

💯

Mill has `--ticker=false` at least.

> Worth adding that I previously wondered if there should be a scheme for inventing names, such as `x, y, z` etc perhaps depending on number of params. But simplicity wins.

Yeah, I also thought about that. I first tried to derive names from types:`int: Int, foo: Foo`, etc. but in the end figured out it was not worth it.

> Also, it would be nice to more directly support the suggestion as a rewrite

Agreed, let's make a separate issue for that if it doesn't already exist!

**Comment by SolalPirelli** [comment]
Re: copy-pasting, do your terminals not allow Alt + left click to select a rectangular area?

**Comment by som-snytt** [comment]
Thanks for the hint, my brain does not allow me to touch both the keyboard and the mouse, but maybe with practice. Oh, I could get an ALT foot pedal.

I'll check for a ticket; I had a branch to port improvements to the stubs message, this may fall under that umbrella.

Also I may have to become a mill convert after all. Things you don't foresee when you get out of bed in the morning.

Thanks again for taking my ticket seriously and resolving it so cleverly.
