### PR TITLE
Fix #4674: Add regression test

### LINKED ISSUE #4674: specifying a type in pattern matching results in a spurious warning
```
val x: String = "something"
x.foreach {
  case 's' => println("s")
  case c: Char => println(c)
} 
```

Results in:
```
[warn] 154 |        case c: Char                   => println(c)
[warn]     |             ^
[warn]     |this will always yield true, since `class Char` is a subclass of `class Char`
```

While it's true that I can just omit the `: Char`, the intent here was to increase readability by specifying the type. Feel free to close if this is not a bug but an intended change.

### PR DESCRIPTION
**Pull request by janrock-ylb**
Test: Passed

### CODE REVIEW

File: tests/neg-custom-args/fatal-warnings/i4674.scala [hunk 1]
```diff
@@ -0,0 +1,9 @@
+object Testi4674 {
+  def T(x: String) = {
+    x.foreach {
+      case 's' => println("s")
+      case c: Char => println(c) // error
```
Comment (allanrenucci) [inline tests/neg-custom-args/fatal-warnings/i4674.scala]: Can you write `// error: type test always succeed` instead. Otherwise we don't what is the error without running the test

File: tests/neg-custom-args/fatal-warnings/i4674.scala [hunk 2]
```diff
@@ -0,0 +1,9 @@
...
+    }
+  }
+  T("test")
```
Comment (allanrenucci) [inline tests/neg-custom-args/fatal-warnings/i4674.scala]: This is not needed. I would remove it. We try to keep tests as small as possible

**Comment by janrock-ylb** [comment]
Done.

Thank you!

**Comment by janrock-ylb** [comment]
CLA signed off. Confirmed from The Scala Team.

**Comment by allanrenucci** [comment]
CLA [signed](https://www.lightbend.com/contribute/cla/scala/check/janrock-ylb). Thanks @janrock-ylb  for the contribution
