### PR TITLE
Fix main: completion test failing on java 8

### LINKED ISSUE #19427: Nightly Dotty workflow of 2024-01-12 failed
See https://github.com/lampepfl/dotty/actions/runs/7497356553

### PR DESCRIPTION
**Pull request by jchyb**
closes #19427

[test_java8]
[test_windows_full]

### CODE REVIEW

File: presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSnippetSuite.scala [hunk 1]
```diff
@@ -77,31 +77,62 @@ class CompletionSnippetSuite extends BaseCompletionSuite:
...
-        |object Main {
-        |  class Gen[T]
-        |  type MyType = Gen[Int]
-        |  new MT@@
-        |}
-        |""".stripMargin,
-      """|MyType
-         |""".stripMargin
-    )
+    if (System.getProperty("java.version").nn.startsWith("1.8")) {
```
Comment (tgodzik) [inline presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSnippetSuite.scala:109]:
```suggestion
    if (!scala.util.Properties.isJavaAtLeast("9")) {
```
should work also

**Review by tgodzik — APPROVED** [review]
Thanks! And sorry for breaking stuff! Added a comment, but you can ignore it.
