### PR TITLE
Fix #9462: Identify inserted apply's more reliably in the Dynamic treatment.

### LINKED ISSUE #9462: The apply syntax does not work with scala.Dynamic's applyDynamic/applyDynamicNamed
## Minimized code

```Scala
import scala.language.dynamics

object MyDynamic {
  object literal extends scala.Dynamic {
    def applyDynamic(name: String)(args: Any*): Any =
      "applyDynamic: " + name + " -> " + args
    def applyDynamicNamed(name: String)(args: (String, Any)*): Any =
      "applyDynamicNamed: " + name + " -> " + args
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    println(MyDynamic.literal())
    println(MyDynamic.literal("foobar"))
    println(MyDynamic.literal(foo = "Foo", bar = 42))
  }
}
```

## Output

```scala
-- [E008] Not Found Error: tests\run\hello.scala:14:22 -------------------------
14 |    println(MyDynamic.literal())
   |            ^^^^^^^^^^^^^^^^^
   |value applyDynamic is not a member of object MyDynamic, but could be made available as an extension method.
   |
   |The following import might fix the problem:
   |
   |  import reflect.Selectable.reflectiveSelectable
   |
-- [E008] Not Found Error: tests\run\hello.scala:15:22 -------------------------
15 |    println(MyDynamic.literal("foobar"))
   |            ^^^^^^^^^^^^^^^^^
   |value applyDynamic is not a member of object MyDynamic, but could be made available as an extension method.
   |
   |The following import might fix the problem:
   |
   |  import reflect.Selectable.reflectiveSelectable
   |
-- [E008] Not Found Error: tests\run\hello.scala:16:22 -------------------------
16 |    println(MyDynamic.literal(foo = "Foo", bar = 42))
   |            ^^^^^^^^^^^^^^^^^
   |            value applyDynamicNamed is not a member of object MyDynamic
3 errors found
```

## Expectation

It runs and outputs the following:
```
applyDynamic: apply -> ArraySeq()
applyDynamic: apply -> ArraySeq(foobar)
applyDynamicNamed: apply -> ArraySeq((foo,Foo), (bar,42))
```

## Notes

This works in Scala 2.

Explicitly calling `.apply` makes it work in Dotty as well:
```scala
    println(MyDynamic.literal.apply())
    println(MyDynamic.literal.apply("foobar"))
    println(MyDynamic.literal.apply(foo = "Foo", bar = 42))
```
This is necessary for Scala.js, because this is how `js.Dynamic.literal` is defined. All code using `js.Dynamic.literal` hits this issue at the moment.

### PR DESCRIPTION
**Pull request by sjrd**
Previously, identifying when there was an inserted apply, which had to be carried through the Dynamic treatment, was done on a syntactical basis. This would mishandle cases written as
```scala
  someContainer.someDynamic()
```
as it would think that this was an explicit dynamic call for `"someDynamic"` on `someContainer` (although `someContainer` is not even a `scala.Dynamic` itself, but `someContainer.someDynamic` is).

We now reliably detect inserted applys by looking at the result of the pre-type-checking of the function part, and testing whether there is a synthetic `Select(_, nme.apply)` node.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -913,7 +913,23 @@ trait Applications extends Compatibility {
...
+            /* TODO Get rid of this case. It is still syntax-based, therefore unreliable.
+             * It is necessary for things like `someDynamic[T](...)`, because in that case,
+             * somehow typedFunPart returns a tree that was typed as `TryDynamicCallType`,
+             * so clearly with the view that an apply insertion was necessary, but doesn't
+             * actually insert the apply!
+             * This is probably something wrong in apply insertion, but I (@sjrd) am out of
+             * my depth there.
+             * In the meantime, this makes tests pass.
+             */
+            case TypeApply(fun, _) => !fun.isInstanceOf[Select]
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: Shouldn't we also check that the name of `fun` has a synthetic span?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: Oh, no

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: What kind of trees do we get here?

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: Anything. For the test that was failing, it was `TypeApply(Ident("qual"), List(oneTArg))`.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: Where I was expecting `typedFunPart` to have returned `TypeApply(Select(Ident("qual"), nme.apply), List(oneTarg))` instead, where the `Select` node would have had a synthetic span.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: I'm wondering if we can get a `TypeApply(Block(..., Select(..., nme.apply)), ...)`. I guess those would never be inserted applies.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:929]: No, in that case, for an inserted apply, the `Select` should be around the `Block`, not inside it.

**Review by nicolasstucki — APPROVED** [review]
