### PR TITLE
Fix #4522: Add a regression test

### LINKED ISSUE #4522: When nested functions are inlined, boxing variables should be avoided
For this code:
```scala
object C {
  def fun: Int = {
    var a = 10
    inline def f(arg: => Unit) = {
      a += 1
      arg
    }

    f {
      return a
    }
    a
  }
}
```
The decompiled code looks like this:
```java
public final class C$ {
    public static final C$ MODULE$;

    static {
        new C$();
    }

    public C$() {
        MODULE$ = this;
    }

    public int fun() {
        IntRef a = IntRef.create(10);
        int var2 = a.elem + 1;
        a.elem = var2;
        return a.elem;
    }

    private void f$1(IntRef a$1, Function0 arg) {
        int var3 = a$1.elem + 1;
        a$1.elem = var3;
        arg.apply();
    }
}

```
`a` should not be boxed

### PR DESCRIPTION
**Pull request by biboudis**
The issue does not appear anymore. I added a bytecode test.

### CODE REVIEW

File: compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala [hunk 1]
```diff
@@ -281,4 +281,51 @@ class InlineBytecodeTests extends DottyBytecodeTest {
...
+          , Op(IADD)
+          , VarOp(ISTORE, 1)
+          , VarOp(ILOAD, 1)
+          , Op(IRETURN)
+          , Label(8)
+          , FrameEntry(0, List(), List("java/lang/Throwable"))
+          , Op(ATHROW)
+          , Label(11)
+          , FrameEntry(4, List(), List("java/lang/Throwable"))
+          , Op(ATHROW)
```
Comment (allanrenucci) [inline compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala]: The 6 lines above should probably not be generated.

There is something fishy going on with the `return a` statement.

Comment (biboudis) [reply compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala]: You are right. I will investigate that in a separate issue because it is unrelated to this one.

Comment (biboudis) [reply compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala]: Updated and opening a new issue for the exception issue investigation. Merci!

Comment (biboudis) [reply compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala]: So @allanrenucci @nicolasstucki I think the observed bytecode is on par with the spec.

The minimal test case is this:

```scala
class Test {
  def fun: Int = {
    var a = 10
    { // throw is generated only when return is nested
      return a
    }
  }
}
```

According to the spec for [return expressions](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#return-expressions):

> Returning from the method from within a nested function may be implemented by throwing and catching a scala.runtime.NonLocalReturnException

So, I think this was the correct behavior (although it is just a nested block and not a nested function).

Comment (allanrenucci) [reply compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala]: Yes we should open an issue. `scalac` does not emit the `athrow` instruction in this example.

Also I don't think it has anything to do with non local return. The tree for `Test::fun` is left unchanged by the `NonLocalReturns` phase. This seems to be an issue with the backend

Comment (biboudis) [reply compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala]: Tracking in #5064 hereafter. Thx @allanrenucci
