### PR TITLE
Test case to show that #16252 works with transparent

### LINKED ISSUE #16252: Wrong match case selected
## Compiler version

3.2.0

## Minimized code

```Scala
class Baz:
  inline def foo: Int = bar(zero)
  inline def bar(inline i: Int): Int = inline i match
    case 0 => 0
    case _ => 1
  private inline def zero = 0

println(Baz().foo)
```

## Output

```scala
1
```

## Expectation

```scala
0
```

See also #15893

### PR DESCRIPTION
**Pull request by odersky**
Closes #16252

### CODE REVIEW

File: tests/run/i16252.scala [hunk 1]
```diff
@@ -0,0 +1,10 @@
+class Baz:
+  transparent inline def foo: Int = bar(zero)
+  transparent inline def bar(inline i: Int): Int = inline i match
+    case 0 => 0
+    case _ => scala.compiletime.error("XD")
+  private transparent inline def zero = 0
+
+@main
+def main =
```
Comment (dwijnand) [inline tests/run/i16252.scala:9]:
```suggestion
def Test =
```

**Review by dwijnand — APPROVED** [review]
