### PR TITLE
Consider static and non-static methods as non-double def

### LINKED ISSUE #17332: `selectStatic` phase generates incorrect prefix - fails genSJSIR phase, -Ycheck:all
## Compiler version

3.2.2

## Minimized code

Compile with scala js mode on

```Scala
package foo

import annotation.static

class MirrorHelpers

object MirrorHelpers:

  @static
  def throwStuff(i: Int): Any = throw new NoSuchElementException(String.valueOf(i))

@main def Test =
  MirrorHelpers.throwStuff(23)
```

## Output

This is what you get with JVM generation
```scala
[[syntax trees at end of                  genBCode]] // /Users/jamie/workspace/scripts/bar/test.scala
package foo {
  @SourceFile("test.scala") final module class test$package extends Object {
    // ...
    @main def Test(): Object = MirrorHelpers.this.throwStuff(23) // <---- SHOULD NOT BE `MirrorHelpers.this`
  }
```

## Expectation
There probably should be a static reference to MirrorHelpers, or the check in `genSJSIR` and `-Ycheck:all` should forgive this format for static methods.
```scala
@main def Test(): Object = foo.MirrorHelpers.throwStuff(23)
```

### LINKED ISSUE #19394: Define `@static def` that is also available on module
## Compiler version

`3.4.0-RC1-bin-20240106-c15cc9c-NIGHTLY`

## Minimized code

```Scala
//> using scala 3.4.0-RC1-bin-20240106-c15cc9c-NIGHTLY

import scala.annotation.static
import scala.annotation.targetName

class Foo

object Foo {
  @static def foo: Foo = ???
  @targetName("foo") def fooBincompat: Foo = foo
}
```

## Output

```
[error] ./test.scala:10:26
[error] Double definition:
[error] def foo: Foo in object Foo at line 9 and
[error] def fooBincompat: Foo in object Foo at line 10
[error] have the same type (): Foo after erasure.
[error]   @targetName("foo") def fooBincompat: Foo = foo
[error]                          ^
```

## Expectation

I'm seeking a way that we can add the `@static` annotation post-facto without breaking binary-compatibility. So we need some way to retain or restore the old definition on the module.

### LINKED ISSUE #19396: `@static` on SJS causes assertion failed: Trying to access the this of another class
## Compiler version

`3.4.0-RC1-bin-20240106-c15cc9c-NIGHTLY`

## Minimized code

```Scala
//> using platform js
//> using scala 3.4.0-RC1-bin-20240106-c15cc9c-NIGHTLY

import scala.annotation.static

class Foo

object Foo {
  @static def foo = ???
}

class Bar {
  def bar = Foo.foo
}
```

## Output (click arrow to expand)
<details>

```scala
java.lang.AssertionError: assertion failed: Trying to access the this of another class: tree.symbol = class Foo, class symbol = class Bar
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1791)
        at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1653)
        at dotty.tools.backend.sjs.JSCodeGen.genNormalApply(JSCodeGen.scala:3056)
        at dotty.tools.backend.sjs.JSCodeGen.genApply(JSCodeGen.scala:2159)
        at dotty.tools.backend.sjs.JSCodeGen.genStatOrExpr(JSCodeGen.scala:1779)
        at dotty.tools.backend.sjs.JSCodeGen.genExpr(JSCodeGen.scala:1653)
        at dotty.tools.backend.sjs.JSCodeGen.genBody$1(JSCodeGen.scala:1583)
        at dotty.tools.backend.sjs.JSCodeGen.genMethodDef(JSCodeGen.scala:1588)
        at dotty.tools.backend.sjs.JSCodeGen.genMethodWithCurrentLocalNameScope$$anonfun$1(JSCodeGen.scala:1555)
        at dotty.tools.backend.sjs.JSCodeGen.withPerMethodBodyState$$anonfun$1(JSCodeGen.scala:107)
        at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:33)
        at dotty.tools.backend.sjs.JSCodeGen.withPerMethodBodyState(JSCodeGen.scala:108)
        at dotty.tools.backend.sjs.JSCodeGen.genMethodWithCurrentLocalNameScope(JSCodeGen.scala:1561)
        at dotty.tools.backend.sjs.JSCodeGen.genMethod$$anonfun$1(JSCodeGen.scala:1415)
        at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:33)
        at dotty.tools.backend.sjs.JSCodeGen.genMethod(JSCodeGen.scala:1416)
        at dotty.tools.backend.sjs.JSCodeGen.genScalaClass$$anonfun$2(JSCodeGen.scala:376)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.backend.sjs.JSCodeGen.genScalaClass(JSCodeGen.scala:381)
        at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit$$anonfun$3$$anonfun$1(JSCodeGen.scala:246)
        at dotty.tools.backend.sjs.ScopedVar$.withScopedVars(ScopedVar.scala:33)
        at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit$$anonfun$3(JSCodeGen.scala:250)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.backend.sjs.JSCodeGen.genCompilationUnit(JSCodeGen.scala:252)
        at dotty.tools.backend.sjs.JSCodeGen.run(JSCodeGen.scala:164)
        at dotty.tools.backend.sjs.GenSJSIR.run(GenSJSIR.scala:18)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:354)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:360)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:315)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:337)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:348)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:357)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:357)
        at dotty.tools.dotc.Run.compileSources(Run.scala:261)
        at dotty.tools.dotc.Run.compile(Run.scala:246)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:133)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$7(BloopHighLevelCompiler.scala:155)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:71)
        at bloop.tracing.NoopTracer$.trace(BraveTracer.scala:53)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:70)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$6(BloopHighLevelCompiler.scala:155)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:71)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
</details>

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #19394
Fixes #19396
Fixes #17332

### CODE REVIEW

**Comment by armanbilge** [comment]
Do the JS backend changes fix https://github.com/lampepfl/dotty/issues/19396?

**Comment by dwijnand** [comment]
Yeah.

**Comment by dwijnand** [comment]
@sjrd Could you let me know how we should fix this?  This works, but perhaps it should be fixed different or even in a phase before the backend.

File: compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala [hunk 1]
```diff
@@ -4769,7 +4773,7 @@ class JSCodeGen()(using genCtx: Context) {
   }
 
   private def isMethodStaticInIR(sym: Symbol): Boolean =
-    sym.is(JavaStatic)
+    sym.is(JavaStatic) || sym.isScalaStatic
```
Comment (sjrd) [inline compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala:4776]: If that works out of the box, it's probably the right way to fix this indeed.

File: compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala [hunk 2]
```diff
@@ -793,6 +793,9 @@ class JSCodeGen()(using genCtx: Context) {
         name.name
     }.toSet
 
+    val staticNames = moduleClass.companionClass.info.allMembers
+      .collect { case d if d.name.isTermName && d.symbol.isScalaStatic => d.name }.toSet
```
Comment (sjrd) [inline compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala:797]: That will only take the *simple* names into account, but not the signatures. Is that what the JVM back-end would do? That seems weird, doesn't it?

Comment (dwijnand) [reply compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala:797]: Yeah.  I added the extra static condition, to restricted to what I was fixing, but other original just logs and moves on on any conflict:

https://github.com/lampepfl/dotty/blob/fa93c73909ede9f794f004e0c5e1124a59fbe58e/compiler/src/dotty/tools/backend/jvm/BCodeHelpers.scala#L488-L500

Perhaps it's naive or short-sighted to ignore signatures, but I think it's that way to bias against the generation of forwarders at the first sign of trouble.  What's the API (or where do I find it) to take signatures into account?

Comment (sjrd) [reply compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala:797]: If the JVM does not take signatures into account, then we shouldn't either on JS.

Otherwise, the best way to actually take signatures into account would be to compare JVM descriptors / IR `MethodName`s.

**Review by sjrd — APPROVED** [review]

**Comment by dwijnand** [comment]
Fixes 2 other issues.  Just seeing if I can get it to also fix #14710 by fixing whatever it's wrongly doing for `@static val`.

**Comment by sjrd** [comment]
You might want to look at the tests that show up in
```bash
$ git grep '// scalajs: --skip --pending'
```
to see if there are any that can be enabled now.

**Comment by armanbilge** [comment]
Thanks, this fixed compilation in Cats Effect. Is this a potential LTS backport candidate?

Unfortunately, the compiled code is still not working at runtime in Scala.js.
- https://github.com/lampepfl/dotty/issues/19441
