### PR TITLE
Impose implicit search limit

### LINKED ISSUE #13838: `Exception: java.lang.OutOfMemoryError` (diverging implicits)
## Compiler version

3.1.1-RC1

## Minimized code

https://github.com/armanbilge/schrodinger/commit/ed9a8bad6229fb8617615cf0397814b7a02fee52

Clone project in clean workspace and run `sbt compile`.

Apologies that this isn't further minimized, not entirely sure how to approach this one. I'd appreciate any pointers.

FWIW it's not a big project, and the module that seems to have the problem is 4 files with < 1k LOC total.

## Output

```
[warn] In the last 8 seconds, 6.706 (86.2%) were spent in GC. [Heap: 0.10GB free of 4.00GB, max 4.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.

  | => monteCarlo / Compile / compileIncremental 312s

...

[warn] In the last 6 seconds, 5.215 (99.8%) were spent in GC. [Heap: 0.00GB free of 4.00GB, max 4.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "classloader-cache-cleanup-0
```

Note this occurs frequently, but not always. Sometimes it compiles just fine.

## Expectation

My code compiles the first time and everything is hunky-dory :)

### PR DESCRIPTION
**Pull request by odersky**
Impose a configurable limit on the total number of nodes constructed during an implicit search.

Fixes #13838

### CODE REVIEW

**Comment by odersky** [comment]
The actual error message is as follows:
```
-- Info: i13838.scala:8:50 -----------------------------------------------------
8 |  def liftF[F[_], A](fa: F[A]): F[Foo[A]] = map(fa)(???)  // error
  |                                                  ^
  |Implicit search problem too large.
  |an implicit search was terminated with failure after trying 1000 expressions.
  |
  |You can change the behavior by setting the `-Ximplicit-search-limit` value.
  |Smaller values cause the search to fail faster.
  |Larger values might make a very large search problem succeed.
-- [E007] Type Mismatch Error: i13838.scala:8:48 -------------------------------
8 |  def liftF[F[_], A](fa: F[A]): F[Foo[A]] = map(fa)(???)  // error
  |                                                ^^
  |      Found:    (fa : F[A])
  |      Required: F²[Foo[A²]]
  |
  |      where:    A  is a type in method liftF
  |                A² is a type variable
  |                F  is a type in method liftF with bounds <: [_] =>> Any
  |                F² is a type variable with constraint <: [_] =>> Any
  |
  |
  |      The following import might make progress towards fixing the problem:
  |
  |        import collection.Searching.search
  |
```
The first "info" part does not make it into the check file. I had to do an info instead of a warning since the warning would get suppressed by the following error.

File: compiler/src/dotty/tools/dotc/config/ScalaSettings.scala [hunk 1]
```diff
@@ -218,6 +218,7 @@ private sealed trait XSettings:
   val Xtarget: Setting[String] = ChoiceSetting("-Xtarget", "target", "Emit bytecode for the specified version of the Java platform. This might produce bytecode that will break at runtime. When on JDK 9+, consider -release as a safer alternative.", ScalaSettings.supportedTargetVersions, "", aliases = List("--Xtarget"))
   val XcheckMacros: Setting[Boolean] = BooleanSetting("-Xcheck-macros", "Check some invariants of macro generated code while expanding macros", aliases = List("--Xcheck-macros"))
   val XmainClass: Setting[String] = StringSetting("-Xmain-class", "path", "Class for manifest's Main-Class entry (only useful with -d <jar>)", "")
+  val XimplicitSearchLimit: Setting[Int] = IntSetting("-Ximplicit-search-limit", "Maximal number of expressions to be generated in an implicit search", 100000)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/config/ScalaSettings.scala:221]: With this default, it takes the original problem 330 seconds (5.5 minutes) to finish. It seems a bit long, was that intended? I also noticed that if we use 90000 it takes 90 seconds and with 50000 it only takes 50 seconds to finish, the original time does not seem to be proportional. I wonder if we reached some memory limitations. Not sure if we should make this limit smaller.

**Review by nicolasstucki — COMMENTED** [review]
Otherwise LGTM
