### PR TITLE
Fix #10769: change synthesized type in def ordinal

### LINKED ISSUE #10769: Crash in ExplicitOuter involving compiler-generated ordinal method in companion of inner sealed class
Minimzed from https://github.com/TimWSpence/cats-stm/pull/196

## Minimized code

```Scala
package stm

trait STMLike[F[_]] {
  import Internals._

  sealed abstract class Txn[+A] {}

  object Txn {
    def abort[A](e: Throwable): Txn[A] = Abort(e)
  }

  object Internals {
    case class Abort(error: Throwable) extends Txn[Nothing]
  }

}
```

## Output (click arrow to expand)
<details>

```scala
-- [E029] Pattern Match Exhaustivity Warning: try/i10769.scala:8:9 -------------
8 |  object Txn {
  |         ^
  |         match may not be exhaustive.
  |
  |         It would fail on pattern case: Internals.Abort(_)

longer explanation available when compiling with `-explain`
exception while typing Internals$.this of class class dotty.tools.dotc.ast.Trees$This # -1
exception while typing x1.$asInstanceOf$[stm.STMLike.Internals.Abort].
  stm$STMLike$Internals$Abort$$$outer
.eq(Internals$.this) of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing x1.$isInstanceOf$[stm.STMLike.Internals.Abort].&&(
  x1.$asInstanceOf$[stm.STMLike.Internals.Abort].
    stm$STMLike$Internals$Abort$$$outer
  .eq(Internals$.this)
) of class class dotty.tools.dotc.ast.Trees$Apply # -1
exception while typing if 
  x1.$isInstanceOf$[stm.STMLike.Internals.Abort].&&(
    x1.$asInstanceOf$[stm.STMLike.Internals.Abort].
      stm$STMLike$Internals$Abort$$$outer
    .eq(Internals$.this)
  )
 then return[matchResult1] 0 else () of class class dotty.tools.dotc.ast.Trees$If # -1
[...]

Exception in thread "main" java.lang.AssertionError: assertion failed: failure to construct path from method ordinal/object Txn/trait STMLike/package stm/package <root> to `this` of object Internals in trait STMLike;
trait STMLike in package stm does not have an outer accessor while compiling try/i10769.scala
java.lang.AssertionError: assertion failed: failure to construct path from method ordinal/object Txn/trait STMLike/package stm/package <root> to `this` of object Internals in trait STMLike;
trait STMLike in package stm does not have an outer accessor
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.loop$1(ExplicitOuter.scala:410)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.path$extension(ExplicitOuter.scala:429)
        at dotty.tools.dotc.transform.Erasure$Typer.typedThis(Erasure.scala:747)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2490)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2551)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2740)
        at dotty.tools.dotc.transform.Erasure$Typer.$anonfun$4(Erasure.scala:792)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.zipWithConserve$extension(Decorators.scala:149)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:792)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2489)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2551)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2740)
        at dotty.tools.dotc.transform.Erasure$Typer.$anonfun$4(Erasure.scala:792)
        at dotty.tools.dotc.core.Decorators$ListDecorator$.zipWithConserve$extension(Decorators.scala:149)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:792)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2489)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2551)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:960)
        at dotty.tools.dotc.transform.Erasure$Typer.typedIf(Erasure.scala:826)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2498)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2551)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2673)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2696)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:984)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:906)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:910)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2497)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2551)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.typedLabeled(Typer.scala:1483)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2482)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2550)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2740)
        at dotty.tools.dotc.typer.Typer.$anonfun$33(Typer.scala:1995)
        at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:216)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1995)
        at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:893)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2466)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2550)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2646)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2696)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:984)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2139)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2477)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2481)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2550)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2646)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2696)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:984)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2139)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2477)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2481)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2550)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2646)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2696)
        at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:984)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2274)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2522)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2551)
        at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:125)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2620)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2624)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2740)
        at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:123)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:296)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:297)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:185)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:195)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:203)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:210)
        at dotty.tools.dotc.Run.compileSources(Run.scala:147)
        at dotty.tools.dotc.Run.compile(Run.scala:129)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
        at dotty.tools.dotc.Driver.process(Driver.scala:193)
        at dotty.tools.dotc.Driver.process(Driver.scala:162)
        at dotty.tools.dotc.Driver.process(Driver.scala:174)
        at dotty.tools.dotc.Driver.main(Driver.scala:201)
        at dotty.tools.dotc.Main.main(Main.scala)
```

</details>

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #10769: change synthesized type in def ordinal

As pointed out by @smarter in #10769, for the following code:

    package stm

    trait STMLike[F[_]] {
      import Internals._

      sealed abstract class Txn[+A] {}

      object Txn {
	def abort[A](e: Throwable): Txn[A] = Abort(e)
      }

      object Internals {
	case class Abort(error: Throwable) extends Txn[Nothing]
      }

    }

The compiler synthesized the following code for the object `Txn`:

    object Txn {
      type MirroredMonoType = STMLike.this.Txn[?]
      def ordinal(x: Txn.MirroredMonoType): Int =
	x match {
          case _:stm.STMLike.Internals.Abort => 0
	}

      def abort[A](e: Throwable): Txn[A] = Abort(e)
    }

In the method `ordinal`, the type for `Internals.Abort` is

    TypeRef(ThisType(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class stm)),trait STMLike)),module class Internals$)),class Abort)

This type is incorrect, as we are not in the object `Internals`. The
explicit outer can only handle such types if it's static. In this
case, the object is not static, thus it crashes the explicit outer.

Co-authored-by: Guillaume Martres <smarter@ubuntu.com>

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/SymUtils.scala [hunk 1]
```diff
@@ -225,7 +225,20 @@ object SymUtils:
 
     /** The typeRef with wildcard arguments for each type parameter */
     def rawTypeRef(using Context) =
-      self.typeRef.appliedTo(self.typeParams.map(_ => TypeBounds.emptyPolyKind))
+      // Change `pre.O.this` to `pre.O` if `O` is an object
+      // This is required to avoid owner crash in ExplicitOuter.
+      // See tests/pos/i10769.scala
+      val fixPrefix = new TypeMap {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/SymUtils.scala:231]: I think this change makes sense, but it's weird to do this for `rawTypeRef` but not `typeRef` and `termRef` (this one is also called from `ordinalBody` when a child is an object), either we should do it for all of them (but we might run into cycles) or we need new method(s) for this concept.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/transform/SymUtils.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:231]: The usage of `.typeRef` and `.termRef` are very common, and not all of them need such substitution, only those that use it in trees.

>  or we need new method(s) for this concept.

This is a good idea. What about we call it `SymDenotation.typeRefForTree` or `SymUtils.typeRefForTree`?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:231]: maybe `reachableTypeRef` to emphasize that the type can be reached through a path from the current ctx.owner?

**Review by smarter — CHANGES_REQUESTED** [review]
- We need `reachableTermRef`, `reachableTypeRef` and `reachableRawTypeRef`, all of those can be useful (and for ordinal we need `reachableTermRef` too since we can have a child object in an inner object).
- Instead of using a TypeMap, I would suggest trying to define them directly in a recursive manner like termRef and typeRef
- Instead of special-casing objects, I would suggest also replacing references to inner classes `A.this.B` with `A#B`, this could be used to fix https://github.com/lampepfl/dotty/issues/10888#issuecomment-749706361 nicely and get rid of `processInner` in ClassfileParser
- I think this is useful enough to be defined directly in SymDenotations, but that's not super important
- This is likely useful enough to be exposed in tasty reflect, but that can be done later.

**Comment by liufengyun** [comment]
> * Instead of special-casing objects, I would suggest also replacing references to inner classes `A.this.B` with `A#B`, this could be used to fix [#10888 (comment)](https://github.com/lampepfl/dotty/issues/10888#issuecomment-749706361) nicely and get rid of `processInner` in ClassfileParser

I'm not sure about this change, as it changes the meaning of the types. It might work for Java, but generally does not work for Dotty.

File: compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala [hunk 2]
```diff
@@ -521,7 +521,7 @@ class SyntheticMembers(thisPhase: DenotTransformer) {
     else {
       val cases =
         for ((child, idx) <- cls.children.zipWithIndex) yield {
-          val patType = if (child.isTerm) child.termRef else child.rawTypeRef
+          val patType = if (child.isTerm) child.termRef else child.reachableRawTypeRef
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala:524]: I think this should be:
```suggestion
          val patType = if (child.isTerm) child.reachableTermRef else child.reachableRawTypeRef
```
to test this, add a `case object` in `object Internals`

**Review by smarter — CHANGES_REQUESTED** [review]
> > Instead of special-casing objects, I would suggest also replacing references to inner classes A.this.B with A#B, this could be used to fix #10888 (comment) nicely and get rid of processInner in ClassfileParser

> I'm not sure about this change, as it changes the meaning of the types. It might work for Java, but generally does not work for Dotty.

The type `A.this.B` is not meaningful if we're not inside `A` or a subclass of `A`. Imagine that we change the test case to use an inner class instead of an inner object:
```scala
package stm

trait STMLike[F[_]] {
  import Internals._

  sealed abstract class Txn[+A] {}

  object Txn {
    def abort[A](e: Throwable): Txn[A] = Abort(e)
  }

  class Internals {
    case class Abort(error: Throwable) extends Txn[Nothing]
  }

}
```
In the generated `ordinal` method for `Txn`, we want to have a `case _: Internals#Abort`, because `case _: Internals.this.Abort` isn't valid.

**Comment by liufengyun** [comment]
> The type `A.this.B` is not meaningful if we're not inside `A` or a subclass of `A`.

I agree. However, given that we don't know the context where the method is called, it's dangerous. We could make the change `A.this.B -> A#B` more than necessary, which may potentially change the semantics of typed patterns that requires outer testing.

On the other hand, in the current usage of `.reachableTermRef` and `.reachableTypeRef`, there is already an explicit precondition in `whyNotGenericSum`:

``` Scala
   /**
    *   - all of its children are addressable through a path from its companion object
    */
    def whyNotGenericSum(using Context): String = ...
```

With such a precondition, the usage of `reachableTermRef` and `reachableTypeRef` will be safe (See added test).

Generally, I think similar care should be taken in doing complex things with `symbol`, as it is really error-prone. The suggested changes don't help avoid such errors, and it may potentially cause other problems, thus I'd suggest stay with the current solution.

(Interestingly, all such use cases I know of are related to children of sealed classes.)

**Comment by smarter** [comment]
> there is already an explicit precondition in whyNotGenericSum

Ah thanks, I had missed that!

**Comment by smarter** [comment]
> We could make the change A.this.B -> A#B more than necessary, which may potentially change the semantics of typed patterns that requires outer testing.

Right, to be correct we would have to check the current `ctx.owner` to decide whether we should do this change, but if we don't have usecases for that (though it could be useful for tasty-reflection?), we don't have to do it now.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 3]
```diff
@@ -1410,6 +1410,33 @@ object SymDenotations {
...
+    /** The termRef where `pre.O$.this` is changed to `pre.O.type` if `O` is a non-static object
+     *
+     *  This is required to avoid owner crash in ExplicitOuter.
+     *  See tests/pos/i10769.scala
+     */
+    def reachableTermRef(using Context) =
+      TermRef(owner.reachableThisType, symbol)
+
+    /** The thisType where `pre.O$.this` is changed to `pre.O.type` if `O` is a non-static object */
+    def reachableThisType(using Context): Type =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1430]: Could the usages of `ThisType.raw` be replaced by `.thisType`?

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 4]
```diff
@@ -1410,6 +1410,33 @@ object SymDenotations {
...
+      if this.is(Package) then
+        ThisType.raw(TypeRef(NoPrefix, symbol.asType))
+      else if this.isTerm then
+        NoPrefix
+      else if !this.isStaticOwner && this.is(Module) then
+        TermRef(owner.reachableThisType, this.sourceModule)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1436]: For simplicity I would suggest always representing objects with termrefs even if they're static.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 4 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: It seems Dotty use `this` type for static modules outside the object consistently, let's see if the change breaks some code or not.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 3 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1430]: It's done.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 5]
```diff
@@ -1410,6 +1410,33 @@ object SymDenotations {
...
+    /** The thisType where `pre.O$.this` is changed to `pre.O.type` if `O` is a non-static object */
+    def reachableThisType(using Context): Type =
+      if this.is(Package) then
+        symbol.thisType
+      else if this.isTerm then
+        NoPrefix
+      else if this.is(Module) then
+        TermRef(owner.reachableThisType, this.sourceModule)
+      else
+        ThisType.raw(TypeRef(owner.reachableThisType, symbol.asType))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1438]: What abotu the ThisType.raw here?

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1438]: This one is different, as we need to call `owner. reachableThisType`.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 6]
```diff
@@ -1410,6 +1410,33 @@ object SymDenotations {
     def namedType(using Context): NamedType =
       if (isType) typeRef else termRef
 
+    /** The typeRef where `pre.O$.this` is changed to `pre.O.type` if `O` is a non-static object
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1413]: These documentation comments need to be updated since we also do this for static objects now.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 6 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Done.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 7]
```diff
@@ -1410,6 +1410,33 @@ object SymDenotations {
     def namedType(using Context): NamedType =
       if (isType) typeRef else termRef
 
+    /** The typeRef where `pre.O$.this` is changed to `pre.O.type`
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:1413]: Perhaps it's worth it to explain this in more details:
```suggestion
    /** Like typeRef, but objects in the prefix are represented by their singleton type,
     *  this means we output `pre.O.member` rather than `pre.O$.this.member`.
```

**Review by smarter — APPROVED** [review]
LGTM, thanks!

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala (hunk 7 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: That's better, thanks 👍
