### PR TITLE
Enforce JVM UTF-8 string limits in the backend

### LINKED ISSUE #15850: "UTF8 string too large" in GenBCode
## Compiler version

3.1.3

## Minimized code

UPDATE: @s5bug minimised it perfectly

```scala
type Level1 = Tuple4[Unit, Unit, Unit, Unit]
type Level2 = Tuple4[Level1, Level1, Level1, Level1]
type Level3 = Tuple4[Level2, Level2, Level2, Level2]
type Level4 = Tuple4[Level3, Level3, Level3, Level3]
type Level5 = Tuple4[Level4, Level4, Level4, Level4]
type Level6 = Tuple4[Level5, Level5, Level5, Level5]
type Level7 = Tuple4[Level6, Level6, Level6, Level6]

def crash(x: Level7): Unit = ()
```

~I don't know how to minimise the code, as it's the first time I'm seeing this error and it only happens with this particular generated file.~

~Scala Native is also involved, but I don't believe it's in any way responsible (although I have no way of confirming that, given that code heavily relies on the SN definitions)~

~Here's the reproduction project with a single (huge) file that causes this.~

~https://github.com/keynmol/dotty-crash-demonstrator~

## Output (click arrow to expand)
<details>

```scala
java.lang.IllegalArgumentException: UTF8 string too large while compiling .../example-nuklear/target/scala-3.1.3/src_managed/main/nuklear.scala
[error] ## Exception when compiling 1 sources to .../example-nuklear/target/scala-3.1.3/classes
[error] java.lang.IllegalArgumentException: UTF8 string too large
[error] scala.tools.asm.ByteVector.putUTF8(ByteVector.java:246)
[error] scala.tools.asm.SymbolTable.addConstantUtf8(SymbolTable.java:774)
[error] scala.tools.asm.MethodWriter.<init>(MethodWriter.java:602)
[error] scala.tools.asm.ClassWriter.visitMethod(ClassWriter.java:446)
[error] scala.tools.asm.tree.MethodNode.accept(MethodNode.java:647)
[error] scala.tools.asm.tree.ClassNode.accept(ClassNode.java:452)
[error] dotty.tools.backend.jvm.GenBCodePipeline$Worker2.getByteArray$1(GenBCode.scala:483)
[error] dotty.tools.backend.jvm.GenBCodePipeline$Worker2.addToQ3(GenBCode.scala:489)
[error] dotty.tools.backend.jvm.GenBCodePipeline$Worker2.run(GenBCode.scala:467)
[error] dotty.tools.backend.jvm.GenBCodePipeline.buildAndSendToDisk(GenBCode.scala:568)
[error] dotty.tools.backend.jvm.GenBCodePipeline.run(GenBCode.scala:531)
[error] dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:67)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:311)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:312)
[error] dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:75)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:225)
```
</details>

### LINKED ISSUE #24597: `compiletime.testing.typeCheckErrors` can result in `UTF8 string too large` in JVM codegen
Based on the OpenCB failure in `plokhotnyuk/jsoniter-scala` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/19775426472/job/56667929815)

If the execution of macro results in StackOverflow or other exception with long stack trace, it might be too long when reaching the JVM backend - at this point the codegen would fail with exception
 
We should either trim the output of such macro, or detect it and fail early. Otherwise it's hard to discover exact place where failing macro was used. 

## Compiler version 

3.8 
3.3 LTS
All Scala versions

## Minimized code

```scala
def Test = scala.compiletime.testing.typeCheckErrors("stackOverflowMacro")
```

```scala
import scala.quoted.*

transparent inline def stackOverflowMacro: Int = ${ StackOverflowMacro.impl }

object StackOverflowMacro:
    def impl(using Quotes): Expr[Int] =  '{ ${impl} + ${impl} }
    

```

## Output

```scala
> scala compile test.scala test.macro.scala -S 3.8.0-RC2 --server=false
java.lang.IllegalArgumentException: UTF8 string too large
        at scala.tools.asm.ByteVector.putUTF8(ByteVector.java:255)
        at scala.tools.asm.SymbolTable.addConstantUtf8(SymbolTable.java:800)
        at scala.tools.asm.SymbolTable.addConstantUtf8Reference(SymbolTable.java:1053)
        at scala.tools.asm.SymbolTable.addConstantString(SymbolTable.java:630)
        at scala.tools.asm.SymbolTable.addConstant(SymbolTable.java:500)
        at scala.tools.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1281)
        at scala.tools.asm.tree.LdcInsnNode.accept(LdcInsnNode.java:75)
        at scala.tools.asm.tree.InsnList.accept(InsnList.java:144)
        at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:751)
        at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:649)
        at scala.tools.asm.tree.ClassNode.accept(ClassNode.java:468)
        at dotty.tools.backend.jvm.PostProcessor.serializeClass(PostProcessor.scala:101)
        at dotty.tools.backend.jvm.PostProcessor.sendToDisk(PostProcessor.scala:37)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit$$anonfun$1$$anonfun$1$$anonfun$1(GeneratedClassHandler.scala:94)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:327)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit$$anonfun$1$$anonfun$1(GeneratedClassHandler.scala:94)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit$$anonfun$1$$anonfun$adapted$1(GeneratedClassHandler.scala:96)
        at dotty.tools.backend.jvm.PostProcessorFrontendAccess$Impl.withThreadLocalReporter(PostProcessorFrontendAccess.scala:140)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit$$anonfun$1(GeneratedClassHandler.scala:96)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit$$anonfun$adapted$1(GeneratedClassHandler.scala:96)
        at scala.concurrent.Future$.apply$$anonfun$1(Future.scala:692)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:503)
        at dotty.tools.backend.jvm.GeneratedClassHandler$.SyncWritingClassHandler$superArg$1$$anonfun$1(GeneratedClassHandler.scala:146)
        at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:22)
        at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:465)
        at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:374)
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:325)
        at scala.concurrent.impl.Promise$DefaultPromise.map(Promise.scala:185)
        at scala.concurrent.Future$.apply(Future.scala:692)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.postProcessUnit(GeneratedClassHandler.scala:96)
        at dotty.tools.backend.jvm.GeneratedClassHandler$WritingClassHandler.process(GeneratedClassHandler.scala:82)
        at dotty.tools.backend.jvm.CodeGen.genUnit(CodeGen.scala:122)
        at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:90)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:386)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:327)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:379)
        at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:98)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1327)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
        at scala.Function0.apply$mcV$sp(Function0.scala:45)
        at dotty.tools.dotc.Run.showProgress(Run.scala:482)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:432)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:325)
        at dotty.tools.dotc.Run.compileSuspendedUnits(Run.scala:446)
        at dotty.tools.dotc.Driver.finish(Driver.scala:64)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:213)
        at dotty.tools.dotc.Driver.process(Driver.scala:181)
        at dotty.tools.dotc.Driver.process(Driver.scala:193)
        at dotty.tools.dotc.Driver.main(Driver.scala:223)
        at dotty.tools.dotc.Main.main(Main.scala)
Error while emitting test$package$
UTF8 string too large
1 error found
```

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #15850 
Fixes #24597 
Subsumes #19622

Enforce UTF-8 limits at bytecode generation time.

### CODE REVIEW

File: compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala [hunk 1]
```diff
@@ -570,8 +567,8 @@ trait BCodeBodyBuilder(val primitives: DottyPrimitives)(using ctx: Context) exte
      *   must-single-thread
      * Otherwise it's safe to call from multiple threads.
      */
-    def genConstant(const: Constant): Unit = {
-      (const.tag/*: @switch*/) match {
+    private def genConstant(const: Constant, pos: SrcPos): Unit = {
+      (const.tag: @switch) match {
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala:571]: I don't know why that `@switch` was commented out but it seems to work fine so might as well

File: compiler/src/dotty/tools/backend/jvm/BCodeHelpers.scala [hunk 2]
```diff
@@ -447,6 +447,9 @@ trait BCodeHelpers(val backendUtils: BackendUtils)(using ctx: Context) extends B
       val jReturnType = toTypeKind(methodInfo.resultType)
       val mdesc = MethodBType(paramJavaTypes, jReturnType).descriptor
       val mirrorMethodName = m.javaSimpleName
+      if !BCodeUtils.checkConstantStringLength(jgensig, mirrorMethodName, mdesc) then
+        report.error("Mirror method signature is too long for the JVM", m.srcPos)
+        return
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/backend/jvm/BCodeHelpers.scala:454]: I don't like having to duplicate this code for mirror generation, IMHO the backend should move towards a model where we first decide which classes and methods we're going to create, including JVM-specific synthetic stuff, and then emit these, but that's for later

File: compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala [hunk 3]
```diff
@@ -22,6 +22,37 @@ import scala.tools.asm
 //      (one can argue we should reuse one of the other existing helper objects, but that's for a later cleanup)
 
 object BCodeUtils {
+  val MAX_BYTES_PER_UTF8_CONSTANT = 65535
+  /** Checks that the given signature if present, or the concatenation of the given name and descriptor, do not exceed the JVM's UTF-8 text size limits. */
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala]: I'm not very happy about having to implement length detection for Java's subset of UTF-8, but we can't reuse ASM's because it's private and catching exceptions to test their message would be both ugly and too late to provide a position in the error...

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala [hunk 4]
```diff
@@ -956,7 +956,12 @@ trait ParallelTesting extends RunnerOrchestration:
               |${unexpected.mkString("Unexpected errors:\n", "\n", "")}
               |$showErrors
               |""".stripMargin.trim.linesIterator.mkString("\n", "\n", "")
-        else if hasMissingAnnotations then s"\nErrors found on incorrect row numbers when compiling $testSource\n$showErrors"
+        else if hasMissingAnnotations then
+          s"""|Errors found on incorrect row numbers when compiling $testSource
+              |$showErrors
+              |${expected.mkString("Unfulfilled expectations:\n", "\n", "")}
+              |${unexpected.mkString("Unexpected errors:\n", "\n", "")}
+              |""".stripMargin.trim.linesIterator.mkString("\n", "\n", "")
```
Comment (SolalPirelli) [inline compiler/test/dotty/tools/vulpix/ParallelTesting.scala:969]: Not directly related but it annoyed me when I put an `// error` on the wrong line not to have information on what went wrong. This is copied and adapted from the case just above.

File: compiler/src/dotty/tools/backend/jvm/PostProcessor.scala [hunk 5]
```diff
@@ -1,12 +1,13 @@
...
 import java.util.concurrent.ConcurrentHashMap
-
 import scala.collection.mutable.ListBuffer
-import dotty.tools.dotc.util.{SourcePosition, NoSourcePosition}
+import dotty.tools.dotc.util.{NoSourcePosition, SourcePosition}
 import dotty.tools.io.AbstractFile
 import dotty.tools.dotc.core.Contexts.*
 import dotty.tools.dotc.core.Decorators.em
+
+import scala.collection.JavaConverters.asScalaIteratorConverter
```
Comment (lrytz) [inline compiler/src/dotty/tools/backend/jvm/PostProcessor.scala]: accidental?

File: compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala [hunk 6]
```diff
@@ -22,6 +22,37 @@ import scala.tools.asm
...
+  def checkConstantStringLength(sig: String | Null, name: String, desc: String = ""): Boolean = {
```
Comment (lrytz) [inline compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala]: I think this method is a bit cryptic, having multiple methods (for signature, name+desc) would make things more clear. Eg, it's weird that we're passing a non-null signature and also a name at some callsites, but then the name is ignored.

File: compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala [hunk 7]
```diff
@@ -22,6 +22,37 @@ import scala.tools.asm
...
+      var byteCount = startAt
+      for
+        i <- 0 until str.length
+      do
+        val c = str.charAt(i)
+        byteCount += (
+          if c <= 0x7F then 1
+          else if c <= 0x7FF then 2
+          else if Character.isHighSurrogate(c) || Character.isLowSurrogate(c) then 2
+          else 3
```
Comment (lrytz) [inline compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala:46]: can you provide a reference (in a code comment) to where this is specified?

also the comment above says "can't be more than 4 bytes per char" but here we never have more than 3.

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala (hunk 4 above)
Comment (som-snytt) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:969]: I have added that code several times!  I just saw it again in this refreshed PR from 2022.
https://github.com/scala/scala3/pull/15624

File: compiler/src/dotty/tools/backend/jvm/PostProcessor.scala (hunk 5 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/backend/jvm/PostProcessor.scala]: Oops, I missed this file while self-reviewing, thanks for pointing it out

File: compiler/test/dotty/tools/vulpix/ParallelTesting.scala (hunk 4 above)
Comment (SolalPirelli) [reply compiler/test/dotty/tools/vulpix/ParallelTesting.scala:969]: good to know I'm not the only one... that PR added it for the 2nd case though (`expectedErrors == 0`), so this is not even a conflict :)

File: compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala (hunk 7 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala:46]: I added details in a comment at the top, which also led me to realize I had forgotten to handle the "null char" case because Java uses "modified UTF-8" which is... weird.

And indeed it's actually 3 bytes per char, I had mixed up char and codepoint in my mind when writing that.

File: compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala (hunk 6 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/backend/jvm/BCodeUtils.scala]: I simplified it

File: compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala [hunk 8]
```diff
@@ -873,7 +883,9 @@ trait BCodeSkelBuilder(using ctx: Context) extends BCodeHelpers {
       // TODO needed? for(ann <- m.symbol.annotations) { ann.symbol.initialize }
       val paramSyms = params.map(_.symbol)
       initJMethod(flags, paramSyms)
-
+      if mnode eq null then
```
Comment (lrytz) [inline compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala:886]: maybe `initJMethod` could return a boolean?

Comment (lrytz) [reply compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala:886]: Ah, I wanted to delete this nitpick comment..
