### PR TITLE
Do not simplify isInstanceOf if unrelated types might be subtypes at run-time

### LINKED ISSUE #25037: Wrongly elided expression by the compiler
## Compiler version

https://github.com/scala/scala3/commit/69c53236b3e89eaa20f1ef72beca5bd57cc11b37

## Minimized code

```scala
object Foo
def foo: Any = Foo
println(Foo.isInstanceOf[Serializable])
println(foo.isInstanceOf[Serializable])
```

## Output

```scala
false
true
```

## Expectation

The bytecode generator will add `Serializable` as a parent to all objects, but statically in the type system `Foo.this` is not a subtype of `Serializable`. As such, the compiler will elide that expression. It shouldn't.

### LINKED ISSUE #25097: Wrongly elided expression by the compiler (in Scala.js)
## Minimized code

```scala
val foo: Any = 1.0
println(1.0.isInstanceOf[Int])
println(foo.isInstanceOf[Int])
```

## Output

```scala
false
true
```

## Expectation

The expected value here is `true`. It is part of Scala.js specification for `isInstanceOf`.

## Note

Could be fixed at the same time as https://github.com/scala/scala3/issues/25037

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #25037
Fixes #25097

Introduce `typeMightBeSubtypeAtRuntime` in `Platform`, and use it in `TypeTestCasts` to avoid simplifying type tests that may have different behavior at runtime on a specific platform.

Implement this method for the JVM, where everything is `Serializable`, and Scala.js, where integer semantics are a little funny due to JS's "everything is a double" model.

Drop the "a value type cannot be an instance of a reference type" error as it's wrong, `1.isInstanceOf[Object]` is `true`, and move the neg test to a run test ensuring this.

## How much have your relied on LLM-based tools in this contribution?

not

## How was the solution tested?

new automated tests

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/config/Platform.scala [hunk 1]
```diff
@@ -49,4 +49,12 @@ abstract class Platform {
...
     sym.info.member(nme.main).hasAltWith(d =>
       isMainMethod(d.symbol) && (sym.is(Module) || d.symbol.isStatic))
+
+  /**
+   * Whether instances of the class represented by the class symbol `c` **might** be a subtype of
+   * the class represented by the class symbol `potentialSuperClass` at runtime on this platform.
+   * This does not imply that they always will be,
+   * only that the compiler cannot fold `x.isInstanceOf[potentialSuperClass]` to false for for `x: c`
+   */
+  def typeMightSubtypeAtRuntime(c: Symbol, potentialSuperClass: Symbol)(using Context): Boolean
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/config/Platform.scala]:
```suggestion
  def typeMightBeSubtypeAtRuntime(c: Symbol, potentialSuperClass: Symbol)(using Context): Boolean
```
?

File: compiler/src/dotty/tools/dotc/config/SJSPlatform.scala [hunk 2]
```diff
@@ -32,4 +32,9 @@ class SJSPlatform()(using Context) extends JavaPlatform {
    */
   override def shouldReceiveJavaSerializationMethods(sym: ClassSymbol)(using Context): Boolean =
     !sym.isSubClass(jsDefinitions.JSAnyClass)
+
+  override def typeMightSubtypeAtRuntime(c: Symbol, potentialSuperClass: Symbol)(using Context): Boolean =
+    // because we deal with primitive types, we also have to deal with the boxed version,
+    // otherwise the compiler will error with, e.g., "cannot test if scala.Double is a subtype of java.lang.Integer"
+    (defn.ScalaNumericValueClasses()(c) && (defn.ScalaNumericValueClasses()(potentialSuperClass) || defn.ScalaNumericBoxedClasses()(potentialSuperClass)))
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/config/SJSPlatform.scala]: You also have to test boxed classes on the left-hand-side. You could have `(x: jl.Integer).isInstanceOf[jl.Double]`.

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 3]
```diff
@@ -250,7 +251,7 @@ object TypeTestsCasts {
 
             val foundEffectiveClass = effectiveClass(expr.tpe.widen)
 
-            if foundEffectiveClass.isPrimitiveValueClass && !testCls.isPrimitiveValueClass then
+            if foundEffectiveClass.isPrimitiveValueClass && !testCls.isPrimitiveValueClass && !ctx.platform.typeMightSubtypeAtRuntime(foundEffectiveClass, testCls) then
               report.error(em"cannot test if value of $exprType is a reference of $testCls", tree.srcPos)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: This change does not seem right. The platform should not influence whether code compiles or not.

File: tests/run/i1354.scala [hunk 4]
```diff
@@ -1,3 +1,6 @@
+// scalajs: --skip
+// (because scala.js has special semantics for numbers)
```
Comment (sjrd) [inline tests/run/i1354.scala:2]: It would be good to decompose this test in two, so that we can still test relevant code paths on Scala.js. In particular, with a mix of `Int`, `Char` and `Boolean`, most of the tests below can still apply on Scala.js.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/config/Platform.scala (hunk 1 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/config/Platform.scala]: but I like verbing nouns :p ok ok

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala (hunk 3 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: there's 1 Scala.js test failing because I commented this out, I'll figure it out on Monday

Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: @sjrd I think this is a case of the compiler being a little over-eager with an error. This report could be a warning, there's nothing inherently broken with testing whether `A` is a subtype of `B` when we know it's unrelated. I pushed a commit with a comment explaining why we need to call the platform here.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: Hum. IMO in that case we must either
a) emit the compile error on JS as well, or
b) make it platform-dependent warning.

It makes no sense to have a platform-dependent compile error (unless there are interop features involved).

a) seems the most conservative here. IMO it's not nonsensical. One can argue that it's just a language rule that we forbid `prim.isInstanceOf[NonPrim]`. It doesn't need to have anything to do with the platform behavior.

Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: OK. Unfortunately the way we get here is not by a direct check in the code but by another part of this file doing some widening (what else? :) ) so let me figure this out...

Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: @sjrd so it turns out a few lines above there already was the infra to do basically (b), the `unreachable` function, so I used it.

However it's not strictly a platform-dependent warning because if we're in a pattern match we instead error with "unreachable case". Why that's an error and not a warning I don't know, but I don't think this PR should change that.

File: project/Build.scala [hunk 5]
```diff
@@ -2192,7 +2192,7 @@ object Build {
    */
   lazy val sjsJUnitTests = project.in(file("tests/sjs-junit")).
     enablePlugins(DottyJSPlugin).
-    dependsOn(`scala-library-sjs`).
+    dependsOn(`scala-library-sjs`, `scala3-compiler-bootstrapped`).
```
Comment (SolalPirelli) [inline project/Build.scala]: since these unit tests also depend on the compiler...

File: project/Build.scala [hunk 6]
```diff
@@ -2192,7 +2192,7 @@ object Build {
...
     settings(
       regularScalaJSProjectSettings,
       bspEnabled := false,
```
Comment (SolalPirelli) [inline project/Build.scala:2200]: for the deleted file below, I changed it to a "warn" test since that aligns with how the compiler was handling other such issues

File: project/Build.scala (hunk 5 above)
Comment (sjrd) [reply project/Build.scala]: I'm afraid that's wrong. That puts the compiler code on the classpath of `sjsJUnitTests` ! (also fixing this should be a separate PR anyway)

File: tests/warn/typetest.check [hunk 7]
```diff
@@ -0,0 +1,4 @@
+-- Warning: tests/warn/typetest.scala:5:10 -----------------------------------------------------------------------------
+5 |  println(i.isInstanceOf[Object])                     // warning
+  |          ^
+  |          this will always yield false since type Int is a primitive and class Object is a reference
```
Comment (sjrd) [inline tests/warn/typetest.check]: It's going to say `true` if you actually run it, though, isn't it?

If it's meant as a progression test, say so in a comment on the test.

File: project/Build.scala (hunk 6 above)
Comment (sjrd) [reply project/Build.scala:2200]: GitHub tip: you can comment on a whole file with the comment icon in the top right corner of a file's diff. This is true even for deleted files.

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 8]
```diff
@@ -249,10 +250,8 @@ object TypeTestsCasts {
             end check
 
             val foundEffectiveClass = effectiveClass(expr.tpe.widen)
-
-            if foundEffectiveClass.isPrimitiveValueClass && !testCls.isPrimitiveValueClass then
-              report.error(em"cannot test if value of $exprType is a reference of $testCls", tree.srcPos)
-              false
+            if foundEffectiveClass.isPrimitiveValueClass && !testCls.isPrimitiveValueClass && !ctx.platform.typeMightBeSubtypeAtRuntime(foundEffectiveClass, testCls) then
+              unreachable(i"$exprType is a primitive and $testCls is a reference")
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala]: I still think it's dubious to report a compile error (when `inMatch` is true) dependent on the platform. Consider
```suggestion
            if foundEffectiveClass.isPrimitiveValueClass && !testCls.isPrimitiveValueClass &&
                (inMatch || !ctx.platform.typeMightBeSubtypeAtRuntime(foundEffectiveClass, testCls)) then
              unreachable(i"$exprType is a primitive and $testCls is a reference")
```

File: project/Build.scala (hunk 6 above)
Comment (SolalPirelli) [reply project/Build.scala:2200]: Neat!

File: tests/warn/typetest.check (hunk 7 above)
Comment (SolalPirelli) [reply tests/warn/typetest.check]: no, it does say `false`, at least running on the JVM

Comment (sjrd) [reply tests/warn/typetest.check]: Well, that would then be a bug, because `(1: Any).isInstanceOf[Object]` definitely answers `true` today. It would be inconsistent for `1.isInstanceOf[Object]` to return `false`.

Comment (SolalPirelli) [reply tests/warn/typetest.check]: It makes sense to me thinking of `: Any` as a boxing operation, a value type instance isn't an instance of Object until you box it.

Comment (sjrd) [reply tests/warn/typetest.check]: No. Boxing is supposed to be transparent in Scala. There's no "boxing operation".

For example, you can still reproduce the result `true` without ever upcasting to `Any`:
```scala
scala> def test[T](x: T): Boolean = x.isInstanceOf[Object]; test[Int](5)
def test[T](x: T): Boolean
val res90: Boolean = true
```

Comment (lrytz) [reply tests/warn/typetest.check]: .. could you say in the PR description what this PR changes? I wanted to take a quick look to understand, having a summary would really help.

Comment (SolalPirelli) [reply tests/warn/typetest.check]: Will do as soon as we agree on what that is 😂

Comment (SolalPirelli) [reply tests/warn/typetest.check]: To be clear this test currently fails to compile on `main`: https://github.com/scala/scala3/blob/main/tests/neg/typetest.scala

Comment (lrytz) [reply tests/warn/typetest.check]: It was more of a general remark; you know what you changed, the thoughts behind it, the research you did. It saves reviewers a lot of time if you can summarize it in the PR description and commit message.

**Comment by SolalPirelli** [comment]
@sjrd I pushed a silly commit that comments out this warning/error entirely and... the only test that fails in the compiler is this `typetest.scala` that appears to be wrong today too. Should I properly delete the warning/error and figure out how to make `1.isInstanceOf[Object]` return `true` as it should?

**Comment by sjrd** [comment]
Let's do that, yes.
