### PR TITLE
Fix #8745: Match Ident prefixes to find potential holes

### LINKED ISSUE #8745: Quoted matching on imported method causes tuple class-cast exception
## Minimized code

Let's say I have a trait with a method extended by a companion:
```Scala
object Companion extends Trait
trait Trait {
  def fun(first: String): String = "anything"
}
```
Then I try to match this code in a macro:
```scala
tree.unseal.underlyingArgument.seal match {
    case vv @ '{ ($s: Trait).fun($arg) } => arg
}
```
When invoking the macro with the `Companion` as an import:
```scala
import Companion._
mac(fun("blah"))
```
The following compiler error occurs:
```
Exception occurred while executing macro expansion.
java.lang.ClassCastException: scala.Tuple1 cannot be cast to scala.Tuple2
    at companionbug.Macro$.macImpl(Macro.scala:16)
```

## Expectation
The code should compile and the match should work.

## Code Sample
Full code sample can be found here:
https://github.com/deusaquilus/companion_bug

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: library/src/scala/internal/quoted/Matcher.scala [hunk 1]
```diff
@@ -271,13 +271,17 @@ private[quoted] object Matcher {
           case (scrutinee, Typed(expr2, _)) =>
             scrutinee =?= expr2
 
-
           /* Match selection */
-          case (Select(qual1, _), Select(qual2, _)) if scrutinee.symbol == pattern.symbol =>
-            qual1 =?= qual2
+          case (ref: Ref, Select(qual2, _)) if scrutinee.symbol == pattern.symbol =>
```
Comment (smarter) [inline library/src/scala/internal/quoted/Matcher.scala:275]: Consider using `tpd.desugarIdent`

Comment (nicolasstucki) [reply library/src/scala/internal/quoted/Matcher.scala]: Good idea. I will use it.

File: library/src/scala/internal/quoted/Matcher.scala [hunk 2]
```diff
@@ -271,13 +271,16 @@ private[quoted] object Matcher {
...
             scrutinee =?= expr2
 
-
           /* Match selection */
           case (Select(qual1, _), Select(qual2, _)) if scrutinee.symbol == pattern.symbol =>
             qual1 =?= qual2
+          case (ref: Ident, Select(qual2, _)) if scrutinee.symbol == pattern.symbol =>
+            Ref.desugarIdent(ref) match
+              case Select(qual1, _) => qual1 =?= qual2
+              case _ => matched
```
Comment (liufengyun) [inline library/src/scala/internal/quoted/Matcher.scala:280]: Or do a type test instead?

File: library/src/scala/tasty/reflect/CompilerInterface.scala [hunk 3]
```diff
@@ -319,6 +319,12 @@ trait CompilerInterface {
 
   def isInstanceOfRef(using ctx: Context): IsInstanceOf[Ref]
 
+  /** A tree representing the same reference as the given type */
+  def Ref_term(tp: TermRef)(using ctx: Context): Ref
+
+  /** Desugar identifier into a select node. Return the tree itself if not possible */
+  def Ref_desugarIdent(tree: Ident)(using ctx: Context): Ref
```
Comment (liufengyun) [inline library/src/scala/tasty/reflect/CompilerInterface.scala:326]: I guess this is only used to implement quoted pattern match, maybe add `private[scala]`?

File: library/src/scala/internal/quoted/Matcher.scala (hunk 2 above)
Comment (nicolasstucki) [reply library/src/scala/internal/quoted/Matcher.scala:280]: No, I need to do the recursion because `qual2` may contain a term hole that needs to be matched.

File: library/src/scala/tasty/reflect/CompilerInterface.scala (hunk 3 above)
Comment (nicolasstucki) [reply library/src/scala/tasty/reflect/CompilerInterface.scala:326]: It seems to be useful in general. It is that or having a unified representation of `Ref` as @smarter suggested. We should discuss.
