### PR TITLE
Fix #10867: Normalize after applyIfParameterized in superType

### LINKED ISSUE #10867: [3.0.0-M3] Curried type function not working as expected
## Minimized code

```Scala
type inserts[a, as <: Tuple] <: Tuple =
  as match
    case EmptyTuple => (a *: EmptyTuple) *: EmptyTuple
    case y *: ys => (a *: y *: ys) *: Tuple.Map[inserts[a, ys], [t <: Tuple] =>> y *: t]

type inserts2[a] =  
  [as <: Tuple] =>> inserts[a, as]

type A = inserts [1, EmptyTuple]
type B = inserts2[1][EmptyTuple]

summon[A =:= ((1 *: EmptyTuple) *: EmptyTuple)]
summon[B =:= ((1 *: EmptyTuple) *: EmptyTuple)]
summon[A =:= B]

type H[t <: Tuple] = Tuple.Concat[t, EmptyTuple]

summon[H[A] =:= H[B]]

// error!
summon[Tuple.Concat[A, EmptyTuple] =:= Tuple.Concat[B, EmptyTuple]]

```

## Output

```scala
// Cannot prove that ((1 : Int) *: EmptyTuple) *: EmptyTuple =:= Tuple.Concat[B, EmptyTuple]
```

## Expectation
The snippet should compile.

(it compiles in `3.0.0-M2` but not in `3.0.0-M3`)

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -4110,7 +4110,7 @@ object Types {
         cachedSuper = tycon match {
           case tycon: HKTypeLambda => defn.AnyType
           case tycon: TypeRef if tycon.symbol.isClass => tycon
-          case tycon: TypeProxy => tycon.superType.applyIfParameterized(args)
+          case tycon: TypeProxy => tycon.superType.applyIfParameterized(args).normalized
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/Types.scala:4113]: I am not sure whether the caching is permissible here. If we normalize, are we certain that the next time around when we demand the super type of an applied type, we get the same normalization result? It does not look obvious to me. 
Maybe we should do this instead.
```scala
    override def superType(using Context): Type =
      if ctx.period != validSuper then
        validSuper = if (tycon.isProvisional) Nowhere else ctx.period
        def reappliedSuper = tycon.superType.applyIfParameterized(args).normalized
        cachedSuper = tycon match
          case tycon: HKTypeLambda => defn.AnyType
          case tycon: TypeRef =>
            if tycon.symbol.isClass then tycon
            else
              if tycon.info.isInstanceof[MatchAlias] then validSuper = Nowhere
              reappliedSuper
          case tycon: TypeProxy => reappliedSuper
          case _ => defn.AnyType
      cachedSuper
```

**Review by odersky — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/core/Types.scala (hunk 1 above)
Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: I updated the PR to change validity of the cache for normalizing match types.

**Comment by odersky** [comment]
LGTM

**Review by odersky — APPROVED** [review]
