### PR TITLE
Regression test

### LINKED ISSUE #15881: Parsed Java breaks eta expansion to SAM type for Java class
## Compiler version

3.2.1-RC1-bin-SNAPSHOT

## Minimized code

```Scala
// J.java
public abstract class J {
        public abstract int f(int i);
}
// K.java
public interface K {
        int f(int i);
}
// s.scala
class C {
  def f(j: J): Int = j.f(42)
  def g(k: K): Int = k.f(17)
}
object Test extends App {
  def bump(i: Int): Int = i + 1
  val c = new C
  println {(
    c.f((i: Int) => i + 1),
    c.g((i: Int) => i + 1),
    c.f(bump),
    c.g(bump),
  )}
}
```

## Output

Expectedly, javac-first succeeds and warns:
```scala
➜  t11644-java javac -d out *.java && ~/projects/dotty/bin/scalac -d out -cp out *.scala && ~/projects/dotty/bin/scala -cp out Test
-- Warning: s.scala:12:8 -----------------------------------------------------------------------------------------------
12 |    c.f(bump),
   |        ^^^^
   |        method bump is eta-expanded even though J does not have the @FunctionalInterface annotation.
-- Warning: s.scala:13:8 -----------------------------------------------------------------------------------------------
13 |    c.g(bump),
   |        ^^^^
   |        method bump is eta-expanded even though K does not have the @FunctionalInterface annotation.
2 warnings found
(43,18,43,18)
```
Unexpectedly, 
```scala
➜  t11644-java ~/projects/dotty/bin/scalac -d out *a
-- [E007] Type Mismatch Error: s.scala:10:8 ----------------------------------------------------------------------------
10 |    c.f((i: Int) => i + 1),
   |        ^^^^^^^^^^^^^^^^^
   |        Found:    Int => Int
   |        Required: J
   |
   | longer explanation available when compiling with `-explain`
-- [E007] Type Mismatch Error: s.scala:12:8 ----------------------------------------------------------------------------
12 |    c.f(bump),
   |        ^^^^
   |        Found:    Int => Int
   |        Required: J
   |
   | longer explanation available when compiling with `-explain`
-- Warning: s.scala:13:8 -----------------------------------------------------------------------------------------------
13 |    c.g(bump),
   |        ^^^^
   |        method bump is eta-expanded even though K does not have the @FunctionalInterface annotation.
1 warning found
2 errors found
```

## Expectation

Parsed Java should not break eta expansion to SAM type for Java class.

Noticed while aligning Scala 2 warnings.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #15881 

Regression test for https://github.com/scala/scala3/pull/18201

I didn't look closely at the ticket, as to whether there is a Java-specific component. Apparently, I thought so.

The test compiles from 3.3.5 with warning.

### CODE REVIEW

File: tests/pos/i15881/J.java [hunk 1]
```diff
@@ -0,0 +1,3 @@
+public abstract class J {
+        public abstract int f(int i);
```
Comment (noti0na1) [inline tests/pos/i15881/J.java:2]: Who would write 8 whitespace for indent? 😶
