### PR TITLE
Make HOAS Quote pattern match with def method capture 

### LINKED ISSUE #17105: HOAS quote pattern fails to match with def caprure
## Compiler version

3.2

## Minimized code

```Scala
// Macro_1.scala
import scala.quoted.*

inline def test: String =  ${ testExpr }
def testExpr(using Quotes): Expr[String] =
  '{ def f(x: Int) = 1; f(3) } match
    case '{ def g(y: Int) = 1; $a(g): Int } =>  Expr(a.show)
    case _ => Expr("not matched")
```

```scala
// Test_2.scala
def app = test
```

## Output
`scalac -Xprint:inlining Macro_1.scala Test_2.scala`

```scala
package <empty> {
  final lazy module val Test_2$package: Test_2$package = new Test_2$package()
  @SourceFile("t/Test_2.scala") final module class Test_2$package() extends
    Object() { this: Test_2$package.type =>
    private def writeReplace(): AnyRef =
      new scala.runtime.ModuleSerializationProxy(classOf[Test_2$package.type])
    def app: String = "not matched":String
  }
}
```

## Expectation

The quote pattern should match and the result should be something like
```scala
    def app: String = "(g: Int => Int) => g(3)":String
```

### PR DESCRIPTION
**Pull request by zeptometer**
This PR will fix #17105 by extracting symbols from eta-expanded identifiers.

This fix enables the use of patterns such as
```scala
case '{ def f(...): T = ...; $g(f): U } => 
```
where `g` will match any expression that may contain references to `f`.

### CODE REVIEW

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 1]
```diff
@@ -206,12 +206,35 @@ object QuoteMatcher {
...
+           * f: (using Int) => Int
+           * => f(using x)
+           * This function restores the symbol of the original method from
+           * the eta-expanded function.
+           */
+          def getCapturedIdent(arg: Tree)(using Context): Ident =
+            arg match
+              case id: Ident => id
+              case Apply(term, _) => getCapturedIdent(term)
+              case Block((ddef: DefDef) :: _, _) => getCapturedIdent(ddef.rhs)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:227]:
```suggestion
              case Block((ddef: DefDef) :: _, _: Closure) => getCapturedIdent(ddef.rhs)
```

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 2]
```diff
@@ -206,12 +206,35 @@ object QuoteMatcher {
...
+              // How should I deal with it?
+              case y => ???
+
           val env = summon[Env]
-          val capturedArgs = args.map(_.symbol)
-          val captureEnv = env.filter((k, v) => !capturedArgs.contains(v))
+          val capturedIds = args.map(getCapturedIdent)
+          val capturedSymbols = capturedIds.map(_.symbol)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:233]: `getCapturedIdent` could return the `Symbol` directly. This way, we can avoid this extra `map`.

File: tests/run-macros/i17105.check
Comment (nicolasstucki) [inline tests/run-macros/i17105.check:1]: These outputs show that we need to adapt the type of `g` in the lambdas. For example `g: (y: scala.Int)scala.Int` should be `g: scala.Int => scala.Int`. We probably need to addapt the type here 
https://github.com/lampepfl/dotty/blob/main/compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala#LL468C13-L468C13. We need to convert `MethodType`s into funtion types. The `defn.FunctionOf` method might be useful here (defined in `Definitions.scala`).

I would expect this output to look like
```
((g: scala.Int => scala.Int, n: scala.Int) => g(n))
((g: (scala.Int, scala.Int) => scala.Int) => g(1, 2))
((g2: (scala.math.Ordered[scala.Int]) => scala.Boolean, ord: scala.math.Ordered[scala.Int]) => (g2(ord).||(2.<(3)): scala.Boolean))
```

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 2 above)
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:233]: Here I intended to use `capturedIds`  as a parameter to `matchedOpen` (we get compiler errors if we use `args` instead).

Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:233]: According to your other comment on i17105.check, it's likely I need to change this part anyway.

File: tests/run-macros/i17105.check
Comment (zeptometer) [reply tests/run-macros/i17105.check:1]: Thank you, I'll try to fix this issue (and add appropriate test cases)

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 3]
```diff
@@ -206,12 +206,35 @@ object QuoteMatcher {
...
+           * => f(using x)
+           * This function restores the symbol of the original method from
+           * the eta-expanded function.
+           */
+          def getCapturedIdent(arg: Tree)(using Context): Ident =
+            arg match
+              case id: Ident => id
+              case Apply(term, _) => getCapturedIdent(term)
+              case Block((ddef: DefDef) :: _, _) => getCapturedIdent(ddef.rhs)
+              // How should I deal with it?
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:228]: TODO: Add case for `Typed(term)` @zeptometer

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 4]
```diff
@@ -206,12 +206,35 @@ object QuoteMatcher {
...
+              case y => ???
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:229]: The standard way to emit errors is `report.error(msg, pos)` or `report.error(msg, tree)`.

[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:229]: In this case, I would remove the default case and let the compiler crash. If we reach that point, it is a compiler bug, not a user error. The default match error will show the tree that we missed, which is what we need to know to be able to add the missing case.

[the remark this answers is not in the document]
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:229]: Got it, then I'll follow that way. Thank you!

File: tests/run-macros/i17105.check
Comment (nicolasstucki) [reply tests/run-macros/i17105.check:1]: `Int => Int` could also be `scala.Function1[scala.Int, scala.Int]`. From `Function0` up to `Function22` we have concrete `FnunctionN` classes that implement the lambda type. `T => R` is equivalent to `Function1[T, R]` in the Scala type system. This only applies to normal function parameters, not if the argument is implicit as in `def f(using T): R = ...` or `T ?=> R` (similar for functions that contain erased parameters).

**Comment by zeptometer** [comment]
Hi @nicolasstucki,  I'm trying to fix the issue that types of parameters in higher-order term holes being method types with the commit 209d7637b8a7d08d812f64572be5932c83776257.

However, the current hotfix fails even with the simplest test case (I used [this test case](https://gist.github.com/zeptometer/d1724f6fdc82d2ff23868ec50aea539c)). I got the following error

```
-- Error: /home/yuito/code/dotty-workspace/issue-17105/test_2.scala:7:43 -------
7 |  testExpr { def f(x: Int) = "hello" * x; f(0) + "bye" }
  |                                          ^^^^
  |                                      parameter g does not take parameters
```

I found this message is caused at a method in [QuoteMatcher.scala:l524](https://github.com/lampepfl/dotty/blob/57c2b665117e0d10d490677edd0f83e093f80b97/compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala#L524), which generates a method body from a quote that matched against higher-order term pattern.

```scala
        def bodyFn(lambdaArgss: List[List[Tree]]): Tree = {
          val argsMap = args.view.map(_.symbol).zip(lambdaArgss.head).toMap
          val body = new TreeMap {
            override def transform(tree: Tree)(using Context): Tree =
              tree match
                case tree: Ident => env.get(tree.symbol).flatMap(argsMap.get).getOrElse(tree)
                case tree => super.transform(tree)
          }.transform(tree)
          TreeOps(body).changeNonLocalOwners(meth)
        }
```

In the test case, the matched body is `f(0) + ("bye")` and the current `bodyFn` turns it into `g(0) + ("bye")` (given `f` maps to `g`). However, here `g` has a function type `Int => String` whereas `f` has a method type `(y: Int) => String`: hence the method call `g(0)` fails (because only methods are allowed to apply at this stage... as far as I understand).

To avoid this issue, we want to refine `bodyFn` to convert `f(0)` to `g.apply(0)`. I guess it will be something like this

```scala
              tree match
                case Apply(fnId: Ident, args) => {
                  val fnId2 = env.get(tree.symbol).flatMap(argsMap.get).getOrElse(tree)
                  ??? // Not sure what is desirable way to construct Tree here...
                }
                case tree => super.transform(tree)
```

That's something I'd like your feedback. Does it sound valid to you? If so, what can I fill for ??? part?

**Comment by zeptometer** [comment]
I managed to fix a part of issue via 7f2771ecd4bd6c798130d7c99c5cdf5968788f47 and added a test case in 5e452099645e470ef82263ee23d801734daab41a 👍 I'll try to generalize the fix to accommodate other patterns.

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 1 above)
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Thank you, added in b120ffb32d40d6b684fdceacf3ff890fe984fad6

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 3 above)
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Done in b120ffb32d40d6b684fdceacf3ff890fe984fad6

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 4 above)
[the remark this answers is not in the document]
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Applied in b120ffb32d40d6b684fdceacf3ff890fe984fad6

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 5]
```diff
@@ -465,14 +510,43 @@ object QuoteMatcher {
...
+                        args.map(untpd.TypedSplice(_)))))
+                    .getOrElse(super.transform(tree))
+                case Apply(fun, args) =>
+                  val tfun = transform(fun)
+                  val targs = transform(args)
+                  tfun.tpe match
+                    // TODO issue-17105: Is this pattern appropriate for methods?
+                    case tp: MethodOrPoly => cpy.Apply(tree)(tfun, targs)
+                    // TODO issue-17105: Appropriate pattern for function (appliable?) types?
+                    case _ => ctx.typer.typed(
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:546]: Is this the right way to construct a typed tree?

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 6]
```diff
@@ -465,14 +510,43 @@ object QuoteMatcher {
...
+                      untpd.Apply(
+                        untpd.Select(untpd.TypedSplice(fnId), nme.apply),
+                        args.map(untpd.TypedSplice(_)))))
+                    .getOrElse(super.transform(tree))
+                case Apply(fun, args) =>
+                  val tfun = transform(fun)
+                  val targs = transform(args)
+                  tfun.tpe match
+                    // TODO issue-17105: Is this pattern appropriate for methods?
+                    case tp: MethodOrPoly => cpy.Apply(tree)(tfun, targs)
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:544]: Is this the right pattern to match against methods?

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 7]
```diff
@@ -465,14 +510,43 @@ object QuoteMatcher {
...
+                 * Remaining TODOs from issue-17105
+                 * * [x] cover the case of nested method call
+                 * * [ ] contextual params?
+                 * * [ ] erasure types?
+                 * * [x] eta-expand only HOAS param methods
+                 */
+                case Apply(methId: Ident, args) =>
+                  env.get(tree.symbol).flatMap(argsMap.get)
+                    .map(fnId => ctx.typer.typed(
+                      untpd.Apply(
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:535]: Is this the right pattern to construct typed tree?

File: tests/run-macros/i17105/Macro_1.scala [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+def testExprImpl(body: Expr[Any])(using Quotes): Expr[String] =
+  body match
+    case '{ def g(y: String) = "placeholder" + y; $a(g): String } =>
+      '{ $a((z: String) => s"[1st case] ${z}") }
+    case '{ def g(y: String)(z: String) = "placeholder" + y; $a(g): String } =>
+      '{ $a((z1: String) => (z2: String) =>  s"[2nd case] ${z1}, ${z2}") }
+    case '{ given i: String = "given"; def g(using s: String) = "placeholder"; $a(g, i): String } =>
+      '{ $a((s: String) => s"[3rd case] ${s}")(0) }
+    /* TODO issue-17105: This causes type error due to another issue from issue-17105 */
+    // case '{ def g(using s: String) = "placeholder"; $a(g) } =>
```
Comment (zeptometer) [inline tests/run-macros/i17105/Macro_1.scala:13]: With this test case, I got the following error.

```
-- [E172] Type Error: /home/yuito/code/dotty-workspace/issue-17105/macro_1.scala:39:56
39 |    case '{ def g(using s: String) = "placeholder"; $a(g): String } =>
   |                                                        ^
   |  No given instance of type String was found for parameter s of method g
```

This seems to be undesirable behavior considering that we don't necessarily resolve
contextual parameters at this point. If it's an issue, it should be fixed as another issue from this issue.

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 7 above)
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:535]: Typing an untyped tree is dangerous. Depending on the context where this is typed, we could end up with different result. It is also a bit inefficient.

The correct way to do this is to create the typed tree directly. In this case you can use the `select` and `appliedToArgs` helper methods to construct this tree. The code should be `fnId.select(nme.apply).appliedToArgs(args))`.

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 9]
```diff
@@ -449,6 +474,26 @@ object QuoteMatcher {
...
+     * PR-17567 Remaining TODOs
+     * * [ ] Implicit / Contextual parameters
+     * * [x] Nested Method Types
+     * * [ ] Erased Types
+     */
+    def adaptTypes(tpe: Type)(using Context): Type =
+      new Types.TypeMap {
+          def apply(tp: Types.Type): Types.Type = tp match
+            case tp: MethodType => {
+              val paramInfos = tp.paramInfos map adaptTypes
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:490]: Here it would be better to call `tp.paramInfos.map.apply(apply)`. Calling it through `adaptTypes` requires the creation of a new `TypeMap` in each recursion.

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 10]
```diff
@@ -449,6 +474,26 @@ object QuoteMatcher {
...
+              val resultType = adaptTypes(tp.resultType)
+              return defn.FunctionOf(paramInfos, resultType)
+            }
+            case _ => mapOver(tp)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:494]: We do not want to do the recursion on all nested types. We only need to map the outermost `MethodType` (and `PolyType` in later on) into lambda types.

Note that there are cases where we can encounter `MethodType` that we do not want to if we have refinement types. For example 
```scala
case '{
  def f(x: { def g(i: Int): Int } ): Unit = ...
  $h(f)
}
```
where `h` would have type `Expr[({ def g(i: Int): Int }) => Unit]` where the `MethodType` of `g` would not be modified.

Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:494]: This is probably what we need
```scala
    def adaptTypes(tpe: Type)(using Context): Type = tpe match
      case tp: MethodType =>
        defn.FunctionOf(tp.paramInfos, adaptTypes(tp.resultType)/*, tp.isImplicitMethod*/) // or tp.isContextualMethod
      case _ =>
        tpe
```

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 11]
```diff
@@ -465,15 +505,31 @@ object QuoteMatcher {
...
+                 * `g.apply(0)` because the type of `g` is `Int => Int` due to eta expansion.
+                 *
+                 * Remaining TODOs from issue-17105
+                 * * [x] cover the case of nested method call
+                 * * [ ] contextual params?
+                 * * [ ] erasure types?
+                 * * [x] eta-expand only HOAS param methods
+                 */
+                case Apply(_, _) if !tree.tpe.isInstanceOf[MethodicType] && env.contains(tree.symbol) =>
+                  def adaptMethodCalls(t: Tree): Tree = t match
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:528]: This code assumes that `tree` in this case is always in the form of `f(arg1)...(argn)`. Is it a safe assumption?

Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:528]: Yes. If not all arguments are applied in the source, the application is eta-expanded to provide the missing arguments explicitly to the call.

File: tests/run-macros/i17105/Macro_1.scala (hunk 8 above)
Comment (nicolasstucki) [reply tests/run-macros/i17105/Macro_1.scala:21]: We should fix that in another PR.

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 12]
```diff
@@ -465,15 +505,31 @@ object QuoteMatcher {
...
+                    case id: Ident => env.get(id.symbol).flatMap(argsMap.get).getOrElse(t)
+                    case Apply(f, a) => adaptMethodCalls(f).select(nme.apply).appliedToArgs(a)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:530]:
```suggestion
                    case Apply(fun, args) => adaptMethodCalls(fun).select(nme.apply).appliedToArgs(args)
```

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 13]
```diff
@@ -206,12 +207,34 @@ object QuoteMatcher {
...
+           *
+           * f: (using Int) => Int
+           * => f(using x)
+           * This function restores the symbol of the original method from
+           * the eta-expanded function.
+           */
+          def getCapturedIdent(arg: Tree)(using Context): Ident =
+            arg match
+              case id: Ident => id
+              case Apply(term, _) => getCapturedIdent(term)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:227]:
```suggestion
              case Apply(fun, _) => getCapturedIdent(fun)
```

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 14]
```diff
@@ -206,12 +207,34 @@ object QuoteMatcher {
...
+              case Block((ddef: DefDef) :: _, _: Closure) => getCapturedIdent(ddef.rhs)
+              case Typed(term, _) => getCapturedIdent(term)
```
Comment (nicolasstucki) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:229]:
```suggestion
              case Typed(expr, _) => getCapturedIdent(expr)
```

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 9 above)
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Fixed, thank you

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala (hunk 10 above)
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Fixed, thank you. I should add this test case.

File: tests/run-macros/i17105/Macro_1.scala (hunk 8 above)
Comment (zeptometer) [reply tests/run-macros/i17105/Macro_1.scala:21]: Note: I created another issue https://github.com/lampepfl/dotty/issues/17905

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 15]
```diff
@@ -341,19 +383,22 @@ object QuoteMatcher {
...
-                        (param1, param2) <- clause1.zip(clause2)
-                      yield
-                        param1.symbol -> param2.symbol
-                    val oldEnv: Env = summon[Env]
-                    val newEnv: List[(Symbol, Symbol)] = (scrutinee.symbol -> pattern.symbol) :: paramSyms
-                    oldEnv ++ newEnv
-                  matchLists(paramss1, paramss2)(_ =?= _)
-                    &&& tpt1 =?= tpt2
-                    &&& withEnv(rhsEnv)(scrutinee.rhs =?= pattern.rhs)
+                  def matchParamss(scparamss: List[ParamClause], ptparamss: List[ParamClause])(using Env): optional[(Env, MatchingExprs)] =
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:386]: This method was necessary to match with nested dependent types such as
```
case '{
      def p(dsl: DSL)(a: dsl.N): dsl.N = a
      $y(p): String
    } =>
      '{ $y((dsl: DSL) => (b2: dsl.N) => dsl.next(b2)) }
```
where second param types are dependent on first params.

Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:392]: Yes, I've added it to test cases. https://github.com/lampepfl/dotty/pull/17567/files#diff-f7f4e796d4ad68562b3441959fa979ec8c04b2ff8981ae8a9bf7c7f83555d389R12-R19

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 16]
```diff
@@ -341,19 +383,31 @@ object QuoteMatcher {
...
+                        (resEnv, mr1 &&& mrrest)
+                      case (Nil, Nil) => (summon[Env], matched)
+                      case _ => notMatched
+                    }
+
+                  val ematch = matchErasedParams(scrutinee, pattern)
+                  val (pEnv, pmatch) = matchParamss(paramss1, paramss2)
+                  val defEnv = pEnv + (scrutinee.symbol -> pattern.symbol)
+
+                  ematch
```
Comment (zeptometer) [inline compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:407]: `ematch` is always `Seq.empty` and `pmatch` should also return `Seq.empty`.
Should I remove the part `ematch &&& pmatch &&&` to simplify logic?

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 17]
```diff
@@ -166,6 +167,25 @@ object QuoteMatcher {
       val scrutinee = normalize(scrutinee0)
       val pattern = normalize(pattern0)
 
+      inline def notMatched[T]: optional[T] =
```
[the remark this answers is not in the document]
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala:170]: I considered the following approach, but catch with `boundary.Break` might not be very good idea (maintainability & performance). How do you think?

```
 catch {
        case _: boundary.Break[MatchingExprs] =>
          if (debug)
            val quotes = QuotesImpl()
            println(
              s""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                  |Scrutinee
                  |  ${scrutinee.show}
                  |did not match pattern
                  |  ${pattern.show}
                  |
                  |with environment: ${summon[Env]}
                  |
                  |Scrutinee: ${quotes.reflect.Printer.TreeStructure.show(scrutinee.asInstanceOf)}
                  |Pattern: ${quotes.reflect.Printer.TreeStructure.show(pattern.asInstanceOf)}
                  |
                  |""".stripMargin)
          notMatched
      }
```

**Comment by zeptometer** [comment]
The latest test report says that the test case quote-nested-6.scala fails, but it passes in my environment https://github.com/lampepfl/dotty/actions/runs/5298658706/jobs/9591140406?pr=17567

```
Output from 'tests/run-staging/quote-nested-6.scala' did not match check file. Actual output:
{
  type T[X] = [A >: scala.Nothing <: scala.Any] =>> scala.collection.immutable.List[A][X]
  val x: java.lang.String = "foo"
  val z: [X >: scala.Nothing <: scala.Any] =>> scala.collection.immutable.List[X][java.lang.String] = scala.List.apply[java.lang.String](x)

  (x: java.lang.String)
}


Test output dumped in: tests/run-staging/quote-nested-6.check.out
  See diff of the checkfile (`brew install icdiff` for colored diff)
    > diff tests/run-staging/quote-nested-6.check tests/run-staging/quote-nested-6.check.out
  Replace checkfile with current output
    > mv tests/run-staging/quote-nested-6.check.out tests/run-staging/quote-nested-6.check
      
foo
```

The issue is that I cannot reproduce this failure in my environment. It might be due to different JDK (I'm using OpenJDK 11). I'll try switching OpenJDK 16.

**Comment by nicolasstucki** [comment]
The failure of `quote-nested-6.scala` was unrelated to this PR. This broke on that main branch due to a conflict between to other PRs, see https://github.com/lampepfl/dotty/pull/17993.

**Review by nicolasstucki — COMMENTED** [review]
Otherwise LGTM

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 18]
```diff
@@ -11,6 +11,7 @@ import dotty.tools.dotc.core.Types.*
 import dotty.tools.dotc.core.StdNames.nme
 import dotty.tools.dotc.core.Symbols.*
 import dotty.tools.dotc.util.optional
+import dotty.tools.dotc.core.Definitions
```
[the remark this answers is not in the document]
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Removed.

File: compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala [hunk 19]
```diff
@@ -497,10 +535,14 @@ object QuoteMatcher {
...
-     *  @param args HOAS arguments (from the pattern)
+     *  @param argIds Identifiers of HOAS arguments (from the pattern)
+     *  @param argTypes Eta-expanded types of HOAS arguments (from the pattern)
      *  @param env Mapping between scrutinee and pattern variables
      */
-    case OpenTree(tree: Tree, patternTpe: Type, args: List[Tree], env: Env)
+    case OpenTree(tree: Tree, patternTpe: Type, argIds: List[Tree], argTypes: List[Type], env: Env)
+
+    /** The Definitions object */
+    def defn(using Context): Definitions = ctx.definitions
```
[the remark this answers is not in the document]
Comment (zeptometer) [reply compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala]: Thank you, I've followed your advice.

**Review by nicolasstucki — APPROVED** [review]
