### PR TITLE
fix #15222 recursively check for product ctor accessibility

### LINKED ISSUE #15222: sum mirror is available when mirror for child can't be summoned
The fix for https://github.com/lampepfl/dotty/pull/14986 does not consider when a sum type has a child for which the mirror can not be summoned.

## Compiler version

3.2.0-RC1-bin-20220517-e5abec0-NIGHTLY

First bad commit d6e17a23e65e8efa0dea608eb5dbfc490a977bd1 in #15008

## Minimized code

```Scala
import scala.deriving.Mirror

package lib {
  sealed trait Foo
  object Foo // Mirror.Of[Foo] cached in companion
  case class Bar private[lib] () extends Foo
  case object Bar // force mirror for Bar to be anonymous.
}

package app {
  val mFoo = summon[Mirror.SumOf[lib.Foo]]
  val mBar = summon[Mirror.ProductOf[lib.Bar]] // error
}
```

## Output

```scala
-- Error: test.scala:11:49 -------------------------------------------------------------
11 |  val mBar = summon[Mirror.ProductOf[lib.Bar]] // error
   |                                                 ^
   |No given instance of type deriving.Mirror.ProductOf[lib.Bar] was found for parameter x of method summon in object Predef. Failed to synthesize an instance of type deriving.Mirror.ProductOf[lib.Bar]: class Bar is not a generic product because the constructor of class Bar is innaccessible from the calling scope.
```

## Expectation

`summon[Mirror.SumOf[lib.Foo]]` should also fail because in the calling scope, the child of Foo, i.e. `Bar` can not have a mirror - this affects signatures of Foo, because object Foo should not cache the mirror.

### LINKED ISSUE #15234: product mirror for scala.Nil.type tries to access the constructor
Any Mirror for a value alias to a case object will crash when calling the `fromProduct` method, this is because it tries to access the constructor. (i.e. a singleton mirror is not synthesised, but instead a standard product mirror).

## Compiler version

3.0.0 - 3.1.2

## Minimized code

```Scala
import scala.deriving.Mirror

@main def Test =
  println(summon[Mirror.Of[Nil.type]].fromProduct(EmptyTuple))
```

## Output

```scala
Exception in thread "main" java.lang.IllegalAccessError: tried to access method scala.collection.immutable.Nil$.<init>()V from class App$package$$anon$1
	at App$package$$anon$1.fromProduct(App.scala:4)
	at App$package$$anon$1.fromProduct(App.scala:4)
	at App$package$.Test(App.scala:4)
	at Test.main(App.scala:3)
```

## Expectation

I expect to see `List()` printed

### PR DESCRIPTION
**Pull request by bishabosha**
mostly a refactoring, except now `whyNotGenericSum` will benefit by checking the constructor accessibility of child product types.

Removes the `declScope` parameter from `whyNotGenericSum` because it is not useful. In all cases it is populated by either the companion object of `self` when it is valid to use as the mirror, or it is the context owner when we should use an anonymous mirror. This is awkward because we end up calling `useCompanionAsSumMirror` twice in each recursive call.

Also fixes an inconsistency where `scala.Nil.type` would not get a singleton mirror, causing a runtime error (and extends it to aliases of singleton enum values)

fixes #15222
fixes #15234

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/SymUtils.scala [hunk 1]
```diff
@@ -145,39 +163,39 @@ object SymUtils:
     *     and also the location of the generated mirror.
     *   - all of its children are generic products, singletons, or generic sums themselves.
     */
-    def whyNotGenericSum(declScope: Symbol)(using Context): String =
+    def whyNotGenericSum(using Context): String =
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/SymUtils.scala:166]: I am not sure why `declScope` is no longer needed. I assume it's OK. But maybe add an explanation to he commit or PR?

**Review by odersky — APPROVED** [review]
Otherwise LGTM

File: compiler/src/dotty/tools/dotc/transform/SymUtils.scala (hunk 1 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:166]: added an explanation to the PR
