### PR TITLE
Set context when reporting summonInline errors

### LINKED ISSUE #13406: assertion failed: <notype> class dotty.tools.dotc.ast.Trees$TypeTree -1 in ReTyper
## Compiler version

3.0.2-RC2

## Minimized code

Reproducer: typelevel/kittens#376
The issue is in `ReducibleSuite`.

## Output (click arrow to expand)
<details>

```scala
[error] java.lang.AssertionError: assertion failed: <notype> class dotty.tools.dotc.ast.Trees$TypeTree -1
[error] 	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error] 	at dotty.tools.dotc.typer.ReTyper.assertTyped(ReTyper.scala:29)
[error] 	at dotty.tools.dotc.typer.ReTyper.promote(ReTyper.scala:33)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTypeTree(ReTyper.scala:69)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTypeTree(ReTyper.scala:68)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2716)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedType(Typer.scala:2943)
[error] 	at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:1421)
[error] 	at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1414)
[error] 	at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1421)
[error] 	at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1551)
[error] 	at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:755)
[error] 	at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:887)
[error] 	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:779)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
[error] 	at dotty.tools.dotc.typer.Namer$ClassCompleter.completeConstructor(Namer.scala:1238)
[error] 	at dotty.tools.dotc.typer.Namer$ClassCompleter.completeInCreationContext(Namer.scala:1354)
[error] 	at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:779)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
[error] 	at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:369)
[error] 	at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2635)
[error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2660)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2755)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2847)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1025)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1029)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2701)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedNew(Typer.scala:780)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2697)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Synthesizer.anonymousMirror(Synthesizer.scala:191)
[error] 	at dotty.tools.dotc.typer.Synthesizer.sumMirror(Synthesizer.scala:338)
[error] 	at dotty.tools.dotc.typer.Synthesizer.$init$$$anonfun$16$$anonfun$1$$anonfun$1$$anonfun$1(Synthesizer.scala:362)
[error] 	at dotty.tools.dotc.typer.Synthesizer.makeMirror(Synthesizer.scala:348)
[error] 	at dotty.tools.dotc.typer.Synthesizer.$init$$$anonfun$19$$anonfun$4(Synthesizer.scala:362)
[error] 	at dotty.tools.dotc.typer.Synthesizer.recur$1(Synthesizer.scala:399)
[error] 	at dotty.tools.dotc.typer.Synthesizer.tryAll(Synthesizer.scala:404)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:854)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Typer.implicitArgs$1(Typer.scala:3284)
[error] 	at dotty.tools.dotc.typer.Typer.addImplicitArgs$3(Typer.scala:3320)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$2(Typer.scala:3400)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3597)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3810)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3173)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3797)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1042)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1138)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.rank$1(Implicits.scala:1217)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1385)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1392)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1400)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1425)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:991)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits.ignoredInstanceNormalImport$1(Implicits.scala:882)
[error] 	at dotty.tools.dotc.typer.Implicits.$anonfun$1(Implicits.scala:896)
[error] 	at dotty.tools.dotc.typer.ImplicitSearchError.hiddenImplicitsAddendum(ErrorReporting.scala:419)
[error] 	at dotty.tools.dotc.typer.ImplicitSearchError.missingArgMsg(ErrorReporting.scala:267)
[error] 	at dotty.tools.dotc.typer.Implicits.missingArgMsg(Implicits.scala:897)
[error] 	at dotty.tools.dotc.typer.Implicits.missingArgMsg$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.missingArgMsg(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Inliner.searchImplicit$1(Inliner.scala:837)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:841)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedTypeApply(Inliner.scala:1549)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$5(ProtoTypes.scala:428)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:359)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:429)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:544)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:447)
[error] 	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:735)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:849)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1057)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:904)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$5$$anonfun$4(Applications.scala:983)
[error] 	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2949)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:994)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1032)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1535)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1031)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2701)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedTypeApply(Inliner.scala:1549)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$4(Typer.scala:3503)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3619)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3810)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3173)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3797)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1042)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1138)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.rank$1(Implicits.scala:1217)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1385)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1392)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1425)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:991)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:848)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Inliner.dotty$tools$dotc$typer$Inliner$reducer$$$_$searchImplicit$2(Inliner.scala:1280)
[error] 	at dotty.tools.dotc.typer.Inliner$reducer$.reducePattern$1(Inliner.scala:1358)
[error] 	at dotty.tools.dotc.typer.Inliner$reducer$.reduceCase$1(Inliner.scala:1439)
[error] 	at dotty.tools.dotc.typer.Inliner$reducer$.recur$2(Inliner.scala:1455)
[error] 	at dotty.tools.dotc.typer.Inliner$reducer$.reduceInlineMatch(Inliner.scala:1458)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatchFinish(Inliner.scala:1571)
[error] 	at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1468)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatch(Inliner.scala:1558)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2707)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$4(Typer.scala:3503)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3619)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3810)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3173)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3797)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1042)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1138)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.rank$1(Implicits.scala:1217)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1385)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1392)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1400)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1425)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:991)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:848)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Inliner.searchImplicit$1(Inliner.scala:834)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:841)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedTypeApply(Inliner.scala:1549)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$5(ProtoTypes.scala:428)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:359)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:429)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:544)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:447)
[error] 	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:735)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:849)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1057)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:904)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$5$$anonfun$4(Applications.scala:983)
[error] 	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2949)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:994)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1032)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1535)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2874)
[error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2897)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1025)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1029)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2701)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatchFinish(Inliner.scala:1593)
[error] 	at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1527)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatch(Inliner.scala:1558)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2707)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1542)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1031)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2701)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatchFinish(Inliner.scala:1593)
[error] 	at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1527)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatch(Inliner.scala:1558)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2707)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1542)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedTypeApply(Inliner.scala:1549)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$5(ProtoTypes.scala:428)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:359)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:429)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:544)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:447)
[error] 	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:735)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:849)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1057)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:904)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$5$$anonfun$4(Applications.scala:983)
[error] 	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2949)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:994)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1032)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1535)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatchFinish(Inliner.scala:1593)
[error] 	at dotty.tools.dotc.typer.Typer.typedMatch(Typer.scala:1527)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedMatch(Inliner.scala:1558)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2707)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1542)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1542)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$5(ProtoTypes.scala:428)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:359)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:429)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:544)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:447)
[error] 	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:735)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:849)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1057)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:904)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$5$$anonfun$4(Applications.scala:983)
[error] 	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2949)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:994)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1032)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1535)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$4(Typer.scala:3503)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3619)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3810)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3173)
[error] 	at dotty.tools.dotc.typer.Typer.readaptSimplified$1(Typer.scala:3174)
[error] 	at dotty.tools.dotc.typer.Typer.addImplicitArgs$3(Typer.scala:3391)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$2(Typer.scala:3400)
[error] 	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3597)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3810)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3173)
[error] 	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3797)
[error] 	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3162)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1042)
[error] 	at dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1138)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.rank$1(Implicits.scala:1217)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1385)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1392)
[error] 	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1425)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:991)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:848)
[error] 	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:774)
[error] 	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Inliner.searchImplicit$1(Inliner.scala:834)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:841)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedTypeApply(Inliner.scala:1549)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.$anonfun$5(ProtoTypes.scala:428)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.cacheTypedArg(ProtoTypes.scala:359)
[error] 	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:429)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:850)
[error] 	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:544)
[error] 	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:609)
[error] 	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:447)
[error] 	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:735)
[error] 	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:849)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1057)
[error] 	at dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:106)
[error] 	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:904)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$5$$anonfun$4(Applications.scala:983)
[error] 	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2949)
[error] 	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:994)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1032)
[error] 	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:317)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedApply(Inliner.scala:1535)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2693)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2941)
[error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1031)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2701)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:1618)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedTypeApply(Inliner.scala:1549)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2712)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:62)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2698)
[error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2756)
[error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:118)
[error] 	at dotty.tools.dotc.typer.Inliner$InlineTyper.typedUnadapted(Inliner.scala:1622)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2821)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2818)
[error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2825)
[error] 	at dotty.tools.dotc.typer.Inliner.inlined(Inliner.scala:1016)
[error] 	at dotty.tools.dotc.typer.Inliner$.inlineCall(Inliner.scala:153)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:86)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1490)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1490)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1386)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:93)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:82)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1490)
[error] 	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1490)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1386)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:35)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:41)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:41)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:54)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1463)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:80)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1474)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
[error] 	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1474)
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
[error] 	at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:94)
[error] 	at dotty.tools.dotc.transform.Inlining$$anon$2.transform(Inlining.scala:72)
[error] 	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
[error] 	at dotty.tools.dotc.transform.Inlining.run(Inlining.scala:44)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
[error] 	at dotty.tools.dotc.transform.Inlining.runOn(Inlining.scala:48)
[error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
[error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
[error] 	at dotty.tools.dotc.Run.compile(Run.scala:150)
[error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] 	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] 	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:457)
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:412)
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:399)
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2362)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2319)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2315)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
</details>

### PR DESCRIPTION
**Pull request by andrzejressel**
Set proper context when reporting summonInline errors - and puts everything in inContext block, so this won't happen in the future.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -852,7 +852,7 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
           val evidence = evTyper.inferImplicitArg(tpt.tpe, tpt.span)(using evCtx)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:852]: You could wrap the whole block using `inContext(evCtx) { ... }` to make sure we don't accidentally use the wrong context anywhere.

Comment (andrzejressel) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: Fixed

**Comment by andrzejressel** [comment]
I've signed CLA

**Comment by nicolasstucki** [comment]
fix #13406

**Review by nicolasstucki — COMMENTED** [review]
@andrzejressel you should squash and rebases the commits and include a short message explaining what the fix is doing.

Otherwise LGTM

**Comment by andrzejressel** [comment]
@nicolasstucki Fixed, should be fine now

**Review by nicolasstucki — APPROVED** [review]
