### PR TITLE
Fix #8838: load Java enum members lazily to avoid cycles

### LINKED ISSUE #8838: `String#split(Char)` extension method stopped working on JDK 14
it's fine on 8, 11, and 13

```
sbt:euler> show scalaVersion
[info] 0.24.0-RC1
sbt:euler> console

scala> System.getProperty("java.version")                                                               
val res0: String = 14.0.1

scala> "foo".split(' ')
1 |"foo".split(' ')
  |            ^^^
  |            Found:    (' ' : Char)
  |            Required: String
```

this can also be seen when Dotty tries to build itself on 14:

```
[error] -- [E007] Type Mismatch Error: /Users/tisue/dotty/doc-tool/src/dotty/tools/dottydoc/staticsite/DefaultParams.scala:72:38 
[error] 72 |  val path: Array[String] = url.split('/').drop(1)
[error]    |                                      ^^^
[error]    |                                      Found:    ('/' : Char)
[error]    |                                      Required: String
[error] one error found
```

the problem also exists in 0.23.0-RC1; I didn't try testing farther back than that

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #8838: load Java enum memers lazily to avoid cycles

It only happens in JDK 14.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -607,8 +603,13 @@ class SpaceEngine(implicit ctx: Context) extends SpaceLogic {
       case tp if tp.isRef(defn.UnitClass) =>
         Typ(ConstantType(Constant(())), true) :: Nil
       case tp if tp.classSymbol.isAllOf(JavaEnumTrait) =>
+        tp.classSymbol.linkedClass.info.decls.toList.map(_.ensureCompleted())
+        val children = tp.classSymbol.children
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:607]: Calls to `.children` could happen in other places, for example from tasty-reflect, can we move the use of `ensureCompleted` inside the definition of `children` itself?

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala [hunk 2]
```diff
@@ -59,10 +59,10 @@ object TypeTestsCasts {
...
     def replaceP(tp: Type)(implicit ctx: Context) = new TypeMap {
       def apply(tp: Type) = tp match {
-        case tref: TypeRef
-        if isPatternTypeSymbol(tref.typeSymbol) => WildcardType
-        case AnnotatedType(_, annot)
-        if annot.symbol == defn.UncheckedAnnot => WildcardType
+        case tref: TypeRef if tref.typeSymbol.isPatternBound =>
+          WildcardType(tref.underlying.bounds)
+        case AnnotatedType(_, annot) if annot.symbol == defn.UncheckedAnnot =>
+          WildcardType
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:65]: Unrelated changes?

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:607]: Also this can probably be done under an `if (tp.classSymbol.isJavaDefined)`

File: compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala:65]: Yes, it's some refactoring.

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:607]: oh, and you can do `decls.foreach` instead of `decls.toList.map`
