### PR TITLE
Fix cycle detection for type aliases with wildcard arguments

### LINKED ISSUE #15507: Cyclic reference in type is not detected
## Compiler version

3.2.0-RC1

## Minimized code

```scala
type _NestedSet2[_] = Set[_NestedSet2[?]]
```

## Output

Compiles, but reduces the right hand side to `Set[Any]`.

## Expectation

Definition should be rejected since it contains a cycle.

### PR DESCRIPTION
**Pull request by odersky**
#15507 escaped the cycle detector since when the right hand side was typechecked,
the type constructor _NestedSet2's type was `[X] <: Any` and the constructor was marked Provisional.
When faced with the application `NestedSet2[?]`, the type checker tried to reduce the application, since
abstract types like `NestedSet2` are not allowed to take wildcards (this would be equivalent in power to existential types, which are not supported in Scala 3). Reduction in a covariant context would give
`Any`, which means that the recursive constructor disappears. 

There was a bug in `safeDealias` that caused this behavior also for non-variant variables. This got fixed in the 2nd commit. 

Fixes #15507

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -2027,12 +2027,19 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+      if tycon == defn.andType || tycon == defn.orType then
         checkedArgs = checkedArgs.mapconserve(arg =>
           checkSimpleKinded(checkNoWildcard(arg)))
+      else if tycon.flagsUNSAFE.is(Provisional) then
+        // A type with Provisional flag is either an alias or abstract type.
+        // If it is an alias type, it would mean the type is cyclic
+        // If it is an abstract type, it would mean the type is an irreducible
+        // application of a higher-kinded type to a wildcard argument.
+        // Either way, the wildcard argument is illegal.
+        // The early test here is needed, so that we do not accidentally reduce
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2039]: Is the call to `checkNoWildcard` you're adding the early test?  Earlier than what?  I see `preCheckKinds` and the bounds checking in PostTyper, but I can't tell where the accidental reduction can happen.

(Also, there's a typo "roght" if you're pushing another commit.)

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:2039]: Yes, `checkNoWildcard`.

**Comment by odersky** [comment]
How I fixed it:

This one was puzzling. I tried to instrument the checkNonCyclic function to see what went wrong. I did that for the original definition
```scala
type _NestedSet1[X] = Set[_NestedSet1[?]]
```
which did not produce an error and the variant
```scala
type _NestedSet1[X] = Set[_NestedSet1[Int]]
```
which did produce an error. But at first I could not spot anything, mostly because I had to print the types in toString form since showing them with the `i` interpolator produced cycles.

It was when I did a diff between the instrumentations of the two definitions that I saw that `NestedSet1` had completely disappeared from the computed right hand side of the type. Instead the RHS was computed as `Set[Any]`. 

That caused the investigation to switch to Namer where the RHS was computed. Here, to be able to bootstrap we first assume a type `[X] >: Nothing <: Any` for `NestedSet1` and mark the symbol as `Provisional`. This is arguably very dirty, but looked like the only practicable way to deal with recursive definitions like this. Then when we computed the RHS we had a `NestedSet1 <: ([X] => Nothing .. Any)` for the constructor and the TypeBounds `Nothing .. Any` for the argument. This is an illegal application since it would be equivalent to an existential type `\exists X.NestedSet1[X]` and Scala 3 does not have existential types. The typer will try in TypeApplications to reduce such existential types away and report an error in PostTyper if that does not work. In this case the reduction did succeed, we end up with just `Nothing..Any`. 

Aside: In fact because of another problem the reduction did not give the TypeBounds type `Nothing..Any` but just the upper bound. That was fixed in `[030e867](https://github.com/lampepfl/dotty/pull/15508/commits/030e867fae1b67469d5c5ba5bdd77c97f4a30ffb)`. 

In either case the whole type was now just `Set[Any]`, or after the fix `Set[? >: Nothing <: Any]`. `NestedSet1` has completely disappeared so no cycle was detected.

The fix was then comparatively simple. If we have a provisional type constructor, we do not allow wildcard arguments. Either the constructor will become an alias type, then it's a cyclic reference error, or it will become an abstract type, then it's an irreducible application to wildcard arguments. In either case it's wrong.
