### PR TITLE
Fix #7650: Drop stale toplevel definitions

### LINKED ISSUE #7650: Toplevel definitions in forgotten class files break compilation
Toplevel definitions have the downside that they can accumulate on the output path and influence subsequent compilations in unexpected ways. Here's an example:

First, compile file `A.scala`
```
@main def Test() = println("test")
```
Next, compile file `B.scala`
```
object Test
```
If the output directory is on the class path, this gives an error indicating that `Test` needs to be applied to `()`. What happens is that the compiler will load and merge the denotations of `Test` in both `A.scala` and `B.scala` and then will get confused since it thinks `Test` is a method. 

The problem is more general: Whenever there are several files with toplevel definitions, these definitions go into separate wrapper objects that are named after their file names. This means that compiling one file with toplevel definitions does not invalidate the definitions in another file. This is normally intended, but it does mean that "junk" in long forgotten class files can come back in unexpected ways. For instance, if one has first toplevel definitions in a file A.scala, and then renames the file to B.scala, possibly with with some changes, the definitions of `A` and `B` will compete as overloaded variants with each other, as long as A$package.class is on the classpath.

The normal way to mitigate the problem is to clean compile whenever a file containing toplevel definitions is renamed. But there's one situation where this is impractical: Toplevel definitions in the empty package. These are created by most simple tests, all the time. It is impractical to require a clean compile before compiling an additional test.

I believe it's better to hide toplevel definitions in the empty package from being visible in other compilation units, unless both units are compiled together. Otherwise we are simply too vulnerable of getting junk in the system that can cause mysterious compilation errors. 

Another, more complicated fix would be to drop shadowed toplevel definitions looking at file creation dates. That is, if we have two toplevel definitions of method `foo` with matching signatures in two different wrappers, go back to the wrapper's associated files and get the file creation date of each. Only keep the method in the newer file. This protects against conflicting versions of `foo`, but not against overloading. We'd still have the problem if we have toplevel definitions like this:
```scala
def foo(x: Long): Unit = ...
val bar = foo(1)
``` 
and then compile them with a junk class file that contains a definition of `foo` over `Int`. One could make the filtering even more aggressive by dropping all same-named methods independent of their signatures, but that would mean that we cannot define overloaded variants of existing methods
in new toplevel definitions anymore. So, no easy solution in sight...

### PR DESCRIPTION
**Pull request by odersky**
If there are several toplevel definitions of the same name in different wrapper objects, drop all but the definition that was compiled last. This mimics the behavior for classes and objects. 

As a consequence, it becomes impossible to have overloaded toplevel definitions in different files, as the alternatives in the last-compiled file always replace the alternatives compiled earlier.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -2122,19 +2122,34 @@ object SymDenotations {
         case pcls :: pobjs1 =>
           if (pcls.isCompleting) recur(pobjs1, acc)
           else {
-            // A package object inherits members from `Any` and `Object` which
-            // should not be accessible from the package prefix.
             val pmembers = pcls.computeNPMembersNamed(name).filterWithPredicate { d =>
+              // Drop members of `Any` and `Object`, as well as top-level definitions
+              // in the empty package that are not defined in the current run.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: I don't think the code below is related to dropping definitions in the empty package ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Oops, that was left from the previous abandoned PR.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 2]
```diff
@@ -2122,8 +2122,6 @@ object SymDenotations {
         case pcls :: pobjs1 =>
           if (pcls.isCompleting) recur(pobjs1, acc)
           else {
-            // A package object inherits members from `Any` and `Object` which
-            // should not be accessible from the package prefix.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: The original comment here seems useful to me and could be restored.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 3]
```diff
@@ -2132,9 +2130,24 @@ object SymDenotations {
...
+      def dropStale(d: DenotUnion): PreDenotation =
+        val compiledNow = d.filterWithPredicate(d =>
+          d.symbol.isDefinedInCurrentRun || d.symbol.associatedFile == null
+            // if a symbol does not have an associated file, assume it is defined
+            // in the current run anyway. This typically happens for pickling and
+            // from-tasty tests that generate a fresh symbol and then re-use it in the next run.
+          )
+        if compiledNow.exists then compiledNow
+        else
+          val youngest = d.aggregate(_.symbol.associatedFile.lastModified, _ max _)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: I'm strongly against any kind of merging logic that takes file modification date into account: there's many situations where this would go wrong, and it adds a new source of non-determinism to compilation. Instead, we can emit an error if overloaded definitions come from multiple files.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: That alone won't help. You still need the modification dates to get rid of junk in old classfiles. Otherwise any conflict would be an error which would be super annoying since often people do not even know how to clean out the output directory! So they are stuck with an error they can't fix.

File: docs/docs/reference/dropped-features/package-objects.md [hunk 4]
```diff
@@ -42,3 +42,6 @@ in a source file `src.scala`, it could be invoked from the command line using a
 "program name" is mangled it is recommended to always put `main` methods in explicitly named objects.
 
 **Note 3:** The notion of `private` is independent of whether a definition is wrapped or not. A `private` toplevel definition is always visible from everywhere in the enclosing package.
+
+**Note 4:** If several wrapper objects contain toplevel definitions with the same name,
```
Comment (anatoliykmetyuk) [inline docs/docs/reference/dropped-features/package-objects.md]: It looks like this is true only for separate compilation. If you have several files, each with an overloaded version of a method, and compile them in one run, the overload will work. If you compile them separately, only the last compiled method will be visible.

**Comment by odersky** [comment]
@smarter Everything we discussed is now implemented. You get warnings if competing toplevel definitions come from different directories. I was not able to do a test for this (won't have the time to do it). If we feel a test is needed, let's open an issue.
