### PR TITLE
Clarify ambiguous reference error message

### LINKED ISSUE #12682: Ambiguous reference error message does not know about rule change in #8622
```scala
object C {
  def m(x: Int) = 1
  object T extends K {
    val x = m(1)
  }
}
class K {
  def m(i: Int) = 2
}
```

gives

```
-- [E049] Reference Error: Test.scala:4:12 -------------------------------------
4 |    val x = m(1)
  |            ^
  |            Reference to m is ambiguous,
  |            it is both defined in object C
  |            and inherited subsequently in object T

Explanation
===========
The compiler can't decide which of the possible choices you
are referencing with m: A definition of lower precedence
in an inner scope, or a definition with higher precedence in
an outer scope.
Note:
 - Definitions in an enclosing scope take precedence over inherited definitions
 - Definitions take precedence over imports
 - Named imports take precedence over wildcard imports
 - You may replace a name when imported using
   import scala.{ m => mTick }
```

The `-explain` message even says "Definitions in an enclosing scope take precedence over inherited definitions".

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes #12682

Name binding is tricky because of the intersection of binding precedence and scope.

I think this states the matter most succinctly: Lower precedence cannot shadow higher.

Also modernized the syntax.

It's arguably weird for the compiler to refer to itself in the third person:

> The compiler can't decide which of the possible choices you are referencing

Less nerdy and more former schoolmarm:

> to which of the possible choices you could possibly be referring

### CODE REVIEW

**Comment by som-snytt** [comment]
@dwijnand please review? Surprisingly difficult rebase over refactor of messages.scala, so if it is not accepted, I will drop it.

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 1]
```diff
@@ -1328,21 +1328,29 @@ class AmbiguousReference(name: Name, newPrec: BindingPrec, prevPrec: BindingPrec
...
+        |in an inner scope cannot shadow a binding with higher precedence in
+        |an outer scope.""".stripMargin
+
+    i"""|The identifier $name is ambiguous because $precedent
+        |
+        |The precedence of the different kinds of bindings, from highest to lowest, is:
+        | - Definitions in an enclosing scope
+        | - Inherited definitions and top-level definitions in packages
+        | - Names introduced by imports
         | - Named imports take precedence over wildcard imports
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:1349]: Should we change this?

```suggestion
        | - Names introduced by named imports
        | - Names introduced by wildcard imports
```

**Review by dwijnand — APPROVED** [review]
LGTM, sorry you waited this long... :(

I have a question, but I don't mind merging this without that change.

File: compiler/src/dotty/tools/dotc/reporting/messages.scala (hunk 1 above)
Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/reporting/messages.scala]: Yes. I was trying to strike a balance of informality.

**Comment by som-snytt** [comment]
Added a commit which finds words for `Names introduced by import of a specific name`. (Where "specific" means "specified".)

"Named import" is too brief to ring with clarity.

There must be a grammatical term for "by import" (similar to "call by name"), as opposed to "by imports" or "by importing".

The follow-up also restores the previous words in the note: the rule of thumb that defs are preferred to imports, and the special mention of the "new" rule, with a clause explaining when it is relevant:
```
+        | - Definitions in an enclosing scope take precedence over inherited definitions,
+        |   which can result in ambiguities in nested classes.
```

Thanks, Dale, for the nudge. No one will say, We didn't adopt Scala 3 because of that stupid message, but I must believe that a collective, cumulative effort must make a difference, not only in aggregate but in the life of some Scala learner yet unborn.

**Comment by SethTisue** [comment]
>  I must believe that a collective, cumulative effort must make a difference, not only in aggregate but in the life of some Scala learner yet unborn.

✊
