### PR TITLE
Fix #5954: Do not check prefix for non locally defined types

### LINKED ISSUE #5954: Incorrect phase consistency check related to inner classes
The following code used to type check, but does not compile after #5763.

```Scala
abstract class MatcherFactory1 {
  class AndNotWord
}

object MatcherFactory1 {
  import scala.quoted._
  import scala.tasty._

  def impl(self: Expr[MatcherFactory1#AndNotWord])(implicit refl: Reflection) =
    '{ ~self }

  def impl2(a: MatcherFactory1)(self: Expr[a.AndNotWord])(implicit refl: Reflection) =
    '{ ~self }
}
```

Error message:

```
-- Error: examples/MatcherFactory1.scala:10:7 ----------------------------------
10 |    '{ ~self }
   |       ^^^^^
   |       access to MatcherFactory1.this from wrong staging level:
   |        - the definition is at level 0,
   |        - but the access is at level 1.
-- Error: examples/MatcherFactory1.scala:13:7 ----------------------------------
13 |    '{ ~self }
   |       ^^^^^
   |       access to MatcherFactory1.this from wrong staging level:
   |        - the definition is at level 0,
   |        - but the access is at level 1.
two errors found
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: tests/neg/i5954.scala [hunk 1]
```diff
@@ -0,0 +1,10 @@
+abstract class MatcherFactory1 {
+  class AndNotWord
+}
+
+object MatcherFactory1 {
+  import scala.quoted._
+
+  def impl2(a: MatcherFactory1)(self: Expr[a.AndNotWord]) =
+  '{ ~self } // error: access to value a from wrong staging level
+}
```
Comment (liufengyun) [inline tests/neg/i5954.scala]: I'm wondering how we can use `a` properly in such context? We need to have some principles to deal with terms in types.

Comment (nicolasstucki) [reply tests/neg/i5954.scala]: Maybe we could encode with something like

```scala
def impl2[T: Type](a: MatcherFactory1)(self: Expr[T])(implicit ev: T =:= a.AndNotWord) = ...
```
