### PR TITLE
fix(#19377): show inherited abstract members in dedicated section

### LINKED ISSUE #19377: Scaladoc doesn't show Builder#addOne as abstract
## Compiler version

Latest api

## Minimized code

image

image

## Expectation

image

I hate to rag on thankless scaladoc, but this strikes me as the low bar of usability. "What do I need to implement?"

Obviously, at the moment I am coding a quick test in vi with no autocomplete, so sue me.

### PR DESCRIPTION
**Pull request by i10416**
close #19377 

Before this commit, inherited abstract members are displayed in "Inherited members" section, which made it a bit difficult for developers to figure out which method to be implemented.

I think there are two solution for the issue.

1. display `abstract` modifier for methods in inherited section
2. add a new dedicated section for inherited abstract members

I choose the 2nd solution because

- it is easier for developers to find methods to be implemented in a dedicated section rather than to look up abstract ones from all the inherited members
- it requires smaller modification to scaladoc codebase

image

### CODE REVIEW

File: scaladoc/src/dotty/tools/scaladoc/renderers/MemberRenderer.scala [hunk 1]
```diff
@@ -323,6 +323,7 @@ class MemberRenderer(signatureRenderer: SignatureRenderer)(using DocContext) ext
       val (allInherited, allDefined) = nonExperimental.partition(isInherited)
       val (depDefined, defined) = allDefined.partition(isDeprecated)
       val (depInherited, inherited) = allInherited.partition(isDeprecated)
+      val (abstractInherited, concreteInherited) = inherited.partition(isAbstract)
```
Comment (i10416) [inline scaladoc/src/dotty/tools/scaladoc/renderers/MemberRenderer.scala:326]: Note:
If we just put inherited abstract members into  "Abstract members" section, it loses the information that these methods are originated from inheritance.

**Review by Florian3k — APPROVED** [review]
