### PR TITLE
Fix #5809: Run the community-build on every PR

### LINKED ISSUE #5809: Run community build on every PR
The way we currently use the community build is quite inefficient because of the asynchronous reporting of errors. The build has now been broken for more than a month, and is now broken from (at last) 4 different PRs.

I would like to propose an alternative approach to make things more efficient: compile the community build on every PR as part of the CI.

I think the best way to do that would be to merge `dotty-staging/sourcecode` with `lampepfl/dotty`, that is:

- Add all the `dotty-staging/community-project-X` as submodules to the dotty repo. We already do that for the collection strawman, also for testing purposes.

- Create a sbt task in dotty's build to compile the community build with the current compiler. It will take about 10 minutes to run can be parallelized with everything else on the CI.

Is anyone opposed to this?

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
This PR is meant to replace the infrastructure previously setup in https://github.com/lampepfl/dotty-community-build. A new sbt project, community-build, is added to dotty's Build.scala and contains all the integration tests for the community build.

In case of failure the tests will output instructions on how to reproduce the error without JUnit. Hopefully these instructions are sufficient to have everyone fix regressions as they are introduced, or as a very last resort, update the code for the community build.

This should be the main improvement over the previous approach, where the community build maintenance was centralized (Allan did all the work) and asynchronous (it's now broken for more than a month...).

Another improvement is that a published local version of the sbt plugin is used when running the integration test, so breakage to sbt-dotty should be cough earlier than before.

Before merging, we should probably generate a new docker image for the CI where we cache all dependencies of the community projects.

### CODE REVIEW

**Comment by allanrenucci** [comment]
What about we add `.travis.yml` file to the repo to run the community build on travis so that we keep the runtime of normal tests low and we let travis take care of caching the community build dependencies?

File: .gitmodules [hunk 1]
```diff
@@ -6,7 +6,45 @@
...
+[submodule "community-build/community-projects/scalatest"]
+	path = community-build/community-projects/scalatest
+	url = https://github.com/dotty-staging/scalatest
+[submodule "community-build/community-projects/scopt"]
+	path = community-build/community-projects/scopt
+	url = https://github.com/dotty-staging/scopt
+[submodule "community-build/community-projects/squants"]
+	path = community-build/community-projects/squants
+	url = https://github.com/dotty-staging/squants
+[submodule "community-build/community-projects/collection-strawman"]
```
Comment (smarter) [inline .gitmodules]: I would either copy-paste the sources of the strawman in our test folder or get rid of it entirely, there's no point in keeping it in a submodule since it's a frozen project that won't evolve anymore.

File: project/Build.scala [hunk 2]
```diff
@@ -1017,6 +1016,30 @@ object Build {
       }.dependsOn(compile in Compile).evaluated
     )
 
+  lazy val `prepare-community-build` = taskKey[Unit]("Publish local the compiler and the sbt plugin. Also store the versions of the published local artefacts in two files, community-build/{dotty-bootstrapped.version,sbt-dotty.sbt}.")
```
Comment (smarter) [inline project/Build.scala]: call the key prepareCommunityBuild since camel-case is the convention for sbt keys (also no need for keys to be lazy vals).

File: project/Build.scala [hunk 3]
```diff
@@ -1017,6 +1016,30 @@ object Build {
...
+        (publishLocal in `dotty-bootstrapped`).value
+        (publishLocal in `sbt-dotty`).value
+        val pluginText = s"""addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "$sbtDottyVersion")"""
+        IO.write(baseDirectory.value / "sbt-dotty.sbt", pluginText)
+        IO.write(baseDirectory.value / "dotty-bootstrapped.version", dottyVersion)
+      },
+      (Test / testOnly) := ((Test / testOnly) dependsOn `prepare-community-build`).evaluated,
+      (Test / test    ) := ((Test / test    ) dependsOn `prepare-community-build`).value,
+      libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % Test,
+      testOptions in Test += Tests.Argument(TestFrameworks.JUnit, "-a", "-v")
```
Comment (smarter) [inline project/Build.scala]: You should use `.settings(commonSettings)` to avoid repeating junit settings, etc.

**Comment by allanrenucci** [comment]
Why does this rely on git submodules? The community build did not.

Adding this many submodules seems like a bad idea. They are a pain to work with and will make cloning the repo super slow...

**Comment by OlivierBlanvillain** [comment]
@allanrenucci because we don't want to break the community build. Pointing to branches makes it very fragile, commit are more stable. It will also let us *document* potential changes required to community build, rather than having stuff happening silently over +10 repos.

> Adding this many submodules seems like a bad idea. They are a pain to work with and will make cloning the repo super slow...

A follow up PR will remove the backend and scala2-lib submodules, which means we will get ride of the submodule requirement for using and testing dotty, and will only need submodules for the community build. In particular we can update drone and the docs to remove the `--recursive`.

**Comment by OlivierBlanvillain** [comment]
@smarter I didn't notice that pdbp upstream uses the sbt-dotty plugin. I think in every other project the plugin was added to make it compile with dotty, so removing the plugin makes the build closer to it's upstream state. If you think it's worth the time I can do another pass to try minimizing the diff of every build...

**Comment by allanrenucci** [comment]
> because we don't want to break the community build. Pointing to branches makes it very fragile, commits are more stable

When I was maintaining the community, I thought it was rather convenient. I would rebase the forks every now and then without needing to update the submodules. The community build never broke because a branch changed. We own the forks, we control branch changes. The forks also have their own CI, so as long as you PR changes to them, there is no reason it will break the community build.

If you think depending on a specific commit is desirable then I would add a new setting to the tests. E.g.
```scala
@Test def scalap = test(
  project = "scalap",
  command = "scalap/compile",
  commit = "ff707"
)
// We now run something like `git reset --hard <commit>`
```
Relying on submodule also makes it harder to add a new project to the community. It wouldn't help if we want external contribution to grow the community build.

**Comment by OlivierBlanvillain** [comment]
Yes the setup was acceptable when its a single person maintaining it and it was not run on every PR, but now I really don't want to have PRs on Dotty being blocked because somebody fucked up something in the community build. Also I really dislike that we do random stuff [like this](https://github.com/dotty-staging/scalatest/pull/8/files) without anyway to relate them to changes in Dotty. Submodules solve both problems.

> If you think depending on a specific commit is desirable then I would add a new setting to the tests. 

You are suggesting to have a file with a list of commit per project, this is exactly what submodules are!

> Relying on submodule also makes it harder to add a new project to the community. It wouldn't help if we want external contribution to grow the community build.

It's literally "git submodule add <url>" + one entry in CommunityBuildTests.scala...

**Comment by OlivierBlanvillain** [comment]
I'm not very happy with Travis, running time are very unpredictable. For instance, doing `dotty-compiler-bootstrapped/publish-local` alone (which is a prerequisite for testing projects in the community build) can take from ~9 min to ~16.5 min (these are the extremums among the few runs in this PR). I think I'm going to revert back to the original idea of doing it all in drone, with the downside of having to manually update the cache in the docker image...

**Comment by OlivierBlanvillain** [comment]
With the cache setup sequentially running the entire full community build seams to be faster than test_bootstrapped, so I think it's better to stick with drone for now. @smarter Do you want to have a second look?

File: .drone.yml [hunk 4]
```diff
@@ -23,33 +23,41 @@ pipeline:
...
     when:
       # sbt scripted tests are slow and only run on nightly or deployment
       event: [ tag, deployment ]
 
+  test_community_build:
+    group: test
+    image: lampepfl/dotty:2019-02-06
+    commands:
+      - cp -R . /tmp/4/ && cd /tmp/4/
+      - export PATH=$PATH:/tmp/4/project/scripts/
```
Comment (smarter) [inline .drone.yml]: You probably want the scripts at the beginning of the PATH.

File: community-build/test/scala/dotty/communitybuild/CommunityBuildTest.scala [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+    // Workarounds for https://github.com/sbt/sbt/issues/4395
+    new File(sys.props("user.home") + "/.sbt/1.0/plugins").mkdirs()
+    val pluginFilePath = communitybuildDir.resolve("sbt-dotty.sbt").toAbsolutePath().toString()
+
+    // Run the sbt command with the compiler version and sbt plugin set in the build
+    val arguments = Seq(
+      "-sbt-version", "1.2.7",
+      s"--addPluginSbtFile=$pluginFilePath",
+      "clean",
+      s"++$compilerVersion!",
```
Comment (smarter) [inline community-build/test/scala/dotty/communitybuild/CommunityBuildTest.scala]: Did you see this suggestion: https://github.com/dotty-staging/pdbp/commit/604c06c50358348d6d2c7daa0aaac0045f43b2f9#r32185635 ?
