### PR TITLE
Fix #6253: Handle repeated args in quoted patterns 

### LINKED ISSUE #6253: Quoted pattern with `: _*` crashes while typing
```scala
import scala.quoted._
import scala.tasty.Reflection
object Macros {
  def impl(self: Expr[StringContext]) given Reflection: Expr[String] = self match {
    case '{ StringContext() } => '{""}
    case '{ StringContext($part1) } => part1
    case '{ StringContext($part1, $part2) } => '{ $part1 + $part2 }
    case '{ StringContext($parts: _*) } => '{ $parts.mkString }
  }
}
```
Crashes with

```
java.lang.Error: internal error: type of quoted pattern selector ? is not fully defined, pos = [344..350] while compiling tests/run-with-compiler/quote-matcher-string-interpolator/quoted_1.scala
Exception in thread "main" java.lang.Error: internal error: type of quoted pattern selector ? is not fully defined, pos = [344..350]
	at dotty.tools.dotc.typer.Inferencing$.fullyDefinedType(Inferencing.scala:43)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedSplice$1(Typer.scala:1990)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.typedSplice(Typer.scala:1982)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2111)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2125)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:2159)
	at dotty.tools.dotc.reporting.TraceSyntax.apply(trace.scala:56)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2152)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2171)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2247)
	at dotty.tools.dotc.typer.Typer.typedWildcardStarArgExpr$1(Typer.scala:583)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedTyped$3(Typer.scala:597)
	at dotty.tools.dotc.typer.Typer.cases$1(Typer.scala:566)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedTyped$1(Typer.scala:595)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.typedTyped(Typer.scala:552)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2075)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2125)
	...
```

Note that in this particular case the type of `parts` should be `Expr[Seq[String]]`

### PR DESCRIPTION
**Pull request by nicolasstucki**
* Handle repeated args in quoted patterns in Typer
* Handle repeated args in quoted patterns in Matcher
* Add Repeated extractor to get `Seq[Expr[T]]` from an `Expr[Seq[T]]`

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Blocked by #6253

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1960,12 +1963,15 @@ class Typer extends Namer
...
+        case Typed(Splice(pat), tpt) if !tpt.tpe.derivesFrom(defn.RepeatedParamClass) =>
           val exprTpt = AppliedTypeTree(TypeTree(defn.QuotedExprType), tpt :: Nil)
           transform(Splice(Typed(pat, exprTpt)))
         case Splice(pat) =>
           try patternHole(tree)
-          finally patBuf += pat
+          finally {
+            val pat1 = pat.subst(defn.RepeatedParamClass :: Nil, defn.SeqClass :: Nil)
+            patBuf += pat1
+          }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: The change here and above looks dubious to me. @odersky could you have a look?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I am not sure a global substitution is the right thing here. I fear it would also affect nested varargs methods that would then become Seq methods. I'd do instead:
```scala
val patType = pat.tpe.widen
val patType1 = patType.underlyingIfRepeated(isJava = false)
val pat1 = if (patType eq patType1) pat else pat.withType(patType1)
```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I use this code now and also updated another place that had the `subst` to use `underlyingIfRepeated`.

**Comment by liufengyun** [comment]
I reverted the changes in Typer, and the tests in this PR pass:

```
--- a/compiler/src/dotty/tools/dotc/typer/Typer.scala
+++ b/compiler/src/dotty/tools/dotc/typer/Typer.scala
@@ -581,7 +581,7 @@ class Typer extends Namer
     if (untpd.isWildcardStarArg(tree)) {
       def typedWildcardStarArgExpr = {
         val ptArg =
-          if (ctx.mode.is(Mode.QuotedPattern)) pt.underlyingIfRepeated(isJava = false)
+          if (ctx.mode.is(Mode.QuotedPattern)) pt
           else WildcardType
         val tpdExpr = typedExpr(tree.expr, ptArg)
         tpdExpr.tpe.widenDealias match {
@@ -1963,17 +1963,12 @@ class Typer extends Namer
     object splitter extends tpd.TreeMap {
       val patBuf = new mutable.ListBuffer[Tree]
       override def transform(tree: Tree)(implicit ctx: Context) = tree match {
-        case Typed(Splice(pat), tpt) if !tpt.tpe.derivesFrom(defn.RepeatedParamClass) =>
+        case Typed(Splice(pat), tpt) =>
           val exprTpt = AppliedTypeTree(TypeTree(defn.QuotedExprType), tpt :: Nil)
           transform(Splice(Typed(pat, exprTpt)))
         case Splice(pat) =>
           try patternHole(tree)
-          finally {
-            val patType = pat.tpe.widen
-            val patType1 = patType.underlyingIfRepeated(isJava = false)
-            val pat1 = if (patType eq patType1) pat else pat.withType(patType1)
-            patBuf += pat1
-          }
+          finally patBuf += pat
         case _ =>
           super.transform(tree)
       }
```

I still fail to understand the rational to go to an underlying type. Could you please elaborate @nicolasstucki ?

**Comment by nicolasstucki** [comment]
We want to avoid having expressions of type `T*` as we could not write `val a: T* = ???`. Instead we use `val a: Seq[T] = ???`.
