### PR TITLE
Fix #1857: Allow lower bounds to influence implicit search

### LINKED ISSUE #1857: implicit summon fails in dotty, works in 2.*
The code below compiles and runs under 2.11.8 and 2.12.1, but fails under dotty with:

```
[info] Compiling 1 Scala source to /home/nmrp3/devel/turingatemyhamster/commandeer/target/scala-2.11/classes...
/home/nmrp3/devel/turingatemyhamster/commandeer/src/main/scala/commandeer/RunMe.scala:32: error: no implicit argument of type DSL found for parameter dsl of method apply in object CommandeerDSL
    val kevin = CommandeerDSL(null.asInstanceOf[Foo])
                                                     ^
/home/nmrp3/devel/turingatemyhamster/commandeer/src/main/scala/commandeer/RunMe.scala:34: error: value Bar is not a member of Nothing(kevin)
    val bar = kevin.Bar("bob", 3)
                    ^
two errors found
[error] (compile:compileIncremental) Compilation failed
```

I'm attempting to summon an implicit instance of a trait, but getting back type information specific to the instance that I've summoned, beyond that in the trait that I summoned it through. There may be a better way to do this with dotty, but I don't know it.

```scala
package commandeer


trait CommandeerDSL[Host] {
  trait Operation[T]
  type Op[T] <: Operation[T]
}

object CommandeerDSL {
  def apply[Host, DSL <: CommandeerDSL[Host]](host: Host)(implicit dsl: DSL): DSL = dsl
}
 
trait Foo {
  def bar(a: String, b: Int): Double
}
 
object Foo {
  implicit val fooDSL: FooDSL = new FooDSL {}
}
 
trait FooDSL extends CommandeerDSL[Foo] {
  sealed trait FooOperation[T] extends Operation[T]
  type Op[T] = FooOperation[T]

  case class Bar(a: String, b: Int) extends FooOperation[Double]
}
 
object RunMe {
  def main(args: Array[String]): Unit = {
    println("Hi Mum")

    val kevin = CommandeerDSL(null.asInstanceOf[Foo])
    println(s"Found DSL for Foo: $kevin")
    val bar = kevin.Bar("bob", 3)
    println(s"Made a bar: $bar")
  }
}
```

### PR DESCRIPTION
**Pull request by odersky**
The previous implementation claimed to conform to the spec:

      We exclude lower bounds to conform to SLS 7.2:
      "The parts of a type T are: [...] if T is an abstract type, the parts of its upper bound"

But in fact we do not need to exclude lower bounds from `namedPartsWith` to do that -
TypeRefs are already lifted to classes, which implements SLS 7.2. Including lower bounds
does affect wildcard types (i1857.scala) and wildcard parameters in implicits (implicit-lower-bound.scala), but the spec does not exclude either of these.

### CODE REVIEW

**Comment by odersky** [comment]
Test optimized hung. It's doing that a lot now. Can we find out the root cause of this?

File: tests/pos/implicit-lower-bound.scala [hunk 1]
```diff
@@ -9,6 +9,6 @@ class Test {
   def get1(implicit lf: List[_ <: Bar]) = {}
   def get2(implicit lf: List[_ >: Bar]) = {}
 
-  get1 // works
-  get2 // error
+  get1
+  get2
```
Comment (smarter) [inline tests/pos/implicit-lower-bound.scala]: I'll note that this line doesn't compile with scalac, so scalac interpretation of SLS 7.2 seems to match what I had in mind.
