### PR TITLE
Fix #2570: Part 3 - The great () insert

### LINKED ISSUE #2570: Scala Wart: Weak eta-expansion
Opening this issue, as suggested by Martin, to provide a place to discuss the individual warts brought up in the blog post [Warts of the Scala Programming Language](http://www.lihaoyi.com/post/WartsoftheScalaProgrammingLanguage.html) and the possibility of mitigating/fixing them in Dotty (and perhaps later in Scala 2.x). These are based on Scala 2.x behavior, which I understand Dotty follows closely, apologies in advance if it has already been fixed

--------------------------------------------------------------------------------

Scala maintains a distinction between "functions" and "methods": in general,
methods are things you call on an object, whereas functions are objects 
themselves. However, since they're so similar ("things you can call"), it gives 
you a way to easily wrap a method in a function object called "eta expansion"

```scala
@ def repeat(s: String, i: Int) = s * i
defined function repeat

@ repeat("hello", 2)
res89: String = "hellohello"

@ val func = repeat _
func: (String, Int) => String = $sess.cmd90$$$Lambda$2796/1082786554@2a3983b9

@ func("hello", 3)
res91: String = "hellohellohello"
```

Above, we use the underscore `_` to assign `repeat _` to a value `func`, which 
is then a function object we can call. This can happen automatically, without the
`_`, based on the "expected type" of the place the method is being used. For 
example, if we expect `func` to be a `(String, Int) => String`, we can assign
`repeat` to it without the `_`:

```scala
@ val func: (String, Int) => String = repeat
func: (String, Int) => String = $sess.cmd92$$$Lambda$2803/669946146@46226d53

@ func("hello", 3)
res92: String = "hellohellohello"
```

Or by stubbing out the arguments with `_` individually:

```scala
@ val func = repeat(_, _)
func: (String, Int) => String = $sess.cmd98$$$Lambda$2832/1025548997@358b1f86
```

This works, but has a bunch of annoying limitations. Firstly, even though you 
can fully convert the method `repeat` into a `(String, Int) => String` value 
using `_`, you cannot *partially* convert it:

```scala
@ val func = repeat("hello", _)
cmd4.sc:1: missing parameter type for expanded function 
((x$1: <error>) => repeat("hello", x$1))
val func = repeat("hello", _)
                           ^
Compilation Failed
```

*Unless* you know the the "expected type" of `func`, in which case you *can*
partially convert it:

```scala
@ val func: Int => String = repeat("hello", _)
func: Int => String = $sess.cmd93$$$Lambda$2808/1138545802@2c229ed2
```

Or you provide the type to the partially-applied-function-argument `_` manually:
```scala

@ repeat("hello", _: Int)
res4: Int => String = $sess.cmd4$$$Lambda$1988/1407003104@5eadc347
```

This is a bit strange to me. If I can easily convert the entire `repeat` method
into a function without specifying any types, why can I not convert it into a 
function if I already know one of the arguments? After all, I have provided
strictly *more* information in the `repeat("hello", _)` case than I have in the
`repeat(_, _)` case, and yet somehow type inference got worse! 

Furthermore, there's a more fundamental issue: if I know that `repeat` is a 
method that takes two arguments, why can't I just do this?

```scala
@ val func = repeat
cmd99.sc:1: missing argument list for method repeat in object cmd88
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `repeat _` or `repeat(_,_)` instead of `repeat`.
val func = repeat
           ^
Compilation Failed
```

After all, since the compiler already knows that `repeat` is a method, and that 
it doesn't have it's arguments provided, why not convert it for me? Why force me
to go through the `_` or `(_, _)` dance, or why ask me to provide an expected type
for `func` if it already knows the type of `repeat`? 

In other languages with first-class functions, like Python, this works fine:

```python
>>> def repeat(s, i):
...     return s * i
...

>>> func = repeat

>>> func("hello", 3)
'hellohellohello'
```

The lack of automatic eta-expansion results in people writing weird code to work
around it, such as this example from [ScalaMock](http://scalamock.org/):

```scala
"drawLine" should "interact with Turtle" in {
  // Create mock Turtle object
  val mockedTurtle = mock[Turtle]
 
  // Set expectations
  (mockedTurtle.setPosition _).expects(10.0, 10.0)
  (mockedTurtle.forward _).expects(5.0)
  (mockedTurtle.getPosition _).expects().returning(15.0, 10.0)
 
  // Exercise System Under Test
  drawLine(mockedTurtle, (10.0, 10.0), (15.0, 10.0))
}
```

Here, the weird `(foo _)` dance is something that they have to do purely 
because of this restriction in eta-expansion.

While I'm sure there are good implementation-reasons why this doesn't work, I
don't see any reason this shouldn't work from a language-semantics point of 
view. From a user's point of view, methods and functions are just "things you 
call", and Scala is generally successful and not asking you to think about the
distinction between them.

However, in cases like this, I think there isn't a good reason the compiler 
shouldn't try a bit harder to figure out what I want before giving up and 
asking me to pepper `_`s or expected types all over the place. The compiler
*already has* all the information it needs - after all, it works if you put 
an `_` after the method - and it just needs to use that information when
the `_` isn't present.

### PR DESCRIPTION
**Pull request by odersky**
Require explicit () for nullary method applications. Fix a lot of files that were in violation. 

This is the final part of addressing #2570.

### CODE REVIEW

**Comment by odersky** [comment]
Migration strategy: We don't complain if the function was compiled by Scala 2 (this is because the Scala libraries need to be cleaned up first, so that they have `()` in the right places.).  

We issue a migration warning under `-language:Scala2`, and fix the problem under `-rewrite`. We 
issue an error otherwise. 

So, to migrate code to Dotty, just compile it with 

    dotc <files> -language:Scala2 -rewrite

It will insert the missing `()` arguments. ScalaFix should do the same. /cc @olafurpg.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -724,41 +724,70 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
...
+       */
+      var paramIndex = Map[Name, Int]()
+
+      /** If parameter `param` appears exactly once as an argument in `args`,
+       *  the singleton list consisting of its position in `args`, otherwise `Nil`.
+       */
+      def paramIndices(param: untpd.ValDef, args: List[untpd.Tree], start: Int): List[Int] = args match {
+        case arg :: args1 =>
+          if (refersTo(arg, param))
+            if (paramIndices(param, args1, start + 1).isEmpty) start :: Nil
```
Comment (senia-psm) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: This method returns `Some` if `param` appears in `args` any odd number of times, not only "exactly one".
Please see [this code snippet](https://scalafiddle.io/sf/UrSR4Gn/0).

Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Good catch.

**Comment by odersky** [comment]
We seem to have an error early on in the CI. The building `dotc` script fails with mysterious errors.

**Comment by olafurpg** [comment]
@odersky Noted. https://github.com/scalacenter/scalafix/issues/204

**Comment by smarter** [comment]
This PR needs to be rebased because scala-backend was updated in https://github.com/lampepfl/dotty/pull/2719

**Comment by odersky** [comment]
We also need to tighten the rules about overriding. It should be no longer legal to override `def f(): T` with `def f: T` and vice versa, except if one of the definitions is in Java or Scala 2 code.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 2]
```diff
@@ -470,6 +477,14 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
     case _ => false
   }
 
+  /** Is tree a compiler-generated `.apply` node that refers to the
+   *  apply of a function class? (implicit functions are excluded)
+   */
+  def isSyntheticApply(tree: Tree): Boolean = tree match {
+    case Select(qual, nme.apply) => tree.pos.end == qual.pos.end
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: Yes, but even for macro-generated apply's I would assume that we should not eta-expand (since the eta-expansion would simply undo what was generated).

File: docs/docs/reference/dropped/auto-apply.md [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+    }
+
+Methods overriding Java or Scala-2 methods are again exempted from this
+requirement.
+
+### Migrating code
+
+Existing Scala code with inconsistent parameters can still be compiled
+in Dotty under `-language:Scala2`. When paired with the `-rewrite`
+option, the code will be automatcally rewritten to conforrm to Dotty's
```
Comment (liufengyun) [inline docs/docs/reference/dropped/auto-apply.md]: Typo: conforrm -> conform.
