### PR TITLE
Handle type alias in capturing wildcards

### LINKED ISSUE #12739: `asInstanceOf` causes type mismatch error when used in method argument position
## Compiler version

3.0.0

## Minimized code

```Scala
object X {

  class CA[A]
  type C = CA[_]
  val c: C = ???
  def f[A](r: CA[A]) = ()

  // works
  f(c)

  // works
  val x = c.asInstanceOf[C]
  f(x)

  // error
  f(c.asInstanceOf[C])

  // works
  f(c.asInstanceOf[c.type])
}
```

## Output

```
[error] -- [E007] Type Mismatch Error: a.scala:16:18 
[error] 16 |  f(c.asInstanceOf[C])
[error]    |    ^^^^^^^^^^^^^^^^^
[error]    |    Found:    X.C
[error]    |    Required: X.CA[A]
[error]    |
[error]    |    where:    A is a type variable
[error] one error found
```

## Expectation

No error.

### PR DESCRIPTION
**Pull request by dwijnand**
We extend capturing wildcards so that it operates on the type after
dealiasing.  However, in line with, for example, derivedRefinedType, we
want to return the original type if nothing was captured, because it's
on that basis that adapt decides whether it needs to cast and re-adapt
to the new type with the type boxes.

Fixes #12739

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 1]
```diff
@@ -499,28 +499,30 @@ object Inferencing {
...
-              case TypeBounds(lo, hi) =>
-                val skolem = SkolemType(defn.TypeBoxClass.typeRef.appliedTo(lo | bounds.loBound, hi & bounds.hiBound))
-                TypeRef(skolem, defn.TypeBox_CAP)
-              case arg => arg
-            }
-          }
-          tp.derivedAppliedType(tycon, args1)
-        case _ =>
-          tp
+      val tparams = tycon.typeParamSymbols
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:517]: This line seems to change the semantics of the original program: If `tycon` is a type lambda instead of a class, its type parameters are not symbols.

**Review by liufengyun — APPROVED** [review]
LGTM

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala (hunk 1 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:517]: Meaning what happens now that didn't happen before?  I'll go back and check, and maybe even just leave it as it was, but it seemed to me that I was reusing a method that contained the same logic that was here, avoiding the cast.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:517]: Yeah, `typeParamSymbols` is almost a structural subset of the previous code here:

```scala
  /** If `self` is a generic class, its type parameter symbols, otherwise Nil */
  final def typeParamSymbols(using Context): List[TypeSymbol] = typeParams match {
    case tparams @ (_: Symbol) :: _ =>
      assert(tparams.forall(_.isInstanceOf[Symbol]))
      tparams.asInstanceOf[List[TypeSymbol]]
        // Note: Two successive calls to typeParams can yield different results here because
        // of different completion status. I.e. the first call might produce some symbols,
        // whereas the second call gives some LambdaParams. This was observed
        // for ticket0137.scala
    case _ => Nil
  }
```

So either I'm very blind or this is fine.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 2]
```diff
@@ -499,28 +499,30 @@ object Inferencing {
...
+      val args1 = args.zipWithConserve(tparams.map(_.paramInfo.substApprox(tparams, args))) {
+        case (TypeBounds(lo, hi), bounds) =>
+          val skolem = SkolemType(defn.TypeBoxClass.typeRef.appliedTo(lo | bounds.loBound, hi & bounds.hiBound))
+          TypeRef(skolem, defn.TypeBox_CAP)
+        case (arg, _) =>
+          arg
       }
+      tp.derivedAppliedType(tycon, args1)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:525]: Will `args1` be `Nil` if `tparams` is `Nil`? If that is the case, then we will need to check `tparams.isEmpty` and return `tp` for that case.

Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:525]: Good eye!  Will fix.

**Review by liufengyun — APPROVED** [review]
