### PR TITLE
Fix #7964: Allow inline enum parameters

### LINKED ISSUE #7964: Cannot pass enum values as inline parameters
## minimized code

```Scala
enum Nums { case One }

def fok(that: Nums) = ???
val ok = fok(Nums.One)

inline def fko(inline that: Nums) = ???
val ko = fko(Nums.One)
```

<details>
<summary>The compiler rejects the use of `One` as an inline parameter.</summary>

```scala
-- Error: ABug.scala:7:18 ------------------------------------------------------
7 |val ko = fko(Nums.One)
  |             ^^^^^^^^
  |             argument to inline parameter must be a known value
1 error found
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Still need to tests that they can be interpreted by the macros (Splicer).

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -836,10 +836,13 @@ trait Checking {
             def isCaseObject(sym: Symbol): Boolean =
               // TODO add alias to Nil in scala package
               sym.is(Case) && sym.is(Module)
+            def isisStaticEnumCase(sym: Symbol): Boolean =
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]:
```suggestion
            def isStaticEnumCase(sym: Symbol): Boolean =
```

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 2]
```diff
@@ -836,10 +836,13 @@ trait Checking {
...
+              sym.is(Enum) && sym.is(JavaStatic) && sym.is(Case)
             val allow =
               ctx.erasedTypes ||
               ctx.inInlineMethod ||
               (tree.symbol.isStatic && isCaseObject(tree.symbol) || isCaseClassApply(tree.symbol)) ||
+              isisStaticEnumCase(tree.symbol) ||
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]:
```suggestion
              isStaticEnumCase(tree.symbol) ||
```
