### PR TITLE
Unpickle arguments of parent constructors in Templates lazily

### LINKED ISSUE #16673: CyclicReference exception, thrown only during incremental compilation
## Compiler version

3.2.1
3.2.2-RC2

## Minimized code

**Important:** We need 2 separete files, or else the error won't happen.

Foo.scala:
```scala
final class Foo(_that: Foo) extends FooStub(_that)
```
FooStub.scala:
```scala
abstract class FooStub(val that: Foo):
  val bar = 1337;
```

## Output

Clean compile succeeds. 

To trigger the error, do the following:
1. Use `~compile` in sbt
2. Make a minor change to `FooStub` source: add or remove 1 digit from `bar`

```scala
[error] -- Error: /myproject/FooStub.scala:2:27 
[error] 2 |abstract class FooStub(val that: Foo):
[error]   |                           ^
[error]   |Could not read definition of class Foo in /myproject/target/scala-3.2.2-RC2/classes/Foo.class
[error]   |An exception was encountered:
[error]   |  dotty.tools.dotc.core.CyclicReference: 
[error]   |Run with -Ydebug-unpickling to see full stack trace.
```
Again, clean recompile succeeds. Until another minor change of source.

After adding suggested `-Ydebug-unpickling` and `-explain` options, got this:

```scala
[error] -- [E046] Cyclic Error: /myproject/FooStub.scala:3:27 
[error] 3 |abstract class FooStub(val that: Foo):
[error]   |                           ^
[error]   |                           Cyclic reference involving method <init>
[error]   |-----------------------------------------------------------------------------
[error]   | Explanation (enabled by `-explain`)
[error]   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]   | constructor FooStub is declared as part of a cycle which makes it impossible for the
[error]   | compiler to decide upon <init>'s type.
[error]   | To avoid this error, try giving <init> an explicit type.
[error]    -----------------------------------------------------------------------------
[error] Explanation
[error] ===========
[error] constructor FooStub is declared as part of a cycle which makes it impossible for the
[error] compiler to decide upon <init>'s type.
[error] To avoid this error, try giving <init> an explicit type.
```

Also, this thing showed up once:
```
OpenJDK 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
OpenJDK 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=131072Kb used=86902Kb max_used=127348Kb free=44169Kb
 bounds [0x00007f8e00000000, 0x00007f8e08000000, 0x00007f8e08000000]
 total_blobs=21123 nmethods=20197 adapters=828
 compilation: enabled
```

### PR DESCRIPTION
**Pull request by odersky**
Avoid reading the arguments of parent constructors unless someone forces them. We don't need them to determine the parent types of the class to which the template belongs. This makes TreeUnpickler as lazy as Namer in this respect and therefore avoids CyclicReferences during unpickling.

Fixes #16673

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/ast/Trees.scala [hunk 1]
```diff
@@ -855,16 +855,30 @@ object Trees {
...
    *                            Typed templates only have parents.
    */
-  case class Template[+T <: Untyped] private[ast] (constr: DefDef[T], parentsOrDerived: List[Tree[T]], self: ValDef[T], private var preBody: LazyTreeList[T])(implicit @constructorOnly src: SourceFile)
+  case class Template[+T <: Untyped] private[ast] (constr: DefDef[T], private var myParentsOrDerived: LazyTreeList[T], self: ValDef[T], private var preBody: LazyTreeList[T])(implicit @constructorOnly src: SourceFile)
     extends DefTree[T] with WithLazyField[List[Tree[T]]] {
     type ThisTree[+T <: Untyped] = Template[T]
     def unforcedBody: LazyTreeList[T] = unforced
     def unforced: LazyTreeList[T] = preBody
+
     protected def force(x: List[Tree[T @uncheckedVariance]]): Unit = preBody = x
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Trees.scala:864]: These methods from `WithLazyField` won't cause `myParentsOrDerived` to be forced which may break various tree traversals where we call `WithLazyField#forceIfLazy`. It seems that `WithLazyField` needs to be generalized to support multiple lazy fields.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/ast/Trees.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/ast/Trees.scala]: In fact they do force `myParentsOrDerived` by the logic in `Template` but that logic is obscure. I cleaned it up.

**Comment by odersky** [comment]
Since this should get into 3,0 a review is time-critical.

File: compiler/src/dotty/tools/dotc/ast/Trees.scala [hunk 2]
```diff
@@ -1013,17 +1021,11 @@ object Trees {
    *  accessed by `unforced` and `force`. Forcing the field will
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/Trees.scala:1021]: The comment still mentions `unforced` which was removed

**Review by sjrd — APPROVED** [review]
Looks fine.

(Also looks like one more reason to store parent types in TEMPLATE independently of super constructor calls. ;) )
