### PR TITLE
Deprecate MapOps.KeySet, replace with private (and more performant) strict/lazy KeySet implementations

### LINKED ISSUE #24749: Map#keySet is slow in 3.8.0-RC3
## Compiler version

3.8.0-RC3

## Minimized code

```scala
object ScalaTest:

  private val n = 10_000

  def main(args: Array[String]): Unit =
    val map: Map[Int, Unit] = (1 to n).map(i => i -> ()).toMap

    // FAST
    meter(".toMap"):
      map.contains

    // SLOW
    val set = map.keySet
    meter(".toMap.keySet"):
      set.contains

  private def meter[A](prefix: String)(f: Int => Boolean): Unit =
    val t = System.nanoTime() / 1_000_000
    for i <- 1 to n do if !f(i) then throw new NoSuchElementException
    println(prefix + " " + (System.nanoTime() / 1_000_000 - t) + "ms")
```

## Output

```
.toMap 3ms
.toMap.keySet 105ms
```

## Expectation

Checking whether a Set derived via the Map#keySet operation contains a key should not be slower than checking whether a Map contains a key. But it's really slow.

Probably due list traversal since https://github.com/scala/scala3/commit/e55df112ed78118a2e831a9fa961fb90ea5c1b15.

The example's execution time grows quadratically with n.

When compiled with Scalac 3.7.4, the example has same short execution times in both cases.

### PR DESCRIPTION
**Pull request by natsukagami**
Fixes #24749.

The PR contains two parts, one tiny and the other more involved.

## `KeySet` performance issues

Previously we use a `List[K]` to hold keys inside the strict KeySet, in order to
keep iteration order stable. However this degrades performance of KeySet as a Set.
The fix is to simply use something that has both. Currently it means `mutable.LinkedHashSet`,
so we use it, even though we don't intend to mutate the set at all.

## Deprecating `KeySet` as a whole and use our private implementations instead

As part of #23769 we categorised most data structures to be strict/pure (as in "not hiding any
computation as part of its structure"), which includes `Set`. **It turns out that our change to `MapOps.GenKeySet` in https://github.com/scala/scala3/pull/23769 was never backwards-compatible -- it creates abstract getters and setters for the `allKeys` val.**

This however clashes with how `.keySet` method was implemented: it returns a `Set[K]`, but
provides _no_ guarantee on whether it is a lazy view over the underlying data structure
(which _can_ be lazy, e.g. when you call `.keySet` from a `MapView`) or a strict set.
With API compatibility in mind, we now create strict key sets (with a copy of the keys)
in the generic case, while trying to detect whether the `.keySet` method was called from an
already strict data-structure (which is the majority case) - returning a thin-wrapper `LazyKeySet`
in that case. As the LazyKeySet works like a view with no aggregation, applying it over a strict
data structure doesn't violate strictness.

This left a few holes however, which was overlooked: some data structures such as `mutable.HashSet`
overrides `.keySet` with their own (protected!) classes, extending from the previously-ambiguous
KeySet classes (that is now made strict), and accidentally ending up always using the strict version.

Unfortunately we cannot modify these extended classes (for TASTy compatibility), so similar versions
extending the thin wrapper are added instead, and the old classes deprecated.
To not shoot ourselves in the foot in the future, these classes are also made `private[collection]`:
We don't expect classes like `HashMap` to be extended with a custom `KeySet`, and in the cases that
it does, it is not a problem to reimplement the missing 4-5 methods in the most efficient way for your
extended data structure.

### CODE REVIEW

**Comment by natsukagami** [comment]
It turns out that our change to `MapOps.GenKeySet` in #23769 was never backwards-compatible -- it creates abstract getters and setters for the `allKeys` val. 

I will make a commit that rolls back this change, add some `unsafeDiscardUses` (which requires #24273 to be backported to the next RC) to make `GenKeySet` capture-check, and then completely deprecate this trait.

**Comment by WojciechMazur** [comment]
Reference compiler is now 3.8.0-RC4 with #24273 backported, it should unblock this PR

**Comment by sjrd** [comment]
> more fluent with CC rules (@sjrd)

Ah, ah, I don't speak CC at all. :rofl:

File: library/src/scala/collection/Map.scala [hunk 1]
```diff
@@ -314,7 +316,10 @@ transparent trait MapOps[K, +V, +CC[_, _] <: IterableOps[?, AnyConstr, ?], +C]
     *  @param key the key
     *  @return    `true` if there is a binding for `key` in this map, `false` otherwise.
     */
-  def contains(key: K): Boolean = get(key).isDefined
+  def contains(key: K): Boolean =
+    // TODO: I'm not sure what's happening here, need to investigate a bit further.
+    // But this check should be fine: we of course can use a MapOps here.
+    caps.unsafe.unsafeDiscardUses(this.get(key)).isDefined
```
Comment (natsukagami) [inline library/src/scala/collection/Map.scala:322]: @odersky could this be a compiler bug? Removing this `unsafeDiscardUses` will yield an use error on `this`, which is of course strange... But this error also only shows up after I added the `unsafeDiscardUses` on the current `KeySet`.

Comment (odersky) [reply library/src/scala/collection/Map.scala:322]: I think the logic in the compiler is quite simple, probably a problem with setup. You could try to add a print to where `discardUses` is checked in `markFree` and see whether it triggers.
