### PR TITLE
Fix #1462: Move LiftTry as late as possible

### LINKED ISSUE #1462: Bad code generated for lazy vals with try
See tests/run/pending/t2333.scala.

Running this gives:

Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 36

### PR DESCRIPTION
**Pull request by smarter**
Otherwise we might miss try expressions which end up on a non-empty expression stack
due to a late transform such as LazyVals.

### CODE REVIEW

File: tests/run/i1692.scala [hunk 1]
```diff
@@ -51,9 +55,6 @@ class LazyNotNullable {
     lazy val l8 = h
   }
 
-  private[this] val i = "I"
-  // not nullable because try is lifted, so i is used outside lazy val initializer
-  lazy val l9 = try i catch { case e: Exception => () }
```
Comment (nicolasstucki) [inline tests/run/i1692.scala]: Shouldn't we keep this test and add the other as a new test? Or this the behavior of this one change?
