### PR TITLE
Drop "no inlines with opaques" implementation restriction

### LINKED ISSUE #12814: Loophole in "no inlined with opaque" checking
The following code is adapted from a [contributors comment](https://contributors.scala-lang.org/t/inline-methods-and-opaque-types/5051/10)
```scala
object refined:
  opaque type Positive = Int

  object Positive extends PositiveFactory

  trait PositiveFactory:
    inline def apply(value: Int): Positive = f(value) // error expected here
    def f(x: Positive): Positive = x

@main def run: Unit =
  import refined.*
  val x = 9
  val nine = Positive.apply(x)
```

**Behavior:**  At phase inlinining, the following error message;
```
-- [E007] Type Mismatch Error: opaque-inline.scala:14:28 -----------------------
14 |  val nine = Positive.apply(x)
   |                            ^
   |                            Found:    (x : Int)
   |                            Required: refined.Positive

longer explanation available when compiling with `-explain`
```
The error message makes no sense here. It came from the inlined expansion of `f(value)` which no longer typechecks
since the code is now outside of the region where the opaque alias was defined.

**Expected** Either an error on the definition of `apply`:
```
-- Error: opaque-inline.scala:8:15 ---------------------------------------------
8 |    inline def apply(value: Int): Positive = f(value)
  |               ^
  |Implementation restriction: No inline methods allowed where opaque type aliases are in scope
```
Or, if we can lift the implementation restriction, successful compilation with -Ycheck:all passing.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #12814

### CODE REVIEW

**Comment by odersky** [comment]
A more positive fix of the problem would drop the implementation restriction that inline methods cannot be defined where opaque types are visible. 

But it looks as hard as ever. Expanding inlines will render code type-incorrect as #12814 shows. We only eliminate opaque types some 20 phases later (after that the program would be type-correct again). And we cannot move elim opaques earlier since RefChecks assumes that opaque types are still opaque.

**Comment by soronpo** [comment]
Instead of restricting inlines completely, maybe just disallow the automatic "casting" to the opaque within the inline?
If I use an opaque type to create a new type `Positive` and I have an inline method that verifies the value, there is no reason I shouldn't be able to use `.asInstanceOf` instead: 
```scala
opaque type Positive <: Int = Int
object Positive:
  inline def apply(inline value : Int) : Positive = 
    inline if (value <= 0) compiletime.error("must be positive")
    else value.asInstanceOf[Positive]
  inline def justAnotherInlineDef : Unit = ??? //this is also disallowed :-(
```
Ideally, we wouldn't want `asInstanceOf[Positive]`, but this is a far better restriction than eliminating any inline definition within the scope of an opaque.

**Comment by smarter** [comment]
> But it looks as hard as ever. 

We've briefly discussed before if we could handle opaques in inline by giving a more precise type to the this proxy we generate, but I don't think anyone has actually tried it so far. Taking https://github.com/lampepfl/dotty/issues/12814 as an example, we get after inlining:
```scala
        val nine: refined.Positive = 
          {
            val PositiveFactory_this: refined.Positive.type = refined.Positive
            PositiveFactory_this.f(x):refined.Positive
          }
```
If we could instead generate:
```scala
  val nine = {
    val r1: refined.type & { type Positive = Int } = refined.asInstanceOf[ refined.type & { type Positive = Int }]
    val PositiveFactory_this: r1.Positive.type = r1.Positive
    PositiveFactory_this.f(x)
  }
```
Then the expansion would typecheck.

**Review by nicolasstucki — APPROVED** [review]

**Comment by odersky** [comment]
@smarter I did a first test with your idea which worked! So I want to follow up on this approach before merging this PR.

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -843,7 +924,16 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
...
     // make them part of `bindingsBuf`. The expansion is then the tree that remains.
-    val expansion = inliner.transform(rhsToInline)
+    val expansion0 = inliner.transform(rhsToInline)
+    val expansion =
+      if opaqueProxies.nonEmpty && !inlinedMethod.is(Transparent) then
+        expansion0.cast(call.tpe)(using ctx.withSource(expansion0.source))
+          // the cast makes sure that the sealing with the declared type
+          // is type correct. Without it we might get problems since the
+          // expression's type is the opaque alias but the call's type is
+          // the opaque type itself. An example is in pos/opaque-inline1.scala.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:934]: This branch is never actually reached for `pos/opaque-inline1.scala`, it is reached for `pos/opaque-inline.scala` but at that point `expansion0.tpe` and `call.tpe` are both `refined.Positive` so the cast doesn't do anything (and the test passes if I delete it).

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 2]
```diff
@@ -556,18 +556,93 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
...
+  def accountForOpaques(binding: ValDef)(using Context): ValDef =
+    binding.symbol.info.foreachPart {
+      case ref: TermRef =>
+        for cls <- ref.widen.classSymbols do
+          if cls.containsOpaques && mapRef(ref).isEmpty then
+            def openOpaqueAliases(selfType: Type): List[(Name, Type)] = selfType match
+              case RefinedType(parent, rname, TypeAlias(alias)) =>
+                val opaq = cls.info.member(rname).symbol
+                if opaq.isOpaqueAlias then
+                  (rname, alias.stripLazyRef.asSeenFrom(ref, cls))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:610]: Minor point: we could check the accessibility of `alias` at this point to generate a slightly better error message if it isn't accessible, but the current one isn't too bad:
```scala
object refined:
  private class Internal(x: Int)
  opaque type Positive = Internal
  inline def Positive(value: Int): Positive = new Internal(value)

object test:
  def run: Unit =
    val x = 9
    val nine = refined.Positive(x)
```
```scala
-- Error: tests/pos/opaque-inline1.scala:10:31 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
10 |    val nine = refined.Positive(x)
   |               ^^^^^^^^^^^^^^^^^^^
   |               class Internal cannot be accessed as a member of (refined : refined.type{Positive = refined.Internal}) from module class test$.
   | This location contains code that was inlined from opaque-inline1.scala:4
```

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 3]
```diff
@@ -556,18 +556,93 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
...
+   *  refer to objects with opaque type aliases and local proxy symbols
+   *  that contain refined versions of these TermRefs where the aliases
+   *  are exposed.
+   */
+  private val opaqueProxies = new mutable.ListBuffer[(TermRef, TermRef)]
+
+  /** Map first halfs of opaqueProxies pairs to second halfs, using =:= as equality */
+  def mapRef(ref: TermRef): Option[TermRef] =
+    opaqueProxies
+      .find((from, to) => from.symbol == ref.symbol && from =:= ref)
```
Comment (johnynek) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala:578]: you can also write:
```scala
opaqueProxies
  .collectFirst { case (from, to) if from.symbol == ref.symbol && from =:= ref => to }
```
and I think not have two lambdas.

File: tests/pos/opaque-inline.scala [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+  opaque type Positive = Int
+
+  object Positive extends PositiveFactory
+
+  trait PositiveFactory:
+    inline def apply(value: Int): Positive = value
+
+    def f(x: Positive): Positive = x
+    inline def fapply(value: Int): Positive =
+      val vv = (value, value) // error: implementation restriction
```
Comment (johnynek) [inline tests/pos/opaque-inline.scala:12]: is this comment correct? Is this still an error? I'm confused about it being in `tests/pos`, maybe it is checking an error message...

Comment (bishabosha) [reply tests/pos/opaque-inline.scala:12]: usually this marks something that was previously an error, which was fixed in the PR that added the file

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 3 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:578]: Thanks for the hint. I'll change it.

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:610]: There was a wrong condition for eliding the proxies, which is fixed in 2414033. Now pos/opaque-inline1 does not compile anymore if I remove the cast. It fails in -Ycheck with
```
java.lang.AssertionError: assertion failed: Found:    Int
Required: refined.Positive
found: class Int in package scala with class Int, flags = final abstract <scala-2.x> <touched>, underlying = Int, AnyVal {...}
expected: type Positive in object refined with type Positive, flags = <deferred> opaque <touched>, underlying = refined.Positive, , Any, {...}
tree = {
  val $proxy1: refined.type{Positive = Int} = 
    refined.$asInstanceOf[refined.type{Positive = Int}]
  val refined$_this: ($proxy1 : refined.type{Positive = Int}) = $proxy1
  refined$_this.f(x):refined$_this.Positive
} while compiling opaque-inline1.scala
```
The weird thing is that with the original condition everything succeeded, even though the expansion was then
```scala
  val x = 9
  val nine = refined.f(x): refined.Positive
```
This is clearly type-incorrect, since `9` is an `Int` and `refined.f` expects as `refined.Positive`. Indeed, if I write this expansion manually, it fails.
```scala
-- [E007] Type Mismatch Error: opaque-inline1.scala:12:25 ----------------------
12 |    val nine = refined.f(x): refined.Positive
   |                         ^
   |                         Found:    (x : Int)
   |                         Required: refined.Positive
```
But somehow `-Ycheck` does not test this. I traced Ychecks behavior and it seems to think that `refined.f: Int => Int` even though it should be `refined.f: Positive => Positive`. The reason for this is that it copies the tree `refined.f` as is from the inline method, which is in a scope where `Positive = Int`. Hence, `Int => Int` is a legal type for `f` there. It's the copying that is wrong, and unfortunately Ycheck does not catch it.

But the cases won't arise anymore with this PR.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 5]
```diff
@@ -843,7 +924,16 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
 
     // Apply inliner to `rhsToInline`, split off any implicit bindings from result, and
     // make them part of `bindingsBuf`. The expansion is then the tree that remains.
-    val expansion = inliner.transform(rhsToInline)
+    val expansion0 = inliner.transform(rhsToInline)
+    val expansion =
+      if opaqueProxies.nonEmpty && !inlinedMethod.is(Transparent) then
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:929]: I am not sure what you propose. Right now, we don't do it for Transparent since we return whatever the inlined function returns. We can't cast to the call type by definition. And for normal inlines we already wrap with the call type. The cast just makes sure that that wrapping is always successful.

[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: After discussing I understand now. I updated the test to also do transparent inlines, and indeed we need a cast in that case as well.

**Review by smarter — APPROVED** [review]
🎆
