### PR TITLE
Fix #3279

### LINKED ISSUE #3279: New REPL crashes when used through "sbt console"
- git clone http://github.com/lampepfl/dotty-example-project
- Set the version number to `0.4.0-bin-20171005-af528a1-NIGHTLY`
- `sbt console`
```scala
scala> 1+1 
[error] (run-main-3) java.lang.ClassNotFoundException: rs$line$1
java.lang.ClassNotFoundException: rs$line$1
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sbt.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:59)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at dotty.tools.repl.Rendering.valueOf(Rendering.scala:51)
        at dotty.tools.repl.Rendering.renderVal(Rendering.scala:75)
        at dotty.tools.repl.ReplDriver.displayMembers$5$$anonfun$4(ReplDriver.scala:262)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at dotty.tools.repl.ReplDriver.displayMembers$1(ReplDriver.scala:262)
        at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$3$$anonfun$2(ReplDriver.scala:289)
        at scala.Option.map(Option.scala:146)
        at dotty.tools.repl.ReplDriver.displayDefinitions$$anonfun$1(ReplDriver.scala:289)
        at dotty.tools.dotc.core.Periods.atPhase(Periods.scala:26)
        at dotty.tools.dotc.core.Phases.atPhase(Phases.scala:36)
        at dotty.tools.repl.ReplDriver.displayDefinitions(ReplDriver.scala:294)
        at dotty.tools.repl.ReplDriver.compile$$anonfun$1(ReplDriver.scala:219)
        at scala.util.Either.fold(Either.scala:188)
        at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:220)
        at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:187)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:140)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
        at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.Defaults$$anonfun$consoleTask$1$$anonfun$apply$54.apply(Defaults.scala:850)
        at sbt.Defaults$$anonfun$consoleTask$1$$anonfun$apply$54.apply(Defaults.scala:850)
        at scala.Option.foreach(Option.scala:236)
        at sbt.Defaults$$anonfun$consoleTask$1.apply(Defaults.scala:850)
        at sbt.Defaults$$anonfun$consoleTask$1.apply(Defaults.scala:845)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (compile:console) Nonzero exit code: 1
[error] Total time: 2 s, completed 6 oct. 2017 17:35:07
```

@felixmulder Do you know if that used to work?

### PR DESCRIPTION
**Pull request by allanrenucci**
When using the repl through "sbt console", we used to use the class
loader sbt give us. But we need a class loader that has the output
directory of the compiler on the classpath

### CODE REVIEW

**Comment by allanrenucci** [comment]
Can I write sbt scipted tests that test the console?

**Comment by felixmulder** [comment]
I'll defer that to @smarter :)

File: compiler/src/dotty/tools/repl/Rendering.scala [hunk 1]
```diff
@@ -21,24 +21,24 @@ import dotc.core.StdNames.str
...
-                              private var currentClassLoader: Option[ClassLoader] = None) {
+                              parentClassLoader: Option[ClassLoader] = None) {
 
-  private def classLoader()(implicit ctx: Context) =
-    currentClassLoader.getOrElse {
-      import java.net.{URL, URLClassLoader}
-
-      /** the compiler's classpath, as URL's */
-      val compilerClasspath: Seq[URL] = ctx.platform.classPath(ctx).asURLs
+  private var _classLoader: ClassLoader = _
```
Comment (smarter) [inline compiler/src/dotty/tools/repl/Rendering.scala]: `private[this]`. Also we usuallly call these variables `myFoo` instead of  `_foo`.
