### PR TITLE
Fix #9642: fix bootstrapping on Windows

### LINKED ISSUE #9642: The bootstrapped build is broken on Windows after #9615
#9615 broke the bootstrapped build on Windows. The following command fails on Windows after this PR:
```
> sbt clean dotty-library-bootstrapped/compile
```
Most likely relevant part of the output:
```
...
[info] Compiling 89 Scala sources and 116 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\library\..\out\bootstrap\dotty-library-bootstrapped\scala-0.27\classes ...
[error] Bad symbolic reference. A signature
[error] refers to Class/T in package java.lang which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
[error] Bad symbolic reference. A signature
[error] refers to String/T in package java.lang which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
java.lang.UnsupportedOperationException: openForMutations while compiling [...]
...
```

<details>
<summary>Full output</summary>

```
C:\Users\sjrdo\Documents\Projets\dotty>sbt clean dotty-library-bootstrapped/compile
[info] welcome to sbt 1.3.12 (AdoptOpenJDK Java 1.8.0_222)
[info] loading global plugins from C:\Users\sjrdo\.sbt\1.0\plugins
[info] loading settings for project dotty-build-build from build.sbt ...
[info] loading project definition from C:\Users\sjrdo\Documents\Projets\dotty\project\project
[info] loading settings for project dotty-build from build.sbt,plugins.sbt ...
[info] loading project definition from C:\Users\sjrdo\Documents\Projets\dotty\project
[info] loading settings for project dotty from build.sbt ...
[info] resolving key references (24980 settings) ...
[info] set current project to dotty (in build file:/C:/Users/sjrdo/Documents/Projets/dotty/)
[success] Total time: 1 s, completed 26 ao¹t 2020 09:46:47
[success] Total time: 0 s, completed 26 ao¹t 2020 09:46:47
[info] Compiling 7 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\interfaces\target\classes ...
[info] Compiling 78 Scala sources and 116 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\library\target\scala-0.27\classes ...
[info] Unpacking scalajs-ir sources to C:\Users\sjrdo\Documents\Projets\dotty\compiler\target\scala-0.27\src_managed\main\scalajs-ir-src...
[info] Compiling 7 Scala sources to C:\Users\sjrdo\Documents\Projets\dotty\tasty\target\scala-0.27\classes ...
[info] Compiling 440 Scala sources and 5 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\compiler\target\scala-0.27\classes ...
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Compiling 44 Scala sources and 1 Java source to C:\Users\sjrdo\Documents\Projets\dotty\doc-tool\target\scala-0.27\classes ...
[info] Compiling 9 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\sbt-bridge\src\target\classes ...
[warn] C:\Users\sjrdo\Documents\Projets\dotty\sbt-bridge\src\xsbt\DelegatingReporter.java:22:1: dotty$tools$dotc$reporting$UniqueMessagePositions$$positions() in dotty.tools.dotc.reporting.AbstractReporter implements dotty$tools$dotc$reporting$UniqueMessagePositions$$positions() in dotty.tools.dotc.reporting.UniqueMessagePositions
[warn]   return type requires unchecked conversion from scala.collection.mutable.HashMap to scala.collection.mutable.HashMap<scala.Tuple2<dotty.tools.dotc.util.SourceFile,java.lang.Object>,java.lang.Object>
[warn] final public class DelegatingReporter extends AbstractReporter {
[warn]   private final xsbti.Reporter delegate;
[warn]
[warn]   private static final Position noPosition = new Position() {
[warn]     public Optional<java.io.File> sourceFile() {
[warn]       return Optional.empty();
[warn]     }
[warn]     public Optional<String> sourcePath() {
[warn]       return Optional.empty();
[warn]     }
[warn]     public Optional<Integer> line() {
[warn]       return Optional.empty();
[warn]     }
[warn]     public String lineContent() {
[warn]       return "";
[warn]     }
[warn]     public Optional<Integer> offset() {
[warn]       return Optional.empty();
[warn]     }
[warn]     public Optional<Integer> pointer() {
[warn]       return Optional.empty();
[warn]     }
[warn]     public Optional<String> pointerSpace() {
[warn]       return Optional.empty();
[warn]     }
[warn]   };
[warn]
[warn]   public DelegatingReporter(xsbti.Reporter delegate) {
[warn]     super();
[warn]     this.delegate = delegate;
[warn]   }
[warn]
[warn]   @Override
[warn]   public void printSummary(Context ctx) {
[warn]     delegate.printSummary();
[warn]   }
[warn]
[warn]   public void doReport(dotty.tools.dotc.reporting.Diagnostic dia, Context ctx) {
[warn]     Severity severity;
[warn]     switch (dia.level()) {
[warn]       case Diagnostic.ERROR:
[warn]         severity = Severity.Error;
[warn]         break;
[warn]       case Diagnostic.WARNING:
[warn]         severity = Severity.Warn;
[warn]         break;
[warn]       case Diagnostic.INFO:
[warn]         severity = Severity.Info;
[warn]         break;
[warn]       default:
[warn]         throw new IllegalArgumentException("Bad diagnostic level: " + dia.level());
[warn]     }
[warn]
[warn]     Position position;
[warn]     if (dia.pos().exists()) {
[warn]       SourcePosition pos = dia.pos();
[warn]       SourceFile src = pos.source();
[warn]       position = new Position() {
[warn]         public Optional<String> sourcePath() {
[warn]           if (!src.exists())
[warn]             return Optional.empty();
[warn]
[warn]           return Optional.ofNullable(src.file().path());
[warn]         }
[warn]         public Optional<java.io.File> sourceFile() {
[warn]           if (!src.exists())
[warn]             return Optional.empty();
[warn]
[warn]           return Optional.ofNullable(src.file().file());
[warn]         }
[warn]         public Optional<Integer> line() {
[warn]           if (src.content().length == 0)
[warn]             return Optional.empty();
[warn]
[warn]           int line = pos.line() + 1;
[warn]           if (line == -1)
[warn]             return Optional.empty();
[warn]
[warn]           return Optional.of(line);
[warn]         }
[warn]         public String lineContent() {
[warn]           if (src.content().length == 0)
[warn]             return "";
[warn]
[warn]           String line = pos.lineContent();
[warn]           if (line.endsWith("\r\n"))
[warn]             return line.substring(0, line.length() - 2);
[warn]           if (line.endsWith("\n") || line.endsWith("\u000c"))
[warn]             return line.substring(0, line.length() - 1);
[warn]
[warn]           return line;
[warn]         }
[warn]         public Optional<Integer> offset() {
[warn]           return Optional.of(pos.point());
[warn]         }
[warn]         public Optional<Integer> pointer() {
[warn]           if (src.content().length == 0)
[warn]             return Optional.empty();
[warn]
[warn]           return Optional.of(pos.point() - src.startOfLine(pos.point()));
[warn]         }
[warn]         public Optional<String> pointerSpace() {
[warn]           if (src.content().length == 0)
[warn]             return Optional.empty();
[warn]
[warn]           String lineContent = this.lineContent();
[warn]           int pointer = this.pointer().get();
[warn]           StringBuilder result = new StringBuilder();
[warn]           for (int i = 0; i < pointer; i++)
[warn]             result.append(lineContent.charAt(i) == '\t' ? '\t' : ' ');
[warn]           return Optional.of(result.toString());
[warn]         }
[warn]       };
[warn]     } else {
[warn]       position = noPosition;
[warn]     }
[warn]
[warn]     Message message = dia.msg();
[warn]     StringBuilder rendered = new StringBuilder();
[warn]     rendered.append(messageAndPos(message, dia.pos(), diagnosticLevel(dia), ctx));
[warn]     boolean shouldExplain = dotty.tools.dotc.reporting.Diagnostic.shouldExplain(dia, ctx);
[warn]     if (shouldExplain && !message.explanation().isEmpty()) {
[warn]       rendered.append(explanation(message, ctx));
[warn]     }
[warn]
[warn]     delegate.log(new Problem(position, message.msg(), severity, rendered.toString()));
[warn]   }
[warn] }
[info] Compiling 89 Scala sources and 116 Java sources to C:\Users\sjrdo\Documents\Projets\dotty\library\..\out\bootstrap\dotty-library-bootstrapped\scala-0.27\classes ...
[error] Bad symbolic reference. A signature
[error] refers to Class/T in package java.lang which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
[error] Bad symbolic reference. A signature
[error] refers to String/T in package java.lang which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
java.lang.UnsupportedOperationException: openForMutations while compiling C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\dotty\internal\CompileTimeMacros.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\dotty\internal\StringContextMacro.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\Enum.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\internal\TupledFunction.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\internal\quoted\CompileTime.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\internal\quoted\Expr.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\internal\quoted\Matcher.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\internal\quoted\Type.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\internal\quoted\Unpickler.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Const.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Consts.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Expr.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Lambda.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Liftable.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\QuoteContext.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Type.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Unliftable.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Unlifted.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\Varargs.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\report.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\unsafe\UnsafeExpr.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\util\ExprMap.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\quoted\util\Var.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src-bootstrapped\scala\runtime\EnumValues.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\DottyPredef.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\Arrays.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\LazyVals.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcB$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcC$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcS$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcV$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0$mcZ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction0.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcDF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcFD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcFF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcFI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcFJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcIF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcJF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcVD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcVF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcVI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcVJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcZD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcZF$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcZI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1$mcZJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction1.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcDJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcFJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcIJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcJJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcVJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZDD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZDI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZDJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZID$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZII$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZIJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZJD$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZJI$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2$mcZJJ$sp.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JFunction2.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure0.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure1.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure10.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure11.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure12.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure13.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure14.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure15.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure16.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure17.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure18.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure19.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure2.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure20.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure21.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure22.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure3.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure4.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure5.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure6.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure7.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure8.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\dotty\runtime\function\JProcedure9.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scalaShadowing\language.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\Conversion.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\Eql.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\FunctionXXL.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\IArray.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\PolyFunction.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\Product0.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\Selectable.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\Tuple.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\TupledFunction.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\RefiningAnnotation.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\alpha.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\constructorOnly.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\infix.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\Alias.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\AnnotationDefault.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\Body.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\Child.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\ContextResultCount.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\Repeated.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\SourceFile.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\TASTYLongSignature.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\TASTYSignature.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\TransparentParam.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\WithBounds.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\sharable.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\internal\unshared.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\static.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\superTrait.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\annotation\threadUnsafe.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\compiletime\ops\package.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\compiletime\package.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\compiletime\testing\Error.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\compiletime\testing\ErrorKind.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\compiletime\testing\package.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\deriving.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\implicits\package.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\internal\Chars.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\internal\MatchCase.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\internal\TypeBox.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\internal\quoted\showName.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\internal\tasty\CompilerInterface.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\main.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\quoted\ScopeException.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\quoted\qctx.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\quoted\show\SyntaxHighlight.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\reflect\Selectable.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\runtime\EnumValue.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\runtime\EnumValueSerializationProxy.java, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\runtime\Tuple.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\runtime\TupleXXL.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\Reflection.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\ExprCastError.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\ExtractorsPrinter.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\Printer.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\SourceCodePrinter.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\TreeAccumulator.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\TreeMap.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\TreeTraverser.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\tasty\reflect\TypeTest.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\util\CommandLineParser.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\util\FromDigits.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\util\FromString.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\util\Not.scala, C:\Users\sjrdo\Documents\Projets\dotty\library\src\scala\util\control\NonLocalReturns.scala
[error] ## Exception when compiling 205 sources to C:\Users\sjrdo\Documents\Projets\dotty\library\..\out\bootstrap\dotty-library-bootstrapped\scala-0.27\classes
[error] java.lang.UnsupportedOperationException: openForMutations
[error] dotty.tools.package$.unsupported(package.scala:25)
[error] dotty.tools.dotc.core.Scopes$Scope.openForMutations(Scopes.scala:178)
[error] dotty.tools.dotc.core.SymDenotations$ClassDenotation.enter(SymDenotations.scala:1791)
[error] dotty.tools.dotc.core.Symbols$Symbol.entered(Symbols.scala:195)
[error] dotty.tools.dotc.core.Definitions.enterMethod(Definitions.scala:143)
[error] dotty.tools.dotc.core.Definitions.String_$plus(Definitions.scala:541)
[error] dotty.tools.dotc.core.Definitions.syntheticCoreMethods(Definitions.scala:1533)
[error] dotty.tools.dotc.core.Definitions.init(Definitions.scala:1547)
[error] dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:796)
[error] dotty.tools.dotc.core.Contexts$Context.initialize(Contexts.scala:534)
[error] dotty.tools.dotc.Run.rootContext(Run.scala:65)
[error] dotty.tools.dotc.Run.<init>(Run.scala:83)
[error] dotty.tools.dotc.Compiler.newRun(Compiler.scala:151)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
[error] dotty.tools.dotc.Driver.process(Driver.scala:195)
[error] dotty.tools.dotc.Main.process(Main.scala)
[error] xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error] xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]
[error] java.lang.UnsupportedOperationException: openForMutations
[error]         at dotty.tools.package$.unsupported(package.scala:25)
[error]         at dotty.tools.dotc.core.Scopes$Scope.openForMutations(Scopes.scala:178)
[error]         at dotty.tools.dotc.core.SymDenotations$ClassDenotation.enter(SymDenotations.scala:1791)
[error]         at dotty.tools.dotc.core.Symbols$Symbol.entered(Symbols.scala:195)
[error]         at dotty.tools.dotc.core.Definitions.enterMethod(Definitions.scala:143)
[error]         at dotty.tools.dotc.core.Definitions.String_$plus(Definitions.scala:541)
[error]         at dotty.tools.dotc.core.Definitions.syntheticCoreMethods(Definitions.scala:1533)
[error]         at dotty.tools.dotc.core.Definitions.init(Definitions.scala:1547)
[error]         at dotty.tools.dotc.core.Contexts$ContextBase.initialize(Contexts.scala:796)
[error]         at dotty.tools.dotc.core.Contexts$Context.initialize(Contexts.scala:534)
[error]         at dotty.tools.dotc.Run.rootContext(Run.scala:65)
[error]         at dotty.tools.dotc.Run.<init>(Run.scala:83)
[error]         at dotty.tools.dotc.Compiler.newRun(Compiler.scala:151)
[error]         at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
[error]         at dotty.tools.dotc.Driver.process(Driver.scala:195)
[error]         at dotty.tools.dotc.Main.process(Main.scala)
[error]         at xsbt.CachedCompilerImpl.run(CachedCompilerImpl.java:69)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.java:41)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (dotty-library-bootstrapped / Compile / compileIncremental) java.lang.UnsupportedOperationException: openForMutations
[error] Total time: 58 s, completed 26 ao¹t 2020 09:47:45
```

</details>

Reverting the PR makes the above command succeed again.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #9642: fix bootstrapping on Windows

### CODE REVIEW

**Comment by liufengyun** [comment]
test performance please

**Review by sjrd — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/classpath/ClassPath.scala [hunk 1]
```diff
@@ -23,8 +23,15 @@ trait SourceFileEntry extends ClassRepresentation {
 }
 
 case class PackageName(dottedString: String) {
+  val dirPathTrailingSlashJar: String = FileUtils.dirPathInJar(dottedString) + "/"
+
+  val dirPathTrailingSlash: String =
+    if (java.io.File.separatorChar == '/')
+      dirPathTrailingSlashJar
+    else
+      FileUtils.dirPath(dottedString) + java.io.File.separator
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/classpath/ClassPath.scala:32]: I don't know if this is too cautious. One justification for the duplication is to save hours of debugging for future maintainers.

WDYT @sjrd ?

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/classpath/ClassPath.scala:32]: If this file name is used for *lookup* only, then it can be `/` on all platforms, including Windows. Java can find files that you specify with `/` as if they were `\`.

Where it breaks down is when *listing* files, then comparing their paths to some other data where you always have `/`, or if you `split('/'`). Because Windows will give you `\`, which won't be compared/split correctly.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/classpath/ClassPath.scala:32]: Yes, that is the worry I have. String paths like `a/b/c` on windows are mines: if they are accidentally spliced to form a bigger string path, errors are guaranteed. Currently (before this commit), they already leak to `DirectoryPath`, and works accidentally.
