### PR TITLE
Fix #1895: Use proper validity period for extension methods

### LINKED ISSUE #1895: Bringing a symbol to a new run is broken
Summarizing what we discussed last month:
A common pattern in `InfoTransformer` like `ExtensionMethods` is to create new symbols like `foo$extension` in the current phase and to add them to the declarations of a class in the next phase. This causes problem when we try to bring forward the denotation corresponding to such a symbol to a subsequent run, because `stillValid` considers a denotation to be valid if it's valid in its owner at the first phase it's defined, but at its first phase the symbol has no owner yet!
Here is a testcase:
```scala
scala> class Foo(x: Int) extends AnyVal { def foo: Int = 1 }
defined class Foo
scala> new Foo(1).foo
Exception in thread "main" dotty.tools.dotc.core.Denotations$StaleSymbol: stale symbol; method foo$extension#33232 in module class Foo$, defined in Period(12..33, run = 4), is referred to in run Period(13..13, run = 6)
        at dotty.tools.dotc.core.Denotations$SingleDenotation.staleSymbolError(Denotations.scala:932)
...
```

We can extend `stillValid` to also check the phase right after the first phase but that's still not enough because InfoTransformers are lazy and the InfoTransformer for the next phase might never have run in the initial run where the symbol was created! I've only been able to reproduce this using the sbt-based bootstrap of dotty by running `dotty-compiler-bootstrapped/test-only -- --tests=repl_all`. I currently work around this by explicitly forcing the denotation of extension methods at the phase where they're entered in their owner, but this is just a hack.

@DarkDimius suggested that we always recompute denotations from pickling, doing this may require a lot of work.

### PR DESCRIPTION
**Pull request by smarter**
When we create a symbol in a DenotationTransformer, we cannot safely
create it at phase `thisPhase.next` since this can lead to cycles. This
is why we created extension methods at phase `thisPhase`, but they're
not really valid at that point since they're only entered in their owner
once the transformer has been run. This lead to stale symbol errors
which were worked around in 51a458e but
the fix is incomplete and does not work with #4604 because that PR moves
the ExtensionMethods phase around.

This PR removes all the workarounds and uses a simpler solution:
create the symbols at phase `thisPhase` but set their validity
period to match the validity of the owner transformed denotation.

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/DenotTransformers.scala [hunk 1]
```diff
@@ -24,9 +24,9 @@ object DenotTransformers {
     /** The last phase during which the transformed denotations are valid */
     def lastPhaseId(implicit ctx: Context) = ctx.nextDenotTransformerId(id + 1)
 
-    /** The validity period of the transformer in the given context */
+    /** The validity period of the transformed denotations in the given context */
     def validFor(implicit ctx: Context): Period =
-      Period(ctx.runId, id, lastPhaseId)
+      Period(ctx.runId, id + 1, lastPhaseId)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: At first I was scared, because it looks really hard to see all the ramifications of this change. But then I found out that the method is in fact not used at all! So do we still want to keep it?
