### PR TITLE
Fix #10123: Try to fully define qualifier type

### LINKED ISSUE #10123: Error on calling a method on the result of a Scala 2 style polymorphic extension method
## Minimized code

```Scala
// build.sbt
lazy val root = project
  .in(file("."))
  .settings(
    scalaVersion := "3.0.0-M1-bin-20201027-b5a1715-NIGHTLY",
    libraryDependencies ++= Seq(
      "com.sksamuel.elastic4s" % "elastic4s-embedded_2.13" % "5.6.11"
    )
  )
```
```scala
//src/main/scala/Main.scala
import com.sksamuel.elastic4s.TcpClient
import com.sksamuel.elastic4s.ElasticDsl
import org.elasticsearch.cluster.health.ClusterHealthStatus

object Main {
  import ElasticDsl._

  def status1(client: TcpClient): ClusterHealthStatus = {
    val response = client.execute(clusterHealth()).await
    response.getStatus()
  }

  def status2(client: TcpClient): ClusterHealthStatus =
    client.execute(clusterHealth()).await.getStatus()
}
```

## Output

```scala
[info] compiling 1 Scala source to /target/scala-3.0.0-M1/classes ...
[error] -- [E008] Not Found Error: /src/main/scala/Main.scala:15:42 
[error] 15 |    client.execute(clusterHealth()).await.getStatus()
[error]    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value getStatus is not a member of org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse - did you mean org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse.getStatus
[error] one error found
```

## Expectation

Method `status1` does compile and so method `status2` should compile as well.

### PR DESCRIPTION
**Pull request by odersky**
Try to fully define qualifier type before emitting an error for
a typed Select.

The one possible objection to doing this is that it might hide other
errors where a type was not sufficiently well defined before we
select on it. On the other hand:

 - My comment in issue #10123 (EDIT: and the reclassified test in 10b99f1 )
   shows that the problem is more widespread than just a single case.
 - We otherwise rely on interpolation to instantiate type variables in
   many cases. But interpolation is meant as an optimization only, to
   keep constraint sets smaller. So, we should be prepared that interpolation
   will not do its job. The fix in this commit is a way to do so.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala [hunk 1]
```diff
@@ -159,6 +160,9 @@ trait TypeAssigner {
       TryDynamicCallType
     else if (qualType.isErroneous || name.toTermName == nme.ERROR)
       UnspecifiedErrorType
+    else if !isFullyDefined(qualType, ForceDegree.none) && isFullyDefined(qualType, ForceDegree.failBottom) then
+      // try again with more defined qualifier type
+      selectionType(tree, qual1)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:165]: `isFullyDefined` traverses the whole type to instantiate type variables, but to be able to type a selection we really only need to make sure the top-level part of the type is instantiated, I've been experimenting with this separately since it would become even more necessary if we allow lambda binders to not be fully instantiated, if you want I can try to extract that into its own PR.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala:165]: Yes, please go ahead with this!

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala]: I added a new method `couldInstantiateTypeVar` to `Inferencing` that does this.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 2]
```diff
@@ -81,6 +81,19 @@ object Inferencing {
     if (depVars.nonEmpty) instantiateSelected(tp, depVars.toList)
   }
 
+  /** If `tp` is type variable with a lower bound in the current constraint,
+   *  instantiate it from below.
+   */
+  def couldInstantiateTypeVar(tp: Type)(using Context): Boolean = tp.dealias match
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:87]: I don't think that's quite right either since given `?F[?A]` I need to instantiate at least `?F`, and then if it's a type lambda I may or may not need to instantaite `?A` too. Also since this is a selection prefix, we want to avoid `Nothing` if possible, in fact in all situation where we're trying to avoid `Nothing`, we only want to avoid it at the top-level. This is what I came up last time I was looking at this: https://github.com/dotty-staging/dotty/blob/63c7bad7f01c5fccf4620376aa7c8f70bc90b66d/compiler/src/dotty/tools/dotc/typer/Inferencing.scala#L49-L83
but I was a bit concerned that this duplicated code from IsFullyDefinedAccumulator.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:88]: Right. In this particular case we need to instantiate the `?F`. The `?A` can come later when we recursively call `typedSelect` on the new call. I have taken your changes and adapted them to `couldInstantiateTypeVar`. You don't need to check for `LazyRef`  in either code, since that is already eliminated by `dealias`. On the other hand, one should look inside AndTypes, OrTypes, and AnnotatedTypes.

**Comment by odersky** [comment]
Ready to merge?

**Comment by smarter** [comment]
I'd like to spend some time reviewing it tomorrow.

**Comment by odersky** [comment]
OK. I let you take it over then.

**Comment by odersky** [comment]
I propose to merge this now.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 3]
```diff
@@ -81,6 +81,28 @@ object Inferencing {
...
+  /** If `tp` is top-level type variable with a lower bound in the current constraint,
+   *  instantiate it from below. We also look for TypeVars whereever their instantiation
+   *  could uncover new type members.
+   */
+  def couldInstantiateTypeVar(tp: Type)(using Context): Boolean = tp.dealias match
+    case tvar: TypeVar
+    if !tvar.isInstantiated
+       && ctx.typerState.constraint.contains(tvar)
+       && tvar.hasLowerBound =>
+      tvar.instantiate(fromBelow = true)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:93]: When trying to select from something that doesn't have a lower-bound, rather than giving up I think it makes sense to try the upper bound, since it might be precise enough, also we could take `instDireciton` into account to be closer to the normal behavior of `isFullyDefined`:
```suggestion
      =>
      val direction = instDirection(tvar.origin)
      tvar.instantiate(fromBelow = direction < 0 || tvar.hasLowerBound)
```

**Review by smarter — CHANGES_REQUESTED** [review]
I've rebased, added a testcase showing that this fixes another issue, and suggested one change, I can take care of committing that change and making sure it works if it looks OK to you.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala (hunk 3 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:93]: I am not sure that will help. The situation is that we try to select a member that does not exist on the type variable. Instantiating to the upper bound would not help in this case. If the member existed on the upper bound, it would also exist on the variable itself.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:93]: > If the member existed on the upper bound, it would also exist on the variable itself.

Ah indeed, because `goParam` in `findMember` will recurse on the upper bound, but isn't that actually problematic? If I have a selection `x.foo` where the type of `x` is a type variable `?T <: B`, we'll end up selecting some overload of `B#foo`, but it's possible that `?T` is then instantiated to some more precise type which contains another overload of `foo` (or an override with a more precise result type), meaning that the member selected is not preserved by retyping (in practice our ReTyper will keep the original selection, but this still seems like a source of confusion since the meaning of the code is not apparent from the types the user sees).

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:93]: This could be a problem. But (1) it's not related to this issue.(2) I don't know how to solve it.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:93]: I think the change I'm proposing together with removing the recursion on the upper bound in `goParam` would solve that issue, but I agree this can be treated separately from this PR.

**Review by smarter — APPROVED** [review]
