### PR TITLE
Fixes #8287 by simplifying the pickled folded constant presentation via homogenize

### LINKED ISSUE #8287: Primitive type operations pickling test fail
## minimized code

```Scala
import scala.compiletime.ops.int._
import scala.annotation.infix

object Test {
  class Vec[S <: Int] {
    @infix def concat [RS <: Int](that : Vec[RS]) : Vec[S + RS] = new Vec[S + RS]
  }

  val v1 = new Vec[1]
  val v2 = new Vec[2]
  val v3 : Vec[3] = v1 concat v2
  val v3a = v1 concat v2
  val v3b : Vec[3] = v3a
}
```

## Compilation output
This is the diff result between `before-pickling.txt` and `after-pickling.txt`
```scala
169c169
<         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(1 : scala.Int) + (2 : scala.Int)])>@
---
>         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(3 : scala.Int)])>@
172c172
<         Test.Vec[(1 : scala.Int) + (2 : scala.Int)]
---
>         Test.Vec[(3 : scala.Int)]
183c183
<         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(1 : scala.Int) + (2 : scala.Int)])>@
---
>         [(2 : scala.Int)]:((that: Test.Vec[(2 : scala.Int)]): Test.Vec[(3 : scala.Int)])>@
186c186
<         Test.Vec[(1 : scala.Int) + (2 : scala.Int)]
---
>         Test.Vec[(3 : scala.Int)]
```
## expectation
Test should succeed. 

cc @OlivierBlanvillain @MaximeKjaer

### PR DESCRIPTION
**Pull request by soronpo**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala [hunk 1]
```diff
@@ -61,8 +61,9 @@ class PlainPrinter(_ctx: Context) extends Printer {
           homogenize(tp.info)
         case tp: LazyRef =>
           homogenize(tp.ref)
-        case AppliedType(tycon, args) =>
-          tycon.dealias.appliedTo(args)
+        case tp@AppliedType(tycon, args) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala]:
```suggestion
        case tp @ AppliedType(tycon, args) =>
```
