### PR TITLE
Compare span points in pathTo to determine best span

### LINKED ISSUE #22207: Incorrect positions / interactive path on mutiple variable declaration
## Compiler version
`3.5.0`

## Minimized code
```Scala
val xx, yy, zz = 1
```

## Output
```scala
[[syntax trees at end of                     typer]] // demo.scala
package <empty>@demo.scala<0..0> {
  final lazy module val demo$package: demo$package@demo.scala<0..0> =
    new demo$package@demo.scala<0..0>@demo.scala<0..0>@demo.scala<0..0>()@
      demo.scala<0..0>
  @demo.scala<0..0>
  final module class demo$package() extends Object@demo.scala<0..0>@
    demo.scala<0..0>()@demo.scala<0..0> {
    this: demo$package@demo.scala<0..0>.type@demo.scala<0..0> =>
    val xx: Int = 1@demo.scala<17..18>@demo.scala[0..4..18]
    val yy: Int = 1@demo.scala<17..18>@demo.scala[0..8..18]
    val zz: Int = 1@demo.scala<17..18>@demo.scala[0..12..18]
  }@demo.scala<0..18>
}@demo.scala<0..18>
```

## Problem
Start and end position for all definitions are the same. This leads to incorrect `Interactive.pathTo` for position on `xx` or `yy` definition -- head being `zz` definition.

## Expectation
I would either expect positions on multiple declaration to be solved as in Scala 2 ([though this is also buggy there](https://github.com/scala/bug/issues/13067)):
```
xx -- `4..18`
yy --`8..18`
zz -- `12..18`
```
or for `Interactive.pathTo` to account for that situation.

### PR DESCRIPTION
**Pull request by Florian3k**
Closes #22207

### CODE REVIEW

File: presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTermSuite.scala [hunk 1]
```diff
@@ -815,3 +815,30 @@ class HoverTermSuite extends BaseHoverSuite:
...
+      )
+
+  @Test def `multiple-valdefs-3` =
+      check(
+        """|object O {
+          |  val xx, yy, z@@z = 1
+          |}
+          |""".stripMargin,
+          "val zz: Int".hover
+      )
```
Comment (tgodzik) [inline presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTermSuite.scala]: Let's maybe add a test with a longer name like:
```scala
  @Test def `multiple-valdefs-3` =
      check(
        """|object O {
          |  val xx, thisIsAVeryLongNa@@me, zz = 1
          |}
          |""".stripMargin,
          "val thisIsAVeryLongName: Int".hover
      )
```

Comment (Florian3k) [reply presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTermSuite.scala]: Done
