### PR TITLE
Fix #8802: Use wildcards for result type approximation of implicits

### LINKED ISSUE #8802: Unable to infer type in presence of type constructors, generics, implicits parameters, and path-dependent types
(Sorry for the very vague name… I couldn’t figure out what is really specific to this issue)

## Minimized code

```Scala
trait Foo[A, B] {
  type Out
}

object Test {

  type Bar[A]

  def unit: Bar[Unit] = ???
  def product[A, B](fst: Bar[A], snd: Bar[B])(implicit foo: Foo[A, B]): Bar[foo.Out] = ???

  implicit def foo[A]: Foo[A, Unit] { type Out = A } = ???

  def check[A](bar: Bar[A])(a: A): Unit = {}

  check(product(unit, unit))(()) // error
}
```

## Output

```scala
-- [E007] Type Mismatch Error: try/i8802.scala:16:8 ----------------------------
16 |  check(product(unit, unit))(()) // error
   |        ^^^^^^^^^^^^^^^^^^^
   |        Found:    Test.Bar[Unit]
   |        Required: Test.Bar[(Foo[Unit, Unit] & Singleton)#Out]
-- [E007] Type Mismatch Error: try/i8802.scala:16:29 ---------------------------
16 |  check(product(unit, unit))(()) // error
   |                             ^^
   |                             Found:    Unit
   |                             Required: (Foo[Unit, Unit] & Singleton)#Out
2 errors found
```

It seems that the compiler doesn’t completely compute the type resulting from calling `product(unit, unit)`. It shows `Foo[Unit, Unit]#Out` instead of taking into account the fact that the actual implicit parameter `foo` had fixed the type `Out` to `Unit`.

## Expectation

The same code compiles with Scala 2. Is it possible to make it compile with Scala 3 as well?

## Workarounds

- Add explicit type instantiations:

~~~ diff
- check(product(unit, unit))(()) // error
+ check[Unit](product(unit, unit))(())
~~~

- Change the signature of `product` to use an additional type parameter instead of using a path-dependent type:

~~~ diff
- def product[A, B](fst: Bar[A], snd: Bar[B])(implicit foo: Foo[A, B]): Bar[foo.Out]
+ def product[A, B, O](fst: Bar[A], snd: Bar[B])(implicit foo: Foo[A, B] { type Out = O }): Bar[O]
~~~

### PR DESCRIPTION
**Pull request by odersky**
Use wildcards for result type approximation of dependent implicit methods.
In a situation like
```
  def f(using x: T): C[x.Out]
```
we need to go constrain the result type of `f` before doing the implicit
search for `T`. Previously we created a fresh type variable `param(1)` with
`T & Singleton` as upper bound. That works well for other uses of
result type approximation, but in this case, we miss constraining
`param(1)` from below by the result of the implicit search. So in the end
`param(1)` gets interpolated to its upper bound, which leads to problems.

One possible solution is to add the missing lower constraint for the dependent
type variable. But it's easier to just use a Wildcard type, which is what
this PR does.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala [hunk 1]
```diff
@@ -568,7 +569,7 @@ object ProtoTypes {
       case poly: PolyType =>
         normalize(constrained(poly).resultType, pt)
       case mt: MethodType =>
-        if (mt.isImplicitMethod) normalize(resultTypeApprox(mt), pt)
+        if (mt.isImplicitMethod) normalize(resultTypeApprox(mt, wildcardOnly = true), pt)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala:572]: The documentation above still says "if result type depends on implicit parameter, replace with fresh type dependent parameter."

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala [hunk 2]
```diff
@@ -536,14 +536,15 @@ object ProtoTypes {
   /** The result type of `mt`, where all references to parameters of `mt` are
    *  replaced by either wildcards (if typevarsMissContext) or TypeParamRefs.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala:537]: The "if typevarsMissContext" part of this comment is incomplete, it was also incomplete before given that we also check `tp.widenExpr.isValueTypeOrWildcard`, so perhaps the comment should just says less:
```suggestion
   *  replaced by either wildcards or TypeParamRefs.
```

**Comment by odersky** [comment]
Also fixes #8825
