### PR TITLE
Check New tree for ill-formed module instantiations

### LINKED ISSUE #17545: Macro can invoke constructor of a case object
## Compiler version

3.2.2, 3.3.0-RC6

## Minimized code
```scala
// InvokeConstructor.scala
//> using scala "3.3.0-RC6"

import scala.quoted.* 

object InvokeConstructor {
  inline def apply[A] = ${ constructorMacro[A] }

  def constructorMacro[A: Type](using Quotes) = {
    import quotes.reflect.*
    val tpe = TypeRepr.of[A]
    New(Inferred(tpe)).select(tpe.typeSymbol.primaryConstructor).appliedToArgs(Nil).asExprOf[A]
  }
}
```
**Variant 1** - a local case object, which doesn't result in a runtime failure but we actually get a new instance of a singleton
```scala
// usage.scala
@main def main = {
  case object Whatever

  val whatever: Whatever.type = InvokeConstructor[Whatever.type]
  println(whatever eq Whatever) // evaluates to false
  println(whatever == Whatever) // evaluates to false
}
```

**Variant 2** - a toplevel case object, this results in a runtime error
```scala
case object Whatever

/*
fails at runtime:
Exception in thread "main" java.lang.IllegalAccessError: class Usage$package$ tried to access private method 'void Whatever$.<init>()' (Usage$package$ and Whatever$ are in unnamed module of loader 'app')
        at Usage$package$.main(Usage.scala:5)
        at main.main(Usage.scala:3)
*/
@main def main = {

  val whatever: Whatever.type = InvokeConstructor[Whatever.type]
}
```

## Expectation
Compilation failure.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #17545

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 1]
```diff
@@ -495,6 +495,18 @@ object TreeChecker {
       assert(tree.qual.typeOpt.isInstanceOf[ThisType], i"expect prefix of Super to be This, actual = ${tree.qual}")
       super.typedSuper(tree, pt)
 
+    override def typedNew(tree: untpd.New, pt: Type)(using Context): Tree =
+      val tree1 = super.typedNew(tree, pt).asInstanceOf[tpd.New]
+      val sym = tree1.tpe.typeSymbol
+      if !(ctx.phase <= postTyperPhase) then
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:501]: this would be clearer as:
```suggestion
      if ctx.phase > postTyperPhase then
```
but could you add a comment explaining why this check is needed?

**Review by smarter — APPROVED** [review]
