### PR TITLE
Refine `hasCommonParent` criterion in OverridingPairs

### LINKED ISSUE #11719: Missing override check leads to ClassCastException
```scala
class Base
class Sub extends Base

trait A[+T] {
  def get(f: T => Boolean): Unit = {}
}

trait B extends A[Base] {
  override def get(f: Base => Boolean): Unit = f(new Base)
}

class C extends B with A[Sub]

object Test {
  def main(args: Array[String]): Unit = {
    val c = new C
    c.get((x: Sub) => true) // ClassCastException: Base cannot be cast to Sub
  }
}
```
In Scala 2 this is rejected (at erasure):
```scala
error: name clash between inherited members:
def get(f: Sub => Boolean): Unit in trait A and
override def get(f: Base => Boolean): Unit in trait B
have same type after erasure: (f: Function1): Unit
class C extends B with A[Sub]
      ^
1 error
```

And a simplified example is rejected by dotty at RefChecks in checkMemberTypesOK:
```scala
class Base
class Sub extends Base

trait A[+T] {
  def get: T = ???
}

trait B extends A[Base] {
  override def get: Base = new Base
}

class C extends B with A[Sub]
```
```scala
-- Error: try/dg3.scala:12:6 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
12 |class C extends B with A[Sub]
   |      ^
   |      method get in trait B is not a legal implementation of `get` in class C
   |        its type             => Base
   |        does not conform to  => Sub
```

The difference is that all parameter-less overrides are considered matching denotations (since they can never be valid overloads), but in the original example, from the point of view of C, the `get` in `A` and the one in `B` are overloads, since they don't have matching signatures as seen from C.

Hopefully this is fixable by tweaking the checkMemberTypesOK logic but I don't have the bandwidth to investigate this for now, do you think you could take a look @odersky ?

### PR DESCRIPTION
**Pull request by odersky**
Fixes #11719

`hasCommonParent` is used to avoid re-visiting overriding pairs that were
already accounted for in a parent. But that only works if the base types
of the classes forming an overriding pair are the same for the parent and
the class itself. Otherwise we might miss an overriding relationship.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ElimErasedValueType.scala [hunk 1]
```diff
@@ -80,6 +81,10 @@ class ElimErasedValueType extends MiniPhase with InfoTransformer { thisPhase =>
   private def checkNoClashes(root: Symbol)(using Context) = {
     val opc = atPhase(thisPhase) {
       new OverridingPairs.Cursor(root) {
+        override def isSubParent(parent: Symbol, bc: Symbol)(using Context) =
+          // Need to compute suparents before erasure to not filter out parents
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/ElimErasedValueType.scala:85]:
```suggestion
          // Need to compute subparents before erasure to not filter out parents
```

File: compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala [hunk 2]
```diff
@@ -64,11 +64,25 @@ object OverridingPairs {
...
+     *  @pre `parent` is a parent class of `base` and it derives from `bc`.
+     *  @return true if the `bc`-basetype of the parent's type is the same as
+     *               the `bc`-basetype of base. In that case, overriding checks
+     *               relative to `parent` already subsume overriding checks
+     *               relative to `base`. See neg/11719a.scala for where this makes
+     *               a difference.
+     */
+    protected def isSubParent(parent: Symbol, bc: Symbol)(using Context) =
+      bc.typeParams.isEmpty
+      || self.baseType(parent).baseType(bc) == self.baseType(bc)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala:77]: While this fixes the immediate problem, it's worth noting that Scala 2 completely removed the subparent logic in https://github.com/scala/scala/pull/7439/commits/cc55bd92dd53fe2eaff29943a3479782bda2ddf2 because:
> subclassing on traits does not imply one's linearisation is contained in the other's

The testcase from that commit is:
```scala
trait IO {
  def c(x: Int): Int = ???
}
trait SO extends IO {
  override final def c(x: Int): Int = ???
}
trait SOIO extends IO {
  override def c(x: Int): Int = ???
}
trait SOSO extends SOIO with SO
abstract class AS extends SO
class L extends AS with SOSO // error expected: c definined in SOIO overrides final method c in SO 
```
Which currently compiles in Dotty, even though we end up overriding a final def with a non-final def. We already have an issue open to keep track of this (https://github.com/lampepfl/dotty/issues/7551) so we don't necessarily need to handle this now.

**Review by smarter — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala:77]: OK. We should evaluate the performance implications of subParents before removing them. Also bridge generation currently relies on the check being present, otherwise you would get duplicate bridges.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala:77]: > Also bridge generation currently relies on the check being present, otherwise you would get duplicate bridges.

Indeed, but Scala 2 had the same issue so https://github.com/scala/scala/commit/cc55bd92dd53fe2eaff29943a3479782bda2ddf2 also takes care of that:
```scala
// Skip nextEntry if the (non-trait) class in `parents` is a subclass of the owners of both low and high.
// this means we'll come back to this entry when we consider `nonTraitParent`, and the linearisation order will be the same
// (this only works for non-trait classes, since subclassing on traits does not imply one's linearisation is contained in the other's)
// This is not just an optimization -- bridge generation relies on visiting each such class only once.
if (!isMatch || (nonTraitParent.isNonBottomSubClass(low.owner) && nonTraitParent.isNonBottomSubClass(high.owner)))
```
