### PR TITLE
Scaladoc: add extension suffixes and fqName to scaladoc searchbar

### LINKED ISSUE #14486: Scaladoc: multiple entries in searchbar for the same function
## Compiler version

Nightly

## Reproduction steps

1. Open https://dotty.epfl.ch/api/index.html
2. Open searchbar
3. Search for `length`

## Output

image

## Expectation

Only one entry for `IArray.length`

### PR DESCRIPTION
**Pull request by jchyb**
Suffixes in the form of italic _extension on (...)_ for extension defs will allow to separate semantically different methods, which previously would have been displayed as the same in searchbar.
File-based location was also replaced with fully qualified name based, in an effort to improve overall readability.
Fixes #14486

Can be viewed on: https://scala3doc.virtuslab.com/pr-fix-searchbar-repeating/scala3/index.html

Zrzut ekranu 2022-04-27 o 11 59 36

### CODE REVIEW

File: scaladoc-js/main/src/searchbar/SearchbarComponent.scala [hunk 1]
```diff
@@ -23,9 +23,16 @@ class SearchbarComponent(engine: SearchbarEngine, inkuireEngine: InkuireJSSearch
...
+      val extensionTargetMessage = if (p.extensionTarget.isEmpty()) {
+        ""
+      } else {
+        " extension on " + p.extensionTarget
+      }
+
       div(cls := "scaladoc-searchbar-row monospace", "result" := "")(
         a(href := location)(
           p.fullName,
+          span(cls := "italic")(extensionTargetMessage),
```
Comment (pikinier20) [inline scaladoc-js/main/src/searchbar/SearchbarComponent.scala:35]: Could be just:
```
span(i(extensionTargetMessage))
```
Then, you wouldn't need to add CSS rule to make the text italic.

**Review by pikinier20 — APPROVED** [review]
Overally, it looks very good to me
