### PR TITLE
Handle pickled forward references in pickled expressions

### LINKED ISSUE #16843: Pickler crash when binding typed pattern to name
## Compiler version

3.3.1-RC1-bin-20230204-a356581-NIGHTLY nad before

## Minimized code

```scala
import scala.quoted.*

case class Foo(x: Int)

inline def foo = ${ fooImpl }

def fooImpl(using Quotes) = 
  val tmp = '{
    1 match
      case x @ (y: Int) => 0
  }

  '{}
```

```scala
val x = foo
```

## Output (click arrow to expand)
<details>

```scala
error] ./MacroTest.scala:1:9: Exception occurred while executing macro expansion.
[error] java.lang.AssertionError: assertion failed: no symbol at Addr(13)
[error]         at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$OwnerTree.search$1(TreeUnpickler.scala:1623)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$OwnerTree.search$1(TreeUnpickler.scala:1629)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$OwnerTree.findOwner(TreeUnpickler.scala:1638)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.symbolAt(TreeUnpickler.scala:268)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readSymRef(TreeUnpickler.scala:261)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readSimpleType$1(TreeUnpickler.scala:423)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:464)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1387)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1449)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readCase(TreeUnpickler.scala:1502)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readCases$$anonfun$2(TreeUnpickler.scala:1493)
[error]         at dotty.tools.tasty.TastyReader.collectWhile(TastyReader.scala:137)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readCases(TreeUnpickler.scala:1494)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1337)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1449)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1314)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1449)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1166)
[error]         at dotty.tools.dotc.core.tasty.TreeUnpickler.unpickle(TreeUnpickler.scala:113)
[error]         at dotty.tools.dotc.core.tasty.DottyUnpickler.computeRootTrees(DottyUnpickler.scala:62)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees(tpd.scala:1287)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees$(tpd.scala:1276)
[error]         at dotty.tools.dotc.core.tasty.DottyUnpickler.rootTrees(DottyUnpickler.scala:44)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.tree(tpd.scala:1291)
[error]         at dotty.tools.dotc.ast.tpd$TreeProvider.tree$(tpd.scala:1276)
[error]         at dotty.tools.dotc.core.tasty.DottyUnpickler.tree(DottyUnpickler.scala:44)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.unpickle(PickledQuotes.scala:274)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:84)
[error]         at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3084)
[error]         at Macro$package$.fooImpl(Macro.scala:8)
[error] 
[error] val x = foo
[error]         ^^^
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**
To compute forward references it was assumed that the owner of that symbol can be found in the TASTy. This is not always the case with TASTy expressions of pickled quotes. The owner might be outside the quote, in this case the context already has the owner of the referenced symbol. These are local symbols defined at the top-level of the TASTy.

Fixes #16843

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala [hunk 1]
```diff
@@ -1620,8 +1620,9 @@ class TreeUnpickler(reader: TastyReader,
         try cs match {
           case ot :: cs1 =>
             if (ot.addr.index == addr.index) {
-              assert(current.exists, i"no symbol at $addr")
-              current
+              // If current does not exist it is beacause this is a pickled expression
+              // and the owner is located outside the expression (i.e. pickled quote).
+              current.orElse(ctx.owner)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala:1625]: This could hide bugs if we're not in fact in a pickled quote. I think it'd be clearer if we stored the quote owner instead. Something like:
```scala
/** If this is a pickled quote, the owner of the quote, otherwise NoSymbol. */
private var rootOwner: Symbol = NoSymbol

...

def unpickle(mode: UnpickleMode)(using Context): List[Tree] = {
  if mode != UnpickleMode.TopLevel then rootOwner = ctx.owner
  ...
}  
...
class OwnerTree(val addr: Addr, tag: Int, reader: TreeReader, val end: Addr) {
  ...
    try search(children, rootOwner)
  ...
}
```

**Review by smarter — CHANGES_REQUESTED** [review]
/cc @sjrd since this seems like it will affect tasty-query

**Review by smarter — APPROVED** [review]
