### PR TITLE
Refine overriding pairs in RefChecks

### LINKED ISSUE #12828: Overload that differs only in parameter type is mistaken as override, crashes with a ClassCastException at runtime
## Compiler version

3.0.1-RC1

## Minimized code

```Scala
trait Foo[A]:
  def foo(x: A): Unit

trait Bar[A] extends Foo[A]:
  def foo(x: A & String): Unit = println(x.toUpperCase)

object Baz extends Bar[Int]

@main def run() = Baz.foo(42)
```

## Output

The code compiles, but fails at run-time:

> java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
>	at Baz$.foo(main.scala:7)

## Expectation

The code should not compile. It should produce the following error:

> object creation impossible, since def foo(x: A): Unit in trait Foo is not defined 
> (Note that
>  parameter A in def foo(x: A): Unit in trait Foo does not match
>  parameter A & String in def foo(x: A & String): Unit in trait Bar
>  type A & String is a subtype of trait A, but method parameter types must match exactly.)

Note: adding the `override` keyword raises a compile-time error:

~~~ scala
trait Foo[A]:
  def foo(x: A): Unit

trait Bar[A] extends Foo[A]:
  override def foo(x: A & String): Unit = println(x.toUpperCase)
//                    ^^^^^^^^^^
// method foo has a different signature than the overridden declaration
~~~

### PR DESCRIPTION
**Pull request by odersky**
We now exclude a pair of overriding / overridden symbols that
have a common subclass parent of the base class only under the
additional condition that their signatures also match when seen
as members of the parent class.

#12828 shows a case where this matters:
```scala
trait Foo[A]:
  def foo(x: A): Unit

trait Bar[A] extends Foo[A]:
  def foo(x: A & String): Unit = println(x.toUpperCase)

object Baz extends Bar[Int] // error overriding foo: incompatible type

@main def run() = Baz.foo(42)
```
When checking `Baz`, there is a common subclass parent (namely `Bar`),
but the signatures of the two `foo` definitions as seen from `Bar` are
different, so we cannot assume that the pair has already been checked.

Fixes #12828

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by smarter** [comment]
Before complicating OverridingPairs more I think it's worth considering how what we're doing differ from Scala 2 which is known to be more correct than us (#7551), namely we know that https://github.com/lampepfl/dotty/blob/master/tests/run/i5094.scala is compiling when it shouldn't because the final method SO is override by the method in SOIO. This was fixed in Scala 2 by https://github.com/scala/scala/pull/7439/commits/cc55bd92dd53fe2eaff29943a3479782bda2ddf2 which says:
> Subclassing on traits does not imply suffixing for their linearisations 

And indeed if we change `OverridingPairs#isSubParent` to also check `!parent.is(Trait)`, then i5094.scala stops compiling, and if we also disable the `if (member.owner != clazz) { ...` block in RefChecks#checkOverride, #12828 is also fixed (and the issue doesn't reappear when replacing the traits by abstract classes). By contrast the fix in this PR doesn't stop i5094.scala from compiling, so it's not clear to me it's the right way forward.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
@smarter Unfortunately, the situation between Scala 2 and 3 is not comparable since Scala 3 is signature based and Scala 2 isn't. So the algorithms are different. The problem with trait ordering in linearization can be fixed easily with another test in OverridingPairs. 

But it turns out that the duplicate checks in `checkAllOverride` that looked redundant are not. They re-introduce the problem. Specifically,  this one:
```scala
      // return if we already checked this combination elsewhere
      if (member.owner != clazz) {
        def deferredCheck = member.is(Deferred) || !other.is(Deferred)
        def subOther(s: Symbol) = s derivesFrom other.owner
        def subMember(s: Symbol) = s derivesFrom member.owner

        if (subOther(member.owner) && deferredCheck)
          //Console.println(infoString(member) + " shadows1 " + infoString(other) " in " + clazz);//DEBUG
          return
```
Here, if we make `foo` in `Foo` concrete, the condition kicks in and the pair is discarded even though the signatures are different. Hence, the test compiles and we get a crash at runtime.

But if Ii remove the early returnn in `checkAllOverrides`, stdlib213 does not compile anymore. It complains as follows:
```scala
[error] -- Error: /__w/dotty/dotty/community-build/community-projects/stdLib213/src/library/scala/collection/MapView.scala:19:6 
[error] 19 |trait MapView[K, +V]
[error]    |      ^
[error]    |trait MapView inherits conflicting members:
[error]    |  method concat in trait IterableOps of type [B >: (K, V)](suffix: IterableOnce[B]): scala.collection.View[B]  and
[error]    |  method concat in trait MapOps of type [V2 >: V](suffix: IterableOnce[(K, V2)]): scala.collection.View[(K, V2)]
[error]    |(Note: this can be resolved by declaring an override in trait MapView.);
[error]    |other members with override errors are:: method ++, method ++:
```
At first glance, this looks like a correct error, and might need to have to fix stdlib213.

**Comment by odersky** [comment]
Refchecks now decouples overriding from signature matching. A signature match is in essence a pre-check that two members might override, but if the two members are methods we also need to compare their parameter types. This has three consequences:

 1. Before emitting an override error, test that parameter types match. If not, we have a false override and no error should be reported.
 2. Before emitting a bridge, do the same test and omit the generation if the test fails
 3. When checking whether a class is fully implemented, check that any implementation also agrees completely in its parameter types.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
That was quite a rabbit hole.

File: compiler/src/dotty/tools/dotc/core/Denotations.scala [hunk 1]
```diff
@@ -1021,7 +1021,7 @@ object Denotations {
      *  erasure (see i8615b, i9109b), Erasure takes care of adding any necessary
      *  bridge to make this work at runtime.
      */
-    def matchesLoosely(other: SingleDenotation)(using Context): Boolean =
+    def matchesLoosely(other: SingleDenotation, alwaysCompareParams: Boolean = false)(using Context): Boolean =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Denotations.scala:1024]: I think this should be called `alwaysCompareTypes` since Type#matches can also check the result type if we're after erasure.

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala [hunk 2]
```diff
@@ -323,6 +323,14 @@ object RefChecks {
             overrideErrorMsg("no longer has compatible type"),
             (if (member.owner == clazz) member else clazz).srcPos))
 
+      /** Do types of term members `member` and `other` as seen from `self` match?
+       *  If not we treat them as not a real override and don't issue certain
+       *  error messages. Also, bridges are not generated in this case.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/RefChecks.scala:328]: Why not skip all error messages instead of only certain one? Currently it looks like we still emit overrideAccessError and overrideTargetNameError but if these methods are not true override then I don't see why we need to.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala:328]: In fact it's just the comment that is wrong. All errors go to overrideError which does the check whether it's a true override.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: > All errors go to overrideError which does the check whether it's a true override

In that case, why not immediately check for false overrides at the top of checkOverride before doing any of the checks?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala]: Because the false overrides check is expensive and override checks are common while override errors are rare.

**Review by smarter — APPROVED** [review]
LGTM, great to see this on more solid footing!

File: tests/neg/i11828.check [hunk 3]
```diff
@@ -0,0 +1,8 @@
+-- Error: tests/neg/i12828.scala:7:7 -----------------------------------------------------------------------------------
```
Comment (julienrf) [inline tests/neg/i11828.check:1]: I think this file should be removed
