### PR TITLE
Fix #4060 by marking ghost symbols as unstable

### LINKED ISSUE #4060: Unsoundness due to `ghost`
Related to #50 #4042 #4031.

```scala
object App {
  def coerce[U, V](u: U): V = {
    trait X { type R >: U }
    trait Y { type R = V }

    class T[A <: X](ghost val a: A)(val value: a.R)

    object O { lazy val x : Y & X = ??? }

    val a = new T[Y & X](O.x)(u)
    a.value
  }

  def main(args: Array[String]): Unit = {
    val x: Int = coerce[String, Int]("a")
    println(x + 1)
  }
}

//////////////////////////////////////////////////////////////

Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
	at App$.main(HelloWorld.scala:15)
	at App.main(HelloWorld.scala)
```

### PR DESCRIPTION
**Pull request by Blaisorblade**
Closes #4060.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
test performance please

File: tests/pos/ghost-pathdep-1.scala [hunk 1]
```diff
@@ -1,19 +0,0 @@
-object Test {
-
-  fun1(new Bar)
-  fun2(new Bar)
-  fun3(new Bar)
-
-  def fun1[F >: Bar <: Foo](ghost f: F): f.X = null.asInstanceOf[f.X]
-  def fun2[F >: Bar <: Foo](ghost f: F)(ghost bar: f.B): f.B = null.asInstanceOf[f.B]
```
Comment (nicolasstucki) [inline tests/pos/ghost-pathdep-1.scala]: Make them neg tests. It is always good to make sure we do not have a regression.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 2]
```diff
@@ -600,7 +600,7 @@ object SymDenotations {
 
     /** Is this a denotation of a stable term (or an arbitrary type)? */
     final def isStable(implicit ctx: Context) =
-      isType || is(Stable) || !(is(UnstableValue) || info.isInstanceOf[ExprType])
+      isType || !is(Ghost) && (is(Stable) || !(is(UnstableValue) || info.isInstanceOf[ExprType]))
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: We should avoid marking the symbols as stable if they are ghost. We could assert that a symbol must at most one of those flags.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Because in some places we might ask if `sym.is(Stable)` which would say true for a symbol with Stable and Ghost flags.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/SymDenotations.scala]: Actually don't do this change

**Comment by Blaisorblade** [comment]
@nicolasstucki Good for you?
