### PR TITLE
Don't allow redefinition of core classes

### LINKED ISSUE #1688: crash on compilable code: assertion failed: Cannot create ClassBType for phantom type Lscala/Null
scalac compiles but dotc crashes.

$ cat abc.scala
```
package scala
sealed trait Null
```

$ dotc abc.scala
```
java.lang.AssertionError: assertion failed: Cannot create ClassBType for phantom type Lscala/Null;
	at scala.Predef$.assert(Predef.scala:165)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.checkInfoConsistency(BTypes.scala:620)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.info_$eq(BTypes.scala:607)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.scala$tools$nsc$backend$jvm$BTypesFromSymbols$$setClassInfo(BTypesFromSymbols.scala:142)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:63)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols$$anonfun$classBTypeFromSymbol$4.apply(BTypesFromSymbols.scala:57)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.classBTypeFromSymbol(BTypesFromSymbols.scala:57)
	at scala.tools.nsc.backend.jvm.BCodeHelpers$BCInnerClassGen$class.getClassBTypeAndRegisterInnerClass(BCodeHelpers.scala:243)
<snipped>
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #1688. Review by @felixmulder

### CODE REVIEW

File: tests/neg/i1688.scala [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package scala
+sealed trait Null  // error
+
+object Null  // error
+
+class AnyVal // error
```
Comment (felixmulder) [inline tests/neg/i1688.scala]: This gets through compilation and prints `5`:

```scala
object scala {
  trait Boolean {
    def x: Int
  }
}

object Test {
  def x: scala.Boolean = new scala.Boolean { val x = 5 }

  def main(args: Array[String]): Unit = println(x.x)
}
```

Not sure if the first object lands in `_root_` or "<empty>" ....

Comment (felixmulder) [inline tests/neg/i1688.scala]: Discussed in person - this is fine because reasons (where reasons == bootstrap)
