### PR TITLE
Fix #6048: set missing position in value class rewiring 

### LINKED ISSUE #6048: Macro expansion failed with missing positions
The macro system should have set default positions to all trees, however when compile ScalaTest, we encountered the following exception:

```
[error] ## Exception when compiling 511 sources to /Users/fliu/Documents/scalatest-upstream/scalatest.dotty/target/scala-0.14/classes
[error] assertion failed: position not set for org.scalactic.anyvals.PosZInt.+$extension3(SizeParam.this.minSize)(
[error]   org.scalactic.anyvals.PosZInt.widenToInt(SizeParam.this.sizeRange)
[error] ) # 2326942 of class dotty.tools.dotc.ast.Trees$Apply in /Users/fliu/Documents/dotty/library/src-bootstrapped/scala/tasty/reflect/utils/TreeUtils.scala
[error] dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
[error] dotty.tools.dotc.typer.Typer$.assertPositioned(Typer.scala:62)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2096)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2112)
[error] dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1246)
[error] dotty.tools.dotc.transform.Erasure$Typer.typedInlined(Erasure.scala:559)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2032)
```

These kind of errors will cause a lot of troubles to macro authors -- as there is no way to explain why it happens and how to avoid that.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #6048: set missing position in value class rewiring (thanks @nicolasstucki )

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala [hunk 1]
```diff
@@ -92,7 +92,7 @@ class VCInlineMethods extends MiniPhase with IdentityDenotTransformer {
       tree // The rewiring will be handled by a fully-applied parent node
     case _ =>
       if (isMethodWithExtension(tree.symbol))
-        rewire(tree).ensureConforms(tree.tpe)
+        rewire(tree).ensureConforms(tree.tpe).withSpan(tree.span)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: I would put the withSpan in the definition of rewire

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: Thanks @smarter . That was what @nicolasstucki and I initially did -- but soon we find it's not the right place due to the recursive nature of `rewire`.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: There is one branch of `rewire` which is not recursive (the last one), that branch should get the withSpan.

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: The problem is that we want to set the initial `tree.span`, instead of the `tree.span` from recursive calls.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: The issue there is that the `tree` is the tree of the qualifier which does not have the position of the full call (it does not cover the arguments). We could pass the position as a parameter to `rewire` instead.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: ah I see, one way to do that would be to change rewire to contain an inner method which is recursive, but I guess it's not very important since it's only used once anyway.

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/VCInlineMethods.scala]: Or we could pass the `span` as an extra parameter.
