### PR TITLE
Fix #3460: Fix semicolon insertion confusion after enum case

### LINKED ISSUE #3460: Syntax error when putting `def` in enum object after simple `case`
This doesn't compile:
```scala
enum class Ducks

object Ducks {
  case Dewey

  def wooohoo: Int = 1
}
```
```scala
-- [E039] Syntax Error: enumo.scala:6:6 ------------------------------------
6 |  def woohoo: Int = 1
  |      ^^^^^^
  |      ';' expected, but identifier found
```
This can be worked around by writing `case Dewey;` or `case Dewey extends Ducks`.

### PR DESCRIPTION
**Pull request by odersky**
After seeing an enum case, the Scanner thought it is in a pattern, and
therefore does not do semicolon insertion on newlines. We now get it
out of that mode by pretending to be passed the `=>`.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -2060,6 +2060,7 @@ object Parsers {
         typeDefOrDcl(start, posMods(start, mods))
       case CASE =>
         enumCase(start, mods)
+          .reporting(t => i"case $t, current = ${in.show} / ${in.sepRegions}%, %")
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: Stray debug statement.

**Comment by allanrenucci** [comment]
Also fixes #2906
