### PR TITLE
Fix generic signatures for mixin forwarders conflicting type parameter names

### LINKED ISSUE #24134: Regression for java compatibility in multiple `akka` / `pekko` projects
Based on the OpenCB failures found in following projects: 
- `apache/pekko-http` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/18235787374/job/51930174633 )
- `akka/akka-http` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/18235787374/job/51930174513) 
-  `apache/pekko-connectors` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/18235787374/job/51930174627) 
- `akka/akka` 
- `apache/pekko` 
- `playframework/playframework`
- `lichess-org/playframework-lila`

## Compiler version
Last good release: 3.8.0-RC1-bin-20250921-834e8e9-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250922-9bd7774-NIGHTLY
Bisect points to: f4330f0cd199355b7105eb9ac286cc07b1a6b62a  (most likely related to the new stdlib)

## Minimized code

```scala
final class Flow[In, Out]:
  def collect[T](pf: PartialFunction[Out, T]): Flow[In, T] = ???

object Flow:
  def create[T](): Flow[T, T] = ???
  
  
abstract class Message:
  def asTextMessage: TextMessage
  
abstract class TextMessage extends Message

abstract class JavaPartialFunction[A, B] extends PartialFunction[A, B]:
  @throws(classOf[Exception]) // required, compiles without annotation
  def apply(x: A, isCheck: Boolean): B
  
  final def isDefinedAt(x: A): Boolean = ???
  final override def apply(x: A): B = ???
  final override def applyOrElse[A1 <: A, B1 >: B](x: A1, default: A1 => B1): B1 = ???
```

```java
public class JavaTestServer {
  public static Flow<Message, Message> greeter() {
    return Flow.<Message>create()
        .collect(
            new JavaPartialFunction<Message, Message>() {
              @Override
              public Message apply(Message msg, boolean isCheck) throws Exception {
                if (isCheck)  throw new RuntimeException(); 
                else return handleTextMessage(msg.asTextMessage());
              }
            });
  }

  public static TextMessage handleTextMessage(TextMessage msg) {
    return null;
  }
}
```

## Output

```scala
Compiling project (Scala 3.8.0-RC1-bin-20251004-9f70200-NIGHTLY, JVM (21))
[error] ./JavaTestServer.java:5:57
[error]  error: name clash: compose(scala.Function1<A#1,Message>) in Function1 and compose(scala.Function1<A#2,A#2>) in JavaPartialFunction have the same erasure, yet neither overrides the other
[error]             new JavaPartialFunction<Message, Message>() {
[error]                                                         ^
Warning: javac exited with exit code 1
```

scala-cli trimmed the output, here's the full, original output: 
```scala 
[error] /build/repo/http-core/src/test/java/org/apache/pekko/http/JavaTestServer.java:69:57: <R>compose(scala.PartialFunction<R,T1>) in scala.runtime.AbstractPartialFunction cannot implement <R>compose(scala.PartialFunction<R,A>) in scala.PartialFunction
[error]   return type scala.PartialFunction<R,R> is not compatible with scala.PartialFunction<R,org.apache.pekko.http.javadsl.model.ws.Message>
[error] {
[error]               @Override
[error]               public Message apply(Message msg, boolean isCheck) throws Exception {
[error]                 if (isCheck)
[error]                   if (msg.isText()) return null;
[error]                   else throw noMatch();
[error]                 else return handleTextMessage(msg.asTextMessage());
[error]               }
[error]             }
[error]             
```

## Notes 
Original code refered to `scala.runtime.AbstractPartialFunction` (which is unsafe) but the same error can be reproduced when refering to public `scala.PartialFunction` 

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by tanishiking**
Fixes #24134

https://github.com/scala/scala3/commit/f99dba239f9f876ab62cd8d870e3e56e1ed7a5d7 started emitting Java generic signature for mixin forwarders.

However, when generating Java generic signatures for mixin forwarders, method-level type parameters could shadow class-level type parameters with the same name.

For example, when `JavaPartialFunction[A, B]` implements `PartialFunction1[A, B]`,

```scala
trait Function1[-T1, +R]:
  def compose[A](g: A => T1): A => R = ???

trait PartialFunction[-A, +B] extends Function1[A, B]:
  def compose[R](k: PartialFunction[R, A]): PartialFunction[R, B] = ???

abstract class JavaPartialFunction[A, B] extends PartialFunction[A, B]
```

the generated mixin forwarder for `compose` in Function1 was like:

```java
public abstract class JavaPartialFunction<A, B> implements scala.PartialFunction<A, B> {
  public <A> scala.Function1<A, B> compose(scala.Function1<A, A>);
```

which is obviously incorrect, the type parameter `A` of `compose[A]` is shadowed by the `A` in `JavaPartialFunction<A, B>`.

The `compose`'s type parameter should use an unique name like:

```java
public abstract class JavaPartialFunction<A, B> implements scala.PartialFunction<A, B> {
  public <T> scala.Function1<T, B> compose(scala.Function1<T, A>);
```

This commit fix the problem by
- Tracks class-level type parameter names when generating method signatures
- Renames conflicting method-level type parameters (A → A1, A2, etc.)

### CODE REVIEW

**Comment by hamzaremmal** [comment]
Do we know yet why the name changed in the first place?

**Comment by tanishiking** [comment]
I'll check that later today

**Comment by hamzaremmal** [comment]
Alright, thanks @tanishiking.

**Comment by tanishiking** [comment]
I confirmed that 9bd7774 already have this issue. Ever since generic signature generation for mixin forwarders was introduced in #23942, it has been producing signatures with name clashes in these cases.

---


The problem is that the member type stored in `mixinForwarderGenericInfos` is `def compose[A](g: A => T1): A => R = ...` (since `Future1` defines it that way). And `GenericSignature`  uses the signature `A` as-is, without considering name shadowing in the subclass.
https://github.com/scala/scala3/blob/9aa08e272988a23fb7c42ae73598be2e71fc799f/compiler/src/dotty/tools/dotc/transform/Mixin.scala#L323-L335

**Comment by tanishiking** [comment]
Some CI checks have failed, but they are unrelated to this change:

- `tests/neg-custom-args/captures/consume-tvar-bound.scala` and `tests/pos-custom-args/captures/i24543.scala` failed in `CompilationTest`, but these failures also occur in `main` as well. Unrealted to this change.
- Community-build failed on `requests`. This is a flaky test; I have submitted a fix to `requests-scala`: https://github.com/com-lihaoyi/requests-scala/pull/213

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -41,9 +41,36 @@ object GenericSignatures {
...
+    // names which are not valid Java identifiers (see git history of this method).
+    def sanitizeName(name: Name): String = name.mangledString
+
     val builder = new StringBuilder(64)
     val isTraitSignature = sym0.enclosingClass.is(Trait)
 
+    // Collect class-level type parameter names to avoid conflicts with method-level type parameters
+    val usedNames = collection.mutable.Set.empty[String]
+    if(sym0.is(Method)) {
+      sym0.enclosingClass.typeParams.foreach { tp =>
```
Comment (hamzaremmal) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:55]: Is this enough? We should get the type parameters of all the enclosing classes.
The core of this issue has to do with substitution and the fact that we convert to String. I could substitute the enclosing of the enclosing class type parameters by something that will create conflicts (from a String point of view).

I would have suggested a more robust algorithm where we do a first pass to go over all the types referred to in the Signature and disambiguate if they have a different id but the same name (as a String).

Comment (tanishiking) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala:55]: > Is this enough? We should get the type parameters of all the enclosing classes.

Ouch, you're right. For example,

```scala
class Container[A]:
  abstract class JavaPartialFunction[B] extends PartialFunction[A, B]:
```

Still have a generic signature attribute having a name clash.

```java
public abstract class Container$JavaPartialFunction<B> implements scala.PartialFunction<A, B> {
  // ...
  public <A> scala.Function1<A, B> compose(scala.Function1<A, A>);
```

---

> The core of this issue has to do with substitution and the fact that we convert to String. I could substitute the enclosing of the enclosing class type parameters by something that will create conflicts (from a String point of view).
> I would have suggested a more robust algorithm where we do a first pass to go over all the types referred to in the Signature and disambiguate if they have a different id but the same name (as a String).

IIUC, that's what this PR does (?), except it collects only a direct parent's type parameters though.
Do you mean, use more "robust" data structure than String for detect name shadowing? (but I feel like String is enough for detecting conflict at a String level in the end).

Anyway, I'll open the issue, and make it work for nested classes.
