### PR TITLE
Fixes #6626. Pass sym.name to sanitizeName instead of sym.name.asSimpleName

### LINKED ISSUE #6626: Compiler crash: is not a simple name while compiling
```scala
class Test[T1] {
  class A[T2]

  object B  {
     def m(): A[B.type] = ???
  }
}
```
```scala
java.lang.UnsupportedOperationException: B[ModuleClass] is not a simple name while compiling tests/pos/ranks.scala
Exception in thread "main" java.lang.UnsupportedOperationException: B[ModuleClass] is not a simple name
        at dotty.tools.dotc.core.Names$DerivedName.asSimpleName(Names.scala:474)
        at dotty.tools.dotc.core.Names$DerivedName.asSimpleName(Names.scala:474)
        at dotty.tools.dotc.core.Names$TypeName.asSimpleName(Names.scala:441)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$2(GenericSignatures.scala:167)
        at dotty.tools.dotc.transform.GenericSignatures$.jsig$1(GenericSignatures.scala:228)
        at dotty.tools.dotc.transform.GenericSignatures$.boxedSig$1(GenericSignatures.scala:64)
        at dotty.tools.dotc.transform.GenericSignatures$.argSig$1(GenericSignatures.scala:145)
        at dotty.tools.dotc.transform.GenericSignatures$.classSig$1$$anonfun$1(GenericSignatures.scala:174)
```

scalac passes

### PR DESCRIPTION
**Pull request by ashwinbhaskar**
`asSimpleName` method on `DerivedName` is implemented to throw `UnspportedOperationException`. The class `GenericSignatures`'s method `classSig` calls `asSimpleName` on instances of `Name` without checking on the actual type (`DerivedName` extends `TermName` which extends `Name`). 
~~A check has been added to refrain calling `asSimpleName` if the type is `DerivedName`. ~~
As @smarter suggested, refrained from calling `asSimpleName` for all the cases because `mangledString` takes care of giving the name of the class in byte code and it is already being called by `sanitizeName`.

### CODE REVIEW

**Comment by ashwinbhaskar** [comment]
> Line 170: should be "name.asSimpleName" instead of "sym.name.asSimpleName".
> PS. Coding style: remove space after "Unit" (line 167) and space before ":" (4 times).

done

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -161,7 +163,14 @@ object GenericSignatures {
 
             // TODO revisit this. Does it align with javac for code that can be expressed in both languages?
             val delimiter = if (builder.charAt(builder.length() - 1) == '>') '.' else '$'
-            builder.append(delimiter).append(sanitizeName(sym.name.asSimpleName))
+
+            @tailrec def appendIfNotDerivedName(name: Name): Unit = name match {
+              case _: DerivedName => //do nothing
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: This will generate an invalid signature. The point of this code is to generate a Java generic signature for the benefit of java code compiling against scala code, for example if I have a method that returns a `List[String]`, the Java bytecode signature will just be:
```java
()Lscala/collection/immutable/List;
```
since Java bytecode doesn't know anything about generics. This will work, but it's annoying to use from Java, so for the sole benefit of javac, we also generate a generic signature:
```java
()Lscala/collection/immutable/List<Ljava/lang/String;>;
```
(you can see this signature by running `javap -p` on a .class file)
This lets javac know that we're returning a List of String and not a List of anything else.

Anyway, in #6626, the problematic method is:
```scala
def m(): A[B.type] = ???
```
The generic signature for this method should contain `B$` since that's the class that corresponds to the object `B`. The problem is that the name of `B` is a derived name (the name of an object name is always a derived name based on the name of the corresponding class), so calling `asSimpleName` will lead to a crash. But the fix is easy: we're interested in the name of the class in bytecode, which we can obtain by calling `mangledString`, it turns out that `sanitizeName` already calls `mangledString`, so I think we can just remove `.asSimpleName` from the original name and have it work.

Comment (ashwinbhaskar) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: ah okay

Comment (ashwinbhaskar) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: that was . good explanation. Can we document this somewhere?

**Comment by ashwinbhaskar** [comment]
> This PR is missing a test.

added test

**Comment by ashwinbhaskar** [comment]
@smarter can this be merged now?

**Comment by smarter** [comment]
If you look at other tests in generic-java-signatures like https://github.com/lampepfl/dotty/blob/master/tests/generic-java-signatures/andTypes.scala you'll see that they have a `main` method which prints the generic type signature of members, the output of this main method must match the corresponding check file https://github.com/lampepfl/dotty/blob/master/tests/generic-java-signatures/andTypes.check. Your test should be enhanced to contain a similar main method (you can just copy paste the one from andTypes.scala) and a check file to make sure that we output the correct signature for `a`
