### PR TITLE
Move quote tagging to Staging

### LINKED ISSUE #7521: Compiler crash with type annotations in quotes
## minimized code

```Scala
import scala.quoted._
import scala.annotation.StaticAnnotation

object Test {
  inline def quote[T]: Unit = ${ quoteImpl[T] }
  def quoteImpl[T: Type](given qctx: QuoteContext): Expr[Unit] = '{
     class Annot extends StaticAnnotation
     var test: T @Annot = ???
  }
}
```

note: annotation is put inside the quote to avoid bug #7519  

<details>
<summary>Stack trace</summary>

```scala
Fatal compiler crash when compiling: tests/run-macros/test:
assertion failed
dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:620)
dotty.tools.dotc.typer.Typer.assignType(Typer.scala:83)
dotty.tools.dotc.ast.tpd$TypedTreeCopier.Annotated(tpd.scala:698)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1338)
dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:127)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1330)
dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:127)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1350)
scala.collection.immutable.List.mapConserve(List.scala:444)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1350)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformSub(Trees.scala:1354)
dotty.tools.dotc.ast.TreeTypeMap.transformDefs(TreeTypeMap.scala:136)
dotty.tools.dotc.ast.TreeTypeMap.transform(TreeTypeMap.scala:106)
dotty.tools.dotc.ast.TreeTypeMap.apply(TreeTypeMap.scala:148)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.addTags(ReifyQuotes.scala:165)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.splitQuote(ReifyQuotes.scala:369)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transformQuotation(ReifyQuotes.scala:189)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:93)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1254)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1260)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:33)
dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:39)
dotty.tools.dotc.ast.TreeMapWithImplicits.recur$1(TreeMapWithImplicits.scala:39)
dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:52)
dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1330)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1350)
scala.collection.immutable.List.mapConserve(List.scala:444)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1350)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1348)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1336)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.ReifyQuotes$QuoteReifier.transform(ReifyQuotes.scala:413)
dotty.tools.dotc.transform.ReifyQuotes$$anon$1.transform(ReifyQuotes.scala:93)
dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
dotty.tools.dotc.transform.ReifyQuotes.run(ReifyQuotes.scala:89)
dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
scala.collection.immutable.List.map(List.scala:219)
dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:162)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
dotty.tools.dotc.Run.runPhases$5(Run.scala:172)
dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:180)
dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
dotty.tools.dotc.Run.compileUnits(Run.scala:187)
dotty.tools.dotc.Run.compileSources(Run.scala:124)
dotty.tools.dotc.Run.compile(Run.scala:107)
dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
dotty.tools.dotc.Driver.process(Driver.scala:189)
dotty.tools.dotc.Driver.process(Driver.scala:158)
dotty.tools.vulpix.ParallelTesting$Test.compile(ParallelTesting.scala:479)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$2$$anonfun$1(ParallelTesting.scala:204)
scala.collection.immutable.List.map(List.scala:219)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$1(ParallelTesting.scala:204)
scala.util.Try$.apply(Try.scala:210)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.dotty$tools$vulpix$ParallelTesting$CompilationLogic$$compileTestSource(ParallelTesting.scala:205)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource$$anonfun$1(ParallelTesting.scala:248)
dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
dotty.tools.vulpix.ParallelTesting$Test.tryCompile(ParallelTesting.scala:420)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource(ParallelTesting.scala:251)
dotty.tools.vulpix.ParallelTesting$Test$LoggedRunnable.run(ParallelTesting.scala:319)
dotty.tools.vulpix.ParallelTesting$$anon$2.run(ParallelTesting.scala:246)
java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```
</details>

### LINKED ISSUE #8052: Compiler crash in tryHeal when accessing Expr of Mirror from wrong staging level
## minimized code

```Scala
import scala.deriving._
import scala.quoted._
import scala.quoted.matching._

object Macro2 {
  trait TC[T] {
    def test(): Unit
  }

  object TC {
    def derived[T: Type](ev: Expr[Mirror.Of[T]])(given qctx: QuoteContext): Expr[TC[T]] = '{
      new TC[T] {
        def encode(): Unit = $ev match {
          case '{ $m: Mirror.ProductOf[T] } => ???
        }
      }
    }
  }
}
```

<details>
<summary>Stack trace</summary>

```scala
*** error while checking tests/run-macros/i8007/Macro_2.scala after phase staging ***
java.lang.AssertionError: assertion failed: access to value evidence$1 from wrong staging level:
 - the definition is at level 0,
 - but the access is at level 1.
in Macro2$.TC$._$$anon.encode while compiling tests/run-macros/i8007/Macro_2.scala
Fatal compiler crash when compiling: tests/run-macros/i8007:
assertion failed: access to value evidence$1 from wrong staging level:
 - the definition is at level 0,
 - but the access is at level 1.
in Macro2$.TC$._$$anon.encode
dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
dotty.tools.dotc.transform.Staging$$anon$1.tryHeal(Staging.scala:53)
dotty.tools.dotc.transform.PCPCheckAndHeal.dotty$tools$dotc$transform$PCPCheckAndHeal$$checkSymLevel(PCPCheckAndHeal.scala:179)
dotty.tools.dotc.transform.PCPCheckAndHeal.checkLevel(PCPCheckAndHeal.scala:100)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.transform.PCPCheckAndHeal.transformSplice(PCPCheckAndHeal.scala:68)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:99)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
scala.collection.immutable.List.mapConserve(List.scala:444)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1299)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1265)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.transform.PCPCheckAndHeal.transformQuotation(PCPCheckAndHeal.scala:58)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:93)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:112)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:119)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
scala.collection.immutable.List.mapConserve(List.scala:444)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformSub(Trees.scala:1351)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1277)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
scala.collection.immutable.List.mapConserve(List.scala:444)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1271)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:105)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.transform.PCPCheckAndHeal.transformQuotation(PCPCheckAndHeal.scala:58)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:93)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1251)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1257)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1327)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:50)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1347)
scala.collection.immutable.List.mapConserve(List.scala:444)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1347)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1345)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1333)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:76)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:126)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
dotty.tools.dotc.transform.Staging.checkPostCondition(Staging.scala:61)
dotty.tools.dotc.transform.TreeChecker.dotty$tools$dotc$transform$TreeChecker$Checker$$_$typedUnadapted$$anonfun$1(TreeChecker.scala:321)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.immutable.List.foreach(List.scala:305)
dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:321)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:2243)
dotty.tools.dotc.typer.Typer.typed(Typer.scala:2255)
dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:289)
dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2363)
dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:124)
dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:97)
dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
scala.collection.immutable.List.map(List.scala:219)
dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:65)
dotty.tools.dotc.Run.compileUnits(Run.scala:192)
dotty.tools.dotc.Run.compileSources(Run.scala:129)
dotty.tools.dotc.Run.compile(Run.scala:112)
dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
dotty.tools.dotc.Driver.process(Driver.scala:189)
dotty.tools.dotc.Driver.process(Driver.scala:158)
dotty.tools.vulpix.ParallelTesting$Test.compile(ParallelTesting.scala:483)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$2$$anonfun$1(ParallelTesting.scala:208)
scala.collection.immutable.List.map(List.scala:223)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$1(ParallelTesting.scala:208)
scala.util.Try$.apply(Try.scala:210)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.dotty$tools$vulpix$ParallelTesting$CompilationLogic$$compileTestSource(ParallelTesting.scala:209)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource$$anonfun$1(ParallelTesting.scala:252)
dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
dotty.tools.vulpix.ParallelTesting$Test.tryCompile(ParallelTesting.scala:424)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource(ParallelTesting.scala:255)
dotty.tools.vulpix.ParallelTesting$Test$LoggedRunnable.run(ParallelTesting.scala:323)
dotty.tools.vulpix.ParallelTesting$$anon$2.run(ParallelTesting.scala:250)
java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```
</details>

### LINKED ISSUE #8302: Cannot heal types in nested type quotes
## minimized code

```Scala
import scala.quoted._
def foo[T](using qctx: QuoteContext, tpe: Type[T]): Expr[Any] =
  '{
    type TT = T
    val t = '[TT]
    ???
  }
```

## Crash output (click arrow to expand)
<details>

```scala
result after staging:
package <empty> {
  import scala.quoted._
  final lazy module val Foo$package: Foo$package$ = 
    new Foo$package$()
  final module class Foo$package$() extends Object(), _root_.scala.
    Serializable
   { this: Foo$package.type =>
    def foo[T >: Nothing <: Any](using qctx: quoted.QuoteContext, 
      tpe: quoted.Type[T]
    ): quoted.Expr[Any] = 
      '{
        {
          type TT = ${tpe}
          val t: quoted.Type[TT] = '[${tpe}]
          ???
        }
      }.apply(qctx)
  }
}


class dotty.tools.dotc.reporting.diagnostic.messages$Error: access to value tpe from wrong staging level:
 - the definition is at level 0,
 - but the access is at level 1. while compiling Foo.scala
Exception in thread "main" class dotty.tools.dotc.reporting.diagnostic.messages$Error at Foo.scala:<122..122>: access to value tpe from wrong staging level:
 - the definition is at level 0,
 - but the access is at level 1.
        at dotty.tools.dotc.reporting.Reporting.error(Reporter.scala:136)
        at dotty.tools.dotc.core.Contexts$Context.error(Contexts.scala:75)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.levelError(PCPCheckAndHeal.scala:237)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.dotty$tools$dotc$transform$PCPCheckAndHeal$$checkSymLevel(PCPCheckAndHeal.scala:183)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.checkLevel(PCPCheckAndHeal.scala:99)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:93)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1321)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1348)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1348)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1346)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1272)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:89)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:106)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transformQuotation(PCPCheckAndHeal.scala:59)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:94)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1252)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1258)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:117)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:97)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:51)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:58)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:108)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1328)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:51)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$2(Trees.scala:1348)
        at scala.collection.immutable.List.mapConserve(List.scala:444)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1348)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1346)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1334)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:101)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:77)
        at dotty.tools.dotc.transform.TreeMapWithStages.op$1(TreeMapWithStages.scala:118)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:120)
        at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:52)
        at dotty.tools.dotc.transform.Staging.checkPostCondition(Staging.scala:59)
        at dotty.tools.dotc.transform.TreeChecker.dotty$tools$dotc$transform$TreeChecker$Checker$$_$typedUnadapted$$anonfun$1(TreeChecker.scala:321)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:305)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:321)
        at dotty.tools.dotc.typer.Typer.op$1(Typer.scala:2247)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2256)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2259)
        at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:289)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2367)
        at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:124)
        at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:97)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:315)
        at scala.collection.immutable.List.map(List.scala:219)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:316)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:167)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:177)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:185)
        at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:192)
        at dotty.tools.dotc.Run.compileSources(Run.scala:129)
        at dotty.tools.dotc.Run.compile(Run.scala:112)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
        at dotty.tools.dotc.Driver.process(Driver.scala:189)
        at dotty.tools.dotc.Driver.process(Driver.scala:158)
        at dotty.tools.dotc.Driver.process(Driver.scala:170)
        at dotty.tools.dotc.Driver.main(Driver.scala:197)
        at dotty.tools.dotc.Main.main(Main.scala)
```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fix #8302, fix #8052 and fix #7521.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 1]
```diff
@@ -54,10 +55,26 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
 
   /** Transform quoted trees while maintaining phase correctness */
   override protected def transformQuotation(body: Tree, quote: Tree)(implicit ctx: Context): Tree = {
+    val taggedTypes = new PCPCheckAndHeal.QuoteTypeTags(quote.span)(using ctx)
+    given Context =
+      if level(ctx) == 0 then contextWithQuoteTypeTags(taggedTypes)(ctx)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Line 70 uses `level != 0`, is `level(ctx) == 0` the same as `level != 0`?

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 2]
```diff
@@ -54,10 +55,26 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
...
     if (ctx.property(InAnnotation).isDefined)
       ctx.error("Cannot have a quote in an annotation", quote.sourcePos)
-    val body1 = transform(body)(quoteContext)
-    super.transformQuotation(body1, quote)
+
+    val body1 =
+      transform(body)(quoteContext)
+
+    val body2 =
+      if level != 0 then body1
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Minor: it seems to me the logic will be more clear if we handle `level == 0` in one branch, and `level != 0` in another at the top-level.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 3]
```diff
@@ -52,7 +52,8 @@ object PickledQuotes {
   private def dealiasTypeTags(tp: Type)(implicit ctx: Context): Type = new TypeMap() {
     override def apply(tp: Type): Type = {
       val tp1 = tp match {
-        case tp: TypeRef if tp.typeSymbol.hasAnnotation(defn.InternalQuoted_QuoteTypeTagAnnot) => tp.dealias
+        case tp: TypeRef if tp.typeSymbol.hasAnnotation(defn.InternalQuoted_QuoteTypeTagAnnot) =>
+          tp.symbol.info.hiBound
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala]: why this change?

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 4]
```diff
@@ -73,7 +90,9 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
         // internal.Quoted.expr[F[T]](... T ...)  -->  internal.Quoted.expr[F[$t]](... T ...)
         val tp = checkType(splice.sourcePos).apply(splice.tpe.widenTermRefExpr)
         cpy.Apply(splice)(cpy.TypeApply(fun)(fun.fun, tpd.TypeTree(tp) :: Nil), body1 :: Nil)
-      case splice: Select => cpy.Select(splice)(body1, splice.name)
+      case splice: Select =>
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Do we need to check this is a type select? Or, it's implied by the case above?

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 5]
```diff
@@ -120,11 +139,14 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
...
-          tp
+          if level > 0 then getQuoteTypeTags.getTagRef(tp.prefix.asInstanceOf[TermRef])
+          else tp
         case tp: TypeRef if tp.symbol == defn.QuotedTypeClass.typeParams.head =>
-          // Adapt direct references to the type of the type parameter T of a quoted.Type[T].
-          // Replace it with a properly encoded type splice. This is the normal for expected for type splices.
-          tp.prefix.select(tpnme.splice)
+          if level > 0 then
+            // Adapt direct references to the type of the type parameter T of a quoted.Type[T].
+            // Replace it with a properly encoded type splice. This is the normal for expected for type splices.
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: typo: `the normal for` -> `the normal form`?

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Elsewhere it seems we only handle type tags `if level > 0`. Maybe add a doc to `transformQuotation`.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 6]
```diff
@@ -201,6 +223,7 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
             sym.isClass // reference to this in inline methods
           )
     case None =>
+      (sym.hasAnnotation(defn.InternalQuoted_QuoteTypeTagAnnot) && level > 0) ||
       sym.is(Package) || sym.owner.isStaticOwner || levelOK(sym.owner)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Minor performance tuning: switch the two lines?

Maybe add a comment for the added line.

File: library/src/scala/quoted/util/ExprMap.scala [hunk 7]
```diff
@@ -64,9 +64,11 @@ trait ExprMap {
           val tp = tpt.tpe match
             // TODO improve code
             case AppliedType(TypeRef(ThisType(TypeRef(NoPrefix(), "scala")), "<repeated>"), List(tp0: Type)) =>
+              // TODO rewrite without using quotes
               type T
-              val a = tp0.seal.asInstanceOf[quoted.Type[T]]
-              '[Seq[$a]].unseal.tpe
+              val qtp: quoted.Type[T] = tp0.seal.asInstanceOf[quoted.Type[T]]
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply library/src/scala/quoted/util/ExprMap.scala]: That is the case. But Types are usually given parameters and this des not affect them.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: I need to write `level(ctx)` or it takes the given context I'm defining recursively.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 4 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: It is not implied by the case above but maybe the case above might be redundant now. I will check.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala (hunk 3 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala]: For some reason the type aliases get transformed into type bounds with equivalent upper and lower bound but they do not get dealiased. I will investigate further.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: I will simplify it

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 4 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: No, the first transforms an Expr splice and the second a Type splice
