### PR TITLE
Fix #6286:  Fix ElimOpaque transformation

### LINKED ISSUE #6286: AssertionError in tpd.newArray on new Array of opaque type
In the companion object of an opaque type `T`, creating an array using `new Array[T]` causes an assertion error. Seems to work outside the companion.
Code:
```scala
object A {
  opaque type T = Int
  object T{
    val a = new Array[T](3)
  }
}
```
Output:
```
exception occurred while compiling opaque-array.scala
java.lang.AssertionError: assertion failed while compiling opaque-array.scala
Exception in thread "main" java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:208)
        at dotty.tools.dotc.ast.tpd$.newArray(tpd.scala:410)
        at dotty.tools.dotc.transform.ArrayConstructors.expand$1(ArrayConstructors.scala:29)
        at dotty.tools.dotc.transform.ArrayConstructors.transformApply(ArrayConstructors.scala:33)
        at dotty.tools.dotc.transform.MegaPhase.goApply(MegaPhase.scala:611)
        at dotty.tools.dotc.transform.MegaPhase.goApply(MegaPhase.scala:612)
        at dotty.tools.dotc.transform.MegaPhase.goApply(MegaPhase.scala:612)
        at dotty.tools.dotc.transform.MegaPhase.goApply(MegaPhase.scala:612)
        at dotty.tools.dotc.transform.MegaPhase.goApply(MegaPhase.scala:612)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:272)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.mapValDef$1(MegaPhase.scala:234)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:238)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
        at dotty.tools.dotc.transform.MegaPhase.transformStat$1(MegaPhase.scala:404)
        at dotty.tools.dotc.transform.MegaPhase.$anonfun$transformStats$2(MegaPhase.scala:409)
        at scala.collection.immutable.List.mapConserve(List.scala:179)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
        at dotty.tools.dotc.transform.MegaPhase.transformStat$1(MegaPhase.scala:404)
        at dotty.tools.dotc.transform.MegaPhase.$anonfun$transformStats$2(MegaPhase.scala:409)
        at scala.collection.immutable.List.mapConserve(List.scala:179)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:339)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:394)
        at dotty.tools.dotc.transform.MegaPhase.transformStat$1(MegaPhase.scala:404)
        at dotty.tools.dotc.transform.MegaPhase.$anonfun$transformStats$2(MegaPhase.scala:409)
        at scala.collection.immutable.List.mapConserve(List.scala:179)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:409)
        at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:356)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:359)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:396)
        at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:415)
        at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:427)
        at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:316)
        at scala.collection.immutable.List.map(List.scala:286)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:314)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:158)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:49)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:155)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:153)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:153)
        at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:178)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:102)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:133)
        at dotty.tools.dotc.Run.compileSources(Run.scala:120)
        at dotty.tools.dotc.Run.compile(Run.scala:104)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
        at dotty.tools.dotc.Driver.process(Driver.scala:170)
        at dotty.tools.dotc.Driver.process(Driver.scala:139)
        at dotty.tools.dotc.Driver.process(Driver.scala:151)
        at dotty.tools.dotc.Driver.main(Driver.scala:178)
        at dotty.tools.dotc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by odersky**
SymTransformers used to transform only SymDenotations. But that does not work for
ElimOpaque, where we also have to transform SingleDenotations that refer to opaque
helpers.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/DenotTransformers.scala [hunk 1]
```diff
@@ -60,11 +60,14 @@ object DenotTransformers {
   /** A transformer that only transforms SymDenotations */
   trait SymTransformer extends DenotTransformer {
 
+  	/** Tramsform the info of a denotation that is not a Symdenotation */
+    def transformInfo(tp: Type, sym: Symbol)(implicit ctx: Context): Type = tp
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: I would call it `transformNonSymInfo` to avoid confusion. Or perhaps just make ElimOpaque a regular DenotTransformer, we can always add another kind of Transformer later if we find more uses for it.

File: compiler/src/dotty/tools/dotc/core/DenotTransformers.scala [hunk 2]
```diff
@@ -60,11 +60,14 @@ object DenotTransformers {
...
+
     def transformSym(sym: SymDenotation)(implicit ctx: Context): SymDenotation
 
     def transform(ref: SingleDenotation)(implicit ctx: Context): SingleDenotation = ref match {
       case ref: SymDenotation => transformSym(ref)
-      case _ => ref
+      case _ => ref.derivedSingleDenotation(ref.symbol, transformInfo(ref.info, ref.symbol))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: Isn't `derivedSingleDenotation` going to force the info of the ref?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: Ah in fact ref.info on that line does that more directly :). That means we're suddenly forcing all infos of non-sym SingleDenotations which doesn't sound ideal.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: Only for opaque helper types. So it's not out of the ordinary,

File: compiler/src/dotty/tools/dotc/core/DenotTransformers.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: OK for `transformNonSymInfo`. I think it's better to leave it there to make it clear that something has to be done if a SymTranformer also changes the infos of symbols.

File: compiler/src/dotty/tools/dotc/core/DenotTransformers.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/DenotTransformers.scala]: You are right. Let's make it a DenotTransformer instead.

**Comment by odersky** [comment]
#6287 is also fixed by this PR
