### PR TITLE
Fix #6341: Revise purity checking

### LINKED ISSUE #6341: Backend crash when passing a field projection with a new at an inline method
```scala
object Test {
  class Config(val t1: Int)

  inline def m(t2:Int) = t2

  m(new Config(3).t1)
}
```

```scala
Unexpected tree in genLoad: TypeTree[TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class Test$)),class Test$Config)]/class dotty.tools.dotc.ast.Trees$TypeTree at: <68..68>
java.lang.RuntimeException: Unexpected tree in genLoad: TypeTree[TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),module class Test$)),class Test$Config)]/class dotty.tools.dotc.ast.Trees$TypeTree at: <68..68>
        at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:390)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:433)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:263)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadQualifier(BCodeBodyBuilder.scala:1012)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genNormalMethodCall$1(BCodeBodyBuilder.scala:784)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:816)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:339)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:83)
        at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.$anonfun$genBlock$1(BCodeBodyBuilder.scala:920)
...
```

### PR DESCRIPTION
**Pull request by odersky**
There is some confusion on terminology that needs to be fixed.

Step 1: Make SimplyPure apply to paths only.

The only point where it is used is in eta expansion to answer the question
whether in a partial application `f(e, _)` the expression `e` should be
lifted out, giving `{ val x = e; y => f(x, y) }` instead of `y => f(e, y)`.
With the change, closures and new expressions are never simply pure, so
are always lifted out. This can reduce the number of allocations, if the
lambda is applied several times.

Step 2: Split the property that something is a path from the property that something is pure, or idempotent.

Step 3: Require an idempotent _path_ in the critical Inliner code.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 1]
```diff
@@ -841,12 +858,15 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
 
 object TreeInfo {
   class PurityLevel(val x: Int) extends AnyVal {
-    def >= (that: PurityLevel): Boolean = x >= that.x
-    def min(that: PurityLevel): PurityLevel = new PurityLevel(x min that.x)
+    def >= (that: PurityLevel): Boolean = (x & that.x) == that.x
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: This change in the semantics of `x` deserves some documentation.

File: compiler/src/dotty/tools/dotc/ast/TreeInfo.scala [hunk 2]
```diff
@@ -841,12 +858,15 @@ trait TypedTreeInfo extends TreeInfo[Type] { self: Trees.Instance[Type] =>
...
 
-  val SimplyPure: PurityLevel = new PurityLevel(3)
-  val Pure: PurityLevel = new PurityLevel(2)
+  val Path: PurityLevel = new PurityLevel(4)
+  val Pure: PurityLevel = new PurityLevel(3)
   val Idempotent: PurityLevel = new PurityLevel(1)
   val Impure: PurityLevel = new PurityLevel(0)
+
+  val PurePath: PurityLevel = new PurityLevel(7)
+  val IdempotentPath: PurityLevel = new PurityLevel(5)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/ast/TreeInfo.scala]: Maybe should be more explicit
```scala
val PurePath: PurityLevel = new PurityLevel(Path.x | Pure.x)
val IdempotentPath: PurityLevel = new PurityLevel(Path.x | Idempotent.x)
```
