### PR TITLE
Fix #10082: show friendly error message related to  type inference

### LINKED ISSUE #10082: Value + is not a member of Int
Inspired by [Context Functions](http://dotty.epfl.ch/docs/reference/contextual/context-functions.html), I decided to practice my bad taste on simulating the `it` anonymous function parameter. But it doesn't work.

## Minimized code

```Scala
object Kotlin:
  def it[T](using t: T) = t
  def fun[T, U](fn: T ?=> U)(x: T): U = fn(using x)

import Kotlin.{fun, it}
List(1).map(fun(it + 1))
```

## Output

```
|List(1).map(fun(it + 1))
  |                ^^^^
  |value + is not a member of Int, but could be made available as an extension method.
  |
  |One of the following imports might fix the problem:
  |
  |  import math.BigDecimal.int2bigDecimal
  |  import math.BigInt.int2bigInt
  |  import math.Numeric.BigDecimalAsIfIntegral.mkNumericOps
  |  import math.Numeric.BigDecimalIsFractional.mkNumericOps
  |  import math.Numeric.BigIntIsIntegral.mkNumericOps
  |  import math.Numeric.IntIsIntegral.mkNumericOps
  |  import Long.long2double
  |  import math.BigDecimal.long2bigDecimal
  |  import Long.long2float
  |  import math.BigInt.long2bigInt
  |

```

## Expectation
This code should compile as `it` has already been inferred as `Int`.

## Workaround
Providing type arguments to `fun` works.

```scala
List(1).map(fun[Int, Int](it + 1))
```

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #10082: show friendly error message related to  type inference

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 1]
```diff
@@ -286,6 +286,8 @@ import transform.SymUtils._
   extends NotFoundMsg(NotAMemberID) {
     //println(i"site = $site, decls = ${site.decls}, source = ${site.typeSymbol.sourceFile}") //DEBUG
 
+    val widenedName: String  = ex"${site.widen}"
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:289]: We have to be very careful about this sort of things: normally, everything in an error message is lazy, this is important since we generate a lot of error messages that we never display (when finding candidates for implicit search for example), anything done eagerly in an error message can impact performance and needs to be measured.
Also, we already have some logic in type inference to stop doing inference when errors exist to make sure we don't report non-sensical messages:
https://github.com/lampepfl/dotty/blob/22c23a5cc648650bb6380dec0c11a5fdc34e1d73/compiler/src/dotty/tools/dotc/typer/Inferencing.scala#L491-L511
We should investigate why this isn't enough to handle this case.

**Review by smarter — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/reporting/messages.scala (hunk 1 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/reporting/messages.scala:289]: (one possible reason is that the logic I linked to is in `interpolateTypeVars`, but a different way to instantiate type variables is to use `isFullyDefined` / `fullyDefinedType` which doesn't go through the same codepath)

Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/reporting/messages.scala]: Thanks for the tip, I took the suggested approach and it seems to work 👍

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 2]
```diff
@@ -509,6 +509,8 @@ trait Inferencing { this: Typer =>
         //     required: String
         //     val y: List[List[String]] = List(List(1))
         val hasUnreportedErrors = state.reporter.hasUnreportedErrors
+        if hasUnreportedErrors then return tree
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:512]: @odersky Any reason we previously still instantiated some type variables when hasUnreportedErrors is true?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Inferencing.scala:512]: I can't see a reason.

File: compiler/src/dotty/tools/dotc/typer/Inferencing.scala [hunk 3]
```diff
@@ -509,6 +509,8 @@ trait Inferencing { this: Typer =>
         //     required: String
         //     val y: List[List[String]] = List(List(1))
         val hasUnreportedErrors = state.reporter.hasUnreportedErrors
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Inferencing.scala:511]: No need to define a local variable, it seems. We can simply return if `state.reporter.hasUnreportedErrors` is true.

**Review by odersky — COMMENTED** [review]
Otherwise LGTM
