### PR TITLE
Fix unescaping of escape sequences by jline in REPL

### LINKED ISSUE #5294: Escape sequences in the REPL
```scala
scala> "\\A"                                                                                                                                                                                                    
1 |"\A"
  |  ^
  |  invalid escape character

scala> "\A"
val res0: String = A
```
First one should not be rejected. Second one should.

I suspect JLine is doing something funny

### PR DESCRIPTION
**Pull request by nrjais**
Fixes #5294

Output
```scala
scala> "\\A"
val res0: String = \A

scala> "\A"
1 |"\A"
  |  ^
  |  invalid escape character

scala>
```

### CODE REVIEW

File: compiler/src/dotty/tools/repl/JLineTerminal.scala [hunk 1]
```diff
@@ -62,6 +62,7 @@ final class JLineTerminal(needsTerminal: Boolean) extends java.io.Closeable {
       .variable(BLINK_MATCHING_PAREN, 0L)       // Don't blink the opening paren after typing a closing paren.
       .option(INSERT_TAB, true)                 // At the beginning of the line, insert tab instead of completing.
       .option(AUTO_FRESH_LINE, true)            // if not at start of line before prompt, move to new line.
+      .option(DISABLE_EVENT_EXPANSION, true)
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/repl/JLineTerminal.scala]: Can you add a comment explaining why

Comment (nrjais) [reply compiler/src/dotty/tools/repl/JLineTerminal.scala]: @allanrenucci I have added the comment. 
Is it understandable?
