### PR TITLE
Fix #7488 and fix #7487: Get String form ConstantType

### LINKED ISSUE #7487: Incorrect return value from typeChecks with inline value
## minimized code

```Scala
import scala.compiletime.testing.typeChecks

object Minimized extends App {
  inline val code = "1 + 1"
  val result1: Boolean = typeChecks(code)    // false
  val result2: Boolean = typeChecks("1 + 1") // true
  println(result1)
  println(result2)
}
```

## expectation

I would have expected that as long as `code` was marked as `inline`, `typeChecks` would evaluate a string value the same as if I included that string directly in the function body.

Also, I noticed that `result1` requires a type annotation to compile. I'm not sure why that should be necessary given `typeChecks` always returns a `Boolean`.

### LINKED ISSUE #7488: Compilation error when inline def calls typeChecks
## minimized code

```Scala
import scala.compiletime.testing.typeChecks

object Minimized extends App {
  
  inline final def assertCompiles(inline code: String): Boolean =
    if (typeChecks(code)) true else false
  
  inline val code = "1 + 1"
  val result = assertCompiles(code)
  println(result)
}

// scala.MatchError: EmptyTree (of class dotty.tools.dotc.ast.Trees$EmptyTree)
```

## expectation

I would expect this to compile and return the same result as `typeChecks`.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 1]
```diff
@@ -197,16 +197,14 @@ object Inliner {
...
-        case _ => None
+      def stripTyped(t: Tree): Tree = t match {
+        case Typed(t2, _) => stripTyped(t2)
+        case _ => t
       }
+
       val Apply(_, codeArg :: Nil) = tree
-      getCodeArgValue(codeArg.underlyingArgument) match {
-        case Some(code) =>
+      ConstFold(stripTyped(codeArg.underlyingArgument)).tpe.widenTermRefExpr match {
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Inliner.scala]: If we call `ConstFold` here, should we add a test like `typeChecks("1" + "1")`?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala]: Added it to `tests/run/i7487.scala`
