### PR TITLE
Fix #11644: Fix broken dotty.tools.io.Path#parent

### LINKED ISSUE #11644: "Could not find TASTY file" error when tasty/class files already exist
## Compiler version

3.0.0-RC1 and 3.0.0-RC2-bin-SNAPSHOT-git-086d1a8
(no issue with 3.0.0-M3)

## Minimized code

```scala
// hello.scala
@main def hello = println("hello, world")
```

## Output

```
$ ls -l
total 4
-rw-r--r-- 1 tgrigg tgrigg 43 Mar  7 15:34 hello.scala

$ scalac -version
Scala compiler version 3.0.0-RC1 -- Copyright 2002-2021, LAMP/EPFL

$ scalac hello.scala

$ ls -l
total 24
-rw-r--r-- 1 tgrigg tgrigg 757 Mar  7 15:35 'hello$package$.class'
-rw-r--r-- 1 tgrigg tgrigg 267 Mar  7 15:35 'hello$package.class'
-rw-r--r-- 1 tgrigg tgrigg 554 Mar  7 15:35 'hello$package.tasty'
-rw-r--r-- 1 tgrigg tgrigg 882 Mar  7 15:35  hello.class
-rw-r--r-- 1 tgrigg tgrigg  43 Mar  7 15:34  hello.scala
-rw-r--r-- 1 tgrigg tgrigg 471 Mar  7 15:35  hello.tasty

$ scalac hello.scala
Could not find TASTY file hello.tasty under ./hello.class
1 error found
```

## Expectation

No error

## Notes

Seems to only be a problem when the class/tasty files are in the current directory.

### PR DESCRIPTION
**Pull request by griggt**
[test_non_bootstrapped]
[test_windows_full]

Fixes #11644

### CODE REVIEW

**Comment by griggt** [comment]
The failure in `test_windows_full` is unrelated to this PR.

File: compiler/src/dotty/tools/io/Path.scala [hunk 1]
```diff
@@ -127,7 +127,15 @@ class Path private[io] (val jpath: JPath) {
...
+    case null =>
+      if (isAbsolute)  // it should be a root
+        toDirectory
+      else if (segments.nonEmpty && segments.last == "..")
+        (this / "..").toDirectory
+      else path match {
+        case "" | "." => Directory("..")
+        case _        => Directory(".")
+      }
     case parent => Directory(parent)
```
Comment (griggt) [inline compiler/src/dotty/tools/io/Path.scala:139]: Just noticed a case that is still broken because it takes this `case parent` path:

```scala
scala> Path("../..").parent
val res0: dotty.tools.io.Directory = ..      // should be ../../..
```

File: compiler/src/dotty/tools/io/Path.scala [hunk 2]
```diff
@@ -127,7 +127,15 @@ class Path private[io] (val jpath: JPath) {
    * @return The path of the parent directory, or root if path is already root
    */
   def parent: Directory = jpath.normalize.getParent match {
```
Comment (griggt) [inline compiler/src/dotty/tools/io/Path.scala:129]: Perhaps it's best to avoid `normalize` altogether.

Consider this case:
- working directory is `/src/dotty`
- `foo` is a symlink to `/tmp/foo`

Before this PR:

```scala
scala> Path("foo/../bar").parent
val res0: dotty.tools.io.Directory = foo/../bar

scala> res0.jpath.toRealPath()
val res1: java.nio.file.Path = /tmp/bar
```

With this PR:

```scala
scala> Path("foo/../bar").parent
val res0: dotty.tools.io.Directory = .

scala> res0.jpath.toRealPath()
val res1: java.nio.file.Path = /src/dotty
```

Scala 2:

```scala
scala> Path("foo/../bar").parent
val res0: scala.reflect.io.Directory = foo/..

scala> res0.jfile.getCanonicalPath()
val res1: String = /tmp
```

readlink:

```
/src/dotty$ readlink -f foo/../bar/..
/tmp
```

**Comment by michelou** [comment]
@griggt Thanks for fixing the files in directory `project/scripts/`.

**Comment by bishabosha** [comment]
@griggt what else do you need to finish on this PR?

**Comment by griggt** [comment]
Several CI jobs (test_windows_fast, test_windows_full, scaladoc/build, scaladoc/community-docs) are failing due to a Bintray / JCenter outage: https://status.bintray.com/incidents/9n84kbm0bjh0

https://github.com/lampepfl/dotty/actions/runs/656300195
https://github.com/lampepfl/dotty/actions/runs/656300193

**Review by bishabosha — APPROVED** [review]
LGTM
