### PR TITLE
Fix #9268: Scala.js: Add support for switch-Matches.

### LINKED ISSUE #9268: Pattern matching with alternatives is compiled to "throw null" with Scala.js
## Minimized code

https://github.com/scala-js/scala-js/blob/master/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala#L626

```Scala
  @Test def leftAlignWithoutWidthThrows(): Unit = {
    for (conversion <- "bBhHsHcCdoxXeEgGf%") {
      val fmt = "ab%-" + conversion + "cd"
      val arg = conversion match {
        case 'e' | 'E' | 'g' | 'G' | 'f' => 5.5
        case _ => 5
      }
      val e =
        expectFormatterThrows(classOf[MissingFormatWidthException], fmt, arg)
      assertEquals(fmt, "%-" + conversion, e.getFormatSpecifier)
    }
  }
```

## Output

Scala.js IR:

```Scala
  @hints(1) private def leftAlignWithoutWidthThrows$$anonfun$1;C;V(conversion: char) {
    val fmt: java.lang.String = (("ab%-" +[string] conversion) +[string] "cd");
    val arg: double = matchResult1[double]: {
      val x1: char = conversion;
      throw null
    };
    val e: java.util.MissingFormatWidthException = this.expectFormatterThrows;Ljava.lang.Class;Ljava.lang.String;Lscala.collection.immutable.Seq;Ljava.lang.Throwable(classOf[java.util.MissingFormatWidthException], fmt, mod:scala.runtime.ScalaRunTime$.genericWrapArray;Ljava.lang.Object;Lscala.collection.immutable.ArraySeq(java.lang.Object[](arg))).asInstanceOf[java.util.MissingFormatWidthException];
    mod:org.junit.Assert$.assertEquals;Ljava.lang.String;Ljava.lang.Object;Ljava.lang.Object;V(fmt, ("%-" +[string] conversion), e.getFormatSpecifier;Ljava.lang.String())
  }
```

JavaScript:

```JavaScript
  leftAlignWithoutWidthThrows__V() {
    const len = $uI("bBhHsHcCdoxXeEgGf%".length);
    let i = 0;
    while ((i < len)) {
      const index = i;
      $uI("bBhHsHcCdoxXeEgGf%".charCodeAt(index));
      throw null
    }
  };
```

## Expectation

This (equivalent?) match expression:

```Scala
      val arg = conversion match {
        case _: ('e' | 'E' | 'g' | 'G' | 'f') => 5.5
        case _ => 5
      }
```

is compiled to the following IR:

```Scala
    val arg: double = matchResult1[double]: {
      val x1: char = conversion;
      if ((((int)'e') ==[int] ((int)x1)) || (((int)'E') ==[int] ((int)x1)) || (((int)'g') ==[int] ((int)x1)) || (((int)'G') ==[int] ((int)x1)) || (((int)'f') ==[int] ((int)x1))) {
        return@matchResult1 5.5d
      };
      return@matchResult1 5.0d
    };
```

and the following JavaScript code:

```JavaScript
const arg = ((((((arg1 === 101) || (arg1 === 69)) || (arg1 === 103)) || (arg1 === 71)) || (arg1 === 102)) ? 5.5 : 5.0);
```

### PR DESCRIPTION
**Pull request by sjrd**
This implementation has been ported from the scalac backend, but is much simpler because it does not have to deal with hacks around scalac's LabelDefs.

---

As preliminary work: For switch-Matches in PatMap, convert scrutinee and alternatives to Int.

In JVM bytecode as well in Scala.js IR, switches only work with primitive ints. Therefore, it makes more sense to convert the scrutinee and alternatives of switch-Matches to Ints early.

This is also what scalac does. See `RegularSwitchMaker` in `patmat/MatchOptimization.scala`.

The JVM back-end tolerates non-ints due its aggressive and blind adaptations everywhere (not because of a deliberate action to support non-Ints). However, the Scala.js back-end does not like receiving non-Ints in `Match`es, because it is much more conservative in where it inserts adaptations (i.e., almost nowhere).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala [hunk 1]
```diff
@@ -821,17 +821,31 @@ object PatternMatcher {
...
+       */
+
+      val intScrutinee =
+        if (scrutinee.tpe.widen.isRef(defn.IntClass)) scrutinee
+        else scrutinee.select(nme.toInt)
+
+      def intLiteral(lit: Tree): Tree =
+        val Literal(constant) = lit
+        if (constant.tag == Constants.IntTag) lit
+        else Literal(Constant(constant.intValue)).withSpan(lit.span)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala:837]:
```suggestion
        else cpy.Literal(lit)(Constant(constant.intValue))
```
to also set the source file of the tree corectly

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala]: Thank you, that's much better!

Updated.
