### PR TITLE
Fix #9751: Fix Inline purity checks

### LINKED ISSUE #9751: Incorrect dead pure code warning for inline parameters
## Minimized code

```Scala
object Test {
  extension (x: Int)
    inline def times(inline op: Unit): Unit = {
      var count = 0
      while count < x do
        op
        count += 1
    }

  10.times { println("hello") }
}
```

## Output

```scala
-- [E129] Potential Issue Warning: examples/times.scala:7:8 --------------------
7 |        op
  |        ^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses
```

## Expectation

The compiler should not generate the warning.

### PR DESCRIPTION
**Pull request by nicolasstucki**
We wrongly identified most inline references as pure as they are effectively erased.
Only erased terms are always pure.
Most of the purity of inline references follows from the normal purity rules except for inline parameters.
These parameters lose their binding when inlined and no purity guaranty can be ensured from the reference.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -3629,8 +3629,12 @@ class Typer extends Namer
     }
 
   private def checkStatementPurity(tree: tpd.Tree)(original: untpd.Tree, exprOwner: Symbol)(using Context): Unit =
-    if (!tree.tpe.isErroneous && !ctx.isAfterTyper && isPureExpr(tree) &&
-        !tree.tpe.isRef(defn.UnitClass) && !isSelfOrSuperConstrCall(tree))
+    if !tree.tpe.isErroneous
+      && !ctx.isAfterTyper
+      && !tree.isInstanceOf[Inlined]
+      && isPureExpr(tree)
+      && !isSelfOrSuperConstrCall(tree)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3636]: `tree.isInstanceOf[Inlined]` : can an inlined tree be pure? What about handle inlined trees in `isPureExpr`?

File: compiler/src/dotty/tools/dotc/transform/TransformByNameApply.scala [hunk 2]
```diff
@@ -47,7 +47,7 @@ abstract class TransformByNameApply extends MiniPhase { thisPhase: DenotTransfor
             ref(defn.cbnArg).appliedToType(argType).appliedTo(arg).withSpan(arg.span)
           arg match {
             case Apply(Select(qual, nme.apply), Nil)
-            if qual.tpe.derivesFrom(defn.FunctionClass(0)) && isPureExpr(qual) =>
+            if qual.tpe.derivesFrom(defn.FunctionClass(0)) && (isPureExpr(qual) || qual.symbol.isAllOf(Inline | Param)) =>
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/TransformByNameApply.scala:50]: Does it matter? If I were correct, the body of inlined methods is never executed, thus only the TASTY matters.

**Review by liufengyun — APPROVED** [review]
Otherwise, LGTM

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3636]: The Inlined trees can be pure which is correctly identified in isPureExpr. Here we special case a
Inlined calls that inserted a pure expression in a statement possition as these are only puede due to other constraints that may change. For example the assert can take a reference to an Inlined true value which converts it in a noop and we do not want to warn that this is a pure expression in statement position.

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala [hunk 3]
```diff
@@ -521,7 +521,7 @@ class Inliner(call: tpd.Tree, rhsToInline: tpd.Tree)(using Context) {
          | Literal(_) =>
         true
       case Ident(_) =>
-        isPureRef(tree)
+        isPureRef(tree) || tree.symbol.isAllOf(Inline | Param)
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:524]: Inline parameters always elide their binding. Previously we elided them because they were wrongly identified as pure.

File: compiler/src/dotty/tools/dotc/transform/TransformByNameApply.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/TransformByNameApply.scala:50]: In theory that seems to be the case. But I caught one that came for the `DottyPredef.assert` when compiling dotty itself. It might be a re-bootstrapping issue.

File: compiler/src/dotty/tools/dotc/typer/Inliner.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Inliner.scala:524]: Makes sense 👍

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3636]: Thanks for the explanation. It might be good to add a short comment after the line.

File: compiler/src/dotty/tools/dotc/transform/TransformByNameApply.scala (hunk 2 above)
Comment (liufengyun) [reply compiler/src/dotty/tools/dotc/transform/TransformByNameApply.scala:50]: I see. It could be some invariants after the typer -- and it's always good to do so.

**Review by liufengyun — APPROVED** [review]
