### PR TITLE
Fix #5077: avoid pattern-bound type for selectors

### LINKED ISSUE #5077: Unexpected behavior for pattern matching on generic case class
The following example defines a simple case class `C` with two members and one generic type. Pattern matching on this class gives some surprising results in various cases, and the results differ significantly from 2.12/2.13 behavior. (In fact, _all_ the three cases below are treated differently in Dotty vs. 2.12/2.13):

```scala
trait Is[A]
case object IsInt extends Is[Int]
case object IsString extends Is[String]
case class C[A](is: Is[A], value: A)

val c_string: C[String] = C(IsString, "name")
val c_any: C[_] = c_string
val any: Any = c_string

// Case 1: Should give compile error, since IsInt is not compatible with C[String]
c_string match {
  case C(IsInt, _) => println(s"An Int") // Can't possibly happen!
  case C(IsString, s) => println(s"A String with length ${s.length}")
  case _ => println("No match")
}

// Case 2: Should match the second case and print the length of the string
c_any match {
  case C(IsInt, i) if i < 10 => println(s"An Int less than 10")
  case C(IsString, s) => println(s"A String with length ${s.length}")
  case _ => println("No match")
}

// Case 3: Same as above; should match the second case and print the length of the string
any match {
  case C(IsInt, i) if i < 10 => println(s"An Int less than 10")
  case C(IsString, s) => println(s"A String with length ${s.length}")
  case _ => println("No match")
}
```

In Dotty 0.9.0-RC, only `Case 3` is handled as expected (which is the only case that isn't handled correctly in 2.12/2.13). The actual result is that `Case 2` fails to compile:

```
[error] -- [E008] Member Not Found Error: C:\dev\dottytest\src\main\scala\Main.scala:23:28
[error] 23 |      case C(IsInt, i) if i < 10 => println(s"An Int less than 10")
[error]    |                          ^^^
[error]    |              value `<` is not a member of C[_]#A - did you mean `i.==`?
[error] -- [E008] Member Not Found Error: C:\dev\dottytest\src\main\scala\Main.scala:24:64
[error] 24 |      case C(IsString, s) => println(s"A String with length ${s.length}")
[error]    |                                                              ^^^^^^^^
[error]    |                                value `length` is not a member of C[_]#A
[error] two errors found
```

I would assume the behavior to be:

### Case 1

This case should be rejected by the compiler since the `IsInt` member is _not_ compatible with `C[String]`. But Dotty accepts this, while 2.12 correctly rejects the pattern match due to incompatible types.

### Case 2

The type being matched is a `C[_]`. 2.12 accepts this pattern match and works as expected, while Dotty does not figure out the type of the corresponding value member. (I am not sure if this is expected in Dotty due to removal of existential types, but it is nevertheless surprising).

### Case 3

This compiles and Dotty is able to infer the type of the value based on the case object given as the first parameter. However, in 2.12 this fails (see: [Scala 2.12 bug 11132](https://github.com/scala/bug/issues/11132))

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #5077: avoid pattern-bound type for selectors

Given the following definition:

    trait Is[A]
    case object IsInt extends Is[Int]
    case object IsString extends Is[String]
    case class C[A](is: Is[A], value: A)

and the pattern match:

    (x: C[_]) match
    case C(IsInt, i) => ...

The typer (enhanced with GADT) will infer `C[A$1]` as the type of the
pattern, where `A$1 =:= Int`.

The patternMatcher generates the following code:

    case val x15: C[A$1] =
      C.unapply[A$1 @ A$1](x9.$asInstanceOf$[C[A$1]])
    case val x16: Is[A$1] = x15._1
    case val x17: A$1 = x15._2        // erase to `Int`
    if IsInt.==(x16) then
      {
        case val i: A$1 = x17
	...
      }

Note that `x17` will have the erased type `Int`. This is incorrect: it
may only assume the type `Int` if the test is true inside the block.
If the test is false, we will get an type cast exception at runtime.

To fix the problem, we replace pattern-bound types by `Any` for
selector results:

    case val x15: C[A$1] =
      C.unapply[A$1 @ A$1](x9.$asInstanceOf$[C[A$1]])
    case val x16: Is[A$1] = x15._1
    case val x17: Any = x15._2
    if IsInt.==(x16) then
      {
        case val i: A$1 = x17.$asInstanceOf$[A$1]
        ...
      }

The patternMatcher will then use a type cast to pass the selector
value for nested unapplys or assign it to bound variables.

### CODE REVIEW

**Comment by dwijnand** [comment]
Isn't this wrong because `==` is user-definable?

**Comment by liufengyun** [comment]
> Isn't this wrong because `==` is user-definable?

Do you mean the first pattern match? Yes, it should be allowed. https://github.com/lampepfl/dotty/issues/5077#issuecomment-739741912 . However, I think it's also fair for the compiler to be incomplete and reject the code. See #9740.

File: tests/run/i5077.scala [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+case object IsString extends Is[String]
+case class C[A](is: Is[A], value: A)
+
+@main
+def Test = {
+  val c_string: C[String] = C(IsString, "name")
+  val c_any: C[_] = c_string
+  val any: Any = c_string
+
+  // Case 1: Should give compile error, since IsInt is not compatible with C[String]
```
Comment (odersky) [inline tests/run/i5077.scala:12]: This should get a changed comment since it does not give a compile error. It would be best if we explained why the behavior deviates from what is proposed in the issue.

**Review by odersky — COMMENTED** [review]
Otherwise LGTM

File: tests/run/i5077.scala (hunk 1 above)
Comment (smarter) [reply tests/run/i5077.scala:12]: It would also be good to have a check file that verifies the exact runtime behavior of this code.
