### PR TITLE
Fix #5140: Ycheck failure in covariant java varargs

### LINKED ISSUE #5140: Ycheck failure in covariant java varargs
This involves Scala code calling a Java varargs methods.

Java
```
  class Animal {}
  class Dog extends Animal {}
  class J {
    void foo(Animal... animal) {}
  }
```

Scala
```
class S {
  val j = new J()
  val x: Array[Dog] = ???
  j.foo(x: _*)
}
```

Compiling without -Ycheck succeeds, but -Ycheck:refchecks fails:
```
exception while typing this.j.foo(this.x) of class class dotty.tools.dotc.ast.Trees$Apply # 802
exception while typing @scala.annotation.internal.SourceFile("tests/neg/java-varargs-cov/S.scala") 
  class
 S() extends Object() { 
  val j: J = new J()
  val x: Array[Dog] = ???
  this.j.foo(this.x)
} of class class dotty.tools.dotc.ast.Trees$TypeDef # 804
exception while typing package <empty> {
  @scala.annotation.internal.SourceFile("tests/neg/java-varargs-cov/S.scala") 
    class
   S() extends Object() { 
    val j: J = new J()
    val x: Array[Dog] = ???
    this.j.foo(this.x)
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # 805
*** error while checking tests/neg/java-varargs-cov/S.scala after phase refchecks ***
exception occurred while compiling tests/neg/java-varargs-cov/S.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: found:    Array[Dog](S.this.x)
required: Array[Animal]


tree = this.x
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.transform.TreeChecker$Checker.adapt(TreeChecker.scala:460)
	at dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:302)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:663)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:661)
	at dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:434)
	at dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:472)
	at dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:255)
	at dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:564)
	at dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:662)
	at dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:722)
	at dotty.tools.dotc.typer.Applications.$anonfun$typedApply$7(Applications.scala:747)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1983)
	at dotty.tools.dotc.typer.Applications.$anonfun$typedApply$1(Applications.scala:748)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:692)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:793)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:690)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:82)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1817)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1868)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:282)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1899)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1895)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1911)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:270)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1951)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1964)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:446)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedClassDef$1(Typer.scala:1564)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1487)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:399)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1808)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1867)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:282)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1899)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1895)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1911)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:270)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1930)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1964)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:446)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedPackageDef$1(Typer.scala:1674)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1667)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1847)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1868)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:112)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:282)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:1899)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1895)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1911)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:270)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1975)
	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:132)
	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:104)
	at dotty.tools.dotc.core.Phases$Phase.$anonfun$runOn$1(Phases.scala:298)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:296)
	at dotty.tools.dotc.core.Phases$Phase.runOn$(Phases.scala:295)
	at dotty.tools.dotc.transform.TreeChecker.runOn(TreeChecker.scala:48)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:174)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:49)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:171)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:169)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:169)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:194)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:90)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:149)
	at dotty.tools.dotc.Run.compileSources(Run.scala:136)
	at dotty.tools.dotc.Run.compile(Run.scala:120)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:31)
	at dotty.tools.dotc.Driver.process(Driver.scala:134)
	at dotty.tools.dotc.Driver.process(Driver.scala:103)
	at dotty.tools.dotc.Driver.process(Driver.scala:115)
	at dotty.tools.dotc.Driver.main(Driver.scala:142)

```

### PR DESCRIPTION
**Pull request by abeln**
Allow passing `Array[Dog]` to a Java varargs that expects an
`Array[Animal]`. This types because Java vargs are represented as
`RepeatedParam[+T]`, which is covariant.

However, after `elimRepeated`, the `RP`s go away and the true type
(Array) is revealed, which was causing a Ycheck error because arrays are
invariant before erasure.

Fix the Ycheck error by casting `Array[Dog]` to `Array[Animal]`. This is
unsound but consistent with the typer behaviour and what scalac does.

### CODE REVIEW

File: tests/pos/i5140/S.scala [hunk 1]
```diff
@@ -0,0 +1,8 @@
+class S {
+  val j = new J()
+  val x: Array[Dog] = ???
+  // Check that x is cast to an `Array[Animal]` after elimRepeated.
+  // Otherwise, the call below would fail in -Ycheck:elimRepeated because arrays are invariant before erasure.
+  // This is unsound but allowed.
+  j.foo(x: _*)
```
Comment (allanrenucci) [inline tests/pos/i5140/S.scala]: Can we also add a line for:
```scala
j.foo(new Dog, new Dog)
```

Comment (abeln) [reply tests/pos/i5140/S.scala]: Done

**Comment by abeln** [comment]
Switched to @smarter's suggestion that we change the type to `Array[_ <: T]`, as opposed to a cast. PTAL

**Comment by abeln** [comment]
@smarter Here's the problem I run into with the `Array[_ <: Animal]` approach. If a Scala method overrides a Java varargs method, then `elimRepeated` has to add a bridge from the Scala method, which expects a `Seq[Animal]`, to the Java signature of the method (which is what the callers see), which is `Array[_ <: Animal]`.

The code generated by `elimRepeated` after this change then looks like
```
  ) class Sub() extends Base() { 
    def foo(x: Seq[Object] @Repeated): Object = x
    override def foo(x: Array[_ <: Object]): Object = 
      this.foo(Predef.wrapRefArray[Object](x))
  }
}
```
Which doesn't work because there's no sound way to convert an `Array[_ <: Object]` into a `Seq[Object]`. Or is there?

If there's no sound way, then I suggest we revert back to the `asInstanceOf` approach of the first commit.

**Comment by smarter** [comment]
The problem is that passing `Object` as the type argument to `wrapRefArray` doesn't work here, but this compile:
```scala
object Test {
  val x: Array[_ <: Object] = Array()
  val y = Predef.wrapRefArray(x)
  val z: Seq[Object] = y
}
```
The infered type argument is `Array[_ <: Object]#T` which is a bit awkward and can't be written in source code but can be inferred by the compiler. We could change whatever code is currently generating the `wrapRefArray` to do the same.

**Comment by abeln** [comment]
PTAL. Changed `elimRepeated` to generate
```
  ) class Sub() extends Base() { 
    def foo(x: Seq[Object] @Repeated): Object = x
      override def foo(x: Array[_ <: Object]): Object =
      this.foo(Predef.wrapRefArray[ <: Object](x))
  }
}
```
Which can't be written with surface syntax (unbound wildcard), but apparently typechecks.

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 2]
```diff
@@ -453,7 +457,9 @@ class TypeApplications(val self: Type) extends AnyVal {
   def underlyingIfRepeated(isJava: Boolean)(implicit ctx: Context): Type =
     if (self.isRepeatedParam) {
       val seqClass = if (isJava) defn.ArrayClass else defn.SeqClass
-      translateParameterized(defn.RepeatedParamClass, seqClass)
+      // If `isJava` is set, then we want to turn `RepeatedParam[T]` into `Array[_ <: T]`,
+      // since arrays aren't covariant until after erasure. See `tests/pos/i5140`.
+      translateParameterized(defn.RepeatedParamClass, seqClass, argIsUpper=isJava)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: spaces around the = sign

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala [hunk 3]
```diff
@@ -435,15 +435,19 @@ class TypeApplications(val self: Type) extends AnyVal {
     case _ => if (self.isMatch) MatchAlias(self) else TypeAlias(self)
   }
 
-  /** Translate a type of the form From[T] to To[T], keep other types as they are.
+  /** Translate a type of the form From[T] to either To[T] or To[_ <: T] (if `argIsUpper` is set). Keep other types as they are.
    *  `from` and `to` must be static classes, both with one type parameter, and the same variance.
    *  Do the same for by name types => From[T] and => To[T]
    */
-  def translateParameterized(from: ClassSymbol, to: ClassSymbol)(implicit ctx: Context): Type = self match {
+  def translateParameterized(from: ClassSymbol, to: ClassSymbol, argIsUpper: Boolean = false)(implicit ctx: Context): Type = self match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: I would call this parameter wildcardArg

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala (hunk 2 above)
Comment (abeln) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: Done

File: compiler/src/dotty/tools/dotc/core/TypeApplications.scala (hunk 3 above)
Comment (abeln) [reply compiler/src/dotty/tools/dotc/core/TypeApplications.scala]: Done

**Comment by abeln** [comment]
Addressed style comments and collapsed review commits.

**Comment by allanrenucci** [comment]
Thanks @abeln!
