### PR TITLE
Fix #1284: Make classTag depend directly on erasure

### LINKED ISSUE #1284: Array of case objects does not compile due to missing ClassTag
```scala
case object A
case object B

object Test {
  Array(A, B)
}
```
```
error: No ClassTag available for (Object & Product0)'
  Array(A, B)
             ^
```

### PR DESCRIPTION
**Pull request by odersky**
In the end, a classTag reflects the erased version of a type. The only
condition for its generation should be that the erasure is stable under
possible instantiations.

### CODE REVIEW

**Comment by odersky** [comment]
Review by @xeno-by ?

File: src/dotty/tools/dotc/typer/Implicits.scala [hunk 1]
```diff
@@ -479,15 +480,12 @@ trait Implicits { self: Typer =>
...
-                .appliedToType(tp)
-                .appliedTo(clsOf(tref))
-                .withPos(pos)
-            case _ =>
-          }
+          if (hasStableErasure(tp))
+            return ref(defn.ClassTagModule)
+              .select(nme.apply)
+              .appliedToType(tp)
+              .appliedTo(clsOf(erasure(tp)))
```
Comment (xeno-by) [inline src/dotty/tools/dotc/typer/Implicits.scala]: That's an interesting DSL! Does it cover the entire language, or it just contains a few most used utilities?

Comment (odersky) [inline src/dotty/tools/dotc/typer/Implicits.scala]: It covers about 30 ops, maybe half of them construct syntax trees. See `ast.tpd#TreeOps` for where it  is defined.

File: src/dotty/tools/dotc/core/TypeErasure.scala [hunk 2]
```diff
@@ -493,4 +509,6 @@ class TypeErasure(isJava: Boolean, semiEraseVCs: Boolean, isConstructor: Boolean
       println(s"no sig for $tp")
       throw ex
   }
+
+
```
Comment (xeno-by) [inline src/dotty/tools/dotc/core/TypeErasure.scala]: Why these newlines?

File: src/dotty/tools/dotc/typer/Implicits.scala [hunk 3]
```diff
@@ -479,15 +480,12 @@ trait Implicits { self: Typer =>
       formal.argTypes match {
         case arg :: Nil =>
           val tp = fullyDefinedType(arg, "ClassTag argument", pos)
-          tp.underlyingClassRef(refinementOK = false) match {
```
Comment (xeno-by) [inline src/dotty/tools/dotc/typer/Implicits.scala]: This call was previously returning `NoType` on some refined types. I'm not sure whether the new logic returns false on them.

Comment (odersky) [inline src/dotty/tools/dotc/typer/Implicits.scala]: It's not directly comparable. My point is the new implementation has some justification (stable erasure) where the old one hadn't.

Comment (xeno-by) [inline src/dotty/tools/dotc/typer/Implicits.scala]: Makes sense.

**Comment by xeno-by** [comment]
To the best of my knowledge, lgtm.
