### PR TITLE
Scaladoc - add option for dynamic side menu

### LINKED ISSUE #18543: Scaladoc output size grows to gigabytes with 1000+ input files
Every page generated by Scaladoc (for package, class, object etc...) contains menu on the left, which contains link to every other page. As a result, Scaladoc output size grows quadratically with number of input files.

In case of scala 3 api documentation, with menu it weights ~730MB, without menu less than 200MB. Although this 0.5GB overhead may by acceptable in this case, it gets worse:
Recently tested on 10k+ classes (all rather simple): Scaladoc after about 38 minutes consumed over 140GB of disk space and crashed with `java.io.IOException: No space left on device`. Without menu it generates ~300MB.

I outline 2 proposed solutions below. They both could be hidden behind a flag, so they would be opt-in.

1. Solution not involving javascript - `iframe`
The menu could be generated once into a file, eg `sidemenu.html`. This file could be then included in iframe on every page.
To make the links inside iframe work, we would include `<base target="_parent">` in `sidemenu.html`
Highlighting current item in menu could be done with a little bit of css and target at the end of iframe url.
This would probably look a little worse than 2nd solution.

2. Solution involving javascript
Serialize menu structure into a file, eg `sidemenu.json`, load it with JS and render. Links and highlighting work as before.

Since this would be opt-in, I'm leaning towards second solution.

### PR DESCRIPTION
**Pull request by Florian3k**
Closes #18543 

This PR adds `-dynamic-side-menu` option to Scaladoc.
With this option Scaladoc doesn't generate side menu (packages etc. tree) in html files. Instead it is serialized into .json file and rendered on the client using Javascript.

- [ ] Add documentation for this option in docs.scala-lang (Update: related PR - https://github.com/scala/docs.scala-lang/pull/2942)

### CODE REVIEW

**Comment by bishabosha** [comment]
looking at the linked issue, this is very important for large code bases

**Comment by szymon-rd** [comment]
Did you check it on various browsers?

**Comment by Florian3k** [comment]
Yes, works fine in Chrome, Firefox, Safari.

File: scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala [hunk 1]
```diff
@@ -45,7 +45,8 @@ object Scaladoc:
     apiSubdirectory : Boolean = false,
     scastieConfiguration: String = "",
     defaultTemplate: Option[String] = None,
-    quickLinks: List[QuickLink] = List.empty
+    quickLinks: List[QuickLink] = List.empty,
+    dynamicSideMenu: Boolean = false,
```
Comment (szymon-rd) [inline scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala:49]: I think it should be dynamic as a default for now (so the default behavior doesn't change). We can change it to default after we ensure it works in practice.

**Review by szymon-rd — APPROVED** [review]
Everything looks good, just one comment about keeping the old one as default for some time.

File: scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala (hunk 1 above)
Comment (Florian3k) [reply scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala:49]: `false` is the old behavior

Comment (szymon-rd) [reply scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala:49]: Oh, right, this one `if` confused me. So everything looks alright!

**Comment by Florian3k** [comment]
Also fixes #19371

**Comment by Florian3k** [comment]
I recon https://github.com/scala/docs.scala-lang/pull/2942 should be merged after new Scala version with those changes is released to avoid confusion about new option not working.
cc @szymon-rd?

**Comment by szymon-rd** [comment]
@Florian3k Yes
