### PR TITLE
Disallow `@targetName` on top-level `class`, `trait`, and `object`

### LINKED ISSUE #15066: `@targetName` on toplevel class/trait/object fails separate compilation
## Compiler version

3.2.0-RC1-bin-20220427-b1f00a7-NIGHTLY and earlier

## Minimized code

**Foo.scala**

```scala
@annotation.targetName("Bar") class Foo:
  def it: Int = 42
```

**Test.scala**

```scala
@main def Test = println(Foo().it)
```

## Output

```
$ scalac Foo.scala
$ scalac Test.scala
-- [E006] Not Found Error: Test.scala:1:25 -------------------------------------
1 |@main def Test = println(Foo().it)
  |                         ^^^
  |                         Not found: Foo
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

I understand that supporting `@targetName` on class/trait/object is intentional (see https://github.com/lampepfl/dotty/issues/11969#issuecomment-812090356), thus I would expect such usage to work with separate compilation.

## Remarks

No issue with joint compilation.
No issue if `Foo` is an inner class.

### PR DESCRIPTION
**Pull request by griggt**
This usage was mostly broken, as it failed with separate compilation.

Closes #15066

### CODE REVIEW

**Comment by griggt** [comment]
Draft for now, to allow time for discussion on the ticket.

File: compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala [hunk 1]
```diff
@@ -176,7 +176,8 @@ enum ErrorMessageID extends java.lang.Enum[ErrorMessageID]:
     MatchableWarningID,
     CannotExtendFunctionID,
     LossyWideningConstantConversionID,
-    ImplicitSearchTooLargeID
+    ImplicitSearchTooLargeID,
+    TargetNameOnTopLevelClassID
```
Comment (som-snytt) [inline compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala:180]: Does anyone else feel the need for an end marker, and also trailing comma before end marker?
