### PR TITLE
Keep qualifier of Ident when selecting setter

### LINKED ISSUE #18713: Overloaded assignment operators defined as extension methods across different objects fail to compile
## Compiler version

3.4.0-RC1-bin-20231006-b1ccc6a-NIGHTLY

## Minimized code

Scastie: https://scastie.scala-lang.org/cYHDxwGgQzm3VBWrIHYQhA

a.scala
```Scala
import language.experimental.relaxedExtensionImports
class A(var x: String = "a")
object AA:
    extension (a: A)
        def f = a.x
        def f_=(x: String) = a.x = x
```
b.scala
```Scala
import language.experimental.relaxedExtensionImports
class B(var x: String = "b")
object BB:
    extension (b: B)
        def f = b.x
        def f_=(x: String) = b.x = x
```
main.scala
```Scala
import language.experimental.relaxedExtensionImports
import AA.*
import BB.* 
@main def main() =
    val a = A()
    a.f = "aa"
    println(a.f)
```

## Output

```
sbt:tmp> run
[info] compiling 1 Scala source to /workspaces/tmp/target/scala-3.4.0-RC1-bin-20231006-b1ccc6a-NIGHTLY/classes ...
[error] -- [E052] Type Error: /workspaces/tmp/main.scala:7:8 --------
[error] 6 |    a.f = "aa"
[error]   |    ^^^^^^^^^^
[error]   |    Reassignment to val f
```

If I remove `def f_=(x: String) = b.x = x` from `B` extension, it runs successfully with `run` in sbt console.

When I then add it back, it runs successfully with `run` in sbt console, but fails again on `run` after `clean`, which is potentially a partial compilation bug.

## Expectation

``
aa
``

### PR DESCRIPTION
**Pull request by nicolasstucki**
We already keep the qualifier as a typed splice if the prefix is an explicit Select.

Fixes #18713

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -1119,7 +1119,13 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
           case Apply(fn, _) if fn.symbol.is(ExtensionMethod) =>
             def toSetter(fn: Tree): untpd.Tree = fn match
               case fn @ Ident(name: TermName) =>
-                untpd.cpy.Ident(fn)(name.setterName)
+                fn.tpe match
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1122]: It looks non-sensical that on the one hand we can refer to a lhs with a simple ident, but on the other hand the setter needs a full tree expansion. Can you add a comment why that is so?

**Review by odersky — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1127]: Added a comment

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 2]
```diff
@@ -1119,7 +1119,19 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
           case Apply(fn, _) if fn.symbol.is(ExtensionMethod) =>
             def toSetter(fn: Tree): untpd.Tree = fn match
               case fn @ Ident(name: TermName) =>
-                untpd.cpy.Ident(fn)(name.setterName)
+                // We need to make sure that the prefix of this extension getter is
+                // retained when we transform it into a setter. Otherwise, we could
+                // end up resoving an unrelated setter from another extension. We
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1124]:
```suggestion
                // end up resolving an unrelated setter from another extension. We
```

**Review by odersky — APPROVED** [review]
