### PR TITLE
Fix #5720: don't output X <: Long in Java generic signatures

### LINKED ISSUE #5720: Illegal signature for higher kinded type with AnyVal upper bound
While testing another patch, I got this output:
```
[info] Test dotty.tools.dotc.CompilationTests.fuzzyAll started
<B:J>Ljava/lang/Object;: ':' expected at index 4ted (115/146, 0 failed, 2s)
<B:J>()V: ':' expected at index 4
[=======================================] completed (146/146, 0 failed, 3s)
```

Grep suggests that might be coming from https://github.com/lampepfl/scala/blob/9ef70dd9b9eeec11cfb72dabb57c61198fa18a20/src/asm/scala/tools/asm/util/CheckClassAdapter.java#L993.

Noting this for future usage, can't investigate right now...

### PR DESCRIPTION
**Pull request by Blaisorblade**
In generic signature generator `jsig`, flag `primitiveOK` remembers if `jsig` is
allowed to output primitive types or not; for instance, upper bounds can't
contain primitive types. When transforming higher-kinded upper bounds `[X] =>
T`, `jsig` correctly recurs on `T`, but must remember flag `primitiveOK`.

The status of `toplevel` should not change either (since it tracks if are still
at the toplevel of the output signature, or instead we have started producing
output), so passing it seems safest. Ideally we should test it at least on
higher types whose body is a suitable `ClassInfo`; with polymorphic function
types, we should also test `PolyType` bodies.

Fix #5720.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala [hunk 1]
```diff
@@ -283,7 +283,7 @@ object GenericSignatures {
           jsig(atp, toplevel, primitiveOK)
 
         case hktl: HKTypeLambda =>
-          jsig(hktl.finalResultType)
+          jsig(hktl.finalResultType, toplevel, primitiveOK)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: recursive methods with default parameters are dangerous and I almost think we should warn when this happens. In any case, I suggest removing the default parameters from this method to avoid this issue in the future.

File: tests/pos/i5720.scala [hunk 2]
```diff
@@ -0,0 +1,5 @@
+class A[B[_] <: Long]
```
Comment (smarter) [inline tests/pos/i5720.scala]: Can you confirm that we get a failed test for this file without the fix ?

Comment (Blaisorblade) [reply tests/pos/i5720.scala]: Yes.

File: compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala (hunk 1 above)
Comment (Blaisorblade) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: Most calls seem to intentionally drop the params. Many times that's appropriate, some times I'm not sure.
Sadly too many other deadlines to review this in depth right now...

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala]: OK, let's keep as-is to minimize the diff with the scalac implementation then.

**Comment by Blaisorblade** [comment]
Failures are in master apparently... http://dotty-ci.epfl.ch/lampepfl/dotty/10135/4.

**Comment by Blaisorblade** [comment]
Still todo: maybe move tests/fuzzy/IAE-4a69457e1319217c3bac170110ea4ba58dca11a6.scala to `pos` (or drop it, as it's a subset of the new test).

**Comment by smarter** [comment]
fixed master: https://github.com/lampepfl/dotty/pull/5818

**Comment by smarter** [comment]
@biboudis Your bot keeps assigning people to PR, can you make it stop ?

File: tests/pos/i5720.scala (hunk 2 above)
Comment (nicolasstucki) [inline tests/pos/i5720.scala]: I would also add some tests in the form of 

```scala
class A[B[_] <: Foo]
class Foo(val i: Int) extends AnyVal
```

Comment (nicolasstucki) [reply tests/pos/i5720.scala]: And with an opaque type that has a primitive type

Comment (nicolasstucki) [reply tests/pos/i5720.scala]: We should also have tests for all primitives
```scala
class AByte[B[_] <: Byte]
...
class AInt[B[_] <: Int]
...
```

**Comment by nicolasstucki** [comment]
The fix LGTM

**Comment by biboudis** [comment]
> @biboudis

looking into it!
