### PR TITLE
Close Files.lines stream

### LINKED ISSUE #14376: Vulpix leaks file handles
## Compiler version

3.1.3-RC1

## Minimized example

Since the latest upgrade I get this on MacOS:

**sbt:scala3> scala3-bootstrapped/testOnly dotty.tools.dotc.CompilationTests
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-interfaces / Test / testOnly
[info] compiling 7 Scala sources to /Users/odersky/workspace/dotty/compiler/target/scala-3.1.2-RC1/classes ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-sbt-bridge / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-library-bootstrapped / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for tasty-core-bootstrapped / Test / testOnly
[info] compiling 4 Scala sources to /Users/odersky/workspace/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] compiling 15 Scala sources to /Users/odersky/workspace/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] compiling 1 Scala source to /Users/odersky/workspace/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/test-classes ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-bootstrapped / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scaladoc / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-staging / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-language-server / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-tasty-inspector / Test / testOnly
[info] Test run started
[info] Test dotty.tools.dotc.CompilationTests.negAll started
[=======================================] completed (1366/1366, 0 failed, 54s)
[info] Test dotty.tools.dotc.CompilationTests.runAll started
[=======================================] completed (1418/1418, 0 failed, 69s)
[info] Test dotty.tools.dotc.CompilationTests.pickling started
[=======================================] completed (3636/3636, 0 failed, 57s)
[info] Test dotty.tools.dotc.CompilationTests.rewrites started
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (6/6, 0 failed, 0s)
[info] Test dotty.tools.dotc.CompilationTests.pos started
[=======================================] completed (2655/2655, 0 failed, 64s)
[info] Test dotty.tools.dotc.CompilationTests.checkInit started
[=======================================] completed (139/139, 0 failed, 0s)
[=======================================] completed (38/38, 0 failed, 0s)
[=======================================] completed (23/23, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[info] Test dotty.tools.dotc.CompilationTests.posTwice started
[=======================================] completed (133/133, 0 failed, 10s)
[info] Test dotty.tools.dotc.CompilationTests.explicitNullsPos started
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/flow-while-loop.scala
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/i13608.scala
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/flow-match.scala
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/opaque-nullable.scala
Fatal compiler crash when compiling: tests/explicit-nulls/pos/flow-while-loop.scala:
/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at dotty.tools.io.Directory.list(Directory.scala:51)
	at dotty.tools.io.PlainFile.iterator(PlainFile.scala:92)
	at scala.collection.View$Filter.iterator(View.scala:144)
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #14376

### CODE REVIEW

File: compiler/test/dotty/tools/utils.scala [hunk 1]
```diff
@@ -47,7 +47,11 @@ def assertThrows[T <: Throwable: ClassTag](p: T => Boolean)(body: => Any): Unit
 end assertThrows
 
 def toolArgsFor(files: List[JPath], charset: Charset = UTF_8): List[String] =
-  files.flatMap(path => toolArgsParse(Files.lines(path, charset).limit(10).toScala(List)))
+  files.flatMap(path => toolArgsParse {
+    val stream = Files.lines(path, charset)
+    try stream.limit(10).toScala(List)
+    finally stream.close()
+  })
```
Comment (smarter) [inline compiler/test/dotty/tools/utils.scala:54]: We normally use scala.util.Using for this:
```suggestion
  files.flatMap(path => toolArgsParse(Using(Files.lines(path, charset))(_.limit(10).toScala(List))))
```

**Review by dwijnand — APPROVED** [review]
I assumed "toScala(List)" were just as much as "terminal operation" as `toArray` is on j.u.s.Stream.  Almost feel like it's a bug that it isn't - it even says:

>      * then converted to the target collection. Note that the stream is processed eagerly while
>      * building the accumulator, even if the target collection is lazy.

Sorry for the bug.

**Comment by dwijnand** [comment]
Oh, nvm, terminal doesn't mean close apparently.  https://stackoverflow.com/a/27382060/463761
