### PR TITLE
Fix capture set variable installation in Setup

### LINKED ISSUE #18881: Capture set inference interacts problematically with inferred impure type variables
## Compiler version

`main`

## Minimized code

```Scala
import language.experimental.captureChecking

trait Resource
def id[X](x: X): x.type = x
def foo[M <: Resource](r: M^) = id(r)
```

## Output

```scala
-- [E007] Type Mismatch Error: issues/cc-setup-impure-classes.scala:5:35 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
5 |def foo[M <: Resource](r: M^) = id(r)
  |                                   ^
  |                                   Found:    (r : M^)
  |                                   Required: M
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

It should work.

### PR DESCRIPTION
**Pull request by Linyxus**
Fixes #18881

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/cc/Setup.scala [hunk 1]
```diff
@@ -555,17 +556,18 @@ class Setup extends PreRecheck, SymTransformer, SetupAPI:
           sym == defn.AnyClass
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/cc/Setup.scala:556]: I think this clause is now redundant. `AnyClass` is not a pure class.

**Review by odersky — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/cc/Setup.scala (hunk 1 above)
Comment (Linyxus) [reply compiler/src/dotty/tools/dotc/cc/Setup.scala]: Thanks! it is now fixed

**Review by odersky — APPROVED** [review]
LGTM!
