### PR TITLE
Fix #1503: be more careful where to insert apply

### LINKED ISSUE #1503: Anonymous functions direct application crash the compiler.
```scala
object Foo {
  (new Function0[Unit] {
    def apply() = println("hello")
  })()
}
```

Note that this does not fail if the `apply` method is written explicitly.

```
Exception in thread "main" java.lang.Error: unexpected type.
 fun = Block(List(TypeDef($anon,Template(DefDef(<init>,List(),List(List()),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,scala)),Unit)],EmptyTree),List(Apply(Select(New(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,lang)),Object)]),<init>),List()), AppliedTypeTree(Ident(Function0),List(Ident(Unit)))),ValDef(_,EmptyTree,EmptyTree),List(DefDef(apply,List(),List(List()),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,$anon)),scala$Function0$$R)],Apply(Ident(println),List(Literal(Constant(hello))))))))),Typed(Select(Apply(Select(New(Ident($anon)),<init>),List()),apply),TypeTree[MethodType(List(), List(), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala),Unit))])),
 methPart(fun) = Typed(Select(Apply(Select(New(Ident($anon)),<init>),List()),apply),TypeTree[MethodType(List(), List(), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala),Unit))]),
 methPart(fun).tpe = MethodType(List(), List(), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala),Unit)),
 tpe = MethodType(List(), List(), TypeRef(TermRef(ThisType(TypeRef(NoPrefix,<root>)),scala),Unit))
	at dotty.tools.dotc.typer.Applications$class.handleUnexpectedFunType(Applications.scala:661)
	at dotty.tools.dotc.typer.Typer.handleUnexpectedFunType(Typer.scala:60)
	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.dotty$tools$dotc$typer$Applications$class$$anonfun$$simpleApply$1(Applications.scala:577)
	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1$$anonfun$apply$5.apply(Applications.scala:603)
	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1$$anonfun$apply$5.apply(Applications.scala:603)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:1472)
	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:604)
	at dotty.tools.dotc.typer.Applications$$anonfun$realApply$1$1.apply(Applications.scala:544)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Applications$class.realApply$1(Applications.scala:544)
	at dotty.tools.dotc.typer.Applications$class.typedApply(Applications.scala:647)
	at dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:60)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1376)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1417)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1427)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1425)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:155)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:56)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1425)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1455)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1460)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1196)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:1144)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1144)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1367)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1415)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1427)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1425)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:155)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:56)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1425)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1449)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1460)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1292)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1283)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1283)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1405)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1417)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1427)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1425)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:155)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:56)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1425)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1464)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$typeCheck$1.apply$mcV$sp(FrontEnd.scala:47)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:23)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:45)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:69)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:69)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:69)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:69)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:66)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:66)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:60)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:60)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:60)
	at dotty.tools.dotc.Run.compileSources(Run.scala:57)
	at dotty.tools.dotc.Run.compile(Run.scala:41)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:26)
	at dotty.tools.dotc.Driver.process(Driver.scala:124)
	at dotty.tools.dotc.Driver.process(Driver.scala:93)
	at dotty.tools.dotc.Driver.process(Driver.scala:105)
	at dotty.tools.dotc.Driver.main(Driver.scala:132)
	at dotty.tools.dotc.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #1503 and related problems which are presented in i1503.scala. 

This was a more fundamental problem to type inference than it appeared at first.

Review by @nicolasstucki or @felixmulder or @smarter.

### CODE REVIEW

File: src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -927,15 +927,25 @@ object Types {
     def narrow(implicit ctx: Context): TermRef =
       TermRef(NoPrefix, ctx.newSkolem(this))
 
-    /** Useful for diagnsotics: The underlying type if this type is a type proxy,
+   /** Useful for diagnsotics: The underlying type if this type is a type proxy,
      *  otherwise NoType
```
Comment (felixmulder) [inline src/dotty/tools/dotc/core/Types.scala]: Nitpick: weird indent doesn't match next row

File: src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -927,15 +927,25 @@ object Types {
...
-    // ----- Normalizing typerefs over refined types ----------------------------
+    /** A "weak" prototype is a FunProto or a PolyProto that applies to a tree
+     *  properly containing the current expression. In that case, we should not
+     *  try to insert an apply to make a tree conform. The apply should be inserted
+     *  on the enclosing tree that is the function part of the actual application.
+     */
+    def isWeakProto: Boolean = false
+
+	/** Overridden in FunProto and PolyProto */
+    def weakenProto: Type = this
```
Comment (felixmulder) [inline src/dotty/tools/dotc/core/Types.scala]: Same on 945-946

**Comment by smarter** [comment]
This now compiles:
```scala
  val foo = () => println("hi")
  val bar = () => println("there")

  (if (1 == 1) foo else bar)()
```
But this doesn't:
```scala
  def foo() = println("hi")
  def bar() = println("there")

  (if (1 == 1) foo else bar)()
```
Stack trace: https://gist.github.com/smarter/91f610d4efb8cdaedff16d9b032d346c

(With scalac, `foo` and `bar` get applied:
```scala
error: Unit does not take parameters
  (if (1 == 1) foo else bar)()
                            ^
```
)

**Comment by odersky** [comment]
@smarter Well spotted. I replaced the PR with a new version which fixes the problem and is simpler than the previous one.

**Comment by smarter** [comment]
That's similar to a fix we tried with Felix except we gave up when we got type errors and didn't try to introduce something like `InfixOpBlock`, nice that this works!

File: src/dotty/tools/dotc/core/Types.scala [hunk 3]
```diff
@@ -927,15 +927,18 @@ object Types {
...
+    /** Useful for diagnostics: The underlying type if this type is a type proxy,
      *  otherwise NoType
      */
     def underlyingIfProxy(implicit ctx: Context) = this match {
       case this1: TypeProxy => this1.underlying
       case _ => NoType
     }
 
-    // ----- Normalizing typerefs over refined types ----------------------------
+	/** If this is a FunProto or PolyProto, WildcardType, otherwise this */
```
Comment (smarter) [inline src/dotty/tools/dotc/core/Types.scala]: - Two extra spaces in the indentation
- This comment should explain the purpose of `notApplied` like the commit message does

File: src/dotty/tools/dotc/typer/Typer.scala [hunk 4]
```diff
@@ -572,7 +572,8 @@ class Typer extends Namer with TypeAssigner with Applications with Implicits wit
   def typedBlock(tree: untpd.Block, pt: Type)(implicit ctx: Context) = track("typedBlock") {
     val exprCtx = index(tree.stats)
     val stats1 = typedStats(tree.stats, ctx.owner)
-    val expr1 = typedExpr(tree.expr, pt)(exprCtx)
+    val ept = if (tree.isInstanceOf[untpd.InfixOpBlock]) pt else pt.notApplied
```
Comment (smarter) [inline src/dotty/tools/dotc/typer/Typer.scala]: Add a comment explaining why `InfixOpBlock` is treated specially here, also a `match` would be cleaner and safer than `isInstanceOf`

File: src/dotty/tools/dotc/core/Types.scala (hunk 3 above)
Comment (smarter) [inline src/dotty/tools/dotc/core/Types.scala]: I'm also not entirely sure why using `WildcardType` does not break type inference in some cases, maybe this could be explained here
