### PR TITLE
Fix #10951: update typedDynamicSelect

### LINKED ISSUE #10951: Error when using tuple type with selectDynamic method syntax
## Minimized code

```Scala
import scala.language.dynamics
object Dyn extends Dynamic:
  def selectDynamic[T](name: String): Option[T] = None

val a: Option[(Int, Int)] = Dyn.asdf[Tuple2[Int, Int]] // works fine
val b: Option[(Int, Int)] = Dyn.selectDynamic[(Int, Int)]("asdf") // works fine
val c: Option[(Int, Int)] = Dyn.asdf[(Int, Int)] // fails
```

## Output

```scala
scala> import scala.language.dynamics

scala> object Dyn extends Dynamic:
     |   def selectDynamic[T](name: String): Option[T] = None
     |
// defined object Dyn

scala> val a: Option[(Int, Int)] = Dyn.asdf[Tuple2[Int, Int]] // works fine
val a: Option[(Int, Int)] = None

scala> val b: Option[(Int, Int)] = Dyn.selectDynamic[(Int, Int)]("asdf") // works fine
val b: Option[(Int, Int)] = None

scala> val c: Option[(Int, Int)] = Dyn.asdf[(Int, Int)] // fails
1 |val c: Option[(Int, Int)] = Dyn.asdf[(Int, Int)] // fails
  |                                      ^
  |cannot infer type; expected type class dotty.tools.dotc.typer.ProtoTypes$AnyTypeConstructorProto$ is not fully defined
```

## Expectation
the last line `val a: Option[(Int, Int)] = Dyn.asdf[(Int, Int)]` should return `None` rather than report an error. Running this in a scala 2.13.4 repl outputs the expected results.

### PR DESCRIPTION
**Pull request by albertpchen**
fixes https://github.com/lampepfl/dotty/issues/10951
pass `List[untpd.Tree]` to `typedDynamicSelect` instead of `List[Tree]`. This resolves the issue, but I have no idea if this is the correct fix. just seemed like the solution based on how `typedDynamicApply` is implemented.

### CODE REVIEW

**Comment by albertpchen** [comment]
could someone restart the CLA check please?

**Review by odersky — CHANGES_REQUESTED** [review]
That change would re-typecheck the function arguments. This is usually a big no-no, since arguments can be arbitrarily large and arbitrarily nested. So there's a risk of an exponential performance blowup for certain cases.

Can we find a way to do this without throwing away the types of the arguments?

**Comment by albertpchen** [comment]
I added `MemoizedTypeTree`  to save the typed args and pass them along to the other typing methods. I'm not that familiar with the code so sorry if this is a terrible hack

File: compiler/src/dotty/tools/dotc/typer/Applications.scala [hunk 1]
```diff
@@ -1076,7 +1076,7 @@ trait Applications extends Compatibility {
           case _ =>
         }
         def tryDynamicTypeApply(): Tree = typedFn match {
-          case typedFn: Select if !pt.isInstanceOf[FunProto] => typedDynamicSelect(typedFn, typedArgs, pt)
+          case typedFn: Select if !pt.isInstanceOf[FunProto] => typedDynamicSelect(typedFn, typedArgs.map(untpd.MemoizedTypeTree(_)), pt)
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Applications.scala:1079]: Let's see whether we find a way to avoid `MemoizedTypeTree`. Why did it not work with `typedArgs` in the first place? What issue gets fixed by wrapping the arguments in `MemoizedTypeTree`?

Comment (albertpchen) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:1079]: the issue with `typedArgs` was that after
`tree.args: List(Tuple(List(Ident(Int), Ident(Int))))`

gets typed to
`typedArgs: List(AppliedTypeTree(TypeTree[TypeRef(...,class Tuple2)],List(Ident(Int), Ident(Int))))`

it fails when it tries to type check the `AppliedTypeTree` again because `typedAppliedTypeTree` sets `pt` to `AnyTypeConstructorProto`
https://github.com/lampepfl/dotty/blob/04ea25cfe9c77f612964ba306f070ba058ee695c/compiler/src/dotty/tools/dotc/typer/Typer.scala#L1700-L1703

So I wrapped `typedArgs` with `MemoizedTypeTree` so that `typedTypeTree` could know that the args were already type checked and return the cached results instead of an error type. doing a `hasType` check + cast worked as well, but having an explicit memoize  type tree seemed like a safer solution.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala:1079]: Thanks for explaining! We actually already have an analogous memoization mechanism in place. It's `untpd.TypedSplice`. Can you try to simply replace `MemoizedTypeTree` with `untpd.TypedSplice`?

Comment (albertpchen) [reply compiler/src/dotty/tools/dotc/typer/Applications.scala]: thanks for the suggestion! i've updated the PR

**Review by odersky — APPROVED** [review]
Looks all good now. Thanks for the fix!
