### PR TITLE
Scaladoc: type rendering fixes and improvements

### LINKED ISSUE #16024: ScalaDoc shows wrong type for this.type
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized example

In Tuple.scala:

```Scala
  inline def map[F[_]](f: [t] => t => F[t]): Map[this.type, F] =
    runtime.Tuples.map(this, f).asInstanceOf[Map[this.type, F]]
```

## Output

Scaladoc output:

<html>
def [map](https://dotty.epfl.ch/api/scala/Tuple.html#map-fffff3e7)[F[_]](f: [t] => (x$1: t) => F[t]): [Map](https://dotty.epfl.ch/api/scala/Tuple$.html#Map-0)[[Tuple](https://dotty.epfl.ch/api/scala/Tuple.html), F]
Called on a tuple (a1, ..., an), returns a new tuple (f(a1), ..., f(an)). The result is typed as (F[A1], ..., F[An]) if the tuple type is fully known. If the tuple is of the form a1 *: ... *: Tuple (that is, the tail is not known to be the cons type.
</html>

## Expectation

`this.type` should be rendered as `this.type`, not `Tuple`. The two have very different meanings. I am not sure whether other singleton types are rendered correctly, we should check that as well.

### LINKED ISSUE #16057: Doc website: `<none>` instead of dependent return type
For example:
nightly:
https://dotty.epfl.ch/api/scala/Tuple$.html#fromProductTyped-96d
3.2.0:
https://scala-lang.org/api/3.x/scala/Tuple$.html#fromProductTyped-96d

### LINKED ISSUE #16084: Discrepancy in signature of `Tuple.splitAt` between api website and implementation
(Also on 3.2.0)
https://dotty.epfl.ch/api/scala/Tuple.html#
Displays:
```scala
inline def splitAt[This >: Tuple <: Tuple](n: Int): (This, Int)
```
Whereas the signature in the implementation is:
```scala
inline def splitAt[This >: this.type <: Tuple](n: Int): Split[This, n.type]
```
https://github.com/lampepfl/dotty/blob/main/library/src/scala/Tuple.scala#L79

### LINKED ISSUE #16143: Prefix in path dependent type lost in scaladoc
## Compiler version

3.2.2-RC1-bin-20221003-5d1497d-NIGHTLY

## Minimized code

```scala
trait Foo[A]:
  type Out

trait Bar[A]:
  type Out

def foo[A](using f: Foo[A])(using b: Bar[f.Out]): b.Out = ???
```

## Output

`foo` is shown in the docs as  

```scala
def foo[A](using f: Foo[A])(using b: Bar[Out]): Out
```

## Expectation

The path prefixes should not be lost from the result type, so `Out` should be `f.Out` or `b.Out`, as defined in the source code. The prefixes should be always preserved - even if there's no ambiguity within a signature.

### PR DESCRIPTION
**Pull request by Florian3k**
This PR introduces multiple fixes and improvements to type rendering in Scaladoc

- Fixed rendering of TypeRefs (`A#B`) and TermRefs (`a.b.type`)
- Fixed rendering of `Tuple1[T]` (previously `(T)`)
- Fixed rendering of `this.type` (except for type bounds, see below)
- Types with `@showAsInfix` are rendered infix
- Correct parenthesizing around infix types, `&` types, `|` types and function types
- Type parameters of superclasses in inherited methods are substituted with actual types from inheriting class/trait (see `scaladoc-testcases/src/tests/supertypeParamsSubstitution.scala`)
https://github.com/lampepfl/dotty/pull/17213/files#diff-93a78912075a9fdb34fefa437d191be59888cb723ccb244374e77033d9eca779R12-R20
- `this` and `type` are highlighted as keywords

fixes #16024
fixes #16143
fixed #16057
fixes #16084 (partially) - fixed rendering of `Int` instead of `n.type` and `(This, n.type)` instead of `Split[This, n.type]`. `this.type` in type bounds remains unfixed. I created separate issue for that #17226

Documentation with those changes has been deployed to https://scala3doc.virtuslab.com/pr-types-rendering-fixes/scala3/api/index.html

### CODE REVIEW

File: scaladoc-testcases/src/tests/functionTypeSignatures.scala [hunk 1]
```diff
@@ -2,9 +2,15 @@ package tests.functionTypeSignatures
 
 type A = ((Int, Int)) => Int
 
-type B = (Int | String) => Int
+type B = (Int | String) => Int //expected: type B = Int | String => Int
```
Comment (Sporarum) [inline scaladoc-testcases/src/tests/functionTypeSignatures.scala:5]: (Same here)
```suggestion
type B = (Int | String) => Int
```

**Review by Sporarum — CHANGES_REQUESTED** [review]
Looks amazing, great job !

I think we should keep/add parens anytime it's ambiguous however, see the proposed changes for more details

File: scaladoc-testcases/src/tests/infixTypes.scala [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+trait ***[A, B]
+
+trait **:[A, B]
+
+def foo[A, B, C, D]: (A SomeTrait B) +++ (C SomeTrait2 D) //expected: def foo[A, B, C, D]: (A SomeTrait B) +++ SomeTrait2[C, D]
+  = ???
+
+// left-associative, same precedence
+
+def a0[X, Y, Z]: X +++ Y +++ Z //expected: def a0[X, Y, Z]: (X +++ Y) +++ Z
```
Comment (Sporarum) [inline scaladoc-testcases/src/tests/infixTypes.scala:33]: If the operator is exactly the same, would it be possible to drop parens then ? ^^'

File: scaladoc-testcases/src/tests/thisType.scala [hunk 3]
```diff
@@ -0,0 +1,8 @@
+package tests
+package thisType
+
+// issue 16024
+
+class X[Map[_, _[_]]]:
+  inline def map[F[_]](f: [t] => t => F[t]): Map[this.type, F] = //expected: inline def map[F[_]](f: [t] => (x$1: t) => F[t]): Map[this.type, F]
```
Comment (Sporarum) [inline scaladoc-testcases/src/tests/thisType.scala:7]: More nitpicking:
Would it be possible to only print the identifier (`x$1`) if it is required ?

Ex: `[t] => (x: t) => t`

I see two ways of doing so:
1. Look at whether the name is synthetic/mangled: ex prints as `[t] => (x: t) => t`
1. Look at whether the name is used on the rhs: ex prints as `[t] => t => t`

File: scaladoc-testcases/src/tests/exports1.scala [hunk 4]
```diff
@@ -14,18 +14,18 @@ class A: //unexpected
    = 1
   var aVar1: 1
    = 1
-  type HKT[T[_], X] //expected: final type HKT = [T[_], X] =>> HKT[T, X]
+  type HKT[T[_], X] //expected: final type HKT = [T[_], X] =>> a.HKT[T, X]
```
Comment (Sporarum) [inline scaladoc-testcases/src/tests/exports1.scala:17]: I'm not sure I understand why we need the `a`/`A` in theses, could you explain ?

**Review by Sporarum — APPROVED** [review]
Thank you for addressing my comments

I found some other things, feel free to address them as well if you want to ^^
(I consider them non-blocking)

File: scaladoc-testcases/src/tests/infixTypes.scala (hunk 2 above)
Comment (Florian3k) [reply scaladoc-testcases/src/tests/infixTypes.scala:33]: Yes, it is possible, but then the associativity of the operator is not immediately obvious. I can change that, but not sure if we want to.

File: scaladoc-testcases/src/tests/thisType.scala (hunk 3 above)
Comment (Florian3k) [reply scaladoc-testcases/src/tests/thisType.scala:7]: I'll look into that.

File: scaladoc-testcases/src/tests/infixTypes.scala (hunk 2 above)
Comment (Sporarum) [reply scaladoc-testcases/src/tests/infixTypes.scala:33]: Hmm, I see what you mean, I think since the associativity rule is purely syntactic (operator ends with `:`) it makes sense to drop the parens

To me the former is easier to read than the latter:
```scala
X *: Y *: Z *: tuple
```
vs
```scala
X *: (Y *: (Z *: tuple))
```

What do others think ?

File: scaladoc-testcases/src/tests/exports1.scala (hunk 4 above)
Comment (Florian3k) [reply scaladoc-testcases/src/tests/exports1.scala:17]: This file is part of test consisting of 2 files: `exports1.scala` and `exports2.scala`

The test:
https://github.com/lampepfl/dotty/blob/ef974367932cb148bda152ed056183f319a9a2fc/scaladoc/test/dotty/tools/scaladoc/signatures/TranslatableSignaturesTestCases.scala#L96

`exports2.scala` for reference:
https://github.com/lampepfl/dotty/blob/ef974367932cb148bda152ed056183f319a9a2fc/scaladoc-testcases/src/tests/exports2.scala#L1-L12

So it's testing for exported member signatures in `class B`.

Signatures are rendered based on `TypeRepr` from Tasty.
For example `TypeRepr` for `val x: HKT[List, Int]` rendered in `class B` looks like this:
```scala
AppliedType(
  TypeRef(
    ThisType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class tests)),object exports1),class A)), // TypeRepr for class A
    type HKT
  ),
  List(
    TypeRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),package),List), // TypeRepr for List
    TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),Int) // TypeRepr for Int
  )
)
```
Based solely on this representation, signature that should be rendered is `A#HKT[List, Int]`

To be honest, I'm not sure entirely whether this is correct way to render signatures of exported members.
If this is not correct, we may want to apply some additional logic for checking if current signature is of an exported member and render it in a different way, but I'm probably gonna need some help with that.

Comment (Sporarum) [reply scaladoc-testcases/src/tests/exports1.scala:17]: @sjrd or @bishabosha, you are very familiar with tasty, what do you think ?

Comment (sjrd) [reply scaladoc-testcases/src/tests/exports1.scala:17]: `a.HKT[T, X]` seems absolutely correct to me. Otherwise you would be defining `B.HKT` in terms of itself.

The `A#HKT[List, Int]` seem a bit suspicious to me. `this` prefix substitution (the so-called `asSeenFrom` operation) should be replacing `this.HKT[List, Int]` from `A` by `a.HKT[List, Int]` when created by an `export a._`.

In fact, the `TypeRef` seems even more suspicious. As is, it means `A.this.HKT`, not really `A#HKT`. But that's quite bad if that's the type given to a member of `B`, since such a type is only valid when you're inside `A`. It seems the compiler is doing something wrong here.

From the point of view of Scaladoc, I think it should display `A.this.HKT` for the `TypeRef(ThisType(A), type HKT)`.

**Comment by Florian3k** [comment]
@Sporarum I fixed rendering of `ThisType` and removed parens around occurrences of the same operator

File: scaladoc-testcases/src/tests/thisType.scala (hunk 3 above)
Comment (Florian3k) [reply scaladoc-testcases/src/tests/thisType.scala:7]: Let's leave that for future improvements.

**Comment by Sporarum** [comment]
Perfect, then from my point of view, this is good to merge !

**Review by Sporarum — APPROVED** [review]

File: scaladoc-testcases/src/tests/thisType.scala (hunk 3 above)
Comment (Sporarum) [reply scaladoc-testcases/src/tests/thisType.scala:7]: Could you open an issue for it ?

Comment (Florian3k) [reply scaladoc-testcases/src/tests/thisType.scala:7]: Done: https://github.com/lampepfl/dotty/issues/17756
