### PR TITLE
Fix #13523: Survive missing Java inner annotation classfiles

### LINKED ISSUE #13523: `Bad symbolic reference` when a java classfile refers to an annotation inner class not on the classpath
## Compiler version

Compiler version: 3.1.0-RC1

## Minimized code

```Scala
object Bot extends App {
  val token = sys.env("DISCORD_TEST_BOT")
  val gid = sys.env("GUILD_ID")
  val client: GatewayDiscordClient = (DiscordClient.create(token).login().block())
  val pingCmd = (ApplicationCommandRequest.builder()
                   .name ("ping")
                   .description ("Test ping command")
                   .build)

  val restClient = client.getRestClient
  val appId = restClient.getApplicationId.block

  (restClient
     .getApplicationService
     .createGuildApplicationCommand (appId, Snowflake.asLong(gid), pingCmd)
     .doOnError (err ⇒ println(s"Can't create command: ${err}"))
     .onErrorResume (e ⇒ Mono.empty())
     .block)

  (client
     on new ReactiveEventAdapter() {
       val cooldown_table = Map[Long, ZonedDateTime]()

       override def onSlashCommand(evt: SlashCommandEvent) = {
         if(evt.getCommandName() == "ping") {
         val reply = evt
           .getInteraction()
           .getMember()
           .toScala
           .map(mem ⇒ { "pong" })
           .getOrElse("Error: no member")
           evt.reply(reply)
         } else {
           Mono.empty()
         }
       }
     }
     blockLast)
}

```

## Output

```scala
[error] Bad symbolic reference. A signature
[error] refers to Value/T in package org.immutables.value which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
[warn] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[warn] externalName = org.immutables.value.Value$Immutable,
[warn] outerName = org.immutables.value.Value,
[warn] innerName = Immutable
[warn] owner.fullName = org.immutables.value.Value
[warn] while parsing ~/.cache/coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/com/discord4j/discord4j-core/3.2.0-SNAPSHOT/discord4j-core-3.2.0-20210908.030540-190.jar(discord4j/core/spec/InteractionApplicationCommandCallbackReplyMonoGenerator.class) while parsing annotations in ~/.cache/coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/com/discord4j/discord4j-core/3.2.0-SNAPSHOT/discord4j-core-3.2.0-20210908.030540-190.jar(discord4j/core/spec/InteractionApplicationCommandCallbackReplyMonoGenerator.class)
[warn] 5 warnings found
```

## Expectation

The code compiles (and run as expected) with the `Scala 2` compiler but give me this error message when compiling with the `Scala 3` compiler.

The full code and `sbt` build file can be found here: https://github.com/n3f4s/scala3D4j3.2ErrorMWE

### PR DESCRIPTION
**Pull request by griggt**
Co-authored-by: Seth Tisue <seth@tisue.net>

Fixes #13523

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
So this is really Tom's fix and I served as reviewer / sounding board. We looked at Guillaume's previous fix together, and then he walked me through this fix, and we discussed it from every angle either of us could think of. Conclusion: LGTM :+1:

(Minor point, I did suggest that the test be in a package rather than in the empty package, since the empty package is a special case, and to be sure that it still worked in the presence of a package prefix.)

Might be good to have one more reviewer, probably @smarter since this is so closely related to his previous fix (#9096).

File: compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala [hunk 1]
```diff
@@ -1127,7 +1127,11 @@ class ClassfileParser(
       val outerName = entry.strippedOuter
       val innerName = entry.originalName
       val owner = classNameToSymbol(outerName)
-      val result = atPhase(typerPhase)(getMember(owner, innerName.toTypeName))
+      val result = owner.denot.infoOrCompleter match
+        case _: StubInfo if hasAnnotation(entry.jflags) =>
+          requiredClass(innerName.toTypeName)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala:1132]: Since this is not obvious, could you add a comment explaining why this is needed and pointing the reader to the test case?

**Review by smarter — APPROVED** [review]
Otherwise LGTM, thanks!
