### PR TITLE
Heal type within quote internal encoding

### LINKED ISSUE #11587: Type not handled correctly in multistage quote
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
import scala.quoted._
class Foo:
  def foo[T: Type](using Quotes): Unit = '{
    def toExpr(using Quotes): Expr[T] = '{ ??? : T }
  }
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: unresolved symbols: type T (line 2) #5195 when pickling tests/run-macros/quoted-liftable-derivation-macro/Derivation_1.scala while compiling tests/run-macros/quoted-liftable-derivation-macro/Derivation_1.scala
java.lang.AssertionError: assertion failed: unresolved symbols: type T (line 2) #5195 when pickling tests/run-macros/quoted-liftable-derivation-macro/Derivation_1.scala
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.core.tasty.TreePickler.pickle(TreePickler.scala:782)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickle(PickledQuotes.scala:168)
        at dotty.tools.dotc.quoted.PickledQuotes$.pickleQuote(PickledQuotes.scala:37)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickleAsTasty$1(PickleQuotes.scala:222)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.pickledQuote(PickleQuotes.scala:305)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transformQuotation(PickleQuotes.scala:142)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:114)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1315)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:148)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1321)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:120)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:148)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
        at scala.collection.immutable.List.mapConserve(List.scala:472)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1335)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:92)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:136)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:99)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:148)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.traverse$1(TreeMapWithImplicits.scala:53)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transformStats(TreeMapWithImplicits.scala:60)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:111)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:148)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1398)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:104)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:148)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
        at scala.collection.immutable.List.mapConserve(List.scala:472)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1407)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:104)
        at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:85)
        at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:148)
        at dotty.tools.dotc.transform.PickleQuotes$QuoteReifier.transform(PickleQuotes.scala:514)
        at dotty.tools.dotc.transform.PickleQuotes$$anon$1.transform(PickleQuotes.scala:95)
        at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:21)
        at dotty.tools.dotc.transform.PickleQuotes.run(PickleQuotes.scala:91)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
        at scala.collection.immutable.List.map(List.scala:246)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
        at dotty.tools.dotc.Run.compileSources(Run.scala:166)
        at dotty.tools.dotc.Run.compile(Run.scala:150)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:198)
        at dotty.tools.dotc.Driver.process(Driver.scala:166)
        at dotty.tools.dotc.Driver.process(Driver.scala:178)
        at dotty.tools.dotc.Driver.main(Driver.scala:208)
        at dotty.tools.dotc.Main.main(Main.scala)```
</details>

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #11587

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 1]
```diff
@@ -118,7 +118,19 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
...
+        val heal = new TypeMap {
+          def apply(tp: Type) = tp match {
+            case AnnotatedType(parent, annot) => AnnotatedType(mapOver(parent), annot)
+            case _ => healTypeOfTerm(fn1.srcPos)(tp)
+          }
+        }
+        val targs1 = targs.map(targ => TypeTree(heal(targ.tpe)))
+        cpy.Apply(quote)(cpy.TypeApply(fn1)(fn0, targs1), body2 :: Nil)
+      case quote: TypeApply =>
+        cpy.TypeApply(quote)(quote.fun, body2 :: Nil)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala:132]: At line 119, `body2` could be a block, and it's used as a type. I guess this case not reachable if `body2` is a block.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala [hunk 2]
```diff
@@ -118,7 +118,19 @@ class PCPCheckAndHeal(@constructorOnly ictx: Context) extends TreeMapWithStages(
...
 
-    super.transformQuotation(body2, quote)
+    quote match {
+      case Apply(fn1 @ TypeApply(fn0, targs), _) =>
+        val heal = new TypeMap {
+          def apply(tp: Type) = tp match {
+            case AnnotatedType(parent, annot) => AnnotatedType(mapOver(parent), annot)
+            case _ => healTypeOfTerm(fn1.srcPos)(tp)
+          }
+        }
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala:128]: I'm wondering why this is not already handled in the recursive call? Can it be handled in `transform`? I'm wondering if it's possible to avoid the `heal` TypeMap here and move the logic to `healTypeOfTerm` -- as there's also a TypeMap there.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 1 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala:132]: Indeed, is not reachable. This is essentially the same logic as in `super.transformQuotation`.

File: compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala (hunk 2 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala]: Moved into `healTypeOfTerm`

**Review by liufengyun — APPROVED** [review]
LGTM
