### PR TITLE
Extend "cannot override mutable variable" restriction to deferred var…

### LINKED ISSUE #14722: Semantic bug when override `var` with `val` and no way to extends from a trait that has a `var` for a `case class`
## Compiler version

3.1.1

## Minimized code

```Scala
trait HasId(var id: String)

case class Entity(override val id: String) extends HasId(id)

val entity = Entity("0001")
entity.id = "0002"
println(entity.id)
```

## Output

```scala
0001
```

## Expectation

Either does not compile or output `0002`.

My intention is that I do not want to introduce a redundant variable just for assigning to trait parameter.
```Scala
trait HasId(var id: String)

case class Entity(var idJustForAssignment: String) extends HasId(idJustForAssignment)

val entity = Entity("id")
entity.id
entity.idJustForAssignment // this is a duplication

```

and this does not work:
```Scala
trait HasId(var id: String)

case class Entity(id: String) extends HasId(id) // and this works when it's a normal class not a case class
```

and this does not work either:
```Scala
trait HasId(var id: String)

case class Entity(override var id: String) extends HasId(id)
```

So there's no way to extends from a trait that has a `var` for a case class.

### PR DESCRIPTION
**Pull request by odersky**
…iables.

Extend "cannot override mutable variable" restriction also to deferred variables.
This aligns the behavior with Scala 2.

Fixes #14722

### CODE REVIEW

File: tests/neg/i13019.scala [hunk 1]
```diff
@@ -10,4 +10,4 @@ class Ok2C extends Ok2 { override var i: Int = 1 }
 
 // was: variable i of type Int cannot override a mutable variable
 trait NotOk {var i: Int}
-class NotOkC extends NotOk { override var i: Int = 1 }
+class NotOkC extends NotOk { override var i: Int = 1 } // error
```
Comment (smarter) [inline tests/neg/i13019.scala:13]: If this breaks it means we're not really aligned with Scala 2 and we need to re-open https://github.com/lampepfl/dotty/issues/13019 /cc @som-snytt . The Scala 2 logic here is https://github.com/scala/scala/commit/9b59f5f9530d54c917479c6bf44aa3007ba0a2df

**Review by smarter — APPROVED** [review]

File: tests/neg/i13019.scala (hunk 1 above)
Comment (som-snytt) [reply tests/neg/i13019.scala:13]: In my tweak I didn't try trait params. I'll take another look at a fix. I haven't taken the trait params coursera yet.
