### PR TITLE
fix #1748: desugaring with StringContext in PatDef

### LINKED ISSUE #1748: Desugaring problem with StringContext in PatDef
Following code failed to compile in Dotty, but it's fine in Scala:

```Scala
object Test {
  implicit class Foo(sc: StringContext) {
    object q {
      def unapply(args: Any*): Option[(Any, Any)] =
        Some((sc.parts(0), sc.parts(1)))
    }
  }

  def f(defn: Any): Any = {
    val q"class $name extends $parent" =  defn
    println(name)
    println(parent)
  }
}
```

It turns out in Desugaring, a case for `Thicket` is missing.

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #1748: desugaring with StringContext in PatDef

The method `getVariables` forgets the case `Thicket`.

Review @felixmulder

### CODE REVIEW

File: tests/pos/i1784.scala [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+        Some((sc.parts(0), sc.parts(1)))
+    }
+  }
+
+  def f(defn: Any): Any = {
+    val q"class $name extends $parent" =  defn
+    println(name)
+    println(parent)
+  }
+}
```
Comment (felixmulder) [inline tests/pos/i1784.scala]: Perhaps this should be a run-test instead since you're printing things? :)

**Comment by felixmulder** [comment]
Checkfile not correct?

**Comment by liufengyun** [comment]
Let me try adding a newline at the end of the check file.
