### PR TITLE
Fix #3638: Fix protected setter generation

### LINKED ISSUE #3638: crash on compilable code:MatchError: Assign(...)
scalac compiles but dotc crashes.

$ dotc -version
```
Dotty compiler version 0.5.0-bin-SNAPSHOT-git-4fefb64 -- Copyright 2002-2017, LAMP/EPFL
```

$ dotc abc.scala
```
exception occurred while compiling abc.scala
Exception in thread "main" scala.MatchError: Assign(Apply(Select(This(Ident(JavaInteraction)),protected$count),List(This(Ident(JavaInteraction)))),Apply(Select(This(Ident(JavaInteraction)),protected$count),List(This(Ident(JavaInteraction))))) (of class dotty.tools.dotc.ast.Trees$Assign)
	at dotty.tools.dotc.transform.SuperAccessors.transformAssign(SuperAccessors.scala:395)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:213)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1153)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:63)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:293)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStat$2(MacroTransform.scala:45)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats$$anonfun$1(MacroTransform.scala:47)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:62)
	at dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:78)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStats(MacroTransform.scala:47)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:61)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$5$$anonfun$1(PostTyper.scala:232)
	at dotty.tools.dotc.transform.SuperAccessors.wrapTemplate(SuperAccessors.scala:410)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform$$anonfun$2(PostTyper.scala:232)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.withNoCheckNews(PostTyper.scala:102)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:233)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1206)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transform(MacroTransform.scala:55)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:248)
	at dotty.tools.dotc.transform.MacroTransform$Transformer.transformStat$2(MacroTransform.scala:43)
<snipped>
```

$ cat abc.scala
```scala
package p {
  package a {
    class JavaInteraction(arr: Array[Char])
        extends java.io.CharArrayReader(arr) {
      class Inner {
        {
          count = count
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

File: tests/pos/i3638.scala [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package p {
+  package a {
+    class JavaInteraction(arr: Array[Char])
```
Comment (smarter) [inline tests/pos/i3638.scala]: It looks like this test was minimized from https://github.com/scala/scala/blob/2.13.x/test/files/jvm/protectedacc.scala, it might be worthwhile to port over the whole test (I think it's a run test but it's in /jvm and not /run so it might need to be run in a special way?).

Comment (odersky) [reply tests/pos/i3638.scala]: I think it can't run on JS because it uses Java classes, that's why it's in jvm. I added the full test to run.

**Comment by odersky** [comment]
@nicolasstucki The FromTasty test fails on protectedacc.scala. Can you take a look to find out what's wrong?

**Comment by nicolasstucki** [comment]
I will have a look

**Comment by nicolasstucki** [comment]
I minimized that issue to 

```scala
package a {
  class PolyA {
    protected def m(): Unit = ()
  }
}

class X extends a.PolyA {
  trait Inner {
    m()
  }
}
```
which can be reproduced with 

```
dotc -d out tests/run/protectedacc.scala
dotc -from-tasty -Ycheck:elimJavaPackages,refchecks,splitter,arrayConstructors,erasure,capturedVars,getClass,elimStaticThis,labelDef -classpath out X a.PolyA 
```

and fails with 
```
Exception in thread "main" java.lang.AssertionError: assertion failed: method super$m is both Deferred and Private
	at scala.Predef$.assert(Predef.scala:219)
	at dotty.tools.dotc.transform.TreeChecker.transformSym(TreeChecker.scala:95)
	at dotty.tools.dotc.core.DenotTransformers$SymTransformer.transform(DenotTransformers.scala:68)
	at dotty.tools.dotc.core.DenotTransformers$SymTransformer.transform$(DenotTransformers.scala:67)
	at dotty.tools.dotc.transform.TreeChecker.transform(TreeChecker.scala:48)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.current(Denotations.scala:872)
	at dotty.tools.dotc.core.Symbols$Symbol.recomputeDenot(Symbols.scala:432)
	at dotty.tools.dotc.core.Symbols$Symbol.computeDenot(Symbols.scala:427)
	at dotty.tools.dotc.core.Symbols$Symbol.denot(Symbols.scala:421)
	at dotty.tools.dotc.core.Symbols$.toDenot(Symbols.scala:684)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.$anonfun$paramAccessors$1(SymDenotations.scala:1765)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.$anonfun$paramAccessors$1$adapted(SymDenotations.scala:1765)
	at dotty.tools.dotc.core.Scopes$Scope.filter(Scopes.scala:104)
	at dotty.tools.dotc.core.SymDenotations$ClassDenotation.paramAccessors(SymDenotations.scala:1765)
	at dotty.tools.dotc.core.Contexts$Context.superCallContext(Contexts.scala:328)
...
```

**Comment by nicolasstucki** [comment]
The failure is after `refchecks`

**Comment by nicolasstucki** [comment]
The bug in `tests/run/protectedacc.scala` when tested from TASTY in unrelated to this fix. I filed an issue and added it to the backlist of the `FromTastyTests`. This PR should be mergeable if the tests pass.

File: compiler/src/dotty/tools/dotc/transform/SuperAccessors.scala [hunk 2]
```diff
@@ -80,10 +80,10 @@ class SuperAccessors(thisPhase: DenotTransformer) {
       val superAcc = clazz.info.decl(superName)
         .suchThat(_.signature == superInfo.signature).symbol
         .orElse {
-          ctx.debuglog(s"add super acc ${sym.showLocated} to $clazz")
-          val deferredOrPrivate = if (clazz is Trait) Deferred else Private
+          ctx.debugLog(s"add super acc ${sym.showLocated} to $clazz")
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/SuperAccessors.scala]: `ctx.debugLog` -> `ctx.debuglog`

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/transform/SuperAccessors.scala]: This commit should also `Fix #3738`

**Comment by nicolasstucki** [comment]
Otherwise LGTM
