### PR TITLE
Fixes #7359 - Fix SAM processing

### LINKED ISSUE #7359: Processing SAM with overridden methods of java.lang.Object fails
Dotty fails to process `@FunctionalInterface` objects when they contain overridden public methods of `java.lang.Object`, but [javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html) states:

> If an interface declares an abstract method overriding one of the public methods of java.lang.Object, that also does not count toward the interface's abstract method count 

## minimized code

```Scala
val comp : java.util.Comparator[Int] = (x, y) => -1
println(comp.compare(1,2))
```
fails with
```scala
-- [E081] Syntax Error: MySam.scala:10:46 --------------------------------------
10 |      val comp : java.util.Comparator[Int] = (x, y) => -1
   |                                              ^
   |                          Missing parameter type
   |                          
   |                          I could not infer the type of the parameter x.
-- [E081] Syntax Error: MySam.scala:10:49 --------------------------------------
10 |      val comp : java.util.Comparator[Int] = (x, y) => -1
   |                                                 ^
   |                          Missing parameter type
   |                          
   |                          I could not infer the type of the parameter y.
two errors found

```

## expectation
The code above should print **-1** to the standard output.

### PR DESCRIPTION
**Pull request by neshkeev**
I would like to start sharing my progress on the #7359 issue in this pull-request.

So far I have came across the problem with [**`java.util.Comparator`**](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html), which happens to contains overridden [`equals`](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#equals-java.lang.Object-) method. [Javadoc states](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html) that overridden methods of `java.lang.Object` have to be ignored:
> If an interface declares an abstract method overriding one of the public methods of java.lang.Object, that also does not count toward the interface's abstract method count

Dotty finds two abstract methods (`equals` and `compare`) in this `@FunctionalInterface` object and fails to recognize it as **`SAM`** and hence fails to assign a proper type to it.

### CODE REVIEW

File: compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala [hunk 1]
```diff
@@ -840,7 +840,8 @@ class DottyBackendInterface(outputDirectory: AbstractFile, val superCallsMap: Ma
     def addRemoteRemoteExceptionAnnotation: Unit = ()
 
     def samMethod(): Symbol = ctx.atPhase(ctx.erasurePhase) {
-      toDenot(sym).info.abstractTermMembers.toList match {
+      val samMethods = toDenot(sym).info.abstractTermMembers.filter(! _.show.contains("equals"))
```
Comment (smarter) [inline compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala]: I haven't tried it, but to filter all symbols that override a java.lang.Object symbol, you probably want:
```suggestion
      val samMethods = toDenot(sym).info.abstractTermMembers
        .filterNot(_.symbol.overriddenSymbol(defn.ObjectClass).exists)
```

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -761,10 +761,15 @@ object Types {
     }
 
     /** The set of abstract term members of this type. */
-    final def abstractTermMembers(implicit ctx: Context): Seq[SingleDenotation] = {
+    final def abstractTermMembers(implicit ctx: Context): Seq[SingleDenotation] = abstractTermMembers { m =>
+      m.is(Deferred) && ! m.matchingMember(defn.ObjectType).exists
```
Comment (neshkeev) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: I replaced the predicate `_.is(Deferred)` with this filter, since methods of `ObjectType` are always generated automatically, so they are not really `abstract`, is it correct?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: Sorry for the delay in responding, I would prefer if we did not change the definition of `abstractTermMembers` and limited the change to `samMethod`, otherwise this might have unintended consequences, for example the following should always emit an error:
```scala
scala> class Foo { def equals(x: Any): Boolean }
1 |class Foo { def equals(x: Any): Boolean }
  |      ^
  |class Foo needs to be abstract, since def equals(x: Any): Boolean is not defined
```

Comment (neshkeev) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: @smarter, the compiler already emits the error from the code from your example with the changed `abstractTermMembers` method.

I changed `abstractTermMembers` because in terms of processing `SAM`s the method happens to be called from three different places (links follow to the exact lines in the files):

1. [`compiler/src/dotty/tools/dotc/core/Types.scala:4372`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/Types.scala#L4372)
2. [`compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala:849`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala#L849)
3. [`tools/dotc/transform/ExpandSAMs.scala:49`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala#L49)

In the whole project the method is accessed in these three places plus once in [`compiler/src/dotty/tools/dotc/typer/RefChecks.scala:483`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/typer/RefChecks.scala#L483). I used the following command to find it out:
```bash
find . -name "*.scala" -not -path "*./.git/*" -type f -exec grep --color "abstractTermMembers" {} \+
```
So I assumed it was okay to change the method. 

I reverted the changes in the `abstractTermMembers` and added a new commit (so there are two of them in the branch now) in order to be able to get back to the previous changes if we decide it is legal to alter the method and stick to the original solution.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: > the compiler already emits the error from the code from your example with the changed abstractTermMembers method.

That's surprising since it calls abstractTermMembers, shouldn't the equals method not be returned ?

> I changed abstractTermMembers because in terms of processing SAMs the method happens to be called from three different places (links follow to the exact lines in the files):

To avoid the duplication without changing the meaning of abstractTermMembers, I suggest defining a `possibleSamMethods` that just calls abstractTermMembers and add the extra filtering (you can also add the `isSuperAccessor` filtering used in ExpandSAMs), the documentation of `possibleSamMethods` can then cite the part in https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html which talks about the special handling of methods of java.lang.Object.

Comment (neshkeev) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: @smarter , I extracted the common method `possibleSamMethods`, please review.
There are still two commits, I will squash them when we are ready to merge the PR.

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 3]
```diff
@@ -767,6 +769,27 @@ object Types {
...
+     *
+     * @see https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html
+     *
+     * @return the set of methods that are abstract and do not match any of [[java.lang.Object]]
+     *
+     */
+    final def possibleSamMethods(implicit ctx: Context): Seq[SingleDenotation] = {
+      record("possibleSamMethods")
+      abstractTermMembers
+        .filterNot(_.symbol.matchingMember(defn.ObjectType).exists)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala]: You can  use only one filterNot call with two conditions

Comment (neshkeev) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: Sorry, I didn't understand, do I need to use a single `filterNot` call with two conditions here?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: Yes, that's more efficient since you're only doing one traversal

Comment (neshkeev) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: @smarter, I amended the method implementation and squashed all the commits into a single one. The PR is ready to be merged.
