### PR TITLE
Fix expandParam's use of argForParam/isArgPrefixOf.

### LINKED ISSUE #19354: java stream API interop regression in 3.4.0-RC1
## Compiler version

3.4.0-RC1

## Minimized code

```scala
import javax.annotation.processing.{ AbstractProcessor, RoundEnvironment }
import javax.lang.model.element.{ ElementKind, PackageElement, TypeElement }

import java.util as ju

class P extends AbstractProcessor {
  override def process(annotations: ju.Set[? <: TypeElement], roundEnv: RoundEnvironment): Boolean = {
    annotations
      .stream()
      .flatMap(annotation => roundEnv.getElementsAnnotatedWith(annotation).stream())
      .filter(element => element.getKind == ElementKind.PACKAGE)
      .map(element => element.asInstanceOf[PackageElement])
      .toList()
    true
  }
}
```

## Output

```
Ambiguous overload. The overloaded alternatives of method getElementsAnnotatedWith in trait RoundEnvironment with types
 (x$0: Class[? <: java.lang.annotation.Annotation]):
  java.util.Set[? <: javax.lang.model.element.Element]
 (x$0: javax.lang.model.element.TypeElement):
  java.util.Set[? <: javax.lang.model.element.Element]
both match arguments ((annotation : Nothing))
```

## Expectation
This java interop with Stream APIs worked in 3.3.1 and all versions before. Regressed in 3.4.0-RC1

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #19354

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 1]
```diff
@@ -6276,7 +6276,7 @@ object Types extends TypeUtils {
      */
     def expandParam(tp: NamedType, pre: Type): Type =
       tp.argForParam(pre) match {
-        case arg @ TypeRef(pre, _) if pre.isArgPrefixOf(arg.symbol) =>
+        case arg @ TypeRef(`pre`, _) if pre.isArgPrefixOf(arg.symbol) =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Types.scala:6279]: Hah, we really need a shadowing warning for this.

**Review by smarter — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/core/Types.scala (hunk 1 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/Types.scala:6279]: Yeah, probably.  Obviously it's worst when the types match up exactly, but I've definitely shadowed things intentionally, ala `port.parse.match { case Some(port) => ... }`, so hard to find the right ergonomics...
