### PR TITLE
Fix #1169: Fix strange type formatting in error message

### LINKED ISSUE #1169: Incorrect bridge gen for method that has value class with underlying Object type as result type
Incorrect bridge generation for method that has value class with the underlying Object type as result type.
The compilation of this code with -Ycheck:all:

``` scala
class A(val x: Object) extends AnyVal
abstract class VCACompanion[T] {
  def yyyy(x: Object): T
}
class XXX extends VCACompanion[A] {
  override def yyyy(x: Object): A = new A("fff")
}
```

results in:

```
 method yyyy is already defined as method yyyy: (x: Object)ErasedValueType(A, Object)
 (the definitions have matching type signatures)
```

The problem is that there is a bridge generation during Erasure for `def yyyy(x: Object): A = ...`. 
This bridge has the same signature as original `def yyyy(x: Object): A = ...`:

```
override def yyyy(x: Object): Object = "fff"
def yyyy(x: Object): Object = new A(this.yyyy(x))
```

### PR DESCRIPTION
**Pull request by odersky**
We already generate an error message for i1169.scala, but it looked weird:

    |bridge generated for member method produce=> X in class XProducer
    |which overrides method produce=> T in trait Producer
    |clashes with definition of the member itself; both have erased type (): Object.

The fix changes how ExprTypes in method signatures are handled. We now get:

    |bridge generated for member method produce: X in class XProducer
    |which overrides method produce: T in trait Producer
    |clashes with definition of the member itself; both have erased type (): Object."

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/Bridges.scala [hunk 1]
```diff
@@ -56,7 +56,13 @@ class Bridges(root: ClassSymbol)(implicit ctx: Context) {
       bridgesScope.lookupAll(member.name).exists(bridge =>
         bridgeTarget(bridge) == member && bridge.signature == other.signature)
     def info(sym: Symbol)(implicit ctx: Context) = sym.info
-    def desc(sym: Symbol)= i"$sym${info(sym)(preErasureCtx)} in ${sym.owner}"
+    def desc(sym: Symbol)= {
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/transform/Bridges.scala]: Maybe:
```scala
val infoStr = sym.showDcl(preErasureCtx)
i"$infoStr in ${sym.owner}"
```
This will print `def produce: => X`. But I think we could configure the printer to not print the `=>`. Other part of the compiler (such as error messages) could benefit from it.

**Comment by liufengyun** [comment]
Need to rebase because of #3892

File: compiler/src/dotty/tools/dotc/transform/Bridges.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/Bridges.scala]: The problem is that printing the type will always print the `=>`. Otherwise it would be confusing. I would should work on the Printer but it has to look at the larger context to do the right thing.
