### PR TITLE
compile dotty with Ysemanticdb

### LINKED ISSUE #8954: Generation of semanticdb for dotty codebase fails
enable flag "-Ysemanticdb" for compilation of dotty. It will cause build to fail.

Semanticdb is needed by metals to provide basic functionality for editors(find references/goto definition).

Here I created a branch showing where things fail what workarounds I did to make compilation succeed -> generate .semanticdb to let metals provide minimal support and how I enabled semanticdb generation(in case I messed up something :P).
https://github.com/kpbochenek/dotty/pull/1/files

Problem 1:
There is a function
 `file:ExtractSemanticDB.scala: private def adjustSpanToName(span: Span, qualSpan: Span, name: Name)(using Context) =`
It throws exception that tries to access characters outside of current source file. It happens for a file:
`dotty/library/src/scala/quoted/autolift.scala 261 with 862 FOR [834..844..863] AND FunctionalInterface`
(it means `autolift.scala` file with 261 characters but it tries to access Span in range 834-863 of name FunctionalInterface)

Problem 2:
When problem1 is fixed(or worked around) you hit problem 2.
```
[error] ## Exception when compiling 444 sources to <...>/dotty/compiler/target/scala-0.24/classes
[error] java.lang.AssertionError: NoDenotation.owner
[error] dotty.tools.dotc.core.SymDenotations$NoDenotation$.owner(SymDenotations.scala:2330)
[error] dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverseTpt$1$$anonfun$1(ExtractSemanticDB.scala:119)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$17$$anonfun$1(ExtractSemanticDB.scala:576)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$7(ExtractSemanticDB.scala:576)
...
```
This one I have not checked more but workaround with `try catch` shows for now there is no more compilation error issues.

### LINKED ISSUE #8970: semanticdb: assertion failed in runMacro test
## To Reproduce

Add `"-Ysemanticdb"` to `checkOptions` in `compiler/test/dotty/tools/vulpix/TestConfiguration.scala` and test `dotty.tools.dotc.BootstrappedOnlyCompilationTests.runMacros`

## Output (click arrow to expand)
<details>

```scala
Fatal compiler crash when compiling: tests/run-macros/i8530:
assertion failed
dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
dotty.tools.dotc.util.Spans$Span$.start$extension(Spans.scala:44)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.computeLocalIdx$1(ExtractSemanticDB.scala:341)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.localIdx$2$$anonfun$1(ExtractSemanticDB.scala:349)
dotty.runtime.function.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:440)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.localIdx$1(ExtractSemanticDB.scala:349)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.addSymName(ExtractSemanticDB.scala:355)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.symbolName(ExtractSemanticDB.scala:362)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.registerUse(ExtractSemanticDB.scala:471)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.registerUseGuarded(ExtractSemanticDB.scala:468)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:222)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1436)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1479)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:238)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1400)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1479)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:238)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply$$anonfun$1(Trees.scala:1360)
scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:168)
scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:164)
scala.collection.immutable.List.foldLeft(List.scala:79)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1360)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1398)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1479)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:238)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply$$anonfun$1(Trees.scala:1360)
scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:168)
scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:164)
scala.collection.immutable.List.foldLeft(List.scala:79)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1360)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1392)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1479)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:238)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1443)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1479)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:181)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$12(ExtractSemanticDB.scala:195)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.immutable.List.foreach(List.scala:333)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:195)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1478)
dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1447)
dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1479)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:181)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse$$anonfun$1(ExtractSemanticDB.scala:139)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.immutable.List.foreach(List.scala:333)
dotty.tools.dotc.semanticdb.ExtractSemanticDB$Extractor.traverse(ExtractSemanticDB.scala:139)
dotty.tools.dotc.semanticdb.ExtractSemanticDB.run(ExtractSemanticDB.scala:45)
dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:318)
scala.collection.immutable.List.map(List.scala:246)
dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:319)
dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:165)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
dotty.tools.dotc.Run.runPhases$5(Run.scala:175)
dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:183)
dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:64)
dotty.tools.dotc.Run.compileUnits(Run.scala:190)
dotty.tools.dotc.Run.compileSources(Run.scala:127)
dotty.tools.dotc.Run.compile(Run.scala:110)
dotty.tools.dotc.Driver.doCompile(Driver.scala:38)
dotty.tools.dotc.Driver.process(Driver.scala:194)
dotty.tools.dotc.Driver.process(Driver.scala:163)
dotty.tools.vulpix.ParallelTesting$Test.compile(ParallelTesting.scala:477)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$2$$anonfun$1(ParallelTesting.scala:208)
scala.collection.immutable.List.map(List.scala:250)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.compileTestSource$$anonfun$1(ParallelTesting.scala:208)
scala.util.Try$.apply(Try.scala:210)
dotty.tools.vulpix.ParallelTesting$CompilationLogic.dotty$tools$vulpix$ParallelTesting$CompilationLogic$$compileTestSource(ParallelTesting.scala:209)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource$$anonfun$1(ParallelTesting.scala:252)
dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
dotty.tools.vulpix.ParallelTesting$Test.tryCompile(ParallelTesting.scala:420)
dotty.tools.vulpix.ParallelTesting$$anon$2.checkTestSource(ParallelTesting.scala:255)
dotty.tools.vulpix.ParallelTesting$Test$LoggedRunnable.run(ParallelTesting.scala:323)
dotty.tools.vulpix.ParallelTesting$$anon$2.run(ParallelTesting.scala:250)
java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
</details>

### PR DESCRIPTION
**Pull request by bishabosha**
fix #8970 fix #8954 

fix a number of issues with semanticdb generation

- support scala 2 def macros
- support var overloads
- support literal types and byname params in constructors (by removing unneccesary code)
- support local definitions from inlined macro generated trees (where symbol has no span)
- prevent infinite recursion on traversal of annotations
- support inlined macro trees from another file
- do not emit occurence for `<special-ops>.throw`
- inlined trees have position in the file of the callsite, not implementation

this also compiles all of the vulpix tests with Ysemanticdb option and the bootstrapped projects (localised to 1 commit)

### CODE REVIEW

File: project/Build.scala [hunk 1]
```diff
@@ -299,6 +299,10 @@ object Build {
     },
     */
 
+    scalacOptions ~= { old =>
+      if (old.contains("-Ysemanticdb")) old else old :+ "-Ysemanticdb"
```
Comment (smarter) [inline project/Build.scala:303]: I'm against this if it slows down the build. Instead, this option can be added to the `tastyBootstrap` test which compiles the whole compiler too: https://github.com/lampepfl/dotty/blob/363dd03087819d5cfd08b6741cbc75618c17dad9/compiler/test/dotty/tools/dotc/CompilationTests.scala#L230 (I'm surprised this isn't actually compiled with Ycheck:all too!)

Comment (bishabosha) [reply project/Build.scala]: Thanks, I've removed this setting and changed the settings of tastyBootstrapped to add -Ysemanticdb

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala [hunk 2]
```diff
@@ -502,7 +504,7 @@ class ExtractSemanticDB extends Phase:
         }).toMap
     end findGetters
 
-    private def adjustSpanToName(span: Span, qualSpan: Span, name: Name)(using Context) =
+    private def adjustSpanToName(span: Span, qualSpan: Span, name: Name, source: SourceFile) =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:506]: Seems like we should remove the `inline private def source(using Context) = ctx.compilationUnit.source` from this file to prevent accidentally using the wrong source.

File: compiler/test/dotty/tools/dotc/CompilationTests.scala [hunk 3]
```diff
@@ -49,6 +49,7 @@ class CompilationTests extends ParallelTesting {
       compileFilesInDir("tests/new", defaultOptions),
       compileFilesInDir("tests/pos-scala2", scala2CompatMode),
       compileFilesInDir("tests/pos-custom-args/erased", defaultOptions.and("-Yerased-terms")),
+      compileFilesInDir("tests/pos-custom-args/semanticdb", defaultOptions.and("-Ysemanticdb")),
```
Comment (smarter) [inline compiler/test/dotty/tools/dotc/CompilationTests.scala:52]: If all tests are run with Ysemantic-db then that option isn't needed right?

File: tests/semanticdb/expect/MethodUsages.scala [hunk 4]
```diff
@@ -30,3 +30,9 @@ class MethodUsages {
   m.m18(1)
   m.m18("")
 }
+
+object MethodUsages {
+  var x: Int = 1
```
Comment (smarter) [inline tests/semanticdb/expect/MethodUsages.scala:35]: What happens with a val?

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala [hunk 5]
```diff
@@ -334,14 +334,16 @@ class ExtractSemanticDB extends Phase:
...
         def computeLocalIdx(): Int =
-          symsAtOffset(sym.span.start).find(_.name == sym.name) match
+          symsAtOffset(startPos(sym)).find(_.name == sym.name) match
             case Some(other) => localIdx(other)
             case None =>
               val idx = nextLocalIdx
               nextLocalIdx += 1
               locals(sym) = idx
-              symsAtOffset(sym.span.start) += sym
+              symsAtOffset(startPos(sym)) += sym
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:346]: Does it really make sense to store things at offset -1?

File: compiler/test/dotty/tools/dotc/CompilationTests.scala (hunk 3 above)
Comment (bishabosha) [reply compiler/test/dotty/tools/dotc/CompilationTests.scala:52]: I would say keep this in case a decision is made to remove -Ysemanticdb from checkOptions, these tests are specifically designed for regression testing the implementation

File: tests/semanticdb/expect/MethodUsages.scala (hunk 4 above)
Comment (bishabosha) [reply tests/semanticdb/expect/MethodUsages.scala:35]: thats tested in the same file with `m18`

Comment (bishabosha) [reply tests/semanticdb/expect/MethodUsages.scala:35]: i should probably refactor to use the same style

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 5 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:346]: Im not sure it matters because this is just a discriminator, but perhaps it is actually a bug in macros because the trees in `sandbox/semanticdb/i8530/App_2.scala` have a position but not their symbol

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 2 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala]: I've updated the code so that the Tree is passed implicitly wherever we require a source

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 5 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:350]: Sounds like it, by default symbols are created without a position so it's easy to forget about passing it

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 2 above)
Comment (smarter) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala]: Hmm this might work but it's kind of an unusual pattern and still seems easy to do the wrong thing by forgetting to pass `given` somewhere. My suggestion would be to pass it explicitly.

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 5 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:350]: what I've seen is that at https://github.com/lampepfl/dotty/blob/363dd03087819d5cfd08b6741cbc75618c17dad9/compiler/src/dotty/tools/dotc/typer/Inliner.scala#L140
when compiling `sandbox/semanticdb/i8530/App_2.scala` is that the symbol of the unapply method being transformed has an index coord

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:350]: ok this is simple, whenever that symbol was loaded `ReadPositions` was not on

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 2 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala]: ok I've updated to use explicit passing

**Comment by bishabosha** [comment]
this will fail until I rebase it on a PR to always provide spans if possible for symbols from TASTy

**Comment by bishabosha** [comment]
@smarter I've added a change here so that compiler newRun enables ReadPositions if Ysemanticdb setting is true

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala (hunk 5 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala]: This is resolved by reading positions from tasty when -Ysemanticdb is set, therefore there is no need to check if span exists

File: compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala [hunk 6]
```diff
@@ -112,6 +116,15 @@ class ExtractSemanticDB extends Phase:
             case tree: Typed => () // hack for inline code
             case tree        => traverse(tree)
 
+
+    // guarded entrypoints
+    private inline def excludeSymbol0(sym: Symbol)(using Context) = !sym.exists || excludeSymbol(sym)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:121]: Checking for symbol existence is pretty fast, so if this is needed in some cases, I would just add the sym.exists check in the original methods.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:121]: I did it this way because the methods that are being guarded are often chained as fallbacks, this would reduce redundant checks, but agreed it would be simpler to just put the checks into the methods

Comment (smarter) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala:121]: Yeah I wouldn't worry about the performance impact of redundant exists check

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala]: Thanks, I've inlined those checks
