### PR TITLE
Fix #2578 Part 1: Tighten type checking of pattern bindings

### LINKED ISSUE #2578: Scala Wart: Conflating total destructuring with partial pattern-matching
Opening this issue, as suggested by Martin, to provide a place to discuss the individual warts brought up in the blog post [Warts of the Scala Programming Language](http://www.lihaoyi.com/post/WartsoftheScalaProgrammingLanguage.html) and the possibility of mitigating/fixing them in Dotty (and perhaps later in Scala 2.x). These are based on Scala 2.x behavior, which I understand Dotty follows closely, apologies in advance if it has already been fixed

--------------------------------------------------------------------------------

The following example, also from 
[Lincon Atkinson's blog](http://latkin.org/blog/2017/05/02/when-the-scala-compiler-doesnt-help/), 
compiles without warning and fails with an exception at runtime:

```scala
@ val (a, b, c) = if (true) "bar" else Some(10)
scala.MatchError: bar (of class java.lang.String)
  $sess.cmd105$.<init>(cmd105.sc:1)
  $sess.cmd105$.<clinit>(cmd105.sc:-1)
```

The basic problem here is that when Scala sees `val (a, b, c) = ...`, it doesn't
mean which of two things you mean:

1. Help me extract the values from `...`, and help me check that it's a tuple
2. Help me extract the values from `...`, and fail at runtime if it is not a tuple

Currently, it assumes the latter, in all cases. 

That makes any sort of "destructuring assignment" unchecked, and thus extremely 
unsafe.

The above example at least happily fails with an exception, but the following 
exhibits the same problem, but instead truncates your data silently, losing the
`5`:
 
```scala
@ for((a, b) <- Seq(1 -> 2, 3 -> 4, 5)) yield a + " " +  b
res107: Seq[String] = List("1 2", "3 4")
```

Though the following also fails with an exception:
```scala
@ Seq(1 -> 2, 3 -> 4, 5).map{case (a, b) => a + " " + b}
scala.MatchError: 5 (of class java.lang.Integer)
  $sess.cmd108$.$anonfun$res108$1(cmd108.sc:1)
  scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  scala.collection.immutable.List.foreach(List.scala:389)
  scala.collection.TraversableLike.map(TraversableLike.scala:234)
  scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  scala.collection.immutable.List.map(List.scala:295)
  $sess.cmd108$.<init>(cmd108.sc:1)
  $sess.cmd108$.<clinit>(cmd108.sc:-1)
```

While interpretation #2 makes sense in `match` blocks and partial-functions,
where you expect to "fall through" to the next handler if it doesn't match, it
doesn't make much sense in cases like this where there *is nowhere to fall
through to*.

The correct solution would look something like this:

- By default, assume the user wants 1. "Help me extract the values from `...`, 
  and help me check that it's a tuple"

- Require a special keyword if the user wants 2. "Help me extract the values 
  from `...`, and fail at runtime if it is not a tuple"

A possible syntax might be using `case`, which Scala developers already 
associate with partial functions and pattern matches: 

```scala
for(case (a, b) <- Seq(1 -> 2, 3 -> 4, 5)) yield a + " " +  b

case val (a, b, c) = if (true) "bar" else Some(10)
```

This would indicate that you want to perform an "partial fail at runtime" 
match, and the earlier non-`case` examples:

```scala
for((a, b) <- Seq(1 -> 2, 3 -> 4, 5)) yield a + " " +  b

val (a, b, c) = if (true) "bar" else Some(10)
```

Could then verify that the pattern match is complete, otherwise fail at
compile time.

PostScript:

I noticed [here](https://www.scala-lang.org/files/archive/spec/2.11/08-pattern-matching.html#irrefutable-patterns) that the Scala language spec already has words in it that talk about irrefutable patterns, which seem to match what I want these for-comprehension and val-destructuring cases to require. Whether those words mean anything, I do not actually know

Yawar Amin has noted that in the Rust language, the cases which closely mirror those in Scala (`let` destructuring, and `while`-loop/`if` destructuring) do have a requirement of the destructuring patterns being irrefutable https://doc.rust-lang.org/beta/book/second-edition/ch18-02-refutability.html

Here's a 2.12 failure mode in for-comprehensions that's nonsensical, and is fundamentally caused by this issue:

```scala
lihaoyi ~$ amm
Loading...
Welcome to the Ammonite Repl 0.9.7
(Scala 2.12.2 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ for((a, b) <- Right((1, 2))) yield a + b
cmd0.sc:1: value withFilter is not a member of scala.util.Right[Nothing,(Int, Int)]
val res0 = for((a, b) <- Right((1, 2))) yield a + b
                              ^
cmd0.sc:1: type mismatch;
 found   : Any
 required: String
val res0 = for((a, b) <- Right((1, 2))) yield a + b
                                                  ^
Compilation Failed
```

### PR DESCRIPTION
**Pull request by odersky**
Check that patterns in val/var defs are irrefutable, unless the pattern is followed by `: @unchecked`.

For the moment, this requires -strict mode. We plan to turn this on by default once the bootstrap compiler supports `: @unchecked` in patterns (i.e. once this PR is part of the bootstrap compiler).

Edit: In fact, we probably can do this only in 3.1, for cross compilation reasons with Scala 2.

### CODE REVIEW

**Comment by smarter** [comment]
> Edit: In fact, we probably can do this only in 3.1, for cross compilation reasons with Scala 2.

We can do it earlier if we get some of the parser changes into Scala 2, right ? What's the minimum set of changes needed ?

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 1]
```diff
@@ -594,6 +597,48 @@ trait Checking {
...
+    !ctx.settings.strict.value || // only in -strict mode for now since mitigations work only after this PR
+    pat.tpe.widen.hasAnnotation(defn.UncheckedAnnot) || {
+      pat match {
+        case Bind(_, pat1) =>
+          checkIrrefutable(pat1, pt)
+        case UnApply(fn, _, pats) =>
+          check(pat, pt) && {
+            val argPts = unapplyArgs(fn.tpe.finalResultType, fn, pats, pat.sourcePos)
+            pats.corresponds(argPts)(checkIrrefutable)
+          }
```
Comment (AleksanderBG) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala]: For `UnApply`, we should also check if the extractor itself is irrefutable, i.e. if it returns `Some`, or `true`, or a product. The logic to do that is in `SpaceEngine#irrefutable`.

Additionally, for some reason unapplies are simply rejected as `val` definitions:
```
scala> {
     |   object Positive { def unapply(i: Int): Option[Int] = Some(i).filter(_ > 0) }
     |   val Positive(p) = 5
     |   5 match { case Positive(p) => p }
     | }
3 |  val Positive(p) = 5
  |      ^^^^^^^^^^^
  | ((i: Int): Option[Int])(Positive.unapply) is not a valid result type of an unapply method of an extractor.
```
