### PR TITLE
Fix regression #23969: Add ensureApplied to the quotes reflect API

### LINKED ISSUE #23969: Incorrect `does not take parameters` error when using quotes reflection
Found in open community build: https://github.com/VirtusLab/community-build3/actions/runs/17687960136/job/50279371233
## Compiler version
3.8.0-RC1-bin-20250912-c4c48e3-NIGHTLY
works correctly in 3.7.3 and earlier

## Minimized code

```scala
@main def main() = runMacro()
```
```scala
import scala.quoted._
inline def runMacro() = ${runMacroImpl}
def runMacroImpl(using Quotes) =
  import quotes.reflect._
  // '{BigDecimal(0).toString()} // works correctly
  Apply(Select.unique('{BigDecimal(0)}.asTerm, "toString"), List()).asExpr
```

## Output

```scala
[error] ./a.scala:4:3
[error] method toString in class BigDecimal does not take parameters
[error]   runMacro()
[error]   ^^^^^^^^^^
```

## Expectation
`BigDecimal(0).toString()` works so AST version of that should work too.

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #23969

The regression would not appear on main (only after release on the nightly version of the compiler, as explained [here](https://github.com/scala/scala3/issues/23969#issuecomment-3385567350)), so I've adjusted the test to be more general.

### CODE REVIEW

File: tests/pos-macros/i23969/Macro.scala [hunk 1]
```diff
@@ -0,0 +1,26 @@
+
+import scala.quoted._
+
+object TestMethods:
+  def a1 = ()
+  def a2() = ()
```
Comment (hamzaremmal) [inline tests/pos-macros/i23969/Macro.scala:6]: I'm curious about what will happen if we do this?

```suggestion
  def a1[T] = ()
  def a2[T]() = ()
```

At least, we should include them in the test.

File: tests/pos-macros/i23969/Macro.scala [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+  Select.unique('{TestMethods}.asTerm, "a1").ensureApplied match
+    case Select(_, _) =>
+    case _ => assert(false)
+  Select.unique('{TestMethods}.asTerm, "a2").ensureApplied match
+    case Apply(_, _) =>
+    case _ => assert(false)
+  Select.unique('{TestMethods}.asTerm, "a3").ensureApplied match
+    case Select(_, _) =>
+    case other => assert(false)
+  Select.unique('{TestMethods}.asTerm, "a4").ensureApplied match
```
Comment (hamzaremmal) [inline tests/pos-macros/i23969/Macro.scala:24]: Mmmh, this is a legitimate question, but if we have a `transparent inline` method, it is subject to type inference, why shouldn't we wrap then in an `Apply` and let type inference do it's thing?

Comment (jchyb) [reply tests/pos-macros/i23969/Macro.scala:24]: This will result in:
```scala
-- Error: tests/pos-macros/i23969/Main.scala:1:19 ------------------------------
1 |@main def Test() = runMacro()
  |                   ^^^^^^^^^^
  |                  method a4 in object TestMethods does not take parameters
```
error, thrown from tpd.Apply. Even if we were to change that, we would have to deal with the TreeChecker run right after the macro expansion. In general, I believe we have to return fully typed trees and I am not aware of any additional type inference done to inlined code after inlining it (so it will be done for quoted code before the macro is expanded, or for non-macro inline method contents, but not changed after inlining, even for non-macro transparent inline methods, more info here: https://github.com/scala/scala3/issues/8739).

Also apologies for weird response times! And thank you for looking at this @hamzaremmal

**Review by hamzaremmal — APPROVED** [review]
