### PR TITLE
Better `try` and `catch` messages

### LINKED ISSUE #1446: Improve error message for `try { } catch { }`
Currently the error is `error: class Unit in package scala does not take parameters`.
It should probably have a message that tells the user that he must at least have one `case`.

### PR DESCRIPTION
**Pull request by felixmulder**
Fixes #1446, and allows a `try` without a `catch` or `finally` as per the spec.

### CODE REVIEW

File: src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -1009,6 +1009,15 @@ object Parsers {
               in.nextToken()
               expr()
             } else EmptyTree
+
+          handler match {
+            case Block(Nil, EmptyTree) => syntaxError(
+              "`catch` block does not contain a valid expression, try adding a case like - `case t: Throwable =>` to the block",
```
Comment (smarter) [inline src/dotty/tools/dotc/parsing/Parsers.scala]: People should not use `Throwable` unless they know what they're doing, I would suggest `case e: Exception =>` instead

Comment (felixmulder) [inline src/dotty/tools/dotc/parsing/Parsers.scala]: Done :)

File: tests/neg/emptyCatch.scala [hunk 2]
```diff
@@ -0,0 +1,3 @@
+object Test {
+  try {} catch {} // error: `catch` block does not contain a valid expression, try adding a case like - `case t: Throwable =>` to the block
```
Comment (smarter) [inline tests/neg/emptyCatch.scala]: You left throwable here

Comment (felixmulder) [inline tests/neg/emptyCatch.scala]: Done - not sure why github is displaying the old code here...

File: src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (smarter) [inline src/dotty/tools/dotc/parsing/Parsers.scala]: I'm not against that, but do we really want to recommend people to do that by default? `NonFatal` will catch `StackOverflowException` among other things

Comment (sjrd) [inline src/dotty/tools/dotc/parsing/Parsers.scala]: It doesn't:
```scala
scala> try { throw new StackOverflowError } catch { case scala.util.control.NonFatal(e) => println("I caught you!") }
java.lang.StackOverflowError
  at .liftedTree1$1(<console>:8)
  ... 33 elided
```
`NonFatal` is *precisely* meant as a good default, to catch all the things you should catch, and none of those you shouldn't.

Comment (smarter) [inline src/dotty/tools/dotc/parsing/Parsers.scala]: Ha you're right, I googled to find the doc and didn't realize I was looking at the 2.9 version :) http://www.scala-lang.org/api/2.9.3/scala/util/control/NonFatal$.html
