### PR TITLE
handle export forwarders in Scala.js

### LINKED ISSUE #12111: Exporting JS facades fails
## Compiler version

* 3.0.0-RC1
* 3.0.1-RC1-bin-20210411-b44cafa-NIGHTLY

## Minimized code

```Scala
object A {
  import scala.scalajs.js
  import scala.scalajs.js.annotation._

  @JSImport("react-dom", JSImport.Namespace, "ReactDOM")
  @js.native
  object ReactDOM extends js.Object
}

object B {
  export A.ReactDOM // errors
}
```

## Output

```
[error] -- Error: asd.scala:11:9 --------------
[error] 11 |  export A.ReactDOM // errors
[error]    |         ^
[error]    |         @js.native members may only call js.native.
[error] -- Error: asd.scala:11:11 -------------
[error] 11 |  export A.ReactDOM // errors
[error]    |           ^^^^^^^^
[error]    |The type of ReactDOM must be explicitly specified because it is JS native.
[error] two errors found
```

## Expectation

Successful compilation.

### PR DESCRIPTION
**Pull request by bishabosha**
- prevent export forwarders in JS native types and JS non-native traits
- remove annotations `js.native`, `js.annotation.*` from export forwarders
  in `PrepJSInterop`

fixes #12111

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala [hunk 1]
```diff
@@ -814,20 +822,41 @@ class PrepJSInterop extends MacroTransform with IdentityDenotTransformer { thisP
       super.transform(tree)
     }
 
+    /** Removes annotations from exported definitions (e.g. `export foo.bar`):
+     *  - `js.native`
+     *  - `js.annotation.*`
+     *  - `js.annotation.internal.*`
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:828]: When `stripJSAnnotsOnExported` is called, we've just checked that the symbol doesn't have any annotation from `internal.*`. So I believe removing stuff from `internal.*` is unnecessary.

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala [hunk 2]
```diff
@@ -814,20 +822,41 @@ class PrepJSInterop extends MacroTransform with IdentityDenotTransformer { thisP
...
     private def checkRHSCallsJSNative(tree: ValOrDefDef, longKindStr: String)(using Context): Unit = {
-      // Check that the rhs is exactly `= js.native`
-      tree.rhs match {
-        case sel: Select if sel.symbol == jsdefn.JSPackage_native =>
-          // ok
-        case _ =>
-          val pos = if (tree.rhs != EmptyTree) tree.rhs.srcPos else tree.srcPos
-          report.error(s"$longKindStr may only call js.native.", pos)
-      }
+      if !tree.symbol.is(Exported) then
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:846]: Is this change needed? The other rules forbid an `export` in places where `checkRHSCallsJSNative` would be called.

Unless this prevents hard-to-understand cascading errors? If that's the reason, please say so in a comment.

**Review by sjrd — CHANGES_REQUESTED** [review]
Can an `export` definition be annotated itself? If yes, we should also forbid JS annotations on `export`s.

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala (hunk 2 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:846]: This is required because this code path will be reached whenever there is a definition in a JS Native type - so it is to prevent getting an extra error

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala (hunk 1 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala]: thank you for the explaination, I have removed the check for `internal.*`

**Comment by bishabosha** [comment]
@sjrd I have added a 'hack' for detecting if we are in a non-native JS trait

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala [hunk 3]
```diff
@@ -997,6 +1032,11 @@ object PrepJSInterop {
     /** A non-native JS object. */
     val JSMod = new OwnerKind(0x20)
 
+    // Modifiers - these add information to a base kind
+
+    /** A modifer for `JSClass` to signal a non-native JS trait */
+    val WithJSTrait = new OwnerKind(0x1000)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:1038]: Instead of introducing this concept of "modifier", I would rather introduce `JSTrait` as new base kind, sitting between `JSClass` and `JSMod`.

Note that `JSClass` and `JSMod` are never directly used for tests, so it only requires adapting the definitions of `JSNonNative` and `AnyClass` below to include `JSTrait` in addition to `JSClass`.

Comment (sjrd) [reply compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:1038]: Perhaps also rename `JSClass` into `JSNonTraitClass` to make things extra clear (not muddying what "class" means).

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala [hunk 4]
```diff
@@ -814,7 +825,28 @@ class PrepJSInterop extends MacroTransform with IdentityDenotTransformer { thisP
       super.transform(tree)
     }
 
+    /** Removes annotations from exported definitions (e.g. `export foo.bar`):
+     *  - `js.native`
+     *  - `js.annotation.*`
+     */
+    private def stripJSAnnotsOnExported(sym: Symbol)(using Context): Unit =
+      if !sym.is(Exported) then return
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala:833]: When the branch(es) of an if have side-effects, in the Scala.js coding style we impose them to be on a separate line, so that they stand out:
```suggestion
      if !sym.is(Exported) then
        return
```

**Review by sjrd — CHANGES_REQUESTED** [review]
Thanks. The logic looks good now. I have mostly a suggestion to turn your "hack" into properly fitting in the design.

File: compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala (hunk 3 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/sjs/PrepJSInterop.scala]: thanks, much cleaner now :)

**Review by sjrd — APPROVED** [review]
