### PR TITLE
Fix #12973: Add regression test

### LINKED ISSUE #12973: scala 3 repl does not work with -cp argument, needs -repl as workaround
## Compiler version

3.0.0 and 3.0.1-RC2

## Minimized code and output
The repl cannot be started with a `-cp` argument.

In 3.0.0 using the .zip from the release on Ubuntu:
```
$ scala -cp "some.jar" 
warning: command option is not correct.
```
In 3.0.1-RC2 instead of a warning, the `-help` output is printed.

## Expectation
* Should start the repl with "some.jar" on claspath.
* Should work as in Scala 2.
 
## Undocumented workaround:
```
$ scala -cp "some.jar" -repl
```

### PR DESCRIPTION
**Pull request by griggt**
Closes #12973

### CODE REVIEW

File: tests/pos/i12973.scala [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// Compiled and placed on the REPL classpath in the bootstrapCmdTests script
+// to test that launching the REPL with `scala -cp <path>` works (issue #12973)
+case class Bug12973():
+  def check = s"$productPrefix is fixed"
```
Comment (som-snytt) [inline tests/pos/i12973.scala:4]: 😄

**Review by anatoliykmetyuk — APPROVED** [review]
