### PR TITLE
Fix #9168: Use `()` for `finally` with empty expression

### LINKED ISSUE #9168: Awesome explanation receives a null tree
## Minimized code

```Scala
$ dotc -explain baddot.scala
-- [E018] Syntax Error: baddot.scala:7:30 --------------------------------------
7 |  def g: Int = try 42 finally ;
  |                              ^
  |                              expression expected but ';' found

Explanation
===========
An expression cannot start with ';'.

-- [E129] Potential Issue Warning: baddot.scala:7:21 ---------------------------
7 |  def g: Int = try 42 finally ;
  |                     ^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses

Explanation
===========
The pure expression null doesn't have any side effect and its result is not assigned elsewhere.
It can be removed without changing the semantics of the program. This may indicate an error.

1 warning found
1 error found
```

## Output

```scala
The pure expression null doesn't have any side effect
```

## Expectation

Awesome error messages should be robust about inputs without any ceremony by the message writer.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -2004,7 +2004,12 @@ object Parsers {
           }
 
           val finalizer =
-            if (in.token == FINALLY) { in.nextToken(); subExpr() }
+            if (in.token == FINALLY) {
+              in.nextToken();
+              val expr = subExpr()
+              if expr.span.exists then expr
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2010]: Instead of checking the span, can't we check if the tree is empty/null?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2010]: Both for `finally ;` and `finally null` the `expr` is `Literal(Constant(null))` but only the latter has a span.
