### PR TITLE
Fix #1703

### LINKED ISSUE #1703: crash on compilable code: NullPointerException
scalac compiles but dotc crashes.

$ cat abc.scala
```
class DuplicateClassName { () => {
  { () =>
    }
}
}

```

$ dotc abc.scala
```
-- Error: abc.scala ----------------------------------------------------------------------------------------------------
1 |class DuplicateClassName { () => {
  |                           ^^
  |                           not a legal self type clause

exception occurred while typechecking abc.scala

exception occurred while compiling abc.scala
Exception in thread "main" java.lang.NullPointerException
	at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:321)
	at dotty.tools.dotc.ast.untpd$.ref(untpd.scala:319)
	at dotty.tools.dotc.ast.desugar$.apply(Desugar.scala:936)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1478)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1484)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1494)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1492)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:132)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:57)
<snipped>
```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #1703. Review by @liufengyun

### CODE REVIEW

**Comment by odersky** [comment]
Was based by accident on #1717. We can separate if #1717 needs more work.

File: tests/pos/i1703.scala [hunk 1]
```diff
@@ -0,0 +1,5 @@
+class DuplicateClassName { () => {
+  { () =>
+    }
+}
+}
```
Comment (liufengyun) [inline tests/pos/i1703.scala]: LGTM, except the the test `tests/pos/i1703.scala` should be in neg directory.
