### PR TITLE
Fix #9994: Handle subtyping between two `ThisType`

### LINKED ISSUE #9994: Overriding method returning this type in final class from TASTy
## Full Reproduction

```
$ mkdir out/testStringBuilderFromTasty
$ sbt
sbt:dotty> dotty-bootstrapped/dotc -d out/testStringBuilderFromTasty community-build/community-projects/stdLib213/src/library/scala/collection/mutable/StringBuilder.scala
sbt:dotty> dotty-bootstrapped/dotc -from-tasty -classpath out/testStringBuilderFromTasty scala.collection.mutable.StringBuilder
...
-- Error: community-build/community-projects/stdLib213/src/library/scala/collection/mutable/StringBuilder.scala:87:6 
87 |  def addOne(x: Char): this.type = { underlying.append(x); this }
   |      ^
   |error overriding method addOne in trait Growable of type (elem: Char): (StringBuilder.this : StringBuilder);
   |  method addOne of type (x: Char): (StringBuilder.this : StringBuilder) has incompatible type
```

## Minimized Reproduction

`Bar.scala`
```scala
trait Foo:
  def foo: this.type

final class Bar extends Foo:
  def foo: this.type = this
```

```
$ mkdir out/test
$ sbt
sbt:dotty> dotty-bootstrapped/dotc StringBuilder.scala -d out/test
sbt:dotty> dotty-bootstrapped/dotc -from-tasty -classpath out/test Bar
```

### PR DESCRIPTION
**Pull request by smarter**
Previously, i9994.scala failed when compiled with `-Ythrough-tasty`
with:

```scala
7 |  def foo: this.type = this
  |      ^
  | error overriding method foo in trait Foo of type => (Bar.this : pkg.Bar);
  |   method foo of type => (Bar.this : pkg.Bar) has incompatible type
```

The two types were pretty-printed the same but were actually:

```scala
ExprType(ThisType(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <root>)),module class <empty>)),class Bar)))
```

and

```scala
ExprType(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Bar)))
```

Fixed by explicitly handling subtyping between two
`ThisType` (previously we felt through to `fourthTry` were the type of
the lhs was widened).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -310,6 +310,8 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
         def compareThis = {
           val cls2 = tp2.cls
           tp1 match {
+            case tp1: ThisType =>
+              (tp1.cls eq cls2) && recur(tp1.tref, tp2.tref)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:314]: I'm not sure about the condition here, `isSubPrefix` does something different:
https://github.com/lampepfl/dotty/blob/0525ba010061c060d759d869c63ea5b54415f729/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L859-L863
Should we do the same here and get rid of `isSubPrefix`, or is there a good reason for treating ThisType in prefix positions specially?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:314]: The isSubPrefix logic is needed to deal with double vision with self types.

I think the test here can be simplified to
```scala
case tp1: ThisType => tp1.cls eq cls2
```
The `tref` is just used to carry the class.

**Review by odersky — CHANGES_REQUESTED** [review]

**Comment by smarter** [comment]
> The tref is just used to carry the class.

Doesn't the tref also determine the path?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 1 above)
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:314]:
```suggestion
              tp1.cls eq cls2
```

**Review by odersky — APPROVED** [review]
Otherwise LGTM
