### PR TITLE
Reject all explicitly written type references with bad bounds

### LINKED ISSUE #15575: Explanation backwards on passing lower type to type argument with lower bound
## Compiler version

3.1.3, 3.2.0-RC1

## Minimized code

```scala
def foo[T >: Any]: Unit = ()
def bar[T]: Unit = foo[T & Any]
```
```scala
def foo[T >: CharSequence]: Unit = ()
foo[String]
```

## Output

```scala
-- [E057] Type Mismatch Error: -------------------------------------------------
1 |def bar[T]: Unit = foo[T & Any]
  |                         ^
  |                 Type argument T & Any does not conform to lower bound Any
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  | I tried to show that
  |   T & Any
  | conforms to
  |   Any
  | but the comparison trace ended with `false`:
  |
  |   ==> T & Any  <:  Any
  |   <== T & Any  <:  Any = true
  |
  | The tests were made under the empty constraint
   -----------------------------------------------------------------------------
1 error found
```
```scala
-- [E057] Type Mismatch Error: -------------------------------------------------
1 |foo[String]
  |    ^
  |    Type argument String does not conform to lower bound CharSequence
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  | I tried to show that
  |   String
  | conforms to
  |   CharSequence
  | but the comparison trace ended with `false`:
  |
  |   ==> String  <:  CharSequence
  |     ==> String  <:  CharSequence
  |       ==> CharSequence  <:  CharSequence (left is approximated)
  |         ==> (java.lang : java.lang.type)  <:  java.lang.type
  |         <== (java.lang : java.lang.type)  <:  java.lang.type = true
  |       <== CharSequence  <:  CharSequence (left is approximated) = true
  |     <== String  <:  CharSequence = true
  |   <== String  <:  CharSequence = true
  |
  | The tests were made under the empty constraint
   -----------------------------------------------------------------------------
1 error found
```

## Expectation

1. An explanation that shows `Any <: T & Any = false`.
2. An explanation that shows `CharSequence <: String = false`.

### LINKED ISSUE #15578: Pattern-bound types with bad bounds lead to unsoundness
```Scala
trait Foo[X >: Any <: Nothing]

@main def Test = (None: Option[Foo[?]]) match {
  case _: Option[Foo[t]] =>
    val unsound: Nothing = (5 : Any) : t
    (unsound : Unit => Unit).apply(())
}
```

The problem seems to be that pattern matching lets us name a type argument which does not correspond to a type member with known good bounds. In DOT, we would not be able to refer to `t`, so the issue would not show up.

Fixes we have thought of so far:
1) Disallowing classes with bad bounds on type parameters
2) Disallowing pat-mat from naming types with bad bounds / only letting pat-mat name types with bounds that are known to be good
3) Disallowing pat-mat from naming type arguments which are not top-level

See also the discussion in https://github.com/lampepfl/dotty/pull/15571 and related PR https://github.com/lampepfl/dotty/pull/15577.

### LINKED ISSUE #15609: Potentially too strict type argument bounds check
Community build regression for https://github.com/zio/zio (maintainer @jdegoes @adamgfraser)
Based on https://scala3.westeurope.cloudapp.azure.com/blue/organizations/jenkins/buildCommunityProject/detail/buildCommunityProject/843/pipeline/
Related change #15571 

## Compiler version
Works with 3.2.0-RC1
Fails with 3.2.1-RC1-bin-20220705-9bb3108-NIGHTLY

## Minimized code

```Scala
sealed trait ZIO[-R, +E, +A]
object ZIO {
  def uninterruptibleMask[R, E, A](f: Any => ZIO[R, E, A]): ZIO[R, E, A] = ???
}

final class ReleaseExit[-R, +E, E1, +A, B] {
  def apply[R1 <: R, E2 >: E <: E1, B1 <: B](use: A => ZIO[R1, E2, B1]): ZIO[R1, E2, B1] =
    ZIO.uninterruptibleMask[R1, E2, B1](restore => ???)
}
```

## Output

```scala
[error] ./test.scala:8:33: type argument has potentially unrealizable bounds  >: E <: E1
[error]     ZIO.uninterruptibleMask[R1, E2, B1](restore => ???)
[error]                                 ^^
Error compiling project (Scala 3.2.1-RC1-bin-20220705-9bb3108-NIGHTLY, JVM)```
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by odersky**
Reject type definitions or bound types in patterns that have possibly conflicting bounds.
However, we can suppress checks for type parameters, since these will need to be instantiated 
with good types themselves. We can also suppress checks for members of abstract classes
or traits or types in refinements since in each case these can be accessed only by selecting
from a concrete value, and bounds are checked when such a value is created. 

Fixes further unsoundness examples added to neg/i15569.scala.

Fixes #15578 
Fixes #15575
Fixes #15609

### CODE REVIEW

File: tests/neg/i13820.scala [hunk 1]
```diff
@@ -0,0 +1,5 @@
+trait Expr { type T }
+
+def foo[A](e: Expr { type T = A }) = e match
+  case e1: Expr { type T <: Int } =>
+    val i: Int = ??? : e1.T // error: unrealizable bounds
```
Comment (dwijnand) [inline tests/neg/i13820.scala:5]: I had a look at this one and it's because its bounds are `= A` and `<: Int`, i.e. `>: A <: A & Int` and it doesn't believe `A <: Int`.  But I think given the match that should be recorded as a fact, from matching the pattern.

The case is totally uncheckable of course, but maybe the compiler should infer that `A <: Int` and not emit this error.

I thought this, i.e. refined type patterns, would be a component @Linyxus' #14754 work but, surprisingly to me, they're not. 🤔

Comment (Linyxus) [reply tests/neg/i13820.scala]: > I thought this, i.e. refined type patterns, would be a component @Linyxus' #14754 work but, surprisingly to me, they're not. 🤔


Yes, ideally that should be done in #14754. But this is currently a missing part of it because we have not figured out a proper way to get the bound symbol in the pattern (if exists). The tricky part is that the symbol of the pattern only gets created *after* we perform GADT reasoning. I have some ideas of how to do this, maybe we could discuss them when reviewing #14754.

**Comment by odersky** [comment]
@dwijnand @Linyxus ping for review

File: compiler/src/dotty/tools/dotc/typer/Checking.scala [hunk 2]
```diff
@@ -86,17 +85,19 @@ object Checking {
...
-      case _ =>
-        true
-    recur(tpe)
+  def checkGoodBounds(sym: Symbol)(using Context): Boolean =
+    val bad = findBadBounds(sym.typeRef)
+    if bad.exists then
+      report.error(em"$sym has possibly conflicting bounds $bad", sym.srcPos)
+    !bad.exists
+
+  /** If `tp` dealiases to a typebounds L..H where not L <:< R
```
Comment (Linyxus) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:94]: There is a typo here: `L <:< R` -> `L <:< H`.

**Review by Linyxus — APPROVED** [review]
Otherwise LGTM!

File: compiler/src/dotty/tools/dotc/typer/Checking.scala (hunk 2 above)
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Checking.scala:94]:
```suggestion
  /** If `tp` dealiases to a typebounds L..H where not L <:< H
```

File: tests/semanticdb/expect/i5854.scala [hunk 3]
```diff
@@ -1,11 +1,7 @@
 package i5854
 
 class B {
-  // Known issue: Can't lookup the symbol of `b.A`
-  // we have to register the symbol of `b { type A }` to the refinementSymtab first
-  // then resolve, or assign same semanticdb symbol for both
-  // fake symbol for b.A, and real symbol of A in b
```
Comment (dwijnand) [inline tests/semanticdb/expect/i5854.scala:7]: Purposely deleted?  Just wondering if this is information worth keeping.

File: tests/semanticdb/metac.expect [hunk 4]
```diff
@@ -3945,20 +3945,20 @@ local0 => type A  >: Any <: Nothing
...
-[7:46..7:52): String -> scala/Predef.String#
-[8:6..8:7): b <- i5854/B#b.
-[8:16..8:17): A <- local0
-[8:21..8:24): Any -> scala/Any#
-[8:28..8:35): Nothing -> scala/Nothing#
-[8:40..8:44): loop -> i5854/B#loop().
-[9:6..9:10): loop <- i5854/B#loop().
-[9:14..9:21): Nothing -> scala/Nothing#
-[9:24..9:28): loop -> i5854/B#loop().
+[3:6..3:7): a <- i5854/B#a.
```
Comment (dwijnand) [inline tests/semanticdb/metac.expect:3948]: How did this get impacted?!  Can't eyeball what part of the diff affected it.  No concerns?

**Review by dwijnand — APPROVED** [review]
Those minor details aside, LGTM
