### PR TITLE
Don't try checking for ambiguous single-element tuples when in types

### LINKED ISSUE #23893: Error "recursive value needs type" when named tuple used with single field
## Compiler version

3.7.2
3.7.3-RC1

## Minimized code

```scala
val foo: (f: String) = "" *: EmptyTuple
val g = foo.f // ok
val f = foo.f // error: recursive value foo needs type
```

## Output

```
Recursive value foo needs type

 Run with -explain-cyclic for more details.
```

## Expectation

If the error is expected, then there should be different text (value `foo` has type annotation).
But I expect that it should compiling.

The following snippet is compiling:
```scala
val foo: (f: String, g: Int) = ("", 42)
val f = foo.f // error: recursive value foo needs type
```

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #23893

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 1]
```diff
@@ -152,7 +152,8 @@ object SymDenotations {
           println(i"${"  " * indent}completing ${if (isType) "type" else "val"} $name")
           indent += 1
 
-          if (myFlags.is(Touched)) throw CyclicReference(this)
+          if myFlags.is(Touched) then
+            throw CyclicReference(this)(using ctx.withOwner(symbol))
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:156]: The `using` bit is done below (in the "we don't need to print stuff" usual case), might as well do it here too. Also used the same formatting as below so it's easier to add a breakpoint.

File: compiler/src/dotty/tools/dotc/core/SymDenotations.scala [hunk 2]
```diff
@@ -164,7 +165,7 @@ object SymDenotations {
           }
           finally {
             indent -= 1
-            println(i"${"  " * indent}completed $name in $owner")
+            println(i"${"  " * indent}completed ${if (isType) "type" else "val"} $name in $owner")
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/core/SymDenotations.scala:168]: Replicate the printing in line 152 to disambiguate types and vals, I was confused when first debugging

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -3713,10 +3713,13 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
 
  /** Checks if `tree` is a named tuple with one element that could be
   *  interpreted as an assignment, such as `(x = 1)`. If so, issues a warning.
+  *  However, only checking the Tuple case if we're not within a type,
```
Comment (SolalPirelli) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
  *  However, only checks the Tuple case if we're not within a type,
```
(will do when rebasing on main anyway to not re-trigger CI for nothing)

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 4]
```diff
@@ -3713,10 +3713,13 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+  *  not only because that's not useful, but because it can lead to cyclic references while checking,
+  *  e.g., `val foo: (f: String) = ... ; val f = foo.f`
   */
-  def checkDeprecatedAssignmentSyntax(tree: untpd.Tuple | untpd.Parens)(using Context): Unit =
+  def checkDeprecatedAssignmentSyntax(tree: untpd.Tuple | untpd.Parens)(using ctx: Context): Unit =
```
Comment (mbovel) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Detail: you don't need to name the parameter, as we have the `ctx` helper that will summon the implicit `Context`.

Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]:
```suggestion
  def checkDeprecatedAssignmentSyntax(tree: untpd.Tuple | untpd.Parens)(using Context): Unit =
```

**Comment by som-snytt** [comment]
Worth adding that the commits could have been squashed and given a more meaningful text.

**Comment by SolalPirelli** [comment]
I'm definitely squashing them in the merge ^^ given that this is a 10ish line change I think the PR title is enough for the one commit that will result from the squash?
