### PR TITLE
More careful ClassTag instantiation

### LINKED ISSUE #23611: Regression in typer for zio-archive/zio-connect
Based on failure in OpenCB for `zio-archive/zio-connect` [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/16538777244/job/46777119324)

## Compiler version

Last good release: 3.7.3-RC1-bin-20250717-fb66af2-NIGHTLY
First bad release: 3.7.3-RC1-bin-20250718-42fdd76-NIGHTLY
Bisect points to e6bf7b82b6377943ec1098393a3e49a83eca7ecb / #23532

## Minimized code

```scala
import java.io.{File, IOException}
import java.net.URI
import java.nio.file.{Path, Paths}
import scala.reflect.ClassTag

trait FileConnectors { 
  def listPath(path: => Path): ZStream[Any, IOException, Path]

  final def listFile(file: => File): ZStream[Any, IOException, File] =
    for {
      path <- null.asInstanceOf[ZStream[Any, IOException, Path]]
      r    <- listPath(path).mapZIO(a => ZIO.attempt(a.toFile).refineToOrDie)
    } yield r
}

sealed trait ZIO[-R, +E, +A]
extension [R, E <: Throwable, A](self: ZIO[R, E, A])
  def refineToOrDie[E1 <: E: ClassTag]: ZIO[R, E1, A] = ???

object ZIO:
  def attempt[A](code: => A): ZIO[Any, Throwable, A] = ???
  
sealed trait ZStream[-R, +E, +A]:
  def map[B](f: A => B): ZStream[R, E, B] = ???
  def flatMap[R1 <: R, E1 >: E, B](f: A => ZStream[R1, E1, B]): ZStream[R1, E1, B]
  def mapZIO[R1 <: R, E1 >: E, A1](f: A => ZIO[R1, E1, A1]): ZStream[R1, E1, A1]
```

## Output

```scala
-- [E007] Type Mismatch Error: /Users/wmazur/projects/scala/community-build3/example.scala:12:6 
12 |      r    <- listPath(path).mapZIO(a => ZIO.attempt(a.toFile).refineToOrDie)
   |      ^
   |      Found:    ZStream[Any, Throwable, java.io.File]
   |      Required: ZStream[Any, java.io.IOException, java.io.File]
13 |    } yield r
   |
   | longer explanation available when compiling with `-explain`
1 error found
Compilation failed
```

## Expectation
Should compile

### PR DESCRIPTION
**Pull request by odersky**
We now use a blend of the new scheme and a backwards compatible special case if type variables as ClassTag arguments are constrained by further type variables.

Fixes #23611

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/Synthesizer.scala [hunk 1]
```diff
@@ -38,9 +38,29 @@ class Synthesizer(typer: Typer)(using @constructorOnly c: Context):
...
         instArg(tp.tp1)
       case tvar: TypeVar if ctx.typerState.constraint.contains(tvar) =>
+      	// If tvar has a lower or upper bound:
+      	//   1. If the bound is not another type variable, use this as approximation.
+      	//   2. Otherwise, if the type can be forced to be fully defined, use that type
+      	//      as approximation.
+      	//   3. Otherwise leave argument uninstantiated.
+      	// The reason for (2) is that we observed complicated constraints in i23611.scala
+      	// that get better types if a fully defined type is computed than if several type
+      	// variables are approximated incrementally. This is a minimization of some ZIP code.
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Synthesizer.scala]:
```suggestion
      	// variables are approximated incrementally. This is a minimization of some ZIO code.
```

**Comment by WojciechMazur** [comment]
I've tried it on community build, but the zio project is still failing - I've figured out that the reproducer was missing an important  part - the `CanFail[E]` implicit evidence in  `refineToOrDie` extension method. With this additional requirement it still fails: 
```scala
[error] ./example.scala:52:7
[error] Found:    ZStream[Any, Throwable, java.io.File]
[error] Required: ZStream[Any, java.io.IOException, java.io.File]
Error compiling project (Scala 3.8.0-RC1-bin-20250805-2b604c5, JVM (21))
```


Below there's a full reproducer: 
```scala
import java.io.{File, IOException}
import java.net.URI
import java.nio.file.{Path, Paths}
import scala.reflect.ClassTag

trait FileConnectors { 
  def listPath(path: => Path): ZStream[Any, IOException, Path]

  final def listFile(file: => File): ZStream[Any, IOException, File] =
    for {
      path <- null.asInstanceOf[ZStream[Any, IOException, Path]]
      r    <- listPath(path).mapZIO(a => ZIO.attempt(a.toFile).refineToOrDie)
    } yield r
}

sealed abstract class CanFail[-E]
object CanFail:
  given [E]: CanFail[E] = ???
  
sealed trait ZIO[-R, +E, +A]
extension [R, E <: Throwable, A](self: ZIO[R, E, A])
  def refineToOrDie[E1 <: E: ClassTag](using CanFail[E]): ZIO[R, E1, A] = ???

object ZIO:
  def attempt[A](code: => A): ZIO[Any, Throwable, A] = ???
  
sealed trait ZStream[-R, +E, +A]:
  def map[B](f: A => B): ZStream[R, E, B] = ???
  def flatMap[R1 <: R, E1 >: E, B](f: A => ZStream[R1, E1, B]): ZStream[R1, E1, B]
  def mapZIO[R1 <: R, E1 >: E, A1](f: A => ZIO[R1, E1, A1]): ZStream[R1, E1, A1]
```

**Comment by odersky** [comment]
The latest minimization also compiles now.

**Review by WojciechMazur — APPROVED** [review]
LGTM, fixes the `zio-archive/zio-connect` build, but does not resolve `erikerlandson/coulomb` issues yet
