### PR TITLE
Fix Select.copy in reflect API losing DerivedName for default getters

### LINKED ISSUE #17445: Copying of function application with default macro casue an error with -Xcheck-macro. (regression)
## Compiler version

3.1.1-RC1-bin-SNAPSHOT. (master at May. 9.2023)

## Minimized code

Macro.scala:
```Scala
package x

import scala.quoted.*
import scala.collection.*


object Macro {

    def myIndexWhere[A](arrOps: ArrayOps[A])(p: A=>Boolean, from:Int):Int =
      ???

    inline def changeIndexWhere[A](inline expr:A):A = ${
        changeIndexWhereImpl('expr)
    }

    def changeIndexWhereImpl[A:Type](expr:Expr[A])(using Quotes):Expr[A] = {
        import quotes.reflect.*
        val r0 = expr.asTerm 
        val checker = new TreeMap() {}
        val r = checker.transformTerm(r0)(Symbol.spliceOwner)
        r0.asExprOf[A]
    }

}
```

X.scala:
```Scala
package x

object X {

  def complileMe:Int = {
    Macro.changeIndexWhere{
      val arr = Array(1,2,3)
      val result = arr.indexWhere(_==2)
      result
    }
  }

}
```

## Output

```scala
info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 2 Scala sources to /Users/rssh/tests/dotty/fail-defparam/target/scala-3.3.1-RC1-bin-SNAPSHOT/classes ...
[error] -- Error: /Users/rssh/tests/dotty/fail-defparam/src/main/scala/x/X.scala:8:26 --
[error]  8 |    Macro.changeIndexWhere{
[error]    |    ^
[error]    |Malformed tree was found while expanding macro with -Xcheck-macros.
[error]    |               |The tree does not conform to the compiler's tree invariants.
[error]    |               |
[error]    |               |Macro was:
[error]    |               |scala.quoted.runtime.Expr.splice[scala.Int](((evidence$2: scala.quoted.Quotes) ?=> x.Macro.changeIndexWhereImpl[scala.Int](scala.quoted.runtime.Expr.quote[scala.Int]({
[error]    |  val arr: scala.Array[scala.Int] = scala.Array.apply(1, 2, 3)
[error]    |  val result: scala.Int = {
[error]    |    val $2$: scala.collection.ArrayOps[scala.Int] = scala.Predef.intArrayOps(arr)
[error]    |    $2$.indexWhere(((_$2: scala.Int) => _$2.==(2)), $2$.indexWhere$default$2)
[error]    |  }
[error]    |
[error]    |  (result: scala.Int)
[error]    |}).apply(using evidence$2))(scala.quoted.Type.of[scala.Int](evidence$2), evidence$2)))
[error]    |               |
[error]    |               |The macro returned:
[error]    |               |{
[error]    |  val arr: scala.Array[scala.Int] = scala.Array.apply(1, 2, 3)
[error]    |  val result: scala.Int = {
[error]    |    val $2$: scala.collection.ArrayOps[scala.Int] = scala.Predef.intArrayOps(arr)
[error]    |    $2$.indexWhere(((_$2: scala.Int) => _$2.==(2)), $2$.indexWhere$default$2)
[error]    |  }
[error]    |
[error]    |  (result: scala.Int)
[error]    |}
[error]    |               |
[error]    |               |Error:
[error]    |               |assertion failed: symbols differ for $2$.indexWhere$default$2
[error]    |was                 : method indexWhere$default$2
[error]    |alternatives by type:  of types 
[error]    |qualifier type      : ($2$ : scala.collection.ArrayOps[Int])
[error]    |tree type           : ($2$.indexWhere$default$2 : => Int @uncheckedVariance) of class class dotty.tools.dotc.core.Types$CachedTermRe
[error]    |               |
[error]    |stacktrace available when compiling with `-Ydebug`
[error]    |               |
[error]  9 |      val arr = Array(1,2,3)
[error] 10 |      val result = arr.indexWhere(_==2)
[error] 11 |      result
[error] 12 |    }
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from Macro.scala:12
[error] 12 |    inline def changeIndexWhere[A](inline expr:A):A = ${
[error]    |                                                      ^
[error] 13 |        changeIndexWhereImpl('expr)
[error] 14 |    }
[error]     ----------------------------------------------------------------------------
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed 9 May 2023, 18:12:50
```

## Expectation

It should be compiled.

After a short investigation,  I have discovered that in TreeChecker, we seek for existence of SimpleName for indexWhere$default$2
when `decl.members` of the appropriate symbol contains DerivedName

### PR DESCRIPTION
**Pull request by rssh**
## Summary

- Fix `Select.copy` in the reflect API (`QuotesImpl`) to preserve `DerivedName` (e.g. `DefaultGetterName`) instead of losing it through `String → SimpleName` conversion
- When the name is unchanged, preserve the original `Name` object from the tree
- When the name is changed to a string that represents a `DerivedName` (e.g. `"copy$default$1"`), unmangle it to recover the canonical interned `DerivedName`
- Add three test cases: identity TreeMap with `ArrayOps.indexWhere`, identity TreeMap with case class `copy`, and a macro that changes default getter names

## Details

The reflect API's `Select.unapply` returns names as `String`, and `Select.copy` converts them back via `toTermName`, creating a `SimpleName`. But default parameter getters (like `copy$default$1`, `indexWhere$default$2`) are stored in scopes as `DerivedName` (`DefaultGetterName`). Since `Name` equality in the compiler is reference-based (identity), the `SimpleName` couldn't be found during `TreeChecker` validation, causing `-Xcheck-macros` to reject trees produced by even an identity `TreeMap`.

Fixes #17445

### CODE REVIEW

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala [hunk 1]
```diff
@@ -579,7 +579,20 @@ class QuotesImpl private (using val ctx: Context) extends Quotes, QuoteUnpickler
...
+            val simpleName = name.toTermName
+            // If the qualifier type has a member whose name matches by string
+            // but not by identity (e.g. DerivedName vs SimpleName for default getters),
+            // use the member's canonical name to preserve name interning invariants.
+            val member = qualifier.tpe.member(simpleName)
+            if member.exists then simpleName
+            else
+              val unmangled = simpleName.unmangle(NameKinds.Scala2MethodNameKinds)
+              if (unmangled ne simpleName) && qualifier.tpe.member(unmangled).exists then unmangled
+              else simpleName
```
Comment (jchyb) [inline compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala]: Do we have a test case for this part? Overall looks good, but I'm wondering if the problem potentially fixed here would also happen for other NameKinds not included in in the Scala2MethodNameKinds list (and so I would need that specific test case I could adjust for that). I guess if we copy but change the qualifier, this code path would be taken, right?

**Review by jchyb — COMMENTED** [review]
Thank you so much! Overall looks great, I only have one question about one part

File: compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala (hunk 1 above)
Comment (rssh) [reply compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala]: yes,   tests/run-macros/i17445-new-default/Macro_1.scala

**Comment by Gedochao** [comment]
@jchyb is this still under review?

**Comment by jchyb** [comment]
Yes, I need to run it locally to check something. I apologize for the delays. I'll do it later today

**Review by jchyb — CHANGES_REQUESTED** [review]

File: tests/run-macros/i17445-new-default/Macro_1.scala [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+  inline def swapFirstArg[T](inline body: T): T =
+    ${ swapFirstArgImpl[T]('body) }
+
+  def swapFirstArgImpl[T: Type](body: Expr[T])(using Quotes): Expr[T] =
+    import quotes.reflect.*
+    val mapped = new TreeMap {
+      override def transformTerm(tree: Term)(owner: Symbol): Term =
+        tree match
+          case Select(qual, name) if name == "copy$default$2" =>
+            Select.copy(tree)(transformTerm(qual)(owner), "copy$default$1")
```
Comment (jchyb) [inline tests/run-macros/i17445-new-default/Macro_1.scala]:
```suggestion
          case Select(qual, name) if name == "copy$default$1" =>
            Select.copy(tree)(transformTerm(qual)(owner), "copy$default$0")
```
I was a little untrustworthy about the code path taken before, so I ran it with some println added, but it turns out you were correct. With that said, at first I was surprised to see it not visiting the wildcard case `case _ =>` at all, but that was caused by the index error here. After this change, I should be able to instantly accept and merge this (apologies for the wait).

Comment (rssh) [reply tests/run-macros/i17445-new-default/Macro_1.scala]: oops,  fixed
