### PR TITLE
Fix #5948: Be more careful with capturing

### LINKED ISSUE #5948: Type inference should be more careful when unifying wildcards to avoid unsoundness
```scala
class Foo[T](var elem: T)

object Test {
  def setFirstInPair[T](pair: (Foo[T], Foo[T])) = {
    pair._1.elem = pair._2.elem
  }

  def setFirstInList[T](list: List[Foo[T]]) = {
    list(0).elem = list(1).elem
  }

  def test1(): Unit = {
    val fooInt = new Foo(1)
    val fooString = new Foo("")
    val pair: (Foo[_], Foo[_]) = (fooInt, fooString)
    setFirstInPair(pair) // Should be an error, like in Scala 2
    println(fooInt.elem + 1) // ClassCastException in Dotty
  }

  def test2(): Unit = {
    val fooInt = new Foo(1)
    val fooString = new Foo("")
    val list: List[Foo[_]] = List(fooInt, fooString)
    setFirstInList(list) // Should be an error, like in Scala 2
    println(fooInt.elem + 1) // ClassCastException in Dotty
  }

  def main(args: Array[String]): Unit = {
    test1()
    test2()
  }
}
```
The Scala 2 errors are:
```scala
try/sound.scala:16: error: no type parameters for method setFirstInPair: (pair: (Foo[T], Foo[T]))Unit exist so that it can be applied to arguments ((Foo[_], Foo[_]))
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : (Foo[_], Foo[_])
 required: (Foo[?T], Foo[?T])
    setFirstInPair(pair) // Should be an error, like in Scala 2
    ^
try/sound.scala:16: error: type mismatch;
 found   : (Foo[_], Foo[_])
 required: (Foo[T], Foo[T])
    setFirstInPair(pair) // Should be an error, like in Scala 2
                   ^
try/sound.scala:24: error: no type parameters for method setFirstInList: (list: List[Foo[T]])Unit exist so that it can be applied to arguments (List[Foo[_]])
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : List[Foo[_]]
 required: List[Foo[?T]]
    setFirstInList(list) // Should be an error, like in Scala 2
    ^
try/sound.scala:24: error: type mismatch;
 found   : List[Foo[_]]
 required: List[Foo[T]]
    setFirstInList(list) // Should be an error, like in Scala 2
                   ^
```

Note that the following compiles fine in Scala 2, so it's not just applying a blanket ban on unifying with wildcards:
```scala
  def foo[T](foo: Foo[T]) = {}
  val x: Foo[_] = new Foo(1)
  foo(x)
```

I'm actually not sure how to reason about the difference in Dotty since we don't have a concept of existential types, /cc @Blaisorblade ?

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
Comment on last commit:

Delete DottyByteCodeTest

I am giving up. This is the worst sort of blindly testing the status quo! It tests some random
code and if that code has changed (because there is some optimization applied now) it fails.
Great! Problem is there's no way to automatically update the code. One has to go in manually and
fix the expected program including all labels! Copy pasting from the diff does not work and there's no
--update-check.

As long as things are like this I am afraid that bytecode tests are throwaway tests. They
blindly test the status quo, and if that changes our best action is to throw away the test.

~~~~


The problem is that while the old test indeed tested nothing of value, a new version of it would
test something interesting: That an unused cast is eliminated. But it's just too hard to update the test, so as long as the testing framework is not upgraded to be more user friendly, these tests are 
not as useful as they could be.

File: compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala [hunk 1]
```diff
@@ -401,55 +401,6 @@ class TestBCode extends DottyBytecodeTest {
...
-        |  }
-        |}
-      """.stripMargin
-
-    checkBCode(source) { dir =>
-      val moduleIn = dir.lookupName("Test.class", directory = false)
-      val moduleNode = loadClassNode(moduleIn.input)
-      val method = getMethod(moduleNode, "test")
-
-      val instructions = instructionsFromMethod(method)
```
Comment (allanrenucci) [inline compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala]: I agree this test is not maintainable. It tests that there is no `return` generated by pattern matcher and could be much simpler. I suggest rewriting the test as follow:
```scala
...
val instructions = instructionsFromMethod(method)
val hasReturn = instruction.exists {
  case Op(Opcodes.RETURN)) => true
  case _ => false
}
assertFalse(hasReturn)
```

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -1001,44 +1011,60 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
+                  case tparam: Symbol => arg1 & paramBounds(tparam)
+                  case _ => arg1 // This case can only arise when a hk-type is illegally instantiated with a wildcard
+                }
+              case _ => arg1
+            }
+            arg2.contains(arg1norm)
+          case _ =>
+            arg1 match {
+              case arg1: TypeBounds =>
+	            tparam match {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: This block is indented too much.

File: compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala (hunk 1 above)
Comment (odersky) [reply compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala]: That looks better, yes!

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -1001,44 +1011,60 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
+	              case tparam: Symbol if leftRoot.isStable || ctx.isAfterTyper =>
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Document why we need a special case after typer

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 4]
```diff
@@ -1001,44 +1011,60 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
+	                val captured = TypeRef(leftRoot, tparam)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I think this only works if some preconditions are carefully respected when calling `recur`, these preconditions should be added in a documentation comment above `def recur`.
Also can we add a sanity check like:
```suggestion
	                val captured = TypeRef(leftRoot, tparam)
	                assert(captured.exists, i"$leftRoot has no member $tparam in isSubArgs($args1, $args2, $tp1, $tparams2)")
```

File: library/src-bootstrapped/scala/internal/TypeBox.scala [hunk 5]
```diff
@@ -0,0 +1,5 @@
+package scala.internal
+
+final abstract class TypeBox[-L, +U] {
```
Comment (smarter) [inline library/src-bootstrapped/scala/internal/TypeBox.scala]: TypeBox can appear in error messages currently, e.g. with the original example from #4376
```scala
-- [E007] Type Mismatch Error: try/i4376.scala:5:5 -----------------------------
5 |    (Array.ofDim[String](1) : Array[_ >: Id[Nothing]])
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |Found:    Array[?1.CAP]
  |Required: Array[_ >: App.Id[_ <: Int]]
  |
  |where:    ?1 is an unknown value of type scala.internal.TypeBox[App.Id[Nothing], Any]
one error found
```
So we should either document what it means, or make the error message higher-level.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 6]
```diff
@@ -1001,44 +1011,60 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
-      val arg1 = args1.head
-      val arg2 = args2.head
-      isSubArg(arg1, arg2) || {
-        // last effort: try to adapt variances of higher-kinded types if this is sound.
-        // TODO: Move this to eta-expansion?
-        val adapted2 = arg2.adaptHkVariances(tparam.paramInfo)
-        adapted2.ne(arg2) && isSubArg(arg1, adapted2)
-      }
-    } && isSubArgs(args1.tail, args2.tail, tp1, tparams.tail)
+    def recur(args1: List[Type], args2: List[Type], tparams2: List[ParamInfo]): Boolean =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: I would rather use another name than `recur` here since this file also has a very long method called `recur` and I don't want to confuse them when reading code:
```suggestion
    def recurArgs(args1: List[Type], args2: List[Type], tparams2: List[ParamInfo]): Boolean =
```

File: compiler/src/dotty/tools/dotc/transform/Erasure.scala [hunk 7]
```diff
@@ -319,8 +319,14 @@ object Erasure {
   class Typer(erasurePhase: DenotTransformer) extends typer.ReTyper with NoChecking {
     import Boxing._
 
+    def isErased(tree: Tree)(implicit ctx: Context): Boolean = tree match {
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/Erasure.scala]: Since it seems to be used only in erasure, I'd leave it there.

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 8]
```diff
@@ -3609,8 +3616,12 @@ object Types {
...
   // ----- Skolem types -----------------------------------------------
 
-  /** A skolem type reference with underlying type `binder`. */
-  case class SkolemType(info: Type) extends UncachedProxyType with ValueType with SingletonType {
+  /** A skolem type reference with underlying type `info`.
+   *  Note: `info` is a var, since this allows one to create a number of skolem types
+   *  and fill in their infos with types that refers to the skolem types recursively.
+   *  This is used in `captureWildcards` in Typer`.
+   */
+  case class SkolemType(var info: Type) extends UncachedProxyType with ValueType with SingletonType {
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/Types.scala]: With the latest simplifications we can make it a val again.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: It's weird. VSCode insists on showing this indented to the left of where it really is.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Looks like the first character in the line is a tab, which github displays as 8 spaces.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 9]
```diff
@@ -2697,10 +2698,27 @@ class Typer extends Namer
...
       // try converting a constant to the target type
       val folded = ConstFold(tree, pt)
-      if (folded ne tree) return adaptConstant(folded, folded.tpe.asInstanceOf[ConstantType])
+      if (folded ne tree)
+        return adaptConstant(folded, folded.tpe.asInstanceOf[ConstantType])
+
+      // If tree's type is not stable and has wildcard arguments, make it
+      // stable by casting it to a skolem. I.e. a tree `t` of widened type `T`
+      // gets widened to `t.$asInstanceOf$[SkolemType(T)]`. This will enable
+      // capture comversion in the subsequent subtype check.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: typo:
```suggestion
      // capture conversion in the subsequent subtype check.
```

Comment (smarter) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Also I'm a bit confused on terminology: isn't "capture conversion" just another name for "skolemization" ? In that case the capture happens here, not in the subsequent subtype check.

File: library/src-bootstrapped/scala/internal/TypeBox.scala [hunk 10]
```diff
@@ -0,0 +1,5 @@
+package scala.internal
```
[the remark this answers is not in the document]
Comment (odersky) [reply library/src-bootstrapped/scala/internal/TypeBox.scala]: The new scheme does  not need TypeBox anymore.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 6 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Good point.

File: library/src-bootstrapped/scala/internal/TypeBox.scala (hunk 5 above)
Comment (odersky) [reply library/src-bootstrapped/scala/internal/TypeBox.scala]: TypeBox is gone now, fortunately.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 9 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I now explain what I mean by capture conversion in `isSubArgs`. I am not sure it's the best term for what happens there, but it corresponds to what Java uses.

**Comment by odersky** [comment]
We now have a much simpler conversion scheme e05c1a7, where we just need to skolemize the type of a tree as a whole, no need to go replace parameters by TypeBoxes.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 11]
```diff
@@ -2697,10 +2698,27 @@ class Typer extends Namer
...
       // try converting a constant to the target type
       val folded = ConstFold(tree, pt)
-      if (folded ne tree) return adaptConstant(folded, folded.tpe.asInstanceOf[ConstantType])
+      if (folded ne tree)
+        return adaptConstant(folded, folded.tpe.asInstanceOf[ConstantType])
+
+      // If tree's type is not stable and has wildcard arguments, make it
+      // stable by casting it to a skolem. I.e. a tree `t` of widened type `T`
+      // gets widened to `t.$asInstanceOf$[SkolemType(T)]`. This will enable
+      // capture conversion in the subsequent subtype check.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: To make it easier to find the relevant code:
```suggestion
      // capture conversion in the subsequent subtype check (see `compareCaptured` in `TypeComparer`)
```

**Comment by odersky** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 12]
```diff
@@ -1001,44 +1026,88 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
...
+         *
+         *   - If we are in mode TypevarsMissContext, which means we test implicits
+         *     for eligibility. In this case, we can be more permissive, since it's
+         *     just a pre-check. This relaxation is needed since the full
+         *     implicit typing might perform an adaptation that skolemizes the
+         *     type of a synthesized tree before comparing it with an expected type.
+         *     This adaptation gives the tree a path type, so that capture conversion
+         *     can do its thing. But no such adaptation is applied for implicit eligibility
+         *     testing, so we have to compensate.
+         */
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]:
```suggestion
         *
         *   See also `adaptToSubType` in `Typer` where a type might be skolemized to allow `leftRoot` to be a path.
         */
```
(there might be a better way to word this)

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 13]
```diff
@@ -130,9 +130,14 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] {
     }
   }
 
+  /** The current approximation state. See `ApproxState`. */
   private[this] var approx: ApproxState = FreshApprox
   protected def approxState: ApproxState = approx
 
+  /** The original left-hand type of the comparison. Gets reset
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala]: Not sure "reset" is the correct word since the value is saved and restored when leaving the nested isSubType. In any case, I think we can avoid having this variable at all by nesting `isSubArgs` inside `isSubType` and rename the parameters of `isSubType` from `tp1` and `tp2` to `origTp1`, `origTp2`. Then `leftRoot` can just be replaced by `origTp1`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 11 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: This comment is no longer part of the latest PR

**Comment by odersky** [comment]
Unfortunately the simplified scheme failed a test: hmm-shonan/Lifters.scala. I have therefore reverted to the old scheme with TypeBoxes.

The essence of the failure is condensed in test `pos/captured.scala`. That test also explains the difference between the two schemes I have tried.

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
test performance please

**Comment by odersky** [comment]
Here's the status:

I replaced the previous unsound capture conversion by two measures:

 1. Apply capture conversion in isSubArgs only if the LHS is a path (then it is sound)
 2. Skolemize wildcards in adapt if a tree does not conform to its expected type.

(2) alone would be sufficient, i.e. all tests pass with it. But performance tests indicate that it's better to also do (1). And, besides, (1) is in a sense less intrusive since we do not need to skolemize. So we should do it when we can.

**Comment by odersky** [comment]
@smarter I am done now. Can you give it another look?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 14]
```diff
@@ -2697,10 +2698,47 @@ class Typer extends Namer
       case tree: Closure => cpy.Closure(tree)(tpt = TypeTree(pt)).withType(pt)
     }
 
+    /** Replace every top-level occurrence of a wildcard type argument by
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: I'm not 100% clear on the notion of "top-level occurence" here, why is in an occurence in a branch of an AndOrType top-level, but not in the widened type of an `ExprType` for example ?

**Comment by odersky** [comment]
> * I still think we could avoid having `leftRoot` be a mutable variable by nesting `isSubArgs` in `isSubType`, but maybe there's a good reason not to do that?

Yes, it's because that way we don't thread a lot of parameters through all recursive calls (in the implementation, not the source). That's why `recur` is outside `isSubArgs`.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 14 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: It's because we have already widened the type before we pass it to `captureWildcards`.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I'll make a note explaining that.
