### PR TITLE
Enhance safe mode

### LINKED ISSUE #25389: Impossible to write any pattern match in safe mode, "Cannot refer to method throw"
## Compiler version

`3.8.4-RC1-bin-20260227-4e9c706-NIGHTLY`

## Minimized code

```scala
package example
import scala.language.experimental.safe

def main = Option(23) match { case Some(x) => (); case None => () }
```

## Output

the obligatory MatchError thrown in every pattern match is rejected.

```scala
-- Error: foo2.scala:4:65 ------------------------------------------------------
4 |def main = Option(23) match { case Some(x) => (); case None => () }
  |                                                                 ^
  |Cannot refer to method throw from safe code since it is neither compiled in safe mode nor tagged with @assumedSafe
1 error found
```

### PR DESCRIPTION
**Pull request by noti0na1**
This PR enhance safe mode and fix a bug:
* add `sym` exists check: the test in #25603 forgets the safe mode import
* add some more safe Java classes
* ~~enforce pattern match exhaustivity: The reason to enforce pattern match exhaustivity is one can intentionally create runtime exceptions by not matching a case.~~

Close #25389

## How much have you relied on LLM-based tools in this contribution?

Ask for suggestions on which classes to add

### CODE REVIEW

**Comment by bishabosha** [comment]
Im a bit surprised that some pattern matches work and others not e.g. https://github.com/scala/scala3/issues/25389

**Comment by noti0na1** [comment]
Technically, the last case of an exhaustive match can be marked as assumed safe.

We cannot just mark `OpsPackageClass` assumed safe for now. We need to way to specify `throw` is impure.

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 1]
```diff
@@ -903,6 +904,7 @@ object SpaceEngine {
     && !sel.tpe.hasAnnotation(defn.RuntimeCheckedAnnot)
     && {
       ctx.settings.YcheckAllPatmat.value
+      || Feature.safeEnabled
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: Here I am not sure. This is not strictly necessary since runtime exceptions are generally OK. So the argument would have to be that -YcheckAllPatPat generally improves the code. But does it? I see it is nowhere turned on except in a few tests that specifically test its behavior. So what evidence do we have that it leads to better code rather than being a nuisance to deal with?

**Review by odersky — CHANGES_REQUESTED** [review]
I suggest removing the exhaustivity part and leave it to be discussed further.

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala (hunk 1 above)
Comment (noti0na1) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala]: The original reason is currently we don't have a boundary to intercept all exceptions for strictly pure function, then a user can intentionally create runtime exceptions by not matching a case in order to leak information without using `throw` explicitly. I can remove this check for this PR and leave it to be discussed further.

**Comment by noti0na1** [comment]
If we think runtime exceptions are fine, then there is not need to forbid `throw` in safe mode I guess?

**Comment by odersky** [comment]
> If we think runtime exceptions are fine, then there is not need to forbid throw in safe mode I guess?

Indeed.

**Comment by noti0na1** [comment]
OK, I will add `OpsPackageClass` to the list
