### PR TITLE
Fix type aliases in beta-reduction of polyfunctions

### LINKED ISSUE #17052: Failure when beta-reducing polymorphic function
## Compiler version

3.3-RC2

## Minimized code

```Scala
def test[F[_]](fAny: F[Any]) =
  { [X] => (fx: F[X]) => { val fx2: F[X] = fx; () } }.apply[Any](fAny)
```

## Output
With `-Ycheck:all`
```scala
exception while typing val fx2: F[X] = fAny of class class dotty.tools.dotc.ast.Trees$ValDef # -1
exception while typing {
  val fx2: F[X] = fAny
  ()
} of class class dotty.tools.dotc.ast.Trees$Block # -1
exception while typing {
  type X = Any
  {
    val fx2: F[X] = fAny
    ()
  }
} of class class dotty.tools.dotc.ast.Trees$Block # -1
exception while typing def test[F[_$1]](fAny: F[Any]): Unit =
  {
    type X = Any
    {
      val fx2: F[X] = fAny
      ()
    }
  } of class class dotty.tools.dotc.ast.Trees$DefDef # -1
exception while typing @SourceFile("t/Macro_1.scala") final module class Macro_1$package() extends Object() {
  private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[Macro_1$package.type])
  def test[F[_$1]](fAny: F[Any]): Unit =
    {
      type X = Any
      {
        val fx2: F[X] = fAny
        ()
      }
    }
} of class class dotty.tools.dotc.ast.Trees$TypeDef # -1
exception while typing package <empty> {
  final lazy module val Macro_1$package: Macro_1$package = new Macro_1$package()
  @SourceFile("t/Macro_1.scala") final module class Macro_1$package() extends Object() {
    private def writeReplace(): AnyRef = new scala.runtime.ModuleSerializationProxy(classOf[Macro_1$package.type])
    def test[F[_$1]](fAny: F[Any]): Unit =
      {
        type X = Any
        {
          val fx2: F[X] = fAny
          ()
        }
      }
  }
} of class class dotty.tools.dotc.ast.Trees$PackageDef # -1
*** error while checking t/Macro_1.scala after phase MegaPhase{firstTransform, checkReentrant, elimPackagePrefixes, cookComments, checkStatic, checkLoopingImplicits, betaReduce, inlineVals, expandSAMs, elimRepeated, refchecks} ***
java.lang.AssertionError: assertion failed: Found:    (fAny : F[Any])
Required: F[X]
found: ??
expected: ??
tree = fAny while running Ycheck on t/Macro_1.scala
exception occurred while compiling t/Macro_1.scala
java.lang.AssertionError: assertion failed: Found:    (fAny : F[Any])
Required: F[X]
found: ??
expected: ??
tree = fAny while compiling t/Macro_1.scala
Exception in thread "main" java.lang.AssertionError: assertion failed: Found:    (fAny : F[Any])
Required: F[X]
found: ??
expected: ??
tree = fAny
```

## Expectation
Should pass `-Ycheck:all`.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #17052

### CODE REVIEW

**Review by smarter — DISMISSED** [review]

File: compiler/src/dotty/tools/dotc/transform/TreeChecker.scala [hunk 1]
```diff
@@ -533,6 +539,11 @@ object TreeChecker {
         i"owner chain = ${tree.symbol.ownersIterator.toList}%, %, ctxOwners = ${ctx.outersIterator.map(_.owner).toList}%, %")
     }
 
+    override def typedTypeDef(tdef: untpd.TypeDef, sym: Symbol)(using Context): Tree = {
+      assert(isTypeDefInfo(sym.info), i"wrong type, expect a template or type bounds for ${sym.fullName}, but found: ${sym.info}")
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/TreeChecker.scala:543]: This is fine as-is, but could also be checked with an or-type type test:
```suggestion
      assert(sym.info.isInstanceOf[ClassInfo | TypeBounds], i"wrong type, expect a template or type bounds for ${sym.fullName}, but found: ${sym.info}")
```

File: compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala [hunk 2]
```diff
@@ -1345,18 +1345,22 @@ object SourceCode {
...
-          this += " >: "
-          printTypeTree(low)
-      }
-      bounds.hi match {
-        case Inferred() => this
-        case hi =>
-          this += " <: "
-          printTypeTree(hi)
-      }
+      if bounds.low.tpe =:= bounds.hi.tpe then
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala]: I used `==` because an extension method could not be instantiated using `eq`. I will investigate that.

[the remark this answers is not in the document]
Comment (smarter) [reply compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala]: Ah I guess because the opaque type is not known to be a subtype of AnyRef, so == should be fine then (but the code uses =:= currently)

[the remark this answers is not in the document]
Comment (nicolasstucki) [reply compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala]: > but the code uses =:= currently

I see `==` in my last commit. Maybe you needed a refresh?

**Review by smarter — APPROVED** [review]

**Comment by nicolasstucki** [comment]
`getScaladoc2Type` was implemented by taking the output of `show` and then regexing it. As the output of `show` is unstable, the behavior of `getScaladoc2Type` changed. I fixed it by implementing `getScaladoc2Type`. @pikinier20 could you have a look at the implementation? Not the change in how `implicit` arguments changed. Now they introduce a space, I do not know if that can cause problems.

File: scaladoc/src/dotty/tools/scaladoc/tasty/Scaladoc2AnchorCreator.scala [hunk 3]
```diff
@@ -7,10 +7,67 @@ import scala.util.matching.Regex
...
+   *
+   *  Types are printed without their paths. No spaces are printed in the output
+   *  except for the one after `(implicit`.
+   */
+  private def signatureAnchor(using Quotes)(sym: quotes.reflect.Symbol): String =
+    import quotes.reflect.*
+    def signatureType(tp: quotes.reflect.TypeRepr): String =
+      tp match
+        case mt @ MethodType(paramNames, paramTypes, res) =>
+          val openClause = if mt.isImplicit then "(implicit " else "("
```
Comment (KacperFKorban) [inline scaladoc/src/dotty/tools/scaladoc/tasty/Scaladoc2AnchorCreator.scala:26]: There are two things that need changing here:
1. There should be no space after `implicit` i.e. in the anchor `implicit` should be merged with the parameter name.
2. Every parameter in an implicit parameter list should have a prepended `implicit` to it e.g. https://www.scala-lang.org/api/2.13.10/scala/collection/ArrayOps.html#flatten[B](implicitasIterable:A=%3Escala.collection.IterableOnce[B],implicitm:scala.reflect.ClassTag[B]):Array[B]

**Review by KacperFKorban — COMMENTED** [review]
Overall, the implementation looks good. The only place that needs tweaking is the `implicit` parameters part -- added a separate comment about that.

File: scaladoc/src/dotty/tools/scaladoc/tasty/Scaladoc2AnchorCreator.scala [hunk 4]
```diff
@@ -7,10 +7,66 @@ import scala.util.matching.Regex
...
+   *  - `f[U1,...](x1:T1,...)(impliciti1:U1,impliciti2:U2,...)...:R` for a `def f[U1, ...](x1: T1, ...)(implicit i1: U1, i2: U2...)...: R`
+   *
+   *  Types are printed without their paths. No spaces are printed in the output.
+   */
+  private def signatureAnchor(using Quotes)(sym: quotes.reflect.Symbol): String =
+    import quotes.reflect.*
+    def signatureType(tp: quotes.reflect.TypeRepr): String =
+      tp match
+        case mt @ MethodType(paramNames, paramTypes, res) =>
+          val implicitPrefix = if mt.isImplicit then "implicit " else ""
```
Comment (KacperFKorban) [inline scaladoc/src/dotty/tools/scaladoc/tasty/Scaladoc2AnchorCreator.scala:25]: There should be no space after `implicit` here. Otherwise LGTM

Comment (nicolasstucki) [reply scaladoc/src/dotty/tools/scaladoc/tasty/Scaladoc2AnchorCreator.scala:25]: Oops

**Review by KacperFKorban — APPROVED** [review]
