### PR TITLE
Adapt type parameters of typed eta expansion according to expected variances

### LINKED ISSUE #916: ListBuffer, Seq and IndexedSeq cannot be compiled together
dotc ./scala-scala/src/library/scala/collection/mutable/ListBuffer.scala -Ycheck:all ./scala-scala/src/library/scala/collection/immutable/Seq.scala ./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala

```scala
checking ./scala-scala/src/library/scala/collection/mutable/ListBuffer.scala after phase frontend
checking ./scala-scala/src/library/scala/collection/immutable/Seq.scala after phase frontend
checking ./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala after phase frontend
checking ./scala-scala/src/library/scala/collection/mutable/ListBuffer.scala after phase posttyper
checking ./scala-scala/src/library/scala/collection/immutable/Seq.scala after phase posttyper
checking ./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala after phase posttyper
checking ./scala-scala/src/library/scala/collection/mutable/ListBuffer.scala after phase pickler
checking ./scala-scala/src/library/scala/collection/immutable/Seq.scala after phase pickler
checking ./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala after phase pickler
checking ./scala-scala/src/library/scala/collection/mutable/ListBuffer.scala after phase TreeTransform:{firstTransform, checkReentrant}
checking ./scala-scala/src/library/scala/collection/immutable/Seq.scala after phase TreeTransform:{firstTransform, checkReentrant}
checking ./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala after phase TreeTransform:{firstTransform, checkReentrant}
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenMapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$MapFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$GenSetFactory$$CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type scala$collection$generic$SetFactory$$CC; assuming they are invariant
./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala:26: error: overriding method companion in trait IndexedSeq of type =>
  scala.collection.generic.GenericCompanion[[+hk$0] =>
    scala.collection.IndexedSeq[hk$0]
  ];
 method companion of type =>
  scala.collection.generic.GenericCompanion[[hk$0] =>
    scala.collection.mutable.IndexedSeq[hk$0]
  ] has incompatible type
  override def companion: GenericCompanion[IndexedSeq]  = IndexedSeq
                 ^
four warnings found
one error found
there were 2 deprecation warning(s); re-run with -deprecation for details

```

### PR DESCRIPTION
**Pull request by odersky**
Fixes #916. Review by @retronym?

### CODE REVIEW

**Comment by DarkDimius** [comment]
https://scala-ci.typesafe.com/job/dotty-master-validate-partest/670/consoleFull
https://scala-ci.typesafe.com/job/dotty-master-validate-partest/668/consoleFull
https://scala-ci.typesafe.com/job/dotty-master-validate-partest/667/consoleFull

the same test failed 3 times with same error. Does not look like random failure

```
[error] *** error while checking /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/OrderingConstraint.scala after phase restoreScopes ***
[error] class dotty.tools.dotc.reporting.Reporter$Error at /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/OrderingConstraint.scala:195: None of the alternatives of val <none> satisfies required predicate
[error] dotty.tools.dotc.reporting.Reporting$class.error(Reporter.scala:106)
[error] dotty.tools.dotc.core.Contexts$Context.error(Contexts.scala:53)
[error] dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:22)
[error] dotty.tools.dotc.typer.ErrorReporting$.errorTree(ErrorReporting.scala:19)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1154)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1149)
[error] dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error] dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:1149)
[error] dotty.tools.dotc.typer.Typer.typedType(Typer.scala:1190)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typedValDef$1.apply(Typer.scala:900)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typedValDef$1.apply(Typer.scala:897)
[error] dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
[error] dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:897)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1086)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1139)
[error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:92)
[error] dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:194)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1151)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1149)
[error] dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:154)
[error] dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:1149)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1$$anonfun$21.apply(Typer.scala:912)
[error] dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1$$anonfun$21.apply(Typer.scala:912)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.mapconserve$extension(Decorators.scala:67)
[error] dotty.tools.dotc.core.Decorators$ListOfListDecorator$$anonfun$nestedMapconserve$extension$1.apply(Decorators.scala:125)
[error] dotty.tools.dotc.core.Decorators$ListOfListDecorator$$anonfun$nestedMapconserve$extension$1.apply(Decorators.scala:125)
[error] dotty.tools.dotc.core.Decorators$ListDecorator$.loop$1(Decorators.scala:51)
[error] <<<
[error] exception occurred while compiling /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Annotations.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Constants.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Constraint.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/ConstraintHandling.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/ConstraintRunInfo.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Contexts.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Decorators.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Definitions.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/DenotTransformers.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Denotations.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Flags.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Hashable.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/NameOps.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Names.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/OrderingConstraint.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Periods.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Phases.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Scopes.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Signature.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/StdNames.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Substituters.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/SymDenotations.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/SymbolLoaders.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Symbols.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/TypeApplications.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/TypeComparer.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/TypeErasure.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/TypeOps.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/TyperState.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Types.scala, /home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/core/Uniques.scala
[info] !! 187 - pos/core                                  [compilation failed]
```

File: src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala [hunk 1]
```diff
@@ -147,6 +147,51 @@ object Scala2Unpickler {
...
+   *  types we get an error.
+   */
+  def adaptArgs(tparams: List[Symbol], args: List[Type])(implicit ctx: Context): List[Type] = tparams match {
+    case tparam :: tparams1 =>
+      val boundLambda = tparam.infoOrCompleter match {
+        case TypeBounds(_, hi) => hi.LambdaClass(forcing = false)
+        case _ => NoSymbol
+      }
+      def adaptArg(arg: Type): Type = arg match {
+        case arg: TypeRef if arg.symbol.isLambdaTrait =>
```
Comment (retronym) [inline src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala]: Unrelated to this change, but the definition of `isLambdaTrait`:

```
    final def isLambdaTrait(implicit ctx: Context): Boolean =
      isClass && name.startsWith(tpnme.LambdaPrefix)
```

Looks prone to falsely matching:

```
scala> class `Lambda|`
defined class Lambda$bar
```

File: src/dotty/tools/dotc/core/TypeApplications.scala [hunk 2]
```diff
@@ -524,21 +524,28 @@ class TypeApplications(val self: Type) extends AnyVal {
...
-  /** Convert a type constructor `TC` with type parameters `T1, ..., Tn` to
+  /** Convert a type constructor `TC` which has type parameters `T1, ..., Tn`
+   *  in a context where type parameters `U1,...,Un` are expected to
    *
    *     LambdaXYZ { Apply = TC[hk$0, ..., hk$n] }
    *
-   *  where XYZ is a corresponds to the variances of the type parameters.
+   *  Here, XYZ corresponds to the variances of
+   *   - `U1,...,Un` if the variances of `T1,...,Tn` are pairwise compatible with `U1,...,Un`,
+   *   - `T1,...,Tn` otherwise.
```
Comment (retronym) [inline src/dotty/tools/dotc/core/TypeApplications.scala]: I'm assuming that the "otherwise" case here only reached in ill-typed programs, and will result in an error being issued in `adapt`.

Comment (odersky) [inline src/dotty/tools/dotc/core/TypeApplications.scala]: I think it can also appear in tryLifted, which gets called during a subtype check. Essentially, we compare an unexpanded hk type with a type lambda and go on expanding the unexpanded type. It seems we can get a discrepancy in variances there.

File: src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala (hunk 1 above)
Comment (odersky) [inline src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala]: Right, we should restrict this to members of the scala package.

**Comment by odersky** [comment]
Heisenbug hates me. Or at least is very good in hiding...

**Comment by retronym** [comment]
@odersky Do you believe this bug is exposed by parallel test execution sharing a symbol table? Or is it a single-threaded non-determinism?

Assuming the former:

What sort of operations are supported concurrently?

I've reviewed a little of the caching code. This is prone to race condition:

```scala
    private def memberCache(implicit ctx: Context): LRUCache[Name, PreDenotation] = {
      if (myMemberCachePeriod != ctx.period) {
        myMemberCache = new LRUCache
        myMemberCachePeriod = ctx.period
      }
      myMemberCache
    }
```

Same story for `LRUCache#enter`:

```scala
  def enter(key: Key, value: Value): Unit = {
    keys(last) = key
    values(last) = value
    last = lastButOne
  }
```

**Comment by DarkDimius** [comment]
@retronym, those methods should be executed by different threads.
Partest gives a new `ContextBase` to every thread and this should mean that all symbols\types\trees\denotation are thread-private.
Though I've added a check to those places 7b94e98, just to be sure I'm not mistaking.

**Comment by odersky** [comment]
The latest additions to diagnostics have finally produced something
interesting. See partial log below. We are not finding a method in a scope,
even though the method (newRefArray) is present and the scope is
well-formed (as verified by checkConsistent). A "slow" (linear) search
finds the method but the initial hashtable lookup didn't. What's more,
several threads try to get the same method. So this seems to point to a
race condition. But as @darkdimius says, scopes should not be shared
between threads. We'll hopefully find out soon whether that's indeed the
case.

One other suggestion: The failures we are seeing happen when running the
bootstrapped dotty compiler, right? Can we instead run the original one for
a while and see whether the errors go away? I would like to exclude that
our implementation of lazy vals has some cross-talk. The failures we are
seeing would be consistent with the hypthesis that the lazy vals in
Definitions somehow get shared between several Definition instances.

[info] *** missing method:
dotty.tools.dotc.core.Decorators$StringDecorator@1ddb9b46 in module
Arrays
[info] decls = Scope{
[info]   def <init>: ()dotty.runtime.Arrays$
[info]   def newGenericArray: [T](length: Int)(implicit tag:
scala.reflect.ClassTag[T])Array[T]
[info]   def seqToArray: [T](xs: scala.collection.Seq[T], clazz:
Class[_])Array[T]
[info]   def newRefArray: [T](length: Int)T
[info]   def newByteArray: (length: Int)Array[Byte]
[info]   def newShortArray: (length: Int)Array[Short]
[info]   def newCharArray: (length: Int)Array[Char]
[info]   def newIntArray: (length: Int)Array[Int]
[info]   def newLongArray: (length: Int)Array[Long]
[info]   def newFloatArray: (length: Int)Array[Float]
[info]   def newDoubleArray: (length: Int)Array[Double]
[info]   def newBooleanArray: (length: Int)Array[Boolean]
[info]   def newUnitArray: (length: Int)Array[Unit]
[info] }
[info] newUnitArray
[info] newBooleanArray
[info] newDoubleArray
[info] newFloatArray
[info] newLongArray
[info] newIntArray
[info] newCharArray
[info] newShortArray
[info] newByteArray
[info] newRefArray
[info] seqToArray
[info] newGenericArray
[info] <init>
[info] *** missing method:
dotty.tools.dotc.core.Decorators$StringDecorator@1ddb9b46 in module
Arrays
[info] *** missing method:
dotty.tools.dotc.core.Decorators$StringDecorator@1ddb9b46 in module
Arrays
[info] decls = Scope{
[info]   def <init>: ()dotty.runtime.Arrays$
[info]   def newGenericArray: [T](length: Int)(implicit tag:
scala.reflect.ClassTag[T])Array[T]
[info]   def seqToArray: [T](xs: scala.collection.Seq[T], clazz:
Class[_])Array[T]
[info]   def newRefArray: [T](length: Int)T
[info]   def newByteArray: (length: Int)Array[Byte]
[info]   def newShortArray: (length: Int)Array[Short]
[info]   def newCharArray: (length: Int)Array[Char]
[info]   def newIntArray: (length: Int)Array[Int]
[info]   def newLongArray: (length: Int)Array[Long]
[info]   def newFloatArray: (length: Int)Array[Float]
[info]   def newDoubleArray: (length: Int)Array[Double]
[info]   def newBooleanArray: (length: Int)Array[Boolean]
[info]   def newUnitArray: (length: Int)Array[Unit]
[info] }
[info] decls = Scope{
[info]   def <init>: ()dotty.runtime.Arrays$
[info]   def newGenericArray: [T](length: Int)(implicit tag:
scala.reflect.ClassTag[T])Array[T]
[info]   def seqToArray: [T](xs: scala.collection.Seq[T], clazz:
Class[_])Array[T]
[info]   def newRefArray: [T](length: Int)T
[info]   def newByteArray: (length: Int)Array[Byte]
[info]   def newShortArray: (length: Int)Array[Short]
[info]   def newCharArray: (length: Int)Array[Char]
[info]   def newIntArray: (length: Int)Array[Int]
[info]   def newLongArray: (length: Int)Array[Long]
[info]   def newFloatArray: (length: Int)Array[Float]
[info]   def newDoubleArray: (length: Int)Array[Double]
[info]   def newBooleanArray: (length: Int)Array[Boolean]
[info]   def newUnitArray: (length: Int)Array[Unit]
[info] }
[info] newUnitArray
[info] newBooleanArray
[info] newDoubleArray
[info] newUnitArray
[info] newBooleanArray
[info] newDoubleArray
[info] newFloatArray
[info] newLongArray
[info] newIntArray
[info] newCharArray
[info] newShortArray
[info] newByteArray
[info] newRefArray
[info] seqToArray
[info] newGenericArray
[info] <init>
[info] newFloatArray
[info] newLongArray
[info] newIntArray
[info] newCharArray
[info] newShortArray
[info] newByteArray
[info] newRefArray
[info] seqToArray
[info] newGenericArray
[info] <init>
[error] **** slow search found: method newRefArray
[error] scope entries found:
[error] no more entries found!
[error] **** slow search found: method newRefArray
[error] scope entries found:
[error] **** slow search found: method newRefArray
[error] scope entries found:
[error] no more entries found!
[error] no more entries found!
[error] exception occurred while compiling
/home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/reporting/ConsoleReporter.scala,
/home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/reporting/Reporter.scala,
/home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/reporting/StoreReporter.scala,
/home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/reporting/ThrowingReporter.scala,
/home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/reporting/UniqueMessagePositions.scala
[error] dotty.tools.dotc.core.Types$TypeError: Missing method: module
Arrays . dotty.tools.dotc.core.Decorators$StringDecorator@1ddb9b46
[error] 	at dotty.tools.dotc.core.Denotations$Denotation.requiredMethod(Denotations.scala:229)
[error] 	at dotty.tools.dotc.core.Definitions.newRefArrayMethod(Definitions.scala:245)
[error] 	at dotty.tools.dotc.core.Definitions.isPolymorphicAfterErasure(Definitions.scala:608)
[error] 	at dotty.tools.dotc.core.TypeErasure$.transformInfo(TypeErasure.scala:174)
[error] 	at dotty.tools.dotc.transform.Erasure.transform(Erasure.scala:54)
[error] 	at dotty.tools.dotc.core.Denotations$SingleDenotation.currentIfExists(Denotations.scala:665)


On Fri, Nov 13, 2015 at 8:32 AM, Dmitry Petrashko <notifications@github.com>
wrote:

> @retronym <https://github.com/retronym>, those methods should be executed
> by different threads.
> Partest gives a new ContextBase to every thread and this should mean that
> all symbols\types\trees\denotation are thread-private.
> Though I've added a check to those places 7b94e98
> <https://github.com/lampepfl/dotty/commit/7b94e98e5cb75db27842ae2a21447eab4ff6a786>,
> just to be sure I'm not mistaking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/pull/950#issuecomment-156354188>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
@odersky Looking at implementation of `MutableScope`, I've found a huge inefficiency, though I do not see how it will lead to lookup failures: #953.

**Comment by retronym** [comment]
What is shared? The name table?

**Comment by odersky** [comment]
Yes, nametable is the only data structure that is shared.

**Comment by odersky** [comment]
rebased to master

**Comment by odersky** [comment]
Wow. Is the Heisenbug slayed, finally?

**Comment by odersky** [comment]
Removed all the added Heisenbug scaffolding for requiredMethod and force pushed.

**Comment by odersky** [comment]
Two successes in a row! I am taking the liberty to merge so that others can profit.
