### PR TITLE
Deskolemize PatternTypeConstrainer

### LINKED ISSUE #11103: Overconstrained GADT bounds in presence of type bounds with non-variant type constructors
## Minimized code

```Scala
@main def test: Unit = {
  class Foo
  class Bar
  
  trait UpBnd[+A]
  trait P extends UpBnd[Foo]
  
  def pmatch[A, T <: UpBnd[A]](s: T): A = s match {
    case p: P => new Foo
  }
  
  class UpBndAndB extends UpBnd[Bar] with P
  // ClassCastException: Foo cannot be cast to Bar
  val x = pmatch(new UpBndAndB)
}
```

## Output

<details><summary>Click to expand</summary>

```scala
java.lang.ClassCastException: main$package$Foo$1 cannot be cast to main$package$Bar$1
	at main$package$.test(main.scala:14)
	at test.main(main.scala:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

## Expectation
The code should be rejected because we do not have enough information about `A`.

I think that having `PatternTypeConstrainer#constrainSimplePatternType` widen the type parameters of type constructors appearing in bounds should do the trick.

### PR DESCRIPTION
**Pull request by abgruszecki**
Before this PR, constrainSimplePatternType did a bunch of manipulations on its arguments and then ran a subtype check. It wrapped one of the types in a SkolemType and replaced type arguments (if any) of the other one with wildcards. The point of those manipulations was to make TypeComparer take a specific path and compare appropriate subcomponents of `constrainSimplePatternType's` arguments. This turned out to be a problem overall. To improve the situation, we instead manually compare the appropriate subcomponents of `constrainSimplePatternType`'s arguments - the changes can be seen as inlining pieces of code from TypeComparer.

Also, this PR adds restoring the GADT constraint to TypeComparer - this turned out to be more important now that constrainSimplePatternType now does multiple isSubType checks.

Fixes #11103, #12476.

### CODE REVIEW

**Comment by abgruszecki** [comment]
test performance please

**Comment by abgruszecki** [comment]
test performance with #exhaustivity please

**Comment by abgruszecki** [comment]
@liufengyun am I doing something wrong? Why won't the performance check run?

**Comment by abgruszecki** [comment]
I added additional explanations to the first commit. The tests passed before and should also pass now.

**Comment by liufengyun** [comment]
@abgruszecki You are not on the whitelist. I'm now adding you.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 1]
```diff
@@ -3840,9 +3840,15 @@ class Typer extends Namer
 
         // approximate type params with bounds
         def approx = new ApproximatingTypeMap {
+          var alreadyExpanding: List[TypeRef] = Nil
           def apply(tp: Type) = tp.dealias match
             case tp: TypeRef if !tp.symbol.isClass =>
-              expandBounds(tp.info.bounds)
+              if alreadyExpanding contains tp then tp else
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:3846]: How is this connected to the rest of the changes? Did the rest trigger a SO here?

**Review by odersky — APPROVED** [review]
I did not understand all the changes in PatternTypeConstrainer, but it looks reasonable.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 1 above)
Comment (abgruszecki) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:3846]: Yes, this is the source of the SO that happened after restoring GADT constraints on failed subtype checks.

**Comment by abgruszecki** [comment]
There was a worrisome jump in performance benchmarks, I still want to take a look at that.

**Comment by abgruszecki** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala [hunk 2]
```diff
@@ -135,27 +143,39 @@ trait PatternTypeConstrainer { self: TypeComparer =>
...
     }
 
-    scrut.dealias match {
+    def dealiasDropNonmoduleRefs(tp: Type) = tp.dealias match {
+      case tp: TermRef =>
+        // we drop TermRefs that don't have a class symbol, as they can't
+        // meaningfully participate in GADT reasoning and just get in the way.
+        // Their info could, for an example, be an AndType. One example where
+        // this is important is an enum case that extends its parent and an
+        // additional trait - argument-less enum cases desugar to vals.
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala:157]: If you have a testcase for this, it'd be nice to refer to it here.

File: compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala [hunk 3]
```diff
@@ -194,7 +214,7 @@ trait PatternTypeConstrainer { self: TypeComparer =>
    *  case classes without also appropriately extending the relevant case class
    *  (see `RefChecks#checkCaseClassInheritanceInvariant`).
    */
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/PatternTypeConstrainer.scala:216]: The documentation comment above still talks about skolem wrapping, presumably that needs to be updated with the new scheme?

**Review by smarter — CHANGES_REQUESTED** [review]

**Comment by abgruszecki** [comment]
@smarter I modified the comments, can you mark it as accepted?

It seems that the second benchmark didn't show a performance decrease compared to current master, so I think we're good to go.

**Review by smarter — APPROVED** [review]
