### PR TITLE
Handle overloaded members when generating Java varargs bridges

### LINKED ISSUE #13043: Overriding Java varargs parameter of overloaded method requires explicit Array syntax
## Compiler version

3.0.0 and 3.0.1

## Minimized code

`intf.java`
```java
interface Intf {
    public void thing(int x);
    public void thing(String... y);
}
```

`impl.scala`
```Scala
class Impl extends Intf {
  override def thing(x: Int) = ???
  override def thing(y: String*) = ???
}
```

## Output

```scala
[error] -- Error: /home/score/varargs-overloading/src/main/scala/impl.scala:1:6 --------
[error] 1 |class Impl extends Intf {
[error]   |      ^
[error]   |class Impl needs to be abstract, since def thing(y: Array[? <: String]): Unit in trait Intf is not defined 
[error]   |(The class implements members with different types: List(override def thing(y: Seq[String]): Nothing in class Impl, override def thing(x: Int): Unit in class Impl)%
[error]   |  %)
[error] -- [E038] Declaration Error: /home/score/varargs-overloading/src/main/scala/impl.scala:3:15 
[error] 3 |  override def thing(y: String*) = ???
[error]   |               ^
[error]   |    method thing has a different signature than the overridden declaration
```

## Expectation

Like in Scala 2, this should be valid code.

The error can be worked around by using an `Array` type directly (not compatible with scala 2's behaviour) or by renaming/removing the overloads on the interface.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #13043

### CODE REVIEW

**Review by smarter — APPROVED** [review]

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala [hunk 1]
```diff
@@ -85,7 +102,8 @@ class ElimRepeated extends MiniPhase with InfoTransformer { thisPhase =>
   private def isVarargsMethod(sym: Symbol)(using Context) =
     hasVarargsAnnotation(sym) ||
       hasRepeatedParams(sym) &&
-      (sym.allOverriddenSymbols.exists(s => s.is(JavaDefined) || hasVarargsAnnotation(s)))
+        overridesJava(sym)
```
Comment (TheElectronWill) [inline compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala:105]: The previous version skipped the checks on overriden symbols when there were no repeated params (hence the parens). Is it intentional to change that?

**Review by TheElectronWill — APPROVED** [review]
Today I learned something :)

File: compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala]: No, this is missing a pair of parens
