### PR TITLE
Refine "can be handled by parent" condition when generting bridges

### LINKED ISSUE #13087: Compiler accepts class as non-abstract, then runtime system fails saying the class is abstract
## Compiler version

3.0.1

## Minimized code

```Scala
import scala.collection.mutable.Builder

class DDD[S,T,A]

trait NN[S, T, A, K[_], +D <: DDD[Set[S],T,K[A]]]
class NNN[S, T, K[_], A] extends NN[S, T, A, K, DDD[Set[S],T,K[A]]]

object NN {
  def newBuilder[S, T, A, K[_]]:
      NNbuilder[S, T, K, A, DDD[Set[S],T,K[A]], NN[S,T,A,K,?], Unit] =
    new NNNbuilder[S, T, K, A]
}

// Remove the type parameter E, hardcoding in E := Unit, and the issue
// goes away.
trait NNbuilder
  [S, T, K[_], A, +D <: DDD[Set[S],T,K[A]], +N <: NN[S,T,A,K,D], E]
    extends Builder[Unit, N] {
  def clear(): Unit = throw new UnsupportedOperationException()
  final def addOne(builder: E): this.type = this
}

// Unfold this class defn, and the issue goes away
abstract class AbstractNNNbuilder
  [S, T, K[_], A, +D <: DDD[Set[S],T,K[A]], +N <: NN[S,T,A,K,D], E]
    extends NNbuilder[S,T,K,A,D,N,E]

class NNNbuilder[S, T, K[_], A] extends AbstractNNNbuilder[
  S, T, K, A, DDD[Set[S], T, K[A]], NNN[S, T, K, A], Unit
] {
  override def result(): NNN[S, T, K, A] = new NNN[S, T, K, A]
}

@main def run: Unit = {
  val builder = NN.newBuilder[String, Char, Int, Set]
  builder += ()
  builder.result()
}
```

## Output (from `sbt`)

```scala
[info] compiling 1 Scala source to /home/jm/Lib/Scala/scratch/target/scala-3.0.1/classes ...
[info] done compiling
[info] running run 
[error] (run-main-56) java.lang.AbstractMethodError: Receiver class NNNbuilder does not define or inherit an implementation of the resolved method 'abstract scala.collection.mutable.Growable addOne(java.lang.Object)' of interface scala.collection.mutable.Growable.
[error] java.lang.AbstractMethodError: Receiver class NNNbuilder does not define or inherit an implementation of the resolved method 'abstract scala.collection.mutable.Growable addOne(java.lang.Object)' of interface scala.collection.mutable.Growable.
[error] 	at scala.collection.mutable.Growable.$plus$eq(Growable.scala:36)
[error] 	at scala.collection.mutable.Growable.$plus$eq$(Growable.scala:36)
[error] 	at AbstractNNNbuilder.$plus$eq(Main.scala:29)
[error] 	at Main$package$.run(Main.scala:45)
[error] 	at run.main(Main.scala:43)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
```

## Expectation

The compiler and RTS should agree that class `NNNbuilder` is not abstract.

### PR DESCRIPTION
**Pull request by odersky**
Fixes #13087

Reverses the outcome in i1240.scala.

### CODE REVIEW

**Comment by odersky** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala [hunk 1]
```diff
@@ -165,5 +166,64 @@ object OverridingPairs {
...
+   *    - matching names and types, but different target names
+   *
+   *  This method is used as a replacement of `matches` in some subclasses of
+   *  OverridingPairs.
+   */
+  def isOverridingPair(sym1: Symbol, sym2: Symbol, self: Type)(using Context): Boolean =
+    if     sym1.owner.is(JavaDefined, butNot = Trait)
+        && sym2.owner.is(JavaDefined, butNot = Trait)
+    then false // javac already handles these checks and inserts bridges
+    else if sym1.isType then true
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala:190]: I guess this isn't new code, but it's weird that this overload of isOverridingPair simply allows all types to match whereas the other overload will check that the kinds match, could this be harmonized?

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala [hunk 2]
```diff
@@ -488,29 +469,9 @@ object RefChecks {
...
-      then false // javac already handles these checks
-      else if sym1.isType then true
-      else
-        val sd1 = sym1.asSeenFrom(self)
-        val sd2 = sym2.asSeenFrom(self)
-        sd1.matchesLoosely(sd2)
-          && (sym1.hasTargetName(sym2.targetName)
-             || compatibleTypes(sym1, sd1.info, sym2, sd2.info))
-
     val opc = new OverridingPairs.Cursor(clazz):
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/RefChecks.scala:472]: PrepJSInterop also performs some overriding checks using Cursor, so I wonder if it should use a subclass of Cursor with the same logic we're now using here in RefChecks, or perhaps the checking logic in PrepJSInterop should be moved to RefChecks? /cc @sjrd

**Review by smarter — APPROVED** [review]
Otherwise LGTM

File: compiler/src/dotty/tools/dotc/typer/RefChecks.scala (hunk 2 above)
Comment (sjrd) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala:472]: It should probably be the same logic as in RefChecks, yes.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/typer/RefChecks.scala:472]: OK, I let you experiment with it. But I am going to merge this as is, since I do not think I have the time to look at all code that considers overriding pairs.

File: compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala (hunk 1 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala:190]: I am not sure. Maybe. But not in this PR. Somebody would have to take the time to experiment and figure this out. It's best to be conservative here since I am sure there are lots of code bases out there that we have not seen yet and that test this logic in interesting ways.
