### PR TITLE
Fix #13320: add .type to modules in messages

### LINKED ISSUE #13320: Improve "did you mean" message when meaning to use object singleton type
## Compiler version

3.0.1

## Minimized code

```Scala
object Foo:
  case object Boo

object Main:
  def main(args: Array[String]) =
    type t = Option[Foo.Boo]

```

## Output

```scala
error] -- [E008] Not Found Error: /tmp/1/Main.scala:7:24 ------------------------------
[error] 7 |    type t = Option[Foo.Boo]
[error]   |                    ^^^^^^^
[error]   |           type Boo is not a member of object Foo - did you mean Foo.Boo$?
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed

```

## Expectation
 type Boo is not a member of object Foo - did you mean Foo.Boo.type?

### PR DESCRIPTION
**Pull request by bjornregnell**
co-authored by: Anatolii Kmetiuk

### CODE REVIEW

**Comment by SethTisue** [comment]
test coverage?

**Comment by bjornregnell** [comment]
I can try to write a test case for it. 
With this test code:
```
object Foo:
  case object Boo

var x: Foo.Booo = Foo.Booo

object Main:
  def main(args: Array[String]) =
    type t = Option[Foo.Boo]
```
Above should with the fix now give these errors when scalac:
```
-- [E008] Not Found Error: /tmp/spree/test.scala:8:24 --------------------------
8 |    type t = Option[Foo.Boo]
  |                    ^^^^^^^
  |       type Boo is not a member of object Foo - did you mean Foo.Boo.type?
-- [E008] Not Found Error: /tmp/spree/test.scala:4:11 --------------------------
4 |var x: Foo.Booo = Foo.Booo
  |       ^^^^^^^^
  |      type Booo is not a member of object Foo - did you mean Foo.Boo.type?
-- [E008] Not Found Error: /tmp/spree/test.scala:4:22 --------------------------
4 |var x: Foo.Booo = Foo.Booo
  |                  ^^^^^^^^
  |          value Booo is not a member of object Foo - did you mean Foo.Boo?
```
Would that be an ok test case? Where to add it and how to name it?

**Comment by griggt** [comment]
I think the test should go in `tests/neg/i13320.scala` and should have an associated `i13320.check` file in the same directory to check the error messages.  Each line of the `.scala` file that is expected to generate a compiler error should be annotated with `// error`

More info on testing with checkfiles may be found here: https://dotty.epfl.ch/docs/contributing/testing.html#testing-with-checkfiles

**Comment by bjornregnell** [comment]
Thanks @griggt (I'll check this out in some weeks time when I have gotten my course going...)

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 1]
```diff
@@ -300,14 +300,14 @@ import transform.SymUtils._
 
       // The names of all non-synthetic, non-private members of `site`
```
Comment (prolativ) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:301]:
```suggestion
      // The symbols of all non-synthetic, non-private members of `site`
```

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 2]
```diff
@@ -325,11 +325,11 @@ import transform.SymUtils._
 
       // A list of possible candidate strings with their Levenstein distances
```
Comment (prolativ) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:326]:
```suggestion
      // A list of possible candidate symbols with their Levenstein distances
```

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 3]
```diff
@@ -325,11 +325,11 @@ import transform.SymUtils._
...
       // to the name of the missing member
-      def closest: List[(Int, String)] = candidates
+      def closest: List[(Int, Symbol)] = candidates
         .toList
-        .map(n => (distance(n, missing), n))
-        .filter((d, n) => d <= maxDist && d < missing.length && d < n.length)
-        .sorted  // sort by distance first, alphabetically second
+        .map(n => (distance(n.name.show, missing), n))
```
Comment (prolativ) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:330]: For less confusion I would advise to rename `n` to `s` all around here as we're now dealing with symbols instead of names

File: compiler/src/dotty/tools/dotc/reporting/messages.scala [hunk 4]
```diff
@@ -352,7 +352,11 @@ import transform.SymUtils._
             val siteName = site match
               case site: NamedType => site.name.show
               case site => i"$site"
-            s" - did you mean $siteName.$n?$enumClause"
+            val showName =
+              // Add .type to the name if it is a module
+              if n.isClass && n.is(Module) then s"${n.name.show}.type"
```
Comment (prolativ) [inline compiler/src/dotty/tools/dotc/reporting/messages.scala:357]: I believe you should get the same result with `.is(ModuleClass)` instead of checking two conditions

File: compiler/src/dotty/tools/dotc/reporting/messages.scala (hunk 3 above)
Comment (michelou) [reply compiler/src/dotty/tools/dotc/reporting/messages.scala:330]: I would use `sym` here (as in `val candidates = ...`) !

**Comment by bjornregnell** [comment]
Great comments! Thanks @prolativ @michelou ! 
(I'll have a go as soon as I can find some spare time for this.)

**Review by prolativ — APPROVED** [review]

**Comment by SethTisue** [comment]
🎉
