### PR TITLE
Patmat: Use less type variables in prefix inference

### LINKED ISSUE #16785: Unreasonably slow (or even non-terminating) compilation of pattern match involving GADT reasoning on nested types
## Compiler version

3.2.2
3.3.0-RC2

## Reproduction steps

```
git clone https://github.com/TomasMikula/libretto.git
cd libretto
git checkout 075f9f1911652ccaaa77dbf16e0b35ebd4a9dfc3
sbt core/compile
```

Note that I hit this bug in the middle of a refactoring session, so most likely the code should not compile just yet.
It is hard to minimize, because whatever I undo, I do get an actual compiler error. I'm hoping you could detect where it's looping, anyway.

**UPDATE:** Here's a minimization:

```Scala
class VarImpl[P, A]()

class ContextImpl[Var[_]]()

trait Lambdas[F[_, _], P] {

  type Var[A] = VarImpl[P, A]

}

class LambdasImpl[F[_, _], P] extends Lambdas[F, P] {

  opaque type Context = ContextImpl[Var]

  sealed trait Foo[A]
  case class Bar[T, U]() extends Foo[F[Var[T], Var[U]]]

  def go[X](that: Foo[Var[X]]): Unit =
    that match
      case _ => ()
}
```

## Output

After a while, compilation hangs with 100% of 1 CPU core.

### PR DESCRIPTION
**Pull request by dwijnand**
In code like:

    class Outer:
      sealed trait Foo
      case class Bar() extends Foo

      def mat(foo: Foo) = foo match
        case Bar() =>

When in the course of decomposing the scrutinee's type, which is
`Outer.this.Foo`, we're trying to instantiate subclass `Outer.this.Bar`,
the `Outer.this` is fixed - it needn't be inferred, via type variables
and type bounds.  Cutting down on type variables, particularly when GADT
symbols are also present, can really speed up the operation, including
making code that used to hang forever compile speedily.

Fixes #16785

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 1]
```diff
@@ -839,40 +839,59 @@ object TypeOps:
...
     //
     // See tests/patmat/i3938.scala
     class InferPrefixMap extends TypeMap {
       var prefixTVar: Type | Null = null
       def apply(tp: Type): Type = tp match {
-        case ThisType(tref: TypeRef) if !tref.symbol.isStaticOwner =>
+        case ThisType(tref) if !tref.symbol.isStaticOwner =>
           val symbol = tref.symbol
-          if (symbol.is(Module))
+          val singletonIx = singletons.indexWhere(_.classSymbol == symbol)
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:870]: Glad to learn there exists `indexWhere`  :-)

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 2]
```diff
@@ -839,40 +839,59 @@ object TypeOps:
...
+            singletons += tp
+            traverseChildren(tp)
+          case tp: TypeRef if tp.symbol.isAbstractOrParamType =>
+            gadtSyms += tp.symbol
+            traverseChildren(tp)
+          case _ =>
+            traverseChildren(tp)
+    TraverseTp2.traverse(tp2)
+    val singletons = TraverseTp2.singletons.toList
+    val gadtSyms   = TraverseTp2.gadtSyms.toList
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:859]: Some comment for `TraverseTp2` would be very helpful.

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 3]
```diff
@@ -839,40 +839,59 @@ object TypeOps:
...
       var prefixTVar: Type | Null = null
       def apply(tp: Type): Type = tp match {
-        case ThisType(tref: TypeRef) if !tref.symbol.isStaticOwner =>
+        case ThisType(tref) if !tref.symbol.isStaticOwner =>
           val symbol = tref.symbol
-          if (symbol.is(Module))
+          val singletonIx = singletons.indexWhere(_.classSymbol == symbol)
+          if singletonIx >= 0 then
+            prefixTVar = singletons(singletonIx)
+            prefixTVar.uncheckedNN
```
Comment (liufengyun) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala:873]: It seems to be possible that `tp2`  contains singletons in its type components that accidentally matches the prefix of `tp1`. But that would not matter in practice, users should not create such esoteric code.  Maybe add a comment mentioning it's intended for `tests/pos/i16785.scala`.

If it's possible to trigger the hang elsewhere in type checking, maybe also add that the fix is just a temporary workaround and should be removed once the deeper problem is resolved.

**Review by liufengyun — APPROVED** [review]
LGTM

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala (hunk 3 above)
Comment (dwijnand) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala:873]: Ah, yeah, I had that thought and forgot when I got to implementing it on tp2's side.  I'll try to see if I can avoid that problem and leave a test reference too.

> If it's possible to trigger the hang elsewhere in type checking, maybe also add that the fix is just a temporary workaround and should be removed once the deeper problem is resolved.

Root problem not withstanding I consider it better to be doing this in general: only add variables where needed.

**Comment by TomasMikula** [comment]
Hi, will this not be backported to release 3.3.0?

My project now
 - compiles with 3.2.2
 - compilation **hangs** with 3.3.0-RC4 (i.e. a **regression**)
 - compiles with 3.3.1-RC1-bin-20230425-c9ca7ce-NIGHTLY (I assume thanks to this fix, but can't be sure).

Note that the example in #16785 also hanged in 3.2.2, so it was not classified as a regression, whereas now I'm hitting a regression.

**Comment by TomasMikula** [comment]
Here's proof of regression:

```
git clone https://github.com/TomasMikula/libretto.git
cd libretto
git checkout b042b14bc4162488f2ad36c3727272212380b295

# compiles with the used Scala version 3.2.2
sbt lambda/compile

# Edit build.sbt, set
# ThisBuild / scalaVersion := "3.3.0-RC4"

# compilation hangs
sbt lambda/compile
```
