### PR TITLE
Fix #3823: Unpickle type holes

### LINKED ISSUE #3823: Quoted types fail unpickling
The following code fails when running the unpickling the quote inside the `show`
```scala
import dotty.tools.dotc.quoted.Runners._
import scala.quoted._
object Test {
  def main(args: Array[String]): Unit = {
    def f[T](x: Expr[T])(t: Type[T]) = '{//'
      val z: t.unary_~ = ~x
    }
    println(f('(2))('[Int]).show)
  }
}
```
It fails with

```
Caused by: scala.MatchError: 255 (of class java.lang.Integer)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthType$1(TreeUnpickler.scala:231)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readType(TreeUnpickler.scala:361)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTpt(TreeUnpickler.scala:1057)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readNewDef(TreeUnpickler.scala:690)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedDef(TreeUnpickler.scala:635)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStat(TreeUnpickler.scala:813)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readIndexedStats$1(TreeUnpickler.scala:851)
	at dotty.tools.dotc.core.tasty.TastyReader.until(TastyReader.scala:125)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:851)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readStats(TreeUnpickler.scala:855)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readBlock$1(TreeUnpickler.scala:939)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:962)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1047)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.$anonfun$readNewDef$4(TreeUnpickler.scala:656)
	at dotty.tools.dotc.core.tasty.TreeUnpickler$LazyReader.complete(TreeUnpickler.scala:1119)
	at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy(Trees.scala:800)
	at dotty.tools.dotc.ast.Trees$WithLazyField.forceIfLazy$(Trees.scala:798)
	at dotty.tools.dotc.ast.Trees$ValDef.forceIfLazy(Trees.scala:656)
	at dotty.tools.dotc.ast.Trees$ValOrDefDef.rhs(Trees.scala:346)
	at dotty.tools.dotc.ast.Trees$ValOrDefDef.rhs$(Trees.scala:346)
	at dotty.tools.dotc.ast.Trees$ValDef.rhs(Trees.scala:656)
	at dotty.tools.dotc.core.quoted.PickledQuotes$.unpickleQuote(PickledQuotes.scala:45)
	at dotty.tools.dotc.core.quoted.PickledQuotes$.quotedToTree(PickledQuotes.scala:35)
	at dotty.tools.dotc.quoted.ExprCompiler$ExprFrontend.$anonfun$runOn$1(ExprCompiler.scala:61)
	at scala.collection.immutable.List.map(List.scala:283)
	at dotty.tools.dotc.quoted.ExprCompiler$ExprFrontend.runOn(ExprCompiler.scala:57)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$3(Run.scala:125)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.trackTime(Stats.scala:47)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2(Run.scala:123)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$2$adapted(Run.scala:121)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:121)
	at dotty.tools.dotc.Run.$anonfun$compileUnits$1(Run.scala:141)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:88)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:107)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:99)
	at dotty.tools.dotc.quoted.ExprCompiler$ExprRun.compileExpr(ExprCompiler.scala:91)
	at dotty.tools.dotc.quoted.QuoteDriver.show(QuoteDriver.scala:42)
	at dotty.tools.dotc.quoted.Runners$$anon$1.show(Runners.scala:27)
	at scala.quoted.Expr.show(Expr.scala:8)
...
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala [hunk 1]
```diff
@@ -136,7 +136,7 @@ class ReifyQuotes extends MacroTransform {
       else {
         val trefs = importedTypes.toList
         val typeDefs = for (tref <- trefs) yield {
-          val tag = New(defn.QuotedTypeType.appliedTo(tref), Nil)
+          val tag = New(defn.QuotedTypeType.appliedTo(tref), Nil) // FIXME: should be an implicitly inferred defn.QuotedTypeType.appliedTo(tref)
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala]: @odersky could you have a look at this one. I did not manage to use the `MacroTransformWithImplicits` and `inferImplicitArg` to get the implicit argument. I looked at b466e0afa6ea1908fcef8dc0fe2b30fa2887949a but it might be too outdated.

File: tests/run-with-compiler/i3823-c.scala [hunk 2]
```diff
@@ -0,0 +1,12 @@
+import dotty.tools.dotc.quoted.Runners._
+import scala.quoted._
+object Test {
+  def main(args: Array[String]): Unit = {
+    def f[T](x: Expr[T])(implicit t: Type[T]) = '{
+      val z = ~x
+    }
```
Comment (nicolasstucki) [inline tests/run-with-compiler/i3823-c.scala]: This quote will be pickled as 
```scala
type T = [[1| ]]
{
  val z: T = [[0| ]]
  ()
}
```

Comment (nicolasstucki) [reply tests/run-with-compiler/i3823-c.scala]: After `ReifyQuotes` the tree is
```scala
package <empty> {
  import dotty.tools.dotc.quoted.Runners._
  import scala.quoted._
  final lazy module val Test: Test$ = new Test$()
  @scala.annotation.internal.SourceFile("Foo.scala") final module class Test$()
     extends
   Object() { this: Test.type => 
    def main(args: Array[String]): Unit = 
      {
        def f[T >: Nothing <: Any](x: quoted.Expr[T])(implicit t: quoted.Type[T]
          )
        : scala.quoted.Expr[Unit] = 
          scala.runtime.quoted.Unpickler.unpickleExpr[Unit](
            scala.collection.immutable.Nil.::[String](
              
                "\\¡«\037\0203\0200\00\00\00\00\00\00\00\00\00\00\00\00\016\02M0£\01\0204ASTs\01\0206_root_\01\0201\'\01\0203Any\01\0205scala\01\0201z\01\0201T\0200¤\0200¢6\0201\0201\0236\0202u\02036\0204\0214\0226\0214\0211\02\0201\0206\02055\0230ÿ\0201\0200\0203\0211\0206£\0205ÿ\0201\02012\0235\025\025"
              
            )
          , [x,new scala.quoted.Type[T]() : Any])
        println(
          f[Int](
            scala.runtime.quoted.Unpickler.unpickleExpr[Int](
              scala.collection.immutable.Nil.::[String](
                
                  "\\¡«\037\0203\0200\00\00\00\00\00\00\00\00\00\00\00\00\n%fð\0235\01\0204ASTs\01\0206_root_\01\0201\'\01\0203Any\01\0205scala\0200\0216\0200\02146\0201\0201\0210\0202u\02036\0204<\0202\025"
                
              )
            , [ : Any])
          )(quoted.Type.IntTag).show(
            dotty.tools.dotc.quoted.Runners.runner[Unit]
          )
        )
      }
  }
}
```

Note that the arguments for the holes are `x` and `new scala.quoted.Type[T]()` hence when unpickling we get an instance of `scala.quoted.Type` with an erased `T`. Instead of `new scala.quoted.Type[T]()` we should have `t`.

Comment (nicolasstucki) [reply tests/run-with-compiler/i3823-c.scala]: If we have 
```scala
def f[T](x: Expr[T])(implicit t: Type[T]) = '{
   val z: ~t= ~x
}
```

then the hole receives the `t` and works as expected.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 3]
```diff
@@ -42,26 +55,24 @@ object PickledQuotes {
     val tastyBytes = TastyString.unpickle(expr.tasty)
     val unpickled = unpickle(tastyBytes, expr.args)
     unpickled match {
-      case PackageDef(_, (vdef: ValDef) :: Nil) => vdef.rhs
-      case PackageDef(_, (tdef: TypeDef) :: Nil) => tdef.rhs
+      case PackageDef(_, (vdef: ValDef) :: Nil) =>
+        if (vdef.name == "quote".toTermName) vdef.rhs
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala]: Maybe add a dollar to the name? It's unambiguous now, but if we sometimes in the future would add toplevel ValDefs to Scala someone could write `val quote = ...`.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala [hunk 4]
```diff
@@ -42,26 +55,24 @@ object PickledQuotes {
...
+        else vdef.rhs.asInstanceOf[TypeApply].args.head
     }
   }
 
   /** Encapsulate the tree in a top level `val` or `type`
-   *    `<tree>` ==> `package _root_ { val ': Any = <tree> }`
+   *    `<tree>` ==> `package _root_ { val quote: Any = <tree> }`
    *    or
-   *    `<type tree>` ==> `package _root_ { type ' = <tree tree> }`
+   *    `<type tree>` ==> `package _root_ { val typeQuote: Any = null.asInstanceOf[<tree>] }`
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala]: Same here, probably safer to write e.g. `$typeQuote`.

File: compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala (hunk 3 above)
Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala]: It should be safe as this will only be contained in expressions `Expr[T]` and expressions do not have packages (hence not top level vals). Regardless the name with `$` is better as it shows that it is a synthetic construct.
