### PR TITLE
Fix #8647: Remove TypeParamRef from instantiated test

### LINKED ISSUE #8647: Nested type parameter in case of match type prevent subsequent cases from being reached
This works:
```scala
final class Two[A, B]()

final class Bla

object Test {

  type Foo[X] = X match
    case Two[Bla, _] =>
      String
    case Two[String, _] =>
      Int

  def test: Foo[Two[String, String]] = 1
}
```
But if I add a type parameter to Bla, then it doesn't work anymore:
```scala
final class Two[A, B]()

final class Bla[A]

object Test {

  type Foo[X] = X match
    case Two[Bla[_], _] =>
      String
    case Two[String, _] =>
      Int

  def test: Foo[Two[String, String]] = 1
}
```
```scala
-- [E007] Type Mismatch Error: try/i8644.scala:28:39 ---------------------------
28 |  def test: Foo[Two[String, String]] = 1
   |                                       ^
   |                                 Found:    (1 : Int)
   |                                 Required: Test.Foo[Two[String, String]]
```

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
It appears that `TypeParamRef`-s that appear in types inside `provablyDisjoint` always come from local type binders. As a result, it's OK to consider types containing `TypeParamRef`-s to be `fullyInstantiated` and trust the result of `isSameType` at that point.

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -2359,7 +2359,7 @@ class TypeComparer(initctx: Context) extends ConstraintHandling[AbsentContext] w
                     x && {
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2359]: I don't understand the comment above: "We can only trust a "no" from `isSameType` when both `arg1` and `arg2` are fully instantiated.". What does "trust" mean here? `isSameType(tp1, tp2)` returning false means "I wasn't able to prove that tp1 and tp2 are the same type, having or not having type variables in these types does not change that.

Comment (OlivierBlanvillain) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2359]: It means we interpret `!isSameType(A, B)` as "`A` and `B` are definetly different type" when the conditions in `&& { ... }` are met. The alternative would be to write another recursive method `provablyNotSameType` in the same style as `provablyDisjoint` that would be used here to draw disjointness conclusions from invarant type parameters.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2359]: > It means we interpret !isSameType(A, B) as "A and B are definetly different type"

Unfortunately that's not true, even if you exclude type variables, type parameters and abstract types. For example `Nothing` and `Int & String` are the same type, but the compiler doesn't know that and `isSameType` will return false.

> The alternative would be to write another recursive method provablyNotSameType in the same style as provablyDisjoint that would be used here to draw disjointness conclusions from invarant type parameters.

That seems like a good way forward yeah.

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:2359]: >  The alternative would be to write another recursive method provablyNotSameType

It looks like scalac has something like this for deciding if it needs to emit an unchecked type test warning, this could be a good inspiration: https://github.com/scala/scala/blob/dfb8f7364a56fc01ad1eaea57980fba586ef6914/src/compiler/scala/tools/nsc/typechecker/Checkable.scala#L275
(we may in fact want to use this in our own unchecked type tests which are currently pretty broken: https://github.com/lampepfl/dotty/pull/8808)
