### PR TITLE
Fixes and improvements to erasure

### LINKED ISSUE #11743: Support extension methods on erased types
## Compiler version

3.0.0-RC1
## Minimized example

```Scala
//  import language.experimental.erasedTerms
import scala.compiletime.erasedValue
type UnivEq[A]
object UnivEq:
  erased def force[A]: UnivEq[A] = erasedValue
  extension [A](erased proof: UnivEq[A])
    inline def univEq(a: A, b: A): Boolean =
      a == b
```
With `-Yerased-terms` or the commented line (after #11695) is merged.

## Output

```scala
-- [E040] Syntax Error: Foo.scala:6:16 -----------------------------------------
6 |  extension [A](erased proof: UnivEq[A])
  |                ^^^^^^
  |                an identifier expected, but 'erased' found
```

## Expectation
It should compile

### PR DESCRIPTION
**Pull request by odersky**
- [x] make erasedTerms a language import
- [x] drop -YerasedTerms setting
- [x] make erased a soft modifier
- [x] fix bugs in erasure involving context functions
- [x] allow `erased` on classes as well
- [x] explain erased classes in docs

Fixes #11743

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Currently `erased` only defined semantics on terms. What would be the semantics of an `erased class`? What is the use-case? 

My intuition is that it would serve a similar purpose as a Phantom type, but in that case I would start with `erased type`. Any instance of such type must be erased.

Another one that might be useful if the `erased object`. This would serve as a place to define `erased given` without generating the object at runtime. It might even be possible to add non-retained `inline def` in such a object.

**Comment by japgolly** [comment]
> What would be the semantics of an erased class? What is the use-case?

An opinion from the sidelines: I would love to use this to define compile-time-only proofs. Having some kind of proof be an `erased class` would give me confidence that it's guaranteed to be erased and that it can't accidentally be misused in a way that it's instantiated at runtime. My understanding is that without the class itself being marked as `erased`, the onus is on me (or downstream users) to always ensure we don't accidentally forget to declare a `given`/function-arg/whatever as `erased`. That would get pretty tedious pretty quickly in large code bases.

**Question:** if an `erased class` is used without being marked as such (eg. `given` instead of `erased given`), would it be
1. a compilation error (eg. `hey! you need to change "given" to "erased given")
2. or could the compiler automatically mark the `given` as `erased` too?

As a user, I think (2) would be awesome :smile:

**Comment by japgolly** [comment]
Btw this would be one of my first use-cases for this awesome feature: universal equality proof at compile-time guaranteed to always just translate to `x == y` after compilation.

```scala
erased final class UnivEq[A]:
  inline def univEq(a: A, b: A): Boolean =
    a == b
```

I'm currently in the process of defining it like this for Scala 3 without an `erased class`:

```scala
// Declaring in a different package because inline methods aren't allowed in opaque types companions :(
package internal:
  opaque type UnivEq[A] = Unit

  object UnivEq:
    def force[A]: UnivEq[A] =
      ()

type UnivEq[A] = internal.UnivEq[A]

object UnivEq:

  inline def force[A]: UnivEq[A] =
    internal.UnivEq.force

  extension [A](proof: UnivEq[A])
    inline def univEq(a: A, b: A): Boolean =
      a == b
```

Then of course there are extension method ops but you get the idea.

https://github.com/japgolly/univeq

**Comment by odersky** [comment]
> As a user, I think (2) would be awesome 😄

So you'll be happy to know that that's what's implemented!

**Comment by odersky** [comment]
Btw, I tried to make the import
```scala
import language.experimental.erased
```
but that failed the bootstrap since erased is a hard keyword under -Yerased-terms. Maybe once `-Yerased-terms` is gone we can do that change.

**Comment by japgolly** [comment]
> So you'll be happy to know that that's what's implemented!

Oh wow @odersky that is fantastic news!! :heart:

**Comment by japgolly** [comment]
In case you hadn't thought of it yet, `=:=` and `<:<` seem like ideal first uses from Scala stdlib.

**Comment by odersky** [comment]
> In case you hadn't thought of it yet, =:= and <:< seem like ideal first uses from Scala stdlib.

Yes, once we get a chance to change it.

File: compiler/src/dotty/tools/dotc/config/Feature.scala [hunk 1]
```diff
@@ -19,11 +19,13 @@ object Feature:
...
     QualifiedName(nme.deprecated, str.toTermName)
 
-  private val Xdependent = experimental("dependent")
-  private val XnamedTypeArguments = experimental("namedTypeArguments")
-  private val XgenericNumberLiterals = experimental("genericNumberLiterals")
-  private val Xmacros = experimental("macros")
-  private val symbolLiterals: TermName = deprecated("symbolLiterals")
+  private val namedTypeArguments = experimental("namedTypeArguments")
+  private val genericNumberLiterals = experimental("genericNumberLiterals")
+  private val macros = experimental("macros")
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/config/Feature.scala:24]:
```suggestion
  private val scala2macros = experimental("macros")
```

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/config/Feature.scala:24]: We also use the name macros for Scala 3 macros in the compiler.

**Review by nicolasstucki — COMMENTED** [review]
> In case you hadn't thought of it yet, `=:=` and `<:<` seem like ideal first uses from Scala stdlib.

That is one of the oldest usecases we have (see [old gist](https://gist.github.com/nicolasstucki/1ab19828fff43ff1e57889d33c181571)). But we need to be able to break the binary compatibility of the standard library to make this change.  Note that to implement this we do NOT need erased classes unless we try to naively port the old implementation.
```scala
type <::<[-From, +To]
type =::=[From, To] <: (From <::< To)
erased given [X]: (X =::= X) = scala.compiletime.erasedValue
extension [From](x: From)
  inline def cast[To](using From <::< To): To = x.asInstanceOf[To] // Safe cast because we know `From <:< To`
```

File: tests/neg/safeThrowsStrawman2.scala [hunk 2]
```diff
@@ -0,0 +1,33 @@
+import language.experimental.erasedTerms
+
+object scalax:
+  erased class CanThrow[E <: Exception]
+  type CTF = CanThrow[Fail]
```
Comment (nicolasstucki) [inline tests/neg/safeThrowsStrawman2.scala:5]: Why not?
```scala
  type CanThrow[E <: Exception]
  type CTF = CanThrow[Fail]
```

File: tests/run/safeThrowsStrawman.scala [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import language.experimental.erasedTerms
+
+object scalax:
+  erased class CanThrow[-E <: Exception]
```
Comment (nicolasstucki) [inline tests/run/safeThrowsStrawman.scala:4]:
```suggestion
  type CanThrow[-E <: Exception]
```

**Review by nicolasstucki — CHANGES_REQUESTED** [review]
We should split this PR into 2
* Make erased an experimental language feature
* Add new `erased class`, find use cases where it is needed and make sure it is sound (phantom types?)

**Comment by nicolasstucki** [comment]
> I'm currently in the process of defining it like this for Scala 3 without an erased class:
> ```scala
> // Declaring in a different package because inline methods aren't allowed in opaque types companions :(
> package internal:
>   opaque type UnivEq[A] = Unit
> 
>   object UnivEq:
>     def force[A]: UnivEq[A] =
>       ()
> 
> type UnivEq[A] = internal.UnivEq[A]
> 
> object UnivEq:
> 
>   inline def force[A]: UnivEq[A] =
>     internal.UnivEq.force
> 
>   extension [A](proof: UnivEq[A])
>     inline def univEq(a: A, b: A): Boolean =
>       a == b
> ```

It seems like this code can simply be translated to erased types as 
```scala
type UnivEq[A]
object UnivEq:
  erased def force[A]: UnivEq[A] = erasedValue
  extension [A](erased proof: UnivEq[A])
    inline def univEq(a: A, b: A): Boolean =
      a == b
```
Issue: we cannot have extension method on erased types (see #11743)

**Comment by nicolasstucki** [comment]
It seems we do not have any use case for `erased class` assuming that #11743 is fixed.

**Comment by nicolasstucki** [comment]
Note: There is a pattern that I have seen since the early days of phantom type. Whenever we try to port a class that should be phantom types, if we try to emulate the original definitions as a class we always end up with awkward and useless code. On the other hand, when we simply started by defining the type and `type Foo[X]` and added the functionality on to of it the code ended up simpler, shorter and easier to understand.

**Comment by nicolasstucki** [comment]
In the current verison of `erased class` we are mixing two distinct features.
* Make all members erased (as shorthand for withing `type` with extension methods on erased `self` / workaround #11743)
* Make the type a phantom type (allow inference of erasedness of definitions based on type)

We also accidentally make the type a subtype of `AnyRef`. This is not a desirable property of a phantom type.

If we what to add phantom type we should start from `erased type` which would have more usecases.

**Comment by nicolasstucki** [comment]
This is failing
```scala
erased class A
erased class B extends A
```

File: compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala [hunk 4]
```diff
@@ -925,7 +925,7 @@ class RefinedPrinter(_ctx: Context) extends PlainPrinter(_ctx) {
       else PrintableFlags(isType)
     if (homogenizedView && mods.flags.isTypeFlags) flagMask &~= GivenOrImplicit // drop implicit/given from classes
     val rawFlags = if (sym.exists) sym.flags else mods.flags
-    if (rawFlags.is(Param)) flagMask = flagMask &~ Given
+    if (rawFlags.is(Param)) flagMask = flagMask &~ Given &~ Erased
```
[the remark this answers is not in the document]
Comment (odersky) [reply compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala:928]: No, inline per param, not per clause

File: docs/docs/reference/metaprogramming/erased-terms-spec.md [hunk 5]
```diff
@@ -5,10 +5,11 @@ title: "Erased Terms Spec"
 
 ## Rules
 
-1. The `erased` modifier can appear:
+1. `erased` is a soft modifier. It can appear:
    * At the start of a parameter block of a method, function or class
    * In a method definition
    * In a `val` definition (but not `lazy val` or `var`)
+   * In a `class` or `trait` definition
```
[the remark this answers is not in the document]
Comment (odersky) [reply docs/docs/reference/metaprogramming/erased-terms-spec.md:12]: Right now I'd only do the minimum we need. Instead of `erased object` you can always write `erased val`.

File: docs/docs/reference/metaprogramming/erased-terms.md [hunk 6]
```diff
@@ -187,4 +193,36 @@ end Machine
    m.turnOn().turnOn() // error: Turning on an already turned on machine
 ```
 
+## Erased Classes
+
+`erased` can also be used as a modifier for a class. An erased class is intended to be used only in erased definitions. If the type of a val definition or parameter is
+a (possibly aliased, refined, or instantiated) erased class, the definition is assumed to be `erased` itself. Likewise, a method with an erased class return type is assumed to be `erased` itself. Since given instances expand to vals and defs, they are also assumed to be erased if the type they produce is an erased class. Finally
```
[the remark this answers is not in the document]
Comment (odersky) [reply docs/docs/reference/metaprogramming/erased-terms.md:199]: I disagree. If `val x: CanThrow` becomes `erased val x: CanThrow` then `def x: CanThrow` should also become `erased def x: CanThrow`, and `def x(): CanThrow` should become `erased def x(): CanThrow`.

[the remark this answers is not in the document]
Comment (odersky) [reply docs/docs/reference/metaprogramming/erased-terms.md:199]: I don't think there's a soundness issue since these are purely syntactic conventions, akin to simple desugarings.

File: tests/neg/safeThrowsStrawman.scala [hunk 7]
```diff
@@ -0,0 +1,29 @@
+import language.experimental.erasedTerms
+import annotation.implicitNotFound
+
+object scalax:
+  @implicitNotFound("The capability to throw exception ${E} is missing.\nThe capability can be provided by one of the following:\n - A using clause `(using CanThrow[${E}])`\n - A throws clause in a result type such as `X throws ${E}`\n - an enclosing `try` that catches ${E}")
+  erased class CanThrow[-E <: Exception]
```
[the remark this answers is not in the document]
Comment (odersky) [reply tests/neg/safeThrowsStrawman.scala:6]: Classes are sticky, types are not. That's why we use a class for `erased`.

**Comment by odersky** [comment]
I think the presumed similarity with phantom types is misleading. This is something completely different, with different rules.

**Comment by nicolasstucki** [comment]
Now that I understand what it does, the misleading part is that `erased class` does not define a class but only the type. There must be a way to make this distinction clearer.

My current understanding is that an erased class defines a type and that any type that derives from will also be an erased type. Then if a term has an erased type it automatically becomes erased. Is that description complete?

**Comment by nicolasstucki** [comment]
Inference of erasedness of parameters does not seem to be working
```scala
import scala.language.experimental.erasedTerms

erased class ErasedTerm

type <::<[-From, +To] <: ErasedTerm

type =::=[From, To] <: (From <::< To)

erased given [X]: (X =::= X) = scala.compiletime.erasedValue

extension [From](x: From)
  inline def cast[To](using From <::< To): To = x.asInstanceOf[To] // Safe cast because we know `From <:< To`


def convert[A, B](a: A)(using /*erased*/ x: A <::< B): B =
  // println(x) // error: OK because x should be erased
                // but currently x is not marked as erased which it should
  a.cast[B]


@main def App: Unit = convert[Int, Int](3) // should not be an error
```

**Comment by odersky** [comment]
> Inference of erasedness of parameters does not seem to be working

That's because types don't generate erased vals; only erased classes do this. And types themselves cannot be erased.

**Comment by nicolasstucki** [comment]
Then how do we abstract over capabilities? I would have expected the following to work but I guess it won't 

```scala
erased class Capability

def foo[Cap <: Capability](using c: Cap): T = ...
```

Is `c` erased or not? Given the previous rule it seams not. But the only values we can create for it are erased.

I remember that this kind of code appeared with some utility functions for capabilities bit I can't remember which one at the moment.

**Comment by nicolasstucki** [comment]
Are `CanThrow[X] & CanThrow[Y]` and `CanThrow[X] | CanThrow[Y]` erased?

**Comment by odersky** [comment]
> My current understanding is that an erased class defines a type 

Yes, in a trivial sense, like any other class.

> and that any type that derives from will also be an erased type. 

No.

> Then if a term has an erased type it automatically becomes erased. Is that description complete?

True only if you replace type by class. `type` definitions cannot be erased.

**Comment by odersky** [comment]
Type parameters and union / intersection types are never erased. It's just class references as the docs state. 

The whole thing is just a syntactic convenience, and we want to keep it simple. Maybe we can extend it in the future if use cases demand it.

**Comment by japgolly** [comment]
Could we add this to the 3.0.0-RC2 milestone?

**Comment by odersky** [comment]
@nicolasstucki The reason want `erased` classes but not `erased` `type` definitions is that type definitions get erased, so we cannot check after erasure whether any references to types persist.

**Comment by odersky** [comment]
> Could we add this to the 3.0.0-RC2 milestone?

Yes, I think that would be good. We should let people try it out asap.

**Comment by nicolasstucki** [comment]
I have some big concerns about the current semantics of `erased class` and it's usability given that I have been unable to port many of the previous use cases. But, I see the value in inferring the erasedness of the terms. I believe that we must tweak the semantics a bit to be able to express all the interesting cases and be much clearer in the docs about what and `erased class`. The current definition feels completely mechanism driven and we should move to a more semantic definition.

As long as users understand that this is **experimental** and that we might change the semantics later it is ok to merge this as is. For this we also need to make sure #11774 is in place. 

This will also help us gather more use-cases from the community.

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
FWY @odersky, I had an idea of how to remove even more syntactic overhead from the `erased` `given`/`def`/`val` definition. See https://github.com/lampepfl/dotty/issues/11739#issuecomment-800447757.

File: compiler/src/dotty/tools/dotc/config/Feature.scala [hunk 8]
```diff
@@ -24,7 +24,7 @@ object Feature:
   private val scala2macros = experimental("macros")
 
   val dependent = experimental("dependent")
-  val erasedTerms = experimental("erasedTerms")
+  val erasedDefinitions = experimental("erasedDefinitions")
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/config/Feature.scala:27]: Erased is not only about definitions. It is also about the term values they provide. This is completely lost with this new name. The `erased class` concept is also about erasing term definitions and uses as arguments. Therefore, the scope of the feature has not really changed.

**Review by nicolasstucki — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/config/Feature.scala (hunk 8 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/config/Feature.scala:27]: The fact that if you erase a definition you also erase its RHS, and if you erase a parameter, you also erase its argument follows naturally since it's the only thing that makes sense. But the trigger is the `erased` on a definition. Or parameter, but I think it's OK to include that in the meaning.

**Review by nicolasstucki — APPROVED** [review]
