### PR TITLE
FullParametrization: allow to have $this of ThisType.

### LINKED ISSUE #1089: TailRec breaks path-dependent types in local-to-block method
This is a minimization of the bug I am encountering in #1061. As @smarter predicted, it is related to TailRec.
```scala
package hello

import scala.annotation.tailrec

class Enclosing {
  class SomeData(val x: Int)

  def localDef(): Unit = {
    def foo(data: SomeData): Int = data.x

    @tailrec
    def test(i: Int, data: SomeData): Unit = {
      if (i != 0) {
        println(foo(data))
        test(i - 1, data)
      }
    }

    test(3, new SomeData(42))
  }
}

object world extends App {
  println("hello dotty!")
  new Enclosing().localDef()
}
```
Compiling with `-Ycheck:tailrec` causes:
```
> run -Ycheck:checkReentrant,tailrec examples/hello.scala
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Packaging /localhome/doeraene/projects/dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running dotty.tools.dotc.Main -Ycheck:checkReentrant,tailrec examples/hello.scala
[error] checking examples/hello.scala after phase TreeTransform:{firstTransform, checkReentrant}
[error] checking examples/hello.scala after phase TreeTransform:{refchecks, elimRepeated, normalizeFlags, extmethods, expandSAMs, tailrec, liftTry, classOf}
[error] *** error while checking examples/hello.scala after phase classOf ***
[error] java.lang.AssertionError: assertion failed: error at examples/hello.scala:14
[error] type mismatch:
[error]  found   : $this.SomeData(data)
[error]  required: Enclosing.this.SomeData
[error] tree = Ident(data)
[error] scala.Predef$.assert(Predef.scala:165)
[error] dotty.tools.dotc.transform.TreeChecker$Checker.adapt(TreeChecker.scala:334)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:205)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:513)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:511)
[error] dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:316)
[error] dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:355)
[error] dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:192)
[error] dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:434)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:512)
... // and many more
```
Changing any of the following things will make it pass Ycheck:

* Change `Enclosing` from `class` to `object`
* Use `String` instead of `SomeData`
* Move `foo()` outside of `localDef()`
* Move both `foo()` and `test()` outside of `localDef()`
* Alter `test()` so that it is not tail-recursive anymore
* Move `SomeData` inside `localDef()`

The presence or absence of the annotation `@tailrec` has no impact. What matters is that `test()` is effectively tail-recursive.
Things that

### PR DESCRIPTION
**Pull request by DarkDimius**
TailRec methods remain members of enclosing class,
it means that they can refer to methods that require this.type.
It means that tailrec, unlike value classes is not allowed to widen
type of $this to it's full self type.

Fixes #1089

### CODE REVIEW

**Comment by DarkDimius** [comment]
@sjrd please review

File: src/dotty/tools/dotc/transform/FullParameterization.scala [hunk 1]
```diff
@@ -86,9 +88,12 @@ trait FullParameterization {
    *    }
    *
    *  If a self type is present, $this has this self type as its type.
+   *
    *  @param abstractOverClass  if true, include the type parameters of the class in the method's list of type parameters.
+   *  @param liftThisType       if true, require created $this to be $this: (Foo[A] & Foo,this).
```
Comment (sjrd) [inline src/dotty/tools/dotc/transform/FullParameterization.scala]: Is `Foo,this` a typo for `Foo.this`?

File: src/dotty/tools/dotc/transform/FullParameterization.scala [hunk 2]
```diff
@@ -86,9 +88,12 @@ trait FullParameterization {
...
+   *                            This is needed of created member stays inside scope of Foo(as in tailrec)
```
Comment (sjrd) [inline src/dotty/tools/dotc/transform/FullParameterization.scala]: of -> if

File: src/dotty/tools/dotc/transform/FullParameterization.scala [hunk 3]
```diff
@@ -217,12 +223,26 @@ trait FullParameterization {
    *  - the `this` of the enclosing class,
    *  - the value parameters of the original method `originalDef`.
    */
-  def forwarder(derived: TermSymbol, originalDef: DefDef, abstractOverClass: Boolean = true)(implicit ctx: Context): Tree =
+  def forwarder(derived: TermSymbol, originalDef: DefDef, abstractOverClass: Boolean = true, liftThisType: Boolean = false)(implicit ctx: Context): Tree = {
+    val fun =
     ref(derived.termRef)
```
Comment (sjrd) [inline src/dotty/tools/dotc/transform/FullParameterization.scala]: Indentation issue

**Comment by sjrd** [comment]
As far as I understand, LGTM.
There are couple of neg tests failing. It might just be that they need their checkfile to be updated.

**Comment by DarkDimius** [comment]
@sjrd, neg tests fail as expected. Actual test failure is in ./scala-scala/src/library/scala/collection/immutable/TrieIterator.scala. I'm having a look at it.

File: src/dotty/tools/dotc/transform/FullParameterization.scala (hunk 1 above)
Comment (smarter) [inline src/dotty/tools/dotc/transform/FullParameterization.scala]: Why not have the type of `$this` simply be `Foo.this` when `liftThisType` is true?

**Comment by DarkDimius** [comment]
rebased over master.

**Comment by DarkDimius** [comment]
@sjrd please have a look.
You could also try rebasing #1061 over this

**Comment by sjrd** [comment]
LGTM. I'll rebase the other one to see if it passes.
