### PR TITLE
Fix #1747: Improve error message for Scala/Java type mismatch

### LINKED ISSUE #1747: Can't implement or override java method with type parameters.
The following code will not compile because it can't match the types method types.
```scala
class Coll[E] extends java.util.Collection[E] {
  def toArray[T](a: Array[T]): Array[T] = ???
  ...
}


-- Error: Coll.scala -----------------------------------------------------------
2 |   def toArray[T](a: Array[T]): Array[T] = ???
  |       ^
  |overriding method toArray in trait Collection of type [T] => (x$0: Array[T])Array[T];
  | method toArray of type [T] => (a: Array[T])Array[T] has incompatible type
-- Error: Coll.scala -----------------------------------------------------------
1 |class Coll[E] extends java.util.Collection[E] {
  |      ^
  |class Coll needs to be abstract, since def toArray: [T] => (x$0: Array[T])Array[T] is not defined 
  |(Note that Array[T] does not match Array[T]: their type parameters differ)

two errors found
```

The same happens when trying to override the method:
```scala
class Coll[E] extends java.util.AbstractSet[E] {
  override def toArray[T](a: Array[T]): Array[T] = ???
  ...
}


-- Error: Coll.scala -----------------------------------------------------------
2 |  override def toArray[T](a: Array[T]): Array[T] = ???
  |               ^
  |overriding method toArray in class AbstractCollection of type [T] => (x$0: Array[T])Array[T];
  | method toArray of type [T] => (a: Array[T])Array[T] has incompatible type

one error found
```

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala [hunk 1]
```diff
@@ -111,11 +111,23 @@ object ErrorReporting {
...
+        case tp: PolyType =>
+          tp.derivedPolyType(resType = dropJavaMethod(tp.resultType))
+        case tp: JavaMethodType =>
+          MethodType(tp.paramNames, tp.paramTypes, dropJavaMethod(tp.resultType))
+        case tp => tp
+      }
+      val found1 = dropJavaMethod(found)
+      val expected1 = dropJavaMethod(expected)
+      if ((found1 eq found) != (expected eq expected1) && (found1 <:< expected1))
+        "\n (Note that Scala's and Java's representation of this type differs)"
```
Comment (nicolasstucki) [inline compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala]: This might not be enough for the user to understand the issue. In the example we would get 
```
overriding method toArray in trait Collection of type [T](x$0: Array[T])Array[T];
       method toArray of type [T](a: Array[T])Array[T] has incompatible type
       (Note that Scala's and Java's representation of this type differs)
```

Would it be possible to hint that to make the representation match one would need to write  
`def toArray[T](a: Array[T with Object]): Array[T with Object]`?

**Comment by nicolasstucki** [comment]
That is all. Otherwise LGTM.

File: compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala (hunk 1 above)
Comment (odersky) [inline compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala]: I thought about it, but it is really tricky and would require quite a bit of code. In short interoperating with Java using arrays requires a lot of context knowledge. Hard to condense that in an error message.
