### PR TITLE
fix(parser): make empty catch an incomplete.

### LINKED ISSUE #4393: REPL multi-row input does not handle correctly catch
```scala
scala> try {
         ???
       } catch { 
3 |} catch {
  |        ^
  |        '}' expected, but eof found
scala> 
```

### PR DESCRIPTION
**Pull request by ckipp01**
When parsing a `TRY` if there is an empty catch block instead of just
returning a syntax error return an incomplete if you're at the EOF. This
ensures that in the REPL if you are in a position like:

```scala
scala> try {
     | ???
     | } catch
```

And you hit enter you'll still be able to continue.

Fixes #4393

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -280,6 +280,12 @@ object Parsers {
         syntaxError(msg, offset)
         skip(stopAtComma = true)
 
+    def syntaxErrorOrIncomplete(msg: Message, offset: Span): Unit =
```
Comment (ckipp01) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:283]: Not sure if this is best or not, but I overloaded the previous `syntaxErrorOrIncomplete` to also be able to take in a `Span` instead of just the offset.

Comment (som-snytt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:283]: `Spic and Span`! but it would be more usual to call the param `span` as in `syntaxError`.

**Comment by som-snytt** [comment]
Thanks, I was able to close my ticket as a duplicate, as my ticket number is 10,000 higher.

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala (hunk 1 above)
Comment (ckipp01) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala]: ah whoops, good catch. Updated.

**Review by odersky — APPROVED** [review]
LGTM
