### PR TITLE
Fix typing closure blocks where result type refers to a closure parameter.

### LINKED ISSUE #23727: Capture checking rejects closure with parameter dependencies
## Compiler version

`main`

## Minimized code

```scala
import language.experimental.captureChecking
import caps.*
def test1(): Unit =
  val t1: (x: () => Unit) -> (y: () ->{x} Unit) -> Unit =
    x => y => ()  // should ok, but error
```

## Output

```scala
5 |    x => y => ()  // should ok, but error
  |    ^^^^^^^^^^^^
  |    Found:    (x: () => Unit) ->'s1 (y: () ->{x²} Unit) -> Unit
  |    Required: (x²: () => Unit) -> (y: () ->{x²} Unit) -> Unit
  |
  |    where:    => refers to the universal root capability
  |              x² is a reference to a value parameter
  |              x² is a reference to a value parameter
  |
  |    Note that capability x is not included in capture set {x}.
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

Should be ok.

It is probably related to #23700.

### PR DESCRIPTION
**Pull request by odersky**
Fix typing closure blocks where the expected result type refers to a closure parameter. A substitution was missing in this case.

Fixes #23727

### CODE REVIEW

File: tests/pos-custom-args/captures/i23727.scala [hunk 1]
```diff
@@ -0,0 +1 @@
+object Test
```
Comment (Linyxus) [inline tests/pos-custom-args/captures/i23727.scala]: This test file is empty.
