### PR TITLE
fix resoruce leaks in tests and REPL, fixes #8358

### LINKED ISSUE #8358: Resource leak : scala.io.BufferedSource not closed
## minimized code

I discovered the issue when running the REPL test [`LoadTests.scala`](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/repl/LoadTests.scala) on Windows (but the issue may not be specific to Windows).

More precisely the following line ([line 76 in `LoadTests.scala`](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/test/dotty/tools/repl/LoadTests.scala#L76)) helped me to identify the issue:
```Scala
Files.walk(dir).sorted(Comparator.reverseOrder).forEach(Files.delete)
```
**NB.** This is another case where an issue gets detected when testing on Windows but falls through the net on Unix/MacOS.

## Compilation output

```
$ sbt -sbt-version 1.3.8 "testOnly dotty.tools.repl.LoadTests"
[info] Loading settings for project dotty-multiline-build-build from build.sbt ...
[...]
[info] Test run started
[info] Test dotty.tools.repl.LoadTests.helloworld started
[info] Test dotty.tools.repl.LoadTests.maindefs started
[info] Test dotty.tools.repl.LoadTests.maindef started
[error] Test dotty.tools.repl.LoadTests failed: java.nio.file.FileSystemException: %TEMP%\repl_load_src3584160550809821314\repl_test3713211733288201754.scala: The process cannot access the file because it is being used by another process.
[error] , took 0.0 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]     at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[error]     at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[error]     at java.nio.file.Files.delete(Files.java:1126)
[error]     at dotty.tools.repl.LoadTests$.removeDir$$anonfun$1(LoadTests.scala:77)
[error]     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[error]     at java.util.ArrayList.forEach(ArrayList.java:1257)
[error]     at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[error]     at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
[error]     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
[error]     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[error]     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[error]     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[error]     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[error]     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[error]     at dotty.tools.repl.LoadTests$.removeDir(LoadTests.scala:77)
[error]     at dotty.tools.repl.LoadTests.removeDir(LoadTests.scala)
[error]     ...
[info] Test run finished: 1 failed, 0 ignored, 3 total, 5.563s
[error] Failed: Total 4, Failed 1, Errors 0, Passed 3
[error] Failed tests:
[error]         dotty.tools.repl.LoadTests
[error] (dotty-compiler / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 16 s, completed 22 Feb 2020 15:19:33
```

## Expectation

```
$ sbt -sbt-version 1.3.8 "compile; testOnly dotty.tools.repl.LoadTests"
[info] Loading settings for project dotty-multiline-build-build from build.sbt ...
[...]
[info] Test run started
[info] Test dotty.tools.repl.LoadTests.helloworld started
[info] Test dotty.tools.repl.LoadTests.maindefs started
[info] Test dotty.tools.repl.LoadTests.maindef started
[info] Test run finished: 0 failed, 0 ignored, 3 total, 5.828s
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 14 s, completed 22 Feb 2020 15:24:49
```

## Solution

The offending code is located in file [`ReplDriver.scala`](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/repl/ReplDriver.scala) and looks as follows ([line 350](https://github.com/lampepfl/dotty/blob/228e5934dde934edc364736d7f9db019f7e8ad99/compiler/src/dotty/tools/repl/ReplDriver.scala#L350)):

```scala
val contents = scala.io.Source.fromFile(file, "UTF-8").mkString
```
Method [`fromFile`](https://www.scala-lang.org/api/current/scala/io/Source$.html#fromFile(uri:java.net.URI,enc:String):scala.io.BufferedSource) returns an [`BufferedSource`](https://www.scala-lang.org/api/current/scala/io/BufferedSource.html) object which needs to be closed ! The following code solves the issue for me:

```scala
val source = scala.io.Source.fromFile(file, "UTF-8")
val contents = source.mkString
source.close()
```
**NB.** Class [`Source`](https://www.scala-lang.org/api/current/scala/io/Source.html) does implement the Java interface [`Closeable`](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html#java.io.Closeable), *not* the object [`Source`](https://www.scala-lang.org/api/current/scala/io/Source$.html).

## Discussion

Usage of `Source.fromFile` can currently be found in 6 locations in Dotty, namely:
```
$ find.exe compiler -name "*.scala" -exec grep -H "Source.fromFile" \{} ;
compiler/src/dotty/tools/repl/ReplDriver.scala:        val contents = scala.io.Source.fromFile(file, "UTF-8").mkString
compiler/test/debug/Gen.scala:    val lines = Source.fromFile(file).getLines().toBuffer
compiler/test/dotty/tools/repl/ReplTest.scala:    val lines = Source.fromFile(f, "UTF-8").getLines().buffered
compiler/test/dotty/tools/repl/ReplTest.scala:      Source.fromFile(f, "UTF-8").getLines().flatMap(filterEmpties).mkString(EOL)
compiler/test/dotty/tools/vulpix/FileDiff.scala:      else Source.fromFile(checkFile, "UTF-8").getLines().toList
compiler/test/dotty/tools/vulpix/ParallelTesting.scala:        Source.fromFile(file, "UTF-8").getLines().zipWithIndex.foreach { case (line, lineNbr) =>
```
I have a PR pending to fix `ReplDriver` in order to successfully pass the REPL test `LoadTests` .

Let me know
- if the case needs more investigation (resp. should be transmitted to the Scala team too)
- or the fix should be applied elsewhere.

### PR DESCRIPTION
**Pull request by rethab**

### CODE REVIEW

File: compiler/test/dotty/tools/repl/ReplTest.scala [hunk 1]
```diff
@@ -56,26 +57,22 @@ class ReplTest(withStaging: Boolean = false, out: ByteArrayOutputStream = new By
 
   def testFile(f: JFile): Unit = {
     val prompt = "scala>"
-    val lines = Source.fromFile(f, "UTF-8").getLines().buffered
 
-    assert(lines.head.startsWith(prompt),
-           s"""Each file has to start with the prompt: "$prompt"""")
-
-    def extractInputs(prompt: String): List[String] = {
+    def extractInputs(lines: BufferedIterator[String]): List[String] = {
```
Comment (smarter) [inline compiler/test/dotty/tools/repl/ReplTest.scala:61]: Could this use a plain collection like a Seq instead of an Iterator? I find iterators way too easy to misuse (e.g., if I try to print their content, then I break any code afterward), and this code isn't performance critical.

Comment (rethab) [reply compiler/test/dotty/tools/repl/ReplTest.scala:61]: Sure, I'll improve this :+1:

**Comment by rethab** [comment]
@smarter this is ready to merge I think
