### PR TITLE
fix #12981 add REPL show diagnostics level warn | err

### LINKED ISSUE #12981: scala 3 repl does not show if a message is an error or a warning (regression from scala 2)
## Compiler version

3.0.0

## Minimized code and output

```Scala
scala> val x = if true then 42
1 |val x = if true then 42
  |                     ^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses

scala> val x = val
1 |val x = val
  |        ^^^
  |        expression expected but val found
```

## Expectation
The first message above should include `warning` and the the second should include `error`. It is conceptually important to understand if the code has run or not, esp. for learners but also for professionals - I don't know all messages by hart if they are warnings or errors. Now it all looks the same in the Scala 3 REPL.

This is a regression from the Scala 2 REPL, in which you can always tell if a message is an error or a warning.

### PR DESCRIPTION
**Pull request by bjornregnell**
See #12981

### CODE REVIEW

File: repl-test-update/run-insert-error.scala [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+  println(s"Enter directory: $dirName")
+  list(dirName).foreach( f =>
+    val path = s"$dirName/$f"
+    if path.isDir then visitDirRecursively(path, isModify)
+    else visitFile(path, isModify)
+  )
+
+@main 
+def run_insert_error(isModify: Boolean): Unit = 
+  visitDirRecursively(replTestDir, isModify)
```
Comment (dwijnand) [inline repl-test-update/run-insert-error.scala:52]: Nicely done :)

But we don't need to merge this into the repo.

**Review by dwijnand — CHANGES_REQUESTED** [review]
The change seems reasonable to me - just need to delete the helper scripter IMO

File: repl-test-update/run-insert-error.scala (hunk 1 above)
Comment (bjornregnell) [reply repl-test-update/run-insert-error.scala]: Thanks! :smiling_face_with_three_hearts:  

The reason that I committed it to the repo was that I realized that *any* change in REPL output will require similar hacks, to avoid a very tedious manual walkthrough of all tests, so this might needed several times again, as the REPL output, err messages etc will improve over time to get in feature parity with the Scala 2 REPL. 

I have moved the util to this repo now so it is still on the internet if someone needs it again:
https://github.com/lunduniversity/introprog/tree/master/util/repl-output-update-tool

Comment (bjornregnell) [reply repl-test-update/run-insert-error.scala]: Just pushed the delete and the checks are running...

Comment (bjornregnell) [reply repl-test-update/run-insert-error.scala]: Let me know if there is a better place for this little repl-output-update hack to be discoverable to this community (?) and I'll contribute it there.

File: compiler/src/dotty/tools/repl/Rendering.scala [hunk 2]
```diff
@@ -33,7 +33,8 @@ private[repl] class Rendering(parentClassLoader: Option[ClassLoader] = None) {
 
   /** A `MessageRenderer` for the REPL without file positions */
   private val messageRenderer = new MessageRendering {
-    override def posStr(pos: SourcePosition, diagnosticLevel: String, message: Message)(using Context): String = ""
+    override def posStr(pos: SourcePosition, diagnosticLevel: String, message: Message)(using Context): String =
+      s"-- $diagnosticLevel:"
```
Comment (bishabosha) [inline compiler/src/dotty/tools/repl/Rendering.scala:37]: might be nice just to color the warning/error header, tests shouldnt need updating:
```suggestion
      hl(diagnosticLevel)(s"-- $diagnosticLevel:")
```

**Review by bishabosha — APPROVED** [review]

File: repl-test-update/run-insert-error.scala (hunk 1 above)
Comment (som-snytt) [reply repl-test-update/run-insert-error.scala]: There is `--update-checkfiles` which is passed via `-D` which should (be made to) work for REPL tests.

Comment (bjornregnell) [reply repl-test-update/run-insert-error.scala]: Ok, feel free to use my util code for that if relevant.

**Comment by bjornregnell** [comment]
@bishabosha Works nice after commenting out fatal warnings in Build.sbt:
image

**Comment by bishabosha** [comment]
> @bishabosha Coloring looks nice (after temporarily commenting out fatal warnings in [Build.sbt]

you can also use this line in sbt shell to reset the compiler settings for the `repl` task:
```scala
set `scala3-compiler-bootstrapped` / Compile / console / scalacOptions := Seq() // or whichever settings you want
```

**Comment by bjornregnell** [comment]
The community_build_a just failed here (but it went through before the color highlighting change, I think, so I'm curious if that really is the problem or the fail is unrelated?)

**Comment by smarter** [comment]
That looks like flaky scalatest's tests failing:
> [error] 	org.scalatest.ParallelTestExecutionSpec

I tried disabling them in https://github.com/lampepfl/dotty/commit/7556fd53d30c22afeee3793694072381ed5a16b9 but somehow they're still being run?

**Comment by bjornregnell** [comment]
Aha. As long as their tests don't depend on color highlighting of REPL output then we're good :)
