### PR TITLE
Fix #1380: Add missing part of the message

### LINKED ISSUE #1380: Custom message when missing type for expanded a function.
``` scala
scala> { case x: Int => 1 }
<console>:11: error: missing parameter type for expanded function
The argument types of an anonymous function must be fully known. (SLS 8.5)
Expected type was: ?
       { case x: Int => 1 }
       ^
```

``` scala
dotty> { case x: Int => 1 } 
  ^
{ case x: Int => 1 }
<console>:5: error: missing parameter type for parameter x$1 of expanded function x$1 => 
  x$1 match {
    case x: Int => 
      1
  }, expected = ?
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala [hunk 1]
```diff
@@ -193,7 +193,9 @@ object messages {
         else
           ""
 
-      i"missing parameter type for parameter ${param.name}$ofFun, expected = $pt"
+      i"""missing parameter type for parameter ${param.name}$ofFun, expected = $pt
+         |The argument types of an anonymous function must be fully known. (SLS 8.5)
+         |"""
```
Comment (allanrenucci) [inline compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala]: This create a spurious new line at the end
