### PR TITLE
Fix #4455: Lift inlined values when quoted

### LINKED ISSUE #4455: Error while compiling macro inline argument used in quote
```scala
import scala.quoted._
object Macros {
  inline def foo(inline i: Int): Int = ~bar('(i))
  def bar(x: Expr[Int]): Expr[Int] = ???
}
```

```
exception while typing Macros.bar(i$1) of class class dotty.tools.dotc.ast.Trees$Apply # 175
exception while typing {
  val i$1: Int = x$0.apply(0).asInstanceOf[Int]
  Macros.bar(i$1)
} of class class dotty.tools.dotc.ast.Trees$Block # 176
exception while typing def $anonfun$1(x$0: Seq[Any]): quoted.Expr[Int] = 
  {
    val i$1: Int = x$0.apply(0).asInstanceOf[Int]
    Macros.bar(i$1)
  } of class class dotty.tools.dotc.ast.Trees$DefDef # 180
exception while typing {
  def $anonfun$1(x$0: Seq[Any]): quoted.Expr[Int] = 
    {
      val i$1: Int = x$0.apply(0).asInstanceOf[Int]
      Macros.bar(i$1)
    }
  closure($anonfun$1)
}
```

We should probably add a `.toExpr` to inlined references that are inside of a quote https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala#L549

### PR DESCRIPTION
**Pull request by nicolasstucki**
This is part of the transformation that allows compiling
the contents of the inline macro. The alternative would be to
pass each inline parameter twice, once as a value and once as
it's tree.

### CODE REVIEW

File: tests/run/i4455/Macro_1.scala [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import scala.quoted._
+object Macros {
+  inline def foo(inline i: Int): Int = ~bar('(i))
+  def bar(x: Expr[Int]): Expr[Int] = x
+
+  inline def foo2(inline i: Int): Int = ~bar('(i + 1))
+  def bar2(x: Expr[Int]): Expr[Int] = x
```
Comment (OlivierBlanvillain) [inline tests/run/i4455/Macro_1.scala]: bar2 is unused

Comment (nicolasstucki) [reply tests/run/i4455/Macro_1.scala]: Oh, I only need one of them. Will remove it.
