### PR TITLE
Synchronize  standard library sources with Scala 2.13.18

### LINKED ISSUE #24204: Regression for unpacking var-arg splices when using Scala 2.13.17
It's no longer possible to guard against null var arg splice in the receiver method. The `vararg == null` is ignored. 
The problem exists when using Scala 3 (using any version) with Scala 2.13.17 stdlib. 
Effectively there is no way to detect null splice: 
- `_ != null` is ignored 
- `_.length > 0` results in  `java.lang.NullPointerException: Cannot read the array length because the return value of "scala.collection.immutable.ArraySeq$ofRef.unsafeArray()" is null` 
- `Option(_).isDefined` evaluates to true (becouse of the null check)

Based on failures in `scalatest/scalatest` in #24190

## Compiler version
All Scala versions, tested: 3.3.7 LTS, 3.7.4-RC1, 3.8.0-RC1-bin-20251017-96aff06-NIGHTLY

## Minimized code

```scala
class NullArgumentException(msg: String) extends IllegalArgumentException(msg)

trait Suite
class Suites(suitesToNest: Suite*) {
  if suitesToNest == null then
    throw NullArgumentException("The passed suites splice is null")

  for
    s <- suitesToNest // triggers NullPointerException
    if s == null
  do
    throw new NullArgumentException("One of the passed suite was null")
}

@main def Test = {
  val aNull: Array[Suite] = null
  try {
    new Suites(aNull*)
    throw IllegalStateException("Should not be reached")
  } catch {
    case ex: NullArgumentException => println(s"ok, expected: $ex")
  }
}

```

## Output

```scala
// scala test.scala  -S 3.7.4-RC1 --dep org.scala-lang:scala-library:2.13.17 
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.reflect.Array.getLength(Native Method)
        at scala.collection.ArrayOps$ArrayIterator.<init>(ArrayOps.scala:126)
        at scala.collection.immutable.ArraySeq$ofRef.iterator(ArraySeq.scala:348)
        at scala.collection.View$Filter.iterator(View.scala:144)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:629)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:628)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:936)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:906)
        at Suites.<init>(test.scala:9)
        at test$package$.Test(test.scala:18)
        at Test.main(test.scala:15)
```

Same problem in nightly which ships it's own stdlib 
```scala
// scala test.scala  -S 3.nightly
Compiled project (Scala 3.8.0-RC1-bin-20251018-96aff06-NIGHTLY, JVM (21))
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.reflect.Array.getLength(Native Method)
        at scala.runtime.ScalaRunTime$.array_length(ScalaRunTime.scala:89)
        at scala.collection.ArrayOps$ArrayIterator.<init>(ArrayOps.scala:129)
        at scala.collection.immutable.ArraySeq$ofRef.iterator(ArraySeq.scala:351)
        at scala.collection.View$Filter.iterator(View.scala:149)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:632)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:337)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:946)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:916)
        at Suites.<init>(test.scala:9)
        at test$package$.Test(test.scala:18)
        at Test.main(test.scala:15)
```
## Expectation
Same behaviour as when using 2.13.16 stdlib

```scala 
// scala test.scala  -S 3.7.4-RC1 --dep org.scala-lang:scala-library:2.13.16
Compiled project (Scala 3.7.4-RC1, JVM (21))
[hint]  "scala-library is outdated, update to 2.13.17"
     scala-library 2.13.16 -> org.scala-lang:scala-library:2.13.17
ok, expected: NullArgumentException: The passed suites splice is null
```

### PR DESCRIPTION
**Pull request by WojciechMazur**
Synchronize stdlib with changes made between Scala 2.13.17 (last sync made in https://github.com/scala/scala3/pull/24063) and 2.13.18 (latest Scala 2.13 release) 

Also adds a script to synchronize changes in the future

Fixes #24204

### CODE REVIEW

File: library/src/scala/runtime/ScalaRunTime.scala [hunk 1]
```diff
@@ -289,20 +289,23 @@ object ScalaRunTime {
...
+  def wrapLongArray(xs: Array[Long]): ArraySeq[Long]                 = if (xs ne null) new ArraySeq.ofLong(xs) else null.asInstanceOf[ArraySeq[Long]]
+  def wrapFloatArray(xs: Array[Float]): ArraySeq[Float]              = if (xs ne null) new ArraySeq.ofFloat(xs) else null.asInstanceOf[ArraySeq[Float]]
+  def wrapCharArray(xs: Array[Char]): ArraySeq[Char]                 = if (xs ne null) new ArraySeq.ofChar(xs) else null.asInstanceOf[ArraySeq[Char]]
+  def wrapByteArray(xs: Array[Byte]): ArraySeq[Byte]                 = if (xs ne null) new ArraySeq.ofByte(xs) else null.asInstanceOf[ArraySeq[Byte]]
+  def wrapShortArray(xs: Array[Short]): ArraySeq[Short]              = if (xs ne null) new ArraySeq.ofShort(xs) else null.asInstanceOf[ArraySeq[Short]]
+  def wrapBooleanArray(xs: Array[Boolean]): ArraySeq[Boolean]        = if (xs ne null) new ArraySeq.ofBoolean(xs) else null.asInstanceOf[ArraySeq[Boolean]]
+  def wrapUnitArray(xs: Array[Unit]): ArraySeq[Unit]                 = if (xs ne null) new ArraySeq.ofUnit(xs) else null.asInstanceOf[ArraySeq[Unit]]
```
Comment (WojciechMazur) [inline library/src/scala/runtime/ScalaRunTime.scala]: @noti0na1 is it ok? Should we adjust the signature as well? I'm not sure what's the best approach here, should we kept it as it is for backward compatibility, make output nullable, or both input and output

**Comment by sjrd** [comment]
We're supposed to have a long-lived branch that constantly `filter-repo`s Scala 2, so that we can have the exact same commits *merged* into `main` (rather than cherry-picked). @hamzaremmal Where's that branch?

File: library/src/scala/runtime/ScalaRunTime.scala (hunk 1 above)
Comment (noti0na1) [reply library/src/scala/runtime/ScalaRunTime.scala]: The signatures look good to me. We can use `ScalaRunTime.mapNull` for rhs to deal with situations like this.

**Comment by hamzaremmal** [comment]
> We're supposed to have a long-lived branch that constantly `filter-repo`s Scala 2, so that we can have the exact same commits _merged_ into `main` (rather than cherry-picked). @hamzaremmal Where's that branch?

It might have been deleted after merging the PR. I'll push it once again and make sure branch protection are set so we cannot force push into it and delete it.
