### PR TITLE
Properly handle `AnyVal`s as refinement members of `Selectable`s 

### LINKED ISSUE #14340: AnyVal value in a Selectable container class is stripped of its wrapper
## Compiler version

v3.1.1-RC2

## Minimized code
https://scastie.scala-lang.org/l6Js266rRd2FuA4p0SkJLA

```Scala
class Foo(val value : Int) extends AnyVal
class Container extends reflect.Selectable
val cont = new Container:
  val foo = new Foo(1)

println(cont.foo.value) //ClassCastException
```

## Output

```scala
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class Playground$Foo (java.lang.Integer is in module java.base of loader 'bootstrap'; Playground$Foo is in unnamed module of loader sbt.internal.BottomClassLoader @433c2ab9)
	at Playground$.<clinit>(main.scala:8)
	at Main$.<clinit>(main.scala:12)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:133)
	at sbt.Run.execute$1(Run.scala:82)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.TrapExit$App.run(TrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

## Expectation
No error.

### PR DESCRIPTION
**Pull request by G1ng3r**
- add dynamic access to value classes field

### CODE REVIEW

**Comment by G1ng3r** [comment]
@prolativ Hi! Could you look into it? I'm new to compiler and not quite sure if this solution is ok or not

File: tests/pos/i14340.scala [hunk 1]
```diff
@@ -0,0 +1,10 @@
+object i14340 {
```
Comment (prolativ) [inline tests/pos/i14340.scala:1]: As this used to fail at runtime, we need to have a test checking if this works at runtime. Tests in `tests/pos` are only checked for successful compilation. You need to move this test to `tests/run/i14340.scala` and make it a runnable program (e.g. by creating a `@main` method).  Also for extra certainty that this actually works as expect you could add a test check file `tests/run/i14340.check` containing the expected console output of the program. In this case it would be simply
```
1
```

File: compiler/src/dotty/tools/dotc/typer/Dynamic.scala [hunk 2]
```diff
@@ -215,10 +216,7 @@ trait Dynamic {
       errorTree(tree, em"Structural access not allowed on method $name because it $reason")
 
     fun.tpe.widen match {
-      case tpe: ValueType =>
-        structuralCall(nme.selectDynamic, Nil).cast(tpe)
-
-      case tpe: MethodType =>
+      case tpe @ (_: MethodType | _: ErasedValueType) =>
```
Comment (prolativ) [inline compiler/src/dotty/tools/dotc/typer/Dynamic.scala:219]: @odersky could you confirm this change should work and not break something else?

File: tests/pos/i14340.scala (hunk 1 above)
Comment (G1ng3r) [reply tests/pos/i14340.scala:1]: Thanks! I did that and solution is not working. Will try something else

Comment (G1ng3r) [reply tests/pos/i14340.scala]: I've found solution, but again I'm not sure about it. I think we nned to wrap called members of Selectable. But it looks not perfect for me

Comment (prolativ) [reply tests/pos/i14340.scala]: I have some doubts if `Dynamic.scala` is really the proper place for the fix. I tried to play with the issue a bit and it seems specific to `reflect.Selectable` rather than to `Selectable` in general. For sure we need more tests here to make sure we won't break something else. Consider cases like this:
* What if we need to deal with nested value classes?
* What if what we call from a `Selectable` should desugar to `applyDynamic` rather than `selectDynamic`?
* What if we provide a custom implementation of `selectDynamic` which doesn't use reflection?

An extended test case could look like this
```scala
class Foo(val value: Int) extends AnyVal
class Bar[A](val value: A) extends AnyVal

class Container1 extends reflect.Selectable

class Container2 extends Selectable:
  def selectDynamic(name: String) = Bar(name)

val cont1 = new Container1:
  val foo = new Foo(1)
  val bar = new Bar(Foo(2))
  def fooFromInt(i: Int) = new Foo(i)

val cont2 = (new Container2).asInstanceOf[Container2 { def qux: Bar[String] }]

@main def Test: Unit =
  println(cont1.foo.value)
  println(cont1.bar.value)
  println(cont1.fooFromInt(3).value)
  println(cont2.qux.value)
```
with expected output
```
1
2
3
qux
```

Comment (G1ng3r) [reply tests/pos/i14340.scala]: Thanks a lot. I will think about another approach

**Review by odersky — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by G1ng3r** [comment]
@prolativ yep, I'm working on it. Stuck on last case, need some time

**Comment by prolativ** [comment]
OK, great. No pressure though. If you're having troubles with some specific issue, you can share your idea here so that we find the solution together

**Comment by G1ng3r** [comment]
@prolativ I pushed my current state, and I have a problem with `cont2.qux.value`. I can't find the way to distinct between cases when value class erased and when it's not. In case with `cont2.qux.value` compiler does not erase value class. But I also think that this case is really weird and we should not consider it. And I could not find the way to solve this issue within `reflect.Selectable` because it works during runtime and there is no information about value classes. I need help with last case if it should be fixed.

**Comment by prolativ** [comment]
I'll have a look at it.
Actually `cont2.qux.value` seems to be the only case that worked before your changes, so breaking this would be a regression - which we can't let into the compiler

**Comment by G1ng3r** [comment]
Oh, you're right. Didnt think about it. I'll try to come up with something else. Thanks

**Comment by prolativ** [comment]
I tried to dig into that a bit and here are my thoughts:

The fix should not even touch `typer.Dynamic` at all.

Probably the cleanest solution would be to change the implementation of `selectDynamic` and `applyDynamic` in `reflect.Selectable` in such a way that if the return type declared in a refinement (e.g. `Foo` for `val foo = new Foo(1)` in our test snippet) is a value class then instead of simply returning the value obtained via reflection we additionally wrap it into this  class. The problem is that in the body of `selectDynamic` and `applyDynamic` we have no information about the type we're supposed to return as the cast to this type is handled later by the compiler. This is a problem I have encountered myself while working on some other stuff. It would be really nice if we could get this information somehow but that would probably require a change to how we desugar access to structural members and to what the signatures of `selectDynamic` and `applyDynamic` should look like. At this moment I don't know if this would be possible in terms of backward compatibility and how much effort it would require. @odersky any thoughts on this?

There's some chance the problem could be alternatively fixed by leaving the implementation of `reflect.Selectable` as it is now but adding a special case to how value classes are erased. If you have a look at `VCElideAllocations.scala` you'll see `case ValueClassUnbox(NewWithArgs(_, List(u))) =>`. Now let's look at our test case. `cont1.foo.value` expands to `cont1().selectDynamic("foo").asInstanceOf[Foo].value()`. Unfortunately the shape of the tree we get from `.asInstanceOf[Foo].value` in  is not matched by `NewWithArgs` so this part doesn't get removed by the compiler, causing a runtime exception. So we might either need to add a new case for matching a cast followed by a call to the value class unwrapping method or add some extra wrapping earlier to match the existing pattern

**Comment by G1ng3r** [comment]
@prolativ Hi! I found the reason why my solution was not working for last case and I fixed it.
I've looked into `VCElideAllocations.scala` and I think we cant fix it there cause at this phase we are not able to box primitives.
Changing API of `reflect.Selectable` is beyond this issue, I guess. So I go with `typer.Dynamic` cause the reason of this issue is `selectDynamic/applyDynamic` result type.

**Comment by prolativ** [comment]
Unfortunately this new approach doesn't work either. Just see how the test would crash if you change
```scala
def selectDynamic(name: String) = Bar(name)
```
to
```scala
def selectDynamic(name: String): Any = Bar(name)
```
(actually I would expect the return type of `selectDynamic` to be `Any` rather than something more specific in most cases).
It also looks like your approach doesn't really work well with nonreflective `Selectable`s when some operations are chained.
Here is an extended test suite that should pass to make sure subtypes of `reflect.Selectable` and custom implementations of `Selectable` work the same way.
```scala
class Container1 extends reflect.Selectable

class Container2(values: Map[String, Any], methods: Map[String, Int => Any]) extends Selectable:
  def selectDynamic(name: String) = values(name)
  def applyDynamic(name: String)(arg: Int) = methods(name)(arg)

class Foo(val value: Int) extends AnyVal
class Bar[A](val value: A) extends AnyVal

object Helpers:
  def foo = Foo(1)
  def bar = Bar(Foo(2))
  def qux1 = Bar(new Container1 { def foo = Foo(10) })
  def qux2 = Bar(new Container2(Map("foo" -> Foo(20)), Map.empty).asInstanceOf[Container2 { def foo: Foo }])

  def cont1 = new Container1:
    def foo = Helpers.foo
    val bar = Helpers.bar
    def qux1 = Helpers.qux1
    def qux2 = Helpers.qux2
    def fooFromInt(i: Int) = Foo(i)

  def cont2values = Map(
    "foo" -> Helpers.foo,
    "bar" -> Helpers.bar,
    "qux1" -> Helpers.qux1,
    "qux2" -> Helpers.qux2
  )

  def cont2methods = Map(
    "fooFromInt" -> { (i: Int) => Foo(i) }
  )

  def cont2 = Container2(cont2values, cont2methods).asInstanceOf[Container2 {
    def foo: Foo
    def bar: Bar[Foo]
    def qux1: Bar[Container1 { def foo: Foo }]
    def qux2: Bar[Container2 { def foo: Foo }]
    def fooFromInt(i: Int): Foo
  }]

@main def Test: Unit =
  val cont1 = Helpers.cont1
  val cont2 = Helpers.cont2

  println(cont1.foo.value)
  println(cont2.foo.value)

  println(cont1.bar.value.value)
  println(cont2.bar.value.value)

  println(cont1.qux1.value.foo.value)
  println(cont2.qux1.value.foo.value)
  
  println(cont1.qux2.value.foo.value)
  println(cont2.qux2.value.foo.value)

  println(cont1.fooFromInt(100).value)
  println(cont2.fooFromInt(100).value)
```
Feel free to our own test cases.
Meanwhile we have to figure out how to fix the current implementation.
I still have a feeling `Dynamic.scala` is not what should be changed (or at least not only) as the desugaring performed here is a part of the specification of the language and changing it might break backward compatibility

**Comment by prolativ** [comment]
Just for clarity: this should print
```
1
1
2
2
10
10
20
20
100
100
```

**Comment by G1ng3r** [comment]
Thanks a lot! I'll think about another approach, and will get back :)

**Comment by prolativ** [comment]
@G1ng3r I think I've managed to slightly modify your approach to make this work - the main point is that special handling of `selectDynamic` and `applyDynamic` should be applied only for subtypes of `reflect.Selectable` - in other cases we should preserve the old behaviour.

@odersky do you think this workaround is acceptable? Currently I can see no other way to fix this without changing the specification of desugaring of `Selectable`s

File: compiler/src/dotty/tools/dotc/typer/Dynamic.scala [hunk 3]
```diff
@@ -214,9 +216,23 @@ trait Dynamic {
...
 
+    extension (tree: Tree)
+      /** The implementations of `selectDynamic` and `applyDynamic` in `scala.reflect.SelectDynamic` have no information about the type of a value obtained via reflection before erasure
+       *  so the can't know if the value should be wrapped in a value class constructor call or not.
+       *  Hence the logic of wrapping is performed here, relying on the fact that the method implementations mentioned above are final.
+       */
+      def maybeBoxingCast(tpe: Type) =
+        val maybeBoxed = 
+          if ValueClasses.isDerivedValueClass(tpe.classSymbol) && qual.tpe <:< defn.ReflectSelectableTypeRef then
+            val underlying = ValueClasses.valueClassUnbox(tpe.classSymbol.asClass).info.resultType.asSeenFrom(tpe, tpe.classSymbol)
```
Comment (dwijnand) [inline compiler/src/dotty/tools/dotc/typer/Dynamic.scala:227]:
```suggestion
            val genericUnderlying = ValueClasses.valueClassUnbox(tpe.classSymbol.asClass)
            val underlying = tpe.select(genericUnderlying).widen.resultType
```

**Review by dwijnand — APPROVED** [review]
Seems good to me.  A couple of suggestions.
