### PR TITLE
Fix #5237: Do not list <xyz> in scala package completions

### LINKED ISSUE #5237: Completion of unexpected locations produce unexpected results
image
When I tried to press the Tab key after `import scala.`, dotty repl gave a lot of unexpected completions: all symbols in the current scope (all members of the `java` and `scala` packages, all members of the `Predef`), all top-level package name, some special symbols (e.g. `<init>`, `<byname>`, `<special-ops>`, `_root`), and some folder names in the current working folder.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Do not recommend `<repeated>`, `<byname>`, `<equals>` and `package` as members of some package (namely the `scala` package).

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/interactive/Completion.scala [hunk 1]
```diff
@@ -252,7 +252,11 @@ object Completion {
       (
            (mode.is(Mode.Term) && sym.isTerm)
         || (mode.is(Mode.Type) && (sym.isType || sym.isStable))
-      )
+      ) &&
+      !sym.isPackageObject &&
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/interactive/Completion.scala]: This one makes sense, but I'd rather not add a bunch of special cases for repeated, byname, etc. Instead I suggest adding the `Artifact` flag to these symbols (we should already be filtering out Artifacts because they should never appear in user code).

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/interactive/Completion.scala]: Added the `Artifact` flag

File: compiler/src/dotty/tools/dotc/interactive/Completion.scala [hunk 2]
```diff
@@ -252,7 +252,9 @@ object Completion {
       (
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/interactive/Completion.scala]: I would move the two added checks above this line. also update the comment at the top of this method.

File: compiler/src/dotty/tools/dotc/interactive/Completion.scala [hunk 3]
```diff
@@ -240,7 +240,9 @@ object Completion {
      *   4. have an existing source symbol,
      *   5. are the module class in case of packages,
      *   6. are mutable accessors, to exclude setters for `var`,
-     *   7. have same term/type kind as name prefix given so far
+     *   7. symbol is not a package object
+     *   8. symbol is not an atifact of the compiler
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/interactive/Completion.scala]:
```suggestion
     *   8. symbol is not an artifact of the compiler
```
