### PR TITLE
Fix #9342: Use semantic name for inline bindings

### LINKED ISSUE #9342: Inlined parameter name conflict
```Scala
trait Label[A]:
  def apply(v: A): String

given [A] as Label[A] = _.toString

extension [A](x: A) inline def label(using inline l: Label[A]): String = l(x)

def label1[A](v: A) = v.label  // Compiles fine

def label2[A](l: A) = l.label  // Fails to compile because parameter `l` matches implicit argument name `l`
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/core/NameKinds.scala [hunk 1]
```diff
@@ -295,7 +295,7 @@ object NameKinds {
   val DocArtifactName: UniqueNameKind        = new UniqueNameKind("$doc")
   val UniqueInlineName: UniqueNameKind       = new UniqueNameKind("$i")
   val InlineScrutineeName: UniqueNameKind    = new UniqueNameKind("$scrutinee")
-  val InlineBinderName: UniqueNameKind       = new UniqueNameKind("$elem")
+  val InlineBinderName: UniqueNameKind       = new UniqueNameKind("$bind")
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/NameKinds.scala:298]: I find `bind` too unspecific, and of the wrong kind. If we use it, it should be `binder`, not `bind`. But maybe `proxy` is better?

Comment (nicolasstucki) [reply compiler/src/dotty/tools/dotc/core/NameKinds.scala]: Indeed, renamed to `proxy`
