### PR TITLE
fix #9179: ensure enum values are singleton with serialisation

### LINKED ISSUE #9179: Singleton enum cases (marked `Serializable`) are incorrectly serialized
## Minimized code

Running twice with 0.25.0-RC1:

```Scala
import java.io._

enum A:
  case B

object Main extends App:
  val file = File("/tmp/EnumSerialization.dat")

  if file.exists
    val a = ObjectInputStream(FileInputStream(file)).readObject().asInstanceOf[A]
    println(a == A.B)
    a match
      case A.B => // passes exhaustivity check
  else
    ObjectOutputStream(FileOutputStream(file)).writeObject(A.B)
```

## Output

On second execution:

```scala
false

[error] java.lang.ExceptionInInitializerError
...
[error] Caused by: scala.MatchError: B (of class A$$anon$1)
```

## Expectation

I expected `a == A.B` because it is marked `Serializable` by default.

I think there are two options:
* to stop `Enum` (with singleton cases) extending `Serializable`, which seems to go against #9011, or
* to generate custom `writeObject()` and `readObject()` when desugaring enum, though I'm not sure if it's possible and worthwhile.

### PR DESCRIPTION
**Pull request by bishabosha**
~depends on #9524 for correct semantics~ merged

fixes #9179 

this also adds the values and valueOf methods to companions of enums parameterised by a type

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/transform/SymUtils.scala [hunk 1]
```diff
@@ -201,6 +201,9 @@ object SymUtils {
   def rawTypeRef(using Context) =
     self.typeRef.appliedTo(self.typeParams.map(_ => TypeBounds.emptyPolyKind))
 
+  def typeRef_*(using Context) =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]: - we don't use the `_*` convention in dotty
- there's already rawTypeRef which should do the same and not be incorrect when an argument is higher-kinded

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]: I tried using rawTypeRef but it fails when the type parameter is not higher kinded

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]: That's a bug somewhere probably 😅

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]:
```scala
scala> enum Tag[+T]:
     |   case Int extends Tag[Int]
     | 
// defined class Tag

scala> val f: Tag[? <: AnyKind] = Tag.Int
1 |val f: Tag[? <: AnyKind] = Tag.Int
  |           ^^^^^^^^^^^^
  |           Missing type parameters for  <: AnyKind
```

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]:
```scala
scala> enum Hoge[F[_]] {
     |   case A extends Hoge[List]
     |   case B extends Hoge[[X] =>> String]
     | }
scala> val f: Hoge[?] = Hoge.A                                                                                                                 
val f: Hoge[?[_$1]] = A
```
this does work (which is the failing test case), so ? is being represented by something else

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]: I think the typer takes care of using the correct bounds for wildcards. Are you constructing untyped or typed trees?

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]: It works if I use the totally untyped TypeBoundsTree(EmptyTree, EmptyTree)

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala:204]: If you're working with untyped trees that's the correct thing to do yeah

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SymUtils.scala]: Sorry, I sent my last reply before yours had loaded, yeah this is done before the enum template is sent to typer

**Comment by bishabosha** [comment]
I guess the issue now is that if someone has the wrong parents for their enum, then they get a cryptic error related to an object of the wrong type being passed to the EnumValues.register method, e.g.:
```scala
scala> enum Tag[+T]:
     |   case Int extends AnyRef
     | 
2 |  case Int extends AnyRef
  |                         ^
  |              Found:    ($anon.this : Object with runtime.EnumValue {...})
  |              Required: Tag[?]
```

**Comment by smarter** [comment]
> I guess the issue now is that if someone has the wrong parents for their enum

Can't we do something like: 
When typechecking a case, verify that it's a subtype of the enum, if not emit an error and artificially add the enum as a parent of the class anyway to avoid follow-on errors

File: library/src/scala/runtime/EnumValueSerializationProxy.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+            try {
+                return AccessController.doPrivileged((PrivilegedExceptionAction<Object[]>) () ->
+                  (Object[])type.getMethod("values").invoke(null));
+            } catch (PrivilegedActionException e) {
+                return rethrowRuntime(e.getCause());
+            }
+        }
+    };
+
+    private static <T> T rethrowRuntime(Throwable e) {
```
Comment (smarter) [inline library/src/scala/runtime/EnumValueSerializationProxy.java:25]: This looks almost like the rethrowRuntime method in ModuleSerializationProxy, but this one is generic, is there any reason for it to be different? https://github.com/scala/scala/blob/2.13.x/src/library/scala/runtime/ModuleSerializationProxy.java
(Also would be good to add a comment at the top of this file mentioning that it's based on ModuleSerializationProxy)

File: compiler/src/dotty/tools/dotc/core/Definitions.scala [hunk 3]
```diff
@@ -651,6 +651,12 @@ class Definitions {
     @tu lazy val Enum_ordinal: Symbol = EnumClass.requiredMethod(nme.ordinal)
 
   @tu lazy val EnumValuesClass: ClassSymbol = requiredClass("scala.runtime.EnumValues")
+  @tu lazy val EnumValueClass: ClassSymbol = requiredClass("scala.runtime.EnumValue")
+
+  @tu lazy val EnumValueSerializationProxyClass: ClassSymbol = requiredClass("scala.runtime.EnumValueSerializationProxy")
+    @tu lazy val EnumValueSerializationProxyConstructor: TermSymbol =
+      EnumValueSerializationProxyClass.requiredMethod(nme.CONSTRUCTOR, List(ClassType(TypeBounds.empty)))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/Definitions.scala:658]: The constructor takes two arguments: a Class[?] and an Int, so that list of argument looks wrong to me;

File: compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala [hunk 4]
```diff
@@ -93,12 +93,14 @@ object DesugarEnums {
    *       }
    */
   private def enumScaffolding(using Context): List[Tree] = {
+    import dotty.tools.dotc.transform.SymUtils._
+    val rawEnumClassRef = rawRef(enumClass.typeRef)
+    extension (tpe: NamedType) def ofRawEnum = AppliedTypeTree(ref(tpe), rawEnumClassRef)
     val valuesDef =
-      DefDef(nme.values, Nil, Nil, TypeTree(defn.ArrayOf(enumClass.typeRef)), Select(valuesDot(nme.values), nme.toArray))
+      DefDef(nme.values, Nil, Nil, defn.ArrayType.ofRawEnum, Select(valuesDot(nme.values), nme.toArray))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala:100]: We should have testcases checking that values work as expected both with higher-kinded and non-higher-kinded type parameters

File: compiler/src/dotty/tools/dotc/core/Definitions.scala (hunk 3 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/core/Definitions.scala:658]: good spot thank you :)

File: library/src/scala/runtime/EnumValueSerializationProxy.java (hunk 2 above)
Comment (bishabosha) [reply library/src/scala/runtime/EnumValueSerializationProxy.java:25]: im not really sure what's the use of it being a separate method, I'll inline it and add the comment

**Comment by bishabosha** [comment]
> When typechecking a case, verify that it's a subtype of the enum, if not emit an error and artificially add the enum as a parent of the class anyway to avoid follow-on errors

for 
```scala
enum Foo[F[_]]:
  case Bar extends AnyRef
```
what's the best way to invent type arguments for Foo that are well formed?

as an alternative which I don't really like I am replacing the body with an empty list if the parents are bad

**Comment by smarter** [comment]
> what's the best way to invent type arguments for Foo that are well formed?

Nothing is poly-kinded so `Foo[Nothing]` should work.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 5]
```diff
@@ -2071,11 +2071,7 @@ class Typer extends Namer
     val parentsWithClass = ensureFirstTreeIsClass(parents.mapconserve(typedParent).filterConserve(!_.isEmpty), cdef.nameSpan)
     val parents1 = ensureConstrCall(cls, parentsWithClass)(using superCtx)
 
-    var forceEmptyBody: Boolean = false
-    val enumCaseDef = optEnumCase(cls)
-    if enumCaseDef.exists then
-      val firstParent = parents1.head.tpe.dealias.typeSymbol
-      forceEmptyBody = !checkEnum(cdef, cls, enumCaseDef, firstParent) // don't bother looking inside the template
+    @annotation.threadUnsafe lazy val firstParent = parents1.head.tpe.dealias.typeSymbol
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:2074]: local lazy vals are always thread-unsafe so that annotation does nothing

File: compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala (hunk 4 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala:99]: added tests

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 5 above)
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: nice thanks

**Comment by bishabosha** [comment]
@smarter thank you for your suggestion about adding in the parent, it seems to not cause any knock on effects

**Comment by bishabosha** [comment]
I was experimenting with removing the EnumValueSerializationProxy class and was filtering on the companion to look for the .values method, but because it is nillary it has ExprType and so its signature is Signature.NotAMethod, should that be correct?

**Comment by smarter** [comment]
>  its info is ExprType and so its signature is Signature.NotAMethod, should that be correct?

That's normal yes, and you can filter by ` .signature == Signature.NotAMethod` to find it

File: compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala [hunk 6]
```diff
@@ -389,23 +401,24 @@ class SyntheticMembers(thisPhase: DenotTransformer) {
...
-      && !hasWriteReplace(clazz)
+      && !hasReadResolve(clazz)
     then
       List(
-        DefDef(writeReplaceDef(clazz),
-          _ => New(defn.EnumValueSerializationProxyClass.typeRef,
-                   defn.EnumValueSerializationProxyConstructor,
-                   List(Literal(Constant(clazz.classParents.head)), This(clazz).select(nme.ordinal).ensureApplied)))
-          .withSpan(ctx.owner.span.focus))
+        DefDef(readResolveDef(clazz),
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala:416]: I think the advantage of writeReplace over readResolve is that it makes serialization cheaper since we don't serialize any potential field defined in the enum

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala:416]: that's true, how about where in the EnumValueSerializationProxy where I was caching the .values array to avoid reflection each time, keep that as it is?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala:416]: Not sure. Are all enums with `.values` instances of java.lang.Enum? If so you could access .values without reflection

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala]: the jvm does its own thing for `java.lang.Enum` so `EnumValueSerializationProxy` doesn't get used for them.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala]: I think one option could be the addition of a `byOrdinal` mixin trait for the companion and serialize that with the ordinal and that would be fast

Comment (smarter) [reply compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala]: Serialization/deserialization isn't a very fast operation anyway, so I wouldn't worry too much about it.

File: compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala [hunk 7]
```diff
@@ -355,31 +355,59 @@ class SyntheticMembers(thisPhase: DenotTransformer) {
...
-    }
     else
       Nil
-  }
+
+  /** does this class extend `scala.runtime.EnumValue` and derive from an enum definition? */
+  extension (sym: ClassSymbol) private def isEnumValueImplementation(using Context): Boolean =
+    derivesFrom(defn.EnumValueClass) && classParents.exists(_.typeSymbol.flags.is(Enum))
+
+  /** If this the class backing a serializable singleton enum value with base class `MyEnum`,
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala:389]:
```suggestion
  /** If this is the class backing a serializable singleton enum value with base class `MyEnum`,
```

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala]: thanks

**Comment by bishabosha** [comment]
I added another case to prevent anonymous classes extending an enum if they were defined within a term called `$new` (where `$new` isn't synthetic)

File: docs/docs/reference/enums/desugarEnums.md [hunk 8]
```diff
@@ -158,29 +158,28 @@ map into `case class`es or `val`s.
...
-   - A method `valueOf(name: String): E`. It returns the singleton case value whose
+   - A method `valueOf(name: String): E'`. It returns the singleton case value whose
      `toString` representation is `name`.
-   - A method `values` which returns an `Array[E]` of all singleton case
-     values in `E`, in the order of their definitions.
+   - A method `values` which returns an `Array[E']` of all singleton case
+     values defined by `E`, in the order of their definitions.
 
-Companion objects of enumerations that contain at least one simple case define in addition:
+Companion objects of enumerations (i.e. `E` is not generic) that contain at least one simple case define in addition:
```
Comment (smarter) [inline docs/docs/reference/enums/desugarEnums.md:170]: This whole section is called "Translation of Enumerations" and covers both generic and non-generic, so non-generic enumeration need a more specialized name than "enumerations" (e.g., "monomorphic enumeration", or "simple enum")

Comment (bishabosha) [reply docs/docs/reference/enums/desugarEnums.md]: Ah yeah that was an oversight, I've got rid of any mention of "enumeration" now, as that was previously defined as requiring "non-generic" base class

**Comment by bishabosha** [comment]
rebased

**Comment by bishabosha** [comment]
I'm thinking that adding `.values` when there are only non-simple enum cases is actually a bug fix, not a new feature, without it `java.util.EnumSet` crashes whenever you try to construct it:
```scala
scala> enum Foo[T] extends java.lang.Enum[Foo[_]] { case A extends Foo[Unit] }
// defined class Foo

scala> java.util.EnumSet.allOf(classOf[Foo[?]])
java.lang.ClassCastException: class rs$line$1$Foo not an enum
	at java.util.EnumSet.noneOf(EnumSet.java:112)
	at java.util.EnumSet.allOf(EnumSet.java:131)
	at rs$line$2$.<init>(rs$line$2:1)
	at rs$line$2$.<clinit>(rs$line$2)
	at rs$line$2.res0(rs$line$2)
        ...
```

**Comment by smarter** [comment]
Agreed (the alternative bugfix would be to reject java.lang.Enum parents for parameterized enums)
