### PR TITLE
Properly desugar `inline given .. with ..`

### LINKED ISSUE #14177: `inline given ... with` not compiling properly
## Compiler version

3.0.0, 3.0.1, 3.1.0, 3.1.1-RC2

## Minimized code

```Scala
import scala.compiletime.*

trait C[A]

inline given [Tup <: Tuple]: C[Tup] with
  val cs = summonAll[Tuple.Map[Tup, C]]

```

## Output

Compilation error:

```scala
method summonAll is declared as `inline`, but was not inlined
```

## Expectation

Compile successfully, or at least provide a better error message if the construct is indeed invalid.

### LINKED ISSUE #14282: Facilitate compile-time typeclass creation
There was a quiproquo in the original issue #14226 and it got closed before clarifying it. I will try to reformulate and be as accurate as possible.

## Compiler version

3.1.0

## Introdution

In Scala 3, you can create traits with inline methods:
```scala
trait Test {

  inline def msg: String
}
```

`msg` is compiles **and runs as expected** if the implementation's exact type is known at compile-time:

```scala
inline given Test = new TestImpl
summon[Test].msg //Deferred inline

inline given TestImpl = new TestImpl
summon[TestImpl].msg //Compiles and runs

transparent inline given Test = new TestImpl
summon[TestImpl].msg //Compiles and runs
```

This behaviour is useful when creating typeclasses that have to (or can) be evaluated at compile-time. A minimized example from on of my projects:
```scala
trait Constraint[A, -B] {

  inline def assert(value: A): Boolean

  inline def getMessage(value: A): String
}

implicit inline def refineValue[A, B, C <: Constraint[A, B]](value: A)(using inline constraint: C): A / B = {
  Constrained(compileTime.preAssert[A, B, C](value, constraint.getMessage(value), constraint.assert(value)))
}
```
This code will pass the compile time-evaluated `String` `constraint.getMessage(value)` and `Boolean` `constraint.assert(value)`

Note: the `C` redudant type parameter forces the compiler to get the exact type of the `Constraint` implementation.

## The Issue

Currently, for Constraints with type parameters, we have to create a brand new class for each implementation:

```scala
trait Less[V] extends AlgebraEntryPoint[MathAlgebra] with Transitive[V] with Asymmetric[V, Greater]

class LessConstraint[A <: Number, V <: A] extends Constraint[A, Less[V]] {
  override inline def assert(value: A): Boolean = NumberOrdering.lt(value, constValue[V])

  override inline def getMessage(value: A): String = "value should be less than the specified one"
}

transparent inline given[A <: Number, V <: A]: Constraint[A, Less[V]] = new LessConstraint
```

Which works but we actually can't use anonymous `given` instances for this:
```scala
given [A <: Number, V <: A]: Constraint[A, Less[V]] with {

  override inline def assert(value: A): Boolean = NumberOrdering.lt(value, constValue[V])

  override inline def getMessage(value: A): String = "value should be less than the specified one"
}
```

The `assert` and `getMessage` methods are not fully inline even when called with an inline `value` input.

## Expectation

I would expect this last example to behave the same as the preceding one above: method calls fully inline.

I hope my issue is now clearer. My goal is not to spam my issue.

### PR DESCRIPTION
**Pull request by nicolasstucki**
```scala
inline given Foo with { .. }
```

now becomes
```scala
inline given def given_Foo: given_Foo = new given_Foo
class given_Foo extends Foo with { ... }
```

There are no creation of `lazy vals` when we have `inline`.
We inline the `new givne_Foo` only, the class does not get inlined.
This is useful to remove the instatiation of the given instance when
the methods are inline themselfs.

Fixes #14282
Fixes #14177

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Replaces #14207

File: tests/pos/i14177b.scala [hunk 1]
```diff
@@ -0,0 +1,15 @@
+class T
+
+inline given fail1: T with
```
Comment (smarter) [inline tests/pos/i14177b.scala:3]: Does transparent inline works / do anything useful here?

**Review by smarter — CHANGES_REQUESTED** [review]
This would need to be documented in the "Given Instance Initialization" section of https://dotty.epfl.ch/docs/reference/contextual/givens.html : If I understand this correctly, if the trait extended by the given instance has side effects in its constructor, they will now be executed at each invocation (we should have tests for that too).

 I think this looks reasonable but it's still a spec change so /cc @odersky (and it will need to be in the release notes of a minor version presumably)

File: tests/pos/i14177b.scala (hunk 1 above)
Comment (nicolasstucki) [reply tests/pos/i14177b.scala:3]: It makes sure that we do not hit the previous issue where the `summonAll` was not inlined due to the `inline` flag that was kept by mistake on the `class fail1`.

Comment (smarter) [reply tests/pos/i14177b.scala:3]: I mean, I there are no testcases with transparent in this pr

Comment (nicolasstucki) [reply tests/pos/i14177b.scala:3]: Sorry, I completely missed the transparent. I will add some test cases.

Comment (nicolasstucki) [reply tests/pos/i14177b.scala:3]: Transparent is failing for the wrong reason. I do not see how transparent would be useful here because we already have the precise type. I will disallow this combination and make sure the error message is correct.

**Review by smarter — APPROVED** [review]

File: docs/docs/reference/contextual/givens.md [hunk 2]
```diff
@@ -100,6 +100,24 @@ transparent inline given mkAnnotations[A, T]: Annotations[A, T] = ${
...
+Example:
+
+```scala
+trait Show[T] {
+  inline def show(x: T): String
+}
+
+inline given Show[Foo] with {
+  /*transparent*/ inline def show(x: Foo): String = ${ ... }
+}
```
[the remark this answers is not in the document]
Comment (nicolasstucki) [reply docs/docs/reference/contextual/givens.md:113]: I could not come up with a useful example of inlining those givens that did not involve also inlining the method.

[the remark this answers is not in the document]
Comment (nicolasstucki) [reply docs/docs/reference/contextual/givens.md:113]: Actually, the only reason why we did not disallow `inline given .. with ..` is for the case where it contains an inline method (as I originally intended in #14207).

[the remark this answers is not in the document]
Comment (smarter) [reply docs/docs/reference/contextual/givens.md:113]: Could the doc describe a concrete situation where it's useful then? I imagine it's needed for the method call to actually be inlined but that should be shown explicitly with an example because it's not obvious

[the remark this answers is not in the document]
Comment (Iltotore) [reply docs/docs/reference/contextual/givens.md:113]: > I imagine it's needed for the method call to actually be inlined but that should be shown explicitly with an example because it's not obvious

The use case of the issue at the origin of this PR was compile-time typeclass. The goal is to allow, as you said, to fully inline the method call. For example, I use it for type refinements/constraints.
